### ISSUE TITLE
gemspec runtime dependencies not included in DEPENDENCIES section of Gemfile.lock

### ISSUE THREAD

**Issue by myronmarston** [bundler/bundler#1041]
[Here's](https://github.com/myronmarston/bundler_gemspec_bug) a simple example project that demonstrates the bug.

[This commit](https://github.com/myronmarston/bundler_gemspec_bug/commit/642cab334c79cacdea1686e2adf54f1f9f0041b2) demonstrates the bug.  Note that the runtime dep is not included in the DEPENDENCIES section of Gemfile.lock, but the development dep is.

[The next commit](https://github.com/myronmarston/bundler_gemspec_bug/commit/75a1c157dc4e2cd919bcb3aff359da9a8671fbd8) demonstrates a workaround, but it would be nice to not have to do this.

[The README](https://github.com/myronmarston/bundler_gemspec_bug#readme) lists my environment info.

**Comment by malakai97** [comment]
I am seeing this error in 1.10.6
