### ISSUE TITLE
Cannot specify different source for a group

### ISSUE THREAD

**Issue by collin** [bundler/bundler#1066]
It would be great if you could:

```
group :development do
  gem "forked_gem", :path => ENV["PATH_TO_FORKED_GEM"]
end

group :production do
  gem "forked_gem", :path => "git://github.com/user/forked_gem"
end
```

Right now this will throw up an error about not being able to specify a gem twice.

**Comment by mrj** [comment]
The solution/workaround is described [here](https://bundler.io/v1.17/man/bundle-config.1.html#LOCAL-GIT-REPOS).
