### ISSUE TITLE
bundle open breaks when using jruby

### ISSUE THREAD

**Issue by trailstrider** [bundler/bundler#1136]
The VIM output is piped to STDOUT without letting me interact with the VIM interface. You can briefly see VIM's warning message:
Vim: Warning: Output is not to a terminal
Vim: Warning: Input is not from a terminal

This is identical to the issue here: https://github.com/lmarlow/gemedit/issues/3

**Comment by segiddins** [comment]
I could not reproduce this issue using Bundler 1.12.0.pre.2, jruby 9.0.4.0, and vim 7.4.1468.
