### ISSUE TITLE
Command line parameter --gemfile is not working as expected

### ISSUE THREAD

**Issue by octplane** [bundler/bundler#1150]
```
bundle install --gemfile=Gemfile-fotonauts 
Could not install to path `Gemfile-fotonauts` because of an invalid symlink. Remove the symlink so the directory can be created.
```

I was expecting bundler to use the provided Gemfile as source. (version 1.0.2, ruby 1.8.7 (2011-02-18 patchlevel 334) [x86_64-linux], MBARI 0x6770, Ruby Enterprise Edition 2011.03)

**Comment by FrankFang** [comment]
@octplane  Where is the .bundle folder
