### ISSUE TITLE
How to tell Gemfile to install a --pre version of a gem?

### ISSUE THREAD

**Issue by ibc** [bundler/bundler#1198]
In my case I need "eventmachine" gem with version >=1.0.0. Currently the official gem version is 0.12.10, but I can install 1.0.0.beta.3 by running `gem install eventmachine --pre`.

How can I tell Gemfile to install such development version of a gem?

**UPDATE:** I've got it right now by writting:

<pre>
gem "eventmachine", ">= 1.0.0.beta"
</pre>

However I think it could fail when the real 1.0.0 version arrives, am I wrong?

**Comment by cybertk** [comment]
+1

**Comment by cben** [comment]
Is this documented anywhere?

https://bundler.io/man/gemfile.5.html merely says "Each gem MAY have one or more version specifiers." but nothing about version specifier syntax / meaning.
https://bundler.io/v1.16/guides/updating_gems.html mentions an `.rc` version but it's in a complex example, and does not specifically explain the effect.
OK, https://bundler.io/gemfile.html does say "`~> 2.2.beta` will match prerelease versions like `2.2.beta.12`" and links to http://guides.rubygems.org/patterns/ for more info (which includes a "Prerelease gems" section).
