### ISSUE TITLE
Git Source with SSH Key

### ISSUE THREAD

**Issue by yfeldblum** [bundler/bundler#1263]
Feature Suggestion - Permit:

```
gem 'my-fancy-gem',
  :git => 'https://github.com/my-account/my-fancy-gem',
  :key => 'keys/my-fancy-gem-deploy' # relative path to the private key
```

This makes developing a private application easier because we can split up the components into difference repositories, and have bundler manage it all. This permits us to write a private application which makes use of private libraries, without forcing us to vendor the private libraries in the application. Instead, we can give bundler the keys to the private libraries, and bundler would use those keys (setting up temp scripts and setting the GIT_SSH env var when doing the git magic) to download the libraries.

**Comment by brettswift** [comment]
... and 5 years later google brings me to the same place!   internal gems in a Gemfile hosted on Atlassian's Stash  - the CI server has a key, but this runs on the agent, and teamcity doesn't seem to pick up the default .ssh path. 

Has anyone hacked this to work in the last 64 months? 😃

**Comment by tyronewilson** [comment]
Sadly I was brought here again even now......
