### ISSUE TITLE
bundle config gemfile  is not working.

### ISSUE THREAD

**Issue by tjiahen** [bundler/bundler#1315]
I try to bundle config gemfile Gemfile.sj and  bundle config gemfile mypathtoit/Gemfile.sj

but it is not working ...

~/.bundle/config

---

BUNDLE_GEMFILE: Gemfile.sj

**Comment by ineiti** [comment]
This is really great - is it possible to add the usage of the new Gemfile also in ```require 'bundler/setup'``` ? Or am I missing something?
