### ISSUE TITLE
Installing linecache19 (0.5.12) with native extensions fails

### ISSUE THREAD

**Issue by mkhezr** [bundler/bundler#1356]
Trying to deploy my rails 3 applicaiton on heroku and gettign the error that follows:

Installing linecache19 (0.5.12) with native extensions Unfortunately, a fatal error has occurred. Please report this error to the Bundler issue tracker at https://github.com/carlhuda/bundler/issues so that we can fix it. Thanks!
       /usr/local/lib/ruby/1.9.1/rubygems/installer.rb:483:in `rescue in block in build_extensions': ERROR: Failed to build gem native extension. (Gem::Installer::ExtensionBuildError)
       /usr/local/bin/ruby extconf.rb
       checking for vm_core.h... no
       checking for vm_core.h... no
       *** extconf.rb failed ***
       Could not create Makefile due to some reason, probably lack of
       necessary libraries and/or headers.  Check the mkmf.log file for more
       details.  You may need configuration options.
       Provided configuration options:
       --with-opt-dir
       --without-opt-dir
       --with-opt-include
       --without-opt-include=${opt-dir}/include
       --with-opt-lib
       --without-opt-lib=${opt-dir}/lib
       --with-make-prog
       --without-make-prog
       --srcdir=.
       --curdir
       --ruby=/usr/local/bin/ruby
       --with-ruby-dir
       --without-ruby-dir
       --with-ruby-include
       --without-ruby-include=${ruby-dir}/include
       --with-ruby-lib
       --without-ruby-lib=${ruby-dir}/lib
       /usr/local/lib/ruby/1.9.1/fileutils.rb:243:in`mkdir': Read-only file system - /usr/local/include/ruby-1.9.1/ruby-1.9.2-p180 (Errno::EROFS)
       from /usr/local/lib/ruby/1.9.1/fileutils.rb:243:in `fu_mkdir'
       from /usr/local/lib/ruby/1.9.1/fileutils.rb:217:in`block (2 levels) in mkdir_p'
       from /usr/local/lib/ruby/1.9.1/fileutils.rb:215:in `reverse_each'
       from /usr/local/lib/ruby/1.9.1/fileutils.rb:215:in`block in mkdir_p'
       from /usr/local/lib/ruby/1.9.1/fileutils.rb:201:in `each'
       from /usr/local/lib/ruby/1.9.1/fileutils.rb:201:in`mkdir_p'
       from /tmp/build_1l59fqsea4v4l/vendor/bundle/ruby/1.9.1/gems/ruby_core_source-0.1.5/lib/ruby_core_source.rb:59:in `block in create_makefile_with_core'
       from /usr/local/lib/ruby/1.9.1/tempfile.rb:320:in`open'
       from /tmp/build_1l59fqsea4v4l/vendor/bundle/ruby/1.9.1/gems/ruby_core_source-0.1.5/lib/ruby_core_source.rb:51:in `create_makefile_with_core'
       from extconf.rb:19:in`<main>'
       Requesting http://ftp.ruby-lang.org/pub/ruby/1.9/ruby-1.9.2-p180.tar.gz
       Downloading http://ftp.ruby-lang.org/pub/ruby/1.9/ruby-1.9.2-p180.tar.gz
       Gem files will remain installed in /tmp/build_1l59fqsea4v4l/vendor/bundle/ruby/1.9.1/gems/linecache19-0.5.12 for inspection.
       Results logged to /tmp/build_1l59fqsea4v4l/vendor/bundle/ruby/1.9.1/gems/linecache19-0.5.12/ext/trace_nums/gem_make.out
       from /usr/local/lib/ruby/1.9.1/rubygems/installer.rb:486:in `block in build_extensions'
       from /usr/local/lib/ruby/1.9.1/rubygems/installer.rb:446:in`each'
       from /usr/local/lib/ruby/1.9.1/rubygems/installer.rb:446:in `build_extensions'
       from /usr/local/lib/ruby/1.9.1/rubygems/installer.rb:198:in`install'
       from /tmp/build_1l59fqsea4v4l/vendor/bundle/ruby/1.9.1/gems/bundler-1.1.pre.8/lib/bundler/source.rb:92:in `block in install'
       from /tmp/build_1l59fqsea4v4l/vendor/bundle/ruby/1.9.1/gems/bundler-1.1.pre.8/lib/bundler/rubygems_integration.rb:78:in`preserve_paths'
       from /tmp/build_1l59fqsea4v4l/vendor/bundle/ruby/1.9.1/gems/bundler-1.1.pre.8/lib/bundler/source.rb:82:in `install'
       from /tmp/build_1l59fqsea4v4l/vendor/bundle/ruby/1.9.1/gems/bundler-1.1.pre.8/lib/bundler/installer.rb:64:in`block (2 levels) in run'
       from /tmp/build_1l59fqsea4v4l/vendor/bundle/ruby/1.9.1/gems/bundler-1.1.pre.8/lib/bundler/rubygems_integration.rb:93:in `with_build_args'
       from /tmp/build_1l59fqsea4v4l/vendor/bundle/ruby/1.9.1/gems/bundler-1.1.pre.8/lib/bundler/installer.rb:63:in`block in run'
       from /tmp/build_1l59fqsea4v4l/vendor/bundle/ruby/1.9.1/gems/bundler-1.1.pre.8/lib/bundler/installer.rb:55:in `run'
       from /tmp/build_1l59fqsea4v4l/vendor/bundle/ruby/1.9.1/gems/bundler-1.1.pre.8/lib/bundler/installer.rb:12:in`install'
       from /tmp/build_1l59fqsea4v4l/vendor/bundle/ruby/1.9.1/gems/bundler-1.1.pre.8/lib/bundler/cli.rb:213:in `install'
       from /tmp/build_1l59fqsea4v4l/vendor/bundle/ruby/1.9.1/gems/bundler-1.1.pre.8/lib/bundler/vendor/thor/task.rb:22:in`run'
       from /tmp/build_1l59fqsea4v4l/vendor/bundle/ruby/1.9.1/gems/bundler-1.1.pre.8/lib/bundler/vendor/thor/invocation.rb:118:in `invoke_task'
       from /tmp/build_1l59fqsea4v4l/vendor/bundle/ruby/1.9.1/gems/bundler-1.1.pre.8/lib/bundler/vendor/thor.rb:263:in`dispatch'
       from /tmp/build_1l59fqsea4v4l/vendor/bundle/ruby/1.9.1/gems/bundler-1.1.pre.8/lib/bundler/vendor/thor/base.rb:386:in `start'
       from /tmp/build_1l59fqsea4v4l/vendor/bundle/ruby/1.9.1/gems/bundler-1.1.pre.8/bin/bundle:13:in`<top (required)>'
       from vendor/bundle/ruby/1.9.1/bin/bundle:19:in `load'
       from vendor/bundle/ruby/1.9.1/bin/bundle:19:in`<main>'
 !
 !     Failed to install gems via Bundler.
 !
 !     Heroku push rejected, failed to compile Ruby/rails app

**Comment by vbrazo** [comment]
Thanks @danp
