### ISSUE TITLE
bundler doesn't install gem specified with :git option

### ISSUE THREAD

**Issue by weyus** [bundler/bundler#1365]
Rails 3.0.10
Bundler 1.0.18

My Gemfile has the following:

gem 'active_scaffold',  :git => 'git://github.com/activescaffold/active_scaffold.git', :branch => 'rails-3.0'

I'm install my gems into my system Ruby installation.

When I execute "sudo gem install", I see:

Using active_scaffold (3.0.19) from git://github.com/activescaffold/active_scaffold.git (at rails-3.0)

If I look at my Gemfile.lock file, I see:

GIT
  remote: git://github.com/activescaffold/active_scaffold.git
  revision: 81e801e2c0dfa71a7ae41808e015e8e80b105537
  branch: rails-3.0
  specs:
    active_scaffold (3.0.19)
      rails (~> 3.0.0)
      render_component_vho
      verification

which shows the correct git revision to pull for the branch.

But the active_scaffold gem is NOT installed in GEM_HOME nor in ~/.bundle/ruby/1.8/gems.

I get 

"git://github.com/activescaffold/active_scaffold.git (at rails-3.0) is not checked out. Please run `bundle install`"

when I attempt to run the Rails server ("rails s").

Subsequent runs of sudo bundle install do not work.

I also tried this on a brand new installation of a Rails app. and got the same results, even excluding the :branch option.

Interestingly, the two dependencies noted above (render_component_vho) and verification are installed just fine, but I imagine that's because they're coming from Rubygems.

**Comment by fones** [comment]
I run into this problem again on AWS ElasticBenstalk

Gemfile:
```
gem 'wisper-activejob', git: 'https://github.com/krisleech/wisper-activejob', branch: 'rails5'
```
Gemfile.lock:
```
GIT
  remote: https://github.com/krisleech/wisper-activejob
  revision: 88a7ecdf1faf17d448d74f52fb88b0c774df7c94
  branch: rails5
  specs:
    wisper-activejob (0.0.2)
      activejob (>= 4.0.0)
      wisper
```

on AWS:
```
[ec2-user current]$ rails -T
https://github.com/krisleech/wisper-activejob (at rails5@88a7ecd) is not yet checked out. Run `bundle install` first.
```

Any idea what can help?

**Comment by segiddins** [comment]
@fones this is a 6 year old issue, please open up a new issue with the details requested in https://github.com/bundler/bundler/blob/master/doc/contributing/ISSUES.md
