### ISSUE TITLE
Need help reporting Ruby 1.9.3 segmentation fault on bundle update

### ISSUE THREAD

**Issue by alexeymuranov** [bundler/bundler#1596]
Hello, i've run into a segmentation fault in _ruby 1.9.3-p0_ when running `bundle update` on rails master branch with _bundler-1.0.21_.  I've explained how to reproduce the issue here, but it is not a _rails_ issue: https://github.com/rails/rails/issues/4050.  Here is the Gemfile that causes the problem:  https://gist.github.com/1502675.

I will appreciate some help because i do not know how to make a _ruby_ bug report out of this.

**Comment by djrobby** [comment]
> I was also able to patch bundler to stop the segfault. Type "which bundle" (or "rbenv which bundle" on rbenv) to locate the executable. Make sure the file comment contains "This file was generated by RubyGems." Add a require 'openssl' before or after require 'rubygems'.

Lifesaver!
