### ISSUE TITLE
 sqlite3.h is missing

### ISSUE THREAD

**Issue by m2web** [bundler/bundler#1613]
I was pushing code to heroku and got the following error:

/usr/local/lib/ruby/1.9.1/rubygems/installer.rb:483:in `rescue in block in build_extensions': ERROR: Failed to build gem native extension. (Gem::Installer::ExtensionBuildError)
       /usr/local/bin/ruby extconf.rb
       checking for sqlite3.h... no
       sqlite3.h is missing. Try 'port install sqlite3 +universal'
       or 'yum install sqlite-devel' and check your shared library search path (the
       location where your sqlite3 shared library is located).
       **\* extconf.rb failed ***
       Could not create Makefile due to some reason, probably lack of
       necessary libraries and/or headers.  Check the mkmf.log file for more
       details.  You may need configuration options.
       Provided configuration options:
       --with-opt-dir
       --without-opt-dir
       --with-opt-include
       --without-opt-include=${opt-dir}/include
       --with-opt-lib
       --without-opt-lib=${opt-dir}/lib
       --with-make-prog
       --without-make-prog
       --srcdir=.
       --curdir
       --ruby=/usr/local/bin/ruby
       --with-sqlite3-dir
       --without-sqlite3-dir
       --with-sqlite3-include
       --without-sqlite3-include=${sqlite3-dir}/include
       --with-sqlite3-lib
       --without-sqlite3-lib=${sqlite3-dir}/lib
       --enable-local
       --disable-local

Please let me know if you have any questions.

**Comment by osgaldor** [comment]
I'm having this same problem after a fresh install of the railsinstaller.  I'm a little new to rails development, how do I install sqlite globally?

**Comment by correaleyval** [comment]
In Ubuntu: sudo apt-get install libsqlite3-dev, solved this problem.

**Comment by cspherical** [comment]
@correaleyval This worked on Ubuntu 18.04.2 LTS

**Comment by elamje** [comment]
If anyone came here for sqlite - Heroku issues, Heroku, doesn't support it. However, the open source PaaS Dokku does. It's basically a clone of Heroku but only made to run on one server with most of the same commands. Since you are in control of the server it runs on, you can use sqlite!
