### ISSUE TITLE
Please support conditional gems

### ISSUE THREAD

**Issue by FooBarWidget** [bundler/bundler#1636]
(Also mentioned on [the Phusion blog](http://blog.phusion.nl/2012/01/19/bundler-and-public-applications/))
Some people are writing apps that are not only meant to be used internally, but also by the general public. Think RedMine. These apps typically allow the user to choose their database driver through `config/database.yml`. However the driver must also be specified inside Gemfile, otherwise the app cannot load it. The result is that the user has to edit both database.yml and Gemfile, which introduces the following problems:
- The user may not necessarily be a Ruby programmer. The Gemfile will confuse him.
- The user is not able to use the `Gemfile.lock` that the developer has provided. This makes installing in deployment mode with the developer-provided Gemfile.lock impossible.

This can be worked around in a very messy form with groups. For example:

```
group :driver_sqlite do
  gem 'sqlite3'
end

group :driver_mysql do
  gem 'msyql'
end

group :driver_postgresql do
  gem 'pg'
end
```

And then, if the user chose to use MySQL:

```
bundle install --without='driver_postgresql driver_sqlite'
```

This is messy because you have to exclude all the things you don't want. If the app supports 10 database drivers then the user has to put 9 drivers on the exclusion list.

I propose supporting conditionals in the Gemfile language. Example:

```
condition :driver => 'sqlite' do
  gem 'sqlite3'
end

condition :driver => 'mysql' do
  gem 'mysql'
end

condition :driver => 'postgresql' do
  gem 'pg'
end

condition :driver => ['mysql', 'sqlite'] do
  gem 'foobar'
end
```

The following command would install the `mysql` and the `foobar` gems:

```
bundle install --condition driver=mysql
```

Here, Bundler _must_ enforce that the `driver` condition is set; if it's not set then it will raise an error. To allow for the `driver` condition to not be set, the developer must explicitly define that the condition may be nil:

```
condition :driver => nil do
  gem 'null-database-driver'
end
```

Here, `bundle install` will install `null-database-driver`.

**Comment by steakknife** [comment]
Just encountered this use-case again, so here's my 20 millicents.

Another solution for conditionals to support `bundle package --all` could be:

```ruby
condition -> { driver? 'sqlite' } do
  gem 'foo'
  gem 'bar'
end

gem 'whatever', condition: -> { ENV.keys.grep(/AWESOME/).any? }
```

Such that the lambda is evaluated sometime *after* Bundler is completely loaded, and the block happens if the lambda returns truthy (so inside the lambda might be your own DSL: `driver?` for example).

And then somehow augment Gemfile.lock to include a bit of ruby (the contents of the lambda) (Yea security or functionality, pick 1.5) 

That way, prod, dev, whatever will run idempotently and as expected, and also arbitrary expressions can be used without breaking `package --all`.

**Comment by steakknife** [comment]
Another method of expressing *a gem's* (as opposed to a project's) soft dependencies *that are not platform-specific* [here](https://github.com/steakknife/oui/blob/ecf8a3baaf7370b737c171bb2a2e70fe483e5df3/ext/mkrf_conf.rb)  (hacky using airquote "native extensions" that aren't really)
