### ISSUE TITLE
Support native extensions for gems specified as paths

### ISSUE THREAD

**Issue by dlee** [bundler/bundler#1679]
Using local gem directories using :path is very useful for gem development. This is no exception for gems that provide native extensions. However, bundler in its current form doesn't allow compiling C extensions for gems specified as paths, according to the Gemfile manpage:

<pre>
Unlike :git, bundler does not compile C extensions for gems specified as paths.
</pre>

This is presumably because we don't want bundler creating files within the local gem's directory. It would be nice if there was a way to tell bundler to force compilation of C extensions in these cases:

```
gem "mygem", :path => "../mygem", :compile => true
# or
gem "mygem", :path => "../mygem", :extensions => true
```

If you think this is too dangerous, then it might be useful to have a :build option, so that doing `bundle install` would automatically `gem build` and then install those gems. Likewise, `bundle update` would delete all :build gems and re-build and re-install them.

```
gem 'mygem', :build => "../mygem"
# or
gem 'mygem', :path => "../path", :build => true
```

**Comment by Papipo** [comment]
Seven years later I resume that project and I still have the same problem. I need a vendored gem (because the git repo is private) which has extensions and bundler doesn't build them 🤷‍♂

**Comment by Papipo** [comment]
I've solved it by putting the packaged gem in `/vendor/cache`
