### ISSUE TITLE
"bundle exec rspec spec" not working on JRuby/Windows

### ISSUE THREAD

**Issue by celsodantas** [bundler/bundler#1689]
I'm trying to run 

```
bundle exec rspec spec
```

and I'm always getting this:

```
$ bundle exec rspec spec
bundler: command not found: rspec
Install missing gem executables with `bundle install`
```

If I run this

```
$ bundle exec rspec
```

It works! I mean, the code works but as I need to pass the spec/ folder, it doesn't do what I want. =[

But it work fine if I use like this:

```
$ bundle exec "rspec spec"
```

But as I'm trying to use <code>Guard</code>, it runs the rspec with no "quotes".

This are my configurations: 

```
$ jruby -v
jruby 1.6.7 (ruby-1.8.7-p357) (2012-02-22 3e82bc8) (Java HotSpot(TM) Client VM 1.7.0) [Windows 7-x86-java]

Windows 7

$ gem -v
1.8.15
```

More info about my configuration (Gemfile[.lock] and bundle config)
https://gist.github.com/1949650

**Comment by phorekka** [comment]
i am also facing the same problem..

**Comment by headius** [comment]
@phorekka There have been some recent issues with `bundle exec` on JRuby 9.1 not finding gems that should be installed. If that sounds familar, I'd report to jruby/jruby first and if we figure out there's something to fix in Bundler we can circle back here.
