### ISSUE TITLE
Selectively Cache Gems

### ISSUE THREAD

**Issue by Fluxx** [bundler/bundler#1795]
I have what I imagine to be a not-so-uncommon use case.  I have a project hosted on Heroku that uses mostly public gems, save for a couple private ones.  Since I don't want [embed my Github un/pw in my Gemfile](http://stackoverflow.com/a/8949955/459863) or pay/run my own private gemserver like [Gemfury](http://www.gemfury.com/), the best solution at present for bundling my private gems on Heroku is to cache all my gems in `vendor/cache` where Bundler will find and use when Heroku runs `bundle install` for me.

This certainly works, but the down side is that I have to cache _all_ my gems, not just the ones that are private.  Caching all the gems bloats the size of my git repo, which isn't a _huge_ deal but does slow things down.  One solution to this to `.gitignore` the `vendor/cache` directory, and then manually `git add` my private gems as needed.  This also certainly works, but has two small downsides:
1. Bundler still copies over all the .gem files locally, which is redundant if they're already on my file system in the normal rubygems cache.
2. It requires me to remember to `git add` the new version of the gem every time I upgrade it.  I might forget to do this, and confuse other developers and potentially cause hard to track down problems.

Again, these are small annoyances, but it seems like a way to selectively cache gems would be best.   That way you could only cache the certain gems that you needed/wanted cached.

My thought on how to do this was the following:
1. Add a  `cache` config option to `bundle config`, which would allow users to configure whether caching was used by default or not.  Setting it to `false` would not automatically cache gems during a `bundle install`.  This config option could also be called `autocache`.
2. Add support in the `Gemfile` for a `:cache => true` option, which would force the gem to be cached, overriding the `cache` `bundle config` option.  This config option could also be called `:force_cache` or something more descriptive.

I looked through the existing issues and source code, so I apologize if this has been suggested before or if there is a better way to do it.  Also, I'm happy to actually do the work and submit a pull request, I just wanted to check and make sure this feature has a chance of being merged before I do.

**Comment by md5** [comment]
Forgive me for commenting on a long-closed issue, but did this issue ever get raised over at `bundler/bundler-features`? I wasn't able to find it over there.

As far as I can tell, there's still no way to selectively cache certain gems other than running `bundle package --all` and manually deleting all but the desired gems.

**Comment by indirect** [comment]
I think that's the workaround that people use today. If you still want this, please open a feature request ticket explaining the scenario and why you want to cache only some gems. Thanks!

**Comment by md5** [comment]
Thanks @indirect. I opened https://github.com/bundler/bundler-features/issues/98
