### ISSUE TITLE
incorrect header check (Zlib::DataError)

### ISSUE THREAD

**Issue by ghost** [bundler/bundler#1914]
I ran bundle install and found the following errors,

```
Fetching full source index from http://rubygems.org/
Unfortunately, a fatal error has occurred. Please report this error to the Bundler issue tracker at https://github.com/carlhuda/bundler/issues so that we can fix it. Please include the full output of the command, your Gemfile and Gemfile.lock. Thanks!
/home/cis/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/site_ruby/1.9.1/rubygems.rb:566:in `inflate': incorrect header check (Zlib::DataError)
    from /home/cis/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/site_ruby/1.9.1/rubygems.rb:566:in `inflate'
    from /home/cis/.rvm/gems/ruby-1.9.2-p0@global/gems/bundler-1.1.3/lib/bundler/fetcher.rb:57:in `fetch_spec'
    from /home/cis/.rvm/gems/ruby-1.9.2-p0@global/gems/bundler-1.1.3/lib/bundler/remote_specification.rb:46:in `_remote_specification'
    from /home/cis/.rvm/gems/ruby-1.9.2-p0@global/gems/bundler-1.1.3/lib/bundler/remote_specification.rb:51:in `method_missing'
    from /home/cis/.rvm/gems/ruby-1.9.2-p0@global/gems/bundler-1.1.3/lib/bundler/spec_set.rb:131:in `tsort_each_child'
    from /home/cis/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/tsort.rb:203:in `each_strongly_connected_component_from'
    from /home/cis/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/tsort.rb:209:in `block in each_strongly_connected_component_from'
    from /home/cis/.rvm/gems/ruby-1.9.2-p0@global/gems/bundler-1.1.3/lib/bundler/spec_set.rb:133:in `block (2 levels) in tsort_each_child'
    from /home/cis/.rvm/gems/ruby-1.9.2-p0@global/gems/bundler-1.1.3/lib/bundler/spec_set.rb:133:in `each'
    from /home/cis/.rvm/gems/ruby-1.9.2-p0@global/gems/bundler-1.1.3/lib/bundler/spec_set.rb:133:in `block in tsort_each_child'
    from /home/cis/.rvm/gems/ruby-1.9.2-p0@global/gems/bundler-1.1.3/lib/bundler/spec_set.rb:131:in `each'
    from /home/cis/.rvm/gems/ruby-1.9.2-p0@global/gems/bundler-1.1.3/lib/bundler/spec_set.rb:131:in `tsort_each_child'
    from /home/cis/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/tsort.rb:203:in `each_strongly_connected_component_from'
    from /home/cis/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/tsort.rb:182:in `block in each_strongly_connected_component'
    from /home/cis/.rvm/gems/ruby-1.9.2-p0@global/gems/bundler-1.1.3/lib/bundler/spec_set.rb:127:in `block in tsort_each_node'
    from /home/cis/.rvm/gems/ruby-1.9.2-p0@global/gems/bundler-1.1.3/lib/bundler/spec_set.rb:127:in `each'
    from /home/cis/.rvm/gems/ruby-1.9.2-p0@global/gems/bundler-1.1.3/lib/bundler/spec_set.rb:127:in `tsort_each_node'
    from /home/cis/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/tsort.rb:180:in `each_strongly_connected_component'
    from /home/cis/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/tsort.rb:148:in `tsort_each'
    from /home/cis/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/tsort.rb:135:in `tsort'
    from /home/cis/.rvm/gems/ruby-1.9.2-p0@global/gems/bundler-1.1.3/lib/bundler/spec_set.rb:110:in `sorted'
    from /home/cis/.rvm/gems/ruby-1.9.2-p0@global/gems/bundler-1.1.3/lib/bundler/installer.rb:55:in `run'
    from /home/cis/.rvm/gems/ruby-1.9.2-p0@global/gems/bundler-1.1.3/lib/bundler/installer.rb:12:in `install'
    from /home/cis/.rvm/gems/ruby-1.9.2-p0@global/gems/bundler-1.1.3/lib/bundler/cli.rb:220:in `install'
    from /home/cis/.rvm/gems/ruby-1.9.2-p0@global/gems/bundler-1.1.3/lib/bundler/vendor/thor/task.rb:22:in `run'
    from /home/cis/.rvm/gems/ruby-1.9.2-p0@global/gems/bundler-1.1.3/lib/bundler/vendor/thor/invocation.rb:118:in `invoke_task'
    from /home/cis/.rvm/gems/ruby-1.9.2-p0@global/gems/bundler-1.1.3/lib/bundler/vendor/thor.rb:263:in `dispatch'
    from /home/cis/.rvm/gems/ruby-1.9.2-p0@global/gems/bundler-1.1.3/lib/bundler/vendor/thor/base.rb:386:in `start'
    from /home/cis/.rvm/gems/ruby-1.9.2-p0@global/gems/bundler-1.1.3/bin/bundle:13:in `<top (required)>'
    from /home/cis/.rvm/gems/ruby-1.9.2-p0@global/bin/bundle:19:in `load'
    from /home/cis/.rvm/gems/ruby-1.9.2-p0@global/bin/bundle:19:in `<main>'

```

**Comment by rohit-webonise** [comment]
I ran bundle install and found the following errors
and got the same issue.
can you please help me out

**Comment by shrikant-ror** [comment]
I am also facing the same error while performing bundle install. Please find my attached screenshot for the same.
![screenshot from 2016-02-16 17-04-46](https://cloud.githubusercontent.com/assets/2870964/13075240/ae334200-d4cf-11e5-916d-31365480f803.png)

**Comment by RochesterinNYC** [comment]
Can you please post the entire error report?

Please follow the following guidelines for reporting this error so that we can help you out: https://github.com/bundler/bundler/blob/master/ISSUES.md#reporting-unresolved-problems

**Comment by shrikant-ror** [comment]
@RochesterinNYC Basically I am trying to set up [loomi open source project](https://github.com/loomio/loomio).

As per their documentation, I have rails, git, node.js and postgres.

After completing my set up I just fired `bundle install` and got the above issue.

**Comment by shrikant-ror** [comment]
Also downgrade the bundler version to 1.6.5 but getting the same type of issue. Please find the error trace
![screenshot from 2016-02-18 18-21-23](https://cloud.githubusercontent.com/assets/2870964/13143812/71199ed4-d66c-11e5-9ada-a75500eced23.png)

Please let me know anything need. If you want to recreate this issue you can take the clone (clone url - https://github.com/loomio/loomio.git ) and try to set up it.

**Comment by RochesterinNYC** [comment]
@shrikant-ror can you post your bundle environment via `bundle env`?

I am unable to reproduce this. I can successfully run `bundle install` after cloning loomio.

This is my bundle env:
```
Environment

    Bundler   1.11.2
    Rubygems  2.5.1
    Ruby      2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin14]
    GEM_HOME  /redacted/.rvm/gems/ruby-2.3.0
    GEM_PATH  /redacted/.rvm/gems/ruby-2.3.0:/Users/pivotal/.rvm/gems/ruby-2.3.0@global
    RVM       1.26.11 (latest)
    Git       2.6.2
    rubygems-bundler (1.4.4)
```

**Comment by shrikant-ror** [comment]
@RochesterinNYC Here is my bundle environment 

Bundler 1.6.5
Ruby 2.3.0 (2015-12-25 patchlevel 0) [x86_64-linux]
Rubygems 2.5.1
rvm 1.26.11 (latest)
GEM_HOME /home/test/.rvm/gems/ruby-2.3.0
GEM_PATH /home/test/.rvm/gems/ruby-2.3.0:/home/test/.rvm/gems/ruby-2.3.0@global
rubygems-bundler (1.4.4)

**Comment by indirect** [comment]
@shrikant-ror you didn't provide the requested information. please follow [ISSUES](https://github.com/bundler/bundler/blob/master/ISSUES.md) and return everything asked for.

**Comment by RochesterinNYC** [comment]
@shrikant-ror a corporate firewall might be the cause of this issue.

These issues seem to be the same or related to your issue:

rubygems/rubygems#466

http://help.rubygems.org/discussions/problems/768-installing-or-updating-any-gem-fails-with-zlibdataerror-incorrect-header-check

For future reference, the more closely you follow and provide info as denoted in [ISSUES](https://github.com/bundler/bundler/blob/master/ISSUES.md), the easier it is for us to assist you.

**Comment by shrikant-ror** [comment]
@RochesterinNYC @indirect  Thanks for your help. Finally able to resolve this issue.

There is issue in my Gemfile. The source address is `http`, so changed it to `https`.

**Comment by eliza-abraham** [comment]
I had the same issue. What worked for me was installing zlib ```brew install zlib```
I had to kill my terminal and open it again before i ran ```bundle install```.
