### ISSUE TITLE
Bundler.require not loading .gemspec dependencies

### ISSUE THREAD

**Issue by jch** [bundler/bundler#2018]
I'm not sure if this is intentional behavior, but from [this documentation](http://gembundler.com/rubygems.html), I expected that `Bundler.require :default` would also require the runtime dependencies specified in .gemspec. I've created a [demo gem](https://github.com/jch/bundler-issue) showing this.

``` ruby
# gemspec
Gem::Specification.new do |gem|
  # snip
  gem.add_dependency 'rack'
end
```

``` ruby
# Gemfile
source 'https://rubygems.org'

# Specify your gem's dependencies in bundler-issue.gemspec
gemspec
```

``` ruby
# test.rb
require 'bundler'
Bundler.require :default  # <-- I expected this to load dependencies in from the gemspec

puts "Dependency loaded: " + defined?(Rack).inspect
```

If I explicitly require rack, it works as expected, and Gemfile.lock lists rack as expected.

**Comment by ifreecarve** [comment]
> Gems must load their own dependencies.

Can you explain what this means, to someone who is unfamiliar with this process?

**Comment by indirect** [comment]
@ifreecarve no problem. Gems are not able to use Bundler, so they should simply `require` the libraries they need.

**Comment by ifreecarve** [comment]
By this you mean that in whatever ruby source files are contained in the gem, you say `require 'some_library'`?  And bundler uses this to determine/download dependencies when you `bundle install`?

(I was able to solve the problem I was having, but I have no idea how.)

**Comment by indirect** [comment]
Not exactly. When you create a gem, list any other gems you depend on in your gemspec. Then, inside the code of your gem, require those gems. So, if your gem depends on Rack, you would add a line like `s.add_runtime_dependency "rack", "~> 1.2"` to your gemspec, and then a line like `require "rack"` to your gem code.




Bundler will use the gemspec to know what to install and add to the load path; your gem will then require it and be able to use it.

**Comment by ifreecarve** [comment]
Hmm... that's what I was doing.  Bundler seemed to be ignoring what i put in `s.add_runtime_dependency`, which is why I asked.  I had tried a variety of things, and although it works now I'm not sure what fixed it.

**Comment by maschwenk** [comment]
@indirect would this potentially change now that `bundler` is part of Ruby std lib?

**Comment by colby-swandale** [comment]
No, this behavior is not changing.
