### ISSUE TITLE
bundle install hangs indefinitely

### ISSUE THREAD

**Issue by doriath** [bundler/bundler#2101]
I have following Gemfile, with no Gemfile.lock, so it should be easy to reproduce:

```
source 'http://rubygems.org'

gem 'mongoid'
gem 'airbrake'
```

For such Gemfile, bundler was not able to resolve the dependencies (at least for few minutes). My environment (bundle config is empty):

```
$ bundle -v
Bundler version 1.2.0
$ ruby -v
ruby 1.9.3p194 (2012-04-20 revision 35410) [x86_64-darwin11.4.0]
$ rvm -v
rvm 1.15.5 (stable) ...
$ gem -v
1.8.24
```

I also removed all cache directories described in ISSUES file.

After using `export DEBUG_RESOLVER=1`, I managed to solve the problem with following Gemfile:

```
source 'http://rubygems.org'

gem 'builder', '3.0.0'
gem 'mongoid'
gem 'airbrake'
```

Here is the gist with the resolver log https://gist.github.com/3722349.

I don't know the resolver algorithm, but after analyzing the logs, it looks like depth first search. The problem is, the version of builder is set to 3.1.8 as the forth gem, and then after 5 other gems there activemodel that requires ~> 3.0.0. Then it is changing versions of those 5 gems, but there is so many versions of them, it takes forever to go up to builder gem, to change it to 3.0.0.

**Comment by saulwiggin** [comment]
i'm still having a problem with this. 

bundle install

is just hanging. I've tried to install individual gems but then running something like

rails s

returns that the gem is not found. Please help I need to stop bundle install hanging so i am able to run the application and carry on.

**Comment by deivid-rodriguez** [comment]
Could you please open a separate bug report with steps to reproduce? This issue is very old and it's closed. Thanks!
