### ISSUE TITLE
Wrong permissions on system-wide installed gem files

### ISSUE THREAD

**Issue by zeha** [bundler/bundler#2136]
When using bundler as non-root, gem files installed into the system location can end up with the wrong permissions, when the user running bundler has a umask != 022.
Additionally, gem cache files end up being owned by the user running bundler.

Example for the cache file ownership:

```
% cat Gemfile
source :rubygems
gem "tzinfo"
% ls -la /var/lib/gems/1.9.1/cache/tzinfo-*
-rw-r--r-- 1 ch ch 311808 Okt 29 15:55 /var/lib/gems/1.9.1/cache/tzinfo-0.3.34.gem
```

Looking at the code, lib/bundler/fetcher.rb does a sudo mv of the cache file into it's final location; replacing this with cp should make this part of the issue go away.

The other part is that the files of the gem themselves end up being created with the users umask.

Example (from the original reporter) with umask 027:

```
/var/lib/gems/1.9.1/cache: 
-rw-r----- 1 rrt rrt  89K Oct 29 10:30 addressable-2.3.2.gem 
-rw-r----- 1 rrt rrt  35K Oct 29 10:30 crack-0.3.1.gem 
-rw-r----- 1 rrt rrt 109K Oct 29 10:30 rake-0.9.2.2.gem 
```

(Other users won't be able to read these gems.)

I'd have expected all the gem files to be owned by root, and have normalized permissions of 0644 / 0755 respectively.

This issue was reported by a user of the Debian package for bundler [1], but I have reproduced this with bundler 1.2.1 installed with gem install.

```
% ruby -v
ruby 1.9.3p194 (2012-04-20 revision 35410) [x86_64-linux]
% gem1.9.1 -v
1.8.23
% bundle -v
Bundler version 1.2.1
```

[1] http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=691743

(Edited twice because I failed to understand the entirety of the issue at first.)

**Comment by jmehnle** [comment]
@indirect,
> Bundler still honors Rubygems' permissions as set, but now sets its own permissions on any files created by it to `0777 & ~File.umask`.

As of what Bundler version?
