### ISSUE TITLE
Removing gem from Gemfile do not remove the gem from the Gemfile.lock file

### ISSUE THREAD

**Issue by zedtux** [bundler/bundler#2146]
It seems that removing a gem from the Gemfile don't update the Gemfile.lock.

For example, I had a gem in my Gemfile.
I removed it and then executed `bundle`.

I removed it with `gem uninstall gem_name`.

But the Gemfile.lock, that is versioned, have not changed.

How to "synchronize" my Gemfile.lock with my Gemfile ?

**Comment by rdubigny** [comment]
It's an old issue but this might help.

1) I manually deleted the unwanted dependencies in the Gemfile (the `gem 'gem_name'` line(s))
2) I ran `bunlder install` => at this point the Gemfile.lock is updated
3) I manually uninstalled unwanted package `gem uninstall gem_name`

Seems ok so far.
