### ISSUE TITLE
bundle check is missing the --without option

### ISSUE THREAD

**Issue by codyfauser** [bundler/bundler#216]
bundle install has the `--without` option, which allows one to ignore gems from particular groups. We are using this facility for our production environment, so that we don't have to install test or development gems on the production servers.

However, in order to speed up deployment and reduce load on the production servers during deployment we're using bundle check during deployment. Unfortunately, bundle check seems to have lost the `--without` option and therefore will always fail unless we don't use the `--without` option when installing gems in production.

**Comment by chrishough** [comment]
@indirect that link is broken? I have the same question as @codyfauser

**Comment by indirect** [comment]
@chrishough correct. Feel free to find the `check_spec.rb` file yourself, though. It's still in this repo.

**Comment by chrishough** [comment]
Wow.. Thanks....

Do you see it here?  https://github.com/bundler/bundler/tree/master/spec/other

**Comment by indirect** [comment]
Sometime in the last seven years, we moved the file. It's now here: https://github.com/bundler/bundler/blob/master/spec/commands/check_spec.rb.

**Comment by chrishough** [comment]
Thank you @indirect
