### ISSUE TITLE
Updating gems from git + branch

### ISSUE THREAD

**Issue by jlecour** [bundler/bundler#2165]
Hi,

I'm maintaining a gem and using it in a project.

During the development phase, I want to try the gem's code in the project, without releasing many beta builds. So I use the `:git` feature of Bundler to checkout the gem's source code from Git.

In the gem repository, I've created a topic branch (and an alpha version number).
In the project Gemfile, I've set this : `gem "my_gem", :git => "git@example.com:my_gem.git", :branch => 'my_branch'`

The first time I `bundle` it's fine ; Bundler fetches the repository, checks out the right branch.

But if I update the gem's source code, push it on the remote repository, and updates the project's bundle, nothing changes. I've verified with `bundle open my_gem` that the code is not updated.

I don't know if I'm missing something obvious here or if this is a "bug".

Thanks for the collective effort of making Bundler more and more awesome.

**Comment by vbklv** [comment]
The issue persists with the latest Bundler.

**Comment by indirect** [comment]
@vbklv please follow [ISSUES](https://github.com/bundler/bundler/blob/master/ISSUES.md) m.

**Comment by skylarmb** [comment]
Hi, its 2016 now and still having this issue on the latest bundler (1.12.5) as of writing this.

An easy solution I came across that works for me is to just comment the line out of the `Gemfile`, run `bundle install`, uncomment it, run `bundle install` again. Bundler then fetches the latest ref from github and updates the Gemfile.lock with the correct ref. Better solution than `bundle update` as you really (most of the time) dont want to update all your gems, and avoids you having to manually update / define a ref in your `Gemfile`.

**Comment by indirect** [comment]
@skylarmb please follow [ISSUES](https://github.com/bundler/bundler/blob/master/ISSUES.md).

**Comment by rcrogers** [comment]
Still seeing this in 2017 for `Bundler version 1.13.7`

**Comment by ndemianc** [comment]
Using bundler (1.13.7) I can observe same issue:

In the Gemfile:

```
...
gem 'custom_gem', git: 'git@github.com:organization/custom_gem.git'
...
```

After first bundle install:
```
...
Using custom_gem 0.1.0 from git@github.com:organization/custom_gem.git (at master@743a980)
...
```
Which is fine, because latest commit on the master has the same SHA eq to 743a980.

After second bundle install with new existing commits on the master branch for custom_gem:
```
...
Using custom_gem 0.1.0 from git@github.com:organization/custom_gem.git (at master@743a980)
...
```

`bundle update custom_gem` - helps, and I can see `bundle install ` uses latest changes for `custom_gem`:
 
```
Using custom_gem 0.1.0 from git@github.com:organization/custom_gem.git (at master@34hfe13)
```

However, shouldn't `bundle install` fetch the latest master for the gem from the github?

**Comment by andremedeiros** [comment]
`bundle install` will simply meet the dependencies in the state that is described by `Gemfile.lock`. This is what guarantees reproducible builds.

In other words, `bundle install` should never install gem versions that your code has never run against.

**Comment by ndemianc** [comment]
@andremedeiros Thank You for clear answer. @andremedeiros Do You consider use of ref along with github link to the gem in Gemfile, as a valid option to get latest sources from latest changes on the master? Or there is another better way to do it, besides using tags and released versions?

**Comment by andremedeiros** [comment]
This is all personal opinion, so take it with a grain of salt.

I wouldn't release to production anything that pointed to a git source with the ref `master`. Typically `master` branches have the latest, and potentially breaking changes that might affect how your application interacts with that particular dependency.

Using a version (or a tag) at least guarantees that no `bundle update` operations will break for that one dependency.

In terms of keeping it updated, you need to explicitly run `bundle update <gem>` (and do check out one of the latest improvements, `--conservative`.)

Again, this gives you the guarantee that the code you ran on your development environment, and that you checked works and passes the tests on your CI is exactly the same that will run in your production environment. In no case will `bundle install` change versions that you've used and that are recorded in your `Gemfile.lock`.

**Comment by dARKaRK** [comment]
Hi,
I'm using `bundler 1.16.0` and am still facing this issue.
I'm using heroku to deploy my application which has some gems which are sourced from github like this:
`gem 'gem-name', git: 'github/repo/location', branch: 'master'`
Now, after I did some changes to my `gem-name` and pushed it to git, the commits do not get updated in the application even after I redeploy(which builds the application from scratch again) it in heroku.
The workaround I found was to `bundle install` locally and push the updated `Gemfile.lock`.
Still, is there no way that bundler will look for latest version of a gem as soon as the gem repo is updated?

**Comment by hakunin** [comment]
Having this issue as well. Gem from repo branch, switching local branch which wants the gem from a different branch and have a local path override.

Bundler absolutely refuses to install it, `bundle update --source <gemname>` tells me to run `bundle install` first and `bundle install` tells me to run `bundle install`.

As a workaround I have to go into `Gemfile.lock`, remove the info on top of the file regarding the gem, run `bundle update --source <gemname>` again and then it works.

But FFS, this can't be so hard to fix! If the gem in `Gemfile` does not match (has a different branch in this case), you just ignore what `Gemfile.lock` says dammit and it would work.
