### ISSUE TITLE
Requiring other gems when working in the console?

### ISSUE THREAD

**Issue by jfcouture** [bundler/bundler#217]
Is there a way to require a gem that is not in the Gemfile? The use case I'm thinking of is mainly playing with things in the console. For example, right now, I'm just generating fake data in the console with the faker gem. I can think of a couple of other gems I just personally use sometimes in the console and it seems kinda absurd to have to edit Gemfile, bundle install relock, and then push to other team members gems I'm the only one using (forgetting to revert in git).

**Comment by hiteshsharma** [comment]
You can append gem path to ruby load path. Do this:
    gem which faker
    => /usr/local/ruby/......../faker-0.1.1/lib/faker.rb

Start Rails console and do the following:
    $: << '/usr/local/ruby/......../faker-0.1.1/lib/'

and now load faker gem
    require 'faker'
    => true
