### ISSUE TITLE
Specs fail on Rubinius

### ISSUE THREAD

**Issue by indirect** [bundler/bundler#2180]
See https://gist.github.com/51452cf46b7fbf1d0f1a for the full failing spec run output.

**Comment by LynnCo** [comment]
Looks like the linked PR fixed this, so I'm closing

**Comment by segiddins** [comment]
Nope, specs still fail horrifically on RBX iirc. Or maybe that's jruby?

**Comment by LynnCo** [comment]
Well it looked solved :/ I can't test at the moment, unfortunately

**Comment by allenzhao** [comment]
I'm working on this ;)

**Comment by allenzhao** [comment]
Trying to use [Docker image provided by Rubinius](https://hub.docker.com/r/rubinius/docker/builds/)

**Comment by segiddins** [comment]
@allenzhao did you ever make any progress on this front?

**Comment by allenzhao** [comment]
@segiddins I did looked into this, but I can't even run specs on Rubinius because of strange 'HOME not set' issues. See https://github.com/rubinius/rubinius/issues/3688. Also, when I tried to run spec on Windows, this happens too. I took some time to look into it but failed to solve it.

**Comment by colby-swandale** [comment]
I'm going to close this issue, there is no work being done on this and the value of getting Rubinius working in CI has changed a lot since this issue was opened.
