### ISSUE TITLE
Should be able to call 'bundle install' via ruby instead of command line

### ISSUE THREAD

**Issue by thewoolleyman** [bundler/bundler#223]
Like "GemInstaller.install" for example.  I shouldn't have to shell out and check the return code when I want to install from ruby - e.g. at the beginning of a ruby script which kicks off my Continuous Integration build.

**Comment by jgonera** [comment]
This doesn't work anymore because `CLI`'s constructor expects some arguments now. Is there any stable API for this? I don't want to use `bundler/inline` because I still want my dependencies to be in a `Gemfile`.

**Comment by indirect** [comment]
The only current stable API for installing is using the CLI tool, so `system %w[bundle install]` is probably your best bet.
