### ISSUE TITLE
Specify patch level in Gemfile

### ISSUE THREAD

**Issue by sethvargo** [bundler/bundler#2231]
According to the website

> The ruby directive explicitly leaves out the ability to specify a patch level. Ruby patches often include important bug and security fixes and are extremely compatible.

This has proven to be false multiple times, [most recently here](https://bugs.ruby-lang.org/issues/7629). Patch levels are _not_ always backward compatible. 

I'm not saying that a patch level should be _required_, but it should definitely be an option.

**Comment by ryanmt** [comment]
+1 formigarafa.  It is pretty weird to not utilize the semantic versioning for ruby like we do for gems.
