### ISSUE TITLE
'bundle install --without development test heroku' fatal error (installing diaspora*)

### ISSUE THREAD

**Issue by mathieusoleil** [bundler/bundler#2240]
bundle install --without development test heroku
leads to a 'fatal error'

Here a record of command and infos asked:

Script started on Tue Jan  8 20:20:07 2013

mercredia@jeudi:/home/mercredia/diaspora % bundle install --without development test heroku

Fetching https://github.com/plataformatec/markerb.git
remote: Counting objects: 104, done.
remote: Compressing objects:   1% (1/70)
remote: Compressing objects:   2% (2/70)
(...)
remote: Compressing objects: 100% (70/70)
remote: Compressing objects: 100% (70/70), done.
Receiving objects:   0% (1/104)  
Receiving objects:   1% (2/104)  
(...)
Resolving deltas:  77% (31/40)  
Resolving deltas:  80% (32/40)  
Resolving deltas:  95% (38/40)  
Resolving deltas: 100% (40/40)  
Resolving deltas: 100% (40/40), done.
Unfortunately, a fatal error has occurred. Please see the Bundler 
troubleshooting documentation at http://bit.ly/bundler-issues. Thanks! 
/usr/local/lib/ruby/gems/1.9/gems/bundler-1.2.3/lib/bundler.rb:294:in `block in load_gemspec_uncached': invalid byte sequence in US-ASCII 

(ArgumentError)
    from /usr/local/lib/ruby/gems/1.9/gems/bundler-1.2.3/lib/bundler.rb:291:in `chdir'
    from /usr/local/lib/ruby/gems/1.9/gems/bundler-1.2.3/lib/bundler.rb:291:in`load_gemspec_uncached'
    from /usr/local/lib/ruby/gems/1.9/gems/bundler-1.2.3/lib/bundler.rb:282:in `load_gemspec'
    from /usr/local/lib/ruby/gems/1.9/gems/bundler-1.2.3/lib/bundler/source.rb:411:in`block in load_spec_files'
    from /usr/local/lib/ruby/gems/1.9/gems/bundler-1.2.3/lib/bundler/source.rb:410:in `each'
    from /usr/local/lib/ruby/gems/1.9/gems/bundler-1.2.3/lib/bundler/source.rb:410:in`load_spec_files'
    from /usr/local/lib/ruby/gems/1.9/gems/bundler-1.2.3/lib/bundler/source.rb:799:in `load_spec_files'
    from /usr/local/lib/ruby/gems/1.9/gems/bundler-1.2.3/lib/bundler/source.rb:381:in`local_specs'
    from /usr/local/lib/ruby/gems/1.9/gems/bundler-1.2.3/lib/bundler/source.rb:774:in `specs'
    from /usr/local/lib/ruby/gems/1.9/gems/bundler-1.2.3/lib/bundler/definition.rb:491:in`block in converge_locked_specs'
    from /usr/local/lib/ruby/gems/1.9/gems/bundler-1.2.3/lib/bundler/definition.rb:480:in `each'
    from /usr/local/lib/ruby/gems/1.9/gems/bundler-1.2.3/lib/bundler/definition.rb:480:in`converge_locked_specs'
    from /usr/local/lib/ruby/gems/1.9/gems/bundler-1.2.3/lib/bundler/definition.rb:166:in `resolve'
    from /usr/local/lib/ruby/gems/1.9/gems/bundler-1.2.3/lib/bundler/definition.rb:113:in`specs'
    from /usr/local/lib/ruby/gems/1.9/gems/bundler-1.2.3/lib/bundler/definition.rb:108:in `resolve_remotely!'
    from /usr/local/lib/ruby/gems/1.9/gems/bundler-1.2.3/lib/bundler/installer.rb:81:in`run'
    from /usr/local/lib/ruby/gems/1.9/gems/bundler-1.2.3/lib/bundler/installer.rb:14:in `install'
    from /usr/local/lib/ruby/gems/1.9/gems/bundler-1.2.3/lib/bundler/cli.rb:230:in`install'
    from /usr/local/lib/ruby/gems/1.9/gems/bundler-1.2.3/lib/bundler/vendor/thor/task.rb:27:in `run'
    from /usr/local/lib/ruby/gems/1.9/gems/bundler-1.2.3/lib/bundler/vendor/thor/invocation.rb:120:in`invoke_task'
    from /usr/local/lib/ruby/gems/1.9/gems/bundler-1.2.3/lib/bundler/vendor/thor.rb:275:in `dispatch'
    from /usr/local/lib/ruby/gems/1.9/gems/bundler-1.2.3/lib/bundler/vendor/thor/base.rb:408:in`start'
    from /usr/local/lib/ruby/gems/1.9/gems/bundler-1.2.3/bin/bundle:14:in `block in <top (required)>'
    from /usr/local/lib/ruby/gems/1.9/gems/bundler-1.2.3/lib/bundler/friendly_errors.rb:4:in`with_friendly_errors'
    from /usr/local/lib/ruby/gems/1.9/gems/bundler-1.2.3/bin/bundle:14:in `<top (required)>'
    from /usr/local/bin/bundle:23:in`load'
    from /usr/local/bin/bundle:23:in `<main>'
mercredia@jeudi:/home/mercredia/diaspora % cat Gemfile 

source 'http://rubygems.org'

gem 'rails', '3.2.10'

gem 'foreman', '0.60.2'

gem 'unicorn', '4.4.0', :require => false

gem 'rails_autolink', '1.0.9'
# cross-origin resource sharing

gem 'rack-cors', '0.2.7', :require => 'rack/cors'
# click-jacking protection

gem 'rack-protection', '1.2'
# authentication

gem 'devise', '2.1.2'

gem 'remotipart', '1.0.2'

gem 'omniauth', '1.1.1'
gem 'omniauth-facebook', '1.4.1'
gem 'omniauth-tumblr', '1.1'
gem 'omniauth-twitter', '0.0.13'

gem 'twitter', '4.2.0'
# mail

gem 'markerb', :git => 'https://github.com/plataformatec/markerb.git'
gem 'messagebus_ruby_api', '1.0.3'

group :production do # we don't install these on travis to speed up test runs
  gem 'rails_admin', '0.2.0'
  gem 'fastercsv', '1.5.5', :require => false
  gem 'rack-ssl', '1.3.2', :require => 'rack/ssl'
  gem 'rack-rewrite', '1.3.1', :require => false

  # analytics
  gem 'rack-google-analytics', '0.11.0', :require => 'rack/google-analytics'
  gem 'rack-piwik', '0.1.3', :require => 'rack/piwik', :require => false

end
# database

gem "activerecord-import", "0.2.11"
gem 'foreigner', '1.2.1'
gem 'mysql2', '0.3.11' if ENV['DB'].nil? || ENV['DB'] == 'all' || ENV['DB'] == 'mysql'
gem 'pg', '0.14.1' if ENV['DB'] == 'all' || ENV['DB'] == 'postgres'
gem 'sqlite3' if ENV['DB'] == 'all' || ENV['DB'] == 'sqlite'
# file uploading

gem 'carrierwave', '0.7.1'
gem 'fog', '1.6.0'
gem 'mini_magick', '3.4'
# JSON and API

gem 'json', '1.7.5'
gem 'acts_as_api', '0.4.1 '
# localization

gem 'i18n-inflector-rails', '~> 1.0'
gem 'rails-i18n', '0.7.0'
# parsing

gem 'nokogiri', '1.5.5'
gem 'redcarpet', "2.2.2"
gem 'roxml', :git => 'https://github.com/Empact/roxml.git', :ref => '7ea9a9ffd2338aaef5b0'
gem 'ruby-oembed', '0.8.7'
# queue

gem 'resque', '1.23.0'
gem 'resque-timeout', '1.0.0'
# tags

gem 'acts-as-taggable-on', '2.3.3'
# URIs and HTTP

gem 'addressable', '2.3.2', :require => 'addressable/uri'
gem 'http_accept_language', '1.0.2'
gem 'typhoeus', '0.3.3'
# views

gem 'haml', '3.1.7'
gem 'mobile-fu', '1.1.0'

gem 'will_paginate', '3.0.3'
gem 'client_side_validations', '3.2.1'
gem 'gon', '4.0.1'
# assets

group :assets do
  gem 'bootstrap-sass', '2.1.1.0'
  gem 'sass-rails', '3.2.5'

  # Windows and OSX have an execjs compatible runtime built-in, Linux users should
  # install Node.js or use 'therubyracer'.
  #
  # See https://github.com/sstephenson/execjs#readme for more supported runtimes

  # gem 'therubyracer', :platform => :ruby

  gem 'handlebars_assets', '0.6.6'
  gem 'uglifier', '1.3.0'

  gem "asset_sync", '0.5.0', :require => false
end

gem 'jquery-rails', '2.1.3'
# web

gem 'faraday', '0.8.4'
gem 'faraday_middleware', '0.9.0'

gem 'jasmine', '1.2.1'
### GROUPS

group :test do

  gem 'capybara', '1.1.3'
  gem 'cucumber-rails', '1.3.0', :require => false
  gem 'database_cleaner', '0.9.1'

  gem 'timecop', '0.5.3'
  gem 'factory_girl_rails', '4.1.0'
  gem 'fixture_builder', '0.3.4'
  gem 'fuubar', '1.1.0'
  gem 'rspec-instafail', '0.2.4', :require => false
  gem 'selenium-webdriver', '2.26.0'

  gem 'webmock', '1.8.11', :require => false

  gem 'spork', '1.0.0rc3'
  gem 'guard-rspec', '2.1.1'
  gem 'guard-spork', '1.2.3'
  gem 'guard-cucumber', '1.2.2'
  gem 'rb-inotify', '0.8.8', :require => false
  gem 'rb-fsevent', '0.9.2', :require => false

end

group :test, :development do
  gem 'debugger', '1.2.1'
  gem "rspec-rails", "2.11.4" 
end

group :development do
  gem 'capistrano', '2.12.0', :require => false
  gem 'capistrano_colors', '0.5.5', :require => false
  gem 'capistrano-ext', '1.2.1', :require => false
end
mercredia@jeudi:/home/mercredia/diaspora % bundle config

Settings are listed in order of priority. The top value will be used.

without
  Set for your local app (/usr/home/mercredia/diaspora/.bundle/config): "development:test:heroku"
mercredia@jeudi:/home/mercredia/diaspora % bundle -v

Bundler version 1.2.3
mercredia@jeudi:/home/mercredia/diaspora % ruby -v

ruby 1.9.3p327 (2012-11-10 revision 37606) [amd64-freebsd9]
mercredia@jeudi:/home/mercredia/diaspora % gem -v

1.8.24
mercredia@jeudi:/home/mercredia/diaspora %  ## no rvm ##

mercredia@jeudi:/home/mercredia/diaspora % gem list

**\* LOCAL GEMS ***

bundler (1.2.3)
rake (10.0.3)
mercredia@jeudi:/home/mercredia/diaspora % exit

exit

Script done on Tue Jan  8 20:21:31 2

**Comment by jadeye** [comment]
A little late but never too late...
This is my first try at [`diaspora`](https://wiki.diasporafoundation.org/Installation/Heroku)....**Error**:

```
$ bundle --without development test heroku production assets
/home/jadeye/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.5.3/lib/bundler/dependency.rb:42:in `block in initialize': undefined method `to_sym' for {:optional=>true}:Hash (NoMethodError)
       /home/jadeye/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.5.3/lib/bundler/dependency.rb:42:in `map'
       /home/jadeye/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.5.3/lib/bundler/dependency.rb:42:in `initialize'
       /home/jadeye/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.5.3/lib/bundler/dsl.rb:76:in `new'
       /home/jadeye/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.5.3/lib/bundler/dsl.rb:76:in `gem'
       /media/Venus/diaspora/Gemfile:64:in `block in eval_gemfile'
       /home/jadeye/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.5.3/lib/bundler/dsl.rb:164:in `group'
       /media/Venus/diaspora/Gemfile:63:in `eval_gemfile'
       /home/jadeye/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.5.3/lib/bundler/dsl.rb:30:in `instance_eval'
       /home/jadeye/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.5.3/lib/bundler/dsl.rb:30:in `eval_gemfile'
       /home/jadeye/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.5.3/lib/bundler/dsl.rb:9:in `evaluate'
       /home/jadeye/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.5.3/lib/bundler/definition.rb:26:in `build'
       /home/jadeye/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.5.3/lib/bundler.rb:152:in `definition'
       /home/jadeye/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.5.3/lib/bundler/cli.rb:253:in `install'
       /home/jadeye/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.5.3/lib/bundler/vendor/thor/command.rb:27:in `run'
       /home/jadeye/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.5.3/lib/bundler/vendor/thor/invocation.rb:121:in `invoke_command'
       /home/jadeye/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.5.3/lib/bundler/vendor/thor.rb:363:in `dispatch'
       /home/jadeye/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.5.3/lib/bundler/vendor/thor/base.rb:440:in `start'
       /home/jadeye/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.5.3/lib/bundler/cli.rb:10:in `start'
       /home/jadeye/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.5.3/bin/bundle:20:in `block in <top (required)>'
       /home/jadeye/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.5.3/lib/bundler/friendly_errors.rb:5:in `with_friendly_errors'
       /home/jadeye/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.5.3/bin/bundle:20:in `<top (required)>'
       /home/jadeye/.rvm/gems/ruby-2.1.1@global/bin/bundle:23:in `load'
       /home/jadeye/.rvm/gems/ruby-2.1.1@global/bin/bundle:23:in `<main>'
       /home/jadeye/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `eval'
       /home/jadeye/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `<main>'
There was an error in your Gemfile, and Bundler cannot continue.
```
Tried all the above but in vain...
Also read all related to `locale`, regenerated `locale`,
Tried most of the suggested [here](http://askubuntu.com/questions/162391/how-do-i-fix-my-locale-issue) with no luck...

Any ides anyone...??
