### ISSUE TITLE
Bundler goes into infinite loop when unable to resolve dependencies

### ISSUE THREAD

**Issue by sethvargo** [bundler/bundler#2297]
With the most recent release of bundler, running `bundle install` when dependencies cannot be met results in an infinite loop in the resolver.

```
DEBUG_RESOLVER=1 bundle install -VV
```

Will show that it locks up and can't resolve (in this case json) because of conflicting sources.

**Comment by aderouineau** [comment]
Perhaps the following paper may be of interest: "Modelling and Resolving Software Dependencies", Daniel Burrows, <https://people.debian.org/~dburrows/model.pdf>
