### ISSUE TITLE
Support for post-install hooks?

### ISSUE THREAD

**Issue by dtnorris** [bundler/bundler#2354]
We are interested in being able to run commands after a bundle install has succeeded and would like to discuss the best way to do this.

**Comment by brandonweiss** [comment]
@indirect I see a lot of talk about Bundler install hooks on different issues/PRs that (like this thread) mentions that Bundler respects RubyGems post install hooks, but I'm testing it out and that doesn't seem to be the case… if I install via `gem install` the hook runs, but if I add the gem to a Gemfile and install it doesn't seem to be triggering the hook. Is that unexpected?

**Comment by segiddins** [comment]
@brandonweiss please open a new issue
