### ISSUE TITLE
Bundler 1.0.22 + Ruby 1.9.2: $ bundle install --> undefined method `list'

### ISSUE THREAD

**Issue by chinseone** [bundler/bundler#2411]
<p>My current version of bundler is 1.0.22 and ruby 1.9.2-p320. When I run $bundle instal, I got the following stack trace:</p>

<code>Fetching source index for http://rubygems.org/
/home/chinseone/.rvm/gems/ruby-1.9.2-p320/gems/bundler-1.0.22/lib/bundler/source.rb:253:in `fetch_all_remote_specs': undefined method`list' for #Gem::SpecFetcher:0x00000001b04338 (NoMethodError)
    from /home/chinseone/.rvm/gems/ruby-1.9.2-p320/gems/bundler-1.0.22/lib/bundler/source.rb:234:in `block in remote_specs'
    from /home/chinseone/.rvm/gems/ruby-1.9.2-p320/gems/bundler-1.0.22/lib/bundler/source.rb:231:in`each'
    from /home/chinseone/.rvm/gems/ruby-1.9.2-p320/gems/bundler-1.0.22/lib/bundler/source.rb:231:in `remote_specs'
    from /home/chinseone/.rvm/gems/ruby-1.9.2-p320/gems/bundler-1.0.22/lib/bundler/source.rb:165:in`fetch_specs'
    from /home/chinseone/.rvm/gems/ruby-1.9.2-p320/gems/bundler-1.0.22/lib/bundler/source.rb:70:in `specs'
    from /home/chinseone/.rvm/gems/ruby-1.9.2-p320/gems/bundler-1.0.22/lib/bundler/definition.rb:176:in`block (2 levels) in index'
    from /home/chinseone/.rvm/gems/ruby-1.9.2-p320/gems/bundler-1.0.22/lib/bundler/definition.rb:175:in `each'
    from /home/chinseone/.rvm/gems/ruby-1.9.2-p320/gems/bundler-1.0.22/lib/bundler/definition.rb:175:in`block in index'
    from /home/chinseone/.rvm/gems/ruby-1.9.2-p320/gems/bundler-1.0.22/lib/bundler/index.rb:7:in `build'
    from /home/chinseone/.rvm/gems/ruby-1.9.2-p320/gems/bundler-1.0.22/lib/bundler/definition.rb:174:in`index'
    from /home/chinseone/.rvm/gems/ruby-1.9.2-p320/gems/bundler-1.0.22/lib/bundler/definition.rb:168:in `resolve'
    from /home/chinseone/.rvm/gems/ruby-1.9.2-p320/gems/bundler-1.0.22/lib/bundler/definition.rb:107:in`specs'
    from /home/chinseone/.rvm/gems/ruby-1.9.2-p320/gems/bundler-1.0.22/lib/bundler/definition.rb:102:in `resolve_remotely!'
    from /home/chinseone/.rvm/gems/ruby-1.9.2-p320/gems/bundler-1.0.22/lib/bundler/installer.rb:43:in`run'
    from /home/chinseone/.rvm/gems/ruby-1.9.2-p320/gems/bundler-1.0.22/lib/bundler/installer.rb:8:in `install'
    from /home/chinseone/.rvm/gems/ruby-1.9.2-p320/gems/bundler-1.0.22/lib/bundler/cli.rb:219:in`install'
    from /home/chinseone/.rvm/gems/ruby-1.9.2-p320/gems/bundler-1.0.22/lib/bundler/vendor/thor/task.rb:22:in `run'
    from /home/chinseone/.rvm/gems/ruby-1.9.2-p320/gems/bundler-1.0.22/lib/bundler/vendor/thor/invocation.rb:118:in`invoke_task'
    from /home/chinseone/.rvm/gems/ruby-1.9.2-p320/gems/bundler-1.0.22/lib/bundler/vendor/thor.rb:263:in `dispatch'
    from /home/chinseone/.rvm/gems/ruby-1.9.2-p320/gems/bundler-1.0.22/lib/bundler/vendor/thor/base.rb:386:in`start'
    from /home/chinseone/.rvm/gems/ruby-1.9.2-p320/gems/bundler-1.0.22/bin/bundle:13:in `<top (required)>'
    from /home/chinseone/.rvm/gems/ruby-1.9.2-p320/bin/bundle:23:in`load'
    from /home/chinseone/.rvm/gems/ruby-1.9.2-p320/bin/bundle:23:in `<main>'
    from /home/chinseone/.rvm/gems/ruby-1.9.2-p320/bin/ruby_noexec_wrapper:14:in`eval'
    from /home/chinseone/.rvm/gems/ruby-1.9.2-p320/bin/ruby_noexec_wrapper:14:in `<main>'
</code>

<p>And the ruby file at the specific line is as followed:</p>

<code>def fetch_all_remote_specs(&blk)
        begin
          # Fetch all specs, minus prerelease specs
          Gem::SpecFetcher.new.list(true, false).each(&blk)
          # Then fetch the prerelease specs
          begin
            Gem::SpecFetcher.new.list(false, true).each(&blk)
          rescue Gem::RemoteFetcher::FetchError
            Bundler.ui.warn "Could not fetch prerelease specs from #{self}"
          end
        rescue Gem::RemoteFetcher::FetchError
          Bundler.ui.warn "Could not reach #{self}"
        end
      end
</code>

I'm completely new to RoR. Anyone could kindly tell me how to fix this 'list' method?

**Comment by mudit44** [comment]
Thanks errakeshpd.
