### ISSUE TITLE
Support for overriding gem dependencies

### ISSUE THREAD

**Issue by robotmay** [bundler/bundler#2412]
As suggested, I'm rewriting this as a new issue instead of tagging it onto the end of [the previous one.](https://github.com/carlhuda/bundler/issues/1549).

This has cropped up before, and there are clearly people who still want the ability to override gem dependencies in their Gemfile (me for one). Forking a repository just to fix 'rake' version conflicts is extremely irritating, and has resulted in about half of my repos just being forks with a single version change in them. My company too, in general, prefers to avoid keeping lots of forked repos around as it makes upgrading an application more complex.

I understand the argument against not using the ability to override dependencies, but I'm not sure I understand the reason for not including that functionality in the first place. There are plenty of package managers which support it, even if (in general) it's a bad idea to use it. I'll provide some evidence when I can actually find the relevant man pages.

I think it's time to discuss this again in light of all the recent security vulnerabilities being found throughout popular Ruby gems. An example I ran across today was noticing that the 'mail' gem required by Padrino 0.10.7 is insecure. I don't really want to fork that repo just to update a number, as I know the latest version won't cause any problems (and if it did then that would justify forking the repo instead). For simple overrides, perhaps just an option would be enough:

```
gem 'mail', '2.4.4', :override => true
```

Or perhaps specifying the gem to override it in:

```
gem 'mail', '2.4.4', :override => ['padrino']
```

Or maybe it's associated to the problematic gem ([as suggested](https://github.com/carlhuda/bundler/issues/1549#issuecomment-3927462) by @myabc):

```
gem 'padrino', '0.10.7' do
  override 'mail', '2.4.4'
end
```

I'm not too sure on the implementation problems of these (as I'm not especially familiar with the Bundler code base), but I'd be willing to try and implement it if nobody else would; so long as there was the possibility of it being merged in.

I totally get the arguments against this feature, but forking repos to update rake is driving me insane :scream:

**Comment by padcom** [comment]
Has that been implemented? If not what's the official way of requesting a feature (and maybe doing a community vote?)

**Comment by TimMoore** [comment]
@padcom you can find the Bundler project's policy on feature requests at https://github.com/bundler/bundler/blob/master/CONTRIBUTING.md#requesting-features

**Comment by chrismo** [comment]
I think this is where the trail leads to currently => https://github.com/bundler/bundler/issues/4552
