### ISSUE TITLE
lots of timeouts

### ISSUE THREAD

**Issue by jrochkind** [bundler/bundler#2421]
When trying `bundle install` on a large project, I'm getting LOTS of timeouts. 

```
Gem::RemoteFetcher::FetchError: Errno::ETIMEDOUT: Operation timed out (https://rubygems.org/gems/net-ssh-2.6.6.gem)
An error occurred while installing net-ssh (2.6.6), and Bundler cannot continue.
Make sure that `gem install net-ssh -v '2.6.6'` succeeds before bundling.
```

If I `gem install net-ssh -v '2.6.6'`, the individual gem installs fine, and quite quickly. 

Then I go do a `bundle install` again, and it gets past net-ssh (presumably because that's installed locally now), but complains with an ETIMEDOUT about whatever gem is next in line. And I need to manaually `gem install` that, rinse, repeat.   It'll be quite a painstaking process to actually get all the gems installed. 

Just guessing: Could there be something wrong with the timeout code such that it's keeping track of the entire `bundle install` process from start to finish, rather than reset the timeout timer on each individual gem?  Could this result in bundler refusing to install a Gemfile with lots of dependencies (in a slowish environment, cause of local network or rubygems infrastructure), becuase it can't get through them all before the timeout?

```
$ ruby -v
ruby 1.9.3p392 (2013-02-22 revision 39386) [x86_64-darwin12.2.1]
$ gem -v
2.0.2
$ bundle -v
Bundler version 1.3.1
```

**Comment by JetQin** [comment]
i think the most easier way is change the Gemfile

change
```
source 'https://rubygems.org'
```
to
```
source 'http://rubygems.org'
```
