### ISSUE TITLE
Trailing quotes get dropped from config values

### ISSUE THREAD

**Issue by dpw** [bundler/bundler#2469]
Using bundler 1.3.5, if I do:

```
bundle config build.eventmachine "--with-cflags='-O2 -pipe -march=native -w'"
```

Then my ~/.bundle/config contains:

```

---
BUNDLE_BUILD__EVENTMACHINE: --with-cflags='-O2 -pipe -march=native -w'
```

But when the relevant gem gets built (eventmachine in this case) the trailing quote in that value gets stripped in the gem build_args, resulting in a build failure:

```
Installing eventmachine (0.12.10) sh: 1: Syntax error: Unterminated quoted string
```

This is caused by the regexp in carlhuda/bundler@d1c555f2e4878ae2d03d802c48c782e36854ace0 discarding the trailing quote.  That ghetto YAML parses needs to be slightly less ghetto.

**Comment by kwisatz** [comment]
I see this was closed in 2014, but it's still or again a problem.

**Comment by deivid-rodriguez** [comment]
@kwisatz Could you please open a new issue with reproduction steps? I tried @xaviershay's reproduction and it worked just fine for me.

**Comment by kwisatz** [comment]
I'll see if I can re-create it later.
Managed to work around it now by simply replacing all double quotes and
just using single quotes as in @xaviershay's example in my
~/.bundle/config file

**Comment by kwisatz** [comment]
I can't reproduce this anymore.
I removed the `BUNDLE_BUILD__EVENTMACHINE` line from my `~/.bundle/config` to make sure I had no artifacts from the previous attempts and without this line, the problem is also gone. 
Maybe the settings I had were from a much older installation of the gem?

**Comment by deivid-rodriguez** [comment]
Not sure... I don't think the settings format has changed recently.
