### ISSUE TITLE
ruby 1.8.7 undefined method `map' for Gem::Specification:Class

### ISSUE THREAD

**Issue by Vittly** [bundler/bundler#2484]
Hello! I am using:

ruby 1.8.7 (2011-02-18 patchlevel 334) [x86_64-linux], MBARI 0x6770, Ruby Enterprise Edition 2011.03
gem 1.5.2

For some gems in the end of installation I got `ERROR:  While executing gem ...  (NoMethodError) undefined method map for Gem::Specification:Class`.
Error doesn't corrupt the installation. All is ok. But when I do `bundle update` it exits at first such error telling me that `em::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension ... Bundler cannot continue.
Make sure that ... succeeds before bundling` and I have to install all gems one-by-one

Should Bundler ignore such errors?

**Comment by Hettomei** [comment]
:+1: For gem update --system (on ubuntu V14 and rbenv + ruby 1.8.7 )
