### ISSUE TITLE
Bundle outdated ignores versions defined in Gemfile

### ISSUE THREAD

**Issue by sheerun** [bundler/bundler#2575]
In my Gemfile I have defined `gem 'rails', '~> 3.2.13'`. Clearly, I want to watch only minor fixes of rails gem. Regardless of that `bundle outdated` shows `* rails (4.0.0 > 3.2.14)` what is useless information for me.

Is there a way to show outdated gems with respect to versions defined in my Gemfile?

**Comment by rud** [comment]
The feature is now built in: `bundle outdated --strict`.
