### ISSUE TITLE
Gem.bin_path(gem_name, exec_name) disregards gem name when exec_name is present

### ISSUE THREAD

**Issue by samsm** [bundler/bundler#2644]
[In rubygems_integration, Gem.bin_path is overwritten.](https://github.com/bundler/bundler/blob/2697b4638d3d85040d2a7d7f9c5af591fa4ae4bf/lib/bundler/rubygems_integration.rb#L303) This is used for binstubs, and possibly other stuff.

One difference between the Rubygems and Bundler implementations is that in Rubygems, `specs` is generated from system gems that match the given gem name and version. Bundler's `specs` is a list of all gems in the bundle, regardless of if they match the gem name passed into bin_path or not.

This creates a situation where `Gem.bin_path("rspec-core", "rspec")` might use an rspec bin from a gem that is in the bundle, but is not rspec-core. I ran into this when I let an rspec binstub leak into a gem I was working on.

I think a solution could be as simple as comparing the name [on this line](https://github.com/bundler/bundler/blob/2697b4638d3d85040d2a7d7f9c5af591fa4ae4bf/lib/bundler/rubygems_integration.rb#L303):

``` ruby
specs.find { |s| s.name == name && s.executables.include?(exec_name) }
```

But a more thorough approach might be to do [what Rubygems does](https://github.com/ruby/ruby/blob/e16d9c42cf7f7d6b8f56cb8cf627591b6bd57f5d/lib/rubygems.rb#L275) and limit the set of available gems to ones that fit the name/version criteria.

I looked into creating a pull request for this, but I was unclear on where that test might live, and what it might look like.

Thanks for reading!

**Comment by pnomolos** [comment]
I believe this issue may exist within a very narrow scope.  I have the following set up:

- I'm using rbenv
- A project which uses a local gem via `bundle config local.GEM_NAME`
- binstubs generated in the project
- binstubs generated in the local gem
- I'm using Bundler version 1.12.5

When trying to run `bin/guard` I get the following error:

```
Bundler is using a binstub that was created for a different gem.
This is deprecated, in future versions you may need to `bundle binstub guard` to work around a system/bundle conflict.
```

I have verified the following:

- My PATH does not contain references to either bin directory (so `bin/guard` is indeed pointing at the correct binstub)
- The project's `bin/guard` reference the guard gem directly.  `load Gem.bin_path("guard", "guard")`
- `load Gem.bin_path("guard", "guard")` __doesn't__ reference the same directory that `bundler show guard` does.  Instead, it reference the local gem's path.

**Comment by segiddins** [comment]
@pnomolos please open a new issue, as this one is closed
