### ISSUE TITLE
Bundler doesn't use the right gems location

### ISSUE THREAD

**Issue by felipec** [bundler/bundler#2667]
The documentation of `bundle install` says this:

"This defaults to the gem home, which is the location that gem install installs gems to."

However, that's not true. My distribution has the following in '/etc/gemrc': gem: --user-install. Which means `gem install foo` works, but bundler doesn't work.

At the very least `bundle install` should have a similar --user-install option, and perhaps even read gemrc, that would be the only way to make sure it does the same as `gem install`.

**Comment by ioquatix** [comment]
I came here and read the discussion. I agree with @felipec, it's confusing that `bundle install` doesn't install to the same location as `gem install` when using `/etc/gemrc` in the manor specified.

**Comment by Karamorf** [comment]
I agree as well. It doesn't need to be the default way bundler handles gem install, but there should be a flag that either looks for the "user-install" setting in ~/.gemrc and /etc/gemrc or some other way to follow where "gem install" actually installs things to.

I think there are two use cases conflicting here. The way case that bundler solves extremely well is dependency management for projects that are getting deployed to various environments. 

The other case where this setup hurts is where you want to have dependency management for helper scripts. These scripts aren't deployed to environments or any sort of project in the classic software development world. These are for diagnosing user problems, mining data for information, etc. and will always be manually used by a person. In this case, why on earth would I want to pollute by system ruby with random gems from this? I guess I should look at getting rvm installed specifically for this, but that seems like overkill when all I need to do to maintain my workstation is separate user gems from system gems.
