### ISSUE TITLE
Bundler disrespects and ignores sudo umask.

### ISSUE THREAD

**Issue by envygeeks** [bundler/bundler#2694]
When bundler has to "invoke sudo" to gem install it disrespects the permissive `umask` placed on `sudo` for non-/root files when a users `umask` is less permissive.  This can lead to a `umask` of **0077** with a permissive `umask` of **0022** enforced by `sudo` to actually end up as the users `umask` of **0077** which is bad for business when it comes to shared gems.

**Comment by kzidane** [comment]
I'm actually having the same issue right now even though `sudo`'s `umask` is `0022`.

```
$ sudo bash -c umask
0022

$ cat Gemfile
source "https://rubygems.org"
gem "minitest"

$ bundle install
Fetching gem metadata from https://rubygems.org/.............
Resolving dependencies...
Using bundler 1.16.4
Fetching minitest 5.11.3
Installing minitest 5.11.3
Bundle complete! 1 Gemfile dependency, 2 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.

$ ls -l /var/lib/gems/2.5.0/specifications/minitest-5.11.3.gemspec
-rw------- 1 root root 4804 Sep  4 16:52 /var/lib/gems/2.5.0/specifications/minitest-5.11.3.gemspec
```

Any thoughts?
