### ISSUE TITLE
Bundler doesn't respect the ruby version when choosing the gem to install

### ISSUE THREAD

**Issue by hanshasselberg** [bundler/bundler#2721]
Hello, 

thank you very much for your work on this great project.
I've been trying to let bundler choose which version of a gem to install depending on the used ruby version. The `mime-types` gem drops Ruby 1.8 support with version `2.0` and I thought I can allow users with a more recent Ruby version to use it: https://github.com/typhoeus/ethon/commit/1a54d0a6a040515154819aa5a410e646ba570c20. But it didn't work out: https://travis-ci.org/typhoeus/ethon/jobs/14217901.

I was reading your guidelines but didn't know what else to provide since everything is already publicly available. Feel free to ask for anything you need.

**Comment by deivid-rodriguez** [comment]
Just unarchiving this repo for a minute to clarify to future readers that this feature was added a long time ago to bundler. If you're running into this issue, upgrade bundler and/or ruby, and you should be alright :tada:.
