### ISSUE TITLE
'bundle clean' doesn't support --path?

### ISSUE THREAD

**Issue by jordansissel** [bundler/bundler#2742]
Was fiddling around. Found 'bundle clean' and tried it. Saw this:

```
% bundle clean
Can only use bundle clean when --path is set or --force is set
```

So, I'm like yay! Let's rock.

```
% bundle clean --path vendor/bundle
Unknown switches '--path'
```

Should this work? It'd be cool if it did. Happy to help fix this. Let me know!

**Comment by dideler** [comment]
Running into the same issue. Also noticed the `--path` option isn't documented.

```
↪ bundle -h clean
Usage:
  bundle clean [OPTIONS]

Options:
      [--dry-run=only print out changes, do not actually clean gems]              
      [--force=forces clean even if --path is not set]                            
      [--no-color=Disable colorization in output]                                 
  -V, [--verbose=Enable verbose output mode]                                      
  -r, [--retry=Specify the number of times you wish to attempt network commands]  

Cleans up unused gems in your bundler directory
```

**Comment by shreve** [comment]
I'm not sure why it's documented the way it is because you're right, @dideler, `--path` isn't an available flag for `bundle clean`.

I just realized this path option needs to be set in a config file.

`bundle config --local path "vendor/bundle"`

adds the line

`BUNDLE_PATH: vendor/bundle`

to `./.bundle/config`, which clears up this issue.

**Comment by TimMoore** [comment]
It's a confusing message that should be fixed, but the idea is that `bundle clean` cleans whatever path `bundle install` installs into. You wouldn't normally want to pass it a different path. It should say something like "Can only use bundle clean when --force is set or bundle install was previously called with the --path option".

The point of this is a safeguard before deleting gems from a location that might be shared between multiple apps. If you get this message and really want it to proceed, use `bundle clean --force`.

I'll leave this open pending a clarification to the warning.

**Comment by shreve** [comment]
How about something a little more verbose like:

```
Bundler doesn't know where to clean. Set the path with `bundle config`, or use `--force` to clean gems globally.
```

**Comment by indirect** [comment]
Apparently we've already updated the error message:

<blockquote>Cleaning all the gems on your system is dangerous! To remove every system gem not in this bundle, run `bundle clean --force`.</blockquote>

**Comment by jordansissel** [comment]
:heart:
