### ISSUE TITLE
Your Ruby version is 2.1.0, but your Gemfile specified 2.1

### ISSUE THREAD

**Issue by bughit** [bundler/bundler#2778]
on bundle install

my understanding is that Gemfile ruby method is not intended for specifying the patch level, at least not necessarily

**Comment by joallard** [comment]
+1

**Comment by NayeemKaka** [comment]
Your Ruby version is 2.1.2, but your Gemfile specified 2.2.0????

**Comment by parabuzzle** [comment]
> @OneDivZero yes, something like that seems reasonable. I think the requirement "2.1" should accept "2.1.x" versions without warning, and the requirement "2.1.3" should raise on 2.1.2 or 2.1.4, for example.

^ This! Please!

**Comment by indirect** [comment]
There's [a ticket](https://trello.com/c/gAWOh4Jk) for this. We're going to do it as soon as we have time. Pull requests are welcome, if you have time before we do.

**Comment by ABdalaa** [comment]
#!/bin/bash

mkdir -p /tmp/repro-2778
cd /tmp/repro-2778

cat > Gemfile <<EOF
ruby '2.2.2'
EOF

bundle install


i use this and it works fine thanks https://avatars3.githubusercontent.com/u/895588?v=3&s=400

**Comment by ABdalaa** [comment]
Your Ruby version is 2.2.2, but your Gemfile specified 2.2.0 
how i could fix this

**Comment by parabuzzle** [comment]
@ABdalaa change your Gemfile to ruby 2.2.2 or install ruby 2.2.0.

**Comment by joallard** [comment]
@indirect Would just being able to specify 2.1 be shorter to implement than being able to specify ">= 2.0.0"? It'd be nice to have. Because the current situation is akin to require pre-2.0 Gemfiles to specify patchlevel; pretty much overkill. (And tbh, it enourages some users to stick with previous versions instead of upgrading the bugfix increment and having to reinstall all of their gems)

**Comment by indirect** [comment]
You only have to reinstall your gems when the Ruby Application Binary Interface changes. That will stay exactly the same regardless of whether that is implemented or not.

**Comment by joallard** [comment]
My question was "is it less complicated to just implement the same functionality that was there before, ie specify Ruby without patchlevel/bugfix than implement a full version specifier?" Because if it is, I'd gladly take that instead of waiting for the full functionality to be implemented

**Comment by indirect** [comment]
Your reasoning for the "simpler" solution was based on something that isn't true--changing the Gemfile from 2.2.1 to 2.2.2 doesn't require reinstalling gems unless your ruby version manager makes you do it.

As for whether the implementation is less hard, yes, you could implement something like the existing patch-level floating, simply using any Z version of that X.Y.Z Ruby version. I'm open to a pull request for that, sure.

**Comment by indirect** [comment]
(Please limit the Z-version float to Ruby 2.1 or greater, since that is when the Z version started tracking patch levels.)

**Comment by parabuzzle** [comment]
I think the Z-version float would be a great stop-gap until semver support is created :) I can work on it this weekend.

**Comment by joallard** [comment]
@parabuzzle Any progress?

**Comment by parabuzzle** [comment]
@joallard work got in the way :disappointed:  so no

**Comment by vanburg** [comment]
@parabuzzle 
Just forget about this problem :)
```ruby
# top of Gemfile:
fail "Ruby 2.2.x required" unless RUBY_VERSION =~ /^2\.2/
```
which produce nice error if you run ``bundle``:
```
[!] There was an error parsing `Gemfile`: Ruby 2.2.x required. Bundler cannot continue.

 #  from /Users/vanburg/src/rails_bare_app/Gemfile:5
 #  -------------------------------------------
 #  # see: https://github.com/bundler/bundler/issues/2845
 >  fail "Ruby 2.2.x required" unless RUBY_VERSION =~ /^2\.2/
 #  
 #  -------------------------------------------
```

**Comment by jpbochi** [comment]
thanks, @vanburg! The error is as ugly as they come, but code fulfils its objective.

**Comment by ewdurbin** [comment]
@vanburg saves the day.
