### ISSUE TITLE
warning with gemspec `Your Gemfile lists the gem X more than once.`

### ISSUE THREAD

**Issue by kostya** [bundler/bundler#2822]
Gemfile:

```ruby
source 'https://rubygems.org'

# Specify your gem's dependencies in eye.gemspec
gemspec

gem 'parallel_tests', :git => "https://github.com/kostya/parallel_tests.git"
```

and gemspec include line:
```
  gem.add_development_dependency 'parallel_tests'
```

bundle shows warning every time (from v1.5.1), 
```
Your Gemfile lists the gem parallel_tests (>= 0) more than once.
You should probably keep only one of them.
While it's not a problem now, it could cause errors if you change the version of just one of them later.
```

For me this is not a warning (i just specify gem source).

**Comment by jakeonrails** [comment]
I got this error when I included a rails engine, whose source code is inside of my rails app directory.

```ruby
gemspec path: 'apps/my-engine'
```

MyEngine adds dependencies via the `.gemspec` file.

by switching to

```ruby
gem 'my-engine', path: 'apps/my-engine'
```

I was able to get this warning to go away.

**Comment by grosser** [comment]
Other scenario that is annoying:

internal gem that depends on other private gems -> always showing a warning

```Ruby
# a.gemspec
s.add_runtime_dependency 'b'
```

now the gemfile needs this to resolve it properly

```Ruby
gemspec
source 'internal-gem-server' do
  gem 'b'
end
```

**Comment by indirect** [comment]
@grosser don't use `gemspec` in that case. the gem spec shortcut is only for the simple case where all gems are public.

**Comment by grosser** [comment]
yeah that works ... but I'd love to not have to repeat all my other gems :)

**Comment by segiddins** [comment]
`gem 'Gemname', path: '.'` should also work :)

**Comment by indirect** [comment]
What @segiddins said. :) The `gemspec` shortcut acts like you _explicitly_ listed all the deps in your Gemfile, while `path .` acts like you didn't.

**Comment by LynnCo** [comment]
There's a lot going on with this issue, and I'm not sure if the original problem (ie. ``Your Gemfile lists the gem X more than once.`) is still relevant? If it is, let us know and we'll re-open this (or preferably create a new issue), but for now I'm closing
