### ISSUE TITLE
Bundler fails to load all rubygems plugins

### ISSUE THREAD

**Issue by zebardy** [bundler/bundler#2824]
When running with GEM_HOME set to a location and a rubygem plugin installed to that location the gem command will load the plugin, but bundler will not. 

This is because bundler calls Gem.load_env_plugins (in bundler::CLI) but not Gem.load_plugins, rubygems calls both (in rubygems/gem_runner.rb). The simple solution is to add a Gem.load_plugins call along side the Gem.load_env_plugins call in bundler::CLI. A better solution (although a far bigger job) would be to move all interaction with the rubygems libraries to Bundler::RubygemsIntegration and have it initialize the rubygems libs appropriately for everything. This would simplify things greatly, but I'd rather have some feedback before attempting the bigger change.

**Comment by LynnCo** [comment]
Might be good to resurrect this once we start working on 3.0
