### ISSUE TITLE
Big gems from git hang during every install doing... something

### ISSUE THREAD

**Issue by indirect** [bundler/bundler#2846]

**Comment by segiddins** [comment]
@indirect have any recollection what a repro case for this was?

**Comment by indirect** [comment]
Sadly it was all private git repos. :/ The one I ran into contained 10,000 text files in various directories, and took _forever_. Something like 10s every time you ran `bundle install`, even though it was already installed.

**Comment by bf4** [comment]
fwiw, ref https://github.com/thoughtbot/suspenders/pull/497 always be `bundle check || bundle install`

**Comment by bf4** [comment]
possibility, recursively shelling out to git in all dependencies? ... a la https://github.com/bundler/bundler/issues/1043#issuecomment-6944571 and http://tenderlovemaking.com/2011/12/05/profiling-rails-startup-with-dtrace.html
