### ISSUE TITLE
Run Travis tests on an in-memory file system

### ISSUE THREAD

**Issue by indirect** [bundler/bundler#2865]
/cc @bleything

**Comment by segiddins** [comment]
@indirect is this actually something we have a prayer's chance of doing? Given `RSpec.current_example` is thread-safe, we could use it to allow parallel example execution, I supposer?

**Comment by RochesterinNYC** [comment]
There are gems for in-memory file systems intended for testing purposes (ex. https://github.com/simonc/memfs). Haven't used any personally so not sure what the canonical or best solution is.

Having parallel tests that are each safely isolated would be amazing though. Though I will note that CodeClimate and similar analysis engines often don't do too well with test coverage and parallel rspecs or similar mechanisms.

**Comment by indirect** [comment]
@segiddins theoretically Travis provides a ramdisk on every machine specifically in case you would like to do this. I remember trying it once, seeing that not every single test passed, and then not having time to investigate further. If we can make it work, it would theoretically increase the speed of the tests by... a lot.

**Comment by indirect** [comment]
@RochesterinNYC we already don't get good coverage reports on our integration tests, and those are the ones that would be sped up by parallel execution and/or ramdisks… I'd be happy with either one, and ecstatic if we can pull off both.

**Comment by segiddins** [comment]
@indirect I couldn't find any docs for Travis having a ramdisk

**Comment by LynnCo** [comment]
*moves to backlog*

**Comment by segiddins** [comment]
I think we can close this as infeasible as long as we have mostly integration specs

**Comment by indirect** [comment]
Every Travis VM ships with a ramdisk mounted at (iirc) `/var/ramfs`. It will be at least 512MB, which I'm not sure about being large enough for our tests or not. Worth trying, because it seems like it would speed up our tests by a _huge_ amount. Integration tests need fast IO.
