### ISSUE TITLE
bundle outdated --strict forgets where a git repo's current position is

### ISSUE THREAD

**Issue by modosc** [bundler/bundler#2887]
(originally from https://github.com/bundler/bundler/issues/2799#issuecomment-34947540)

    dbundle --version
    Bundler version 1.6.0.pre.2

 if i have a gem with a git url:

    gem 'formatted_rails_logger', :git => 'https://github.com/jrochkind/formatted_rails_logger'

    GIT
      remote: https://github.com/jrochkind/formatted_rails_logger
      revision: 291293afa85a8b177cbfdde62983964d34b1bab2
      specs:
        formatted_rails_logger (0.3.0)
          rails (~> 3.2.0)

when i run bundle outdated --strict i get this output:

    Outdated gems included in the bundle:
      * formatted_rails_logger (0.3.0 291293a > 0.3.0)

when of course 291293a is the version i currently have installed. this happens with gems that have git urls with or without a version.

**Comment by agis-** [comment]
@modosc I couldn't reproduce the issue. Can you provide detailed steps or maybe check if this issue is also present in the latest bundler versions?

**Comment by agis-** [comment]
Closing this due to lack of feedback. Feel free to share more info and we'll happily reopen.
