### ISSUE TITLE
Bundler sometimes fails to detect that it is running on jruby

### ISSUE THREAD

**Issue by tobsch** [bundler/bundler#2890]
Hi there,

I have a bit of a strange issues that happens for years now on different computers in our company:

We're using buildr as build tool and jRuby as ruby implementation. Buildr is available in two versions:
- one jRuby (-java) version which uses the native Java-Support
- one MRI version which depends on RJB as java bridge

RJB comes with a native extension and fails to install on jRuby.
It sometimes happens that bundler "thinks" it is on MRI when it really is on jRuby and tries to install the normal MRI-Version.
Sometimes means, that it is hard to reproduce and most times, we where able to solve it through installing a fixed (older) version of buildr?
Is this some caching issue?
I'm not sure if it is on the bundler or the rubygems side.

Best,

Tobias

**Comment by anoduck** [comment]
Thanks, for the insight...and some laughter. i.e. ... "just stop...problem solved".
