### ISSUE TITLE
bundler doesn't recognize Windows platform

### ISSUE THREAD

**Issue by mdesantis** [bundler/bundler#2910]
I'm using Ruby 2.0.0 p451 x64 (from http://rubyinstaller.org) on Windows 7 64bit, and bundler 1.5.3 and 1.6.0.rc.

I have a Gemfile like this:

```ruby
source 'https://rubygems.org'
gem 'win32-dir', platforms: :mswin
```

When I run `bundle install` the `win32-dir` doesn't get picked for installation:
```
> bundle install
DL is deprecated, please use Fiddle
Fetching gem metadata from https://rubygems.org/..........
Fetching additional metadata from https://rubygems.org/..
Resolving dependencies...
Using bundler 1.6.0.rc
Your bundle is complete!
Use `bundle show [gemname]` to see where a bundled gem is installed.
```

It is confirmed by `bundle show`:

```
> bundle show
DL is deprecated, please use Fiddle
Gems included by the bundle:
  * bundler (1.6.0.rc)
```

And confirmed by the fact that `require 'win32/dir'` doesn't work.

This is the generated `Gemfile.lock`:

```
GEM
  remote: https://rubygems.org/
  specs:

PLATFORMS
  x64-mingw32

DEPENDENCIES
  win32-dir
```

**Comment by rgb-one** [comment]
I made one amendment to your reproduction script, ie. I replaced `mingw` with `x64_mingw` and it works now. This is pretty old so maybe the issue got fixed since this was posted, or maybe the change I made did it, I don't know.
