### ISSUE TITLE
Stack level too deep running binstubed rspec

### ISSUE THREAD

**Issue by waiting-for-dev** [bundler/bundler#2928]
When running binstubed `rspec` I get:

```
/home/marc/.rbenv/versions/2.1.1/lib/ruby/2.1.0/forwardable.rb:186: stack level too deep (SystemStackError)
```

It would seem it is related to #2203, but I think it isn't because I'm not using `rvm` nor `rubygems-bundler`. I'm using `rbenv` but, in fact, I can reproduce without using it it, just using system ruby.

It seems more related to one month old wayneeseguin/rvm#2619 issue opened in `rvm` repository and closed as not related to them.

If I run `ruby -wdS bin/rspec` [I get this output](https://gist.github.com/waiting-for-dev/9663649)

Following it is the input of `bundle env`:

```
Bundler 1.5.3
Ruby 2.1.1 (2014-02-24 patchlevel 76) [x86_64-linux]
Rubygems 2.2.2
GEM_HOME 


Gemfile
source 'https://rubygems.org'

ruby File.read('.ruby-version').strip

# Specify your gem's dependencies in front_matter_parser.gemspec
gemspec


Gemfile.lock
PATH
  remote: .
  specs:
    front_matter_parser (0.0.1)

GEM
  remote: https://rubygems.org/
  specs:
    diff-lcs (1.2.5)
    rake (10.1.1)
    rspec (2.14.1)
      rspec-core (~> 2.14.0)
      rspec-expectations (~> 2.14.0)
      rspec-mocks (~> 2.14.0)
    rspec-core (2.14.8)
    rspec-expectations (2.14.5)
      diff-lcs (>= 1.1.3, < 2.0)
    rspec-mocks (2.14.6)

PLATFORMS
  ruby

DEPENDENCIES
  bundler (~> 1.5, < 1.6)
  front_matter_parser!
  rake (~> 10.1)
  rspec (~> 2.14)
```

**Comment by zedtux** [comment]
`bundle exec gem pristine rspec-core` saved my day ! Thank you @indirect.
