### ISSUE TITLE
Print warning when bundler is run by root

### ISSUE THREAD

**Issue by indirect** [bundler/bundler#2936]
Running `sudo bundle install` can cause huge and cascading problems for users trying to install gems on OS X into the system gems. We should print a warning and explain that Bundler will prompt for sudo if it's needed. We should also warn people that `sudo bundle` will break git gems, because they have to be writable by the user that Bundler runs as.

**Comment by assarbad** [comment]
Just wondering. I am not a Ruby buff, but can't you check the equivalent of running `uname -s` on the shell against a value of `"Darwin"` and only in that case issue the warning?

Thanks for reading.

[This StackOverflow](http://stackoverflow.com/a/34318529) post brought me here.

**Comment by ioquatix** [comment]
I'm using bundler to install some deployment tools on linux VPSs which need to be installed preferably as root (don't have sudo by default). Is there some way to ignore this case?

**Comment by colby-swandale** [comment]
@ioquatix There is a config option `silence_root_warning` or ENV var `BUNDLE_SILENCE_ROOT_WARNING` that will silence the sudo warning.
