### ISSUE TITLE
Ruby engine gem won't work unless Rails is required?

### ISSUE THREAD

**Issue by TrevorHinesley** [bundler/bundler#2943]
I have a local gem that I'm making called `abracadabra`, and `lib/abracadabra.rb` looks like this:

``` ruby
require "abracadabra/version"
require "abracadabra/engine"
```

But that doesn't work unless I add `require "rails"`. The error I get in irb is:

`NameError: uninitialized constant Rails`

And here is lib/abracadabra/engine.rb:

``` ruby
module Abracadabra
  class Engine < ::Rails::Engine
    initializer 'abracadabra.initialize' do
      ActiveSupport.on_load(:action_view) do
        include Abracadabra::ViewHelpers
      end
    end
  end
end
```

Am I doing something wrong?

**Comment by vfonic** [comment]
@TrevorHinesley do you remember what fixed this issue? I'm having the same problem.

**Comment by AtulKsol** [comment]
@TrevorHinesley and @vfonic Are you able to fix the issue?
Actually I'm also doing this in my engine.rb- class Engine < Rails::Engine
but its throwing me an error.

**Comment by vfonic** [comment]
@AtulKsol be careful that, when building Rails engine gem, you'd want to make rails a dependency, not only dev dependency.

I'm on phone, can't show example now, but hope you understand it.
spec.add_dependency...

**Comment by TrevorHinesley** [comment]
@AtulKsol @vfonic check out my gem here to see how I fixed it: https://github.com/TrevorHinesley/abracadabra

**Comment by AtulKsol** [comment]
Thanks @vfonic , though I've already added `rails` to dependency not only development. ;-) :+1: 
@TrevorHinesley I'll check your gem Abracadarba :)
