### ISSUE TITLE
Remove ruby version check from "bundle exec"?

### ISSUE THREAD

**Issue by nirvdrum** [bundler/bundler#2952]
This is a continuation to #2951.  Is there any reason to do a Ruby version check when running "bundle exec" at all?  As far as I can tell there's two situations:

* Running a command that does load the Gemfile, such as "bundle exec rails c"
* Running a command that doesn't load the Gemfile at all, such as "bundle exec ruby -v"

I realize I'm stating the obvious there.  But in the former case, the Ruby version check will be performed by the subcommand anyway.  As of today, it's effectively being run twice.  In the latter case, where the Gemfile isn't being loaded, you wouldn't see the error you see today, but does that really matter?  Bundler isn't being used for anything other than a command dispatcher in that case.

**Comment by segiddins** [comment]
@indirect are those spec failures OK?
