### ISSUE TITLE
resolver can't deal effectively with old Ruby versions

### ISSUE THREAD

**Issue by aspiers** [bundler/bundler#2965]
[Apologies if this is a duplicate, but I heard that [as of bundler 1.6 all resolver bugs are supposed to be fixed](https://github.com/bundler/bundler/issues/2437#issuecomment-39439061), and when I searched the issues for `resolver` it found 151 closed and 2 open, neither of which relate to this report.]

If I install Ruby 1.8.7 via `rvm`, and then create a fresh `Gemfile`:

```
source 'https://rubygems.org'
gem 'guard'
```

then I get the following:

```
$ bundle
Fetching gem metadata from https://rubygems.org/...........
Fetching additional metadata from https://rubygems.org/..
Resolving dependencies...
Using timers 1.1.0

Gem::InstallError: celluloid requires Ruby version >= 1.9.2.
An error occurred while installing celluloid (0.15.2), and Bundler cannot continue.
Make sure that `gem install celluloid -v '0.15.2'` succeeds before bundling.
```

AFAICS this is because `guard` requires `listen`, and [newer versions of `listen` require `celluloid`](https://github.com/guard/listen/blob/master/listen.gemspec) which [requires Ruby >= 1.9.2](https://github.com/celluloid/celluloid/blob/master/celluloid.gemspec), but unfortunately bundler's output does not make this at all obvious.  The only way I have found to debug this is to re-run bundler on a newer Ruby and then manually inspect the resulting `Gemfile.lock`, and even then presumably there is no guarantee that a `Gemfile.lock` generated on a newer Ruby can accurately represent the incomplete dependency tree which caused the above error on 1.8.7.

Assuming my analysis above is correct, why did bundler even mention celluloid?  Shouldn't it have noticed that [`listen` requires 1.9.3](https://github.com/guard/listen/blob/master/listen.gemspec#L21) even before trying to solve `listen`'s gem dependencies?  So at worst I would have expected it to output:

```
Gem::InstallError: listen requires Ruby version >= 1.9.3.
An error occurred while installing listen (2.7.1), and Bundler cannot continue.
Make sure that `gem install listen -v '2.7.1'` succeeds before bundling.
```

and by not prematurely iterating further down the dependency tree, it would have been easier to debug.

At best, there would be some way of getting bundler to dump the partial dependency tree it was using at the point the error was generated.  For example, it could offer an option to dump `Gemfile.lock.broken` or similar.

However, whilst it would be great if bundler made it easier to debug this kind of scenario, that's not the main issue I want to report here (let me know if you would prefer a separate issue for that).

**The main issue is that bundler's resolver can't figure out for itself that an older version of `listen` would be able to satisfy the dependencies.**  If I add the following hint to my `Gemfile`:

```
gem 'listen', '< 2.0'
```

then bundler successfully resolves all dependencies:

```
Fetching gem metadata from https://rubygems.org/............
Fetching additional metadata from https://rubygems.org/..
Resolving dependencies...
Installing ffi 1.9.3
Installing rb-fsevent 0.9.4
Installing rb-inotify 0.9.3
Installing rb-kqueue 0.2.2
Installing listen 1.3.1
Using bundler 1.6.1
Your bundle is complete!
Use `bundle show [gemname]` to see where a bundled gem is installed.
```

but it really should not need the hint, because it already has the necessary metadata available to figure this out.

BTW this is not an isolated case.  Another example is attempting to install `chefspec`.  Again, even though [`chefspec`'s metadata clearly states Ruby >= 1.9 is required](https://github.com/sethvargo/chefspec/blob/master/chefspec.gemspec#L27), bundler attempts to install it, only failing when it reaches the `fauxhai` leaf in the dependency tree.

**Comment by Jerskouille** [comment]
Hi there, three years later I'm still having those issues.
I'm stuck with a broken build and the unability to know which gem is dependent on the failing one in this process.

How should I proceed ? `bundle install --verbose` is not helping, bundling on a newer platform doesn't pull the specific gem in my dependency tree, I'm basically stuck.

**Comment by segiddins** [comment]
@Jerskouille please open a new issue with the information requested in https://github.com/bundler/bundler/blob/master/doc/contributing/ISSUES.md
