### ISSUE TITLE
ask for permission before using password-less sudo

### ISSUE THREAD

**Issue by aspiers** [bundler/bundler#3006]
I've been using bundler for years already in various scenarios (and BTW it's **awesome** ;-) but somehow this is the first time I noticed that if I am using the system-wide `/usr/bin/ruby` (e.g. `rvm use system`) and I have `sudoers` configured to allow running arbitrary commands as `root`, if I do `bundle install` as non-root, it will happily take advantage of that and start running a load of `sudo` commands to install gems system-wide into `/usr/lib64`.  It's of course possible I've misunderstood something, but this was a big WTF moment for me, since now my nice clean rpm-managed root filesystem was messed up with no warning at all.

I realise that by default, bundler tries installs gems to the same location as `gem install`, and that in the above case, that means system-wide.  I realise that there are totally valid scenarios where that is the required behaviour (e.g. since [supporting half-and-half system+user setups is a nightmare](https://github.com/bundler/bundler/issues/946#issuecomment-12483423)), and I'm totally OK with that.  I'm also OK with the general idea of bundler achieving that via `sudo`.  *However*, in the `NOPASSWD sudoers` case, this happens without any warning, and IMHO that's definitely not cool.  It's a bit like leaving your front door unlocked - yes, you are probably asking for trouble, but you still really hope that people will have the courtesy to knock before they come in ;-)

I have read #710, #890, #946 etc. and I'm aware that setting `GEM_HOME` to a writable location will prevent this.  But that's a bit like someone telling you "remember to lock the door when you leave!"  Yes most of the time you'll remember, but occasionally you'll screw up (e.g. a bug in your shell start-up scripts, or you unset it for some reason and forgot to reset it later) - and on those occasions bundler should still behave like the courteous guest who remembers to knock.

So I would suggest:

*   Before using `sudo`, bundler should do `sudo -l` to check whether it is allowed to do stuff without first prompting for the user password.
*   If `sudo -l` shows that a password is required, carry on with the existing behaviour, since `sudo` will naturally ensure that bundler is a polite guest.
*   Otherwise, *by default* prompt the user once per bundler run, asking for permission to use `sudo`.  I suggest the following prompt text:

```
bundler needs to use sudo in order to install gems to $GEM_HOME,
and has detected that this user is allowed to use `sudo` without
any password prompts (`NOPASSWD` in /etc/sudoers).

Are you happy for bundler to use sudo?

    n - no, quit (default)
    y - yes, allow bundler to use sudo just for this run
    A - always, configure bundler to never again ask permission,
        via: bundle config sudo.passwordless always
    N - never, configure bundler to never again attempt to use
        password-less sudo, via: 
        bundle config sudo.passwordless always

Enter your choice [nyAN] ?
```

So the `sudo.passwordless` option would default to `ask`, and in this case, when STDIN is not a tty, it would default to aborting without using `sudo` (since it would have run out of ways to get permission from the user).

Hope that makes sense.  Thanks a lot for listening!

**Comment by bard** [comment]
This just bit me as well, while the documentation explicitly claim it won't happen:

```
bundle-install(1)
By default, bundler installs gems to the same location as gem install.
```

When I run `gem install` as a user, it installs to `~/.gem`.

I guess this comes from a combination of circumstances (maybe `gem install` installs to user directory because it can't install to system, and bundler expects `sudo` also to mean "prompt the user for password"), however the net result is that bundler breaks the contract.

I think @aspiers 's suggestion on how to handle it is sound.

**Comment by LynnCo** [comment]
Closing in favor of https://github.com/bundler/bundler/issues/2565

**Comment by LynnCo** [comment]
Correction! This is a better issue since that one is explicitly about `--user-install`
