### ISSUE TITLE
Documentation contains incorrect command

### ISSUE THREAD

**Issue by scragar** [bundler/bundler#3018]
If you visit the deploying page: http://bundler.io/v1.6/deploying.html
You'll see that the first command it writes is:

    echo ".bundle\n" >> .gitignore

This command is incorrect, echo by default will not convert escape chars like `\n` into new lines. It will with the -e flag, meaning

    echo -e ".bundle\n" >> .gitignore

will work as intended.

PS: I couldn't find any way to report this bug against the documentation, I hope by writing it here it will be passed on.

**Comment by TimMoore** [comment]
This has been fixed on the site to no longer include the `\n`
