### ISSUE TITLE
`bundle update` appears to try to install wrong platform gem

### ISSUE THREAD

**Issue by rf-** [bundler/bundler#3023]
Basically the situation is:
* The existing Gemfile has a dependency on `pry`
* Pry has Windows platform gems which depend on `win32console`
* On a Mac, if I change the Gemfile to include `gem 'pry', '0.10.0.pre2'` and then run `bundle update pry`, it tries to install `win32console` and dies

Here's a repro script and output: https://gist.github.com/6c557396599562731032

Actually, it looks like running `bundle update` or `bundle update pry` breaks even if 0.10.0.pre2 has already successfully installed with `bundle install`.

**Comment by rgb-one** [comment]
This issue seems sorted in `pry 0.10.0.pre3`. @indirect , if you still have queries regarding universal gems open a new issue.
