### ISSUE TITLE
Installing local gems requires write permissions

### ISSUE THREAD

**Issue by BCCRiskAdvisory** [bundler/bundler#3048]
When using a local gem,  the bundler installation process writes a .gem file to that directory, before moving it (to GEM_HOME?). This means that you cannot install a gem from a location that you do not have write access to. 

Wouldn't it make more sense to write the .gem file directly to it's final location? I don't want other users on my system to have write access to the gem dir, but they should be able to use the gem.

**Comment by agis-** [comment]
@BCCRiskAdvisory I couldn't reproduce the issue in 1.10.6 following the steps you've described. If you still see the error in the latest versions, let us know and we'll reopen the issue. Thanks!
