### ISSUE TITLE
Local git can break bundle install

### ISSUE THREAD

**Issue by indirect** [bundler/bundler#3054]
1. Use git locals to lock to a dependency commit after the latest commit available from the remote.
2. Bundle on another machine
3. Notice that machine can't bundle successfully until the git cache is deleted AND the new dependency commit is pushed

**Comment by segiddins** [comment]
@indirect want to come up with a repro script for this?

**Comment by segiddins** [comment]
Closing because I think this is fixed.

**Comment by indirect** [comment]
I think it is fixed, thanks!
