### ISSUE TITLE
Universal gems do not match x64-mingw32 platform

### ISSUE THREAD

**Issue by joshcooper** [bundler/bundler#3066]
I have a Gemfile:

<pre>
source "https://rubygems.org"
gem 'windows-api'
</pre>

Currently, `windows-api` is at version [`0.4.2`](https://rubygems.org/gems/windows-api/versions/0.4.2). It has a dependency on [`win32-api`](https://github.com/djberg96/windows-api/blob/windows-api-0.4.2/windows-api.gemspec#L17).

In ruby 1.9.3p374, bundler successfully resolves the most recent version of the gem, which happens to be [`win32-api-1.5.1-universal-mingw32`](https://rubygems.org/gems/win32-api/versions/1.5.1-universal-mingw32), containing precompiled binaries for both x86 and x64. 

<pre>
C:\work\foo>bundle install --path .bundle
...
Activated:
  windows-api (0.4.2)
Requirements:
  win32-api (>= 1.4.5) x86-mingw32
Attempting:
  win32-api (>= 1.4.5) x86-mingw32
  Activating: win32-api (1.5.1)
    * windows-api (>= 0)
    * win32-api (>= 1.4.5)
    Dependencies

Installing win32-api 1.5.1
Installing windows-api 0.4.2
Using bundler 1.6.2
</pre>

However, on ruby 2.0.0p481 x64, the universal gem does not match, and bundler falls back to [`win32-api-1.4.8`](https://rubygems.org/gems/win32-api/versions/1.4.8), which is a `ruby` version that requires the DevKit to be installed to compile the native extension.

<pre>
C:\work\foo>ruby --version
ruby 2.0.0p481 (2014-05-08) [x64-mingw32]
C:\work\foo>gem --version
2.0.14
C:\work\foo>bundle --version
Bundler version 1.6.2
C:\work\foo>bundle install --path .bundle
...
Activated:
  windows-api (0.4.2)
Requirements:
  win32-api (>= 1.4.5) x64-mingw32
Attempting:
  win32-api (>= 1.4.5) x64-mingw32
  Activating: win32-api (1.4.8)
    * windows-api (>= 0)
    * win32-api (>= 1.4.5)
    Dependencies

Gem::InstallError: The 'win32-api' native gem requires installed build tools.
</pre>

However, `gem install windows-api` on ruby 2.0.0 x64 correctly pulls in the `win32-api-1.5.1-universal-mingw32` gem as expected:

<pre>
C:\work\foo>ruby --version
ruby 2.0.0p481 (2014-05-08) [x64-mingw32]
C:\work\foo>gem install windows-api
Fetching: win32-api-1.5.1-universal-mingw32.gem (100%)
Successfully installed win32-api-1.5.1-universal-mingw32
Fetching: windows-api-0.4.2.gem (100%)
Successfully installed windows-api-0.4.2
</pre>

There seems to be an issue with how bundler compares the current `x64-mingw32` platform against possible matches. I would expect it to prefer an exact match, e.g. `x64-mingw32`, but fall back to `universal-mingw32` before trying earlier versions.

**Comment by indirect** [comment]
This is fixed in 1.9.3
