### ISSUE TITLE
Bundler.require breaks twilio-ruby gem, I want to help fix it.

### ISSUE THREAD

**Issue by kinvolved1** [bundler/bundler#3072]
Hello, I don't know if this is the right place to put this but I'd like to help you debug the problem if that's ok.

Using Bundler.require(:default, Rails.env) with the twilio-ruby gems destroys the functionality of the gem, all the class methods don't exist.

I've got a bit of a rant going on over here: http://stackoverflow.com/questions/24297635/twilio-library-doesnt-work-in-rails-but-works-outside-rails

I've narrowed it down to the function call and I can't imagine what it's doing, but because I'm a newbie to Ruby/Rails I'm not sure where to go from here. Removing Bundler.require and requiring everything *by hand* resolves the problem for me. I'd rather avoid fundamentally changing the code base I have inherited. 

How can I get you more information?

**Comment by agis-** [comment]
Closing this due to lack of feedback.

@kinvolved1 Feel free to share more info (eg. reproduction steps) and I'll happily reopen :)
