### ISSUE TITLE
outdated has problems that install does not

### ISSUE THREAD

**Issue by jjb** [bundler/bundler#3088]
when I run `bundle outdated`, i get

```
Fetching source index from https://rubygems.org/
Resolving dependencies....
Bundler could not find compatible versions for gem "sass":
  In Gemfile:
    sass (~> 3.2.0) ruby

    sass (3.3.0)
```

This is surprising because nothing in my Gemfile or Gemfile.lock specifies or even allows sass 3.3. Some initial research suggests that this might be caused by one of the gems I'm including erroneously including its own Gemfile.lock, or something like that.

But what is strange and what I'm writing this ticket about is that I do not have this problem with any other bundler commands (install, exec). Bundler seems to think my Gemfile and Gemfile.lock are perfectly healthy and usable when installing gems or firing up the environment. But for some reason it can't get past this incompatibility when checking for outdated gems.

Any ideas?

I'll be happy to share my Gemfile and Gemfile.lock privately if anyone is interested.

**Comment by agis-** [comment]
So is this still an issue? /cc @jjb @indirect

**Comment by jjb** [comment]
I haven't experienced it myself for many months.

**Comment by indirect** [comment]
IIRC this was a bug in Molinillo that has been fixed for a while.

**Comment by agis-** [comment]
Cool!

@segiddins Can you confirm what @indirect said? If so, we can close this.

**Comment by segiddins** [comment]
uuuuum so this bug actually predates bundler using Molinillo :P

I'm good closing this though, we can always re-open if there's another gemfile that comes around
