### ISSUE TITLE
does not install latest version of gems dependencies, installs older instead

### ISSUE THREAD

**Issue by jrochkind** [bundler/bundler#3089]
bundler 1.6.3

I have isolated to this reproduction Gemfile:

```
source "https://rubygems.org"

gem "rails", ">= 3.2.12", "< 4.1"
gem "sass-rails"
```

I would expect that to install the latest Rails < 4.1 available: 4.0.8

Instead it installs rails 4.0.5. [Gemfile.lock](https://gist.github.com/jrochkind/d7b461e646e76fd75789)

That would make sense only if there were for some reason no `sass-rails` compatible with 4.0.8, if the latest rails a sass-rails could work with were rails 4.0.5.

But that doesn't seem to be the case, and it installed `sass-rails 4.0.1` -- which isn't the latest sass-rails either, but is still apparently compatible with rails 4.0.8.  

So why did it choose to install an older rails and an older sass-rails? 

If we choose to force the issue for testing purposes:

```
source "https://rubygems.org"

gem "rails", ">= 3.2.12", "< 4.1", "= 4.0.8"
gem "sass-rails"
```

Then it is perfectly happy to install Rails 4.0.8 -- this time with sass-rails 4.0.3, the most recent sass-rails too.  [Gemfile.lock](https://gist.github.com/jrochkind/fe7e4881b9198285d08e)

In the first case, rails 4.0.8 and sass-rails 4.0.3 would still seem to be the most recent gems that satisfy the dependencies expressed. Why is bundler installing older versions instead? Is this a bug?

**Comment by faustoct** [comment]
is that fixed? still getting older versions after `gem update`
