### ISSUE TITLE
Gemfile is evaluated twice when a lockfile exists

### ISSUE THREAD

**Issue by grosser** [bundler/bundler#3096]
```Ruby
#Gemfile
puts "WUT"
```

no Gemfile.lock -> WUT
with Gemfile.lock -> WUTWUT

tracked it down to this guy: https://github.com/bundler/bundler/blob/master/lib/bundler/installer.rb#L63-L71

I guess it should reuse the definition from https://github.com/bundler/bundler/blob/master/lib/bundler/cli/install.rb#L77-L78

not only `bundle install` also bundle exec ruby -e 1 evaluates the Gemfile twice, so basically every bundle run could save a few miliseconds

**Comment by segiddins** [comment]
So I took a look, and the second evaluation happens at https://github.com/bundler/bundler/blob/master/lib/bundler/installer.rb#L69, where it's checked whether we need to do a `local` install.

**Comment by segiddins** [comment]
I have a fix for this that I'll PR in a minute

**Comment by LynnCo** [comment]
If anyone wants to help with segiddins's PR for this, that's here -> https://github.com/bundler/bundler/pull/4417

**Comment by segiddins** [comment]
This is now fixed on 2.0
