### ISSUE TITLE
'bundler package --all' fails to find git-sourced gem if Bundler.setup is called twice.

### ISSUE THREAD

**Issue by abargnesi** [bundler/bundler#3100]
Possibly related to #3009.

Given the Gemfile

```ruby
source 'https://rubygems.org'

gem 'bel', :git => 'https://github.com/OpenBEL/bel.rb.git'
gem 'sinatra'
```

If you run something like:

```ruby
require 'rubygems'
require 'bundler'
Bundler.setup(:development)

# require a development gem dependencies
require 'term/ansicolor'

# This call exits with status 7.
# Message: Could not find bel-0.3.0.gem for installation
system('bundle package --all')
```

The ``bundle package --all`` is unable to locate the git-sourced gem.

Bundler.setup sets ``RUBYOPT="-rbundler/setup"`` which the ``system`` calls picks up. This seems to be the cause of the failure.

Expanded example at https://gist.github.com/abargnesi/1ac06c31e76296f0df40

@TimMoore recommended wrapping the call in ``Bundler.with_clean_env`` like:

```ruby
Bundler.with_clean_env {
    system("bundle package --all")
}
```

This will unset RUBYOPT and allow the git-sourced gem to be saved to the vendor/cache.

Shouldn't Bundler.setup be an idempotent action?

**Comment by agis-** [comment]
Fixed by #3497.
