### ISSUE TITLE
bundle install  could not find gem ( .....   ) at local machine

### ISSUE THREAD

**Issue by GPnow** [bundler/bundler#3152]
i am a ROR noob,i was following a tutorial,i am using bundler 1.7.0,ruby 2.1.2,rails 4.1.4

here is my Gemfile
source 'https://rubygems.org'
ruby '2.1.2'
gem 'rails', '4.1.4'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
group:doc do
gem 'sdoc', '~> 0.4.0',require:false
end  
gem 'spring'  
group :development,:test do 
     gem 'sqlite3'
     gem 'rspec-rails','2.13.1'
end
group :test do 
   gem 'selenium--webdriver','2.35.1'
   gem 'capybara','2.1.0'
end
group :production do 
   gem 'pg','0.15.1'
   gem 'rails_12factor','0.0.2'
end

after this i was supposed to do ---> ral@ubuntu:~/rails_project/sample_app$ bundle install --without production
which gave this error
ral@ubuntu:~/rails_project/sample_app$ bundle install --without production 
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Could not find gem 'selenium--webdriver (= 2.35.1) ruby' in the gems available on this machine.

so i did gem install selenium--webdriver 2.35.1

again doing bundle install --without production i got the same error ,but got a new error when i did it using local,complaining it could not find some other gem,and this went on and on,i dont want to install these gem globally.
ral@ubuntu:~/rails_project/sample_app$ gem list

**\* LOCAL GEMS ***

actionmailer (4.1.4)
actionpack (4.1.4)
actionview (4.1.4)
activemodel (4.1.4)
activerecord (4.1.4)
activesupport (4.1.4)
addressable (2.3.6)
arel (5.0.1.20140414130214)
bigdecimal (1.2.4)
builder (3.2.2)
bundler (1.7.0, 1.6.5)
bundler-unload (1.0.2)
childprocess (0.5.3)
coffee-rails (4.0.1)
coffee-script (2.3.0)
coffee-script-source (1.7.1)
erubis (2.7.0)
excon (0.39.5)
execjs (2.2.1)
executable-hooks (1.3.2)
ffi (1.9.3)
gem-wrappers (1.2.5)
heroku (3.10.1)
heroku-api (0.3.19)
hike (1.2.3)
i18n (0.6.11)
io-console (0.4.2)
jbuilder (2.1.3)
jquery-rails (3.1.1)
json (1.8.1)
launchy (2.4.2)
mail (2.5.4)
mime-types (1.25.1)
minitest (5.4.0, 4.7.5)
multi_json (1.10.1)
netrc (0.7.7)
polyglot (0.3.5)
psych (2.0.5)
rack (1.5.2)
rack-test (0.6.2)
rails (4.1.4)
railties (4.1.4)
rake (10.3.2, 10.1.0)
rdoc (4.1.1, 4.1.0)
rest-client (1.6.7)
rubygems-bundler (1.4.4)
rubygems-update (2.4.1)
rubyzip (1.1.6, 0.9.9)
rvm (1.11.3.9)
sass (3.3.14, 3.2.19, 3.2.0)
sass-rails (4.0.3)
sdoc (0.4.1)
selenium-webdriver (2.35.1)
spring (1.1.3)
sprockets (2.12.1, 2.11.0)
sprockets-rails (2.1.3)
sqlite3 (1.3.9)
test-unit (2.1.2.0)
thor (0.19.1)
thread_safe (0.3.4)
tilt (1.4.1)
treetop (1.4.15)
turbolinks (2.3.0, 2.2.3, 2.2.2)
tzinfo (1.2.2)
uglifier (2.5.3)
websocket (1.0.7)

**Comment by developer-rameshraj** [comment]
- 

`
# 
> **# 1.** 

`
