### ISSUE TITLE
Bundler leaves empty folders after running the installation

### ISSUE THREAD

**Issue by snitko** [bundler/bundler#3156]
So, each time I run `bundle install` it leaves those empty folders called like this:

```
bundler20140825-12408-1nteweu
```

What are they and how do I tell bundler to delete them automatically?

**Comment by Nickk4** [comment]
I seem to be having the same issue. See for screen shot: http://s000.tinyupload.com/?file_id=05598539612585221106. I'm new to programming so don't really feel confident to follow the instructions on https://github.com/carlhuda/bundler/blob/master/ISSUES.md, where removal of settings is suggested.

**Comment by rgb-one** [comment]
Ah. I have seen this before. It seems you are on Windows. Is that c9.io you are using? That is the only place I have experienced this. Can you post the output of the `bundle env` command?

**Comment by segiddins** [comment]
Also, please double check if this is still happening with Bundler v1.10?

**Comment by rgb-one** [comment]
Just did, it isn't

**Comment by Nickk4** [comment]
I can confirm I use Cloud9. Below the output of `bundle env`. I haven't included bundler in my Gemfile. It seems to be installen based on a rails dependency? When I run `gem dependency -R` the output includes:
`Gem uglifier-2.7.1`
`  bundler (~> 1.3, development)`
What would you recommend me to do (sorry newbie as I am)?

Bundler 1.7.6
Ruby 2.1.5 (2014-11-13 patchlevel 273) [x86_64-linux]
Rubygems 2.4.3
rvm 1.26.9 (1.26.9)
GEM_HOME /usr/local/rvm/gems/ruby-2.1.5
GEM_PATH /usr/local/rvm/gems/ruby-2.1.5:/usr/local/rvm/gems/ruby-2.1.5@global
rubygems-bundler (1.4.4)

Bundler settings
  without
    Set for your local app (/home/ubuntu/workspace/***/.bundle/config): "production"


Gemfile
source 'https://rubygems.org'

ruby                  '2.1.5'
gem 'rails',          '4.2.1'
gem 'bcrypt',         '3.1.10'

gem 'faker',          '1.4.3'

gem 'carrierwave',    '0.10.0'
gem 'mini_magick',    '4.2.4'
gem 'fog',            '1.30.0'
gem 'aws-sdk',        '2.0.45'

gem 'sass-rails',     '5.0.3'
gem 'bootstrap-sass', '3.3.4.1'
gem 'uglifier',       '2.7.1'
gem 'coffee-rails',   '4.1.0'

gem 'wice_grid',      git: 'https://github.com/leikind/wice_grid.git', branch: 'rails3'   # ***** Version '3.4.14' didn't support bootstrap yet: https://github.com/leikind/wice_grid/issues/223. So for now, installed unstable version with bootstrap support.
gem 'bootstrap-datepicker-rails', '1.4.0'

gem 'friendly_id',    '5.1.0'

gem 'jquery-rails',   '4.0.3'
gem 'turbolinks',     '2.5.3'
gem 'jbuilder',       '2.2.16'
gem 'sdoc',           '0.4.1', group: :doc

gem 'pg',             '0.18.2'

group :development, :test do
  gem 'byebug',       '5.0.0'
  gem 'web-console',  '2.1.2'
  gem 'spring',       '1.3.6'
end

group :test do
  gem 'minitest-reporters', '1.0.16'
  gem 'mini_backtrace',     '0.1.3'
  gem 'guard',              '2.12.5'
  gem 'guard-minitest',     '2.4.4'
end

group :production do
  gem 'rails_12factor',     '0.0.3'
  # To use Heroku's HTTP server Puma
  gem 'puma',               '2.11.2'
end

Gemfile.lock
GIT
  remote: https://github.com/leikind/wice_grid.git
  revision: 37ff2bdb5625c70cb83619cc7b2c8dcddfd7472c
  branch: rails3
  specs:
    wice_grid (3.4.14)
      coffee-rails
      kaminari (>= 0.13.0)

GEM
  remote: https://rubygems.org/
  specs:
    CFPropertyList (2.3.1)
    actionmailer (4.2.1)
      actionpack (= 4.2.1)
      actionview (= 4.2.1)
      activejob (= 4.2.1)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 1.0, >= 1.0.5)
    actionpack (4.2.1)
      actionview (= 4.2.1)
      activesupport (= 4.2.1)
      rack (~> 1.6)
      rack-test (~> 0.6.2)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.1)
    actionview (4.2.1)
      activesupport (= 4.2.1)
      builder (~> 3.1)
      erubis (~> 2.7.0)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.1)
    activejob (4.2.1)
      activesupport (= 4.2.1)
      globalid (>= 0.3.0)
    activemodel (4.2.1)
      activesupport (= 4.2.1)
      builder (~> 3.1)
    activerecord (4.2.1)
      activemodel (= 4.2.1)
      activesupport (= 4.2.1)
      arel (~> 6.0)
    activesupport (4.2.1)
      i18n (~> 0.7)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.3, >= 0.3.4)
      tzinfo (~> 1.1)
    ansi (1.5.0)
    arel (6.0.0)
    autoprefixer-rails (5.2.0)
      execjs
      json
    aws-sdk (2.0.45)
      aws-sdk-resources (= 2.0.45)
    aws-sdk-core (2.0.45)
      builder (~> 3.0)
      jmespath (~> 1.0)
      multi_json (~> 1.0)
    aws-sdk-resources (2.0.45)
      aws-sdk-core (= 2.0.45)
    bcrypt (3.1.10)
    binding_of_caller (0.7.2)
      debug_inspector (>= 0.0.1)
    bootstrap-datepicker-rails (1.4.0)
      railties (>= 3.0)
    bootstrap-sass (3.3.4.1)
      autoprefixer-rails (>= 5.0.0.1)
      sass (>= 3.2.19)
    builder (3.2.2)
    byebug (5.0.0)
      columnize (= 0.9.0)
    carrierwave (0.10.0)
      activemodel (>= 3.2.0)
      activesupport (>= 3.2.0)
      json (>= 1.7)
      mime-types (>= 1.16)
    celluloid (0.16.0)
      timers (~> 4.0.0)
    coderay (1.1.0)
    coffee-rails (4.1.0)
      coffee-script (>= 2.2.0)
      railties (>= 4.0.0, < 5.0)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.9.1.1)
    columnize (0.9.0)
    debug_inspector (0.0.2)
    erubis (2.7.0)
    excon (0.45.3)
    execjs (2.5.2)
    faker (1.4.3)
      i18n (~> 0.5)
    ffi (1.9.8)
    fission (0.5.0)
      CFPropertyList (~> 2.2)
    fog (1.30.0)
      fog-atmos
      fog-aws (~> 0.0)
      fog-brightbox (~> 0.4)
      fog-core (~> 1.27, >= 1.27.4)
      fog-ecloud
      fog-google (>= 0.0.2)
      fog-json
      fog-local
      fog-powerdns (>= 0.1.1)
      fog-profitbricks
      fog-radosgw (>= 0.0.2)
      fog-riakcs
      fog-sakuracloud (>= 0.0.4)
      fog-serverlove
      fog-softlayer
      fog-storm_on_demand
      fog-terremark
      fog-vmfusion
      fog-voxel
      fog-xml (~> 0.1.1)
      ipaddress (~> 0.5)
      nokogiri (~> 1.5, >= 1.5.11)
    fog-atmos (0.1.0)
      fog-core
      fog-xml
    fog-aws (0.4.0)
      fog-core (~> 1.27)
      fog-json (~> 1.0)
      fog-xml (~> 0.1)
      ipaddress (~> 0.8)
    fog-brightbox (0.7.1)
      fog-core (~> 1.22)
      fog-json
      inflecto (~> 0.0.2)
    fog-core (1.30.0)
      builder
      excon (~> 0.45)
      formatador (~> 0.2)
      mime-types
      net-scp (~> 1.1)
      net-ssh (>= 2.1.3)
    fog-ecloud (0.1.1)
      fog-core
      fog-xml
    fog-google (0.0.5)
      fog-core
      fog-json
      fog-xml
    fog-json (1.0.1)
      fog-core (~> 1.0)
      multi_json (~> 1.0)
    fog-local (0.2.1)
      fog-core (~> 1.27)
    fog-powerdns (0.1.1)
      fog-core (~> 1.27)
      fog-json (~> 1.0)
      fog-xml (~> 0.1)
    fog-profitbricks (0.0.2)
      fog-core
      fog-xml
      nokogiri
    fog-radosgw (0.0.4)
      fog-core (>= 1.21.0)
      fog-json
      fog-xml (>= 0.0.1)
    fog-riakcs (0.1.0)
      fog-core
      fog-json
      fog-xml
    fog-sakuracloud (1.0.1)
      fog-core
      fog-json
    fog-serverlove (0.1.2)
      fog-core
      fog-json
    fog-softlayer (0.4.6)
      fog-core
      fog-json
    fog-storm_on_demand (0.1.1)
      fog-core
      fog-json
    fog-terremark (0.1.0)
      fog-core
      fog-xml
    fog-vmfusion (0.1.0)
      fission
      fog-core
    fog-voxel (0.1.0)
      fog-core
      fog-xml
    fog-xml (0.1.2)
      fog-core
      nokogiri (~> 1.5, >= 1.5.11)
    formatador (0.2.5)
    friendly_id (5.1.0)
      activerecord (>= 4.0.0)
    globalid (0.3.5)
      activesupport (>= 4.1.0)
    guard (2.12.5)
      formatador (>= 0.2.4)
      listen (~> 2.7)
      lumberjack (~> 1.0)
      nenv (~> 0.1)
      notiffany (~> 0.0)
      pry (>= 0.9.12)
      shellany (~> 0.0)
      thor (>= 0.18.1)
    guard-compat (1.2.1)
    guard-minitest (2.4.4)
      guard-compat (~> 1.2)
      minitest (>= 3.0)
    hitimes (1.2.2)
    i18n (0.7.0)
    inflecto (0.0.2)
    ipaddress (0.8.0)
    jbuilder (2.2.16)
      activesupport (>= 3.0.0, < 5)
      multi_json (~> 1.2)
    jmespath (1.0.2)
      multi_json (~> 1.0)
    jquery-rails (4.0.3)
      rails-dom-testing (~> 1.0)
      railties (>= 4.2.0)
      thor (>= 0.14, < 2.0)
    json (1.8.2)
    kaminari (0.16.3)
      actionpack (>= 3.0.0)
      activesupport (>= 3.0.0)
    listen (2.10.0)
      celluloid (~> 0.16.0)
      rb-fsevent (>= 0.9.3)
      rb-inotify (>= 0.9)
    loofah (2.0.2)
      nokogiri (>= 1.5.9)
    lumberjack (1.0.9)
    mail (2.6.3)
      mime-types (>= 1.16, < 3)
    method_source (0.8.2)
    mime-types (2.6.1)
    mini_backtrace (0.1.3)
      minitest (> 1.2.0)
      rails (>= 2.3.3)
    mini_magick (4.2.4)
    mini_portile (0.6.2)
    minitest (5.7.0)
    minitest-reporters (1.0.16)
      ansi
      builder
      minitest (>= 5.0)
      ruby-progressbar
    multi_json (1.11.0)
    nenv (0.2.0)
    net-scp (1.2.1)
      net-ssh (>= 2.6.5)
    net-ssh (2.9.2)
    nokogiri (1.6.6.2)
      mini_portile (~> 0.6.0)
    notiffany (0.0.6)
      nenv (~> 0.1)
      shellany (~> 0.0)
    pg (0.18.2)
    pry (0.10.1)
      coderay (~> 1.1.0)
      method_source (~> 0.8.1)
      slop (~> 3.4)
    puma (2.11.2)
      rack (>= 1.1, < 2.0)
    rack (1.6.1)
    rack-test (0.6.3)
      rack (>= 1.0)
    rails (4.2.1)
      actionmailer (= 4.2.1)
      actionpack (= 4.2.1)
      actionview (= 4.2.1)
      activejob (= 4.2.1)
      activemodel (= 4.2.1)
      activerecord (= 4.2.1)
      activesupport (= 4.2.1)
      bundler (>= 1.3.0, < 2.0)
      railties (= 4.2.1)
      sprockets-rails
    rails-deprecated_sanitizer (1.0.3)
      activesupport (>= 4.2.0.alpha)
    rails-dom-testing (1.0.6)
      activesupport (>= 4.2.0.beta, < 5.0)
      nokogiri (~> 1.6.0)
      rails-deprecated_sanitizer (>= 1.0.1)
    rails-html-sanitizer (1.0.2)
      loofah (~> 2.0)
    rails_12factor (0.0.3)
      rails_serve_static_assets
      rails_stdout_logging
    rails_serve_static_assets (0.0.4)
    rails_stdout_logging (0.0.3)
    railties (4.2.1)
      actionpack (= 4.2.1)
      activesupport (= 4.2.1)
      rake (>= 0.8.7)
      thor (>= 0.18.1, < 2.0)
    rake (10.4.2)
    rb-fsevent (0.9.5)
    rb-inotify (0.9.5)
      ffi (>= 0.5.0)
    rdoc (4.2.0)
      json (~> 1.4)
    ruby-progressbar (1.7.5)
    sass (3.4.14)
    sass-rails (5.0.3)
      railties (>= 4.0.0, < 5.0)
      sass (~> 3.1)
      sprockets (>= 2.8, < 4.0)
      sprockets-rails (>= 2.0, < 4.0)
      tilt (~> 1.1)
    sdoc (0.4.1)
      json (~> 1.7, >= 1.7.7)
      rdoc (~> 4.0)
    shellany (0.0.1)
    slop (3.6.0)
    spring (1.3.6)
    sprockets (3.1.0)
      rack (~> 1.0)
    sprockets-rails (2.3.1)
      actionpack (>= 3.0)
      activesupport (>= 3.0)
      sprockets (>= 2.8, < 4.0)
    thor (0.19.1)
    thread_safe (0.3.5)
    tilt (1.4.1)
    timers (4.0.1)
      hitimes
    turbolinks (2.5.3)
      coffee-rails
    tzinfo (1.2.2)
      thread_safe (~> 0.1)
    uglifier (2.7.1)
      execjs (>= 0.3.0)
      json (>= 1.8.0)
    web-console (2.1.2)
      activemodel (>= 4.0)
      binding_of_caller (>= 0.7.2)
      railties (>= 4.0)
      sprockets-rails (>= 2.0, < 4.0)

PLATFORMS
  ruby

DEPENDENCIES
  aws-sdk (= 2.0.45)
  bcrypt (= 3.1.10)
  bootstrap-datepicker-rails (= 1.4.0)
  bootstrap-sass (= 3.3.4.1)
  byebug (= 5.0.0)
  carrierwave (= 0.10.0)
  coffee-rails (= 4.1.0)
  faker (= 1.4.3)
  fog (= 1.30.0)
  friendly_id (= 5.1.0)
  guard (= 2.12.5)
  guard-minitest (= 2.4.4)
  jbuilder (= 2.2.16)
  jquery-rails (= 4.0.3)
  mini_backtrace (= 0.1.3)
  mini_magick (= 4.2.4)
  minitest-reporters (= 1.0.16)
  pg (= 0.18.2)
  puma (= 2.11.2)
  rails (= 4.2.1)
  rails_12factor (= 0.0.3)
  sass-rails (= 5.0.3)
  sdoc (= 0.4.1)
  spring (= 1.3.6)
  turbolinks (= 2.5.3)
  uglifier (= 2.7.1)
  web-console (= 2.1.2)
  wice_grid!

**Comment by rgb-one** [comment]
I have tested with versions `1.8.2`, `1.9.6`, `1.7.7`, `1.10.2` which do not reproduce the issue. I then installed bundler 1.7.6 locally (this version is installed system wide by default) and the issue persisits. So it is safe to say this is an issue with bundler version 1.7.6. I installed version 1.7.5 but it seem the system bundler gets priority because of the higher version so I was unable to test that.

**Comment by rgb-one** [comment]
Rails does use bundler for managing project dependencies from my understanding. To address this issue install any upgrade bundler. Version 1.7.6 has been the only version to cause this issue. You can upgrade to the latest version of bundler with `gem install bundler`.

**Comment by Nickk4** [comment]
Thanks, this indeed also solved it for me

**Comment by lmahendra** [comment]
Hi, bundler is giving me the following error, 
 Could not find jbuilder-2.2.16 in any of the sources (Bundler::GemNotFound)

I tried everything here to make it work. Actually my app was working till I made some modifications in Gemfile and app for APIs. since then, it's giving me these kind of errors, I could resolve some of those but this one is actually making me pull hairs. I tried resetting the bundler and gems but not helped.

Can anyone please help me resolve the error?
