### ISSUE TITLE
Bundle warning about duplicated development dependencies when it should not

### ISSUE THREAD

**Issue by kaukas** [bundler/bundler#3163]
Hello.

First of all, thank you for all of your work on bundler! One of my daily tools!

I am working on a gem that can be used in both MRI and JRuby. Most of the dependencies are the same except for a few bits here and there. So I have the following (stripped down) setup:

https://gist.github.com/kaukas/7f91788682be1cfb32f2

When I run `bundle install` in either MRI or JRuby I get this warning about rake-the-development-dependency:

```
Your Gemfile lists the gem rake (>= 0) more than once.
You should probably keep only one of them.
While it's not a problem now, it could cause errors if you change the version of just one of them later.
```

Bundler seems to be happy and silent if I move `rake` to the runtime dependencies though.

It's just an annoyance but I have quite a few repeating development dependencies and I get the warning politely repeated for every one of them.

Of course, the real package names are not important here. `add_development_dependency` and multiple `platforms` declarations should trigger this any time.

Do you think that's a real bug or am I misconfiguring something?

Thank you!

**Comment by agis-** [comment]
@kaukas Since this is kind of an old issue, can you please check if the warning persists on 1.10.6 and if so, then share your Gemfile as well? Thanks!

**Comment by kaukas** [comment]
Yes, I am still getting that same warning with bundler 1.10.6 and the original setup as specified in https://gist.github.com/kaukas/7f91788682be1cfb32f2.

**Comment by LynnCo** [comment]
related https://github.com/bundler/bundler/issues/2822

**Comment by segiddins** [comment]
I'm not sure we can really fix this issue, I think my answer would be use the same gem name for both platform gems (in different gem files), and let bundler auto-select the proper platform

**Comment by colby-swandale** [comment]
There has been no reply to this issue for a long time so i'm going to close this.
