### ISSUE TITLE
bundle install fails on Ruby 1.9.3 if HTTP auth stored in bundle.config

### ISSUE THREAD

**Issue by plutino** [bundler/bundler#3180]
STR:
1. save private gem server credentials in ~/.bundle/config or with `bundle config` and remove any credentials in project Gemfile.
2. switch to Ruby 1.9.3 (tested on both rvm and chruby).
3. in Rails project directory do `bundle install`.

O:
Get a 401 error.  `bundle -V` shows that credentials are not added to to the HTTP request

D:
gems successfully installed as in other Ruby versions (tested on Ruby 2.1.2)

This happens on Bundler version 1.6.4-1.7.2

**Comment by TimMoore** [comment]
Finally have a proposed fix for all known issues with source credentials at #3342.

**Comment by TimMoore** [comment]
Fixed in 1.7.12.
