### ISSUE TITLE
`strip!': can't modify frozen String (RuntimeError)

### ISSUE THREAD

**Issue by dipolesource** [bundler/bundler#3187]
Hi Bundler team!

Got the following failure error on MRI1.9.3 but not when I switched to MRI2.1.2. I don't need resolution. Just reporting because it asked me to. Cheers!

[master]lotus: git remote -v
origin	https://github.com/lotus/lotus.git (fetch)
origin	https://github.com/lotus/lotus.git (push)

[master]lotus: git rev-parse head
e2f2b8112018cddf9fc9020986732a7e9ad8fd0e

````
[master]lotus: bundle
Unfortunately, a fatal error has occurred. Please report this error to the Bundler issue tracker at https://github.com/carlhuda/bundler/issues so that we can fix it. Please include the full output of the command, your Gemfile and Gemfile.lock. Thanks!
/Users/dipolesource/.rbenv/versions/1.9.3-p125/lib/ruby/1.9.1/rubygems/version.rb:191:in `strip!': can't modify frozen String (RuntimeError)
	from /Users/dipolesource/.rbenv/versions/1.9.3-p125/lib/ruby/1.9.1/rubygems/version.rb:191:in `initialize'
	from /Users/dipolesource/.rbenv/versions/1.9.3-p125/lib/ruby/1.9.1/rubygems/version.rb:178:in `new'
	from /Users/dipolesource/.rbenv/versions/1.9.3-p125/lib/ruby/1.9.1/rubygems/version.rb:178:in `create'
	from /Users/dipolesource/.rbenv/versions/1.9.3-p125/lib/ruby/1.9.1/rubygems/specification.rb:2092:in `version='
	from /Users/dipolesource/Sites/lotus/lotusrb.gemspec:8:in `block in <main>'
	from /Users/dipolesource/.rbenv/versions/1.9.3-p125/lib/ruby/1.9.1/rubygems/specification.rb:1346:in `initialize'
	from /Users/dipolesource/Sites/lotus/lotusrb.gemspec:6:in `new'
	from /Users/dipolesource/Sites/lotus/lotusrb.gemspec:6:in `<main>'
	from /Users/dipolesource/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/bundler-1.1.2/lib/bundler.rb:280:in `eval'
	from /Users/dipolesource/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/bundler-1.1.2/lib/bundler.rb:280:in `rescue in block in load_gemspec'
	from /Users/dipolesource/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/bundler-1.1.2/lib/bundler.rb:275:in `block in load_gemspec'
	from /Users/dipolesource/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/bundler-1.1.2/lib/bundler.rb:273:in `chdir'
	from /Users/dipolesource/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/bundler-1.1.2/lib/bundler.rb:273:in `load_gemspec'
	from /Users/dipolesource/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/bundler-1.1.2/lib/bundler/dsl.rb:39:in `gemspec'
	from /Users/dipolesource/Sites/lotus/Gemfile:2:in `evaluate'
	from /Users/dipolesource/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/bundler-1.1.2/lib/bundler/dsl.rb:7:in `instance_eval'
	from /Users/dipolesource/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/bundler-1.1.2/lib/bundler/dsl.rb:7:in `evaluate'
	from /Users/dipolesource/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/bundler-1.1.2/lib/bundler/definition.rb:18:in `build'
	from /Users/dipolesource/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/bundler-1.1.2/lib/bundler.rb:135:in `definition'
	from /Users/dipolesource/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/bundler-1.1.2/lib/bundler/cli.rb:220:in `install'
	from /Users/dipolesource/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/bundler-1.1.2/lib/bundler/vendor/thor/task.rb:22:in `run'
	from /Users/dipolesource/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/bundler-1.1.2/lib/bundler/vendor/thor/invocation.rb:118:in `invoke_task'
	from /Users/dipolesource/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/bundler-1.1.2/lib/bundler/vendor/thor.rb:263:in `dispatch'
	from /Users/dipolesource/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/bundler-1.1.2/lib/bundler/vendor/thor/base.rb:386:in `start'
	from /Users/dipolesource/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/bundler-1.1.2/bin/bundle:13:in `<top (required)>'
	from /Users/dipolesource/.rbenv/versions/1.9.3-p125/bin/bundle:19:in `load'
	from /Users/dipolesource/.rbenv/versions/1.9.3-p125/bin/bundle:19:in `<main>'
````

**Comment by arthurnn** [comment]
fixed by https://github.com/bundler/bundler/pull/3469 
thanks all

**Comment by phansaorin** [comment]
@arthurnn I have met problem like you but I don't know how to solve.

**Comment by arthurnn** [comment]
@phansaorin can you try updating to the latest version of bundler? `gem update bundler`

that should solve the issue.
thanks

**Comment by phansaorin** [comment]
@arthurnn It still not work for me.

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/bundler/bundler/search?q=Permission+denied+-+%2Fusr%2Fshare%2Fredmine%2F.bundle&type=Issues

If there aren't any reports for this error yet, please create copy and paste the report template above into a new issue. Don't forget to anonymize any private data! The new issue form is located at:
https://github.com/bundler/bundler/issues/new

do you have any idea.Please
thank

**Comment by arthurnn** [comment]
@phansaorin try updating your ruby, rubygems, and bundler to latest versions.

**Comment by phansaorin** [comment]
@arthurnn  really thank you boy. But now I got one more error is 

We're sorry, but something went wrong.

We've been notified about this issue and we'll take a look at it shortly.

Do you have any idea?

**Comment by indirect** [comment]
@phansaorin Please create a gist with the entire output and give it to us here.

**Comment by phansaorin** [comment]
my etc/apache2/sites-avarible/redmine.conf

<virtualhost *:80>
   DocumentRoot /usr/share/redmine/public
   PassengerResolveSymlinksInDocumentRoot on
</virtualhost>

host file /etc/hosts
127.0.0.1 localhost

my redmine version is 2.5
ubuntu 14.04
ruby 1.9.3
rails 3.2.19

The error is : 

We're sorry, but something went wrong.

We've been notified about this issue and we'll take a look at it shortly.
Information for the administrator of this website


It is really hard for me because I am new user of Ubuntu

**Comment by phansaorin** [comment]
@indirect please check my mention above

**Comment by indirect** [comment]
Sorry, that is not related to Bundler at all. That is an apache error.

**Comment by phansaorin** [comment]
@indirect thank you. Tried to fix this issue
