### ISSUE TITLE
NameError: uninitialized constant Thor::Base

### ISSUE THREAD

**Issue by andrewhavens** [bundler/bundler#3205]
I am in the process of developing a Rails Engine. I see this error when I try to run any Rake tasks:

    NameError: uninitialized constant Thor::Base

It seems that this error only appears when I add the `guard` gem to my Gemfile.

```
$ ruby -v
ruby 2.1.3
$ bundle -v
Bundler version 1.7.3
```

## Steps to reproduce:

Create a new rails engine (I used Rails 4.1.6):

    rails plugin new my_engine_name -T --full --mountable --dummy-path=spec/dummy 

Add `guard` gem to the Gemfile:

```ruby
source "https://rubygems.org"
gemspec
gem 'guard'
```

Run `bundle install`. Then use rake:

    $ bundle exec rake whatever
    NameError: uninitialized constant Thor::Base

I noticed that Guard lists Thor as a dependency:

    # Gemfile.lock
    ...
    guard (2.6.1)
      formatador (>= 0.2.4)
      listen (~> 2.7)
      lumberjack (~> 1.0)
      pry (>= 0.9.12)
      thor (>= 0.18.1)
    ...
    thor (0.19.1)

I'm not sure which version of Thor Bundler uses. Could it be that Bundler loads `thor 0.19.1` before it's vendored version when running `bundle exec rake ...` and that `0.19.1` has some API changes that Bundler is choking on?

**Comment by segiddins** [comment]
This should be fixed on `master`, now that the vendored version of Thor is properly namespaced.
