### ISSUE TITLE
Distinguish CI command runs from the rest

### ISSUE THREAD

**Issue by andremedeiros** [bundler/bundler#3233]
Right now, the commands are being reported and counted without differentiation as to their source.

@indirect suggests we should split them up by source when they run on CI systems.

A brief research wielded these environment variables we can use to pinpoint what CI system is running:

- Travis CI: `TRAVIS` (or, even better, `HAS_JOSH_K_SEAL_OF_APPROVAL`); /cc @joshk
- CircleCI: `CIRCLECI` (or any of the other env variables it sets when starting a container);
- Semaphore: `SEMAPHORE`;
- Jenkins: `JENKINS_URL`;
- Buildbox: `BUILDBOX`;
- Codeship: `CI_NAME` set to `codeship`;
- Go: `GO_SERVER_URL`;
- SnapCI: `SNAP_CI`;

Let me know if I've missed anything before I do the work for this.

**Comment by simi** [comment]
What about to distinguish command runs from non-interactive shells (CI, deploy, ...) also? But I'm not sure if that's easy to do universal check.

**Comment by fotanus** [comment]
If this turns out to be interesting, I can look for a way on how to do. Maybe open a new issue for that one?

**Comment by segiddins** [comment]
closed by https://github.com/bundler/bundler/pull/3646.
