### ISSUE TITLE
Installing a gem into the system with `rake install` is breaking

### ISSUE THREAD

**Issue by brandonweiss** [bundler/bundler#3236]
Relevant versions are `ruby 2.1.3p242`, `ruby gems 2.4.2`, and `bundler 1.7.4`.

I'm working on a gem that I generated using `bundle init`. It has two development dependencies (bundler and rake, added by `bundle init`) and one regular dependency, thor, which I added.

When it's time to test it out, I run `rake install` to install it into my system gems, and get this:

```plain
$ rake install
foobar 0.1.0 built to pkg/foobar-0.1.0.gem.
rake aborted!
Couldn't install gem, run `gem install /Users/brandon/Code/foobar/pkg/foobar-0.1.0.gem' for more detailed output

Tasks: TOP => install
(See full trace by running task with --trace)
```

So I run `gem install /Users/brandon/Code/foobar/pkg/foobar-0.1.0.gem` and get:

```plain
$ gem install /Users/brandon/Code/foobar/pkg/foobar-0.1.0.gem
Fetching: thor-0.19.1.gem (100%)
Successfully installed thor-0.19.1
Successfully installed foobar-0.1.0
2 gems installed
```

I would have expected it to fail and see the reason why, but instead it installs. I uninstall both foobar and thor and try to figure out why. I run `rake install --trace` and see that it’s failing on [line 69 of gem_helper](https://github.com/bundler/bundler/blob/v1.7.4/lib/bundler/gem_helper.rb#L69). It appears that the gem is being installed with the `--local` flag. If I run `gem install /Users/brandon/Code/foobar/pkg/foobar-0.1.0.gem --local` I get:

```plain
$ gem install /Users/brandon/Code/foobar/pkg/foobar-0.1.0.gem --local
ERROR:  Could not find a valid gem 'thor' (~> 0.19.1) in any repository
```

OK, that probably makes sense because I install dependencies with `bundle install --path vendor`. So the thor dependency isn’t in my system gems it’s in `vendor/ruby`, which is why `gem install --local` can’t find it and `rake install` is failing. I would need to run `rake install` through Bundler in order for it to find that gem repository. So I run `bundle exec rake install` and get:

```plain
$ bundle exec rake install
foobar 0.1.0 built to pkg/foobar-0.1.0.gem.
foobar (0.1.0) installed.
```

That appears to work but when I list out my gems it’s not there.

1. I think perhaps the error output when running `rake install` should be updated to include the `--local` flag, since that is technically how it is being installed. It was slightly confusing that running the command to see the error actually wound up succeeding.
2. Is this behavior a bug? Or is the problem that I shouldn’t be bundling with `--path vendor` when making a gem? I thought I’d done that previously and it had worked, but the last time I created a gem was a while ago and I can’t remember what the specifics of that environment (the different versions of everything) were in order to reproduce it.

**Comment by bjarketrux** [comment]
I have the same problem. Need to install my command line tool (not using bundle exec) but I need to do it manually, because of the --local option. Why is the flag even set?

**Comment by indirect** [comment]
Ugh. :( We had to add that flag back when Rubygems had a bug that made it impossible to install _without_ the --local flag, and now it sounds like it’s changed and gone the other way. :( Time to remove the flag, I guess.

**Comment by bjarketrux** [comment]
That would be great thanks :)

**Comment by segiddins** [comment]
I believe this is closed by https://github.com/bundler/bundler/commit/5684b3e0f5fd081739a9df73b6a1c8392643a083.

**Comment by brandonweiss** [comment]
:tada:
