### ISSUE TITLE
Bundler keep asking to checkout git repo 

### ISSUE THREAD

**Issue by brauliobo** [bundler/bundler#3242]
Bundler keep asking to checkout git repo, even after I ran it before several times. It keeps asking over and over again.
Version is 1.7.4

    The git source git://github.com/coletivoEITA/omniauth-browserid.git is not yet checked out. Please run `bundle install` before trying to start your application

**Comment by wtfiwtz** [comment]
Check your version of Spring is not 1.3.0 or 1.3.1 - see these:
https://github.com/bundler/bundler/issues/3070
https://github.com/rails/spring/issues/383

**Comment by brauliobo** [comment]
@TimMoore nice, please run `script/noosfero-plugins enable oauth` and the `bundle`. The `oauth` plugin has a `Gemfile` that depends on git repos.

@TimMoore maybe this is related to RVM gemset switching, but I still cannot always reproduce this.

**Comment by TimMoore** [comment]
@brauliobo `script/noosfero-plugins enable oauth` produces an error on my machine:

```
[13:06:12] tmoore@tmoore-macbook-pro:~/Projects/bundler/issues/noosfero-ecosol (master=) $ script/noosfero-plugins enable oauth
readlink: illegal option -- f
usage: readlink [-n] [file ...]
```

I guess this is a Linux-only thing? You haven't given us all of the information we ask for in https://github.com/bundler/bundler/blob/master/ISSUES.md#reporting-unresolved-problems so it's very hard for anyone to help you.

**Comment by brauliobo** [comment]
@TimMoore finally I could reproduce this.
Use as Gemfile:

    source :rubygems
    gem 'omniauth-browserid', github: 'coletivoEITA/omniauth-browserid', branch: 'master'

Then run `bundle install` and then `rm Gemfile.lock` and then `bundle exec irb`.

The problem is that without the Gemfile.lock bundle can't know about the cache, which is something strange to me. It should use by default the last checked out commit.

**Comment by brauliobo** [comment]
The problem is quite frequent for me as I frequently change branchs and enable/disable noosfero's plugins (which changes the `Gemfile.lock`)

**Comment by TimMoore** [comment]
@brauliobo I'm a little confused about your reproduction steps. Why do you `rm Gemfile.lock`? I wouldn't expect `bundle exec` to work without a `Gemfile.lock`.

If you frequently change branches and enable or disable plugins, then you should run `bundle install` after each change to your configuration. Bundler needs `Gemfile.lock` to know which gems to load. Maybe consider running `bundle install` from the `script/noosfero-plugins` script.

**Comment by brauliobo** [comment]
@TimMoore for gems not loaded via git, the Gemfile.lock is not necessary, it run the app with the latest versions available of the gems. The same behaviour should be valid for gems installed via git, IMO.

**Comment by TimMoore** [comment]
Good point. Looks like `bundle exec` normally regenerates the lock file if all of the gems are already available locally.

**Comment by indirect** [comment]
Okay, so after trying this myself, this is the current expected behaviour. Git repositories may have been updated, and with no Gemfile.lock, `bundle install` needs to run to update the git repo before it is possible to `bundle exec`.

While it _could_ be possible to `bundle exec` by simply locking to the currently checked-out git commit, it is not something that we have ever supported in the past. That means this isn't a bug, but a feature request for git repositories.

If you'd like us to add this feature to Bundler in the future, could you open a feature request at the bundler/bundler-features issue tracker? Thanks!

**Comment by brauliobo** [comment]
this also makes the performance of inline gemfiles (with `gemfile` from https://github.com/bundler/bundler/blob/master/lib/bundler/inline.rb) very bad, as it needs to fetch the git repo everytime the script is run as obviously there isn't a `Gemfile.lock` involved
