### ISSUE TITLE
How to change bundler source?

### ISSUE THREAD

**Issue by TangMonk** [bundler/bundler#3243]
I am in china, the  `source 'https://rubygems.org'` is pretty slowly when excute `bundle install`, So I always change the Gemfile first line to `http://ruby.taobao.org/`.

Can I set the default option from bundle command line without change source every time? like this:

``` bash
$ bundle config source http://ruby.taobao.org/
```

**Comment by dedles** [comment]
After returning from China, how could I change the source back to rubygems?

**Comment by indirect** [comment]
@dedles run `bundle config --delete mirror.https://rubygems.org`. See `bundle help config` for full help.

**Comment by dedles** [comment]
Thanks!
