### ISSUE TITLE
submodules=>true doesn't work for rugged

### ISSUE THREAD

**Issue by jweather** [bundler/bundler#3251]
Gemfile:
> gem 'rugged', :git => 'https://github.com/libgit2/rugged.git', :submodules => true

Output:
> C:\Users\JWeatherford\Desktop\sonic-pi\app\gui\qt>bundler install
> Updating https://github.com/jweather/hamster.git
> Updating https://github.com/jweather/ruby-beautify.git
> Fetching https://github.com/libgit2/rugged.git
> fatal: destination path 'vendor/libgit2' already exists and is not an empty directory.
> Clone of 'https://github.com/libgit2/libgit2.git' into submodule path 'vendor/libgit2' failed
> Retrying git submodule update --init --recursive due to error (2/3): Bundler::Source::Git::GitCommandError Git error: command `git submodule update --init --recursive` in directory c:/users/jweatherford/desktop/sonic-pi/app/server/native/windows/lib/ruby/gems/1.9.1/bundler/gems/rugged-273e247d72dc has failed.
> If this error persists you could try removing the cache directory 'c:/users/jweatherford/desktop/sonic-pi/app/server/native/windows/lib/ruby/gems/1.9.1/cache/bundler/git/rugged-7fee50588a821baac99ce836721cd0259aeedc25'
> fatal: destination path 'vendor/libgit2' already exists and is not an empty directory.
> Clone of 'https://github.com/libgit2/libgit2.git' into submodule path 'vendor/libgit2' failed
> Retrying git submodule update --init --recursive due to error (3/3): Bundler::Source::Git::GitCommandError Git error: command `git submodule update --init --recursive` in directory c:/users/jweatherford/desktop/sonic-pi/app/server/native/windows/lib/ruby/gems/1.9.1/bundler/gems/rugged-273e247d72dc has failed.
> If this error persists you could try removing the cache directory 'c:/users/jweatherford/desktop/sonic-pi/app/server/native/windows/lib/ruby/gems/1.9.1/cache/bundler/git/rugged-7fee50588a821baac99ce836721cd0259aeedc25'
> fatal: destination path 'vendor/libgit2' already exists and is not an empty directory.
> Clone of 'https://github.com/libgit2/libgit2.git' into submodule path 'vendor/libgit2' failed
> Git error: command `git submodule update --init --recursive` in directory c:/users/jweatherford/desktop/sonic-pi/app/server/native/windows/lib/ruby/gems/1.9.1/bundler/gems/rugged-273e247d72dc has failed.
> If this error persists you could try removing the cache directory 'c:/users/jweatherford/desktop/sonic-pi/app/server/native/windows/lib/ruby/gems/1.9.1/cache/bundler/git/rugged-7fee50588a821baac99ce836721cd0259aeedc25'

**Comment by indirect** [comment]
Well, this works fine for me:

```
$ cat Gemfile
gem 'rugged', :git => 'https://github.com/libgit2/rugged.git', :submodules => true
$ bundle install
Fetching https://github.com/libgit2/rugged.git
Cloning into 'vendor/libgit2'...
remote: Counting objects: 59652, done.
remote: Compressing objects: 100% (17281/17281), done.
remote: Total 59652 (delta 41202), reused 59611 (delta 41164), pack-reused 0
Receiving objects: 100% (59652/59652), 24.12 MiB | 64.00 KiB/s, done.
Resolving deltas: 100% (41202/41202), done.
Checking connectivity... done.
Resolving dependencies...
Using bundler 1.9.1
Using rugged 0.23.0b1 from https://github.com/libgit2/rugged.git (at master)
Bundle complete! 1 Gemfile dependency, 2 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
```

Can you provide specific reproduction steps?

**Comment by dankohn** [comment]
I had this issue and fixed it with `rm -rf /Users/dan/.rbenv/versions/2.2.2/lib/ruby/gems && gem install bundler && bundle`.
