### ISSUE TITLE
bundle install runs forever

### ISSUE THREAD

**Issue by adrifelt** [bundler/bundler#3280]
I'm trying to run bundle install, but it hangs. I walked away from my computer for 3 hrs and when I came back it was still in the same place.

From running "DEBUG_RESOLVER=true bundle install" I see that it hangs after the same chunk:

==== Iterating ====

Activated:
  github-pages (29)
  jekyll (2.4.0)
  jekyll-coffeescript (1.0.0)
  redcarpet (3.1.2)
  rdiscount (2.1.7)
  jemoji (0.3.0)
  kramdown (1.3.1)
  jekyll-sitemap (0.6.0)
  jekyll-mentions (0.1.3)
  maruku (0.7.0)
  colorator (0.1)
  pygments.rb (0.6.0)
  html-pipeline (1.9.0)
  liquid (2.6.1)
  yajl-ruby (1.1.0)
  jekyll-sass-converter (1.2.0)
  RedCloth (4.2.9)
  jekyll-redirect-from (0.6.2)
  jekyll-gist (1.1.0)
  jekyll-paginate (1.1.0)
  coffee-script (2.3.0)
  mercenary (0.3.5)
  posix-spawn (0.3.9)
  github-pages-health-check (0.2.1)
  toml (0.1.2)
  parslet (1.5.0)
  jekyll-watch (1.1.2)
  classifier-reborn (2.0.2)
  gemoji (2.1.0)
  blankslate (2.1.2.4)
  fast-stemmer (1.0.2)
  safe_yaml (1.0.4)
  net-dns (0.8.0)
  terminal-table (1.4.5)
  public_suffix (1.4.6)
  listen (2.8.3)
  celluloid (0.16.0)
  rb-fsevent (0.9.4)
  timers (4.0.1)
  rb-inotify (0.9.5)
  hitimes (1.2.2)
  coffee-script-source (1.8.0)
  nokogiri (1.6.5)
  mini_portile (0.6.1)
  ffi (1.9.6)
  execjs (2.2.2)
  sass (3.4.9)
  activesupport (4.1.8)
  i18n (0.6.11)
  json (1.8.1)
  tzinfo (1.2.2)
  thread_safe (0.3.4)
Requirements:
  minitest (~> 5.1) ruby
Attempting:
  minitest (~> 5.1) ruby
  Activating: minitest (5.4.3)
    \* github-pages (>= 0)
    \* jekyll-mentions (= 0.1.3)
    \* html-pipeline (~> 1.9.0)
    \* activesupport (>= 2)
    \* minitest (~> 5.1)
    Dependencies

And this seems to somehow be related:
/Applications/Xcode.app/Contents/Developer/usr/bin/xcrun lipo -create -output conftest

**Comment by thinknot** [comment]
Just wanted to comment that I ran into a similar looping conftest problem while using Bundler, except on a Debian linux stack with rvm. 
The workaround mentioned above `gem install nokogiri` worked for me, and then I was able to finish running `bundle install`. So it seems this autoconf problem may also occur outside of OS X toolchains.

Here is what the process stack looked like most of the time the endless loop was running:

    6971 pts/1    Sl+    0:02  |           \_ ruby /home/rmdev/.rvm/gems/ruby-2.1.6/bin/bundle install --without postgresql sqlite
    6980 pts/1    S+     0:00  |               \_ sh -c /home/rmdev/.rvm/rubies/ruby-2.1.6/bin/ruby -r ./siteconf20150803-6971-127slnm.rb extconf.rb 2>&1
    6981 pts/1    Sl+    0:37  |                   \_ /home/rmdev/.rvm/rubies/ruby-2.1.6/bin/ruby -r ./siteconf20150803-6971-127slnm.rb extconf.rb
    10890 pts/1    S+     0:00  |                       \_ gcc -o conftest -I/home/rmdev/.rvm/rubies/ruby-2.1.6/include/ruby-2.1.0/x86_64-linux -I/home/rmdev/.rvm/rubies/ruby-2.1.6/include/ruby-2.1.0/ruby/backward -I/home/rmdev/.rvm/rubies/ruby-2.1.6/include/ruby-2.1.0 -I. -I/usr/local/include -O3 -fno-fast-math -ggdb3 -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wunused-variable -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wimplicit-function-declaration -fPIC conftest.c -L. -L/home/rmdev/.rvm/rubies/                                                                                                                                           ruby-2.1.6/lib -Wl,-R/home/rmdev/.rvm/rubies/ruby-2.1.6/lib -L/usr/local/lib -Wl,-R/usr/local/lib -L. -fstack-protector -rdynamic -Wl,-export-dynamic -lm -Wl,-R -Wl,/home/rmdev/.rvm/rubies/rub                                                                                                                                           y-2.1.6/lib -L/home/rmdev/.rvm/rubies/ruby-2.1.6/lib -lruby -lmysqlclient -lm -lpthread -lrt -ldl -lcrypt -lm -lc                                                                                                            

The Gemfile in question is for redmine 3.0.4
Bundler version 1.10.6
ruby 2.1.6p336 (2015-04-13 revision 50298) [x86_64-linux]
gem 2.4.8
rvm 1.26.11 (master)
rubygems-bundler (1.4.4)
