### ISSUE TITLE
Gem path points to "gemfiles" directory

### ISSUE THREAD

**Issue by avit** [bundler/bundler#3286]
I'm trying to use my own fork of this gem: https://github.com/premailer/premailer/

Note, the original gem source has a "gemfiles" directory at the root.

The original gem works if loaded from rubygems. When I point to the git repo from my Gemfile, it seems to recognize the "gemfiles" directory instead of the correct gem root:

```ruby
# Gemfile
gem "premailer", github: "premailer/premailer", branch: "master"
```

```
$ bundle update premailer
...
$ bundle show premailer
/opt/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/bundler/gems/premailer-28e3cb96befb/gemfiles
```

The result is that none of the gem files can be found; `require "premailer"` fails. Manually deleting the "gemfiles" seems to resolve to the correct directory:

```
$ rm -r /opt/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/bundler/gems/premailer-28e3cb96befb/gemfiles

$ bundle show premailer
/opt/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/bundler/gems/premailer-28e3cb96befb
```

**Comment by indirect** [comment]
Ticketed in [this Trello ticket](https://trello.com/c/DQx0OKJl).
