### ISSUE TITLE
Add ability to ignore .bundle/config

### ISSUE THREAD

**Issue by jordansissel** [bundler/bundler#3288]
In my bundler usage, I absolutely never want flags/configuration saved to .bundle/config. I have observed that between two different `bundle install` invocations, the first one's flags are saved to .bundle/config and the second invocation completely ignores any CLI flags and uses only .bundle/config. This causes pain and suffering :P 

I am willing to provide patches to solve this, but wish guidance from y'all on what the interface should be. Should it be a flag to `bundle install`?

**Comment by quoideneuf** [comment]
+1 I really find the existing behavior counter-intuitive and unfriendly to build tasks

**Comment by indirect** [comment]
@quoideneuf why are you +1ing a feature that we have already started implementing? :/

**Comment by quoideneuf** [comment]
@indirect - Sorry, I didn't know you were.

**Comment by indirect** [comment]
> Flags will not be persisted in Bundler 2.0

It's already mostly done, even! We'll be shipping Bundler 2.0 sometime soon, probably within 2 releases.

**Comment by quoideneuf** [comment]
Well, in that case all I have to say is :+1:

**Comment by daniel-barlow** [comment]
In bundler 1.14.6 I appear to be able to work around this - at the expense of creating mess on my filesystem - by setting `BUNDLE_APP_CONFIG` to an empty temporary directory before each command that might write it.  For example

```
BUNDLE_APP_CONFIG=$TMPDIR/bundle.$$ bundle package --no-install --all
```

Obviously, important not to reuse the same temporary directory next time ;-)

**Comment by wesm-outreach** [comment]
> @indirect commented on Sep 23, 2015 
> Flags will not be persisted in Bundler 2.0  It's already mostly done, even! We'll be shipping Bundler 2.0 sometime soon, probably within 2 releases.

Any idea when we'll get bundler 2?

**Comment by indirect** [comment]
@wesm-outreach amazingly, soon. The master branch of this repo is currently 2.0, and we are working on a smoother upgrade path, guides, and documentation before we release.
