### ISSUE TITLE
When credentials are configured for a source, use them unconditionally

### ISSUE THREAD

**Issue by TimMoore** [bundler/bundler#3297]
Right now (as of 1.7.9), it tries to make an unauthenticated request first, then retries with authentication if the first request fails.

This causes issues on some gem servers. For example, Gemfury supports the dependency API and allows a mix of public and private gems in the same repository. It does not forbid unauthenticated requests, but it returns partial information.

See discussion on #3180, #3260 and #3296.

**Comment by dpiddy** [comment]
As shown in #3296 this is a pretty big unexpected behavior change in a patch release. Can the auth changes be reverted?

**Comment by TimMoore** [comment]
OK yeah let's revert for now.

**Comment by TimMoore** [comment]
Work-in-progress branch is here https://github.com/TimMoore/bundler/tree/issue-3297-always-use-source-credentials

Still a few things broken. I'll give it another look when I have some free time tonight or this weekend.

**Comment by TimMoore** [comment]
I have a working (AFAICT) fix over at #3342 now.
