### ISSUE TITLE
bundle update not performing correctly with git source

### ISSUE THREAD

**Issue by BenMorganIO** [bundler/bundler#3300]
Currently I am using the `git` method to link to a repo a pull down some specific gems as so:

```ruby
git "https://github.com/spree/spree.git", branch: "2-4-stable" do
  gem "spree_core"
  gem "spree_api"
  gem "spree_backend"
  gem "spree_sample"
end
```

This happily install the four spree gems for me, but when I go to `bundle update spree_core` it doesn't actually update the gem. I end up having to comment out to block, `bundle`, add the block back in, and do another `bundle`.

Thoughts?

**Comment by zedtux** [comment]
I'm encountering this issue too. I have forked the cucumber gem, updated it this morning, and doing `bundle update cucumber` is not working.

[Here is my `bundle env`](https://gist.github.com/zedtux/65a539ec5b7247152a7e)

**Comment by zedtux** [comment]
Also here is the way I wrote the gem line in my Gemfile:

    gem 'cucumber', github: 'zedtux/cucumber', branch: 'v1.3.x-bugfix'

**Comment by zedtux** [comment]
Changing to this fixed the issue:

    gem 'cucumber', git: 'https://github.com/zedtux/cucumber.git', branch: 'v1.3.x-bugfix'

I don't know if it's a bug in the previous way of writing the gem line or if changing the Gemfile is forcing bundler to update the git repo...

**Comment by zedtux** [comment]
Arf... reverting to the `github: 'zedtux/cucumber' ` and doing update also forced bundler to update the gem. I would say 'touching' the Gemfile make it working, so there is a bug.

**Comment by indirect** [comment]
I've created a [Trello ticket to reduce the requests for gem metadata](https://trello.com/c/gBqeGWpb), but most gems still need to be requested from most sources.
