### ISSUE TITLE
`bundle install` doesn't load rubygems plugins before invoking post_install hooks

### ISSUE THREAD

**Issue by jordansissel** [bundler/bundler#3310]
When doing `bundle install`, it appears that any gem plugins are not loaded, so any post-install hooks used by any installed gems that include gem plugins are not available.

To fix it, I found that putting `Gem.load_plugins` at the top of this `install` method works:
https://github.com/bundler/bundler/blob/v1.7.8/lib/bundler/source/path.rb#L73

I am looking into some kind of workaround, but I'm not sure if one can be had :P

**Comment by LynnCo** [comment]
Not sure if this is still an issue, but if it is we have someone working on the (only mildly related) plugin system

**Comment by segiddins** [comment]
We already call `Gem.load_plugins` inside the installer, so without a reproduction case for the bug, I'm going to close this for now.
