### ISSUE TITLE
NixOS support

### ISSUE THREAD

**Issue by cstrahan** [bundler/bundler#3327]
Hello,

As a [NixOS](http://nixos.org) collaborator, I'm trying to improve the way we package Ruby applications. What I have so far is a tool - [Bundix](http://github.com/cstrahan/bundix) - that takes a Gemfile and Gemfile.lock and spits out a Nix package definition. However, I still have one big problem: if I have a Gemfile, but no corresponding Gemfile.lock, `Bundler::Defintion#resolve` will fail if the gems aren't already installed locally.

    /nix/store/m3207fx0vzkjzz096dqmf1dkx6nwsa97-ruby-2.1.3-p0-bundler-1.7.4/lib/ruby/gems/2.1.3/gems/bundler-1.7.4/lib/bundler/resolver.rb:357:in `resolve': Could not find gem 'sup (= 0.20.0) ruby' in the gems available on this machine. (Bundler::GemNotFound)
            from /nix/store/m3207fx0vzkjzz096dqmf1dkx6nwsa97-ruby-2.1.3-p0-bundler-1.7.4/lib/ruby/gems/2.1.3/gems/bundler-1.7.4/lib/bundler/resolver.rb:164:in `start'
            from /nix/store/m3207fx0vzkjzz096dqmf1dkx6nwsa97-ruby-2.1.3-p0-bundler-1.7.4/lib/ruby/gems/2.1.3/gems/bundler-1.7.4/lib/bundler/resolver.rb:129:in `resolve'
            from /nix/store/m3207fx0vzkjzz096dqmf1dkx6nwsa97-ruby-2.1.3-p0-bundler-1.7.4/lib/ruby/gems/2.1.3/gems/bundler-1.7.4/lib/bundler/definition.rb:193:in `resolve'
            from /nix/store/pp8mpq1j84vmbvw3vyb5s098dvrrqi01-ruby-2.1.3-p0-bundix-0.1.0/lib/ruby/gems/2.1.3/gems/bundix-0.1.0/lib/bundix/cli.rb:43:in `expr'
            from /nix/store/pdvvxl1l9am9mhwjpp9wwpfc9j8n4c8h-ruby-2.1.3-p0-thor-0.19.1/lib/ruby/gems/2.1.3/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
            from /nix/store/pdvvxl1l9am9mhwjpp9wwpfc9j8n4c8h-ruby-2.1.3-p0-thor-0.19.1/lib/ruby/gems/2.1.3/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
            from /nix/store/pdvvxl1l9am9mhwjpp9wwpfc9j8n4c8h-ruby-2.1.3-p0-thor-0.19.1/lib/ruby/gems/2.1.3/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
            from /nix/store/pdvvxl1l9am9mhwjpp9wwpfc9j8n4c8h-ruby-2.1.3-p0-thor-0.19.1/lib/ruby/gems/2.1.3/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
            from /nix/store/pp8mpq1j84vmbvw3vyb5s098dvrrqi01-ruby-2.1.3-p0-bundix-0.1.0/lib/ruby/gems/2.1.3/gems/bundix-0.1.0/bin/bundix:4:in `<main>'

This may not *seem* like a big deal, as it would seem reasonable to just run `bundle install` once to create the Gemfile.lock. However, that would be very impractical for us: *every*  C extension in the graph will require a `gem` argument to be passed through for every library that the C extension links to. So let's say a particular application has 5 gems with C extensions, and each of those links to 3 libraries; that's 15 different library locations that *must* be passed explicitly.

This might sound odd: on most flavors of Linux, gems install just fine with their default assumption that everything they need will be in `/usr/{,local/}{bin,lib,include}`. Unfortunately, to enable NixOS's major distinguishing feature - deterministic packages - the [FHS](http://www.pathname.com/fhs/) had to be abandoned: on NixOS, the `/usr/{,local/}{bin,lib,include}` folders do not exist, and there are no analogues: every package is installed in its own prefix. Therefore, it is very important that we have some way to resolve dependencies without having to install the gems first. The maintenance burden would just be too great otherwise.

Is there a way to make `Bundler::Defintion#resolve` work without having the gems installed? If not, can we have this featured implemented, please? (Or is there a more appropriate/suitable API in Bundler that I should be using instead?)

**Comment by cstrahan** [comment]
@TimMoore `bundler package --no-install` still wants to install gems into `$GEM_HOME`. If I try something nonsensical like this:

    GEM_HOME=/dev/null GEM_PATH=/dev/null bundler package --no-install
    Your Gemfile contains path and git dependencies. If you want to package them as well, please pass the --all flag. This will be the default on Bundler 2.0.
    Fetching gem metadata from https://rubygems.org/..
    Resolving dependencies...
    Using bundler 1.7.9
    
    Errno::EEXIST: File exists @ dir_s_mkdir - /dev/null
    An error occurred while installing thor (0.19.1), and Bundler cannot continue.
    Make sure that `gem install thor -v '0.19.1'` succeeds before bundling.

It claims that it's trying to run `gem install`. Sure enough, if I don't mess with `$GEM_HOME`:

    tree $GEM_HOME
    /home/cstrahan/.gem/ruby/2.1.3
    └── cache
        └── thor-0.19.1.gem

**Comment by TimMoore** [comment]
Sounds like there could be a bug where it still tries to ensure that `$GEM_HOME` exists even when running with `--no-install`, but in my testing it didn't install anything there.

**Comment by cstrahan** [comment]
@TimMoore It appears I've stumbled across a related bug: if one of the gems that is about to be installed is on the `$GEM_PATH` (and I assume the second criterion is that the the same gem is *not* in `$GEM_HOME`), `bundler package --no-install` can't find the gem, while `bundle show` can:

    $ GEM_PATH=/nix/store/qmiwbc0shz1zfdxmadsmy1wgrarc5abq-ruby-2.1.3-p0-thor-0.19.1/lib/ruby/gems/2.1.3${GEM_PATH:+:}$GEM_PATH \
        /nix/store/lwvrp8p5gmh31dw75fjpf3d56mhqwjfk-ruby-1.9.3-p547-bundler-HEAD/bin/bundler package --no-install
    Resolving dependencies...
    Using bundler 1.7.9
    Using thor 0.19.1
    Using bundix 0.1.0 from source at .
    Updating files in vendor/cache
    Could not find thor-0.19.1.gem for installation
    
    $ /nix/store/lwvrp8p5gmh31dw75fjpf3d56mhqwjfk-ruby-1.9.3-p547-bundler-HEAD/bin/bundle show thor
    /nix/store/qmiwbc0shz1zfdxmadsmy1wgrarc5abq-ruby-2.1.3-p0-thor-0.19.1/lib/ruby/gems/2.1.3/gems/thor-0.19.1

Compared to:

    $ /nix/store/lwvrp8p5gmh31dw75fjpf3d56mhqwjfk-ruby-1.9.3-p547-bundler-HEAD/bin/bundler package --no-install
    Your Gemfile contains path and git dependencies. If you want to package them as well, please pass the --all flag. This will be the default on Bundler 2.0.
    Fetching gem metadata from https://rubygems.org/..
    Resolving dependencies...
    Using bundler 1.7.9
    Installing thor 0.19.1
    Using bundix 0.1.0 from source at .
    Bundle complete! 1 Gemfile dependency, 3 gems now installed.
    Use `bundle show [gemname]` to see where a bundled gem is installed.
    Updating files in vendor/cache
      * thor-0.19.1.gem
    
    $ /nix/store/lwvrp8p5gmh31dw75fjpf3d56mhqwjfk-ruby-1.9.3-p547-bundler-HEAD/bin/bundle show thor
    Could not find thor-0.19.1 in any of the sources

**Comment by cstrahan** [comment]
Ok, so the reason I'm seeing the behavior above is because of the way I build rubygem packages: the packages don't include the cached gem file.

I think `Bundler::Source::RubyGems#installed_specs` should use `#cached_path` to reject any specs that don't also have a corresponding cached gem file, that way `#install` will fetch the gem.

**Comment by indirect** [comment]
In Rubygems world, the cached gem file is the source of truth. Without it, rubygems won't correctly (most notable the 'gem pristine' command). Installing a gem always means caching the .gem file.

**Comment by cstrahan** [comment]
@indirect Fair enough. Looks like there's a decent amount of confusion around this: https://lists.fedoraproject.org/pipermail/ruby-sig/2012-August/001089.html. The official Fedora packaging docs suggest that the .gem shouldn't be cached. Oh well.

**Comment by cstrahan** [comment]
So, at this point, I feel like I'm close. However, when I use `bundler package --no-install`, it doesn't include the required bundler version in the Gemfile.lock, whereas my old approach of manually resolving the gems *did* include the bundler version. Is this a bug? Or is this intended, and I'll just need to continue using the internals directly?

**Comment by indirect** [comment]
There is no such thing as a "required bundler version", yet. Right now (with the awkward exception of the `ruby` command), all Gemfiles and Gemfile.locks are compatible with all versions of Bundler from 1.0.0 up.

**Comment by indirect** [comment]
(Even if there is a Bundler version in the Gemfile or in the Gemfile.lock, it is ignored by Bundler internally.)

**Comment by indirect** [comment]
@cstrahan I understand the philosophical objection to keeping a copy of the compressed artifact as well as the uncompressed files, but I'm just letting you know that Rubygems (and Bundler) both depend on the .gem file being there to function correctly. If Fedora wants to delete it, that then becomes their problem. :)

**Comment by cstrahan** [comment]
> There is no such thing as a "required bundler version", yet. Right now (with the awkward exception of the ruby command), all Gemfiles and Gemfile.locks are compatible with all versions of Bundler from 1.0.0 up.

I mean my application has a dependency on `bundler` (to parse the Gemfile.lock), but `bundle install`/`bundle package` doesn't include `bundler` in the lock file that bundler generates.

Here's the Gemfile:

    source 'https://rubygems.org'
    gemspec

Here's the relevant bits of the gemspec:

      s.add_runtime_dependency 'bundler', '~> 1.7.4'
      s.add_runtime_dependency 'thor',    '~> 0.19.1'

Here's the Gemfile.lock that was created:

    PATH
      remote: .
      specs:
        bundix (0.1.0)
          bundler (~> 1.7.4)
          thor (~> 0.19.1)
    
    GEM
      remote: https://rubygems.org/
      specs:
        thor (0.19.1)
    
    PLATFORMS
      ruby
    
    DEPENDENCIES
      bundix!

The locked bundler version should be listed under GEM specs, unless bundler intentionally doesn't allow itself to be listed among gems in the lockfile.

**Comment by cstrahan** [comment]
> (Even if there is a Bundler version in the Gemfile or in the Gemfile.lock, it is ignored by Bundler internally.)

Oops, that's what I get for reading/replying serially. :)

**Comment by cstrahan** [comment]
> @cstrahan I understand the philosophical objection to keeping a copy of the compressed artifact as well as the uncompressed files, but I'm just letting you know that Rubygems (and Bundler too) depend on the .gem file being there to function correctly. If Fedora wants to delete it, that then becomes their problem. :)

Hah, yeah, I don't mind playing by the rules, whatever those rules may be. Thanks for letting me know.

**Comment by TimMoore** [comment]
Is this addressed by #3439?

**Comment by cstrahan** [comment]
@TimMoore Yep!
