### ISSUE TITLE
Add :mri_22 platform in addition to :ruby_22

### ISSUE THREAD

**Issue by mvz** [bundler/bundler#3333]
In 019a3cf733a537b9d6fd3ec297f0def7ccc18db3 the `:ruby_22` platform option was added, but not the corresponding `:mri_22`, even though the necessary predicate methods were added.

**Comment by mvz** [comment]
I'll see about creating a PR for this.

**Comment by andremedeiros** [comment]
That would be fantastic! Thank you.

**Comment by mvz** [comment]
It looks like this was already added to the `1-7-stable` branch in 3472286166e1626fbfbf5d3bbe16e22e9cea496f.
