### ISSUE TITLE
Gem non available in /Users/clement/.rbenv/shims

### ISSUE THREAD

**Issue by craigzour** [bundler/bundler#3339]
Hi,

Installing gem from official repo does not work the same way than private repo. I am not able to find my gem executable in /Users/clement/.rbenv/shims when I am installing the gem using a private repo. 

I tried with Thor library using private repo first :

source 'https://rubygems.org'
gem 'thor', :git => 'https://github.com/erikhuda/thor'

No Thor executable in /Users/clement/.rbenv/shims

Then I tried with the official repo :

source 'https://rubygems.org'
gem 'thor'

Now I see the Thor executable in /Users/clement/.rbenv/shims.

Is it a bug ?

Thank you !

**Comment by indirect** [comment]
No.

**Comment by craigzour** [comment]
So it is a predefined behaviour ?

**Comment by indirect** [comment]
I don't know what that question means.

**Comment by craigzour** [comment]
Why Thor executable is available in /Users/clement/.rbenv/shims after bundle install when I fetch Thor from official repo (gem 'thor') and not when I fetch it from private repo (gem 'thor', :git => 'https://github.com/erikhuda/thor') ?

**Comment by TimMoore** [comment]
@craigzour gems from git are a Bundler-specific feature that isn't supported by Rubygems natively, so they're not stored in the same place as native Rubygems gems.

**Comment by craigzour** [comment]
@TimMoore Oh ok ! Thank you !

**Comment by indirect** [comment]
Because rbenv only knows how to create shims for regular rubygems, not for git gems. Always use `bundle exec`.

**Comment by craigzour** [comment]
@indirect Alright ! Thanks
