### ISSUE TITLE
Dependency Restriction using Platforms doesn't behave as expected.

### ISSUE THREAD

**Issue by bryanrite** [bundler/bundler#3340]
While trying to support 1.9.2 in a gem I maintain, I'm trying to restrict a library version: i18n >= 0.7 doesn't work on < ruby 1.9.3.

My gemfile looks like:
```
gem "activerecord", "~> 3.2.0", :require => "active_record"
gem "i18n", "~> 0.6.0", :platforms => [:ruby_19, :ruby_18]
```
ActiveRecord lists `"i18n", "~> 0.6"` as a dependency. I would think that limiting to `"~> 0.6.0"` would only apply to the two platforms (ruby 1.9.x and ruby 1.8.x), but:

```
$ ruby -v
ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-darwin14.0]

$ bundle update
...
Using i18n 0.6.11 (was 0.7.0)
...
```

It appears to limit i18n to `~> 0.6.0` for all versions of ruby, not just 1.9 and 1.8 as expected.

Thanks so much!

**Comment by TimMoore** [comment]
That isn't how the platform option is intended to work. When you add a platform, that means that Bundler will not require that gem to be installed when you run it on other platforms. It _does_ consider it when resolving gems versions and dependencies. If it didn't, then there could be cascading effects causing other gems to be resolved differently, and you could end up with a completely different set of versions on different platforms.

If you'd like to test your gem with different versions of a dependency, the way that's commonly done is to have multiple Gemfiles that each specify an exact version, and then use the `BUNDLE_GEMFILE` environment variable to say which one you want to use.

Check out http://docs.travis-ci.com/user/languages/ruby/#Testing-against-multiple-versions-of-dependencies-(Ruby-on-Rails%2C-EventMachine%2C-etc) and https://semaphoreapp.com/blog/2013/11/14/how-to-use-different-gemfiles-with-bundler.html

You can also use environment variables in a single Gemfile as described at http://www.schneems.com/post/50991826838/testing-against-multiple-rails-versions/
