### ISSUE TITLE
Credentials in Gemfile should override ones in config

### ISSUE THREAD

**Issue by TimMoore** [bundler/bundler#3343]
See discussion at https://github.com/bundler/bundler/pull/3342#discussion_r22688056

**Comment by indirect** [comment]
Whoops, I guess I misread how it works now. :P I can see the argument for config overriding Gemfile, and I'm not sure which one makes more sense. How do you feel about it?

**Comment by TimMoore** [comment]
Yeah, I'm of two minds about it myself. On the one hand, the config is more personal, so it would make sense to have config take precedence if you're building random Gemfiles (with other credentials? it could happen I guess). On the other hand, the ones in the Gemfile are more obvious, so it could be confusing if you're looking at them right there and they aren't being used.

It would be good to hear from people who actually use this feature (I don't).

Whatever we decide, we should explicitly document it and write a spec for it so that it doesn't change again.

**Comment by TimMoore** [comment]
I'm thinking that regardless of what makes more sense, if the way it currently works is to use what's in the Gemfile, we shouldn't change that in a bug fix release.

**Comment by indirect** [comment]
This is how it works now, happily.
