### ISSUE TITLE
[Probable feature request] Tell bundler to install development dependencies for installed gems

### ISSUE THREAD

**Issue by purbon** [bundler/bundler#3347]
Hi,
 while using bundler to install a few dependencies, I face with the need to request bundler to install also their development dependencies.

This might not be an expected behaviour, but I would like to be able to request bundler to do it, as we can do with regular rubygems. Would like to see what is the main opinion here about that? is this something nice for more people? 

From: http://guides.rubygems.org/command-reference/#gem-install
```
-​-development - Install additional development dependencies
-​-development-all - Install development dependencies for all gems (including dev deps themselves)
```

/cheers

**Comment by indirect** [comment]
Please explain more about why you want this feature, including example uses. Why is this better than checking out a repo and running bundle install? What are you trying to do? How would you enable or disable this option? What would it improve? How are you solving this problem now? Why would Bundler doing this be better than that? Thanks.

**Comment by purbon** [comment]
Thanks for your answer @indirect, I know this is not what is expected from Bundler, but wanted to share anyway in case it might help.

My situation is the next, we use bundler at https://github.com/elasticsearch/logstash to install a set of plugins (gems), if we're in development environment, we aim to have also their development dependencies downloaded so we can for example fun test.

For us having bundler do that, would mean only one fast and reliable way of doing thing.

**Comment by indirect** [comment]
@purbon many (perhaps most) gems cannot run their tests after `gem install foo --development--all`. The Gemfile for each project must be installed using `bundle install` first. I don't think the feature you are requesting will give you the result you want.

If you want to test logstash against gems, you should just add those gems to the logstash Gemfile and use them. Development gems aren't needed.

**Comment by purbon** [comment]
Thanks for the comments @indirect.
