### ISSUE TITLE
BUNDLE_IGNORE_CONFIG ignored for "bundle package --all"

### ISSUE THREAD

**Issue by jacobat** [bundler/bundler#3352]
Running `bundle package --all` creates a new config, even if I tell Bundler to ignore configs:
```sh
$ export BUNDLE_IGNORE_CONFIG=1
$ rm -r .bundle
$ bundle package --all
...
$ find .bundle/config
.bundle/config
```
I would expect Bundler not to write a config when running with `BUNDLE_IGNORE_CONFIG`.

**Comment by agis-** [comment]
From the man page:

> Executing bundle with the `BUNDLE_IGNORE_CONFIG` environment variable set will
cause it to ignore all configuration.

I don't think it's implied that Bundler will not *write* to the config. It states that it will not *read* from it.

So I don't think this is an issue? /cc @segiddins

**Comment by segiddins** [comment]
👍🏻 to what @agis- said, makes total sense
