### ISSUE TITLE
Errors printed to STDOUT, not STDERR.

### ISSUE THREAD

**Issue by jnraine** [bundler/bundler#3353]
All errors rescued by [friendly_error.rb](https://github.com/bundler/bundler/blob/master/lib/bundler/friendly_errors.rb) are printed to STDOUT.

```shell
$ bundle install --foo-bar
Unknown switches '--foo-bar'
$ bundle install --foo-bar > /dev/null
$ bundle install --foo-bar 2> /dev/null
Unknown switches '--foo-bar'
```

Is this intentional? It tripped me up while writing specs for https://github.com/bundler/bundler/pull/3351 – the error messages were not being printed after the bundle command failed because the standard error buffer was empty: https://github.com/bundler/bundler/blob/master/spec/support/helpers.rb#L136

It's a pretty subtle issue that isn't likely to affect many people, but if it's unintentional behaviour it may be worth updating.

**Comment by indirect** [comment]
Yeah, we should fix this.

**Comment by jnraine** [comment]
I spend some time looking into this tonight and it's not as simple as I'd have hoped. 

`#with_friendly_errors` passes a string to `Bundler.ui.error` which calls `Bundler::UI::Shell#tell_me` with the string and `:red`. Eventually, the string is passed to `Thor::Shell::Basic#say` where it is formatted and printed to stdout. 

The tricky bit is that `Thor::Shell::Basic` doesn't provide a way to print a message to stderr except for `Thor::Shell::Basic#error`, which is intended for internal use by Thor only and doesn't provide colour or width formatting.

So, either we write methods that do the formatting and printing to STDERR outside of Thor, write a method that calls into the guts of Thor for formatting and then print it ourselves, or add a method / modify a method in Thor directly (e.g., `Thor::Shell::Basic#say_error` or `Thor::Shell::Basic#say("foo", error: true)`.

None of these options are great, but for the sake of doing the least work and not hacking dependencies, I think the second option is my favourite. Maybe something like:

```ruby
# lib/bundler/ui/shell.rb
def say_error(message = '', color = nil, force_new_line = (message.to_s !~ /( |\t)\Z/))
  buffer = @shell.prepare_message(message, *color)
  buffer << "\n" if force_new_line && !message.end_with?("\n")

  @shell.stderr.print(buffer)
  @shell.stderr.flush
end
```

With tests, we'll notice if Thor changes it's guts when `vendor/` is upgraded and can tweak the method at that time.

I'm all ears for a better solution, as this is a bit gross.

**Comment by indirect** [comment]
pretty sure that’s why we haven’t done it so far. :P your solution is the cleanest one I’ve seen yet!

**Comment by jnraine** [comment]
:smile:

I've submitted a PR with a working implementation. The solution isn't _great_ so feel free to axe it if you don't feel it's clean enough.

**Comment by savulchik** [comment]
+1 for fixing this issue

**Comment by segiddins** [comment]
This was done in https://github.com/bundler/bundler/commit/300fcbe2a06b9b44d1935e01a1548be22949ffaa, which will ship in Bundler 2.0.
