### ISSUE TITLE
"bundle package" support for --frozen

### ISSUE THREAD

**Issue by philwhln** [bundler/bundler#3356]
Trying to use "bundle package --frozen", but it's not a supported switch as it is with "bundle install".

```
$ bundle package --frozen
Unknown switches '--frozen'
```

Internally "bundle package" calls "bundle install", which it passes its parsed options to, so it should be trivial to support this and the entire "bundle install" options should probably be supported by "bundle package".

**Comment by indirect** [comment]
Right now, you should call install first and then package. We'll think about expanding the options that package supports in the future.

**Comment by philwhln** [comment]
> you should call install first and then package

Thanks for the tip!

Our current (untested) workaround proposal is use BUNDLE_FROZEN environment variable.
