### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by Rlin415** [bundler/bundler#3357]
Can someone help me out here with installing Bundler? When I enter the command gem install bundler I get an this error -- ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Library/Ruby/Gems/2.0.0 directory. How do I gain permission to the directory?

**Comment by segiddins** [comment]
`sudo gem install bundler`

**Comment by Rlin415** [comment]
Thank you! It works now!
