### ISSUE TITLE
HTTPUnprocessableEntity error: Too many gems?

### ISSUE THREAD

**Issue by TrevorHinesley** [bundler/bundler#3362]
I've never seen this before. I'm using Bundler 1.5.3 and this randomly started happening when trying to `bundle` in my Rails repo. It has roughly 30 gems. I've used Bundler on projects twice this size without this issue. Using `bundle --full-index` works but takes forever. Why is this suddenly coming up? Here's the full error:

```
Fetching gem metadata from https://rubygems.org/...
Retrying dependency api due to error (2/3): Bundler::HTTPError Net::HTTPUnprocessableEntity: Too many gems (use --full-index instead)
Retrying dependency api due to error (3/3): Bundler::HTTPError Net::HTTPUnprocessableEntity: Too many gems (use --full-index instead)
```

**Comment by indirect** [comment]
Upgrade to Bundler 1.7.2.

**Comment by westonganger** [comment]
issue still occuring in 1.7.12

**Comment by indirect** [comment]
https://github.com/bundler/bundler/blob/master/ISSUES.md

**Comment by alexfalkowski** [comment]
I get this when I run bundle outdated. Is the above supposed to point to the solution?

**Comment by indirect** [comment]
@alexfalkowski First, upgrade to the latest version of Bundler with `gem install bundler`. If you're still getting the error message after that, follow its instructions and run `bundle update --full-index`.

**Comment by indirect** [comment]
@TrevorHinesley @westonganger I'm closing this issue because neither of you have provided the information requested in [ISSUES](https://github.com/carlhuda/bundler/blob/master/ISSUES.md), but feel free to open a ticket with that information if you are still seeing this problem.

**Comment by alexfalkowski** [comment]
@indirect I have followed the instructions. I have no problem installing or updating the gems. The only issue I have is when I run bundle outdated and I get

```ruby
Bundler::HTTPError Net::HTTPUnprocessableEntity: Too many gems (use --full-index instead)
```

Though I can't pass --full-index to bundle outdated as I get

```ruby
Unknown switches '--full-index'
```

Any help would be greatly appreciated.

**Comment by indirect** [comment]
@alexfalkowski follow the instructions in [ISSUES](https://github.com/bundler/bundler/blob/master/ISSUES.md), which include instructions on how to file a ticket.

**Comment by alexfalkowski** [comment]
Cool
