### ISSUE TITLE
bundler treating pre-release version higher than major release versions

### ISSUE THREAD

**Issue by pencilcheck** [bundler/bundler#3364]
I was upgrading from rails 4.1.1 to 4.2.0 and I couldn't. This is the error I get when I run `bundle update rails`

```
$ bundle update rails
Fetching source index from https://rails-assets.org/
Fetching source index from https://rubygems.org/
Resolving dependencies....
Bundler could not find compatible versions for gem
"activesupport":
  In Gemfile:
    rails (= 4.2.0) ruby depends on
      activesupport (= 4.2.0) ruby

    rails (= 4.2.0) ruby depends on
      actionmailer (= 4.2.0) ruby depends on
        rails-dom-testing (>= 1.0.5, ~> 1.0) ruby depends on
          activesupport (4.2.0.beta1)
```

And my Gemfile
https://gist.github.com/27a23219f4e39d789d8c

ruby 2.1.3
bundler 1.7.12
rubygem 2.4.5

I have submit a bug report to rails-dom-testing at https://github.com/rails/rails-dom-testing/issues/33#issuecomment-71587640

And we both recognize that this could be a upstream bug.

**Comment by rafaelfranca** [comment]
Just tried to reproduce it in a minimal Gemfile.

Just having Rails in the Gemfile I could not reproduce the issue. My [Gemfile and Gemfile.lock before the bundle update](https://gist.github.com/rafaelfranca/9aed7139ee5cc6e9ac4c).

I just changed the Gemfile to use Rails 4.2.0 and run bundle update and everything worked fine.

My env:

Ruby 2.2.0
bundler 1.7.12
rubygem 2.4.5

gem env

```
RubyGems Environment:
  - RUBYGEMS VERSION: 2.4.5
  - RUBY VERSION: 2.2.0 (2014-12-25 patchlevel 0) [x86_64-darwin14]
  - INSTALLATION DIRECTORY: /opt/rubies/2.2.0/lib/ruby/gems/2.2.0
  - RUBY EXECUTABLE: /opt/rubies/2.2.0/bin/ruby
  - EXECUTABLE DIRECTORY: /opt/rubies/2.2.0/bin
  - SPEC CACHE DIRECTORY: /Users/rafaelfranca/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /opt/rubies/2.2.0/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-14
  - GEM PATHS:
     - /opt/rubies/2.2.0/lib/ruby/gems/2.2.0
     - /opt/boxen/rbenv/plugins/rbenv-gem-rehash
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - "gem" => "--no-ri --no-rdoc"
     - :benchmark => false
     - :sources => ["http://rubygems.org"]
  - REMOTE SOURCES:
     - http://rubygems.org
  - SHELL PATH:
     - /opt/boxen/rbenv/versions/2.2.0/bin
     - /opt/boxen/rbenv/libexec
     - /usr/local/heroku/bin
     - bin
     - /opt/boxen/packer
     - /opt/boxen/heroku/bin
     - /opt/boxen/rbenv/shims
     - /opt/boxen/rbenv/bin
     - /opt/boxen/ruby-build/bin
     - /opt/boxen/phantomenv/shims
     - /opt/boxen/phantomenv/bin
     - node_modules/.bin
     - /opt/boxen/nodenv/shims
     - /opt/boxen/nodenv/bin
     - /opt/boxen/homebrew/bin
     - /opt/boxen/homebrew/sbin
     - /opt/boxen/bin
     - /Users/rafaelfranca/Projects/github/elixir/bin
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /opt/X11/bin
     - ~/Scripts
```

I believe some other gem in your Gemfile is locking Rails and bundler is just giving pointing to the wrong gem.

**Comment by rafaelfranca** [comment]
@pencilcheck what happen if you call just `bundle update`?

**Comment by pencilcheck** [comment]
@rafaelfranca last time I run it goes into infinite loop with "Resolving dependencies ................................................" and the dots just keeps going. This time I will wait a bit longer and see what happens.

**Comment by pencilcheck** [comment]
Actually, this time it worked!! Then I wonder why updating individual gem will not work hmmm

**Comment by rafaelfranca** [comment]
Look at which gems changed when you using `bundle update`. Maybe another gem was freezing the Rails version.

**Comment by pencilcheck** [comment]
It's a long list, including some changes recommended by the documentation to upgrading rails for example 'responders', 'web-console', etc

https://gist.github.com/0f96fef5412ff938eff8

**Comment by rafaelfranca** [comment]
ng_classify, slim-rails and responders lock Rails to < 4.2. So my suspicion that bundler is pointing to the wrong gem may be correct.

**Comment by pencilcheck** [comment]
Confirmed. 

So bundler cannot detect those gems and upgrade them as well? Would be nice if bundler can only update gems that are also not satisfying the new requirements introduced after upgrading. After running `bundle update` there are too many gem updated that my app just start acting weird, some css are not showing up, some gems are not working properly.

**Comment by rafaelfranca** [comment]
The whole point of bundler is not auto upgrade gems unless requested. The problem here is that it is pointing to the wrong gem, but given it point to the right gem you could do:

```
bundle update rails ng_classigy slim-rails responders
```

and I believe everything would work fine.

**Comment by pencilcheck** [comment]
@rafaelfranca oh yea, you are right, that worked. bundler was pointing to the wrong gem, now I am upgraded to 4.2.0 without upgrading all other gems. Thanks!

Then I wonder how it pointed to the wrong gem in the first place hmm.

**Comment by TimMoore** [comment]
I'm trying to reproduce this, and I get a different error:

```
Bundler could not find compatible versions for gem "railties":
  In Gemfile:
    activeadmin (>= 0) ruby depends on
      inherited_resources (!= 1.5.0, ~> 1.4) ruby depends on
        responders (>= 0) ruby depends on
          railties (< 4.2, >= 3.2) ruby

    rails (= 4.2.0) ruby depends on
      railties (4.2.0)
```

but that's probably because it resolved differently in the first place. @pencilcheck could you add your original (pre-upgrade) `Gemfile.lock` to the gist please?

It's possible that there's a bug here, but I'm not sure. When you have a `Gemfile` with a lot of dependencies and few constraints, there are a lot of possible failing combinations. Bundler shouldn't error out when there is a successful combination (although it might take a long time to find) but if it can't find a working combination, there could be a lot of different potential fixes and it only prints an error based on the last candidate that it tried. If you want to get extremely verbose output to see everything that it tries as it goes, set the `DEBUG_RESOLVER` environment variable (e.g., `DEBUG_RESOLVER=1 bundle update rails`).

**Comment by pencilcheck** [comment]
I fixed the issue with the suggestions from @rafaelfranca but I just happen to reproduce another case here, let me gist the original Gemfile.lock before upgrade and the offending Gemfile configurations.

Gemfile.lock  
https://gist.github.com/b58b022431ad15c11db5  

Gemfile  
https://gist.github.com/7cddc4438c322a8f4297  

I am trying to upgrade rspec to ~> 3.1 (I commented it out but try uncomment it), the error I got when I run `bundle update rspec`
```
Bundler could not find compatible versions for gem
"rspec-expectations":
  In Gemfile:
    rspec-rails (~> 3.0.0) ruby depends on
      rspec-expectations (~> 3.0.0) ruby

    rspec-collection_matchers (~> 1.1.2) ruby depends on
      rspec-expectations (2.99.0.beta1)
```

rspec-collection_matchers depends on >= rspec expectations 2.99.0.beta1 somehow is conflicted with rspec-expectations ~> 3.0.0



I have also gist the output running with DEBUG_RESOLVER below:

https://gist.github.com/2620df380dd04f32b7d8

**Comment by mdemare** [comment]
I'm getting this error:

```
Bundler could not find compatible versions for gem "activesupport":
  In Gemfile:
    core (>= 0) ruby depends on
      rails (= 4.2.0) ruby depends on
        activejob (= 4.2.0) ruby depends on
          activesupport (= 4.2.0) ruby

    core (>= 0) ruby depends on
      rails (= 4.2.0) ruby depends on
        actionview (= 4.2.0) ruby depends on
          rails-dom-testing (>= 1.0.5, ~> 1.0) ruby depends on
            activesupport (4.2.0.beta1)
```

Very strange.

**Comment by indirect** [comment]
@mdemare see [ISSUES](https://github.com/bundler/bundler/blob/master/ISSUES.md) and open a ticket, please.

**Comment by TimMoore** [comment]
In Bundler 1.9.1, the error message is slightly different and provides a better pointer to the actual problem:

```
Bundler could not find compatible versions for gem "rspec-expectations":
  In Gemfile:
    rspec-collection_matchers (~> 1.1.2) ruby depends on
      rspec-expectations (>= 2.99.0.beta1) ruby

    rspec-rails (~> 3.0.0) ruby depends on
      rspec-expectations (~> 3.0.0) ruby

    rspec (~> 3.1) ruby depends on
      rspec-expectations (~> 3.1.0) ruby
```

If I also change the `rspec-rails` version constraint to `~> 3.1` then `bundle update rspec` works as expected. @pencilcheck can you confirm?

This `Gemfile` takes quite a long time to resolve. You'll be better served by providing more specific dependency constraints in the `Gemfile`.

**Comment by pencilcheck** [comment]
How do you change the version constraint of a gem? And let me upgrade bundler, I just found out that I was using a very old version (v1.7.12), will let you know how it goes.

**Comment by TimMoore** [comment]
> How do you change the version constraint of a gem?

Just edit the `Gemfile`. The one you sent in the gist has `gem 'rspec-rails', '~> 3.0.0' # for the rails generator` in it, which will prevent updating to version 3.1.

You can change it to `gem 'rspec-rails', '~> 3.1'` if you want to allow any RSpec 3.x version 3.1.0 or greater.

As a shortcut, because `rspec-rails` depends on `rspec` itself, you can leave `rspec` out of your `Gemfile`. Then, you can change the version of `rspec-rails` to keep them more or less in sync.

> And let me upgrade bundler, I just found out that I was using a very old version (v1.7.12), will let you know how it goes.

To be fair to you: v1.7.12 is only about three months old. We've been releasing frequently this year! :smile:
