### ISSUE TITLE
Bundler spams Gemfile lock with the same gem over and over

### ISSUE THREAD

**Issue by jgeiger** [bundler/bundler#3373]
This is the same as #3216, I just didn't want to comment in that closed request.

I am having the issue using Bundler 1.7.12.

Gemfile.lock
     treetop (1.4.15)
       polyglot
+      polyglot
+      polyglot
... snip ...
+      polyglot (>= 0.3.1)
+      polyglot (>= 0.3.1)

**Comment by TimMoore** [comment]
Please post the _full_ output from `bundle env` (cutting out any private credentials if they appear)

**Comment by indirect** [comment]
Closing for lack of information.
