### ISSUE TITLE
"bundle install" doesn't query rubygems.org correctly when an empty source block is defined

### ISSUE THREAD

**Issue by brockspratlen** [bundler/bundler#3377]
We have been seeing very strange behavior with bundler 1.7.12 and the new source block notation.

We have been able to pare down the issue such that it is reproducible with a script: https://gist.github.com/brockspratlen/b634bcc59e506e913fb8#file-source_bug_repro-sh

Essentially, bundler reports that it can't find a given gem in any of our sources, even though the version requested clearly exists on rubygems.org. Explicitly calling ```gem install -v <version>``` and then running ```bundle install``` again fixes the issue for that particular gem, but often bundler stumbles on another gem in the same exact manner. 

Removing all sources from our Gemfile except for ```https://rubygems.org``` gets bundle install working again, but that is not a workable solution for us since we are trying to include gems from a private gem server.

Base Gemfile (used in the reproduction script):

```
source 'https://rubygems.org'

source 'https://rails-assets.org' do
end

gem 'geocoder', '1.1.2'
```

Output from ```bundle env```:

```
Bundler 1.7.12
Ruby 2.2.0 (2014-12-25 patchlevel 0) [x86_64-linux]
Rubygems 2.4.5
GEM_HOME
```

Other pertinents:

* Ubuntu 14.04 LTS
* Ruby 2.2.0 installed system-wide (no ruby version managers in use)
* Reproduced (with the provided script) against a fresh install of the OS and ruby via Docker

This may be related to #3368, not sure though.

Also, if you want an environment identical to the one we use to reproduce the bug, here is the Dockerfile we used: https://gist.github.com/brockspratlen/b634bcc59e506e913fb8#file-dockerfile

**Comment by brockspratlen** [comment]
Just to be clear - we don't actually have an empty source block in our app's Gemfile. Just thought it would help clarify things if we showed the absolute simplest reproduction case.

**Comment by TimMoore** [comment]
This should be fixed in 1.7.13. Please try upgrading and let us know if you still have any problems.

**Comment by misha-slyusarev** [comment]
I caught this with Bundler version 1.10.6 and Ruby 2.1.1. 

As described above I have my private gem inside 'source' block and it has various public dependencies which I have to install explicitly before 'bundle install'. I use Jenkins.

Any thoughts what might be wrong?

**Comment by indirect** [comment]
@misha-slyusarev this issue is closed. please open a new ticket following [ISSUES](https://github.com/bundler/bundler/blob/master/ISSUES.md).
