### ISSUE TITLE
Gem found in multiple sources warning appears when using source block.

### ISSUE THREAD

**Issue by BenMorganIO** [bundler/bundler#3378]
Using this as a Gemfile:

```ruby
source "https://rubygems.org"

source "https://rails-assets.org" do
  gem "rails-assets-angular"
end
```

And after running `bundle` you should receive this warning:

```ruby
Your bundle is complete!
Use `bundle show [gemname]` to see where a bundled gem is installed.
Warning: the gem 'rails-assets-angular' was found in multiple sources.
Installed from: https://rails-assets.org/
Also found in:
  * https://rubygems.org/
You should add a source requirement to restrict this gem to your preferred source.
For example:
    gem 'rails-assets-angular', :source => 'https://rails-assets.org/'
```

I don't believe this warning should be presented since the gem `rails-assets-angular` is being contained with a `source` block.

**Comment by unchris** [comment]
We're seeing this as well with Bundler 1.7.11. We've wrapped some gems in one source block, and the rest of the gems in another source block and get:

```bash
Warning: the gem 'rest-client' was found in multiple sources.
Installed from: https://rubygems.org/
Also found in:
  * https://code.stripe.com/
You should add a source requirement to restrict this gem to your preferred source.
For example:
    gem 'rest-client', :source => 'https://rubygems.org/'
Warning: the gem 'stripe' was found in multiple sources.
Installed from: https://code.stripe.com/
Also found in:
  * https://rubygems.org/
You should add a source requirement to restrict this gem to your preferred source.
For example:
    gem 'stripe', :source => 'https://code.stripe.com/'
```

We've also tried simply specifying the `:source` property instead of using the block syntax and that doesn't help either.

**Comment by indirect** [comment]
I can't reproduce this using the given Gemfiles, on Bundler 1.7.11, 1.7.12, or 1.7.13.pre. Please upgrade to the latest version of bundler (`gem install bundler`), and then provide the information requested in [ISSUES](https://github.com/bundler/bundler/blob/master/ISSUES.md) if this is still an issue for you.
