### ISSUE TITLE
bundle install doesn't search referenced gems in all sources

### ISSUE THREAD

**Issue by krumts** [bundler/bundler#3381]
I am using bundler 1.7.12 and have currently the following issue:

I have a Gemfile specifying multiple sources - one is a private geminabox repo containing some patched gems, and the second is rubygems.org from which I expect to get the rest.
```
# use an internal gem repo for patched gems
source "https://rubygems.org"

gem "colorize"
gem "erubis"

source "http://somerepo/geminabox" do
  gem "gem_a", "1.0.1"
  gem "gem_b", "1.0.1"
end
```

Additionally gem_a has a dependency on fog 1.23.0, and (I think this is causing the issue) in the private repo there is a very old version of fog (1.5.x).

The result at the end is:
```
Could not find gem 'fog (~> 1.23.0) ruby', which is required by gem 'gem_a (= 1.0.1) ruby', in any of the sources.
```
Fog is definitely available on rubygems.org in the required version, but it seems that bundler doesn't fall back to search it there if a different version is available in the private repo.

Calling ```bundle install --full-index``` helps - it installs the bundle properly, however I am not sure this is the right thing to do.

I looked for similar issues:
* #3380, but there the error message is not about a referenced bundle
* #3336, but this one should already be fixed in the bundler release I am using

Therefore decided to open a new one.

**Comment by alex-ross** [comment]
Got the same issue with that version

**Comment by felixbuenemann** [comment]
Same issue on 1.7.12, using `--full-index` helped. I'm also using the rails-assets.org source if that matters.

**Comment by TimMoore** [comment]
This should be fixed in 1.7.13. Please try upgrading and let us know if you still have any problems.

**Comment by krumts** [comment]
Works fine now. Thanks a lot for the fix!

**Comment by idoa01** [comment]
I'm using version 1.9.4 of bundler and I'm still having the same issue
Gemfile:
```rb
source 'https://rubygems.org'

source "http://somerepo/geminabox" do
  gem "gem_a", ">=0.2.0"
end
```
`gem_a` depends on `bunny` and I'm getting the following error:
```
Fetching source index from http://somerepo/geminabox
Fetching gem metadata from https://rubygems.org/..
Fetching version metadata from https://rubygems.org/.
Resolving dependencies...
Bundler could not find compatible versions for gem "bunny":
  In Gemfile:
    gem_a (>= 0.2.0) ruby depends on
      bunny (~> 0.9.0.pre7) ruby
Could not find gem 'bunny (~> 0.9.0.pre7) ruby', which is required by gem 'gem_a (>= 0.2.0) ruby', in any of the sources.
```

bundle env:
```
    Bundler   1.9.4
    Rubygems  2.4.5
    Ruby      2.2.0p0 (2014-12-25 revision 49005) [x86_64-linux]

    RVM       1.26.9 (latest)
    Git       1.9.1
    rubygems-bundler (1.4.4)
```

**Comment by indirect** [comment]
Thanks for reporting this issue! Since the problem on this ticket is solved, please open a new ticket, and describe: 1) what you did, 2) what happened, and 3) what you expected to happen.

**Comment by idoa01** [comment]
:+1:
