### ISSUE TITLE
LoadError unless 'bundle install --deployment' is run

### ISSUE THREAD

**Issue by DaniG2k** [bundler/bundler#3384]
I'm reporting this as a bug because I've never had to do this in two years that I've used Bundler.
On my VPS, if I tried to run `rails c production` I was getting the following message:

    $ rails c production
    /home/dani/.rvm/gems/ruby-2.2.0/bin/rails:23:in `load': cannot load such file -- /home/dani/.rvm/gems/ruby-2.2.0/specifications/bin/rails (LoadError)
        from /home/dani/.rvm/gems/ruby-2.2.0/bin/rails:23:in `<main>'
        from /home/dani/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
        from /home/dani/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'

I tried running both `bundle install` and `bundle update` multiple times.
The directory `/home/dani/.rvm/gems/ruby-2.2.0/specifications/` existed and contained a bunch of .gemspec files. However, `/home/dani/.rvm/gems/ruby-2.2.0/specifications/bin/` did not exist.

The output of `bundle show rails` was `/home/dani/.rvm/gems/ruby-2.2.0/gems/rails-4.2.0`. Oddly, the output of `cat /home/dani/myapp/.bundle/config` was `No such file or directory`.

Finally, after running `bundle update` as well as reinstalling Ruby 2.2.0 itself, and remaking every gem pristine, I tried running:

`bundle install --deployment`

Which finally seemed to have fixed the problem.

However, I am not sure if this is the correct solution or if this is an issue with **Bundler 1.7.13**. Can someone please confirm if this is correct or if this is only a temporary solution?

I have posted a thread about this on [StackOverflow](http://stackoverflow.com/questions/28414845/rails-4-passenger-errors-after-updating-gems).

Thanks

**Comment by indirect** [comment]
I'm glad you were able to resolve your problem! Unfortunately, this ticket doesn't contain enought details for me to reproduce the issue, or even really guess what the issue might have been. In the future, please include all of the details requested in [ISSUES](https://github.com/bundler/bundler/blob/master/ISSUES.md) if you think you've discovered a bug in Bundler. Thanks!

**Comment by DaniG2k** [comment]
Hi I will try to include all the details form ISSUES. Disabling the --deployment mode with `bundle install --no-deployment` sets the problem back again so I can possibly help diagnose the issue.

Please note: I've tried all the troubleshooting steps.

The Gist is [here](https://gist.github.com/DaniG2k/ecbf319d982eefa089d0). Please let me know if you need more information. Again, please note that I'm reporting this as a bug because I've never had to run bundle install with --deployment in two years that I've been using it so it seems odd that I'd have to start using it now.

Thanks and kind regards!

**Comment by indirect** [comment]
To be honest, this issue looks like it has nothing to do with Bundler, and more to do with your rvm setup? I've never seen this particular problem before. You definitely should be running `bundle install --deployment` when you deploy, since it helps with other specific problems. If you see this issue crop up again, let us know!

**Comment by DaniG2k** [comment]
Could be, but I reinstalled/recompiled Ruby 2.2.0 using rvm, then I rebuilt every gem as well after removing everything, just to make sure. Still same problem :confounded:

**Comment by DaniG2k** [comment]
Ok so just to be sure, I just ran `$ rvm --force gemset empty`. I get one error message:

`ERROR:  Gem::GemNotInHomeException: Gem 'json-1.8.1' is not installed in directory /home/dani/.rvm/gems/ruby-2.2.0`

If I look at [this StackOverflow thread](http://stackoverflow.com/questions/21095098/why-wont-bundler-install-json-gem) it seems that the culprit was indeed Bundler. The fix, they mention, was to run `gem update bundler`

**Comment by DaniG2k** [comment]
I am convinced this has to do with Bundler. I have reverted all my changes to find out what the error was. I run `bundle install` and then when I run `rails c` I get:

    $ rails c
    git://github.com/radar/by_star (at master) is not yet checked out. Run `bundle install` first.

Please check [this thread](https://github.com/activeadmin/activeadmin/issues/2899) where people were having similar issues and the problem was with Bundler.

**Comment by DaniG2k** [comment]
And a [possible fix](https://coderwall.com/p/yw1jlg/fixing-bundler-issues-like-git-github-com-is-not-checked-out-please-run-bundle-install)?

**Comment by DaniG2k** [comment]
My apologies. I have confirmed with others that there is a [bug](https://github.com/rails/spring/issues/383#issuecomment-73701815) in Spring 1.3.1.

**Comment by DaniG2k** [comment]
I've tried to reinstall rvm, reinstall ruby, reinstall rails, reinstall all gems, ran bundle install, ran bundle update......still same error message :disappointed:

To reproduce: created a new rails 4.2 project, run `rails c` to make sure spring is started, add a git gem to my Gemfile (like gem 'by_star', :git => "git://github.com/radar/by_star"), run `bundle install` and then try to use any spring-related command. This seems to be a git-gem issue with bundler and spring. :confused: :

**Comment by TimMoore** [comment]
I think you need to run `spring stop` whenever you add new gems.

**Comment by cuterxy** [comment]
I solved this problem by running `spring binstub` .
