### ISSUE TITLE
SSL certificate verify fail on ruby gem

### ISSUE THREAD

**Issue by ddezeeuw** [bundler/bundler#3387]
Bundler fails to install because of the SSL certificate which does not verify at rubygems.org.
Maybe this is not the best place for such an error report, and i'm sorry for that.

**Comment by TimMoore** [comment]
I don't think this is the right place, and in any case you haven't provided much information here.

Check the issues in the rubygems tracker — there have been many previous reports of SSL issues, and there are solutions posted in those threads https://github.com/rubygems/rubygems/search?q=SSL&type=Issues&utf8=%E2%9C%93

**Comment by ddezeeuw** [comment]
I'm sorry it's my fault. well.. actually a well known bug, but I had to search better for it.
I fixed it by following this link  https://gist.github.com/luislavena/f064211759ee0f806c88 . It explains why it breaks and offers a fix. (the gems demand a specific ruby version which mismatches with the current SSL certificates) - I leave this here for someone who has the same problems.
