### ISSUE TITLE
Issue when running bundle install

### ISSUE THREAD

**Issue by iamgenius** [bundler/bundler#3390]
hguerrier@server:~/active_admin$ bundle
Using rake 10.4.2
Using i18n 0.7.0
Using json 1.8.2
Using minitest 5.5.1
Using thread_safe 0.3.4
Using tzinfo 1.2.2
Using activesupport 4.2.0
Using builder 3.2.2
Using erubis 2.7.0
Using mini_portile 0.6.2
Using nokogiri 1.6.6.2
Using rails-deprecated_sanitizer 1.0.3
Using rails-dom-testing 1.0.5
Using loofah 2.0.1
Using rails-html-sanitizer 1.0.1
Using actionview 4.2.0
Using rack 1.6.0
Using rack-test 0.6.3
Using actionpack 4.2.0
Using globalid 0.3.2
Using activejob 4.2.0
Using mime-types 2.4.3
Using mail 2.6.3
Using actionmailer 4.2.0
Using activemodel 4.2.0
Using arel 6.0.0
Using activerecord 4.2.0
Using debug_inspector 0.0.2
Using binding_of_caller 0.7.2
Using columnize 0.9.0
Using debugger-linecache 1.2.0
Using slop 3.6.0
Using byebug 3.5.1
Using coffee-script-source 1.9.0
Using execjs 2.3.0
Using coffee-script 2.3.0
Using thor 0.19.1
Using railties 4.2.0
Using coffee-rails 4.1.0
Using hike 1.2.3
Using multi_json 1.10.1
Using jbuilder 2.2.6
Using jquery-rails 4.0.3
Using bundler 1.8.0
Using tilt 1.4.1
Using sprockets 2.12.3
Using sprockets-rails 2.2.4
Using rails 4.2.0
Using rdoc 4.2.0
Using sdoc 0.4.1
Using spring 1.3.1
Using sqlite3 1.3.10
Using turbolinks 2.5.3
Using uglifier 2.7.0
Using web-console 2.0.0
Updating files in vendor/cache
  * rake-10.4.2.gem
――― ERROR REPORT TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――
- What did you do?
- What did you expect to happen?
- What happened instead?

Error details

    Errno::EACCES: Permission denied @ rb_sysopen - /home/hguerrier/active_admin/vendor/cache/rake-10.4.2.gem
    /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/fileutils.rb:1402:in `initialize'
    /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/fileutils.rb:1402:in `open'
    /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/fileutils.rb:1402:in `block in copy_file'
    /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/fileutils.rb:1401:in `open'
    /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/fileutils.rb:1401:in `copy_file'
    /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/fileutils.rb:483:in `copy_file'
    /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/fileutils.rb:400:in `block in cp'
    /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/fileutils.rb:1579:in `block in fu_each_src_dest'
    /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/fileutils.rb:1593:in `fu_each_src_dest0'
    /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/fileutils.rb:1577:in `fu_each_src_dest'
    /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/fileutils.rb:399:in `cp'
    /usr/local/rvm/gems/ruby-2.1.5/gems/bundler-1.8.0/lib/bundler/source/rubygems.rb:151:in `cache'
    /usr/local/rvm/gems/ruby-2.1.5/gems/bundler-1.8.0/lib/bundler/runtime.rb:116:in `block in cache'
    /usr/local/rvm/gems/ruby-2.1.5/gems/bundler-1.8.0/lib/bundler/runtime.rb:113:in `cache'
    /usr/local/rvm/gems/ruby-2.1.5/gems/bundler-1.8.0/lib/bundler/cli/install.rb:81:in `run'
    /usr/local/rvm/gems/ruby-2.1.5/gems/bundler-1.8.0/lib/bundler/cli.rb:157:in `install'
    /usr/local/rvm/gems/ruby-2.1.5/gems/bundler-1.8.0/lib/bundler/vendor/thor/command.rb:27:in `run'
    /usr/local/rvm/gems/ruby-2.1.5/gems/bundler-1.8.0/lib/bundler/vendor/thor/invocation.rb:121:in `invoke_command'
    /usr/local/rvm/gems/ruby-2.1.5/gems/bundler-1.8.0/lib/bundler/vendor/thor.rb:363:in `dispatch'
    /usr/local/rvm/gems/ruby-2.1.5/gems/bundler-1.8.0/lib/bundler/vendor/thor/base.rb:440:in `start'
    /usr/local/rvm/gems/ruby-2.1.5/gems/bundler-1.8.0/lib/bundler/cli.rb:10:in `start'
    /usr/local/rvm/gems/ruby-2.1.5/gems/bundler-1.8.0/bin/bundle:20:in `block in <top (required)>'
    /usr/local/rvm/gems/ruby-2.1.5/gems/bundler-1.8.0/lib/bundler/friendly_errors.rb:6:in `with_friendly_errors'
    /usr/local/rvm/gems/ruby-2.1.5/gems/bundler-1.8.0/bin/bundle:18:in `<top (required)>'
    /usr/local/rvm/gems/ruby-2.1.5/bin/bundle:23:in `load'
    /usr/local/rvm/gems/ruby-2.1.5/bin/bundle:23:in `<main>'
    /usr/local/rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
    /usr/local/rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'

Environment

    Bundler   1.8.0
    Rubygems  2.4.3
    Ruby      2.1.5p273 (2014-11-13 revision 48405) [x86_64-linux]
    GEM_HOME  /usr/local/rvm/gems/ruby-2.1.5
    GEM_PATH  /usr/local/rvm/gems/ruby-2.1.5:/usr/local/rvm/gems/ruby-2.1.5@global
    RVM       1.26.10 (latest)
    Git       1.9.1
    rubygems-bundler (1.4.4)
――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/bundler/bundler/search?q=Permission+denied+%40+rb_sysopen+-+%2Fhome%2Fhguerrier%2Factive_admin%2Fvendor%2Fcache%2Frake-10.4.2.gem&type=Issues

If there aren't any reports for this error yet, please create copy and paste the report template above into a new issue. Don't forget to anonymize any private data! The new issue form is located at:
https://github.com/bundler/bundler/issues/new

**Comment by TimMoore** [comment]
This looks like you don't have permission to write to `/home/hguerrier/active_admin/vendor/cache`. Could you check the permissions on that directory and any files inside it?

**Comment by phansaorin** [comment]
I have met this problem too. Could you detail than this.

**Comment by TimMoore** [comment]
@phansaorin could you please open a new issue with all of the information requested at https://github.com/bundler/bundler/blob/master/ISSUES.md#reporting-unresolved-problems?

**Comment by phansaorin** [comment]
@TimMoore this is my issue.
 First, try this link to see if there are any existing issue reports for this error:
https://github.com/bundler/bundler/search?q=%28%3Cunknown%3E%29%3A+could+not+find+expected+%27%3A%27+while+scanning+a+simple+key+at+line+24+column+1&type=Issues

If there aren't any reports for this error yet, please create copy and paste the report template above into a new issue. Don't forget to anonymize any private data! The new issue form is located at:
https://github.com/bundler/bundler/issues/new
