### ISSUE TITLE
Bundler sometimes doesn't find gems on 1.8.0

### ISSUE THREAD

**Issue by corbt** [bundler/bundler#3393]
It looks like there is a regression in 1.8.0 leading to bundler not finding gems in some cases.

When running my Rails server with the Puma gem, the command "bundle exec puma" throws the following error:

```
/usr/local/rbenv/versions/2.2.0/lib/ruby/2.2.0/rubygems/dependency.rb:315:in `to_specs': Could not find 'rack' (= 1.6.0) among 10 total gem(s) (Gem::LoadError)
Checked in 'GEM_PATH=/.gem/ruby/2.2.0:/usr/local/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0', execute `gem env` for more information
	from /usr/local/rbenv/versions/2.2.0/lib/ruby/2.2.0/rubygems/dependency.rb:324:in `to_spec'
	from /usr/local/rbenv/versions/2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_gem.rb:64:in `gem'
	from /srv/www/legacy-video/shared/vendor/bundle/ruby/2.2.0/gems/puma-2.11.0/bin/puma-wild:20:in `block in <main>'
	from /srv/www/legacy-video/shared/vendor/bundle/ruby/2.2.0/gems/puma-2.11.0/bin/puma-wild:18:in `each'
	from /srv/www/legacy-video/shared/vendor/bundle/ruby/2.2.0/gems/puma-2.11.0/bin/puma-wild:18:in `<main>'
```

The above-reported GEM_PATH is the rbenv default, so it looks like bundler is ignoring the bundle entirely. Interestingly, other commands (eg "bundle exec rails console") work fine, and "`bundle env`" shows the gem_path set to the correct bundle path. I didn't change anything in `.bundle/config` either. Puma might be doing something nonstandard, but since reverting to Bundler 1.7.11 fixes the issue, I think this is the right place to report it.

**Comment by indirect** [comment]
This was a bug in Puma, and it is fixed in the latest bugfix release.
