### ISSUE TITLE
O_O

### ISSUE THREAD

**Issue by Walovari** [bundler/bundler#3396]
――― ERROR REPORT TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――
- What did you do?
- What did you expect to happen?
- What happened instead?

Error details

    ArgumentError: Malformed version number string ~> 0.6.0
    /home/walovari/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/version.rb:206:in `initialize'
    /home/walovari/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/version.rb:198:in `new'
    /home/walovari/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/version.rb:198:in `new'
    /home/walovari/.rvm/gems/ruby-2.1.5/gems/bundler-1.8.0/lib/bundler/lockfile_parser.rb:134:in `parse_spec'
    /home/walovari/.rvm/gems/ruby-2.1.5/gems/bundler-1.8.0/lib/bundler/lockfile_parser.rb:98:in `parse_source'
    /home/walovari/.rvm/gems/ruby-2.1.5/gems/bundler-1.8.0/lib/bundler/lockfile_parser.rb:45:in `block in initialize'
    /home/walovari/.rvm/gems/ruby-2.1.5/gems/bundler-1.8.0/lib/bundler/lockfile_parser.rb:39:in `each'
    /home/walovari/.rvm/gems/ruby-2.1.5/gems/bundler-1.8.0/lib/bundler/lockfile_parser.rb:39:in `initialize'
    /home/walovari/.rvm/gems/ruby-2.1.5/gems/bundler-1.8.0/lib/bundler/definition.rb:57:in `new'
    /home/walovari/.rvm/gems/ruby-2.1.5/gems/bundler-1.8.0/lib/bundler/definition.rb:57:in `initialize'
    /home/walovari/.rvm/gems/ruby-2.1.5/gems/bundler-1.8.0/lib/bundler/dsl.rb:161:in `new'
    /home/walovari/.rvm/gems/ruby-2.1.5/gems/bundler-1.8.0/lib/bundler/dsl.rb:161:in `to_definition'
    /home/walovari/.rvm/gems/ruby-2.1.5/gems/bundler-1.8.0/lib/bundler/dsl.rb:11:in `evaluate'
    /home/walovari/.rvm/gems/ruby-2.1.5/gems/bundler-1.8.0/lib/bundler/definition.rb:25:in `build'
    /home/walovari/.rvm/gems/ruby-2.1.5/gems/bundler-1.8.0/lib/bundler.rb:155:in `definition'
    /home/walovari/.rvm/gems/ruby-2.1.5/gems/bundler-1.8.0/lib/bundler/cli/install.rb:78:in `run'
    /home/walovari/.rvm/gems/ruby-2.1.5/gems/bundler-1.8.0/lib/bundler/cli.rb:157:in `install'
    /home/walovari/.rvm/gems/ruby-2.1.5/gems/bundler-1.8.0/lib/bundler/vendor/thor/command.rb:27:in `run'
    /home/walovari/.rvm/gems/ruby-2.1.5/gems/bundler-1.8.0/lib/bundler/vendor/thor/invocation.rb:121:in `invoke_command'
    /home/walovari/.rvm/gems/ruby-2.1.5/gems/bundler-1.8.0/lib/bundler/vendor/thor.rb:363:in `dispatch'
    /home/walovari/.rvm/gems/ruby-2.1.5/gems/bundler-1.8.0/lib/bundler/vendor/thor/base.rb:440:in `start'
    /home/walovari/.rvm/gems/ruby-2.1.5/gems/bundler-1.8.0/lib/bundler/cli.rb:10:in `start'
    /home/walovari/.rvm/gems/ruby-2.1.5/gems/bundler-1.8.0/bin/bundle:20:in `block in <top (required)>'
    /home/walovari/.rvm/gems/ruby-2.1.5/gems/bundler-1.8.0/lib/bundler/friendly_errors.rb:6:in `with_friendly_errors'
    /home/walovari/.rvm/gems/ruby-2.1.5/gems/bundler-1.8.0/bin/bundle:18:in `<top (required)>'
    /home/walovari/.rvm/gems/ruby-2.1.5/bin/bundle:23:in `load'
    /home/walovari/.rvm/gems/ruby-2.1.5/bin/bundle:23:in `<main>'
    /home/walovari/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
    /home/walovari/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'

Environment

    Bundler   1.8.0
    Rubygems  2.4.5
    Ruby      2.1.5p273 (2014-11-13 revision 48405) [x86_64-linux]
    GEM_HOME  /home/walovari/.rvm/gems/ruby-2.1.5
    GEM_PATH  /home/walovari/.rvm/gems/ruby-2.1.5:/home/walovari/.rvm/gems/ruby-2.1.5@global
    RVM       1.26.10 (master)
    Git       2.3.0
    rubygems-bundler (1.4.4)
――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

**Comment by TimMoore** [comment]
We'll need to see your Gemfile and Gemfile.lock to diagnose this.

**Comment by Walovari** [comment]
Gemfile http://pastebin.com/K9EJg4fP 
Gemfile.lock http://pastebin.com/e75ZUv3k

**Comment by indirect** [comment]
Fixed in 52660ae35b728b419e8cb4ea6fa8b4595cf21969.
