### ISSUE TITLE
Standalone binstub broken for rake-10.4.2 on MRI 2.2

### ISSUE THREAD

**Issue by pd** [bundler/bundler#3401]
Given this Gemfile:

~~~ruby
source 'https://rubygems.org'
gem 'rake'
~~~

Running `bundle install --binstubs --standalone --deployment` results in a `vendor/bundle` that does not include rake, a `bin/rake` binstub which loads my _local_ (shipped-with-ruby) rake, and a `setup.rb` that also references my local ruby's rake.

I noticed this when attempting to deploy an application on MRI 2.2.0.

To reproduce:

~~~
$ ruby -v && gem -v && bundle --version && rake --version
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin14]
2.4.5
Bundler version 1.8.2
rake, version 10.4.2

$ cat Gemfile
source 'https://rubygems.org'
gem 'rake'

$ bundle && bundle install --binstubs --standalone --deployment
Fetching gem metadata from https://rubygems.org/..
Fetching version metadata from https://rubygems.org/.
Resolving dependencies...
Using rake 10.4.2
Using bundler 1.8.2
Bundle complete! 1 Gemfile dependency, 2 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
Using rake 10.4.2
Using bundler 1.8.2
Bundle complete! 1 Gemfile dependency, 2 gems now installed.
Bundled gems are installed into ./vendor/bundle.

$ tree vendor
vendor
└── bundle
    ├── bundler
    │   └── setup.rb
    └── ruby
        └── 2.2.0

4 directories, 1 file

$ tail -1 bin/rake
load File.expand_path '../../../../.rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/rake-10.4.2/bin/rake', __FILE__
~~~

Note that `vendor/bundle/ruby/2.2.0` is empty, and the binstub is walking all the way up to my `~/.rubies/...` directory.

On 2.1.5:

~~~
$ rm -rf .bundle Gemfile.lock bin vendor
$ ruby -v && gem -v && bundle --version && rake --version
ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-darwin14.0]
2.4.5
Bundler version 1.8.2
rake, version 10.4.2

$ bundle && bundle install --binstubs --standalone --deployment
Using rake 10.4.2
Using bundler 1.8.2
Bundle complete! 1 Gemfile dependency, 2 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
Fetching gem metadata from https://rubygems.org/..
Fetching version metadata from https://rubygems.org/.
Using bundler 1.8.2
Installing rake 10.4.2
Bundle complete! 1 Gemfile dependency, 2 gems now installed.
Bundled gems are installed into ./vendor/bundle.

$ tail -1 bin/rake
load File.expand_path '../../vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/bin/rake', __FILE__
~~~

As best I can tell, nothing but the ruby version involved is any different. =\

If I change my rake dependency to, say, `'10.4.1'`, bundler properly includes it in the bundle.

**Comment by indirect** [comment]
That rake version is included with that version of Ruby. This isn't a bug.

**Comment by pd** [comment]
The binstub is generated, but points at a path that won't be present on the machine we deploy to (unless you get really, really lucky with `../../../../` etc).

Should the binstub be skipped? As it stands now, `bin/rake` on a remote machine fails instantly.

**Comment by indirect** [comment]
I see. Yeah, that's a bug. Special-casing gems built in to Ruby is such a pain. :( We should point that binstub at the directory of the rake that's built in to Ruby. Thanks for the bug report!

**Comment by TimMoore** [comment]
> We should point that binstub at the directory of the rake that's built in to Ruby.

Is there a machine-independent way to do that?

**Comment by indirect** [comment]
There's a Rubygems method that returns the bin for a given gem, maybe that will work?
