### ISSUE TITLE
Do not apply certs to a gem when running `bundle install` for said gem

### ISSUE THREAD

**Issue by ToadJamb** [bundler/bundler#3402]
Let's say I have a gem that I want to sign with a cert and I have my cert set up to automatically get applied to my gem when I build it. Every time I need to run `bundle install`, I get prompted for the password in order to apply the cert. I fail to see the point in this as this 'version' does not exist as a .gem file. Is there a way to disable applying the cert in this case? Am I missing a reason this behavior is desirable? Or is there currently a way to handle this that I'm missing? (I have done quite a bit of searching and perusing of docs).

**Comment by indirect** [comment]
Running `bundle install` does not build the gems, it installs them. I'm not sure what the question is, here.

**Comment by ToadJamb** [comment]
1. Create a gem certificate that has a password-protected private key.
2. Use that cert. automatically when building gems.
3. Run `bundle install`.
4. Get prompted for the password to your private key.

This is a situation where it seems that applying the cert. is unnecessary and meaningless, as my Gemfile.lock is pointing to the source code for the gem itself.

I know cert's, security and so-on are not a first-class citizen in the ruby/gem ecosystem, which means few people see such things. This particular problem not only requires that you apply a cert. automatically, but that you password-protect your private key for that cert. and I know not many people actually do the former, which means even fewer do the latter, I'm sure.

**Comment by indirect** [comment]
Sorry, I don't even know how to do steps 1 or 2. Please provide all of the information requested in [ISSUES](https://github.com/bundler/bundler/blob/master/ISSUES.md), and if possible gist a script that reproduces your issue from scratch.

**Comment by ToadJamb** [comment]
https://gist.github.com/ToadJamb/12f05d4a84aa82747e3b

I did try to build in a warning that stops and lets the user know in the case that keys already exist, but I think it is still worth noting that this script has potential to overwrite a private key file.

**Comment by ToadJamb** [comment]
https://gist.github.com/ToadJamb/09b6d575f1745ff55988

I did try to build in a warning that stops and lets the user know in the case that keys already exist, but I think it is still worth noting that this script has potential to overwrite a private key file.

**Comment by ToadJamb** [comment]
After running that script once (assuming the keys get created and moved to correct location), all it takes is running `bundle install` from the current path to continue to get prompted for your password.

**Comment by TimMoore** [comment]
@ToadJamb thanks for the reproduction script.

I can reproduce this with Bundler 1.6.2 (which is what you showed in your gist) but not in 1.8.2 (the most recent version). Could you try upgrading and let us know if it solves the problem for you?

**Comment by TimMoore** [comment]
I'll assume this is fixed unless we hear otherwise.
