### ISSUE TITLE
Allow Bundler to bootstrap itself

### ISSUE THREAD

**Issue by sschuberth** [bundler/bundler#3406]
It would be nice if Bundler could be used with a fresh installation of Ruby without even manually installing the Bundler Gem first. For that to work one would only commit the Bundler Gem to the SCM, similar to what "--standalone" currently does for all required Gems. However, all remaining required Gems would be installed by a call to "bundle install" as usual.

**Comment by indirect** [comment]
You can 'rake install' from a checkout of a tag, no need to check in tarballs.

**Comment by sschuberth** [comment]
Sorry, can you elaborate this a bit more? How exactly would I do that starting from my own project that I plan to use Bundler with?

**Comment by indirect** [comment]
Oh I see what you mean. You can already do this. If you have a copy of the bundler gem checked in, run ` gem install /path/to/bundler-1.8.2.gem`.

**Comment by sschuberth** [comment]
That's also not what I was planing to do. I want to check in Bundler itself, not its Gem, into my own project's repository so that I can use that checked in version of Bundler to run `bundle install` and install all remaining required Gems (except the Bundler Gem itself).

**Comment by TimMoore** [comment]
@sschuberth you can accomplish this by setting the `GEM_HOME` environment variable to a relative path like this:

```bash
~/Projects/bundler/issues/testapp $ export GEM_HOME=gems
~/Projects/bundler/issues/testapp $ gem install bundler
Fetching: bundler-1.8.2.gem (100%)
Successfully installed bundler-1.8.2
1 gem installed
~/Projects/bundler/issues/testapp $ gems/bin/bundle -v
Bundler version 1.8.2
```

I like to use this project to sandbox gems in my different projects: https://github.com/postmodern/gem_home

It automates setting your gem home, adjusting your path, etc.

**Comment by sschuberth** [comment]
Thanks @TimMoore, that's what I was looking for.
