### ISSUE TITLE
Should be able to specify rubygems version in Gemfile

### ISSUE THREAD

**Issue by huy** [bundler/bundler#3407]
Currently we can only specify ruby version in Gemfile. It would be useful to have ability to specify also rubygems version. We have encountered a lot of problem when different rubygems version cause failure when installing native extensions.

**Comment by indirect** [comment]
We're working on a fix for gems that depend on certain versions of rubygems, but in the meantime you can simply add a line to your gemfile that raises of the rubygems version is wrong.
