### ISSUE TITLE
Changelog is outdated

### ISSUE THREAD

**Issue by gravis** [bundler/bundler#3408]
Hi,

I noticed the [changelog](https://github.com/bundler/bundler/blob/master/CHANGELOG.md) file is behind releases by 2 versions :(
Any chance to have it updated?

Thanks

**Comment by olivierlacan** [comment]
I'll join the chorus, it's pretty important for a project like bundler to keep its change log up-to-date.

**Comment by segiddins** [comment]
Pretty sure @indirect just hasn't merged 1.8 stable into master since the release of 1.8.0.

**Comment by indirect** [comment]
The changelog is completely up to date. Please look at the CHANGELOG.md file in the git tag of the version you are interested in.




The changelog in master varies depending on the current state of up-merges from version branches.

**Comment by gravis** [comment]
You mean tags (and releases) are ahead master?
Sounds weird to me :)

**Comment by indirect** [comment]
Try running a project with multiple branches that all have active development and releases of different versions at the same time sometime. :)

**Comment by TimMoore** [comment]
master is now up to date with v1.8.2

**Comment by gravis** [comment]
Thanks!
