### ISSUE TITLE
rspec BUNDLE_GEM__TEST setting doesn't add rspec to Gemfile

### ISSUE THREAD

**Issue by olivierlacan** [bundler/bundler#3410]
Causes this error: 
```
bundler-1.8.2/lib/bundler/rubygems_integration.rb:261:in `block in replace_gem': rspec-core is not part of the bundle. Add it to Gemfile. (Gem::LoadError)
```

Wouldn't it make sense to add rspec to the Gemfile when `BUNDLE_GEM__TEST` is set to `rspec` and the new gem is generated with spec directory?

**Comment by olivierlacan** [comment]
Or actually, to the gemspec.

**Comment by indirect** [comment]
Whoops. Yeah, I think that's a bug. Thanks!
