### ISSUE TITLE
Does not respect the versioning ~> directive

### ISSUE THREAD

**Issue by joneslee85** [bundler/bundler#3411]
Since last week, I've had few errors related to versioning conflicts while working on PR for rollbar-gem and newrelic_rpm. What I found that the `~>` does not work, for my case, ActiveSupport 3.2 depends on ~> 0.6 yet bundler (1.8.2) install version 0.7 instead of 0.6.9.

Here is the Travis CI failed build for your investigation: https://travis-ci.org/newrelic/rpm/builds/51044928

**Comment by TimMoore** [comment]
I think you've misunderstood how the `~>` specifier works.

`~> 0.6` expands to `>= 0.6, < 1.0`. In your case, you want to use `~> 0.6.0` (note the extra digit), which expands to `>= 0.6.0, < 0.7`.

Full documentation is at http://guides.rubygems.org/patterns/#pessimistic-version-constraint
