### ISSUE TITLE
“Could not find gem …” error, apparent conflict between `gem … :path` and `gem … :bundle`

### ISSUE THREAD

**Issue by kch** [bundler/bundler#3417]
Minimal repro app here: https://github.com/kch/bundler-source-bug

Original SO question with some details: http://stackoverflow.com/questions/28557998/could-not-find-gem-error-with-bundler-using-custom-gem-source

The SO question doesn't get into what seems to be the issue, which is:

If you require a gem with `gem foo, bundle:…` things work fine. If you require a gem with `gem bar, path:…`, but as soon as you require both at in the same Gemfile, things get borked.

More specifically, bundler is then unable to find any gems with a custom source.

This occurs when the source is passed as a parameter to `gem` or when `source` is called with a block, but not with the traditional `source url` at the top.

/cc @hone @schneems yo.

**Comment by indirect** [comment]
Have you tried this with 1.8.2, which fixed at least one similar issue?

**Comment by kch** [comment]
Yeah versions are listed in the SO question, all latest.

```
$ ruby -v    # => ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin14]
$ gem -v     # => 2.4.5
$ bundle -v  # => Bundler version 1.8.2
```

**Comment by kch** [comment]
Try the repro app. It has zero actual code in it. Unless you count the Gemfile. Just follow the Readme.

**Comment by eagletmt** [comment]
It seems same with #3414 .

**Comment by kch** [comment]
Yup, seems to be the same.

**Comment by TimMoore** [comment]
Closing this in favor of #3414.
