### ISSUE TITLE
Multiple `path` conflict with secondary `source` in Gemfile

### ISSUE THREAD

**Issue by eagletmt** [bundler/bundler#3430]
When `:path` option is used in multiple gems, #3414 issue still exists.
I added a failing spec here: https://github.com/eagletmt/bundler/commit/3ad56c8c34a1493b7ca9d91350ad05a8eaf6f0cd .

**Comment by TimMoore** [comment]
Thanks!

**Comment by macfanatic** [comment]
I can confirm that the following fails for me on a fresh RVM Ruby 1.9.3 install for an older project:

```ruby
source 'https://rubygems.org'

gem 'rails'

source 'internal gem server' do
  gem 'internal_gem'
  gem 'in_development', path: '~/Desktop/in_development'
end
```

Moving the gem with `:path` option outside the source block does not resolve the issue either, it has to be commented out entirely.

On bundler `1.8.3` that was just released.
```

**Comment by TimMoore** [comment]
@eagletmt / @macfanatic would you be able to test out a fix?

https://github.com/TimMoore/bundler/tree/revert-local-rubygems

Clone that repo, check out the `revert-local-rubygems` branch, then run `rake install` to install the patched version.

**Comment by eagletmt** [comment]
I will work since it's virtually equivalent to my #3418 .

**Comment by TimMoore** [comment]
Bundler 1.8.4 has been released with this fix.
