### ISSUE TITLE
Gemfile with source blocks partly working

### ISSUE THREAD

**Issue by schmurfy** [bundler/bundler#3432]
I have a Gemfile with two sources which looks like this:

```ruby
source "xxx"
source 'https://rubygems.org'

gem 'a'
gem 'mygem'
gem 'c'
# [...]
```

when I ran `bundle` with the latest bundler (1.8.3) it said I should provide a block to source to let it know where to pull gems from, this is a really nice feature I wanted so I jumped on it and tried to change my Gemfile to:

```ruby
source "xxx" do
  gem 'mygem'
end

source 'https://rubygems.org'

gem 'a'
gem 'c'
```

and then I ran `bundle`, until then everything is fine, it exited without error and the gem in and outside the block were listed on the output.

Now comes my problems ^^

```
$ bundle install
[...]
Bundle complete! 46 Gemfile dependencies, 99 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.

$ bundle check
Resolving dependencies...
Bundler can't satisfy your Gemfile's dependencies.
Install missing gems with `bundle install`.

$ bundle exec irb
Could not find gem mygem' in rubygems repository http://<myrepo_url>.
Source does not contain any versions of 'mygem'
Run `bundle install` to install missing gems.

```

Did I do something wrong ?

PS: I tried to put the source with block at the end of the file but it changed nothing, same error.

**Comment by jlecour** [comment]
I have the same issue.

**Comment by fracklen** [comment]
Same here

**Comment by TimMoore** [comment]
Thanks for the report. Would any of you be able to test out a fix?

https://github.com/TimMoore/bundler/tree/revert-local-rubygems

Clone that repo, check out the `revert-local-rubygems` branch, then run `rake install` to install the patched version.

**Comment by schmurfy** [comment]
it works for me with your branch :)

**Comment by TimMoore** [comment]
Bundler 1.8.4 has been released with this fix.

**Comment by schmurfy** [comment]
thanks :)

**Comment by fracklen** [comment]
@TimMoore the new version seems to work - partly.
Running ```bundle exec rails s``` starts the process with inconsistent versions of the gems in the block.
Not the versions in the `Gemfile.lock`

Reverting to a `Gemfile` without blocks solves the issue.

**Comment by TimMoore** [comment]
@fracklen could you create a new issue with the details from `bundle env` (replacing any private credentials with dummy credentials)? Also include any other details that might be relevant... for example, what versions of the gems are being used instead of the locked versions?

**Comment by moneypenny** [comment]
1.8.4 fixed the problem for me.

**Comment by venriq** [comment]
I'm using version 1.10.6 of bundler and it doesn't find the gems declared in a source block.

**Comment by indirect** [comment]
Please open a new ticket after following following ISSUES.md.
