### ISSUE TITLE
Remove code of conduct from generated gems

### ISSUE THREAD

**Issue by jimmycuadra** [bundler/bundler#3435]
Bundler 1.8 introduces some new interactive prompts when generating a gem with `bundle gem`. One of the questions asks whether or not you'd like to generate a "code of conduct" file to live in the root of the repository. Bundler should not do this at all.

I understand that it's optional and one can simply say "no," but I don't think a code of conduct is an appropriate thing for Bundler to take a stance on in any fashion. Bundler should be a packaging tool for managing packages. It should be devoid of any opinions on politics. As it's become the de facto tool for managing packages in the Ruby ecosystem, I think Bundler should have a responsibility not to use its prevalence to introduce things that are not related to the technical details of package management in Ruby.

Issue #3305 discusses the danger of using any sort of code of conduct that wasn't actually intended or that won't be upheld by the project maintainers. Bundler should not be a platform for any sort of political or social advocacy. It's simply far out of bounds for what this project should do.

To be clear, I don't think anything in the generated code of conduct is at all unreasonable. I don't disagree that what is described in it is something open source projects should strive for. I simply think it is not Bundler's business how someone runs their project and that it should not take any sort of stance on the matter, even if it is optional but suggested.

One could argue that including a software license by default is also a political statement, and I actually agree with that as well. In that sense, Bundler 1.8 takes a step in a better direction by asking before generating the MIT license (whereas it used to be included unconditionally), but this still has the issue that that the code of conduct does: it implies that you *should* accept a particular policy about your project.

All projects will have ruby files. Bundler should help people package them. Not all projects will want the code of conduct now being suggested to them. People have wildly differing opinions on topics like this, and it's not appropriate for Bundler as a project to take any position on the matter.

Thanks for considering this.

**Comment by indirect** [comment]
Bundler doesn't take a position, it asks you your position. Are you objecting to being asked your position? Or are you objecting to Bundler allowing users who want a code of conduct from being able to generate one?

**Comment by jimmycuadra** [comment]
I'm objecting to:

1) a code of conduct being anything a software package needs by default
2) in the event that a code of conduct is desired, that the document has any sort of pre-filled text that provides a policy that the user did not write themselves

**Comment by jimmycuadra** [comment]
I would consider the presence of this file being "taking a position": https://github.com/bundler/bundler/blob/25f55d96e79f34575fb45da27379091666d48f61/lib/bundler/templates/newgem/CODE_OF_CONDUCT.md.tt

**Comment by segiddins** [comment]
I think Bundler offering to generate a CoC is a wonderful thing, and will hopefully prompt more of the community to consider the fact that their open source gems are not just bits of code, but rather exist in a wider context.

**Comment by indirect** [comment]
Thank you for your input. The Bundler team does not consider the presence of a template file that is _not included by default_ to be taking a position. If you personally don't want to use that file, you not only don't have to use it, you don't have to do anything to not use it.

Have a great day!

**Comment by jimmycuadra** [comment]
> Bundler doesn't take a position, it asks you your position.

It does not ask your position. It asks if you agree with Bundler's default position, without showing you that position before you respond, nonetheless. The text included in the default code of conduct is an extremely specific position, going so far as to link to a website containing details about that position.

**Comment by theckman** [comment]
@indirect You've agreed to accept this in to the codebase and all responsibility that comes with it. That would indicate you agree with its usefulness/position. The actions of the project and your words do not align.

I'm not in disagreement with CoCs. However, this is not something to be solved by bundler IMHO. What technical concern / issue does it address?

**Comment by jimmycuadra** [comment]
> If you personally don't want to use that file, you not only don't have to use it, you don't have to do anything to not use it.

The ability for a user to opt-out is not my complaint. The inclusion of any opinion whatsoever on a non-technical problem is. Asking a simple yes/no question that many users are likely not even to read, and **especially** not presenting them with the text of the policy they're agreeing to uphold, will end up with many projects including this specifically selected policy that is likely not intended, and even if it was intended, has guided the user to make a political choice that was never any of Bundler's business.

**Comment by indirect** [comment]
Since neither of you seem to be reading what I wrote, I'll say it one more time: the default is NO. The file is not included unless the user actively types "yes". I think we're done here.
