### ISSUE TITLE
Support for resolving gems and printing the lockfile to stdout

### ISSUE THREAD

**Issue by cstrahan** [bundler/bundler#3437]
This is related to #3327

-----

Right now, there's only one way to get a lockfile for a given Gemfile without first installing the gems: `bundler package --no-install`. This poses a couple problems for OS packaging:

1. It assumes that bundler can persist that `--no-install` flag in `.bundle/config`, which makes it impossible to shell out to bundler from a third-party tool without polluting the user's current directory and current bundler config.
2. It spends a great deal of time downloading the gems, which isn't necessary if all you want to do is resolve the gem versions and dependency graph, which is all we need for maintaining OS packages (and it also pollutes the current directory).
3. Printing the lockfile to stdout would be more composable, compared to putting the lockfile in the current directory.

Having a way to *just* resolve the dependency graph and print the resulting lockfile would be a huge help for people packaging Ruby applications.

("Packaging" here is a bit overloaded. I'm referring to packaging for package managers, like apt/yum/nix, etc)

**Comment by cstrahan** [comment]
Another idea: instead of adding a new option to the CLI, perhaps an effort could be made to create a stable, public API for such things. A great example would [Cabal](https://www.haskell.org/cabal/), which exposes everything it knows about packing [in its API](http://hackage.haskell.org/package/Cabal).

**Comment by indirect** [comment]
Is that the sound of volunteering that I hear? :)

**Comment by cstrahan** [comment]
@indirect At some point, possibly... But I'm pretty burnt out at the moment. I'd sooner pay someone else to do it (can't do that at the moment, though, as I'm living off of savings).

**Comment by segiddins** [comment]
```ruby
require 'bundler'
puts Bundler.definition(true).to_lock
```

**Comment by indirect** [comment]
Ha. You're much more concise than I am. :) I'm convinced that we need a lock command, though, and we might as well have `lock --print` or `lock --stdout` while we're at it. If anyone wants to implement that, go for it.

**Comment by segiddins** [comment]
What would said `lock` command do without options?

**Comment by indirect** [comment]
Resolve the `Gemfile` and write the lockfile into `Gemfile.lock`, but not install any gems.

**Comment by cstrahan** [comment]
@segiddins That snippet is not quite sufficient; if the required gems aren't installed locally, you get an error along the lines of:

    /home/cstrahan/.gem/ruby/gems/bundler-1.8.3/lib/bundler/resolver.rb:435:in `version_conflict': Could not find gem 'thor (~> 0.19.1) ruby', which is required by gem 'bundix (>= 0) ruby', in any of the sources. (Bundler::VersionConflict)
            from /home/cstrahan/.gem/ruby/gems/bundler-1.8.3/lib/bundler/resolver.rb:233:in `resolve_for_conflict'
            from /home/cstrahan/.gem/ruby/gems/bundler-1.8.3/lib/bundler/resolver.rb:251:in `resolve_conflict'
            from /home/cstrahan/.gem/ruby/gems/bundler-1.8.3/lib/bundler/resolver.rb:374:in `resolve'
            from /home/cstrahan/.gem/ruby/gems/bundler-1.8.3/lib/bundler/resolver.rb:167:in `start'
            from /home/cstrahan/.gem/ruby/gems/bundler-1.8.3/lib/bundler/resolver.rb:129:in `resolve'
            from /home/cstrahan/.gem/ruby/gems/bundler-1.8.3/lib/bundler/definition.rb:193:in `resolve'
            from /home/cstrahan/.gem/ruby/gems/bundler-1.8.3/lib/bundler/definition.rb:266:in `block in to_lock'
            from /home/cstrahan/.gem/ruby/gems/bundler-1.8.3/lib/bundler/definition.rb:262:in `each'
            from /home/cstrahan/.gem/ruby/gems/bundler-1.8.3/lib/bundler/definition.rb:262:in `to_lock'
            from test.rb:2:in `<main>'

**Comment by segiddins** [comment]
```ruby
require 'bundler'
definition = Bundler.definition(true)
definition.resolve_remotely!
puts definition.to_lock
```

**Comment by segiddins** [comment]
@cstrahan take a look at https://github.com/bundler/bundler/issues/3439

**Comment by cstrahan** [comment]
@segiddins Wow, very nice - thank you! :).
