### ISSUE TITLE
[bundle gem] Replace interactive prompts with command options

### ISSUE THREAD

**Issue by postmodern** [bundler/bundler#3443]
Interactive prompts are annoying and disrupt workflow. They should be replaced with command-line options with appropriate default values. Consider adding a `--[no-]-code-of-conduct` option.

**Comment by indirect** [comment]
The option already exists, and the interactive prompts are one-time only. You can even avoid them entirely by setting the config before using bundle gem. Still too annoying?

**Comment by postmodern** [comment]
That seems incredibly confusing to new users. Are you saying the interactive prompts are to configure the defaults? That should go in another command to explicitly configure `bundle gem` defaults. Please, checkout how I handle things in my [ore](https://github.com/ore/ore#readme) gem generator.

**Comment by indirect** [comment]
Yes, the interactive prompts are to configure the defaults. There was a public discussion about this on a Bundler ticket, and it ended with consensus from everyone in the discussion that the default values should be "no", there should be an explanation of the implications of "yes", and the responses should be saved for subsequent gems.

I agree that interactive prompts are somewhat annoying, but haven't yet found a better way to ensure that the implications of the yes/no decision are explained.

**Comment by indirect** [comment]
And again, the command prompts already exist. Are you simply asking for the first-run prompt and explanations of MIT and Contributor Covenant be removed? Why are you asking for changes in a feature that you don't use at all?

**Comment by postmodern** [comment]
I don't think a CLI is a good place to explain new/breaking changes to the user. User's rely on CLIs as part of their (sometimes daily) workflow, and any new output is distracting. A better place would be to add the note to the `post_install_message` in the gemspec, or write up a blog post.

The interactive prompts should be removed. `bundle gem` should generate a gem without _any_ interactive prompts, ever. Now, whether `LICENSE.txt` and `CODE_OF_CONDUCT.txt` are generated by default, is up to the developers and users. Configuration of the generator defaults should be handled via a separate command. By using a separate command you require the user explicitly make the choice to change the defaults. You also avoid surprising the user when they run `bundle gem` after updating bundler.

But hey, what do I know :P

**Comment by indirect** [comment]
Thanks for your feedback! I've been vaguely entertaining the idea of printing a warning explaining the CoC and license, and asking users to use `bundle config` to choose, similar to how git complains about a missing email and name. @hone, @TimMoore, do you have feelings one way or the other?

**Comment by TimMoore** [comment]
I don't have a big problem with the prompts. I'd rather not invest a lot of time and effort into further changes to `bundle gem`, which has IMHO outlived its original purpose and is outside the scope of Bundler's primary responsibility. I'm happy to see ore and other tools take over the responsibility for gem templates. One template will never suit everyone.

**Comment by nmarley** [comment]
I agree with @postmodern — why the interactive prompts instead of sensible defaults?

**Comment by nmarley** [comment]
> ...and the interactive prompts are one-time only.

It keeps asking me if I want to create a code of conduct, but only if I keep choosing 'no'. If I pick 'yes', then it stops asking. This seems to be either: 1) broken (not setting the default behavior), or 2) a bad design decision. The prompts don't stop unless I say "yes" to that question.

**Comment by pducks32** [comment]
@nmarley I'm not sure whether or not the behavior you discovered is intended or not—though I believe it is—but I issued a PR to fix the problem anyway.

**Comment by indirect** [comment]
@nmarley that's definitely a bug, and I'm really sorry about that. I thought we had a test to make sure it was working correctly. :/

@pducks32 thanks for the patch!
