### ISSUE TITLE
Add a --private option to `bundle gem` for internal gems

### ISSUE THREAD

**Issue by postmodern** [bundler/bundler#3445]
Oftentimes organizations will use `bundle gem` to generate proprietary gems. These gems do not need the following things:

* `bundler/tasks` in the `Rakefile` - wouldn't want to accidentally release it rubygems.org.
* `LICENSE` - by default all code is owned by the organization.
* `CODE_OF_CONDUCT` - organization's own CoC applies.

**Comment by indirect** [comment]
Newly generated gems are unable to be pushed to rubygems.org (or anywhere else) until the allowed push hosts have been set. In addition, new gems lack license and CoC files, so what you are describing is effectively the default. (Admittedly, on a first run, you'll have to push enter three times to save the defaults to the config).

**Comment by postmodern** [comment]
@indirect you can still accidentally run `rake release`. There should be a `--no-release-tasks` option, or such.

**Comment by postmodern** [comment]
@indirect also what if the user allowed `LICENSE` and `CODE_OF_CONDUCT` for their personal projects, but then used `bundle gem` for a commercial gem?

**Comment by indirect** [comment]
Private gems are usually pushed to private gem servers (or at least I hope they are!) which is why we used allowed_push_hosts. What's the use case for no release tasks?

**Comment by indirect** [comment]
Presumably they would either run --no-coc --no-mit or delete the generated files rather than checking them in. I'm open to adding a combined flag if there are people who actually want it, but I'm really only concerned with problems people are actually having, rather than problems we can imagine they might have.

**Comment by postmodern** [comment]
Most organizations do not run a gem server, they simply bundle against the git repo.
