### ISSUE TITLE
bundler fails to install gem

### ISSUE THREAD

**Issue by manish211** [bundler/bundler#3446]
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /home/.rubies/ruby-2.1.3/bin/ruby -r ./siteconf20150228-3404-1f8s19v.rb extconf.rb 
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/home/.rubies/ruby-2.1.3/bin/ruby
extconf.rb:45:in `open': No such file or directory @ dir_initialize - /usr/bin/include (Errno::ENOENT)
	from extconf.rb:45:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /home/.gem/ruby/2.1.3/gems/rjb-1.4.9 for inspection.
Results logged to /home/.gem/ruby/2.1.3/extensions/x86_64-linux/2.1.0-static/rjb-1.4.9/gem_make.out
An error occurred while installing rjb (1.4.9), and Bundler cannot continue.
Make sure that `gem install rjb -v '1.4.9'` succeeds before bundling.

**Comment by TimMoore** [comment]
Sorry, but this isn't a Bundler bug. Try following the instructions in the error message (Make sure that `gem install rjb -v '1.4.9'` succeeds before bundling) and checking the logged output in ` /home/.gem/ruby/2.1.3/extensions/x86_64-linux/2.1.0-static/rjb-1.4.9/gem_make.out`.

You might have some luck searching the rjb gem's issue tracker: https://github.com/arton/rjb/issues?q=
