### ISSUE TITLE
Warn on git protocol URLs

### ISSUE THREAD

**Issue by TimMoore** [bundler/bundler#3448]
We've had a number of pull requests submitted to change the `github` DSL shortcut to use `https` instead of the `git` protocol (most recently #3447).

This breaks backwards compatibility because the URL is expanded before it goes in the lock file, so updating Bundler would create a change in the lock file even without changing the `Gemfile` at all. This can break deployment if the server has a newer version of Bundler than what was used at development time.

The 2.0 branch has already made the change, but in 1.9 we should warn on any `git` protocol URLs (including ones expanded from `github`) and suggest replacing them with explicit URLs or overriding the shortcut in the `Gemfile`.

(Maybe we should even get rid of the shortcut entirely in 2.0 and encourage people to define their own.)

**Comment by indirect** [comment]
:+1:

**Comment by rgb-one** [comment]
I think this issue can be closed following #3453
