### ISSUE TITLE
Psych::SyntaxError: (<unknown>): mapping values are not allowed in this context

### ISSUE THREAD

**Issue by pedrobrasileiro** [bundler/bundler#3454]
I trying execute bundle install 

――― ERROR REPORT TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――
- What did you do?
- What did you expect to happen?
- What happened instead?

Error details

    Psych::SyntaxError: (<unknown>): mapping values are not allowed in this context at line 2 column 33
    /usr/local/rvm/rubies/ruby-2.0.0-p195/lib/ruby/2.0.0/psych.rb:205:in `parse'
    /usr/local/rvm/rubies/ruby-2.0.0-p195/lib/ruby/2.0.0/psych.rb:205:in `parse_stream'
    /usr/local/rvm/rubies/ruby-2.0.0-p195/lib/ruby/2.0.0/psych.rb:153:in `parse'
    /usr/local/rvm/rubies/ruby-2.0.0-p195/lib/ruby/2.0.0/psych.rb:129:in `load'
    /usr/local/rvm/rubies/ruby-2.0.0-p195/lib/ruby/site_ruby/2.0.0/rubygems/config_file.rb:333:in `load_file'
    /usr/local/rvm/rubies/ruby-2.0.0-p195/lib/ruby/site_ruby/2.0.0/rubygems/config_file.rb:198:in `initialize'
    /usr/local/rvm/rubies/ruby-2.0.0-p195/lib/ruby/site_ruby/2.0.0/rubygems.rb:297:in `new'
    /usr/local/rvm/rubies/ruby-2.0.0-p195/lib/ruby/site_ruby/2.0.0/rubygems.rb:297:in `configuration'
    /usr/local/rvm/gems/ruby-2.0.0-p195@global/gems/bundler-1.8.3/lib/bundler/rubygems_integration.rb:49:in `configuration'
    /usr/local/rvm/gems/ruby-2.0.0-p195@global/gems/bundler-1.8.3/lib/bundler/rubygems_integration.rb:72:in `sources='
    /usr/local/rvm/gems/ruby-2.0.0-p195@global/gems/bundler-1.8.3/lib/bundler/fetcher.rb:207:in `specs'
    /usr/local/rvm/gems/ruby-2.0.0-p195@global/gems/bundler-1.8.3/lib/bundler/source/rubygems.rb:309:in `block (2 levels) in remote_specs'
    /usr/local/rvm/gems/ruby-2.0.0-p195@global/gems/bundler-1.8.3/lib/bundler/source/rubygems.rb:307:in `each'
    /usr/local/rvm/gems/ruby-2.0.0-p195@global/gems/bundler-1.8.3/lib/bundler/source/rubygems.rb:307:in `block in remote_specs'
    /usr/local/rvm/gems/ruby-2.0.0-p195@global/gems/bundler-1.8.3/lib/bundler/index.rb:9:in `build'
    /usr/local/rvm/gems/ruby-2.0.0-p195@global/gems/bundler-1.8.3/lib/bundler/source/rubygems.rb:292:in `remote_specs'
    /usr/local/rvm/gems/ruby-2.0.0-p195@global/gems/bundler-1.8.3/lib/bundler/source/rubygems.rb:74:in `specs'
    /usr/local/rvm/gems/ruby-2.0.0-p195@global/gems/bundler-1.8.3/lib/bundler/source/local_rubygems.rb:7:in `specs'
    /usr/local/rvm/gems/ruby-2.0.0-p195@global/gems/bundler-1.8.3/lib/bundler/lazy_specification.rb:53:in `__materialize__'
    /usr/local/rvm/gems/ruby-2.0.0-p195@global/gems/bundler-1.8.3/lib/bundler/spec_set.rb:88:in `block in materialize'
    /usr/local/rvm/gems/ruby-2.0.0-p195@global/gems/bundler-1.8.3/lib/bundler/spec_set.rb:85:in `map!'
    /usr/local/rvm/gems/ruby-2.0.0-p195@global/gems/bundler-1.8.3/lib/bundler/spec_set.rb:85:in `materialize'
    /usr/local/rvm/gems/ruby-2.0.0-p195@global/gems/bundler-1.8.3/lib/bundler/definition.rb:132:in `specs'
    /usr/local/rvm/gems/ruby-2.0.0-p195@global/gems/bundler-1.8.3/lib/bundler/definition.rb:121:in `resolve_remotely!'
    /usr/local/rvm/gems/ruby-2.0.0-p195@global/gems/bundler-1.8.3/lib/bundler/installer.rb:79:in `run'
    /usr/local/rvm/gems/ruby-2.0.0-p195@global/gems/bundler-1.8.3/lib/bundler/installer.rb:18:in `install'
    /usr/local/rvm/gems/ruby-2.0.0-p195@global/gems/bundler-1.8.3/lib/bundler/cli/install.rb:80:in `run'
    /usr/local/rvm/gems/ruby-2.0.0-p195@global/gems/bundler-1.8.3/lib/bundler/cli.rb:157:in `install'
    /usr/local/rvm/gems/ruby-2.0.0-p195@global/gems/bundler-1.8.3/lib/bundler/vendor/thor/command.rb:27:in `run'
    /usr/local/rvm/gems/ruby-2.0.0-p195@global/gems/bundler-1.8.3/lib/bundler/vendor/thor/invocation.rb:121:in `invoke_command'
    /usr/local/rvm/gems/ruby-2.0.0-p195@global/gems/bundler-1.8.3/lib/bundler/vendor/thor.rb:363:in `dispatch'
    /usr/local/rvm/gems/ruby-2.0.0-p195@global/gems/bundler-1.8.3/lib/bundler/vendor/thor/base.rb:440:in `start'
    /usr/local/rvm/gems/ruby-2.0.0-p195@global/gems/bundler-1.8.3/lib/bundler/cli.rb:10:in `start'
    /usr/local/rvm/gems/ruby-2.0.0-p195@global/gems/bundler-1.8.3/bin/bundle:20:in `block in <top (required)>'
    /usr/local/rvm/gems/ruby-2.0.0-p195@global/gems/bundler-1.8.3/lib/bundler/friendly_errors.rb:6:in `with_friendly_errors'
    /usr/local/rvm/gems/ruby-2.0.0-p195@global/gems/bundler-1.8.3/bin/bundle:18:in `<top (required)>'
    /usr/local/rvm/gems/ruby-2.0.0-p195@global/bin/bundle:23:in `load'
    /usr/local/rvm/gems/ruby-2.0.0-p195@global/bin/bundle:23:in `<main>'
    /usr/local/rvm/gems/ruby-2.0.0-p195@global/bin/ruby_executable_hooks:15:in `eval'
    /usr/local/rvm/gems/ruby-2.0.0-p195@global/bin/ruby_executable_hooks:15:in `<main>'

Environment

    Bundler   1.8.3
    Rubygems  2.4.6
    Ruby      2.0.0p195 (2013-05-14 revision 40734) [x86_64-linux]
    GEM_HOME  /usr/local/rvm/gems/ruby-2.0.0-p195@project
    GEM_PATH  /usr/local/rvm/gems/ruby-2.0.0-p195@project:/usr/local/rvm/gems/ruby-2.0.0-p195@global
    RVM       1.26.10 (latest)
    Git       1.9.1
    rubygems-bundler (1.4.4)
――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

**Comment by indirect** [comment]
@tenderlove was this a change in a recent version of psych? I remember that we were seeing this on rubygems.org, too. /cc @arthurnn

**Comment by arthurnn** [comment]
@indirect The error on rubygems.org was a bit different ,https://github.com/rubygems/rubygems.org/pull/894 , it was related to `safe_load` and alises. I dont think thats what is happening here.

@pedrobrasileiro I wonder which gem is causing this, can you post your Gemfile in a gist so I can simulate this error locally?
thanks

**Comment by indirect** [comment]
Closing due to lack of information.
