### ISSUE TITLE
bundler does not pass on --verbose

### ISSUE THREAD

**Issue by ABaumgaertner** [bundler/bundler#3455]
bundler switches to verbose mode, but the parameter is not passed on to gem

**Comment by indirect** [comment]
What does that even mean? Bundler does not call the gem command.

**Comment by ABaumgaertner** [comment]
it invokes devkit if necessary - how can i see the output

**Comment by indirect** [comment]
Bundler does not currently have a way to display that information. If you need that information, we recommend running `gem install GEMNAME --verbose` instead.
