### ISSUE TITLE
RuntimeError: can't modify frozen String

### ISSUE THREAD

**Issue by easyrider-new** [bundler/bundler#3457]
Error details

    RuntimeError: can't modify frozen String
    /usr/lib/ruby/1.9.1/rubygems/version.rb:191:in `strip!'
    /usr/lib/ruby/1.9.1/rubygems/version.rb:191:in `initialize'
    /home/kk/projects/ultravie/Gemfile:47:in `new'
    /home/kk/projects/ultravie/Gemfile:47:in `eval_gemfile'
    /home/kk/.rvm/gems/ruby-1.8.7-p358@ultravie/gems/bundler-1.8.3/lib/bundler/dsl.rb:32:in `instance_eval'
    /home/kk/.rvm/gems/ruby-1.8.7-p358@ultravie/gems/bundler-1.8.3/lib/bundler/dsl.rb:32:in `eval_gemfile'
    /home/kk/.rvm/gems/ruby-1.8.7-p358@ultravie/gems/bundler-1.8.3/lib/bundler/dsl.rb:10:in `evaluate'
    /home/kk/.rvm/gems/ruby-1.8.7-p358@ultravie/gems/bundler-1.8.3/lib/bundler/definition.rb:25:in `build'
    /home/kk/.rvm/gems/ruby-1.8.7-p358@ultravie/gems/bundler-1.8.3/lib/bundler.rb:155:in `definition'
    /home/kk/.rvm/gems/ruby-1.8.7-p358@ultravie/gems/bundler-1.8.3/lib/bundler/cli/install.rb:78:in `run'
    /home/kk/.rvm/gems/ruby-1.8.7-p358@ultravie/gems/bundler-1.8.3/lib/bundler/cli.rb:157:in `install'
    /home/kk/.rvm/gems/ruby-1.8.7-p358@ultravie/gems/bundler-1.8.3/lib/bundler/vendor/thor/command.rb:27:in `run'
    /home/kk/.rvm/gems/ruby-1.8.7-p358@ultravie/gems/bundler-1.8.3/lib/bundler/vendor/thor/invocation.rb:121:in `invoke_command'
    /home/kk/.rvm/gems/ruby-1.8.7-p358@ultravie/gems/bundler-1.8.3/lib/bundler/vendor/thor.rb:363:in `dispatch'
    /home/kk/.rvm/gems/ruby-1.8.7-p358@ultravie/gems/bundler-1.8.3/lib/bundler/vendor/thor/base.rb:440:in `start'
    /home/kk/.rvm/gems/ruby-1.8.7-p358@ultravie/gems/bundler-1.8.3/lib/bundler/cli.rb:10:in `start'
    /home/kk/.rvm/gems/ruby-1.8.7-p358@ultravie/gems/bundler-1.8.3/bin/bundle:20:in `block in <top (required)>'
    /home/kk/.rvm/gems/ruby-1.8.7-p358@ultravie/gems/bundler-1.8.3/lib/bundler/friendly_errors.rb:6:in `with_friendly_errors'
    /home/kk/.rvm/gems/ruby-1.8.7-p358@ultravie/gems/bundler-1.8.3/bin/bundle:18:in `<top (required)>'
    /home/kk/.rvm/gems/ruby-1.8.7-p358@ultravie/bin/bundle:23:in `load'
    /home/kk/.rvm/gems/ruby-1.8.7-p358@ultravie/bin/bundle:23:in `<main>'

Environment

    Bundler   1.8.3
    Rubygems  1.8.23
    Ruby      1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]
    GEM_HOME  /home/kk/.rvm/gems/ruby-1.8.7-p358@ultravie
    GEM_PATH  /home/kk/.rvm/gems/ruby-1.8.7-p358@ultravie:/home/kk/.rvm/gems/ruby-1.8.7-p358@global
    RVM       1.26.3 ()
    Git       1.9.1
――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/bundler/bundler/search?q=can%27t+modify+frozen+String&type=Issues

If there aren't any reports for this error yet, please create copy and paste the report template above into a new issue. Don't forget to anonymize any private data! The new issue form is located at:
https://github.com/bundler/bundler/issues/new

**Comment by segiddins** [comment]
There's an open issue that details this -- in the short term, you can update the version of RubyGems you're using to fix this.

**Comment by arthurnn** [comment]
is this kinda a dup of https://github.com/bundler/bundler/issues/3187 ?

**Comment by segiddins** [comment]
I believe so, @arthurnn.

**Comment by segiddins** [comment]
@easyrider-new could you please share the contents of your Gemfile?
