### ISSUE TITLE
Bundler 1.7.9+ gets older versions of some direct Gemfile requirements than it used to

### ISSUE THREAD

**Issue by keiths-osc** [bundler/bundler#3459]
Starting with bundler 1.7.9 all the way through the current release (1.8.3 at the time I logged this), I've noticed that bundler has started getting old versions of some direct requirements where it didn't before.  The problem unfortunately is happening with a combination of some public gems from rubygems.org and some in-house gems that aren't available on rubygems.org, so I can't provide an actual Gemfile that you can immediately run.  However, I have forked bundler [here](https://github.com/keiths-osc/bundler) and added a couple of test scenarios to the rspec tests that reproduces the problem I am running into.

The scenarios use nonsense gem names, but reproduce the problem I am hitting.  I added two branches to my fork:
* The [resolver_bug_test branch](https://github.com/keiths-osc/bundler/tree/resolver_bug_test) was branched off of the ```v1.7.8``` tag.  The new scenarios I added pass when executed here.
* The [resolver_bug branch](https://github.com/keiths-osc/bundler/tree/resolver_bug) was branched off of the ```1-8-stable``` branch.  The exact same scenarios fail when executed here.

In the first scenario, we are emulating a Gemfile that looks similar to this:

```
source 'http://whatever'

gem 'foo' 
```

Versions 1.2.1, 3.0.0, and 3.0.5 of foo all exist in the gem source.
* Prior to bundler 1.7.9, a bundle install would get version 3.0.5.
* Bundler 1.7.9+ picks 1.2.1 instead.

The second scenario is nearly identical to the first, except that a constrant of ```>= 3.0.0``` has been added to the foo gem.

* Prior to bundler 1.7.9, a bundle install would get version 3.0.5.
* Bundler 1.7.9+ picks 3.0.0 instead.

If I explicitly set the constraint on the foo gem to be ```= 3.0.5``` to force bundler to pick the highest version, it has no problem being able to install it.

So, I seem to have found a case where bundler is deciding to install the lowest possible version of a requirement, where it used to install the highest possible version.

The index I added to the specs represents the smallest dependency graph and set of available gem versions in the gem source in order to expose this problem. I picked this out of a much larger real-life graph with hundreds of versions of all the various gems available with a great deal of trial and error.  For the index I added to the specs, if I remove any one dependency or delete any of the "extra" gems I included that aren't explicitly needed for bundler to be able to find a solution (such as baz version 5.0.2), bundler starts getting the latest version of foo again instead of the lowest version.

The changeset that seems to have caused this behavior change was https://github.com/bundler/bundler/commit/74c974e0985203ffc59e7c23971c5fcddec39454, which was first released in 1.7.9.  I realize that, technically, bundler is still meeting the requirements of my original Gemfile since it basically said that I would accept any version of foo.  However, the change in behavior I'm hitting seems like an unintended side effect.

There is one other thing that seems worth mentioning.  When testing off the master branch of bundler, this problem doesn't seem to happen.  I've noticed that the resolver has been heavily changed between 1-8-stable and master.  If it's going to be a good long while before those changes are released, then I was hoping maybe someone out there that is familiar with the resolver would be able to fix this fairly easily in 1.7 and/or 1.8. However, if that doesn't work out, it might be worth considering at least pulling my new test scenarios into master to make sure this problem doesn't come back.

**Comment by indirect** [comment]
Thank you for writing the tests! Can you submit them as a pull request?

You're right, and the resolver has changed a lot in master. (We're now sharing a single resolver between Bundler and CocoaPods! It's pretty awesome.) I'm hoping to release a 1.9 prerelease gem by the end of the week.

**Comment by keiths-osc** [comment]
Thanks, I'd be happy to submit a pull request.  I assume you want the request for the master branch?

**Comment by segiddins** [comment]
This can now be closed.
