### ISSUE TITLE
NoMethodError: undefined method `each' for ".":String

### ISSUE THREAD

**Issue by elnat** [bundler/bundler#3467]
Hi all. After install ruby on ubuntu 14.04, i try in bash "bundle install" and recive next:
Error details

    NoMethodError: undefined method `each' for ".":String
    /usr/lib/ruby/1.9.1/rubygems/specification.rb:974:in `contains_requirable_file?'
    /usr/lib/ruby/1.9.1/rubygems/specification.rb:443:in `block in find_by_path'
    /usr/lib/ruby/1.9.1/rubygems/specification.rb:411:in `block in each'
    /usr/lib/ruby/1.9.1/rubygems/specification.rb:410:in `each'
    /usr/lib/ruby/1.9.1/rubygems/specification.rb:410:in `each'
    /usr/lib/ruby/1.9.1/rubygems/specification.rb:442:in `find'
    /usr/lib/ruby/1.9.1/rubygems/specification.rb:442:in `find_by_path'
    /usr/lib/ruby/1.9.1/rubygems.rb:206:in `try_activate'
    /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:59:in `rescue in require'
    /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:35:in `require'
    /var/lib/gems/1.9.1/gems/bundler-1.8.4/lib/bundler/vendor/net/http/persistent.rb:12:in `<top (required)>'
    /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    /var/lib/gems/1.9.1/gems/bundler-1.8.4/lib/bundler/vendored_persistent.rb:11:in `<top (required)>'
    /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    /var/lib/gems/1.9.1/gems/bundler-1.8.4/lib/bundler/fetcher.rb:1:in `<top (required)>'
    /var/lib/gems/1.9.1/gems/bundler-1.8.4/lib/bundler/cli/install.rb:72:in `run'
    /var/lib/gems/1.9.1/gems/bundler-1.8.4/lib/bundler/cli.rb:157:in `install'
    /var/lib/gems/1.9.1/gems/bundler-1.8.4/lib/bundler/vendor/thor/command.rb:27:in `run'
    /var/lib/gems/1.9.1/gems/bundler-1.8.4/lib/bundler/vendor/thor/invocation.rb:121:in `invoke_command'
    /var/lib/gems/1.9.1/gems/bundler-1.8.4/lib/bundler/vendor/thor.rb:363:in `dispatch'
    /var/lib/gems/1.9.1/gems/bundler-1.8.4/lib/bundler/vendor/thor/base.rb:440:in `start'
    /var/lib/gems/1.9.1/gems/bundler-1.8.4/lib/bundler/cli.rb:10:in `start'
    /var/lib/gems/1.9.1/gems/bundler-1.8.4/bin/bundle:20:in `block in <top (required)>'
    /var/lib/gems/1.9.1/gems/bundler-1.8.4/lib/bundler/friendly_errors.rb:6:in `with_friendly_errors'
    /var/lib/gems/1.9.1/gems/bundler-1.8.4/bin/bundle:18:in `<top (required)>'
    /usr/local/bin/bundle:23:in `load'
    /usr/local/bin/bundle:23:in `<main>'

then i try: 
fixer@fix:~$ gem
/usr/lib/ruby/1.9.1/rubygems/specification.rb:1416:in `lib_dirs_glob': undefined method `first' for ".":String (NoMethodError)
	from /usr/lib/ruby/1.9.1/rubygems/specification.rb:1482:in `matches_for_glob'
	from /usr/lib/ruby/1.9.1/rubygems.rb:484:in `block in find_files'
	from /usr/lib/ruby/1.9.1/rubygems/specification.rb:411:in `block in each'
	from /usr/lib/ruby/1.9.1/rubygems/specification.rb:410:in `each'
	from /usr/lib/ruby/1.9.1/rubygems/specification.rb:410:in `each'
	from /usr/lib/ruby/1.9.1/rubygems.rb:483:in `map'
	from /usr/lib/ruby/1.9.1/rubygems.rb:483:in `find_files'
	from /usr/lib/ruby/1.9.1/rubygems.rb:1108:in `load_plugins'
	from /usr/lib/ruby/1.9.1/rubygems/gem_runner.rb:86:in `<top (required)>'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /usr/bin/gem:9:in `<main>'
fixer@fix:~$ 

Environment

    Bundler   1.8.4
    Rubygems  1.8.23
    Ruby      1.9.3p484 (2013-11-22 revision 43786) [i686-linux]
    Git       1.9.1

**Comment by indirect** [comment]
Please provide the information requested in [ISSUES](https://github.com/bundler/bundler/blob/master/ISSUES.md) so we can troubleshoot.

**Comment by elnat** [comment]
problem is over :)) in dir /var/lib/gem/1.9.1 was addressable-2.3.6 addressable-2.3.7, just delete 1, and all work fine thx .......
