### ISSUE TITLE
SSL issue on windows 7

### ISSUE THREAD

**Issue by Mic75** [bundler/bundler#3468]
### - What did you do?
Run bundle install with the following Gemfile from [jekyllrb](http://jekyllrb.com/docs/github-pages/) 
```
source 'https://rubygems.org'
require 'json'
require 'open-uri'
versions = JSON.parse(open('https://pages.github.com/versions.json').read)
gem 'github-pages', versions['github-pages']
```
### - What happened ?

    **OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed**
    D:/app/Ruby22-x64/lib/ruby/2.2.0/net/http.rb:923:in `connect'
    D:/app/Ruby22-x64/lib/ruby/2.2.0/net/http.rb:923:in `block in connect'
    D:/app/Ruby22-x64/lib/ruby/2.2.0/timeout.rb:74:in `timeout'
    D:/app/Ruby22-x64/lib/ruby/2.2.0/net/http.rb:923:in `connect'
    D:/app/Ruby22-x64/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
    D:/app/Ruby22-x64/lib/ruby/2.2.0/net/http.rb:852:in `start'
    D:/app/Ruby22-x64/lib/ruby/2.2.0/open-uri.rb:318:in `open_http'
    D:/app/Ruby22-x64/lib/ruby/2.2.0/open-uri.rb:736:in `buffer_open'
    D:/app/Ruby22-x64/lib/ruby/2.2.0/open-uri.rb:211:in `block in open_loop'
    D:/app/Ruby22-x64/lib/ruby/2.2.0/open-uri.rb:209:in `catch'
    D:/app/Ruby22-x64/lib/ruby/2.2.0/open-uri.rb:209:in `open_loop'
    D:/app/Ruby22-x64/lib/ruby/2.2.0/open-uri.rb:150:in `open_uri'
    D:/app/Ruby22-x64/lib/ruby/2.2.0/open-uri.rb:716:in `open'
    D:/app/Ruby22-x64/lib/ruby/2.2.0/open-uri.rb:34:in `open'
    D:/<dir_to_gemfile>/Gemfile:5:in `eval_gemfile'
    D:/app/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.8.4/lib/bundler/dsl.rb:32:in `instance_eval'
    D:/app/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.8.4/lib/bundler/dsl.rb:32:in `eval_gemfile'
    D:/app/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.8.4/lib/bundler/dsl.rb:10:in `evaluate'
    D:/app/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.8.4/lib/bundler/definition.rb:25:in `build'
    D:/app/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.8.4/lib/bundler.rb:155:in `definition'
    D:/app/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.8.4/lib/bundler/cli/install.rb:78:in `run'
    D:/app/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.8.4/lib/bundler/cli.rb:157:in `install'
    D:/app/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.8.4/lib/bundler/vendor/thor/command.rb:27:in `run'
    D:/app/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.8.4/lib/bundler/vendor/thor/invocation.rb:121:in `invoke_command'
    D:/app/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.8.4/lib/bundler/vendor/thor.rb:363:in `dispatch'
    D:/app/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.8.4/lib/bundler/vendor/thor/base.rb:440:in `start'
    D:/app/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.8.4/lib/bundler/cli.rb:10:in `start'
    D:/app/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.8.4/bin/bundle:20:in `block in <top (required)>'
    D:/app/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.8.4/lib/bundler/friendly_errors.rb:6:in `with_friendly_errors'
    D:/app/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.8.4/bin/bundle:18:in `<top (required)>'
    D:/app/Ruby22-x64/bin/bundle:23:in `load'
    D:/app/Ruby22-x64/bin/bundle:23:in `<main>'

### Environment

    Bundler   1.8.4
    Rubygems  2.3.0
    Ruby      2.2.1p85 (2015-02-26 revision 49769) [x64-mingw32]
    GEM_HOME  D:/app/Ruby22-x64/lib/ruby/gems/2.2.0
    GEM_PATH  D:/app/Ruby22-x64/lib/ruby/gems/2.2.0;C:/Users/<user>/.gem/ruby/2.2.0
    Git       1.9.5.msysgit.0

**Comment by TimMoore** [comment]
Try the troubleshooting steps in this gist https://gist.github.com/luislavena/f064211759ee0f806c88

**Comment by TimMoore** [comment]
Closing this, because it isn't actually a bug in Bundler.

**Comment by Mic75** [comment]
Thanks Tim.
Actually, I had already tried the steps from the mentioned gist prior to posting the issue.
But, indeed, the issue is not related to Bundler.

**Comment by revenforv** [comment]
Mic, following solution works fine for me

```ruby
source 'http://rubygems.org'

require 'json'
require 'open-uri'

# doing this because server admin forgot to renew their certificate!
OpenSSL::SSL.send(:remove_const, :VERIFY_PEER)
OpenSSL::SSL.const_set(:VERIFY_PEER, OpenSSL::SSL::VERIFY_NONE)

versions = JSON.parse(open('https://pages.github.com/versions.json').read)

gem 'github-pages', versions['github-pages']
```
