### ISSUE TITLE
Bundler::which sometimes recognizes a directory as an executable.

### ISSUE THREAD

**Issue by JunichiMorimoto** [bundler/bundler#3472]
Bundler::which doesn't return nil if the argument is a name of
directory.
This problem is fixed in 628927b6eebf2523ad18f7042da6ac598d000d61, but the same problem remains in Bundler::which yet.

e.g.
When PATH has "C:\Windows" and "C:\Windows\ruby" exists, and a command
bundle exec ruby
is executed, Bundler::which recognizes "C:\Windows\ruby" as executable, and it is set as a bin_path in Bundler::CLI::Exec#run.

So, similar to 628927b6eebf2523ad18f7042da6ac598d000d61, I fixed as below.
https://github.com/JunichiMorimoto/bundler/commit/867e1fcbb34ec15ff3e6c60e17a326c833cf87e8

May I create a pull request?

**Comment by indirect** [comment]
Thanks! Cherry-picked as b41357489b63cfbc1b957e575e495e1383d5c9cb.
