### ISSUE TITLE
bundle install error

### ISSUE THREAD

**Issue by ksatia** [bundler/bundler#3473]
――― ERROR REPORT TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――
- What did you do?
- What did you expect to happen?
- What happened instead?

Error details

    URI::InvalidURIError: bad URI(is not URI?): https:// rubygems.org/
    /Users/KaranSatia/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/uri/rfc3986_parser.rb:66:in `split'
    /Users/KaranSatia/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/uri/rfc3986_parser.rb:72:in `parse'
    /Users/KaranSatia/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/uri/common.rb:226:in `parse'
    /Users/KaranSatia/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/uri/common.rb:713:in `URI'
    /Users/KaranSatia/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.8.3/lib/bundler/source/rubygems.rb:227:in `normalize_uri'
    /Users/KaranSatia/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.8.3/lib/bundler/source/rubygems.rb:169:in `add_remote'
    /Users/KaranSatia/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.8.3/lib/bundler/source_list.rb:26:in `add_rubygems_remote'
    /Users/KaranSatia/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.8.3/lib/bundler/dsl.rb:116:in `source'
    /Users/KaranSatia/Desktop/WORKSPACE/learn-rails/Gemfile:1:in `eval_gemfile'
    /Users/KaranSatia/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.8.3/lib/bundler/dsl.rb:32:in `instance_eval'
    /Users/KaranSatia/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.8.3/lib/bundler/dsl.rb:32:in `eval_gemfile'
    /Users/KaranSatia/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.8.3/lib/bundler/dsl.rb:10:in `evaluate'
    /Users/KaranSatia/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.8.3/lib/bundler/definition.rb:25:in `build'
    /Users/KaranSatia/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.8.3/lib/bundler.rb:155:in `definition'
    /Users/KaranSatia/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.8.3/lib/bundler/cli/install.rb:78:in `run'
    /Users/KaranSatia/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.8.3/lib/bundler/cli.rb:157:in `install'
    /Users/KaranSatia/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.8.3/lib/bundler/vendor/thor/command.rb:27:in `run'
    /Users/KaranSatia/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.8.3/lib/bundler/vendor/thor/invocation.rb:121:in `invoke_command'
    /Users/KaranSatia/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.8.3/lib/bundler/vendor/thor.rb:363:in `dispatch'
    /Users/KaranSatia/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.8.3/lib/bundler/vendor/thor/base.rb:440:in `start'
    /Users/KaranSatia/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.8.3/lib/bundler/cli.rb:10:in `start'
    /Users/KaranSatia/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.8.3/bin/bundle:20:in `block in <top (required)>'
    /Users/KaranSatia/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.8.3/lib/bundler/friendly_errors.rb:6:in `with_friendly_errors'
    /Users/KaranSatia/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.8.3/bin/bundle:18:in `<top (required)>'
    /Users/KaranSatia/.rvm/gems/ruby-2.2.0@global/bin/bundle:23:in `load'
    /Users/KaranSatia/.rvm/gems/ruby-2.2.0@global/bin/bundle:23:in `<main>'
    /Users/KaranSatia/.rvm/gems/ruby-2.2.0@learn-rails/bin/ruby_executable_hooks:15:in `eval'
    /Users/KaranSatia/.rvm/gems/ruby-2.2.0@learn-rails/bin/ruby_executable_hooks:15:in `<main>'

Environment

    Bundler   1.8.3
    Rubygems  2.4.6
    Ruby      2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin14]
    GEM_HOME  /Users/KaranSatia/.rvm/gems/ruby-2.2.0@learn-rails
    GEM_PATH  /Users/KaranSatia/.rvm/gems/ruby-2.2.0@learn-rails:/Users/KaranSatia/.rvm/gems/ruby-2.2.0@global
    RVM       1.26.10 (latest)
    Git       2.3.1
    rubygems-bundler (1.4.4)
――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

**Comment by ksatia** [comment]
no idea what to do from here...

**Comment by andremedeiros** [comment]
Hi @ksatia, 

It seems like your source declaration on your `Gemfile` is invalid.

Please confirm if there's no space in the URL, like so:

```
# Gemfile
source 'https://rubygems.org'

ruby '2.2.1'

# your gems...
```

**Comment by ksatia** [comment]
Literally 2 seconds before you sent me that answer I noticed the space in the URL declaration. I changed it, and while the error message has changed, there is still an error. 

/Users/KaranSatia/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/requirement.rb:100:in `parse': Illformed requirement ["~ > 4.0.3"] (Gem::Requirement::BadRequirementError)
       /Users/KaranSatia/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/requirement.rb:130:in `block in initialize'
       /Users/KaranSatia/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/requirement.rb:130:in `map!'
       /Users/KaranSatia/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/requirement.rb:130:in `initialize'
       /Users/KaranSatia/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/requirement.rb:58:in `new'
       /Users/KaranSatia/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/requirement.rb:58:in `create'
       /Users/KaranSatia/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/dependency.rb:58:in `initialize'
       /Users/KaranSatia/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.8.3/lib/bundler/dependency.rb:51:in `initialize'
       /Users/KaranSatia/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.8.3/lib/bundler/dsl.rb:74:in `new'
       /Users/KaranSatia/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.8.3/lib/bundler/dsl.rb:74:in `gem'
       /Users/KaranSatia/Desktop/WORKSPACE/learn-rails/Gemfile:7:in `eval_gemfile'
       /Users/KaranSatia/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.8.3/lib/bundler/dsl.rb:32:in `instance_eval'
       /Users/KaranSatia/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.8.3/lib/bundler/dsl.rb:32:in `eval_gemfile'
       /Users/KaranSatia/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.8.3/lib/bundler/dsl.rb:10:in `evaluate'
       /Users/KaranSatia/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.8.3/lib/bundler/definition.rb:25:in `build'
       /Users/KaranSatia/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.8.3/lib/bundler.rb:155:in `definition'
       /Users/KaranSatia/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.8.3/lib/bundler/cli/install.rb:78:in `run'
       /Users/KaranSatia/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.8.3/lib/bundler/cli.rb:157:in `install'
       /Users/KaranSatia/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.8.3/lib/bundler/vendor/thor/command.rb:27:in `run'
       /Users/KaranSatia/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.8.3/lib/bundler/vendor/thor/invocation.rb:121:in `invoke_command'
       /Users/KaranSatia/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.8.3/lib/bundler/vendor/thor.rb:363:in `dispatch'
       /Users/KaranSatia/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.8.3/lib/bundler/vendor/thor/base.rb:440:in `start'
       /Users/KaranSatia/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.8.3/lib/bundler/cli.rb:10:in `start'
       /Users/KaranSatia/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.8.3/bin/bundle:20:in `block in <top (required)>'
       /Users/KaranSatia/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.8.3/lib/bundler/friendly_errors.rb:6:in `with_friendly_errors'
       /Users/KaranSatia/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.8.3/bin/bundle:18:in `<top (required)>'
       /Users/KaranSatia/.rvm/gems/ruby-2.2.0@global/bin/bundle:23:in `load'
       /Users/KaranSatia/.rvm/gems/ruby-2.2.0@global/bin/bundle:23:in `<main>'
       /Users/KaranSatia/.rvm/gems/ruby-2.2.0@learn-rails/bin/ruby_executable_hooks:15:in `eval'
       /Users/KaranSatia/.rvm/gems/ruby-2.2.0@learn-rails/bin/ruby_executable_hooks:15:in `<main>'

There was an error in your Gemfile, and Bundler cannot continue.

**Comment by arthurnn** [comment]
seems like you have another extra space in here: `"~ > 4.0.3"`

**Comment by ksatia** [comment]
@arthurnn THANK YOU. Learning to always check things like that before bothering other people...
