### ISSUE TITLE
Error creating new project

### ISSUE THREAD

**Issue by antonio-fasolato** [bundler/bundler#3474]
I was trying to create a new empty project with 'bundle gem' but received this error

bundle gem rubyTest2
DL is deprecated, please use Fiddle
Creating gem 'rubyTest2'...
â?â?â? ERROR REPORT TEMPLATE â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?
- What did you do?
- What did you expect to happen?
- What happened instead?

Error details

    NameError: undefined local variable or method `opts' for #<Bundler::CLI::Gem:0x2d42978>
    C:/Ruby21/lib/ruby/gems/2.1.0/gems/bundler-1.9.0.pre/lib/bundler/cli/gem.rb:43:in `run'
    C:/Ruby21/lib/ruby/gems/2.1.0/gems/bundler-1.9.0.pre/lib/bundler/cli.rb:351:in `gem'
    C:/Ruby21/lib/ruby/gems/2.1.0/gems/bundler-1.9.0.pre/lib/bundler/vendor/thor-0.19.1/lib/thor/command.rb:27:in `run'
    C:/Ruby21/lib/ruby/gems/2.1.0/gems/bundler-1.9.0.pre/lib/bundler/vendor/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    C:/Ruby21/lib/ruby/gems/2.1.0/gems/bundler-1.9.0.pre/lib/bundler/vendor/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    C:/Ruby21/lib/ruby/gems/2.1.0/gems/bundler-1.9.0.pre/lib/bundler/vendor/thor-0.19.1/lib/thor/base.rb:440:in `start'
    C:/Ruby21/lib/ruby/gems/2.1.0/gems/bundler-1.9.0.pre/lib/bundler/cli.rb:10:in `start'
    C:/Ruby21/lib/ruby/gems/2.1.0/gems/bundler-1.9.0.pre/bin/bundle:20:in `block in <top (required)>'
    C:/Ruby21/lib/ruby/gems/2.1.0/gems/bundler-1.9.0.pre/lib/bundler/friendly_errors.rb:6:in `with_friendly_errors'
    C:/Ruby21/lib/ruby/gems/2.1.0/gems/bundler-1.9.0.pre/bin/bundle:18:in `<top (required)>'
    C:/Ruby21/bin/bundle:23:in `load'
    C:/Ruby21/bin/bundle:23:in `<main>'

Environment

    Bundler   1.9.0.pre
    Rubygems  2.4.6
    Ruby      2.1.5p273 (2014-11-13 revision 48405) [i386-mingw32]
    Git       1.9.4.msysgit.0
â?â?â? TEMPLATE END â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?â?

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/bundler/bundler/search?q=undefined+local+variable+or+method+%60opts%27+for+%23%3CBundler%3A%3ACLI%3A%3AGem%3A0x2d42978%3E&type=Issues

If there aren't any reports for this error yet, please create copy and paste the report template above into a new issue. Don't forget to anonymize any private data! The new issue form is located at:
https://github.com/bundler/bundler/issues/new

My system is a windows 7 pro machine, ruby version ruby 2.1.5p273 (2014-11-13 revision 48405) [i386-mingw32] and bundler 1.9.0.pre

If you need any more informations let me know

**Comment by andremedeiros** [comment]
Hi @antonio-fasolato, thank you for reporting.

This was an issue we've already caught and fixed, pending a new `pre` release.

Thank you also for testing betas. Really helps! :heart:
