### ISSUE TITLE
bad URI(is not URI?)

### ISSUE THREAD

**Issue by jolux** [bundler/bundler#3477]
I get this error message whenever I try to use bundle in my gh-pages Gemfile directory:

――― ERROR REPORT TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――
- What did you do?
- What did you expect to happen?
- What happened instead?

Error details

    URI::InvalidURIError: bad URI(is not URI?): https://rubygems.org"/
    /usr/local/Cellar/ruby/2.2.1/lib/ruby/2.2.0/uri/rfc3986_parser.rb:66:in `split'
    /usr/local/Cellar/ruby/2.2.1/lib/ruby/2.2.0/uri/rfc3986_parser.rb:72:in `parse'
    /usr/local/Cellar/ruby/2.2.1/lib/ruby/2.2.0/uri/common.rb:226:in `parse'
    /usr/local/Cellar/ruby/2.2.1/lib/ruby/2.2.0/uri/common.rb:713:in `URI'
    /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.8.5/lib/bundler/source/rubygems.rb:232:in `normalize_uri'
    /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.8.5/lib/bundler/source/rubygems.rb:174:in `add_remote'
    /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.8.5/lib/bundler/source_list.rb:26:in `add_rubygems_remote'
    /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.8.5/lib/bundler/dsl.rb:116:in `source'
    /Users/benklebe/klebeklebe.me/klebeklebe.github.io/Gemfile:1:in `eval_gemfile'
    /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.8.5/lib/bundler/dsl.rb:32:in `instance_eval'
    /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.8.5/lib/bundler/dsl.rb:32:in `eval_gemfile'
    /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.8.5/lib/bundler/dsl.rb:10:in `evaluate'
    /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.8.5/lib/bundler/definition.rb:25:in `build'
    /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.8.5/lib/bundler.rb:155:in `definition'
    /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.8.5/lib/bundler/cli/install.rb:78:in `run'
    /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.8.5/lib/bundler/cli.rb:157:in `install'
    /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.8.5/lib/bundler/vendor/thor/command.rb:27:in `run'
    /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.8.5/lib/bundler/vendor/thor/invocation.rb:121:in `invoke_command'
    /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.8.5/lib/bundler/vendor/thor.rb:363:in `dispatch'
    /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.8.5/lib/bundler/vendor/thor/base.rb:440:in `start'
    /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.8.5/lib/bundler/cli.rb:10:in `start'
    /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.8.5/bin/bundle:20:in `block in <top (required)>'
    /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.8.5/lib/bundler/friendly_errors.rb:6:in `with_friendly_errors'
    /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.8.5/bin/bundle:18:in `<top (required)>'
    /usr/local/bin/bundle:23:in `load'
    /usr/local/bin/bundle:23:in `<main>'

Environment

    Bundler   1.8.5
    Rubygems  2.4.6
    Ruby      2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]
    GEM_HOME  /usr/local/lib/ruby/gems/2.2.0
    GEM_PATH  /usr/local/lib/ruby/gems/2.2.0:/Users/benklebe/.gem/ruby/2.2.0:/usr/local/Cellar/ruby/2.2.1/lib/ruby/gems/2.2.0
    Git       2.3.2
――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

Kind of a newb with regards to ruby. Any help is appreciated!

**Comment by TimMoore** [comment]
Looks like there is a typo in the `source` line. A misplaced double-quote?

If you're having trouble spotting it, you can post the contents of your `Gemfile` and we can help you correct it.

**Comment by jolux** [comment]
Duh! Should have noticed that. My bad for not checking first. I'll close 
the issue.

Sincerely,

Ben Klebe

**Comment by moueimei** [comment]
Error details

    URI::InvalidURIError: bad URI(is not URI?): https://rubygems.org/ /
      /usr/local/lib/ruby/2.0.0/uri/common.rb:176:in `split'
      /usr/local/lib/ruby/2.0.0/uri/common.rb:211:in `parse'
      /usr/local/lib/ruby/2.0.0/uri/common.rb:747:in `parse'
      /usr/local/lib/ruby/2.0.0/uri/common.rb:996:in `URI'
      /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.11.2/lib/bundler/source/rubygems.rb:268:in `normalize_uri'
      /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.11.2/lib/bundler/source/rubygems.rb:207:in `add_remote'
      /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.11.2/lib/bundler/lockfile_parser.rb:112:in `block in parse_source'
      /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.11.2/lib/bundler/lockfile_parser.rb:111:in `each'
      /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.11.2/lib/bundler/lockfile_parser.rb:111:in `parse_source'
      /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.11.2/lib/bundler/lockfile_parser.rb:54:in `block in initialize'
      /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.11.2/lib/bundler/lockfile_parser.rb:41:in `each'
      /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.11.2/lib/bundler/lockfile_parser.rb:41:in `initialize'
      /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.11.2/lib/bundler/definition.rb:61:in `new'
      /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.11.2/lib/bundler/definition.rb:61:in `initialize'
      /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.11.2/lib/bundler/dsl.rb:173:in `new'
      /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.11.2/lib/bundler/dsl.rb:173:in `to_definition'
      /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.11.2/lib/bundler/dsl.rb:11:in `evaluate'
      /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.11.2/lib/bundler/definition.rb:24:in `build'
      /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.11.2/lib/bundler.rb:120:in `definition'
      /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.11.2/lib/bundler/cli/install.rb:102:in `run'
      /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.11.2/lib/bundler/cli.rb:172:in `install'
      /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.11.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.11.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.11.2/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.11.2/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.11.2/lib/bundler/cli.rb:10:in `start'
      /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.11.2/exe/bundle:19:in `block in <top (required)>'
      /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.11.2/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
      /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.11.2/exe/bundle:17:in `<top (required)>'
      /usr/bin/bundle:23:in `load'
      /usr/bin/bundle:23:in `<main>'

Environment

    Bundler   1.11.2
    Rubygems  2.0.14
    Ruby      2.0.0p353 (2013-11-22 revision 43784) [x86_64-linux]
    GEM_HOME  /home/git/gitlab/vendor/bundle/ruby/2.0.0
    GEM_PATH  
    Git       1.8.4.1

Any help is appreciated!

**Comment by RochesterinNYC** [comment]
Please post your `Gemfile`.

**Comment by moueimei** [comment]
[Gemfile.txt](https://github.com/bundler/bundler/files/181649/Gemfile.txt)

**Comment by moueimei** [comment]
Gemfile file name add '.txt'

**Comment by TimMoore** [comment]
Actually it looks like this error is happening when parsing `Gemfile.lock`. Is it possible that you introduced a typo into that file @moueimei?

**Comment by moueimei** [comment]
[Gemfile.lock.txt](https://github.com/bundler/bundler/files/181660/Gemfile.lock.txt)

**Comment by moueimei** [comment]
Gemfile.lock Where to set the wrong

**Comment by TimMoore** [comment]
That looks OK too. How about `bundle config`?

**Comment by TimMoore** [comment]
Oh wait I spoke too soon... looks like `Gemfile.lock` has a trailing space in the `remote` line.

**Comment by RochesterinNYC** [comment]
@moueimei Change `https://rubygems.org/` to `https://rubygems.org` in both the `Gemfile` and the `Gemfile.lock` and you should not have this error.

**Comment by moueimei** [comment]
"Gemfile.lock has a trailing space in the remote line. "  delete  space,now run Ok,thank you! @TimMoore

**Comment by sankansm** [comment]
i am having nearly similar issue....

Installing the 'vagrant-proxyconf' plugin. This can take a few minutes...
C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/uri/rfc3986_parser.rb:66:in `split': bad URI(is not URI?): http://a206752:xxxxxx@httppxgot.srv.volvo.com:8080 (URI::InvalidURIError)
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/uri/rfc3986_parser.rb:72:in `parse'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/uri/common.rb:226:in `parse'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/uri/common.rb:713:in `URI'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/rubygems/request.rb:126:in `get_proxy_from_env'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/rubygems/remote_fetcher.rb:395:in `proxy_for'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/rubygems/remote_fetcher.rb:347:in `request'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/rubygems/remote_fetcher.rb:237:in `fetch_http'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/rubygems/remote_fetcher.rb:273:in `fetch_path'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/rubygems/source.rb:91:in `dependency_resolver_set'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/rubygems/resolver/best_set.rb:23:in `block in pick_sets'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/rubygems/source_list.rb:97:in `each'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/rubygems/source_list.rb:97:in `each_source'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/rubygems/resolver/best_set.rb:22:in `pick_sets'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/rubygems/resolver/best_set.rb:28:in `find_all'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/rubygems/resolver/installer_set.rb:151:in `find_all'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/bundler.rb:409:in `find_all'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/rubygems/resolver/composed_set.rb:54:in `block in find_all'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/rubygems/resolver/composed_set.rb:53:in `map'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/rubygems/resolver/composed_set.rb:53:in `find_all'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/rubygems/resolver.rb:209:in `find_possible'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/rubygems/resolver.rb:346:in `resolve_for'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/rubygems/resolver.rb:196:in `resolve'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/rubygems/request_set.rb:358:in `resolve'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/bundler.rb:278:in `internal_install'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/bundler.rb:104:in `install'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/plugin/manager.rb:62:in `block in install_plugin'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/plugin/manager.rb:72:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/plugin/manager.rb:72:in `install_plugin'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.3/plugins/commands/plugin/action/install_gem.rb:29:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/action/builder.rb:116:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/action/runner.rb:66:in `block in run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/util/busy.rb:19:in `busy'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/action/runner.rb:66:in `run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.3/plugins/commands/plugin/command/base.rb:14:in `action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.3/plugins/commands/plugin/command/install.rb:32:in `block in execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.3/plugins/commands/plugin/command/install.rb:31:in `each'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.3/plugins/commands/plugin/command/install.rb:31:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.3/plugins/commands/plugin/command/root.rb:66:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/cli.rb:42:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/environment.rb:308:in `cli'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.3/bin/vagrant:127:in `<main>
