### ISSUE TITLE
Allow to fetch gems from remote when not present during bundle package

### ISSUE THREAD

**Issue by xdmx** [bundler/bundler#3482]
I'm setting a docker file and to avoid having to download all gems at every change I want to use bundle package and use the cache to install them.

The problem is that I delete bundler's cache (in /usr/local/bundle/cache/) in a docker step in order to decrease the container size, and so when I run bundle package I get "Could not find xyz.gem for installation"

It would be very useful a flag --remote-fetch on the package command that would tell bundler to download the .gem from remote if not present locally and save it into vendor/cache

**Comment by indirect** [comment]
Just delete the vendor/cache directory and then run `bundle package`.

**Comment by xdmx** [comment]
It doesn't work

I initially install all gems with bundle install (into /usr/local/bundle)
They are installed and in /usr/local/bundle/cache/ there are all .gem files
I delete all files into /usr/local/bundle/cache
I delete vendor/cache
I run bundle package and I get this

```
# bundle package --all --no-install
Using json 1.8.2
[...]
Using websocket-rails 0.7.0
Bundle complete! 57 Gemfile dependencies, 188 gems now installed.
Bundled gems are installed into /usr/local/bundle.
Updating files in vendor/cache
  * rake-10.4.2.gem
Could not find CFPropertyList-2.3.0.gem for installation
```


After the first run in vendor/cache I'd have some .gem files, if I delete the folder in order to have bundle to download them again (which it's not doing) that would vanish having vendor/cache in order to avoid having to download all .gem files.

I think a --remote-fetch would be better suited, for each gem it would check the vendor/cache, if the file is there it skips to the next gem, if not it checks the local cache (/usr/bundle/cache), if present it copies the file into vendor/cache, if not, it downloads it from rubygems. If you prefer I'll open an issue on the bundler-features repo

**Comment by xdmx** [comment]
Or otherwise this could be the default even without a specific flag and without having to remove vendor/cache... If I run bundle package is because I want to have all gems packaged into vendor/cache, if it already has the gems into it it shouldn't be a problem, neither if the local cache doesn't have the .gem files anymore

**Comment by indirect** [comment]
You're deliberately breaking the way that Rubygems and Bundler work. The system-level cache (which apparently is /usr/local/bundle/cache for you) MUST contain copies of the .gem files for every installed gem. If you delete them, you have broken your Rubygems installation.

**Comment by xdmx** [comment]
I guess so, I thought that the bundle/cache folder had .gem files that were not useful anymore after the installation since they were extracted into bundle/gems, bundle check didn't return any error and the app worked correctly. I guess I'll have to keep the bundle/cache then
In my opinion a cache should always be safe to remove, if it doesn't exist anymore it should be regenerated (or in this case download the .gem files again), otherwise it shouldn't be called cache but archive or something else :smile:

**Comment by indirect** [comment]
You can delete vendor/cache, but the Rubygems structure that Bundler uses requires that all installed gems still be present inside the $GEM_HOME/cache directory. Without those .gem files, many parts of Rubygems and Bundler stop working, including the `gem pristine` command, as well as the `bundle package` command (as you noticed).

That was a long way of saying “it’s not strictly a cache, but we can’t change it now, sorry”. :)

**Comment by xdmx** [comment]
Eheh, gotcha. Thankfully I discovered it in development and not in production

Thanks for all the info and sorry for the noise :smile:
