### ISSUE TITLE
windows: binary gems not compatible between ruby 21.5 and 2.2.1

### ISSUE THREAD

**Issue by net1957** [bundler/bundler#3488]
On my windows system I'm using pik (windows RVM...) to chose between multiple ruby version.

For this issue I use the ruby-oci8 gem as example.

in the gem file I use:
````
gem 'ruby-oci8', '~> 2.1.0'
````
When I run 'bundle install' or 'bundle update'  :
  * If i'm using ruby 2.1.5, bundler download and install ruby-oci8-2.1.7-x64-mingw32 gem and it's working as expected.

  * If i'm using ruby  2.2.1, bundler do the same job with the same gem
but this gem isn't working on ruby 2.2.1.

To get it working you have to to compile it with 
````
gem install ruby-oci8 --platform=ruby
````
but the next time you use bundler update it will fetch the precompiled one that break at runtime.

How can I tell bundler to install the gem with the ruby platform ?

versions:
Windows 8.1 x64
ruby 2.1.5p273 (2014-11-13 revision 48405) [x64-mingw32]
ruby 2.2.1p85 (2015-02-26 revision 49769) [x64-mingw32]
bundler (1.8.5)
rubygem 2.4.6

**Comment by TimMoore** [comment]
This sounds to me like the same problem described in #3456. Is that right?

**Comment by net1957** [comment]
Yes, seems to be the same.

I don't see any workaround for windows users... Could hit many binary gems!
How can we know that gemxx-2.1.7-x64-mingw32 is for ruby 2.1.5 or ruby 2.2.1 ?

Any idea about a solution or workaround?

**Comment by indirect** [comment]
The "required ruby version" in the gemspec is how you can know.

**Comment by net1957** [comment]
But I'm a user of the gem.
The gem is the same for ruby 2.1.5 and 2.2.1
only the compiled version is not compatible between the 2 (ruby 2.2 is not binary compatible with ruby 2.1)
And I know i can compile the gem using --platform=ruby to force compilation

How can Bundler do it when I run bundle on my project ?

I tried 'bundle config build.ruby-oci8 --platform=ruby' without success
It seems that bundler prefer the precompiled gem over the ruby platform gem.

**Comment by indirect** [comment]
Bundler does not currently have a way to force a gem to be installed for a different platform than the current platform. Sorry. :(

**Comment by net1957** [comment]
I'm on he current platform!

I can't install a precompiled gem on ruby 2.2.1

**Comment by rgb-one** [comment]
Can Bundler, upon running `bundle install` or `bundle update` compile a specific gem instead of installing the precompiled version of the gem which is its default action?
I think the problem here is that net1957 force compiles the gem with `gem install ruby-oci8 --platform=ruby` but when he runs `bundle install` or `bundle update`, the compiled gem is overwritten with the precompiled gem which Bundler installs. Is that right?

**Comment by net1957** [comment]
It's not overwritten but bundler add the precompiled one  and at execution it use this one

after `gem install ruby-oci8 --platform=ruby`:
````
*** LOCAL GEMS ***
ruby-oci8 (2.1.7)
````

in gemfile:
````
gem 'ruby-oci8', '~> 2.1.0'
````
after bundle
````
*** LOCAL GEMS ***
ruby-oci8 (2.1.7 ruby x64-mingw32)
````

**Comment by TimMoore** [comment]
I'm going to close this issue to keep all of the related discussion in the thread on #3456. Unfortunately, I don't think there's a solution at this time.
