### ISSUE TITLE
User defined gem templates?

### ISSUE THREAD

**Issue by TheNotary** [bundler/bundler#3494]
I often find myself starting out apps of either 3 different kinds:
-  Daemons which run either via /etc/init.d or windows services
-  Apps that have a -web option where they launch an http service on port 3030
-  CLI apps that make changes to the file system (and require specific testing code and load data from a ~/.gem_name/ configuration folder)

I've been playing around with modifying the internal template provided in bundler, and I've had success with adding an option to bundler to use a user defined.  It would certainly increase my own productivity, but I'm a sysadmin so my uses with ruby may be seen as a bit overly specific.  

Here's the progress I've made so far, and if this feature is considered useful, I'd be more than happy to clean up the code and have it conform to any specs needed for a merge.  

https://github.com/TheNotary/bundler/compare/master...TheNotary:allow-user-defined-gem-templates

What are some thoughts about adding some code to allow for user defined gem templates?

**Comment by indirect** [comment]
Hey there! We've been trying to keep the gem command in Bundler as small as possible, since creating gems isn't really a core purpose of Bundler itself. There's another project, called Ore, that allows creating gems from user-defined templates already. Can you try it and let us know whether it does what you're looking for or not? Thanks!

**Comment by TheNotary** [comment]
Thanks for the reply.  I've looked over ore in the past and I've never understood how to create an actual template with it.  I've previously assumed it's either not intended to do what I want it to do or its documentation is incomplete in the area of template creation.  I think ore's templates are based on adding 'fragments' of things at a time, with a root project structure to be modified, rather than defining the root project structure in the manor I'm hoping to jigger together.  

I think it's a good idea to keep bundler as simple as possible, tbh I was pretty hesitant to even begin developing on bundler's gem command given the fact that I was essentially tampering with a dependency of almost everything I've ever built, ha.

**Comment by bf4** [comment]
So, I'd be willing to add a `template_file` option to bundler to enable the functionality. It's basically already built in. See http://www.benjaminfleischer.com/2015/04/07/gem-templates-with-thor/ and https://github.com/bf4/gemnerator (Just wrote released this today)

**Comment by indirect** [comment]
Since our long-term plan is to move away from Thor, I think it's best to point people at Ore for templated gems. :)

**Comment by TheNotary** [comment]
I can't believe it's already been 17 days since I opened this!  

For the record, ore almost certainly doesn't work the way bundler does things.  I think you feed it a list of switches until it meets the specifications for a 'template' for a new gem, which is an approach that may have it's merits, but it isn't what I'd want to use to start projects.  I think there's room for more contenders in this area of ruby dev, especially considering Ore's not really getting that many commits lately, and the latest release was actually 2012.  Maybe that tells of gem attention or maybe gem 'perfection' but its definitely not using an algo compatible with creating gem classes in a straight forward manor.  

I started a repo for doing it bundler's way 17 days ago apparently, but I ran out of time for it.  I left off with it realizing that I needed to take out Thor to make it's syntax cleaner, ironically.  The bulk of the work was just getting it to run with the minimal amount of bundler code as possible.  The repo is online now, but not in an especially exciting state.  It needs a refactor, but it might serve as an idea generator or something you might want to borrow from or contribute to if it's what you're looking for bf4.  https://github.com/TheNotary/bundlegem

Indirect, if you cut out Thor from the repo, would you design an options grabbing system that would be the same syntax as Thor?  I had the displeasure of stripping out parts of Thor today, but I'm curious what you'll do about all the commands that are built into the gem so far.
