### ISSUE TITLE
Clarify documentation of source selection with a block and what a bang (!) means

### ISSUE THREAD

**Issue by aprescott** [bundler/bundler#3502]
The new block-form of `source` is really great, and I'm glad it improves the security of `Gemfile`. Unfortunately, I had some confusion (see https://github.com/mperham/sidekiq/issues/2199#issuecomment-78264403 for example) around a `!` showing up in my `Gemfile.lock`. For example, when I changed

```ruby
gem "foo"
```

to

```ruby
source "https://example.com/foo" do
  gem "foo"
end
```

My `Gemfile.lock` changed from containing

```
foo
```

to containing

```
foo!
```

This looked broken to me because I'd only ever seen `foo!` to mean "this is coming from a local path" or something similar.

In both the [1.7 changelog](http://bundler.io/v1.7/whats_new.html#version17) and the [1.8 changelog](http://bundler.io/v1.8/whats_new.html#version18) I couldn't find any explanation of whether the addition of a `!` was expected and all fine. A coworker later pointed me to [the relevant part of bundler's source](https://github.com/bundler/bundler/blob/cab48fb8273108eb95d5b4332bdb9ad21a6524fb/lib/bundler/lockfile_parser.rb#L106-L134).

I think it'd be really useful to document that this is expected behavior somewhere. Perhaps also along with documentation of how `!` works in general?

**Comment by segiddins** [comment]
I believe none of the lockfile format is documented nor public?

**Comment by aprescott** [comment]
Oh, interesting. It is visible to developers though, to allow them to confirm things are set up correctly. I know that, quite often, I'll double-check that a `bundle update` has done the right thing. That makes me want to know what `!` means, but I can see the difficulty given the assumption that `Gemfile.lock` is never documented...

**Comment by indirect** [comment]
As soon as we document the lockfile format, this will be documented! But right now there isn't even a spec for the lockfile, let alone documentation. :)

**Comment by aprescott** [comment]
I'll go with that! :)
