### ISSUE TITLE
Bundler puts a trailing space in "BUNDLE_BIN" variable.

### ISSUE THREAD

**Issue by 1dot44mb** [bundler/bundler#3504]
By default; bundler puts a trailing space in "BUNDLE_BIN" variable.
I installed bundler on a clean vagrant box via "gem install bundler".
This causes the error: http://stackoverflow.com/questions/29232331/vagrant-rails-shared-folder-bundler-error when trying to run "bundle install".

Here is bundle env:
```
Environment

    Bundler   1.9.1
    Rubygems  2.4.6
    Ruby      2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]
    GEM_HOME  /home/vagrant/.rvm/gems/ruby-2.2.1
    GEM_PATH  /home/vagrant/.rvm/gems/ruby-2.2.1:/home/vagrant/.rvm/gems/ruby-2.2.1@global
    RVM       1.26.10 (latest)
    Git       1.9.1

Bundler settings

    bin
      Set for your local app (/vagrant/.bundle/config): "bin "
    no_prune
      Set for your local app (/vagrant/.bundle/config): "'true' "
    path
      Set for your local app (/vagrant/.bundle/config): ".bundle"
    disable_shared_gems
      Set for your local app (/vagrant/.bundle/config): "1"
    clean
      Set for your local app (/vagrant/.bundle/config): "true"
```
You may notice that BUNDLE_BIN = "bin ", which leads to errors in File.open in file initialize.rb line 175 because ruby can not open file with a space in path (because such file does not exist).

Editing .bundle/config and setting BUNDLE_BIN to "bin" (removed space) solved bundle install errors.

**Comment by indirect** [comment]
What makes you think that this is a default? When I run `bundle install --binstubs`, the config that is set is just `"bin"`. Can you please follow [ISSUES](https://github.com/bundler/bundler/blob/master/ISSUES.md) and provide reproduction steps?

**Comment by 1dot44mb** [comment]
Well, i thought i made a clean dev. environment. But now come to think of it, maybe its not by default, i may somehow modified the file. If its not reproducible, i think its not default behavior then.
Sorry for confusion. Thanks.
