### ISSUE TITLE
non-git source and bundle config local override?

### ISSUE THREAD

**Issue by mooreniemi** [bundler/bundler#3507]
`C02LX2KVFD58:~/work repos/repo $ bundle config`

```
  Settings are listed in order of priority. The top value will be used.

  disable_local_branch_check
  Set for the current user (/Users/amooreniemi/.bundle/config): "true"

  local.core_resource
  Set for the current user (/Users/amooreniemi/.bundle/config): "/Users/amooreniemi/work repos/core-resource-rb"
```

`C02LX2KVFD58:~/work repos/repo $ bundle show core_resource`
```
  /Users/amooreniemi/.rvm/gems/jruby-1.7.4/gems/core_resource-1.0.7
```

The relevant gem "core_resource" is sourced from artifactory. Only my gems sourced from gitolite seem to respect the local override. So like `gem 'auth', git: 'gitolite@git.work.com:auth-gem',` is respected.

This is a huge bummer for me when developing at work, because it means I have to go back to using `path` directive overrides. It's annoying to have to worry about accidentally checking in a Gemfile that could break all my colleagues' boxes.

**Comment by TimMoore** [comment]
This is correct: the local override is only for git sources by design.

The reason for this is that Bundler needs to be able to lock to a specific version of the gem. When using git repos, it locks to a commit hash. It can use a local git repository to lock to a commit hash in the same way as a remote repo. If you're using a gem from a gem server, there's no way to fetch a specific git revision or match up a gem version to a git commit.

Without locking to a specific version, Bundler can't ensure the same code is running in production as on your development machine.

**Comment by mooreniemi** [comment]
@TimMoore thanks for the quick reply!

Does Bundler have any plans to support, in addition to commit hash, matching on semantic version? If not, we may move back off Artifactory to Gitolite, because the overhead of doing manual overrides is too much for our process currently.

Can you tell me where in the Bundler code base what you're describing is happening? I'd be curious if I could do a pull request to support matching on version (or maybe Zipcar can do a local fork for our purposes). AFAIK, gem server APIs usually do expose version as a matter of course. (I'm having trouble finding the artifactory docs on this, but from what I can see, it would.)

Also, perhaps I am misunderstanding, but it looks like at least the RubyGems API exposes the sha: http://guides.rubygems.org/rubygems-org-api/#gem-version-methods Would that not work to match on?

**Comment by indirect** [comment]
@mooreniemi the reason that local overrides only work with git repos is so that deploys to production will use _exactly_ the same code that you used in development as part of your local override.

Without a git repository, that's impossible. As a result, local overrides are only supported with git repositories.

**Comment by mooreniemi** [comment]
@indirect I understand, why is it impossible without a git repository? If a gem has a sha, why is that insufficient to check against?

**Comment by indirect** [comment]
Er... what gem are you talking about? Local development, by definition, means that there is not a released, packaged gem that Bundler could use.

**Comment by mooreniemi** [comment]
@indirect So we locally have git repos for us to work on our internally hosted gems. So locally, I def have a hash of my last commit (we're an all git house at Zipcar). No work is shared outside of it.

When I finish a ticket, I often have made changes to a gem, and made changes to an app using that gem (so the "host" app has the relevant Gemfile). So for the ticket to be tested and released, the QE needs to locally reproduce the feature functionality. To do this, they will jump on my branches (one branch per repo, so the gem has a branch and the host app a corresponding branch). However, my host app should have its Gemfile appropriate for production (so the QE can merge subsequent to test), which means I should not have any directives overriding the gem I also worked on.

Thus, if I've made changes to a gem as part of the same ticket, the QE needs to open the Gemfile, and manually override the gem to point to their local copy of the gem (which will also be on the branch of my current work). Then when they are done, they will manually remove that override from the Gemfile, and push the host app and gem changes to their respective master branches. At that point, no override is needed, because now my gem changes are in master, and we have Jenkins doing semantic versioning bumps on git commits.

My gem will be hosted on artifactory (internal only gem server, mainly used for java actually afaik, so it may just not be worth it in Ruby). 

When we were hosting our gems on gitolite, our internally hosted Gems were not managed via semantic versioning but via the git commit hash, so our QEs never needed to do this manual overriding in the Gemfile because bundle config would match on the gem name and use the local copy. (They'd just need to make sure they were locally pulled on my branch for my gem.)

Does that make a little more sense?

**Comment by indirect** [comment]
Yeah, you're doing it wrong. :) If you want to release gems, you have to _release_ gems. Release a new version of the gem that you've edited, and update the lock file in the host app to point to your new release. Then the QE person gets your changes by checking out the branch and running `bundle install`.

**Comment by mooreniemi** [comment]
@indirect What purpose does the local override serve then, if not to facilitate this kind of testing?

**Comment by indirect** [comment]
It allows you to develop locally when dependencies are experiencing a high rate of change without breaking the guarantee that you will deploy the same code that you used in development. That guarantee is the entire reason that Bundler exists.

**Comment by mooreniemi** [comment]
I must be misunderstanding something fundamental, so I appreciate your patience in replying. 

To Bundler's stated purpose, one needs a commit hash to have an absolute reference to compare the local code to the deployed code. Bundler relies on `revision: 5b333aa45844838d8159872abdb4aafe22cdbf64` in the Gemfile.lock for that, I am guessing, when a gem has the `git:` directive? Or for gems without it, it relies on semantic versioning which equals a release, I am further guessing?

If a gem server exposed that revision hash (and I'm guessing the sha RubyGems exposes is such), why couldn't that be used to the same purpose without the git directive?

I am not deeply experienced with dep management tools, but my intuition was basically, "a semantic version is a nicety for a human so they don't have to read a SHA". But the way it is implemented currently in Bundler, or the way I'm understanding your replies, you are saying a semantic version is for releases only, and a SHA can not be supported once a gem is released.

**Comment by segiddins** [comment]
If I'm correct, I believe that the local override doesn't affect the lockfile, so it exists purely as a development convenience -- as a means of opting out of dependency management for convenience while rapidly iterating.

**Comment by indirect** [comment]
@mooreniemi yeah, I think there are some missing pieces here. Git SHAs are derived from the files contained in the source code repository. Gems are released artifacts, containing some (but not all) of the files that were present in the git repository. The SHAs exposed by RubyGems.org are calculated from the `.gem` file, and have nothing whatsoever to do with any git SHAs.

There is no way to correlate git SHAs with released gems, and that is why the "git locals" feature requires git.

**Comment by TimMoore** [comment]
@mooreniemi it sounds like using gems sourced from git is a better fit for your workflow. Why did you move away from it?

@segiddins the local override _does_ affect the lock file. It will lock you to the latest commit in the local git repository, with the assumption that you'll be pushing the change in the gem to a remote repo and committing the change to `Gemfile.lock` in the app that depends on it.

If you have local changes that are not committed in the local gem repo, that is a bit of a loophole that you need to be careful with.

**Comment by mooreniemi** [comment]
@TimMoore we moved from gitolite to artifactory for hosting our gems. Don't blame me on this, I am not our devops department. :) I may, armed with this thread, push us to go back. But the reasoning for the move was so that our gems can have semantic versioning. That's a nice convenience for other teams that may want to pin to an older version of the gem. I think it may be better for us to just use a git tag instead though.

@indirect Yep, so relying on git makes sense given that implementation, and prevents working outside of exposing git hashes. But if Rubygems can calculate a SHA from a .gem file, why can't Bundler? IIRC, this is kinda what nix does. In which case, git is a convenience, not a necessity. Or is the Rubygems guarantee less strong than yours? My other thought is perhaps Artifactory (we have a vendor contact dude so who knows) could expose a git commit hash, in which case, I think the block would be on Bundler's side as I guess that gems without git directives don't get checked against the bundle config local.

Finally, to be fair, the only reason this comes up right now is because this gem is at the stage in its lifecycle where it's strongly coupled to its originating host app still. (The gem effectively blocks its host app when breaking changes happen.) My feeling at this point in my career is this is a typical, short-lived, and somewhat inevitable part of modularizing code, but hopefully I'll find a better way eventually. :)

**Comment by indirect** [comment]
I think you've hit the nail on the head: coupled gems should be git repos so they can change in concert with the host app, decoupled gems should be released with versions and used with versions. It doesn't make sense for us to support a complicated and honestly sketchy-sounding link between gems and git shas just for a situation that's supposed to be temporary. :)
