### ISSUE TITLE
Bundler can require incorrect system gem version

### ISSUE THREAD

**Issue by ktheory** [bundler/bundler#3508]
I noticed that my app was requiring a builtin gem version different from the one in Gemfile.lock and `vendor/cache`, even though I was installing gems with `bundle install --deployment --path ...`.

Turns out a debian package was installing a different version of minitest, and putting it earlier in the load path than the ruby package's version.

IMHO, this is a bundler issue b/c bundler is supposed to ensure that the gem versions in `Gemfile.lock` are the one's the application loads, regardless of other system gems.

### More details:

I made a [Docker image demonstrating the issue here](https://github.com/ktheory/bundler-system-gem-bug).

The Gemfile is locked to minitest `= 4.7.5`, which is also in `vendor/cache`.

The `ruby2.1` debian package installs minitest 4.7.5 to `/usr/lib/ruby/2.1.0`.

The `ruby-minitest` deb package installs minitest 5.2.1 to
`/usr/lib/ruby/vendor_ruby`.

Since the minitest 5.2.1 load path comes earlier 4.7.5, requiring minitest loads
5.2.1 instead of 4.7.5.

#### How to run the demo

Clone `https://github.com/ktheory/bundler-system-gem-bug.git` and run `docker build .`

Note the test failure in the output:
```
  1) Failure:
BundlerSystemGemBug#test_should_require_minitest_version_from_gemfile [/system-gem-bug.rb:9]:
Expected: "4.7.5"
  Actual: "5.2.1"
```

Commenting out [Dockerfile#14](https://github.com/ktheory/bundler-system-gem-bug/blob/64fe5ad8385513c97af76885a78129763cd33fc0/Dockerfile#L14) where the newer minitest version is installed makes the test pass.

FYI, this is the ruby load path:
```
# ruby -rbundler/setup -e 'puts $:'
/usr/lib/ruby/gems/2.1.0/gems/minitest-4.7.5/lib
/var/lib/gems/2.1.0/gems/bundler-1.9.1/lib/gems/bundler-1.9.1/lib
/var/lib/gems/2.1.0/gems/bundler-1.9.1/lib
/usr/local/lib/site_ruby/2.1.0
/usr/local/lib/x86_64-linux-gnu/site_ruby
/usr/local/lib/site_ruby
/usr/lib/ruby/vendor_ruby/2.1.0
/usr/lib/x86_64-linux-gnu/ruby/vendor_ruby/2.1.0
/usr/lib/ruby/vendor_ruby
/usr/lib/ruby/2.1.0
/usr/lib/x86_64-linux-gnu/ruby/2.1.0
```

**Comment by indirect** [comment]
Bundler manages gems, and the vendor_ruby directory is not for gems. It's fine for Debian to put ruby files wherever they want, but that package is not installing a gem, and so its outside the dependencies that Bundler can manage.





What you're asking for here is not simply load path management but also for Bundler to audit every single invocation of the "require" method, and I don't think that's possible with reasonable performance.

**Comment by ktheory** [comment]
Thanks so much for your quick reply @indirect (and for maintaining bundler!)

> What you're asking for here is not simply load path management but also for Bundler to audit every single invocation of the "require" method, and I don't think that's possible with reasonable performance.

All right, I figured this would be straightforward to fix by installing the vendored system gems to `BUNDLE_PATH`.

I can workaround this issue easily enough by making sure the `ruby-minitest` debian package isn't installed...but it seems like a gotcha that if it or similar deb pacakges are ever installed, it could break our app.

Also, it's weird that `/usr/lib/ruby/gems/2.1.0/gems/minitest-4.7.5/lib` is in the load path, but that directory doesn't exist. Presumably b/c the gemspec is installed nearby `/usr/lib/ruby/gems/2.1.0/specifications/default/minitest-4.7.5.gemspec`. Just the ways of brightbox's packages I guess.

Thanks again.

**Comment by indirect** [comment]
I think this is another example of how debian packages do things to ruby that are... idiosyncratic. The directory `/usr/lib/ruby/vendor_ruby` does not hold system gems, and files put into that directory are not even gems, let alone system gems. That is why Bundler isn't able to manage them. :(

**Comment by ktheory** [comment]
@indirect thanks for explaining...
> files put into that directory are not even gems

I wasn't familiar with `/usr/lib/ruby/vendor_ruby` until I ran in to this issue. I'll close this out with the understanding that installing stuff in that directory is counter to bundler's approach of requiring explicit gem versions.
