### ISSUE TITLE
bin/console & bin/setup should be executable for new gems

### ISSUE THREAD

**Issue by yuriihabrusiev** [bundler/bundler#3511]
As Bundler now generates `bin/` directory for development-only executables, default `bin/console` and `bin/setup` should be executable.

```
chmod +x bin/console
chmod +x bin/setup
```

**Comment by indirect** [comment]
Ack. they should be! Thanks for this report!

**Comment by indirect** [comment]
Fixed, and will be released shortly in 1.9.2.
