### ISSUE TITLE
Minitest template is wrong

### ISSUE THREAD

**Issue by yuriihabrusiev** [bundler/bundler#3512]
Bundler creates `test/test_#{my_gem}.rb` file with class `TestMyGem`, but common practice is to create `test/#{my_gem}_test.rb` file with class `MyGemTest`.

Also - why test helper called `minitest_helper`?

**Comment by arthurnn** [comment]
good catch @yuriihabrusiev .. I am working in a solution for this..
Indeed your 2 points should be followed.
