### ISSUE TITLE
Warnings with Bundler 1.9.1 from Molinillo

### ISSUE THREAD

**Issue by zzak** [bundler/bundler#3516]
Not sure if these were fixed in master yet.. or who to report it to..

```
/home/travis/.rvm/gems/ruby-2.2.0/gems/bundler-1.9.1/lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph.rb:64: warning: possible reference to past scope - vertices
/home/travis/.rvm/gems/ruby-2.2.0/gems/bundler-1.9.1/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:106: warning: private attribute?
/home/travis/.rvm/gems/ruby-2.2.0/gems/bundler-1.9.1/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:109: warning: private attribute?
/home/travis/.rvm/gems/ruby-2.2.0/gems/bundler-1.9.1/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:112: warning: private attribute?
```

**Comment by segiddins** [comment]
Those warnings disagree with the Molinillo style guide.

**Comment by JuanitoFatas** [comment]
Possible related: https://bugs.ruby-lang.org/issues/10967

**Comment by zzak** [comment]
I'm not familiar with Molinillo, or their style guide.. but it would be nice to fix these somehow.

Should I report this upstream?

**Comment by segiddins** [comment]
@zzak I am Molinillo, and my/the CocoaPods style guide is definitely in favor of using private attributes over direct ivar access.

**Comment by indirect** [comment]
We generally try to keep the Bundler codebase from containing any warnings, but the private attribute one seems especially weird/contested to me. :/

**Comment by segiddins** [comment]
I just fixed the first warning on `Molinillo` master, but I'm not changing the use of private attributes -- that's a silly warning imho.

**Comment by segiddins** [comment]
This is fixed in 1-9-stable.

**Comment by indirect** [comment]
This will be part of 1.9.2, released shortly.
