### ISSUE TITLE
Bundler sometimes spams one gem in Gemfile.lock

### ISSUE THREAD

**Issue by stalker37** [bundler/bundler#3522]
Bug #3216  return.

Version 1.9.1.
bug is alive
rvm use 2.1.5 do bundle install --path ../../shared/gems

Fetching gem metadata from http://rubygems.org/.........
Fetching version metadata from http://rubygems.org/..
Resolving dependencies....
Installing rake 10.4.2
Installing multi_json 1.11.0
..
Installing ansi 1.5.0
Using bundler 1.9.1

in Gemfile.lock i see

treetop (1.4.15)
polyglot
polyglot
polyglot
..
polyglot (>= 0.3.1)
polyglot (>= 0.3.1)
polyglot (>= 0.3.1)

**Comment by segiddins** [comment]
Can confirm. I'll look into fixing it this weekend, thanks for the bug report @stalker37

**Comment by arthurnn** [comment]
@segiddins the `treetop` gem has bad data in our dependencies db see  http://api.rubygems.org/api/v1/dependencies.json?gems=treetop

**Comment by indirect** [comment]
Going to release 1.9.2 with the fix for this shortly.
