### ISSUE TITLE
Move thread-safety warning to bottom of install output

### ISSUE THREAD

**Issue by indirect** [bundler/bundler#3523]
We print a warning when RubyGems is too old to support parallel gem installation:

> Rubygems 2.0.14 is not threadsafe, so your gems must be installed one at a time. Upgrade to Rubygems 2.1.0 or higher to enable parallel gem installation.

We should print that warning after the list of gems, because right now the warning usually scrolls off the screen by the time `bundle install` is finished.

**Comment by segiddins** [comment]
All warnings should probably be printed at the end of whatever command is invoked.

**Comment by pducks32** [comment]
Can we print them at both? So that if they see it at the beginning they can cancel the install and upgrade RG and not have to wait so much longer for them to be installed sequentially?

**Comment by pducks32** [comment]
And then maybe set a flag to turn off the message?

**Comment by indirect** [comment]
hmmmmmmm that's actually a good point. I take it back, we should print the RubyGems thread safety warning at the top, and other warnings at the bottom. :P
