### ISSUE TITLE
pre versions treated differently with 1.9.2

### ISSUE THREAD

**Issue by zanker** [bundler/bundler#3543]
Running into a strange issue with the dependency resolution in 1.9.2, downgrading to 1.8.6 works fine. I expect it's because of the pre gem.

None of the gems have a hard requirement, they're `>=` or none is set.

```
Bundler could not find compatible versions for gem "http-inhouse-gem":
  In snapshot (Gemfile.lock):
    http-inhouse-gem (= 3.0.3.pre6)

  In Gemfile:
    mail-inhouse-gem (>= 0) ruby depends on
      http-inhouse-gem (>= 0) ruby

    http-inhouse-gem (>= 3.0.3.pre5) ruby

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict
```

**Comment by zanker** [comment]
Actually looks like this mightttt be due to our internal Stickler servers not supporting the full dependency API.

**Comment by indirect** [comment]
@copiousfreetime y u hate the dependency api ;'(
