### ISSUE TITLE
 Encoding::CompatibilityError: incompatible encoding regexp match (UTF-8 regexp with ASCII-8BIT string)

### ISSUE THREAD

**Issue by qwerty2323** [bundler/bundler#3547]
HI, I'm trying to use bundler and this error pops-up.
P.S. Totall noob here.

Error details

    Encoding::CompatibilityError: incompatible encoding regexp match (UTF-8 regexp with ASCII-8BIT string)
    /home/USERNAME/.rvm/gems/ruby-2.1.3/gems/bundler-1.9.2/lib/bundler/dsl.rb:34:in `gsub'
    /home/USERNAME/.rvm/gems/ruby-2.1.3/gems/bundler-1.9.2/lib/bundler/dsl.rb:34:in `rescue in eval_gemfile'
    /home/USERNAME/.rvm/gems/ruby-2.1.3/gems/bundler-1.9.2/lib/bundler/dsl.rb:31:in `eval_gemfile'
    /home/USERNAME/.rvm/gems/ruby-2.1.3/gems/bundler-1.9.2/lib/bundler/dsl.rb:10:in `evaluate'
    /home/USERNAME/.rvm/gems/ruby-2.1.3/gems/bundler-1.9.2/lib/bundler/definition.rb:25:in `build'
    /home/USERNAME/.rvm/gems/ruby-2.1.3/gems/bundler-1.9.2/lib/bundler.rb:155:in `definition'
    /home/USERNAME/.rvm/gems/ruby-2.1.3/gems/bundler-1.9.2/lib/bundler/cli/install.rb:78:in `run'
    /home/USERNAME/.rvm/gems/ruby-2.1.3/gems/bundler-1.9.2/lib/bundler/cli.rb:157:in `install'
    /home/USERNAME/.rvm/gems/ruby-2.1.3/gems/bundler-1.9.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
    /home/USERNAME/.rvm/gems/ruby-2.1.3/gems/bundler-1.9.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
    /home/USERNAME/.rvm/gems/ruby-2.1.3/gems/bundler-1.9.2/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
    /home/USERNAME/.rvm/gems/ruby-2.1.3/gems/bundler-1.9.2/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
    /home/USERNAME/.rvm/gems/ruby-2.1.3/gems/bundler-1.9.2/lib/bundler/cli.rb:10:in `start'
    /home/USERNAME/.rvm/gems/ruby-2.1.3/gems/bundler-1.9.2/bin/bundle:20:in `block in <top (required)>'
    /home/USERNAME/.rvm/gems/ruby-2.1.3/gems/bundler-1.9.2/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
    /home/USERNAME/.rvm/gems/ruby-2.1.3/gems/bundler-1.9.2/bin/bundle:18:in `<top (required)>'
    /home/USERNAME/.rvm/gems/ruby-2.1.3/bin/bundle:23:in `load'
    /home/USERNAME/.rvm/gems/ruby-2.1.3/bin/bundle:23:in `<main>'
    /home/USERNAME/.rvm/gems/ruby-2.1.3/bin/ruby_executable_hooks:15:in `eval'
    /home/USERNAME/.rvm/gems/ruby-2.1.3/bin/ruby_executable_hooks:15:in `<main>'

Environment

    Bundler   1.9.2
    Rubygems  2.2.2
    Ruby      2.1.3p242 (2014-09-19 revision 47630) [x86_64-linux]
    GEM_HOME  /home/USERNAME/.rvm/gems/ruby-2.1.3
    GEM_PATH  /home/USERNAME/.rvm/gems/ruby-2.1.3:/home/qwerty/.rvm/gems/ruby-2.1.3@global
    RVM       1.25.31 (stable)
    Git       1.7.10.4
    rubygems-bundler (1.4.4)

**Comment by indirect** [comment]
Can you run `bundle env` and create a gist with the output for us to try to reproduce your problem? Thanks!

**Comment by qwerty2323** [comment]
Environment

    Bundler   1.9.2
    Rubygems  2.2.2
    Ruby      2.1.3p242 (2014-09-19 revision 47630) [x86_64-linux]
    GEM_HOME  /home/USERNAME/.rvm/gems/ruby-2.1.3
    GEM_PATH  /home/USERNAME/.rvm/gems/ruby-2.1.3:/home/qwerty/.rvm/gems/ruby-2.1.3@global
    RVM       1.25.31 (stable)
    Git       1.7.10.4
    rubygems-bundler (1.4.4)

Gemfile

    source 'https://rubygems.org'
    
    
    # Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
    gem 'rails', '4.1.6'
    
    # Use SCSS for stylesheets
    gem 'sass-rails', '~> 4.0.3'
    # Use Uglifier as compressor for JavaScript assets
    gem 'uglifier', '>= 1.3.0'
    # Use CoffeeScript for .js.coffee assets and views
    gem 'coffee-rails', '~> 4.0.0'
    # See https://github.com/sstephenson/execjs#readme for more supported runtimes
    gem 'therubyracer',  platforms: :ruby
    
    # Use jquery as the JavaScript library
    gem 'jquery-rails'
    # Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
    gem 'turbolinks'
    # Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
    gem 'jbuilder', '~> 2.0'
    # bundle exec rake doc:rails generates the API under doc/api.
    gem 'sdoc', '~> 0.4.0',          group: :doc
    
    # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
    group :development, :test do
    gem 'spring',        
    # Use postgereSQL as the database for Active Record
    gem 'pg', '~> 0.18.1'
    gem 'byebug',
    gem 'web-console',
    gem 'rspec'
    end
    # Use ActiveModel has_secure_password
    # gem 'bcrypt', '~> 3.1.7'
    
    # Use unicorn as the app server
    # gem 'unicorn'
    
    # Use Capistrano for deployment
    # gem 'capistrano-rails', group: :development
    
    # Use debugger
    # gem 'debugger', group: [:development, :test]

Gemfile.lock

    <No /home/USERNAME/Sites/TEST/Gemfile.lock found>

**Comment by indirect** [comment]
Your Gemfile has an error in it:

```
gem 'spring',        
```

is not valid Ruby. You need to delete the comma.

**Comment by segiddins** [comment]
When there's an error evaluating the Gemfile, we need to make sure to show a proper error.

**Comment by indirect** [comment]
@segiddins I'm pretty sure your Gemfile error pretty printing changes in master fixed this.

**Comment by segiddins** [comment]
@indirect maybe `Bundler.read_file` aught to convert the files contents to UTF8?

**Comment by qwerty2323** [comment]
It's all working now, thanks a lot!
