### ISSUE TITLE
can not start rails server 

### ISSUE THREAD

**Issue by diwu86** [bundler/bundler#3548]
I can not start rails server since Friday April 3rd. It took about 30mins to start. If I hit Ctrl-C , I see this error:

s/diwu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph.rb:237:in `shallow_eql?': Interrupt
	from /Users/diwu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph.rb:193:in `block in outgoing_edges'
	from /Users/diwu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph.rb:193:in `select'
	from /Users/diwu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph.rb:193:in `outgoing_edges'
	from /Users/diwu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph.rb:211:in `successors'
	from /Users/diwu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph.rb:251:in `path_to?'
	from /Users/diwu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph.rb:251:in `block in path_to?'
	from /Users/diwu/.rbenv/versions/2.1.2/lib/ruby/2.1.0/set.rb:263:in `each_key'
	from /Users/diwu/.rbenv/versions/2.1.2/lib/ruby/2.1.0/set.rb:263:in `each'
	from /Users/diwu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph.rb:251:in `any?'
	from /Users/diwu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph.rb:251:in `path_to?'
	from /Users/diwu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph.rb:251:in `block in path_to?'
	from /Users/diwu/.rbenv/versions/2.1.2/lib/ruby/2.1.0/set.rb:263:in `each_key'
	from /Users/diwu/.rbenv/versions/2.1.2/lib/ruby/2.1.0/set.rb:263:in `each'
	from /Users/diwu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph.rb:251:in `any?'
	from /Users/diwu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph.rb:251:in `path_to?'
	from /Users/diwu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph.rb:251:in `block in path_to?'
	from /Users/diwu/.rbenv/versions/2.1.2/lib/ruby/2.1.0/set.rb:263:in `each_key'
	from /Users/diwu/.rbenv/versions/2.1.2/lib/ruby/2.1.0/set.rb:263:in `each'
	from /Users/diwu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph.rb:251:in `any?'
	from /Users/diwu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph.rb:251:in `path_to?'
	from /Users/diwu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph.rb:251:in `block in path_to?'
	from /Users/diwu/.rbenv/versions/2.1.2/lib/ruby/2.1.0/set.rb:263:in `each_key'
	from /Users/diwu/.rbenv/versions/2.1.2/lib/ruby/2.1.0/set.rb:263:in `each'
	from /Users/diwu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph.rb:251:in `any?'
	from /Users/diwu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph.rb:251:in `path_to?'
	from /Users/diwu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph.rb:251:in `block in path_to?'
	from /Users/diwu/.rbenv/versions/2.1.2/lib/ruby/2.1.0/set.rb:263:in `each_key'
	from /Users/diwu/.rbenv/versions/2.1.2/lib/ruby/2.1.0/set.rb:263:in `each'
	from /Users/diwu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph.rb:251:in `any?'
	from /Users/diwu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph.rb:251:in `path_to?'
	from /Users/diwu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph.rb:251:in `block in path_to?'
	from /Users/diwu/.rbenv/versions/2.1.2/lib/ruby/2.1.0/set.rb:263:in `each_key'
	from /Users/diwu/.rbenv/versions/2.1.2/lib/ruby/2.1.0/set.rb:263:in `each'
	from /Users/diwu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph.rb:251:in `any?'
	from /Users/diwu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph.rb:251:in `path_to?'
	from /Users/diwu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph.rb:251:in `block in path_to?'
	from /Users/diwu/.rbenv/versions/2.1.2/lib/ruby/2.1.0/set.rb:263:in `each_key'
	from /Users/diwu/.rbenv/versions/2.1.2/lib/ruby/2.1.0/set.rb:263:in `each'
	from /Users/diwu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph.rb:251:in `any?'
	from /Users/diwu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph.rb:251:in `path_to?'
	from /Users/diwu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph.rb:251:in `block in path_to?'
	from /Users/diwu/.rbenv/versions/2.1.2/lib/ruby/2.1.0/set.rb:263:in `each_key'
	from /Users/diwu/.rbenv/versions/2.1.2/lib/ruby/2.1.0/set.rb:263:in `each'
	from /Users/diwu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph.rb:251:in `any?'
	from /Users/diwu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph.rb:251:in `path_to?'
	from /Users/diwu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph.rb:251:in `block in path_to?'
	from /Users/diwu/.rbenv/versions/2.1.2/lib/ruby/2.1.0/set.rb:263:in `each_key'
	from /Users/diwu/.rbenv/versions/2.1.2/lib/ruby/2.1.0/set.rb:263:in `each'
	from /Users/diwu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph.rb:251:in `any?'
	from /Users/diwu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph.rb:251:in `path_to?'
	from /Users/diwu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph.rb:251:in `block in path_to?'
	from /Users/diwu/.rbenv/versions/2.1.2/lib/ruby/2.1.0/set.rb:263:in `each_key'
	from /Users/diwu/.rbenv/versions/2.1.2/lib/ruby/2.1.0/set.rb:263:in `each'
	from /Users/diwu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph.rb:251:in `any?'
	from /Users/diwu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph.rb:251:in `path_to?'
	from /Users/diwu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph.rb:152:in `add_edge'
	from /Users/diwu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph.rb:101:in `block in add_child_vertex'
	from /Users/diwu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph.rb:100:in `each'
	from /Users/diwu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph.rb:100:in `add_child_vertex'
	from /Users/diwu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:391:in `block in require_nested_dependencies_for'
	from /Users/diwu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:391:in `each'
	from /Users/diwu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:391:in `require_nested_dependencies_for'
	from /Users/diwu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:381:in `activate_spec'
	from /Users/diwu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:358:in `attempt_to_activate_new_spec'
	from /Users/diwu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:313:in `attempt_to_activate'
	from /Users/diwu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:142:in `process_topmost_state'
	from /Users/diwu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:68:in `resolve'
	from /Users/diwu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/vendor/molinillo/lib/molinillo/resolver.rb:40:in `resolve'
	from /Users/diwu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/resolver.rb:200:in `start'
	from /Users/diwu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/resolver.rb:182:in `resolve'
	from /Users/diwu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/definition.rb:193:in `resolve'
	from /Users/diwu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/definition.rb:132:in `specs'
	from /Users/diwu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/definition.rb:177:in `specs_for'
	from /Users/diwu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/definition.rb:166:in `requested_specs'
	from /Users/diwu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/environment.rb:18:in `requested_specs'
	from /Users/diwu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/runtime.rb:13:in `setup'
	from /Users/diwu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler.rb:122:in `setup'
	from /Users/diwu/sage/sageone_us/host_app/config/boot.rb:16:in `<top (required)>'
	from /Users/diwu/.rbenv/versions/2.1.2/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/diwu/.rbenv/versions/2.1.2/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from script/rails:5:in `<main>'

Is this bundler related issue? If not, can anyone give me some hint how to solve this problem. Thanks.

**Comment by Tanete** [comment]
The error info after you pressed Ctrl-C maybe not accurate. I think you'd better move your project to another machine and try again.

**Comment by diwu86** [comment]
Several our developers got the similar error and we all have these :
/Users/diwu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph.rb:251:inany?'
from /Users/diwu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph.rb:251:in path_to?' from /Users/diwu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.9.2/lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph.rb:251:inblock in path_to?'
from /Users/diwu/.rbenv/versions/2.1.2/lib/ruby/2.1.0/set.rb:263:in each_key' from /Users/diwu/.rbenv/versions/2.1.2/lib/ruby/2.1.0/set.rb:263:ineach'....

**Comment by segiddins** [comment]
Hi @diwu86 , could you please share your Gemfile so I can reproduce the issue?

**Comment by diwu86** [comment]
Sorry I can not share my Gemfile because of the company security issue. But I will try to narrow down to some gems.

**Comment by diwu86** [comment]
I can not find any gem causing this issue. But once I downgrade bundler to 1.7.12, it works fine.

**Comment by indirect** [comment]
@diwu86 We cannot do anything to fix this problem unless you provide us with the information printed by running `bundle env`, including the Gemfile.
