### ISSUE TITLE
Bundler silently ignores StandardError when loading files

### ISSUE THREAD

**Issue by bricker** [bundler/bundler#3549]
Example project, explanation of problem, expected/actual result, and steps to reproduce can be found here: https://github.com/bricker/bundler_require_fail

With commit f740c40598142d990d59e129293c22c5d6f980b7 , a generic `rescue` block is wrapped around the `Kernel.require` line which loads your libraries. This block only outputs warning and debug text to `Bundler.ui`, which is [NOT VISIBLE by default](https://github.com/bundler/bundler/blob/c8c7d58a6628097bbe58dd47c11b5e9dc25c897a/lib/bundler.rb#L95-L97).

So, if the file being required throws any error inheriting from `StandardError` (most errors), the error is by default silently ignored and the file isn't loaded. This gives you confusing, unrelated errors that tell you nothing about the actual problem.

My suggestion is to either remove the generic `rescue`, or at least re-raise the error. Let me know the preferred fix and I can implement.

Thanks!

**Comment by indirect** [comment]
Yeah, I think reverting this is a good idea. Thanks for reporting!

**Comment by indirect** [comment]
This fix is released in 1.8.7, and will be released in 1.9.3 soon.
