### ISSUE TITLE
BUNDLE_PATH differences in local vs. global configuration

### ISSUE THREAD

**Issue by toupeira** [bundler/bundler#3552]
I have the following defaults in `~/.bundle/config`:

```yaml
---
BUNDLE_PATH: ".bundle"
BUNDLE_DISABLE_SHARED_GEMS: '1'
BUNDLE_BIN: ".bundle/bin"
```

For some reason this changes Bundler's behaviour (compared to having the same settings in a per-project config, without the defaults) to installing gems directly in `.bundle/gems` instead of `.bundle/ruby/$ABI_VERSION/gems`.

Looking at the [relevant code](https://github.com/bundler/bundler/blob/442d576a83f7e3324567fb93c43fc2b6da9074f1/lib/bundler/settings.rb#L126-L137) it turns out the Ruby scope is only appended to a locally set path, while a global setting or a `$BUNDLE_PATH` environment variable are used as-is.

Is this behaviour deliberate? I have a feeling this can cause problems with major Ruby upgrades, since compiled gems have to be linked to the new ABI. It also breaks [vim-bundler](https://github.com/tpope/vim-bundler) which doesn't detect gems in this unexpected location.

**Comment by indirect** [comment]
Sadly it seemed like a good idea to someone (not me) once, and now we have to support it until Bundler 2.0. :/ We are definitely changing it then, though. The closest you can do to a workaround today is to have your ruby version switcher set $BUNDLE_PATH to ~/path/RUBY_ENGINE/ABI_VERSION. Sorry about that!

@smlance this is another good simple change, printing a warning if the global setting is set in1.99 and then changing the behaviour in 2.0.

**Comment by toupeira** [comment]
Ok thanks, fair enough :)

If anybody else stumbles over this, the following hacky workaround does the trick for me with rbenv:

```sh
#!/usr/bin/env bash
ruby_abi=$( echo "$RBENV_VERSION" | cut -d. -f1-2 ).0
export BUNDLE_PATH=".bundle/ruby/$ruby_abi"
```

Place this in `~/.rbenv/plugins/bundle-path/etc/rbenv.d/exec/bundle-path.bash`.

**Comment by smlance** [comment]
I think this is handled in 2-0-dev: https://github.com/bundler/bundler/blob/2-0-dev/lib/bundler/settings.rb#L159-L175. It looks like `ruby_scope` will be concatenated to the bundle path as long as it's not the RubyGems bundle path.

I can write some specs at some point to check that globally configured paths include `ruby_scope`.

**Comment by toupeira** [comment]
Looks like it will break existing bundles in `.bundle/gems` though, so a warning would be nice.

**Comment by indirect** [comment]
The 2.0 upgrade will require running "bundle install" again, which will fix this--do you think adding a warning on top of that would be helpful?

**Comment by toupeira** [comment]
Ah ok in that case I don't really mind, though it still might be useful so users know they can delete their `.bundle/gems` folders. But this use case might be very rare and a mention in the release notes could be completely sufficient...

**Comment by rmm5t** [comment]
For any future onlookers: I packaged up what @toupeira suggested into a reusable rbenv plugin:
https://github.com/rmm5t/rbenv-bundle-path-fix

**Comment by msbit** [comment]
@indirect I seem to still be seeing this with v2.0.1, was the 1.x behaviour preserved, or do I need to update some other configuration item?

**Comment by indirect** [comment]
@msbit I think we pushed back the breaking change to Bundler 3.0, and there is ongoing work right now to add deprecation messages around breaking changes before we flip the switch.

**Comment by msbit** [comment]
Just had a look over the history of `lib/bundler/settings.rb` and noticed this [merged pull request](https://github.com/bundler/bundler/pull/6628) which adds a feature flag to make the behaviour consistent under 2.x, so now I can do the following: 

```
$ cat ~/.bundle/config
---
BUNDLE_PATH: "/home/tom/.gem"
BUNDLE_GLOBAL_PATH_APPENDS_RUBY_SCOPE: "true"
```

to deal with this for now.
