### ISSUE TITLE
bundle check options to skip all github / git gems

### ISSUE THREAD

**Issue by u007** [bundler/bundler#3561]
Hi,

is it possible to skip all git/github repository when doing bundle check?
im trying to check all gems which isnt installed on the system,
and i find it not possible if ive github or git gems in the gemfile.
and is there an options to 'checkall' to check all missing gems in gemfile?

thanks

**Comment by indirect** [comment]
No, unfortunately it's impossible to know if all the gems are installed without those git repositories—the git gems might need other gems!

**Comment by u007** [comment]
problem is, even if my github repositories are up to date, it still state its missing when i ran bundle check

**Comment by u007** [comment]
please reopen... its an issue

**Comment by indirect** [comment]
You original request is not an issue. If you're having a problem that you think may be a bug in Bundler, follow the instructions in [ISSUES](https://github.com/bundler/bundler/blob/master/ISSUES.md).
