### ISSUE TITLE
bundle exec error

### ISSUE THREAD

**Issue by sroller** [bundler/bundler#3573]
I tried to exec a script in the context of bundle. The call crashed right away.

Error details

    Errno::ENOEXEC: Exec format error - send_saved_filters.rb
    C:/RUBY/lib/ruby/gems/2.1.0/gems/bundler-1.9.4/lib/bundler/cli/exec.rb:30:in `exec'
    C:/RUBY/lib/ruby/gems/2.1.0/gems/bundler-1.9.4/lib/bundler/cli/exec.rb:30:in `run'
    C:/RUBY/lib/ruby/gems/2.1.0/gems/bundler-1.9.4/lib/bundler/cli.rb:271:in `exec'
    C:/RUBY/lib/ruby/gems/2.1.0/gems/bundler-1.9.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
    C:/RUBY/lib/ruby/gems/2.1.0/gems/bundler-1.9.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
    C:/RUBY/lib/ruby/gems/2.1.0/gems/bundler-1.9.4/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
    C:/RUBY/lib/ruby/gems/2.1.0/gems/bundler-1.9.4/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
    C:/RUBY/lib/ruby/gems/2.1.0/gems/bundler-1.9.4/lib/bundler/cli.rb:10:in `start'
    C:/RUBY/lib/ruby/gems/2.1.0/gems/bundler-1.9.4/bin/bundle:20:in `block in <top (required)>'
    C:/RUBY/lib/ruby/gems/2.1.0/gems/bundler-1.9.4/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
    C:/RUBY/lib/ruby/gems/2.1.0/gems/bundler-1.9.4/bin/bundle:18:in `<top (required)>'
    C:/ruby/bin/bundle:23:in `load'
    C:/ruby/bin/bundle:23:in `<main>'

Environment

    Bundler   1.9.4
    Rubygems  2.4.6
    Ruby      2.1.5p273 (2014-11-13 revision 48405) [i386-mingw32]
    GEM_HOME  C:/RUBY/lib/ruby/gems/2.1.0
    GEM_PATH  C:/RUBY/lib/ruby/gems/2.1.0;C:/Users/steffenr/.gem/ruby/2.1.0
    Git       1.9.5.msysgit.0

Bundler settings

    bin_path
      Set via BUNDLE_BIN_PATH: "C:/RUBY/lib/ruby/gems/2.1.0/gems/bundler-1.9.4/bin/bundle"
    gemfile
      Set via BUNDLE_GEMFILE: "C:/src/JIRA/Gemfile"

**Comment by segiddins** [comment]
@sroller what command did you run?

**Comment by sroller** [comment]
bundle exec <my-script>

**Comment by indirect** [comment]
Please follow [ISSUES](https://github.com/bundler/bundler/blob/master/ISSUES.md).

**Comment by sroller** [comment]
@indirect I'm on Windows. None of the hints apply.
There is no ~/.bundle, no ~/.gem/bundler, no ~/.gems/cache/bundler
no $GEM_HOME variable set
no vendor directory
I deleted Gemfile.lock
no rubygems-bundler, no open_gem
no rvm on Windows

    bundle install

runs ok, finishes with

    Bundle complete!

**Comment by indirect** [comment]
Is your ruby script not executable? Do you need to run "bundle exec ruby my_script.rb"?

**Comment by sroller** [comment]
@indirect Ha! That was it. I thought bundler would execute the script directly.

**Comment by indirect** [comment]
It did execute the script directly... but your script isn't a program. :)

**Comment by segiddins** [comment]
@indirect let's close this?
