### ISSUE TITLE
Bundler uses MRI even when started with JRuby (Windows)

### ISSUE THREAD

**Issue by jkutner** [bundler/bundler#3574]
On Windows, with this line my `Gemfile`:

```ruby
ruby '1.9.3', :engine => 'jruby', :engine_version => '1.7.18'
```

The following occurs if an MRI `ruby` is before `jruby` on my path:

```sh-session
> ruby -v 
ruby 2.1.5p273 (2014-11-13 revision 48405) [i386-mingw32]

> jruby -v
jruby 1.7.18 (1.9.3p551) 2014-12-22 625381c on Java HotSpot(TM) Client VM 1.8.0_45-b14 +jit [Windows 7-x86]

> jruby -S gem install bundler -v 1.9.4
...

> jruby -S bundle install
...

> jruby -S bundle exec rake db:create db:migrate
io/console not supported; tty will not be manipulated
Your Ruby engine is ruby, but your Gemfile specified jruby
```

If MRI is after JRuby on my path this problem does not occur (even though the JRuby installation does not have a `ruby` command).

**Comment by segiddins** [comment]
It's up to you to have the correct Ruby version show up as the `ruby` executable -- the `ruby` directive in your Gemfile won't change the ruby version, but only validates it.

**Comment by jkutner** [comment]
@segiddins why does it work when there is no `ruby` on my path at all? 

Shouldn't the runtime that initialized the bundler process take precedence over the `ruby` on my path?

**Comment by segiddins** [comment]
Ah I'm sorry, I misunderstood. Yes, the ruby that called the `bundle` command should be the one used. I'm guessing that might be a bug in `bundle exec`?

**Comment by jkutner** [comment]
@segiddins cool. I'll submit a patch for this shortly. Thanks for taking a look!

**Comment by indirect** [comment]
It sounds like your `rake` command might have a shebang that points to MRI. `bundle exec` has no control whatsoever (and has no way to have control over) the ruby that will be run by the `rake` command. All it can do is set `$RUBYOPT`, and then run the `rake` command.

**Comment by jkutner** [comment]
Oh I see, it's the `rake` on the path, not the `ruby` on the path. That makes it tricker.

So I've confirmed that I can fix this by running:

```
$ jruby -S bundle exec jruby -S rake db:create db:migrate
```

I will close this unless you have a suggestion on how to make this less verbose?

**Comment by indirect** [comment]
Run `jruby -S bundle binstubs rake` to create a `bin/rake` with a shebang that points to JRuby, and then just run `bin/rake db:create`.

**Comment by jkutner** [comment]
@indirect @segiddins thanks!
