### ISSUE TITLE
make bundler connection options configurable

### ISSUE THREAD

**Issue by peterlynch** [bundler/bundler#3583]
In environments where the remote server serving gems is slow to respond and or the work performed by the remote server to generate the response is significant ( long list of gems ) [the hardcoded connection timeout of 10 seconds](https://github.com/bundler/bundler/blob/master/lib/bundler/fetcher.rb#L61:L63) may not be enough to complete the request. Bundler will reset it's connection after 10 seconds and try again 3 times.

It would be helpful to provide a configuration option to adjust the connection timeout option so that bundler users can work around slowly performing hosts.

Since the logic and code touched would be near identical, consider making retries and redirect limit configurable as well, although less important for the purposes of this report.

These settings are typically more important in corporate environments where requests are routed through all manner of proxies and firewalls.

**Comment by indirect** [comment]
This seems reasonable. A pull request would be welcome!

**Comment by peterlynch** [comment]
BTW - I noticed you already have `--retry` option available to the install command.

**Comment by pducks32** [comment]
Finishing this up...I'll PR this evening.

**Comment by peterlynch** [comment]
I'd like to suggest that the setting be something a user can set once and forget it, in addition to a command line option. It is often hard to predict which requests will be the ones that will be slow, so a 'set and forget'  option is important.

**Comment by pducks32** [comment]
They'll be config options so you can set them per call using flags, or globally and locally with `bundle config`

**Comment by peterlynch** [comment]
looks fine here, although have not personally tested it

Thanks for your efforts

**Comment by mkristian** [comment]
great new to see my habit of of just rerun ```bundle install``` repeated tiime is going away soon. very much appreciated to be able to configure the timeouts and retries.
