### ISSUE TITLE
Gem found in multiple sources

### ISSUE THREAD

**Issue by nickpearson** [bundler/bundler#3585]
I had a similar problem as reported in #3378, and it appears to come up when a gem from the primary source depends on a gem from a custom source. For example, `stripe-ruby-mock` depends on `stripe`, and even when the `source` is specified for the `stripe` gem, Bundler is giving the "found in multiple sources" error.

Here's a quick demo to reproduce this. Note: if you have the `stripe` gem installed, you'll have to uninstall it in order to get the error message.

```bash
# if necessary, uninstall stripe gem
gem uninstall stripe

mkdir bundler-test && cd bundler-test
echo "source 'https://rubygems.org'"                   >> Gemfile
echo "gem 'json'"                                      >> Gemfile
echo "gem 'stripe', source: 'https://code.stripe.com'" >> Gemfile
echo "gem 'stripe-ruby-mock'"                          >> Gemfile
bundle install
```

This produces the following output:

```
Fetching source index from https://code.stripe.com/
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/.....
Fetching version metadata from https://rubygems.org/..
Fetching source index from https://code.stripe.com/
Using blankslate 3.1.3
Using dante 0.2.0
Using unf_ext 0.0.7.1
Using unf 0.1.4
Using domain_name 0.5.24
Using http-cookie 1.0.2
Using multi_json 1.11.0
Using rack 1.6.0
Using mime-types 2.4.3
Using netrc 0.10.3
Using rest-client 1.8.0
Using jimson-temp 0.9.5
Using json 1.8.2
Installing stripe 1.20.1
Using stripe-ruby-mock 2.1.1
Using bundler 1.9.4
Bundle complete! 3 Gemfile dependencies, 16 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
Warning: the gem 'stripe' was found in multiple sources.
Installed from: https://rubygems.org/
Also found in:
  * https://code.stripe.com/
You should add a source requirement to restrict this gem to your preferred source.
For example:
    gem 'stripe', :source => 'https://rubygems.org/'
Then uninstall the gem 'stripe' (or delete all bundled gems) and then install again.
```

This is on OS X 10.9 with Ruby 2.2.2 (p95) and Bundler 1.9.4.

Notes:
* The `json` gem is present as it seemed to be necessary to trigger the error message, possibly indicating a problem with mixed `source`s in gems in a dependency hierarchy (`stripe-ruby-mock` depends on `stripe` depends on `json`).
* Running `bundle install` again does not report an error. (Not a problem necessarily, just an observation for trying to reproduce this.)
* The error seemingly only appears on a fresh install (when `bundler` is the only installed gem prior to running `bundle install`) or when all of the gems in my example are installed except for `stripe`.

**Comment by rgb-one** [comment]
I have been able to reproduce the warnings using both bundler 1.7.6 and 1.9.4. My initial attempt with bundler 1.7.6 produced no warnings, however upon purging all locally installed gems, I was able to reproduce the scenario. This isn't an error as the gems are successfully retrieved and installed. The warnings are suggestions as far as I can see, however they do point to some less than ideal functionality.

Examining the output of both v1.7.6 and v1.9.4 which reproduces the scenario, bundler seems to handle prioritizing sources differently. In v1.7.6 the gem stripe is retrieved from the specified gem source `https://code.stripe.com/` while the dependencies which are available to both specified sources get retrieved from the primary source `https://rubygems.org/`. This behaviour is contradicted a bit in the output of v1.9.4 where all gems if available from both sources are retrieved from the primary source while only gems not available from the primary source are retrieved from the secondary source(s). On both occasions `bundle install` performs its task retrieving and installing the required gems, however, the way it does this in the two mentioned versions seem to be a bit different. Can a developer verify that there have been changes to how bundler retrieves gems from its sources?

Here are my outputs:
*bundler 1.7.6*
```
Fetching source index from https://code.stripe.com/
Fetching source index from https://code.stripe.com/
Fetching gem metadata from https://rubygems.org/...........
Fetching additional metadata from https://rubygems.org/.........
Resolving dependencies...
Installing blankslate 3.1.3
Installing dante 0.2.0
Installing unf_ext 0.0.7.1
Installing unf 0.1.4
Installing domain_name 0.5.24
Installing http-cookie 1.0.2
Installing multi_json 1.11.0
Installing rack 1.6.0
Installing mime-types 2.4.3
Installing netrc 0.10.3
Installing rest-client 1.8.0
Installing jimson-temp 0.9.5
Installing json 1.8.2
Installing stripe 1.20.1
Installing stripe-ruby-mock 2.1.1
Using bundler 1.7.6
Your bundle is complete!
Use `bundle show [gemname]` to see where a bundled gem is installed.
Warning: the gem 'mime-types' was found in multiple sources.
Installed from: https://rubygems.org/
Also found in:
  * https://code.stripe.com/
You should add a source requirement to restrict this gem to your preferred source.
For example:
    gem 'mime-types', :source => 'https://rubygems.org/'
Warning: the gem 'rest-client' was found in multiple sources.
Installed from: https://rubygems.org/
Also found in:
  * https://code.stripe.com/
You should add a source requirement to restrict this gem to your preferred source.
For example:
    gem 'rest-client', :source => 'https://rubygems.org/'
Warning: the gem 'stripe' was found in multiple sources.
Installed from: https://code.stripe.com/
Also found in:
  * https://rubygems.org/
You should add a source requirement to restrict this gem to your preferred source.
For example:
    gem 'stripe', :source => 'https://code.stripe.com/'
```

*bundler 1.9.4*
```
Fetching source index from https://code.stripe.com/
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/.....
Fetching version metadata from https://rubygems.org/..
Fetching source index from https://code.stripe.com/
Installing blankslate 3.1.3
Installing dante 0.2.0
Installing unf_ext 0.0.7.1
Installing unf 0.1.4
Installing domain_name 0.5.24
Installing http-cookie 1.0.2
Installing multi_json 1.11.0
Installing rack 1.6.0
Installing mime-types 2.4.3
Installing netrc 0.10.3
Installing rest-client 1.8.0
Installing jimson-temp 0.9.5
Installing json 1.8.2
Installing stripe 1.20.1
Installing stripe-ruby-mock 2.1.1
Using bundler 1.9.4
Bundle complete! 3 Gemfile dependencies, 16 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
Warning: the gem 'stripe' was found in multiple sources.
Installed from: https://rubygems.org/
Also found in:
  * https://code.stripe.com/
You should add a source requirement to restrict this gem to your preferred source.
For example:
    gem 'stripe', :source => 'https://rubygems.org/'
Then uninstall the gem 'stripe' (or delete all bundled gems) and then install again.
```

A minor suggestion, how about using yellow for warning messages? Yellow is the agreed upon convention for representing warnings no?

**Comment by TimMoore** [comment]
Another observation: I only see this behaviour when there is an existing, up-to-date `Gemfile.lock`. When I remove all gems and also remove `Gemfile.lock`, I do not see a warning.

**Comment by rgb-one** [comment]
Indeed @TimMoore, I have just tested removing the `Gemfile.lock` and `bundle install` perform without any warning message.

**Comment by TimMoore** [comment]
@nickpearson / @rgb-one I have a fix proposed at #3592. If you are able to test that branch with your projects, that would be really helpful. Thanks for the report!

**Comment by nickpearson** [comment]
Thanks @rgb-one for the added details and @TimMoore for the changes. I gave it a try and it seems to have fixed the issue on the first install, but I found a case where I still get the warning.

After successfully installing (with no warning), I uninstalled the `stripe` gem and ran `bundle install` again, which gave the same warning. This happens on the current `1.9.4` and on the `1.7-stable` branch, which contains your #3592 changes.

After some more testing, I think I've narrowed it down some more, and I simplified things by getting rid of the `json` and `stripe-ruby-mock` gem dependencies. I can reliably reproduce the warning with the following steps:

```bash
# uninstall stripe gem
gem uninstall stripe

mkdir bundler-test && cd bundler-test
echo "source 'https://rubygems.org'"                   >> Gemfile
echo "gem 'stripe', source: 'https://code.stripe.com'" >> Gemfile
bundle install
# no warning

# uninstall stripe gem again
gem uninstall stripe

bundle install
# warning shown
```

Hopefully this makes things easier to track down without the unnecessary dependencies.

A couple more things to note:

* This seems like an obscure case, but I came across this scenario after installing Ruby 2.2.2 (at which point I had an existing `Gemfile` and `Gemfile.lock` but only had the `bundler` gem installed) and running `bundle install` in my current project.
* To test your PR, I downloaded the [`1-7-stable` branch](https://github.com/bundler/bundler/tree/1-7-stable) and just ran `~/bundler-1-7-stable/bin/bundle install`. Let me know if there's a better way.

**Comment by indirect** [comment]
@nickpearson it looks like you wound up running your currently installed Bundler, rather than the Bundler that you had checked out. It's important to set up the Ruby load path so that you get the exact files you want. In [DEVELOPMENT], we suggest running a checkout like this: `ruby -I/path/to/bundler/lib /path/to/bundler/bin/bundle`.

I tested the particular case you outline above, and I was able to reproduce the warning with the current release of Bundler, but the warning was gone using the 1-7-stable branch. I'll cut new releases of 1.7, 1.8, and 1.9 with the fix tonight.

**Comment by nickpearson** [comment]
Excellent, thank you @TimMoore for the fix and @indirect for confirming and merging. Thanks also for the instructions on how to run a different version of Bundler by specifying a load path.

**Comment by hooopo** [comment]
@TimMoore @indirect After I update bundler version to 1.9.5 in my production server, I found issue with LOAD_PATH:

Gemfile:

```
source 'https://rubygems.org/'
gem 'core', :path => '../core'
```

And core gemspec:

```
s.add_runtime_dependency 'unf', '~> 0'
```

Bundler 1.9.5 - 1.11.2:
```
bundle -v && bundle exec ruby -e 'puts $LOAD_PATH'|grep unf
Bundler version 1.9.5
```

Bundler 1.9.4:

```
bundle -v && bundle exec ruby -e 'puts $LOAD_PATH'|grep unf
Bundler version 1.9.4
/var/www2/console/shared/bundle/ruby/2.1.0/gems/unf-0.1.4/lib
/var/www2/console/shared/bundle/ruby/2.1.0/gems/unf_ext-0.0.7.1/lib
/var/www2/console/shared/bundle/ruby/2.1.0/extensions/x86_64-linux/2.1.0-static/unf_ext-0.0.7.1
```

I think Bundler 1.9.4 is right.

**Comment by TimMoore** [comment]
Hi @hooopo this issue is closed... if you're still having issues with the latest version of Bundler, please follow the instructions at https://github.com/bundler/bundler/blob/master/ISSUES.md and create a new issue so that your report doesn't get lost. Thanks!
