### ISSUE TITLE
What if you *really* wanted to use a specific gem from the system, is there a way to do it with a hack or otherwise?

### ISSUE THREAD

**Issue by ginty** [bundler/bundler#3591]
Hi All,

Similar to #1964 I would like bundle install to use a gem from the system if it is already installed there rather than installing it again in the local bundle.

My situation is this:

* I am running Ruby in an enterprise environment, this is a Rhel5-based system with access to a tool collection from about 10 years ago. Individual users do not have root access.
* Furthermore updating this system Ruby to add new gems is a pain in the ass and not a straightforward process, so limiting users to bundle install --local will severely limit gem availability.
* Installing nokogiri in this environment is hard, despite that team's obvious effort to make it easier by packaging binaries, it is still hard to make it install reliably for all developers when they run bundle install.
* It has however been successfully installed to the system Ruby and it is available from there.
* In an effort to make user install more reliable we have specified an absolute version of nokogiri in all of our Gemfiles (the one that has been installed to the system), but nonetheless, nokogiri-related bundle install issues with individual user environments is a recurring problem.

Like #1964, what I would really like is for bundle install to recognize that the version of nokogiri the bundle needs is available from the system and to just use that, rather than trying to re-install it in the user's local gems.

It seems that the bundler core team do not want to provide this functionality, however as mentioned above using bundle --local is not really an option here.
Using something other than Bundler is not really an option either, since it is a great tool that solves 99.9% of our requirements except for this one thing.

So I am curious if any Bundler experts could advise on possible hacks that I could make to a fork of Bundler to enable this, or any other approach that they could recommend?

Many thanks in advance,
Stephen

**Comment by indirect** [comment]
As you note in your message, the way that Bundler works is to automatically set up gems from one place. You can choose whether to use "system" gems (meaning gems installed to the same place as the `gem install` command would use), or install bundled gems to a specific location dedicated to that application. In early alpha versions of Bundler, we experimented with the ability to use gems from both locations at the same time, and it was a huge failure. It was confusing, it caused bugs, and it was extremely hard to manage or reason about.

If your users can read the system gems, why not copy the installed copy of nokogiri into the local bundle? While I appreciate that Bundler nearly does what you want, we don't have plans to ever support simultaneously using gems from more than one place.

**Comment by akostadinov** [comment]
I think the issue is only to allow `local-first` resolution of gems with a separate switch, rather than force downloading newest version when version is not fixed. I couldn't see any compelling argument why user should not be allowed that freedom.
