### ISSUE TITLE
Compromise in infinite loop on circular dependency.

### ISSUE THREAD

**Issue by digitalextremist** [bundler/bundler#3594]
Searching for `infinite` returns over 30 issues. I see fairly recently a new dependency resolver was put in place, but the issue still remains. Because sometimes circular dependencies are needed. In that case they are not "circular" but "interdependent" -- however Bundler cannot function in that condition.

IMHO, Bundler ought to detect that a circular dependency exists, and to satisfy the dependency at the point that it begins to recurse. It ought to be a point of flow-control, not a point of failure:

https://github.com/bundler/bundler/blob/master/lib/bundler/resolver.rb

At this point, if the dependency has been met ( the gem already exists in the bundle ) could it not just stop here, and continue on? At the very least a warning could be shown, but even that seems unnecessary. The next problem would be scary warnings about fully safe gems.

The behavior I am suggesting is safe, because moving the gems out of `Gemfile` and into `gemspec` only, allows the application to run. The problem with that solution is it's not possible to specify a git repository for the location of the gem. Any changes to the gem need to be cut and pushed to RubyGems. This leads to many needless gems in RubyGems, and a lot of extra steps in CI and local debugging.

##### The example prompting the compromise:

* `celluloid` depends on:
    * `celluloid-extras`
    * `celluloid-essentials`
* `celluloid-supervision` depends on:
    * `celluloid-essentials` ( expecting `celluloid` itself to come along )
* `celluloid-pool` depends on:
    * `celluloid-essentials` ( expecting `celluloid` itself to come along )
* `celluloid-fsm` depends on:
    * `celluloid-essentials` ( expecting `celluloid` itself to come along )
* `celluloid-essentials` depends on:
    * `celluloid` itself.
        * It is useless alone, but collects gems together mostly.
        * This is needed for tests primarily, but still.
    * `celluloid-supervision` ( for backport of expected behaviors )
    * `celluloid-pool` ( for backport of expected behaviors )
    * `celluloid-fsm` ( for backport of expected behaviors )
* Etc...

Right now these are all spelled out in the respective `gemspec` files, but it causes the problem I mentioned.

**Comment by digitalextremist** [comment]
At first it seemed like removing the `gemspec` call from the `Gemfile` resolved the issue, but it does not.

**Comment by digitalextremist** [comment]
The example prompting the compromise:

* `celluloid-supervision` depends on:
    * `celluloid-essentials` ( expecting `celluloid` itself to come along )
* `celluloid-pool` depends on:
    * `celluloid-essentials` ( expecting `celluloid` itself to come along )
* `celluloid-fsm` depends on:
    * `celluloid-essentials` ( expecting `celluloid` itself to come along )
* `celluloid-essentials` depends on:
    * `celluloid` itself; it is useless alone, but collects gems together mostly.
    * `celluloid-supervision` ( for backport of expected behaviors )
    * `celluloid-pool` ( for backport of expected behaviors )
    * `celluloid-fsm` ( for backport of expected behaviors )
* `celluloid` depends on:
    * `celluloid-extras`
    * `celluloid-essentials`
    * `celluloid-supervision` ( for backport of expected behaviors )
    * `celluloid-pool` ( for backport of expected behaviors )
    * `celluloid-fsm` ( for backport of expected behaviors )

Right now these are all spelled out in the respective `gemspec` files, but it causes the problem I mentioned.

**Comment by digitalextremist** [comment]
More discussion of the issue: http://stackoverflow.com/questions/29893470/how-to-create-interdependent-ruby-gems-with-bundler-and-still-use-repositories

**Comment by digitalextremist** [comment]
The the time being, the only solution other than the problems caused by #3597, is to have each gem depend on each other.

**Comment by indirect** [comment]
If a gem (let's call it A) has a dependency (let's call it B), that implies that gem A will `require` code from gem B. The `require` statement in gem A means that gem A cannot run until code from gem B is loaded. If code from gem A requires code from gem B that in turn requires code from gem A, that is an impossible dependency. I don't understand how "compromise" is possible in a situation where the interpreter either dies in an infinite loop or prints a "circular dependencies are bad, stop that" warning.
