### ISSUE TITLE
Add Information About Testing to Default Readme

### ISSUE THREAD

**Issue by fny** [bundler/bundler#3596]
It's a bit awkward that there's info provided about how to dive into a console but none about how to run tests, especially given the importance of testing!

In fact, it might be even more helpful to provide required configuration to make `rake test` actually do something.

**Comment by indirect** [comment]
The readme is aimed at end-users of Bundler, not developers of Bundler. The `DEVELOPMENT.md` file is the correct place for this, and we in fact explain not only [which commands to run](https://github.com/bundler/bundler/blob/master/DEVELOPMENT.md#development-setup), but how to use an in-development version of Bundler from the command line as well.

That said, I think it makes sense to clearly link to the DEVELOPMENT.md file from the main readme, noting that it contains information on how to do development work on the Bundler codebase. Pull requests to do that would be welcome!

**Comment by fny** [comment]
I don't think I was clear enough. I'm talking about the [default readme for new gems](https://github.com/bundler/bundler/blob/master/lib/bundler/templates/newgem/README.md.tt) not Bundler's readme.

**Comment by indirect** [comment]
Oh! Yeah, the readme saying "run bundle install" seems good. The gem template doesn't include tests by default, but if you want to add instructions to the readme conditional on testing being enabled, go for it.

**Comment by simi** [comment]
I think a short info about `rake test` will be welcomed here when testing is enabled.
