### ISSUE TITLE
Neither Gemfile nor gemspec causing download of 4th tier of dependencies.

### ISSUE THREAD

**Issue by digitalextremist** [bundler/bundler#3597]
Stumbled onto trying to solve #3594:

Now if I do this arrangement instead... see image:

![gems](https://cloud.githubusercontent.com/assets/21095/7369930/fdb7b312-ed6a-11e4-8087-224b79a85e48.png)

... the ones in gray don't even download! No circular dependency any more, but even if I have a local repository mapped to that gem in the Gemfile, the gem doesn't get added to the bundle.

`gem -v` reads `2.4.6`
`bundle -v` reads `1.6.2`

Here are the abridged `gemspecs` and `Gemfiles` which just dependency pieces added. I've tried `add_runtime_dependency` and `add_dependency` and `add_development_dependency` no change.

### `celluloid.gemspec`
```ruby
Gem::Specification.new do |gem|
  gem.add_runtime_dependency "celluloid-essentials"
  gem.add_dependency 'bundler'
end
```
### `celluloid-essentials.gemspec`
```ruby
Gem::Specification.new do |gem|
  gem.add_development_dependency 'bundler'
  gem.add_dependency 'celluloid-gems', '0.20.0'
end
```

### `celluloid-gems.gemspec`
```ruby
Gem::Specification.new do |gem|
  gem.add_runtime_dependency "celluloid-extras", ">= 0.1.0"
  gem.add_runtime_dependency "celluloid-supervision", ">= 0.10.0.pre2"
  gem.add_runtime_dependency "celluloid-fsm", ">= 0.9.0.pre1"
  gem.add_runtime_dependency "celluloid-pool", ">= 0.10.0.pre2"
  gem.add_dependency 'bundler'
end
```

### `celluloid-*` ( `pool`, `supervision`, `fsm`, `extras` are all the same )
```ruby
Gem::Specification.new do |gem|
  gem.add_development_dependency 'bundler'
  gem.add_dependency "celluloid"
end
```

---

### `Gemfile` for those four gems:

```ruby
source 'https://rubygems.org'
gemspec
gem 'celluloid', github: 'celluloid/celluloid', branch: '0.17.0-prerelease'
```

### `Gemfile` for `celluloid-gems`
```ruby
source 'https://rubygems.org'
gemspec
gem 'celluloid-extras', github: 'celluloid/celluloid-extras', branch: 'master'
gem 'celluloid-supervision', github: 'celluloid/celluloid-supervision', branch: 'master'
gem 'celluloid-pool', github: 'celluloid/celluloid-pool', branch: 'master'
gem 'celluloid-fsm', github: 'celluloid/celluloid-fsm', branch: 'master'
```

### `Gemfile` for `celluloid-essentials`
```ruby
source 'https://rubygems.org'
gemspec
gem "bundler"
gem "coveralls", require: false
gem "celluloid-gems", github: "celluloid/celluloid-gems", branch: "master"
```

### `Gemfile` for `celluloid`
```ruby
source 'https://rubygems.org'
gemspec
gem "bundler"
gem "coveralls", require: false
gem "timers", github: "celluloid/timers"
gem "celluloid-essentials", github: "celluloid/celluloid-essentials", branch: "master"
```

Output of `bundle update` in `celluloid` directory:

```ruby
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Using rake 10.4.2
Using ast 2.0.0
Using parser 2.2.2.1
Using astrolabe 1.3.0
Using benchmark-ips 1.2.0
Using benchmark_suite 1.0.0
Using bundler 1.6.2
Using celluloid 0.17.0.pre7 from source at .
Using celluloid-gems 0.20.0
Using celluloid-essentials 0.20.0.pre12 from git://github.com/celluloid/celluloid-essentials.git (at /home/de/FOSS/celluverse/celluloid-essentials)
Using coderay 1.1.0
Using json 1.8.2
Using unf_ext 0.0.7.1
Using unf 0.1.4
Using domain_name 0.5.24
Using http-cookie 1.0.2
Using mime-types 2.5
Using netrc 0.10.3
Using rest-client 1.8.0
Using docile 1.1.5
Using simplecov-html 0.10.0
Using simplecov 0.10.0
Using tins 1.5.1
Using term-ansicolor 1.3.0
Using thor 0.19.1
Using coveralls 0.8.1
Using diff-lcs 1.2.5
Using dotenv 2.0.1
Using ffi 1.9.8
Using formatador 0.2.5
Using rb-fsevent 0.9.4
Using rb-inotify 0.9.5
Using listen 2.9.0
Using lumberjack 1.0.9
Using nenv 0.2.0
Using shellany 0.0.1
Using notiffany 0.0.6
Using method_source 0.8.2
Using slop 3.6.0
Using pry 0.10.1
Using guard 2.12.5
Using guard-compat 1.2.1
Using rspec-support 3.2.2
Using rspec-core 3.2.3
Using rspec-expectations 3.2.1
Using rspec-mocks 3.2.1
Using rspec 3.2.0
Using guard-rspec 4.5.0
Using hitimes 1.2.2
Using powerpack 0.1.0
Using rainbow 2.0.0
Using rspec-log_split 0.1.2 from git://github.com/abstractive/rspec-log_split.git (at master)
Using rspec-retry 0.4.0
Using ruby-progressbar 1.7.5
Using rubocop 0.30.1
Using timers 4.0.1 from git://github.com/celluloid/timers.git (at master)
Your bundle is updated!
```

None of the 4 gray gems... What can I do to get those dependencies to link?

---

If I remove `celluloid-gems` and have `celluloid-essentials` depend on the gray four, #3594 comes back. No matter what something is either missing, or broken, but this arrangement is necessary!

And from the 4 gems, `timers` isn't available... which is totally unrelated, but equally vital.

---

I've performed all the 'clear out before asking' tasks, no caches, no lingering data. I would really appreciate help with this. This is holding back the release of each of those gems.

**Comment by digitalextremist** [comment]
The the time being, the only solution other than the problems caused by #3594, is to have each gem depend on each other.

**Comment by indirect** [comment]
Thank you for the report! Unfortunately, this explanation does not tell me how to reproduce the problem. Please provide clear reproduction steps (or best yet, a script to reproduce the issue), with an explanation of:

  1. The command you ran
  2. What you expected to happen
  3. What happened instead

**Comment by agis-** [comment]
@digitalextremist Closing this due to lack of feedback. Please share more info and we'll hapilly reopen. Thanks!
