### ISSUE TITLE
Update source code repo URL on rubygems.org

### ISSUE THREAD

**Issue by nirvdrum** [bundler/bundler#3598]
The source code repository listed for Bundler on rubygems.org is http://github.com/carlhuda/bundler/.  While this is configured to redirect to https://github.com/bundler/bundler, it'd be helpful for API clients if the value were updated in RubyGems.

**Comment by pducks32** [comment]
You should open an issue on their repo: https://github.com/rubygems/rubygems.org

**Comment by nirvdrum** [comment]
They don't maintain that metadata.  The owner of a gem is responsible for supplying the values.

**Comment by pducks32** [comment]
Oh sorry I thought you meant the link t bundler on rubygems in general not on the actual bundler gem page.

**Comment by segiddins** [comment]
Just updated the rubygems.org metadata, thanks for the heads up @nirvdrum !
