### ISSUE TITLE
(<unknown>): could not find expected ':' while scanning a simple key at line 2 column 1

### ISSUE THREAD

**Issue by rafaeldelucena** [bundler/bundler#3599]
- What did you do?
Install Rubies behind a proxy on Ubuntu 14.04 LTS, following this link: https://gorails.com/setup/ubuntu/14.04
- What did you expect to happen?
- What happened instead?
See below

Error details

    Psych::SyntaxError: (<unknown>): could not find expected ':' while scanning a simple key at line 2 column 1
    /home/rafael/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/psych.rb:370:in `parse'
    /home/rafael/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/psych.rb:370:in `parse_stream'
    /home/rafael/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/psych.rb:318:in `parse'
    /home/rafael/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/psych.rb:245:in `load'
    /home/rafael/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/config_file.rb:333:in `load_file'
    /home/rafael/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/config_file.rb:198:in `initialize'
    /home/rafael/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems.rb:297:in `new'
    /home/rafael/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems.rb:297:in `configuration'
    /home/rafael/.rvm/gems/ruby-2.2.1/gems/bundler-1.9.4/lib/bundler/rubygems_integration.rb:49:in `configuration'
    /home/rafael/.rvm/gems/ruby-2.2.1/gems/bundler-1.9.4/lib/bundler/rubygems_integration.rb:72:in `sources='
    /home/rafael/.rvm/gems/ruby-2.2.1/gems/bundler-1.9.4/lib/bundler/fetcher.rb:207:in `specs'
    /home/rafael/.rvm/gems/ruby-2.2.1/gems/bundler-1.9.4/lib/bundler/source/rubygems.rb:324:in `block (2 levels) in remote_specs'
    /home/rafael/.rvm/gems/ruby-2.2.1/gems/bundler-1.9.4/lib/bundler/source/rubygems.rb:322:in `each'
    /home/rafael/.rvm/gems/ruby-2.2.1/gems/bundler-1.9.4/lib/bundler/source/rubygems.rb:322:in `block in remote_specs'
    /home/rafael/.rvm/gems/ruby-2.2.1/gems/bundler-1.9.4/lib/bundler/index.rb:9:in `build'
    /home/rafael/.rvm/gems/ruby-2.2.1/gems/bundler-1.9.4/lib/bundler/source/rubygems.rb:305:in `remote_specs'
    /home/rafael/.rvm/gems/ruby-2.2.1/gems/bundler-1.9.4/lib/bundler/source/rubygems.rb:79:in `specs'
    /home/rafael/.rvm/gems/ruby-2.2.1/gems/bundler-1.9.4/lib/bundler/lazy_specification.rb:53:in `__materialize__'
    /home/rafael/.rvm/gems/ruby-2.2.1/gems/bundler-1.9.4/lib/bundler/spec_set.rb:88:in `block in materialize'
    /home/rafael/.rvm/gems/ruby-2.2.1/gems/bundler-1.9.4/lib/bundler/spec_set.rb:85:in `map!'
    /home/rafael/.rvm/gems/ruby-2.2.1/gems/bundler-1.9.4/lib/bundler/spec_set.rb:85:in `materialize'
    /home/rafael/.rvm/gems/ruby-2.2.1/gems/bundler-1.9.4/lib/bundler/definition.rb:132:in `specs'
    /home/rafael/.rvm/gems/ruby-2.2.1/gems/bundler-1.9.4/lib/bundler/definition.rb:121:in `resolve_remotely!'
    /home/rafael/.rvm/gems/ruby-2.2.1/gems/bundler-1.9.4/lib/bundler/installer.rb:79:in `run'
    /home/rafael/.rvm/gems/ruby-2.2.1/gems/bundler-1.9.4/lib/bundler/installer.rb:18:in `install'
    /home/rafael/.rvm/gems/ruby-2.2.1/gems/bundler-1.9.4/lib/bundler/cli/install.rb:80:in `run'
    /home/rafael/.rvm/gems/ruby-2.2.1/gems/bundler-1.9.4/lib/bundler/cli.rb:157:in `install'
    /home/rafael/.rvm/gems/ruby-2.2.1/gems/bundler-1.9.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
    /home/rafael/.rvm/gems/ruby-2.2.1/gems/bundler-1.9.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
    /home/rafael/.rvm/gems/ruby-2.2.1/gems/bundler-1.9.4/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
    /home/rafael/.rvm/gems/ruby-2.2.1/gems/bundler-1.9.4/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
    /home/rafael/.rvm/gems/ruby-2.2.1/gems/bundler-1.9.4/lib/bundler/cli.rb:10:in `start'
    /home/rafael/.rvm/gems/ruby-2.2.1/gems/bundler-1.9.4/bin/bundle:20:in `block in <top (required)>'
    /home/rafael/.rvm/gems/ruby-2.2.1/gems/bundler-1.9.4/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
    /home/rafael/.rvm/gems/ruby-2.2.1/gems/bundler-1.9.4/bin/bundle:18:in `<top (required)>'
    /home/rafael/.rvm/gems/ruby-2.2.1/bin/bundle:23:in `load'
    /home/rafael/.rvm/gems/ruby-2.2.1/bin/bundle:23:in `<main>'
    /home/rafael/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
    /home/rafael/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'

Environment

    Bundler   1.9.4
    Rubygems  2.4.6
    Ruby      2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]
    GEM_HOME  /home/rafael/.rvm/gems/ruby-2.2.1
    GEM_PATH  /home/rafael/.rvm/gems/ruby-2.2.1:/home/rafael/.rvm/gems/ruby-2.2.1@global
    RVM       1.26.11 (latest)
    Git       1.9.1
    rubygems-bundler (1.4.4)

**Comment by segiddins** [comment]
This appears to be an issue with RubyGems reading its config file, rather than a bundler issue.
