### ISSUE TITLE
Fix (& document) ignore_message config

### ISSUE THREAD

**Issue by indirect** [bundler/bundler#3600]
Right now the ignore_message config isn't documented in the `config` manpage, and it also causes empty post-install messages to be printed out for every gem that isn't actively ignored. We should fix that for 1.10 :)

/cc @pducks32

**Comment by pducks32** [comment]
So is every gem—even ones w/o a post-install message—printing an empty one?

**Comment by segiddins** [comment]
This should probably be fixed in 1-9-stable
