### ISSUE TITLE
Existing Bundler conflict when creating development environment

### ISSUE THREAD

**Issue by cdwort** [bundler/bundler#3605]
Hi All, 

@indirect and @segiddins let me know in #3604 that I should not have to uninstall an existing version of bundler in order to build the development dependencies. I ran into the following problem which was solved by uninstalling bundler.

Ruby version
```
$ ruby -v
ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-darwin13.0]
```
RubyGems version (used both 2.4.6 and 2.2.2)
```
$ gem -v
2.4.6
```
Bundler version
```
$ bundle -v
Bundler version 1.7.6
```
RVM version
```
$ gem -v
rvm 1.26.10 (master) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
```

Steps to repro:
1. Clone bundler/bundler repo
2. cd into top level of repo
3. At master (SHA: 9191d8ffe8f3dc242222f02a6db07e5ea766c524)
4. run `rake spec:deps`

Output (with my debugging statements):
```
$ rake spec:deps
[DEBUG LOG IN shared_helpers.rb#pwd] Bundler.rubygems.class: Bundler::RubygemsIntegration::Future
[DEBUG LOG IN shared_helpers.rb#pwd] Bundler.rubygems.version: #<Gem::Version "2.4.6">
[DEBUG LOG IN shared_helpers.rb#pwd] Bundler.rubygems.version.source_location: ["/Users/James/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.6/lib/bundler/rubygems_integration.rb", 15]
rake aborted!
NoMethodError: undefined method `ext_lock' for #<Bundler::RubygemsIntegration::Future:0x007fccb3123d38>
/Users/James/dev/bundler/lib/bundler/shared_helpers.rb:60:in `pwd'
/Users/James/dev/bundler/lib/bundler/gem_helper.rb:27:in `initialize'
/Users/James/dev/bundler/lib/bundler/gem_helper.rb:13:in `new'
/Users/James/dev/bundler/lib/bundler/gem_helper.rb:13:in `install_tasks'
/Users/James/dev/bundler/lib/bundler/gem_tasks.rb:2:in `<top (required)>'
/Users/James/dev/bundler/Rakefile:309:in `<top (required)>'
/Users/James/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
/Users/James/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
(See full trace by running task with --trace)
```

Once I saw this was finding the classes in the pre-installed Bundler, I just uninstalled all versions of bundler in my global gemset for Ruby 2.1.5.

Reinstalling Bundler into that gemset recreated the error.

Happy to get you any additional information that would be helpful.

Thanks!

**Comment by segiddins** [comment]
That stack trace doesn't look like it contains the global bundler to me?

**Comment by cdwort** [comment]
The stack trace is fine, yes. But the call that fails in the repo code is calling a class which is defined in the global gemset. See the logging statement... 

Maybe I'm wrong, but once I uninstalled the global gem, then the `source_location` pointed to the repo's definition of RubygemsIntegration class and everything worked.

I also put a bunch of logging statements in the initialization of the RubygemIntegration class. It never hit the repo code until I removed the preinstalled bundler.

**Comment by cdwort** [comment]
Relevant logging statement:
`[DEBUG LOG IN shared_helpers.rb#pwd] Bundler.rubygems.version.source_location: ["/Users/James/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.6/lib/bundler/rubygems_integration.rb", 15]`

**Comment by indirect** [comment]
That makes it sound like Bundler was required before Rake was even loaded. Do you by any chance have the rubygems-bundler gem installed?

**Comment by cdwort** [comment]
Ah, yes, I do! I forgot that question from the ISSUES.md.

When I uninstall rubygems-bundler, everything works as expected.

Thanks for your time! Sorry it was something you've probably seen hundreds of times.

**Comment by indirect** [comment]
Ugh, that gem causes more problems by itself than any other single thing I can think of. :( Sorry for the trouble, and thanks for reporting your issue!
