### ISSUE TITLE
Bundler should NOT include private credentials in Gemfile.lock from source urls in Gemfile

### ISSUE THREAD

**Issue by joelpresence** [bundler/bundler#3609]
Hi,

I use GemFury for private gems.  In my `Gemfile` I have code like:
```
# In Gemfile
source "https://#{ENV['FURY_AUTH']}@gem.fury.io/devpresence/" do
  gem 'presence_common_web', '~> 0.1.4'
end
```
The environment variable `FURY_AUTH` has value `_MY_SECRET_FURY_TOKEN_`.  When I run `bundle install` or `bundle update`, bundler updates `Gemfile.lock` to include:
```
# In Gemfile.lock
remote: https://_MY_SECRET_FURY_TOKEN_@gem.fury.io/devpresence/
```
This is a risk because now `_MY_SECRET_FURY_TOKEN_` risks getting committed to source control.  I took great care to *not* list my secret token in plain text in `Gemfile` (e.g. by specifying it as an env var) so bundler/gems should not now just write the secret token to the `Gemfile.lock`.

When I deploy this, say to Heroku, I further specify an env var as in:
```
bash> heroku config:set FURY_AUTH=_MY_SECRET_FURY_TOKEN_
```
so even Heroku deploys don't contain my secret token (except in private runtime config).

Further, when I run tests, bundler seems to periodically update `Gemfile.lock`.  So even if I manually edit `Gemfile.lock` to remove `_MY_SECRET_FURY_TOKEN_`, bundler seems to periodically re-add it, without me even running bundler manually (maybe rspec is doing this?).

I would propose that if a source url in the Gemfile contains valid HTTP credentials, and the bundler-created `Gemfile.lock` remote url contains credentials as in:
```
remote: https://token@host/path
remote: https://user:password@host/path
```
then bundler should automatically strip these when it's creating the `Gemfile.lock` from `Gemfile`.

So
```
# CASE 1: CURRENT BEHAVIOR
# In Gemfile
source "https://#{ENV['FURY_AUTH']}@gem.fury.io/devpresence/" do
  gem 'presence_common_web', '~> 0.1.4'
end

# Becomes in Gemfile.lock
remote: https://_MY_SECRET_FURY_TOKEN_@gem.fury.io/devpresence/

# CASE 2: DESIRED BEHAVIOR
# In Gemfile
source "https://#{ENV['FURY_AUTH']}@gem.fury.io/devpresence/" do
  gem 'presence_common_web', '~> 0.1.4'
end

# Becomes in Gemfile.lock
remote: https://gem.fury.io/devpresence/
```

We need this change to make it possible to use bundler in a safe and secure fashion with private gem sources.

It's not an option to just "not commit Gemfile.lock" as that precludes git deploys to Heroku etc.

Thanks!

**Comment by TimMoore** [comment]
@joelpresence the best solution to this is to use `bundle config` to store credentials, rather than an environment variable substituted into the Gemfile. See http://bundler.io/man/gemfile.5.html#CREDENTIALS-credentials- for details.

If you do want to use an environment variable for whatever reason, you can take advantage of the fact that Bundler can read any config setting from the environment http://bundler.io/man/bundle-config.1.html#CONFIGURATION-KEYS So, in your case, `BUNDLE_GEM__FURY__IO=<token>`

We went back and forth a couple of times on whether to strip credentials from URLs in the Gemfile, but it caused problems for some users, so we settled on these rules:

- Credentials set via `bundle config` (including via `BUNDLE_*` environment variables) will not be written to `Gemfile.lock`.
- Credentials set in the Gemfile directly _will_ be written to `Gemfile.lock` for backwards compatibility

If you want details, you can refer back to other issues where this has been discussed:

* #3150
* #3049
* #3118
* #3120
* #3137
* #3201

**Comment by joelpresence** [comment]
@TimMoore thanks for the response!

Will the `bundle config` work on Heroku?  If not, then it's not a viable solution for many people.

Also, can we not add an option to the gem file like:
```
# In Gemfile
write_credentials_to_lockfile: false
```
`write_credentials_to_lockfile` could default to `true`, so it would be totally backwards compatible.  Only those that need to specify it as `false` would do so.

I'd be happy to help with a patch.

Thanks!

**Comment by joelpresence** [comment]
And can't we say that anybody who was including credentials in a Gemfile in plaintext was doing things in an insecure manner that we shouldn't encourage?  I generally support backwards compatibility, but this seems like a big security risk in bundler to be honest.

And the tricky thing is that the current behavior violates the principle of least surprise: since I'm substituting in env vars to Gemfile and runtime, I'm not expecting them (especially credentials) to get copied into the Gemfile.lock.  The fact that it happens under the hood, without warning me, is not really a good thing.  It's a security risk and the credentials get propagated unexpectedly and without warning.

Thoughts?

Thanks again!

**Comment by joelpresence** [comment]
And using bundle config is not a secure solution because to deploy to Heroku, I need to put the private credentials in the bundle config file, and check it into source control so that it gets git pushed.  So we're right back where we started: private gem credentials checked into source control, which is a no-no.

Or does bundle config do ENV var substitution?

Thanks.  :-)

**Comment by TimMoore** [comment]
Yeah... I did mention above you can still use an environment variable:

> If you do want to use an environment variable with Heroku, you can take advantage of the fact that Bundler can read any config setting from the environment http://bundler.io/man/bundle-config.1.html#CONFIGURATION-KEYS So, in your case, `BUNDLE_GEM__FURY__IO=<token>`

I'm not too enthusiastic about adding a new option to the Gemfile for this, since we already have another solution.

I agree that including credentials in the Gemfile in plaintext is a bad practice, but for a long time it was the only approach available for authenticating to gem servers. In general, Bundler makes a strong guarantee for semantic versioning, so we can't break backward compatibility.

It sounds like a good idea to print a warning if there are credentials in the Gemfile (including ones that are interpolated). If you're willing to help with a patch for that, it would be greatly appreciated!

**Comment by TimMoore** [comment]
I just realized that the environment variable feature for credentials is only available from Bundler 1.8+, and Heroku is still using 1.7.x. I'm not sure if it's possible to update that yourself.

**Comment by joelpresence** [comment]
Please re-open this issue.  None of the suggested workarounds work on Heroku and this is a real security risk.

```
heroku run bundle --version
Running `bundle --version` attached to terminal... up, run.7571
Bundler version 1.7.12
```
😞

I just spent 1/2 hour trying to get this to work on Heroku and no matter what I try, I cannot get Heroku to use `BUNDLE_GEM__FURY__IO` when I have set it using `heroku config:set BUNDLE_GEM__FURY__IO=MyToken`.

This works locally on my MacbookPro.  It's just Heroku.

So any suggestions as to what I should do now?

As per https://devcenter.heroku.com/articles/ruby-support:
```
The following libraries are used by the platform for managing and running Ruby applications and cannot be specified.

    Bundler v1.7.13: Application dependency resolution and management.
```

I agree that we should support backwards compatibility.  But allowing private gem credentials to sneak into Gemfile.lock like this is a real and serious security risk.  We really need to figure out a workaround that will work for Heroku as well as those environments using newer versions of bundler.

I'm happy to create PR for my `write_credentials_to_lockfile: false` idea for Gemfile.  If you can point me in the write direction: which files to look at and what I need to worry about and test then I can work on it!

Otherwise, what can we do?  We just can't allow secure private credentials to be committed to source control and the fact that bundler sneaks them into Gemfile.lock means that even if we try to manually delete them each time, they will sneak in eventually.

Any ideas?  I'm happy to help however I can ...

Can we re-open this issue please?

Thanks!

**Comment by segiddins** [comment]
@joelpresence I don't see a need for you to make that PR, since heroku would need to update the default bundler version for you to be able to use it, at which time the ENV vars will work.

**Comment by joelpresence** [comment]
Yes, good point @segiddins, I was just about to write that myself.  Duhhh, sorry, I didn't think of that initially.  My bad.

This is a serious enough security risk that I think I should ask Heroku to make an update to their version of bundler.  What do people think?

Is there another way I can prevent bundler from sneaking in credentials into Gemfile.lock that will work with Heroku's version of bundler?

I guess I could try some kind of git pre-commit hook or similar to clean the credentials out of Gemfile.lock, but that seems brittle and would be a pain for other dev on my team to setup.  The credentials might get written to the ephemeral Gemfile.lock on Heroku during deploy, but they wouldn't be written to the local Gemfile.lock during development and that would at least prevent them from being committed to git.

Thoughts?

**Comment by TimMoore** [comment]
The best workaround I can think of until Heroku upgrades Bundler is to put a conditional into the `Gemfile`, like (untested code):

```ruby
gemfury_source =
  if Gem::Version.new(Bundler::VERSION) > Gem::Version.new('1.8.0')
    "https://gem.fury.io/devpresence/"
  else
    "https://#{ENV['FURY_AUTH']}@gem.fury.io/devpresence/"
  end
```

That should let you use Bundle config locally and the `FURY_AUTH` environment variable with Heroku.

The only thing I'm not sure about is whether that will cause the `bundle install --deployment` to fail on Heroku because the Gemfile.lock appears to be out of date. I _think_ the version on Heroku normalizes the URLs before comparing to see if the lock file is outdated.

**Comment by joelpresence** [comment]
Thanks for the suggestion @TimMoore .  I tried it and it didn't work on Heroku.  I have raised this as an ultra-urgent security issue with Heroku.  Do you think this merits a public vulnerability disclosure after some time if Heroku is unable to update bundler?  This is a legit security risk ...

Here's the Heroku output:
```
remote:        Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
remote:        You are trying to install in deployment mode after changing
remote:        your Gemfile. Run `bundle install` elsewhere and add the
remote:        updated Gemfile.lock to version control.
remote:        You have added to the Gemfile:
remote:        * presence_common_web (~> 0.1.5)
remote:        You have deleted from the Gemfile:
remote:        * presence_common_web (~> 0.1.4)
remote:        Bundler Output: You are trying to install in deployment mode after changing
remote:        your Gemfile. Run `bundle install` elsewhere and add the
remote:        updated Gemfile.lock to version control.
```

Thanks again for all of your suggestions and hard work on bundler - much appreciated!

**Comment by TimMoore** [comment]
If you're looking for a workaround, it seems from that error message that updating `presence_common_web`  could do the trick. I'm kind of surprised to see that message, actually, unless you did update the version in `Gemfile` but did not commit the updated `Gemfile.lock`.

**Comment by denmat** [comment]
Hmmm, I would say that this is a fundamentally bad security flaw in bundler.  I can just see the people being able to search github for the Gemfile.lock with username/passwords.

My problem is similar to @joelpresence. However I'm trying to build docker containers from private github repos. I was hoping to pass my token through as an environment var.

This is possible with `https://#ENV[<token>]:auth/account` but records that in the lockfile. Should there ever be a time where you include auth tokens in a lock file? This is one backwards compatibility issue I would be proud to break.

Okay, so what I have tried to do as a work around is add a

`bundle config https://github.com <token>:x-oauth-basic` and `bundle config github.com <creds>` prior to running the `bundle install` in the the container (and remove at the end). However this also does not work as I would have hoped:

```
web_1       | Fetching https://github.com/<removed>/<removed>.git
web_1       | fatal: could not read Username for 'https://github.com': No such device or address
web_1       | Retrying git clone 'https://github.com/<removed>/<removed>.git' "/marketplace/current/vendor/cache/ruby/2.2.0/cache/bundler/git/<removed>-34c75a6a08000eb03f1c668bb1dec4fbe264aaae" --bare --no-hardlinks --quiet due to error (2/4): Bundler::Source::Git::GitCommandError Git error: command `git clone 'https://github.com/<removed>/<removed>.git' "/marketplace/current/vendor/cache/ruby/2.2.0/cache/bundler/git/<removed>-34c75a6a08000eb03f1c668bb1dec4fbe264aaae" --bare --no-hardlinks --quiet` in directory /marketplace/current has failed.
```

Gemfile:
```
gem '<removed>',                      :git => 'https://github.com/<removed>/<removed>.git',
                                                  :branch => 'master',
```

Is there something wrong here? 

docs indicate that this should work:
> $ bundle config https://gems.example.com/ user:password

but maybe that is only for `source`?

**Comment by indirect** [comment]
@denmat support for git url credentials is in master, and will be included in the next version of Bundler.
