### ISSUE TITLE
dir_s_mkdir - /opt/metasploit-framework/.bundle

### ISSUE THREAD

**Issue by master2be1** [bundler/bundler#3613]
――― ERROR REPORT TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――
- What did you do?
- What did you expect to happen?
- What happened instead?

Error details

    Errno::EACCES: Permission denied @ dir_s_mkdir - /opt/metasploit-framework/.bundle
    /home/oheneba/.rbenv/versions/2.1.5/lib/ruby/2.1.0/fileutils.rb:250:in `mkdir'
    /home/oheneba/.rbenv/versions/2.1.5/lib/ruby/2.1.0/fileutils.rb:250:in `fu_mkdir'
    /home/oheneba/.rbenv/versions/2.1.5/lib/ruby/2.1.0/fileutils.rb:224:in `block (2 levels) in mkdir_p'
    /home/oheneba/.rbenv/versions/2.1.5/lib/ruby/2.1.0/fileutils.rb:222:in `reverse_each'
    /home/oheneba/.rbenv/versions/2.1.5/lib/ruby/2.1.0/fileutils.rb:222:in `block in mkdir_p'
    /home/oheneba/.rbenv/versions/2.1.5/lib/ruby/2.1.0/fileutils.rb:208:in `each'
    /home/oheneba/.rbenv/versions/2.1.5/lib/ruby/2.1.0/fileutils.rb:208:in `mkdir_p'
    /home/oheneba/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.9.5/lib/bundler/settings.rb:158:in `set_key'
    /home/oheneba/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.9.5/lib/bundler/settings.rb:26:in `[]='
    /home/oheneba/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.9.5/lib/bundler/cli/binstubs.rb:13:in `run'
    /home/oheneba/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.9.5/lib/bundler/cli.rb:209:in `binstubs'
    /home/oheneba/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.9.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
    /home/oheneba/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.9.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
    /home/oheneba/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.9.5/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
    /home/oheneba/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.9.5/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
    /home/oheneba/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.9.5/lib/bundler/cli.rb:10:in `start'
    /home/oheneba/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.9.5/bin/bundle:20:in `block in <top (required)>'
    /home/oheneba/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.9.5/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
    /home/oheneba/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.9.5/bin/bundle:18:in `<top (required)>'
    /home/oheneba/.rbenv/versions/2.1.5/bin/bundle:23:in `load'
    /home/oheneba/.rbenv/versions/2.1.5/bin/bundle:23:in `<main>'

Environment

    Bundler   1.9.5
    Rubygems  2.2.2
    Ruby      2.1.5p273 (2014-11-13 revision 48405) [x86_64-linux]
    GEM_HOME  /home/oheneba/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0
    GEM_PATH  /home/oheneba/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0:/home/oheneba/.gem/ruby/2.1.0
    Git       1.7.9.5

Bundler settings

    bin
      Set for your local app (/opt/metasploit-framework/.bundle/config): "/usr/local/bin"
――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

**Comment by indirect** [comment]
You should grant permission for your user to make changes to /opt/metasploit.

**Comment by master2be1** [comment]
Could you plaese guide me step by step?
I'm a novice

**Comment by indirect** [comment]
Sorry, this isn't a place for tech support, it's just for bugs in Bundler. This isn't a bug, this is you telling Bundler to install something where your computer won't let it. Maybe you can get help from the Metasploit team.

**Comment by master2be1** [comment]
Ok. tnx a lot. I appreciate your prompt response.
