### ISSUE TITLE
Unable to install dependencies (or run any rake task) on a fresh clone

### ISSUE THREAD

**Issue by aprescott** [bundler/bundler#3627]
I'm trying to get started with a PR and I seem to be unable to get `rake` to work properly, meaning I can't do `rake spec:deps`.

```shell
cd /tmp
git clone https://github.com/bundler/bundler.git && cd bundler
rake -T
```

```
rake aborted!
NoMethodError: undefined method `ext_lock' for #<Bundler::RubygemsIntegration::Future:0x007f9701a765a8>
/private/tmp/bundler/lib/bundler/shared_helpers.rb:58:in `pwd'
/Users/adamprescott/.gem/ruby/2.1.4/gems/bundler-1.7.4/lib/bundler/gem_helper.rb:27:in `initialize'
/Users/adamprescott/.gem/ruby/2.1.4/gems/bundler-1.7.4/lib/bundler/gem_helper.rb:13:in `new'
/Users/adamprescott/.gem/ruby/2.1.4/gems/bundler-1.7.4/lib/bundler/gem_helper.rb:13:in `install_tasks'
/Users/adamprescott/.gem/ruby/2.1.4/gems/bundler-1.7.4/lib/bundler/gem_tasks.rb:2:in `<top (required)>'
/private/tmp/bundler/Rakefile:312:in `<top (required)>'
/Users/adamprescott/.gem/ruby/2.1.4/bin/ruby_executable_hooks:15:in `eval'
/Users/adamprescott/.gem/ruby/2.1.4/bin/ruby_executable_hooks:15:in `<main>'
(See full trace by running task with --trace)
```

It comes out of `shared_helpers.rb`:

```ruby
def pwd
  Bundler.rubygems.ext_lock.synchronize do
    Dir.pwd
  end
end
```

What's interesting is that the error comes from `Bundler::RubygemsIntegration::Future:0x007f9701a765a8` (note: `Future`), but if I open a console with `lib/bundler` required, then I can call `ext_lock`:

```
$ irb -Ilib
>> require "bundler"
=> true
>> Bundler.rubygems.ext_lock
=> #<Monitor:0x007fa82113c510 @mon_owner=nil, @mon_count=0, @mon_mutex=#<Mutex:0x007fa82113c3f8>>
```

But the `Bundler.rubygems` object in this console is actually a `Bundler::RubygemsIntegration::MoreFuture`, not a `Future`.

Am I missing something obvious here?

**Comment by indirect** [comment]
It sounds like you're somehow mixing versions of Ruby and/or RubyGems. Maybe check the shebang for your `rake`?

**Comment by fotanus** [comment]
I just had to do this and got this error. I was using an older version of ruby. Use 2.2.2, I'm it should work.

**Comment by aprescott** [comment]
@fotanus that seems to be it. I was initially on 2.1.4, and I was using the `rubygems-bundler` gem. After I reset my shebangs with `gem pristine --all`, I still had the issue. Using 2.2.2 works, even with `rubygems-bundler`.

**Comment by aprescott** [comment]
Thanks so much!
