### ISSUE TITLE
without sudo or su?

### ISSUE THREAD

**Issue by u007** [bundler/bundler#3628]
Hi,

is there a way that we ask bundler to use another ssh account with sudo rights,
but run bundle install with another user?

example:
user1 owns the project,
but useradmin is the sudo user,

highly appreciate your tinker with this :)

**Comment by indirect** [comment]
Sure, SSH as `useradmin`, and then run `sudo su user1 -c bundle install`. You don’t need bundler to do this. :)

**Comment by u007** [comment]
it someone return 
```
bash: bundle: command not found
```
but if i change 'bundle install' to 'ls', it works

**Comment by indirect** [comment]
That means you need to fix your environment, but this is a tracker just for bugs in Bundler. If you find a bug in Bundler, please let us know! But we can’t help you with server setup problems.
