### ISSUE TITLE
Regression: `rake build` throws nil errors with bundler/gem_task from the top of the master branch

### ISSUE THREAD

**Issue by pjump** [bundler/bundler#3632]
Steps to reproduce:

##SETUP
bundle gem foo
cd $_
#Clean up FIXME's etc.
find . -type f -exec sed '/Put your gem/ d' -i {} \;
find . -type f -exec sed 's/TODO//g' -i {} \;
find . -type f -exec sed 's/FIXME//g' -i {} \;
## The thing
rake build
#on 1.9.4 ---works OK, delegates to the gem task from rubygems/package_task, and thus takes about 0.5 s 
#on 1.9.6 --- stopped delegating to the gem task from rubygems/pacakge_task and now takes about twice as long (an annoying lag if you ask me)
#on master --- still laggish and throws `a TypeError: no implicit conversion of nil into String`

**Comment by indirect** [comment]
![img_5916](https://cloud.githubusercontent.com/assets/78/7546909/9d4c5234-f5db-11e4-8a46-7ded783842a8.jpg)

Also, what?

```

$ bundle -v
Bundler version 1.9.6

$ bundle gem foo
Creating gem 'foo'...
      create  foo/Gemfile
      create  foo/.gitignore
      create  foo/lib/foo.rb
      create  foo/lib/foo/version.rb
      create  foo/foo.gemspec
      create  foo/Rakefile
      create  foo/README.md
      create  foo/bin/console
      create  foo/bin/setup
      create  foo/.travis.yml
      create  foo/.rspec
      create  foo/spec/spec_helper.rb
      create  foo/spec/foo_spec.rb
Initializing git repo in /Users/andre/src/bundler/testcases/3632/foo

$ cd foo

$ vim foo.gemspec 

$ time rake build
foo 0.1.0 built to pkg/foo-0.1.0.gem.

real    0m0.570s
user    0m0.515s
sys     0m0.046s
```

**Comment by pjump** [comment]
This bug report is about the master branch, not about 1.9.6.

**Comment by indirect** [comment]
> #on 1.9.6 --- stopped delegating to the gem task from rubygems/pacakge_task and now takes about twice as long (an annoying lag if you ask me)

Can't reproduce this, see above.

> #on master --- still laggish and throws a TypeError: no implicit conversion of nil into String

Can't reproduce this:

```
$ bundle -v
Bundler version 1.10.0.pre.2

$ time rake build
foo 0.1.0 built to pkg/foo-0.1.0.gem.

real    0m0.563s
user    0m0.509s
sys     0m0.045s
```

**Comment by pjump** [comment]
Apologies. You're right. That nil error was something I messed up by playing with it. Sorry.
