### ISSUE TITLE
Simple Gemfile causes "bundle update" to never finish

### ISSUE THREAD

**Issue by donv** [bundler/bundler#3634]
When running ```bundle update``` with the following Gemfile, the command never completes.  It runs with "Resolving dependencies" forever.  This happens on new installations using RVM for MRI and JRuby.

```ruby
source 'https://rubygems.org/'

gem 'rails', '<4.2.0'
gem 'actionpack-page_caching'
gem 'simple_workflow'
```

**Comment by segiddins** [comment]
@donv what version of bundler is this with?

**Comment by segiddins** [comment]
Hm, the issue here seems to be with a combo of `attempt_to_swap` and our sorting heuristic...

**Comment by segiddins** [comment]
@Who828 what do you think of using `dependency.requirements_list.size` as part of the sort?

**Comment by donv** [comment]
@segiddins  This is with bundler 1.9.6.

**Comment by donv** [comment]
I left it going for a while and with the simple Gemfile it actually finished in the end:

```
real	0m46.411s
user	1m10.831s
sys	0m1.680s
```

That is with all the gems already installed before running the command.

**Comment by segiddins** [comment]
Yup, I think I have an optimization in mind that may help this pathological case.
