### ISSUE TITLE
How can I add rake to Gemfile

### ISSUE THREAD

**Issue by gretchenista** [bundler/bundler#3640]
I am trying to create a database on active record. Literally thousands of times, I have either typed 'bundle exec rake db:create' or sudo bundle exec rake db:create'. I keep getting the same error message over and over:

♥ sudo bundle exec rake db:create
Password:
/Library/Ruby/Gems/2.0.0/gems/bundler-1.9.4/lib/bundler/rubygems_integration.rb:263:in `block in replace_gem': rake is not part of the bundle. Add it to Gemfile. (Gem::LoadError)
	from /usr/bin/rake:22:in `<main>'

How can I add rake to Gemfile so that I can create a database? 

By the way, here is my Gemfile as well as Gemfile.lock:
Gemfile

    source 'https://rubygems.org'
    
    gem 'activerecord'
    gem 'pg'
    
    gem 'rspec'
    gem 'faker'

Gemfile.lock

    GEM
      remote: https://rubygems.org/
      specs:
        activemodel (4.2.0)
          activesupport (= 4.2.0)
          builder (~> 3.1)
        activerecord (4.2.0)
          activemodel (= 4.2.0)
          activesupport (= 4.2.0)
          arel (~> 6.0)
        activesupport (4.2.0)
          i18n (~> 0.7)
          json (~> 1.7, >= 1.7.7)
          minitest (~> 5.1)
          thread_safe (~> 0.3, >= 0.3.4)
          tzinfo (~> 1.1)
        arel (6.0.0)
        builder (3.2.2)
        diff-lcs (1.2.5)
        faker (1.4.3)
          i18n (~> 0.5)
        i18n (0.7.0)
        json (1.8.2)
        minitest (5.5.1)
        pg (0.18.1)
        rspec (3.1.0)
          rspec-core (~> 3.1.0)
          rspec-expectations (~> 3.1.0)
          rspec-mocks (~> 3.1.0)
        rspec-core (3.1.7)
          rspec-support (~> 3.1.0)
        rspec-expectations (3.1.2)
          diff-lcs (>= 1.2.0, < 2.0)
          rspec-support (~> 3.1.0)
        rspec-mocks (3.1.3)
          rspec-support (~> 3.1.0)
        rspec-support (3.1.2)
        thread_safe (0.3.4)
        tzinfo (1.2.2)
          thread_safe (~> 0.1)
    
    PLATFORMS
      ruby
    
    DEPENDENCIES
      activerecord
      faker
      pg
      rspec

**Comment by segiddins** [comment]
Can you just add the line `gem "rake"` to your `Gemfile` and run `bundle install`?

**Comment by gretchenista** [comment]
I have tried adding 'gem "rake"' to Gemfile and then ran bundle install, but this message came up:

 bundle install
Undefined local variable or method `‘rake’' for Gemfile
        from /Users/gretchen/ruby_challenges/sinatra/activerecord-template/Gemfile:9

**Comment by segiddins** [comment]
that looks like you're using Unicode quotes instead of straight quotes

**Comment by gretchenista** [comment]
I feel stupid, but what is the difference between Unicode and straight quotes?

**Comment by segiddins** [comment]
`‘` are the quotes you pasted, but in ruby, to get strings, you must use`'`.

**Comment by indirect** [comment]
Technically, all quotes are Unicode quotes. I think what @segiddins meant was that your error contains "smart" quotes. Unfortunately, there are many different characters that all look like quotation marks, and Ruby only understands the characters ' and ", but not the curly/smart quotes that show up in your error message.

You can probably fix this by deleting the rake line from your Gemfile and typing it in again yourself, in a plaintext editor. (Editors like Word or TextEdit might automatically convert plain quotes into smart quotes, recreating the problem.)

**Comment by gretchenista** [comment]
I had 'rake' in Unicode but all the others in straight, so I had to copy and paste the straight quotes to go around rake. Even when adding to Gemfile, I am still getting the same error message as the original post over and over.  How can I get past load error?

**Comment by indirect** [comment]
@gretchenista please paste you new Gemfile, and copy and paste the exact command you are running, and the exact message you are getting.

**Comment by gretchenista** [comment]
Gemfile:
source 'https://rubygems.org'

gem 'activerecord'
gem 'pg'

gem 'rspec'
gem 'faker'

gem 'rake'

Gemfile.lock:
GEM
  remote: https://rubygems.org/
  specs:
    activemodel (4.2.0)
      activesupport (= 4.2.0)
      builder (~> 3.1)
    activerecord (4.2.0)
      activemodel (= 4.2.0)
      activesupport (= 4.2.0)
      arel (~> 6.0)
    activesupport (4.2.0)
      i18n (~> 0.7)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.3, >= 0.3.4)
      tzinfo (~> 1.1)
    arel (6.0.0)
    builder (3.2.2)
    diff-lcs (1.2.5)
    faker (1.4.3)
      i18n (~> 0.5)
    i18n (0.7.0)
    json (1.8.2)
    minitest (5.5.1)
    pg (0.18.1)
    rspec (3.1.0)
      rspec-core (~> 3.1.0)
      rspec-expectations (~> 3.1.0)
      rspec-mocks (~> 3.1.0)
    rspec-core (3.1.7)
      rspec-support (~> 3.1.0)
    rspec-expectations (3.1.2)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.1.0)
    rspec-mocks (3.1.3)
      rspec-support (~> 3.1.0)
    rspec-support (3.1.2)
    thread_safe (0.3.4)
    tzinfo (1.2.2)
      thread_safe (~> 0.1)

PLATFORMS
  ruby

DEPENDENCIES
  activerecord
  faker
  pg
  rspec
rake 

Command and error message:
♥ bundle exec rake db:create
/Library/Ruby/Gems/2.0.0/gems/bundler-1.9.4/lib/bundler/rubygems_integration.rb:263:in `block in replace_gem': rake is not part of the bundle. Add it to Gemfile. (Gem::LoadError)
	from /usr/bin/rake:22:in `<main>'

**Comment by indirect** [comment]
Wow, I um... I really don't know. That normally works. Can you run `bundle install` and paste the output? How about running `bundle exec rake -T`? Also, could you show the output from running `head $(which bundler)` and `head $(which rake`)?

**Comment by gretchenista** [comment]
Thank you, Andre. I tried bundle exec rake -T, but I kept getting the same error message:
 
bundle exec rake -T

/Library/Ruby/Gems/2.0.0/gems/bundler-1.9.4/lib/bundler/rubygems_integration.rb:263:in `block in replace_gem': rake is not part of the bundle. Add it to Gemfile. (Gem::LoadError)
	from /usr/bin/rake:22:in `<main>'

My computer is a MacBook Air, so sometimes, I have to use sudo to make the commands work.

**Comment by segiddins** [comment]
@indirect might it matter that `rake` is not in the list of specs?

**Comment by indirect** [comment]
@segiddins yup, pretty sure that's it. :(

@gretchenista I listed four commands. Please run all four, and show the output from each one.

**Comment by gretchenista** [comment]
Bundler is:
/usr/bin/bundler

Rake is:
/usr/bin/rake

**Comment by indirect** [comment]
@gretchenista I need you to run these four commands, exactly, and copy and paste all of the text from the terminal, including where you typed the command, and what was printed out after you ran the command:

1. `bundle install`
2. `head $(which bundle)`
3. `head $(which rake)`
4. `bundle exec rake -T`

I put all four of those in my message above, but so far you've only run one of them.

**Comment by gretchenista** [comment]
♥ bundle install
Using i18n 0.7.0
Using json 1.8.2
Using minitest 5.5.1
Using thread_safe 0.3.4
Using tzinfo 1.2.2
Using activesupport 4.2.0
Using builder 3.2.2
Using activemodel 4.2.0
Using arel 6.0.0
Using activerecord 4.2.0
Using diff-lcs 1.2.5
Using faker 1.4.3
Using pg 0.18.1
Using rspec-support 3.1.2
Using rspec-core 3.1.7
Using rspec-expectations 3.1.2
Using rspec-mocks 3.1.3
Using rspec 3.1.0
Using bundler 1.9.4
Bundle complete! 5 Gemfile dependencies, 19 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.

**Comment by gretchenista** [comment]
♥ head $(which bundle)
#!/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
#
# This file was generated by RubyGems.
#
# The application 'bundler' is installed as part of a gem, and
# this file is here to facilitate running it.
#

require 'rubygems'

**Comment by gretchenista** [comment]
♥ head $(which rake)
#!/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
#
# This file was generated by RubyGems.
#
# The application 'rake' is installed as part of a gem, and
# this file is here to facilitate running it.
#

require 'rubygems'

**Comment by gretchenista** [comment]
♥ bundle exec rake -T
/Library/Ruby/Gems/2.0.0/gems/bundler-1.9.4/lib/bundler/rubygems_integration.rb:263:in `block in replace_gem': rake is not part of the bundle. Add it to Gemfile. (Gem::LoadError)
	from /usr/bin/rake:22:in `<main>'

Thank you, Andre, but I think I have exhausted everything. It looks like my MacBook is hopeless in creating active record databases.

**Comment by indirect** [comment]
Okay, I think I see the problem. Try running these commands exactly:

```
rm Gemfile.lock
rm Gemfile
echo "source 'https://rubygems.org'" >> Gemfile
echo "gem 'rake'" >> Gemfile
echo "gem 'activerecord'" >> Gemfile
echo "gem 'pg'" >> Gemfile
bundle install
bundle exec rake -T
```

Please paste the entire output of running each command and all the text printed when you run them. (You can do it in one message, and I suggest putting `\`\`\`` on a line before and after, so that it will look like the text above.)

**Comment by gretchenista** [comment]
Thank you, Andre, but I am still not getting through. My MacBook still refuses to download rake.
♥ rm Gemfile.lock
gretchen: activerecord-template
♥ rm Gemfile
gretchen: activerecord-template
♥ echo "source 'https://rubygems.org'" >> Gemfile
gretchen: activerecord-template
♥ echo "gem 'rake'" >> Gemfile
gretchen: activerecord-template
♥ echo "gem 'activerecord'" >> Gemfile
gretchen: activerecord-template
♥ echo "gem 'pg'" >> Gemfile
gretchen: activerecord-template
♥ bundle install
Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/..
Resolving dependencies...
Using rake 10.4.2
Using i18n 0.7.0
Using json 1.8.2
Using minitest 5.6.1
Using thread_safe 0.3.5
Using tzinfo 1.2.2
Using activesupport 4.2.1
Using builder 3.2.2
Using activemodel 4.2.1
Using arel 6.0.0
Using activerecord 4.2.1
Using pg 0.18.1
Using bundler 1.9.4
Bundle complete! 3 Gemfile dependencies, 13 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
gretchen: activerecord-template
♥ bundle exec rake -T
rake aborted!
LoadError: cannot load such file -- rspec/core/rake_task
/Users/gretchen/ruby_challenges/sinatra/activerecord-template/Rakefile:2:in `require'
/Users/gretchen/ruby_challenges/sinatra/activerecord-template/Rakefile:2:in `<top (required)>'
(See full trace by running task with --trace)
gretchen: activerecord-template
♥

**Comment by indirect** [comment]
Aha! That fixed it. Now run these commands:

```
echo "gem 'rspec'" >> Gemfile
echo "gem 'faker'" >> Gemfile
bundle install
bundle exec rake -T
```

**Comment by gretchenista** [comment]
Finally, no error message! Thank you, Andre! You are awesome!
♥ echo "gem 'rspec'" >> Gemfile
gretchen: activerecord-template
♥ echo "gem 'faker'" >> Gemfile
gretchen: activerecord-template
♥ bundle install
Resolving dependencies...
Using rake 10.4.2
Using i18n 0.7.0
Using json 1.8.2
Using minitest 5.6.1
Using thread_safe 0.3.5
Using tzinfo 1.2.2
Using activesupport 4.2.1
Using builder 3.2.2
Using activemodel 4.2.1
Using arel 6.0.0
Using activerecord 4.2.1
Using diff-lcs 1.2.5
Using faker 1.4.3
Using pg 0.18.1
Using rspec-support 3.2.2
Using rspec-core 3.2.2
Using rspec-expectations 3.2.0
Using rspec-mocks 3.2.1
Using rspec 3.2.0
Using bundler 1.9.4
Bundle complete! 5 Gemfile dependencies, 20 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
gretchen: activerecord-template
♥ bundle exec rake -T
rake console             # Start IRB with application environment loaded
rake db:create           # Create activerecord-template databases
rake db:drop             # Drop activerecord-template databases
rake db:migrate          # Migrate the database
rake db:reset            # Drop, create, and migrate the database
rake db:seed             # Populate the database with sample data
rake generate:migration  # Create a database migration
rake spec                # Run the specs
gretchen: activerecord-template
♥

**Comment by gretchenista** [comment]
Hooray for Andre! He saved the day!

**Comment by mollyabbott** [comment]
Thank you! This worked for me too!

**Comment by maplion** [comment]
This is awesome and it worked for me too, thank you!

For my edification, however, I would appreciate if someone could explain (in detail) what is going on here and why this fixes it.

**Comment by indirect** [comment]
@maplion somehow, while the `Gemfile` had smart quotes in it, Bundler created an invalid `Gemfile.lock` file that did not contain `rake`. The solution was to delete `Gemfile.lock` and re-create it by running `bundle install`.

**Comment by maplion** [comment]
@indirect   I see, thank you Andre.

**Comment by paulettee** [comment]
Andre, I tried the steps above but I keep get this error.

Could not find rake-12.0.0 in any of the sources (Bundler::GemNotFound)
  /root/.rvm/gems/ruby-2.4.0/gems/bundler-1.15.4/lib/bundler/spec_set.rb:87:in `block in materialize'
  /root/.rvm/gems/ruby-2.4.0/gems/bundler-1.15.4/lib/bundler/spec_set.rb:81:in `map!'
  /root/.rvm/gems/ruby-2.4.0/gems/bundler-1.15.4/lib/bundler/spec_set.rb:81:in `materialize'
  /root/.rvm/gems/ruby-2.4.0/gems/bundler-1.15.4/lib/bundler/definition.rb:159:in `specs'
  /root/.rvm/gems/ruby-2.4.0/gems/bundler-1.15.4/lib/bundler/definition.rb:218:in `specs_for'
  /root/.rvm/gems/ruby-2.4.0/gems/bundler-1.15.4/lib/bundler/definition.rb:207:in `requested_specs'
  /root/.rvm/gems/ruby-2.4.0/gems/bundler-1.15.4/lib/bundler/runtime.rb:109:in `block in definition_method'
  /root/.rvm/gems/ruby-2.4.0/gems/bundler-1.15.4/lib/bundler/runtime.rb:21:in `setup'
  /root/.rvm/gems/ruby-2.4.0/gems/bundler-1.15.4/lib/bundler.rb:101:in `setup'
  /root/.rvm/gems/ruby-2.4.0/gems/bundler-1.15.4/lib/bundler/setup.rb:19:in `<top (required)>'
  /usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  /usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  /usr/share/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:430:in `activate_gem'
  /usr/share/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:297:in `block in run_load_path_setup_code'
  /usr/share/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:435:in `running_bundler'
  /usr/share/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:296:in `run_load_path_setup_code'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:100:in `preload_app'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:156:in `<module:App>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:29:in `<main>'
