### ISSUE TITLE
bundle install fails on json-1.8.2

### ISSUE THREAD

**Issue by geeth4sg** [bundler/bundler#3650]
I've tried to host my ruby apps, we've built native gems on private ftp and it is called on Gemfile. json is not installed on bundle install, but it could install by bundler package. We need to install all the gems in app path .bundle/package by bundle install. please refer the outputs.. 

```
httpd@system:~/application/snapshot-20150514155610686$ bundle install --path .bundle/package --without development test
Fetching gem metadata from http://rubygems.org/............
Fetching gem metadata from https://rep.fury
Resolving dependencies...
Using rake 10.4.2
Using i18n 0.7.0

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /pkg/ruby-lang.org/ruby/2.1.2/bin/ruby -r ./siteconf20150515-3887-11c0u01.rb extconf.rb 
creating Makefile

make "DESTDIR=" clean
sh: make: command not found

make "DESTDIR="
sh: make: command not found

make failed, exit code 127

Gem files will remain installed in/application/archives/snapshot-20150514155610686/.bundle/package/ruby/2.1.0/gems/json-1.8.2 for inspection.
Results logged to /application/archives/snapshot-20150514155610686/.bundle/package/ruby/2.1.0/extensions/x86_64-linux/2.1.0/json-1.8.2/gem_make.out
An error occurred while installing json (1.8.2), and Bundler cannot continue.
Make sure that `gem install json -v '1.8.2'` succeeds before bundling.
```
```
httpd@system:~/application/snapshot-20150514155610686$ bundler package
Warning: this Gemfile contains multiple primary sources. Using `source` more than once without a block is a security risk, and may result in installing unexpected gems. To resolve this warning, use a block to indicate which gems should come from the secondary source. To upgrade this warning to an error, run `bundle config disable_multisource true`.
Your Gemfile contains path and git dependencies. If you want to package them as well, please pass the --all flag. This will be the default on Bundler 2.0.
Fetching gem metadata from http://rubygems.org/............
Fetching gem metadata from https://rep.fury
Fetching version metadata from http://rubygems.org/..
Fetching version metadata from https://rep.fury
Resolving dependencies....
Installing rake 10.3.2
Installing i18n 0.7.0
Installing json 1.8.2
Installing minitest 5.5.1
```

**Comment by TimMoore** [comment]
@geeth4sg please follow the troubleshooting steps in https://github.com/bundler/bundler/blob/master/ISSUES.md, and if that doesn't solve your problem, reply back here with all of the information requested in the "Reporting unresolved problems" section of that guide.

**Comment by geeth4sg** [comment]
thanks for the reply@TimMoore.. I am new to this.. Can we install both for an app?

**Comment by TimMoore** [comment]
Yes, `bundle package` fetches the gems and caches them locally in `vendor/cache`. If you have a `vendor/cache` directory, then running `bundle install` again will try to install the cached gems from there if they are up to date, and will update them if they aren't.

You can read about it at http://bundler.io/bundle_package.html

**Comment by geeth4sg** [comment]
ok. thanks for the explanation. but we are trying only bundle install with custom path "bundle install --path .bundle/package --without development test" .. do you have idea why json is not installed @TimMoore ..

**Comment by TimMoore** [comment]
@geeth4sg please do follow the instructions in the https://github.com/bundler/bundler/blob/master/ISSUES.md document. We on the Bundler team need the information we ask for there before we can help.

**Comment by rgb-one** [comment]
I have come acrossi this. It is a simple solution. Install the `make` utility on you machine. Install `gcc` as well.

**Comment by kovalevvitaliy** [comment]
apt-get install make g++ gcc libssl-dev
