### ISSUE TITLE
Bundler Error - Errno::EACCES: Permission denied

### ISSUE THREAD

**Issue by andvikram** [bundler/bundler#3652]
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `/home/----/.rvm/gems/ruby-1.9.3-p551@----/bin/bundle install --deployment --without production test development`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what actually happened was...

Error details

    Errno::EACCES: Permission denied - /home/-----/#####/-----/vendor/bundle/ruby/1.9.1/cache/bundler
      /home/-----/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/fileutils.rb:247:in `mkdir'
      /home/-----/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/fileutils.rb:247:in `fu_mkdir'
      /home/-----/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/fileutils.rb:221:in `block (2 levels) in mkdir_p'
      /home/-----/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/fileutils.rb:219:in `reverse_each'
      /home/-----/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/fileutils.rb:219:in `block in mkdir_p'
      /home/-----/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/fileutils.rb:205:in `each'
      /home/-----/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/fileutils.rb:205:in `mkdir_p'
      /home/-----/.rvm/gems/ruby-1.9.3-p551@-----/gems/bundler-1.9.8/lib/bundler/source/git/git_proxy.rb:76:in `checkout'
      /home/-----/.rvm/gems/ruby-1.9.3-p551@-----/gems/bundler-1.9.8/lib/bundler/source/git.rb:153:in `specs'
      /home/-----/.rvm/gems/ruby-1.9.3-p551@-----/gems/bundler-1.9.8/lib/bundler/lazy_specification.rb:53:in `__materialize__'
      /home/-----/.rvm/gems/ruby-1.9.3-p551@-----/gems/bundler-1.9.8/lib/bundler/spec_set.rb:88:in `block in materialize'
      /home/-----/.rvm/gems/ruby-1.9.3-p551@-----/gems/bundler-1.9.8/lib/bundler/spec_set.rb:85:in `map!'
      /home/-----/.rvm/gems/ruby-1.9.3-p551@-----/gems/bundler-1.9.8/lib/bundler/spec_set.rb:85:in `materialize'
      /home/-----/.rvm/gems/ruby-1.9.3-p551@-----/gems/bundler-1.9.8/lib/bundler/definition.rb:132:in `specs'
      /home/-----/.rvm/gems/ruby-1.9.3-p551@-----/gems/bundler-1.9.8/lib/bundler/definition.rb:121:in `resolve_remotely!'
      /home/--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `/home/----/.rvm/gems/ruby-1.9.3-p551@----/bin/bundle install --deployment --without production test development`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what actually happened was...

Error details

    Errno::EACCES: Permission denied - /home/-----/#####/-----/vendor/bundle/ruby/1.9.1/cache/bundler
      /home/-----/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/fileutils.rb:247:in `mkdir'
      /home/-----/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/fileutils.rb:247:in `fu_mkdir'
      /home/-----/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/fileutils.rb:221:in `block (2 levels) in mkdir_p'
      /home/-----/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/fileutils.rb:219:in `reverse_each'
      /home/-----/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/fileutils.rb:219:in `block in mkdir_p'
      /home/-----/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/fileutils.rb:205:in `each'
      /home/-----/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/fileutils.rb:205:in `mkdir_p'
      /home/-----/.rvm/gems/ruby-1.9.3-p551@-----/gems/bundler-1.9.8/lib/bundler/source/git/git_proxy.rb:76:in `checkout'
      /home/-----/.rvm/gems/ruby-1.9.3-p551@-----/gems/bundler-1.9.8/lib/bundler/source/git.rb:153:in `specs'
      /home/-----/.rvm/gems/ruby-1.9.3-p551@-----/gems/bundler-1.9.8/lib/bundler/lazy_specification.rb:53:in `__materialize__'
      /home/-----/.rvm/gems/ruby-1.9.3-p551@-----/gems/bundler-1.9.8/lib/bundler/spec_set.rb:88:in `block in materialize'
      /home/-----/.rvm/gems/ruby-1.9.3-p551@-----/gems/bundler-1.9.8/lib/bundler/spec_set.rb:85:in `map!'
      /home/-----/.rvm/gems/ruby-1.9.3-p551@-----/gems/bundler-1.9.8/lib/bundler/spec_set.rb:85:in `materialize'
      /home/-----/.rvm/gems/ruby-1.9.3-p551@-----/gems/bundler-1.9.8/lib/bundler/definition.rb:132:in `specs'
      /home/-----/.rvm/gems/ruby-1.9.3-p551@-----/gems/bundler-1.9.8/lib/bundler/definition.rb:121:in `resolve_remotely!'
      /home/-----/.rvm/gems/ruby-1.9.3-p551@-----/gems/bundler-1.9.8/lib/bundler/installer.rb:79:in `run'
      /home/-----/.rvm/gems/ruby-1.9.3-p551@-----/gems/bundler-1.9.8/lib/bundler/installer.rb:18:in `install'
      /home/-----/.rvm/gems/ruby-1.9.3-p551@-----/gems/bundler-1.9.8/lib/bundler/cli/install.rb:80:in `run'
      /home/-----/.rvm/gems/ruby-1.9.3-p551@-----/gems/bundler-1.9.8/lib/bundler/cli.rb:155:in `install'
      /home/-----/.rvm/gems/ruby-1.9.3-p551@-----/gems/bundler-1.9.8/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /home/-----/.rvm/gems/ruby-1.9.3-p551@-----/gems/bundler-1.9.8/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /home/-----/.rvm/gems/ruby-1.9.3-p551@-----/gems/bundler-1.9.8/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /home/-----/.rvm/gems/ruby-1.9.3-p551@-----/gems/bundler-1.9.8/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /home/-----/.rvm/gems/ruby-1.9.3-p551@-----/gems/bundler-1.9.8/lib/bundler/cli.rb:10:in `start'
      /home/-----/.rvm/gems/ruby-1.9.3-p551@-----/gems/bundler-1.9.8/bin/bundle:20:in `block in <top (required)>'
      /home/-----/.rvm/gems/ruby-1.9.3-p551@-----/gems/bundler-1.9.8/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
      /home/-----/.rvm/gems/ruby-1.9.3-p551@-----/gems/bundler-1.9.8/bin/bundle:18:in `<top (required)>'
      /home/-----/.rvm/gems/ruby-1.9.3-p551@-----/bin/bundle:23:in `load'
      /home/-----/.rvm/gems/ruby-1.9.3-p551@-----/bin/bundle:23:in `<main>'
      /home/-----/.rvm/gems/ruby-1.9.3-p551@-----/bin/ruby_executable_hooks:15:in `eval'
      /home/-----/.rvm/gems/ruby-1.9.3-p551@-----/bin/ruby_executable_hooks:15:in `<main>'

Environment

    Bundler   1.9.8
    Rubygems  2.4.3
    Ruby      1.9.3p551 (2014-11-13 revision 48407) [x86_64-linux]
    GEM_HOME  /home/-----/#####/-----/vendor/bundle/ruby/1.9.1
    GEM_PATH  
    RVM       1.26.8 (latest)
    Git       1.9.1

Bundler settings

    frozen
      Set for your local app (/home/-----/#####/-----/.bundle/config): "1"
    path
      Set for your local app (/home/-----/#####/-----/.bundle/config): "vendor/bundle"
    without
      Set for your local app (/home/-----/#####/-----/.bundle/config): "production:test:development"
    disable_shared_gems
      Set for your local app (/home/-----/#####/-----/.bundle/config): "1"
--- TEMPLATE END ----------------------------------------------------------------

**Comment by rgb-one** [comment]
Is `rvm

**Comment by al2o3cr** [comment]
@andvikram Are you running an antivirus package? IIRC, there was a weird race condition in the Rails 2.3 gem installer where the AV would make a newly-created empty directory unreadable for a handful of milliseconds while it "scanned".

**Comment by supertopher** [comment]
rvm expects that you own the directories where your gems are installed in OSX.  you may find some success by taking ownership back of your entire rvm directory with something like

``` chown -R $USER $HOME/.rvm/ ```
