### ISSUE TITLE
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

### ISSUE THREAD

**Issue by endangurura** [bundler/bundler#3653]
Error details:

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /usr/bin/ruby22 -r ./siteconf20150516-14301-1j6lmf2.rb extconf.rb
checking for rb_trap_immediate in ruby.h,rubysig.h... no
checking for rb_thread_blocking_region()... no
checking for inotify_init() in sys/inotify.h... yes
checking for writev() in sys/uio.h... yes
checking for rb_thread_check_ints()... yes
checking for rb_time_new()... yes
checking for sys/event.h... no
checking for epoll_create() in sys/epoll.h... yes
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling kb.cpp
kb.cpp: In member function ‘virtual void KeyboardDescriptor::Read()’:
kb.cpp:77:27: warning: ignoring return value of ‘ssize_t read(int, void*, size_t)’, declared with attribute warn_unused_result [-Wunused-result]
  read (GetSocket(), &c, 1);
                           ^
compiling cmain.cpp
compiling pipe.cpp
compiling em.cpp
em.cpp: In member function ‘bool EventMachine_t::_RunEpollOnce()’:
em.cpp:525:65: error: ‘rb_thread_select’ was not declared in this scope
  if ((ret = rb_thread_select(epfd + 1, &fdreads, NULL, NULL, &tv)) < 1) {
                                                                 ^
em.cpp:566:37: error: ‘rb_thread_select’ was not declared in this scope
   EmSelect (0, NULL, NULL, NULL, &tv);
                                     ^
em.cpp: In member function ‘int SelectData_t::_Select()’:
em.cpp:812:67: error: ‘rb_thread_select’ was not declared in this scope
  return EmSelect (maxsocket+1, &fdreads, &fdwrites, &fderrors, &tv);
                                                                   ^
em.cpp: In member function ‘bool EventMachine_t::_RunSelectOnce()’:
em.cpp:951:40: error: ‘rb_thread_select’ was not declared in this scope
      EmSelect (0, NULL, NULL, NULL, &tv);
                                        ^
em.cpp: In member function ‘void EventMachine_t::SignalLoopBreaker()’:
em.cpp:282:34: warning: ignoring return value of ‘ssize_t write(int, const void*, size_t)’, declared with attribute warn_unused_result [-Wunused-result]
  write (LoopBreakerWriter, "", 1);
                                  ^
em.cpp: In member function ‘void EventMachine_t::_ReadLoopBreaker()’:
em.cpp:998:50: warning: ignoring return value of ‘ssize_t read(int, void*, size_t)’, declared with attribute warn_unused_result [-Wunused-result]
  read (LoopBreakerReader, buffer, sizeof(buffer));
                                                  ^
Makefile:229: recipe for target 'em.o' failed
make: *** [em.o] Error 1

make failed, exit code 2

Gem files will remain installed in /home/spock/.gem/ruby/2.2.0/gems/eventmachine-1.0.0.beta.3 for inspection.
Results logged to /home/spock/.gem/ruby/2.2.0/extensions/x86_64-linux/2.2.0/eventmachine-1.0.0.beta.3/gem_make.out
An error occurred while installing eventmachine (1.0.0.beta.3), and Bundler
cannot continue.
Make sure that `gem install eventmachine -v '1.0.0.beta.3'` succeeds before
bundling.

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /usr/bin/ruby22 -r ./siteconf20150516-14437-1vj9bxd.rb extconf.rb
checking for sqlite3.h... yes
checking for sqlite3_libversion_number() in -lsqlite3... yes
checking for rb_proc_arity()... yes
checking for sqlite3_initialize()... yes
checking for sqlite3_backup_init()... yes
checking for sqlite3_column_database_name()... yes
checking for sqlite3_enable_load_extension()... yes
checking for sqlite3_load_extension()... yes
checking for sqlite3_open_v2()... yes
checking for sqlite3_prepare_v2()... yes
checking for sqlite3_int64 in sqlite3.h... yes
checking for sqlite3_uint64 in sqlite3.h... yes
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling backup.c
compiling sqlite3.c
compiling database.c
compiling exception.c
compiling statement.c
In file included from statement.c:1:0:
statement.c: In function ‘bind_param’:
./sqlite3_ruby.h:16:34: error: invalid type argument of ‘->’ (have ‘int’)
 #define RBIGNUM_LEN(x) RBIGNUM(x)->len
                                  ^
statement.c:261:11: note: in expansion of macro ‘RBIGNUM_LEN’
       if (RBIGNUM_LEN(value) * SIZEOF_BDIGITS <= 8) {
           ^
statement.c:261:32: error: ‘SIZEOF_BDIGITS’ undeclared (first use in this function)
       if (RBIGNUM_LEN(value) * SIZEOF_BDIGITS <= 8) {
                                ^
statement.c:261:32: note: each undeclared identifier is reported only once for each function it appears in
Makefile:237: recipe for target 'statement.o' failed
make: *** [statement.o] Error 1

make failed, exit code 2

Gem files will remain installed in /home/spock/.gem/ruby/2.2.0/gems/sqlite3-1.3.8 for inspection.
Results logged to /home/spock/.gem/ruby/2.2.0/extensions/x86_64-linux/2.2.0/sqlite3-1.3.8/gem_make.out
An error occurred while installing sqlite3 (1.3.8), and Bundler cannot continue.
Make sure that `gem install sqlite3 -v '1.3.8'` succeeds before bundling.

**Comment by endangurura** [comment]
/usr/bin/ruby22 -r ./siteconf20150516-14053-1k72is4.rb extconf.rb
checking for sqlite3.h... yes
checking for sqlite3_libversion_number() in -lsqlite3... yes
checking for rb_proc_arity()... yes
checking for sqlite3_initialize()... yes
checking for sqlite3_backup_init()... yes
checking for sqlite3_column_database_name()... yes
checking for sqlite3_enable_load_extension()... yes
checking for sqlite3_load_extension()... yes
checking for sqlite3_open_v2()... yes
checking for sqlite3_prepare_v2()... yes
checking for sqlite3_int64 in sqlite3.h... yes
checking for sqlite3_uint64 in sqlite3.h... yes
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling backup.c
compiling sqlite3.c
compiling database.c
compiling exception.c
compiling statement.c
<ns/x86_64-linux/2.2.0/sqlite3-1.3.8/gem_make.out" 39L, 1529C 1,1           Top

**Comment by TimMoore** [comment]
Did you try to make sure that `gem install sqlite3 -v '1.3.8'` succeeds as it says? This looks like a problem compiling these gems on your system, and not anything having to do with Bundler specifically.

**Comment by rgb-one** [comment]
For building `eventmachine` ensure you have these dependencies installed:

* OpenSSL
* libstd++ (some systems, such as debian, may require an explicit install in order for the compiler to support this)
* Ruby
* Rake

For the `sqlite3` gem:
* Ensure you have `sqlite3` installed (this is a different package. The `sqlite3` gem is an interface to sqlite3)

Ensure these are installed and try again.

**Comment by endangurura** [comment]
Solved!
It was a problem of compiling these gems... 
It was the event machine eventmachine -v '1.0.0.beta.3' which doesn't compile on ruby 2.2.0.
bundle update eventmachine  and installing the latest eventmachine -v 1.0.7 solved it. 
It had nothing to do with bundler.
Thanks.
