### ISSUE TITLE
Warn if RUBYGEMS_GEMDEPS is set

### ISSUE THREAD

**Issue by segiddins** [bundler/bundler#3656]
Should we do this so there's less confusion when rubygems and bundler clash?

**Comment by indirect** [comment]
How do they clash? And yes, that seems likely :/

**Comment by segiddins** [comment]
If rubygems in any resolves things differently than bundler, we might not be able to setup our environment correctly. Haven't we also had issues with things like `rubygems-bundler` in the past?

**Comment by indirect** [comment]
I have no idea what happens if you set `RUBYGEMS_GEMDEPS` and also use Bundler. I guess we should check?

As for `rubygems-bundler`, that was broken because of trying to automatically `bundle exec` not because of `RUBYGEMS_GEMDEPS`. But yes, definitely issues.

**Comment by agis-** [comment]
Does a warning on every CLI command along the lines of "`RUBYGEMS_GEMDEPS` is set and this may cause bundler to conflict with rubygems" sounds sufficient?

**Comment by segiddins** [comment]
@agis- yeah

**Comment by ioquatix** [comment]
Is this still relevant? It's nice that I don't have to use `bundle exec` everywhere. With bundler and rubygems merging, can we find some consensus on this?
