### ISSUE TITLE
Revisit default Rakefile for `bundle gem --ext`

### ISSUE THREAD

**Issue by andremedeiros** [bundler/bundler#3665]
After revisiting `bundle gem --ext <your_gem_name>`, I found that the default Rakefile isn't as convenient as it should be.

As a default task, we get a test runner, but with C extensions, we should consider something along the lines of this:

```ruby
require "bundler/gem_tasks"
require "rake/testtask"

Rake::TestTask.new(:test) do |t|
  t.libs << "test"
end

require "rake/extensiontask"

Rake::ExtensionTask.new("journalist") do |ext|
  ext.lib_dir = "lib/journalist"
end

task :default => [:clobber, :compile, :test]
```

I'd like to hear some thoughts about this (especially the opposing kind) before applying the change.

**Comment by simi** [comment]
@andremedeiros I'm using

```ruby
task :default => [:clean, :compile, :test]
```

**Comment by andremedeiros** [comment]
I wonder what the difference is between `clean` and `clobber`...

Already looks a lot more useful than the currently generated one.

**Comment by simi** [comment]
If I understand this well `clobber` removes all files in `CLEAN` and `CLOBBER`, but `clean` removes only files in `CLEAN`.

This means for example that compiled extension (for example *.so file) will not be removed before compilation. I'm using this to keep latest successfully compiled extension for additional testing when compilation fails. But maybe `clobber` will be better default.

**Comment by andremedeiros** [comment]
Cool. Thanks for the feedback, @simi.

I'll leave this issue open for another couple of days, and if nobody opposes, I'll go ahead and change it. 

@indirect can we make sure that we don't release 1.10 before we make a decision on this.

**Comment by indirect** [comment]
@andremedeiros yeah, I'm only getting the RC out today, so you have at least a week to finalize.

**Comment by simi** [comment]
Does it make sense to do followup for this for JAVA extensions (when you run bundler gem my-little-gemy --ext under jruby)?

**Comment by andremedeiros** [comment]
@simi what would be different for Java extensions? I have 0 experience with those so I'd like to know more.

Right now there's an empty repo sitting on the bundler org, which will get all those improvements.
