### ISSUE TITLE
Bundler issues warning when a gem is on both the global source and a one-off source

### ISSUE THREAD

**Issue by cowboyd** [bundler/bundler#3671]
I have a Gemfile that looks like this:

```ruby
source "https://rubygems.org"
gem "rails"
gem 'capistrano-graphite', '1.0.5.spiceworks.1', require: false, source: "http://gem-server.spice.spiceworks.com"
```

The custom source `gem-server.spice.spiceworks.com` contains both the `capistrano-graphite` gem as well as `rails`.

When I run bundle install, it succeeds, but indicates several warnings about some of the gems being on both sources:

```sh
/C/S/tmp ❯❯❯ bundle install
Fetching gem metadata from http://gem-server.spice.spiceworks.com/...
Fetching gem metadata from https://rubygems.org/......
Fetching version metadata from http://gem-server.spice.spiceworks.com/...
Fetching version metadata from https://rubygems.org/..
Fetching gem metadata from http://gem-server.spice.spiceworks.com/...
Fetching version metadata from http://gem-server.spice.spiceworks.com/...
Fetching dependency metadata from http://gem-server.spice.spiceworks.com/..
Using i18n 0.7.0
Using builder 3.2.2
Using erubis 2.7.0
Using mini_portile 0.6.2
Using rack 1.6.1
Using mime-types 2.5
Using arel 6.0.0
Using colorize 0.7.7
Using net-ssh 2.9.2
Using bundler 1.9.9
Using thor 0.19.1
Using json 1.8.2
Using rake 10.4.2
Using thread_safe 0.3.5
Using minitest 5.6.1
Using nokogiri 1.6.6.2
Using rack-test 0.6.3
Using sprockets 3.1.0
Using mail 2.6.3
Using net-scp 1.2.1
Using tzinfo 1.2.2
Using loofah 2.0.2
Using sshkit 1.7.1
Using rails-html-sanitizer 1.0.2
Using capistrano 3.4.0
Installing capistrano-graphite 1.0.5.spiceworks.1
Installing activesupport 4.2.1
Using rails-deprecated_sanitizer 1.0.3
Using globalid 0.3.5
Using activemodel 4.2.1
Using rails-dom-testing 1.0.6
Using activejob 4.2.1
Using actionview 4.2.1
Installing actionpack 4.2.1
Using actionmailer 4.2.1
Using railties 4.2.1
Using sprockets-rails 2.3.1
Installing activerecord 4.2.1
Installing rails 4.2.1
Bundle complete! 2 Gemfile dependencies, 39 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
Warning: the gem 'activesupport' was found in multiple sources.
Installed from: https://rubygems.org/
Also found in:
  * http://gem-server.spice.spiceworks.com/
You should add a source requirement to restrict this gem to your preferred source.
For example:
    gem 'activesupport', :source => 'https://rubygems.org/'
Then uninstall the gem 'activesupport' (or delete all bundled gems) and then install again.
Warning: the gem 'activerecord' was found in multiple sources.
Installed from: https://rubygems.org/
Also found in:
  * http://gem-server.spice.spiceworks.com/
You should add a source requirement to restrict this gem to your preferred source.
For example:
    gem 'activerecord', :source => 'https://rubygems.org/'
Then uninstall the gem 'activerecord' (or delete all bundled gems) and then install again.
Warning: the gem 'actionpack' was found in multiple sources.
Installed from: https://rubygems.org/
Also found in:
  * http://gem-server.spice.spiceworks.com/
You should add a source requirement to restrict this gem to your preferred source.
For example:
    gem 'actionpack', :source => 'https://rubygems.org/'
Then uninstall the gem 'actionpack' (or delete all bundled gems) and then install again.
Warning: the gem 'rails' was found in multiple sources.
Installed from: https://rubygems.org/
Also found in:
  * http://gem-server.spice.spiceworks.com/
You should add a source requirement to restrict this gem to your preferred source.
For example:
    gem 'rails', :source => 'https://rubygems.org/'
Then uninstall the gem 'rails' (or delete all bundled gems) and then install again.
```

I don't know if that is the intended behavior, or a bug in bundler, but my intuition tells me that the Gemfile is pretty unambigous: the custom source should only be used for the one gem. I don't really care that other gems might incidentally exist on my custom source because I've specified rubygems.org as the global one and so it should take precedence over all others.

The same error manifests itself if I structure the `Gemfile` like so:

```ruby
source "https://rubygems.org"
gem "rails"

source "http://gem-server.spice.spiceworks.com" do
  gem 'capistrano-graphite', '1.0.5.spiceworks.1', require: false
end
```

This seems also very counterintuitive since the block form communicates very strongly to the reader that the source is only in effect inside the scope of the block, and cannot effect decisions outside it.

Might be related to #3537

**Comment by indirect** [comment]
The potential issue is when you have a child dependency (in this case, rails depending on activesupport), and that child dependency is present in both sources.

Here's the scenario we're trying to warn you about:

`capistrano-graphite` depends on `capistrano`. `capistrano` is present in both the `spiceworks.com` server and `rubygems.org`. Since it's a child dependency, the Gemfile doesn't specify which server it should be installed from. Regrettably, intuition in this case is that Bundler will be able to read the developer's mind: install `capistrano` from `rubygems.org` if that's what I want, but install `capistrano` from `spiceworks.com` if that's what I want.

Since Bundler can't read minds or know how to resolve conflicts like that, it prints a warning. Are you saying that you want Bundler to silently select between servers without any input from you in situations like that?

**Comment by cowboyd** [comment]
There needn't be any mind reading if Bundler specifies clear precedence rules when resolving sources and unambiguously sticks by them. That way, if I understand the rules, then I can act with confidence when working with multiple sources.

In my opinion, those precedence rules should be that the scope of a source should be as narrow as possible, so that developers never have to think about transitive dependencies when it comes to resolving conflicts. If I explicitly name the source of a gem, then that's what it gets, otherwise it gets the default source. Simple. Predictable. Custom sources are always opt-in. Honestly anything else seems dangerous (and ultimately infeasible when it comes to resolving dependencies of dependencies of dependencies)

In the event it appears that, despite the warnings, *this is in fact what bundler is already doing*, so it appears to think that this is the most reasonable choice. My vote is to make it official, and no warnings necessary.

**Comment by TimMoore** [comment]
What if you have a gem in a custom source that depends on other gems that are only available from that custom source? This is a pretty common scenario for private gems. With your proposal, all of the private transitive dependencies would then have to be declared explicitly in the app's `Gemfile` as well as the `gemspec`s for each private gem. I think a lot of people would be unhappy with that.

> In the event it appears that, despite the warnings, this is in fact what bundler is already doing, so it appears to think that this is the most reasonable choice. My vote is to make it official, and no warnings necessary.

The current behaviour doesn't guarantee this. There are a lot of variables that this depends on, including the order that it resolves the top-level gems, and the versions available in each source. For example, if there were a newer, compatible version of one of the gems available in the private source, I believe it would prefer that.

**Comment by cowboyd** [comment]
>What if you have a gem in a custom source that depends on other gems that are only available from that custom source? This is a pretty common scenario for private gems. With your proposal, all of the private transitive dependencies would then have to be declared explicitly in the app's Gemfile as well as the gemspecs for each private gem. 

As always, it's a trade-off. Yes, you would have to specify each dependency in the Gemile and the gemspec, but in return you're improving the developer ergonomics for (what I completely and totally conjecture based on no data whatsover is) the vast majority. After all, if I want to avoid these warnings, you end up having to put in a lot of extra explicit dependencies in the toplevel of your Gemfile which makes a lot of people unhappy for the same reason. 

I may very well have it backwards though.

Also, there may be other schemes that do a better job of satisfying both populations. This could be having an option to load all dependencies from the same source, or perhaps it could be to ensure that all transitive dependencies from a top-level entry are loaded from the its same source and requiring an explicit resolution only when a gem appears in the dependency tree of more than one source.

**Comment by TimMoore** [comment]
> This could be having an option to load all dependencies from the same source, or perhaps it could be to ensure that all transitive dependencies from a top-level entry are loaded from the its same source and requiring an explicit resolution only when a gem appears in the dependency tree of more than one source.

Maybe there is a bug here. It should only be searching in private sources for gems that are (transitive) dependencies of the gems declared in those sources.

**Comment by TimMoore** [comment]
This is meant to be tested by `spec/install/gems/sources_spec.rb:180`:

```
bundle install with gems on multiple sources
  with source affinity
    with an indirect dependency
      when the indirect dependency is in the pinned source
        and in another source
          installs from the same source without any warning
```

The test passes on master, so there must be some other condition that isn't tested. Maybe it's because some of the gems are already installed? @cowboyd do you get the same warning when you do a totally clean `bundle install`? You can test by installing to a different location `bundle install --path tmp/gems` or similar (keep in mind that the path setting is sticky in `.bundle/config`, so you'll need to unset it there afterwards).

**Comment by TimMoore** [comment]
On second thought, that test is actually testing the inverse case. I'll write up another test.

**Comment by TimMoore** [comment]
I've pushed a branch to https://github.com/TimMoore/bundler/tree/issue-3671 with a failing spec: https://github.com/bundler/bundler/compare/1-7-stable...TimMoore:issue-3671?expand=1

@indirect what do you think about those specs: do those capture the behavior we intend?

The first case ("and the dependency is only in the top-level source") passes as expected, but the other two fail, implying that Bundler is searching in pinned sources for dependencies of top-level gems, even when none of the pinned gems shre that dependency.

**Comment by indirect** [comment]
@tmoore yes, I think that spec is what we want. you can PR that if you like, and next core member with time can work on it.

**Comment by TimMoore** [comment]
OK, I'll push the branch to bundler/bundler and open a PR.

I should have some time this afternoon to take a shot at fixing it, but I have a bad feeling it might be a kind of big change.

**Comment by TimMoore** [comment]
The pull request is #3696

**Comment by LynnCo** [comment]
The PR for this (https://github.com/bundler/bundler/pull/3696) has stalled a bit, anyone is free to pick it up though!

**Comment by segiddins** [comment]
Given https://github.com/bundler/bundler/pull/3696 has been fixed on 2-0-dev, can we close this?
