### ISSUE TITLE
Bundler reports issues in `Gemfile.lock` regardless of the file being used as gemfile

### ISSUE THREAD

**Issue by AgentAntelope** [bundler/bundler#3672]
For example, in the event of a merge conflict in the file GemfileFast, bundler provides the following error:

![screen shot 2015-05-22 at 10 58 58](https://cloud.githubusercontent.com/assets/1962412/7768298/98adfa66-0071-11e5-9ec3-fad80c0e9299.png)

**Comment by rgb-one** [comment]
Can you provide more information following the guidelines in [ISSUE](https://github.com/bundler/bundler/blob/master/ISSUES.md).

**Comment by segiddins** [comment]
@rgb-one no additional info needed. 

Yes, there are places where we hardcode `Gemfile.lock` where we shouldn't.

**Comment by AgentAntelope** [comment]
Thanks, @segiddins.

I've had a bit of a look at this in an attempt to fix it. It seems that the `LockfileParser`, which generates this error, has no knowledge of the filename of the file it's trying to parse. I attempted to give it that information, but the assumptions seems to be baked in in quite a few places; Not just the lockfile parser, but the `lockfile` helper method, and other places too.

Sadly I think this is too large a piece of work for me without knowing more about the direction the code is headed in.
