### ISSUE TITLE
 ERROR REPORT TEMPLATE

### ISSUE THREAD

**Issue by jguzmanf88** [bundler/bundler#3675]
Someone can help me?

/Documentos/Ruby/blog2$ bundle install
/home/ubuntuadm/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/ext/builder.rb:73: warning: Insecure world writable dir /usr/local/rvm/gems/ruby-2.2.1/bin in PATH, mode 042777
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `/usr/local/rvm/gems/ruby-2.2.1/bin/bundle install`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what actually happened was...

Error details

    Errno::EACCES: Permission denied @ rb_sysopen - /usr/local/rvm/gems/ruby-2.2.1@global/extensions/x86_64-linux/2.1.0-static/executable-hooks-1.3.2/gem_make.out
      /home/ubuntuadm/.rbenv/versions/2.1.6/lib/ruby/2.1.0/open-uri.rb:36:in `initialize'
      /home/ubuntuadm/.rbenv/versions/2.1.6/lib/ruby/2.1.0/open-uri.rb:36:in `open'
      /home/ubuntuadm/.rbenv/versions/2.1.6/lib/ruby/2.1.0/open-uri.rb:36:in `open'
      /home/ubuntuadm/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/ext/builder.rb:212:in `write_gem_make_out'
      /home/ubuntuadm/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/ext/builder.rb:132:in `build_error'
      /home/ubuntuadm/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/ext/builder.rb:171:in `rescue in build_extension'
      /home/ubuntuadm/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/ext/builder.rb:156:in `build_extension'
      /home/ubuntuadm/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/ext/builder.rb:198:in `block in build_extensions'
      /home/ubuntuadm/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/ext/builder.rb:195:in `each'
      /home/ubuntuadm/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/ext/builder.rb:195:in `build_extensions'
      /home/ubuntuadm/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/specification.rb:1436:in `block in build_extensions'
      /home/ubuntuadm/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/user_interaction.rb:45:in `use_ui'
      /home/ubuntuadm/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/specification.rb:1434:in `build_extensions'
      /home/ubuntuadm/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/stub_specification.rb:60:in `build_extensions'
      /home/ubuntuadm/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/basic_specification.rb:56:in `contains_requirable_file?'
      /home/ubuntuadm/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/specification.rb:925:in `block in find_inactive_by_path'
      /home/ubuntuadm/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/specification.rb:924:in `each'
      /home/ubuntuadm/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/specification.rb:924:in `find'
      /home/ubuntuadm/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/specification.rb:924:in `find_inactive_by_path'
      /home/ubuntuadm/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems.rb:185:in `try_activate'
      /home/ubuntuadm/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:132:in `rescue in require'
      /home/ubuntuadm/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:144:in `require'
      /usr/local/rvm/gems/ruby-2.2.1/gems/bundler-1.9.9/lib/bundler/vendor/net/http/persistent.rb:12:in `<top (required)>'
      /home/ubuntuadm/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
      /home/ubuntuadm/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
      /usr/local/rvm/gems/ruby-2.2.1/gems/bundler-1.9.9/lib/bundler/vendored_persistent.rb:11:in `<top (required)>'
      /home/ubuntuadm/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
      /home/ubuntuadm/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
      /usr/local/rvm/gems/ruby-2.2.1/gems/bundler-1.9.9/lib/bundler/fetcher.rb:1:in `<top (required)>'
      /usr/local/rvm/gems/ruby-2.2.1/gems/bundler-1.9.9/lib/bundler/cli/install.rb:72:in `run'
      /usr/local/rvm/gems/ruby-2.2.1/gems/bundler-1.9.9/lib/bundler/cli.rb:155:in `install'
      /usr/local/rvm/gems/ruby-2.2.1/gems/bundler-1.9.9/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /usr/local/rvm/gems/ruby-2.2.1/gems/bundler-1.9.9/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /usr/local/rvm/gems/ruby-2.2.1/gems/bundler-1.9.9/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /usr/local/rvm/gems/ruby-2.2.1/gems/bundler-1.9.9/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /usr/local/rvm/gems/ruby-2.2.1/gems/bundler-1.9.9/lib/bundler/cli.rb:10:in `start'
      /usr/local/rvm/gems/ruby-2.2.1/gems/bundler-1.9.9/bin/bundle:20:in `block in <top (required)>'
      /usr/local/rvm/gems/ruby-2.2.1/gems/bundler-1.9.9/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
      /usr/local/rvm/gems/ruby-2.2.1/gems/bundler-1.9.9/bin/bundle:18:in `<top (required)>'
      /usr/local/rvm/gems/ruby-2.2.1/bin/bundle:23:in `load'
      /usr/local/rvm/gems/ruby-2.2.1/bin/bundle:23:in `<main>'

Environment

    Bundler   1.9.9
    Rubygems  2.2.3
    Ruby      2.1.6p336 (2015-04-13 revision 50298) [x86_64-linux]
    GEM_HOME  /usr/local/rvm/gems/ruby-2.2.1
    GEM_PATH  /usr/local/rvm/gems/ruby-2.2.1:/usr/local/rvm/gems/ruby-2.2.1@global
    RVM       1.26.11 (master)
    Git       1.9.1
    rubygems-bundler (1.4.4)
--- TEMPLATE END ----------------------------------------------------------------

**Comment by andremedeiros** [comment]
Bundler can't write into your gems directory (thus the `Errno::EACCES: Permission denied`)

Most likely that gem set was created with `sudo` and your normal user (which is running Bundler) can't write on it.

**Comment by jguzmanf88** [comment]
Oh... I can ser now. How can i fix that?

**Comment by andremedeiros** [comment]
You'd have to find out which directory is owned by root and `chown` it.

**Comment by jguzmanf88** [comment]
Thank's a lot!!!
