### ISSUE TITLE
Add `pkg` to Rake's CLOBBER FileList

### ISSUE THREAD

**Issue by jasonkarns** [bundler/bundler#3676]
Bundler's gem_tasks are quite helpful. But the first thing that needs added to a new gem's Rakefile is frequently `require 'rake/clean'` and `CLOBBER.include 'pkg'`

Since 'pkg' is hardcoded into the `build` task, might it also be handy to pre-populate the `CLOBBER` FileList with 'pkg' as well?

**Comment by indirect** [comment]
It might be handy... can you elaborate on why you need to clobber pkg? I never do, and the only side effect seems to be ending up with old versions of the gem sitting in pkg...

**Comment by jasonkarns** [comment]
"need" is a bit strong. It's mostly just the urge to keep things tidy. And
a bit of habit. I typically `make clean` or `npm run clean` or `rake clean`.

Of course, in keeping with rake's fine distinction of clean vs clobber, I
use `clobber` for gems. (`clean` being for temporary/intermediate files,
`clobber` being for resulting/generated files)

So there's no particular reason why I have the compulsion for cleaning. But
given that rake has default semantics for clean, I figured it'd be worth
considering applying those semantics to bundler's tasks.

**Comment by indirect** [comment]
Yeah, seems reasonable. Send a PR?

**Comment by jasonkarns** [comment]
sure thing!
