### ISSUE TITLE
Bundler 1.10 downgrade rails verison

### ISSUE THREAD

**Issue by Sega100500** [bundler/bundler#3685]
Gemfile:
gem 'rails', '~> 3.2.16'

before 1.10 version of bundler it install rails 3.2.21
All work FINE!

bundle update
version 1.10 long time:
Resolving dependencies....................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
etc

After
install rails 3.2.13

Why?!!!

**Comment by indirect** [comment]
Thank you for reporting this issue! Please follow the instructions in [ISSUES](https://github.com/carlhuda/bundler/blob/master/ISSUES.md) and provide us with the requested information so that we can try to reproduce this issue and fix it.

**Comment by Sega100500** [comment]
Sorry
After delete Gemfile.lock
bundle install
bundle update

All FINE!
