### ISSUE TITLE
No such file or directory @ rb_file_s_stat - MIT-LICENSE

### ISSUE THREAD

**Issue by kdisneur** [bundler/bundler#3686]
- What did you do?

  I ran the command `/home/ubuntu/.rvm/gems/ruby-2.1.6@global/bin/bundle install --path=../vendor/bundle`
  We use Circle-CI and we update bundler each time we run the tests. The tests had no gem updates, just some view related code.
Tests were green yesterday and now they are all failing (a rebuild of master leads to a fail also). 

- What did you expect to happen?

  I expected Bundler to install my gems as usual

- What happened instead?

  Instead, what actually happened was...

Error details

    Errno::ENOENT: No such file or directory @ rb_file_s_stat - MIT-LICENSE
      /home/ubuntu/.rvm/rubies/ruby-2.1.6/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:2716:in `stat'
      /home/ubuntu/.rvm/rubies/ruby-2.1.6/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:2716:in `block in validate_permissions'
      /home/ubuntu/.rvm/rubies/ruby-2.1.6/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:2715:in `each'
      /home/ubuntu/.rvm/rubies/ruby-2.1.6/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:2715:in `validate_permissions'
      /home/ubuntu/.rvm/rubies/ruby-2.1.6/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:2582:in `validate'
      /home/ubuntu/.rvm/gems/ruby-2.1.6@global/gems/bundler-1.10.1/lib/bundler/rubygems_integration.rb:51:in `block in validate'
      /home/ubuntu/.rvm/gems/ruby-2.1.6@global/gems/bundler-1.10.1/lib/bundler/ui/shell.rb:76:in `silence'
      /home/ubuntu/.rvm/gems/ruby-2.1.6@global/gems/bundler-1.10.1/lib/bundler/rubygems_integration.rb:51:in `validate'
      /home/ubuntu/.rvm/gems/ruby-2.1.6@global/gems/bundler-1.10.1/lib/bundler.rb:369:in `block in load_gemspec_uncached'
      /home/ubuntu/.rvm/gems/ruby-2.1.6@global/gems/bundler-1.10.1/lib/bundler/shared_helpers.rb:53:in `chdir'
      /home/ubuntu/.rvm/gems/ruby-2.1.6@global/gems/bundler-1.10.1/lib/bundler/shared_helpers.rb:53:in `block in chdir'
      /home/ubuntu/.rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
      /home/ubuntu/.rvm/gems/ruby-2.1.6@global/gems/bundler-1.10.1/lib/bundler/shared_helpers.rb:52:in `chdir'
      /home/ubuntu/.rvm/gems/ruby-2.1.6@global/gems/bundler-1.10.1/lib/bundler.rb:362:in `load_gemspec_uncached'
      /home/ubuntu/.rvm/gems/ruby-2.1.6@global/gems/bundler-1.10.1/lib/bundler.rb:352:in `load_gemspec'
      /home/ubuntu/.rvm/gems/ruby-2.1.6@global/gems/bundler-1.10.1/lib/bundler/source/path.rb:134:in `block in load_spec_files'
      /home/ubuntu/.rvm/gems/ruby-2.1.6@global/gems/bundler-1.10.1/lib/bundler/source/path.rb:133:in `each'
      /home/ubuntu/.rvm/gems/ruby-2.1.6@global/gems/bundler-1.10.1/lib/bundler/source/path.rb:133:in `load_spec_files'
      /home/ubuntu/.rvm/gems/ruby-2.1.6@global/gems/bundler-1.10.1/lib/bundler/source/git.rb:189:in `load_spec_files'
      /home/ubuntu/.rvm/gems/ruby-2.1.6@global/gems/bundler-1.10.1/lib/bundler/source/path.rb:91:in `local_specs'
      /home/ubuntu/.rvm/gems/ruby-2.1.6@global/gems/bundler-1.10.1/lib/bundler/source/git.rb:159:in `specs'
      /home/ubuntu/.rvm/gems/ruby-2.1.6@global/gems/bundler-1.10.1/lib/bundler/definition.rb:210:in `block (2 levels) in index'
      /home/ubuntu/.rvm/gems/ruby-2.1.6@global/gems/bundler-1.10.1/lib/bundler/definition.rb:208:in `each'
      /home/ubuntu/.rvm/gems/ruby-2.1.6@global/gems/bundler-1.10.1/lib/bundler/definition.rb:208:in `block in index'
      /home/ubuntu/.rvm/gems/ruby-2.1.6@global/gems/bundler-1.10.1/lib/bundler/index.rb:9:in `build'
      /home/ubuntu/.rvm/gems/ruby-2.1.6@global/gems/bundler-1.10.1/lib/bundler/definition.rb:205:in `index'
      /home/ubuntu/.rvm/gems/ruby-2.1.6@global/gems/bundler-1.10.1/lib/bundler/definition.rb:199:in `resolve'
      /home/ubuntu/.rvm/gems/ruby-2.1.6@global/gems/bundler-1.10.1/lib/bundler/definition.rb:165:in `missing_specs'
      /home/ubuntu/.rvm/gems/ruby-2.1.6@global/gems/bundler-1.10.1/lib/bundler/installer.rb:70:in `block in run'
      /home/ubuntu/.rvm/gems/ruby-2.1.6@global/gems/bundler-1.10.1/lib/bundler/ui/shell.rb:76:in `silence'
      /home/ubuntu/.rvm/gems/ruby-2.1.6@global/gems/bundler-1.10.1/lib/bundler/installer.rb:67:in `run'
      /home/ubuntu/.rvm/gems/ruby-2.1.6@global/gems/bundler-1.10.1/lib/bundler/installer.rb:18:in `install'
      /home/ubuntu/.rvm/gems/ruby-2.1.6@global/gems/bundler-1.10.1/lib/bundler/cli/install.rb:107:in `run'
      /home/ubuntu/.rvm/gems/ruby-2.1.6@global/gems/bundler-1.10.1/lib/bundler/cli.rb:158:in `install'
      /home/ubuntu/.rvm/gems/ruby-2.1.6@global/gems/bundler-1.10.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /home/ubuntu/.rvm/gems/ruby-2.1.6@global/gems/bundler-1.10.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /home/ubuntu/.rvm/gems/ruby-2.1.6@global/gems/bundler-1.10.1/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /home/ubuntu/.rvm/gems/ruby-2.1.6@global/gems/bundler-1.10.1/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /home/ubuntu/.rvm/gems/ruby-2.1.6@global/gems/bundler-1.10.1/lib/bundler/cli.rb:10:in `start'
      /home/ubuntu/.rvm/gems/ruby-2.1.6@global/gems/bundler-1.10.1/bin/bundle:20:in `block in <top (required)>'
      /home/ubuntu/.rvm/gems/ruby-2.1.6@global/gems/bundler-1.10.1/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
      /home/ubuntu/.rvm/gems/ruby-2.1.6@global/gems/bundler-1.10.1/bin/bundle:18:in `<top (required)>'
      /home/ubuntu/.rvm/gems/ruby-2.1.6@global/bin/bundle:23:in `load'
      /home/ubuntu/.rvm/gems/ruby-2.1.6@global/bin/bundle:23:in `<main>'
      /home/ubuntu/.rvm/gems/ruby-2.1.6@global/bin/ruby_executable_hooks:15:in `eval'
      /home/ubuntu/.rvm/gems/ruby-2.1.6@global/bin/ruby_executable_hooks:15:in `<main>'

Environment

    Bundler   1.10.1
    Rubygems  2.4.6
    Ruby      2.1.6p336 (2015-04-13 revision 50298) [x86_64-linux]
    GEM_HOME  /home/ubuntu/<project>/vendor/bundle/ruby/2.1.0
    GEM_PATH  
    RVM       1.26.10 (1.26.10)
    Git       1.8.5.6

Bundler settings

    path
      Set for your local app (/home/ubuntu/<project>/.bundle/config): "../vendor/bundle"
    disable_shared_gems
      Set for your local app (/home/ubuntu/<project>/.bundle/config): "1"

**Comment by andremedeiros** [comment]
I guess this is probably a no, but could you share your Gemfile? I strongly suspect this has to do with a bad gem spec.

**Comment by kdisneur** [comment]
As intended I can't upload the Gemfile but we found the issue (thanks @andremedeiros for your suggestion).

The problem was one of our project (last update 11 months ago) which specifies, in its gemspec, some inexistant files: MIT-LICENSE, Rakefile,.. So I removed these useless informations and it works again.

So it's maybe a regression from the previous version of bundler but it can be fixed easily. We also had some errors because of duplication in our gemspec. So we have just cleaned the gemspec and everything looks OK  \o/. 

But, definitively, all these things were working yesterday and I don't see anything about this kind of change in the CHANGELOG. Any clue of why it happens now?

**Comment by jvanbaarsen** [comment]
I ran into this problem as well. In our case it was because of this gem: https://github.com/intercity/knife-solo which was declared as follow in our gemfile:

```
gem 'knife-solo', :github => 'intercity/knife-solo', :branch => 'nodes-out-of-kitchen', :submodules => true
```

The file that could not be found was: 
```
 Errno::ENOENT: No such file or directory @ rb_file_s_stat - lib/knife-solo/resources/patch_cookbooks/chef-solo-search/.travis.yml
```
Which is in a submodule for that gem. I checked the repo for the submodule, and the file is still present there.

**Comment by kdisneur** [comment]
We also add an error because name and email were set to `TODO`. 

It definitively looks like the gems used as a git dependency are now validated when we bundle.

**Comment by segiddins** [comment]
We definitely should add file existence checking to RubyGems, and in the meantime rescuing errno and explaining where it's coming from might make sense?

**Comment by jvanbaarsen** [comment]
@segiddins Yeah that sounds like a good fix! In that case you know what is causing the error :D It has taken me about 3 hours to figure out haha

**Comment by kdisneur** [comment]
@segiddins yup could be awesome

@jvanbaarsen I debugged it the ugly way: opening `rubygems/specification.rb:2716` and `puts` the name of the gem in a rescue before raising. OK it's not neat at all but, at least, you find the problem quickly :D

**Comment by segiddins** [comment]
This should be fixed by https://github.com/bundler/bundler/issues/3708, which will be released shortly.

**Comment by jvanbaarsen** [comment]
@segiddins Thanks for the quick response/fix :+1:

**Comment by kdisneur** [comment]
@segiddins: thank you :100:

**Comment by abookyun** [comment]
@segiddins thank you :100:
