### ISSUE TITLE
Gemspec invalid error with Bundler 1.10.1

### ISSUE THREAD

**Issue by sarsena** [bundler/bundler#3688]
```The gemspec at /opt/partner_printer_tool/shared/bundled_gems/ruby/1.9.1/bundler/gems/secondbase-bd249ef4d1ae/secondbase.gemspec is not valid. The validation error was 'duplicate dependency on activerecord (~> 3.0.0, development), (~> 3.0.0) use: add_runtime_dependency 'activerecord', '~> 3.0.0', '~> 3.0.0'```

Im not sure why im getting this now on the secondbase gem. I was not getting this issue yesterday when I tried to run assets:precompile.  Here is my `bundle -v`:
`Bundler version 1.10.1`

**Comment by segiddins** [comment]
As the error says, the `secondbase.gemspec` isn't valid. In bundler 1.10, `path` and `git` gem specs are validated.

**Comment by aviflax** [comment]
So you guys made bundler stricter… this is tough for those of use who don’t understand how to fix issues like these. Some guidance would be helpful. Thanks!

**Comment by segiddins** [comment]
@aviflax we made this change in order to allow us to give you easier errors when pulling in invalid gemspecs, rather than blowing up in mysterious ways.

**Comment by aviflax** [comment]
@segiddins that makes sense and I appreciate and support it! Just FYI as a Ruby dabbler I just have no idea how to proceed when I get this error.
