### ISSUE TITLE
Bundler inline cannot require if installing gem at the same time

### ISSUE THREAD

**Issue by repinel** [bundler/bundler#3693]
When trying to use the example provided by the [inline feature](https://github.com/bundler/bundler/pull/3440), changing the `gemfile` line to indicate that the gems should be installed:

```
#!/usr/bin/env ruby

require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'
  gem 'json', require: false
  gem 'nap', require: 'rest'
  gem 'cocoapods', '~> 0.34.1'
end

puts Pod::VERSION # => "0.34.4"
```

I get the following at the first time I run it:

```
bundler-1.10.2/lib/bundler/runtime.rb:76:in `require': cannot load such file -- rest (LoadError)
  from bundler-1.10.2/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
  from bundler-1.10.2/lib/bundler/runtime.rb:72:in `each'
  from bundler-1.10.2/lib/bundler/runtime.rb:72:in `block in require'
  from bundler-1.10.2/lib/bundler/runtime.rb:61:in `each'
  from bundler-1.10.2/lib/bundler/runtime.rb:61:in `require'
  from bundler-1.10.2/lib/bundler/inline.rb:55:in `gemfile'
  from example.rb:5:in `<main>'
```

After the first time, when the gems are already installed, everything goes fine and I get the expected output `0.34.4`.

I have:
* Bundler version 1.10.2
* Rubygems 2.4.7
* ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14] [MRI]
* rvm 1.26.11

Let me know if you need more information. If it is a real issue, I'd love to try working on it.

**Comment by segiddins** [comment]
Can confirm.

**Comment by segiddins** [comment]
Closed by https://github.com/bundler/bundler/issues/3694.

**Comment by repinel** [comment]
Thank you!  :+1:
