### ISSUE TITLE
Errno::ENOENT: No such file or directory @ rb_file_s_stat - .rspec

### ISSUE THREAD

**Issue by simmogs** [bundler/bundler#3698]
- What did you do?

  I ran the command `/home/graeme/.rvm/gems/ruby-2.1.2@transform/bin/bundle `

- What did you expect to happen?

  I expected Bundler to install my gems.

- What happened instead?

  Instead, what actually happened was that it threw up an error as per below. There is a .rspec file in the project directory.

Error details

    Errno::ENOENT: No such file or directory @ rb_file_s_stat - .rspec
      /home/graeme/.rvm/rubies/ruby-2.1.2/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:2716:in `stat'
      /home/graeme/.rvm/rubies/ruby-2.1.2/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:2716:in `block in validate_permissions'
      /home/graeme/.rvm/rubies/ruby-2.1.2/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:2715:in `each'
      /home/graeme/.rvm/rubies/ruby-2.1.2/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:2715:in `validate_permissions'
      /home/graeme/.rvm/rubies/ruby-2.1.2/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:2582:in `validate'
      /home/graeme/.rvm/gems/ruby-2.1.2@transform/gems/bundler-1.10.1/lib/bundler/rubygems_integration.rb:51:in `block in validate'
      /home/graeme/.rvm/gems/ruby-2.1.2@transform/gems/bundler-1.10.1/lib/bundler/ui/shell.rb:76:in `silence'
      /home/graeme/.rvm/gems/ruby-2.1.2@transform/gems/bundler-1.10.1/lib/bundler/rubygems_integration.rb:51:in `validate'
      /home/graeme/.rvm/gems/ruby-2.1.2@transform/gems/bundler-1.10.1/lib/bundler.rb:369:in `block in load_gemspec_uncached'
      /home/graeme/.rvm/gems/ruby-2.1.2@transform/gems/bundler-1.10.1/lib/bundler/shared_helpers.rb:53:in `chdir'
      /home/graeme/.rvm/gems/ruby-2.1.2@transform/gems/bundler-1.10.1/lib/bundler/shared_helpers.rb:53:in `block in chdir'
      /home/graeme/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
      /home/graeme/.rvm/gems/ruby-2.1.2@transform/gems/bundler-1.10.1/lib/bundler/shared_helpers.rb:52:in `chdir'
      /home/graeme/.rvm/gems/ruby-2.1.2@transform/gems/bundler-1.10.1/lib/bundler.rb:362:in `load_gemspec_uncached'
      /home/graeme/.rvm/gems/ruby-2.1.2@transform/gems/bundler-1.10.1/lib/bundler.rb:352:in `load_gemspec'
      /home/graeme/.rvm/gems/ruby-2.1.2@transform/gems/bundler-1.10.1/lib/bundler/source/path.rb:134:in `block in load_spec_files'
      /home/graeme/.rvm/gems/ruby-2.1.2@transform/gems/bundler-1.10.1/lib/bundler/source/path.rb:133:in `each'
      /home/graeme/.rvm/gems/ruby-2.1.2@transform/gems/bundler-1.10.1/lib/bundler/source/path.rb:133:in `load_spec_files'
      /home/graeme/.rvm/gems/ruby-2.1.2@transform/gems/bundler-1.10.1/lib/bundler/source/git.rb:189:in `load_spec_files'
      /home/graeme/.rvm/gems/ruby-2.1.2@transform/gems/bundler-1.10.1/lib/bundler/source/path.rb:91:in `local_specs'
      /home/graeme/.rvm/gems/ruby-2.1.2@transform/gems/bundler-1.10.1/lib/bundler/source/git.rb:159:in `specs'
      /home/graeme/.rvm/gems/ruby-2.1.2@transform/gems/bundler-1.10.1/lib/bundler/lazy_specification.rb:53:in `__materialize__'
      /home/graeme/.rvm/gems/ruby-2.1.2@transform/gems/bundler-1.10.1/lib/bundler/spec_set.rb:88:in `block in materialize'
      /home/graeme/.rvm/gems/ruby-2.1.2@transform/gems/bundler-1.10.1/lib/bundler/spec_set.rb:85:in `map!'
      /home/graeme/.rvm/gems/ruby-2.1.2@transform/gems/bundler-1.10.1/lib/bundler/spec_set.rb:85:in `materialize'
      /home/graeme/.rvm/gems/ruby-2.1.2@transform/gems/bundler-1.10.1/lib/bundler/definition.rb:165:in `missing_specs'
      /home/graeme/.rvm/gems/ruby-2.1.2@transform/gems/bundler-1.10.1/lib/bundler/installer.rb:70:in `block in run'
      /home/graeme/.rvm/gems/ruby-2.1.2@transform/gems/bundler-1.10.1/lib/bundler/ui/shell.rb:76:in `silence'
      /home/graeme/.rvm/gems/ruby-2.1.2@transform/gems/bundler-1.10.1/lib/bundler/installer.rb:67:in `run'
      /home/graeme/.rvm/gems/ruby-2.1.2@transform/gems/bundler-1.10.1/lib/bundler/installer.rb:18:in `install'
      /home/graeme/.rvm/gems/ruby-2.1.2@transform/gems/bundler-1.10.1/lib/bundler/cli/install.rb:107:in `run'
      /home/graeme/.rvm/gems/ruby-2.1.2@transform/gems/bundler-1.10.1/lib/bundler/cli.rb:158:in `install'
      /home/graeme/.rvm/gems/ruby-2.1.2@transform/gems/bundler-1.10.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /home/graeme/.rvm/gems/ruby-2.1.2@transform/gems/bundler-1.10.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /home/graeme/.rvm/gems/ruby-2.1.2@transform/gems/bundler-1.10.1/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /home/graeme/.rvm/gems/ruby-2.1.2@transform/gems/bundler-1.10.1/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /home/graeme/.rvm/gems/ruby-2.1.2@transform/gems/bundler-1.10.1/lib/bundler/cli.rb:10:in `start'
      /home/graeme/.rvm/gems/ruby-2.1.2@transform/gems/bundler-1.10.1/bin/bundle:20:in `block in <top (required)>'
      /home/graeme/.rvm/gems/ruby-2.1.2@transform/gems/bundler-1.10.1/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
      /home/graeme/.rvm/gems/ruby-2.1.2@transform/gems/bundler-1.10.1/bin/bundle:18:in `<top (required)>'
      /home/graeme/.rvm/gems/ruby-2.1.2@transform/bin/bundle:23:in `load'
      /home/graeme/.rvm/gems/ruby-2.1.2@transform/bin/bundle:23:in `<main>'
      /home/graeme/.rvm/gems/ruby-2.1.2@transform/bin/ruby_executable_hooks:15:in `eval'
      /home/graeme/.rvm/gems/ruby-2.1.2@transform/bin/ruby_executable_hooks:15:in `<main>'

Environment

    Bundler   1.10.1
    Rubygems  2.4.7
    Ruby      2.1.2p95 (2014-05-08 revision 45877) [x86_64-linux]
    GEM_HOME  /home/graeme/.rvm/gems/ruby-2.1.2@transform
    GEM_PATH  /home/graeme/.rvm/gems/ruby-2.1.2@transform:/home/graeme/.rvm/gems/ruby-2.1.2@global
    RVM       1.26.11 (latest)
    Git       2.1.4
    rubygems-bundler (1.4.4)

Bundler settings

    gem.coc
      Set for the current user (/home/graeme/.bundle/config): "false"
    gem.mit
      Set for the current user (/home/graeme/.bundle/config): "false"
    gem.test
      Set for the current user (/home/graeme/.bundle/config): "rspec"
    cache_all
      Set for your local app (/home/graeme/Code/tdrc/transform/.bundle/config): "true"

**Comment by maxvlc** [comment]
```Environment
    Bundler   1.10.2
    Rubygems  2.4.6
    Ruby      2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux]
    GEM_HOME  /home/travis/build/Soluciones/Verema/vendor/bundle/ruby/2.2.0
    GEM_PATH  
    RVM       1.26.10 (latest-minor)
    Git       1.8.5.6

**Comment by hundredwatt** [comment]
I ran into the same issue on ubuntu when running `rake` tasks

**Comment by Chili-Man** [comment]
I am running in to this issue as well, I pasted the output here:
https://gist.github.com/Chili-Man/47a6816b86429f35f634

**Comment by wakabala** [comment]
I too ran into this issues, was it something recent that hapepned?

**Comment by reiz** [comment]
I have a similar issue.

**Comment by reiz** [comment]
I solved my issue #3702. Problem was that in the gemspec a non existing file was referenced.

**Comment by annejohnson** [comment]
This was happening to me, except with Gemfile.lock instead of .rspec.

I got around it for now by switching down to bundler v. 1.9.6.

**Comment by segiddins** [comment]
This is an issue with rubygems validation of specifications. I've already out in a PR over there to fix the issue, but in the meantime, I'll add a more informative exception to bundler. 

-Samuel E. Giddins

On Jun 2, 2015, at 6:35 AM, Anne Johnson <notifications@github.com> wrote:

This was happening to me, except with Gemfile.lock instead of .rspec.

I got around it for now by switching down to bundler v. 1.9.6.

**Comment by simsalabim** [comment]
Experienced exactly the same with Gemfile.lock. Went with workaround from @annejohnson and downgraded bundler from 1.10.2 to 1.9.6. Thanks @annejohnson!

**Comment by fertobar** [comment]
downgraded bundler from 1.10.2 to 1.9.6 works for me too! thanks!

**Comment by gsecillano** [comment]
Why 1.9.6 and not 1.9.7-1.9.9?

**Comment by fertobar** [comment]
I not try with 1.9.7-1.9.9, but may be works too :) 
With last bundler version I got similar error posted in the top description.

**Comment by gsecillano** [comment]
FYI, I tried 1.9.9 and it does not seem to have the problem.

**Comment by segiddins** [comment]
Yes, this is a known issue with rubygems that was exposed in bundler 1.10. No need to keep posting, we're aware of it, a fix has already been merged to rubygems, and a fix will be made for bundler soon.

**Comment by maxvlc** [comment]
In our case the problem wasthe bundle version, with 1.9.9 works fine...

**Comment by segiddins** [comment]
Should be fixed by https://github.com/bundler/bundler/issues/3708, which will be released shortly.

**Comment by jakeatwork** [comment]
reverting to bundler 1.9.6 worked for me...the latest version still had this issue when using ruby motion, redpotion, and hockey app sdk to build  ios apps.

**Comment by ctsstc** [comment]
If you end up here from google this may be more relevant: 
https://github.com/rails/rails/issues/26658
