### ISSUE TITLE
phishing frenzy on ubuntu 14

### ISSUE THREAD

**Issue by Bressie** [bundler/bundler#3703]
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `/home/blaz/.rvm/gems/ruby-2.1.1/bin/bundle install --deployment`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what actually happened was...

Error details

    Errno::EACCES: Permission denied @ dir_s_mkdir - /var/www/phishing-frenzy/.bundle
      /home/blaz/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/fileutils.rb:250:in `mkdir'
      /home/blaz/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/fileutils.rb:250:in `fu_mkdir'
      /home/blaz/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/fileutils.rb:224:in `block (2 levels) in mkdir_p'
      /home/blaz/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/fileutils.rb:222:in `reverse_each'
      /home/blaz/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/fileutils.rb:222:in `block in mkdir_p'
      /home/blaz/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/fileutils.rb:208:in `each'
      /home/blaz/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/fileutils.rb:208:in `mkdir_p'
      /home/blaz/.rvm/gems/ruby-2.1.1/gems/bundler-1.10.2/lib/bundler/settings.rb:208:in `set_key'
      /home/blaz/.rvm/gems/ruby-2.1.1/gems/bundler-1.10.2/lib/bundler/settings.rb:31:in `[]='
      /home/blaz/.rvm/gems/ruby-2.1.1/gems/bundler-1.10.2/lib/bundler/cli/install.rb:76:in `run'
      /home/blaz/.rvm/gems/ruby-2.1.1/gems/bundler-1.10.2/lib/bundler/cli.rb:158:in `install'
      /home/blaz/.rvm/gems/ruby-2.1.1/gems/bundler-1.10.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /home/blaz/.rvm/gems/ruby-2.1.1/gems/bundler-1.10.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /home/blaz/.rvm/gems/ruby-2.1.1/gems/bundler-1.10.2/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /home/blaz/.rvm/gems/ruby-2.1.1/gems/bundler-1.10.2/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /home/blaz/.rvm/gems/ruby-2.1.1/gems/bundler-1.10.2/lib/bundler/cli.rb:10:in `start'
      /home/blaz/.rvm/gems/ruby-2.1.1/gems/bundler-1.10.2/bin/bundle:20:in `block in <top (required)>'
      /home/blaz/.rvm/gems/ruby-2.1.1/gems/bundler-1.10.2/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
      /home/blaz/.rvm/gems/ruby-2.1.1/gems/bundler-1.10.2/bin/bundle:18:in `<top (required)>'
      /home/blaz/.rvm/gems/ruby-2.1.1/bin/bundle:23:in `load'
      /home/blaz/.rvm/gems/ruby-2.1.1/bin/bundle:23:in `<main>'
      /home/blaz/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `eval'
      /home/blaz/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `<main>'

Environment

    Bundler   1.10.2
    Rubygems  2.4.7
    Ruby      2.1.1p76 (2014-02-24 revision 45161) [x86_64-linux]
    GEM_HOME  /home/blaz/.rvm/gems/ruby-2.1.1
    GEM_PATH  /home/blaz/.rvm/gems/ruby-2.1.1:/home/blaz/.rvm/gems/ruby-2.1.1@global
    RVM       1.26.11 (master)
    Git       1.9.1
    rubygems-bundler (1.4.4)

Bundler settings

    frozen
      Set for your local app (/var/www/phishing-frenzy/.bundle/config): "1"
--- TEMPLATE END ----------------------------------------------------------------

**Comment by simi** [comment]
You have not access to `/var/www/phishing-frenzy/.bundle` (bundler is trying to make that directory) for user running `bundle`.

**Comment by Bressie** [comment]
thanks

**Comment by segiddins** [comment]
We should give a better error message
