### ISSUE TITLE
Unknown switches '--path'

### ISSUE THREAD

**Issue by JScott** [bundler/bundler#3712]
I'm trying to do a `bundle install` in code with. I ran across some old issues which suggested something like this:
```ruby
Dir.chdir('.test') { Bundler::CLI.start.invoke(:install) }
```

However, that gives this error with Bundler v1.10.2:
```
/Users/jscott/.gem/ruby/2.2.1/gems/bundler-1.10.2/lib/bundler/cli.rb:24:in `rescue in initialize': Unknown switches '--path' (Bundler::InvalidOption)
```

After a bit of monkeypatching I found that `Bundle::Thor::Base` was begin initialized with local_options of ['--path', '.test']. The error seems weird since path is a valid flag for `bundle install` and the local_options are internally generated.

**Comment by segiddins** [comment]
You probably want `Bundler::CLI.start %w(install)` ?

**Comment by JScott** [comment]
That seems to work, thanks. Is that actually documented anywhere? I was sort of piecing it together from old issues and comments.

**Comment by segiddins** [comment]
Nope, pretty much all of bundlers internals are just that -- internal.
