### ISSUE TITLE
Specs for RubyGems UI working

### ISSUE THREAD

**Issue by segiddins** [bundler/bundler#3714]
In:
- [ ] Rakefiles
- [ ] bundle exec
- [ ] -rbundler/setup

**Comment by segiddins** [comment]
This is much harder than expected...

**Comment by kkirsche** [comment]
Could you elaborate what the goal of this is? Not sure I understand what "RubyGems UI" is

**Comment by agis-** [comment]
@segiddins Is this still relevant? If so, can you elaborate on what's to be done so anyone else can pick this up?

**Comment by segiddins** [comment]
It is relevant, but I guarantee you no one will want to do it 😜

**Comment by agis-** [comment]
Ah it's good it's fine, nevermind! :runner: :smile:

**Comment by RochesterinNYC** [comment]
Could we get a quick context dump on this?

**Comment by segiddins** [comment]
I believe it was about the things RubyGems prints being printed properly, prompted by https://github.com/bundler/bundler/pull/3707 (and the underlying issue https://github.com/bundler/bundler/issues/3710)
