### ISSUE TITLE
`install --force` should delete existing gems before installing

### ISSUE THREAD

**Issue by indirect** [bundler/bundler#3715]
> @segiddins that's a bug in force, then. we need to nuke the directory, since it's possible that a malicious gem could install files that don't get overwritten when the non-malicious gem is installed. :/

**Comment by karlo57** [comment]
@indirect Can you provide more details? I'd like to help fix this bug. Thanks!

**Comment by indirect** [comment]
@karlo57 sure, no problem.

Right now, when you run `bundle install --force`, we download each .gem file again (even if we already have a copy downloaded), and we install each gem again (even if that gem is already installed). The additional thing we need to do is _uninstall_ each gem before we download and install it again. Or if not uninstall, at least delete the directory containing the installed/unpacked files, to guarantee that the only files that are left afterward came from the gem that was just installed with `--force`.

**Comment by karlo57** [comment]
@indirect  I'm deleting the bundle path on first run of the install process if the `--force` flag is ticked. Is this correct? And should I also delete the user's directories for instances that the user has defined a different install path?

Thanks!

https://github.com/karlo57/bundler/commit/1f1688ae8440827342f0dd54aaf1e5a7ac104470

**Comment by karlo57** [comment]
I think we should close this now? I'll create a new issue for the new bug found out.

**Comment by agis-** [comment]
@karlo57 Resolved by which commit?

**Comment by agis-** [comment]
@indirect Should we close this now that https://github.com/bundler/bundler/commit/13c445680f65293ee50f11718e8a86bfa87abd2e is merged? It's not clear if this is an issue fixed by that commit or it's a non-issue.

**Comment by indirect** [comment]
I guess it was a non-issue? Either way, seems resolved by a test now.
