### ISSUE TITLE
Errno::ENOENT: No such file or directory @ rb_file_s_stat - README.markdown

### ISSUE THREAD

**Issue by mmsayyam** [bundler/bundler#3718]
Hi
I already created this readme.markdown file but still m getting this error at bundle install. Can you help me out???

**Comment by rgb-one** [comment]
Hey could we need more information to assist you with your issue. Follow the [https://github.com/bundler/bundler/blob/master/ISSUES.md] guidelines to troubleshoot your issue. If the troubleshooting steps don't solve the problem, post the information that is asked for in this thread.

**Comment by segiddins** [comment]
This should be fixed in 1.10.3.
