### ISSUE TITLE
BUNDLED WITH meta-data may want to only include the major version

### ISSUE THREAD

**Issue by zspencer** [bundler/bundler#3719]
Let us pretend we're all very good citizens keeping our bundler up to date. Every time a new patch release comes out, our entire team does a `gem update bundler` and work merrily on our way; resulting in a single commit to bump the BUNDLED WITH meta data in the Gemfile.lock.

But now let's pretend we're not all very good citizens. We've got a Vagrant machine that's on bundler 1.10.2 and our local machine is < 1.0 and one of our team mates is on 1.10.3 and... so on and so forth.

When we commit our Gemfile.lock to VCS, we now get to see merge conflicts depending on who ran `bundle` last. (This problem is exacerbated by `spring`s habit of re-bundling all the time).

So we have a few options:

* `checkout` the change and accept the primary branch as the canonical bundler version.
* `gem update bundler` and make sure everyones on the latest version, instead of whatever version we were running before like uncouth barbarians.
* `add` the change, and engage in a good old round of fisticuffs with whomever last committed and rolled back the version.

Instead, I propose that we lock the `BUNLED WITH` in Gemfile.lock to *only* include the major version (or perhaps an independent "API version")

Admittedly this has several flaws:

* It may break backwards compatibility. I have no clue. Maybe `BUNDLED WITH` is doing something really important and my user-level understanding of `bundler` prevents me from seeing it
* It prevents team members from seeing that they need to update `bundler`. The VCS conflict is a pretty clear signal we may need to upgrade; which is a pretty reasonable response.
* It takes a suggestion of mine seriously; which will inflate my already blimp-like ego to more epic proportions; resulting in my head being mistaken for a weather balloon.

Thoughts?

**Comment by nzifnab** [comment]
Why is the `BUNDLED WITH` updating when the `Gemfile.lock` itself has not even changed? I'd say it should only update if someone's re-bundled and updated the gems.

**Comment by cjolly** [comment]
Let that weather balloon fly, @zspencer! 5 minutes in to `1.10` and one of our team member has minor version `1.10.2`, I have `1.10.3` and we're arguing in campfire about who needs to upgrade or downgrade ;)

I'm with @nzifnab (with whom I'm arguing with in campfire!) and think it should only occur when an actual change occurs in the lock.

**Comment by nzifnab** [comment]
Ok, something is really wrong here. Why it Gemfile.lock being updated just by switching branches?

        $ git status
        On branch feature-branch
        Your branch is up-to-date with 'origin/feature-branch'.
        nothing to commit, working directory clean
        $ git checkout master
        Switched to branch 'master'
        Your branch is behind 'origin/master' by 1 commit, and can be fast-forwarded.
          (use "git pull" to update your local branch)
        ruby-2.2.2@servemanager  nbenes:servemanager(master)$ git status
        On branch master
        Your branch is behind 'origin/master' by 1 commit, and can be fast-forwarded.
          (use "git pull" to update your local branch)
        Changes not staged for commit:
          (use "git add <file>..." to update what will be committed)
          (use "git checkout -- <file>..." to discard changes in working directory)

          modified:   Gemfile.lock

**Comment by zspencer** [comment]
@nzifnab + @cjolly It's likely you're switching to a branch that was bundled with a pre `1.10` version; and then `rails` + `spring` are running the `bundle` command behind the scenes, causing the Gemfile.lock to get re-generated.

**Comment by cjolly** [comment]
@zspencer yeah, we somehow missed the drama-filled thread from yesterday, too. We'll upgrade our bundlers and keep on rolling. 

Thanks for bundler everyone! I remember the days before it and it wasn't pretty!

**Comment by parndt** [comment]
See #3697 for more discussion around this

**Comment by zspencer** [comment]
Closing  because #3697 adequately addresses my concerns.

**Comment by indirect** [comment]
@zspencer thanks for writing up your concerns, and thanks for letting us know that the explanation makes sense!

**Comment by indirect** [comment]
We've continued to listen to feedback, and released additional workarounds for BUNDLED WITH pain, including a final version of Bundler 1.9, and more workarounds in 1.10.4 and 1.10.5. Read more about it [on the Bundler blog](http://bundler.io/blog/2015/06/24/version-1-10-released.html).
