### ISSUE TITLE
Configuration option to disable BUNDLED WITH?

### ISSUE THREAD

**Issue by bronson** [bundler/bundler#3720]
Hi, I'm getting really tired of having to manually remove the BUNDLED WITH from my lock files.  It's easy to forget and accidentally commit it.  And, for obvious reasons, I don't want to force everyone on my team to update the version of bundler that they're using.

Any chance of adding a configuration option to suppress BUNDLED WITH?  That way we can all be happy?

This is related to https://github.com/bundler/bundler/issues/3697 of course.  Thanks for Bundler!

**Comment by segiddins** [comment]
As a feature request, this probably belongs over on https://github.com/bundler/bundler-features.

**Comment by indirect** [comment]
@bronson feature requests do belong over on the features tracker, so I'm going to close this, but I encourage you to open a feature request over there.

**Comment by bronson** [comment]
OK.  To me this would be a fix to a pretty irritating bug but I'm happy to oblige.
