### ISSUE TITLE
Bundler inline called with bundle exec

### ISSUE THREAD

**Issue by repinel** [bundler/bundler#3721]
If you run the example provided by the [inline feature](https://github.com/bundler/bundler/pull/3440) with `bundle exec` in a project that contains a `Gemfile`, the following is displayed:

```
.rvm/gems/ruby-2.2.2@bundler-test/gems/bundler-1.10.3/lib/bundler/resolver.rb:345:in `block in verify_gemfile_dependencies_are_found!': Could not find gem 'json (>= 0) ruby' in any of the gem sources listed in your Gemfile or available on this machine. (Bundler::GemNotFound)
  from .rvm/gems/ruby-2.2.2@bundler-test/gems/bundler-1.10.3/lib/bundler/resolver.rb:323:in `each'
  from .rvm/gems/ruby-2.2.2@bundler-test/gems/bundler-1.10.3/lib/bundler/resolver.rb:323:in `verify_gemfile_dependencies_are_found!'
  from .rvm/gems/ruby-2.2.2@bundler-test/gems/bundler-1.10.3/lib/bundler/resolver.rb:198:in `start'
  from .rvm/gems/ruby-2.2.2@bundler-test/gems/bundler-1.10.3/lib/bundler/resolver.rb:182:in `resolve'
  from .rvm/gems/ruby-2.2.2@bundler-test/gems/bundler-1.10.3/lib/bundler/definition.rb:199:in `resolve'
  from .rvm/gems/ruby-2.2.2@bundler-test/gems/bundler-1.10.3/lib/bundler/definition.rb:139:in `specs'
  from .rvm/gems/ruby-2.2.2@bundler-test/gems/bundler-1.10.3/lib/bundler/definition.rb:184:in `specs_for'
  from .rvm/gems/ruby-2.2.2@bundler-test/gems/bundler-1.10.3/lib/bundler/definition.rb:173:in `requested_specs'
  from .rvm/gems/ruby-2.2.2@bundler-test/gems/bundler-1.10.3/lib/bundler/environment.rb:18:in `requested_specs'
  from .rvm/gems/ruby-2.2.2@bundler-test/gems/bundler-1.10.3/lib/bundler/runtime.rb:13:in `setup'
  from .rvm/gems/ruby-2.2.2@bundler-test/gems/bundler-1.10.3/lib/bundler/inline.rb:54:in `gemfile'
  from example.rb:5:in `<main>'
```
My gemset does have the `json` gem:

```
$ gem list json

*** LOCAL GEMS ***

json (1.8.3, 1.8.1)
```

However, the `Gemfile` does not:
```
$ bundle exec gem list json

*** LOCAL GEMS ***
```
@segiddins Would you know if that is expected?

**Comment by indirect** [comment]
The inline feature doesn't support `bundle exec`.

**Comment by repinel** [comment]
@indirect Should it be added to the documentation? Thanks

**Comment by indirect** [comment]
It sounds like you're trying to use an inline gemfile inside an application that already has a Gemfile--that doesn't make sense. Inline gemfiles are documented as usable _instead_ of a separate Gemfile, not _with_ a separate Gemfile.

I would like to fix the documentation. What made you think that inline worked with a separate Gemfile? What made you think that inline would work with bundle exec?

**Comment by repinel** [comment]
> It sounds like you're trying to use an inline gemfile inside an application that already has a Gemfile--that doesn't make sense.

Yes, you are definitely right on that, it doesn't make after all.

> Inline gemfiles are documented as usable instead of a separate Gemfile, not with a separate Gemfile.

I believe I missed that part of docs. Sorry for the confusion and thanks for the prompt replies!
