### ISSUE TITLE
IPv6 literal not recognised for http_proxy env var

### ISSUE THREAD

**Issue by mpalmer** [bundler/bundler#3725]
If an IPv6 literal is specified as the address for an HTTP proxy (such as `http_proxy=http://[2001:db8::1]:3128`) it doesn't get recognised, and bundler attempts to talk to the destination directly (which doesn't work for my network).

This appears to be much the same problem as I recently reported in rubygems/rubygems#1268.  Applying the same philosophy as indicated in rubygems/rubygems#1275 (namely, change change all calls to `proxy_uri.host` to `proxy_uri.hostname`) to `lib/bundler/vendor/net/http/persistent.rb` appears to do the trick.

**Comment by indirect** [comment]
Can you send a pull request to [net-http-persistent](https://github.com/drbrain/net-http-persistent)? We're just using the code from that gem.

**Comment by mpalmer** [comment]
I can't send a PR, I don't know enough about the constraints of that codebase to be able to form an acceptable patch.

**Comment by indirect** [comment]
Fair enough. We're unlikely to support IPv6 proxies soon, then.
