### ISSUE TITLE
Bundler won't ignore production gems in development

### ISSUE THREAD

**Issue by dt1973** [bundler/bundler#3734]
Expanding on https://github.com/bundler/bundler/issues/2341 and after having followed the recommended troubleshooting steps -- Bundler won't ignore production gems in development, even when specifying `RAILS_ENV=development bundle install`.

```
group :production do
  # This should not be installed in development
  gem "ruby-clean-css"
end
```

Using Bundler 1.10.3 with Ruby 2.2.0 on OpenBSD 5.7.

**Comment by TimMoore** [comment]
@dt1973 Bundler doesn't look at `RAILS_ENV` at all. If you want to install without the production group, run `bundle install --without production`.

There's documentation about how groups work at http://bundler.io/v1.9/groups.html

**Comment by dt1973** [comment]
Is there a way to make it look at `RAILS_ENV`?

Feels a bit redundant as I have to tell both the Gemfile and the command line that I don't want these gems in development.

**Comment by TimMoore** [comment]
Groups in Bundler are only related to Rails environments by convention, but they are entirely user defined and don't necessarily match up to environments at all. Also keep in mind that Bundler is not tied to Rails in any way and is used in a lot of contexts other than Rails apps.
