### ISSUE TITLE
Bundler 1.8.5 crashing using Rails 4.1.8, Ruby 2.2.1, and RVM

### ISSUE THREAD

**Issue by pdxrod** [bundler/bundler#3735]
――― ERROR REPORT TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――
- What did you do? - Created a new Rails 4.1.8 app, created an rvm gemset with Ruby 2.2.1p85, added browserify to the Gemfile, entered 'gem install bundler 1.8.5', and ran bundle
- What did you expect to happen? It should have installed the gems from the Gemfile in the gemset
- What happened instead? It crashed with the following message:

Error details

    Errno::EEXIST: File exists @ dir_s_mkdir - /Users/rod/.rvm/gems/ruby-2.2.1@simple_react_app/bundler
    /Users/rod/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/fileutils.rb:252:in `mkdir'
    /Users/rod/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/fileutils.rb:252:in `fu_mkdir'
    /Users/rod/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/fileutils.rb:226:in `block (2 levels) in mkdir_p'
    /Users/rod/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/fileutils.rb:224:in `reverse_each'
    /Users/rod/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/fileutils.rb:224:in `block in mkdir_p'
    /Users/rod/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/fileutils.rb:210:in `each'
    /Users/rod/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/fileutils.rb:210:in `mkdir_p'
    /Users/rod/.rvm/gems/ruby-2.2.1@simple_react_app/gems/bundler-1.8.5/lib/bundler/source/git/git_proxy.rb:83:in `copy_to'
    /Users/rod/.rvm/gems/ruby-2.2.1@simple_react_app/gems/bundler-1.8.5/lib/bundler/source/git.rb:154:in `specs'
    /Users/rod/.rvm/gems/ruby-2.2.1@simple_react_app/gems/bundler-1.8.5/lib/bundler/definition.rb:518:in `block in converge_locked_specs'
    /Users/rod/.rvm/gems/ruby-2.2.1@simple_react_app/gems/bundler-1.8.5/lib/bundler/definition.rb:507:in `each'
    /Users/rod/.rvm/gems/ruby-2.2.1@simple_react_app/gems/bundler-1.8.5/lib/bundler/definition.rb:507:in `converge_locked_specs'
    /Users/rod/.rvm/gems/ruby-2.2.1@simple_react_app/gems/bundler-1.8.5/lib/bundler/definition.rb:190:in `resolve'
    /Users/rod/.rvm/gems/ruby-2.2.1@simple_react_app/gems/bundler-1.8.5/lib/bundler/definition.rb:132:in `specs'
    /Users/rod/.rvm/gems/ruby-2.2.1@simple_react_app/gems/bundler-1.8.5/lib/bundler/definition.rb:121:in `resolve_remotely!'
    /Users/rod/.rvm/gems/ruby-2.2.1@simple_react_app/gems/bundler-1.8.5/lib/bundler/installer.rb:79:in `run'
    /Users/rod/.rvm/gems/ruby-2.2.1@simple_react_app/gems/bundler-1.8.5/lib/bundler/installer.rb:18:in `install'
    /Users/rod/.rvm/gems/ruby-2.2.1@simple_react_app/gems/bundler-1.8.5/lib/bundler/cli/install.rb:80:in `run'
    /Users/rod/.rvm/gems/ruby-2.2.1@simple_react_app/gems/bundler-1.8.5/lib/bundler/cli.rb:157:in `install'
    /Users/rod/.rvm/gems/ruby-2.2.1@simple_react_app/gems/bundler-1.8.5/lib/bundler/vendor/thor/command.rb:27:in `run'
    /Users/rod/.rvm/gems/ruby-2.2.1@simple_react_app/gems/bundler-1.8.5/lib/bundler/vendor/thor/invocation.rb:121:in `invoke_command'
    /Users/rod/.rvm/gems/ruby-2.2.1@simple_react_app/gems/bundler-1.8.5/lib/bundler/vendor/thor.rb:363:in `dispatch'
    /Users/rod/.rvm/gems/ruby-2.2.1@simple_react_app/gems/bundler-1.8.5/lib/bundler/vendor/thor/base.rb:440:in `start'
    /Users/rod/.rvm/gems/ruby-2.2.1@simple_react_app/gems/bundler-1.8.5/lib/bundler/cli.rb:10:in `start'
    /Users/rod/.rvm/gems/ruby-2.2.1@simple_react_app/gems/bundler-1.8.5/bin/bundle:20:in `block in <top (required)>'
    /Users/rod/.rvm/gems/ruby-2.2.1@simple_react_app/gems/bundler-1.8.5/lib/bundler/friendly_errors.rb:6:in `with_friendly_errors'
    /Users/rod/.rvm/gems/ruby-2.2.1@simple_react_app/gems/bundler-1.8.5/bin/bundle:18:in `<top (required)>'
    /Users/rod/.rvm/gems/ruby-2.2.1@simple_react_app/bin/bundle:23:in `load'
    /Users/rod/.rvm/gems/ruby-2.2.1@simple_react_app/bin/bundle:23:in `<main>'
    /Users/rod/.rvm/gems/ruby-2.2.1@simple_react_app/bin/ruby_executable_hooks:15:in `eval'
    /Users/rod/.rvm/gems/ruby-2.2.1@simple_react_app/bin/ruby_executable_hooks:15:in `<main>'

Environment

    Bundler   1.8.5
    Rubygems  2.4.6
    Ruby      2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin13]
    GEM_HOME  /Users/rod/.rvm/gems/ruby-2.2.1@simple_react_app
    GEM_PATH  /Users/rod/.rvm/gems/ruby-2.2.1@simple_react_app:/Users/rod/.rvm/gems/ruby-2.2.1@global
    RVM       1.26.11 (master)
    Git       1.9.5 (Apple Git-50.3)
    rubygems-bundler (1.4.4)
――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

**Comment by pdxrod** [comment]
I forgot to add. I'd cloned the gemset from another rather large one. When I recreated my new gemset for my new rails app, bundler worked fine.

**Comment by indirect** [comment]
@bundler/core looks like we need to catch EEXIST during directory creation operations.

**Comment by segiddins** [comment]
`EEXIST` should only happen on a `mkdir_p` or `mkpath` when it's a file instead of a directory

**Comment by indirect** [comment]
Totally true, but we still need to catch it to avoid throwing a backtrace.

**Comment by segiddins** [comment]
Yup, just pointing up why it's happening!
