### ISSUE TITLE
"gems that depend on each other" message is incorrect

### ISSUE THREAD

**Issue by jcoyne** [bundler/bundler#3738]
I'm running bundler 1.10.3
when I bundle update I get this message

> Your Gemfile requires gems that depend on each other, creating an infinite loop. Please remove either gem 'linkeddata' or gem 'rdf-vocab' and try again.

However, only the `rdf-vocab` gem is in my `Gemfile`.  linkeddata is in my `Gemfile.lock` though.

**Comment by indirect** [comment]
If rdf-vocab depends on linkeddata, and linkeddata depends on rdf-vocab, that's an infinite loop. The gems need to be fixed before you can use them.

**Comment by jcoyne** [comment]
My problem is the message. It says "Your Gemfile requires gems that depend on each other" but really my Gemfile only requires one of the gems. It should be rephrased to say "You have required 'rdf-vocab'  in your gemfile which has a circular dependency with 'linkeddata'".

**Comment by asymmetric** [comment]
I would argue that your Gemfile *indirectly* requires `linkeddata`, by virtue of directly requiring `rdf-vocab`, so IMHO the wording is correct.

**Comment by TimMoore** [comment]
Would it help if it said "Your Bundle requires gems..."? Having it come up with a message that's both specific and accurate is pretty tricky, because there are many different scenarios where you could run into a circular dependency. None of the gems involved are necessarily named directly in the Gemfile.

**Comment by jcoyne** [comment]
@TimMoore yes, that would be a better message

**Comment by jcoyne** [comment]
@asymmetric Technically correct yes, but not the as clear as it could be.

**Comment by TimMoore** [comment]
@jcoyne would you be able to put together a pull request to improve the message? 😄
