### ISSUE TITLE
No Block Given error

### ISSUE THREAD

**Issue by ragnarisxx** [bundler/bundler#3739]
![image](https://cloud.githubusercontent.com/assets/12847437/8111810/81fcae8a-1029-11e5-9ce4-8bbe5183cd39.png)

**Comment by ragnarisxx** [comment]
and here is my gemfile
![image](https://cloud.githubusercontent.com/assets/12847437/8111883/ea61064c-1029-11e5-9917-f9724dcabb43.png)

**Comment by indirect** [comment]
On line 6, you have to write `gem 'sqlite3', group: [:development, :test]`.

@segiddins lol how's this for an error that you didn't expect to have to catch in the DSL

**Comment by ragnarisxx** [comment]
Oh wow... What a simple mistake lol! Thanks for pointing it out!

**Comment by segiddins** [comment]
@indirect I bet you on 1.10 it has a new DSLError ;)
