### ISSUE TITLE
Yanked gems aren't updated

### ISSUE THREAD

**Issue by jcoyne** [bundler/bundler#3740]
Using bundler 1.10.3

I have a gemfile lock that has a gem linkeddata (1.1.11.1) which has been yanked. (https://rubygems.org/gems/linkeddata/versions/1.1.11.1). I do not directly specify linkeddata in my Gemfile. There is a transitive dependency on `linkeddata (~> 1.1)`

When I do `bundle update linkeddata`, it does not change the Gemfile.lock.

When I move the code to another machine and do `bundle install` it fails:
```
Could not find linkeddata-1.1.11.1 in any of the sources
```

**Comment by jcoyne** [comment]
What's worse, if I `rm Gemfile.lock` and `bundle install` it recreates the gemfile.lock with linkeddata-1.1.11.1

**Comment by jcoyne** [comment]
It has the expected behavior if I `gem uninstall linkeddata -v 1.1.11.1` then `bundle update linkeddata`

**Comment by segiddins** [comment]
Yes, that is to be expected.
