### ISSUE TITLE
About bundle exec error

### ISSUE THREAD

**Issue by ytksy** [bundler/bundler#3741]
I had a problem when I was learning Ruby on Rails with Rails tutorial(Chapter 8.2.1).
And I got the following report. 
Can you please tell me what I should do the next? 

foo@bar-PC ~/rails_project/sample_app (sign-in-out)
$ bundle exec spec/models/user_spec.rb
--- ERROR REPORT TEMPLATE ------------------------------------------------------
-
- What did you do?

  I ran the command `c:/Ruby200-x64/bin/bundle exec spec/models/user_spec.rb`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what actually happened was...

Error details

    Errno::ENOEXEC: Exec format error - spec/models/user_spec.rb
      c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/bundler-1.10.3/lib/bundler/cli/exe
c.rb:33:in `exec'
      c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/bundler-1.10.3/lib/bundler/cli/exe
c.rb:33:in `run'
      c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/bundler-1.10.3/lib/bundler/cli.rb:
274:in `exec'
      c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/bundler-1.10.3/lib/bundler/vendor/
thor/lib/thor/command.rb:27:in `run'
      c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/bundler-1.10.3/lib/bundler/vendor/
thor/lib/thor/invocation.rb:126:in `invoke_command'
      c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/bundler-1.10.3/lib/bundler/vendor/
thor/lib/thor.rb:359:in `dispatch'
      c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/bundler-1.10.3/lib/bundler/vendor/
thor/lib/thor/base.rb:440:in `start'
      c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/bundler-1.10.3/lib/bundler/cli.rb:
10:in `start'
      c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/bundler-1.10.3/bin/bundle:20:in `b
lock in <top (required)>'
      c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/bundler-1.10.3/lib/bundler/friendl
y_errors.rb:7:in `with_friendly_errors'
      c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/bundler-1.10.3/bin/bundle:18:in `<
top (required)>'
      c:/Ruby200-x64/bin/bundle:23:in `load'
      c:/Ruby200-x64/bin/bundle:23:in `<main>'

Environment
   
    Win7 Homepack SP1 
    Bundler   1.10.3
    Rubygems  2.0.14
    Ruby      2.0.0p645 (2015-04-13 revision 0) [x64-mingw32]
    GEM_HOME  c:/Ruby200-x64/lib/ruby/gems/2.0.0
    GEM_PATH  c:/Ruby200-x64/lib/ruby/gems/2.0.0;c:/Users/foo/.gem/ruby/2.0.0
    Git       1.9.5.msysgit.1

Bundler settings

    without
      Set for your local app (c:/Users/foo/rails_project/sample_app/.bundle/conf
ig): "production"
    bin_path
      Set via BUNDLE_BIN_PATH: "c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/bundler-
1.10.3/bin/bundle"
    gemfile
      Set via BUNDLE_GEMFILE: "c:/Users/foo/rails_project/sample_app/Gemfile"
--- TEMPLATE END ---------------------------------------------------------------
-

**Comment by TimMoore** [comment]
@ytksy that's a pretty unhelpful error message (that we should fix), but what it means is that the file you told it to exec (`spec/models/user_spec.rb`) is not executable. It looks like you forgot to include `rspec` as in `c:/Ruby200-x64/bin/bundle exec rspec spec/models/user_spec.rb`

**Comment by ytksy** [comment]
@TimMoore  Ahh I didn't realize i had to include rspec.
I appreciate it. Arigatou gozaimasu!
