### ISSUE TITLE
Running "bundle" command doesn't list webmock

### ISSUE THREAD

**Issue by turgs** [bundler/bundler#3748]
I can't get the *webmock* gem to work. It's listed in my Gemfile as

    group :test do
      gem 'webmock'
    end

The errors I seeing suggest the gem isn't even installed.

When I run `bundle`, I get the list of gems in use, however webmock isn't in the list!
No matter what I've tried, I can't get webmock to install. Is there something I can do?

Note: I must confess that a few weeks ago I did run `gem uninstall webmock` as I was having big issues with webmock incorrectly blocking HTTP requests when running in production mode (but that ended up being obviously my fault as I didn't have 'webmock' contained to a test group in the gemfile).

I'm sure this problem is probably a side-effect of doing that, but is there a way I can recover from it and make the world right again?

Cheers
Tim

**Comment by segiddins** [comment]
Please follow [ISSUES](https://github.com/bundler/bundler/blob/master/ISSUES.md) and provide a complete description of your environment, what you are doing, what happens, what you expect to happen instead, and why you expect that. Thanks!

**Comment by indirect** [comment]
Chances are good that you ran "bundle install --without test" at some point. Use bundle confit to check, and then delete the without setting to install everything again.

**Comment by turgs** [comment]
Fantastic. Thank you. Deleting the line out of bundle config did the trick.
