### ISSUE TITLE
Remove or disable bin/setup by default

### ISSUE THREAD

**Issue by postmodern** [bundler/bundler#3753]
It serves no real purpose for gems. Feels more like a feature for apps, not gems.

**Comment by indirect** [comment]
I'm very glad to hear that your personal gems don't need any development setup beyond bundle install. That is not true for many gems, and the bin/setup script is a deliberate effort to standardize setup across projects, gem or app.

**Comment by postmodern** [comment]
@indirect can you name more than five random gems that require a custom shell script for setup? From my experience developing gems, the majority of libraries are small and self-contained. The only libraries that might need additional setup, are C/FFI extensions that depend on libraries that may be installed from the package manager. This seems like a feature that most do not need and should not be forced upon users without their consent.

**Comment by andremedeiros** [comment]
On the top of my head, it's a common practice at GitHub.

[Linguist][1]: [script/bootstrap][2]
[Markup][3]: [script/bootstrap][4]
[task_list][5]: [script/bootstrap][6]

I'm sure if you search you'll find more.

[1]: https://github.com/github/linguist
[2]: https://github.com/github/linguist/blob/master/script/bootstrap
[3]: https://github.com/github/markup
[4]: https://github.com/github/markup/blob/master/script/bootstrap
[5]: https://github.com/github/task_list
[6]: https://github.com/github/task_list/blob/master/script/bootstrap

**Comment by postmodern** [comment]
@andreagoulet please do not prematurely close this issue. It may be a common practice at GitHub or BaseCamp, but is it a common practice among _the Ruby community_?

**Comment by indirect** [comment]
Thank you for the feedback about how you manage your gems. This change was with the consensus of the core team, in acknowledgement and support of the community trend of encapsulating setup for a project into a single script. We're going to keep it, at least for now.

**Comment by gettalong** [comment]
@postmodern Completely agree with you! Why create superfluous `bin/console` and `bin/setup` scripts? What is wrong with the good old Rakefile? It is also automatically generated, just add the setup stuff there.
