### ISSUE TITLE
Make bin/console a rake task

### ISSUE THREAD

**Issue by postmodern** [bundler/bundler#3754]
Why are we generating a `bin/console` when we already have `bundle console`. Ideally this should be moved into a rake task (see [rubygems-tasks](https://github.com/postmodern/rubygems-tasks/blob/master/lib/rubygems/tasks/console.rb)).

**Comment by indirect** [comment]
Because 'bundle console' led to requests for .consolrc led to deprecating the entire console command for 2.0. If you want a custom console command, cool. Customize bin/console. I guess rake console could possibly be a reasonable replacement, but I don't really see the benefits of moving it?

**Comment by postmodern** [comment]
The benefit would be fewer boilerplate files cluttering up the project. Ideally, a project generator should generate a skeleton, in other words, the most minimal project structure that still works.
