### ISSUE TITLE
Link to the CoC in the README

### ISSUE THREAD

**Issue by postmodern** [bundler/bundler#3755]
Instead of generating and storing the `CODE_OF_CONDUCT.txt` file in every git repository, why not simply link to it in the README?

**Comment by rgb-one** [comment]
Not quite sure what you mean. Could you elaborate?

**Comment by simi** [comment]
@rgb-one probably remove https://github.com/bundler/bundler/blob/master/CODE_OF_CONDUCT.md file and link to original CoC in the README.md file.

**Comment by segiddins** [comment]
I don't think this is something we want to do.

**Comment by postmodern** [comment]
@rgb-one @simi yep, add a hyper-link in the README to the Code of Conduct document, instead of generating it for every new gem. All Codes of Conduct eventually change, so this would eliminate the problem of having everyone update to the latest version.

**Comment by indirect** [comment]
@simi that's the Bundler code of conduct, not the code of conduct that's included with new gems if you opt in. We're not going to remove that one, and there is no "original". It's specifically written for this project.

@postmodern no, we're not going to remove the file. If you opt in during gem generation, that's the CoC you're establishing for your project. Pointing only to a URL means that it can disappear or change without notice, which is the exact opposite of what you want for a CoC.
