### ISSUE TITLE
Network s unreachable

### ISSUE THREAD

**Issue by vipul2690** [bundler/bundler#3765]
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `/home/vipul/.rvm/gems/ruby-2.2.0/bin/bundle install`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what actually happened was...

Error details

    Errno::ENETUNREACH: Network is unreachable - connect(2) for "rubygems.org" port 443
      /home/vipul/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/net/http.rb:879:in `initialize'
      /home/vipul/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/net/http.rb:879:in `open'
      /home/vipul/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'
      /home/vipul/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/timeout.rb:74:in `timeout'
      /home/vipul/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/net/http.rb:878:in `connect'
      /home/vipul/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/net/http.rb:1456:in `begin_transport'
      /home/vipul/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/net/http.rb:1409:in `transport_request'
      /home/vipul/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/net/http.rb:1383:in `request'
      /home/vipul/.rvm/gems/ruby-2.2.0/gems/bundler-1.10.4/lib/bundler/vendor/net/http/persistent.rb:999:in `request'
      /home/vipul/.rvm/gems/ruby-2.2.0/gems/bundler-1.10.4/lib/bundler/fetcher/downloader.rb:45:in `request'
      /home/vipul/.rvm/gems/ruby-2.2.0/gems/bundler-1.10.4/lib/bundler/fetcher/downloader.rb:15:in `fetch'
      /home/vipul/.rvm/gems/ruby-2.2.0/gems/bundler-1.10.4/lib/bundler/fetcher.rb:87:in `fetch_spec'
      /home/vipul/.rvm/gems/ruby-2.2.0/gems/bundler-1.10.4/lib/bundler/remote_specification.rb:46:in `_remote_specification'
      /home/vipul/.rvm/gems/ruby-2.2.0/gems/bundler-1.10.4/lib/bundler/remote_specification.rb:51:in `method_missing'
      /home/vipul/.rvm/gems/ruby-2.2.0/gems/bundler-1.10.4/lib/bundler/spec_set.rb:148:in `tsort_each_child'
      /home/vipul/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:413:in `call'
      /home/vipul/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:413:in `each_strongly_connected_component_from'
      /home/vipul/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:419:in `block in each_strongly_connected_component_from'
      /home/vipul/.rvm/gems/ruby-2.2.0/gems/bundler-1.10.4/lib/bundler/spec_set.rb:150:in `block (2 levels) in tsort_each_child'
      /home/vipul/.rvm/gems/ruby-2.2.0/gems/bundler-1.10.4/lib/bundler/spec_set.rb:150:in `each'
      /home/vipul/.rvm/gems/ruby-2.2.0/gems/bundler-1.10.4/lib/bundler/spec_set.rb:150:in `block in tsort_each_child'
      /home/vipul/.rvm/gems/ruby-2.2.0/gems/bundler-1.10.4/lib/bundler/spec_set.rb:148:in `each'
      /home/vipul/.rvm/gems/ruby-2.2.0/gems/bundler-1.10.4/lib/bundler/spec_set.rb:148:in `tsort_each_child'
      /home/vipul/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:413:in `call'
      /home/vipul/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:413:in `each_strongly_connected_component_from'
      /home/vipul/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
      /home/vipul/.rvm/gems/ruby-2.2.0/gems/bundler-1.10.4/lib/bundler/spec_set.rb:144:in `block in tsort_each_node'
      /home/vipul/.rvm/gems/ruby-2.2.0/gems/bundler-1.10.4/lib/bundler/spec_set.rb:144:in `each'
      /home/vipul/.rvm/gems/ruby-2.2.0/gems/bundler-1.10.4/lib/bundler/spec_set.rb:144:in `tsort_each_node'
      /home/vipul/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:345:in `call'
      /home/vipul/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
      /home/vipul/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
      /home/vipul/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:174:in `each'
      /home/vipul/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:174:in `to_a'
      /home/vipul/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:174:in `tsort'
      /home/vipul/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:150:in `tsort'
      /home/vipul/.rvm/gems/ruby-2.2.0/gems/bundler-1.10.4/lib/bundler/spec_set.rb:113:in `sorted'
      /home/vipul/.rvm/gems/ruby-2.2.0/gems/bundler-1.10.4/lib/bundler/installer.rb:265:in `install_sequentially'
      /home/vipul/.rvm/gems/ruby-2.2.0/gems/bundler-1.10.4/lib/bundler/installer.rb:93:in `run'
      /home/vipul/.rvm/gems/ruby-2.2.0/gems/bundler-1.10.4/lib/bundler/installer.rb:18:in `install'
      /home/vipul/.rvm/gems/ruby-2.2.0/gems/bundler-1.10.4/lib/bundler/cli/install.rb:107:in `run'
      /home/vipul/.rvm/gems/ruby-2.2.0/gems/bundler-1.10.4/lib/bundler/cli.rb:162:in `install'
      /home/vipul/.rvm/gems/ruby-2.2.0/gems/bundler-1.10.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /home/vipul/.rvm/gems/ruby-2.2.0/gems/bundler-1.10.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /home/vipul/.rvm/gems/ruby-2.2.0/gems/bundler-1.10.4/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /home/vipul/.rvm/gems/ruby-2.2.0/gems/bundler-1.10.4/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /home/vipul/.rvm/gems/ruby-2.2.0/gems/bundler-1.10.4/lib/bundler/cli.rb:10:in `start'
      /home/vipul/.rvm/gems/ruby-2.2.0/gems/bundler-1.10.4/bin/bundle:20:in `block in <top (required)>'
      /home/vipul/.rvm/gems/ruby-2.2.0/gems/bundler-1.10.4/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
      /home/vipul/.rvm/gems/ruby-2.2.0/gems/bundler-1.10.4/bin/bundle:18:in `<top (required)>'
      /home/vipul/.rvm/gems/ruby-2.2.0/bin/bundle:23:in `load'
      /home/vipul/.rvm/gems/ruby-2.2.0/bin/bundle:23:in `<main>'

Environment

    Bundler   1.10.4
    Rubygems  2.4.5
    Ruby      2.2.0p0 (2014-12-25 revision 49005) [i686-linux]
    GEM_HOME  /home/vipul/.rvm/gems/ruby-2.2.0
    GEM_PATH  /home/vipul/.rvm/gems/ruby-2.2.0:/home/vipul/.rvm/gems/ruby-2.2.0@global
    RVM       1.26.11 (latest)
    Git       1.7.9.5

**Comment by indirect** [comment]
Thanks for reporting this. We should start catching this exception and reporting that the network was unreachable in an error message.

**Comment by steverob** [comment]
@indirect opened a PR #3771 that adds `Errno::ENETUNREACH` to the `HTTP_ERRORS` array. Would this be enough to handle this?

**Comment by indirect** [comment]
Closing as fixed since #3771 is merged.
