### ISSUE TITLE
Bundler.setup does not give user friendly errors and custom groups

### ISSUE THREAD

**Issue by habibalamin** [bundler/bundler#3770]
You can require 'bundler/setup' to get a friendly error for GemNotFound. However, you can't supply groups. I have a PR for this already (which I will reference this from), so you can see what I'm talking about.

I have a few failing tests which I'm stuck on, though.

(Also, this is a separate issue, but even just calling Bundler.setup myself with a custom group, it gives me a GemNotFound error for a gem in a group I haven't included.)

**Comment by indirect** [comment]
Thanks for opening this issue! And thank you for the PR. It's great to see someone working on solving their own issues already. :)

Can you describe why you want to be able to get friendly errors while calling `Bundler.setup`? Or the other way around, can you describe why you want to be able to call `setup` with specific groups instead of just `require 'bundler/setup'`?

This request implies that you are choosing not to skip installing gems with `bundle install --without GROUP`, but you still want to keep the gems in GROUP from being added to the load path. What problem are you trying to solve with that solution?

Thanks!

**Comment by habibalamin** [comment]
Well, I want friendly errors, because non-friendly errors don't look as nice. I'd rather be told in red text that a gem is missing, rather than seeing a backtrace for it. It's not a massive issue, just a nicety. :)

As for groups, I prefer the opt-in nature of the setup command, rather than the opt-out nature of the `--without` flag. I want to be able to `Bundler.setup :default, ENV['RACK_ENV']` )or possibly `Bundler.setup *MyApp.groups(assets: %w[development test])` a la Rails) *and* get friendly errors at the same time.

**Comment by indirect** [comment]
Well, Rails does in fact `require 'bundler/setup'`, so I'm still not totally clear on what you're trying to do. You _have_ to opt out with `--without` if you don't want the gems to be installed. If you wait to opt out until you are calling `Bundler.setup`, the gems are already installed, and at that point I don't understand why you care if they are on the load path or not.

**Comment by habibalamin** [comment]
Sorry, I've updated my comment a few times (because I never get it right first time). Yes, I know Rails does require the setup file, but they go on to use `Bundler.require` in a similar way to how I used `Bundler.setup` there.

Yes, now that you mention it, why does it matter if they're on the load path when they're already installed anyway? That's a fair point, I guess I'd prefer an opt-in version of the `--without` flag then, maybe something like `--only`, which is a completely different issue and one I haven't written anything for.

**Comment by indirect** [comment]
We just added `--only`, check out the docs for the newest version of Bundler. :)

**Comment by indirect** [comment]
(Well, we added optional groups and a --with flag. It's similar. If it doesn't satisfy your use-case, let us know!)

**Comment by habibalamin** [comment]
Haha, awesome. I guess we can close this, then. :grinning:.
