### ISSUE TITLE
Bug With ruby2.2.0:/usr/local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- md5 (LoadError)

### ISSUE THREAD

**Issue by beruhan** [bundler/bundler#3778]
when I setup whatweb on Ubuntu14.04,it's install successfully,but when I used it,I get error:
```
~$ whatweb www.google.cn
/usr/local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- md5 (LoadError)
	from /usr/local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/bin/whatweb:55:in `<main>
```

I don't know how to dealwith it,I need help

**Comment by indirect** [comment]
Hi, and thanks for reporting this! Unfortunately, this tracker is for bugs in Bundler, and the error that you are seeing has nothing to do with Bundler. Since the error is coming from whatweb, I suggest opening a ticket on the whatweb tracker instead.
