### ISSUE TITLE
Bundle install gives me error

### ISSUE THREAD

**Issue by bgvo** [bundler/bundler#3780]
- What did you do?

  I ran the command `/Users/borjagvo/.rbenv/versions/2.1.2/bin/bundle install`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what actually happened was...

Error details

    Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /Users/borjagvo/.rbenv/versions/2.1.2/bin/ruby extconf.rb
checking if the C compiler accepts ... yes
checking if the C compiler accepts -Wno-error=unused-command-line-argument-hard-error-in-future... no
Building nokogiri using packaged libraries.
checking for iconv... yes
************************************************************************
IMPORTANT NOTICE:

Buidling Nokogiri with a packaged version of libxml2-2.9.2.

Team Nokogiri will keep on doing their best to provide security
updates in a timely manner, but if this is a concern for you and want
to use the system library instead; abort this installation process and
reinstall nokogiri as follows:

    gem install nokogiri -- --use-system-libraries
  [--with-xml2-config=/path/to/xml2-config]
  [--with-xslt-config=/path/to/xslt-config]

If you are using Bundler, tell it to use the option:

    bundle config build.nokogiri --use-system-libraries
    bundle install

Note, however, that nokogiri is not fully compatible with arbitrary
versions of libxml2 provided by OS/package vendors.
************************************************************************
Extracting libxml2-2.9.2.tar.gz into tmp/x86_64-apple-darwin14.3.0/ports/libxml2/2.9.2... OK
Running 'compile' for libxml2 2.9.2... ERROR, review '/Users/borjagvo/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/nokogiri-1.6.4.1/ext/nokogiri/tmp/x86_64-apple-darwin14.3.0/ports/libxml2/2.9.2/compile.log' to see what happened.
/Users/borjagvo/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/mini_portile-0.6.2/lib/mini_portile.rb:279:in `block in execute': Failed to complete compile task (RuntimeError)
	from /Users/borjagvo/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/mini_portile-0.6.2/lib/mini_portile.rb:271:in `chdir'
	from /Users/borjagvo/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/mini_portile-0.6.2/lib/mini_portile.rb:271:in `execute'
	from /Users/borjagvo/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/mini_portile-0.6.2/lib/mini_portile.rb:70:in `compile'
	from /Users/borjagvo/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/mini_portile-0.6.2/lib/mini_portile.rb:110:in `cook'
	from extconf.rb:268:in `block in process_recipe'
	from extconf.rb:167:in `tap'
	from extconf.rb:167:in `process_recipe'
	from extconf.rb:455:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /Users/borjagvo/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/nokogiri-1.6.4.1 for inspection.
Results logged to /Users/borjagvo/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/extensions/x86_64-darwin-14/2.1.0-static/nokogiri-1.6.4.1/gem_make.out

      /Users/borjagvo/.rbenv/versions/2.1.2/lib/ruby/2.1.0/rubygems/ext/builder.rb:89:in `run'
      /Users/borjagvo/.rbenv/versions/2.1.2/lib/ruby/2.1.0/rubygems/ext/ext_conf_builder.rb:38:in `block in build'
      /Users/borjagvo/.rbenv/versions/2.1.2/lib/ruby/2.1.0/tempfile.rb:324:in `open'
      /Users/borjagvo/.rbenv/versions/2.1.2/lib/ruby/2.1.0/rubygems/ext/ext_conf_builder.rb:17:in `build'
      /Users/borjagvo/.rbenv/versions/2.1.2/lib/ruby/2.1.0/rubygems/ext/builder.rb:161:in `block (2 levels) in build_extension'
      /Users/borjagvo/.rbenv/versions/2.1.2/lib/ruby/2.1.0/rubygems/ext/builder.rb:160:in `chdir'
      /Users/borjagvo/.rbenv/versions/2.1.2/lib/ruby/2.1.0/rubygems/ext/builder.rb:160:in `block in build_extension'
      /Users/borjagvo/.rbenv/versions/2.1.2/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
      /Users/borjagvo/.rbenv/versions/2.1.2/lib/ruby/2.1.0/rubygems/ext/builder.rb:159:in `build_extension'
      /Users/borjagvo/.rbenv/versions/2.1.2/lib/ruby/2.1.0/rubygems/ext/builder.rb:198:in `block in build_extensions'
      /Users/borjagvo/.rbenv/versions/2.1.2/lib/ruby/2.1.0/rubygems/ext/builder.rb:195:in `each'
      /Users/borjagvo/.rbenv/versions/2.1.2/lib/ruby/2.1.0/rubygems/ext/builder.rb:195:in `build_extensions'
      /Users/borjagvo/.rbenv/versions/2.1.2/lib/ruby/2.1.0/rubygems/specification.rb:1436:in `block in build_extensions'
      /Users/borjagvo/.rbenv/versions/2.1.2/lib/ruby/2.1.0/rubygems/user_interaction.rb:45:in `use_ui'
      /Users/borjagvo/.rbenv/versions/2.1.2/lib/ruby/2.1.0/rubygems/specification.rb:1434:in `build_extensions'
      /Users/borjagvo/.rbenv/versions/2.1.2/lib/ruby/2.1.0/rubygems/stub_specification.rb:60:in `build_extensions'
      /Users/borjagvo/.rbenv/versions/2.1.2/lib/ruby/2.1.0/rubygems/basic_specification.rb:56:in `contains_requirable_file?'
      /Users/borjagvo/.rbenv/versions/2.1.2/lib/ruby/2.1.0/rubygems/specification.rb:925:in `block in find_inactive_by_path'
      /Users/borjagvo/.rbenv/versions/2.1.2/lib/ruby/2.1.0/rubygems/specification.rb:924:in `each'
      /Users/borjagvo/.rbenv/versions/2.1.2/lib/ruby/2.1.0/rubygems/specification.rb:924:in `find'
      /Users/borjagvo/.rbenv/versions/2.1.2/lib/ruby/2.1.0/rubygems/specification.rb:924:in `find_inactive_by_path'
      /Users/borjagvo/.rbenv/versions/2.1.2/lib/ruby/2.1.0/rubygems.rb:185:in `try_activate'
      /Users/borjagvo/.rbenv/versions/2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:132:in `rescue in require'
      /Users/borjagvo/.rbenv/versions/2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:144:in `require'
      /Users/borjagvo/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.10.4/lib/bundler/vendor/net/http/persistent.rb:12:in `<top (required)>'
      /Users/borjagvo/.rbenv/versions/2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
      /Users/borjagvo/.rbenv/versions/2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
      /Users/borjagvo/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.10.4/lib/bundler/vendored_persistent.rb:11:in `<top (required)>'
      /Users/borjagvo/.rbenv/versions/2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
      /Users/borjagvo/.rbenv/versions/2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
      /Users/borjagvo/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.10.4/lib/bundler/fetcher.rb:1:in `<top (required)>'
      /Users/borjagvo/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.10.4/lib/bundler/cli/install.rb:98:in `run'
      /Users/borjagvo/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.10.4/lib/bundler/cli.rb:162:in `install'
      /Users/borjagvo/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.10.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /Users/borjagvo/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.10.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /Users/borjagvo/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.10.4/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /Users/borjagvo/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.10.4/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /Users/borjagvo/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.10.4/lib/bundler/cli.rb:10:in `start'
      /Users/borjagvo/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.10.4/bin/bundle:20:in `block in <top (required)>'
      /Users/borjagvo/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.10.4/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
      /Users/borjagvo/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.10.4/bin/bundle:18:in `<top (required)>'
      /Users/borjagvo/.rbenv/versions/2.1.2/bin/bundle:23:in `load'
      /Users/borjagvo/.rbenv/versions/2.1.2/bin/bundle:23:in `<main>'

Environment

    Bundler   1.10.4
    Rubygems  2.2.2
    Ruby      2.1.2p95 (2014-05-08 revision 45877) [x86_64-darwin14.0]
    Git       2.4.4

Bundler settings

    gem.mit
      Set for the current user (/Users/borjagvo/.bundle/config): "0"
    gem.test
      Set for the current user (/Users/borjagvo/.bundle/config): "minitest"
    path
      Set for your local app (/Users/borjagvo/MyStuff/Work/Gemfeed/dev/repos/api/.bundle/config): "/Users/borjagvo/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler"
    disable_shared_gems
      Set for your local app (/Users/borjagvo/MyStuff/Work/Gemfeed/dev/repos/api/.bundle/config): "1"

**Comment by segiddins** [comment]
What's the contents of /Users/borjagvo/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/nokogiri-1.6.4.1/ext/nokogiri/tmp/x86_64-apple-darwin14.3.0/ports/libxml2/2.9.2/compile.log ?

This is likely more of a RubyGems / Nokogiri issue than a bundler one.

**Comment by bgvo** [comment]
Borjas-MacBook-Pro:api borjagvo$ cat /Users/borjagvo/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/nokogiri-1.6.4.1/ext/nokogiri/tmp/x86_64-apple-darwin14.3.0/    ports/libxml2/2.9.2/compile.log
    /Applications/Xcode.app/Contents/Developer/usr/bin/make  all-recursive
    Making all in include
    Making all in libxml
    cd ../.. && /bin/sh ./config.status include/libxml/xmlversion.h
    config.status: creating include/libxml/xmlversion.h
    make[3]: Nothing to be done for `all-am'.
    Making all in .
      CC       SAX.lo
    /bin/sh: ./libtool: No such file or directory
    make[2]: *** [SAX.lo] Error 127
    make[1]: *** [all-recursive] Error 1
    make: *** [all] Error 2

**Comment by segiddins** [comment]
Ok then, this is definitely not a bundler error then.
