### ISSUE TITLE
new issue

### ISSUE THREAD

**Issue by veni011** [bundler/bundler#3782]
――― ERROR REPORT TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――
- What did you do?
- What did you expect to happen?
- What happened instead?

Error details

    LocalJumpError: no block given (yield)
    /usr/local/rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/dsl.rb:166:in `group'
    /home/ubuntu/workspace/hello_app/Gemfile:23:in `eval_gemfile'
    /usr/local/rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/dsl.rb:32:in `instance_eval'
    /usr/local/rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/dsl.rb:32:in `eval_gemfile'
    /usr/local/rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/dsl.rb:10:in `evaluate'
    /usr/local/rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/definition.rb:25:in `build'
    /usr/local/rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler.rb:155:in `definition'
    /usr/local/rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/cli/install.rb:78:in `run'
    /usr/local/rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/cli.rb:157:in `install'
    /usr/local/rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/vendor/thor/command.rb:27:in `run'
    /usr/local/rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/vendor/thor/invocation.rb:121:in `invoke_command'
    /usr/local/rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/vendor/thor.rb:363:in `dispatch'
    /usr/local/rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/vendor/thor/base.rb:440:in `start'
    /usr/local/rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/cli.rb:10:in `start'
    /usr/local/rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/bin/bundle:20:in `block in <top (required)>'
    /usr/local/rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/friendly_errors.rb:6:in `with_friendly_errors'
    /usr/local/rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/bin/bundle:18:in `<top (required)>'
    /usr/local/rvm/gems/ruby-2.2.1@global/bin/bundle:23:in `load'
    /usr/local/rvm/gems/ruby-2.2.1@global/bin/bundle:23:in `<main>'
    /usr/local/rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
    /usr/local/rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'

Environment

    Bundler   1.8.4
    Rubygems  2.4.6
    Ruby      2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]
    GEM_HOME  /usr/local/rvm/gems/ruby-2.2.1
    GEM_PATH  /usr/local/rvm/gems/ruby-2.2.1:/usr/local/rvm/gems/ruby-2.2.1@global
    RVM       1.26.11 (latest)
    Git       1.9.1
    rubygems-bundler (1.4.4)

Bundler settings

    without
      Set for your local app (/home/ubuntu/workspace/hello_app/.bundle/config): "production"
      Set for the current user (/home/ubuntu/.bundle/config): "production"
――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

**Comment by indirect** [comment]
Your gemfile contains a call to the “group” method without a “do” block.

Also, your copy of Bundler is many months old. Please run `gem install bundler` to get a newer version of Bundler with a better error message for this problem.

**Comment by veni011** [comment]
Error created while attempting to link to link to Heroku. However, setup was created within a GemFile adding new Gems: 

group :production do
gem 'pg' '0.17.1'
gem 'rails_12factor' '0.0.2'
end

**Comment by veni011** [comment]
many thanks!! I will do!! : ) Cheers!!
