### ISSUE TITLE
Gemfile friendly error should allow ruby requirement exceptions

### ISSUE THREAD

**Issue by indirect** [bundler/bundler#3783]
The new friendly Gemfile error handler mistakenly treats exceptions raised from the Ruby version checker as if they are syntax errors or something similar:

```
[!] There was an error parsing `Gemfile`: ruby_version must match the :engine_version for MRI. Bundler cannot continue.
 #  from /home/travis/build/bundler/bundler/tmp/bundled_app/Gemfile:2
 #  -------------------------------------------
 #  source "file:///home/travis/build/bundler/bundler/tmp/gems/remote1"
 >  ruby "1.8.7", :engine => 'ruby', :engine_version => '1.2.4'
 #  
 #  -------------------------------------------
```

This happens during the spec named "raises an error if engine version doesn't match ruby version for MRI", among others.

Instead, we should simply treat the exception as a normal friendly error, and print the message out in red and exit non-zero.

**Comment by segiddins** [comment]
@indirect it only does so for the exceptions raised in `RubyDsl#ruby` directly -- validation done in the definition isn't caught by the DSL error.

**Comment by indirect** [comment]
Right... this ticket is about the fact that we have some errors that should be able to pass through the DSL error catcher.

**Comment by segiddins** [comment]
I guess I just disagree, since those issues are gundementally misuses of the DSL? Why not point out the line that has the issue when we know that info?

**Comment by indirect** [comment]
Pointing out the line seems great, the weird part is "There was an error parsing `Gemfile`". It wasn't a parsing error, it was a constraint violation in a Gemfile that is syntactically valid. So we either need a second DSL error mode for "not a parse error but a runtime error", or just pass those errors through.

**Comment by segiddins** [comment]
`There was an error evaluating Gemfile` ?

**Comment by indirect** [comment]
Yeah, that seems reasonable to me. I'm ultimately hoping to make it clear that the error "you put a ruby version and an engine version that conflict" is a different kind of error than "you have a typo in your Gemfile and we can't parse it".
