### ISSUE TITLE
Bundler says the bundle is ok but can't actually do anything with it

### ISSUE THREAD

**Issue by mauricio** [bundler/bundler#3787]
So, I have a very weird issue here that I can't easily reproduce.

I have an ubuntu 12.04 machine that had ruby 2.2.2 built in a separate path and linked to `/opt/default-ruby` and it includes the latest bundler (1.10.5). This machine runs an simple program and I use chef to set it up with the deployment bundle and everything, but when I try to actually run the code it fails.

If I ask bundler what's up with the bundle, it says it's all fine:

```
ubuntu@ip:/opt/bluecopper/current$ /opt/default-ruby/bundle check
fatal: Not a git repository (or any of the parent directories): .git
The Gemfile's dependencies are satisfied
```

And:

```
ubuntu@ip:/opt/bluecopper/current$ /opt/default-ruby/bundle list
fatal: Not a git repository (or any of the parent directories): .git
Gems included by the bundle:
  * aws-sdk-v1 (1.64.0)
  * bluecopper (0.1.0)
  * bundler (1.10.5)
  * dotenv (2.0.2)
  * json (1.8.3)
  * mini_portile (0.6.2)
  * multi_json (1.11.1)
  * nokogiri (1.6.6.2)
  * rollbar (1.5.3)
  * thor (0.19.1)
```

But when I call exec, the issue shows up:

```
ubuntu@ip:/opt/bluecopper/current$ /opt/default-ruby/ruby -S bundle exec bluecopper start -c app-config.yml 
fatal: Not a git repository (or any of the parent directories): .git
Could not find json-1.8.3 in any of the sources
Run `bundle install` to install missing gems.
```

Any idea what this could be and how I could troubleshoot or provide more info?

The local `.bundle/config` file is:

```
---
BUNDLE_FROZEN: '1'
BUNDLE_PATH: "/opt/bluecopper/shared/bundle"
BUNDLE_WITHOUT: development:test
BUNDLE_DISABLE_SHARED_GEMS: '1'
```

**Comment by indirect** [comment]
It sounds like maybe `/opt/default-ruby/bundle` doesn't actually use `/opt/default-ruby/ruby`. Is that true?

**Comment by mauricio** [comment]
the shebang seems to indicate it does use it:

```ruby
#!/usr/local/ruby/2.2.2/bin/ruby
#
# This file was generated by RubyGems.
#
# The application 'bundler' is installed as part of a gem, and
# this file is here to facilitate running it.
#

require 'rubygems'

version = ">= 0"

if ARGV.first
  str = ARGV.first
  str = str.dup.force_encoding("BINARY") if str.respond_to? :force_encoding
  if str =~ /\A_(.*)_\z/ and Gem::Version.correct?($1) then
    version = $1
    ARGV.shift
  end
end

gem 'bundler', version
load Gem.bin_path('bundler', 'bundle', version)
```

And:

```
ubuntu@ip:/opt/bluecopper/current$ ls -l /opt/default-ruby
lrwxrwxrwx 1 root root 25 Jun 25 19:39 /opt/default-ruby -> /usr/local/ruby/2.2.2/bin
```

I've also tried to call it with `/opt/default-ruby/ruby -S bundle` and it still breaks.

**Comment by indirect** [comment]
Okay. Try the troubleshooting steps in [ISSUES](https://github.com/bundler/bundler/blob/master/ISSUES.md), and if that doesn't help, try `bundle show json`, and check up on the files in the path that gets printed.

**Comment by TimMoore** [comment]
Also could you check the shebang for `bluecopper`? It could be invoking a different version of Ruby.

**Comment by mauricio** [comment]
@TimMoore right on target!

The shebang for the `bluecopper` command was using `/usr/bin/env ruby` and picking up the system ruby, not a bundler issue, thanks everyone!
