### ISSUE TITLE
Bundle Update crashes

### ISSUE THREAD

**Issue by xsmaster** [bundler/bundler#3789]
I tryed to update my bundle

My Gemfile:

source 'https://rubygems.org'

gem 'rest-client'
gem 'json'

Bundle show:

Gems included by the bundle:
  * bundler (1.10.4)
  * domain_name (0.5.24)
  * http-cookie (1.0.2)
  * json (1.8.3)
  * mime-types (2.6.1)
  * netrc (0.10.3)
  * rest-client (1.8.0)
  * unf (0.1.4)
  * unf_ext (0.0.7.1)

- What did you do?

  I ran the command `/Users/USER_NAME/.rvm/gems/ruby-2.2.1/bin/bundle update`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what actually happened was...

Error details

    NoMethodError: undefined method `dump' for nil:NilClass
      /Users/USER_NAME/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http/response.rb:119:in `error!'
      /Users/USER_NAME/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http/response.rb:128:in `value'
      /Users/USER_NAME/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:915:in `connect'
      /Users/USER_NAME/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
      /Users/USER_NAME/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:858:in `start'
      /Users/USER_NAME/.rvm/gems/ruby-2.2.1/gems/bundler-1.10.4/lib/bundler/vendor/net/http/persistent.rb:700:in `start'
      /Users/USER_NAME/.rvm/gems/ruby-2.2.1/gems/bundler-1.10.4/lib/bundler/vendor/net/http/persistent.rb:631:in `connection_for'
      /Users/USER_NAME/.rvm/gems/ruby-2.2.1/gems/bundler-1.10.4/lib/bundler/vendor/net/http/persistent.rb:994:in `request'
      /Users/USER_NAME/.rvm/gems/ruby-2.2.1/gems/bundler-1.10.4/lib/bundler/fetcher/downloader.rb:45:in `request'
      /Users/USER_NAME/.rvm/gems/ruby-2.2.1/gems/bundler-1.10.4/lib/bundler/fetcher/downloader.rb:15:in `fetch'
      /Users/USER_NAME/.rvm/gems/ruby-2.2.1/gems/bundler-1.10.4/lib/bundler/fetcher/dependency.rb:7:in `api_available?'
      /Users/USER_NAME/.rvm/gems/ruby-2.2.1/gems/bundler-1.10.4/lib/bundler/fetcher.rb:135:in `block in use_api'
      /Users/USER_NAME/.rvm/gems/ruby-2.2.1/gems/bundler-1.10.4/lib/bundler/fetcher.rb:135:in `reject!'
      /Users/USER_NAME/.rvm/gems/ruby-2.2.1/gems/bundler-1.10.4/lib/bundler/fetcher.rb:135:in `use_api'
      /Users/USER_NAME/.rvm/gems/ruby-2.2.1/gems/bundler-1.10.4/lib/bundler/source/rubygems.rb:320:in `select'
      /Users/USER_NAME/.rvm/gems/ruby-2.2.1/gems/bundler-1.10.4/lib/bundler/source/rubygems.rb:320:in `api_fetchers'
      /Users/USER_NAME/.rvm/gems/ruby-2.2.1/gems/bundler-1.10.4/lib/bundler/source/rubygems.rb:325:in `block in remote_specs'
      /Users/USER_NAME/.rvm/gems/ruby-2.2.1/gems/bundler-1.10.4/lib/bundler/index.rb:9:in `build'
      /Users/USER_NAME/.rvm/gems/ruby-2.2.1/gems/bundler-1.10.4/lib/bundler/source/rubygems.rb:324:in `remote_specs'
      /Users/USER_NAME/.rvm/gems/ruby-2.2.1/gems/bundler-1.10.4/lib/bundler/source/rubygems.rb:81:in `specs'
      /Users/USER_NAME/.rvm/gems/ruby-2.2.1/gems/bundler-1.10.4/lib/bundler/definition.rb:211:in `block (2 levels) in index'
      /Users/USER_NAME/.rvm/gems/ruby-2.2.1/gems/bundler-1.10.4/lib/bundler/definition.rb:209:in `each'
      /Users/USER_NAME/.rvm/gems/ruby-2.2.1/gems/bundler-1.10.4/lib/bundler/definition.rb:209:in `block in index'
      /Users/USER_NAME/.rvm/gems/ruby-2.2.1/gems/bundler-1.10.4/lib/bundler/index.rb:9:in `build'
      /Users/USER_NAME/.rvm/gems/ruby-2.2.1/gems/bundler-1.10.4/lib/bundler/definition.rb:206:in `index'
      /Users/USER_NAME/.rvm/gems/ruby-2.2.1/gems/bundler-1.10.4/lib/bundler/definition.rb:200:in `resolve'
      /Users/USER_NAME/.rvm/gems/ruby-2.2.1/gems/bundler-1.10.4/lib/bundler/definition.rb:140:in `specs'
      /Users/USER_NAME/.rvm/gems/ruby-2.2.1/gems/bundler-1.10.4/lib/bundler/definition.rb:129:in `resolve_remotely!'
      /Users/USER_NAME/.rvm/gems/ruby-2.2.1/gems/bundler-1.10.4/lib/bundler/installer.rb:79:in `run'
      /Users/USER_NAME/.rvm/gems/ruby-2.2.1/gems/bundler-1.10.4/lib/bundler/installer.rb:18:in `install'
      /Users/USER_NAME/.rvm/gems/ruby-2.2.1/gems/bundler-1.10.4/lib/bundler/cli/update.rb:51:in `run'
      /Users/USER_NAME/.rvm/gems/ruby-2.2.1/gems/bundler-1.10.4/lib/bundler/cli.rb:187:in `update'
      /Users/USER_NAME/.rvm/gems/ruby-2.2.1/gems/bundler-1.10.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /Users/USER_NAME/.rvm/gems/ruby-2.2.1/gems/bundler-1.10.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /Users/USER_NAME/.rvm/gems/ruby-2.2.1/gems/bundler-1.10.4/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /Users/USER_NAME/.rvm/gems/ruby-2.2.1/gems/bundler-1.10.4/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /Users/USER_NAME/.rvm/gems/ruby-2.2.1/gems/bundler-1.10.4/lib/bundler/cli.rb:10:in `start'
      /Users/USER_NAME/.rvm/gems/ruby-2.2.1/gems/bundler-1.10.4/bin/bundle:20:in `block in <top (required)>'
      /Users/USER_NAME/.rvm/gems/ruby-2.2.1/gems/bundler-1.10.4/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
      /Users/USER_NAME/.rvm/gems/ruby-2.2.1/gems/bundler-1.10.4/bin/bundle:18:in `<top (required)>'
      /Users/USER_NAME/.rvm/gems/ruby-2.2.1/bin/bundle:23:in `load'
      /Users/USER_NAME/.rvm/gems/ruby-2.2.1/bin/bundle:23:in `<top (required)>'
      -e:1:in `load'
      -e:1:in `<main>'

Environment

    Bundler   1.10.4
    Rubygems  2.4.6
    Ruby      2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]
    GEM_HOME  /Users/USER_NAME/.rvm/gems/ruby-2.2.1
    GEM_PATH  /Users/USER_NAME/.rvm/gems/ruby-2.2.1:/Users/USER_NAME/.rvm/gems/ruby-2.2.1@global
    RVM       1.26.11 (latest)
    Git       2.3.2 (Apple Git-55)
    rubygems-bundler (1.4.4)

**Comment by indirect** [comment]
Hi there! The backtrace points to the net/http library, which is part of Ruby. Perhaps you need to upgrade to the latest version of Ruby, 2.2.2? If it still doesn't work for you, please include the output of `bundle env`. Thanks!

**Comment by xsmaster** [comment]
@indirect - To follow up on this. I had my proxy turned on and it was blocking outbound connections. Sorry for raising a bug for user error. Killer stack track tho. :) Thanks for your help and support.
