### ISSUE TITLE
OpenSSL::X509::StoreError: setting default path failed: Invalid keystore format

### ISSUE THREAD

**Issue by shabesoglu** [bundler/bundler#3795]
I am using jruby-1.7.4 on osx, and I get the below error when running "bundle install".

Error details

    OpenSSL::X509::StoreError: setting default path failed: Invalid keystore format
      org/jruby/ext/openssl/X509Store.java:185:in `set_default_paths'
     ....

**Comment by segiddins** [comment]
This looks like a ruby / openssl issue rather than a bundler one?

**Comment by shabesoglu** [comment]
I think you are right because I see this issue only when I use JRuby.

**Comment by xiajian** [comment]
I find solution in here: https://gist.github.com/kendagriff/adec3713b4dfe6a1abdf
