### ISSUE TITLE
i encountered following error after issuing  "bundle pack && bundle install --path vender/cache" command while installing snorby. Does anyone have any solution?

### ISSUE THREAD

**Issue by FaizaRahat** [bundler/bundler#3798]
- What did you do?

  I ran the command `/usr/local/bin/bundle install --path vender/cache`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what actually happened was...

Error details

    Errno::EACCES: Permission denied - /var/www/snorby/.bundle
      /usr/lib/ruby/1.9.1/fileutils.rb:247:in `mkdir'
      /usr/lib/ruby/1.9.1/fileutils.rb:247:in `fu_mkdir'
      /usr/lib/ruby/1.9.1/fileutils.rb:221:in `block (2 levels) in mkdir_p'
      /usr/lib/ruby/1.9.1/fileutils.rb:219:in `reverse_each'
      /usr/lib/ruby/1.9.1/fileutils.rb:219:in `block in mkdir_p'
      /usr/lib/ruby/1.9.1/fileutils.rb:205:in `each'
      /usr/lib/ruby/1.9.1/fileutils.rb:205:in `mkdir_p'
      /var/lib/gems/1.9.1/gems/bundler-1.10.5/lib/bundler/settings.rb:208:in `set_key'
      /var/lib/gems/1.9.1/gems/bundler-1.10.5/lib/bundler/settings.rb:31:in `[]='
      /var/lib/gems/1.9.1/gems/bundler-1.10.5/lib/bundler/cli/install.rb:87:in `run'
      /var/lib/gems/1.9.1/gems/bundler-1.10.5/lib/bundler/cli.rb:162:in `install'
      /var/lib/gems/1.9.1/gems/bundler-1.10.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /var/lib/gems/1.9.1/gems/bundler-1.10.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /var/lib/gems/1.9.1/gems/bundler-1.10.5/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /var/lib/gems/1.9.1/gems/bundler-1.10.5/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /var/lib/gems/1.9.1/gems/bundler-1.10.5/lib/bundler/cli.rb:10:in `start'
      /var/lib/gems/1.9.1/gems/bundler-1.10.5/bin/bundle:20:in `block in <top (required)>'
      /var/lib/gems/1.9.1/gems/bundler-1.10.5/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
      /var/lib/gems/1.9.1/gems/bundler-1.10.5/bin/bundle:18:in `<top (required)>'
      /usr/local/bin/bundle:23:in `load'
      /usr/local/bin/bundle:23:in `<main>'

Environment

    Bundler   1.10.5
    Rubygems  1.8.23
    Ruby      1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]
    Git       1.9.1

Bundler settings

    path
      Set for your local app (/var/www/snorby/.bundle/config): "vender/cache

**Comment by TimMoore** [comment]
This means you don't have write permission in the directory you're running `bundle` from. It needs to be able to write it's config file.

**Comment by FaizaRahat** [comment]
Thanks a lot that really helped i forgot to add the user in the www-data group and then set the write permission. my bad.
