### ISSUE TITLE
Can't bundle with current version gems

### ISSUE THREAD

**Issue by kangkyu** [bundler/bundler#3801]
I ran `bundle install` and error messages happened as follows.

Error details

    Psych::SyntaxError: (<unknown>): mapping values are not allowed in this context at line 2 column 30
      /Users/ugp/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/psych-2.0.13/lib/psych.rb:370:in `parse'
      /Users/ugp/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/psych-2.0.13/lib/psych.rb:370:in `parse_stream'
      /Users/ugp/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/psych-2.0.13/lib/psych.rb:318:in `parse'
      /Users/ugp/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/psych-2.0.13/lib/psych.rb:245:in `load'
      /Users/ugp/.rbenv/versions/2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/config_file.rb:333:in `load_file'
      /Users/ugp/.rbenv/versions/2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/config_file.rb:198:in `initialize'
      /Users/ugp/.rbenv/versions/2.2.2/lib/ruby/site_ruby/2.2.0/rubygems.rb:297:in `new'
      /Users/ugp/.rbenv/versions/2.2.2/lib/ruby/site_ruby/2.2.0/rubygems.rb:297:in `configuration'
      /Users/ugp/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.10.5/lib/bundler/rubygems_integration.rb:65:in `configuration'
      /Users/ugp/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.10.5/lib/bundler/rubygems_integration.rb:88:in `sources='
      /Users/ugp/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.10.5/lib/bundler/fetcher.rb:126:in `specs'
      /Users/ugp/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.10.5/lib/bundler/source/rubygems.rb:343:in `block (2 levels) in remote_specs'
      /Users/ugp/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.10.5/lib/bundler/source/rubygems.rb:341:in `each'
      /Users/ugp/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.10.5/lib/bundler/source/rubygems.rb:341:in `block in remote_specs'
      /Users/ugp/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.10.5/lib/bundler/index.rb:9:in `build'
      /Users/ugp/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.10.5/lib/bundler/source/rubygems.rb:324:in `remote_specs'
      /Users/ugp/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.10.5/lib/bundler/source/rubygems.rb:81:in `specs'
      /Users/ugp/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.10.5/lib/bundler/definition.rb:211:in `block (2 levels) in index'
      /Users/ugp/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.10.5/lib/bundler/definition.rb:209:in `each'
      /Users/ugp/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.10.5/lib/bundler/definition.rb:209:in `block in index'
      /Users/ugp/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.10.5/lib/bundler/index.rb:9:in `build'
      /Users/ugp/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.10.5/lib/bundler/definition.rb:206:in `index'
      /Users/ugp/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.10.5/lib/bundler/definition.rb:200:in `resolve'
      /Users/ugp/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.10.5/lib/bundler/definition.rb:140:in `specs'
      /Users/ugp/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.10.5/lib/bundler/definition.rb:129:in `resolve_remotely!'
      /Users/ugp/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.10.5/lib/bundler/installer.rb:79:in `run'
      /Users/ugp/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.10.5/lib/bundler/installer.rb:18:in `install'
      /Users/ugp/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.10.5/lib/bundler/cli/install.rb:107:in `run'
      /Users/ugp/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.10.5/lib/bundler/cli.rb:162:in `install'
      /Users/ugp/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.10.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /Users/ugp/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.10.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /Users/ugp/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.10.5/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /Users/ugp/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.10.5/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /Users/ugp/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.10.5/lib/bundler/cli.rb:10:in `start'
      /Users/ugp/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.10.5/bin/bundle:20:in `block in <top (required)>'
      /Users/ugp/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.10.5/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
      /Users/ugp/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.10.5/bin/bundle:18:in `<top (required)>'
      /Users/ugp/.rbenv/versions/2.2.2/bin/bundle:23:in `load'
      /Users/ugp/.rbenv/versions/2.2.2/bin/bundle:23:in `<main>'

Environment

    Bundler   1.10.5
    Rubygems  2.4.8
    Ruby      2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]
    GEM_HOME  /Users/ugp/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0
    GEM_PATH  /Users/ugp/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0:/Users/ugp/.gem/ruby/2.2.0
    Git       2.4.5

**Comment by segiddins** [comment]
This appears to be a rubygems/psych issue.
