### ISSUE TITLE
Cannot update bundler: no implicit conversion of nil into String

### ISSUE THREAD

**Issue by paneq** [bundler/bundler#3804]
```
vagrant@b:~/current$ bundle --version
Bundler version 1.7.12

vagrant@b:~/current$ gem install bundler
Fetching: bundler-1.10.5.gem (100%)
ERROR:  While executing gem ... (TypeError)
    no implicit conversion of nil into String

vagrant@b:~/current$ which ruby
/home/vagrant/2.1.4/bin/ruby
```

**Comment by indirect** [comment]
The gem command is RubyGems, so I believe this is an issue with rubygems/rubygems

**Comment by paneq** [comment]
@indirect but other gems install ok, so maybe this is a gemspec configuration problem? I will try to report in rubygems anyway.

**Comment by indirect** [comment]
Bundler 1.10.5 installs onto many other machines, so it sounds like the problem is on your machine--maybe RubyGems can help you debug it.
