### ISSUE TITLE
bundle outdated/update within patch, minor, major version 

### ISSUE THREAD

**Issue by ComLock** [bundler/bundler#3805]
I would like to be able to only show or update outdated gems where a newer version is within patch, or minor version. As in do the easy upgrades first.

```sh
bundle update --patch
```

A no-op flag to show what would be done, without doing it would also be nice.

```sh
bundle -n update --minor
```

Then you would not really need the outdated command :)

**Comment by indirect** [comment]
This sounds lovely. Any interest in sending a pull request? :grin:

**Comment by ComLock** [comment]
Sure, I'm going on vacation soon though, so it might be a while. In the mean time, anyone please feel free to make it... :grin:

**Comment by agis-** [comment]
@indirect I'm interested in doing this. Any insights on how this should be approached?

**Comment by indirect** [comment]
This is something that we haven't ever done before! I think what you will probably end up having to do is constructing Gem::Requirement objects with ~> so you can limit the minor or tiny versions that the resolver will look for. I imagine that --minor would end up iterating over all the gems and adding ~> X.Y constraints to each gem in the bundle before trying to resolve. I'm also not sure that would work, but it's where I would start. :)

**Comment by trusche** [comment]
I've been wanting this as well for a long time. @agis let me know if I can help please.

**Comment by agis-** [comment]
I won't have the time to do this so please feel free to take a shot!

**Comment by bronzdoc** [comment]
Closed  by https://github.com/bundler/bundler/pull/4249
