### ISSUE TITLE
bundle gem generates test framework dev dependency without version constraint

### ISSUE THREAD

**Issue by tf** [bundler/bundler#3806]
While I think `bundle gem -t rspec` is a nice touch, I wonder if there should be a version constraint on the generated gemspec entry. At the moment it only says `add_development_dependency 'rspec'`. Given that `Gemfile.lock` is git ignored, I think it would be best practice to depend upon a specific major version. Not sure though how to figure out the appropriate major version. Maybe simply hard coding it is enough since the generator will have to be checked for RSpec 4.0 compatibility anyway once that is released.

**Comment by andremedeiros** [comment]
You're probably right, although I'm not sure how we would even go about this.

I'm open to suggestions as to how to pick versions.

@indirect @segiddins do you guys want to weigh in?

**Comment by segiddins** [comment]
I agree hard coding a major version for rspec in the generator should be fine

**Comment by andremedeiros** [comment]
So you mean, for RSpec, `~> 3.0` should do it?

**Comment by tf** [comment]
I'd say so. I guess there would need to be some hash keeping major versions for the different test frameworks supported by the `-t` option.

**Comment by indirect** [comment]
I'm fine with just tracking the current major version of RSpec and Minitest. Hard coded version strings seems fine, major releases aren't even every year.

**Comment by tf** [comment]
Yes, but the name of the testing framework is [passed to the gemspec template as a variable](https://github.com/bundler/bundler/blob/master/lib/bundler/templates/newgem/newgem.gemspec.tt#L41).I'd suggest adding `config[:test_framework_version]`, which would be set 3.0 for RSpec and 5.0 for Minitest in [`Bundler::CLI::Gem`](https://github.com/bundler/bundler/blob/master/lib/bundler/cli/gem.rb#L68).

Would you be interested in a PR? Is there some sort of test coverage for the gem generator?

**Comment by segiddins** [comment]
@tf yeah, a PR would be great! There's some test coverage in `spec/commands/newgem_spec.rb`

**Comment by tf** [comment]
I've submitted a first draft. Maybe we can continue our discussion there.

**Comment by tf** [comment]
Could somebody help me figure out why the tests of my PR #3811 fail for RubyGems < 2.0? Thanks!
