### ISSUE TITLE
undefined method `dependencies' for nil:NilClass

### ISSUE THREAD

**Issue by RodneyTurnham** [bundler/bundler#3814]
- What did you do?

  I ran the command `/Users/rodneyturnham/.rvm/gems/ruby-2.2.2@global/bin/bundle `

- What did you expect to happen?

  I expected Bundler to update gems or confirm already-installed gems are current

- What happened instead?

  Instead, what actually happened was bundle failed with this error report. Failure was immediate -- very little time (< 1 sec) between command and failure.

Error details

    NoMethodError: undefined method `dependencies' for nil:NilClass
      /Users/rodneyturnham/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.10.4/lib/bundler/index.rb:133:in `block in =='
      /Users/rodneyturnham/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.10.4/lib/bundler/index.rb:94:in `each'
      /Users/rodneyturnham/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.10.4/lib/bundler/index.rb:94:in `block in each'
      /Users/rodneyturnham/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.10.4/lib/bundler/index.rb:93:in `each'
      /Users/rodneyturnham/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.10.4/lib/bundler/index.rb:93:in `each'
      /Users/rodneyturnham/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.10.4/lib/bundler/index.rb:131:in `all?'
      /Users/rodneyturnham/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.10.4/lib/bundler/index.rb:131:in `=='
      /Users/rodneyturnham/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.10.4/lib/bundler/definition.rb:444:in `!='
      /Users/rodneyturnham/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.10.4/lib/bundler/definition.rb:444:in `specs_changed?'
      /Users/rodneyturnham/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.10.4/lib/bundler/definition.rb:476:in `block in converge_paths'
      /Users/rodneyturnham/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.10.4/lib/bundler/definition.rb:475:in `any?'
      /Users/rodneyturnham/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.10.4/lib/bundler/definition.rb:475:in `converge_paths'
      /Users/rodneyturnham/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.10.4/lib/bundler/definition.rb:93:in `initialize'
      /Users/rodneyturnham/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.10.4/lib/bundler/dsl.rb:166:in `new'
      /Users/rodneyturnham/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.10.4/lib/bundler/dsl.rb:166:in `to_definition'
      /Users/rodneyturnham/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.10.4/lib/bundler/dsl.rb:11:in `evaluate'
      /Users/rodneyturnham/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.10.4/lib/bundler/definition.rb:26:in `build'
      /Users/rodneyturnham/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.10.4/lib/bundler.rb:155:in `definition'
      /Users/rodneyturnham/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.10.4/lib/bundler/cli/install.rb:104:in `run'
      /Users/rodneyturnham/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.10.4/lib/bundler/cli.rb:162:in `install'
      /Users/rodneyturnham/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.10.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /Users/rodneyturnham/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.10.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /Users/rodneyturnham/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.10.4/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /Users/rodneyturnham/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.10.4/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /Users/rodneyturnham/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.10.4/lib/bundler/cli.rb:10:in `start'
      /Users/rodneyturnham/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.10.4/bin/bundle:20:in `block in <top (required)>'
      /Users/rodneyturnham/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.10.4/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
      /Users/rodneyturnham/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.10.4/bin/bundle:18:in `<top (required)>'
      /Users/rodneyturnham/.rvm/gems/ruby-2.2.2@global/bin/bundle:23:in `load'
      /Users/rodneyturnham/.rvm/gems/ruby-2.2.2@global/bin/bundle:23:in `<main>'
      /Users/rodneyturnham/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `eval'
      /Users/rodneyturnham/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `<main>'

Environment

    Bundler   1.10.4
    Rubygems  2.4.8
    Ruby      2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]
    GEM_HOME  /Users/rodneyturnham/.rvm/gems/ruby-2.2.2
    GEM_PATH  /Users/rodneyturnham/.rvm/gems/ruby-2.2.2:/Users/rodneyturnham/.rvm/gems/ruby-2.2.2@global
    RVM       1.25.34 (stable)
    Git       1.9.3 (Apple Git-50)
    rubygems-bundler (1.4.4)

**Comment by segiddins** [comment]
@RodneyTurnham can you share the Gemfile that lead to this error?

**Comment by RodneyTurnham** [comment]
source 'https://rubygems.org'

gem 'rails',             '4.2.2'
gem 'responders',        '~> 2.0'
gem 'pg',                '0.18.1'

gem 'figaro',            '1.1.1'
gem 'puma',              '2.11.3'
gem 'asset_sync',        '1.1.0'

gem 'dossier',           '2.12.1'
gem 'dossier-segmenter', '0.12.0'
gem 'jquery.fileupload-rails'

gem 'carrierwave-riak', :require => "carrierwave/riak"

gem 'render_csv',        '~> 2.1.0.beta1'

# assets
gem 'sass-rails', '~> 5.0.0'
gem 'uglifier', '>= 2.7.1'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'ngannotate-rails', '~> 0.9.6.2'
gem 'compass-rails', '~> 2.0.4'

# angular gems
gem 'ng-rails-csrf', '~> 0.1.0'
gem 'angularjs-rails-resource', '~> 1.1.1'
gem 'angular-rails-i18n', github: 'justbaker/angular-rails-i18n', tag: 'v0.0.2'

gem 'simple_form', '~> 3.1.0'
gem 'jbuilder', '~> 1.2'

# components
gem 'devise',     '~> 3.5.1'

# vendored gems
gem 'apiary', '4.9.0',  path: 'vendor/apiary', require: 'apiary/api/mars'

# api1
gem 'kaminari', '~> 0.16.1'

# apollo
gem 'zendesk_api', '~> 1.5.1'

# finder
gem 'statesman', '~> 1.1.0'
gem "flash_render", "~> 1.2.0"

# formula
gem "pdfkit", "~> 0.6.2"
gem "nokogiri", "1.6.5"
gem 'rubyzip',     '~> 1.1.6'
gem 'rrod',        '~> 1.0.0.alpha.9'
gem 'rrod-rails',  github: 'rrods/rrod-rails'

# Seeding/Demo Data
gem 'factory_girl_rails', '~> 4.5.0'
gem "faker", "~> 1.4.3"
gem 'seedbank', '~> 0.3.0'

# queen_city
gem "haml", "~> 4.0"
gem "bootstrap-sass", "2.3.2.2"
gem "draper",  "~> 1.3.0"
gem "searchlight", "~> 3.1.1"

# scrooge
gem "activemerchant", "~> 1.43.1"

group :development, :test do
  gem 'rspec-rails',        '~> 3.3.2'
  gem 'shoulda-matchers',   '~> 2.8'
  gem 'pry',                '~> 0.10.1'
  gem 'capybara',           '~> 2.4.4'
  gem 'capybara-email',     '~> 2.4.0'
  gem 'capybara-mechanize', '~> 1.4.0'
  gem "launchy",            '~> 2.4.2'
end

group :test do
  gem 'timecop'
  gem 'simplecov',           '~> 0.7.1', require: false
end

gem 'redcarpet'
gem 'airbrake',   '~> 4.1'
gem 'whenever',   require: false

**Comment by dfockler** [comment]
FWIW I tried running this Gemfile with Ruby 2.2.2,  Bundler 1.10.5, and RubyGems 2.4.5, and it worked just fine for me on OSX 10.10.3.

**Comment by cdwort** [comment]
Making sure that I had rubygems-bundler, I was also able to get this to work with:
```
Bundler   1.10.4
Rubygems  2.4.5
Ruby      ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin14]
GEM_HOME  /Users/aunger/.rvm/gems/ruby-2.2.0@test-bundler
GEM_PATH  /Users/aunger/.rvm/gems/ruby-2.2.0@test-bundler:/Users/aunger/.rvm/gems/ruby-2.2.0@global
RVM       1.26.9 (stable)
Git       2.3.2 (Apple Git-55)
rubygems-bundler (1.4.4)
```

I'm three minor versions off Rubygems from the original and also two minor versions off Ruby.

**Comment by segiddins** [comment]
So this only happens when using `rubygems-bundler` ?

**Comment by cdwort** [comment]
No, I thought it would be good to make sure that was tested, since @dfockler hadn't mentioned that detail in his attempt to reproduce.

I was able to successfully bundle with `rubygems-bundler` at version `1.4.4`. I failed to reproduce the original error seen by @RodneyTurnham. But I didn't perfectly recreate the environment he specified.

**Comment by dfockler** [comment]
Ah yeah, I wasn't using RVM.

**Comment by indirect** [comment]
@RodneyTurnham Without a copy of `vendor/apiary` it's hard to be 100% sure, but I was also able to install the Gemfile you provided (minus apiary) with no problem. Bundler 1.10.5, Ruby 2.2.2, RubyGems, 2.4.5.

**Comment by justbaker** [comment]
@indirect I've confirmed it was `vendor/apiary` causing issues, due to a git submodule listed in the Gemfile being absent. If a git submodule is referenced as a gem in the Gemfile and doesn't exist, then this error will occur.

**Comment by indirect** [comment]
@justbaker unfortunately, that's still not enough information to reproduce this problem. When I try to install without the path, I just get the error I expect:

```

$ cat Gemfile
source "http://rubygems.org"
gem 'rack'
# vendored gems
gem 'apiary', '4.9.0',  path: 'vendor/apiary', require: 'apiary/api/mars'

$ bundle install --path .bundle
The path `/Users/andre/src/bundler/testcases/3814/vendor/apiary` does not exist.
```

**Comment by justbaker** [comment]
@indirect: I was able to reproduce this again, and I would say this is indeed not an issue.

This exception occurs when the Gemfile.lock references the `apiary` gem after a fresh clone. The git submodule is not synced yet, so the `vendor/apiary` directory is empty.

running

    rm Gemfile.lock
    bundle install

fixed it for me.
