### ISSUE TITLE
bundler interferring with `gem install`

### ISSUE THREAD

**Issue by postmodern** [bundler/bundler#3821]
I noticed that the [install](https://github.com/postmodern/rubygems-tasks/blob/949bdd5115ccd8594c2accae94bf1913ac60f509/lib/rubygems/tasks/install.rb#L56-L58) task in rubygems-tasks errors when bundler is activated. I assume I would have to use something like `Bundler.with_original_env { ... }`. However, by blocking `gem install`, this breaks all the other code that automatically installs gems.

    >>> Installing ore-0.11.0.gem ...
    ERROR:  While executing gem ... (TypeError)
        no implicit conversion of nil into String
    !!! Command failed: gem install -q pkg/ore-0.11.0.gem

**Comment by indirect** [comment]
Could you run it with --verbose so we can at least see the backtrace? This is definitely a bug that needs fixing.

**Comment by postmodern** [comment]
Appears I got burned by Fedora's ruby again. `gem install` is trying to spawn rdoc, but it's only available from my user installed gems, which bundler correctly disables. Works fine when I switch to a stock ruby-2.2.

<pre>
Successfully installed rubygems-tasks-0.2.4
ERROR:  While executing gem ... (Gem::DocumentError)
    RDoc is not installed: cannot load such file -- rdoc/rdoc
	/usr/local/share/ruby/site_ruby/rubygems/rdoc.rb:107:in `rescue in load_rdoc'
	/usr/local/share/ruby/site_ruby/rubygems/rdoc.rb:96:in `load_rdoc'
	/usr/local/share/ruby/site_ruby/rubygems/rdoc.rb:324:in `setup'
	/usr/local/share/ruby/site_ruby/rubygems/rdoc.rb:183:in `generate'
	/usr/local/share/ruby/site_ruby/rubygems/rdoc.rb:81:in `block in generation_hook'
	/usr/local/share/ruby/site_ruby/rubygems/rdoc.rb:80:in `each'
	/usr/local/share/ruby/site_ruby/rubygems/rdoc.rb:80:in `generation_hook'
	/usr/local/share/ruby/site_ruby/rubygems/request_set.rb:188:in `call'
	/usr/local/share/ruby/site_ruby/rubygems/request_set.rb:188:in `block in install'
	/usr/local/share/ruby/site_ruby/rubygems/request_set.rb:187:in `each'
	/usr/local/share/ruby/site_ruby/rubygems/request_set.rb:187:in `install'
	/usr/local/share/ruby/site_ruby/rubygems/commands/install_command.rb:249:in `install_gem'
	/usr/local/share/ruby/site_ruby/rubygems/commands/install_command.rb:299:in `block in install_gems'
	/usr/local/share/ruby/site_ruby/rubygems/commands/install_command.rb:295:in `each'
	/usr/local/share/ruby/site_ruby/rubygems/commands/install_command.rb:295:in `install_gems'
	/usr/local/share/ruby/site_ruby/rubygems/commands/install_command.rb:202:in `execute'
	/usr/local/share/ruby/site_ruby/rubygems/command.rb:307:in `invoke_with_build_args'
	/usr/local/share/ruby/site_ruby/rubygems/command_manager.rb:168:in `process_args'
	/usr/local/share/ruby/site_ruby/rubygems/command_manager.rb:138:in `run'
	/usr/local/share/ruby/site_ruby/rubygems/gem_runner.rb:54:in `run'
	/usr/bin/gem:21:in `<main>'
</pre>

**Comment by postmodern** [comment]
@indirect I don't suppose I could convince you to add `/usr/share/gems/` to bundler's gem directory whitelist?

**Comment by indirect** [comment]
What gem directory whitelist? I can probably be convinced, I'm just not sure what that means. :)

**Comment by postmodern** [comment]
I thought bundler made an exception for rubinius'es ruby-sl gems? Fedora reorganized MRI's files to better conform to the FHS. Built-in gems were moved to `/usr/share/gems/`. In the past I successfully convinced the package maintainers to symlink the files in `/usr/share/gems/gems/.../lib/...` back into `/usr/lib/ruby`, so they were still available from stdlib.

**Comment by indirect** [comment]
We do have some special logic around built-in gems. Maybe we're just not detecting Fedora's correctly? I'd be okay with extending the built-in detector logic to catch them, if that's all that's involved.

**Comment by postmodern** [comment]
In the meantime, I asked Fedora to add a rdoc symlink. https://bugzilla.redhat.com/show_bug.cgi?id=1242118
