### ISSUE TITLE
BUNDLED WITH updates a lower version as well.

### ISSUE THREAD

**Issue by AvnerCohen** [bundler/bundler#3824]
With reference to the locked #3697 

@indirect Wrote this:
````
Older versions of Bundler will not lower the number in the lock, but will warn the user that they are out of date and may not be able to install this bundle successfully.
````

However I can clearly see a downgrade of Gemfile lock from 1.10.4 to 1.10.3 in one of our developers machines, I have not spent time debugging that as I first hoping for clarification.

Isn't that contradicting the above intended behaviour?

As an aside, thanks for making Bundler !! :smile_cat:

**Comment by segiddins** [comment]
Can you provide a reproduction script for that, since it shouldn't ever happen?

**Comment by AvnerCohen** [comment]
No. I can't. It happened once and we couldn't recreate it. I'll have to assume some rvm/bundler hiccup, but that's just a wild guess.

Closing this, 10x!

**Comment by indirect** [comment]
A possible answer is that that person had a ruby with Bundler 1.9 installed, ran a command, realized they were on the wrong Ruby, than switched to a Ruby with 1.10.3 installed.

To be super clear: that should not happen. and if it does it is a bug we will give high priority. 😅
