### ISSUE TITLE
`bundle gem xxx` creates wrong `xxx.gemspec` under Windows

### ISSUE THREAD

**Issue by jarmo** [bundler/bundler#3829]
Under Windows, when using `bundle gem xxx` to create new gem a gemspec is wrong regarding gem binaries.

This is what it looks like now:

```ruby
spec.bindir        = "exe"
spec.executables   = spec.files.grep(%r{^exe/}) { |f| File.basename(f) }
```

There is no directory `exe`, but it is `bin` like usually.

This is how it should be instead regardless of OS used:
```ruby
spec.bindir        = "bin"
# Add only spec.name binary by default, otherwise console and setup will be also added, which we do not want
spec.executables   = [spec.name] if File.exists?(File.join(spec.bindir, spec.name))
```

Bundler version is `1.10.5`.

**Comment by segiddins** [comment]
No, when you `bundle gem` a gem with executables now, it places those in `exe`. `bin` is now used for commands used while developing the gem.

**Comment by simi** [comment]
see http://bundler.io/blog/2015/03/20/moving-bins-to-exe.html for more info

**Comment by jarmo** [comment]
I see. Didn't know about this fundamental change in gem development.

Closing this issue now if that's the way of the future. Thanks for the information!
