### ISSUE TITLE
Bundler - Issues when bundle packaging

### ISSUE THREAD

**Issue by thehogg13** [bundler/bundler#3873]
When trying to do a `bundle package --all --no-install` i am now getting the following error message.

--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `/Users/ashaustin/.rbenv/versions/2.2.0/bin/bundle package --all --no-install`

- What did you expect to happen? 

  I expected Bundler to...

- What happened instead?

  Instead, what actually happened was i got "Unfortunately, an unexpected error occurred, and Bundler cannot continue."

Error details

    NoMethodError: undefined method `remote' for nil:NilClass
      /Users/ashaustin/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/source/rubygems.rb:388:in `fetch_gem'
      /Users/ashaustin/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/source/rubygems.rb:192:in `cached_built_in_gem'
      /Users/ashaustin/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/source/rubygems.rb:175:in `cache'
      /Users/ashaustin/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:113:in `block in cache'
      /Users/ashaustin/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:110:in `cache'
      /Users/ashaustin/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/cli/install.rb:108:in `run'
      /Users/ashaustin/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/cli/package.rb:32:in `install'
      /Users/ashaustin/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/cli/package.rb:16:in `run'
      /Users/ashaustin/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/cli.rb:265:in `package'
      /Users/ashaustin/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /Users/ashaustin/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /Users/ashaustin/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /Users/ashaustin/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /Users/ashaustin/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/cli.rb:10:in `start'
      /Users/ashaustin/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/bin/bundle:20:in `block in <top (required)>'
      /Users/ashaustin/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
      /Users/ashaustin/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/bin/bundle:18:in `<top (required)>'
      /Users/ashaustin/.rbenv/versions/2.2.0/bin/bundle:23:in `load'
      /Users/ashaustin/.rbenv/versions/2.2.0/bin/bundle:23:in `<main>'

Environment

    Bundler   1.10.6
    Rubygems  2.4.5
    Ruby      2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin14]
    GEM_HOME  /private/tmp/bluemix.z8V/johanna/vendor/cache
    GEM_PATH  
    Git       2.3.2 (Apple Git-55)

Bundler settings

    cache_all
      Set for your local app (/private/tmp/bluemix.z8V/johanna/.bundle/config): true
      Set for the current user (/Users/ashaustin/.bundle/config): "true"
    path
      Set for the current user (/Users/ashaustin/.bundle/config): "vendor/cache"
    without
      Set for your local app (/private/tmp/bluemix.z8V/johanna/.bundle/config): "test:development:staging"
      Set via BUNDLE_WITHOUT: "test:development:staging"
      Set for the current user (/Users/ashaustin/.bundle/config): "test:development:staging"
    disable_shared_gems
      Set for your local app (/private/tmp/bluemix.z8V/johanna/.bundle/config): "1"
      Set for the current user (/Users/ashaustin/.bundle/config): "1"
    no_install
      Set for your local app (/private/tmp/bluemix.z8V/johanna/.bundle/config): true
--- TEMPLATE END ----------------------------------------------------------------

Im sorry im not too sure what else i can include to help , but i am keen to get whatever might assist. thanks heaps.

**Comment by segiddins** [comment]
What's your `Gemfile`?

**Comment by thehogg13** [comment]
require "./lib/host_helper"
require "./lib/github_url_helper"

source HostHelper.new.gem_host

ruby "2.2.0"

#Core
gem 'activerecord-session_store'
gem 'browser'
gem 'cache_digests'
gem 'dotiw'
gem 'integration', git: GithubUrlHelper.private_github_url('Ferocia/integration'), ref: "e36bdba"
gem 'escape_utils'
gem 'fast_blank'
gem 'grape', '~> 0.10.0'
gem 'grape-entity', '~> 0.4.0'
gem 'grape-swagger', '~> 0.9.0'
gem 'grape-swagger-rails'
gem 'j_admin', git: GithubUrlHelper.private_github_url('Ferocia/j_admin'), tag: '0.0.9'
gem 'json'
gem 'monetize'
# Bug preventing deployments (requests password on deploy attempt)
# http://stackoverflow.com/questions/21560297/capistrano-sshauthenticationfailed-not-prompting-for-password
# https://github.com/net-ssh/net-ssh/compare/v2.7.0...v2.9.2
# Still broken on version 2.9.2 on last attempt
gem 'net-ssh', '2.7.0'
gem 'rack'
gem 'rails', '4.1.11'
gem 'rails-prg', '0.1.1'
gem 'rack-protection', require: 'rack/protection'
gem 'rake'
gem 'rein'
gem 'safe_yaml'
gem 'secure_headers'
gem 'rails_12factor'

#Cache
gem 'rack-cache'
gem 'dalli'

#Modeling
gem 'validates_email_format_of'
gem 'fiscali'
gem 'acts_as_list'

#Presentation
gem 'nestive', git: GithubUrlHelper.private_github_url('plasticine/nestive'), branch: 'master'
gem 'ui', path: 'vendor/ui'

#Logging
gem 'lograge' , git: GithubUrlHelper.private_github_url('ferocia/lograge'), branch: 'master'

#Monitoring
gem 'exception_notification'
gem 'newrelic_rpm'
gem 'newrelic-grape'

group :development, :test, :staging, :benberdemo, :demo do
  gem 'stethoscope'
end

#Async processing
gem 'sidekiq'

#Deploy
gem 'capistrano'
gem 'capistrano-strategy-copy-bundled', git: GithubUrlHelper.private_github_url('tommeier/capistrano-strategy-copy-bundled'), ref: '8b6fe53'
gem 'unicorn'
gem 'unicorn-worker-killer'
gem 'subcontractor'

#Assets
gem 'bourbon'
gem 'coffee-rails'
gem 'coffee-script-source'
gem 'neat'
gem 'sass-globbing'
gem 'sass-rails'
gem 'uglifier'

#Mail
gem 'premailer-rails'

#IBM Bluemix job Scheduler
gem 'clockwork'

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'foreman'
  gem 'pygments.rb', require: false
end

group :test do
  gem 'j-pages', path: "vendor/j-auto/vendor/j-pages"
  gem 'capybara'
  gem 'capybara-screenshot'
  gem 'capybara-inline-screenshot'
  gem 'database_cleaner'
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'hashie'

  gem 'rspec-activemodel-mocks'
  gem 'selenium-webdriver'
  gem 'shoulda-matchers', require: false
  gem 'simplecov'
  gem 'webmock'

  gem 'test-queue'

  gem 'timecop'

  gem 'turnip'
  gem 'zonebie', require: false
end

group :development, :test do
  gem 'awesome_print'
  gem 'brakeman', "~> 3.0.2"
  gem 'cane'
  gem 'dotenv'
  gem 'ir_b'
  gem 'pry'
  gem 'jasmine'
  gem 'jasmine_selenium_runner'
  gem 'quiet_assets'
  gem 'kayessess'
  gem 'rspec-rails', '~> 3.0'
  gem 'rubocop', require: false
  # test-queue as of 0.2.12 still uses a legacy formatter.
  # this gem is required to silence a warning. Remove when test-queue is updated.
  # note rspec-core has to be called explicitly here due to a dependency bug in legacy_formatters.
  gem 'rspec-core'
  gem 'rspec-legacy_formatters'
end

group :development, :staging, :test, :demo, :cfdemo1, :cfdemo2, :cftrain1, :cftrain2 do
  gem 'pg'
end

group :development, :staging, :benberf, :benberh do
  gem 'peek', git: GithubUrlHelper.private_github_url('plasticine/peek'), ref: 'bc84d63'
  gem 'peek-dalli'
  gem 'peek-gc'
  gem 'peek-redis'
end

group :development, :staging do
  gem 'peek-git'
end

group :development, :test, :staging, :benberf, :benberh  do
  gem 'peek-api_profiler', git: GithubUrlHelper.private_github_url('Ferocia/peek-api_profiler'), ref: '1ba0c27a029f38542bbf3aef61d166a71615cc07'
end

group :development, :test, :staging do
  gem 'peek-pg'
end

# BERDEMO uses fakewebseal to show the demo login page
group :development, :staging, :test, :benberdemo, :ferberdemo, :demo, :cfdemo1, :cfdemo2, :cftrain1, :cftrain2 do
  gem 'fake_web_seal', git: GithubUrlHelper.private_github_url('Ferocia/fake_web_seal'), ref: '60257faf6ba222726be3def65d63015906244121'
end

group :staging, :benberf, :benberq, :benberm, :benberp, :benberspd, :benberh do
  gem 'therubyracer', '~> 0.12'

  #FOR MSSQL
  #gem 'activerecord-sqlserver-adapter', git: GithubUrlHelper.private_github_url('rails-sqlserver/activerecord-sqlserver-adapter'), ref: '8bccbaa02afd9fd4ff877c33f51c67e845fcfcf8'
  #gem 'tiny_tds', git: GithubUrlHelper.private_github_url('rails-sqlserver/tiny_tds'), ref: 'ed4e43ec2598fc7879359f53b6d941b9e92234bc'
end

**Comment by thehogg13** [comment]
We have a private gem server , so `HostHelper.new.gem_host` and `URL_HELPER` are used to send certain clients to that Gem Server

**Comment by segiddins** [comment]
In that case, we won't really be able to investigate -- we really need a Gemfile we can run ourselves that reproduces the issue, sorry!

**Comment by thehogg13** [comment]
Closed the issue since there was no way to help me.
