### ISSUE TITLE
I want to fix this issue

### ISSUE THREAD

**Issue by Justin-Park** [bundler/bundler#3880]
I want fix this issue, but I'm newbie... plz help me..

--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `/usr/local/bin/bundle install`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what actually happened was...

Error details

    fatal: deadlock detected
      /usr/local/lib/ruby/1.9.1/thread.rb:189:in `sleep'
      /usr/local/lib/ruby/1.9.1/thread.rb:189:in `block in pop'
      <internal:prelude>:10:in `synchronize'
      /usr/local/lib/ruby/1.9.1/thread.rb:184:in `pop'
      /usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/worker.rb:35:in `deq'
      /usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/installer/parallel_installer.rb:93:in `process_specs'
      /usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/installer/parallel_installer.rb:74:in `call'
      /usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/installer/parallel_installer.rb:56:in `call'
      /usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/installer.rb:274:in `install_in_parallel'
      /usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/installer.rb:91:in `run'
      /usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/installer.rb:18:in `install'
      /usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/cli/install.rb:107:in `run'
      /usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/cli.rb:162:in `install'
      /usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/cli.rb:10:in `start'
      /usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.10.6/bin/bundle:20:in `block in <top (required)>'
      /usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
      /usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.10.6/bin/bundle:18:in `<top (required)>'
      /usr/local/bin/bundle:23:in `load'
      /usr/local/bin/bundle:23:in `<main>'

Environment

    Bundler   1.10.6
    Rubygems  2.4.8
    Ruby      1.9.3p551 (2014-11-13 revision 48407) [armv7l-linux-eabi]
    GEM_HOME  /usr/local/lib/ruby/gems/1.9.1
    GEM_PATH  /usr/local/lib/ruby/gems/1.9.1:/root/.gem/ruby/1.9.1
    Git       2.1.4

Bundler settings

    jobs
      Set for the current user (/root/.bundle/config): "7"

**Comment by rgb-one** [comment]
What device are you using (eg. laptop, tablet, phone, etc.)? Can you provide the Gemfile you used when you got the error. 
If you can provide steps to to reproduce this error that would be useful.

**Comment by indirect** [comment]
This is the same issue reported in #3692, but unfortunately no one has given us enough information to reproduce it yet. Can you tell us how to reproduce it?

**Comment by Justin-Park** [comment]
Sorry for late reply, I've resolved that problem. (I using on Raspberry PI
2)
I removed all my bundle and Re-Install.
Thank you for your interesting!

2015-07-26 6:46 GMT+09:00 André Arko <notifications@github.com>:
