### ISSUE TITLE
Bundle error sudo -u git -H bundle install --deployment --without development test mysql aws

### ISSUE THREAD

**Issue by michaelmanoCOM** [bundler/bundler#3883]
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `/usr/local/bin/bundle install --deployment --without development test mysql aws`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what actually happened was...

Error details

    Errno::EACCES: Permission denied @ rb_sysopen - /home/git/gitlab/.bundle/config
      /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/settings.rb:210:in `initialize'
      /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/settings.rb:210:in `open'
      /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/settings.rb:210:in `set_key'
      /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/settings.rb:31:in `[]='
      /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/cli/install.rb:76:in `run'
      /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/cli.rb:162:in `install'
      /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/cli.rb:10:in `start'
      /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/bin/bundle:20:in `block in <top (required)>'
      /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
      /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/bin/bundle:18:in `<top (required)>'
      /usr/local/bin/bundle:23:in `load'
      /usr/local/bin/bundle:23:in `<main>'

Environment

    Bundler   1.10.6
    Rubygems  2.2.2
    Ruby      2.1.2p95 (2014-05-08 revision 45877) [x86_64-linux]
    Git       2.1.4

Bundler settings

    jobs
      Set for your local app (/home/git/gitlab/.bundle/config): "3"
    frozen
      Set for your local app (/home/git/gitlab/.bundle/config): "1"
--- TEMPLATE END ----------------------------------------------------------------

**Comment by indirect** [comment]
Change the permissions on `/home/git/gitlab/.bundle/config` so that Bundler can read it.

**Comment by ProckStar** [comment]
Hmmmm ... not understanding what to change the permissions too. I'm getting the exact same error, only difference is the Git version I'm using is 1.9.1

The permissions on the config file is rw-r--r-- 
Owner and group are root

I thought I knew enough about permissions to make sense of this, but the file is readable by user, group and world. Wouldn't Bundler be part of the "world"? Do I need to change the owner or group? if so, what do I change it to?

... Scott

**Comment by indirect** [comment]
I don't know, to be honest. All I know is that your error message says that the OS won't let Ruby open the config file that Bundler needs to read. :/

**Comment by TimMoore** [comment]
It needs write permission as well
