### ISSUE TITLE
NoMethodError: undefined method `remote' for nil:NilClass

### ISSUE THREAD

**Issue by lukaso** [bundler/bundler#3887]
- What did you do?

  I ran the command `/Users/loberhub/.rbenv/versions/2.1.6/bin/bundle `

- What did you expect to happen?

  I expected Bundler to...package

- What happened instead?

  Instead, what actually happened was...it crashed with the error below after having completed bundling.

Error details

    NoMethodError: undefined method `remote' for nil:NilClass
      /Users/loberhub/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/bundler-1.10.4/lib/bundler/source/rubygems.rb:388:in `fetch_gem'
      /Users/loberhub/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/bundler-1.10.4/lib/bundler/source/rubygems.rb:192:in `cached_built_in_gem'
      /Users/loberhub/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/bundler-1.10.4/lib/bundler/source/rubygems.rb:175:in `cache'
      /Users/loberhub/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/bundler-1.10.4/lib/bundler/runtime.rb:113:in `block in cache'
      /Users/loberhub/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/bundler-1.10.4/lib/bundler/runtime.rb:110:in `cache'
      /Users/loberhub/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/bundler-1.10.4/lib/bundler/cli/install.rb:108:in `run'
      /Users/loberhub/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/bundler-1.10.4/lib/bundler/cli.rb:162:in `install'
      /Users/loberhub/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/bundler-1.10.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /Users/loberhub/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/bundler-1.10.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /Users/loberhub/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/bundler-1.10.4/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /Users/loberhub/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/bundler-1.10.4/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /Users/loberhub/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/bundler-1.10.4/lib/bundler/cli.rb:10:in `start'
      /Users/loberhub/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/bundler-1.10.4/bin/bundle:20:in `block in <top (required)>'
      /Users/loberhub/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/bundler-1.10.4/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
      /Users/loberhub/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/bundler-1.10.4/bin/bundle:18:in `<top (required)>'
      /Users/loberhub/.rbenv/versions/2.1.6/bin/bundle:23:in `load'
      /Users/loberhub/.rbenv/versions/2.1.6/bin/bundle:23:in `<main>'

Environment

    Bundler   1.10.4
    Rubygems  2.2.3
    Ruby      2.1.6p336 (2015-04-13 revision 50298) [x86_64-darwin14.0]
    GEM_HOME  /Users/loberhub/projects/chopin/vendor/bundle/ruby/2.1.0
    GEM_PATH
    Git       2.4.4

Bundler settings

    path
      Set for your local app (/Users/loberhub/projects/chopin/.bundle/config): "vendor/bundle"
    disable_shared_gems
      Set for your local app (/Users/loberhub/projects/chopin/.bundle/config): "1"
    jobs
      Set for your local app (/Users/loberhub/projects/chopin/.bundle/config): "4"
    cache_all
      Set for your local app (/Users/loberhub/projects/chopin/.bundle/config): "true"
    cache_all_platforms
      Set for your local app (/Users/loberhub/projects/chopin/.bundle/config): "true"

**Comment by indirect** [comment]
Can you share the output from `bundle env`?

**Comment by lukaso** [comment]
I think this is a duplicate of #3158.

I have a hypothesis of what the problem is:

This failure occurs when a gem is included in the Gemfile that is already built into ruby. I was trying to work around gems that are no longer included in ruby 2.2 but bundling in ruby 2.1.6. For me it was test-unit. Does that sound right?

**Comment by lukaso** [comment]
This example from #3158 reproduces my problem exactly:

```
mkdir /tmp/bundler_repro

# I am using rbenv, plz adjust to your setup
echo "2.1.6" > /tmp/bundler_repro/.ruby-version

# This gem version matches exactly the version number of io-console
# in the ruby 2.1.6 builtin gemset. 
# Probably explains the presence of 'cached_built_in_gem' in the callstack.
echo "gem 'io-console', '= 0.4.3', :require => false" > /tmp/bundler_repro/Gemfile 

# boom
cd /tmp/bundler_repro && bundle package
```

```
- What did you do?

  I ran the command `/Users/loberhub/.rbenv/versions/2.1.6/bin/bundle package`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what actually happened was...


Error details

    NoMethodError: undefined method `remote' for nil:NilClass
      /Users/loberhub/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/source/rubygems.rb:390:in `fetch_gem'
      /Users/loberhub/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/source/rubygems.rb:194:in `cached_built_in_gem'
      /Users/loberhub/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/source/rubygems.rb:175:in `cache'
      /Users/loberhub/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:113:in `block in cache'
      /Users/loberhub/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:110:in `cache'
      /Users/loberhub/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/cli/install.rb:108:in `run'
      /Users/loberhub/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/cli/package.rb:32:in `install'
      /Users/loberhub/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/cli/package.rb:16:in `run'
      /Users/loberhub/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/cli.rb:265:in `package'
      /Users/loberhub/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /Users/loberhub/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /Users/loberhub/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /Users/loberhub/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /Users/loberhub/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/cli.rb:10:in `start'
      /Users/loberhub/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/bin/bundle:20:in `block in <top (required)>'
      /Users/loberhub/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
      /Users/loberhub/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/bin/bundle:18:in `<top (required)>'
      /Users/loberhub/.rbenv/versions/2.1.6/bin/bundle:23:in `load'
      /Users/loberhub/.rbenv/versions/2.1.6/bin/bundle:23:in `<main>'

Environment

    Bundler   1.10.6
    Rubygems  2.2.3
    Ruby      2.1.6p336 (2015-04-13 revision 50298) [x86_64-darwin14.0]
    GEM_HOME  /Users/loberhub/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0
    GEM_PATH  /Users/loberhub/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0:/Users/loberhub/.gem/ruby/2.1.0
    Git       2.4.4
--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/bundler/bundler/search?q=undefined+method+%60remote%27+for+nil%3ANilClass&type=Issues

If there aren't any reports for this error yet, please create copy and paste the report template above into a new issue. Don't forget to anonymize any private data! The new issue form is located at:
https://github.com/bundler/bundler/issues/new
```

And here is bundler env:
```
Environment

    Bundler   1.10.6
    Rubygems  2.2.3
    Ruby      2.1.6p336 (2015-04-13 revision 50298) [x86_64-darwin14.0]
    Git       2.4.4

Gemfile

    gem 'io-console', '= 0.4.3', :require => false

Gemfile.lock

    GEM
      specs:
        io-console (0.4.3)

    PLATFORMS
      ruby

    DEPENDENCIES
      io-console (= 0.4.3)

    BUNDLED WITH
       1.10.6
```

**Comment by agis-** [comment]
Fixed by https://github.com/bundler/bundler/pull/3896.
