### ISSUE TITLE
Help Integration for Command Plugins

### ISSUE THREAD

**Issue by tf** [bundler/bundler#3894]
I really like the simplicity of adding commands to bundler by placing `bundler-something` executables on the path. What do you think about also adding integration for the `bundle help` command? Right now calling `bundle help something` just returns with "command not found". In the simplest case we could adapt the help command to simply turn `bundle help something` into `bundler-something --help` if such an executable exists.

Since `bundle help` simply renders a static man page, I see no easy way of listing plugin commands there. Even worse bundler has no good way of knowing which command plugins exist.

But would you be interested in a PR adding the first part?

**Comment by segiddins** [comment]
I personally prefer using `--help` to a separate subcommand, so ¯\_(ツ)_/¯

**Comment by tf** [comment]
Ok, I'll close this then. Cheers

**Comment by indirect** [comment]
We're working on a system that lets Bundler know what plugins exist; in the meantime, I'm okay with a PR that does `Bundler.which("bundle-foo") && exec("bundle-foo", "--help")` as a fallback.

**Comment by tf** [comment]
Alright. I'll open a PR when a get the time.

**Comment by tf** [comment]
see #3911
