### ISSUE TITLE
Handle missing commits clearly

### ISSUE THREAD

**Issue by postmodern** [bundler/bundler#3897]
This error message could probably be a little more clear:

<pre>
Updating https://XXXXXXXXXXXXXX:x-oauth-basic@github.com/XXXXX/XXXXXXXXXXXX.git
fatal: ambiguous argument 'FOO': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Git error: command `git rev-parse FOO` in directory
/home/hal/.gem/ruby/2.1.6/cache/bundler/git/XXXXXX-XXXXXXXXXXXXXXXXXXXXX
has failed.
If this error persists you could try removing the cache directory
'/home/hal/.gem/ruby/2.1.6/cache/bundler/git/XXXXXXXX-XXXXXXXXXXXXXXXXXXXXX'
</pre>

**Comment by cdwort** [comment]
If we ran `git rev-parse --verify FOO` before running `git rev-parse FOO`, would that allow us to distinguish between failures due to branch not existing and having an outdated cache?

**Comment by indirect** [comment]
I don't know what the difference is, tbh! How do they differ? (I believe the message is for branches that are checked out by Bundler and then force pushed, since Bundler thinks the cache is up to date, and you have to delete the cache to fetch again over the existing branch.)

**Comment by cdwort** [comment]
@indirect I don't either really... it's Google's answer to how to check if a branch exists. 

I would think it would help, except that it's a flag on the original command we're running. Perhaps it will fail on the issue that we're trying to suggest happens with the cache. I don't know enough about our cache to tell whether it would lead us to not be able to find the branch even if it actually exists. It seems unlikely, but I don't know enough to say.

**Comment by cdwort** [comment]
Hm, yeah, it looks like it's more like a stricter version of `rev-parse`. From docs, it does not look like it can succeed if `rev-parse` can't. The real test would be to get the cache involved, but here's a quick test:

<img width="748" alt="screen shot 2015-07-30 at 8 11 23 pm" src="https://cloud.githubusercontent.com/assets/1014482/8998768/49542230-36f7-11e5-9479-b76f18ff8c55.png">

Seems likely, then, that we can't easily determine the difference between a branch not being in the cache and the branch not existing at all. Perhaps altering our error message to something like:

```
If the revision or path exists and this error persists, you could try removing the cache directory
```

**Comment by indirect** [comment]
Ahh. We should probably change the command we call to `git rev-parse abc123 --` then, to remove the ambiguity warning. Then, it sounds like we want to add a single retry clause that either force-updates the cache repo or deletes it and clones it again before reporting failure.

**Comment by agis-** [comment]
Is this still an issue? I've tried the above scenarios on *master* and Bundler successfully fetched the new revision (even if it was force-pushed or pushed *after* the initial cache was downloaded).

**Comment by indirect** [comment]
@agis- I think the scenario is something like:

1. Create Gemfile `gem "mygem", git: "myname/myrepo", branch: "mybranch"
2. `bundle install --path .bundle`
3. `cd myrepo; git checkout mybranch; git commit --amend "new commit"; git push -f origin mybranch`
4. Remove Bundler git cache (`rm -rf .bundle`)
5. `bundle install --path .bundle` will now fail because the locked SHA does not exist.

**Comment by agis-** [comment]
Cool, will look into it. Meanwhile, I've prepared a patch to show more friendly errors when the given ref does not exist.

**Comment by agis-** [comment]
@indirect I couldn't reproduce this following the steps you described above and with either master or 1.10.6.

@postmodern what version of bundler you were using?

**Comment by indirect** [comment]
@agis- whoa, I guess the problem is fixed, then, and I just didn't realize. Thanks for verifying!
