### ISSUE TITLE
A CLI flag to install a gem and add definition to Gemfile

### ISSUE THREAD

**Issue by jingweno** [bundler/bundler#3899]
What do you think of adding an optional flag to insert gem definition to `Gemfile` as part of `bundle install`:

```
$ bundle install a_gem --save
```

The gem is installed, an entry is added to `Gemfile`:

```rb
gem 'a_gem'
```

and `Gemfile.lock` is updated to lock to the latest version.

Other usage:

```
$ bundle install a_gem --version 0.0.1 --save development
```

Then in `Gemfile`:

```rb
group :development do
  gem 'a_gem', '0.0.1'
end
```

I would like to discuss it before contributing this feature.

**Comment by segiddins** [comment]
Doesn't `bundle inject` basically already do this?

**Comment by jingweno** [comment]
I didn't know about `bundle inject`. But it seems it can be just one or two flags in `bundle install`.

**Comment by jingweno** [comment]
`bundle inject` always requires a version. I would hope it can just get me the latest version if I don't specify it:

```
Usage:
  bundle inject GEM VERSION ...
```

Besides, I can't make the gem nest in a group.

**Comment by segiddins** [comment]
Sounds like a great plugin to me! I don't see this being core enough functionality to warrant being in bundler proper, but it would make for a nice plugin once that work is done!

**Comment by jingweno** [comment]
Sounds like bundler has a plugin system?

**Comment by indirect** [comment]
`bundle inject` is intended for use by deploy systems like Engine Yard (they paid me to write the feature). I intended to create a `bundle add GEM [VERSION]` command that wraps inject, but I never got around to it.

To create a plugin, build a gem named `bundle-add` that contains an executable named `bundle-add`, Bundler will run it when you run `bundle add`.

**Comment by jingweno** [comment]
@indirect What does `bundle-add` do? Why needing another wrapper? I could contribute this feature. But basically my preference is a flag in `bundle install` as mentioned in the description.

**Comment by indirect** [comment]
80% of the work on Bundler is maintenance. That means that if we accept that flag into core, we are agreeing to do 80% of the work, because we will have to keep it working for years. You are the second or third person to ask for the ability to add gems via command, so agreeing to do all that work doesn't make sense for us right now. If you create a plugin, and it's popular, we will likely add it to core.

**Comment by jingweno** [comment]
Is it possible that I create a plugin named bundle-install that wraps bundle install and adds more functionality?

**Comment by indirect** [comment]
No, the install command cannot be wrapped by a plugin. Also, if this is accepted into core, it will be as a separate command, not as a flag to install.

**Comment by tf** [comment]
+1 for a `bundle add` plugin. In contrast to npm (which might have inspired this feature request) `bundle install` does not take a package name parameter. So I think it makes sense as a separate command.

One other nice thing that should be adopted from npm: automatically insert a pessimistic version constraint based on the latest gem version in the Gemfile even if no `--version` parameter is passed to `bundle add`, i.e.:

    $ bundle add some_gem
    Successfully installed some_gem 4.3.2
    
    # Gemfile
    gem 'some_gem', '~> 4.3'

**Comment by segiddins** [comment]
I'm going to close this for now, but do let us know if you end up building the plugin!
