### ISSUE TITLE
`/usr/bin/bundle` compilation leads to segfaults

### ISSUE THREAD

**Issue by nathanl** [bundler/bundler#3902]
I've had mysterious segfaults when running rails for a while, and finally figured out how to reproduce them.

- Install a new version of Ruby - say, 2.2.2
- In a project folder, switch to using Ruby 2.2.2. (`$GEM_HOME` is now `~/.gem/ruby/2.2.2`)
- `bundle`. No such gem.
- `gem install bundler`
- `bundle`. **Here's where my problem occurred**.

Because I've just installed bundler, `bundle` in the shell session actually still points to `/usr/bin/bundle`, not `.gem/ruby/2.1.2/bin/bundle`. Any gems it installs with native extensions will be linked to my system Ruby version, and may segfault when I try to use them with Ruby 2.2.2.

Without knowing what was happening, I was flailing around, uninstalling and reinstalling stuff and seemingly getting success/failure at random.

I'm not sure what the best solution is for this; personally, I've edited `/usr/bin/bundle` to shout at me and exit.

**Comment by segiddins** [comment]
I don't think there's really anything bundler can do to help here -- the bundler executable you invoked runs with whatever ruby it points to.

**Comment by indirect** [comment]
I think this is a bug in your ruby switcher. When I install a new ruby and then switch to it and install Bundler, the newly installed Bundler is immediately in my path to be called, so this problem doesn't happen.

**Comment by franckverrot** [comment]
You might want to run `hash -r` (if you use bash) or `rehash` (on zsh) to make sure your shell doesn't use its cache to resolve the path of the `bundle` command.
If you're using a version switcher, this is supposed to be done for you though...

**Comment by nathanl** [comment]
I didn't figure there was much Bundler could do about it, but I thought it odd that `which gem` pointed to the correct one but `which bundle` didn't. I guess if Bundler shipped with Ruby it would have been in the same path location. Who doesn't use Bundler with Ruby? :) 

Anyway, I mostly wanted to document this in case anybody else on the interwebs has the same issue. Thanks for all your work on Bundler!

**Comment by nathanl** [comment]
I still doubt that Bundler can do anything about this, but one thing bothers me:

> If you're using a version switcher, this is supposed to be done for you

It's only done for you if you're 1) using a version switcher and 2) have it set up to autoswitch before every command.

What would make more sense to me is if every `gem install` of a gem with `spec.executables` would run `hash -r` after installation.

**Comment by indirect** [comment]
If you're using rbenv, there is a plugin (iirc calls rbenv-rehash) to do this for you automatically. I haven't had this problem myself while using chruby.
