### ISSUE TITLE
Output of `outdated` for git-sourced gems

### ISSUE THREAD

**Issue by jordanthomas** [bundler/bundler#3909]
When running `bundle outdated` the output begins with `Updating [url]` for each of the git-sourced gems in the Gemfile. This is confusing since it makes it look like gems are being updated.

Could the UI output of the `checkout` method be updated or mellowed out to match  _"Fetching xxxx metadata from..."_?

**Comment by vinnyjth** [comment]
This has always confused me. Seems like a worthy request.

**Comment by mberning** [comment]
+1 - I think the language could be clearer

**Comment by segiddins** [comment]
A PR adjusting the language would be much appreciated!

**Comment by jordanthomas** [comment]
Here's a crack at it: https://github.com/bundler/bundler/pull/3918

**Comment by agis-** [comment]
I guess this should be closed since #3918 is merged (https://github.com/bundler/bundler/commit/b22f0f490c6cdbfa3dd4d46234a850668dc89692).

**Comment by jordanthomas** [comment]
👍🏻
