### ISSUE TITLE
Parallel jobs break system gems installation

### ISSUE THREAD

**Issue by saveriomiroddi** [bundler/bundler#3910]
When bundler is configured for using parallel jobs, the installation of system gems (which request sudo permissions) fails.

Specifically, on `bundle install` execution, several password prompts show up at the same time (as many as the parallel jobs configured), and even if the correct password is inserted, it will be rejected as wrong.

The workaround is to either override the parallel jobs parameter to 1, or to disable this feature from the configuration at all.

The bundler version is 1.10.6.

**Comment by segiddins** [comment]
We probably should make sure `sudo` access is wrapped in a mutex
