### ISSUE TITLE
Different order of dependencies in Gemfile.lock for OSX and Ubuntu

### ISSUE THREAD

**Issue by hasghari** [bundler/bundler#3914]
With no change in the Gemfile, OSX and Ubuntu produce a slightly different Gemfile.lock. Both platforms are running Bundler 1.10.6

**Comment by indirect** [comment]
Please supply the output of `bundle env` so we can try to reproduce this.

**Comment by hasghari** [comment]
http://alphaimages.s3.amazonaws.com/osx-bundle-env.txt

**Comment by hasghari** [comment]
I was able to solve our immediate issue by removing an explicit dependency in the Gemfile that is fetched as a transitive dependency of another gem.
