### ISSUE TITLE
bundle install - "You need to install git to be able to use gems from git repositories"

### ISSUE THREAD

**Issue by JoelNietoTec** [bundler/bundler#3915]
OS: Windows 10 x64
Bundler version: 1.10.6
Git installed
Rails version: 4.2.3

**Comment by indirect** [comment]
Bundler can’t find git. Maybe you need to add it to your PATH?

**Comment by agis-** [comment]
Closing this due to lack of feedback. If the problem persists, let us know and we'll reopen the issue.

**Comment by rxsharp** [comment]
I'm getting this issue as well but when I deploy through Amazon Elastic Beanstalk. I went into the ssh and installed git but it didn't solve the issue.

**Comment by indirect** [comment]
This ticket is closed. If you're having a problem, please follow [ISSUES](https://github.com/bundler/bundler/blob/master/ISSUES.md).
