### ISSUE TITLE
when run "bundle install"  got error

### ISSUE THREAD

**Issue by 0704681032** [bundler/bundler#3916]
/usr/local/rvm/gems/ruby-1.9.3-p448/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/shell/basic.rb:356: warning: Insecure world writable dir /usr/local/mysql/bin in PATH, mode 040777
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your bundle as root will break this application for all non-root users on this machine.
git: /usr/local/mysql/lib/mysql/libz.so.1: no version information available (required by git)
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `/usr/local/rvm/gems/ruby-1.9.3-p448/bin/bundle install`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what actually happened was...

Error details

    ArgumentError: no HTTP request path given
      /usr/local/rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/net/http.rb:1860:in `initialize'
      /usr/local/rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/net/http.rb:2094:in `initialize'
      /usr/local/rvm/gems/ruby-1.9.3-p448/gems/bundler-1.10.6/lib/bundler/fetcher/downloader.rb:39:in `new'
      /usr/local/rvm/gems/ruby-1.9.3-p448/gems/bundler-1.10.6/lib/bundler/fetcher/downloader.rb:39:in `request'
      /usr/local/rvm/gems/ruby-1.9.3-p448/gems/bundler-1.10.6/lib/bundler/fetcher/downloader.rb:15:in `fetch'
      /usr/local/rvm/gems/ruby-1.9.3-p448/gems/bundler-1.10.6/lib/bundler/fetcher/dependency.rb:7:in `api_available?'
      /usr/local/rvm/gems/ruby-1.9.3-p448/gems/bundler-1.10.6/lib/bundler/fetcher.rb:135:in `block in use_api'
      /usr/local/rvm/gems/ruby-1.9.3-p448/gems/bundler-1.10.6/lib/bundler/fetcher.rb:135:in `reject!'
      /usr/local/rvm/gems/ruby-1.9.3-p448/gems/bundler-1.10.6/lib/bundler/fetcher.rb:135:in `use_api'
      /usr/local/rvm/gems/ruby-1.9.3-p448/gems/bundler-1.10.6/lib/bundler/source/rubygems.rb:320:in `select'
      /usr/local/rvm/gems/ruby-1.9.3-p448/gems/bundler-1.10.6/lib/bundler/source/rubygems.rb:320:in `api_fetchers'
      /usr/local/rvm/gems/ruby-1.9.3-p448/gems/bundler-1.10.6/lib/bundler/source/rubygems.rb:325:in `block in remote_specs'
      /usr/local/rvm/gems/ruby-1.9.3-p448/gems/bundler-1.10.6/lib/bundler/index.rb:9:in `build'
      /usr/local/rvm/gems/ruby-1.9.3-p448/gems/bundler-1.10.6/lib/bundler/source/rubygems.rb:324:in `remote_specs'
      /usr/local/rvm/gems/ruby-1.9.3-p448/gems/bundler-1.10.6/lib/bundler/source/rubygems.rb:81:in `specs'
      /usr/local/rvm/gems/ruby-1.9.3-p448/gems/bundler-1.10.6/lib/bundler/definition.rb:211:in `block (2 levels) in index'
      /usr/local/rvm/gems/ruby-1.9.3-p448/gems/bundler-1.10.6/lib/bundler/definition.rb:209:in `each'
      /usr/local/rvm/gems/ruby-1.9.3-p448/gems/bundler-1.10.6/lib/bundler/definition.rb:209:in `block in index'
      /usr/local/rvm/gems/ruby-1.9.3-p448/gems/bundler-1.10.6/lib/bundler/index.rb:9:in `build'
      /usr/local/rvm/gems/ruby-1.9.3-p448/gems/bundler-1.10.6/lib/bundler/definition.rb:206:in `index'
      /usr/local/rvm/gems/ruby-1.9.3-p448/gems/bundler-1.10.6/lib/bundler/definition.rb:200:in `resolve'
      /usr/local/rvm/gems/ruby-1.9.3-p448/gems/bundler-1.10.6/lib/bundler/definition.rb:140:in `specs'
      /usr/local/rvm/gems/ruby-1.9.3-p448/gems/bundler-1.10.6/lib/bundler/definition.rb:129:in `resolve_remotely!'
      /usr/local/rvm/gems/ruby-1.9.3-p448/gems/bundler-1.10.6/lib/bundler/installer.rb:79:in `run'
      /usr/local/rvm/gems/ruby-1.9.3-p448/gems/bundler-1.10.6/lib/bundler/installer.rb:18:in `install'
      /usr/local/rvm/gems/ruby-1.9.3-p448/gems/bundler-1.10.6/lib/bundler/cli/install.rb:107:in `run'
      /usr/local/rvm/gems/ruby-1.9.3-p448/gems/bundler-1.10.6/lib/bundler/cli.rb:162:in `install'
      /usr/local/rvm/gems/ruby-1.9.3-p448/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /usr/local/rvm/gems/ruby-1.9.3-p448/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /usr/local/rvm/gems/ruby-1.9.3-p448/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /usr/local/rvm/gems/ruby-1.9.3-p448/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /usr/local/rvm/gems/ruby-1.9.3-p448/gems/bundler-1.10.6/lib/bundler/cli.rb:10:in `start'
      /usr/local/rvm/gems/ruby-1.9.3-p448/gems/bundler-1.10.6/bin/bundle:20:in `block in <top (required)>'
      /usr/local/rvm/gems/ruby-1.9.3-p448/gems/bundler-1.10.6/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
      /usr/local/rvm/gems/ruby-1.9.3-p448/gems/bundler-1.10.6/bin/bundle:18:in `<top (required)>'
      /usr/local/rvm/gems/ruby-1.9.3-p448/bin/bundle:23:in `load'
      /usr/local/rvm/gems/ruby-1.9.3-p448/bin/bundle:23:in `<main>'

Environment

    Bundler   1.10.6
    Rubygems  2.4.8
    Ruby      1.9.3p448 (2013-06-27 revision 41675) [x86_64-linux]
    GEM_HOME  /usr/local/rvm/gems/ruby-1.9.3-p448
    GEM_PATH  /usr/local/rvm/gems/ruby-1.9.3-p448:/usr/local/rvm/gems/ruby-1.9.3-p448@global
    RVM       1.22.1 (stable)
    Git       1.7.1

Bundler settings

    without
      Set for your local app (/usr/local/redmine-2.6.6/.bundle/config): "postgresql:rmagick:development:test:sqlite"
--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/bundler/bundler/search?q=no+HTTP+request+path+given&type=Issues

If there aren't any reports for this error yet, please create copy and paste the report template above into a new issue. Don't forget to anonymize any private data! The new issue form is located at:
https://github.com/bundler/bundler/issues/new

**Comment by segiddins** [comment]
@0704681032 can you please also share your Gemfile? Thanks!

**Comment by agis-** [comment]
@0704681032 Closing this due to lack of feedback. Feel free to share more information and I'll be happy to reopen.
