### ISSUE TITLE
bundle command throws error

### ISSUE THREAD

**Issue by Scosentino** [bundler/bundler#3925]
- What did you do?
- What did you expect to happen?
- What happened instead?

Error details

    ArgumentError: no HTTP request path given
    /usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/net/http/generic_request.rb:24:in `initialize'
    /usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/net/http/request.rb:14:in `initialize'
    /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.9.4/lib/bundler/fetcher.rb:294:in `new'
    /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.9.4/lib/bundler/fetcher.rb:294:in `request'
    /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.9.4/lib/bundler/fetcher.rb:270:in `fetch'
    /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.9.4/lib/bundler/fetcher.rb:242:in `use_api'
    /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.9.4/lib/bundler/source/rubygems.rb:301:in `block in api_fetchers'
    /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.9.4/lib/bundler/source/rubygems.rb:301:in `select'
    /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.9.4/lib/bundler/source/rubygems.rb:301:in `api_fetchers'
    /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.9.4/lib/bundler/source/rubygems.rb:306:in `block in remote_specs'
    /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.9.4/lib/bundler/index.rb:9:in `build'
    /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.9.4/lib/bundler/source/rubygems.rb:305:in `remote_specs'
    /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.9.4/lib/bundler/source/rubygems.rb:79:in `specs'
    /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.9.4/lib/bundler/definition.rb:204:in `block (2 levels) in index'
    /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.9.4/lib/bundler/definition.rb:202:in `each'
    /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.9.4/lib/bundler/definition.rb:202:in `block in index'
    /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.9.4/lib/bundler/index.rb:9:in `build'
    /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.9.4/lib/bundler/definition.rb:199:in `index'
    /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.9.4/lib/bundler/definition.rb:193:in `resolve'
    /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.9.4/lib/bundler/definition.rb:132:in `specs'
    /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.9.4/lib/bundler/definition.rb:121:in `resolve_remotely!'
    /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.9.4/lib/bundler/installer.rb:79:in `run'
    /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.9.4/lib/bundler/installer.rb:18:in `install'
    /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.9.4/lib/bundler/cli/install.rb:80:in `run'
    /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.9.4/lib/bundler/cli.rb:157:in `install'
    /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.9.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
    /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.9.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
    /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.9.4/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
    /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.9.4/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
    /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.9.4/lib/bundler/cli.rb:10:in `start'
    /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.9.4/bin/bundle:20:in `block in <top (required)>'
    /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.9.4/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
    /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.9.4/bin/bundle:18:in `<top (required)>'
    /usr/local/bin/bundle:23:in `load'
    /usr/local/bin/bundle:23:in `<main>'

Environment

    Bundler   1.9.4
    Rubygems  2.4.5
    Ruby      2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]
    GEM_HOME  /usr/local/lib/ruby/gems/2.2.0
    GEM_PATH  /usr/local/lib/ruby/gems/2.2.0:/Users/Scosentino/.gem/ruby/2.2.0:/usr/local/Cellar/ruby/2.2.2/lib/ruby/gems/2.2.0
    Git       2.3.5

You can find the repo here https://github.com/Scosentino/towboatislamorada

**Comment by Scosentino** [comment]
Im trying to deploy to heroku and heroku tells me i need a Gemfile.lock but when i try to run the bundle command i get the above error

**Comment by segiddins** [comment]
Can you please share your Gemfile? Thanks!

**Comment by Scosentino** [comment]
source "https:rubygems.org"
ruby "2.2.2"
gem 'sinatra'

**Comment by segiddins** [comment]
Ah looks like we need to do a better job validating source URLs to show a nice error. Thanks!

**Comment by segiddins** [comment]
(You can fix things yourself in the meantime by changing the URL to be a valid one, `https://rubygems.org`)

**Comment by Scosentino** [comment]
Great!! Can I help write the contributing code? Or get some kind of credit

**Comment by Scosentino** [comment]
:)

**Comment by segiddins** [comment]
Feel free :) The change will _probably_ be somewhere in `lib/bundler/source/rubygems.rb` to validate the URL

**Comment by Scosentino** [comment]
A bit beyond my level.. lol maybe next time

**Comment by agis-** [comment]
@segiddins Hello! I took a shot and opened a PR. Doing this in the `Downloader` seemed better to me since this case could also be non-rubygems specific. Not sure if this is the correct way though as I'm unfamiliar with the codebase.
