### ISSUE TITLE
bundler hangs indefinitely with no output 

### ISSUE THREAD

**Issue by pik** [bundler/bundler#3926]
I'm running `bundle exec rails console` in my project's root directory. Here is the dtruss output: 

https://gist.github.com/pik/e15fd230524d0a1e01e2

**Comment by indirect** [comment]
Please provide the output of `bundle env`, as well as the backtrack that prints when you press control-c.

**Comment by agis-** [comment]
Closing this since we haven't received any further feedback. We'll be glad to reopen if we receive further info.
