### ISSUE TITLE
Bundler Truck Factor

### ISSUE THREAD

**Issue by gavelino** [bundler/bundler#3931]
As part of my PhD research on code authorship, we calculated the Truck Factor (TF) of some popular GitHub repositories.

As you probably know, the [Truck (or Bus) Factor](https://en.wikipedia.org/wiki/Bus_factor) designates the minimal number of developers that have to be hit by a truck (or quit) before a project is incapacitated. In our work, we consider that a system is in trouble if more than 50% of its files become orphan (i.e., without a main author).

More details on our work in this preprint: https://peerj.com/preprints/1233

We calculated the TF for **Bundler** and obtained a value of **3**.

The developers responsible for this TF are:

Andre Arko - author of 62% of the files
Carl Lerche - author of 19% of the files
Terence Lee - author of 15% of the files

To validate our results, we would like to ask **Bundler** developers the following three brief questions:

(a) Do you agree that the listed developers are the main developers of **Bundler**?

(b) Do you agree that **Bundler** will be in trouble if the listed developers leave the project (e.g., if they win in the lottery, to be less morbid)?

(c) Does **Bundler** have some characteristics that would attenuate the loss of the listed developers (e.g., detailed documentation)?

Thanks in advance for your collaboration,

Guilherme Avelino
PhD Student
Applied Software Engineering Group (ASERG)
UFMG, Brazil
http://aserg.labsoft.dcc.ufmg.br/

**Comment by segiddins** [comment]
Bundler's issue tracker is for tracking bugs reported against the Bundler codebase, so I'm going to close this as out-of-scope and off-topic.
