### ISSUE TITLE
Errno::EPROTO: Protocol error - /vagrant/vendor /ruby

### ISSUE THREAD

**Issue by bibarCB** [bundler/bundler#3932]
- What did you do?

  I ran the command `/home/vagrant/.rvm/gems/ruby-2.0.0-p247/bin/bundle `

- What did you expect to happen?

  I expected Bundler to bundle on vagrant!

- What happened instead?

  Instead, what actually happened was this error below

Error details

    Errno::EPROTO: Protocol error - /vagrant/vendor /ruby
      /home/vagrant/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/fileutils.rb:245:in `mkdir'
      /home/vagrant/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/fileutils.rb:245:in `fu_mkdir'
      /home/vagrant/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/fileutils.rb:219:in `block (2 levels) in mkdir_p'
      /home/vagrant/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/fileutils.rb:217:in `reverse_each'
      /home/vagrant/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/fileutils.rb:217:in `block in mkdir_p'
      /home/vagrant/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/fileutils.rb:203:in `each'
      /home/vagrant/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/fileutils.rb:203:in `mkdir_p'
      /home/vagrant/.rvm/gems/ruby-2.0.0-p247/gems/bundler-1.10.6/lib/bundler.rb:308:in `mkdir_p'
      /home/vagrant/.rvm/gems/ruby-2.0.0-p247/gems/bundler-1.10.6/lib/bundler/installer.rb:278:in `create_bundle_path'
      /home/vagrant/.rvm/gems/ruby-2.0.0-p247/gems/bundler-1.10.6/lib/bundler/installer.rb:54:in `run'
      /home/vagrant/.rvm/gems/ruby-2.0.0-p247/gems/bundler-1.10.6/lib/bundler/installer.rb:18:in `install'
      /home/vagrant/.rvm/gems/ruby-2.0.0-p247/gems/bundler-1.10.6/lib/bundler/cli/install.rb:107:in `run'
      /home/vagrant/.rvm/gems/ruby-2.0.0-p247/gems/bundler-1.10.6/lib/bundler/cli.rb:162:in `install'
      /home/vagrant/.rvm/gems/ruby-2.0.0-p247/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /home/vagrant/.rvm/gems/ruby-2.0.0-p247/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /home/vagrant/.rvm/gems/ruby-2.0.0-p247/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /home/vagrant/.rvm/gems/ruby-2.0.0-p247/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /home/vagrant/.rvm/gems/ruby-2.0.0-p247/gems/bundler-1.10.6/lib/bundler/cli.rb:10:in `start'
      /home/vagrant/.rvm/gems/ruby-2.0.0-p247/gems/bundler-1.10.6/bin/bundle:20:in `block in <top (required)>'
      /home/vagrant/.rvm/gems/ruby-2.0.0-p247/gems/bundler-1.10.6/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
      /home/vagrant/.rvm/gems/ruby-2.0.0-p247/gems/bundler-1.10.6/bin/bundle:18:in `<top (required)>'
      /home/vagrant/.rvm/gems/ruby-2.0.0-p247/bin/bundle:23:in `load'
      /home/vagrant/.rvm/gems/ruby-2.0.0-p247/bin/bundle:23:in `<main>'
      /home/vagrant/.rvm/gems/ruby-2.0.0-p247/bin/ruby_executable_hooks:15:in `eval'
      /home/vagrant/.rvm/gems/ruby-2.0.0-p247/bin/ruby_executable_hooks:15:in `<main>'

Environment

    Bundler   1.10.6
    Rubygems  2.0.3
    Ruby      2.0.0p247 (2013-06-27 revision 41674) [i686-linux]
    GEM_HOME  /vagrant/vendor /ruby/2.0.0
    GEM_PATH
    RVM       1.26.11 (latest)
    Git       1.7.9.5

Bundler settings

    path
      Set for your local app (/vagrant/.bundle/config): "vendor "
    bin
      Set for your local app (/vagrant/.bundle/config): "bin "
    disable_shared_gems
      Set for your local app (/vagrant/.bundle/config): "1"

**Comment by segiddins** [comment]
I think the issue here is that your `GEM_HOME` has an extra space in it?

**Comment by agis-** [comment]
@bibarCB Hey, any updates on this? Has what @segiddins suggested solved your issue?

**Comment by agis-** [comment]
Closing this due to lack of feedback. Feel free to share more info and I'll happily reopen.
