### ISSUE TITLE
git push heroku master for ruby on rail don't work 

### ISSUE THREAD

**Issue by cannele75000** [bundler/bundler#3940]
Hi, 

I'm trying to deployng code to Heroku, but it's fail and i can't fix it. Can you help me please (sorry for my english)

iMacdeemmak:first_app$ git push heroku master
Counting objects: 64, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (53/53), done.
Writing objects: 100% (64/64), 16.47 KiB | 0 bytes/s, done.
Total 64 (delta 2), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Ruby app detected
remote: -----> Compiling Ruby/Rails
remote: -----> Using Ruby version: ruby-2.0.0
remote: -----> Installing dependencies using 1.9.7
remote:        Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
remote:        Fetching gem metadata from https://rubygems.org/...........
remote:        Fetching version metadata from https://rubygems.org/...
remote:        Fetching dependency metadata from https://rubygems.org/..
remote:        Rubygems 2.0.14 is not threadsafe, so your gems must be installed one at a time. Upgrade to Rubygems 2.1.0 or higher to enable parallel gem installation.
remote:        Installing rake 10.4.2
remote:        Installing i18n 0.7.0
remote:        Installing json 1.8.3
remote:        Installing minitest 5.8.0
remote:        Installing thread_safe 0.3.5
remote:        Installing tzinfo 1.2.2
remote:        Installing activesupport 4.2.3
remote:        Installing builder 3.2.2
remote:        Installing erubis 2.7.0
remote:        Installing mini_portile 0.6.2
remote:        Installing nokogiri 1.6.6.2
remote:        Installing rails-deprecated_sanitizer 1.0.3
remote:        Installing rails-dom-testing 1.0.6
remote:        Installing loofah 2.0.2
remote:        Installing rails-html-sanitizer 1.0.2
remote:        Installing actionview 4.2.3
remote:        Installing rack 1.6.4
remote:        Installing rack-test 0.6.3
remote:        Installing actionpack 4.2.3
remote:        Installing globalid 0.3.6
remote:        Installing activejob 4.2.3
remote:        Installing mime-types 2.6.1
remote:        Installing mail 2.6.3
remote:        Installing actionmailer 4.2.3
remote:        Installing activemodel 4.2.3
remote:        Installing arel 6.0.3
remote:        Installing activerecord 4.2.3
remote:        Installing coffee-script-source 1.9.1.1
remote:        Installing execjs 2.5.2
remote:        Installing coffee-script 2.4.1
remote:        Installing thor 0.19.1
remote:        Installing railties 4.2.3
remote:        Installing coffee-rails 4.1.0
remote:        Installing multi_json 1.11.2
remote:        Installing jbuilder 2.3.1
remote:        Installing jquery-rails 4.0.4
remote:        Using bundler 1.9.7
remote:        Installing sprockets 3.2.0
remote:        Installing sprockets-rails 2.3.2
remote:        Installing rails 4.2.3
remote:        Installing rdoc 4.2.0
remote:        Installing sass 3.4.16
remote:        Installing tilt 1.4.1
remote:        Installing sass-rails 5.0.3
remote:        Installing sdoc 0.4.1
remote:        Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.
remote:        /tmp/build_00b01dcc5aed9f98559c1cd78ce93d6d/vendor/ruby-2.0.0/bin/ruby extconf.rb
remote:        checking for sqlite3.h... no
remote:        sqlite3.h is missing. Try 'port install sqlite3 +universal',
remote:        'yum install sqlite-devel' or 'apt-get install libsqlite3-dev'
remote:        and check your shared library search path (the
remote:        location where your sqlite3 shared library is located).
remote:        *** extconf.rb failed ***
remote:        Could not create Makefile due to some reason, probably lack of necessary
remote:        libraries and/or headers.  Check the mkmf.log file for more details.  You may
remote:        need configuration options.
remote:        Provided configuration options:
remote:        --with-opt-dir
remote:        --without-opt-dir
remote:        --with-opt-include
remote:        --without-opt-include=${opt-dir}/include
remote:        --with-opt-lib
remote:        --without-opt-lib=${opt-dir}/lib
remote:        --with-make-prog
remote:        --without-make-prog
remote:        --srcdir=.
remote:        --curdir
remote:        --ruby=/tmp/build_00b01dcc5aed9f98559c1cd78ce93d6d/vendor/ruby-2.0.0/bin/ruby
remote:        --with-sqlite3-dir
remote:        --without-sqlite3-dir
remote:        --with-sqlite3-include
remote:        --without-sqlite3-include=${sqlite3-dir}/include
remote:        --with-sqlite3-lib
remote:        --without-sqlite3-lib=${sqlite3-dir}/
remote:        Gem files will remain installed in /tmp/build_00b01dcc5aed9f98559c1cd78ce93d6d/vendor/bundle/ruby/2.0.0/gems/sqlite3-1.3.10 for inspection.
remote:        Results logged to /tmp/build_00b01dcc5aed9f98559c1cd78ce93d6d/vendor/bundle/ruby/2.0.0/gems/sqlite3-1.3.10/ext/sqlite3/gem_make.out
remote:        An error occurred while installing sqlite3 (1.3.10), and Bundler cannot
remote:        continue.
remote:        Make sure that `gem install sqlite3 -v '1.3.10'` succeeds before bundling.
remote:        Bundler Output: Fetching gem metadata from https://rubygems.org/...........
remote:        Fetching version metadata from https://rubygems.org/...
remote:        Fetching dependency metadata from https://rubygems.org/..
remote:        Rubygems 2.0.14 is not threadsafe, so your gems must be installed one at a time. Upgrade to Rubygems 2.1.0 or higher to enable parallel gem installation.
remote:        Installing rake 10.4.2
remote:        Installing i18n 0.7.0
remote:        Installing json 1.8.3
remote:        Installing minitest 5.8.0
remote:        Installing thread_safe 0.3.5
remote:        Installing tzinfo 1.2.2
remote:        Installing activesupport 4.2.3
remote:        Installing builder 3.2.2
remote:        Installing erubis 2.7.0
remote:        Installing mini_portile 0.6.2
remote:        Installing nokogiri 1.6.6.2
remote:        Installing rails-deprecated_sanitizer 1.0.3
remote:        Installing rails-dom-testing 1.0.6
remote:        Installing loofah 2.0.2
remote:        Installing rails-html-sanitizer 1.0.2
remote:        Installing actionview 4.2.3
remote:        Installing rack 1.6.4
remote:        Installing rack-test 0.6.3
remote:        Installing actionpack 4.2.3
remote:        Installing globalid 0.3.6
remote:        Installing activejob 4.2.3
remote:        Installing mime-types 2.6.1
remote:        Installing mail 2.6.3
remote:        Installing actionmailer 4.2.3
remote:        Installing activemodel 4.2.3
remote:        Installing arel 6.0.3
remote:        Installing activerecord 4.2.3
remote:        Installing coffee-script-source 1.9.1.1
remote:        Installing execjs 2.5.2
remote:        Installing coffee-script 2.4.1
remote:        Installing thor 0.19.1
remote:        Installing railties 4.2.3
remote:        Installing coffee-rails 4.1.0
remote:        Installing multi_json 1.11.2
remote:        Installing jbuilder 2.3.1
remote:        Installing jquery-rails 4.0.4
remote:        Using bundler 1.9.7
remote:        Installing sprockets 3.2.0
remote:        Installing sprockets-rails 2.3.2
remote:        Installing rails 4.2.3
remote:        Installing rdoc 4.2.0
remote:        Installing sass 3.4.16
remote:        Installing tilt 1.4.1
remote:        Installing sass-rails 5.0.3
remote:        Installing sdoc 0.4.1
remote:        
remote:        Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.
remote:        
remote:        /tmp/build_00b01dcc5aed9f98559c1cd78ce93d6d/vendor/ruby-2.0.0/bin/ruby extconf.rb
remote:        checking for sqlite3.h... no
remote:        sqlite3.h is missing. Try 'port install sqlite3 +universal',
remote:        'yum install sqlite-devel' or 'apt-get install libsqlite3-dev'
remote:        and check your shared library search path (the
remote:        location where your sqlite3 shared library is located).
remote:        *** extconf.rb failed ***
remote:        Could not create Makefile due to some reason, probably lack of necessary
remote:        libraries and/or headers.  Check the mkmf.log file for more details.  You may
remote:        need configuration options.
remote:        
remote:        Provided configuration options:
remote:        --with-opt-dir
remote:        --without-opt-dir
remote:        --with-opt-include
remote:        --without-opt-include=${opt-dir}/include
remote:        --with-opt-lib
remote:        --without-opt-lib=${opt-dir}/lib
remote:        --with-make-prog
remote:        --without-make-prog
remote:        --srcdir=.
remote:        --curdir
remote:        --ruby=/tmp/build_00b01dcc5aed9f98559c1cd78ce93d6d/vendor/ruby-2.0.0/bin/ruby
remote:        --with-sqlite3-dir
remote:        --without-sqlite3-dir
remote:        --with-sqlite3-include
remote:        --without-sqlite3-include=${sqlite3-dir}/include
remote:        --with-sqlite3-lib
remote:        --without-sqlite3-lib=${sqlite3-dir}/
remote:        
remote:        
remote:        Gem files will remain installed in /tmp/build_00b01dcc5aed9f98559c1cd78ce93d6d/vendor/bundle/ruby/2.0.0/gems/sqlite3-1.3.10 for inspection.
remote:        Results logged to /tmp/build_00b01dcc5aed9f98559c1cd78ce93d6d/vendor/bundle/ruby/2.0.0/gems/sqlite3-1.3.10/ext/sqlite3/gem_make.out
remote:        An error occurred while installing sqlite3 (1.3.10), and Bundler cannot
remote:        continue.
remote:        Make sure that `gem install sqlite3 -v '1.3.10'` succeeds before bundling.
remote:  !
remote:  !     Failed to install gems via Bundler.
remote:  !     
remote:  !     Detected sqlite3 gem which is not supported on Heroku.
remote:  !     https://devcenter.heroku.com/articles/sqlite3
remote:  !
remote: 
remote:  !     Push rejected, failed to compile Ruby app
remote: 
remote: Verifying deploy....
remote: 
remote: !	Push rejected to secret-forest-4173.
remote: 
To https://git.heroku.com/secret-forest-4173.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/secret-forest-4173.git'
iMacdeemmak:first_app$ 

Thanks for you help
Cannele

**Comment by segiddins** [comment]
This looks like user error, since the Heroku's error message includes the following:

```
Detected sqlite3 gem which is not supported on Heroku.
https://devcenter.heroku.com/articles/sqlite3
```

**Comment by cannele75000** [comment]
And what is the solution ? please

**Comment by segiddins** [comment]
I'd recommend reading the page heroic links to

**Comment by cannele75000** [comment]
ok thank you very much
