### ISSUE TITLE
ronn still uses hpricot

### ISSUE THREAD

**Issue by zeha** [bundler/bundler#3946]
Dear Bundler team,

I want to bring to your attention that the documentation tool https://github.com/rtomayko/ronn/ which you're depending on still uses https://github.com/hpricot/hpricot which - as you likely know - is unmaintained.

Please find a solution to this, as we (Debian) don't want to ship unmaintained and broken libraries like hpricot forever.

Many thanks,
Christian

**Comment by indirect** [comment]
It's a development dependency, to generate help files that are shipped inside the Bundler gem. You should never have been shipping either ronn or hpricot in the first place.

**Comment by zeha** [comment]
We're not supposed to ship pre-generated files, so we do need to ship ronn and hpricot at the moment.

**Comment by indirect** [comment]
Sounds like your (Debian's) problem, then, because we (Bundler) don't want anyone to install or use hpricot themselves.

**Comment by zeha** [comment]
Alright, but then we're not going to ship man pages with bundler.

**Comment by zeha** [comment]
(We don't have the manpower to fix ronn or hpricot ourselves.)

**Comment by indirect** [comment]
Punishing end users as a result of rigid packaging rules that don't make sense for gems sounds like every distro I've had the misfortune to interact with so far.

The Bundler team does not advise (or even support) using Bundler from distro packages, only installed via Rubygems. You (Debian) decided to make changes to the gem, therefore you (Debian) need to deal with and support the consequences of that decision.

I don't know where you got the idea that we have the manpower to fix ronn or hpricot, but we don't.

**Comment by zeha** [comment]
I agree that it's unfortunate, but I can't ship stuff where it's not clear how it's built (this isn't a packaging rule, but comes from the freedom we want to guarantee our users and downstreams). But let's not make this a distro flamewar.
We actually don't really want to ship Bundler in the first place, but given other packages (i.e. rails and many others) directly make use of Bundler, we don't have a choice.

I had hoped that you could either use another tool, or maybe talk someone else into fixing ronn, as you're likely to have way more influence :)

**Comment by segiddins** [comment]
Bundler never has and probably never will support any method of installation that is not RubyGems. I'm sorry if that's incompatible with how you want to manage your own packaging, but at the end of the day this is the very reason why Bundler only supports installation via RubyGems -- it eliminates all of those problems.

**Comment by zeha** [comment]
Fair enough!
