### ISSUE TITLE
I am not a social warrior

### ISSUE THREAD

**Issue by fdutey** [bundler/bundler#3949]
I was very happy to discover your "anti-harassment" suggestion with a link pointing to feminist forum. 
Now, I'm not one of those intellectual terrorist, but to speak a language you understand: I am deeply offended by that, can you remove that from `bundle gem` command? 
I don't like to have fascist messages appearing on my screen when I'm coding.

Thanks.

**Comment by simi** [comment]
You mean https://github.com/bundler/bundler/blob/301bec2f2c636372d2c4a16e5b41b9ced08935b6/lib/bundler/cli/gem.rb#L99-L108?

**Comment by segiddins** [comment]
@fdutey this sort of issue is not appropriate. You're completely at liberty to decide whether or not `bundle gem` generates a CoC (and of course are free to delete if you you accidentally say yes). It's quite honestly impossible to be offended by offering you the choice of including a text file in your gem.
