### ISSUE TITLE
Getting strange error when running `bundle`

### ISSUE THREAD

**Issue by ulrikaugustsson** [bundler/bundler#3951]
Disclaimer: I'm not a rubyist, just helping a friend out with some frontend stuff.

- What did you do?

  I ran the command `/home/ulrik/.rbenv/versions/1.9.3-p551/bin/bundle `

- What did you expect to happen?

  Run...

- What happened instead?

  Fat error

Error details

    NoMethodError: undefined method `dependencies' for nil:NilClass
      /home/ulrik/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/index.rb:133:in `block in =='
      /home/ulrik/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/index.rb:94:in `each'
      /home/ulrik/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/index.rb:94:in `block in each'
      /home/ulrik/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/index.rb:93:in `each'
      /home/ulrik/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/index.rb:93:in `each'
      /home/ulrik/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/index.rb:131:in `all?'
      /home/ulrik/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/index.rb:131:in `=='
      /home/ulrik/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/definition.rb:445:in `!='
      /home/ulrik/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/definition.rb:445:in `specs_changed?'
      /home/ulrik/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/definition.rb:477:in `block in converge_paths'
      /home/ulrik/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/definition.rb:476:in `each'
      /home/ulrik/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/definition.rb:476:in `any?'
      /home/ulrik/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/definition.rb:476:in `converge_paths'
      /home/ulrik/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/definition.rb:93:in `initialize'
      /home/ulrik/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/dsl.rb:166:in `new'
      /home/ulrik/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/dsl.rb:166:in `to_definition'
      /home/ulrik/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/dsl.rb:11:in `evaluate'
      /home/ulrik/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/definition.rb:26:in `build'
      /home/ulrik/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/bundler-1.10.6/lib/bundler.rb:155:in `definition'
      /home/ulrik/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/cli/install.rb:104:in `run'
      /home/ulrik/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/cli.rb:162:in `install'
      /home/ulrik/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /home/ulrik/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /home/ulrik/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /home/ulrik/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /home/ulrik/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/cli.rb:10:in `start'
      /home/ulrik/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/bundler-1.10.6/bin/bundle:20:in `block in <top (required)>'
      /home/ulrik/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
      /home/ulrik/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/bundler-1.10.6/bin/bundle:18:in `<top (required)>'
      /home/ulrik/.rbenv/versions/1.9.3-p551/bin/bundle:23:in `load'
      /home/ulrik/.rbenv/versions/1.9.3-p551/bin/bundle:23:in `<main>'

Environment

    Bundler   1.10.6
    Rubygems  1.8.23.2
    Ruby      1.9.3p551 (2014-11-13 revision 48407) [x86_64-linux]
    GEM_HOME  /home/ulrik/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1
    GEM_PATH  /home/ulrik/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1:/home/ulrik/.gem/ruby/1.9.1
    Git       2.1.4

**Comment by ulrikaugustsson** [comment]
Gemfile
```rb
source 'https://rubygems.org'

ruby '1.9.3' # also specified in .ruby-version

gem 'rails', '~> 3.2'
gem 'pg'

gem 'formtastic', '~> 2.0'
gem 'simple_form'
gem 'devise'
gem 'puma'
gem 'newrelic_rpm'

gem 'jquery-rails', '~> 2.0.0'
gem 'bootstrap-sass', '~> 2.3.0'
gem 'tinymce-rails', '~> 3.5'
gem 'delayed_job_active_record'

gem 'refinerycms', '~> 2.0'
gem 'refinerycms-i18n', '~> 2.0'
gem 'refinerycms-courses', '1.0', path: 'vendor/extensions'
gem 'refinerycms-page_notifications', '1.0', path: 'vendor/extensions'

gem 'forem', git: 'git://github.com/radar/forem.git'

group :assets do
  gem 'sass-rails', '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end

group :production do
  gem 'fog'
  gem 'aws-ses', '~> 0.4.4', require: 'aws/ses'
  gem 'exception_notification', '2.6.1'
  gem 'newrelic_rpm'
  gem 'rails_12factor'
end

group :test do
  gem 'minitest'
  gem 'capybara', '~> 2.0'
  gem 'launchy'
end
```

**Comment by ulrikaugustsson** [comment]
I get pretty much the same error when running `rails server`

**Comment by agis-** [comment]
@ulrikaugustsson Can you post your Gemfile.lock?

**Comment by agis-** [comment]
I've tried reproducing the issue. Some of the gems listed in the Gemfile depend on ruby 2, so bundler cannot resolve them (eg. `babosa`).

Can you post your Gemfile.lock?

**Comment by ulrikaugustsson** [comment]
We found out there seems to be some backward incompatability somewhere. Closing the issue.
