### ISSUE TITLE
bundler doesn't resolve dependencies coming from git repositories

### ISSUE THREAD

**Issue by x-yuri** [bundler/bundler#3953]
Consider the following `Gemfile`:

```
source 'https://rubygems.org'
gem 'pry-byebug'
gem 'byebug', github: 'deivid-rodriguez/byebug'
```

It fails with:

```
Could not find gem 'byebug (~> 4.0) ruby', which is required by gem 'pry-byebug (>= 0) ruby', in any of the sources.
```

**Comment by segiddins** [comment]
When you specify a git source, bundle will only consider the exact source you've specified.

**Comment by indirect** [comment]
Byebug in that git repo is version 6.0.2. The pry-byebug gem requires byebug > 4 but < 5. There is no byebug gem > 4 and < 5 in the git repo. This isn't a bug.

**Comment by x-yuri** [comment]
I see, I didn't notice `pry-byebug` I have in `Gemfile.lock` requires `byebug ~> 4.0`.

I thought it requires as fresh version of `byebug` as possible. And gems from git sources don't have version associated with them. Which prevents `bundler` from resolving dependencies. Which turned out to be wrong.
