### ISSUE TITLE
bundle exec prevents STDOUT from being piped?

### ISSUE THREAD

**Issue by frrisus** [bundler/bundler#3962]
Filed this on the libxml-ruby gem, but I'm guessing that's the wrong place for it. (See https://github.com/xml4r/libxml-ruby/issues/109)

The symptom is this: While running under `bundle exec`, if I create an XML document using the libxml-ruby gem and use puts to write it to STDOUT, it does so. However, if I try to pipe or redirect the output of the script, it writes nothing. If I run the script directly without `bundle exec`, everything works fine.

I originally found this problem with bundler 1.9.3 and ruby 2.2.2. It is not reproducible under ruby 2.1.5 but is reproducible with bundler 1.10 and ruby 2.2.3, as seen here: 
```
Environment

    Bundler   1.10.6
    Rubygems  2.4.8
    Ruby      2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux]
    GEM_HOME  /home/becordes/.rvm/gems/ruby-2.2.3@global
    RVM       1.26.11 (latest)
    Git       2.1.0

Gemfile

    source 'https://rubygems.org'
    gem 'libxml-ruby'

Gemfile.lock

    GEM
      remote: https://rubygems.org/
      specs:
        libxml-ruby (2.8.0)
    
    PLATFORMS
      ruby
    
    DEPENDENCIES
      libxml-ruby
    
    BUNDLED WITH
       1.10.6
```
Here's my test script:
```ruby
#!/usr/bin/env ruby

require 'libxml'

d = LibXML::XML::Document::new
d.root = LibXML::XML::Node.new('configs')

puts d.to_s
```
And a console log showing the problem:
```
% ./test.rb
<?xml version="1.0" encoding="UTF-8"?>
<configs/>
% ./test.rb > foo
% cat foo
<?xml version="1.0" encoding="UTF-8"?>
<configs/>
% ls -l foo
-rw-r--r-- 1 becordes staff 50 Jun 18 16:12 foo
% rm foo
% bundle install
Fetching gem metadata from https://rubygems.org/..
Fetching version metadata from https://rubygems.org/.
Resolving dependencies...
Installing libxml-ruby 2.8.0 with native extensions
Using bundler 1.10.6
Bundle complete! 1 Gemfile dependency, 2 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
% bundle exec ./test.rb
<?xml version="1.0" encoding="UTF-8"?>
<configs/>
% bundle exec ./test.rb > foo
% cat foo
% ls -l foo
-rw-r--r-- 1 becordes staff 0 Jun 18 16:10 foo
```

**Comment by svallory** [comment]
"When you call `exec`, you create a new process, and although this process inherits the file you set as standard out, it doesn't inherit the other settings, in particular the sync setting.

In order to get unbuffered output in the new process, you need to set it in that process. If you don't want to modify `test.rb` one workaround could be to create another file, named somethig like `sync.rb` containing just:

`STDOUT.sync = true`

which you can then require when running your command:

`exec 'bundle exec ruby -r./sync test.rb'`

The new Ruby process will now require sync.rb, which simply sets sync mode on STDOUT to true before executing your script."

source: http://stackoverflow.com/questions/9949156/ruby-file-output-from-fork

**Comment by frrisus** [comment]
Yes, that's true. But the `exec` that they're referring to in that SO post is ruby's `exec`, not `bundle exec`. (Of course, maybe `bundle` is using ruby's `exec` under the hood...)

In my case, the problem isn't that the output is buffered but gets to STDOUT eventually, it's that the output never makes it back to STDOUT at all.

My understanding of buffered filehandles is that when they are closed -- which happens automatically when a process ends, no matter how it was started -- they flush themselves. Which means anything written to STDOUT that hadn't been flushed / synced will get flushed at the end of the script. But that data never shows up at all.

Is `bundle` doing some sort of STDOUT / filehandle manipulation behind the scenes on the child process? Or maybe ruby isn't quite cleaning up after itself like it should?

**Comment by svallory** [comment]
@frrisus you are right. I don't know if bundle does any magic and, in theory, you are right about getting all the unflushed data at the end. But I had the exact same problem you had. In my case it was a rake task.
going from `bundle exec rake ts:start` to `bundle exec rake -r ./sync-stdout.rb ts:start` solved it for me.

Maybe by syncing you get around of whatever voodoo bundle is making.

**Comment by indirect** [comment]
You may be interested in [--keep-file-descriptors](http://bundler.io/man/bundle-exec.1.html) and/or #2628. If you think you have a genuine bug, please follow [issues](https://github.com/bundler/bundler/blob/master/ISSUES.md)

**Comment by agis-** [comment]
Closing this due to lack of feedback. If you feel this is still an issue, please share more info and I'll reopen. Thanks!

**Comment by tgarnett** [comment]
Already closed, but I'll just note this is reproducible independently of bundler so is almost certainly a bug in the libxml gem.
