### ISSUE TITLE
Bundle install TypeError: no implicit conversion of Array into String

### ISSUE THREAD

**Issue by jfrioux** [bundler/bundler#3963]
I ran the command `/home/user/.rvm/gems/ruby-2.1.3/bin/bundle install`

I expected Bundler to install the gems specified in my gemfile

Instead, what actually happened was...

    TypeError: no implicit conversion of Array into String
      /home/user/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/rubygems/specification.rb:2448:in `directory?'
      /home/user/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/rubygems/specification.rb:2448:in `block in validate'
      /home/user/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/rubygems/specification.rb:2448:in `delete_if'
      /home/user/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/rubygems/specification.rb:2448:in `validate'
      /home/user/.rvm/gems/ruby-2.1.3/gems/bundler-1.10.6/lib/bundler/rubygems_integration.rb:51:in `block in validate'
      /home/user/.rvm/gems/ruby-2.1.3/gems/bundler-1.10.6/lib/bundler/ui/shell.rb:76:in `silence'
      /home/user/.rvm/gems/ruby-2.1.3/gems/bundler-1.10.6/lib/bundler/rubygems_integration.rb:51:in `validate'
      /home/user/.rvm/gems/ruby-2.1.3/gems/bundler-1.10.6/lib/bundler.rb:370:in `block in load_gemspec_uncached'
      /home/user/.rvm/gems/ruby-2.1.3/gems/bundler-1.10.6/lib/bundler/shared_helpers.rb:53:in `chdir'
      /home/user/.rvm/gems/ruby-2.1.3/gems/bundler-1.10.6/lib/bundler/shared_helpers.rb:53:in `block in chdir'
      /home/user/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
      /home/user/.rvm/gems/ruby-2.1.3/gems/bundler-1.10.6/lib/bundler/shared_helpers.rb:52:in `chdir'
      /home/user/.rvm/gems/ruby-2.1.3/gems/bundler-1.10.6/lib/bundler.rb:363:in `load_gemspec_uncached'
      /home/user/.rvm/gems/ruby-2.1.3/gems/bundler-1.10.6/lib/bundler.rb:353:in `load_gemspec'
      /home/user/.rvm/gems/ruby-2.1.3/gems/bundler-1.10.6/lib/bundler/source/path.rb:135:in `block in load_spec_files'
      /home/user/.rvm/gems/ruby-2.1.3/gems/bundler-1.10.6/lib/bundler/source/path.rb:134:in `each'
      /home/user/.rvm/gems/ruby-2.1.3/gems/bundler-1.10.6/lib/bundler/source/path.rb:134:in `load_spec_files'
      /home/user/.rvm/gems/ruby-2.1.3/gems/bundler-1.10.6/lib/bundler/source/path.rb:92:in `local_specs'
      /home/user/.rvm/gems/ruby-2.1.3/gems/bundler-1.10.6/lib/bundler/source/path.rb:100:in `specs'
      /home/user/.rvm/gems/ruby-2.1.3/gems/bundler-1.10.6/lib/bundler/definition.rb:550:in `block in converge_locked_specs'
      /home/user/.rvm/gems/ruby-2.1.3/gems/bundler-1.10.6/lib/bundler/definition.rb:539:in `each'
      /home/user/.rvm/gems/ruby-2.1.3/gems/bundler-1.10.6/lib/bundler/definition.rb:539:in `converge_locked_specs'
      /home/user/.rvm/gems/ruby-2.1.3/gems/bundler-1.10.6/lib/bundler/definition.rb:195:in `resolve'
      /home/user/.rvm/gems/ruby-2.1.3/gems/bundler-1.10.6/lib/bundler/definition.rb:140:in `specs'
      /home/user/.rvm/gems/ruby-2.1.3/gems/bundler-1.10.6/lib/bundler/definition.rb:129:in `resolve_remotely!'
      /home/user/.rvm/gems/ruby-2.1.3/gems/bundler-1.10.6/lib/bundler/installer.rb:79:in `run'
      /home/user/.rvm/gems/ruby-2.1.3/gems/bundler-1.10.6/lib/bundler/installer.rb:18:in `install'
      /home/user/.rvm/gems/ruby-2.1.3/gems/bundler-1.10.6/lib/bundler/cli/install.rb:107:in `run'
      /home/user/.rvm/gems/ruby-2.1.3/gems/bundler-1.10.6/lib/bundler/cli.rb:162:in `install'
      /home/user/.rvm/gems/ruby-2.1.3/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /home/user/.rvm/gems/ruby-2.1.3/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /home/user/.rvm/gems/ruby-2.1.3/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /home/user/.rvm/gems/ruby-2.1.3/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /home/user/.rvm/gems/ruby-2.1.3/gems/bundler-1.10.6/lib/bundler/cli.rb:10:in `start'
      /home/user/.rvm/gems/ruby-2.1.3/gems/bundler-1.10.6/bin/bundle:20:in `block in <top (required)>'
      /home/user/.rvm/gems/ruby-2.1.3/gems/bundler-1.10.6/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
      /home/user/.rvm/gems/ruby-2.1.3/gems/bundler-1.10.6/bin/bundle:18:in `<top (required)>'
      /home/user/.rvm/gems/ruby-2.1.3/bin/bundle:23:in `load'
      /home/user/.rvm/gems/ruby-2.1.3/bin/bundle:23:in `<main>'
      /home/user/.rvm/gems/ruby-2.1.3/bin/ruby_executable_hooks:15:in `eval'
      /home/user/.rvm/gems/ruby-2.1.3/bin/ruby_executable_hooks:15:in `<main>' `

Environment

    Bundler   1.10.6
    Rubygems  2.2.2
    Ruby      2.1.3p242 (2014-09-19 revision 47630) [x86_64-linux]
    GEM_HOME  /home/user/.rvm/gems/ruby-2.1.3
    GEM_PATH  /home/user/.rvm/gems/ruby-2.1.3:/home/user/.rvm/gems/ruby-2.1.3@global
    RVM       1.26.11 (latest)
    Git       1.9.3
    rubygems-bundler (1.4.4)

**Comment by jfrioux** [comment]
Happens only when I specify a pat for a gem, i.e.

`gem 'my_local_gem', :path => '/home/user/Projects/my_local_gem'`

**Comment by segiddins** [comment]
Looks to me like RubyGems things your gemspec is invalid?

**Comment by jfrioux** [comment]
I checked and you are right. We corrected the issue, but my local version still had it.

I'm closing this issue. Thanks.
