### ISSUE TITLE
'bundle help list' shows help for 'bundle show'

### ISSUE THREAD

**Issue by voxik** [bundler/bundler#3972]
This was originally reported at [1]:

~~~
Description of problem:
'bundle help list' command provides the same output as for 'bundle help show' command. It looks like if no GEM is provided to 'bundle show' its behaviour is same as for 'bundle list' but still I think 'bundle help list' should not have in usage 'bundle show GEM [OPTIONS]'.
And if 'bundle show' without a GEM specified should be the same as 'bundle list' it should be also mentioned in man page.


Version-Release number of selected component (if applicable):
rubygem-bundler-1.7.8-3.el7.noarch

How reproducible:
100%

Steps to Reproduce:
1.bundle help show
2.bundle help list
3.and compare the outputs

Actual results:
bundle help list

Usage:
  bundle show GEM [OPTIONS]

Options:
      [--paths=List the paths of all gems that are required by your Gemfile.], [--no-paths]  
      [--no-color=Disable colorization in output], [--no-no-color]                           
  -V, [--verbose=Enable verbose output mode], [--no-verbose]                                 
  -r, [--retry=Specify the number of times you wish to attempt network commands]             

Description:
  Show lists the names and versions of all gems that are required by your Gemfile. Calling show with [GEM] 
  will list the exact location of that gem on your machine.

Expected results:
bundle list should have its own description in help

Additional info:
~~~

This seems to be intentional, i.e. looking at the source (https://github.com/bundler/bundler/blob/master/lib/bundler/cli.rb#L206), it appears that the list and show commands should have the same functionality but then the ```bundle help``` says:

~~~
       bundle list(1)
	      Show all of the gems in the current bundle

       bundle show(1)
	      Show the source location of a particular gem in the bundle
~~~

Which implies minor difference. Would you mind to clarify this a bit?

[1] https://bugzilla.redhat.com/show_bug.cgi?id=1257622

**Comment by agis-** [comment]
Indeed, there is no difference.

I believe we should split the two functionalities (showing the path of a gem and the list of all gems) to be two separate commands with different implementations:

1) `bundle list` lists all the gems and does not accept any arguments
2) `bundle show` *must* be passed a gem name

@indirect WDYT?

**Comment by indirect** [comment]
I completely forgot that `list` even exists, and I use `show` exclusively. I agree that list shouldn't accept arguments, and I'd be happy with removing list in 2.0, and only documenting `show`, with or without arguments.

**Comment by TimMoore** [comment]
Looks like we can close this
