### ISSUE TITLE
bundle install --no-deployment Error

### ISSUE THREAD

**Issue by basilmariano** [bundler/bundler#3980]
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `/usr/bin/bundle install --no-deployment`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what actually happened was...

Error details

    Errno::EACCES: Permission denied - /Users/panfilomariano/webprojs/sinologue/.bundle/config
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.10.6/lib/bundler/settings.rb:210:in `initialize'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.10.6/lib/bundler/settings.rb:210:in `open'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.10.6/lib/bundler/settings.rb:210:in `set_key'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.10.6/lib/bundler/settings.rb:31:in `[]='
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.10.6/lib/bundler/cli/install.rb:85:in `run'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.10.6/lib/bundler/cli.rb:162:in `install'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.10.6/lib/bundler/cli.rb:10:in `start'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.10.6/bin/bundle:20:in `block in <top (required)>'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.10.6/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.10.6/bin/bundle:18:in `<top (required)>'
      /usr/bin/bundle:23:in `load'
      /usr/bin/bundle:23:in `<main>'

Environment

    Bundler   1.10.6
    Rubygems  2.0.14
    Ruby      2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
    Git       2.3.2 (Apple Git-55)

Bundler settings

    build.libv8
      Set for the current user (/Users/panfilomariano/.bundle/config): "--with-system-v8"
    without
      Set for your local app (/Users/panfilomariano/webprojs/sinologue/.bundle/config): "development:test"
    disable_shared_gems
      Set for your local app (/Users/panfilomariano/webprojs/sinologue/.bundle/config): "1"
--- TEMPLATE END ----------------------------------------------------------------

**Comment by indirect** [comment]
Bundler needs to be able to edit the file `.bundle/config` to run, but you will not allow it. Run `chown $USER /Users/panfilomariano/webprojs/sinologue/.bundle/config` to allow it, and then `bundle install`.

**Comment by basilmariano** [comment]
I can do bundle install but when i bundle install --no-deployment, i get
this issue

**Comment by indirect** [comment]
Bundler needs to be able to edit the file .bundle/config to run, but you will not allow it. Run `chown $USER /Users/panfilomariano/webprojs/sinologue/.bundle/config` and then `chmod o+w /Users/panfilomariano/webprojs/sinologue/.bundle/config` to allow it, and then run `bundle install --no-deployment`.

**Comment by basilmariano** [comment]
and it works!!

Thanks you so much.

You just saved my day :)

more  power to Bundler

**Comment by marlonfa** [comment]
Hi, my error is this:

    Bundler settings

    without
      Set for your local app (/Library/Ruby/Gems/2.0.0/gems/bundler-1.10.6/bin/.bundle/config): "development:test"
      Set for the current user (/Users/Marlon/.bundle/config): "development:test 

I tried the above methods, but failed.
My command is: bundle install --without development test
