### ISSUE TITLE
with_clean_env does not replace original RUBYLIB environmental variable

### ISSUE THREAD

**Issue by robertclancy** [bundler/bundler#3982]
[with_clean_env](https://github.com/bundler/bundler/blob/9cb77343377856af5920691d99ba9075a8bccec2/lib/bundler.rb#L274-L284) does not reset the RUBYLIB environmental variable. This results in any calls to bundler in that environment will use the current bundler version. For example, I would expect
```
bundle _1.10.0_ exec ruby -e "require 'bundler'; Bundler.clean_system('bundle _1.9.1_ exec ruby -e \"require \\'bundler\\'; puts Bundler::VERSION\"')"
```
to return 1.9.1, but it returns 1.10.0.

**Comment by indirect** [comment]
The Bundler gem is not loaded from `RUBYLIB`... perhaps you can give an example that does use `RUBYLIB` for something?

**Comment by indirect** [comment]
Whoops; sorry, I misunderstood your example. This is a bug! Thanks for reporting it.

**Comment by indirect** [comment]
(This was broken by #2536, which changed from using RUBYOPT to using RUBYLIB, but did not update `with_clean_env` to clean RUBYLIB as well as RUBYOPT).
