### ISSUE TITLE
Retrying dependency api due to error (4/4): Zlib::BufError buffer error

### ISSUE THREAD

**Issue by guiyichen** [bundler/bundler#3984]
```
Zlib::BufError: buffer error
      /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:357:in `finish'
      /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:357:in `finish'
      /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:262:in `ensure in inflater'
      /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:262:in `inflater'
      /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:274:in `read_body_0'
      /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:201:in `read_body'
      /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:226:in `body'
      /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:163:in `reading_
```

**Comment by segiddins** [comment]
I'm not even seeing bundler in that stack trace.

**Comment by guiyichen** [comment]
guiyichendeMacBook-Pro:gitlab guiyichen$ sudo gem install rake
Password:
Successfully installed rake-10.4.2
Parsing documentation for rake-10.4.2
1 gem installed
guiyichendeMacBook-Pro:gitlab guiyichen$ sudo -u root -H bash -l -c 'bundle exec rake gitlab:check RAILS_ENV=production'
Could not find rake-10.4.2 in any of the sources
Run `bundle install` to install missing gems.
guiyichendeMacBook-Pro:gitlab guiyichen$ rails s -e production -p worms
Could not find rake-10.4.2 in any of the sources
Run `bundle install` to install missing gems.

**Comment by segiddins** [comment]
And have you run `bundle install`?

**Comment by guiyichen** [comment]
yes,
guiyichendeMacBook-Pro:gitlab guiyichen$ bundle install
Fetching gem metadata from https://rubygems.org/.......
Fetching version metadata from https://rubygems.org/.Retrying dependency api due to error (2/4): Bundler::HTTPError Network error while fetching https://bundler.rubygems.org/api/v1/dependencies?gems=bones,rcov,ZenTest,rubyforge,rspec,simplecov,virtus,pattern-match,git,bones-rcov,bones-rubyforge,bones-rspec,bones-zentest,sexp_processor,spruz,hoe,ruby-maven-libs,thor,maven-tools,multi_json,simplecov-html,docile,lockfile,json,gherkin,parser,power_assert,ast,slop,rake,little-plugger,loquacious,rdoc,bones-git,bones-extras,archive-tar-minitar,term-ansicolor,trollop,ruby_parser,debugger-ruby_core_source,ruby_core_source,facets,language,unf,flexmock,uber,activesupport,RubyInline,SexpProcessor,ffi
..
Fetching dependency metadata from https://rubygems.org/..

Bundler::GemspecError: Could not read gem at /Users/guiyichen/learngit/gitlab/vendor/bundle/ruby/2.0.0/cache/rake-10.4.2.gem. It may be corrupted.
An error occurred while installing rake (10.4.2), and Bundler cannot continue.
Make sure that `gem install rake -v '10.4.2'` succeeds before bundling.
guiyichendeMacBook-Pro:gitlab guiyichen$ gem sources --remove https://rubygems.org/
source https://rubygems.org/ not present in cache

**Comment by agis-** [comment]
@guiyichen Can you post your Gemfile and the output of `$ bundle env`?

**Comment by agis-** [comment]
@guiyichen Closing this due to lack of feedback. Feel free to share more info and I'll reopen. Thanks!
