### ISSUE TITLE
Unfortunately, an unexpected error occurred, and Bundler cannot continue

### ISSUE THREAD

**Issue by helsayed** [bundler/bundler#3988]
- What did you do?

  I ran the command `/home/hussein/.rvm/gems/ruby-2.2.2@prohealth/bin/bundle install --path /home/ubuntu/prohealth/shared/bundle --without development test --deployment --quiet`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what actually happened was...

Error details

    Errno::EACCES: Permission denied @ dir_s_mkdir - /home/ubuntu
      /home/hussein/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/fileutils.rb:252:in `mkdir'
      /home/hussein/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/fileutils.rb:252:in `fu_mkdir'
      /home/hussein/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/fileutils.rb:226:in `block (2 levels) in mkdir_p'
      /home/hussein/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/fileutils.rb:224:in `reverse_each'
      /home/hussein/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/fileutils.rb:224:in `block in mkdir_p'
      /home/hussein/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/fileutils.rb:210:in `each'
      /home/hussein/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/fileutils.rb:210:in `mkdir_p'
      /home/hussein/.rvm/gems/ruby-2.2.2@prohealth/gems/bundler-1.9.6/lib/bundler.rb:310:in `mkdir_p'
      /home/hussein/.rvm/gems/ruby-2.2.2@prohealth/gems/bundler-1.9.6/lib/bundler/installer.rb:332:in `create_bundle_path'
      /home/hussein/.rvm/gems/ruby-2.2.2@prohealth/gems/bundler-1.9.6/lib/bundler/installer.rb:54:in `run'
      /home/hussein/.rvm/gems/ruby-2.2.2@prohealth/gems/bundler-1.9.6/lib/bundler/installer.rb:18:in `install'
      /home/hussein/.rvm/gems/ruby-2.2.2@prohealth/gems/bundler-1.9.6/lib/bundler/cli/install.rb:80:in `run'
      /home/hussein/.rvm/gems/ruby-2.2.2@prohealth/gems/bundler-1.9.6/lib/bundler/cli.rb:157:in `install'
      /home/hussein/.rvm/gems/ruby-2.2.2@prohealth/gems/bundler-1.9.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /home/hussein/.rvm/gems/ruby-2.2.2@prohealth/gems/bundler-1.9.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /home/hussein/.rvm/gems/ruby-2.2.2@prohealth/gems/bundler-1.9.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /home/hussein/.rvm/gems/ruby-2.2.2@prohealth/gems/bundler-1.9.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /home/hussein/.rvm/gems/ruby-2.2.2@prohealth/gems/bundler-1.9.6/lib/bundler/cli.rb:10:in `start'
      /home/hussein/.rvm/gems/ruby-2.2.2@prohealth/gems/bundler-1.9.6/bin/bundle:20:in `block in <top (required)>'
      /home/hussein/.rvm/gems/ruby-2.2.2@prohealth/gems/bundler-1.9.6/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
      /home/hussein/.rvm/gems/ruby-2.2.2@prohealth/gems/bundler-1.9.6/bin/bundle:18:in `<top (required)>'
      /home/hussein/.rvm/gems/ruby-2.2.2@prohealth/bin/bundle:23:in `load'
      /home/hussein/.rvm/gems/ruby-2.2.2@prohealth/bin/bundle:23:in `<main>'

Environment

    Bundler   1.9.6
    Rubygems  2.4.5
    Ruby      2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux]
    GEM_HOME  /home/ubuntu/prohealth/shared/bundle/ruby/2.2.0
    GEM_PATH  
    RVM       1.25.28 (stable)
    Git       1.9.1

Bundler settings

    frozen
      Set for your local app (/home/hussein/badrit_projects/prohealth/prohealth/.bundle/config): "1"
    path
      Set for your local app (/home/hussein/badrit_projects/prohealth/prohealth/.bundle/config): "/home/ubuntu/prohealth/shared/bundle"
    without
      Set for your local app (/home/hussein/badrit_projects/prohealth/prohealth/.bundle/config): "development:test"
    disable_shared_gems
      Set for your local app (/home/hussein/badrit_projects/prohealth/prohealth/.bundle/config): "1"

**Comment by segiddins** [comment]
It looks like you don't have write access to `GEM_HOME`
