### ISSUE TITLE
Report friendly errors due to incorrect GEM_HOME paths

### ISSUE THREAD

**Issue by arthurkulchenko** [bundler/bundler#3990]
$bundle install
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `/Users/user1/.rvm/gems/ruby-2.2.2/bin/bundle install`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what actually happened was...

Error details

    Errno::ENOTSUP: Operation not supported @ dir_s_mkdir - /home/deployer
      /Users/user1/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/fileutils.rb:252:in `mkdir'
      /Users/user1/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/fileutils.rb:252:in `fu_mkdir'
      /Users/user1/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/fileutils.rb:226:in `block (2 levels) in mkdir_p'
      /Users/user1/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/fileutils.rb:224:in `reverse_each'
      /Users/user1/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/fileutils.rb:224:in `block in mkdir_p'
      /Users/user1/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/fileutils.rb:210:in `each'
      /Users/user1/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/fileutils.rb:210:in `mkdir_p'
      /Users/user1/.rvm/gems/ruby-2.2.2/gems/bundler-1.10.6/lib/bundler.rb:308:in `mkdir_p'
      /Users/user1/.rvm/gems/ruby-2.2.2/gems/bundler-1.10.6/lib/bundler/installer.rb:278:in `create_bundle_path'
      /Users/user1/.rvm/gems/ruby-2.2.2/gems/bundler-1.10.6/lib/bundler/installer.rb:54:in `run'
      /Users/user1/.rvm/gems/ruby-2.2.2/gems/bundler-1.10.6/lib/bundler/installer.rb:18:in `install'
      /Users/user1/.rvm/gems/ruby-2.2.2/gems/bundler-1.10.6/lib/bundler/cli/install.rb:107:in `run'
      /Users/user1/.rvm/gems/ruby-2.2.2/gems/bundler-1.10.6/lib/bundler/cli.rb:162:in `install'
      /Users/user1/.rvm/gems/ruby-2.2.2/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /Users/user1/.rvm/gems/ruby-2.2.2/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /Users/user1/.rvm/gems/ruby-2.2.2/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /Users/user1/.rvm/gems/ruby-2.2.2/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /Users/user1/.rvm/gems/ruby-2.2.2/gems/bundler-1.10.6/lib/bundler/cli.rb:10:in `start'
      /Users/user1/.rvm/gems/ruby-2.2.2/gems/bundler-1.10.6/bin/bundle:20:in `block in <top (required)>'
      /Users/user1/.rvm/gems/ruby-2.2.2/gems/bundler-1.10.6/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
      /Users/user1/.rvm/gems/ruby-2.2.2/gems/bundler-1.10.6/bin/bundle:18:in `<top (required)>'
      /Users/user1/.rvm/gems/ruby-2.2.2/bin/bundle:23:in `load'
      /Users/user1/.rvm/gems/ruby-2.2.2/bin/bundle:23:in `<main>'
      /Users/user1/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `eval'
      /Users/user1/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `<main>'

Environment

    Bundler   1.10.6
    Rubygems  2.4.6
    Ruby      2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]
    GEM_HOME  /home/deployer/app/shared/bundle/ruby/2.2.0
    GEM_PATH  
    RVM       1.26.11 (master)
    Git       2.4.3

Bundler settings

    gem.test
      Set for the current user (/Users/user1/.bundle/config): "false"
    path
      Set for your local app (/Users/user1/Documents/projectname/.bundle/config): "/home/deployer/app/shared/bundle"
    disable_shared_gems
      Set for your local app (/Users/user1/Documents/projectname/.bundle/config): "1"
--- TEMPLATE END ----------------------------------------------------------------

I think there are some bundle settings exist cose when I ran 'bundle install' it's returned 
GEM_HOME  /home/deployer/app/shared/bundle/ruby/2.2.0 in Environment block as you can see,
And when I type this - "echo $GEM_HOME" I get "/Users/user1/.rvm/gems/ruby-2.2.2"...
also I get "/home/deployer/app/shared/bundle/ruby/2.2.0" on my remote VDS

SOLVED
by replacing BUNDLE_PATH in projectname/.bundle/config from /home/deployer/app/shared/bundle/ruby/2.2.0 - remote $GEM_HOME
to
/Users/user1/.rvm/gems/ruby-2.2.2  - local $GEM_HOME
How it's changed I really don't know, and don't understand...

**Comment by agis-** [comment]
I think that the issue lies in your `GEM_HOME` not being set properly by rvm.

**Comment by indirect** [comment]
We should definitely catch this error and report the problem, though...

**Comment by arthurkulchenko** [comment]
SOLVED
by replacing BUNDLE_PATH in projectname/.bundle/config from /home/deployer/app/shared/bundle/ruby/2.2.0 - remote $GEM_HOME
to
/Users/user1/.rvm/gems/ruby-2.2.2  - local $GEM_HOME
How it's changed I really don't know, and don't understand...

**Comment by agis-** [comment]
I wasn't able to reproduce this by mimicking your setup. @arthurkulchenko Any chance you may give some insight on was actually triggering the problem?

**Comment by arthurkulchenko** [comment]
I looked around and checked shell history and diff's and assumed that it maybe was this...
env RAILS_ENV=development ~/.rvm/bin/rvm default do bundle install 
if not, it could be bug with fish shell

**Comment by agis-** [comment]
This is fixed on master by https://github.com/bundler/bundler/pull/4016.
