### ISSUE TITLE
bundle update runs, but bundle exec complains of incompatible gems

### ISSUE THREAD

**Issue by krobi64** [bundler/bundler#3998]
bundler version: 1.9.4
ruby version: ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin13]

I ran bundle update, and I get a message that it installed the new  version of my gem. However, when I use `bundle exec`, I get 

```
Bundler could not find compatible versions for gem "my_first_gem":
  In snapshot (Gemfile.lock):
    my_first_gem (= 1.0.1.rc4)

  In Gemfile:
    my_engine (~> 0.1.9) ruby depends on
      my_first_gem (>= 0) ruby

    my_first_gem (~> 1.0.1.rc4) ruby

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
``` 

I am running these commands while trying to build `my_engine`.

**Comment by indirect** [comment]
Please tell us how we can reproduce this problem! If you're not sure how to do that, check [ISSUES](https://github.com/carlhuda/bundler/blob/master/ISSUES.md).

**Comment by agis-** [comment]
Closing this due to lack of feedback.

@krobi64 Feel free to share more info and we'll be happy to reopen. Thanks!
