### ISSUE TITLE
binstubs command not mentioned in documentation

### ISSUE THREAD

**Issue by dwieringa** [bundler/bundler#4000]
I just noticed I'm supposed to be using `bundle binstubs <gemfile>` according to:
* https://github.com/rails/rails/issues/8974#issuecomment-14130313

I was looking for some more information and noticed that the `binstubs` command is not referenced in the bundle documentation.

ie http://bundler.io/v1.10/man/bundle.1.html

It looks like it was introduced in 1.3 (according to What's new in Bundler).

Ah, with google, I found it at http://bundler.io/v1.10/commands.html, but my first reaction was to hit the "Read documentation" link on the main page.

**Comment by indirect** [comment]
We should definitely add a manpage for `binstubs` (or if it already exists, mention it in the main help page).

**Comment by Zorbash** [comment]
@indirect A manpage for `binstubs` does not seem to exist. I'm preparing a PR for this.

**Comment by RochesterinNYC** [comment]
@Zorbash are you still working on the PR for a `binstubs` manpage?

**Comment by LynnCo** [comment]
*ping*

> @Zorbash are you still working on the PR for a binstubs manpage?

**Comment by Zorbash** [comment]
@LynnCo @RochesterinNYC I still have some unfinished work in a branch, i'll do my best to turn it into a PR soon.
