### ISSUE TITLE
Gentoo x64 install failure

### ISSUE THREAD

**Issue by ruddy32** [bundler/bundler#4006]
While installing bundler on Gentoo Linux x64 using root account, the install process generate the following log :
^[[0m ^[[31;01m*^[[0m ERROR: dev-ruby/metasploit-model-1.0.0::gentoo failed (prepare phase):
 ^[[31;01m*^[[0m   (no error message)
 ^[[31;01m*^[[0m
 ^[[31;01m*^[[0m Call stack:
 ^[[31;01m*^[[0m     ebuild.sh, line   93:  Called src_prepare
 ^[[31;01m*^[[0m   environment, line 4433:  Called ruby-ng_src_prepare
 ^[[31;01m*^[[0m   environment, line 4123:  Called _ruby_each_implementation 'each_ruby_prepare'
 ^[[31;01m*^[[0m   environment, line  498:  Called _ruby_invoke_environment 'ruby20' 'each_ruby_prepare'
 ^[[31;01m*^[[0m   environment, line  593:  Called each_ruby_prepare
 ^[[31;01m*^[[0m   environment, line  898:  Called die
 ^[[31;01m*^[[0m The specific snippet of code:
 ^[[31;01m*^[[0m           BUNDLE_GEMFILE=Gemfile ${RUBY} -S bundle install --local || die;
 ^[[31;01m*^[[0m
 ^[[31;01m*^[[0m If you need support, post the output of `emerge --info '=dev-ruby/metasploit-model-1.0.0::gentoo'`,
 ^[[31;01m*^[[0m the complete build log and the output of `emerge -pqv '=dev-ruby/metasploit-model-1.0.0::gentoo'`.
!!! When you file a bug report, please include the following information:
GENTOO_VM=  CLASSPATH="" JAVA_HOME=".../current-system-vm"
JAVACFLAGS="" COMPILER=""
and of course, the output of emerge --info =metasploit-model-1.0.0
 ^[[31;01m*^[[0m The complete build log is located at '.../tmp/portage/dev-ruby/metasploit-model-1.0.0/temp/build.log'.
 ^[[31;01m*^[[0m The ebuild environment file is located at '.../tmp/portage/dev-ruby/metasploit-model-1.0.0/temp/environment'.
 ^[[31;01m*^[[0m Working directory: '.../tmp/portage/dev-ruby/metasploit-model-1.0.0/work/ruby20/metasploit-model-1.0.0'
 ^[[31;01m*^[[0m S: '.../tmp/portage/dev-ruby/metasploit-model-1.0.0/work/ruby20/metasploit-model-1.0.0'
 ^[[31;01m*^[[0m --------------------------- ACCESS VIOLATION SUMMARY ---------------------------
 ^[[31;01m*^[[0m LOG FILE: ".../sandbox/sandbox-25320.log"
 ^[[31;01m*^[[0m
VERSION 1.0
FORMAT: F - Function called
FORMAT: S - Access Status
FORMAT: P - Path as passed to function
FORMAT: A - Absolute Path (not canonical)
FORMAT: R - Canonical Path
FORMAT: C - Command Line

F: mkdir
S: deny
P: /usr/local/lib64/ruby
A: /usr/local/lib64/ruby
R: /usr/local/lib64/ruby
C: /usr/bin/ruby20 -S bundle install --local

F: mkdir
S: deny
P: /usr/local/lib64/ruby
A: /usr/local/lib64/ruby
R: /usr/local/lib64/ruby
C: /usr/bin/ruby20 -S bundle install --local
 ^[[31;01m*^[[0m --------------------------------------------------------------------------------

**Comment by indirect** [comment]
This tracker is for bugs in Bundler. You pasted the output from a `gentoo emerge` command, which is not Bundler. Please ask the maintainers of the portage package that you are attempting to install for help.
