### ISSUE TITLE
Update CoC with extra wording from Contributor Covenant v1.2.0

### ISSUE THREAD

**Issue by heliocola** [bundler/bundler#4007]
I reviewed and update a few words in the CoC based on the version 1.2.0 of the Contributor Covenant (CC).

Changes: https://github.com/heliocola/bundler/commit/117689bbaf92a75e7088b1e1b35837481fc4a190

The main changes are extra wording while defining 'regardless of...' sentence.
I noticed CC uses the term 'personal appearance' while Bundler CoC uses 'physical appearance'. Since it isn't a change in CC from 1.1.0 to 1.2.0 I left the reference to 'physical appearance'.

If you guys agree with the additions I can send the PR.
If you have any question, suggestion, comment, please give me a (e-)ring!

**Comment by indirect** [comment]
I am happy to make the Bundler CoC match CC 1.2 exactly, feel free to send a PR!

**Comment by heliocola** [comment]
@indirect cool, I will send it your way.
