### ISSUE TITLE
Permission denied @ dir_s_mkdir - /var/www/travel/code/.bundle

### ISSUE THREAD

**Issue by balajigalave** [bundler/bundler#4009]
――― ERROR REPORT TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――
- What did you do?
- What did you expect to happen?
- What happened instead?

Error details

    Errno::EACCES: Permission denied @ dir_s_mkdir - /var/www/travel/code/.bundle
    /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/fileutils.rb:252:in `mkdir'
    /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/fileutils.rb:252:in `fu_mkdir'
    /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/fileutils.rb:226:in `block (2 levels) in mkdir_p'
    /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/fileutils.rb:224:in `reverse_each'
    /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/fileutils.rb:224:in `block in mkdir_p'
    /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/fileutils.rb:210:in `each'
    /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/fileutils.rb:210:in `mkdir_p'
    /usr/local/rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/settings.rb:153:in `set_key'
    /usr/local/rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/settings.rb:21:in `[]='
    /usr/local/rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/settings.rb:94:in `without='
    /usr/local/rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/cli/install.rb:71:in `run'
    /usr/local/rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/cli.rb:157:in `install'
    /usr/local/rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/vendor/thor/command.rb:27:in `run'
    /usr/local/rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/vendor/thor/invocation.rb:121:in `invoke_command'
    /usr/local/rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/vendor/thor.rb:363:in `dispatch'
    /usr/local/rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/vendor/thor/base.rb:440:in `start'
    /usr/local/rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/cli.rb:10:in `start'
    /usr/local/rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/bin/bundle:20:in `block in <top (required)>'
    /usr/local/rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/friendly_errors.rb:6:in `with_friendly_errors'
    /usr/local/rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/bin/bundle:18:in `<top (required)>'
    /usr/local/rvm/gems/ruby-2.2.1@global/bin/bundle:23:in `load'
    /usr/local/rvm/gems/ruby-2.2.1@global/bin/bundle:23:in `<main>'
    /usr/local/rvm/gems/ruby-2.2.1@global/bin/ruby_executable_hooks:15:in `eval'
    /usr/local/rvm/gems/ruby-2.2.1@global/bin/ruby_executable_hooks:15:in `<main>'

Environment

    Bundler   1.8.4
    Rubygems  2.4.6
    Ruby      2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]
    GEM_HOME  /usr/local/rvm/gems/ruby-2.2.1
    GEM_PATH  /usr/local/rvm/gems/ruby-2.2.1:/usr/local/rvm/gems/ruby-2.2.1@global
    RVM       1.26.11 (latest)
    Git       1.9.1
    rubygems-bundler (1.4.4)

Bundler settings

    without
      Set for your local app (/var/www/travel/code/.bundle/config): "production:from:."
――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/bundler/bundler/search?q=Permission+denied+%40+dir_s_mkdir+-+%2Fvar%2Fwww%2Ftravel%2Fcode%2F.bundle&type=Issues

If there aren't any reports for this error yet, please create copy and paste the report template above into a new issue. Don't forget to anonymize any private data! The new issue form is located at:
https://github.com/bundler/bundler/issues/new
ubuntu@ip-172-31-29-207:/var/www/travel/code$ ^C
ubuntu@ip-172-31-29-207:/var/www/travel/code$ https://github.com/bundler/bundler/search?q=Permission+denied+%40+dir_s_mkdir+-+%2Fvar%2Fwww%2Ftravel%2Fcode%2F.bundle&type=Issues
[1] 725
ubuntu@ip-172-31-29-207:/var/www/travel/code$ -bash: https://github.com/bundler/bundler/search?q=Permission+denied+%40+dir_s_mkdir+-+%2Fvar%2Fwww%2Ftravel%2Fcode%2F.bundle: No such file or directory
^C
[1]+  Exit 127                https://github.com/bundler/bundler/search?q=Permission+denied+%40+dir_s_mkdir+-+%2Fvar%2Fwww%2Ftravel%2Fcode%2F.bundle

**Comment by rgb-one** [comment]
It seems you don't have write pemission to that directory. Bundler is trying to write to .bundle but cannot because the user you are logged in as cannot write to the var/www/travel/code directory. You could try running bundler in a location where you do have full read write access like your home directory.
