### ISSUE TITLE
SSH Key Option

### ISSUE THREAD

**Issue by mcasper** [bundler/bundler#4011]
My company finds itself in the position where it wants to load one of our private repos into several of our applications. Currently the ways to do that seem to be:

* Running your own gem server
* Using x-oauth-basic auth with a personal or machine account access token and https url
* Using a service like Gemfury

Running a gem server seems like overkill for just loading one gem in a few places, we would like not to have to manage and expose personal access tokens or machine account tokens, and we don't want to pay for a service when it can be avoided.

It would be great if you could specify an ssh key to use when loading a gem through ssh. I imagine it would look something like: 
```
gem "my_gem", git: "git@github.com/owner/my_gem", ssh_key: "/path/to/key.pub"
```

So I suppose my questions are, is this a desired feature? Had this already been discussed and decided upon somewhere else that I couldn't find? If it is a desired feature, has anyone started on it/has plans to start on it? If it's desired and not being worked on, I would be glad to take a stab at it.

**Comment by indirect** [comment]
Load the SSH key into an SSH agent using `ssh-add` before you `bundle install`. It will Just Work™.

**Comment by indirect** [comment]
Alternatively, [set up an SSH config file](http://superuser.com/a/232406). Either way, Bundler just runs git commands, and git provides no way to set the SSH key. You'll need to use one of the mechanisms that git supports to authenticate git clones with a key.

**Comment by antoineco** [comment]
@indirect in some situations this doesn't work:

1. Even if you have multiple keys loaded in your SSH agent using `ssh-add`, bundler will only use the first one in the list. Could be a git issue as well, I have to check.

2. The SSH config file trick doesn't work if both projects are hosted at the same URL, i.e. on github.com

For people using 1 deploy key per project this is really hard to handle, you basically have to run `ssh-add` and `bundle install` in a loop, making sure you add and remove the keys in the same order as defined in the Gemfile.

**Comment by mcasper** [comment]
The solution we ended up using for this was to wrap all our git commands in a git_ssh script:

https://gist.github.com/mcasper/9e139fb7687dc983a59a

We're in the same boat is @antoineco, using separate deploy-only keys for multiple repos, and this script allows you to run something like `~/git_ssh.sh -i ~/.ssh/id_rsa-project1 fetch`.

It's not ideal, and I wish git had better support for specifying the ssh key, but it was the best we could come up with.

**Comment by indirect** [comment]
I don't think that an option in the Gemfile is an acceptable solution for this—a path to an SSH key is going to be machine-specific, and that's not something that you want shared between development and production.

Is there something stopping you all from creating a Github account to use for deploys and adding that account (with a single SSH key) as a read-only collaborator to all of the repos in question?

If we were to add support for this, it would be a config setting, and it would probably be something like `bundle config git_ssh_key.gemname "path/to/key"`, but I'm not convinced that it's serving a common need, yet.

**Comment by antoineco** [comment]
> I'm not convinced that it's serving a common need, yet

Probably not. I like the suggestion of setting on key per repo inside the Bundler configuration though.
