### ISSUE TITLE
Colour `bundle update x` differently

### ISSUE THREAD

**Issue by orta** [bundler/bundler#4013]
Compare:
![screen shot 2015-09-25 at 08 45 48](https://cloud.githubusercontent.com/assets/49038/10095434/d6644740-6361-11e5-992b-771b0f038da0.png)

With (CocoaPods)
![screen shot 2015-09-25 at 08 45 30](https://cloud.githubusercontent.com/assets/49038/10095431/cec04610-6361-11e5-8719-b7fd36b60020.png)

The change in wording also helps when scanning down the left hand side. Making it say `Updating` instead of `Installing` gets you an extra point. Tested on 1.10.6

**Comment by segiddins** [comment]
@orta it's saying `using` because it isn't actually installing anything -- it's using an already downloaded version of that gem. It _could_ stand to say `updating` since it's changing the lock, but I believe we've nixed this output anyways in 2.0, or relegated it to verbose mode only.

**Comment by orta** [comment]
> It could stand to say updating since it's changing the lock, but I believe we've nixed this output anyways in 2.0

Cool, cool, sound like you've got it under control.
