### ISSUE TITLE
Error while installing bundler

### ISSUE THREAD

**Issue by shakti07316222085** [bundler/bundler#4014]
Dear Team
I  am getting error while installing bundler. Please let me know what i have do to correct the same.

--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `/usr/local/bin/bundle install --without development test --deployment`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what actually happened was...

Error details

    Errno::EACCES: Permission denied - /var/www/html/elmo/vendor/bundle/ruby/1.9.1/cache/bundler
      /usr/lib/ruby/1.9.1/fileutils.rb:247:in `mkdir'
      /usr/lib/ruby/1.9.1/fileutils.rb:247:in `fu_mkdir'
      /usr/lib/ruby/1.9.1/fileutils.rb:221:in `block (2 levels) in mkdir_p'
      /usr/lib/ruby/1.9.1/fileutils.rb:219:in `reverse_each'
      /usr/lib/ruby/1.9.1/fileutils.rb:219:in `block in mkdir_p'
      /usr/lib/ruby/1.9.1/fileutils.rb:205:in `each'
      /usr/lib/ruby/1.9.1/fileutils.rb:205:in `mkdir_p'
      /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/source/git/git_proxy.rb:76:in `checkout'
      /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/source/git.rb:153:in `specs'
      /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/lazy_specification.rb:53:in `__materialize__'
      /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/spec_set.rb:88:in `block in materialize'
      /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/spec_set.rb:85:in `map!'
      /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/spec_set.rb:85:in `materialize'
      /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/definition.rb:140:in `specs'
      /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/definition.rb:129:in `resolve_remotely!'
      /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/installer.rb:79:in `run'
      /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/installer.rb:18:in `install'
      /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/cli/install.rb:107:in `run'
      /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/cli.rb:162:in `install'
      /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/cli.rb:10:in `start'
      /var/lib/gems/1.9.1/gems/bundler-1.10.6/bin/bundle:20:in `block in <top (required)>'
      /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
      /var/lib/gems/1.9.1/gems/bundler-1.10.6/bin/bundle:18:in `<top (required)>'
      /usr/local/bin/bundle:23:in `load'
      /usr/local/bin/bundle:23:in `<main>'

Environment

    Bundler   1.10.6
    Rubygems  1.8.23
    Ruby      1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]
    GEM_HOME  /var/www/html/elmo/vendor/bundle/ruby/1.9.1
    GEM_PATH
    Git       1.9.1

Kind Regards
Shakti Singh

**Comment by agis-** [comment]
This must be the same as #4009.

**Comment by shakti07316222085** [comment]
I have seen the issue #4009. and provided the desired permission but still not working.

**Comment by segiddins** [comment]
Let's just add a better error message here ¯\_(ツ)_/¯
