### ISSUE TITLE
--without is ignored when --local is defined

### ISSUE THREAD

**Issue by pravi** [bundler/bundler#4023]
when bundle install --local --without development test is given bundle still fails trying to find dependencies in development and test group. Tested with gitlab and diaspora Gemfiles.

**Comment by indirect** [comment]
This isn't a bug. You must have either a Gemfile.lock or every gem downloaded, so that Bundler can make sure that the versions are compatible. The without option only disables installing gems, it cannot remove the need to download those gems.

**Comment by pravi** [comment]
@indirect can this be considered a feature request? This will be useful in a debian environment.

For example, we want only gems listed in production for the debian package of a rails app (gitlab, diaspora) and we want to check all dependency requirements are met locally (we install them from debian's package repository using native deb packages). Same goes for postgres or mysql groups.

When we chose postgres, mysql2 gem/deb is not installed but we want to be able check all other dependencies are locally met. But currently bundler throws an error saying mysql2 is not found, even when --without mysql is selected.

**Comment by indirect** [comment]
@pravi it is impossible to check if the dependencies are satisfied unless every dependency's gemspec is present. There is unfortunately no way to eliminate that requirement.

**Comment by pravi** [comment]
@indirect but gemspecs for all gems in a particular group is already present. In diaspora, Gemfile has production, development and test groups. We have gemspecs for all gems in production present locally. How hard it would be change the behaviour?

**Comment by pravi** [comment]
@indirect can't it be excluded when you parse the Gemfile, so the Gemfile will appear to have only the required groups?

**Comment by indirect** [comment]
@pravi no, it cannot. it is impossible to know what the dependencies for the application are unless you include every group.

**Comment by mvz** [comment]
@indirect Do you mean that Bundler needs to know all the possible dependencies, so that, even if you exclude a group, it doesn't install versions of gems that will conflict with gems in that group, should you want to install them later on?

**Comment by segiddins** [comment]
@mvz correct
