### ISSUE TITLE
bundle install without remembering --with --without for vagrant?

### ISSUE THREAD

**Issue by nruth** [bundler/bundler#4024]
Assume rails / bundler

When I run our vagrant install script it's 
`bundle install --without production test --with development`
When I install on the same laptop without vagrant it's 
`bundle install --with development test --without production`

These stomp on each other, and cause tests to fail (without vagrant) because the test group has been removed.
It'd be really great if there was a --dont-remember flag or similar for bundle install so I can stop the vagrant installation changing the project settings outside of vagrant (which I assume are being saved to the same file, due to the project directory being shared)

**Comment by segiddins** [comment]
As of bundler 2, settings will only be remembered from ` bundle config `

**Comment by nruth** [comment]
Great, thanks for telling me. Closing.
