### ISSUE TITLE
Deprecate bundle console command

### ISSUE THREAD

**Issue by Zorbash** [bundler/bundler#4025]
In 748d8ec it is stated that:
> Bundler 2.0 will deprecate
the `bundle console` command, and instead add a script to each generated
gem that loads `bundler/setup` and then loads the gem.

Currently there is no relevant issue in the [`2.0`](https://github.com/bundler/bundler/issues?utf8=%E2%9C%93&q=milestone%3A2.0) milestone, so i'm suggesting that we add one if it is still part of the [`2.0`](https://github.com/bundler/bundler/issues?utf8=%E2%9C%93&q=milestone%3A2.0) roadmap.

**Comment by indirect** [comment]
Yeah, good catch! The console command has gotten many, many pull requests for different kinds of customization and so we eventually realized that an editable bin/console is the only way to provide that level of customization. The gem command already creates bin/console, so all that's left is to remove the console command. For bonus points, you could add a deprecation warning to the console command in the 1-99 branch. :)

**Comment by Zorbash** [comment]
Great! I'm preparing a PR for this.

**Comment by agis-** [comment]
This is done (`bundle-console` is deprecated and removed in bundler 2.0).
