### ISSUE TITLE
Bundler-provided rake tasks for install and update

### ISSUE THREAD

**Issue by dchelimsky** [bundler/bundler#403]
I'm working with an automated deployment tool that checks out code and runs a single rake task. I'm not able to use bundler with this tool unless I vendor all the gems, which I'd like to avoid.

To resolve this, I'd like to be able to set up a `rake bundle:install` task, but it doesn't work if I haven't already run `bundle install`.

What do you think about a 'rake' mode for bundler, where you can put this at the top of your Rakefile:

<pre>
require 'bundler'
Bundler.setup :rake do
  ## the rest of the Rakefile
end
</pre>

Bundler would check if the bundle is locked. If so, it yields to the block. If not, it tries to resolve the bundle. If resolution succeeds it yields to the block. If not, it does not yield to the block.

In either case, it registers `bundle:install` and `bundle:update` tasks so you can access them.

Crazy?

**Comment by dancinglightning** [comment]
Hi, google lead here after i heard about these tasks. They are useful for maintaining gems.
indirects argument of not needing docs (which i looked for in vain on the site) doesn't really hold as it assumes perfect information distribution :-(
Proving this are several gems out there that provide functionality like this. 
Quite a wasted double effort as everyone uses bundle, right ?

require 'bundler/gem_tasks'    -->  Rakefile

**Comment by indirect** [comment]
I wasn't arguing against docs, I was explaining why we didn't have any yet. I also said it would be great if someone wrote docs. Could you send a pull request?

**Comment by dancinglightning** [comment]
Not that i am against helping a little with such a great tool, but i think it will involve more process/talking.
For a start i wouldn't know where on the site it should go. Seeing as it is not "bundle xxx" command related and everything else is. 
But i can start that process by opening and issue, ok?
btw: you won't remember, but we met at frozen rails last year, talked a bit about vm's and rubinius one morning.
