### ISSUE TITLE
not respecting ruby version requirement

### ISSUE THREAD

**Issue by grosser** [bundler/bundler#4046]
bundler should pick the highest possible version of a gem, not pick a version that is incompatible and then fail

```Ruby
source 'https://rubygems.org'

gem 'mustache' # wants 2.0.0
```

```
rbenv shell 1.9.3
bundle
Fetching gem metadata from https://rubygems.org/..
Fetching version metadata from https://rubygems.org/.
Resolving dependencies...
Using bundler 1.10.6
Installing mustache 1.0.2

Gem::InstallError: mustache requires Ruby version ~> 2.0.
An error occurred while installing mustache (1.0.2), and Bundler cannot continue.
Make sure that `gem install mustache -v '1.0.2'` succeeds before bundling.
bundle -v
Bundler version 1.10.6
```

**Comment by segiddins** [comment]
This will be fixed by a pair of open PRs, one of which is the new index format.

**Comment by scarver2** [comment]
This may be related to this issue. 

bundler is attempting to update net-ssh v2.8.0 to v3.0.1 which requires. Ruby 2.0

````
Updating net-ssh
ERROR:  Error installing net-ssh:
	net-ssh requires Ruby version >= 2.0.
````

**Comment by segiddins** [comment]
This is a feature that were working on adding, as I said.

**Comment by chris-rock** [comment]
:+1:

**Comment by segiddins** [comment]
This will be in Bundler 1.12.

**Comment by chris-rock** [comment]
@segiddins Just discovered, that this is not working with the latest bundler 1.12 version. See my gist here: https://gist.github.com/chris-rock/6b7648c692fb3c758646

**Comment by chris-rock** [comment]
@srenatus had a good idea to work around this problem for now:

```
# pin dependency for Ruby 1.9.3 since bundler is not
# detecting that net-ssh 3 does not work with 1.9.3
if Gem::Version.new(RUBY_VERSION) <= Gem::Version.new('1.9.3')
  gem 'net-ssh', '~> 2.9'
end
```

**Comment by grosser** [comment]
afaik this does not work because it changes the lock file ... used this with success for a while though

```
gem 'net-ssh', platform: (RUBY_VERSION > "2.0.0" ? :ruby : :win32)
```

**Comment by indirect** [comment]
This should work on 1.12 as long as Bundler is able to access the new index format. Give it a try with `gem install bundler --pre`.
