### ISSUE TITLE
Invalid autoload for `Bundler::Specification`?

### ISSUE THREAD

**Issue by backus** [bundler/bundler#4050]
It looks like `lib/bundler.rb` specified the following autoload

```ruby
module Bundler
  # ...

  autoload :Specification,         "bundler/shared_helpers"

  # ...
end
```

even though `Bundler::Specification` was removed in 0f97e4fcea15b2e5f2d6d045c686b5750c5d54de.  Should this be removed?

**Comment by segiddins** [comment]
Probably? Try removing it and see if the specs still pass?

**Comment by backus** [comment]
Merged!

For context on this issue: I'm writing a tool which enumerates methods defined at a point in time in the ruby VM.  As a result, for every top level constant the following is performed:

```ruby
SomeConstant.constants.map { |const_name| SomeConstant.const_get(const_name) }
```

therefore, since my gem uses bundler, it always ends up doing the following

```ruby
Bundler.constants.map { |const_name| Bundler.const_get(const_name) }
```

which triggered the invalid autoload of `Bundler::Specification`
