### ISSUE TITLE
Permission Denied Error

### ISSUE THREAD

**Issue by mikemonk** [bundler/bundler#4053]
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `/usr/local/bin/bundle install --without test development`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what actually happened was...

Error details

    Errno::EACCES: Permission denied - /home/user/Downloads/wpscan/.bundle
      /usr/lib/ruby/1.9.1/fileutils.rb:247:in `mkdir'
      /usr/lib/ruby/1.9.1/fileutils.rb:247:in `fu_mkdir'
      /usr/lib/ruby/1.9.1/fileutils.rb:221:in `block (2 levels) in mkdir_p'
      /usr/lib/ruby/1.9.1/fileutils.rb:219:in `reverse_each'
      /usr/lib/ruby/1.9.1/fileutils.rb:219:in `block in mkdir_p'
      /usr/lib/ruby/1.9.1/fileutils.rb:205:in `each'
      /usr/lib/ruby/1.9.1/fileutils.rb:205:in `mkdir_p'
      /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/settings.rb:208:in `set_key'
      /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/settings.rb:31:in `[]='
      /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/settings.rb:199:in `set_array'
      /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/settings.rb:117:in `without='
      /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/cli/install.rb:96:in `run'
      /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/cli.rb:162:in `install'
      /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/cli.rb:10:in `start'
      /var/lib/gems/1.9.1/gems/bundler-1.10.6/bin/bundle:20:in `block in <top (required)>'
      /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
      /var/lib/gems/1.9.1/gems/bundler-1.10.6/bin/bundle:18:in `<top (required)>'
      /usr/local/bin/bundle:23:in `load'
      /usr/local/bin/bundle:23:in `<main>'

Environment

    Bundler   1.10.6
    Rubygems  1.8.23
    Ruby      1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]
    Git       1.9.1

Bundler settings

    without
      Set for your local app (/home/user/Downloads/wpscan/.bundle/config): "test:development"
--- TEMPLATE END ----------------------------------------------------------------

**Comment by agis-** [comment]
It looks like Bundler is trying to write to `/home/user/Downloads/wpscan/.bundle` but doesn't have the proper permissions to do so.

**Comment by mikemonk** [comment]
I tried this already:  sudo chmod -R 755 Downloads/

I was also running the installer with sudo, so not sure what to set for the permissions

**Comment by agis-** [comment]
755 gives write access only to the owner. Maybe the folder is not owned by the user bundler runs with?

It's clear that bundler has no write access to `/home/user/Downloads/wpscan/.bundle`.

**Comment by agis-** [comment]
Closing this as it's a file system permission issue.
