### ISSUE TITLE
local bundle config throws error about branch, even though gemfile specifies correct branch

### ISSUE THREAD

**Issue by stephenhmarsh** [bundler/bundler#4056]
Bundler version 1.10.6
git version 2.5.3
ruby 2.2.3 (via RVM)

A couple of my projects have a dependency for another gem that I have cloned locally for development.

In my Gemfile I have:

<pre>
gem 'my_gem', :git=>'git://github.com/path_to/my_gem.git', :branch=>'rails4'
</pre>

To override that locally, I use:
`bundle config local.my_gem /Path/to/gem`

Here's the error, though:
<pre>
$ bundle show my_gem
Local override for my_gem at /Users/stephenmarsh/dev/my_gem is using branch rails4 but Gemfile specifies rails4
</pre>

Obviously this is a very confusing error because the branches are identical/apparently correct.

I have tried combinations of: re-pulling that branch from origin, running `bundle update my_gem`, and deleting and re-cloning the my_gem repo from scratch.  None of these work.

**Comment by stephenhmarsh** [comment]
Found the problem. 

I put some debugging code in bundler in the `local_override!` method of Git.rb

<pre>
if git_proxy.branch != options["branch"] && !Bundler.settings[:disable_local_branch_check]
 puts options["branch"].inspect
 puts git_proxy.branch.inspect
 raise GitError, "Local override for #{name} at #{path} is using branch " \
   "#{git_proxy.branch} but Gemfile specifies #{options["branch"]}"
end
</pre>

the result was:

<pre>
"rails4"
"\e[32mrails4\e[m"
</pre>

it seems the ANSI code for green is becoming part of the string in the new ``@git_proxy``

this seems to come from the branch method in GitProxy.rb

<pre>
def branch
  @branch ||= allowed_in_path do
     git("branch") =~ /^\* (.*)$/ && $1.strip
   end
end
</pre>

It turns out that ``git("branch")`` was returning: `` "  master\e[m\n* \e[32mrails4\e[m\n  rails4_bootstrap3\e[m\n"``

So, I disabled color terminal outputs from git by running:  ``git config --global color.ui false``

And now it works. :D

I'm not sure if this is technically a Git bug or a Bundler bug, or simply poorly configured settings in my environment somewhere?

**Comment by indirect** [comment]
Maybe we need to run git commands with the --no-color option? Or maybe use a lower level git command that doesn't include colorization.

**Comment by stephenhmarsh** [comment]
Thanks @indirect.  I am not seeing this error with ``git config --global color.ui auto`` either.  Only seeing it with color.ui ``always``.

Has it ever been discussed to change this to:
<pre>
        def branch
          @branch ||= allowed_in_path do
            git("rev-parse --abbrev-ref HEAD").strip
          end
        end
</pre>

?

As this does not have any colorization, even with ``always``, and eliminates the need for Regex?

Would be happy to make a PR if this sounds like right direction.

**Comment by segiddins** [comment]
@stephenhmarsh a PR for that would be excellent :)

**Comment by stephenhmarsh** [comment]
Hi, can someone please advise which branch I should base my bugfix off of and/or PR to?  It was discovered on 1.10.6, but I see this method has been unchanged for quite a while.  Thanks!

**Comment by segiddins** [comment]
It should be based off of master. :)
