### ISSUE TITLE
Compatible version issue for gem "httpi"

### ISSUE THREAD

**Issue by anymatus** [bundler/bundler#4060]
I'm trying to use google-dfp-api.. I had to resolve several dependencies but.. I can not resolve this one:

```
Bundler could not find compatible versions for gem "http":
  In Gemfile:
    google-dfp-api (~> 0.10.1) ruby depends on
      google-ads-common (~> 0.10.1) ruby depends on
        httpi (~> 1.1.0) ruby

    savon (~> 2.3.0) ruby depends on
      httpi (2.1.0)
```

please.. any help is welcome.. Thanks!

**Comment by segiddins** [comment]
That's an unresolvable conflict. You can't use that version of `google-dap-api` with that version of `savon`, as the error message says.
