### ISSUE TITLE
bundler package --all & bundle install --deployment do not work together when referencing local gems

### ISSUE THREAD

**Issue by arjunsharma** [bundler/bundler#4062]
I have created a repository with steps to reproduce, and a code example, here: https://github.com/arjunsharma/shared_local_gems_issue

Here's the TL;DR:

I have a couple of Rails apps that share local gems. When I deploy one of those apps to a PaaS like Pivotal Web Services (PWS), which uses CloudFoundry, only the Rails directory is pushed. This means that my directory that contains the shared local gems, which lives outside of both of the Rails apps, does not get pushed.

I have worked around this by using `bundle package --all && bundle install` to vendor my gems in `vendor/cache`. When I push my app to PWS, the buildpack it uses (based on the Heroku buildpack, which runs the same bundler commands) runs "bundle install --deployment". This errors out because my Gemfile.lock points to my `vendor/cache` directory, while my Gemfile points to the directory where the shared gems live. Here is the error:

```
You are trying to install in deployment mode after changing
your Gemfile. Run `bundle install` elsewhere and add the
updated Gemfile.lock to version control.

You have added to the Gemfile:
* source: source at ../components/shared_gem

You have deleted from the Gemfile:
* source: source at vendor/cache/shared_gem
```

My current workaround is to use a ternary to tell bundler to look in `vendor/cache` if the local directory isn't present. This works because `bundler install --deployment` is only run during deployment, which is when I need bundler to point to `vendor/cache`.

I'm open to trying to help patch this issue if there's a change that needs to be made in Bundler. If there's another way I should be approaching this issue, I'm also happy to test out alternate solutions and close this issue. The real client project I'm working on where this issue came up has > 10 local gems, and having 10 ternaries in my Gemfile isn't my favorite solution to this issue.

Thanks.

**Comment by indirect** [comment]
I'm not entirely sure this is a bug—changing the path of a gem is not allowed during --deployment mode. If you actively want to change the path only during deploys, I think you should not be using --deployment (although then you lose the guard against desynchronized Gemfiles and locks that deploy mode provides ). If you don't want to change the path, why not have your deploy script create a symlink at the location where Bundler expects to find the gem?

**Comment by arjunsharma** [comment]
My concern is that I'm not sure if `bundle package --all && bundle install` should be changing the Gemfile.lock, although I will readily admit that despite doing a lot of Ruby development for the last few years I'm certainly not a bundler expert.

After running those two commands in my sample code, the Gemfile.lock now says:
```
PATH
  remote: vendor/cache/shared_gem
  specs:
    shared_gem (0.1.0)
```

But my Gemfile continues to say:
```
gem 'shared_gem', path: '../components/shared_gem'
```
which is an invalid state for `bundle install --deployment`, which is what the most common Ruby buildpacks do. ([Here](https://github.com/heroku/heroku-buildpack-ruby/blob/8db0a60e1d0148611cd6dd075c339548ee8ae2e3/lib/language_pack/ruby.rb#L550) is where it does it in the Heroku Ruby buildpack, the CloudFoundry Ruby buildpack is forked from that).

If this is the expected behavior, then I will probably continue to maintain the ternary in my Gemfile to make it work for deployments rather than manage symlinks. It just feels like a hacky workaround for what seems to be a valid use case.

The other possibility is that maybe the buildpacks shouldn't do a "bundle install --deployment" if the gems are already present in vendor/cache?

**Comment by indirect** [comment]
What do you think would make sense in this situation? It seems bad to modify your Gemfile, and --deployment mode by definition raises an exception of the lock and Gemfile don't match. As a result, I'd suggest symlinking `vendor/cache/component` to `../../../component` in development, and then changing your Gemfile to match.

**Comment by agis-** [comment]
Closing this due to lack of feedback.
