### ISSUE TITLE
Unable to run gem install bundler

### ISSUE THREAD

**Issue by sahilbabbar** [bundler/bundler#4065]
I am unable to run ```gem install bundler``` as it is giving the following error:

>ERROR:  While executing gem ... (Errno::EPERM)
>Operation not permitted - /usr/bin/bundle

I had recently upgraded to El Capitan and facing *Nokogiri* gem issue and for more details see: https://github.com/sparklemotion/nokogiri/issues/1367

**Comment by segiddins** [comment]
This is not a bundler issue -- you'll need to install the gem binstubs to a directory you have write permissions for.

**Comment by sahilbabbar** [comment]
Are you talking about this gem => https://rubygems.org/gems/rubocop_prefer_binstubs

But I am the super user and therefore, should have permissions.

**Comment by segiddins** [comment]
No, you'll need to either change your `GEM_HOME` or do something like `sudo gem install bundler -n /usr/local/bin` because of El Cap's introduction of SIP (System Integrity Protection).

**Comment by sahilbabbar** [comment]
Thanks for assistance, @segiddins. But it would be greatly helpful if you can be specific in the commands that need to be followed.

**Comment by davinci06** [comment]
Could not find nokogiri-1.6.6.2 in any of the sources
Run `bundle install` to install missing gems. 
The OS X El Capitan

**Comment by zsb87** [comment]
segiddins ' s answer is awesome! Thank you@segiddins

**Comment by ekinetz** [comment]
Thank you @segiddins ! You saved me a lot of time

**Comment by davidskeck** [comment]
Thank you @segiddins :+1:

**Comment by zwgithub** [comment]
thanks

**Comment by YanHaovvGo** [comment]
Thank you @segiddins

**Comment by Strangehill** [comment]
A solution that has worked for me is installing rbenv, and switching away from the built-in version of ruby to a new ruby installation, e.g. `rbenv global 2.2.3`

**Comment by splurtcake** [comment]
Thank you @segiddins — this was driving me crazy

**Comment by petermikitsh** [comment]
@segiddins' solution worked for me, thank you.

**Comment by johuder33** [comment]
@segiddins thank you, you save a lot of my time. 👍

**Comment by indirect** [comment]
@segiddins I'm thinking maybe we should add an explanation about this to rubygems? (not that it will help right away, but maybe eventually 😝)

**Comment by segiddins** [comment]
@indirect sure, open up an issue there with some wording?

**Comment by nevercodealone** [comment]
segiddins post

`sudo gem install bundler -n /usr/local/bin`

fixed it for me
