### ISSUE TITLE
Rails app not working after bundle install --path

### ISSUE THREAD

**Issue by brchristian** [bundler/bundler#4068]
Not sure if this is the right place to report this issue I'm having, so apologies in advance if not, but any words of wisdom would be a huge help. I'm working on a Rails app in an Ubuntu environment using Rbenv and Bundler. In my app folder, I can run `bundle exec rails console`, `bundle exec rails server`, etc., and all work fine.

I run `bundle` and see `Bundle complete!` Everything still works.

However, I'd like to have my bundle in a shared folder. When I run `bundle install --path /home/deploy/domains/myapp/shared/bundle` I get a similar `Bundle complete!` message but now my app doesn't work:

    deploy@myapp:~/domains/myapp/releases/new_release_path$ bundle exec rails console
    /home/deploy/domains/myapp/shared/bundle/ruby/2.2.0/bin/rails:23:in `load': cannot load such file -- /home/deploy/domains/myapp/shared/bundle/ruby/2.2.0/specifications/bin/rails (LoadError)
    	from /home/deploy/domains/myapp/shared/bundle/ruby/2.2.0/bin/rails:23:in `<main>'

Nothing I can do will seem to get the app working. If I remove the newly created `.bundle/` folder by `rm -rf .bundle/`, the app works again.

What's going on here, and how can I get the `bundle install --path` to happen without breaking my app?

If it's useful, running `bundle env` seems to show the only noticeable difference as being that after installing with the path flag, I see:

Bundler settings

    path
      Set for your local app (/home/deploy/domains/myapp/releases/new_release_path/.bundle/config): "/home/deploy/domains/myapp/shared/bundle"
    disable_shared_gems
      Set for your local app (/home/deploy/domains/myapp/releases/new_release_path/.bundle/config): "1"

I'm not deeply familiar with how Bundler works under the hood, so thanks for any pointers!

**Comment by indirect** [comment]
Rails does not support bundle exec as of 4.0+. You need to run the `bin/rails` in your app directory instead.
