### ISSUE TITLE
Unfortunately, an unexpected error occurred, and Bundler cannot continue.

### ISSUE THREAD

**Issue by kumarh01** [bundler/bundler#4081]
What did you do?

  I ran the command `C:/Ruby22-x64/bin/bundle exec rspec`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what actually happened was...

Error details

    Errno::ENOEXEC: Exec format error - rspec
      C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/cli/exec.rb:33:in `exec'
      C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/cli/exec.rb:33:in `run'
      C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/cli.rb:279:in `exec'
      C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/cli.rb:10:in `start'
      C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/bin/bundle:20:in `block in <top (required)>'
      C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
      C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/bin/bundle:18:in `<top (required)>'
      C:/Ruby22-x64/bin/bundle:23:in `load'
      C:/Ruby22-x64/bin/bundle:23:in `<main>'

Environment

    Bundler   1.10.6
    Rubygems  2.4.8
    Ruby      2.2.3p173 (2015-08-18 revision 51636) [x64-mingw32]
    GEM_HOME  C:/Ruby22-x64/lib/ruby/gems/2.2.0
    GEM_PATH  C:/Ruby22-x64/lib/ruby/gems/2.2.0;C:/Users/kumar/.gem/ruby/2.2.0
    Git       not installed

Bundler settings

    bin_path
      Set via BUNDLE_BIN_PATH: "C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/bin/bundle"
    gemfile
      Set via BUNDLE_GEMFILE: "C:/Ruby22-x64/bin/Gemfile"
--- TEMPLATE END ----------------------------------------------------------------

**Comment by segiddins** [comment]
So it looks like we need to rescue ENOEXEC and make that a better error
