### ISSUE TITLE
Error after type command 'bundle install'

### ISSUE THREAD

**Issue by sopheak-se** [bundler/bundler#4084]
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `/usr/bin/bundle install`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what actually happened was...

Error details

    Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /usr/bin/ruby2.1 extconf.rb
/home/sopheak/.rvm/rubies/ruby-2.0.0-p643/lib/ruby/gems/2.0.0/gems/executable-hooks-1.3.2/lib/executable-hooks/regenerate_binstubs_command.rb:71:in `initialize': Permission denied @ rb_sysopen - /usr/bin/rake (Errno::EACCES)
	from /home/sopheak/.rvm/rubies/ruby-2.0.0-p643/lib/ruby/gems/2.0.0/gems/executable-hooks-1.3.2/lib/executable-hooks/regenerate_binstubs_command.rb:71:in `open'
	from /home/sopheak/.rvm/rubies/ruby-2.0.0-p643/lib/ruby/gems/2.0.0/gems/executable-hooks-1.3.2/lib/executable-hooks/regenerate_binstubs_command.rb:71:in `block in try_to_fix_binstubs'
	from /home/sopheak/.rvm/rubies/ruby-2.0.0-p643/lib/ruby/gems/2.0.0/gems/executable-hooks-1.3.2/lib/executable-hooks/regenerate_binstubs_command.rb:69:in `map'
	from /home/sopheak/.rvm/rubies/ruby-2.0.0-p643/lib/ruby/gems/2.0.0/gems/executable-hooks-1.3.2/lib/executable-hooks/regenerate_binstubs_command.rb:69:in `try_to_fix_binstubs'
	from /home/sopheak/.rvm/rubies/ruby-2.0.0-p643/lib/ruby/gems/2.0.0/gems/executable-hooks-1.3.2/lib/executable-hooks/regenerate_binstubs_command.rb:46:in `block in execute_no_wrapper'
	from /home/sopheak/.rvm/rubies/ruby-2.0.0-p643/lib/ruby/gems/2.0.0/gems/executable-hooks-1.3.2/lib/executable-hooks/regenerate_binstubs_command.rb:44:in `each'
	from /home/sopheak/.rvm/rubies/ruby-2.0.0-p643/lib/ruby/gems/2.0.0/gems/executable-hooks-1.3.2/lib/executable-hooks/regenerate_binstubs_command.rb:44:in `execute_no_wrapper'
	from extconf.rb:19:in `<main>'
executable-hooks 1.3.2
rake 10.1.0

extconf failed, exit code 1

Gem files will remain installed in /home/sopheak/.rvm/gems/ruby-2.0.0-p643@global/gems/executable-hooks-1.3.2 for inspection.
Results logged to /home/sopheak/.rvm/gems/ruby-2.0.0-p643@global/extensions/x86_64-linux/2.1.0/executable-hooks-1.3.2/gem_make.out

      /usr/lib/ruby/2.1.0/rubygems/ext/builder.rb:89:in `run'
      /usr/lib/ruby/2.1.0/rubygems/ext/ext_conf_builder.rb:38:in `block in build'
      /usr/lib/ruby/2.1.0/tempfile.rb:324:in `open'
      /usr/lib/ruby/2.1.0/rubygems/ext/ext_conf_builder.rb:17:in `build'
      /usr/lib/ruby/2.1.0/rubygems/ext/builder.rb:161:in `block (2 levels) in build_extension'
      /usr/lib/ruby/2.1.0/rubygems/ext/builder.rb:160:in `chdir'
      /usr/lib/ruby/2.1.0/rubygems/ext/builder.rb:160:in `block in build_extension'
      /usr/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
      /usr/lib/ruby/2.1.0/rubygems/ext/builder.rb:159:in `build_extension'
      /usr/lib/ruby/2.1.0/rubygems/ext/builder.rb:198:in `block in build_extensions'
      /usr/lib/ruby/2.1.0/rubygems/ext/builder.rb:195:in `each'
      /usr/lib/ruby/2.1.0/rubygems/ext/builder.rb:195:in `build_extensions'
      /usr/lib/ruby/2.1.0/rubygems/specification.rb:1436:in `block in build_extensions'
      /usr/lib/ruby/2.1.0/rubygems/user_interaction.rb:45:in `use_ui'
      /usr/lib/ruby/2.1.0/rubygems/specification.rb:1434:in `build_extensions'
      /usr/lib/ruby/2.1.0/rubygems/stub_specification.rb:60:in `build_extensions'
      /usr/lib/ruby/2.1.0/rubygems/basic_specification.rb:56:in `contains_requirable_file?'
      /usr/lib/ruby/2.1.0/rubygems/specification.rb:925:in `block in find_inactive_by_path'
      /usr/lib/ruby/2.1.0/rubygems/specification.rb:924:in `each'
      /usr/lib/ruby/2.1.0/rubygems/specification.rb:924:in `find'
      /usr/lib/ruby/2.1.0/rubygems/specification.rb:924:in `find_inactive_by_path'
      /usr/lib/ruby/2.1.0/rubygems.rb:185:in `try_activate'
      /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:132:in `rescue in require'
      /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:144:in `require'
      /usr/lib/ruby/vendor_ruby/net/http/persistent.rb:12:in `<top (required)>'
      /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
      /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
      /usr/lib/ruby/vendor_ruby/bundler/vendored_persistent.rb:9:in `<top (required)>'
      /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
      /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
      /usr/lib/ruby/vendor_ruby/bundler/fetcher.rb:1:in `<top (required)>'
      /usr/lib/ruby/vendor_ruby/bundler/cli/install.rb:98:in `run'
      /usr/lib/ruby/vendor_ruby/bundler/cli.rb:162:in `install'
      /usr/lib/ruby/vendor_ruby/thor/command.rb:27:in `run'
      /usr/lib/ruby/vendor_ruby/thor/invocation.rb:126:in `invoke_command'
      /usr/lib/ruby/vendor_ruby/thor.rb:359:in `dispatch'
      /usr/lib/ruby/vendor_ruby/thor/base.rb:440:in `start'
      /usr/lib/ruby/vendor_ruby/bundler/cli.rb:10:in `start'
      /usr/bin/bundle:20:in `block in <main>'
      /usr/lib/ruby/vendor_ruby/bundler/friendly_errors.rb:7:in `with_friendly_errors'
      /usr/bin/bundle:18:in `<main>'

Environment

    Bundler   1.10.6
    Rubygems  2.2.2
    Ruby      2.1.5p273 (2014-11-13 revision 0) [x86_64-linux-gnu]
    GEM_HOME  /home/sopheak/.rvm/gems/ruby-2.0.0-p643
    GEM_PATH  /home/sopheak/.rvm/gems/ruby-2.0.0-p643:/home/sopheak/.rvm/gems/ruby-2.0.0-p643@global
    RVM       1.26.11 (latest)
    Git       2.6.2
    rubygems-bundler (1.4.4)
--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/bundler/bundler/search?q=ERROR%3A+Failed+to+build+gem+native+extension.&type=Issues

If there aren't any reports for this error yet, please create copy and paste the report template above into a new issue. Don't forget to anonymize any private data! The new issue form is located at:
https://github.com/bundler/bundler/issues/new

**Comment by indirect** [comment]
This has nothing to do with Bundler, and is a problem created entirely by the executable-hooks gem.
