### ISSUE TITLE
How I can use command line gem without preloading Gemfile from folder where it's executed?

### ISSUE THREAD

**Issue by igorkasyanchuk** [bundler/bundler#4086]
PLEASE HELP 

http://stackoverflow.com/questions/33435734/gem-development-not-load-other-gemfile

I've an issue with gem file development, for example I'm creating a gem with executable command.

It all works well, I can run command, BUT I've issue that if I'm trying to run command inside another project folder it's USING Gemfile from this second project.

Can I somehow disable it? I want only to use Gemfile (and .gemspec) from my gem, and not with folder where it was executed.

Thanks Igor

**Comment by segiddins** [comment]
You can set the BUNLDE_GEMFILE env variable to tell bundler what file to read as your GEMFILE.

**Comment by bronzdoc** [comment]
@igorkasyanchuk did @segiddins suggestion solved your problem?
