### ISSUE TITLE
Bundler fails on bundle update on jruby-9.0.1.0. dependency on byebug 6.0.2

### ISSUE THREAD

**Issue by MonkeyOfRoll** [bundler/bundler#4088]
Hi - I am new to ruby, so will do my best to explain this problem - hopefully this is the right place, though I understand that this could equally be a problem with jruby or something else in my setup. 

I am using 
bundler-1.10.6  
jruby-9.0.1.0
on OSX

when attempting a bundle update, it tries to install byebug 6.0.2, but cannot due to jruby not supporting c extensions:

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

   /xxxxx/xxxxxxx/.rvm/rubies/jruby-9.0.1.0/bin/jruby -r ./siteconf20151030-50067-48g5im.rb extconf.rb
NotImplementedError: C extensions are not supported
    <top> at /xxxxx/xxxxxxx/rubies/jruby-9.0.1.0/lib/ruby/stdlib/mkmf.rb:1
  require at org/jruby/RubyKernel.java:939
   (root) at /xxxxx/xxxxxxx/.rvm/rubies/jruby-9.0.1.0/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:1
    <top> at extconf.rb:6

extconf failed, exit code 1

Gem files will remain installed in /xxxxx/xxxxxxx/.rvm/gems/jruby-9.0.1.0/gems/byebug-6.0.2 for inspection.
Results logged to /xxxxx/xxxxxxx/.rvm/gems/jruby-9.0.1.0/extensions/universal-java-1.7/2.2.0/byebug-6.0.2/gem_make.out
An error occurred while installing byebug (6.0.2), and Bundler cannot continue.
Make sure that `gem install byebug -v '6.0.2'` succeeds before bundling.

If you try gem install byebug -v '6.0.2' you get the same error - as expected. jruby does not support c extensions.

Bundler appears to be the gem with a dependency on byebug, when using the reverse dependencies command on byebug.

Should I use a specific version of bundler on jruby?

**Comment by segiddins** [comment]
Bundler has no dependencies

**Comment by deivid-rodriguez** [comment]
@MonkeyOfRoll `byebug`, unfortunately, does not support `jruby`. So if your app is `jruby` only, just remove it from your `Gemfile`. In any case, this is certainly not a problem in `bundler`.
