### ISSUE TITLE
Error on bundle install

### ISSUE THREAD

**Issue by hennersz** [bundler/bundler#4092]
- What did you do?

  I ran the command `/usr/local/rvm/gems/ruby-2.2.1/bin/bundle install --deployment --without development test`

- What did you expect to happen?

  I expected Bundler to...

install gems for my rails app

- What happened instead?

  Instead, what actually happened was...

Error details

    Errno::EACCES: Permission denied @ dir_s_mkdir - /var/www/myapp/code/.bundle
      /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/fileutils.rb:252:in `mkdir'
      /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/fileutils.rb:252:in `fu_mkdir'
      /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/fileutils.rb:226:in `block (2 levels) in mkdir_p'
      /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/fileutils.rb:224:in `reverse_each'
      /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/fileutils.rb:224:in `block in mkdir_p'
      /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/fileutils.rb:210:in `each'
      /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/fileutils.rb:210:in `mkdir_p'
      /usr/local/rvm/gems/ruby-2.2.1/gems/bundler-1.10.6/lib/bundler/settings.rb:208:in `set_key'
      /usr/local/rvm/gems/ruby-2.2.1/gems/bundler-1.10.6/lib/bundler/settings.rb:31:in `[]='
      /usr/local/rvm/gems/ruby-2.2.1/gems/bundler-1.10.6/lib/bundler/cli/install.rb:76:in `run'
      /usr/local/rvm/gems/ruby-2.2.1/gems/bundler-1.10.6/lib/bundler/cli.rb:162:in `install'
      /usr/local/rvm/gems/ruby-2.2.1/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /usr/local/rvm/gems/ruby-2.2.1/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /usr/local/rvm/gems/ruby-2.2.1/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /usr/local/rvm/gems/ruby-2.2.1/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /usr/local/rvm/gems/ruby-2.2.1/gems/bundler-1.10.6/lib/bundler/cli.rb:10:in `start'
      /usr/local/rvm/gems/ruby-2.2.1/gems/bundler-1.10.6/bin/bundle:20:in `block in <top (required)>'
      /usr/local/rvm/gems/ruby-2.2.1/gems/bundler-1.10.6/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
      /usr/local/rvm/gems/ruby-2.2.1/gems/bundler-1.10.6/bin/bundle:18:in `<top (required)>'
      /usr/local/rvm/gems/ruby-2.2.1/bin/bundle:23:in `load'
      /usr/local/rvm/gems/ruby-2.2.1/bin/bundle:23:in `<main>'
      /usr/local/rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
      /usr/local/rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'

Environment

    Bundler   1.10.6
    Rubygems  2.4.8
    Ruby      2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]
    GEM_HOME  /usr/local/rvm/gems/ruby-2.2.1
    GEM_PATH  /usr/local/rvm/gems/ruby-2.2.1:/usr/local/rvm/gems/ruby-2.2.1@global
    RVM       1.26.11 (latest)
    Git       1.8.3.1
    rubygems-bundler (1.4.4)

Bundler settings

    frozen
      Set for your local app (/var/www/myapp/code/.bundle/config): "1"

**Comment by segiddins** [comment]
This now prints a more informative error on `master` -- you need to have write permissions for `.bundle`.
