### ISSUE TITLE
Error loading RubyGems plugin "/home/bsfx/.rvm/gems/jruby-1.7.19@global/gems/executable-hooks-1.3.2/lib/rubygems_plugin.rb": load error: rubygems/security -- java.lang.ExceptionInInitializerError: null (LoadError)

### ISSUE THREAD

**Issue by jiafuguang870519** [bundler/bundler#4093]
Error loading RubyGems plugin "/home/bsfx/.rvm/gems/jruby-1.7.19@global/gems/executable-hooks-1.3.2/lib/rubygems_plugin.rb": load error: rubygems/security -- java.lang.ExceptionInInitializerError: null (LoadError)
――― ERROR REPORT TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――
- What did you do?
- What did you expect to happen?
- What happened instead?

Error details

    NoMethodError: undefined method `reset' for Gem::Security:Module
    /home/bsfx/.rvm/rubies/jruby-1.7.19/lib/ruby/shared/rubygems.rb:283:in `clear_paths'
    /home/bsfx/.rvm/gems/jruby-1.7.19@global/gems/bundler-1.9.4/lib/bundler/rubygems_integration.rb:122:in `clear_paths'
    /home/bsfx/.rvm/gems/jruby-1.7.19@global/gems/bundler-1.9.4/lib/bundler.rb:436:in `configure_gem_home'
    /home/bsfx/.rvm/gems/jruby-1.7.19@global/gems/bundler-1.9.4/lib/bundler.rb:427:in `configure_gem_home_and_path'
    /home/bsfx/.rvm/gems/jruby-1.7.19@global/gems/bundler-1.9.4/lib/bundler.rb:92:in `configure'
    /home/bsfx/.rvm/gems/jruby-1.7.19@global/gems/bundler-1.9.4/lib/bundler.rb:153:in `definition'
    /home/bsfx/.rvm/gems/jruby-1.7.19@global/gems/bundler-1.9.4/lib/bundler/cli/install.rb:78:in `run'
    /home/bsfx/.rvm/gems/jruby-1.7.19@global/gems/bundler-1.9.4/lib/bundler/cli.rb:157:in `install'
    /home/bsfx/.rvm/gems/jruby-1.7.19@global/gems/bundler-1.9.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
    /home/bsfx/.rvm/gems/jruby-1.7.19@global/gems/bundler-1.9.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
    /home/bsfx/.rvm/gems/jruby-1.7.19@global/gems/bundler-1.9.4/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
    /home/bsfx/.rvm/gems/jruby-1.7.19@global/gems/bundler-1.9.4/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
    /home/bsfx/.rvm/gems/jruby-1.7.19@global/gems/bundler-1.9.4/lib/bundler/cli.rb:10:in `start'
    /home/bsfx/.rvm/gems/jruby-1.7.19@global/gems/bundler-1.9.4/bin/bundle:20:in `(root)'
    /home/bsfx/.rvm/gems/jruby-1.7.19@global/gems/bundler-1.9.4/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
    /home/bsfx/.rvm/gems/jruby-1.7.19@global/gems/bundler-1.9.4/bin/bundle:18:in `(root)'
    org/jruby/RubyKernel.java:1087:in `load'
    /home/bsfx/.rvm/gems/jruby-1.7.19@global/bin/bundle:1:in `(root)'
    org/jruby/RubyKernel.java:1107:in `eval'
    /home/bsfx/.rvm/gems/jruby-1.7.19@global/bin/jruby_executable_hooks:15:in `(root)'

Environment

    Bundler   1.9.4
    Rubygems  2.4.5
    Ruby      1.9.3p551 (2015-01-29 revision 48406) [java]
    GEM_HOME  /home/bsfx/.rvm/gems/jruby-1.7.19@jfg_gems
    GEM_PATH  /home/bsfx/.rvm/gems/jruby-1.7.19@jfg_gems:/home/bsfx/.rvm/gems/jruby-1.7.19@global
    RVM       1.25.28 (stable)
    Git       1.7.9.5
    rubygems-bundler (1.4.4)
――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/bundler/bundler/search?q=undefined+method+%60reset%27+for+Gem%3A%3ASecurity%3AModule&type=Issues

If there aren't any reports for this error yet, please create copy and paste the report template above into a new issue. Don't forget to anonymize any private data! The new issue form is located at:
https://github.com/bundler/bundler/issues/new

**Comment by segiddins** [comment]
This looks like a rubygems or a plugin bug. What makes you think this is an issue in bundler itself?
