### ISSUE TITLE
--no-coc and --no-mit options does not work

### ISSUE THREAD

**Issue by bolshakov** [bundler/bundler#4094]
I'm running the following command:

```
> bundle --version
Bundler version 1.10.6
> bundle gem my_gem --no-coc --no-mit
```

But it ignores my options and generate MIT license CODE_OF_CONDUCT file

**Comment by segiddins** [comment]
I seem to recall us fixing that at some point? Can you check if the issue still exists on master?

**Comment by rgb-one** [comment]
I just tested it on master. When I run it the options `--no-coc`, `--no-mit` seem to be ignored as I am still prompted as to whether or not I would like to add a Code of Conduct and an MIT licence file. I would think that those two prompts would be bypassed and only the testing prompt would show but that's not the case; I get all three prompts.

Here is the input/output:
~~~
:~$ dbundle -v
Bundler version 1.11.0.pre.2
:~$ bundle gem my_gem --no-coc --no-mit
Creating gem 'my_gem'...
Do you want to include a code of conduct in gems you generate?
Codes of conduct can increase contributions to your project by contributors who prefer collaborative, safe spaces. You can read more about the code of conduct at contributor-covenant.org. Having a code of conduct means agreeing to the responsibility of enforcing it, so be sure that you are prepared to do that. For suggestions about how to enforce codes of conduct, see bit.ly/coc-enforcement. y/(n): n
Do you want to license your code permissively under the MIT license?
This means that any other developer or company will be legally allowed to use your code for free as long as they admit you created it. You can read more about the MIT license at choosealicense.com/licenses/mit. y/(n): n
Do you want to generate tests with your gem?
Type 'rspec' or 'minitest' to generate those test files now and in the future. rspec/minitest/(none): none
      create  my_gem/Gemfile
      create  my_gem/.gitignore
      create  my_gem/lib/my_gem.rb
      create  my_gem/lib/my_gem/version.rb
      create  my_gem/my_gem.gemspec
      create  my_gem/Rakefile
      create  my_gem/README.md
      create  my_gem/bin/console
      create  my_gem/bin/setup
Initializing git repo in /home/vagrant/my_gem
:~$ ls my_gem/
bin  Gemfile  lib  my_gem.gemspec  Rakefile  README.md
~~~

**Comment by rgb-one** [comment]
Working on master.

**Comment by RochesterinNYC** [comment]
@rgb-one Is this reopened because it's not working on master/the latest release?

**Comment by rgb-one** [comment]
@RochesterinNYC Yea. It seems this hasn't reached master yet.

**Comment by rgb-one** [comment]
Closed accidentally just now :p

**Comment by RochesterinNYC** [comment]
Hm, this is on master according to the following: https://github.com/bundler/bundler/commit/6c18c55406e386c6b9d591b589360face9211096 ? 
Maybe I don't understand the release flow for Bundler?

**Comment by rgb-one** [comment]
Have a go yourself.I tried `bundle gem my_gem --no-coc --no-mit` and still got prompted if I wanted to use a CODE_OF_CONDUCT or licence file.

**Comment by rgb-one** [comment]
The way it seems to works is that when you are prompted for the first time with the 3 choices (COC, MIT, test framework) your reply is logged in the `.bundler/config` file. So if I reply no to the CODE_OF_CONDUCT.md, no to the LICENCE.txt and no to the test framework, these options are stored in the `.bundler/config` as:
```
BUNDLE_GEM__COC: false
BUNDLE_GEM__MIT: false
BUNDLE_GEM__TEST: false
```

These setting persist after creating my_gem so `bundle gem` will create any new gems project without these files (so running `bundle gem my_gem --no-coc --no-mit` wouldn't do anything).

On the other hand, running `bundle gem my_gem --coc`, `bundle gem my_gem --mit` and `bundle gem my_gem --test` and the combo of all three flags work as expected.

What does the fix add to this? It seems to work fine as is.

**Comment by RochesterinNYC** [comment]
Oh okay, gotcha, so the behavior that my PR fixed was that the --no-coc and --no-mit flags were completely ignored and did not work at all. They were being overridden by the default configs set by the first time the user answers those prompts. The behavior now is that if you have your `.bundler/config` settings set, `--no-coc` and/or `--no-mit` will override those settings for the execution of that one command. Nothing's been changed or fixed regarding prompting the user to set the defaults for those while those flags are used. However, I see your point in that using the `--no-mit` and `--no-coc` flags should not have the user face the prompts and simply not create `LICENSE.txt` and `CODE_OF_CONDUCT.md`. The user shouldn't be faced with the prompts (if they haven't set default configs yet) until the next time that they run the `bundle gem ____` command without those flags, correct?

Also, for your second case, does that not work on master? I just tried it with master and using `--no-coc` and `--no-mit` successfully overrides the default configs that you set during user prompts for that one execution, which was the desired behavior. I.e. if you use `bundle gem testing --no-coc`, it will bypass whatever `BUNDLE_GEM__COC` value you have set and not create a `CODE_OF_CONDUCT.md`.

**Comment by rgb-one** [comment]
>However, I see your point in that using the --no-mit and --no-coc flags should not have the user face the prompts and simply not create LICENSE.txt and CODE_OF_CONDUCT.md. The user shouldn't be faced with the prompts (if they haven't set default configs yet) until the next time that they run the bundle gem ____ command without those flags, correct? If so, I'd be willing to write another PR that fixes this behavior.

I actually wasn't trying to make a point. The intention was to state my observations with the idea that it bring about some clarity on what was going on in case something was missed. But yea, what you said about the user not being prompted for the `CODE_OF_CONDUCT.md`, or the `LICENCE.txt` when running `--no-coc` or `--no-mit` for the first time sounds good. However, this poses a few issues. This assumes that adding the `CODE_OF_CONDUCT.md` and `LICENCE.txt` file is default behavior for bundler when running the `bundle gem` command when the actual default action is to prompt the user to make 3 choices. Also, what about the testing framework option? If only `--no-coc` and `--no-mit` are chosen, will the user still be prompted to select a test framework?

For the second case, it works. The problem was that I was using bundler version `1.10.6` instead of `master` (`1.11.2`).

**Comment by RochesterinNYC** [comment]
@indirect @segiddins so what is the desired user behavior/story here regarding the `mit`, `coc`, and `test` flags interfacing with the configuring default settings prompts?

Do we want to have `--no-coc`, `--no-mit`, `--mit`, and `--no-mit` override any "ask the user for default configs" behavior and only prompt them for a `mit`, `coc`, or `test` setting if both there are no default settings and they don't have a flag relating to that setting activated? When they don't have any default settings, it does feel a bit odd UX wise to pass a `--mit` or `--no-mit` flag (knowing that this definitely will or will not create a `LICENSE.txt`) and then being immediately prompted "`Do you want to license your code permissively under the MIT license?`"

The user story would be something like:
```
Given I'm a Bundler user
When I use a --mit flag in executing 'bundler gem'
Then I should not be prompted at all about MIT Licenses
Because I used the --mit flag knowing this would definitively create a LICENSE.txt
```

And so forth for the other flags.

**Comment by RochesterinNYC** [comment]
Ah gotcha, understood.

@indirect @segiddins so what is the desired user behavior/story here regarding the `mit`, `coc`, and `test` flags interfacing with the configuring default settings prompts?

Do we want to have `--no-coc`, `--no-mit`, `--mit`, and `--no-mit` override any "ask the user for default configs" behavior and only prompt them for a `mit`, `coc`, or `test` setting if both there are no default settings and they don't have a flag relating to that setting activated? When they don't have any default settings, it does feel a bit odd UX wise to pass a `--mit` or `--no-mit` flag (knowing that this definitely will or will not create a `LICENSE.txt`) and then being immediately prompted "`Do you want to license your code permissively under the MIT license?`"

The user story would be something like:
```
Given I'm a Bundler user
When I use a --mit flag in executing 'bundler gem'
Then I should not be prompted at all about MIT Licenses
Because I used the --mit flag knowing this would definitively create a LICENSE.txt
```

And so forth for the other flags.

**Comment by indirect** [comment]
@RochesterinNYC yes, that sounds like the desired behavior.

**Comment by RochesterinNYC** [comment]
Okay, the current behavior for `coc`, `mit`, and the `test` framework options follows that. Think this issue's good to close?

**Comment by indirect** [comment]
Cool, thanks for fixing it!
