### ISSUE TITLE
Bundler changes my Gemfile.lock when I think it shouldn't

### ISSUE THREAD

**Issue by deivid-rodriguez** [bundler/bundler#4096]
##### Gemfile
```ruby
source 'https://rubygems.org'

ENV['VERSION'] ||= '2.2.2'
ENV['ENGINE'] ||= 'jruby'
ENV['ENGINE_VERSION'] ||= '9.0.3.0'

ruby ENV['VERSION'], engine: ENV['ENGINE'],
                     engine_version: ENV['ENGINE_VERSION']

gem 'activerecord-jdbcpostgresql-adapter',
    github: 'jruby/activerecord-jdbc-adapter',
    ref: 'a49eb10427610e4a418d9c0ff87343b1d9358273',
    platform: :jruby

gem 'pg', '0.18.3', platform: :mri
```

##### Gemfile.lock
```
GIT
  remote: git://github.com/jruby/activerecord-jdbc-adapter.git
  revision: a49eb10427610e4a418d9c0ff87343b1d9358273
  ref: a49eb10427610e4a418d9c0ff87343b1d9358273
  specs:
    activerecord-jdbc-adapter (1.3.19)
      activerecord (>= 2.2)
    activerecord-jdbcpostgresql-adapter (1.3.19)
      activerecord-jdbc-adapter (~> 1.3.19)
      jdbc-postgres (>= 9.1)

GEM
  remote: https://rubygems.org/
  specs:
    activemodel (4.2.4)
      activesupport (= 4.2.4)
      builder (~> 3.1)
    activerecord (4.2.4)
      activemodel (= 4.2.4)
      activesupport (= 4.2.4)
      arel (~> 6.0)
    activesupport (4.2.4)
      i18n (~> 0.7)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.3, >= 0.3.4)
      tzinfo (~> 1.1)
    arel (6.0.3)
    builder (3.2.2)
    i18n (0.7.0)
    jdbc-postgres (9.4.1204)
    json (1.8.3-java)
    minitest (5.8.2)
    pg (0.18.3)
    thread_safe (0.3.5-java)
    tzinfo (1.2.2)
      thread_safe (~> 0.1)

PLATFORMS
  java
  ruby

DEPENDENCIES
  activerecord-jdbcpostgresql-adapter!
  pg (= 0.18.3)

BUNDLED WITH
   1.10.6
```

If I run `bundle update` in `jruby`, all good, nothing changes.

If I switch to MRI and run, `VERSION=2.2.3 ENGINE=ruby ENGINE_VERSION=2.2.3 bundle update`, `bundler` actually downgrades my `jruby` dependencies... :open_mouth: 

```diff
diff --git a/Gemfile.lock b/Gemfile.lock
index 48d00ee..26e718c 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -8,6 +8,7 @@ GIT
     activerecord-jdbcpostgresql-adapter (1.3.19)
       activerecord-jdbc-adapter (~> 1.3.19)
       jdbc-postgres (>= 9.1)
+    jdbc-postgres (9.3.1102)
 
 GEM
   remote: https://rubygems.org/
@@ -28,7 +29,6 @@ GEM
     arel (6.0.3)
     builder (3.2.2)
     i18n (0.7.0)
-    jdbc-postgres (9.4.1204)
     json (1.8.3-java)
     minitest (5.8.2)
     pg (0.18.3)
```

Is this unexpected or I'm doing something wrong or unsupported?

**Comment by rgb-one** [comment]
How many times did you try this?

**Comment by deivid-rodriguez** [comment]
I don't remember. How is that possibly relevant?

**Comment by indirect** [comment]
@deivid-rodriguez for the record, Bundler does not officially support lock files across platforms (i.e. between Windows, java, and *nix). Because gems can have completely different dependencies on different platforms, it's not even really possible to create a lock that makes sense on one platform and have it apply on another platform.

We're interested in improving this in the future, but for right now you can't count on an MRI lock being usable in JRuby, and vice versa.

**Comment by deivid-rodriguez** [comment]
@indirect Thanks for that information. Should I close this and reopen if you ever officially support this?

Supporting this officially seems definitely possible since it works already! I've been using this for months and this is the only minor problem I've found. By the way, this got solved when I started using a later reference for `activerecord-jdbcpostgresql-adapter`.

**Comment by indirect** [comment]
@deivid-rodriguez I'm glad you were able to get it working! As you've noticed, it already works in the easy case... the problem is that in the hard case there doesn't seem to be anything that can be done besides keeping separate lock files.

**Comment by deivid-rodriguez** [comment]
@indirect Not sure what we call "the hard case" here but I've been using this with very different bundler features as you can see in the sample `Gemfile` I posted.

Anyways, I'd like to ask a question. What's exactly not officially supported? At first I assumed it was specifying the ruby version dinamically like I'm doing, but after rereading your messages I understand that things like the `platform:` parameter are not officially supported either?

Thanks for your work!
