### ISSUE TITLE
Could not find compatible versions for gem (on Windows)

### ISSUE THREAD

**Issue by davatron5000** [bundler/bundler#4098]
Trying to `bundle install` and add the `did_you_mean` gem but getting this error every time I add a new gem. I shouldn't be getting this error when I'm not touching `nokogiri`. /cc @schneems 

```
Bundler could not find compatible versions for gem "nokogiri":
  In snapshot (Gemfile.lock):
    nokogiri (= 1.6.7.rc3)

  In Gemfile:
    rails (= 4.2.0) ruby depends on
      actionmailer (= 4.2.0) ruby depends on
        rails-dom-testing (>= 1.0.5, ~> 1.0) ruby depends on
          nokogiri (~> 1.6.0) ruby

    nokogiri (~> 1.6.0) x64-mingw32

    nokogiri (~> 1.6.0) x86-mingw32

    nokogiri (= 1.6.7.rc3) x86-mingw32

    nokogiri (= 1.6.7.rc3) x64-mingw32

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
```

Here's my `bundle env` output: https://gist.github.com/davatron5000/cbc910d0f8f4fd323dc9

**Comment by schneems** [comment]
Any ideas on how to move forwards here? Is this expected behavior? Any help is appreciated

**Comment by davatron5000** [comment]
fwiw, I did `bundle update` & `bundle install` a few times and it sorta worked.

**Comment by indirect** [comment]
Closing as "sorta worked", but feel free to let us know if you have problems later.
