### ISSUE TITLE
Upgrade Redmin error

### ISSUE THREAD

**Issue by iversonlin330** [bundler/bundler#4115]
First i got error from the website
-------------------------------------------------------
It looks like Bundler could not find a gem. Maybe you didn't install all the gems that this application needs. To install your gems, please run:

bundle install

If that didn't work, then the problem is probably caused by your application being run under a different environment than it's supposed to. Please check the following:

    Is this app supposed to be run as the www-data user?
    Is this app being run on the correct Ruby interpreter? Below you will see which Ruby interpreter Phusion Passenger attempted to use.

-------- The exception is as follows: -------
Could not find gem 'rails (= 4.2.4) ruby' in any of the gem sources listed in your Gemfile or available on this machine. (Bundler::GemNotFound)

  /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/resolver.rb:347:in `block in verify_gemfile_dependencies_are_found!'
  /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/resolver.rb:325:in `each'
  /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/resolver.rb:325:in `verify_gemfile_dependencies_are_found!'
  /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/resolver.rb:198:in `start'
  /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/resolver.rb:182:in `resolve'
  /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/definition.rb:200:in `resolve'
  /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/definition.rb:140:in `specs'
  /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/definition.rb:185:in `specs_for'
  /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/definition.rb:174:in `requested_specs'
  /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/environment.rb:18:in `requested_specs'
  /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/runtime.rb:13:in `setup'
  /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler.rb:127:in `setup'
  /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/setup.rb:18:in `<top (required)>'
  /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:60:in `require'
  /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:60:in `rescue in require'
  /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:35:in `require'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:245:in `block in run_load_path_setup_code'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:348:in `running_bundler'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:243:in `run_load_path_setup_code'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:100:in `preload_app'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:158:in `<module:App>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:29:in `<module:PhusionPassenger>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:28:in `<main>'

-------------------------------------------------------------
Then i got bundle intstall
---------------------------------------------------
 Errno::EACCES: Permission denied - /usr/share/redmine/.bundle
      /usr/lib/ruby/1.9.1/fileutils.rb:247:in `mkdir'
      /usr/lib/ruby/1.9.1/fileutils.rb:247:in `fu_mkdir'
      /usr/lib/ruby/1.9.1/fileutils.rb:221:in `block (2 levels) in mkdir_p'
      /usr/lib/ruby/1.9.1/fileutils.rb:219:in `reverse_each'
      /usr/lib/ruby/1.9.1/fileutils.rb:219:in `block in mkdir_p'
      /usr/lib/ruby/1.9.1/fileutils.rb:205:in `each'
      /usr/lib/ruby/1.9.1/fileutils.rb:205:in `mkdir_p'
      /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/settings.rb:208:in `set_key'
      /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/settings.rb:31:in `[]='
      /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/settings.rb:199:in `set_array'
      /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/settings.rb:117:in `without='
      /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/cli/install.rb:96:in `run'
      /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/cli.rb:162:in `install'
      /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/cli.rb:10:in `start'
      /var/lib/gems/1.9.1/gems/bundler-1.10.6/bin/bundle:20:in `block in <top (required)>'
      /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
      /var/lib/gems/1.9.1/gems/bundler-1.10.6/bin/bundle:18:in `<top (required)>'
      /usr/local/bin/bundle:23:in `load'
      /usr/local/bin/bundle:23:in `<main>'

Environment

    Bundler   1.10.6
    Rubygems  1.8.23
    Ruby      1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]
    Git       1.9.1

Bundler settings

    without
      Set for your local app (/usr/share/redmine/.bundle/config): "development:test:rmagick"
      Set for the current user (/home/david/.bundle/config): "development:test:rmagick"
-------------------------------------------------

**Comment by fotanus** [comment]
Have you tried to open an issue for redmine? It seems that you do not have write permission on `/usr/share/redmine/`.

**Comment by segiddins** [comment]
This should have a friendlier error message in 1.11.0.pre.1.

**Comment by iversonlin330** [comment]
how can i solve it,thank
