### ISSUE TITLE
Having had time to install bundle on my pc window 10

### ISSUE THREAD

**Issue by devalresourse** [bundler/bundler#4119]
the error report is https://github.com/bundler/bundler/issues?q=Permission+denied+%40+rb_sysopen+-+ Gemfile&type=Issues

**Comment by segiddins** [comment]
Please share the error report?

**Comment by devalresourse** [comment]
Gem:: RemoteFetcher::FetchError: SSL_connect returned=1 errno=) state=SSLv3
read server certificate B: certificate verify failed (
https://rubygems.global.ssl.fastly.net/gems/i18n-0.7.0.gem) An erroe
occured while installing i18n(0.7.0), and Bundler cannot continue. Make
sure that gem install i18n -v '0.7.0' succeeds before bundling.

On Tue, Nov 24, 2015 at 5:01 PM, Samuel E. Giddins <notifications@github.com

**Comment by devalresourse** [comment]
Gem:: RemoteFetcher::FetchError: SSL_connect returned=1 errno=) state=SSLv3 read server certificate B: certificate verify failed (https://rubygems.global.ssl.fastly.net/gems/i18n-0.7.0.gem) An erroe occured while installing i18n(0.7.0), and Bundler cannot continue. Make sure that gem install i18n -v '0.7.0' succeeds before bundling.

**Comment by segiddins** [comment]
And does running gem install succeed for you?

**Comment by devalresourse** [comment]
No it working
