### ISSUE TITLE
`bundle install` does not detect missing gems

### ISSUE THREAD

**Issue by majewsky** [bundler/bundler#4121]
I was trying to debug problems with the connection to my corporate Rubygems mirror, but since `bundle install` does not connect to the server when all the gems are there, I just deleted one of the gems (`rm -r $(bundle show --paths | tail -n 1)` if you want to reproduce). The next `bundle install` did not detect this, it just said "Bundle complete" and exited. Logically, the app would now fail to run since some gems are missing.

Environment is Bundler 1.10.6 on Ruby 2.2.0 on rbenv on an Arch Linux VM. The application did not define a gemset (if it did, I would just have `rm -r`'d the gemset, which `bundle install` actually detects and handles properly).

**Comment by segiddins** [comment]
I believe that's to be expected, as you never removed the specifications.

**Comment by majewsky** [comment]
What is a specification, and where can I find documentation about it?

**Comment by segiddins** [comment]
you really should be using things like `gem uninstall` and `gem pristine`. Since you've manually deleted files, I'm tempted to say this isn't a bundler bug?

**Comment by majewsky** [comment]
Apparently not, although I would appreciate an answer to my question to actually understand what is going on here.

**Comment by segiddins** [comment]
which question?

**Comment by majewsky** [comment]
> What is a specification, and where can I find documentation about it?

My confusion about Bundler's behavior suggests that the documentation is lacking in some way. I did `bundle help install | grep -i specification`, but that does not find anything like a "specification" in the docs.

**Comment by indirect** [comment]
@majewsky removing the path printed by bundle show does not uninstall the gem. Doing things Bundler doesn't support will make Bundler behave unexpectedly.

**Comment by indirect** [comment]
(A specification is a file that contains gem metadata, installed by Bundler into another directory, and used to track what gems have been installed. It's not documented because it's an internal implementation detail.)

**Comment by majewsky** [comment]
I still consider it unexpected behavior that deleting a whole gemset does not upset Bundler in the slightest way, yet deleting a single gem confuses it beyond repair.

**Comment by indirect** [comment]
@majewsky I'm not sure where you got the impression that running `rm -rf` on that path would uninstall that gem, but it definitely doesn't work that way. Please install and uninstall gems using the `bundle` or `gem` commands if you want things to keep working.
