### ISSUE TITLE
Bundle install

### ISSUE THREAD

**Issue by chrome01** [bundler/bundler#4122]
bundle install
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `/Users/Name/.rvm/gems/ruby-2.1.1@myapp/bin/bundle install`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what actually happened was...

Error details

    Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    Permission denied @ dir_s_mkdir - ./.gem.20151125-838-rsn8jt

Gem files will remain installed in /Users/Name/.rvm/gems/ruby-2.1.1@global/gems/curb-0.8.6 for inspection.
Results logged to /Users/Name/.rvm/gems/ruby-2.1.1@global/extensions/x86_64-darwin-14/2.1.0-static/curb-0.8.6/gem_make.out

      /Users/Name/.rbenv/versions/2.1.1/lib/ruby/2.1.0/tmpdir.rb:85:in `mkdir'
      /Users/Name/.rbenv/versions/2.1.1/lib/ruby/2.1.0/tmpdir.rb:85:in `block in mktmpdir'
      /Users/Name/.rbenv/versions/2.1.1/lib/ruby/2.1.0/tmpdir.rb:142:in `create'
      /Users/Name/.rbenv/versions/2.1.1/lib/ruby/2.1.0/tmpdir.rb:85:in `mktmpdir'
      /Users/Name/.rbenv/versions/2.1.1/lib/ruby/2.1.0/rubygems/ext/ext_conf_builder.rb:14:in `build'
      /Users/Name/.rbenv/versions/2.1.1/lib/ruby/2.1.0/rubygems/ext/builder.rb:161:in `block (2 levels) in build_extension'
      /Users/Name/.rbenv/versions/2.1.1/lib/ruby/2.1.0/rubygems/ext/builder.rb:160:in `chdir'
      /Users/Name/.rbenv/versions/2.1.1/lib/ruby/2.1.0/rubygems/ext/builder.rb:160:in `block in build_extension'
      /Users/Name/.rbenv/versions/2.1.1/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
      /Users/Name/.rbenv/versions/2.1.1/lib/ruby/2.1.0/rubygems/ext/builder.rb:159:in `build_extension'
      /Users/Name/.rbenv/versions/2.1.1/lib/ruby/2.1.0/rubygems/ext/builder.rb:198:in `block in build_extensions'
      /Users/Name/.rbenv/versions/2.1.1/lib/ruby/2.1.0/rubygems/ext/builder.rb:195:in `each'
      /Users/Name/.rbenv/versions/2.1.1/lib/ruby/2.1.0/rubygems/ext/builder.rb:195:in `build_extensions'
      /Users/Name/.rbenv/versions/2.1.1/lib/ruby/2.1.0/rubygems/specification.rb:1436:in `block in build_extensions'
      /Users/Name/.rbenv/versions/2.1.1/lib/ruby/2.1.0/rubygems/user_interaction.rb:45:in `use_ui'
      /Users/Name/.rbenv/versions/2.1.1/lib/ruby/2.1.0/rubygems/specification.rb:1434:in `build_extensions'
      /Users/Name/.rbenv/versions/2.1.1/lib/ruby/2.1.0/rubygems/stub_specification.rb:60:in `build_extensions'
      /Users/Name/.rbenv/versions/2.1.1/lib/ruby/2.1.0/rubygems/basic_specification.rb:56:in `contains_requirable_file?'
      /Users/Name/.rbenv/versions/2.1.1/lib/ruby/2.1.0/rubygems/specification.rb:925:in `block in find_inactive_by_path'
      /Users/Name/.rbenv/versions/2.1.1/lib/ruby/2.1.0/rubygems/specification.rb:924:in `each'
      /Users/Name/.rbenv/versions/2.1.1/lib/ruby/2.1.0/rubygems/specification.rb:924:in `find'
      /Users/Name/.rbenv/versions/2.1.1/lib/ruby/2.1.0/rubygems/specification.rb:924:in `find_inactive_by_path'
      /Users/Name/.rbenv/versions/2.1.1/lib/ruby/2.1.0/rubygems.rb:185:in `try_activate'
      /Users/Name/.rbenv/versions/2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:132:in `rescue in require'
      /Users/Name/.rbenv/versions/2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:144:in `require'
      /Users/Name/.rvm/gems/ruby-2.1.1@myapp/gems/bundler-1.10.6/lib/bundler/vendor/net/http/persistent.rb:12:in `<top (required)>'
      /Users/Name/.rbenv/versions/2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
      /Users/Name/.rbenv/versions/2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
      /Users/Name/.rvm/gems/ruby-2.1.1@myapp/gems/bundler-1.10.6/lib/bundler/vendored_persistent.rb:11:in `<top (required)>'
      /Users/Name/.rbenv/versions/2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
      /Users/Name/.rbenv/versions/2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
      /Users/Name/.rvm/gems/ruby-2.1.1@myapp/gems/bundler-1.10.6/lib/bundler/fetcher.rb:1:in `<top (required)>'
      /Users/Name/.rvm/gems/ruby-2.1.1@myapp/gems/bundler-1.10.6/lib/bundler/cli/install.rb:98:in `run'
      /Users/Name/.rvm/gems/ruby-2.1.1@myapp/gems/bundler-1.10.6/lib/bundler/cli.rb:162:in `install'
      /Users/Name/.rvm/gems/ruby-2.1.1@myapp/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /Users/Name/.rvm/gems/ruby-2.1.1@myapp/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /Users/Name/.rvm/gems/ruby-2.1.1@myapp/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /Users/Name/.rvm/gems/ruby-2.1.1@myapp/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /Users/Name/.rvm/gems/ruby-2.1.1@myapp/gems/bundler-1.10.6/lib/bundler/cli.rb:10:in `start'
      /Users/Name/.rvm/gems/ruby-2.1.1@myapp/gems/bundler-1.10.6/bin/bundle:20:in `block in <top (required)>'
      /Users/Name/.rvm/gems/ruby-2.1.1@myapp/gems/bundler-1.10.6/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
      /Users/Name/.rvm/gems/ruby-2.1.1@myapp/gems/bundler-1.10.6/bin/bundle:18:in `<top (required)>'
      /Users/Name/.rvm/gems/ruby-2.1.1@myapp/bin/bundle:23:in `load'
      /Users/Name/.rvm/gems/ruby-2.1.1@myapp/bin/bundle:23:in `<main>'

Environment

    Bundler   1.10.6
    Rubygems  2.2.2
    Ruby      2.1.1p76 (2014-02-24 revision 45161) [x86_64-darwin14.0]
    GEM_HOME  /Users/Name/.rvm/gems/ruby-2.1.1@myapp
    GEM_PATH  /Users/Name/.rvm/gems/ruby-2.1.1@myapp:/Users/Name/.rvm/gems/ruby-2.1.1@global
    RVM       1.26.11 (latest)
    Git       1.9.2
    rubygems-bundler (1.4.3)

Bundler settings

    build.libv8
      Set for the current user (/Users/Name/.bundle/config): "--with-system-v8"
--- TEMPLATE END -------------------Name

**Comment by TimMoore** [comment]
This looks like the problem is that you don't have permission to write to the current directory where you're running bundle.
