### ISSUE TITLE
Use HTTPS for github sources

### ISSUE THREAD

**Issue by dziemba** [bundler/bundler#4126]
The `github` git source [currently uses](https://github.com/bundler/bundler/blob/437f604956e629e1b96270d87f6fdb05b189de2d/lib/bundler/dsl.rb#L222) the git protocol. Since there is no authentication or encryption of any kind, it's insecure to use it over the internet (we already use HTTPS instead of HTTP for rubygems sources when possible). 

I propose we change it to HTTPS, as it is already the case for gists and bitbucket sources. 

[bundler-audit](https://github.com/rubysec/bundler-audit) complains about this already, so Gemfiles
like `gem 'rails', github: 'rails/rails'` will not pass.

**Comment by segiddins** [comment]
This is already done on the 2.0 branch. We can't make this change before then because it would break backwards compatibility.
