### ISSUE TITLE
Probe the configured mirror and drop to the source uri in case it fails

### ISSUE THREAD

**Issue by pcarranza** [bundler/bundler#4128]
To support using *gemstash* in the office and keep the *zero conf* style when the user is not in the same network anymore we could just probe the configured mirror for a given upstream server to check if it is still there. If it is not, we just drop down to the actual upstream server.

The behaviour would be something like this:

open tcp connection to the upstream mirrored with a connection timeout of 0.5 seconds, on timeout, keep the url as is to go for the actual upstream server.

A quick look at the code points me at the `remote.rb` file. Would it be acceptable to probe the server there? should I look any other place in the source? any particular guideline?

cc @indirect

**Comment by TimMoore** [comment]
I'm not sure everyone would want this behavior. Some people want to enforce use of a mirror for security reasons. So I think it would need to be configurable and default to off.

**Comment by indirect** [comment]
Yes, I think that's how I would like it to work for me, too. I would even be happy with a much lower timeout, since the gemstash server should be local if it is going to be available at all. Maybe we can provide this via a `bundle config mirror.URL.fallback true` setting?

**Comment by indirect** [comment]
(I think @TimMoore is right, and we want this to be opt-in for mirror fallback, but for developers using gemstash in their office, this could be really nice.)

**Comment by pcarranza** [comment]
I agree, it makes sense to make it an optional behaviour.

Then the way to enable this fallback is by providing this `.fallback=true` trailing to a mirror url.

Timeout of 0.1 secs? configurable with an option? => `bundle config mirror.URL.fallback_timeout` for ex?

I'll give it a try.

**Comment by pcarranza** [comment]
Just wondering if it makes sense to just enable the `fallback_timeout` and not use the `fallback=true` at all.

**Comment by TimMoore** [comment]
I was thinking the same. If there were two configs, it might be confusing what the behavior should be when `fallback_timeout` is set but `fallback` isn't. Maybe just have `fallback_timeout` which can be set to either a number of milliseconds or `true` to use the default timeout.

**Comment by pcarranza** [comment]
Yep, it makes sense and keeps things neat and simple. I like it.

I'll build it as soon as I can. Thanks for the feedback.

**Comment by pcarranza** [comment]
A feature suggested by @smellsblue that I think makes sense: add support for setting gemstash as the mirror for all the upstreams, something like this: `bundle config mirror.all http://localhost:9292`

That would make gemstash the default server for anything, and we should just send the header to let gemstash know what are we looking for.

**Comment by pcarranza** [comment]
Closing as the PR was merged.
