### ISSUE TITLE
bundle package fails to bundle anything if stdlib-included gems are mentioned in Gemfile 

### ISSUE THREAD

**Issue by krig** [bundler/bundler#4131]
Despite fix #3896, bundler still doesn't succeed in bundling gems when `json` is required. It no longer crashes with a null error, but now no gems are cached at all since bundler exits at a later stage:

```
[   27s] Bundle complete! 18 Gemfile dependencies, 63 gems now installed.
[   27s] Gems in the group test were not installed.
[   27s] Use `bundle show [gemname]` to see where a bundled gem is installed.
[   27s] Updating files in vendor/cache
[   27s]   * i18n-0.7.0.gem
[   27s] json-1.8.1 is built in to Ruby, and can't be cached because your Gemfile doesn't have any sources that contain it.
[   27s] Missing gem file 'json-1.8.1.gem'.
```

**Comment by segiddins** [comment]
What's the output of `bundle env`?

**Comment by krig** [comment]
https://gist.github.com/krig/baa54b145f8e00baf7e2

Bundler version says 1.10.6, but I have patched it with commit 5f2d983fc.

**Comment by segiddins** [comment]
I believe this is behaving as intended. Default gems don't include a `.gem` file we can cache, and since you haven't specified another source to download gems from, there's nowhere bundler could go to get a cachable version of JSON.

**Comment by krig** [comment]
Hmm. The question is how I can make bundler work for me in this case though. I'm fine with bundler not caching gems that are included in the stdlib, but I do need to cache other gems. I can't rely on pulling in gems from the internet, since we need reproducible builds, so adding rubygems.org to the Gemfile is not an option.

**Comment by segiddins** [comment]
You can get a reproducible build by caching, but bundler does need a place to get those gems from to cache, which is what adding the source to your gemfile does.

**Comment by indirect** [comment]
@krig download a copy of that .gem file and place it in /vendor/cache.
