### ISSUE TITLE
string contains null byte

### ISSUE THREAD

**Issue by fuzziness** [bundler/bundler#4133]
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `/Users/harakei/.rvm/gems/ruby-2.2.3@global/bin/bundle install`

- What did you expect to happen?

  I expected Bundler to install gems as usual

- What happened instead?

  Instead, what actually happened was an unexpected error and Bundler cannot continue.

Error details

    ArgumentError: string contains null byte
      /Users/harakei/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/specification.rb:2490:in `directory?'
      /Users/harakei/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/specification.rb:2490:in `block in validate'
      /Users/harakei/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/specification.rb:2490:in `delete_if'
      /Users/harakei/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/specification.rb:2490:in `validate'
      /Users/harakei/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/rubygems_integration.rb:51:in `block in validate'
      /Users/harakei/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/ui/shell.rb:76:in `silence'
      /Users/harakei/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/rubygems_integration.rb:51:in `validate'
      /Users/harakei/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler.rb:370:in `block in load_gemspec_uncached'
      /Users/harakei/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/shared_helpers.rb:53:in `chdir'
      /Users/harakei/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/shared_helpers.rb:53:in `block in chdir'
      /Users/harakei/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
      /Users/harakei/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/shared_helpers.rb:52:in `chdir'
      /Users/harakei/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler.rb:363:in `load_gemspec_uncached'
      /Users/harakei/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler.rb:353:in `load_gemspec'
      /Users/harakei/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/source/path.rb:135:in `block in load_spec_files'
      /Users/harakei/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/source/path.rb:134:in `each'
      /Users/harakei/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/source/path.rb:134:in `load_spec_files'
      /Users/harakei/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/source/path.rb:92:in `local_specs'
      /Users/harakei/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/source/path.rb:100:in `specs'
      /Users/harakei/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/definition.rb:550:in `block in converge_locked_specs'
      /Users/harakei/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/definition.rb:539:in `each'
      /Users/harakei/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/definition.rb:539:in `converge_locked_specs'
      /Users/harakei/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/definition.rb:195:in `resolve'
      /Users/harakei/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/definition.rb:140:in `specs'
      /Users/harakei/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/definition.rb:129:in `resolve_remotely!'
      /Users/harakei/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/installer.rb:79:in `run'
      /Users/harakei/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/installer.rb:18:in `install'
      /Users/harakei/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/cli/install.rb:107:in `run'
      /Users/harakei/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/cli.rb:162:in `install'
      /Users/harakei/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /Users/harakei/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /Users/harakei/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /Users/harakei/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /Users/harakei/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/cli.rb:10:in `start'
      /Users/harakei/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/bin/bundle:20:in `block in <top (required)>'
      /Users/harakei/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
      /Users/harakei/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/bin/bundle:18:in `<top (required)>'
      /Users/harakei/.rvm/gems/ruby-2.2.3@global/bin/bundle:23:in `load'
      /Users/harakei/.rvm/gems/ruby-2.2.3@global/bin/bundle:23:in `<main>'
      /Users/harakei/.rvm/gems/ruby-2.2.3@market_commons/bin/ruby_executable_hooks:15:in `eval'
      /Users/harakei/.rvm/gems/ruby-2.2.3@market_commons/bin/ruby_executable_hooks:15:in `<main>'

Environment

    Bundler   1.10.6
    Rubygems  2.4.5.1
    Ruby      2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin14]
    GEM_HOME  /Users/harakei/.rvm/gems/ruby-2.2.3@market_commons
    GEM_PATH  /Users/harakei/.rvm/gems/ruby-2.2.3@market_commons:/Users/harakei/.rvm/gems/ruby-2.2.3@global
    RVM       1.26.11 (master)
    Git       2.6.3
    rubygems-bundler (1.4.4)

Bundler settings

    build.nokogiri
      Set for the current user (/Users/harakei/.bundle/config): "--use-system-libraries"
    gem.test
      Set for the current user (/Users/harakei/.bundle/config): "rspec"
    gem.coc
      Set for the current user (/Users/harakei/.bundle/config): "0"
    gem.mit
      Set for the current user (/Users/harakei/.bundle/config): "0"
    gemfile
      Set via BUNDLE_GEMFILE: "/Volumes/storage/dev/smallpay/market_commons/Gemfile.dev"
--- TEMPLATE END ----------------------------------------------------------------

**Comment by fuzziness** [comment]
sorry, my fault. a ' instead "

**Comment by thetizzo** [comment]
Putting some more details here for any future Googlers.  For me this issue was caused by changing the double quotes to single quotes in this line from my gemspec:

```ruby
spec.files         = `git ls-files -z`.split("\x0")
```

**Comment by HimaChitalia** [comment]
@thetizzo You saved my day! Thank you :-)

**Comment by nterry** [comment]
@thetizzo My hero

**Comment by Schwad** [comment]
@thetizzo Hello from 2019 - you saved my bacon this morning, thank you so much!

**Comment by ForeverZer0** [comment]
> Putting some more details here for any future Googlers. For me this issue was caused by changing the double quotes to single quotes in this line from my gemspec:
> 
> ```ruby
> spec.files         = `git ls-files -z`.split("\x0")
> ```

One of the true heroes of the internet.

**Comment by darkodosenovic** [comment]
👍

**Comment by meowsus** [comment]
I wrote @thetizzo into my will after this one.

**Comment by Thegrtn** [comment]
![Thank You, @thetizzo ](https://media.giphy.com/media/IcGkqdUmYLFGE/giphy.gif)
**_@thetizzo_**
