### ISSUE TITLE
Errno::EACCES: Permission denied @ rb_sysopen - /opt/current/.bundle/config

### ISSUE THREAD

**Issue by ljerome** [bundler/bundler#4134]
hello 

When I run "rvm all do bundle install --without development test" in the folder of my redmine's website i got the following error message:

redmine@redmine2:/opt/current$ bundle install --without development test
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `/home/redmine/.rvm/gems/ruby-2.2.1/bin/bundle install --without development test`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what actually happened was...

Error details

    Errno::EACCES: Permission denied @ rb_sysopen - /opt/current/.bundle/config
      /home/redmine/.rvm/gems/ruby-2.2.1/gems/bundler-1.10.6/lib/bundler/settings.rb:210:in `initialize'
      /home/redmine/.rvm/gems/ruby-2.2.1/gems/bundler-1.10.6/lib/bundler/settings.rb:210:in `open'
      /home/redmine/.rvm/gems/ruby-2.2.1/gems/bundler-1.10.6/lib/bundler/settings.rb:210:in `set_key'
      /home/redmine/.rvm/gems/ruby-2.2.1/gems/bundler-1.10.6/lib/bundler/settings.rb:31:in `[]='
      /home/redmine/.rvm/gems/ruby-2.2.1/gems/bundler-1.10.6/lib/bundler/settings.rb:199:in `set_array'
      /home/redmine/.rvm/gems/ruby-2.2.1/gems/bundler-1.10.6/lib/bundler/settings.rb:117:in `without='
      /home/redmine/.rvm/gems/ruby-2.2.1/gems/bundler-1.10.6/lib/bundler/cli/install.rb:96:in `run'
      /home/redmine/.rvm/gems/ruby-2.2.1/gems/bundler-1.10.6/lib/bundler/cli.rb:162:in `install'
      /home/redmine/.rvm/gems/ruby-2.2.1/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /home/redmine/.rvm/gems/ruby-2.2.1/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /home/redmine/.rvm/gems/ruby-2.2.1/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /home/redmine/.rvm/gems/ruby-2.2.1/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /home/redmine/.rvm/gems/ruby-2.2.1/gems/bundler-1.10.6/lib/bundler/cli.rb:10:in `start'
      /home/redmine/.rvm/gems/ruby-2.2.1/gems/bundler-1.10.6/bin/bundle:20:in `block in <top (required)>'
      /home/redmine/.rvm/gems/ruby-2.2.1/gems/bundler-1.10.6/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
      /home/redmine/.rvm/gems/ruby-2.2.1/gems/bundler-1.10.6/bin/bundle:18:in `<top (required)>'
      /home/redmine/.rvm/gems/ruby-2.2.1/bin/bundle:23:in `load'
      /home/redmine/.rvm/gems/ruby-2.2.1/bin/bundle:23:in `<main>'
      /home/redmine/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
      /home/redmine/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'

Environment

    Bundler   1.10.6
    Rubygems  2.4.8
    Ruby      2.2.1p85 (2015-02-26 revision 49769) [i686-linux]
    GEM_HOME  /home/redmine/.rvm/gems/ruby-2.2.1
    GEM_PATH  /home/redmine/.rvm/gems/ruby-2.2.1:/home/redmine/.rvm/gems/ruby-2.2.1@global
    RVM       1.26.11 (latest)
    Git       2.1.4
    rubygems-bundler (1.4.4)

Bundler settings

    without
      Set for your local app (/opt/current/.bundle/config): "development:test"
      Set for the current user (/home/redmine/.bundle/config): "development:test"
--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/bundler/bundler/search?q=Permission+denied+%40+rb_sysopen+-+%2Fopt%2Fcurrent%2F.bundle%2Fconfig&type=Issues

If there aren't any reports for this error yet, please create copy and paste the report template above into a new issue. Don't forget to anonymize any private data! The new issue form is located at:
https://github.com/bundler/bundler/issues/new

Please can someone help me solved this issue?

**Comment by segiddins** [comment]
This has a better error message in 1.11. You'll need to grant access to that directory.
