### ISSUE TITLE
bundler adds the Gem bindir to PATH even if it is configured to generate its own

### ISSUE THREAD

**Issue by doudou** [bundler/bundler#4137]
I have a bundler environment set up, with bundler generating binstubs in a path of my choosing. However, bundler exec adds the Gem bindir ($HOME/.gems/ruby/VERSION/bin) to PATH instead of this binstub path.

**Comment by indirect** [comment]
that is correct. the binstubs only exists to run those commands, so there is no reason to use them with bundle exec.

**Comment by doudou** [comment]
The script I run under `bundler exec` (in this case, a Rake task) itself starts a subcommand. This subcommand ends up being run outside the bundle context, which is definitely not what I would expect.

In principle, this should work fine since the stub requires the gem, which itself is set properly. However, the gem ended up being generated with a different ruby minor version than the one running rake, and the script is therefore executed under that minor version instead of the one from the bundler context.

What would be the downside of exposing bundler's binstubs within the bundler context ? Doesn't that ensure some form of consistency ?

**Comment by indirect** [comment]
Unfortunately, Bundler cannot distinguish between your case (wanting the same Ruby despite a gem binstubs that says otherwise) and the opposite case (someone who actually wants to run a command under a different Ruby). As a result, Bundler can only honor the PATH during subcommands.

**Comment by doudou** [comment]
Mmmm ... I'm not sure I understand. While running "under bundler" (e.g. `bundler exec rake`), isn't it the expectation that the environment would be "the bundler environment" (that is to say, do whatever the bundler binstubs tell you to do) ?

**Comment by indirect** [comment]
If you're shelling out, you could be intending anything at all. For example, Homebrew runs under the system Ruby, and shelling out to run a brew command from your bundle exec rake should not preserve which ruby is being used.

**Comment by doudou** [comment]
Understood ... thanks !
