### ISSUE TITLE
bundler adds the bindir to PATH even if it is already included in PATH

### ISSUE THREAD

**Issue by doudou** [bundler/bundler#4138]
I use bundler as part of a bigger system, where PATH might include the path to bin directories
from Ruby packages that are not managed by bundler.

As part of the environment setup, bundler *prepends* the Gem bindir to PATH, which breaks the
setup for any bin script that is defined by a Gem *and* by one of the packages (under bundler,
the Gem will win).

The bug IMO is that I am careful to add bundler's bin path to PATH "at the right place". It would
be nice if bundler could honor that setup and not add its own path mandatorily,

**Comment by segiddins** [comment]
You should be using `Bundler.with_original_env` if you want access to your original environment variables
