### ISSUE TITLE
ambiguous error message when refs are missing from a git dependency

### ISSUE THREAD

**Issue by doy** [bundler/bundler#4140]
This is related to, but not quite the same as, #3897.

When you run `bundle install` in a project that has a dependency on a git ref, and that ref no longer exists, you get an error message like
```
Git error: command `git reset --hard 0d4f9b7dcc50fe5235abd5035a49c7075ae514d6` in directory /home/doy/tmp/bundler-test/vendor/bundle/ruby/2.1.0/bundler/gems/bundler-test-0d4f9b7dcc50 has
failed.
If this error persists you could try removing the cache directory '/home/doy/tmp/bundler-test/vendor/bundle/ruby/2.1.0/cache/bundler/git/bundler-test-a59c53842b1d2c30f68c5498ce0cca55e39b6e20'
```

This is pretty unhelpful, since removing the cache directory isn't actually going to fix anything in this case. A much more helpful response here would be for bundler to automatically remove the cache directory and try again, and if it fails the second time, give an error message indicating that the remote ref actually doesn't exist.

**Comment by segiddins** [comment]
What version of bundler are you running? I think we might have improved this in the 1.11 beta. If not, a pull request doing so would be much appreciated :)

**Comment by doy** [comment]
This was on 1.10.6 - I'll give it a try, thanks!
