### ISSUE TITLE
standalone binstubs sometimes have an incorrect load path.

### ISSUE THREAD

**Issue by glennpratt** [bundler/bundler#4144]
I have a somewhat complicated build process that uses `--standalone` and `--binstubs`.

This build process works fine on my machine, but occasionally others get broken builds (using the same version of ruby and bundler).

Trying to use a binstub, we get:

```
$ binstubs/pumactl
/usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- bundler/setup (LoadError)
from /usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
from /opt/acquia/cloud-database-api/binstubs/pumactl:11:in `<main>'
```

Looking in the particular binstub, `binstubs/pumactl`:

```ruby
#!/usr/bin/env ruby
#
# This file was generated by Bundler.
#
# The application 'pumactl' is installed as part of a gem, and
# this file is here to facilitate running it.
#

$:.unshift File.expand_path '../../vendor/bundle/ruby/2.2.0/gems/json-1.8.3/ext/json/ext/parser/vendor/bundle', __FILE__

require 'bundler/setup'
load File.expand_path '../../vendor/bundle/ruby/2.2.0/gems/puma-2.15.3/bin/pumactl', __FILE__
```

Here's a reproduction script:

https://gist.github.com/glennpratt/b039e4558875a3608419

Note, this issues appears to only happen when --jobs > 2.

**Comment by TimMoore** [comment]
@glennpratt is this still an issue for you? If so, please add all of the information requested at https://github.com/bundler/bundler/blob/master/ISSUES.md#reporting-unresolved-problems

**Comment by glennpratt** [comment]
@TimMoore yes it is. I'll add more information and open a PR of a fix that appears to work for me.

**Comment by glennpratt** [comment]
@TimMoore I added a reproduction script and a pull request (#4264).
