### ISSUE TITLE
Exclamation marks (!) in Gemfile.lock causing error

### ISSUE THREAD

**Issue by user453584** [bundler/bundler#4146]
Just updated to version v1.11.0, and immediately my dependencies in `Gemfile.lock` all had exclamations marks added to the end, causing the following error on the production server:

> You are trying to install in deployment mode after changing your Gemfile. Run `bundle install` elsewhere and add the updated Gemfile.lock to version control.

What changed in this latest version that would cause this issue?

**Comment by segiddins** [comment]
What is the output of `bundle env`?

**Comment by agis-** [comment]
Closing this due to lack of feedback. Feel free to share more info and we'll happily reopen.
