### ISSUE TITLE
Problem with bundler on ruby 2.2.3

### ISSUE THREAD

**Issue by AlexCppns** [bundler/bundler#4159]
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

    project-dir $ bundle

- What did you expect to happen?

  I expected Bundler to... bundle the application

- What happened instead?

  Instead, what actually happened was... see below

Error details

    RuntimeError: LazySpecification has not been materialized yet (calling :required_ruby_version [])
      /var/lib/gems/2.2.0/gems/bundler-1.11.0/lib/bundler/lazy_specification.rb:75:in `method_missing'
      /var/lib/gems/2.2.0/gems/bundler-1.11.0/lib/bundler/resolver.rb:132:in `for?'
      /var/lib/gems/2.2.0/gems/bundler-1.11.0/lib/bundler/resolver.rb:275:in `block in search_for'
      /var/lib/gems/2.2.0/gems/bundler-1.11.0/lib/bundler/resolver.rb:275:in `select'
      /var/lib/gems/2.2.0/gems/bundler-1.11.0/lib/bundler/resolver.rb:275:in `search_for'
      /var/lib/gems/2.2.0/gems/bundler-1.11.0/lib/bundler/resolver.rb:332:in `block in verify_gemfile_dependencies_are_found!'
      /var/lib/gems/2.2.0/gems/bundler-1.11.0/lib/bundler/resolver.rb:330:in `each'
      /var/lib/gems/2.2.0/gems/bundler-1.11.0/lib/bundler/resolver.rb:330:in `verify_gemfile_dependencies_are_found!'
      /var/lib/gems/2.2.0/gems/bundler-1.11.0/lib/bundler/resolver.rb:199:in `start'
      /var/lib/gems/2.2.0/gems/bundler-1.11.0/lib/bundler/resolver.rb:183:in `resolve'
      /var/lib/gems/2.2.0/gems/bundler-1.11.0/lib/bundler/definition.rb:198:in `resolve'
      /var/lib/gems/2.2.0/gems/bundler-1.11.0/lib/bundler/definition.rb:163:in `missing_specs'
      /var/lib/gems/2.2.0/gems/bundler-1.11.0/lib/bundler/installer.rb:187:in `block in resolve_if_need'
      /var/lib/gems/2.2.0/gems/bundler-1.11.0/lib/bundler/ui/shell.rb:80:in `silence'
      /var/lib/gems/2.2.0/gems/bundler-1.11.0/lib/bundler/installer.rb:184:in `resolve_if_need'
      /var/lib/gems/2.2.0/gems/bundler-1.11.0/lib/bundler/installer.rb:69:in `run'
      /var/lib/gems/2.2.0/gems/bundler-1.11.0/lib/bundler/installer.rb:21:in `install'
      /var/lib/gems/2.2.0/gems/bundler-1.11.0/lib/bundler/cli/install.rb:105:in `run'
      /var/lib/gems/2.2.0/gems/bundler-1.11.0/lib/bundler/cli.rb:172:in `install'
      /var/lib/gems/2.2.0/gems/bundler-1.11.0/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /var/lib/gems/2.2.0/gems/bundler-1.11.0/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /var/lib/gems/2.2.0/gems/bundler-1.11.0/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /var/lib/gems/2.2.0/gems/bundler-1.11.0/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /var/lib/gems/2.2.0/gems/bundler-1.11.0/lib/bundler/cli.rb:10:in `start'
      /var/lib/gems/2.2.0/gems/bundler-1.11.0/exe/bundle:19:in `block in <top (required)>'
      /var/lib/gems/2.2.0/gems/bundler-1.11.0/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
      /var/lib/gems/2.2.0/gems/bundler-1.11.0/exe/bundle:17:in `<top (required)>'
      /usr/local/bin/bundle:23:in `load'
      /usr/local/bin/bundle:23:in `<main>'

Environment

    Bundler   1.11.0
    Rubygems  2.4.5.1
    Ruby      2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux-gnu]
    GEM_HOME  /var/lib/gems/2.2.0
    GEM_PATH  /var/lib/gems/2.2.0:/home/alex/.gem/ruby/2.2.0:/usr/share/rubygems-integration/2.2.0:/usr/share/rubygems-integration/all
    Git       2.6.4
--- TEMPLATE END ----------------------------------------------------------------

Update - it's a problem with the following gem: `https://github.com/twitterdev/twitter-ruby-ads-sdk`, I am looking into it.

Update - installing bundler 1.10.0 fixed the problem.

**Comment by markiz** [comment]
Same thing happens on me while trying to install a local gem via path: source. I've also noticed that removing "ruby 2.2.1" line from Gemfile helped.

**Comment by el3ctro-** [comment]
Installing Bundler 1.11.0 gives me the error:
/Users/el3ctro/.rvm/gems/ruby-2.2.1@myapp/gems/bundler-1.11.0/lib/bundler/lazy_specification.rb:75:in `method_missing': LazySpecification has not been materialized yet (calling :required_ruby_version []) (RuntimeError)

**Comment by davesag** [comment]
This just started to happen to me this morning. `ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin14]`

**Comment by mattolson** [comment]
:+1: Happening to me too all of the sudden

**Comment by taggaddaaaa** [comment]
i removed "ruby 2.2.1" from gemfile and IT WORKED thank you so much markiz!! Was stuck since 2 hours!

**Comment by grosser** [comment]
fixed in 1.11.2

**Comment by segiddins** [comment]
@AlexCppns can you verify that 1.11.2 fixes things for you? Thanks!
