### ISSUE TITLE
Bundler ignores local gem, even though declared in config

### ISSUE THREAD

**Issue by paddor** [bundler/bundler#4162]
I'm working on a ruby gem which depends on another gem that I develop simultaneously on my machine. So I used `bundle config --local local.czmq-ffi-gen $HOME/src/ruby/czmq-ffi-gen` a few days ago and it worked perfectly.

Unfortunately, it stopped working and I can't figure out why. No matter what I do, whether I set the config locally (in the depending git repository) or user-wide in ~/.bundle/config, it won't use the gem from sources anymore. It keeps using the one installed.

`czmq-ffi-gen` is the gem which I'd like to use by source. It's loaded from the wrong place:
```
➜  cztop git:(master) ✗ bundle show czmq-ffi-gen
/Users/paddor/.gem/ruby/2.2.3/gems/czmq-ffi-gen-0.2.1
```

Even though config is set:
```
➜  cztop git:(master) ✗ cat .bundle/config
---
BUNDLE_LOCAL__CZMQ-FFI-GEN: "/Users/paddor/src/ruby/czmq-ffi-gen"
```

And is correct:
```
➜  cztop git:(master) ✗ la /Users/paddor/src/ruby/czmq-ffi-gen
total 96
drwxr-xr-x+ 16 paddor  staff   544B Dec 15 01:43 .git/
-rw-r--r--+  1 paddor  staff   101B Dec  8 00:37 .gitignore
-rw-r--r--+  1 paddor  staff    88B Dec  7 04:46 .gitmodules
-rw-r--r--+  1 paddor  staff    31B Dec  7 04:54 .rspec
-rw-r--r--+  1 paddor  staff   229B Dec  9 04:41 .travis.yml
-rw-r--r--+  1 paddor  staff    33B Dec  9 05:12 AUTHORS
-rw-r--r--+  1 paddor  staff   433B Dec 12 16:48 CHANGES.md
-rw-r--r--+  1 paddor  staff    38B Dec  7 03:19 Gemfile
-rw-r--r--+  1 paddor  staff   705B Dec 12 22:45 Gemfile.lock
-rw-r--r--+  1 paddor  staff   733B Dec  7 03:17 LICENSE
-rw-r--r--+  1 paddor  staff   3.2K Dec  9 05:01 README.md
-rw-r--r--+  1 paddor  staff   117B Dec  7 03:18 Rakefile
drwxr-xr-x+  4 paddor  staff   136B Dec  7 18:52 bin/
drwxr-xr-x+  4 paddor  staff   136B Dec  9 06:16 ci-scripts/
-rw-r--r--+  1 paddor  staff   1.4K Dec  9 05:12 czmq-ffi-gen.gemspec
drwxr-xr-x+  4 paddor  staff   136B Dec 15 01:20 lib/
drwxr-xr-x+  6 paddor  staff   204B Dec 12 16:49 pkg/
drwxr-xr-x+  4 paddor  staff   136B Dec 10 01:35 spec/
drwxr-xr-x+  3 paddor  staff   102B Dec  7 04:46 vendor/
drwxr-xr-x+  3 paddor  staff   102B Dec 15 01:09 zdir-test-dir/
➜  cztop git:(master) ✗
```

Any ideas? Thanks.

**Comment by paddor** [comment]
Hey @indirect, nice talk at RubyConf this year. I watched the video. :-)

Any ideas about my issue? It happens with other (non-mine) gems too. Thanks for the help.

**Comment by paddor** [comment]
It works now. I had to move the requirement from the Gemspec into Gemfile and also specify the `git:` option. Now it's completely rendudant.

What's the point of this override feature, if it won't override a setting, unless the setting itself basically says what the override says?

It'd be really nice if it'd work as expected, meaning: Just use the local gem from the override path if the override says so. Or at least warn why the override isn't used.

**Comment by segiddins** [comment]
The got override only works when the gem is already being included via a git source in the Gemfile.

**Comment by paddor** [comment]
May I ask why? That condition makes this feature essentially useless.

My usecase is this: Let's say gem A depends on gem B. The Gemfile of A says `gemspec`, and `A.gemspec` says `gem.add_runtime_dependency("B")`. When I'm working on gem A, I sometimes also work on gem B. I expect this feature to assist me in this case, so I can make gem A use the local gem B, **without** changing the Gemfile (because the Gemfile is check into version control, and other developers might not want to use it off a Git repository or have their local Git repository at another location).

Also, as recommended [here](http://yehudakatz.com/2010/12/16/clarifying-the-roles-of-the-gemspec-and-gemfile/), I do not want to specify my gem's runtime dependencies in the Gemfile at all.

Can bundler not assist with this usecase?

**Comment by segiddins** [comment]
It has to work that way because otherwise there's no way for bundler to record the commit sha you're using in the lockfile.

**Comment by paddor** [comment]
Why not? It can take the current commit SHA from the Git repository located at the path set by `bundler config local.B /path/to/repo`.

**Comment by segiddins** [comment]
But it can only do that if the gem is already declared to come from a git source.

**Comment by paddor** [comment]
Why? Sorry, but that's not a real reason. It knows the gem B is needed by gem A, because A.gemspec says so. No matter if it's declared to come from a git source. The name of B counts. After all, one specifies B's name is the key in `bundle config local.B /path/to/repo`, and not that it's declared to come from a git source or it's original git source.

**Comment by paddor** [comment]
Asked differently, what am I supposed to do? Is there maybe a more elegant way for my usecase?

Merry Christmas. :-)

**Comment by indirect** [comment]
@paddor saying "that's not a real reason" to someone who just went out of their way to help you for free is not cool. That kind of treatment more or less completely removes any motivation to help you. If you have questions, don't understand, or something seems wrong to you, say "I have a question" or "I don't understand" or "that's weird, you said X but I am observing Y when I do Z".

To answer your question as specifically as possible: the entire point of the git locals feature is to ease local development while preserving Bundler's fundamental guarantee: you will get the same code in production that you got in development. The only way to do this is to use git gems and save the commit sha in the lockfile.

If you want to simply work with a local copy of a gem, edit your Gemfile to change the line `gem "foo"` to `gem "foo", path: "/path/to/checkout/of/foo". This removes all the guarantees that Bundler provides, and so we do not recommend it.

**Comment by paddor** [comment]
@indirect Sorry if that seemed harsh. "I still do not understand" is what I actually meant.

Thanks for the explanation. It would all make sense if I was developing an application. But as far as I know, there's no need to make that fundamental guarantee when you're developing a gem. For the same reason it's also not recommended to include a gem's Gemfile.lock into version control, right? (as advised [here](http://yehudakatz.com/2010/12/16/clarifying-the-roles-of-the-gemspec-and-gemfile/))

Sorry for dragging this out, but I really hoped there was a nicer solution than changing my Gemfile and keeping it "dirty" (and never accidentally commit it along with other changes).
