### ISSUE TITLE
Errno::EPROTO: Protocol error @ dir_s_mkdir

### ISSUE THREAD

**Issue by andresabraz** [bundler/bundler#4163]
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `/home/vagrant/.rbenv/versions/2.2.3/bin/bundle install --path`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what actually happened was...

Error details

    Errno::EPROTO: Protocol error @ dir_s_mkdir - /vagrant/projects/.bundle
      /home/vagrant/.rbenv/versions/2.2.3/lib/ruby/2.2.0/fileutils.rb:252:in `mkdir'
      /home/vagrant/.rbenv/versions/2.2.3/lib/ruby/2.2.0/fileutils.rb:252:in `fu_mkdir'
      /home/vagrant/.rbenv/versions/2.2.3/lib/ruby/2.2.0/fileutils.rb:226:in `block (2 levels) in mkdir_p'
      /home/vagrant/.rbenv/versions/2.2.3/lib/ruby/2.2.0/fileutils.rb:224:in `reverse_each'
      /home/vagrant/.rbenv/versions/2.2.3/lib/ruby/2.2.0/fileutils.rb:224:in `block in mkdir_p'
      /home/vagrant/.rbenv/versions/2.2.3/lib/ruby/2.2.0/fileutils.rb:210:in `each'
      /home/vagrant/.rbenv/versions/2.2.3/lib/ruby/2.2.0/fileutils.rb:210:in `mkdir_p'
      /home/vagrant/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.11.0/lib/bundler/settings.rb:208:in `block in set_key'
      /home/vagrant/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.11.0/lib/bundler/shared_helpers.rb:114:in `filesystem_access'
      /home/vagrant/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.11.0/lib/bundler/settings.rb:207:in `set_key'
      /home/vagrant/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.11.0/lib/bundler/settings.rb:33:in `[]='
      /home/vagrant/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.11.0/lib/bundler/cli/install.rb:85:in `run'
      /home/vagrant/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.11.0/lib/bundler/cli.rb:172:in `install'
      /home/vagrant/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.11.0/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /home/vagrant/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.11.0/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /home/vagrant/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.11.0/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /home/vagrant/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.11.0/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /home/vagrant/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.11.0/lib/bundler/cli.rb:10:in `start'
      /home/vagrant/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.11.0/exe/bundle:19:in `block in <top (required)>'
      /home/vagrant/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.11.0/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
      /home/vagrant/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.11.0/exe/bundle:17:in `<top (required)>'
      /home/vagrant/.rbenv/versions/2.2.3/bin/bundle:23:in `load'
      /home/vagrant/.rbenv/versions/2.2.3/bin/bundle:23:in `<main>'

Environment

    Bundler   1.11.0
    Rubygems  2.4.5.1
    Ruby      2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux]
    Git       2.6.4

Bundler settings

    path
      Set for your local app (/vagrant/projects/.bundle/config): "path"
      Set for the current user (/home/vagrant/.bundle/config): "path"
    disable_shared_gems
      Set for the current user (/home/vagrant/.bundle/config): "1"
--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/bundler/bundler/search?q=Protocol+error+%40+dir_s_mkdir+-+%2Fvagrant%2Fprojects%2F.bundle&type=Issues

If there aren't any reports for this error yet, please create copy and paste the report template above into a new issue. Don't forget to anonymize any private data! The new issue form is located at:
https://github.com/bundler/bundler/issues/new

**Comment by rgb-one** [comment]
The directory you ran bundler in, did you clone it from the guest (vagrant VM) or the host system? If it was cloned from the host then that may be the problem. Clone the directory in the vagrant VM and run `bundle install --path` again from the vagrant VM. The idea is to give the vagrant VM full access to the directory so.

**Comment by RochesterinNYC** [comment]
Should there be a custom error and/or error message returned for these rather than just error out because of the uncaught `Errno::EPROTO`?

I guess the issue is that it seems that a wide range of errors (possibly any error?) that occur in the presence of virtualization will raise this error.
