### ISSUE TITLE
Permission denied @ unlink_internal

### ISSUE THREAD

**Issue by oka-haist** [bundler/bundler#4170]
- What did you do?

  I ran the command `/usr/local/bin/bundle clean --force`

- What did you expect to happen?

  I expected Bundler to remove all the gems from my system

- What happened instead?

  Instead, it removed a few and stopped. Can't go on with bundle clean

Error details

    Errno::EACCES: Permission denied @ unlink_internal - /usr/local/lib/ruby/gems/2.2.0/cache/sdoc-0.4.1.gem
      /usr/local/lib/ruby/2.2.0/fileutils.rb:1450:in `unlink'
      /usr/local/lib/ruby/2.2.0/fileutils.rb:1450:in `block in remove_file'
      /usr/local/lib/ruby/2.2.0/fileutils.rb:1455:in `platform_support'
      /usr/local/lib/ruby/2.2.0/fileutils.rb:1449:in `remove_file'
      /usr/local/lib/ruby/2.2.0/fileutils.rb:793:in `remove_file'
      /usr/local/lib/ruby/2.2.0/fileutils.rb:571:in `block in rm'
      /usr/local/lib/ruby/2.2.0/fileutils.rb:570:in `each'
      /usr/local/lib/ruby/2.2.0/fileutils.rb:570:in `rm'
      /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:204:in `block in clean'
      /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:204:in `each'
      /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:204:in `clean'
      /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/cli/clean.rb:11:in `run'
      /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/cli.rb:373:in `clean'
      /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/cli.rb:10:in `start'
      /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/bin/bundle:20:in `block in <top (required)>'
      /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
      /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/bin/bundle:18:in `<top (required)>'
      /usr/local/bin/bundle:23:in `load'
      /usr/local/bin/bundle:23:in `<main>'

Environment

    Bundler   1.10.6
    Rubygems  2.4.5.1
    Ruby      2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux]
    GEM_HOME  /usr/local/lib/ruby/gems/2.2.0
    GEM_PATH  /usr/local/lib/ruby/gems/2.2.0:/home/user/.gem/ruby/2.2.0
    Git       1.9.1

**Comment by segiddins** [comment]
Thanks for the error report! At the very least, this should fail with a friendly error.

**Comment by RochesterinNYC** [comment]
@segiddins What is the desired end behavior regarding this? 

Would the command stop and fail on trying to remove a file/directory you don't have permission for and output a more helpful error message? 

vs.

Would the command print a helpful error message for that instance of deletion, and then keep going and attempting to delete the other files/directories it's supposed to delete?

**Comment by segiddins** [comment]
@RochesterinNYC just using `SharedHelpers.filesystem_access` in `clean` for now should suffice

**Comment by RochesterinNYC** [comment]
Gotcha, thanks for the point in the right direction.

**Comment by RochesterinNYC** [comment]
Think this can be closed now. 

@oka-haist, your original error was probably caused by a lack of bundler system access to a directory that contained a gem that was being removed. Now, the same error should have an error message stating this lack of permissions/access.

**Comment by oka-haist** [comment]
Ok, thank you.
