### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by jekaterina1** [bundler/bundler#4174]
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `C:/Ruby/bin/bundle install`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what actually happened was...

Error details

    Errno::ENOENT: No such file or directory - git clone "git://github.com/gregbell/active_admin.git" "C:/Ruby/lib/ruby/gems/2.1.0/cache/bundler/git/active_admin-d67faab65e9b74efbc8efb4a777a851e9f78b2ca" --bare --no-hardlinks --quiet
      C:/Ruby/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/source/git/git_proxy.rb:133:in ``'
      C:/Ruby/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/source/git/git_proxy.rb:133:in `block in git'
      C:/Ruby/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/shared_helpers.rb:71:in `call'
      C:/Ruby/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/shared_helpers.rb:71:in `with_clean_git_env'
      C:/Ruby/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/source/git/git_proxy.rb:133:in `git'
      C:/Ruby/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/source/git/git_proxy.rb:127:in `block in git_retry'
      C:/Ruby/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/retry.rb:38:in `call'
      C:/Ruby/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/retry.rb:38:in `run'
      C:/Ruby/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/retry.rb:28:in `attempt'
      C:/Ruby/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/source/git/git_proxy.rb:126:in `git_retry'
      C:/Ruby/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/source/git/git_proxy.rb:82:in `checkout'
      C:/Ruby/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/source/git.rb:153:in `specs'
      C:/Ruby/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/definition.rb:541:in `block in converge_locked_specs'
      C:/Ruby/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/definition.rb:530:in `each'
      C:/Ruby/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/definition.rb:530:in `converge_locked_specs'
      C:/Ruby/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/definition.rb:192:in `resolve'
      C:/Ruby/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/definition.rb:137:in `specs'
      C:/Ruby/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/definition.rb:126:in `resolve_remotely!'
      C:/Ruby/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/installer.rb:194:in `resolve_if_need'
      C:/Ruby/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/installer.rb:69:in `run'
      C:/Ruby/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/installer.rb:21:in `install'
      C:/Ruby/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/cli/install.rb:105:in `run'
      C:/Ruby/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/cli.rb:172:in `install'
      C:/Ruby/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      C:/Ruby/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      C:/Ruby/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      C:/Ruby/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      C:/Ruby/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/cli.rb:10:in `start'
      C:/Ruby/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/exe/bundle:19:in `block in <top (required)>'
      C:/Ruby/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
      C:/Ruby/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/exe/bundle:17:in `<top (required)>'
      C:/Ruby/bin/bundle:23:in `load'
      C:/Ruby/bin/bundle:23:in `<main>'

Environment

    Bundler   1.11.2
    Rubygems  2.2.5
    Ruby      2.1.7p400 (2015-08-18 revision 51632) [x64-mingw32]
    GEM_HOME  C:/Ruby/lib/ruby/gems/2.1.0
    GEM_PATH  C:/Ruby/lib/ruby/gems/2.1.0;C:/Users/Joluś/.gem/ruby/2.1.0
    Git       not installed
--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/bundler/bundler/search?q=No+such+file+or+directory+-+git+clone+%22git%3A%2F%2Fgithub.com%2Fgregbell%2Factive_admin.git%22+%22C%3A%2FRuby%2Flib%2Fruby%2Fgems%2F2.1.0%2Fcache%2Fbundler%2Fgit%2Factive_admin-d67faab65e9b74efbc8efb4a777a851e9f78b2ca%22+--bare+--no-hardlinks+--quiet&type=Issues

If there aren't any reports for this error yet, please create copy and paste the report template above into a new issue. Don't forget to anonymize any private data! The new issue form is located at:
https://github.com/bundler/bundler/issues/new

**Comment by rgb-one** [comment]
The problem is you don't have `git` installed. It can be installed from here: http://git-scm.com/download/

**Comment by jekaterina1** [comment]
Problem solved, thanks!

**Comment by rgb-one** [comment]
:)
