### ISSUE TITLE
gemspec contains a -z arg for find which breaks builds on linux

### ISSUE THREAD

**Issue by joequant** [bundler/bundler#4175]
The gemspec for bundler contains a find command with a -z argument which causes the rebuild of the gem to break on linux.

**Comment by segiddins** [comment]
What version of git are you running?

**Comment by joequant** [comment]
2.6.4 but the problem seems to be in the ruby.gemspec

**Comment by segiddins** [comment]
What ruby.gemspec? There is only bundler.gemspec...

**Comment by RochesterinNYC** [comment]
@joequant I assume you meant `bundler.gemspec` instead of `ruby.gemspec`?

Can we see the error and/or stack trace you're getting? Along with some system info via `bundle env`?
