### ISSUE TITLE
NoMethodError: undefined method `<' for nil:NilClass

### ISSUE THREAD

**Issue by jschwendt** [bundler/bundler#4177]
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `/Users/joeschwendt/.rvm/gems/ruby-2.2.0/bin/bundle install`

- What did you expect to happen?

  I expected Bundler to install all of my rails gems.

- What happened instead?

  Instead, what actually happened was it installed what appears to be most of my gems but then dies with the following error.

Error details

    NoMethodError: undefined method `<' for nil:NilClass
      /Users/joeschwendt/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.11.2/lib/bundler/definition.rb:253:in `lock'
      /Users/joeschwendt/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.11.2/lib/bundler/environment.rb:34:in `lock'
      /Users/joeschwendt/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.11.2/lib/bundler/installer.rb:72:in `run'
      /Users/joeschwendt/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.11.2/lib/bundler/installer.rb:21:in `install'
      /Users/joeschwendt/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.11.2/lib/bundler/cli/install.rb:105:in `run'
      /Users/joeschwendt/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.11.2/lib/bundler/cli.rb:172:in `install'
      /Users/joeschwendt/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.11.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /Users/joeschwendt/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.11.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /Users/joeschwendt/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.11.2/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /Users/joeschwendt/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.11.2/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /Users/joeschwendt/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.11.2/lib/bundler/cli.rb:10:in `start'
      /Users/joeschwendt/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.11.2/exe/bundle:19:in `block in <top (required)>'
      /Users/joeschwendt/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.11.2/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
      /Users/joeschwendt/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.11.2/exe/bundle:17:in `<top (required)>'
      /Users/joeschwendt/.rvm/gems/ruby-2.2.0/bin/bundle:23:in `load'
      /Users/joeschwendt/.rvm/gems/ruby-2.2.0/bin/bundle:23:in `<main>'
      /Users/joeschwendt/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
      /Users/joeschwendt/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'

Environment

    Bundler   1.11.2
    Rubygems  2.4.5
    Ruby      2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin14]
    GEM_HOME  /Users/joeschwendt/.rvm/gems/ruby-2.2.0@global
    RVM       1.26.10 (latest)
    Git       2.2.1
    rubygems-bundler (1.4.4)
--- TEMPLATE END ----------------------------------------------------------------

**Comment by RochesterinNYC** [comment]
Would you mind copying and pasting your `Gemfile` and `Gemfile.lock`?

**Comment by jschwendt** [comment]
Note, this works fine when I remove the Gemfile.lock, but I lose all of my versioning.

Gemfile
----------------------
source 'https://rubygems.org'

ruby '2.2.0'

gem 'active_model_serializers'
gem 'acts-as-taggable-on'
gem 'airbrake'
gem 'analytical'
gem 'aws-sdk'
gem 'bitters', require: false
gem 'bourbon', '~> 3.2.1'
gem 'ckeditor'
gem 'coffee-rails'
gem 'color_difference'
gem 'daemons'
gem 'detect_timezone_rails'
gem 'draper'
gem 'email_validator'
gem 'flamegraph'
gem 'flutie'
gem 'geocoder'
gem 'hashids'
gem 'health_check'
gem 'high_voltage'
gem 'hirefire-resource'
gem 'httparty'
gem 'http'
gem 'diffy'
gem 'i18n-tasks'
gem 'interactor-rails'
gem 'jbuilder'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'linkedin-oauth2', git: 'https://github.com/emorikawa/linkedin-oauth2.git'
gem 'linkedin-scraper'
gem 'mandrill-api', require: 'mandrill'
gem 'miro'
gem 'mixpanel-ruby'
gem 'monban'
gem 'monban-generators'
gem 'money-rails'
gem "mongoid", "~> 4.0.0"
gem 'neat', '~> 1.5.1'
gem 'nested_form'
gem 'nokogiri'
gem 'nondestructive_migrations'
gem 'normalize-rails', '~> 3.0.0'
gem 'paperclip', :git=> 'https://github.com/thoughtbot/paperclip', :ref => '523bd46c768226893f23889079a7aa9c73b57d68'
gem 'pg'
gem 'phony_rails'
gem 'pundit'
gem 'rack-attack'
gem 'rack-timeout'
gem 'rails', '4.2'
gem 'recipient_interceptor'
gem 'responders', '~> 2.0'
gem 'resque-cleaner'
gem 'resque_mailer'
gem 'resque-pool'
gem 'resque-queue-priority'
gem 'resque-retry'
gem 'resque-rollbar'
gem 'resque-serializable', :git => 'https://github.com/jschwendt/resque-serializable.git'
gem 'resque-timeout'
gem 'rmagick'
gem 'rollbar', '~> 2.5.2'
gem 'sass-rails', '~> 4.0.3'
gem 'simple_form'
gem 'slack-notifier'
gem 'skylight'
gem 'stackprof'
gem 'StreetAddress'
gem 'time_for_a_boolean'
gem 'title'
gem 'uglifier'
gem 'puma'
gem 'useragent'
gem 'versionist'
gem 'yajl-ruby', require: 'yajl'
gem 'zero_push'

group :development do
  gem 'bullet'
  gem 'spring'
  gem 'spring-commands-rspec'
  gem 'web-console', '~> 2.0'
end

group :development, :test, :staging do
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'prawn'
end

group :development, :test do
  gem 'awesome_print'
  gem 'byebug'
  gem 'dotenv-rails'
  gem 'guard-rspec', require: false
  gem 'pry-byebug'
  gem 'pry-rails'
  gem 'railroady'
  gem 'rspec-rails', '~> 3.0.0'
end

group :test do
  gem 'capybara-webkit', '>= 1.2.0'
  gem 'database_cleaner'
  gem 'email_spec'
  gem 'formulaic'
  gem 'json-schema'
  gem 'json_spec'
  gem 'launchy'
  gem 'shoulda-matchers', require: false
  gem 'simplecov', require: false
  gem 'timecop'
  gem 'webmock'
end

group :staging, :production do
  gem 'dalli'
  gem 'kgio'
  gem 'opbeat'
  gem 'newrelic_rpm'
  gem 'rack-cache'
  gem 'rails_12factor'
end

Gemfile.lock
----------------------------
GIT
  remote: https://github.com/emorikawa/linkedin-oauth2.git
  revision: ceb63460b8b45b7e00766ae3a4c3e361d76c6ffc
  specs:
    linkedin-oauth2 (1.0.0)
      faraday (~> 0.9)
      hashie (~> 3.2)
      oauth2 (~> 1.0)

GIT
  remote: https://github.com/jschwendt/resque-serializable.git
  revision: 92f7d3ee7adda43e7f0dda4f4757cb5ec3ddea96
  specs:
    resque-serializable (0.0.3)
      resque (>= 1.19.0)

GIT
  remote: https://github.com/thoughtbot/paperclip
  revision: 523bd46c768226893f23889079a7aa9c73b57d68
  ref: 523bd46c768226893f23889079a7aa9c73b57d68
  specs:
    paperclip (4.3.1)
      activemodel (>= 3.2.0)
      activesupport (>= 3.2.0)
      cocaine (~> 0.5.5)
      mime-types
      mimemagic (= 0.3.0)

GEM
  remote: https://rubygems.org/
  specs:
    StreetAddress (1.0.6)
    actionmailer (4.2.0)
      actionpack (= 4.2.0)
      actionview (= 4.2.0)
      activejob (= 4.2.0)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 1.0, >= 1.0.5)
    actionpack (4.2.0)
      actionview (= 4.2.0)
      activesupport (= 4.2.0)
      rack (~> 1.6.0)
      rack-test (~> 0.6.2)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.1)
    actionview (4.2.0)
      activesupport (= 4.2.0)
      builder (~> 3.1)
      erubis (~> 2.7.0)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.1)
    active_model_serializers (0.9.3)
      activemodel (>= 3.2)
    activejob (4.2.0)
      activesupport (= 4.2.0)
      globalid (>= 0.3.0)
    activemodel (4.2.0)
      activesupport (= 4.2.0)
      builder (~> 3.1)
    activerecord (4.2.0)
      activemodel (= 4.2.0)
      activesupport (= 4.2.0)
      arel (~> 6.0)
    activesupport (4.2.0)
      i18n (~> 0.7)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.3, >= 0.3.4)
      tzinfo (~> 1.1)
    acts-as-taggable-on (3.5.0)
      activerecord (>= 3.2, < 5)
    addressable (2.3.8)
    airbrake (4.3.3)
      builder
      multi_json
    analytical (3.0.12)
    arel (6.0.3)
    ast (2.1.0)
    awesome_print (1.6.1)
    aws-sdk (2.1.35)
      aws-sdk-resources (= 2.1.35)
    aws-sdk-core (2.1.35)
      jmespath (~> 1.0)
    aws-sdk-resources (2.1.35)
      aws-sdk-core (= 2.1.35)
    bcrypt (3.1.10)
    binding_of_caller (0.7.2)
      debug_inspector (>= 0.0.1)
    bitters (1.0.0)
      bourbon (>= 3.2)
      sass (>= 3.2)
      thor
    bourbon (3.2.4)
      sass (~> 3.2)
      thor
    bson (3.2.6)
    builder (3.2.2)
    bullet (4.14.10)
      activesupport (>= 3.0.0)
      uniform_notifier (~> 1.9.0)
    byebug (5.0.0)
      columnize (= 0.9.0)
    capybara (2.5.0)
      mime-types (>= 1.16)
      nokogiri (>= 1.3.3)
      rack (>= 1.0.0)
      rack-test (>= 0.5.4)
      xpath (~> 2.0)
    capybara-webkit (1.7.1)
      capybara (>= 2.3.0, < 2.6.0)
      json
    chunky_png (1.3.5)
    ckeditor (4.1.4)
      cocaine
      orm_adapter (~> 0.5.0)
    climate_control (0.0.3)
      activesupport (>= 3.0)
    cocaine (0.5.7)
      climate_control (>= 0.0.3, < 1.0)
    coderay (1.1.0)
    coffee-rails (4.1.0)
      coffee-script (>= 2.2.0)
      railties (>= 4.0.0, < 5.0)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.9.1.1)
    color (1.8)
    color_difference (0.0.1)
    columnize (0.9.0)
    connection_pool (2.2.0)
    crack (0.4.2)
      safe_yaml (~> 1.0.0)
    daemons (1.2.3)
    dalli (2.7.4)
    database_cleaner (1.5.1)
    debug_inspector (0.0.2)
    detect_timezone_rails (0.0.5)
      railties (>= 3.1)
    diff-lcs (1.2.5)
    diffy (3.0.7)
    docile (1.1.5)
    domain_name (0.5.25)
      unf (>= 0.0.5, < 1.0.0)
    dotenv (2.0.2)
    dotenv-rails (2.0.2)
      dotenv (= 2.0.2)
      railties (~> 4.0)
    draper (2.1.0)
      actionpack (>= 3.0)
      activemodel (>= 3.0)
      activesupport (>= 3.0)
      request_store (~> 1.0)
    easy_translate (0.5.0)
      json
      thread
      thread_safe
    email_spec (1.6.0)
      launchy (~> 2.1)
      mail (~> 2.2)
    email_validator (1.6.0)
      activemodel
    erubis (2.7.0)
    excon (0.45.4)
    execjs (2.6.0)
    factory_girl (4.5.0)
      activesupport (>= 3.0.0)
    factory_girl_rails (4.5.0)
      factory_girl (~> 4.5.0)
      railties (>= 3.0.0)
    faker (1.5.0)
      i18n (~> 0.5)
    faraday (0.9.2)
      multipart-post (>= 1.2, < 3)
    faraday_middleware (0.9.2)
      faraday (>= 0.7.4, < 0.10)
    fast_stack (0.1.0)
      rake
      rake-compiler
    ffi (1.9.10)
    flamegraph (0.1.0)
      fast_stack
    flutie (2.0.0)
    formatador (0.2.5)
    formulaic (0.3.0)
      activesupport
      capybara
      i18n
    geocoder (1.2.12)
    globalid (0.3.6)
      activesupport (>= 4.1.0)
    guard (2.13.0)
      formatador (>= 0.2.4)
      listen (>= 2.7, <= 4.0)
      lumberjack (~> 1.0)
      nenv (~> 0.1)
      notiffany (~> 0.0)
      pry (>= 0.9.12)
      shellany (~> 0.0)
      thor (>= 0.18.1)
    guard-compat (1.2.1)
    guard-rspec (4.6.4)
      guard (~> 2.1)
      guard-compat (~> 1.1)
      rspec (>= 2.99.0, < 4.0)
    hashdiff (0.2.2)
    hashids (1.0.2)
    hashie (3.4.3)
    health_check (1.5.1)
      rails (>= 2.3.0)
    high_voltage (2.4.0)
    highline (1.7.8)
    hike (1.2.3)
    hirefire-resource (0.3.8)
    http (0.9.8)
      addressable (~> 2.3)
      http-cookie (~> 1.0)
      http-form_data (~> 1.0.1)
      http_parser.rb (~> 0.6.0)
    http-cookie (1.0.2)
      domain_name (~> 0.5)
    http-form_data (1.0.1)
    http_parser.rb (0.6.0)
    httparty (0.13.7)
      json (~> 1.8)
      multi_xml (>= 0.5.2)
    i18n (0.7.0)
    i18n-tasks (0.9.1)
      activesupport (>= 4.0.2)
      ast (>= 2.1.0)
      easy_translate (>= 0.5.0)
      erubis
      highline (>= 1.7.3)
      i18n
      parser (>= 2.2.3.0)
      term-ansicolor (>= 1.3.2)
      terminal-table (>= 1.5.1)
    interactor (3.1.0)
    interactor-rails (2.0.1)
      interactor (~> 3.0)
      rails (>= 3, < 5)
    jbuilder (2.3.2)
      activesupport (>= 3.0.0, < 5)
      multi_json (~> 1.2)
    jmespath (1.1.3)
    jquery-rails (4.0.5)
      rails-dom-testing (~> 1.0)
      railties (>= 4.2.0)
      thor (>= 0.14, < 2.0)
    jquery-ui-rails (5.0.5)
      railties (>= 3.2.16)
    json (1.8.3)
    json-schema (2.5.1)
      addressable (~> 2.3.7)
    json_spec (1.1.4)
      multi_json (~> 1.0)
      rspec (>= 2.0, < 4.0)
    jwt (1.5.2)
    kgio (2.10.0)
    launchy (2.4.3)
      addressable (~> 2.3)
    linkedin-scraper (1.0.1)
      mechanize (~> 2)
    listen (3.0.3)
      rb-fsevent (>= 0.9.3)
      rb-inotify (>= 0.9)
    loofah (2.0.3)
      nokogiri (>= 1.5.9)
    lumberjack (1.0.9)
    mail (2.6.3)
      mime-types (>= 1.16, < 3)
    mandrill-api (1.0.53)
      excon (>= 0.16.0, < 1.0)
      json (>= 1.7.7, < 2.0)
    mechanize (2.7.3)
      domain_name (~> 0.5, >= 0.5.1)
      http-cookie (~> 1.0)
      mime-types (~> 2.0)
      net-http-digest_auth (~> 1.1, >= 1.1.1)
      net-http-persistent (~> 2.5, >= 2.5.2)
      nokogiri (~> 1.4)
      ntlm-http (~> 0.1, >= 0.1.1)
      webrobots (>= 0.0.9, < 0.2)
    method_source (0.8.2)
    mime-types (2.6.2)
    mimemagic (0.3.0)
    mini_portile (0.6.2)
    minitest (5.8.3)
    miro (0.3.0)
      cocaine
      color
      oily_png
    mixpanel-ruby (2.2.0)
    monban (0.2.1)
      bcrypt
      rails
      warden
    monban-generators (0.0.4)
      monban (>= 0.0.12)
    monetize (1.1.0)
      money (~> 6.5.0)
    money (6.5.1)
      i18n (>= 0.6.4, <= 0.7.0)
    money-rails (1.4.1)
      activesupport (>= 3.0)
      monetize (~> 1.1.0)
      money (~> 6.5.0)
      railties (>= 3.0)
    mongoid (4.0.2)
      activemodel (~> 4.0)
      moped (~> 2.0.0)
      origin (~> 2.1)
      tzinfo (>= 0.3.37)
    mono_logger (1.1.0)
    moped (2.0.7)
      bson (~> 3.0)
      connection_pool (~> 2.0)
      optionable (~> 0.2.0)
    multi_json (1.11.2)
    multi_xml (0.5.5)
    multipart-post (2.0.0)
    neat (1.5.1)
      bourbon (>= 3.1)
      sass (~> 3.2.19)
    nenv (0.2.0)
    nested_form (0.3.2)
    net-http-digest_auth (1.4)
    net-http-persistent (2.9.4)
    newrelic_rpm (3.14.0.305)
    nokogiri (1.6.6.2)
      mini_portile (~> 0.6.0)
    nondestructive_migrations (1.1)
      activerecord (>= 4.0)
    normalize-rails (3.0.3)
    notiffany (0.0.8)
      nenv (~> 0.1)
      shellany (~> 0.0)
    ntlm-http (0.1.1)
    oauth2 (1.0.0)
      faraday (>= 0.8, < 0.10)
      jwt (~> 1.0)
      multi_json (~> 1.3)
      multi_xml (~> 0.5)
      rack (~> 1.2)
    oily_png (1.2.0)
      chunky_png (~> 1.3.1)
    opbeat (2.0.0)
      faraday (>= 0.7.6, < 0.10)
      multi_json (~> 1.0)
    optionable (0.2.0)
    origin (2.1.1)
    orm_adapter (0.5.0)
    parser (2.2.3.0)
      ast (>= 1.1, < 3.0)
    pdf-core (0.6.0)
    pg (0.18.3)
    phony (2.15.7)
    phony_rails (0.12.10)
      activesupport (>= 3.0)
      phony (~> 2.12)
    prawn (2.0.2)
      pdf-core (~> 0.6.0)
      ttfunk (~> 1.4.0)
    pry (0.10.3)
      coderay (~> 1.1.0)
      method_source (~> 0.8.1)
      slop (~> 3.4)
    pry-byebug (3.2.0)
      byebug (~> 5.0)
      pry (~> 0.10)
    pry-rails (0.3.4)
      pry (>= 0.9.10)
    puma (2.14.0)
    pundit (1.0.1)
      activesupport (>= 3.0.0)
    rack (1.6.4)
    rack-attack (4.3.0)
      rack
    rack-cache (1.5.1)
      rack (>= 0.4)
    rack-protection (1.5.3)
      rack
    rack-test (0.6.3)
      rack (>= 1.0)
    rack-timeout (0.3.2)
    railroady (1.4.1)
    rails (4.2.0)
      actionmailer (= 4.2.0)
      actionpack (= 4.2.0)
      actionview (= 4.2.0)
      activejob (= 4.2.0)
      activemodel (= 4.2.0)
      activerecord (= 4.2.0)
      activesupport (= 4.2.0)
      bundler (>= 1.3.0, < 2.0)
      railties (= 4.2.0)
      sprockets-rails
    rails-deprecated_sanitizer (1.0.3)
      activesupport (>= 4.2.0.alpha)
    rails-dom-testing (1.0.7)
      activesupport (>= 4.2.0.beta, < 5.0)
      nokogiri (~> 1.6.0)
      rails-deprecated_sanitizer (>= 1.0.1)
    rails-html-sanitizer (1.0.2)
      loofah (~> 2.0)
    rails_12factor (0.0.3)
      rails_serve_static_assets
      rails_stdout_logging
    rails_serve_static_assets (0.0.4)
    rails_stdout_logging (0.0.4)
    railties (4.2.0)
      actionpack (= 4.2.0)
      activesupport (= 4.2.0)
      rake (>= 0.8.7)
      thor (>= 0.18.1, < 2.0)
    rake (10.4.2)
    rake-compiler (0.9.5)
      rake
    rb-fsevent (0.9.6)
    rb-inotify (0.9.5)
      ffi (>= 0.5.0)
    recipient_interceptor (0.1.2)
      mail
    redis (3.2.1)
    redis-namespace (1.5.2)
      redis (~> 3.0, >= 3.0.4)
    request_store (1.2.0)
    responders (2.1.0)
      railties (>= 4.2.0, < 5)
    resque (1.25.2)
      mono_logger (~> 1.0)
      multi_json (~> 1.0)
      redis-namespace (~> 1.3)
      sinatra (>= 0.9.2)
      vegas (~> 0.1.2)
    resque-cleaner (0.3.0)
      resque (~> 1.0)
    resque-pool (0.6.0)
      rake
      resque (~> 1.22)
    resque-queue-priority (0.6.2)
      resque (~> 1.10)
    resque-retry (1.5.0)
      resque (~> 1.25)
      resque-scheduler (~> 4.0)
    resque-rollbar (0.3.0)
      resque
      rollbar (>= 1.2)
    resque-scheduler (4.0.0)
      mono_logger (~> 1.0)
      redis (~> 3.0)
      resque (~> 1.25)
      rufus-scheduler (~> 3.0)
    resque-timeout (1.0.0)
      resque (~> 1.0)
    resque_mailer (2.2.7)
      actionmailer (>= 3.0)
    rmagick (2.15.4)
    rollbar (2.5.2)
      multi_json
    rspec (3.0.0)
      rspec-core (~> 3.0.0)
      rspec-expectations (~> 3.0.0)
      rspec-mocks (~> 3.0.0)
    rspec-core (3.0.4)
      rspec-support (~> 3.0.0)
    rspec-expectations (3.0.4)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.0.0)
    rspec-mocks (3.0.4)
      rspec-support (~> 3.0.0)
    rspec-rails (3.0.2)
      actionpack (>= 3.0)
      activesupport (>= 3.0)
      railties (>= 3.0)
      rspec-core (~> 3.0.0)
      rspec-expectations (~> 3.0.0)
      rspec-mocks (~> 3.0.0)
      rspec-support (~> 3.0.0)
    rspec-support (3.0.4)
    rufus-scheduler (3.1.7)
    safe_yaml (1.0.4)
    sass (3.2.19)
    sass-rails (4.0.5)
      railties (>= 4.0.0, < 5.0)
      sass (~> 3.2.2)
      sprockets (~> 2.8, < 3.0)
      sprockets-rails (~> 2.0)
    shellany (0.0.1)
    shoulda-matchers (3.0.1)
      activesupport (>= 4.0.0)
    simple_form (3.2.0)
      actionpack (~> 4.0)
      activemodel (~> 4.0)
    simplecov (0.10.0)
      docile (~> 1.1.0)
      json (~> 1.8)
      simplecov-html (~> 0.10.0)
    simplecov-html (0.10.0)
    sinatra (1.4.6)
      rack (~> 1.4)
      rack-protection (~> 1.4)
      tilt (>= 1.3, < 3)
    skylight (0.10.0)
      activesupport (>= 3.0.0)
    slack-notifier (1.4.0)
    slop (3.6.0)
    spring (1.4.0)
    spring-commands-rspec (1.0.4)
      spring (>= 0.9.1)
    sprockets (2.12.4)
      hike (~> 1.2)
      multi_json (~> 1.0)
      rack (~> 1.0)
      tilt (~> 1.1, != 1.3.0)
    sprockets-rails (2.3.3)
      actionpack (>= 3.0)
      activesupport (>= 3.0)
      sprockets (>= 2.8, < 4.0)
    stackprof (0.2.7)
    term-ansicolor (1.3.2)
      tins (~> 1.0)
    terminal-table (1.5.2)
    thor (0.19.1)
    thread (0.2.2)
    thread_safe (0.3.5)
    tilt (1.4.1)
    time_for_a_boolean (0.0.6)
      activerecord
      railties
    timecop (0.8.0)
    tins (1.6.0)
    title (0.0.5)
      i18n
      rails (>= 3.1)
    ttfunk (1.4.0)
    tzinfo (1.2.2)
      thread_safe (~> 0.1)
    uglifier (2.7.2)
      execjs (>= 0.3.0)
      json (>= 1.8.0)
    unf (0.1.4)
      unf_ext
    unf_ext (0.0.7.1)
    uniform_notifier (1.9.0)
    useragent (0.16.2)
    vegas (0.1.11)
      rack (>= 1.0.0)
    versionist (1.4.1)
      activesupport (>= 3)
      railties (>= 3)
      yard (~> 0.7)
    warden (1.2.3)
      rack (>= 1.0)
    web-console (2.2.1)
      activemodel (>= 4.0)
      binding_of_caller (>= 0.7.2)
      railties (>= 4.0)
      sprockets-rails (>= 2.0, < 4.0)
    webmock (1.22.3)
      addressable (>= 2.3.6)
      crack (>= 0.3.2)
      hashdiff
    webrobots (0.1.1)
    xpath (2.0.0)
      nokogiri (~> 1.3)
    yajl-ruby (1.2.1)
    yard (0.8.7.6)
    zero_push (2.5.1)
      faraday (~> 0.9.0)
      faraday_middleware (~> 0.9.0)

PLATFORMS
  ruby

DEPENDENCIES
  StreetAddress
  active_model_serializers
  acts-as-taggable-on
  airbrake
  analytical
  awesome_print
  aws-sdk
  bitters
  bourbon (~> 3.2.1)
  bullet
  byebug
  capybara-webkit (>= 1.2.0)
  ckeditor
  coffee-rails
  color_difference
  daemons
  dalli
  database_cleaner
  detect_timezone_rails
  diffy
  dotenv-rails
  draper
  email_spec
  email_validator
  factory_girl_rails
  faker
  flamegraph
  flutie
  formulaic
  geocoder
  guard-rspec
  hashids
  health_check
  high_voltage
  hirefire-resource
  http
  httparty
  i18n-tasks
  interactor-rails
  jbuilder
  jquery-rails
  jquery-ui-rails
  json-schema
  json_spec
  kgio
  launchy
  linkedin-oauth2!
  linkedin-scraper
  mandrill-api
  miro
  mixpanel-ruby
  monban
  monban-generators
  money-rails
  mongoid (~> 4.0.0)
  neat (~> 1.5.1)
  nested_form
  newrelic_rpm
  nokogiri
  nondestructive_migrations
  normalize-rails (~> 3.0.0)
  opbeat
  paperclip!
  pg
  phony_rails
  prawn
  pry-byebug
  pry-rails
  puma
  pundit
  rack-attack
  rack-cache
  rack-timeout
  railroady
  rails (= 4.2)
  rails_12factor
  recipient_interceptor
  responders (~> 2.0)
  resque-cleaner
  resque-pool
  resque-queue-priority
  resque-retry
  resque-rollbar
  resque-serializable!
  resque-timeout
  resque_mailer
  rmagick
  rollbar (~> 2.5.2)
  rspec-rails (~> 3.0.0)
  sass-rails (~> 4.0.3)
  shoulda-matchers
  simple_form
  simplecov
  skylight
  slack-notifier
  spring
  spring-commands-rspec
  stackprof
  time_for_a_boolean
  timecop
  title
  uglifier
  useragent
  versionist
  web-console (~> 2.0)
  webmock
  yajl-ruby
  zero_push

BUNDLED WITH
   1.10.6

**Comment by RochesterinNYC** [comment]
Hm, using the same versions of rubygems, ruby, and bundler but rbenv instead of rvm and Git version 2.5.0, I can't seem to replicate the issue.

**Comment by TimMoore** [comment]
@jschwendt is this still an issue for you?

**Comment by jschwendt** [comment]
When I changed over to rbenv, everything is fine now.  I also upgraded to ruby 2.2.3.  Thanks for looking into this.

**Comment by TimMoore** [comment]
Thanks for confirming

**Comment by connorshea** [comment]
I just got this issue, albeit with `NoMethodError: undefined method `>' for nil:NilClass`. Is the only solution to use rbenv instead of rvm?

It occured when running `bundle outdated --patch`, but the `--minor` and `--major` flags work fine.

**Comment by RochesterinNYC** [comment]
@connorshea That sounds like it might be a different issue, could you open a new issue with reproduction steps and more information?

**Comment by connorshea** [comment]
@RochesterinNYC opened at #4438
