### ISSUE TITLE
newer bundler versions (> 1.10.x ) miss a lot of files when creating an rpm

### ISSUE THREAD

**Issue by spuhler** [bundler/bundler#4179]
when trying to create an rpm, I miss about 70% of the files. See https://www.rpmfind.net/linux/RPM/mageia/cauldron/i586/media/core/release/ruby-bundler-1.11.2-1.mga6.noarch.html
puting a sed -i -e 's|find -z \(.*\)`|find \1 -print0`|' %{oname}.gemspec in the %prep stage after %gem_setup resolves the issue. What is this option "-z" for?

**Comment by indirect** [comment]
@spuhler sorry, I can't tell what the problem you are reporting is here. Can you please follow [ISSUES](https://github.com/bundler/bundler/blob/master/ISSUES.md) and report all the information we need to diagnose a bug?

**Comment by spuhler** [comment]
let me reword it. I am trying to package the current bundler as an rpm for Mageia. However I am missing about 70% of the files in the rpm.
when removing the "-z" option from line   
s.files = `git ls-files -z`.split("\x0").reject {|f| f.match(%r{^(test|spec|features)/}) }
in the bundler.gemspec file all files get added in the rpm

**Comment by indirect** [comment]
@spuhler the Bundler team only supports distributing, installing, and using Bundler as a RubyGems gem. I'm sorry you're having trouble with your RPM, but that's not something that we provide support for doing. The existing gemspec works for us to create .gem releases, and that's what we need it to do.
