### ISSUE TITLE
Bundlers all up to 1.11.2 but some deployments still insist on removing BUNDLED WITH

### ISSUE THREAD

**Issue by tardate** [bundler/bundler#4180]
I have an app deployed to two servers (load-balanced pair - same CentOS config).

As far as I can tell, these servers are identical, but for some reason, `bundle install` insists on removing `BUNDLED WITH` from the Gemfile.lock on one machine but not the other.

Facts:
* servers have the same commit deployed
* Gemfile.lock is checked-in, and includes `BUNDLED WITH` 1.11.2
* both servers running rvm 1.26.11 and an (old I know) ruby 1.9.3-p327
* both servers updated to bundler 1.11.2

The behaviour is consistent. I can repeat many times over. server 1 always leaves `BUNDLED WITH` in place, but server 2 always removes it.

Base on what I understand from all the other `bundled with` issues like \#3697 this should not be happening. Am I wrong?  Any suggestions on how I can track down the issue I'm seeing?

## server 1
```
$ rvm -v
rvm 1.26.11 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
$ ruby -v
ruby 1.9.3p327 (2012-11-10 revision 37606) [x86_64-linux]
$ git log -n1
commit 2a7f759d79b35d99d86a9729c17c17fbe505a227
$ git status
# On branch staging
nothing to commit (working directory clean)
$ bundler -v
Bundler version 1.11.2
$ bundle install
[...]
Bundle complete! 13 Gemfile dependencies, 59 gems now installed.
$ git status
# On branch staging
nothing to commit, working directory clean
```
## server 2
```
$ rvm -v
rvm 1.26.11 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
$ ruby -v
ruby 1.9.3p327 (2012-11-10 revision 37606) [x86_64-linux]
$ git log -n1
commit 2a7f759d79b35d99d86a9729c17c17fbe505a227
$ git status
# On branch staging
nothing to commit (working directory clean)
$ bundler -v
Bundler version 1.11.2
$ bundle install
[...]
Bundle complete! 13 Gemfile dependencies, 59 gems now installed.
$ git status
# On branch staging
# Changed but not updated:
#   (use "git add <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working directory)
#
#       modified:   Gemfile.lock
#
no changes added to commit (use "git add" and/or "git commit -a")
$ git diff Gemfile.lock
diff --git a/utilities/Gemfile.lock b/utilities/Gemfile.lock
index 46342b3..e489ef3 100644
--- a/utilities/Gemfile.lock
+++ b/utilities/Gemfile.lock
@@ -218,6 +218,3 @@ DEPENDENCIES
   jwt (~> 0.1.8)
   newrelic_plugin
   passenger (= 3.0.19)
-
-BUNDLED WITH
-   1.11.2
```

**Comment by indirect** [comment]
Sounds like you have environment variables set on server 2 that are somehow loading an older version of Bundler (perhaps from a different ruby version?)

**Comment by tardate** [comment]
hi @indirect no, don't think environment variables (there are no appreciable diffs except hostname etc)

I think I may have tracked it down:
* server 2 had rubygems-bundler (1.1.0)
* server 1 had rubygems-bundler (1.4.4, 1.1.0)

I don't know what was responsible for installing/updating rubygems-bundler to 1.4.4 on server 1, since it's not explicitly referenced in any Gemfiles, scripts or our installation procedures.

However, when I `gem update rubygems-bundler` and get them both on 1.4.4, the problem with the vanishing 'BUNDLED WITH` has gone away.

That's real strange. I don't see any references to `rubygems-bundler` in the BUNDLED WITH saga. I guess that's because these issues are with quite an old app running pre ruby 2?

**Comment by indirect** [comment]
@tardate Got it. I guess that's not super surprising: the rubygems-bundler gem is created by the maintainer of rvm. It is not endorsed or supported by the teams of either RubyGems or Bundler, and can cause unexpected problems if it is installed (and FWIW, the Bundler team's official recommendation is to uninstall it completely).

I'll keep this issue in mind for future troubleshooting suggestions, thanks for reporting back with the solution!
