### ISSUE TITLE
getting this error after adding the polymer-rails gem

### ISSUE THREAD

**Issue by didieruzan** [bundler/bundler#4181]
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `/Users/didieruzan/.rbenv/versions/2.1.2/bin/bundle install`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what actually happened was...

Error details

    RuntimeError: LazySpecification has not been materialized yet (calling :required_ruby_version [])
      /Users/didieruzan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.11.0/lib/bundler/lazy_specification.rb:75:in `method_missing'
      /Users/didieruzan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.11.0/lib/bundler/resolver.rb:132:in `for?'
      /Users/didieruzan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.11.0/lib/bundler/resolver.rb:275:in `block in search_for'
      /Users/didieruzan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.11.0/lib/bundler/resolver.rb:275:in `select'
      /Users/didieruzan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.11.0/lib/bundler/resolver.rb:275:in `search_for'
      /Users/didieruzan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.11.0/lib/bundler/resolver.rb:332:in `block in verify_gemfile_dependencies_are_found!'
      /Users/didieruzan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.11.0/lib/bundler/resolver.rb:330:in `each'
      /Users/didieruzan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.11.0/lib/bundler/resolver.rb:330:in `verify_gemfile_dependencies_are_found!'
      /Users/didieruzan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.11.0/lib/bundler/resolver.rb:199:in `start'
      /Users/didieruzan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.11.0/lib/bundler/resolver.rb:183:in `resolve'
      /Users/didieruzan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.11.0/lib/bundler/definition.rb:198:in `resolve'
      /Users/didieruzan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.11.0/lib/bundler/definition.rb:163:in `missing_specs'
      /Users/didieruzan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.11.0/lib/bundler/installer.rb:187:in `block in resolve_if_need'
      /Users/didieruzan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.11.0/lib/bundler/ui/shell.rb:80:in `silence'
      /Users/didieruzan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.11.0/lib/bundler/installer.rb:184:in `resolve_if_need'
      /Users/didieruzan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.11.0/lib/bundler/installer.rb:69:in `run'
      /Users/didieruzan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.11.0/lib/bundler/installer.rb:21:in `install'
      /Users/didieruzan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.11.0/lib/bundler/cli/install.rb:105:in `run'
      /Users/didieruzan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.11.0/lib/bundler/cli.rb:172:in `install'
      /Users/didieruzan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.11.0/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /Users/didieruzan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.11.0/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /Users/didieruzan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.11.0/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /Users/didieruzan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.11.0/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /Users/didieruzan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.11.0/lib/bundler/cli.rb:10:in `start'
      /Users/didieruzan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.11.0/exe/bundle:19:in `block in <top (required)>'
      /Users/didieruzan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.11.0/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
      /Users/didieruzan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.11.0/exe/bundle:17:in `<top (required)>'
      /Users/didieruzan/.rbenv/versions/2.1.2/bin/bundle:23:in `load'
      /Users/didieruzan/.rbenv/versions/2.1.2/bin/bundle:23:in `<main>'

Environment

    Bundler   1.11.0
    Rubygems  2.2.2
    Ruby      2.1.2p95 (2014-05-08 revision 45877) [x86_64-darwin14.0]
    GEM_HOME  /Users/didieruzan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0
    GEM_PATH  /Users/didieruzan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0:/Users/didieruzan/.gem/ruby/2.1.0
    Git       2.5.4 (Apple Git-61)

Bundler settings

    without
      Set for your local app (/Users/didieruzan/dev/samurai/.bundle/config): "production:server"
--- TEMPLATE END ----------------------------------------------------------------

**Comment by segiddins** [comment]
This should be fixed in 1.11.2, can you try updating?

**Comment by didieruzan** [comment]
Yes that did it, Thanks
