### ISSUE TITLE
Errno::EAGAIN: Resource temporarily unavailable @ rb_sysopen

### ISSUE THREAD

**Issue by p-vital** [bundler/bundler#4183]
Getting this error when running bundle install and a new gem needs to be downloaded/installed:
<pre>
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `/home/user/.rbenv/versions/2.2.4/bin/bundle install`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what actually happened was...

Error details

    Errno::EAGAIN: Resource temporarily unavailable @ rb_sysopen - /home/user/app/Gemfile.lock
      /home/user/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/definition.rb:268:in `initialize'
      /home/user/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/definition.rb:268:in `open'
      /home/user/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/definition.rb:268:in `block in lock'
      /home/user/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/shared_helpers.rb:114:in `filesystem_access'
      /home/user/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/definition.rb:267:in `lock'
      /home/user/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/environment.rb:34:in `lock'
      /home/user/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/installer.rb:72:in `run'
      /home/user/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/installer.rb:21:in `install'
      /home/user/.rbenv/rbenv.d/exec/gem-rehash/rubygems_plugin.rb:27:in `install'
      /home/user/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/cli/install.rb:105:in `run'
      /home/user/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/cli.rb:172:in `install'
      /home/user/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /home/user/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /home/user/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /home/user/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /home/user/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/cli.rb:10:in `start'
      /home/user/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/exe/bundle:19:in `block in <top (required)>'
      /home/user/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
      /home/user/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/exe/bundle:17:in `<top (required)>'
      /home/user/.rbenv/versions/2.2.4/bin/bundle:23:in `load'
      /home/user/.rbenv/versions/2.2.4/bin/bundle:23:in `<main>'

Environment

    Bundler   1.11.2
    Rubygems  2.4.5.1
    Ruby      2.2.4p230 (2015-12-16 revision 53155) [x86_64-linux]
    GEM_HOME  /home/user/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0
    GEM_PATH  /home/user/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0:/home/user/.gem/ruby/2.2.0
    Git       1.9.1
--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/bundler/bundler/search?q=Resource+temporarily+unavailable+%40+rb_sysopen+-+%2Fhome%2Fuser%2Fapp%2FGemfile.lock&type=Issues

If there aren't any reports for this error yet, please create copy and paste the report template above into a new issue. Don't forget to anonymize any private data! The new issue form is located at:
https://github.com/bundler/bundler/issues/new
</pre>
This happens after all the gems are installed.
Gemfile.lock is not updated.

Then I run `bundle install` again and it succeeds and updates Gemfile.lock.

The OS is Ubuntu 14.04 in a virtualbox VM.

**Comment by indirect** [comment]
@segiddins @RochesterinNYC looks like we're missing a permissions error from the friendly handler

**Comment by agis-** [comment]
Fixed by #4189.
