### ISSUE TITLE
bundler.require is not requiring gems if it's "require name" is different from "gem name"

### ISSUE THREAD

**Issue by PositiveAlex** [bundler/bundler#4190]
For instance, i need to write: 

`gem 'ruby-oci8', :require => 'oci8'`

to be able to autorequire this module in `bundle.require`

**Comment by indirect** [comment]
Yup, that's exactly how Bundler works.

**Comment by indirect** [comment]
(It might be worth suggesting to the author of ruby-oci8 to release their gem as oci8 instead)
