### ISSUE TITLE
Wrong version problem

### ISSUE THREAD

**Issue by luiz-rocha** [bundler/bundler#4194]
How could that be possible?

$ /var/lib/gems/2.2.0/gems/bundler-1.11.2/exe/bundle --version
Bundler version 1.3.5

**Comment by segiddins** [comment]
what happens if you execute the rubygems-generated binstub instead?

**Comment by luiz-rocha** [comment]
$ bin/bundle --version
Bundler version 1.3.5

$ ruby2.2 bin/bundle --version
Bundler version 1.3.5

**Comment by luiz-rocha** [comment]
I installed using
sudo gem2.2 install bundler

**Comment by segiddins** [comment]
What's the `bin/bundle` you're running? What happens if you just run `bundle --version` without pointing directly to an executable?

**Comment by luiz-rocha** [comment]
I'm pointing to my project bin's folder.
Because when i run bundle in my project folder, it says:
- Your Ruby version is 1.9.3, but your Gemfile specified 2.2.3
And running bundle --version
- Bundler version 1.11.2
or when i run bin/bundle which starts the version 2.2
Current Bundler version: bundler (1.3.5)

I don't understand why this problem happens

**Comment by luiz-rocha** [comment]
I installed ruby and bundler again and it seems to be worked
Thanks for the help
