### ISSUE TITLE
Bundle install hangs for unknown reason

### ISSUE THREAD

**Issue by andrewhavens** [bundler/bundler#4203]
I am using the latest version of bundler (1.11.2). For some reason, bundle install now hangs but I don't know why. Here's a gist of my `bundle env` output: https://gist.github.com/andrewhavens/6baa0e4e947a79132b64

Here is what my terminal looks like when it's hanging. You can see `git-upload-pack` is running, but I don't know what it is doing or why it is hanging.

<img width="734" alt="screen shot 2016-01-07 at 11 46 41 am" src="https://cloud.githubusercontent.com/assets/446392/12181145/5b5bd57e-b535-11e5-8120-9460afc02ab7.png">

**Comment by segiddins** [comment]
Interesting... that Gemfile / Gemfile.lock installs fine for me. It's also really strange that we're not printing _any_ verbose output there. Is there any chance you have some sort of weird git config set up?

**Comment by andrewhavens** [comment]
No, nothing weird. It was working for me yesterday. I switched to a different version of Ruby (2.2.3) and ran `bundle install` again, and it worked. Not sure if I should switch back to 2.2.2 and see if I can reproduce it.

**Comment by andrewhavens** [comment]
By the way, I'm seeing this issue again today. I have been using Ruby 2.2.3. I just added a gem to my Gemfile which points to a GitHub repo, and now it is hanging. This is all I ever see:

```
$ bundle install --verbose
Fetching git://github.com/Dockyard/capybara-email.git
```

**Comment by TimMoore** [comment]
This sounds like a network problem to me. Could something be blocking git protocol connections from your network?

**Comment by dcrec1** [comment]
It also happens with me, but only with Ruby 2.2.3, Ruby 2.2.2 bundles fine.

**Comment by indirect** [comment]
@dcrec1 please open a new issue, following [ISSUES](https://github.com/bundler/bundler/blob/master/ISSUES.md). If you can, please also follow the "I have a deadlock, but I don't know where" instructions from [i am a puts debuggerer](http://tenderlovemaking.com/2016/02/05/i-am-a-puts-debuggerer.html) and include the full thread backtraces. Thanks!
