### ISSUE TITLE
No value provided for required arguments 'app_path'

### ISSUE THREAD

**Issue by HSweetness** [bundler/bundler#4204]
Hey every one I'm new to this, but i am having trouble first, it said i had no gems and then i did something and this game up and when i try to create a new blog, its says No value provided for required arguments 'app_path'. please help

 -r, [--ruby=PATH]                                      # Path to the Ruby binary of your choice
                                                         # Default: C:/RailsInstaller/Ruby2.1.0/bin/ruby.exe
  -m, [--template=TEMPLATE]                              # Path to some application template (can be a filesystem path or URL)
      [--skip-gemfile], [--no-skip-gemfile]              # Don't create a Gemfile
  -B, [--skip-bundle], [--no-skip-bundle]                # Don't run bundle install
  -G, [--skip-git], [--no-skip-git]                      # Skip .gitignore file
      [--skip-keeps], [--no-skip-keeps]                  # Skip source control .keep files
  -O, [--skip-active-record], [--no-skip-active-record]  # Skip Active Record files
  -V, [--skip-action-view], [--no-skip-action-view]      # Skip Action View files
  -S, [--skip-sprockets], [--no-skip-sprockets]          # Skip Sprockets files
      [--skip-spring], [--no-skip-spring]                # Don't install Spring application preloader
  -d, [--database=DATABASE]                              # Preconfigure for selected database (options: mysql/oracle/postgresql/sqlite3/frontbase/ibm_db/sqlserver/jdbcmysql/jdbcsqlite3/jdbcpostgresql/jdbc)
                                                         # Default: sqlite3
  -j, [--javascript=JAVASCRIPT]                          # Preconfigure for selected JavaScript library
                                                         # Default: jquery
  -J, [--skip-javascript], [--no-skip-javascript]        # Skip JavaScript files
      [--dev], [--no-dev]                                # Setup the application with Gemfile pointing to your Rails checkout
      [--edge], [--no-edge]                              # Setup the application with Gemfile pointing to Rails repository
  -T, [--skip-test-unit], [--no-skip-test-unit]          # Skip Test::Unit files
      [--rc=RC]                                          # Path to file containing extra configuration options for rails command
      [--no-rc], [--no-no-rc]                            # Skip loading of extra configuration options from .railsrc file

**Comment by segiddins** [comment]
@HSweetness what exactly is going wrong for you? This doesn't really seem to have anything to do with bundler?

**Comment by HSweetness** [comment]
I don't know it's saying that it can't find gem file, and licenses are not valid.

Sent from Sweets iPhone

On Jan 7, 2016, at 4:15 PM, Samuel E. Giddins <notifications@github.com<mailto:notifications@github.com>> wrote:


@HSweetness<https://github.com/HSweetness> what exactly is going wrong for you? This doesn't really seem to have anything to do with bundler?

-

**Comment by HSweetness** [comment]
em::RemoteFetcher::FetchError: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://rubygems.org/gems/rake-10.4.2.gem)
An error occurred while installing rake (10.4.2), and Bundler cannot continue.
Make sure that `gem install rake -v '10.4.2'` succeeds before bundling.


________________________________

**Comment by segiddins** [comment]
And does `gem install rake -v '10.4.2'` succeed for you? It looks like your machine is unable to complete an SSL handshake with the rubygems.org server to me.

**Comment by HSweetness** [comment]
No it doesn't I say it cant identify gem, what should I do to fix it ?

Sent from Sweets iPhone

On Jan 7, 2016, at 4:46 PM, Samuel E. Giddins <notifications@github.com<mailto:notifications@github.com>> wrote:


And does gem install rake -v '10.4.2' succeed for you? It looks like your machine is unable to complete an SSL handshake with the rubygems.org<http://rubygems.org> server to me.

-

**Comment by TimMoore** [comment]
@HSweetness try the suggestions at https://gist.github.com/luislavena/f064211759ee0f806c88

**Comment by HSweetness** [comment]
I download the file but having trouble, updating it.

Sent from Sweets iPhone

On Jan 7, 2016, at 5:52 PM, Tim Moore <notifications@github.com<mailto:notifications@github.com>> wrote:


@HSweetness<https://github.com/HSweetness> try the suggestions at https://gist.github.com/luislavena/f064211759ee0f806c88

-

**Comment by HSweetness** [comment]
hey thanks, I think it worked, do i need to install gems now?


Fetching gem metadata from https://rubygems.org/...........
Fetching additional metadata from https://rubygems.org/..
Resolving dependencies...
Installing rake 10.4.2
Installing i18n 0.7.0
Installing json 1.8.3
Installing minitest 5.8.3
Installing thread_safe 0.3.5
Using tzinfo 1.2.2
Using activesupport 4.1.8
Using builder 3.2.2
Using erubis 2.7.0
Using actionview 4.1.8
Installing rack 1.5.5
Installing rack-test 0.6.3
Using actionpack 4.1.8
Installing mime-types 2.99
Using mail 2.6.3
Using actionmailer 4.1.8
Using activemodel 4.1.8
Using arel 5.0.1.20140414130214
Using activerecord 4.1.8
Using bundler 1.7.7
Installing coffee-script-source 1.10.0
Installing execjs 2.6.0
Installing coffee-script 2.4.1
Using thor 0.19.1
Using railties 4.1.8
Installing coffee-rails 4.0.1
Using hike 1.2.3
Installing multi_json 1.11.2
Installing jbuilder 2.4.0
Installing jquery-rails 3.1.4
Using tilt 1.4.1
Installing sprockets 2.12.4
Installing sprockets-rails 2.3.3
Using rails 4.1.8
Installing rdoc 4.2.1
Using sass 3.2.19
Using sass-rails 4.0.5
Installing sdoc 0.4.1
Installing sqlite3 1.3.11
Installing turbolinks 2.5.3
Installing tzinfo-data 1.2015.7
Installing uglifier 2.7.2
Your bundle is complete!
Use `bundle show [gemname]` to see where a bundled gem is installed.
Post-install message from rdoc:
Depending on your version of ruby, you may need to install ruby rdoc/ri data:

<= 1.8.6 : unsupported
 = 1.8.7 : gem install rdoc-data; rdoc-data --install
 = 1.9.1 : gem install rdoc-data; rdoc-data --install
>= 1.9.2 : nothing to do! Yay!

________________________________

**Comment by TimMoore** [comment]
That looks like it worked to me!
