### ISSUE TITLE
document timeout, redirect and retry options

### ISSUE THREAD

**Issue by peterlynch** [bundler/bundler#4205]
In #3583, configurable timeouts, and redirects were added.

Noting that while there was a --retry option for bundle install already, there remains no --timeout or --redirect option implemented - those settings are only possible via bundle config BUNDLE_TIMEOUT and BUNDLE_REDIRECT.

Also those config options are not documented in the bundle config manual, so it is hard to find how to set these without some knowledge of how to set Environment type config options and detailed knowledge of #3586 changes.

This should be better documented.

**Comment by segiddins** [comment]
@peterlynch a PR improving the documentation would be 🚀

**Comment by RochesterinNYC** [comment]
This can be closed as it was addressed by #4215.
