### ISSUE TITLE
Gemfile.local would be really, really, really, useful...  Please?

### ISSUE THREAD

**Issue by patrick99e99** [bundler/bundler#4212]
I've seen a lot of stackoverflow discussion about developers wanting this, and according to this thread

http://stackoverflow.com/questions/4244182/how-to-customize-gemfile-per-developer

It was stated that this was a proposed feature but it was decided to not be included as part of bundler.

...

My situation, I simply want to customize my console by using a tool such as "irbtools".  I can't do this (as far as I understand) without adding it to my project's gemfile, and this will result in everyone on my team suddenly having the exact same changes to their console, which is not acceptable.  I've also read a lot of people say things like "add a line of code at the end of your Gemfile that will read in a local file, and then you'll get your local gemfile!"---  Except they fail to realize this will result in changes to the Gemfile.lock which is unacceptable.

It is a huge frustration to me that I cannot do this, and as a response I got in the irc forum when talking about this was: "seems like a bad idea, Might lead to 'works on my machine'. "

To which I replied:  "the point is, developers should have the freedom to do what they want. if its dangerous for them, then that's their problem.  Bundler shouldn't be trying to save developers from themselves".

So, if I can get blessings here, I will gladly make a pr to do the work to enable this feature.  But I do not want to waste my time (as I have many times in the past on various "open source projects") trying to make something that is useful to me and others, yet the maintainer says "DENIED" because it goes against whatever-- their "philosophy".

Thank you.

**Comment by segiddins** [comment]
This belongs in the bundler/bundler-features repo, but beware that we've gotten this request before and have yet to see a satisfactory proposal for how to implement it. As to your specific usecase, optional groups per-developer probably does 95% of what you need with 0 changes to bundler.
