### ISSUE TITLE
Rubocop fails by default on generated gem

### ISSUE THREAD

**Issue by MOZGIII** [bundler/bundler#4220]
Default gemspec (and other) templates are using double quotes extensively.
It works, but it leads to the following ugliness when using **rubocop**:
![2016-01-20 09 46 12](https://cloud.githubusercontent.com/assets/265507/12441687/b21e54e8-bf5a-11e5-8139-b3413b9fcdf0.png)

Does it really have to be the case?

The first problem there is that generated template does not pass rubocop checks by default. Why wouldn't it? It's a bug to me. This one can be fixed either by changing the templates to be inline with the default settings or by adding a custom rubocop file that would explicitly set some changes to the defaults.

The second problem is that I want to be able to choose the quotes to use. I used to like double quotes. Now I like single quotes. Tomorrow - double quotes again. Someone else might not - at the same time. It's ok, since it's just a template, and I'm still able to change thing to be the way I want them to be. But really takes time. Adding an option would fix that.

Anyway, I'm mostly disturbed by taking manual actions for rubocop to work (let's try to fix that here), and those above are just possible ways on how to look on the problem. So, what do you think?

**Comment by segiddins** [comment]
Why not just run `rubocop -a` or use Ore?

**Comment by segiddins** [comment]
Closing because the generated files conform to Bundler's own style guide.
