### ISSUE TITLE
Q&A Plugin on Redmine 2.4.2

### ISSUE THREAD

**Issue by ravmohun** [bundler/bundler#4234]
Dear All,

I am installing the plugin Q&A, however, i am getting error messages.
I browse to the command prompt path to run bundle install:
C:\BitNami\redmine-2.4.2-0\apps\redmine\htdocs\plugins\redmine_questions

the following error messages:

C:\BitNami\redmine-2.4.2-0\apps\redmine\htdocs\plugins\redmine_questions>bundle
install
Rubygems 1.8.24 is not threadsafe, so your gems will be installed one at a time.
 Upgrade to Rubygems 2.1.0 or higher to enable parallel gem installation.
Using rake 0.9.2.2
Using redmine_crm 0.0.4
Using bundler 1.11.2
Bundle complete! 2 Gemfile dependencies, 3 gems now installed.
Gems in the groups development and test were not installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.

C:\BitNami\redmine-2.4.2-0\apps\redmine\htdocs\plugins\redmine_questions>

and when i ran:
bundle exec rake redmine:plugins NAME=redmine_questions RAILS_ENV=production

the following error message appear:

![qa](https://cloud.githubusercontent.com/assets/16878038/12549331/15d21ef6-c376-11e5-9030-1071ca16c126.png)

Kindly help.

**Comment by segiddins** [comment]
What's the output of `bundle env`?

**Comment by ravmohun** [comment]
Hi segiddins,

Many thanks for assisting me on this issue.
I trust i can rely on your expertise to solve this problem.
I am trying hard to resolve but am failing.
Please find attached output as you requested.
![bundle env](https://cloud.githubusercontent.com/assets/16878038/12573001/cad927ae-c40c-11e5-959b-b9b615f59cc6.png)

**Comment by segiddins** [comment]
OK, so I'm actually having trouble seeing where the bundler issue is?

**Comment by ravmohun** [comment]
any other suggestion please?

**Comment by ravmohun** [comment]
Hi segiddins,

The Q&A plugin is offered on Redmine CRM.
Would it install on free version of redmine 2.4.2?
