### ISSUE TITLE
Setting credentials for gem sources via environment variable does not work if domain name contains dash

### ISSUE THREAD

**Issue by fschwahn** [bundler/bundler#4241]
Hi,
I have a gem host at `gems.with-dash.com`, and I cannot set the credentials using an environment variable (as explained [here](http://bundler.io/man/bundle-config.1.html#CREDENTIALS-FOR-GEM-SOURCES)) because dashes are not allowed in environment variable names (it would have to be `BUNDLE_GEMS__WITH-DASH__COM`, which is invalid at least in bash).

Am I missing something here? I'd be willing to put together a pull request that converts the dash to an underscore in this case. Would this be worthwhile?

**Comment by segiddins** [comment]
I can set an env var with a dash fine using Ruby, maybe you just need to escape the dash?

**Comment by segiddins** [comment]
`env 'foo-bar=bar' env` => `foo-bar=bar`

**Comment by segiddins** [comment]
You can also always use `bundle config` to set the configuration

**Comment by fschwahn** [comment]
Thanks for your quick reply, and for the solutions!

I'd like to set the environment variable using `export`, and I don't see any way to achieve that when the variable name includes a dash. It just seemed like an oversight to me.

You can close this if it is out of scope, as there are alternative ways I can work around this problem. Thanks again!

**Comment by segiddins** [comment]
Yeah, sorry, does kinda feel out of scope to me :/

**Comment by fschwahn** [comment]
Sure, no worries. If it hasn't come up until now, it's most probably of an edge case.

**Comment by fschwahn** [comment]
Hi, sorry to bother again, I will quickly outline my use case, maybe you re-evaluate your stance:

I'm using Gitlab CI for our internal gems. Gitlab CI has a feature which allows you to specify so-called secret environment variables, which are injected in the CI run. We have several internal gems that reference each other, and using any method other than the environment variable approach would force me to include the credentials of our internal gem host in the repository, which I'd like to avoid.

I have [raised this issue with Gitlab](https://gitlab.com/gitlab-org/gitlab-ce/issues/12744), but they are unwilling / not able to allow environment variables with dashes, as these are invalid in bash (and they use bash to set these environment variables).

Thanks again for your attention!
