### ISSUE TITLE
Inconsistent UI re --gemfile

### ISSUE THREAD

**Issue by nyarly** [bundler/bundler#4242]
It's useful that `bundle install` takes a `--gemfile` argument, but it's frustrating that `bundle show` and `bundle update` don't. I use separate gemfiles along with CI build matricies to test compatibility with version of outside gems - RSpec for instance, and maintaining those lockfiles becomes painful when the versions of gems change.

**Comment by segiddins** [comment]
I'd recommend using the `BUNDLE_GEMFILE` env var.

**Comment by nyarly** [comment]
I'm aware of B_E but I use it infrequently, and it doesn't appear in the `help` docs for `bundle` `show` or `install.` Conversely, since `install` has `--gemfile` it's confusing and surprising that `update` and `show` don't.  Conceivably, the solution is simply to document the environment variables that Bundler respects, but having `--gemfile` only available for some cases where `BUNDLE_GEMFILE` would take effect is confusing.

**Comment by segiddins** [comment]
I can't even remember if we've gotten rid of the `--gemfile` option -- all it does is store the gem file as `bundle config --local` would

**Comment by nyarly** [comment]
Based on the CHANGELOG, it's only been added to `install` `init` and `check`.

Looking at https://github.com/bundler/bundler/blob/master/lib/bundler/cli.rb#L19-L20 any command with the gemfile option would use that to override `BUNDLE_GEMFILE` which is the only way the gemfile seems to be located thereafter.  In other words, where it's available, `--gemfile` is equivalent to and trumps the environment variable.

**Comment by segiddins** [comment]
Sure, a PR with tests would be welcome

**Comment by nyarly** [comment]
Unfortunately, `rake spec:deps; rake spec` (per DEVELOPING.md) produces 455 failures on a fresh checkout from master - mostly they seem to be related to git behavior.

**Comment by segiddins** [comment]
Please open up a separate issue for that, making sure you're using the binstubs in `bin`.

**Comment by RochesterinNYC** [comment]
@nyarly are you still working on a PR for the `--gemfile` flag?

**Comment by nyarly** [comment]
I am - it's getting fewer cycles than some other projects, but it's in my queue. This week, probably.

**Comment by sstern6** [comment]
@segiddins Im getting a lot of failures as well when forking off of master to run locally to test.

I was not aware you needed to use binstubs for bin, according to the documentation it says to run this command : `$ bundle binstubs [GEM] [--force] [--path=PATH]` to have binstubs.

Then with what you said would --path be to bin in order to run the tests successfully?

**Comment by segiddins** [comment]
I meant running `bin/rake` instead of `rake` while developing bundler

**Comment by fatkodima** [comment]
So this should be closed accordingly to https://github.com/bundler/bundler/pull/6273 and https://github.com/bundler/bundler/commit/698b247ed83a0f03e86c6d6954c380b9eeab8060
