### ISSUE TITLE
Optional Changelog for gems updated via `bundle update`?

### ISSUE THREAD

**Issue by connorshea** [bundler/bundler#4243]
I'd love the option to have changes from the previous version to the current version of a gem be displayed in the Terminal after Bundler finishes a run of `bundle update`.

As an example, I'd like something like:

```
Connors-MacBook-Pro:Rails-Project connor$ bundle update
Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies......................................................
Using rake 10.5.0
Using i18n 0.7.0
Using json 1.8.3
Installing stripe 1.34.0 (was 1.33.1)
Installing actionpack 4.2.5.1 (was 4.2.5)
Installing actionmailer 4.2.5.1 (was 4.2.5)
Installing railties 4.2.5.1 (was 4.2.5)
Installing rails 4.2.5.1 (was 4.2.5)
Bundle updated!

CHANGES
-----------------------------
rails 4.2.5.1:
Fixes multiple important security vulnerabilities.

See http://weblog.rubyonrails.org/2016/1/25/Rails-5-0-0-beta1-1-4-2-5-1-4-1-14-1-3-2-22-1-and-rails-html-sanitizer-1-0-3-have-been-released/ for more information.

stripe 1.34.0:
Add support for deleting products and SKUs
```

Again, just an example. How reasonable is this? I would assume this would be a change that has to be handled by RubyGems as well as Bundler?

I always have to check every gem's GitHub manually when a major update comes out, would be nice to have that feature built-in.

**Comment by indirect** [comment]
RubyGems don't provide changelogs in a standard way (and often not at all), so there's not really anything for us to show. :/
