### ISSUE TITLE
Can't begin Bundler development

### ISSUE THREAD

**Issue by nyarly** [bundler/bundler#4246]
Referring to DEVELOPMENT.md, I ran `rake spec:deps`, `rake spec` which resulted in 400+ spec fails. 

On advice from @segiddins I added the local bin directory to my `PATH`. 

I've added `bundler/lib` and `bundler/exe/bundle` to `RUBYLIB.`

Still no dice.

I'm on Linux, running MRI 2.1.7 at the moment. There's a warning about rspec-micks ~> 3.4.0 `Unresolved specs during Gem::Specification.reset:`, and the first fail is indeed `undefined method `allow'`

Lots of the fails report `/usr/lib/ruby/site_ruby/1.9.1/rubygems/dependency.rb:315:in `to_specs': Could not find 'git_tracker' (>= 0) among 0 total gem(s) (Gem::LoadError)` which is weird since, as noted, this is under MRI 2.1.7

**Comment by nyarly** [comment]
No difference - although I wouldn't have expected one with ./bin in the PATH. Anyhow, here's the output: https://gist.github.com/nyarly/f0c7a25a113b820b5c70

**Comment by segiddins** [comment]
ah. I think I know what this is. try `gem cleanup rspec-mocks` ?

**Comment by nyarly** [comment]
That get's me a lot farther.

I still get the errors about `Could not find 'git_tracker' (>= 0) among 2 total gem` and I get stalls at "bundle install with gem sources / the simple case / creates a Gemfile.lock on a blank Gemfile"

**Comment by segiddins** [comment]
I'm not sure what to tell you -- it works locally and on CI, and we do our best to create an isolated environment for the tests.

**Comment by nyarly** [comment]
I'll see if I can figure out that detail - perhaps it's worth documenting.

**Comment by segiddins** [comment]
Does a patch like this help for you?

```diff
diff --git a/bin/rspec b/bin/rspec
index 94e0d89..9614dde 100755
--- a/bin/rspec
+++ b/bin/rspec
@@ -7,4 +7,8 @@ bundler_spec.dependencies.each do |dep|
   gem dep.name, dep.requirement.to_s
 end
 
+Gem::Specification.unresolved_deps.each do |name, dep|
+  gem dep.name, dep.requirement.to_s
+end
+
 load Gem.bin_path("rspec-core", "rspec")
```

**Comment by nyarly** [comment]
It doesn't. I still get the `git_tracker` issue. Honestly, I think I'm willing to live with 20 failures for the moment and lean on CI to make sure I didn't break anything new. The PR I have in mind should be pretty minor. Thanks for your help here.

**Comment by segiddins** [comment]
@nyarly I meant does that diff fix the 2000+ failures?

**Comment by nyarly** [comment]
There's a misunderstanding: I started with 400+, and the `gem clean` command fixed the majority. The remainder (~30) are all related to this `git_tracker` gem being missing. I'd _like_ to start from a green bar, but I think I can add specs an implement a change to the Thor CLI without that. If these all pass in CI, I'm willing to work with a small set of known fails and check my PR against CI when the time comes - more than I'm willing to drain more of your time.

**Comment by segiddins** [comment]
The `git_tracker` issue is due to your `git` binary actually being a rubygem executable, which predictably causes problems

**Comment by nyarly** [comment]
That doesn't line up with what I'm seeing here:

which git #=> /usr/bin/git
less git #=> <ELF output>

Failures look like:

```
/usr/lib/ruby/site_ruby/1.9.1/rubygems/dependency.rb:315:in `to_specs': Could not find 'git_tracker' (>= 0) among 0 total gem(s) (Gem::LoadError)
Checked in 'GEM_PATH=/home/judson/ruby/foreign_projects/bundler/tmp/gems/system', execute `gem env` for more information
        from /usr/lib/ruby/site_ruby/1.9.1/rubygems/dependency.rb:324:in `to_spec'
        from /usr/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_gem.rb:64:in `gem'
        from /home/judson/.gem/ruby/2.0.0/bin/git-tracker:22:in `<main>'
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
warning: You appear to have cloned an empty repository.
fatal: Needed a single revision
The git source /home/judson/ruby/foreign_projects/bundler/tmp/libs/foo-1.0 is not yet checked out. Please run `bundle install` before trying to start your application
```

**Comment by nyarly** [comment]
Finally hunted this down: at some point it appears that a prepare-commit-msg hook file was installed in my system templates directory. Not sure how this happened - probably git-tracker itself is the most likely suspect.

The solution for me was to remove that file - I've got a per-user templates directory, so it wasn't an issue for normal git usage.

I'm not sure if this warrants any further action than to close the issue, and leave my travails for some future troubled soul to discover.
