### ISSUE TITLE
Confusing error message when local gems have invalid gemspec

### ISSUE THREAD

**Issue by dbslone** [bundler/bundler#4248]
First I want to say :+1: for enforcing gemspecs to be valid before bundler will install the gems.

I just upgraded to ruby 2.3.0 and installed the latest version of bundler and when I ran `bundle install` I received the following message:

```
$ bundle install
The gemspec at /lib/rails_admin_devise_invitable/rails_admin_devise_invitable.gemspec is not valid. The validation error was '"FIXME" or "TODO" is not an author'
The gemspec at /lib/rails_admin_devise_invitable/rails_admin_devise_invitable.gemspec is not valid. The validation error was '"FIXME" or "TODO" is not an author'
Fetching gem metadata from https://rubygems.org/.......
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Could not find gem 'rails_admin_devise_invitable' in source at `lib/rails_admin_devise_invitable`.
Source does not contain any versions of 'rails_admin_devise_invitable'
```

The error message is confusing because I thought it was unable to find the gem once I corrected the errors in the gemspec everything worked as expected.

My suggestion would be that the error message should inform the user to correct the specified gemspec file(s) then run bundle install again.

**Comment by TimMoore** [comment]
Thanks for the report, @dbslone. Are you able to share the failing project with us to help reproduce the issue? Is it open source?

**Comment by dbslone** [comment]
@TimMoore Unfortunately the app isn't open source but I should have some time over the weekend to create new rails app that reproduces the error that I can share

**Comment by RochesterinNYC** [comment]
@dbslone what would you have expected error message wise ? Something along the lines of:

```
$ bundle install

Gem::InvalidSpecificationException: The gemspec at /lib/rails_admin_devise_invitable/rails_admin_devise_invitable.gemspec is not valid. Please fix the gemspec.
```

**Comment by dbslone** [comment]
@RochesterinNYC Yeah I think that error message is clearer and would inform users that once the gemspec is corrected operations should proceed as expected.

**Comment by segiddins** [comment]
Closed by https://github.com/bundler/bundler/pull/4250.
