### ISSUE TITLE
bundle exec's "with_original_env" doesn't preserve PATH

### ISSUE THREAD

**Issue by njam** [bundler/bundler#4251]
I'm looking for a way to restore the original environment PATH inside a ruby script executed with `bundle exec <script>`. I understand `Bundler.with_original_env` ( and `Bundler.with_clean_env`)  should provide this functionality.

It seems to me though that the **PATH is not correctly preserved when running `bundle exec`**, because `lib/bundler.rb` is loaded *twice* during such an execution (once when running the `bundle` binary, and once when executing the script with `Kernel.exec('<script>')` in `cli/exec.rb`).
Therefore `Bundler.ORIGINAL_ENV` is overwritten twice, and can't be restored to the original value.

To illustrate I've added a spec about this here (which fails): https://github.com/njam/bundler/commit/8871e4166375ee9a679b5f74f099ee88a4c3d1b8

I think the only way to pass along the original environment to the sub process is by setting yet another environment variable. Maybe bundler should store the environment serialized in `BUNDLE_ORIGINAL_ENV`, and then load it from there if present?

Is this interpretation correct, or am I using the code wrong?

**Comment by njam** [comment]
In https://github.com/bundler/bundler/issues/2369 I can find:
> when you use `bundle exec ruby`, the "original" environment is the one created by `bundle exec`.

On the other hand the [`bundle exec` docu](http://bundler.io/v1.11/man/bundle-exec.1.html) says:
> Any subshells created inside the block will be given the environment present before Bundler was activated.

There's an implementation to pass along the original environment in another environment variable `_BUNDLER_ORIGINAL_ENV` in https://github.com/bundler/bundler/pull/2390. But there were problems about the encoding to use (json not available?). Is this still the case?

**Comment by indirect** [comment]
Thanks for the report! It looks like this is a bug. The intention is that `PATH` be restored to what it was when `bundle exec` was called.

**Comment by segiddins** [comment]
@indirect isn't this what `BUNDLER_ORIG_MANPATH` does for `man`? If so, we could probably use that logic for `PATH` as well

**Comment by segiddins** [comment]
@njam can you check if https://github.com/bundler/bundler/issues/4256 fixes things for you?

**Comment by njam** [comment]
Unfortunately not completely.
It looks good to store the original `PATH` In `_ORIGINAL_PATH`, but then I think we need to somehow restore it in `with_original_env`? The original path never makes it into  `ORIGINAL_ENV`.

You can check by running this spec: https://github.com/njam/bundler/commit/8871e4166375ee9a679b5f74f099ee88a4c3d1b8

**Comment by indirect** [comment]
@segiddins sounds like we maybe want to pull on that spec?

**Comment by segiddins** [comment]
Go ahead @indirect
