### ISSUE TITLE
Gemfile.lock curroption detection fails in multi-dependency case

### ISSUE THREAD

**Issue by AlexRiedler** [bundler/bundler#4270]
## Description

This may be more of a feature than a bug; please give forgiveness.

If you lose a line in a Gemfile.lock of a dependency, the load order of gems might be incorrect and result in a failure when Bundler.require()

I provide the following minimal example:
## Example

note before reading, ethon actually depends on `ffi (>= 1.3.0)` but the line has been removed in the Gemfile.lock (which might happen during a bad git merge for instance).

```
Gemfile

    source 'http://rubygems.org'

    gem 'typhoeus', '0.6.9'
    gem 'spoon', '0.0.4'

Gemfile.lock

    GEM
      remote: http://rubygems.org/
      specs:
        ethon (0.8.1)
        ffi (1.9.10)
        spoon (0.0.4)
          ffi
        typhoeus (0.6.9)
          ethon (>= 0.7.1)

    PLATFORMS
      ruby

    DEPENDENCIES
      spoon (= 0.0.4)
      typhoeus (= 0.6.9)

    BUNDLED WITH
       1.11.2
```

```
bundle exec irb
requirb(main):001:0> require 'bundler'
=> false
irb(main):002:0> Bundler.require(:default)
LoadError: cannot load such file -- ffi
        from /Users/ariedler/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ethon-0.8.1/lib/ethon.rb:2:in `require'
        from /Users/ariedler/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ethon-0.8.1/lib/ethon.rb:2:in `<top (required)>'
        from /Users/ariedler/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/typhoeus-0.6.9/lib/typhoeus.rb:2:in `require'
        from /Users/ariedler/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/typhoeus-0.6.9/lib/typhoeus.rb:2:in `<top (required)>'
        from /Users/ariedler/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:77:in `require'
        from /Users/ariedler/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:77:in `block (2 levels) in require'
        from /Users/ariedler/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `each'
        from /Users/ariedler/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `block in require'
        from /Users/ariedler/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `each'
        from /Users/ariedler/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `require'
        from /Users/ariedler/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler.rb:99:in `require'
        from (irb):2
        from /Users/ariedler/.rbenv/versions/2.2.3/bin/irb:11:in `<main>'
```
## Expected Behaviour

on `bundle install` --> `Your Gemfile.lock is corrupt. ....`

**Comment by segiddins** [comment]
detecting its corrupt would require loading all of the specs, though :(

**Comment by indirect** [comment]
I think it is (maybe) reasonable to validate the Gemfile during install/update, when we have to load the gemspecs anyway, although it does not seem good to validate it at any other time.

**Comment by segiddins** [comment]
Ah this is during bundler.require though, so maybe?

**Comment by CirrusThink** [comment]
We have been using 1.10.6 for capistrano deployments and took about 2 hours today to figure out that we we had updated a deployment to bundler 1.11.x and could not deploy because of Your Gemfile.lock is corrupt. .... Problem is that we puplessy removed memcached form a dependency because we cant get the gem to install on Solaris 11.  .. is there an option to use bundler 1.11.x and stil manipulate the dependencies ? something like BTW dont use this particular dependency maybe in the gemfile ?

**Comment by indirect** [comment]
@CirrusThink yes, you can use `install_if`. Please open a new ticket if you're having a new issue.

**Comment by LynnCo** [comment]
To clarify, this is a feature request for validating errors in lockfiles

**Comment by segiddins** [comment]
Output from bundler 1.15:

```
Fetching gem metadata from http://rubygems.org/.........
Fetching version metadata from http://rubygems.org/.
Fetching ethon 0.8.1
Using ffi 1.9.10
Using bundler 1.15.1
Downloading ethon-0.8.1 revealed dependencies not in the API or the lockfile (ffi (>= 1.3.0)).
Either installing with `--full-index` or running `bundle update ethon` should fix the problem.
```

And indeed `bundle update ethon` fixes the issue.
