### ISSUE TITLE
bundle outdated does not work together with bundle install --deployment

### ISSUE THREAD

**Issue by Aqualon** [bundler/bundler#4287]
If you run ```bundle install --deployment``` a call of ```bundle outdated``` afterwards will just show that there are no outdated gems.

I created a new rails app and ran bundle outdated

```
$ bundle outdated
Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies.....

Outdated gems included in the bundle:
  * rails (newest 4.2.5.1, installed 4.2.5, requested = 4.2.5) in group "default"
  * web-console (newest 3.1.1, installed 2.3.0, requested ~> 2.0) in group "development"
  * actionmailer (newest 4.2.5.1, installed 4.2.5)
  * actionpack (newest 4.2.5.1, installed 4.2.5)
  * actionview (newest 4.2.5.1, installed 4.2.5)
  * activejob (newest 4.2.5.1, installed 4.2.5)
  * activemodel (newest 4.2.5.1, installed 4.2.5)
  * activerecord (newest 4.2.5.1, installed 4.2.5)
  * activesupport (newest 4.2.5.1, installed 4.2.5)
  * arel (newest 7.0.0, installed 6.0.3)
  * mime-types (newest 3.0, installed 2.99)
  * mini_portile2 (newest 2.1.0, installed 2.0.0)
  * railties (newest 4.2.5.1, installed 4.2.5)
```

So there are outdated gems. After this I ran ```bundle install --deployment``` and get this for bundle outdated:
```
$ bundle outdated
Fetching gem metadata from https://rubygems.org/.
Fetching version metadata from https://rubygems.org/.

Bundle up to date!
```

Is this expected behavior or a bug? If it's expected, maybe the output should give you a hint?

**Comment by RochesterinNYC** [comment]
I believe this is expected behavior when using the `--deployment` flag. It's stated in the docs (http://bundler.io/bundle_install.html) that using `--deployment` induces the following installation detail:

`Require an up-to-date Gemfile.lock (equivalent to --frozen)`

**Comment by Aqualon** [comment]
Agreed, it makes sense, that bundler can't update any gems, if `Gemfile.lock` is frozen. For me it's still surprising behavior that `bundle outdated` doesn't give a hint about this and just says everything is up-to-date (maybe caused a bit by not having called `--deployment` on purpose, but by testing a script for Jenkins locally, so I didn't think about this)

**Comment by RochesterinNYC** [comment]
To provide some more context, the reason that the second `bundle outdated` shows no gems to update despite the lack of `Gemfile.lock` update is that `bundle install --deployment` changes your `.bundle/config` to the following:

```yaml
---
BUNDLE_FROZEN: '1'
BUNDLE_PATH: vendor/bundle
BUNDLE_DISABLE_SHARED_GEMS: '1'
```

and installs the gems into `vendor/bundle` by default (instead of to your system). And from then on, using `bundle` in that app directory interacts with the gems installed into your `vendor/bundle` directory rather than your system gems.

What kind of clarification message do you think would be helpful?

Something like?
```
$ bundle outdated
Fetching gem metadata from https://rubygems.org/.
Fetching version metadata from https://rubygems.org/.

Gemfile.lock is currently frozen.
Bundle up to date!
```

**Comment by Aqualon** [comment]
Maybe something similar to what bundle update tells you in this case:

```
You are trying to check outdated gems in deployment mode. Run `bundle outdated` elsewhere.

If this is a development machine, remove the Gemfile freeze 
by running `bundle install --no-deployment`.
```
