### ISSUE TITLE
error with gemserver password with special char: `URI::InvalidComponentError: bad component(expected user component)`

### ISSUE THREAD

**Issue by pmahoney** [bundler/bundler#4288]
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I have a gemserver that requires HTTP basic auth. It's not `rubygems.org`, of course, but I'm using it here to reproduce the bug. My password has special characters, which cause the exception below.

  Note: I can work around the issue by URL encoding my password, e.g. `ruby -r cgi -e 'p CGI.escape "pass{word"'`

  With the Gemfile:

```
source 'https://rubygems.org/'
gem 'bundler'
```
  I ran the command `BUNDLE_RUBYGEMS__ORG="user:pass{word" bundle` with the Gemfile:

- What did you expect to happen?

  I expected Bundler to use the given credentials when connecting to the gemserver.

- What happened instead?

  Instead, what actually happened was bundler failed with the following error:

Error details

    URI::InvalidComponentError: bad component(expected user component): pass{word
      $RUBY_HOME/lib/ruby/2.1.0/uri/generic.rb:440:in `check_password'
      $RUBY_HOME/lib/ruby/2.1.0/uri/generic.rb:390:in `check_userinfo'
      $RUBY_HOME/lib/ruby/2.1.0/uri/generic.rb:455:in `userinfo='
      $GEM_HOME/gems/bundler-1.11.2/lib/bundler/source/rubygems/remote.rb:22:in `apply_auth'
      $GEM_HOME/gems/bundler-1.11.2/lib/bundler/source/rubygems/remote.rb:13:in `initialize'
      $GEM_HOME/gems/bundler-1.11.2/lib/bundler/source/rubygems.rb:230:in `new'
      $GEM_HOME/gems/bundler-1.11.2/lib/bundler/source/rubygems.rb:230:in `block in fetchers'
      $GEM_HOME/gems/bundler-1.11.2/lib/bundler/source/rubygems.rb:229:in `map'
      $GEM_HOME/gems/bundler-1.11.2/lib/bundler/source/rubygems.rb:229:in `fetchers'
      $GEM_HOME/gems/bundler-1.11.2/lib/bundler/source/rubygems.rb:335:in `block in remote_specs'
      $GEM_HOME/gems/bundler-1.11.2/lib/bundler/index.rb:9:in `build'
      $GEM_HOME/gems/bundler-1.11.2/lib/bundler/source/rubygems.rb:334:in `remote_specs'
      $GEM_HOME/gems/bundler-1.11.2/lib/bundler/source/rubygems.rb:81:in `specs'
      $GEM_HOME/gems/bundler-1.11.2/lib/bundler/definition.rb:209:in `block (2 levels) in index'
      $GEM_HOME/gems/bundler-1.11.2/lib/bundler/definition.rb:207:in `each'
      $GEM_HOME/gems/bundler-1.11.2/lib/bundler/definition.rb:207:in `block in index'
      $GEM_HOME/gems/bundler-1.11.2/lib/bundler/index.rb:9:in `build'
      $GEM_HOME/gems/bundler-1.11.2/lib/bundler/definition.rb:204:in `index'
      $GEM_HOME/gems/bundler-1.11.2/lib/bundler/definition.rb:198:in `resolve'
      $GEM_HOME/gems/bundler-1.11.2/lib/bundler/definition.rb:137:in `specs'
      $GEM_HOME/gems/bundler-1.11.2/lib/bundler/definition.rb:126:in `resolve_remotely!'
      $GEM_HOME/gems/bundler-1.11.2/lib/bundler/installer.rb:194:in `resolve_if_need'
      $GEM_HOME/gems/bundler-1.11.2/lib/bundler/installer.rb:69:in `run'
      $GEM_HOME/gems/bundler-1.11.2/lib/bundler/installer.rb:21:in `install'
      $GEM_HOME/gems/bundler-1.11.2/lib/bundler/cli/install.rb:105:in `run'
      $GEM_HOME/gems/bundler-1.11.2/lib/bundler/cli.rb:172:in `install'
      $GEM_HOME/gems/bundler-1.11.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      $GEM_HOME/gems/bundler-1.11.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      $GEM_HOME/gems/bundler-1.11.2/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      $GEM_HOME/gems/bundler-1.11.2/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      $GEM_HOME/gems/bundler-1.11.2/lib/bundler/cli.rb:10:in `start'
      $GEM_HOME/gems/bundler-1.11.2/exe/bundle:19:in `block in <top (required)>'
      $GEM_HOME/gems/bundler-1.11.2/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
      $GEM_HOME/gems/bundler-1.11.2/exe/bundle:17:in `<top (required)>'
      $GEM_HOME/bin/bundle:23:in `load'
      $GEM_HOME/bin/bundle:23:in `<main>'

Environment

    Bundler   1.11.2
    Rubygems  2.2.2
    Ruby      2.1.1p76 (2014-02-24 revision 0) [x86_64-darwin15.0]
    GEM_HOME  $GEM_HOME
    GEM_PATH  $RUBY_HOME/lib/ruby/gems/2.1.1
    Git       2.7.0

Bundler settings

    rubygems.org
      Set via BUNDLE_RUBYGEMS__ORG: "user:pass{word"
--- TEMPLATE END ----------------------------------------------------------------

**Comment by segiddins** [comment]
Hmmm, what happens if you manually encode the credentials before putting them in the env var?

**Comment by pmahoney** [comment]
@segiddins Sorry if my note wasn't clear. Manually encoding them before putting them in the env var is a successful workaround.

**Comment by segiddins** [comment]
I'm not sure if that should be the answer then, since you could have a `:` in the username or password and bundler would then mis-encode

**Comment by indirect** [comment]
@segiddins we could unescape colons after CGI escaping the value? ...then we need to worry about double-escapes, and everything is terrible. :/

**Comment by segiddins** [comment]
I'm going to say all we ought to do here is provide a better error message when applying auth.

**Comment by indirect** [comment]
Sold. Let's specifically call out that usernames and passwords need to already be CGI escaped.

**Comment by RochesterinNYC** [comment]
I can implement that tomorrow evening if no one wants to knock it out before then.
