### ISSUE TITLE
bundle gem creates unnecessary double-quoted strings

### ISSUE THREAD

**Issue by chrisjones-tripletri** [bundler/bundler#4289]
These strings, like VERSION = "0.1.0" fail validators like rubocop.  It seems like single quoted strings would just as well, and anyone using rubocop would have an easier time using bundle gem.   If this seems like a bug worth fixing, I would be happy to take a shot at fixing it myself, but I did not want to do that until a fix was approved by more knowledgable contributors.

**Comment by segiddins** [comment]
Nope, there are other issues / PRs about this. `bundlr gem` creates a gem that complies with bundlers own style guide.
