### ISSUE TITLE
cannot spawn processes which use a different Gemfile than the spawning process.

### ISSUE THREAD

**Issue by bhaibel** [bundler/bundler#4296]
So, this is a weird one and I'm sorry. Three parts; the first is just unexpected behavior that might be a wontfix. The second and third are crashes though.

**Background**

I'm writing a ruby microapp (App A) that needs to

1. check out a git repository containing a Rails app (App B) to a tempdir
2. run a command in the context of App B's rails runner.

The relevant code looks something like this:

```ruby
system("git clone #{repo_path} #{target_dir}"
system("bundle install", chdir: target_dir)
system("bundle exec rails runner #{command}", chdir: target_dir)
```

**Thing One: Unexpected Behavior**

When this code is run from App A in the context of `bundle exec`, like so:

```
~/bhaibel/code/app_a > bundle exec rake problem_task
```

the "inner" bundler calls use App A's bundle despite being called from a directory containing App B. The same applies if I replace the `system` calls with backticks, `Open3.capture2e`, `Process.spawn`, whatever. 

**Thing Two: A Crash**

I tried changing the install command to:

```ruby
system("bundle install --gemfile Gemfile", chdir: target_dir)
```

in order to force the inner bundler calls to use App B's Gemfile.

When I run this, I get the following crash report:

Error details

    RuntimeError: Specs already loaded
      /Users/bhaibel/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/definition.rb:123:in `resolve_remotely!'
      /Users/bhaibel/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/installer.rb:194:in `resolve_if_need'
      /Users/bhaibel/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/installer.rb:69:in `run'
      /Users/bhaibel/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/installer.rb:21:in `install'
      /usr/local/Cellar/rbenv/1.0.0/rbenv.d/exec/gem-rehash/rubygems_plugin.rb:27:in `install'
      /Users/bhaibel/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/cli/install.rb:105:in `run'
      /Users/bhaibel/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/cli.rb:172:in `install'
      /Users/bhaibel/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /Users/bhaibel/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /Users/bhaibel/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /Users/bhaibel/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /Users/bhaibel/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/cli.rb:10:in `start'
      /Users/bhaibel/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/exe/bundle:19:in `block in <top (required)>'
      /Users/bhaibel/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
      /Users/bhaibel/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/exe/bundle:17:in `<top (required)>'
      /Users/bhaibel/.rbenv/versions/2.2.3/bin/bundle:23:in `load'
      /Users/bhaibel/.rbenv/versions/2.2.3/bin/bundle:23:in `<main>'

Environment

    Bundler   1.11.2
    Rubygems  2.4.5.1
    Ruby      2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin14]
    GEM_HOME  /Users/bhaibel/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0
    GEM_PATH  /Users/bhaibel/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0:/Users/bhaibel/.gem/ruby/2.2.0
    Git       2.7.1

Bundler settings

    bin_path
      Set via BUNDLE_BIN_PATH: "/Users/bhaibel/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/exe/bundle"
    gemfile
      Set via BUNDLE_GEMFILE: "/private/var/folders/48/bsfm3htx7858t1yn67x05d080000gn/T/d20160212-814-axmh3k/target/Gemfile"

**Thing Three: Bonus Weird Crash!**

At one point while fussing at this, I had code that looked like so:

```ruby
pid = Process.spawn('bundle install', chdir: target_dir)
wait pid
```

Since the appropriate method is `Process.wait`, not `wait`, this led to my parent ruby process throwing a `RuntimeError` like one would expect. HOWEVER! The zombie bundle install process left behind carried on and crashed in a fun way:

Error details

    Errno::ENOENT: No such file or directory - getcwd
      /Users/bhaibel/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/vendor/thor/lib/thor/actions.rb:109:in `expand_path'
      /Users/bhaibel/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/vendor/thor/lib/thor/actions.rb:109:in `destination_root='
      /Users/bhaibel/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/vendor/thor/lib/thor/actions.rb:85:in `initialize'
      /Users/bhaibel/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/cli.rb:17:in `initialize'
      /Users/bhaibel/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/vendor/thor/lib/thor.rb:355:in `new'
      /Users/bhaibel/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/vendor/thor/lib/thor.rb:355:in `dispatch'
      /Users/bhaibel/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /Users/bhaibel/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/cli.rb:10:in `start'
      /Users/bhaibel/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/exe/bundle:19:in `block in <top (required)>'
      /Users/bhaibel/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
      /Users/bhaibel/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/exe/bundle:17:in `<top (required)>'
      /Users/bhaibel/.rbenv/versions/2.2.3/bin/bundle:23:in `load'
      /Users/bhaibel/.rbenv/versions/2.2.3/bin/bundle:23:in `<main>'

Environment

    Bundler   1.11.2
    Rubygems  2.4.5.1
    Ruby      2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin14]
    GEM_HOME  /Users/bhaibel/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0
    GEM_PATH  /Users/bhaibel/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0:/Users/bhaibel/.gem/ruby/2.2.0
    Git       2.7.1

Bundler settings

    bin_path
      Set via BUNDLE_BIN_PATH: "/Users/bhaibel/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/exe/bundle"
    gemfile
      Set via BUNDLE_GEMFILE: "/Users/bhaibel/code/app_a/Gemfile"

**Comment by segiddins** [comment]
`Bundler.with_clean_env` is what you want
