### ISSUE TITLE
keep getting error when installing

### ISSUE THREAD

**Issue by chuckwilliams10** [bundler/bundler#4300]
When running the bundle install..I keep getting this error:
NoMethodError: undefined method 'spec' for nil:NilClass
An error occurred while installing datetimepicker-rails (4.7.16), and Bundler can't continue.

I have checked my Gem file..it has this

gem 'datetimepicker-rails', github: 'zpaulovics/datetimepicker-rails', branch: 'master', submodules: true

Any Ideas....thanks a ton.

**Comment by indirect** [comment]
Thanks for reporting this! Please follow [ISSUES](https://github.com/bundler/bundler/blob/master/ISSUES.md) so we can try to figure out what's going on.

**Comment by chuckwilliams10** [comment]
I looked at the info issues area.

here is my env information:
[BundlerENV.pdf](https://github.com/bundler/bundler/files/130016/BundlerENV.pdf)

I am just trying to install gem 'datetimepicker-rails', github: 'zpaulovics/datetimepicker-rails', branch: 'master', submodules: true

via the bundle install command....any help would be great...

**Comment by indirect** [comment]
Your Bundler version is over a year old. Please upgrade by running `gem install bundler` and then try again.

**Comment by chuckwilliams10** [comment]
Thanks a ton...
