### ISSUE TITLE
Error trying to install for wpscan (CentOS 6)

### ISSUE THREAD

**Issue by Cadmos** [bundler/bundler#4316]
Linux 2.6.32-042stab108.6 x86_64

--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `/usr/bin/bundle install --without test development`

  I expected Bundler to be installed for wpscan

**sudo gem install bundler && bundle install --without test development**

Fetching: bundler-1.11.2.gem (100%)
Successfully installed bundler-1.11.2
1 gem installed
Installing ri documentation for bundler-1.11.2...
Installing RDoc documentation for bundler-1.11.2...
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your bundle as root will break this application for all non-root users
on this machine.

Error details

    TypeError: Cipher is not a module
      /usr/lib/ruby/1.8/openssl/cipher.rb:22
      /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
      /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `require'
      /usr/lib/ruby/1.8/openssl.rb:20
      /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
      /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `require'
      /usr/lib/ruby/gems/1.8/gems/bundler-1.11.2/lib/bundler/vendored_persistent.rb:4
      /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
      /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `require'
      /usr/lib/ruby/gems/1.8/gems/bundler-1.11.2/lib/bundler/fetcher.rb:1
      /usr/lib/ruby/gems/1.8/gems/bundler-1.11.2/lib/bundler/cli/install.rb:96:in `run'
      /usr/lib/ruby/gems/1.8/gems/bundler-1.11.2/lib/bundler/cli.rb:172:in `install'
      /usr/lib/ruby/gems/1.8/gems/bundler-1.11.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `__send__'
      /usr/lib/ruby/gems/1.8/gems/bundler-1.11.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /usr/lib/ruby/gems/1.8/gems/bundler-1.11.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /usr/lib/ruby/gems/1.8/gems/bundler-1.11.2/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /usr/lib/ruby/gems/1.8/gems/bundler-1.11.2/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /usr/lib/ruby/gems/1.8/gems/bundler-1.11.2/lib/bundler/cli.rb:10:in `start'
      /usr/lib/ruby/gems/1.8/gems/bundler-1.11.2/exe/bundle:19
      /usr/lib/ruby/gems/1.8/gems/bundler-1.11.2/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
      /usr/lib/ruby/gems/1.8/gems/bundler-1.11.2/exe/bundle:17
      /usr/bin/bundle:19:in `load'
      /usr/bin/bundle:19

Environment

    Bundler   1.11.2
    Rubygems  1.7.2
    Ruby      1.8.7 (2011-06-30 patchlevel 352) [x86_64-linux]
    Git       1.7.12.4

Bundler settings

    without
      Set for your local app (/var/wpscan/.bundle/config): "test:development"
--- TEMPLATE END ----------------------------------------------------------------

**Comment by allenzhao** [comment]
Does this help with your problem? Seems a problem with ruby itself.
http://serverfault.com/questions/114725/openssl-support-for-ruby-cipher-is-not-a-module-typeerror

**Comment by segiddins** [comment]
This is not an issue with bundler -- its an issue with your Ruby / OpenSSL installation.
