### ISSUE TITLE
Handle ruby patch level being -1

### ISSUE THREAD

**Issue by segiddins** [bundler/bundler#4317]
This is what happens on ruby-head, for instance. So `Bundler::RubyVersion` needs to handle it

**Comment by segiddins** [comment]
@RochesterinNYC any interest in looking into this one?

**Comment by RochesterinNYC** [comment]
Sure! I'd need a bit more context on what the issue exactly is though. Given a ruby version `v##.##.z`, what is the format for `z` that `Bundler::RubyVersion` can't handle?

**Comment by segiddins** [comment]
No, not the patch part of the version. The `RUBY_PATCHLEVEL` constant is -1

**Comment by RochesterinNYC** [comment]
Ah gotcha, thanks for the clarification.
