### ISSUE TITLE
pass error messages on to user

### ISSUE THREAD

**Issue by rickthepick** [bundler/bundler#4319]
Bundler gave this error message:

Bundler::GemRequireError: There was an error while trying to load the gem 'thrift'.
/Users/rkissh/.rvm/gems/ruby-1.9.3-p547@sappy/gems/bundler-1.11.2/lib/bundler/runtime.rb:81:in `rescue in block (2 levels) in require'
/Users/rkissh/.rvm/gems/ruby-1.9.3-p547@sappy/gems/bundler-1.11.2/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
/Users/rkissh/.rvm/gems/ruby-1.9.3-p547@sappy/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `each'
/Users/rkissh/.rvm/gems/ruby-1.9.3-p547@sappy/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `block in require'
/Users/rkissh/.rvm/gems/ruby-1.9.3-p547@sappy/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `each'
/Users/rkissh/.rvm/gems/ruby-1.9.3-p547@sappy/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `require'
/Users/rkissh/.rvm/gems/ruby-1.9.3-p547@sappy/gems/bundler-1.11.2/lib/bundler.rb:99:in `require'
/Users/rkissh/opx/sappy/config/application.rb:11:in `<top (required)>'
/Users/rkissh/opx/sappy/Rakefile:4:in `require'
/Users/rkissh/opx/sappy/Rakefile:4:in `<top (required)>'
./rake:17:in `<main>'

Thinking that bundler might know more than it was telling, I looked at runtime.rb:81 and saw that was the case.  I changed that line to
"There was an error while trying to load the gem '#{file}': #{e.message}"
and tried again

Bundler::GemRequireError: There was an error while trying to load the gem 'thrift': Failed to load thrift binary for your platform (x86_64-darwin14.1.0/1.9.3) Run ./compile_native_library.rb
/Users/rkissh/.rvm/gems/ruby-1.9.3-p547@sappy/gems/bundler-1.11.2/lib/bundler/runtime.rb:81:in `rescue in block (2 levels) in require'...

There we go!

**Comment by segiddins** [comment]
This will be fixed by https://github.com/bundler/bundler/pull/4284, which is just missing test coverage

**Comment by LynnCo** [comment]
The PR segiddins mentioned has been merged, so I assumed this is resolved. Let us know if it's not!
