### ISSUE TITLE
Allow user added gems in an UserGemfile

### ISSUE THREAD

**Issue by phortx** [bundler/bundler#4327]
From my [StackOverflow Question](http://stackoverflow.com/questions/35647167/bundler-allow-user-added-gems-in-an-usergemfile/35648268):

> I'm developing a ruby/rails application which should be highly extensible by adding plugins. A plugin is - obviously - a gem, which follows specific roules and contains library code, a rails engine with assets, routes, controllers, views and whatever. Additionally there wille be some kind of API which allows the plugin developer to register custom entries to abstract concepts of the app like adding cronjobs (theres some kind of cron in the main system), adding commands to the CLI and so on.
> 
> There will be some 'builtin' plugins containted in the Gemfile shipped with the app due they're part of the app and always activated. And there will be a pool of community written gems which are optional.
> 
> Now I'm searching for a possibility to let the user, who installs the app on his machine, addional gems (containing plugins) to the app.
> 
> The simplest (but not best) solution would be to say "Just add the plugin gems you want to the Gemfile before running `bundle install`)". But if there comes an update of the app, the Gemfile would be potentially conflicting and either be resetted or the user have to resolve those conflicts. That's something I don't want actually.
> 
> A nicer way would be to say "Hey, here's a UserGemfile, just add the plugin gems you want to that file and run `bundle install`". That `UserGemfile` would be listed in the `.gitignore` and everything would be nice.
> 
> Unfortunately it seems like bundler doesn't support something like that.
> 
> Do you have any advice how to tackle that issue?

**Comment by segiddins** [comment]
There's an issue on bundler/bundler-features about this. My off-the-cuff reccomendation is to make your app a gem, that way users can include it and whatever else they want in their Gemfile.

**Comment by RochesterinNYC** [comment]
bundler/bundler-features#86
