### ISSUE TITLE
Net::HTTPServerException 407 "Proxy Authorization Required"

### ISSUE THREAD

**Issue by kbsivacse** [bundler/bundler#4328]
Getting below error even after setting proxy authentication using the below environment variable

export http_proxy=http://name:password@proxy_server:port/
export https_proxy=http_proxy

$ bundle install --deployment --without development test postgres aws --retry 1
Fetching source index from https://rubygems.org/
Retrying fetcher due to error (2/2): Net::HTTPServerException 407 "Proxy Authorization Required"

Environment

    Bundler   1.11.2
    Rubygems  2.0.3
    Ruby      2.0.0p247 (2013-06-27 revision 41674) [x86_64-linux]
    GEM_HOME  /home/git/gitlab/vendor/bundle/ruby/2.0.0
    GEM_PATH
    Git       1.9.1

Bundler settings

    retry
      Set for your local app (/home/git/gitlab/.bundle/config): 1
    frozen
      Set for your local app (/home/git/gitlab/.bundle/config): "1"
    path
      Set for your local app (/home/git/gitlab/.bundle/config): "vendor/bundle"
    without
      Set for your local app (/home/git/gitlab/.bundle/config): "development:test:postgres:aws:development-1.1.3.gem"
    disable_shared_gems
      Set for your local app (/home/git/gitlab/.bundle/config): "1"

**Comment by RochesterinNYC** [comment]
Can you try the following: rubygems/rubygems#1068

**Comment by allenzhao** [comment]
Instead of setting proxy username within `http_proxy`, you should probably set them separately as follows:

`export http_proxy_user=username` and `export http_proxy_pass=password`

and keep only the ip and port in `http_proxy`. If you want to use https rather than http, just change http_proxy_user to https_proxy_user

**Comment by kbsivacse** [comment]
Thanks for your quick reply.

 I have tried the below things (with small as well as in Caps separately), but no luck

export http_proxy=<host>:<port>
export http_proxy_user=<username>
export http_proxy_pass=<password>
export https_proxy=$http_proxy
export https_proxy_user=<username>
export https_proxy_pass=<password>

export HTTP_PROXY=<host>:<port>
export HTTP_PROXY_USER=<username>
export HTTP_PROXY_PASS=<password>
export HTTPS_PROXY=$http_proxy
export HTTPS_PROXY_USER=<username>
export HTTPS_PROXY_PASS=<password>

Still getting 
Net::HTTPServerException: 407 "Proxy Authorization Required"

Please confirm if there any code change to be done to fix this in .rb files

**Comment by RochesterinNYC** [comment]
Can you verify that your credentials are correct?

Additionally, can you try upgrading to the latest version of Rubygems (`v2.6.1`)?

**Comment by LynnCo** [comment]
ping @kbsivacse

> Can you verify that your credentials are correct?
> Additionally, can you try upgrading to the latest version of Rubygems (`v2.6.1`)?

**Comment by LynnCo** [comment]
Closing due to lack of user response. @kbsivacse feel free to follow up with us though

**Comment by stobias123** [comment]
I'm having this same issue, I have verified that my proxy credentials are working.

**Comment by irmpow** [comment]
I have same from some library, which used in my new project
~$ env | grep proxy
http_proxy_user=user
https_proxy_user=user
http_proxy=http://user:pass@ip:port/
ftp_proxy=http://user:pass@ip:port/
all_proxy=socks://ip:port/
socks_proxy=http://user:pass@ip:port/
https_proxy=http://user:pass@ip:port/
no_proxy=localhost,127.0.0.0/8,::1
https_proxy_pass=pass
http_proxy_pass=pass

I relogin to rails console and still
Net::HTTPServerException: 407 "Proxy Authentication Required"

**Comment by lelvisl** [comment]
problem in ruby  - https://bugs.ruby-lang.org/issues/12921
