### ISSUE TITLE
err: Could not retrieve catalog from remote server: Error 500 on SERVER: <!DOCTYPE html

### ISSUE THREAD

**Issue by kosewu** [bundler/bundler#4329]
Please help been battling this for hours
passenger version
/usr/local/share/ruby/gems/2.0/gems/passenger-5.0.26/buildout/apache2/mod_passenger.so

ruby -v 
ruby 2.0.0p648 (2015-12-16) [x86_64-linux]

Went into my /tmp/passenger-error-qBkEHX.html and this is what i get:
  <ul class="corporate_identity">
                                <li class="logo"><a href="https://www.phusionpassenger.com"><span>Phusion Passenger</span></a></li>
                        </ul>
                </div>
                <div id="site_body">
                        <h1 class="error_title">Web application could not be started</h1>
                        <div id="content">
                                <pre>cannot load such file -- puppet/application/master (LoadError)
  /usr/share/ruby/vendor_ruby/2.0/rubygems/core_ext/kernel_require.rb:<wbr>55:<wbr>in `require&apos;
  /usr/share/ruby/vendor_ruby/2.0/rubygems/core_ext/kernel_require.rb:<wbr>55:<wbr>in `require&apos;
  config.ru:<wbr>13:<wbr>in `block in &lt;main&gt;&apos;
  /usr/local/share/ruby/gems/2.0/gems/rack-1.6.4/lib/rack/builder.rb:<wbr>55:<wbr>in `instance_eval&apos;
  /usr/local/share/ruby/gems/2.0/gems/rack-1.6.4/lib/rack/builder.rb:<wbr>55:<wbr>in `initialize&apos;
  config.ru:<wbr>1:<wbr>in `new&apos;
  config.ru:<wbr>1:<wbr>in `&lt;main&gt;&apos;
  /usr/local/share/ruby/gems/2.0/gems/passenger-5.0.26//src/helper-scripts/rack-preloader.rb:<wbr>110:<wbr>in `eval&apos;
  /usr/local/share/ruby/gems/2.0/gems/passenger-5.0.26//src/helper-scripts/rack-preloader.rb:<wbr>110:<wbr>in `preload_app&apos;
  /usr/local/share/ruby/gems/2.0/gems/passenger-5.0.26//src/helper-scripts/rack-preloader.rb:<wbr>156:<wbr>in `&lt;module:<wbr>App&gt;&apos;
  /usr/local/share/ruby/gems/2.0/gems/passenger-5.0.26//src/helper-scripts/rack-preloader.rb:<wbr>30:<wbr>in `&lt;module:<wbr>PhusionPassenger&gt;&apos;
  /usr/local/share/ruby/gems/2.0/gems/passenger-5.0.26//src/helper-scripts/rack-preloader.rb:<wbr>29:<wbr>in `&lt;main&gt;&apos;
</pre>

                                <dl>
                                <dt>Error ID</dt>
                                <dd>c0722536</dd>
                                <dt>Application root</dt>
                                <dd>/usr/share/puppet/rack/puppetmasterd</dd>
                                <dt>Environment (value of RAILS_ENV, RACK_ENV, WSGI_ENV, NODE_ENV and PASSENGER_APP_ENV)</dt>
                                <dd>production</dd>

                                        <dt>Ruby interpreter command</dt>
                                        <dd><pre>/usr/bin/ruby</pre></dd>

                                <dt>User and groups</dt>
                                <dd><pre>uid=<wbr>52(puppet) gid=<wbr>52(puppet) groups=<wbr>52(puppet)
</pre></dd>
                                <dt>Environment variables</dt>
                                <dd><pre>TERM =<wbr> xterm
PATH =<wbr> /sbin:<wbr>/usr/sbin:<wbr>/bin:<wbr>/usr/bin
PWD =<wbr> /usr/share/puppet/rack/puppetmasterd
LANG =<wbr> C
SHLVL =<wbr> 2
_ =<wbr> /usr/sbin/httpd

**Comment by segiddins** [comment]
This doesn't look to be a bundler issue to me -- I'm not seeing anything related to bundler in that stack trace. Is it possible you're just having trouble getting your app set up?
