### ISSUE TITLE
package --all-platforms doesn't match docs

### ISSUE THREAD

**Issue by indirect** [bundler/bundler#4330]
As noted in #4295, the docs for `--all-platforms` say that we'll resolve and cache all platforms, without mentioning that "all" means platforms this Gemfile has previously been resolved on. We should either document exactly how to package onto multiple platforms or fix the option to actually resolve and cache all platforms.

**Comment by segiddins** [comment]
I vote fix the docs and do something separate for "add a foreign platform to my lockfile"

**Comment by indirect** [comment]
I think this option should probably be more specific, maybe `--all-locked-platforms`. I can then imagine something like `lock --all-platforms` meaning that, with `cache --all-platforms` meaning to lock and cache all platforms.

**Comment by LynnCo** [comment]
- [ ] fix the docs (https://github.com/bundler/bundler/pull/4331)
- [ ] update `--all-platforms` (WIP)

**Comment by segiddins** [comment]
I vote for not changing the `--all-platforms` behavior, given my recent changes to platform support and the existence of `lock --add-platform`

**Comment by indirect** [comment]
Agreed. I think we will want `cache` to default to this behavior of caching for all locked platforms in 2.0, with management of which platforms done via `lock`.

**Comment by segiddins** [comment]
👍 In which case we can close this issue
