### ISSUE TITLE
Respect XDG basedir spec for global configuration file

### ISSUE THREAD

**Issue by jasonkarns** [bundler/bundler#4333]
To conform to the XDG basedir spec, bundler's config file ought to be stored at `${XDG_CONFIG_HOME:-$HOME/.config}/bundler/config`

I'm not completely sure what other files are stored under `~/.bundle`, but there are other XDG-defined directories for cache and runtime files, if so needed.

https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by segiddins** [comment]
a) that's a breaking change
b) dumb question but what does XDG stand for, and what makes it the authoritative spec for how command line apps store things on disk?

**Comment by jasonkarns** [comment]
doesn't need to be a breaking change. most tools that have migrated do so by first checking if `~/.my-app` exists and using it if so. If it doesn't exist, then the XDG settings are honored. This way people can opt-in by moving the files themselves (or removing the old ones). Some tools go a step further and migrate the files automatically.

XDG is a group that works on interoperability between *nix systems. The basedir spec is just one aspect of the larger focus of the group. The primary benefit to users is: standardized configurability by users/sysadmins across apps. (And it falls in lines with Apple guidelines on not polluting userspace)

git is the largest project that I'm aware of that conforms. keybase does as well. I've seen many others but can't recall them offhand.

**Comment by gioele** [comment]
The problem is not limited to the configuration file, but also cache files.

Cache files should be stored at

    ${$XDG_CACHE_HOME:-$HOME/.cache}/bundler

instead of `~/.bundler/cache`.

If we need to appeal to authority, we can add Firefox, Thunderbird, Chromium and Inkscape to the list of apps that follow the XDG Basedir spec and do not clutter our lovely $HOMEs. :)

**Comment by LynnCo** [comment]
Doesn't seem like anyone on the team is too excited about implementing this, @jasonkarns or @gioele would you want to work on a PR? (we aren't guaranteed to merge it, but it would help make your case)

**Comment by valeth** [comment]
Is anybody already working on this?

**Comment by segiddins** [comment]
@valeth not at the moment!

**Comment by jasonkarns** [comment]
I can give it a shot soon.

**Comment by colby-swandale** [comment]
This has been added in #6024
