### ISSUE TITLE
Gems in a source block with non-numeric suffix do not meet dependency requirements

### ISSUE THREAD

**Issue by Valarissa** [bundler/bundler#4337]
I've been running into an issue:

```
Bundler could not find compatible versions for gem "newrelic_rpm":
  In snapshot (Gemfile.lock):
    newrelic_rpm (= 3.15.0.314.pre)

  In Gemfile:
    newrelic_rpm (= 3.15.0.314.pre)

    new_relic-rubicon (~> 0.5.0) was resolved to 0.5.0, which depends on
      newrelic_rpm (>= 3.7.0)
```

Basically, when the line `gem 'newrelic_rpm', '3.15.0.314.pre'` is placed within a source block, the above error occurs. When it is moved outside of a source block, it works to satisfy the dependency requirement.

I've fiddled with things a bit, and any version with a non-numeric suffix causes the error (i.e. 3.15.0.314.better still causes the issue, however, 3.15.0.314.0001 does not).

I'm willing to work with people in order to both diagnose this issue and work on a solution, but it does seem to be an issue.

**Comment by Valarissa** [comment]
This is occurring in version 1.11.2 and can be bypassed by running `bundle install --local` if the vendor/cache gem exists.

**Comment by segiddins** [comment]
Can you please share a gemfile we can use to debug? Thanks!

**Comment by Valarissa** [comment]
I can't share the one that I found the issue with as it contains private gems with my work. I will work to make one that can be used to test things for this.

**Comment by Valarissa** [comment]
Discovered via https://github.com/bundler/bundler/issues/2938 that this is all working as intended. Gemspec for the gem that had requirements contained no letter and was therefore correctly ignoring the prerelease gem.
