### ISSUE TITLE
Documentation cop

### ISSUE THREAD

**Issue by indirect** [bundler/bundler#4338]
We'd like to fail the build anytime our documentation contains certain iffy words, like "actually", "obviously", "just", "clearly", and others like that. While we're at it, it would be great to fail on "he" or "she".

The failure messages should hopefully explain a little bit about why and about what can be done instead (eg use "they").

**Comment by sonalkr132** [comment]
Hi @RochesterinNYC I wanted to work on it as well.
I think we can write a [custom cop](https://github.com/bbatsov/rubocop/#custom-cops) like [rspec-cop](https://github.com/nevir/rubocop-rspec) for it (I don't mean we should write a gem but we can most definetly see how they have use rubocop api)

Also, coala's [keyword bear](https://github.com/coala-analyzer/coala-bears/blob/master/bears/general/KeywordBear.py) has some details about going about this.

Let me know what do you think.

**Comment by RochesterinNYC** [comment]
Hi @sonalkr132. Sure, feel free to take this on. I can provide guidance if needed.

Using Rubocop for this might be too much overhead? We already have specs that screen for certain qualities about the actual text in the codebase (ex. using single quotes `'` in the `describe` blocks for specs is screened against). This could be a logical place to add this functionality. Take a look at https://github.com/bundler/bundler/blob/master/spec/quality_spec.rb

**Comment by RochesterinNYC** [comment]
@sonalkr132 please give me a headsup as to whether you're willing to take this on.
