### ISSUE TITLE
Version resolver fails to find matching versions, even though they exist

### ISSUE THREAD

**Issue by colszowka** [bundler/bundler#4340]
Note: I documented the problem [that I had in the respective gem already](https://github.com/guard/guard-rspec/issues/360)

* Ruby 2.3.0
* Bundler 1.11.2 and 1.12.0.pre.2

Here's the isolated problem:

```ruby
# Gemfile
source 'https://rubygems.org'

gem 'rspec-rails', '~> 3.5.0.beta1'
gem 'guard-rspec', '~> 4.6'
```

Running `bundle` gives me:

```
Bundler could not find compatible versions for gem "rspec-core":
  In Gemfile:
    guard-rspec (~> 4.6) was resolved to 4.6.0, which depends on
      rspec (< 4.0, >= 2.99.0) was resolved to 2.99.0, which depends on
        rspec-core (~> 2.99.0)

    rspec-rails (~> 3.5.0.beta1) was resolved to 3.5.0.beta1, which depends on
      rspec-core (= 3.5.0.beta1)
```

Being explicit about the versions I want from `rspec` and `rspec-core` fixes the issue:

```ruby
# Gemfile
source 'https://rubygems.org'

gem 'rspec', '~> 3.5.0.beta1'
gem 'rspec-core', '~> 3.5.0.beta1'
gem 'rspec-rails', '~> 3.5.0.beta1'
gem 'guard-rspec', '~> 4.6'
```

I'm not sure if this is a subtle issue in the dependency graph defined by the family of rspec gems and might need filing there, but I do feel from the error output that the bundler resolver should have been able to figure this out on its own without extra cues in the Gemfile.

**Comment by segiddins** [comment]
So I think I know why this is happening (because of the beta dependency coming from `rspec-rails`, and the lack of a prerelease specifier in the dependency from `guard-rspec`) but I'm not sure whether this is the intended behavior or not

**Comment by Valarissa** [comment]
This seems like an identical issue to the one I was dealing with, you can feel free to close out https://github.com/bundler/bundler/issues/4337 if desired. It appears, based on some poking and prodding, that any gem version with non-numeric characters will have trouble filling dependency requirements.

**Comment by Valarissa** [comment]
Worth noting that this is working as intended, from what can be gleaned here: https://github.com/bundler/bundler/issues/2938
