### ISSUE TITLE
Handle yanked gems in a clear way

### ISSUE THREAD

**Issue by indirect** [bundler/bundler#4344]
Today, when a gem is yanked, we throw the exact same error as when you manually enter a version number into your Gemfile that doesn't actually exist. If a gem is yanked, we have evidence that the version used to exist (in the lockfile), and so we should be able to print an error message that is much more informative, something along the lines of: 

> Your bundle is locked to foo-1.2.3, but that version could not be found in any of the sources listed in your Gemfile. If you haven't changed sources, that means the author of foo-1.2.3 has removed it. You'll need to update your bundle to a different version of foo that hasn't been removed in order to install.

**Comment by allenzhao** [comment]
@RochesterinNYC I'm interested in implement this ;)

**Comment by RochesterinNYC** [comment]
@allenzhao Go ahead, let me know if you need any help/guidance.

**Comment by allenzhao** [comment]
@RochesterinNYC Hi, I think I need a little help on where to look at. Where do you think is the correct location to handle this?

**Comment by RochesterinNYC** [comment]
I think here might be a good place to start looking? https://github.com/bundler/bundler/blob/master/lib/bundler/definition.rb#L339

**Comment by RochesterinNYC** [comment]
@allenzhao A good starting place might be: https://github.com/bundler/bundler/blob/master/lib/bundler/installer.rb#L183

**Comment by sstern6** [comment]
@allenzhao How is the progress on this going?

**Comment by allenzhao** [comment]
@sstern6 Sorry, but I'm still getting familiar with the code base and working on it. It took me more than expected. So if you've already got an idea on how to work on it, please go ahead. If not, I'm trying to deliver one next week ;)

**Comment by sstern6** [comment]
@allenzhao no worries, I am also very new to the code base and having trouble getting all tests to pass.  Just wanted to see status on your progress.  I will go try and help out on other issues.  

However, if you would like to pair or work on this together feel free to email me.

**Comment by RochesterinNYC** [comment]
@allenzhao what's your status on this? This would be a good first issue for you to fix/implement as an official GSoC student.

**Comment by allenzhao** [comment]
@RochesterinNYC I'll start to work more next week. Been busy with school stuff. Sorry for the delay
