### ISSUE TITLE
Git repos should not be updated when `--local` is passed in Bundler 2

### ISSUE THREAD

**Issue by indirect** [bundler/bundler#4347]
Right now, running `bundle install --local` will still check out and/or update git repos. It shouldn't, but this behavior has been around long enough that I'd like to fix it in Bundler 2.

**Comment by chalkos** [comment]
I'll try to fix this.

**Comment by chalkos** [comment]
I created a spec for this and it seems that `bundle install --local` will still check out git repos, but following runs of `bundle install --local` or `bundle install` do not update nor checkout git repos.

Following this I also created code that does not check out git repositories if `--local` is used. I'm running all specs now to check if I broke something else and then I'll create a PR to branch `2-0-dev`.

**Comment by LynnCo** [comment]
This'll have to be revisited after the 2.0 merge (https://github.com/bundler/bundler/pull/4564)

**Comment by chalkos** [comment]
This was merged into 2.0-dev by #4353
The commit from 28 May just had a bad commit message, I meant to refer a different issue.

**Comment by LynnCo** [comment]
👍
