### ISSUE TITLE
Bundler cannot continue.

### ISSUE THREAD

**Issue by YooTanya** [bundler/bundler#4349]
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `/Users/apple/.rbenv/versions/2.1.3/bin/bundle `

- What did you expect to happen?

  I expected Bundler to install gems

- What happened instead?

  Instead, what actually happened was unexpected stop

Error details

    ArgumentError: Invalid source: nil
      /Users/apple/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/source_list.rb:93:in `source_list_for'
      /Users/apple/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/source_list.rb:43:in `get'
      /Users/apple/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/definition.rb:558:in `block in converge_locked_specs'
      /Users/apple/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/definition.rb:555:in `converge_locked_specs'
      /Users/apple/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/definition.rb:195:in `resolve'
      /Users/apple/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/definition.rb:166:in `missing_specs'
      /Users/apple/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/installer.rb:70:in `block in run'
      /Users/apple/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/ui/shell.rb:76:in `silence'
      /Users/apple/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/installer.rb:67:in `run'
      /Users/apple/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/installer.rb:18:in `install'
      /Users/apple/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/cli/install.rb:107:in `run'
      /Users/apple/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/cli.rb:162:in `install'
      /Users/apple/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /Users/apple/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /Users/apple/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /Users/apple/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /Users/apple/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/cli.rb:10:in `start'
      /Users/apple/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/bin/bundle:20:in `block in <top (required)>'
      /Users/apple/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
      /Users/apple/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/bin/bundle:18:in `<top (required)>'
      /Users/apple/.rbenv/versions/2.1.3/bin/bundle:23:in `load'
      /Users/apple/.rbenv/versions/2.1.3/bin/bundle:23:in `<main>'

Environment

    Bundler   1.10.6
    Rubygems  2.2.2
    Ruby      2.1.3p242 (2014-09-19 revision 47630) [x86_64-darwin13.0]
    GEM_HOME  /Users/apple/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0
    GEM_PATH  /Users/apple/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0:/Users/apple/.gem/ruby/2.1.0
    Git       1.9.3 (Apple Git-50)
--- TEMPLATE END ----------------------------------------------------------------

**Comment by segiddins** [comment]
Please include your Gemfile in the error report.

**Comment by LynnCo** [comment]
Closing this due to lack of information, @YooTanya I can re-open it if needed
