### ISSUE TITLE
Bundle without change in implicit behavior in v1.10.0

### ISSUE THREAD

**Issue by schneems** [bundler/bundler#4351]
Prior to version 1.10.0 if you are installing using the explicit flag `--without` only the arguments provided will be used in the bundle command so if you

```
$ bundle _1.9.10_ install  --without development:test
# ...
Gems in the groups development and test were not installed.
```

Then it will only exclude your `development` and `test` groups, However with 1.10.0 any config in your `.bundle/config` will get merged in. So someone in your team checks in their bundle config that looks like this:

```
$ cat .bundle/config
---
BUNDLE_WITHOUT: unneeded
```

And you run this

```
$ bundle _1.10.0_ install  --without development:test
```

You exclude a group not present in the explicit without flag:

```
Gems in the groups development, test and unneeded were not installed.
```

I checked over the changelog and I haven't  yet figured out exactly where this change in implicit behavior came from (forgive me if I missed it in the changelog). Should we retroactively document this change or is it a bug that should be reverted?

cc/ @hone

**Comment by indirect** [comment]
It was definitely a bug that `.bundle/config` was ignored if you passed `--without`. You should be able to run `bundle config without foo` and then `bundle install --without bar` to get a bundle without foo or bar. 

Unrelated to the behavior change, never ever check in your `.bundle` directory. It contains repo/checkout local state like the location of the installed bundle, configured git local gems, and other settings that should not be shared between multiple checkouts of a single repo.

**Comment by schneems** [comment]
We should add that to the changelog for completeness. How does this sound?

```
  - The `--without` flag now includes bundle config `BUNDLE_WITHOUT` value
```

We could warn when we find a `.bundle/config` when someone deploys an app to Heroku.

**Comment by indirect** [comment]
How about:

```
## Bugfixes

 - Without groups saved via `config` are no longer ignored when the `--without` flag is used
```

Warning users who check in their `.bundle/config` seems like a very good idea.

**Comment by schneems** [comment]
I like that, I'll send over a doc PR. Btw we're on 1.11.2 as of yesterday. Some minor issues (https://devcenter.heroku.com/articles/bundler-version#known-upgrade-issues), but so relatively smooth sailing.
