### ISSUE TITLE
Ability to set `--local` via environment variable 

### ISSUE THREAD

**Issue by schneems** [bundler/bundler#4356]
Is it possible to set the `--local` flag via environment variable?

```
$ bundle install --local
Could not find gem 'blkjasldkfj' in any of the gem sources listed in your Gemfile or available on this machine.
```

This doesn't work on 1.11.2:

```
$ BUNDLE_LOCAL=1 bundle install
Fetching gem metadata from https://rubygems.org/..........
Fetching version metadata from https://rubygems.org/..
Could not find gem 'blkjasldkfj' in any of the gem sources listed in your Gemfile or available on this machine.
```

Are there any switches (flags with no arguments) that bundle install takes that can be set with an environment variable? Not sure if there is a pattern that already exists for these types of flags or what you think about adding support for them if none exist.

**Comment by segiddins** [comment]
Additionally, this seems more like a question than an issue to me?

**Comment by indirect** [comment]
Yes, I was trying to warn that a simple PR that moved local into settings would probably result in the option getting saved into config and used again later...

**Comment by schneems** [comment]
We don't support arbitrary flags on Heroku https://github.com/heroku/heroku-buildpack-ruby/pull/439 and would rather do something bundler compliant than custom. i.e. we don't want to hijack the BUNDLE_* env var if bundler will end up using it eventually.

**Comment by indirect** [comment]
@schneems why not add argument support to the buildpack instead of sending a PR for every single flag in Bundler, then?

**Comment by segiddins** [comment]
e.g. `${BUNDLER_ARGS}` would be forward-compliant for forever

**Comment by schneems** [comment]
The only config flag anyone has asked for is `--local`. I might also be interested in `--verbose`. The main reason for not bypassing bundler and adding straight to Heroku is one of standardization and interface.

If we're going to add it to Heroku we would probably add it to an environment variable, so we would probably use `BUNDLE_LOCAL`. if 1 year from now everyone forgets this conversation happened and bundler gets support for a `BUNDLE_LOCAL` environment variable but it does something different than what Heroku implements, then that's a problem. Or if the interface is slightly different like `BUNDLE_LOCAL_` or something, then now there's two interfaces to the same setting, and it's bloat.

`BUNDLE_ARGS` isn't great for us because we don't want more control than that (assuming you're thinking we pass it straight into the command). We have other systems that expect files to be installed to certain paths for example. If people can shoot themselves in the foot with a configuration option they will, even when the ability to configure that thing isn't valuable. It also opens the door to do weird scripting things. It's good for a catchall option, but for that I would prefer people forked the buildpack, at least then they know they're responsible for the crazy stuff they throw into their bundle install command.

I also don't want people accidentally thinking that setting a Heroku specific environment variable would work locally. Which is another benefit if we keep the interface standard.

If it was valuable enough to add I would prefer spending my time on a PR and waiting until it was released. Or if it just worked (TM) today, then I would document it. I'm not sure I want to implement this in Heroku directly without more consideration.

**Comment by indirect** [comment]
I'm not sure we want to implement this in Bundler directly without more consideration, so I think we're at an impasse. 😝
