### ISSUE TITLE
Bundle viz

### ISSUE THREAD

**Issue by austinc88** [bundler/bundler#4359]
Hi,

I was using the command 'bundle viz' to generate dependency graphs for my ruby codebases. However, I am finding with very large codebases with ~100 gems, the graph becomes hard to read. I was wondering if there was any way to generate this data in perhaps an excel table of some sort to be able to view what the children and parent of each dependency?

Thanks!

**Comment by sstern6** [comment]
@austinc88 interesting point, I was just reading the docs and it seems like the only output format it supports is a PNG file, not a csv or tsv http://bundler.io/v1.1/bundle_viz.html.  I'd like someone else to chime in on this and maybe this could be added as an improvement if its not possible currently.

**Comment by segiddins** [comment]
Closing this for now -- discussion should take place on https://github.com/bundler/bundler-features/issues/114, as this is a feature request.

**Comment by sstern6** [comment]
Thanks @segiddins
