### ISSUE TITLE
Rubygems 2.6.2 Calls undefined method `size` on `Bundler::SpecSet`

### ISSUE THREAD

**Issue by danielsdeleo** [bundler/bundler#4368]
I have some code that does `Gem::Specification.find_by_name(@gem_name_for_base_dir)`. When I run this with rubygems 2.6.2, some code internal to rubygems calls `#size` on a `Bundler::SpecSet` object, resulting in 

```
NoMethodError: undefined method `size' for #<Bundler::SpecSet:0x007f879baa2d08>
 /Users/ddeleo/.rbenv/versions/2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/dependency.rb:310:in `to_specs'
 /Users/ddeleo/.rbenv/versions/2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/dependency.rb:330:in `to_spec'
 /Users/ddeleo/.rbenv/versions/2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1028:in `find_by_name'
```

(I've trimmed the rest of the stack trace as I think it's not relevant to you).

I noticed that `Bundler::SpecSet` does define `#length`, and aliasing this method as size seems to resolve my issue.

**Comment by PierreR** [comment]
Could this fix backported in 1.12.x ? If I am not mistaken, this fix is still not available on any stable release.
