### ISSUE TITLE
Long config options seem to be 'lost'

### ISSUE THREAD

**Issue by TiMBuS** [bundler/bundler#4370]
So, bundler seems to be 'losing' my rather long build options whenever it updates the config:

```
$ bundle config thingy --asdf --fdsa --ty='oh man i hope this doesnt break bundler because that would suck' --ehhh='oh geez it looks like i might have broken bundler somehow' --very-important-option=DontDeleteRoot

$ bundle config thingy
Settings for `thingy` in order of priority. The top value will be used
Set for your local app (blah): "'--asdf --fdsa --ty=oh man i hope this doesnt break bundler because that would suck --ehhh=oh geez it looks like i might have broken bundler somehow"
```
```
$ bundle --version
Bundler version 1.12.0.rc
```

Contents of .bundle/config:
```
---
BUNDLE_THINGY: "--asdf --fdsa --ty=oh man i hope this doesnt break bundler because
  that would suck --ehhh=oh geez it looks like i might have broken bundler somehow
  --very-important-option=DontDeleteRoot"
```
Note that it can't seem to read the last line, specifically.

Annoyingly, it works if I manually fix up the config to only use one or two lines, but any time bundler tries to regenerate the config, it's broken again.

**Comment by segiddins** [comment]
That's very odd, as bundler uses the YAML module to serialize the config file

**Comment by TiMBuS** [comment]
Yeah, it looked like YAML output, but the reader seems to be doing something.. 'fancy'..

Especially since it's trying to show me the YAML pipe `|` operator if I add it to the config in an attempt to make it load more lines. Surely that should have been stripped..

**Comment by segiddins** [comment]
what's the output out `ruby -ryaml -e 'p YAML.load(".bundle/config")'` ?

**Comment by TiMBuS** [comment]
Sorry, didn't see this yesterday.

Yes the YAML module loads the config correctly, when using `load_file`.
`{ "BUNDLE_THINGY"=>"--asdf --fdsa --ty=oh man i hope this doesnt break bundler because that would suck --ehhh=oh geez it looks like i might have broken bundler somehow --very-important-option=DontDeleteRoot" }`

I have replicated this issue on an ubuntu machine and a red hat one, running different ruby and bundler versions. Are you not seeing the same issue?

**Comment by jbodah** [comment]
Problem seems to be related with the regex in [Bundler::Settings#load_config](https://github.com/bundler/bundler/blob/83350e3693c5ed5dd7e55916411e5c2c877548d3/lib/bundler/settings.rb#L228)

Changing to `^(BUNDLE_.+): (['"]?)(.*(?:(\n(?!BUNDLE).+)*)?)\2$` seems to work for the [limited test sample](http://rubular.com/r/IynXtnCfRp) I've tried. That thing is a bit of a beast though and it might be better to move away from regex

**Comment by TiMBuS** [comment]
Yeah, I actually fixed this for myself last weekend by changing load_config to: 
```ruby
def load_config(config_file)
  valid_file = config_file && config_file.exist? && !config_file.size.zero?
  if !ignore_config? && valid_file
    require "bundler/psyched_yaml"
    config = YAML.load_file(config_file)
    if config.is_a?(Hash)
      return config.select { |key|
        key.match(/^(BUNDLE_.+)/)
      }.map { |key, value|
        [convert_to_backward_compatible_key(key), value]
      }.to_h
    end
  end
  {}
end
```
I decided against making a pull request because I figured such a change might cause compatibility issues that I'm not really willing to put my name next to. 

And I'm also pretty bad at ruby so, there's that too :P

**Comment by segiddins** [comment]
Yeah, we can't use the `yaml` module to read the config since it'd cause issues if the user has a different psych in their lockfile

**Comment by TiMBuS** [comment]
But you can use it to write the config? :confused:

Well. Okay. The regex fix works well enough then.

**Comment by segiddins** [comment]
Yeah, since the config is never written to when using `Bundler.setup`, `-rbundler/setup`, or `bundle exec`

**Comment by TiMBuS** [comment]
I'm assuming your bundler/psyched_yaml module guarantees that your output format will always be the same, but I'm just having trouble reasoning why you bother saving it as YAML at all, if it can lead to strange errors like this. Why not just stick with a more basic format?

My 'bonus question' is.. why would an alternate psych version not be able to.. read YAML? Or is the problem something deeper than that?

**Comment by segiddins** [comment]
the problem is that we could activate the incorrect version of psych

**Comment by segiddins** [comment]
> why you bother saving it as YAML at all

We have to, to be backwards compatible. There's a long history around this that has involved lots of pain for us, believe me :(

**Comment by TiMBuS** [comment]
> the problem is that we could activate the incorrect version of psych
Ooooh. I get it. Well, carry on then. Thanks for fixing this.
