### ISSUE TITLE
1.12.0.rc: cannot install omniauth-google-oauth2 0.4.1 using new index

### ISSUE THREAD

**Issue by TimMoore** [bundler/bundler#4371]
I noticed this in a real project, but was able to reproduce it in a new project: installing omniauth-google-oauth2 0.4.1 fails with "Could not find omniauth-google-oauth2-0.4.1 in any of the sources"

I notice that this was just released in the last day, so it could be an issue propagating to the new index? https://rubygems.org/gems/omniauth-google-oauth2/versions/0.4.1

There are full reproduction steps including output at https://gist.github.com/TimMoore/34c6fcd9795b4904602b

**Comment by TimMoore** [comment]
As you can see in the gist, the problem disappeared with `--full-index`, but I couldn't find a flag to force 1.12 to use the API rather than the compact index.

**Comment by indirect** [comment]
Can confirm that 0.4.1 is not present: http://index.rubygems.org/info/omniauth-google-oauth2

**Comment by TimMoore** [comment]
On a tip from @indirect, I tried bypassing the Fastly cache, and that also fixes it:

```
$ sed -e 's/rubygems.org/bundler.rubygems.org/' -i .bak Gemfile
$ head -n2 Gemfile
# A sample Gemfile
source "https://bundler.rubygems.org"
$ rm -rf .bundle/gems
$ bundle install --quiet
$?
0
```

**Comment by segiddins** [comment]
This was fixed by https://github.com/bundler/bundler-api/issues/132 and expiring the new index files on fastly.
