### ISSUE TITLE
Excluded (--without) git dependencies are still included.

### ISSUE THREAD

**Issue by glennpratt** [bundler/bundler#4373]
For a few reasons (package size, private development dependencies) I'd like to only include runtime dependencies with gems we package for deployment. The `--without` option works great for hosted gems, but development gems used from source (e.g. `:git`) are still included.

reproduction script to follow shortly

**Comment by glennpratt** [comment]
Reproduction script:

https://gist.github.com/glennpratt/9a916fed18d0aeea53a9

**Comment by RochesterinNYC** [comment]
It sounds like you might be looking for the `--deployment` flag? http://bundler.io/v1.11/deploying.html

I can verify that running the following command: `bundle install --deployment --without development` on your reproduction script's `Gemfile` (provided a `Gemfile.lock` is present) will result in no `vendor/bundle/ruby/2.2.0/bundler` directory and hence no `vendor/bundle/ruby/2.2.0/bundler/gems/thor-sha`.

For some additional context as to why that's there in the first place, see "Why Is Bundler Downloading Gems From --without Groups?" in http://bundler.io/faq.html

**Comment by RochesterinNYC** [comment]
@glennpratt does utilization of the `--deployment` flag fit your needs?

**Comment by LynnCo** [comment]
Assuming @glennpratt got their issue resolved, and closing this. Will re-open if needed!

**Comment by RochesterinNYC** [comment]
Just bumped into this issue again at work, and while using the `--deployment` flag does work, we shouldn't force users to use that flag unless they're actually deploying. If they want to `bundle install --without group-containing-git-gem` locally, that should work and not do anything with the git specified gem. Reopening.
