### ISSUE TITLE
Pathological Gemfile

### ISSUE THREAD

**Issue by segiddins** [bundler/bundler#4376]
```ruby
source 'https://rubygems.org'

gem 'middleman', '~> 3.4'
gem 'middleman-rouge'
gem 'rouge', git: 'https://github.com/jneen/rouge', ref: 'd989f18'
gem 'bootstrap-sass', '~> 3.3'
gem 'bh', '~> 1.3'

gem 'link-checker'
```

This takes forever to resolve.

**Comment by segiddins** [comment]
Problem at the end of the day seems to be `nokogiri`

**Comment by jbodah** [comment]
I also had a nokogiri resolution issue the other day. I got around it by upgrading nokogiri first then resolving everything else

**Comment by segiddins** [comment]
With https://github.com/bundler/bundler/pull/4580 and https://github.com/CocoaPods/Molinillo/pull/40, this gets down to a few seconds

**Comment by stopdropandrew** [comment]
Wow, had a large Gemfile where dependency resolution during an update was taking 3hrs on 1.12.5, updated to 1.13.0.rc.2 and it's now taking 30s. 😓

**Comment by segiddins** [comment]
that sounds like an awesome improvement, glad to see it @stopdropandrew !
