### ISSUE TITLE
Environment variable not interoplated

### ISSUE THREAD

**Issue by bbuchalter** [bundler/bundler#4382]
- What did you do?

I updated my `~/.bundle/config` file to look like this, and then ran `bundle` on a local project.
```
---
BUNDLE_DISABLE_LOCAL_BRANCH_CHECK: 'true'
BUNDLE_PATH: vendor/bundle/$RUBY_VERSION
BUNDLE_DISABLE_SHARED_GEMS: '1'
```

- What did you expect to happen?

Install my gems in a per-project, per-Ruby basis.
 

- What happened instead?
```
    Errno::ENOENT: No such file or directory @ chmod_internal - /Users/brianb/workspace/solidus_auth_devise/vendor/bundle/$RUBY_VERSION/bundler/gems/solidus-a673c5844f6e
    /Users/brianb/.gem/ruby/2.1.5/gems/bundler-1.8.5/lib/bundler/source/git/git_proxy.rb:86:in `chmod'
    /Users/brianb/.gem/ruby/2.1.5/gems/bundler-1.8.5/lib/bundler/source/git/git_proxy.rb:86:in `copy_to'
    /Users/brianb/.gem/ruby/2.1.5/gems/bundler-1.8.5/lib/bundler/source/git.rb:154:in `specs'
    /Users/brianb/.gem/ruby/2.1.5/gems/bundler-1.8.5/lib/bundler/definition.rb:204:in `block (2 levels) in index'
    /Users/brianb/.gem/ruby/2.1.5/gems/bundler-1.8.5/lib/bundler/definition.rb:202:in `each'
    /Users/brianb/.gem/ruby/2.1.5/gems/bundler-1.8.5/lib/bundler/definition.rb:202:in `block in index'
    /Users/brianb/.gem/ruby/2.1.5/gems/bundler-1.8.5/lib/bundler/index.rb:9:in `build'
    /Users/brianb/.gem/ruby/2.1.5/gems/bundler-1.8.5/lib/bundler/definition.rb:199:in `index'
    /Users/brianb/.gem/ruby/2.1.5/gems/bundler-1.8.5/lib/bundler/definition.rb:193:in `resolve'
    /Users/brianb/.gem/ruby/2.1.5/gems/bundler-1.8.5/lib/bundler/definition.rb:132:in `specs'
  1 ---
    /Users/brianb/.gem/ruby/2.1.5/gems/bundler-1.8.5/lib/bundler/definition.rb:121:in `resolve_remotely!'
    /Users/brianb/.gem/ruby/2.1.5/gems/bundler-1.8.5/lib/bundler/installer.rb:79:in `run'
    /Users/brianb/.gem/ruby/2.1.5/gems/bundler-1.8.5/lib/bundler/installer.rb:18:in `install'
    /Users/brianb/.gem/ruby/2.1.5/gems/bundler-1.8.5/lib/bundler/cli/install.rb:80:in `run'
    /Users/brianb/.gem/ruby/2.1.5/gems/bundler-1.8.5/lib/bundler/cli.rb:157:in `install'
    /Users/brianb/.gem/ruby/2.1.5/gems/bundler-1.8.5/lib/bundler/vendor/thor/command.rb:27:in `run'
    /Users/brianb/.gem/ruby/2.1.5/gems/bundler-1.8.5/lib/bundler/vendor/thor/invocation.rb:121:in `invoke_command'
    /Users/brianb/.gem/ruby/2.1.5/gems/bundler-1.8.5/lib/bundler/vendor/thor.rb:363:in `dispatch'
    /Users/brianb/.gem/ruby/2.1.5/gems/bundler-1.8.5/lib/bundler/vendor/thor/base.rb:440:in `start'
    /Users/brianb/.gem/ruby/2.1.5/gems/bundler-1.8.5/lib/bundler/cli.rb:10:in `start'
    /Users/brianb/.gem/ruby/2.1.5/gems/bundler-1.8.5/bin/bundle:20:in `block in <top (required)>'
    /Users/brianb/.gem/ruby/2.1.5/gems/bundler-1.8.5/lib/bundler/friendly_errors.rb:6:in `with_friendly_errors'
    /Users/brianb/.gem/ruby/2.1.5/gems/bundler-1.8.5/bin/bundle:18:in `<top (required)>'
    /Users/brianb/.gem/ruby/2.1.5/bin/bundle:23:in `load'
    /Users/brianb/.gem/ruby/2.1.5/bin/bundle:23:in `<main>'

Environment

    Bundler   1.8.5
    Rubygems  2.2.2
    Ruby      2.1.5p273 (2014-11-13 revision 48405) [x86_64-darwin13.0]
    GEM_HOME  /Users/brianb/workspace/solidus_auth_devise/vendor/bundle/$RUBY_VERSION
    GEM_PATH
    Git       2.6.4

Bundler settings

    disable_local_branch_check
      Set for the current user (/Users/brianb/.bundle/config): "true"
    path
      Set for the current user (/Users/brianb/.bundle/config): "vendor/bundle/$RUBY_VERSION"
    disable_shared_gems
      Set for your local app (/Users/brianb/workspace/solidus_auth_devise/.bundle/config): "1"
      Set for the current user (/Users/brianb/.bundle/config): "1"
```

**Comment by RochesterinNYC** [comment]
Is there documentation somewhere detailing that this line in the config (`BUNDLE_PATH: vendor/bundle/$RUBY_VERSION`) would be interpolated with the environment `RUBY_VERSION`?

**Comment by bbuchalter** [comment]
Hey @RochesterinNYC, thanks for the quick reply. Is this [the place](http://www.rubydoc.info/github/bundler/bundler/Bundler.bundle_path) where that documentation would/should be?

**Comment by RochesterinNYC** [comment]
Sorry, my question was basically asking how you came to believe that using `$RUBY_VERSION` in the config yaml would evaluate that and interpolate it as something like `ruby-2.2.4` or etc. I can't find it in the documentation anywhere but I might be looking in the wrong places. I want to help you determine whether this is the right way to do in-config interpolation and the feature is broken, or if this is not an actual Bundler feature. Additionally, what problem are you trying to solve with this in-config interpolation?

**Comment by bbuchalter** [comment]
My goal was to have a per-project, per-Ruby vendorized bundle. If I switch Ruby's, I don't want them to share the same vendor path.

I don't necessarily think this is a bundle problem (or an intended feature), but since it triggered a bundler exception and encouraged me to raise this issue, I thought I'd give it a try.

If we look at [where the exception was raised](https://github.com/bundler/bundler/blob/v1.8.5/lib/bundler/source/git/git_proxy.rb#L86) there are a few things of note:
- This was run against an _old_ version of Bundler (1.8.5) because I was testing a gem against Ruby 2.1.5
- The exception got triggered in `File.chmod`'s "internal implementation", which almost certainly means this is not a Bundler issue.

That said, I'm going to close this issue, but would welcome feedback about how to achieve my per-project, per-Ruby vendorized bundle. Thanks!
