### ISSUE TITLE
Errors while using the dependency API should suggest --full-index

### ISSUE THREAD

**Issue by indirect** [bundler/bundler#4384]
If Bundler experiences 3 errors in a row while trying to contact the dependency API, it will raise and exit. The error message should suggest trying `bundle install --full-index`, which downloads a static file instead of trying to use the dynamic dependency API, and almost always works around the problem while the API is having issues.

**Comment by RochesterinNYC** [comment]
Are these the [lines](https://github.com/bundler/bundler/blob/master/lib/bundler/fetcher/dependency.rb#L30-L32) you're referring to in terms of contacting the Dependency API? Not quite sure exactly where the retry point you're referring to is.
