### ISSUE TITLE
Prerelease gems with `-` cause `bundle show` to fail

### ISSUE THREAD

**Issue by indirect** [bundler/bundler#4385]
```
$ cat Gemfile
source "https://rubygems.org"
gem "rack-timeout", "0.4.0-beta.1", github: "heroku/rack-timeout"

$ bundle install
Fetching git://github.com/heroku/rack-timeout.git
Fetching gem metadata from https://rubygems.org/
Fetching version metadata from https://rubygems.org/
Resolving dependencies...
Using bundler 1.12.0.rc
Using rack-timeout 0.4.0.pre.beta.1 from git://github.com/heroku/rack-timeout.git (at master@e6d7211)
Bundle complete! 1 Gemfile dependency, 2 gems now installed.
Bundled gems are installed into ./.bundle.

$ bundle show
The git source git://github.com/heroku/rack-timeout.git is not yet checked out. Please run `bundle install` before trying to start your application

$ bundle exec echo what
what

$ bundle show
The git source git://github.com/heroku/rack-timeout.git is not yet checked out. Please run `bundle install` before trying to start your application
```

First, it should never be possible to have `install` succeed and then have `show` fail. It should be doubly-impossible to have `install` and `exec` both succeed and still have `show` fail. Lastly, Bundler says it's using `rack-timeout 0.4.0.pre.beta.1`. That's not a version that exists, because [the gemspec for rack-timeout](https://github.com/heroku/rack-timeout/blob/master/rack-timeout.gemspec#L5) has the version set to `0.4.0-beta.1`.

???

**Comment by indirect** [comment]
Seems like the pre weirdness is coming from RubyGems:

```
irb(main):002:0> Gem::Requirement.new("~> 0.4.0-beta.1")
=> #<Gem::Requirement:0x007feae983ca80 @requirements=[["~>", #<Gem::Version "0.4.0.pre.beta.1">]]>
```

**Comment by segiddins** [comment]
https://github.com/rubygems/rubygems/blob/22737a10a13d15bcfa05c1ea75e04a274ef8713f/lib/rubygems/version.rb#L210 shows that changing the version is 100% intentional

**Comment by segiddins** [comment]
So what's super weird is that `bundle show rack-timeout --verbose` works...

**Comment by segiddins** [comment]
I have a fix
