### ISSUE TITLE
SyntaxError: (<unknown>): mapping values are not allowed in this context at line 3 column 6

### ISSUE THREAD

**Issue by Yerramillimurthy** [bundler/bundler#4387]
Hi,

Below error message is displayed when I executed bundle install:

SyntaxError: (<unknown>): mapping values are not allowed in this context at line 3 column 4

**Comment by RochesterinNYC** [comment]
Please post the generated error report, your `Gemfile` and/or `Gemfile.lock`, and results of running `bundle env`. We need more information to figure out what's going on.

**Comment by LynnCo** [comment]
@Yerramillimurthy is this still an issue? If not I will close it

**Comment by RochesterinNYC** [comment]
Closing due to lack of response.
