### ISSUE TITLE
Add `Bundler.require(:all)` for requiring all Gems?

### ISSUE THREAD

**Issue by farkasity** [bundler/bundler#4390]
All Gems mean all gems including `:default` and all gems in all group.

**Comment by jbodah** [comment]
Note you can also do `Bundler.require(*Bundler.definition.groups)` to achieve the same goal

**Comment by farkasity** [comment]
@jbodah Thanks a lot, but I think maybe `:all` is more user-friendly.

**Comment by segiddins** [comment]
We don't advocate people use `bundler.require` when they don't need to, so it's unlikely this feature will be added.
