### ISSUE TITLE
Bundle update creates proper local gem repository folder with contents for previous version of gem

### ISSUE THREAD

**Issue by rhuppert** [bundler/bundler#4391]
I am experiencing a confusing problem with an update for a particular gem (rails-footnotes).  This gem is certainly not critical to my project, but my concern is that other gems might be affected with similar behavior.

I realized that a modification to the gem in the most recent version of rails-footnotes was not working, so I tried to resolved it by running gem uninstall for both versions of the gem and then running bundle install. It worked for a while and then I noticed later it had reverted to the previous version, even though "bundle list rails-footnotes" indicated 4.1.8 (the new version), yet the specific files changes were not reflected in the rbenv home directory for that version of the gem.

My thought was this was a rbenv issue, so I uninstalled it completely and then reinstalled it and then the 2.3.0 version of Ruby I am using.  I also updated rubygems, After that I ran bundle install for my Rails 4.2.6 project, and, to my surprise, the gem in question is listed as 4.1.8, but upon checking one of the local files in question, it clearly does not match the contents of the file on github.

Perhaps I am missing something in my understanding of how Bundler should work or perhaps this is not a Bundler issue at all.  I am perplexed.

My concern is that Bundler reported I was running a version that clearly had not been updated, even though the folder name indicated it had.  Could the issue be with some gem issue with the rails-footnotes gem itself?

gist for bunde env: https://gist.github.com/rhuppert/591de797f5270613d53d
```
rails-footnotes/lib/rails-footnotes/notes/queries_note.rb, line 23:

From my local machine:
  def title
    queries = self.events.count
    total_time = self.events.map(&:duration).sum
    query_color = generate_red_color(self.events.count, alert_sql_number)
    db_color    = generate_red_color(total_time, alert_db_time)

    <<-TITLE
    <span style="background-color:#{query_color}">Queries (#{queries})</span>
    <span style="background-color:#{db_color}">DB (#{"%.3f" % total_time}ms)</span>
    TITLE
  end

from github master:
  def title
    queries = self.events.count
    total_time = self.events.map(&:duration).sum
    query_color = alert_color(self.events.count, alert_sql_number)
    db_color    = alert_color(total_time, alert_db_time)

    <<-TITLE
    <span style="background-color:#{query_color}">Queries (#{queries})</span>
    <span style="background-color:#{db_color}">DB (#{"%.3f" % total_time}ms)</span>
    TITLE
  end
```

**Comment by TimMoore** [comment]
@rhuppert the code you see on master hasn't been released as a new gem version yet.

Here's the code in the 4.1.8 tag: https://github.com/josevalim/rails-footnotes/blob/4.1.8/lib/rails-footnotes/notes/queries_note.rb

If you need to use the code on master, you can use Bundler's support for git gems: http://bundler.io/v1.11/git.html

**Comment by rhuppert** [comment]
Wow.  Another mind fart!  Thanks @TimMoore.  I had the impression it had been changed.  At least things are a bit cleaner on my end.
