### ISSUE TITLE
Gemfile.lock, PLATFORMS, ruby disappeared

### ISSUE THREAD

**Issue by skydiverhz** [bundler/bundler#4405]
I'm running Windows 7 Pro 64bit, Ruby 2.1.7p400, and Rails 4.2.1 on my laptop. Both Ruby and Rails were installed in August 2015. A week ago I noticed that while my Gemfile.lock, PLATFORMS lists x64-mingw32 but "ruby" is suddenly missing. I checked some apps from a few weeks ago and their Gemfile.lock lists both ruby and x64-mingw32 (see below)
How do I correct this?
Current:
PLATFORMS
  x64-mingw32
Previous: 
PLATFORMS
  ruby
  x64-mingw32

**Comment by segiddins** [comment]
try running `bundle install` on a non-Windows machine

**Comment by skydiverhz** [comment]
Thanks for the suggestion. I tried that, bundle exec bundle install, and deleted the Gemfile.lock and tried again. None worked. I don't know if it's the missing ruby platform, but I can't run "ruby homework.rb" I get the error "ruby: No such file or directory -- homework.rb (LoadError)".

**Comment by skydiverhz** [comment]
Thanks for the suggestion. I tried that, bundle exec bundle install, and deleted the Gemfile.lock and tried again. None worked. I don't know if it's the missing ruby platform, but I can't run "ruby homework.rb" I get the error "ruby: No such file or directory -- homework.rb (LoadError)".

However, if I copy homework.rb into an old app directory where the Gemfile.lock includes the ruby platform,   the command "ruby homework.rb" works. 

 

Harold

**Comment by LynnCo** [comment]
Looks like you got the issue resolved @skydiverhz, so I'm closing this issue

**Comment by skydiverhz** [comment]
Please leave it open. The one answer didn't resolve the problem. 

On May 3, 2016, at 8:06 AM, Lynn Cyrin <notifications@github.com> wrote:

Looks like you got the issue resolved @skydiverhz, so I'm closing this issue
