### ISSUE TITLE
bundle install incorrectly getting ancient gem.

### ISSUE THREAD

**Issue by tdreyno** [bundler/bundler#4406]
Given the `Gemfile`:

```
source 'https://rubygems.org'
gem 'middleman', '>= 4.0.0'
gem 'middleman-blog'
```

`bundle install` installs `middleman-blog` 0.1.5
`gem install middleman-blog` correctly installs 4.0.0

Ruby version: 2.2.3
Bundler version: 1.11.2

Resulting `Gemfile.lock` below:

```
GEM
  remote: https://rubygems.org/
  specs:
    activesupport (4.2.6)
      i18n (~> 0.7)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.3, >= 0.3.4)
      tzinfo (~> 1.1)
    addressable (2.3.8)
    backports (3.6.8)
    capybara (2.5.0)
      mime-types (>= 1.16)
      nokogiri (>= 1.3.3)
      rack (>= 1.0.0)
      rack-test (>= 0.5.4)
      xpath (~> 2.0)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.10.0)
    compass-import-once (1.0.5)
      sass (>= 3.2, < 3.5)
    concurrent-ruby (1.0.1)
    contracts (0.13.0)
    erubis (2.7.0)
    execjs (2.6.0)
    fast_blank (1.0.0)
    fastimage (1.9.0)
      addressable (~> 2.3.5)
    ffi (1.9.10)
    haml (4.0.7)
      tilt
    hamster (3.0.0)
      concurrent-ruby (~> 1.0)
    hashie (3.4.3)
    i18n (0.7.0)
    json (1.8.3)
    kramdown (1.10.0)
    listen (3.0.6)
      rb-fsevent (>= 0.9.3)
      rb-inotify (>= 0.9.7)
    middleman (4.1.6)
      coffee-script (~> 2.2)
      compass-import-once (= 1.0.5)
      haml (>= 4.0.5)
      kramdown (~> 1.2)
      middleman-cli (= 4.1.6)
      middleman-core (= 4.1.6)
      sass (>= 3.4.0, < 4.0)
    middleman-blog (0.1.5)
    middleman-cli (4.1.6)
      thor (>= 0.17.0, < 2.0)
    middleman-core (4.1.6)
      activesupport (~> 4.2)
      addressable (~> 2.3)
      backports (~> 3.6)
      bundler (~> 1.1)
      capybara (~> 2.5.0)
      contracts (~> 0.13.0)
      erubis
      execjs (~> 2.0)
      fast_blank
      fastimage (~> 1.7)
      hamster (~> 3.0)
      hashie (~> 3.4)
      i18n (~> 0.7.0)
      listen (~> 3.0)
      padrino-helpers (~> 0.13.0)
      parallel
      rack (>= 1.4.5, < 2.0)
      sass (>= 3.4)
      tilt (~> 1.4.1)
      uglifier (~> 2.6)
    mime-types (3.0)
      mime-types-data (~> 3.2015)
    mime-types-data (3.2016.0221)
    mini_portile2 (2.0.0)
    minitest (5.8.4)
    nokogiri (1.6.7.2)
      mini_portile2 (~> 2.0.0.rc2)
    padrino-helpers (0.13.1)
      i18n (~> 0.6, >= 0.6.7)
      padrino-support (= 0.13.1)
      tilt (~> 1.4.1)
    padrino-support (0.13.1)
      activesupport (>= 3.1)
    parallel (1.8.0)
    rack (1.6.4)
    rack-test (0.6.3)
      rack (>= 1.0)
    rb-fsevent (0.9.7)
    rb-inotify (0.9.7)
      ffi (>= 0.5.0)
    sass (3.4.21)
    thor (0.19.1)
    thread_safe (0.3.5)
    tilt (1.4.1)
    tzinfo (1.2.2)
      thread_safe (~> 0.1)
    uglifier (2.7.2)
      execjs (>= 0.3.0)
      json (>= 1.8.0)
    xpath (2.0.0)
      nokogiri (~> 1.3)

PLATFORMS
  ruby

DEPENDENCIES
  middleman (>= 4.0.0)
  middleman-blog

BUNDLED WITH
   1.11.2
```

**Comment by segiddins** [comment]
I cannot reproduce with the given Gemfile -- in a clean directory, it installs `middleman-blog 4.0.0`

**Comment by tdreyno** [comment]
Really? It's 100% reproducible on OS X 10.11. Even after starting with an empty gemset. Just tested against Ruby 2.3.0 as well, same result.

Is there anything fancy I should do? A way to get some additional logs which might show why it is selecting that version?

I'm forwarding this report from several I've gotten on the main Middleman bug tracker, so it's definitely happening consistently for more than just myself.

**Comment by segiddins** [comment]
Ah interesting -- I was testing with 1.12.0.rc.1, you're right that it fails on 1.11.2. So it turns out we've already fixed this one :)

**Comment by tdreyno** [comment]
Awesome!

**Comment by lamont-granquist** [comment]
I can replicate on bundler-1.12.0.rc but I noticed that to install middleman-blog-4.0.0 that fastimage had to be downgraded to 1.8.1  if I pin both of them:

```ruby
# If you do not have OpenSSL installed, update
# the following line to use "http://" instead
source 'https://rubygems.org'

gem "middleman"

gem "fastimage", "~> 1.9"

gem "middleman-blog", "~> 4.0"

# Live-reloading plugin
gem "middleman-livereload", "~> 3.1.0"

# For faster file watcher updates on Windows:
gem "wdm", "~> 0.1.0", :platforms => [:mswin, :mingw]

# Windows does not come with time zone data
gem "tzinfo-data", platforms: [:mswin, :mingw, :jruby]
```

Then there is currently no solution:

```ruby
Bundler could not find compatible versions for gem "addressable":
  In Gemfile:
    fastimage (~> 1.9) was resolved to 1.9.0, which depends on
      addressable (~> 2.3.5)

    middleman-blog (~> 4.0) was resolved to 4.0.0, which depends on
      addressable (~> 2.4.0)

    middleman-blog (~> 4.0) was resolved to 4.0.0, which depends on
      middleman-core (>= 4.0.0) was resolved to 4.1.6, which depends on
        addressable (~> 2.3)
```

So for me, bundler is choosing to downgrade middleman-blog to 0.1.5 instead of downgrading fastimage to 1.8.1

@segiddins if you're getting a different result this might actually be something useful to track down as a bug.  I definitely think its poor behavior to have different depsolving when you do it vs. when i do it (for whatever random reason).  It also seems like bundler could warn about this situation better and/or it could pick a bit better.  In this case since I explicitly put `middleman-blog` in the Gemfile I probably would prefer to have the latest version of than, and since fastimage is entirely a transitive dep that's the one that I'd prefer to have downgraded.  I dunno if you can throw some kind of 'weight' into molinillo to make it less likely to downgrade my explicit inputs vs the transitively solved deps though (kinda expect not...)

clearly though the overly constraining deps on addressable are the root cause of this...

**Comment by segiddins** [comment]
@lamont-granquist the ability to "prefer" explicit deps is an interesting one, but algorithmicly speaking I have no idea how you'd implement that.

**Comment by lamont-granquist** [comment]
Yeah somehow you'd need to be able to 'teach' molinillo to 'weight' its explicit constraints more than the transitive ones...

Maybe bundler could warn when explicit deps weren't getting the latest version or were getting major version downgrades?

I've seen this before where i put a half dozen different apps in a Gemfile and they get into a fight over some shared transitive dep like the json gem, and i wind up with some super-downgraded version of one of the things that i wanted.   What I wind up doing is annotating every line with `">= <current version>"` which helps push the depsolver to find a solution more like one that I actually want.  If you can't make molinillo guess right, then it might be useful to output a warning when it looks like it may have guessed wrong...

Problem is that this is getting into a legitimately 'hard' area of computer science, and users just get angrysauce at bundler over it.  I'm not sure if its even solvable,but there might be something that could be done to give users hints...

(what mildly amusing is that i hit this problem playing around with middleman for a weekend project, but $DAYJOB at Chef is also switching over to molinillo for our cookbook depsolver so most likely it'll wind up being a work problem for me eventually as well -- there's a guy at work who knows vastly more about depsolvers from a CS background than i do and maybe i'll ping him next week...)
