### ISSUE TITLE
Version specific gem :platform in Gemfile doesn't do anything that I can see

### ISSUE THREAD

**Issue by kjg** [bundler/bundler#4420]
Running Bundler Version 1.11.2

If I have a Gemfile that specifies

``` ruby
platforms :ruby_18 do
  gem "rake", "< 11.0"
end
platforms :ruby_20 do
  gem "rake", "> 11.0"
end
```

I get the error

```
[!] There was an error parsing `Gemfile`: You cannot specify the same gem twice with different version requirements.
You specified: rake (< 11.0) and rake (> 11.0). Bundler cannot continue.
```

Am I just missing the point of the version specific platform option on the gems?

Is there anyway to meet this use case of installing a different version of the gem depending on the version of ruby?

Even though rake specifies it's REQUIRED RUBY VERSION in it's gemfile, bundler still tries to install >11 when I'm on ruby 1.8.7 for example, so using `platforms :ruby_20` is what I'd expect to have to do to work around this, but that doesn't seem to work either.

**Comment by segiddins** [comment]
There's no way to do this -- you'll need to stick with 10.x for 1.8 compatibility.

**Comment by kjg** [comment]
What is the intended use case for the version specific platform identifiers? The docs indicate that it does constrain the ruby version http://bundler.io/v1.11/man/gemfile.5.html#PLATFORMS-platforms-

**Comment by segiddins** [comment]
Yes, they do, but a single bundle must be self-coherent, regardless of different groups, platform blocks, install_if blocks, etc

**Comment by antoineco** [comment]
Does it also mean 

```ruby
gem 'rspec', '< 3.2.0', :platforms => :ruby_18
gem 'puppetlabs_spec_helper'
```

won't actually cap the `rspec` version if 'puppetlabs_spec_helper' requires `rspec` without defining a version? This is happening to me right now.

**Comment by lynnco** [comment]
So as far as I can tell, this is best interpreted as a feature request to allow Bundler to have different versions of the same gem on different platforms? cc @kjg

**Comment by segiddins** [comment]
If that's the feature request, we can close this -- that's simply not in the cards. It goes completely against bundler's promise of installing the same dependencies everywhere. If this functionality is something the user wants, they will have to use a regular ruby conditional and deal with the fact that their lockfile with change every time that they switch ruby versions

**Comment by kjg** [comment]
Gems inside the platform ruby_18 block still seem to get installed even on ruby 2.0

**Comment by antoineco** [comment]
@kjg I confirm that

**Comment by segiddins** [comment]
Closing, this is how the `:platform` filter is intended to work -- it only changes which gems are activated at runtime and intentionally does not allow specifying different versions of the same gem.
