### ISSUE TITLE
2.0.0/rubygems/specification.rb:2504:in `stat': File name too long - .gitignore (Errno::ENAMETOOLONG)

### ISSUE THREAD

**Issue by yuvasoft** [bundler/bundler#4421]
Error details

    Errno::ENAMETOOLONG: File name too long - .gitignore

while running 'bundle / rake db:create'

**Comment by RochesterinNYC** [comment]
Hi, can you provide the generated bundle error report? From the look of your issue title, it seems that the error might stem from Rubygems and not Bundler.

**Comment by yuvasoft** [comment]
Here is the complete details:

--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `/home/yuva/.rvm/gems/ruby-2.0.0-p0@sellrest/bin/bundle `

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what actually happened was...


Error details

    Errno::ENAMETOOLONG: File name too long - .gitignore
.rspec
.travis.yml
CHANGELOG.rdoc
Gemfile
LICENSE.txt
README.md
Rakefile
app/controllers/impressionist_controller.rb
app/models/impression.rb
app/models/impressionist/bots.rb
app/models/impressionist/impressionable.rb
impressionist.gemspec
lib/generators/active_record/impressionist_generator.rb
lib/generators/active_record/templates/create_impressions_table.rb
lib/generators/impressionist_generator.rb
lib/generators/mongo_mapper/impressionist_generator.rb
lib/generators/mongoid/impressionist_generator.rb
lib/generators/templates/impression.rb
lib/impressionist.rb
lib/impressionist/bots.rb
lib/impressionist/controllers/mongoid/impressionist_controller.rb
lib/impressionist/engine.rb
lib/impressionist/models/active_record/impression.rb
lib/impressionist/models/active_record/impressionist/impressionable.rb
lib/impressionist/models/mongo_mapper/impression.rb
lib/impressionist/models/mongo_mapper/impressionist/impressionable.rb
lib/impressionist/models/mongoid/impression.rb
lib/impressionist/models/mongoid/impressionist/impressionable.rb
lib/impressionist/version.rb
logo.png
spec/spec_helper.rb
test_app/.gitignore
test_app/.rspec
test_app/Gemfile
test_app/README
test_app/README.rdoc
test_app/Rakefile
test_app/app/assets/images/rails.png
test_app/app/assets/javascripts/application.js
test_app/app/assets/stylesheets/application.css
test_app/app/controllers/application_controller.rb
test_app/app/controllers/articles_controller.rb
test_app/app/controllers/dummy_controller.rb
test_app/app/controllers/posts_controller.rb
test_app/app/controllers/widgets_controller.rb
test_app/app/helpers/application_helper.rb
test_app/app/mailers/.gitkeep
test_app/app/models/.gitkeep
test_app/app/models/article.rb
test_app/app/models/dummy.rb
test_app/app/models/post.rb
test_app/app/models/user.rb
test_app/app/models/widget.rb
test_app/app/views/articles/index.html.erb
test_app/app/views/articles/show.html.erb
test_app/app/views/dummy/index.html.erb
test_app/app/views/layouts/application.html.erb
test_app/app/views/posts/edit.html.erb
test_app/app/views/posts/index.html.erb
test_app/app/views/posts/show.html.erb
test_app/app/views/widgets/index.html.erb
test_app/app/views/widgets/new.html.erb
test_app/app/views/widgets/show.html.erb
test_app/config.ru
test_app/config/application.rb
test_app/config/boot.rb
test_app/config/cucumber.yml
test_app/config/database.yml
test_app/config/environment.rb
test_app/config/environments/development.rb
test_app/config/environments/pg_test.rb
test_app/config/environments/production.rb
test_app/config/environments/test.rb
test_app/config/initializers/backtrace_silencers.rb
test_app/config/initializers/impression.rb
test_app/config/initializers/inflections.rb
test_app/config/initializers/mime_types.rb
test_app/config/initializers/secret_token.rb
test_app/config/initializers/session_store.rb
test_app/config/initializers/wrap_parameters.rb
test_app/config/locales/en.yml
test_app/config/routes.rb
test_app/db/migrate/20110201153144_create_articles.rb
test_app/db/migrate/20110210205028_create_posts.rb
test_app/db/migrate/20111127184039_create_widgets.rb
test_app/db/seeds.rb
test_app/lib/assets/.gitkeep
test_app/lib/tasks/.gitkeep
test_app/lib/tasks/cucumber.rake
test_app/log/.gitkeep
test_app/public/404.html
test_app/public/422.html
test_app/public/500.html
test_app/public/favicon.ico
test_app/public/images/rails.png
test_app/public/index.html
test_app/public/javascripts/application.js
test_app/public/javascripts/controls.js
test_app/public/javascripts/dragdrop.js
test_app/public/javascripts/effects.js
test_app/public/javascripts/prototype.js
test_app/public/javascripts/rails.js
test_app/public/robots.txt
test_app/public/stylesheets/.gitkeep
test_app/script/cucumber
test_app/script/rails
test_app/spec/controllers/controller_spec.rb
test_app/spec/controllers/impressionist_uniqueness_spec.rb
test_app/spec/fixtures/articles.yml
test_app/spec/fixtures/impressions.yml
test_app/spec/fixtures/posts.yml
test_app/spec/fixtures/widgets.yml
test_app/spec/initializers/initializers_spec.rb
test_app/spec/models/bots_spec.rb
test_app/spec/models/counter_caching_spec.rb
test_app/spec/models/model_spec.rb
test_app/spec/rails_generators/rails_generators_spec.rb
test_app/spec/spec_helper.rb
upgrade_migrations/version_0_3_0.rb
upgrade_migrations/version_0_4_0.rb

      /home/yuva/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/site_ruby/2.0.0/rubygems/specification.rb:2504:in `stat'
      /home/yuva/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/site_ruby/2.0.0/rubygems/specification.rb:2504:in `block in validate_permissions'
      /home/yuva/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/site_ruby/2.0.0/rubygems/specification.rb:2503:in `each'
      /home/yuva/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/site_ruby/2.0.0/rubygems/specification.rb:2503:in `validate_permissions'
      /home/yuva/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/site_ruby/2.0.0/rubygems/specification.rb:2435:in `validate'
      /home/yuva/.rvm/gems/ruby-2.0.0-p0@sellrest/gems/bundler-1.11.2/lib/bundler/rubygems_integration.rb:51:in `block in validate'
      /home/yuva/.rvm/gems/ruby-2.0.0-p0@sellrest/gems/bundler-1.11.2/lib/bundler/ui/shell.rb:80:in `silence'
      /home/yuva/.rvm/gems/ruby-2.0.0-p0@sellrest/gems/bundler-1.11.2/lib/bundler/rubygems_integration.rb:51:in `validate'
      /home/yuva/.rvm/gems/ruby-2.0.0-p0@sellrest/gems/bundler-1.11.2/lib/bundler.rb:346:in `block in load_gemspec_uncached'
      /home/yuva/.rvm/gems/ruby-2.0.0-p0@sellrest/gems/bundler-1.11.2/lib/bundler/shared_helpers.rb:53:in `chdir'
      /home/yuva/.rvm/gems/ruby-2.0.0-p0@sellrest/gems/bundler-1.11.2/lib/bundler/shared_helpers.rb:53:in `block in chdir'
      /home/yuva/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
      /home/yuva/.rvm/gems/ruby-2.0.0-p0@sellrest/gems/bundler-1.11.2/lib/bundler/shared_helpers.rb:52:in `chdir'
      /home/yuva/.rvm/gems/ruby-2.0.0-p0@sellrest/gems/bundler-1.11.2/lib/bundler.rb:339:in `load_gemspec_uncached'
      /home/yuva/.rvm/gems/ruby-2.0.0-p0@sellrest/gems/bundler-1.11.2/lib/bundler.rb:329:in `load_gemspec'
      /home/yuva/.rvm/gems/ruby-2.0.0-p0@sellrest/gems/bundler-1.11.2/lib/bundler/source/path.rb:135:in `block in load_spec_files'
      /home/yuva/.rvm/gems/ruby-2.0.0-p0@sellrest/gems/bundler-1.11.2/lib/bundler/source/path.rb:134:in `each'
      /home/yuva/.rvm/gems/ruby-2.0.0-p0@sellrest/gems/bundler-1.11.2/lib/bundler/source/path.rb:134:in `load_spec_files'
      /home/yuva/.rvm/gems/ruby-2.0.0-p0@sellrest/gems/bundler-1.11.2/lib/bundler/source/git.rb:188:in `load_spec_files'
      /home/yuva/.rvm/gems/ruby-2.0.0-p0@sellrest/gems/bundler-1.11.2/lib/bundler/source/path.rb:92:in `local_specs'
      /home/yuva/.rvm/gems/ruby-2.0.0-p0@sellrest/gems/bundler-1.11.2/lib/bundler/source/git.rb:159:in `specs'
      /home/yuva/.rvm/gems/ruby-2.0.0-p0@sellrest/gems/bundler-1.11.2/lib/bundler/lazy_specification.rb:53:in `__materialize__'
      /home/yuva/.rvm/gems/ruby-2.0.0-p0@sellrest/gems/bundler-1.11.2/lib/bundler/spec_set.rb:90:in `block in materialize'
      /home/yuva/.rvm/gems/ruby-2.0.0-p0@sellrest/gems/bundler-1.11.2/lib/bundler/spec_set.rb:87:in `map!'
      /home/yuva/.rvm/gems/ruby-2.0.0-p0@sellrest/gems/bundler-1.11.2/lib/bundler/spec_set.rb:87:in `materialize'
      /home/yuva/.rvm/gems/ruby-2.0.0-p0@sellrest/gems/bundler-1.11.2/lib/bundler/definition.rb:163:in `missing_specs'
      /home/yuva/.rvm/gems/ruby-2.0.0-p0@sellrest/gems/bundler-1.11.2/lib/bundler/installer.rb:187:in `block in resolve_if_need'
      /home/yuva/.rvm/gems/ruby-2.0.0-p0@sellrest/gems/bundler-1.11.2/lib/bundler/ui/shell.rb:80:in `silence'
      /home/yuva/.rvm/gems/ruby-2.0.0-p0@sellrest/gems/bundler-1.11.2/lib/bundler/installer.rb:184:in `resolve_if_need'
      /home/yuva/.rvm/gems/ruby-2.0.0-p0@sellrest/gems/bundler-1.11.2/lib/bundler/installer.rb:69:in `run'
      /home/yuva/.rvm/gems/ruby-2.0.0-p0@sellrest/gems/bundler-1.11.2/lib/bundler/installer.rb:21:in `install'
      /home/yuva/.rvm/gems/ruby-2.0.0-p0@sellrest/gems/bundler-1.11.2/lib/bundler/cli/install.rb:105:in `run'
      /home/yuva/.rvm/gems/ruby-2.0.0-p0@sellrest/gems/bundler-1.11.2/lib/bundler/cli.rb:172:in `install'
      /home/yuva/.rvm/gems/ruby-2.0.0-p0@sellrest/gems/bundler-1.11.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /home/yuva/.rvm/gems/ruby-2.0.0-p0@sellrest/gems/bundler-1.11.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /home/yuva/.rvm/gems/ruby-2.0.0-p0@sellrest/gems/bundler-1.11.2/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /home/yuva/.rvm/gems/ruby-2.0.0-p0@sellrest/gems/bundler-1.11.2/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /home/yuva/.rvm/gems/ruby-2.0.0-p0@sellrest/gems/bundler-1.11.2/lib/bundler/cli.rb:10:in `start'
      /home/yuva/.rvm/gems/ruby-2.0.0-p0@sellrest/gems/bundler-1.11.2/exe/bundle:19:in `block in <top (required)>'
      /home/yuva/.rvm/gems/ruby-2.0.0-p0@sellrest/gems/bundler-1.11.2/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
      /home/yuva/.rvm/gems/ruby-2.0.0-p0@sellrest/gems/bundler-1.11.2/exe/bundle:17:in `<top (required)>'
      /home/yuva/.rvm/gems/ruby-2.0.0-p0@sellrest/bin/bundle:19:in `load'
      /home/yuva/.rvm/gems/ruby-2.0.0-p0@sellrest/bin/bundle:19:in `<main>'
      /home/yuva/.rvm/gems/ruby-2.0.0-p0@sellrest/bin/ruby_executable_hooks:15:in `eval'
      /home/yuva/.rvm/gems/ruby-2.0.0-p0@sellrest/bin/ruby_executable_hooks:15:in `<main>'

Environment

    Bundler   1.11.2
    Rubygems  2.0.0.rc.2
    Ruby      2.0.0p0 (2013-02-24 revision 39474) [i686-linux]
    GEM_HOME  /home/yuva/Desktop/payal/Valeda/sellrestvaleda/vendor/bundle/ruby/2.0.0
    GEM_PATH  
    RVM       1.25.30 (stable)
    Git       1.7.9.5

Bundler settings

    gem.test
      Set for the current user (/home/yuva/.bundle/config): "false"
    gem.mit
      Set for the current user (/home/yuva/.bundle/config): "true"
    gem.coc
      Set for the current user (/home/yuva/.bundle/config): "true"
    cache_all
      Set for your local app (/home/yuva/Desktop/payal/Valeda/sellrestvaleda/.bundle/config): "true"
    frozen
      Set for your local app (/home/yuva/Desktop/payal/Valeda/sellrestvaleda/.bundle/config): "1"
    path
      Set for your local app (/home/yuva/Desktop/payal/Valeda/sellrestvaleda/.bundle/config): "vendor/bundle"
    disable_shared_gems
      Set for your local app (/home/yuva/Desktop/payal/Valeda/sellrestvaleda/.bundle/config): "1"
--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/bundler/bundler/search?q=File+name+too+long+-+.gitignore&type=Issues

If there aren't any reports for this error yet, please create copy and paste the report template above into a new issue. Don't forget to anonymize any private data! The new issue form is located at:
https://github.com/bundler/bundler/issues/new

**Comment by segiddins** [comment]
Can you please add your Gemfile to that error report as well?

**Comment by yuvasoft** [comment]
This is GemFile:

source 'https://rubygems.org'

gem 'rails', '~> 4.0.5'

# dalli for cache
gem 'dalli'
gem 'devise', :git => 'git://github.com/plataformatec/devise.git', :branch => 'master'
gem "authority", "~> 2.6.0"
gem 'sqlite3'
gem "paperclip", "~> 3.5"
gem "fog", "~> 1.19.0"
gem 'country_select'
gem "make_flaggable", github: 'medihack/make_flaggable', :ref => 'd7309'
gem 'sidekiq'
gem "capistrano-sidekiq"

gem 'ruby-graphviz', :require => 'graphviz'
gem 'geokit'
gem 'geokit-rails'

#twitter for blog
gem 'twitter'
#seo-friendly-urls
gem 'friendly_id', '~> 5.0.0'

# Admin Interface
gem 'ransack', github: 'ernie/ransack', branch: 'master'
gem 'inherited_resources', github:'josevalim/inherited_resources', branch: 'master'
gem 'activeadmin', github: 'gregbell/active_admin', branch: 'master'
gem 'gibbon'

# Impressions
gem 'impressionist', :github => 'bennick/impressionist', :branch => 'rails_4'

# Log events
gem 'event_logger'

# Cron jobs
gem 'whenever', :require => false

# CC Processing
gem "twocheckout", "~> 0.1.4"


gem 'coffee-rails', '~> 4.0.0'
gem 'sass-rails',   '~> 4.0.0'
gem 'haml-rails'
gem 'haml', '~> 4.0'
gem 'formtastic', github: 'justinfrench/formtastic', branch: 'master'
  gem 'uglifier', '>= 1.0.3'


# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'


# Build JSON APIs with ease.
gem "active_model_serializers"

# Modernizr for stupid IE
gem "modernizr-rails"

# Bootstrap
gem 'bootstrap-sass', '~> 2.3.2.1'

# Font-Awesome for icons
gem 'font-awesome-rails'


group :development do

# LocalTunnel
 # gem "localtunnel", "~> 0.3"
  # Dev Errors
  gem "better_errors"
  gem 'binding_of_caller'
  gem 'meta_request'

  gem 'pry-rails'
  

  gem 'awesome_print'
  gem 'guard-rspec'
  gem 'hirb'
end

group :test, :development do
  gem "rspec-rails", "~> 2.14.2"
  gem "rb-fsevent"
  gem 'capybara'
  gem 'database_cleaner', "~> 1.0.1" 
  gem 'selenium-webdriver'
  gem "factory_girl_rails", "~> 4.0"
  gem "faker", "~> 1.1.2"
  gem 'shoulda-matchers', "1.4.0"
end
group :production, :staging do
  gem 'mysql2'
end
# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano', group: :development
gem 'capistrano'
gem 'rvm-capistrano', :require => false
# To use debugger
# gem 'debugger'

# Application Monitoring
gem 'newrelic_rpm'

**Comment by segiddins** [comment]
```
Bundler could not find compatible versions for gem "railties":
  In Gemfile:
    coffee-rails (~> 4.0.0) was resolved to 4.0.1, which depends on
      railties (< 5.0, >= 4.0.0)

    coffee-rails (~> 4.0.0) was resolved to 4.0.1, which depends on
      railties (< 5.0, >= 4.0.0)

    devise was resolved to 4.0.0.rc2, which depends on
      railties (< 5.1, >= 4.1.0)

    factory_girl_rails (~> 4.0) was resolved to 4.6.0, which depends on
      railties (>= 3.0.0)

    activeadmin was resolved to 1.0.0.pre2, which depends on
      inherited_resources (~> 1.6) was resolved to 1.6.0, which depends on
        railties (< 5, >= 3.2)

    rails (~> 4.0.5) was resolved to 4.0.5, which depends on
      railties (= 4.0.5)

    rspec-rails (~> 2.14.2) was resolved to 2.14.2, which depends on
      railties (>= 3.0)
```

**Comment by segiddins** [comment]
The issue you originally reported seems to be with `impressionist`, and I cannot reproduce that issue

**Comment by segiddins** [comment]
Closing due to lack of response.
