### ISSUE TITLE
Bad hostname

### ISSUE THREAD

**Issue by mano92fuentes** [bundler/bundler#4424]
How can I set m.fuentes@l.m.cu  as the user and maraa  as the password in a proxy authentification

the scheme http does not accept registry part: m.fuentes@lab.matcom.uh.cu:mariateresa@10.6.100.71 (or bad hostname?)

**Comment by sstern6** [comment]
@mano92fuentes have you looked here?

http://stackoverflow.com/questions/3877055/how-to-use-bundler-behind-a-proxy

or 

http://stackoverflow.com/questions/18213242/how-to-use-rails-bundler-behind-a-proxy-network

**Comment by LynnCo** [comment]
Think its safe to assume @mano92fuentes resolved this issue, closing
