### ISSUE TITLE
Add support for `--without` in `bundle check`?

### ISSUE THREAD

**Issue by orta** [bundler/bundler#4426]
A relatively common pattern to save time on CI is to run something like:

```sh
bundle check  || bundle install 
```

However it's possible to have a subset of the gems in your `Gemfile` installed when using `--without`, this means that a check like the following:

``` sh
bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3 --without development
```

Will [always fail](https://github.com/artsy/eigen/pull/1383#discussion_r58343670), as gems from the development group would not be present - thus negating the `bundle check`. My assumption when [amending](https://github.com/artsy/eigen/pull/1383/commits/523b38c7001a18dd82f65bf5f5985665bfacce1a)  our CI was that I could apply the same `--without` to `bundle check` too. Make sense?

**Comment by segiddins** [comment]
You can run `bundle config without` before check / install

**Comment by LynnCo** [comment]
I'm assuming your issue was solved with the previous comment @orta, and closing this. Will re-open if you think its still needed

**Comment by orta** [comment]
That's hard to say, from a user's perspective - I still think it's the option should be exposed on the command line, but @segiddins' technique was enough to not need it once I asked. The choice of closed is the bundler team's 👍

**Comment by thedrow** [comment]
I also think that --without should be a supported option for check.

**Comment by keith** [comment]
You can also use the `BUNDLE_WITHOUT=group` env var to do this
