### ISSUE TITLE
GC overhead limit exceeded

### ISSUE THREAD

**Issue by SeanRoy** [bundler/bundler#4427]
> bundle install
WARN: Unresolved specs during Gem::Specification.reset:
      ffi (>= 0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
Warning: this Gemfile contains multiple primary sources. Using `source` more than once without a block is a security risk, and may result in installing unexpected gems. To resolve this warning, use a block to indicate which gems should come from the secondary source. To upgrade this warning to an error, run `bundle config disable_multisource true`.
Fetching source index from http://rails-assets.org/
Fetching source index from http://rails-assets.org/
Fetching source index from https://gems.contribsys.com/
Fetching source index from https://rubygems.org/
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `/home/sean/.rbenv/versions/jruby-1.7.16/bin/bundler `

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what actually happened was...

Error details

    Java::JavaLang::OutOfMemoryError: GC overhead limit exceeded
      org.jruby.RubyArray.newArray(RubyArray.java:160)
      org.jruby.RubyArray.newArray(RubyArray.java:175)
      org.jruby.Ruby.newArray(Ruby.java:3251)
      rubyjit.Bundler::Index$$search_by_spec_82a6d52fd3e5dc22c2e8bb689686b6713c9c06011115085362.__file__(/home/sean/.rbenv/versions/jruby-1.7.16/lib/ruby/gems/shared/gems/bundler-1.11.2/lib/bundler/index.rb:181)
      rubyjit.Bundler::Index$$search_by_spec_82a6d52fd3e5dc22c2e8bb689686b6713c9c06011115085362.__file__(/home/sean/.rbenv/versions/jruby-1.7.16/lib/ruby/gems/shared/gems/bundler-1.11.2/lib/bundler/index.rb)
      org.jruby.internal.runtime.methods.JittedMethod.call(JittedMethod.java:181)
      org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)
      org.jruby.ast.FCallOneArgNode.interpret(FCallOneArgNode.java:36)
      org.jruby.ast.DAsgnNode.interpret(DAsgnNode.java:110)
      org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
      org.jruby.ast.AndNode.interpret(AndNode.java:93)
      org.jruby.ast.IfNode.interpret(IfNode.java:110)
      org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
      org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
      org.jruby.evaluator.ASTInterpreter.INTERPRET_BLOCK(ASTInterpreter.java:112)
      org.jruby.runtime.Interpreted19Block.evalBlockBody(Interpreted19Block.java:206)
      org.jruby.runtime.Interpreted19Block.yield(Interpreted19Block.java:157)
      org.jruby.runtime.Block.yield(Block.java:142)
      org.jruby.RubyArray.eachCommon(RubyArray.java:1606)
      org.jruby.RubyArray.each(RubyArray.java:1613)
      org.jruby.RubyArray$INVOKER$i$0$0$each.call(RubyArray$INVOKER$i$0$0$each.gen)
      org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:143)
      org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:149)
      org.jruby.ast.CallNoArgBlockPassNode.interpret(CallNoArgBlockPassNode.java:53)
      org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
      org.jruby.evaluator.ASTInterpreter.INTERPRET_BLOCK(ASTInterpreter.java:112)
      org.jruby.runtime.Interpreted19Block.evalBlockBody(Interpreted19Block.java:206)
      org.jruby.runtime.Interpreted19Block.yield(Interpreted19Block.java:157)
      org.jruby.runtime.Block.yield(Block.java:142)
      org.jruby.RubyArray.eachCommon(RubyArray.java:1606)
      org.jruby.RubyArray.each(RubyArray.java:1613)
      org.jruby.RubyArray$INVOKER$i$0$0$each.call(RubyArray$INVOKER$i$0$0$each.gen)

Environment

    Bundler   1.11.2
    Rubygems  2.1.9
    Ruby      1.9.3p392 (2014-09-25 revision 39386) [java]
    GEM_HOME  /home/sean/.rbenv/versions/jruby-1.7.16/lib/ruby/gems/shared
    GEM_PATH  /home/sean/.rbenv/versions/jruby-1.7.16/lib/ruby/gems/shared:/home/sean/.gem/jruby/1.9
    Git       1.9.1
--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/bundler/bundler/search?q=GC+overhead+limit+exceeded&type=Issues

If there aren't any reports for this error yet, please create copy and paste the report template above into a new issue. Don't forget to anonymize any private data! The new issue form is located at:
https://github.com/bundler/bundler/issues/new

**Comment by segiddins** [comment]
Can you also try with the latest RubyGems (2.6.3)? Bundler can do some things to decrease memory usage as of RubyGems 2.5.

**Comment by LynnCo** [comment]
Ping @SeanRoy is this still an issue?

**Comment by RochesterinNYC** [comment]
Closing due to lack of response. Please let us know if there are any updates or additional relevant info.

**Comment by jmatraszek** [comment]
Hi,
I am not the OP, but this is still a bug for me. Updated rubygems to 2.6.4. Happens only in my Jenkins installation (using rbenv):

```
+ gem --version

2.6.4
+ bundle install --binstubs

Warning: the running version of Bundler is older than the version that created the lockfile. We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.

Fetching source index from https://rubygems.org/

--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `/opt/jenkins/.rbenv/versions/jruby-1.7.20/bin/bundle install --binstubs`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what actually happened was...


Error details

    Java::JavaLang::OutOfMemoryError: GC overhead limit exceeded
      org.jruby.util.ByteList.<init>(ByteList.java:91)
      org.jruby.RubyString.newStringLight(RubyString.java:500)
      rubyjit.Bundler::Index$$\=\^\^_c02bd7836228bb0981d11651e47eb9ebb9837d2f1028566121.__file__(/opt/jenkins/.rbenv/versions/jruby-1.7.20/lib/ruby/gems/shared/gems/bundler-1.11.2/lib/bundler/index.rb:91)
      rubyjit.Bundler::Index$$\=\^\^_c02bd7836228bb0981d11651e47eb9ebb9837d2f1028566121.__file__(/opt/jenkins/.rbenv/versions/jruby-1.7.20/lib/ruby/gems/shared/gems/bundler-1.11.2/lib/bundler/index.rb)
      org.jruby.internal.runtime.methods.JittedMethod.call(JittedMethod.java:181)
      org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)
      org.jruby.runtime.callsite.ShiftLeftCallSite.call(ShiftLeftCallSite.java:24)
      org.jruby.ast.CallOneArgNode.interpret(CallOneArgNode.java:57)
      org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
      org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
      org.jruby.evaluator.ASTInterpreter.INTERPRET_BLOCK(ASTInterpreter.java:112)
      org.jruby.runtime.Interpreted19Block.evalBlockBody(Interpreted19Block.java:206)
      org.jruby.runtime.Interpreted19Block.yield(Interpreted19Block.java:157)
      org.jruby.runtime.Block.yield(Block.java:142)
      org.jruby.RubyArray.eachCommon(RubyArray.java:1606)
      org.jruby.RubyArray.each(RubyArray.java:1613)
      org.jruby.RubyArray$INVOKER$i$0$0$each.call(RubyArray$INVOKER$i$0$0$each.gen)
      org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:316)
      org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:145)
      org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:154)
      org.jruby.ast.CallNoArgBlockNode.interpret(CallNoArgBlockNode.java:64)
      org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
      org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
      org.jruby.ast.RescueNode.executeBody(RescueNode.java:221)
      org.jruby.ast.RescueNode.interpret(RescueNode.java:116)
      org.jruby.ast.EnsureNode.interpret(EnsureNode.java:96)
      org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)
      org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:225)
      org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:219)
      org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:346)
      org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:204)
      org.jruby.ast.FCallTwoArgNode.interpret(FCallTwoArgNode.java:38)

Environment

    Bundler   1.11.2
    Rubygems  2.6.4
    Ruby      1.9.3p551 (2015-05-04 revision 48406) [java]
    GEM_HOME  /opt/jenkins/.rbenv/versions/jruby-1.7.20/lib/ruby/gems/shared
    GEM_PATH  /opt/jenkins/.rbenv/versions/jruby-1.7.20/lib/ruby/gems/shared:/opt/jenkins/.gem/jruby/1.9
    Git       1.7.1

Bundler settings

    bin
      Set for your local app (/opt/jenkins/workspace/ICLS - Build WEB DEV RPM/.bundle/config): "bin"
--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.
```

**Comment by ogibayashi** [comment]
Hello,

I also encountered this issue with jruby
* jruby both 9.1.2.0 / 1.7.25
* rubygems: 2.6.4
* bundler 1.12.5

`JRUBY_OPTS='-X-C -J-Xmx1024m -J-XX:+UseConcMarkSweepGC'` worked for me.
