### ISSUE TITLE
Gem list not showing all the gems

### ISSUE THREAD

**Issue by ravi-juhomi** [bundler/bundler#4428]
Hi I have deployed my code through capistrano, so by default it will bundle install the gem file in specific path which i mentioned in my deploy.rb file where these gems should be installed. Once the deployment done and when i check the folder,  gems are there but when i do gem list gems not showing, at the same time when i do bundle show it shows all the gems with using prefix. 

Help will be appriciated and i had stuck up for last 2 days with this....

**Comment by jbodah** [comment]
I believe you're looking for "bundle list"

**Comment by ravi-juhomi** [comment]
@jbodah thanks for your reply. Ya bundle list shows all gems but when i use any gem for a command like rake db:migrate it says "**The program 'rake' is currently not installed. You can install it by typing:**" which means gem is not installed but how can it be possible to display the gem in bundle list.

**Comment by jbodah** [comment]
I believe Capistrano generally deploys your gems to the vendor repo so they are local to your deploy revision. These won't get picked up by the gem command by default because they aren't in your default gem path. You'll want to use "bundle exec rake" which should add the vendor repo to your gem path and make the gem usable

**Comment by ravi-juhomi** [comment]
so you are saying like i have to go to project folder and run the command **bundle exec rake**  right ?

**Comment by jbodah** [comment]
Yes, I believe that should work for you

**Comment by ravi-juhomi** [comment]
@jbodah Thanks for your suggestions i figured out the reason for why gems not showing in gem list. after fixing that when i do **bundle exec rake db:migrate** i get error like rake aborted and no method error source_index for gem module. I googled and got some suggestions like gem update --system 1.8.25 and i tried that too... but did not work out ...what could be reason for this error....

**Comment by jbodah** [comment]
@ravi-juhomi Is that the exact error you're getting? The line you posted should be updating RubyGems. I wouldn't specify the version when you're updating RubyGems (1.8.x seems pretty old)

https://github.com/rubygems/rubygems#description

Assuming that `Gem` is where the error is coming from, I'd just run a straight `gem update --system`

**Comment by ravi-juhomi** [comment]
Hi, the command which you mentioned gem update it worked fine.

Now i am getting some new issue, when i install git using capistrano from my local machine to my new ubuntu server it says

"/home/ubuntu/.rvm/bin/rvm-shell: No such file or directory" what would be the reason. just now i lanuched the new server. Does it comes because of my local machine rvm problem ?

**Comment by jbodah** [comment]
This seems to be moving outside the scope of bundler now, but I'd check to see if the path you listed exists. You may have to install rvm on your deploy host

**Comment by TimMoore** [comment]
It doesn't sound like there's a Bundler bug here, so I'll close the issue now.
