### ISSUE TITLE
error when creating new rails projects, "Permission denied"

### ISSUE THREAD

**Issue by mbr84** [bundler/bundler#4429]
Here is the error report template:

Error details

    Errno::EACCES: Permission denied @ rb_sysopen - /Users/username/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/versions
      /Users/username/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.12.0.rc/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:32:in `initialize'
      /Users/username/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.12.0.rc/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:32:in `open'
      /Users/username/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.12.0.rc/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:32:in `open'
      /Users/username/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.12.0.rc/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:32:in `update'
      /Users/username/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.12.0.rc/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:63:in `update'
      /Users/username/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.12.0.rc/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:54:in `update_and_parse_checksums!'
      /Users/username/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.12.0.rc/lib/bundler/fetcher/compact_index.rb:63:in `available?'
      /Users/username/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.12.0.rc/lib/bundler/fetcher/compact_index.rb:15:in `call'
      /Users/username/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.12.0.rc/lib/bundler/fetcher/compact_index.rb:15:in `block in compact_index_request'
      /Users/username/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.12.0.rc/lib/bundler/fetcher.rb:154:in `use_api'
      /Users/username/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.12.0.rc/lib/bundler/source/rubygems.rb:331:in `block in api_fetchers'
      /Users/username/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.12.0.rc/lib/bundler/source/rubygems.rb:331:in `select'
      /Users/username/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.12.0.rc/lib/bundler/source/rubygems.rb:331:in `api_fetchers'
      /Users/username/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.12.0.rc/lib/bundler/source/rubygems.rb:336:in `block in remote_specs'
      /Users/username/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.12.0.rc/lib/bundler/index.rb:10:in `build'
      /Users/username/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.12.0.rc/lib/bundler/source/rubygems.rb:335:in `remote_specs'
      /Users/username/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.12.0.rc/lib/bundler/source/rubygems.rb:82:in `specs'
      /Users/username/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.12.0.rc/lib/bundler/definition.rb:211:in `block (2 levels) in index'
      /Users/username/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.12.0.rc/lib/bundler/definition.rb:209:in `each'
      /Users/username/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.12.0.rc/lib/bundler/definition.rb:209:in `block in index'
      /Users/username/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.12.0.rc/lib/bundler/index.rb:10:in `build'
      /Users/username/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.12.0.rc/lib/bundler/definition.rb:206:in `index'
      /Users/username/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.12.0.rc/lib/bundler/definition.rb:200:in `resolve'
      /Users/username/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.12.0.rc/lib/bundler/definition.rb:140:in `specs'
      /Users/username/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.12.0.rc/lib/bundler/definition.rb:129:in `resolve_remotely!'
      /Users/username/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.12.0.rc/lib/bundler/installer.rb:195:in `resolve_if_need'
      /Users/username/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.12.0.rc/lib/bundler/installer.rb:70:in `run'
      /Users/username/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.12.0.rc/lib/bundler/installer.rb:22:in `install'
      /usr/local/Cellar/rbenv/1.0.0/rbenv.d/exec/gem-rehash/rubygems_plugin.rb:27:in `install'
      /Users/username/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.12.0.rc/lib/bundler/cli/install.rb:102:in `run'
      /Users/username/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.12.0.rc/lib/bundler/cli.rb:175:in `install'
      /Users/username/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.12.0.rc/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /Users/username/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.12.0.rc/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /Users/username/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.12.0.rc/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /Users/username/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.12.0.rc/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /Users/username/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.12.0.rc/lib/bundler/cli.rb:11:in `start'
      /Users/username/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.12.0.rc/exe/bundle:27:in `block in <main>'
      /Users/username/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.12.0.rc/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
      /Users/username/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.12.0.rc/exe/bundle:19:in `<main>'

Environment
      
  Bundler   1.12.0.rc
  Rubygems  2.6.3
  Ruby      2.1.2p95 (2014-05-08 revision 45877) [x86_64-darwin15.0]
  GEM_HOME  /Users/username/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0
  GEM_PATH  /Users/username/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0:/Users/username/.gem/ruby/2.1.0
  Git       2.8.1
      
      Bundler settings
      
  orig_path
    Set via BUNDLE_ORIG_PATH: "/Users/username/.rbenv/versions/2.1.2/bin:/usr/local/Cellar/rbenv/1.0.0/libexec:/Users/username/.rbenv/shims:/Users/username/.rbenv/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/username/.rvm/bin"

**Comment by RochesterinNYC** [comment]
Do you have the correct file permissions on the file or directories listed in: `/Users/username/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/versions` ?

**Comment by mbr84** [comment]
I think I figured it out. I think bundler was installed to the root
directory. Uninstalling and reinstalling fixed the issue. Thanks for the
great reply time
