### ISSUE TITLE
Fix installation instructions

### ISSUE THREAD

**Issue by aragnon** [bundler/bundler#4433]
The instructions on your website are not valid. 

You claim the following:
```
Getting started with bundler is easy! Open a terminal window and run this command:

$ gem install bundler

```

However, reality disagrees with you:

```
gem install bundler
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions into the /var/lib/gems/1.9.1 directory.
```

Annoying if reality doesn't match your fantasy, isn't it? 

I don't particularly care about some random person suggesting something; I just want you to fix the website, such that the instructions are actually correct. 

Alternatively, you can also state that bundler is abandonware and has no maintainers.

**Comment by segiddins** [comment]
@aragnon it looks like you may need to use `sudo` since you don't have write permissions for your gem home.

Additionally, the tone of your ticket isn't very friendly, just a heads up. We take time out of our days to help our users, and being passive-agressive is a poor way to say thank you for that.

**Comment by aragnon** [comment]
Funny you mention that; the way I see it is that you are lying in your marketing material and are wasting my time.

**Comment by aragnon** [comment]
And, incidentally, you apparently failed to understand my remarks. I specifically said that I was *not* interested in some random person suggesting something. Except, that's *exactly* what you did, wasting more of my time.

**Comment by segiddins** [comment]
Except I'm not some 'random person', I'm one of Bundler's maintainers. Sorry that the bundler tool and the bundler website, which are both free for you, don't live up to your standards.

**Comment by aragnon** [comment]
Sorry, anyone who distributes such a blatantly broken tool is a random person to me.

**Comment by aragnon** [comment]
You failed to fix the issue.

**Comment by aragnon** [comment]
You are free to close the issue once it is fixed.

**Comment by indirect** [comment]
@aragnon Hi. I'm the Bundler team lead. Tickets on this project are covered by [a code of conduct](https://github.com/bundler/bundler/blob/master/CODE_OF_CONDUCT.md), and you are not following it. This is your final warning—any further code of conduct violations will result in a ban.

**Comment by segiddins** [comment]
@aragnon this is your last warning. Please treat people with respect in our issue tracker, otherwise we'll have to ask you to leave. I have given you a potential workaround for your setup, even though your original ticket was ignoring the instructions in our contributing guidelines and likely in violation of our code of conduct.

**Comment by aragnon** [comment]
@indirect, @sarahduve How about you shove that code of conduct you have written yourself up your arse? You are fucking pathetic that you don't just fix an issue when it is reported. 

Do you think I care for one second about your opinion? I do not care about people who cannot fix the software they have written themselves; as far as I am concerned, you are a cancer, because you spread code which does not work.

**Comment by segiddins** [comment]
@aragnon since you have not heeded the warning, we will be forced to block you from the Bundler GitHub organization, sorry.
