### ISSUE TITLE
.bundle/config gets written with CRLF line endings on Windows

### ISSUE THREAD

**Issue by perlun** [bundler/bundler#4435]
This is a problem in my case, since `BUNDLE_PATH` will then contain a ^M at the end, so `bundler install` will create a folder with a ^M in it... :smile:

(This is when using `bundler` on Windows 10 with msys2)

I think the only sane approach would be to _always_ write to `.bundle/config` with LF-only line endings. That's the only universal approach that will work everywhere.

This has the downside that people using e.g. Notepad on Windows will not be able to read the file. I think we can live with that; you should be using better editors than Notepad anyway.

**Comment by indirect** [comment]
Ugh, what a bug. Thanks for pointing this out. Since this is already out in the wild, we will need to add handling for either \n or \r\n linebreaks.

**Comment by perlun** [comment]
Perhaps converting \r\n to \n when reading the file is simplest.

To avoid "dirty files" in git (when switching between Windows and Unix/OSX for the same working copy), writing the file with \n would also be nice. But like you say, handling it properly (when reading the file) is probably most important.

If you point me to the relevant code I might be able to lend a helping hand.
