### ISSUE TITLE
RBX bundle install consumes gigabytes of memory

### ISSUE THREAD

**Issue by deadeyejoe** [bundler/bundler#4444]
I'm trying to deploy a rails app, running the following command:

`bundle install --local`

And bundler exits saying it's been killed. I've watched the process in top and it appears to be consuming 3GB+ of memory. Some things to note:
- I'm using rbx-3.21
- I'm running it on an ec2 t2.medium instance (4GB memory), there's a 1GB swap file on the machine too.
- There are ~250 gems in the bundle
- I'm using packaged gems (i.e. I've run `bundle package --all` etc).

Is there anything that can be done to mitigate this? I was under the impression that using packaged gems would be quicker/more efficient?

output of `bundler env` is in this [gist](https://gist.github.com/deadeyejoe/639ed5c85a2b5693da4228813429fbb9) along with the output from `dmesg` saying the process has been killed.

**Comment by deadeyejoe** [comment]
Additional information:

I've just reprovisioned the machine, deleted the vendor/cache directory, and run a plain old `bundle install`. It still runs out of memory, but gets much further than the previous command.

**Comment by segiddins** [comment]
Whats the output of `bundle install --verbose`?

**Comment by deadeyejoe** [comment]
I've updated the [gist](https://gist.github.com/deadeyejoe/639ed5c85a2b5693da4228813429fbb9) with the output of both `bundle install --verbose` and `bundle install --local --verbose`.

Interestingly the `bundle install --verbose` command managed to finish. It was still consuming a similar amount of memory though.

**Comment by segiddins** [comment]
My guess here is the GC is keeping the raw contents of too many `.gem` files in memory at once, but I have no way of confirming that

**Comment by colby-swandale** [comment]
This issue has not been active for a long time. If this is still an issue then feel free to open a new issue that uses the latest version of Bundler.
