### ISSUE TITLE
Bundle outdates gives incorrect results sometimes

### ISSUE THREAD

**Issue by deivid-rodriguez** [bundler/bundler#4450]
I noticed this strange problem.

With this `Gemfile`

```ruby
source 'https://rubygems.org'

gem 'pry', github: 'pry'
```

all good...

```shell
$ bundle outdated 
Fetching git://github.com/pry/pry.git
Fetching gem metadata from https://rubygems.org/..........
Fetching version metadata from https://rubygems.org/..
Resolving dependencies...

Bundle up to date!
```

But with this other Gemfile

```ruby
source 'https://rubygems.org'

gem 'pry', github: 'pry'
gem 'travis', '~> 1.8'
```

`pry` gem gets incorrectly reported as outdated.

```shell
$ bundle outdated
Fetching git://github.com/pry/pry.git
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies...

Outdated gems included in the bundle:
  * pry (newest 0.10.3, installed 0.10.3 f5c97ca) in group "default"
  * typhoeus (newest 1.0.1, installed 0.8.0)
```

Refs: https://github.com/pry/pry/pull/1510

**Comment by segiddins** [comment]
Is it possible there's a newer commit on master than the one you've pinned to in your lockfile?

**Comment by deivid-rodriguez** [comment]
No, it happens with the latest commit in pry's master.

**Comment by segiddins** [comment]
@RochesterinNYC any interest in taking a look at this?

**Comment by RochesterinNYC** [comment]
Yup, I'll take a look later. @deivid-rodriguez Can you post the results of `bundle env`?

**Comment by deivid-rodriguez** [comment]
Of course.

```shell
$ bundle env
Environment

    Bundler   1.12.0.rc.2
    Rubygems  2.6.3
    Ruby      2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]
    GEM_HOME  /home/deivid/.gem/ruby/2.3.0
    GEM_PATH  /home/deivid/.gem/ruby/2.3.0:/home/deivid/.rubies/ruby-2.3.0/lib/ruby/gems/2.3.0
    Git       2.8.1

Bundler settings

    orig_path
      Set via BUNDLE_ORIG_PATH: "/home/deivid/.gem/ruby/2.3.0/bin:/home/deivid/.rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/bin:/home/deivid/.rubies/ruby-2.3.0/bin:/home/deivid/.local/bin:/home/deivid/.cabal/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/go/bin"
    orig_gem_path
      Set via BUNDLE_ORIG_GEM_PATH: "/home/deivid/.gem/ruby/2.3.0:/home/deivid/.rubies/ruby-2.3.0/lib/ruby/gems/2.3.0"

Gemfile

    source 'https://rubygems.org'
    
    gem 'pry', github: 'pry'
    gem 'travis', '~> 1.8'

Gemfile.lock

    GIT
      remote: git://github.com/pry/pry.git
      revision: f5c97cac103a9f04b854ed5b117a8cc27c7e8dd6
      specs:
        pry (0.10.3)
          coderay (~> 1.1.0)
          method_source (~> 0.8.1)
    
    GEM
      remote: https://rubygems.org/
      specs:
        addressable (2.4.0)
        backports (3.6.8)
        coderay (1.1.1)
        ethon (0.8.1)
          ffi (>= 1.3.0)
        faraday (0.9.2)
          multipart-post (>= 1.2, < 3)
        faraday_middleware (0.10.0)
          faraday (>= 0.7.4, < 0.10)
        ffi (1.9.10)
        gh (0.14.0)
          addressable
          backports
          faraday (~> 0.8)
          multi_json (~> 1.0)
          net-http-persistent (>= 2.7)
          net-http-pipeline
        highline (1.7.8)
        json (1.8.3)
        launchy (2.4.3)
          addressable (~> 2.3)
        method_source (0.8.2)
        multi_json (1.11.2)
        multipart-post (2.0.0)
        net-http-persistent (2.9.4)
        net-http-pipeline (1.0.1)
        pusher-client (0.6.2)
          json
          websocket (~> 1.0)
        travis (1.8.2)
          backports
          faraday (~> 0.9)
          faraday_middleware (~> 0.9, >= 0.9.1)
          gh (~> 0.13)
          highline (~> 1.6)
          launchy (~> 2.1)
          pusher-client (~> 0.4)
          typhoeus (~> 0.6, >= 0.6.8)
        typhoeus (0.8.0)
          ethon (>= 0.8.0)
        websocket (1.2.3)
    
    PLATFORMS
      ruby
    
    DEPENDENCIES
      pry!
      travis (~> 1.8)
    
    BUNDLED WITH
       1.12.0.rc.2
```

**Comment by deivid-rodriguez** [comment]
@RochesterinNYC Did you have a chance to have a look? Thank you!!

**Comment by RochesterinNYC** [comment]
@deivid-rodriguez Hm, I'm unable to reproduce in the exact manner. Getting the following output with the first `Gemfile`:

```
$ dbundle outdated
Fetching git://github.com/pry/pry.git
Fetching source index from https://rubygems.org/
Resolving dependencies....

Outdated gems included in the bundle:
  * pry (newest 0.10.3, installed 0.10.3 f5c97ca) in group "default"
```

**Comment by deivid-rodriguez** [comment]
@RochesterinNYC mmmm, weird, no? I'll investigate my environment to try to figure out what's going on. In any case, the output you get is unexpected too, right?

**Comment by RochesterinNYC** [comment]
@deivid-rodriguez it'd be nice to get exact reproduction but yes, I do agree that something might be odd or possibly incorrect with the UX here.

**Comment by RochesterinNYC** [comment]
I've looked into this and the cause of the problem seems to be this: https://github.com/bundler/bundler/blob/master/lib/bundler/cli/outdated.rb#L53-L57

The spec that is being set to `active_spec` and used for comparison for `bundle outdated` is a gemspec with platform `java` and does not seem to have a `git_version`. The spec before that in the ordered array of `pry` gemspecs is the correct `Gem::Specification` that has a platform of `ruby`.

Thanks for this bug report, I think this uncovered a larger bug as a whole with `bundle outdated`, in that it will show pending updates for a gem regardless of what platform you're currently using the gem with. I.e. if you're using gem `duradura` on platform java with version `v1.0.1`, and the latest java platform version of this gem is `v1.0.1` but the latest ruby platform version of this gem is `v1.0.2`, `bundle outdated` will tell you that you can update `duradura` to `v1.0.2`.

**Comment by deivid-rodriguez** [comment]
@RochesterinNYC Thanks for looking into this!

This issue has this "more-information-needed" label but I'm not sure whether you actually need any more info. Anyways, I just tried this on a empty Ruby `2.3.1` bundle and got the exact same results as I originally reported. In case that might help.

**Comment by RochesterinNYC** [comment]
Yup, I think I have enough information here. Though, what do you mean by an an empty Ruby bundle? An empty Gemfile? A Gemfile that's not supposed to have any updates?

**Comment by LynnCo** [comment]
(I'm reorganizing the issues and there are bound to be tons of false positives, sorry about that)

**Comment by deivid-rodriguez** [comment]
@LynnCo No worries!

@RochesterinNYC Oh, sorry about my inaccuracy, language problems :) I mean a fresh Ruby installation where the only gems installed are the ones involved in this issue.

**Comment by RochesterinNYC** [comment]
@deivid-rodriguez this should be fixed now on master branch of bundler.

**Comment by deivid-rodriguez** [comment]
Thanks, looking forward for a release!
