### ISSUE TITLE
Minimum Ruby version

### ISSUE THREAD

**Issue by moore3071** [bundler/bundler#4452]
### Suggested feature

-Allow for setting a minimum ruby version at least to the minor version number in the gemfile. This would be very helpful when working with a cross-distro group that doesn't want to use rvm (an Arch user with a Debian user pulling from pacman's repos and dpkg for their respective Ruby packages).

_I believe this relates to #4160 but I'm unfortunately staring in as an end-user currently and not as a developer, and thus am unsure of the underlying restrictions in Ruby and the gem system._

**Comment by bronzdoc** [comment]
Hi @moore3071 can you open an issue with this feature at https://github.com/bundler/bundler-features thanks!

**Comment by e2** [comment]
A link for anyone who got: https://github.com/bundler/bundler-features/issues/119

**Comment by shraddha-bhadauria** [comment]
I recently upgraded to Ruby 2.6.0 from 2.5.2.
I had real tough time installing ruby 2.6.0
Now i have 2.6.0, 2.6.1 and 2.5.2 versions on my system. 
However, now when I run rake db:migrate, i get the following error.
 
rbenv: version `ruby-2.6.0' is not installed

Also, when i run  `bundle env`
rbenv: version `ruby-2.6.0' is not installed (set by /Users/XXXXXXX/assign2/.ruby-version)

**Comment by deivid-rodriguez** [comment]
Hi @shraddha-bhadauria, this is most likely not a bundler issue but I problem with your ruby installation. Try `rbenv versions` to see which versions `rbenv` can actually see. If ruby-2.6.0 is not there, there was probably a problem with installing 2.6.0 and you should reinstall it.

**Comment by shraddha-bhadauria** [comment]
Looks like i messed up with two versions. And i need to run the command `source /Users/username/.rvm/scripts/rvm`, for every session.

**Comment by deivid-rodriguez** [comment]
Ugh, maybe your version managers are tripping up each other. You should choose either [rbenv](https://github.com/rbenv/rbenv) or [rvm](https://github.com/rvm/rvm), and completely remove the other one from your system.

**Comment by shraddha-bhadauria** [comment]
Yup, understood that... would do the same.
