### ISSUE TITLE
Use the gem hash to throw an exception on mismatch

### ISSUE THREAD

**Issue by lynnco** [bundler/bundler#4464]
From here https://github.com/bundler/bundler/issues/4461#issuecomment-214003067

The index format includes a hash of the gem contents, bundler can check those vs local to see if the content is mismatched

**Comment by indirect** [comment]
I don't actually know if this is done... we might need to re-open this for the time being?

**Comment by LynnCo** [comment]
Oh, ha, I closed this one because I was gonna move it to Bundler-features, but not that stuff is gonna be moved *here* so I'm glad you caught this

**Comment by indirect** [comment]
👍
