### ISSUE TITLE
Show better errors when failing to `require`

### ISSUE THREAD

**Issue by westoque** [bundler/bundler#4466]
I am using bundler with `foreman` and when I run a task such as `foreman run bin/rails c` it shows the error:

```
/Users/westoque/.rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler/runtime.rb:82:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'bulk_insert'. (Bundler::GemRequireError)
```

Upon further investigation in `Bundler::Runtime#require` and `puts`-ing the error, the actual error was:

```
#<RuntimeError: Database URL cannot be empty>
```

I think the error should be included in the exception message itself so I would not be confused as to where the issue was. From first look, it seemed to be a bundler problem but in reality was not.

Thanks.

**Comment by RochesterinNYC** [comment]
Does #4187 fix this behavior? Could you try with the latest Bundler version (`v1.12.0.rc.4`) and see if the error message is more helpful?

**Comment by westoque** [comment]
@RochesterinNYC confirmed that #4187 does fix the behavior. Thanks.
