### ISSUE TITLE
Errno::ECONNRESET not being caught and retried?

### ISSUE THREAD

**Issue by suan** [bundler/bundler#4468]
We're seeing instances of
```
Gem::RemoteFetcher::FetchError: Errno::ECONNRESET: Connection reset by peer - SSL_connect (https://rubygems.org/gems/multi_json-1.11.2.gem)
An error occurred while installing multi_json (1.11.2), and Bundler cannot
continue.
```
even though we're calling `bundle install` with `--retry=3` (full Chef command is:)
```
sudo su - deploy -c 'cd /srv/www/someapp/releases/20160423042438 && /usr/local/bin/bundle install --path /home/deploy/.bundler/orders --without=development test noci --retry=3' 2>&1
```

We're using bundler 1.10.6, which I understand is not the latest, but looking at the changelog retrying for this error class should already be present in that version. Also unlike https://github.com/bundler/bundler/issues/3717 we don't have any custom Ruby in our Gemfile.

**Comment by segiddins** [comment]
Can you check if this is fixed by the 1.12 release candidate?  Thanks!

**Comment by suan** [comment]
@segiddins I'll try to upgrade in our various environments and report back

**Comment by RochesterinNYC** [comment]
@suan any update on this?

**Comment by suan** [comment]
I don't think I've seen it happen since the new release, tho I think I've seen a different but similar error since. I'll close this issue and maybe create a separate one
