### ISSUE TITLE
Strange error at 'run -> bundle install' time

### ISSUE THREAD

**Issue by romozart** [bundler/bundler#4473]
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?
  I ran the command `C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/exe/bundle install`

- What did you expect to happen?
  I expected Bundler to install gems properly

- What happened instead?
  Instead, the following error was thrown

Error details

    SyntaxError: C:/Ruby22/lib/ruby/site_ruby/devkit.rb:13: syntax error, unexpected '<', expecting end-of-input
<% tool_names.each_pair do |k,v| -%>

 ^
      C:/Ruby22/lib/ruby/2.2.0/rubygems/defaults/operating_system.rb:3:in `load'
      C:/Ruby22/lib/ruby/2.2.0/rubygems/defaults/operating_system.rb:3:in `block in <top (required)>'
      C:/Ruby22/lib/ruby/2.2.0/rubygems/installer.rb:275:in `call'
      C:/Ruby22/lib/ruby/2.2.0/rubygems/installer.rb:275:in `block in run_pre_install_hooks'
      C:/Ruby22/lib/ruby/2.2.0/rubygems/installer.rb:274:in `each'
      C:/Ruby22/lib/ruby/2.2.0/rubygems/installer.rb:274:in `run_pre_install_hooks'
      C:/Ruby22/lib/ruby/2.2.0/rubygems/installer.rb:235:in `install'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/source/rubygems.rb:142:in `block in install'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/rubygems_integration.rb:151:in `preserve_paths'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/source/rubygems.rb:134:in `install'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/installer/gem_installer.rb:56:in `install'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/installer/gem_installer.rb:14:in `install_from_spec'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/installer/parallel_installer.rb:90:in `block in worker_pool'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/worker.rb:55:in `call'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/worker.rb:55:in `apply_func'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/worker.rb:50:in `block in process_queue'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/worker.rb:47:in `loop'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/worker.rb:47:in `process_queue'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/worker.rb:22:in `block (2 levels) in initialize'

Environment

    Bundler   1.11.2
    Rubygems  2.4.5.1
    Ruby      2.2.4p230 (2015-12-16 revision 53155) [i386-mingw32]
    GEM_HOME  C:/Ruby22/lib/ruby/gems/2.2.0
    GEM_PATH  C:/Ruby22/lib/ruby/gems/2.2.0;C:/Users/USER/.gem/ruby/2.2.0
    Git       2.7.4.windows.1
--- TEMPLATE END ----------------------------------------------------------------

Could anyone please shed some light on it?

Thank you very much in advance!

**Comment by TimMoore** [comment]
@romozart please try @rgb-one's suggestions from this similar issue: https://github.com/bundler/bundler/issues/4176#issuecomment-166040150

> It is recommended that you install ruby version 2.1.X on the RubyInstaller website because it is stable and provides a wider range of supported packages; maybe you could give that a try as well as install the corresponding DevKit for that version of Ruby.

**Comment by romozart** [comment]
Now for some unknown reason the message I get at "run -> bundle install" is:
"Checksum of /versions does not match the checksum provided by server! Something
is wrong."

I might just uninstall Ruby and Rails and start from scratch. Any reason I shouldn't do that and "fix" this instead?

**Comment by romozart** [comment]
Issue fixed...
Thanks @TimMoore very much for the help!

**Comment by segiddins** [comment]
Should be fixed in 1.12.1!
