### ISSUE TITLE
Repository contains zero padded file modes

### ISSUE THREAD

**Issue by MarkVillacampa** [bundler/bundler#4475]
When I have this in my `.gitconfig`

```
[transfer] 
        fsckobjects = false
[fetch] 
        fsckobjects = false
[receive] 
        fsckObjects = false
```

And try to clone the repository, I get:

```
Cloning into 'bundler'...
remote: Counting objects: 55341, done.
remote: Compressing objects: 100% (21/21), done.
error: object 6f2d5934ff01d3d7d6a4dcad3063299c17f08fdc: zeroPaddedFilemode: contains zero-padded file modes
fatal: Error in object
fatal: index-pack failed
```

As a workaround I simply set those flags to false.

Here's some information on how to potentially fix this issue:

http://stackoverflow.com/questions/14700502/how-to-fix-git-zero-padded-file-modes-warning

This is issue is not a showstopper or priority, but just wanted to document it in an issue in case someone experiences it.

**Comment by RochesterinNYC** [comment]
Thanks for the issue @MarkVillacampa. I don't think we can fix this from a Bundler maintenance end as, if I'm understanding the fix correctly, it would result in the rewriting of a lot of SHAs and we can't really force push over all the old relevant commits. As a result, I'm closing this issue but thank you for including this fix and the context in the Bundler issues. If it becomes a more common pain point, maybe a reference or mention in the DEVELOPMENT docs could become a possibility.

**Comment by patcon** [comment]
just hit the same thing for the same commit object

**Comment by Roguelazer** [comment]
I ran into this today; for what it's worth, more and more environments are enabling `fetch.fsckObjects` for security reasons and it's kind of frustrating that this repo can't be safely cloned without disabling some of git's security checks...

Maybe at least it's worth putting something in the README?
