### ISSUE TITLE
bundle exec CMD --help opens bundler man-page

### ISSUE THREAD

**Issue by dziemba** [bundler/bundler#4480]
When running `bundle exec rspec --help` on bundler 1.11.2 it displays the help output of RSpec, as expected. 

Running the same command on bundler 1.12.0 opens the bundler-exec man page and completely ignores the specified command.

For some reason it works for the `bundler` command, only `bundle` is affected.

Some more examples:

```bash
# these work as expected
bundle exec rspec --version
bundle exec rspec -- --version
bundle exec rspec
bundler exec rspec --help

# these don't work
bundle exec rspec --help
bundle exec rspec -- --help
bundle exec this_will_never_be_executed_anyway --help
bundle exec this_will_never_be_executed_anyway -- --help
```

To reproduce it:
```dockerfile
FROM ubuntu:16.04
RUN apt-get update && apt-get install -y ruby
RUN gem install bundler -v 1.12.0
```

```bash
docker build -t bundler-test .

# works as expected (says no Gemfile)
docker run bundler-test bundler exec foobar --help

# opens the man-page
docker run bundler-test bundle exec foobar --help
```

**Comment by RochesterinNYC** [comment]
Hi @dziemba, thanks for the issue. I believe this was introduced in #4178. While having `--help` go to the man pages for all the other Bundler commands makes sense (I.e. `bundle package --help` goes to the man page for bundle package), I do agree that following that behavior for `bundle exec` might feel weird and unexpected. 

Are there any other Bundler commands you as a user might feel the `--help` redirect behavior is unexpected for?

**Comment by RochesterinNYC** [comment]
Also. I'm assigning this issue and fix to one of our Google Summer of Code students: @b-ggs
