### ISSUE TITLE
Bundle run as user with no home directory fails

### ISSUE THREAD

**Issue by ianbamforth** [bundler/bundler#4481]
Previously I could run a command like `sudo -u homelessuser bundle install`, and the .bundle directory would be created in whatever directory I was currently in.  Now it appears that the `$HOME` variable is used as the working directory - a homeless user doesn't set this, so it carries over from the user running the command.

**Comment by segiddins** [comment]
Can you please share the issue template describing how bundler fails in this circumstance? Thanks!

**Comment by ianbamforth** [comment]
Ok, running as jenkins (a user with sudo provileges, and $HOME set to /home/jenkins), attempting to install `smartstack` as a homeless user `smartstack`, the command `sudo su - smartstack bundle install smartstack` exits with code `23` and message `STDOUT: There was an error while trying to write to
`/home/jenkins/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47`.
It is likely that you need to grant write permissions for that path.`.

**Comment by ianbamforth** [comment]
For info, I'm using the Airbnb smartstack cookbook.

**Comment by segiddins** [comment]
Hm, so we need to store the new index caches somewhere, so currently that's in the user's home directory, just like where bundler global settings are stored -- I can't really think of a way around requiring a $HOME.

**Comment by ianbamforth** [comment]
I suppose either the cwd, or something in $TMP would be ok?

**Comment by segiddins** [comment]
but those wouldn't be user-global locations, which is what we need

**Comment by ianbamforth** [comment]
Sorry, I am not that familiar with bundler - why do you require (and what is) a user-global location?  Do you mean a location that is both persistent and unique to a user?

**Comment by segiddins** [comment]
Yes

**Comment by ianbamforth** [comment]
Is the .bundle directory required after an install completes, or is it purely a cache for speeding up the next install? For users with no home directory it wouldn't be unreasonable to drop the persistence requirement would it?

**Comment by segiddins** [comment]
Well, the global settings file is needed if you ever run `bundle config --global` and the whole point of the new index is that it utilizes caching to speed up installation and reduce load on our servers.

**Comment by ianbamforth** [comment]
I see your point.  Wonder how other projects handle this - it should be a solved problem really.  Plenty of other tools cache stuff in a user's home directory.

**Comment by LynnCo** [comment]
Seems like in the case of a homeless user we should rescue from the write error, and use cwd / tmp for the sake of not having the install fail

**Comment by segiddins** [comment]
@LynnCo but that would totally break persisted global configurations and make `bundle install` obnoxiously slow

**Comment by LynnCo** [comment]
@segiddins show a warning about how not having a home set makes installs dramatically slower, but then proceed with the install anyway? That's what I would want as a user

**Comment by segiddins** [comment]
But that's not what we want as the people who run the servers

**Comment by LynnCo** [comment]
Ahhhhh, gotcha

**Comment by alovak** [comment]
We use ```bundle install``` only once when we create server image (we use 'immutable servers' approach). So cache is useless for such cases. Slow means works for us. You can speed up things only if you do bundle install more than 1 time. The same is mentioned here #4489

@segiddins

**Comment by duelinmarkers** [comment]
In an automated CI environment where deployment artifacts are being built, we try to avoid having anything tied to a certain user by not setting `HOME` and/or `USER`. We now (with bundler 1.12.1) have builds failing because (it appears) the build is trying to write the index cache to `/.bundle/...` (file-system root). If we could override the location of the index cache with an extra command-line argument, rather than having bundler assume those ENV vars are available, it seems like that would fix our issue and allow us to point at a location that would persist from build to build, which would be good for your servers.

**Comment by indirect** [comment]
I believe that using `$CWD/.bundle` is the correct answer if `$HOME` is not set.

**Comment by indirect** [comment]
(Allowing the "user level" bundler settings directory to be set in a config option and ENV var also seems completely reasonable to me, and like we should do it.)

**Comment by mexisme** [comment]
NB:
Have found running `bundle package --all` from our build machine, and deploying the zipped-up dir has gotten around the issue.

**Comment by stiller-leser** [comment]
This also appears to be a problem during the AWS OpsWorks setup, since bundler is trying to write to `/root/.bundle/cache/compact_index/` which it can't access, resulting in failed setup routines here.

**Comment by lynnco** [comment]
> I believe that using $CWD/.bundle is the correct answer if $HOME is not set.

I believe this was addressed by either https://github.com/bundler/bundler/pull/4951 or https://github.com/bundler/bundler/pull/4531? I'm closing this now, but please re-open it if that is not the case!

**Comment by abiacco** [comment]
I ran across this in bundler 1.14.6.
So what's the proper way now to change the dir being used?
I'm using jenkins war under a tomcat install and i don't allow writability on the tomcat home directory, though i do have a writable temp subdirectory under the tomcat home i could use.
I'm doing a bundle install from vendor/cache on every build.
So would it be kosher to do (in my jenkins build script): HOME=<tomcat_home>/temp bundle install?

Thanks

**Comment by nejweti** [comment]
you can run `source ~/.bash_profile` first and proceed.
