### ISSUE TITLE
Problem running bundle install after upgrading Rails 2 to Rails 3.0 

### ISSUE THREAD

**Issue by blimey74** [bundler/bundler#4484]
- What did you do?

  I ran the command `/home/xxxx/.rvm/gems/ruby-1.9.3-p551@caf_rails3/bin/bundle install`

- What did you expect to happen?

  I expected Bundler to install all gems specified in my Gemfile

- What happened instead?

  I got the error below, I should also mention that I'm running this on a Virtual Box guest running Centos 6.7, the host is running Ubuntu 14.04

Error details

    NoMethodError: undefined method `payload' for nil:NilClass
      /home/xxxx/.rvm/gems/ruby-1.9.3-p551@caf_rails3/gems/bundler-1.12.0/lib/bundler/resolver.rb:303:in `block in sort_dependencies'
      /home/xxxx/.rvm/gems/ruby-1.9.3-p551@caf_rails3/gems/bundler-1.12.0/lib/bundler/resolver.rb:300:in `each'
      /home/xxxx/.rvm/gems/ruby-1.9.3-p551@caf_rails3/gems/bundler-1.12.0/lib/bundler/resolver.rb:300:in `sort_by'
      /home/xxxx/.rvm/gems/ruby-1.9.3-p551@caf_rails3/gems/bundler-1.12.0/lib/bundler/resolver.rb:300:in `sort_dependencies'
      /home/xxxx/.rvm/gems/ruby-1.9.3-p551@caf_rails3/gems/bundler-1.12.0/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:131:in `block (2 levels) in <class:Resolution>'
      /home/xxxx/.rvm/gems/ruby-1.9.3-p551@caf_rails3/gems/bundler-1.12.0/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:431:in `push_state_for_requirements'
      /home/xxxx/.rvm/gems/ruby-1.9.3-p551@caf_rails3/gems/bundler-1.12.0/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:423:in `require_nested_dependencies_for'
      /home/xxxx/.rvm/gems/ruby-1.9.3-p551@caf_rails3/gems/bundler-1.12.0/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:411:in `activate_spec'
      /home/xxxx/.rvm/gems/ruby-1.9.3-p551@caf_rails3/gems/bundler-1.12.0/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:376:in `attempt_to_activate_new_spec'
      /home/xxxx/.rvm/gems/ruby-1.9.3-p551@caf_rails3/gems/bundler-1.12.0/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:320:in `attempt_to_activate'
      /home/xxxx/.rvm/gems/ruby-1.9.3-p551@caf_rails3/gems/bundler-1.12.0/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:147:in `process_topmost_state'
      /home/xxxx/.rvm/gems/ruby-1.9.3-p551@caf_rails3/gems/bundler-1.12.0/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:72:in `resolve'
      /home/xxxx/.rvm/gems/ruby-1.9.3-p551@caf_rails3/gems/bundler-1.12.0/lib/bundler/vendor/molinillo/lib/molinillo/resolver.rb:38:in `resolve'
      /home/xxxx/.rvm/gems/ruby-1.9.3-p551@caf_rails3/gems/bundler-1.12.0/lib/bundler/resolver.rb:201:in `start'
      /home/xxxx/.rvm/gems/ruby-1.9.3-p551@caf_rails3/gems/bundler-1.12.0/lib/bundler/resolver.rb:184:in `resolve'
      /home/xxxx/.rvm/gems/ruby-1.9.3-p551@caf_rails3/gems/bundler-1.12.0/lib/bundler/definition.rb:200:in `resolve'
      /home/xxxx/.rvm/gems/ruby-1.9.3-p551@caf_rails3/gems/bundler-1.12.0/lib/bundler/definition.rb:140:in `specs'
      /home/xxxx/.rvm/gems/ruby-1.9.3-p551@caf_rails3/gems/bundler-1.12.0/lib/bundler/definition.rb:129:in `resolve_remotely!'
      /home/xxxx/.rvm/gems/ruby-1.9.3-p551@caf_rails3/gems/bundler-1.12.0/lib/bundler/installer.rb:195:in `resolve_if_need'
      /home/xxxx/.rvm/gems/ruby-1.9.3-p551@caf_rails3/gems/bundler-1.12.0/lib/bundler/installer.rb:70:in `run'
      /home/xxxx/.rvm/gems/ruby-1.9.3-p551@caf_rails3/gems/bundler-1.12.0/lib/bundler/installer.rb:22:in `install'
      /home/xxxx/.rvm/gems/ruby-1.9.3-p551@caf_rails3/gems/bundler-1.12.0/lib/bundler/cli/install.rb:102:in `run'
      /home/xxxx/.rvm/gems/ruby-1.9.3-p551@caf_rails3/gems/bundler-1.12.0/lib/bundler/cli.rb:175:in `install'
      /home/xxxx/.rvm/gems/ruby-1.9.3-p551@caf_rails3/gems/bundler-1.12.0/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /home/xxxx/.rvm/gems/ruby-1.9.3-p551@caf_rails3/gems/bundler-1.12.0/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /home/xxxx/.rvm/gems/ruby-1.9.3-p551@caf_rails3/gems/bundler-1.12.0/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /home/xxxx/.rvm/gems/ruby-1.9.3-p551@caf_rails3/gems/bundler-1.12.0/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /home/xxxx/.rvm/gems/ruby-1.9.3-p551@caf_rails3/gems/bundler-1.12.0/lib/bundler/cli.rb:11:in `start'
      /home/xxxx/.rvm/gems/ruby-1.9.3-p551@caf_rails3/gems/bundler-1.12.0/exe/bundle:27:in `block in <top (required)>'
      /home/xxxx/.rvm/gems/ruby-1.9.3-p551@caf_rails3/gems/bundler-1.12.0/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
      /home/xxxx/.rvm/gems/ruby-1.9.3-p551@caf_rails3/gems/bundler-1.12.0/exe/bundle:19:in `<top (required)>'
      /home/xxxx/.rvm/gems/ruby-1.9.3-p551@caf_rails3/bin/bundle:22:in `load'
      /home/xxxx/.rvm/gems/ruby-1.9.3-p551@caf_rails3/bin/bundle:22:in `<main>'
      /home/xxxx/.rvm/gems/ruby-1.9.3-p551@caf_rails3/bin/ruby_executable_hooks:15:in `eval'
      /home/xxxx/.rvm/gems/ruby-1.9.3-p551@caf_rails3/bin/ruby_executable_hooks:15:in `<main>'

Environment
      
  Bundler   1.12.0
  Rubygems  2.6.4
  Ruby      1.9.3p551 (2014-11-13 revision 48407) [x86_64-linux]
  GEM_HOME  /home/xxxx/.rvm/gems/ruby-1.9.3-p551@caf_rails3
  GEM_PATH  /home/xxxx/.rvm/gems/ruby-1.9.3-p551@caf_rails3:/home/xxxx/.rvm/gems/ruby-1.9.3-p551@global
  RVM       1.27.0 (latest)
  Git       1.7.12.4
  Host:   Virtual Box guest running Centos 6.7 on Ubuntu 14.04 host machine
      
      Bundler settings
      
  orig_path
    Set via BUNDLE_ORIG_PATH: "/home/xxxx/.rvm/gems/ruby-1.9.3-p551@caf_rails3/bin:/home/xxxx/.rvm/gems/ruby-1.9.3-p551@global/bin:/home/xxxx/.rvm/rubies/ruby-1.9.3-p551/bin:/home/xxxx/.rvm/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/home/xxxx/bin:/home/xxxx/bin:/home/xxxx/bin"
  orig_gem_path
    Set via BUNDLE_ORIG_GEM_PATH: "/home/xxxx/.rvm/gems/ruby-1.9.3-p551@caf_rails3:/home/xxxx/.rvm/gems/ruby-1.9.3-p551@global"

**Comment by segiddins** [comment]
This has already been fixed by https://github.com/CocoaPods/Molinillo/pull/38, it just needs a new release of Molinillo.

**Comment by blimey74** [comment]
OK thanks for the rapid response...how can I configure bundler to pick up the version of molinillo with this fix? Sorry I'm a bit of a Ruby newbie so out of my depth here.

**Comment by segiddins** [comment]
You can't, at the moment, but the issue has been fixed upstream which will make its way into a bundler release eventually.

**Comment by blimey74** [comment]
OK just so I can let my boss know, do you have any idea when the next bundler release with this fix might be?

**Comment by segiddins** [comment]
No clue

**Comment by blimey74** [comment]
OK thanks for the help

**Comment by segiddins** [comment]
Fix should be present in 1.12.1

**Comment by blimey74** [comment]
Brilliant - thanks for telling me!
