### ISSUE TITLE
bundle exec makes $0==__FILE__ comparison fail in v1.12.0

### ISSUE THREAD

**Issue by manlon** [bundler/bundler#4488]
I have a script that relies on the `$0 == __FILE__` trick to determine if it is being run at the top level:
```
$ cat test.rb
#!/usr/bin/env ruby
if $0 == __FILE__
  puts "ok #{$0}"
else
  puts "mismatch! #{$0} != #{__FILE__}"
end
```
With bundler v1.11.2
```
$ bundle exec ./test.rb                                                                                                                                       
ok ./test.rb
```
With 1.12.0
```
$ bundle exec ./test.rb
mismatch! ./test.rb != /home/vagrant/test.rb
````
I.e., `__FILE__` is expanded, breaking `bundle exec` for such scripts.

**Comment by segiddins** [comment]
Ah so we need to File.expand_path before setting `$0`. Should be an easy fix

**Comment by manlon** [comment]
Expanding $0 would fix my particular issue, but note the previous behavior was that the values are the same as the way the script is invoked from the command line (as it is for a ruby script without bundler). Not sure what else might depend on this behavior.

**Comment by segiddins** [comment]
Ah gotcha... it's because we're `load`ing the absolute path :/

**Comment by indirect** [comment]
I think we need the path to be relative from `Dir.pwd` at exec time?

**Comment by segiddins** [comment]
So I dug into this, and it only seems to happen when you invoke with a `./`. I have no idea how to fix it, since it's `Kernel.load` itself that's turning that into an absolute path

**Comment by segiddins** [comment]
This is pretty much unfixable, see https://github.com/bundler/bundler/issues/4491 for reasons why (also, discrepancies between ruby versions complicate things)

**Comment by yob** [comment]
We ran into this today too, so I thought I'd add another use case to the discussion.

We still use delayed job with a few rails apps, and use the process names in our monitoring setup to ensure the worker processes are running. The worker processes are started with `bundle exec rake jobs:work`

With bundler 1.11.2, the process name looked like this:

```
$ ps ux | grep rake
jh        1758 62.2  2.4 385816 202032 pts/3   Sl+  16:16   0:04 ruby /home/jh/.rbenv/versions/2.2.4/bin/rake jobs:work
```

With bundler 1.12.1, the process name looks like this:

```
$ ps ux | grep rake
jh        2036 78.8  2.1 356688 172660 pts/3   Sl+  16:16   0:03 /home/jh/.rbenv/versions/2.2.4/bin/rake
```
The new version doesn't include the rake name, so we can't easily detect which rake processes are our job workers.

**Comment by segiddins** [comment]
@yob that could be worked around by calling `Process.setproctitle`, if you have any interest in making a PR

**Comment by yob** [comment]
Thanks @segiddins. I had a go at modifying `lib/bundler/cli/exec.rb` today, and something very simple would suit our purposes:

```diff
diff --git a/lib/bundler/cli/exec.rb b/lib/bundler/cli/exec.rb
index 00e42c9..f1eb61a 100644
--- a/lib/bundler/cli/exec.rb
+++ b/lib/bundler/cli/exec.rb
@@ -57,6 +57,7 @@ module Bundler
       args.pop if args.last.is_a?(Hash)
       ARGV.replace(args)
       $0 = file
+      Process.setproctitle(process_title(file, *args))
       ui = Bundler.ui
       Bundler.ui = nil
       require "bundler/setup"
@@ -70,6 +71,14 @@ module Bundler
       abort "#{e.class}: #{e.message}\n  #{backtrace.join("\n  ")}"
     end
 
+    def process_title(file, *args)
+      if args.empty?
+        file
+      else
+        "#{file} #{args.join(' ')}"
+      end
+    end
+
``` 
It looks like  `spec/commands/exec_spec.rb` is the appropriate place to spec the change, and this context looks promising: 

    "`load`ing a ruby file instead of `exec`ing"

Those specs appear to create a temporary script and Gemfile, then execute the script and inspect stdout, stderr, status code, etc. I think I'd need to include the process name in the test script stdout, but I'm not sure how to do that in a cross-platform manner. Can I shell out to `ps`? If only there was a `Process.title` method....

**Comment by segiddins** [comment]
Seems reasonable to me?

**Comment by indirect** [comment]
@segiddins I looked at #4491, and I still don't understand why fixing this is impossible... can you explain with words instead of code?

**Comment by segiddins** [comment]
@indirect iirc it had to do with __FILE__ and $0 not being able to align when called via ./foo

**Comment by lynnco** [comment]
Resolved with https://github.com/bundler/bundler/pull/4863
