### ISSUE TITLE
User context being persisted in bundler in 1.12 in puzzling way

### ISSUE THREAD

**Issue by frightenedmonkey** [bundler/bundler#4489]
Our infrastructure uses chef for configuration management. Today, I ran into permissions errors for bundler when trying to spin up new cloud instances. The error is the standard gem cache error when the user that executes bundler doesn't have correct file permissions set. The root of the problem seems to be that the the $HOME of the user that initially kicks of a process that eventually runs `bundle install` will be assumed to be the user that wants to run the `bundle install`, even if the user that executes the `bundle install is a different user.

The context: we use chef-solo on our instances. The root user will execute chef, and we have a recipe that will execute a `bundle install {with-some-options}` as the `nagios` user. The recipe is failing due to the `nagios` user being unable to access `/root/.bundle/cache/compact_index/rubygems.org.443.{snip}`. I assumed this was due to a problem in our cookbooks, so I investigated. However, running chef-solo from *my user* on the nodes using `sudo chef-solo` resulted in the same permissions error, but for *my* user:
```
There was an error while trying to write to
`/home/michael/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47`.
It is likely that you need to grant write permissions for that path.
```

Forcing a downgrade to 1.11.2 on the instance cleared up the problem with no other changes.

I haven't spent the time investigating how bundler is resolving that far back up the process execution context. My best guess is that bundler is grabbing the HOME environment variable, and that that is somehow being persisted down through the execution context from the original user. Unfortunately, I haven't had time to actually spend time spelunking through the codebase to validate that assumption. And I'll admit it's probably a fairly naïve assumption.

**Comment by RochesterinNYC** [comment]
This sounds somewhat related to #4481 in terms of $HOME environment variable usage.
