### ISSUE TITLE
gem update fail bundler 1.12.1

### ISSUE THREAD

**Issue by Sega100500** [bundler/bundler#4492]
$ gem update
fail:
```
Updating bundler
ERROR:  Error installing bundler:
        Unable to resolve dependency: user requested 'bundler (= 1.12.1)'
```
$ gem install bundler -v 1.12.1
fail:
```
ERROR:  Could not find a valid gem 'bundler' (= 1.12.1) in any repository
ERROR:  Possible alternatives: bundler
```

Ruby 2.3.1
installed bundler 1.12.0

**Comment by deepj** [comment]
The same issue here

**Comment by mwrock** [comment]
I have been having this same issue. Oddly gem fetch bundler retrieves an installble version of bundler 1.12.1
```
gem fetch bundler
gem install bundler
```
Then `gem install bundler` installs 1.12.1. But if I then uninstall it, delete the gem file and run `gem install bundler` again, it retrieves 1.12.10.

**Comment by segiddins** [comment]
Known issue with the bundler api, we're working on mitigating as we speak

**Comment by segiddins** [comment]
We've now fixed this, sorry for the inconvenience!

**Comment by mwrock** [comment]
Is there an accompanying issue or PR that would explain what was happening there?

I'm just curious what was the real issue in more detail for my own educational purposes. Thanks!

**Comment by segiddins** [comment]
https://github.com/bundler/bundler-api/pull/164, https://github.com/bundler/bundler-api/pull/156, https://github.com/bundler/bundler-api/pull/160, https://github.com/bundler/bundler-api/pull/161
