### ISSUE TITLE
Cannot package xcodeproj gem with v1.12.1 on Travis CI

### ISSUE THREAD

**Issue by alykhank** [bundler/bundler#4494]
After v1.12.1 was released, our use of `bundle package --no-install` on Travis CI began to fail with the error check added in #3896. The same steps still work when using v1.11.2.

Our use case is that we create a ZIP/TAR distribution that is provided to users, and within that distribution there is a Ruby script that gets executed by our code. The Ruby script requires the xcodeproj gem, but we do not want to require the user connect to RubyGems nor have to install xcodeproj somewhere on their system. We achieve this by setting `GEM_HOME` and `GEM_PATH`, using `gem install --local --no-rdoc --no-ri xcodeproj-*.gem` to install the gem within our distribution directory, and running our script. If there is a better way to perform this whole procedure, please let us know!

To accomplish this, we bundle the xcodeproj gem and its dependencies into `.gem` files using `bundle package --no-install` with the following `Gemfile`:

```ruby
source 'https://rubygems.org'
gem 'xcodeproj', '~> 0.28.2'
```

On our development machines, this works with both Bundler v1.11.2 and v1.12.1. On Travis CI, this works with v1.11.2 but fails with v1.12.1.

To reproduce the behaviour in a Docker container ([after installing Docker Engine](https://docs.docker.com/engine/installation/)), perform the following steps:

1. `docker run -it quay.io/travisci/travis-jvm /bin/bash` (Note: this has to download a ~5GB image)
2. `su - travis`
3. `rvm install 2.3.0`
4. Download `bundler-1.12.1-package.sh` from https://gist.github.com/alykhank/e64fc110c27797c569ca60d7c81e51f2 (also contains the output of `bundle env`)
5. `chmod u+x bundler-1.12.1-package.sh`
6. `./bundler-1.12.1-package.sh`

Fails with the output displayed in the Gist comments.

Using Bundler v1.11.2 for the same purpose works fine:

```
gem install bundler -v 1.11.2
bundle _1.11.2_ package --no-install

# Fetching gem metadata from https://rubygems.org/................
# Fetching version metadata from https://rubygems.org/..
# Resolving dependencies...
# Using json 1.8.3
# Using bundler 1.11.2
# Bundle complete! 1 Gemfile dependency, 10 gems now installed.
# Use `bundle show [gemname]` to see where a bundled gem is installed.
# Updating files in vendor/cache
#   * i18n-0.7.0.gem
#   * json-1.8.3.gem
#   * minitest-5.8.4.gem
#   * thread_safe-0.3.5.gem
#   * tzinfo-1.2.2.gem
#   * activesupport-4.2.6.gem
#   * claide-0.9.1.gem
#   * colored-1.2.gem
#   * xcodeproj-0.28.2.gem
```

**Comment by indirect** [comment]
The relevant error message is:

```
# json-1.8.3 is built in to Ruby, and can't be cached because your Gemfile doesn't have any sources that contain it.
# Missing gem file 'json-1.8.3.gem'.
```

This error is definitely a bug, since your `Gemfile` does have rubygems.org inside it. Thanks for reporting this!

**Comment by mokhan** [comment]
Is the proper workaround for this to rollback to bundler 1.11.2?

**Comment by indirect** [comment]
@segiddins @rochesterinnyc any theories about this one?

**Comment by segiddins** [comment]
Nope, someone else will have to debug since I don't have docker set up

**Comment by RochesterinNYC** [comment]
I'll take a look at it sometime soon.

**Comment by hbd225** [comment]
It seems like Bundler::Fetcher::CompactIndex returns specs setting nil to `ruby` platform so that Bundler::Index can't find spec correctly.
But I'm not sure why...:sweat:

![screen shot 2016-05-11 at 06 18 29](https://cloud.githubusercontent.com/assets/6078076/15163072/640d3906-1741-11e6-9767-e1678f66cedd.png)

**Comment by segiddins** [comment]
https://github.com/bundler/bundler/pull/4558 might fix this

**Comment by hbd225** [comment]
I confirmed bundler v1.12.4 fixed this issue.
