### ISSUE TITLE
Suggest `--full-index` on new index failures or missing gems

### ISSUE THREAD

**Issue by indirect** [bundler/bundler#4496]
While we're getting all the kinks worked out of the compact index, we should suggest that users try adding `--full-index` to their command when there's a missing gem (especially if that gem is locked).

Relatedly, we should fall back to the full index (or at least the dependency API?) anytime there's a 4xx or 5xx response from the compact index server.

**Comment by LynnCo** [comment]
Related! https://github.com/bundler/bundler/issues/4384

**Comment by segiddins** [comment]
We already have automatic fallback through the list of different fetchers, I think that should be sufficient?
