### ISSUE TITLE
Possible CDN issue for new gem index for "inspec" gem

### ISSUE THREAD

**Issue by danielsdeleo** [bundler/bundler#4497]
Given a simple gemfile like this:

```ruby
source "https://rubygems.org"

gem "inspec", "~> 0.20.1"
```

I'm getting:

```
bundle install       
Fetching gem metadata from https://rubygems.org/
Fetching version metadata from https://rubygems.org/
Could not find inspec-0.20.1 in any of the sources
```

The same gemfile works fine with 1.11.x of bundler. I originally thought this had something to do with windows/not windows, but my windows machines are in Azure and my machines that do not see this problem are elsewhere, so it could be a CDN issue instead. I can repro the issue on a Windows VM and on my host OS (OS X) on my laptop.

Also, I've found that version 0.20.1 is not included if I navigate to https://index.rubygems.org/info/inspec in a browser (tried chrome and safari), but for whatever reason, I do see it if I fetch the data with curl.

**Comment by segiddins** [comment]
This issue really belongs over on the bundler/bundler-api repo

**Comment by danielsdeleo** [comment]
Ok, I didn't know that existed, moved to https://github.com/bundler/bundler-api/issues/167
