### ISSUE TITLE
Alias `bundle COMMAND --help` to `bundle help COMMAND`

### ISSUE THREAD

**Issue by LynnCo** [bundler/bundler#4498]
Fairly basic and low priority change IMO. Will work on a PR for this unless someone thinks its Actually Bad

**Comment by indirect** [comment]
I'm pretty sure we shipped this in 1.12? I feel like we did, anyway...

**Comment by LynnCo** [comment]
I'll check again, sec

**Comment by RochesterinNYC** [comment]
This was added via #4178

**Comment by LynnCo** [comment]
Yea I must have been working off of 1.11 earlier today, closing ~
