### ISSUE TITLE
Support a project enforced bundler version with a .bundler-version file

### ISSUE THREAD

**Issue by hlascelles** [bundler/bundler#4502]
Much like the `.ruby-version` file, it would be great for the `bundle` command to search up the path hierarchy to look for a `.bundler-version` file, which would dictate a team/project version.

It could optionally warn, error, or auto-install.

The [postit](https://github.com/bundler/postit) project is in this problem space, but requires the user to remember to use that command.

**Comment by hlascelles** [comment]
Much like the `.ruby-version` file, it would be great for the `bundle` command to search up the path hierarchy to look for a `.bundler-version` file, which would dictate a team/project version.

It could optionally warn, error, or auto-install.

**Comment by LynnCo** [comment]
@segiddins did you intent on merging the postit features into Bundler eventually?

**Comment by segiddins** [comment]
I have an experimental bundler branch that automatically invokes postit, but honestly my inclination is to punt on this and just make it happen as part of the bundler/rubygems merger.

**Comment by segiddins** [comment]
This can now been done when the experimental `postit_trampoline.rb` is enabled && the `BUNDLER_VERSION` environment variable is set (and also reading the locked version from the Gemfile.lock), so I don't think we really want to support yet another dotfile?

**Comment by segiddins** [comment]
Closing as the existing trampolining feature covers this.
