### ISSUE TITLE
bundle show --paths --without development test

### ISSUE THREAD

**Issue by lynncyrin** [bundler/bundler#4503]
From: https://github.com/bundler/bundler-features/issues/39

**Comment by potato20** [comment]
any update? this would be nice

**Comment by potato20** [comment]
especially the `--without` flag

**Comment by indirect** [comment]
@potato20 the update is: this is a feature request. feel free to implement it and send a PR if you're motivated. :)

**Comment by segiddins** [comment]
`bundle show` is gone in Bundler 2, so I'm closing this.
