### ISSUE TITLE
Add option --skip-ruby-directive

### ISSUE THREAD

**Issue by lynncyrin** [bundler/bundler#4505]
From: https://github.com/bundler/bundler-features/issues/45

**Comment by mikegee** [comment]
Is this still important to you, @zzak?

**Comment by zzak** [comment]
@mikegee no, I think this might work instead: `ruby ENV['RUBY_VERSION'] || '2.4.3'`, there are probably other ways to workaround it w/o adding yet another thing to bundler.

**Comment by colby-swandale** [comment]
This ticket has been alive for a long time now and no one has come to us asking for this so closing.
