### ISSUE TITLE
Warn if using production s3 source

### ISSUE THREAD

**Issue by lynnco** [bundler/bundler#4507]
from: https://github.com/bundler/bundler-features/issues/51

I believe this issue is no longer relevant as of the new index format though

**Comment by LynnCo** [comment]
Closing as no longer relevant (feel free to fact check me though)

**Comment by segiddins** [comment]
Still relevant

**Comment by segiddins** [comment]
Might it make more sense to just disallow direct access to the bucket from the S3 side instead of doing it in bundler?

**Comment by colby-swandale** [comment]
@segiddins is still something that needs to be done? I agree that S3 should just restrict its access.

**Comment by segiddins** [comment]
Uh I think that's more for the rubygems.org infra

**Comment by colby-swandale** [comment]
@segiddins can i close this then? Do you want to log a ticket on rubygems somewhere?
