### ISSUE TITLE
Add bundle pristine command

### ISSUE THREAD

**Issue by lynnco** [bundler/bundler#4509]
From: https://github.com/bundler/bundler-features/issues/5

**Comment by allenzhao** [comment]
I'm trying to implement this feature, and after reading discussion @ bundler/bundler-features#5, and this feature can be implemented by adding support for git gems, and it supports other types of gems by just invoking ` bundle exec gem pristine` right? @indirect @segiddins @RochesterinNYC

**Comment by RochesterinNYC** [comment]
@allenzhao that is correct, though gems that are specified via `path` will need to be handled as well.

**Comment by indirect** [comment]
On an installed gem, we can re-install from the .gem file, and on a git repo we can `checkout --force`, but for a path we don't have any original files to restore—I think calling `pristine` on a path gem should print an error and exit.

**Comment by RochesterinNYC** [comment]
Hm, so say for a `Gemfile` with 100 regular and git gems and 1 path gem, how will the user use `bundle pristine` on that `Gemfile`? I think we should somehow support this kind of use case without requiring the user to temporarily remove or comment out the path gem and run `bundle pristine`.

**Comment by RochesterinNYC** [comment]
Actually, any reason we wouldn't just print a warning (ex. `"path-gem" gem specified by path "../../path-gem" could not be restored as path gems cannot be restored`) rather than erroring out?

**Comment by indirect** [comment]
Oh yeah! If you're `pristine`ing more than one gem, just a warning seems fine. I was thinking of a single gem. :)

**Comment by RochesterinNYC** [comment]
Oh, gotcha. Yup, agree on the erroring out for the case of single `path` gem `pristine`ing.

**Comment by allenzhao** [comment]
I was going over gem pristine's code and [command options](http://guides.rubygems.org/command-reference/#gem-pristine) and wondering if we need everything similar or just a few?
Any thoughts/comments?

**Comment by RochesterinNYC** [comment]
Don't think we need `-​-all` as invoking `bundle pristine` without a gem name passed will basically be invoking on all the gems in the bundle.
Not sure how the `--version` indicator would apply as the `Gemfile.lock` would already indicate the locked version to restore.
I see the value in the others.

**Comment by RochesterinNYC** [comment]
@segiddins @indirect input on this would be helpful as I'm not as familiar with Rubygems as y'all.

**Comment by lynnco** [comment]
ping @segiddins @indirect

> I was going over gem pristine's code and command options and wondering if we need everything similar or just a few? Any thoughts/comments?

(also I think its safe to assume @allenzhao might not have time to continue working on this)

**Comment by segiddins** [comment]
Implemented in https://github.com/bundler/bundler/pull/5503
