### ISSUE TITLE
"bundle home" & "bundle source" commands

### ISSUE THREAD

**Issue by lynnco** [bundler/bundler#4510]
From: https://github.com/bundler/bundler-features/issues/56

**Comment by segiddins** [comment]
As André said, this seems like a great plugin to me.
Note that Bundler 1.15 contains the `bundle info` command, which will print the following:

```
  * rake (10.5.0)
	Summary: Rake is a Make-like program implemented in Ruby
	Homepage: https://github.com/ruby/rake
	Path: /Users/segiddins/.gem/ruby/2.4.1/gems/rake-10.5.0
```
