### ISSUE TITLE
Bundler version bundler-1.12.1 doesn't respect --path argument

### ISSUE THREAD

**Issue by parabolic** [bundler/bundler#4521]
**os:** ubuntu-14.04
**ruby version:** 2.3.0
Hi, I seem to run into an issue when I try to bundle gems with the latest bundle.
I install it via chef with the following command:
```
gem_package bundler
```
and I got the latest bundler version 1.12.1 but I also got an error where I cannot bundle the gems with the following command and username **deploy**:
```
bundle install --deployment --path /srv/www/cms
```
The error reported is:
```
STDOUT: There was an error while trying to write to
`/home/ubuntu/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47`.
It is likely that you need to grant write permissions for that path.
```
I get the .bundle directory in /srv/www/cms and the bundler fails with the above mentioned error.
Changing the version back to 1.11.2 works like a charm:
```
gem_package "bundler" do 
 version "1.11.2"
end
```
Please advise.

**Comment by segiddins** [comment]
Do id you grant write permissions for that path, as the error suggested?

**Comment by parabolic** [comment]
Hi,
well no because I was running the command as the user **deploy** which has it's own home directory **/home/deploy** therefore it doesn't make any sense for it to write into another users home dir.
Basically bundler wanted to write to ubuntu although it was run as a deploy user.
I confirmed the command while chef was running by doing ```ps aux``` and saw that chef executes the command correctly and with the correct user.

**Comment by johnd-itison** [comment]
I'm seeing this too:

```
$ sudo -u app RAILS_ENV=staging /opt/rbenv/shims/bundle install --deployment --binstubs --path vendor/bundle --without development test doc
There was an error while trying to write to `/home/john/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47`. It is likely that
you need to grant write permissions for that path.
```

I get the same result with or without `--deployment` - it looks like it's fixed on using `$HOME/.bundle` regardless of any other options passed?

**Comment by parabolic** [comment]
Seems that this problem is absent in bundler 1.12.4
THanks! YOu can close this issue
