### ISSUE TITLE
Bundler.io links to wrong changelog

### ISSUE THREAD

**Issue by georgeu2000** [bundler/bundler#4522]
http://bundler.io/v1.12/whats_new.html button links to v1.11 changelog. 

I think it should link to 1.12 changelog.

![image](https://cloud.githubusercontent.com/assets/794632/15000393/59166ffc-1144-11e6-9ff9-48bfbfe9095b.png)

**Comment by LynnCo** [comment]
The repo for the website is here https://github.com/bundler/bundler-site

**Comment by georgeu2000** [comment]
OK, I'll make a pull request.
