### ISSUE TITLE
What is the purpose of .bundle directory?

### ISSUE THREAD

**Issue by georgeu2000** [bundler/bundler#4523]
After upgrading to Bundler 1.12.1, when bundling, a .bundle directory was created. I searched the changelog for 1.12 and 1.11, but did not find any mention of it.

What is the purpose of .bundle directory? Should it be included in the repo?

**Comment by indirect** [comment]
It stores files used by Bundler (for example, configuration settings in `.bundle/config`'. It should not be included in the repo.

**Comment by segiddins** [comment]
@indirect should probably go in the FAQ on the site

**Comment by LynnCo** [comment]
Probably in the changelog also, since that's where I would imagine looking first

**Comment by segiddins** [comment]
There's actually no change that belongs in the CHANGELOG, that directory has been there for forever

**Comment by LynnCo** [comment]
Today I Learned ~

**Comment by agargiulo** [comment]
You say it's been there forever, but the directory wasn't created when running `bundle install` with version 1.11.2 of bundler, but it was created with bundler 1.12.2

**Comment by segiddins** [comment]
That's just a coincidence -- the directory has existed and been used by bundler since before I started using it.

**Comment by agargiulo** [comment]
That's really strange, since as far as I can remember, it's never created a `.bundle` directory in the working directory before, this is the first time I'm seeing it be generated. (I noticed because it wasn't in my `.gitignore`)

**Comment by georgeu2000** [comment]
Yep, me too. I don't mind deleting it, but never seen it before.

**Comment by indirect** [comment]
You need to leave the directory if you want Bundler to be able to remember your settings. You should gitignore the .bundle directory.

**Comment by RochesterinNYC** [comment]
Hm, if there is actually something in `1.12` that is causing this `.bundle` to  be generated every time (on normal bundle command runs that don't actually save or involve any bundle config options) as a side effect, this might merit something being mentioned in the CHANGELOG or release notes?

Will try to reproduce.

**Comment by agargiulo** [comment]
@indirect I get that, but this is what is generated:

```shell
% ls -l .bundle
total 4.0K
-rw-r--r--. 1 agargiulo agargiulo 7 May  6 12:43 config
% cat .bundle/config
--- {}
```

And I'm not asking Bundle to set anything, so there's nothing to be saved for later.

**Comment by 007** [comment]
Another data point:

```diff
diff --git a/.bundle/config b/.bundle/config
index 944e454..84ae275 100644
--- a/.bundle/config
+++ b/.bundle/config
@@ -1,2 +1,2 @@
 ---
-BUNDLE_JOBS: 4
+BUNDLE_JOBS: '4'
```

This is with zero other changes in the repo other than 1.11.x to 1.12.x version of bundler.

**Comment by segiddins** [comment]
@007 that change is intentional

**Comment by 007** [comment]
Intentional, sure, but is that maybe the reason that `.bundle.config` is being written vs being a no-op, since there's some kind of type validation happening?

**Comment by segiddins** [comment]
no, we had to re-write the serialization logic since it was breaking in other circumstances
