### ISSUE TITLE
Permission Errors

### ISSUE THREAD

**Issue by juniorRubyist** [bundler/bundler#4528]
- What did you do?

  I ran the command `/Users/joseph/.rvm/gems/ruby-2.3.0@global/gems/bundler-1.12.2/exe/bundle install`

- What did you expect to happen?

  I expected Bundler to install the gems for Rails.

- What happened instead?

  Instead, what actually happened was...

Error details

    Errno::EACCES: Permission denied @ rb_sysopen - /Users/joseph/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/versions
      /Users/joseph/.rvm/gems/ruby-2.3.0@global/gems/bundler-1.12.2/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:44:in `initialize'
      /Users/joseph/.rvm/gems/ruby-2.3.0@global/gems/bundler-1.12.2/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:44:in `open'
      /Users/joseph/.rvm/gems/ruby-2.3.0@global/gems/bundler-1.12.2/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:44:in `open'
      /Users/joseph/.rvm/gems/ruby-2.3.0@global/gems/bundler-1.12.2/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:44:in `update'
      /Users/joseph/.rvm/gems/ruby-2.3.0@global/gems/bundler-1.12.2/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:64:in `update'
      /Users/joseph/.rvm/gems/ruby-2.3.0@global/gems/bundler-1.12.2/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:55:in `update_and_parse_checksums!'
      /Users/joseph/.rvm/gems/ruby-2.3.0@global/gems/bundler-1.12.2/lib/bundler/fetcher/compact_index.rb:63:in `available?'
      /Users/joseph/.rvm/gems/ruby-2.3.0@global/gems/bundler-1.12.2/lib/bundler/fetcher/compact_index.rb:15:in `call'
      /Users/joseph/.rvm/gems/ruby-2.3.0@global/gems/bundler-1.12.2/lib/bundler/fetcher/compact_index.rb:15:in `block in compact_index_request'
      /Users/joseph/.rvm/gems/ruby-2.3.0@global/gems/bundler-1.12.2/lib/bundler/fetcher.rb:154:in `use_api'
      /Users/joseph/.rvm/gems/ruby-2.3.0@global/gems/bundler-1.12.2/lib/bundler/source/rubygems.rb:331:in `block in api_fetchers'
      /Users/joseph/.rvm/gems/ruby-2.3.0@global/gems/bundler-1.12.2/lib/bundler/source/rubygems.rb:331:in `select'
      /Users/joseph/.rvm/gems/ruby-2.3.0@global/gems/bundler-1.12.2/lib/bundler/source/rubygems.rb:331:in `api_fetchers'
      /Users/joseph/.rvm/gems/ruby-2.3.0@global/gems/bundler-1.12.2/lib/bundler/source/rubygems.rb:336:in `block in remote_specs'
      /Users/joseph/.rvm/gems/ruby-2.3.0@global/gems/bundler-1.12.2/lib/bundler/index.rb:10:in `build'
      /Users/joseph/.rvm/gems/ruby-2.3.0@global/gems/bundler-1.12.2/lib/bundler/source/rubygems.rb:335:in `remote_specs'
      /Users/joseph/.rvm/gems/ruby-2.3.0@global/gems/bundler-1.12.2/lib/bundler/source/rubygems.rb:82:in `specs'
      /Users/joseph/.rvm/gems/ruby-2.3.0@global/gems/bundler-1.12.2/lib/bundler/definition.rb:211:in `block (2 levels) in index'
      /Users/joseph/.rvm/gems/ruby-2.3.0@global/gems/bundler-1.12.2/lib/bundler/definition.rb:209:in `each'
      /Users/joseph/.rvm/gems/ruby-2.3.0@global/gems/bundler-1.12.2/lib/bundler/definition.rb:209:in `block in index'
      /Users/joseph/.rvm/gems/ruby-2.3.0@global/gems/bundler-1.12.2/lib/bundler/index.rb:10:in `build'
      /Users/joseph/.rvm/gems/ruby-2.3.0@global/gems/bundler-1.12.2/lib/bundler/definition.rb:206:in `index'
      /Users/joseph/.rvm/gems/ruby-2.3.0@global/gems/bundler-1.12.2/lib/bundler/definition.rb:200:in `resolve'
      /Users/joseph/.rvm/gems/ruby-2.3.0@global/gems/bundler-1.12.2/lib/bundler/definition.rb:140:in `specs'
      /Users/joseph/.rvm/gems/ruby-2.3.0@global/gems/bundler-1.12.2/lib/bundler/definition.rb:129:in `resolve_remotely!'
      /Users/joseph/.rvm/gems/ruby-2.3.0@global/gems/bundler-1.12.2/lib/bundler/installer.rb:195:in `resolve_if_need'
      /Users/joseph/.rvm/gems/ruby-2.3.0@global/gems/bundler-1.12.2/lib/bundler/installer.rb:70:in `run'
      /Users/joseph/.rvm/gems/ruby-2.3.0@global/gems/bundler-1.12.2/lib/bundler/installer.rb:22:in `install'
      /Users/joseph/.rvm/gems/ruby-2.3.0@global/gems/bundler-1.12.2/lib/bundler/cli/install.rb:102:in `run'
      /Users/joseph/.rvm/gems/ruby-2.3.0@global/gems/bundler-1.12.2/lib/bundler/cli.rb:175:in `install'
      /Users/joseph/.rvm/gems/ruby-2.3.0@global/gems/bundler-1.12.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /Users/joseph/.rvm/gems/ruby-2.3.0@global/gems/bundler-1.12.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /Users/joseph/.rvm/gems/ruby-2.3.0@global/gems/bundler-1.12.2/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /Users/joseph/.rvm/gems/ruby-2.3.0@global/gems/bundler-1.12.2/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /Users/joseph/.rvm/gems/ruby-2.3.0@global/gems/bundler-1.12.2/lib/bundler/cli.rb:11:in `start'
      /Users/joseph/.rvm/gems/ruby-2.3.0@global/gems/bundler-1.12.2/exe/bundle:27:in `block in <main>'
      /Users/joseph/.rvm/gems/ruby-2.3.0@global/gems/bundler-1.12.2/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
      /Users/joseph/.rvm/gems/ruby-2.3.0@global/gems/bundler-1.12.2/exe/bundle:19:in `<main>'

Environment
      
  Bundler   1.12.2
  Rubygems  2.5.1
  Ruby      2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin11.0]
  GEM_HOME  /Users/joseph/.rvm/gems/ruby-2.3.0
  GEM_PATH  /Users/joseph/.rvm/gems/ruby-2.3.0:/Users/joseph/.rvm/gems/ruby-2.3.0@global
  RVM       1.27.0 (latest)
  Git       1.7.12.4 (Apple Git-37)
  rubygems-bundler (1.4.4)
      
      Bundler settings
      
  orig_path
    Set via BUNDLE_ORIG_PATH: "/Users/joseph/.rvm/gems/ruby-2.3.0/bin:/Users/joseph/.rvm/gems/ruby-2.3.0@global/bin:/Users/joseph/.rvm/rubies/ruby-2.3.0/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/X11/bin:/usr/local/MacGPG2/bin:/Users/joseph/.rvm/bin"
  orig_gem_path
    Set via BUNDLE_ORIG_GEM_PATH: "/Users/joseph/.rvm/gems/ruby-2.3.0:/Users/joseph/.rvm/gems/ruby-2.3.0@global"

*Also*, do not suggest me issues #4458,  #4431, or #4429. I read them and they do not work for me.

I run Mac OS X 10.7.5 and I have Xcode installed.

**Comment by juniorRubyist** [comment]
@LynnCo Pardon me, but is there a fix? I need to get my Rails project started. It has been over two weeks.

**Comment by RochesterinNYC** [comment]
@juniorRubyist does this issue persist with the latest version of Bundler? `v1.12.4`?

**Comment by juniorRubyist** [comment]
No, thank you so much!
