### ISSUE TITLE
Bundler clean --force after system upgrade.

### ISSUE THREAD

**Issue by coelhotopetudo** [bundler/bundler#4532]
I want to develop locally using jekyll then push it to github pages. I did it successfuly when my system was Ubuntu 14.04 LTS, but after upgrading to 16.04 today, my jekyll environment stop working.

  I ran the command `/usr/local/bin/bundle clean --force` (with sudo command was executed successfuly)

  I expected Bundler to remove all gems, but gives:

Error details

    Errno::EACCES: Permission denied @ unlink_internal - /usr/local/lib/ruby/gems/2.1.0/cache/jekyll-watch-1.3.1.gem
      /usr/local/lib/ruby/2.1.0/fileutils.rb:1454:in `unlink'
      /usr/local/lib/ruby/2.1.0/fileutils.rb:1454:in `block in remove_file'
      /usr/local/lib/ruby/2.1.0/fileutils.rb:1459:in `platform_support'
      /usr/local/lib/ruby/2.1.0/fileutils.rb:1453:in `remove_file'
      /usr/local/lib/ruby/2.1.0/fileutils.rb:791:in `remove_file'
      /usr/local/lib/ruby/2.1.0/fileutils.rb:569:in `block in rm'
      /usr/local/lib/ruby/2.1.0/fileutils.rb:568:in `each'
      /usr/local/lib/ruby/2.1.0/fileutils.rb:568:in `rm'
      /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:192:in `block in clean'
      /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:192:in `each'
      /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:192:in `clean'
      /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/cli/clean.rb:11:in `run'
      /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/cli.rb:384:in `clean'
      /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/cli.rb:10:in `start'
      /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/exe/bundle:19:in `block in <top (required)>'
      /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
      /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/exe/bundle:17:in `<top (required)>'
      /usr/local/bin/bundle:23:in `load'
      /usr/local/bin/bundle:23:in `<main>'

Environment

    Bundler   1.11.2
    Rubygems  2.2.2
    Ruby      2.1.2p95 (2014-05-08 revision 45877) [x86_64-linux]
    GEM_HOME  /usr/local/lib/ruby/gems/2.1.0
    GEM_PATH  /usr/local/lib/ruby/gems/2.1.0:/home/alisson/.gem/ruby/2.1.0
    Git       2.7.4

**Comment by agis-** [comment]
I believe this is fixed by #4173; try upgrading to the latest Bundler.
