### ISSUE TITLE
"an unexpected error occurred, and Bundler cannot continue"

### ISSUE THREAD

**Issue by ygannett** [bundler/bundler#4534]
No case fits below aren't found in your resource.
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `/Users/yukiko/.rvm/gems/ruby-1.9.3-p551@omega.level_of_omega/bin/bundle install`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what actually happened was...

Error details

    Errno::EACCES: Permission denied - /Users/yukiko/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/versions
      /Users/yukiko/.rvm/gems/ruby-1.9.3-p551@omega.level_of_omega/gems/bundler-1.12.3/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:44:in `initialize'
      /Users/yukiko/.rvm/gems/ruby-1.9.3-p551@omega.level_of_omega/gems/bundler-1.12.3/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:44:in `open'
      /Users/yukiko/.rvm/gems/ruby-1.9.3-p551@omega.level_of_omega/gems/bundler-1.12.3/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:44:in `open'
      /Users/yukiko/.rvm/gems/ruby-1.9.3-p551@omega.level_of_omega/gems/bundler-1.12.3/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:44:in `update'
      /Users/yukiko/.rvm/gems/ruby-1.9.3-p551@omega.level_of_omega/gems/bundler-1.12.3/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:64:in `update'
      /Users/yukiko/.rvm/gems/ruby-1.9.3-p551@omega.level_of_omega/gems/bundler-1.12.3/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:55:in `update_and_parse_checksums!'
      /Users/yukiko/.rvm/gems/ruby-1.9.3-p551@omega.level_of_omega/gems/bundler-1.12.3/lib/bundler/fetcher/compact_index.rb:65:in `available?'
      /Users/yukiko/.rvm/gems/ruby-1.9.3-p551@omega.level_of_omega/gems/bundler-1.12.3/lib/bundler/fetcher/compact_index.rb:15:in `call'
      /Users/yukiko/.rvm/gems/ruby-1.9.3-p551@omega.level_of_omega/gems/bundler-1.12.3/lib/bundler/fetcher/compact_index.rb:15:in `block in compact_index_request'
      /Users/yukiko/.rvm/gems/ruby-1.9.3-p551@omega.level_of_omega/gems/bundler-1.12.3/lib/bundler/fetcher.rb:154:in `use_api'
      /Users/yukiko/.rvm/gems/ruby-1.9.3-p551@omega.level_of_omega/gems/bundler-1.12.3/lib/bundler/source/rubygems.rb:331:in `block in api_fetchers'
      /Users/yukiko/.rvm/gems/ruby-1.9.3-p551@omega.level_of_omega/gems/bundler-1.12.3/lib/bundler/source/rubygems.rb:331:in `select'
      /Users/yukiko/.rvm/gems/ruby-1.9.3-p551@omega.level_of_omega/gems/bundler-1.12.3/lib/bundler/source/rubygems.rb:331:in `api_fetchers'
      /Users/yukiko/.rvm/gems/ruby-1.9.3-p551@omega.level_of_omega/gems/bundler-1.12.3/lib/bundler/source/rubygems.rb:336:in `block in remote_specs'
      /Users/yukiko/.rvm/gems/ruby-1.9.3-p551@omega.level_of_omega/gems/bundler-1.12.3/lib/bundler/index.rb:10:in `build'
      /Users/yukiko/.rvm/gems/ruby-1.9.3-p551@omega.level_of_omega/gems/bundler-1.12.3/lib/bundler/source/rubygems.rb:335:in `remote_specs'
      /Users/yukiko/.rvm/gems/ruby-1.9.3-p551@omega.level_of_omega/gems/bundler-1.12.3/lib/bundler/source/rubygems.rb:82:in `specs'
      /Users/yukiko/.rvm/gems/ruby-1.9.3-p551@omega.level_of_omega/gems/bundler-1.12.3/lib/bundler/definition.rb:211:in `block (2 levels) in index'
      /Users/yukiko/.rvm/gems/ruby-1.9.3-p551@omega.level_of_omega/gems/bundler-1.12.3/lib/bundler/definition.rb:209:in `each'
      /Users/yukiko/.rvm/gems/ruby-1.9.3-p551@omega.level_of_omega/gems/bundler-1.12.3/lib/bundler/definition.rb:209:in `block in index'
      /Users/yukiko/.rvm/gems/ruby-1.9.3-p551@omega.level_of_omega/gems/bundler-1.12.3/lib/bundler/index.rb:10:in `build'
      /Users/yukiko/.rvm/gems/ruby-1.9.3-p551@omega.level_of_omega/gems/bundler-1.12.3/lib/bundler/definition.rb:206:in `index'
      /Users/yukiko/.rvm/gems/ruby-1.9.3-p551@omega.level_of_omega/gems/bundler-1.12.3/lib/bundler/definition.rb:200:in `resolve'
      /Users/yukiko/.rvm/gems/ruby-1.9.3-p551@omega.level_of_omega/gems/bundler-1.12.3/lib/bundler/definition.rb:140:in `specs'
      /Users/yukiko/.rvm/gems/ruby-1.9.3-p551@omega.level_of_omega/gems/bundler-1.12.3/lib/bundler/definition.rb:129:in `resolve_remotely!'
      /Users/yukiko/.rvm/gems/ruby-1.9.3-p551@omega.level_of_omega/gems/bundler-1.12.3/lib/bundler/installer.rb:195:in `resolve_if_need'
      /Users/yukiko/.rvm/gems/ruby-1.9.3-p551@omega.level_of_omega/gems/bundler-1.12.3/lib/bundler/installer.rb:70:in `run'
      /Users/yukiko/.rvm/gems/ruby-1.9.3-p551@omega.level_of_omega/gems/bundler-1.12.3/lib/bundler/installer.rb:22:in `install'
      /Users/yukiko/.rvm/gems/ruby-1.9.3-p551@omega.level_of_omega/gems/bundler-1.12.3/lib/bundler/cli/install.rb:102:in `run'
      /Users/yukiko/.rvm/gems/ruby-1.9.3-p551@omega.level_of_omega/gems/bundler-1.12.3/lib/bundler/cli.rb:175:in `install'
      /Users/yukiko/.rvm/gems/ruby-1.9.3-p551@omega.level_of_omega/gems/bundler-1.12.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /Users/yukiko/.rvm/gems/ruby-1.9.3-p551@omega.level_of_omega/gems/bundler-1.12.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /Users/yukiko/.rvm/gems/ruby-1.9.3-p551@omega.level_of_omega/gems/bundler-1.12.3/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /Users/yukiko/.rvm/gems/ruby-1.9.3-p551@omega.level_of_omega/gems/bundler-1.12.3/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /Users/yukiko/.rvm/gems/ruby-1.9.3-p551@omega.level_of_omega/gems/bundler-1.12.3/lib/bundler/cli.rb:11:in `start'
      /Users/yukiko/.rvm/gems/ruby-1.9.3-p551@omega.level_of_omega/gems/bundler-1.12.3/exe/bundle:27:in `block in <top (required)>'
      /Users/yukiko/.rvm/gems/ruby-1.9.3-p551@omega.level_of_omega/gems/bundler-1.12.3/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
      /Users/yukiko/.rvm/gems/ruby-1.9.3-p551@omega.level_of_omega/gems/bundler-1.12.3/exe/bundle:19:in `<top (required)>'
      /Users/yukiko/.rvm/gems/ruby-1.9.3-p551@omega.level_of_omega/bin/bundle:23:in `load'
      /Users/yukiko/.rvm/gems/ruby-1.9.3-p551@omega.level_of_omega/bin/bundle:23:in `<main>'
      /Users/yukiko/.rvm/gems/ruby-1.9.3-p551@omega.level_of_omega/bin/ruby_executable_hooks:15:in `eval'
      /Users/yukiko/.rvm/gems/ruby-1.9.3-p551@omega.level_of_omega/bin/ruby_executable_hooks:15:in `<main>'

Environment
      
  Bundler   1.12.3
  Rubygems  2.4.8
  Ruby      1.9.3p551 (2014-11-13 revision 48407) [x86_64-darwin15.4.0]
  GEM_HOME  /Users/yukiko/.rvm/gems/ruby-1.9.3-p551@omega.level_of_omega
  GEM_PATH  /Users/yukiko/.rvm/gems/ruby-1.9.3-p551@omega.level_of_omega:/Users/yukiko/.rvm/gems/ruby-1.9.3-p551@global
  RVM       1.27.0 (master)
  Git       2.7.4 (Apple Git-66)
  rubygems-bundler (1.4.4)
      
      Bundler settings
      
  orig_path
    Set via BUNDLE_ORIG_PATH: "/Users/yukiko/.rvm/gems/ruby-1.9.3-p551@omega.level_of_omega/bin:/Users/yukiko/.rvm/gems/ruby-1.9.3-p551@global/bin:/Users/yukiko/.rvm/rubies/ruby-1.9.3-p551/bin:/Users/yukiko/.rvm/bin:/usr/sbin:/usr/local/mysql/bin:/bin:/usr/bin:/usr/local/bin"
  orig_gem_path
    Set via BUNDLE_ORIG_GEM_PATH: "/Users/yukiko/.rvm/gems/ruby-1.9.3-p551@omega.level_of_omega:/Users/yukiko/.rvm/gems/ruby-1.9.3-p551@global"
--- TEMPLATE END ----------------------------------------------------------------

**Comment by manajay** [comment]
i have the same issue

**Comment by RochesterinNYC** [comment]
Does this persist with the latest version of bundler? `v1.12.4`?

**Comment by LynnCo** [comment]
ping @ygannett @manajay 

> Does this persist with the latest version of bundler?

**Comment by LynnCo** [comment]
Closing due to lack of user response, although this particular issue may either already be resolved.
