### ISSUE TITLE
Add viz-esque feature to expose deep dependency trees

### ISSUE THREAD

**Issue by LynnCo** [bundler/bundler#4536]
_From @jmmastey on March 26, 2016 16:7_

Hey all,

Per the recent npm kerfuffle and articles like [this one](http://lucumr.pocoo.org/2016/3/24/open-source-trust-scaling/), I was reviewing a codebase to see what sorts of unnecessary dependencies I could remove. A few things that would be useful in this case but that I can't find are:

1) The total, deduplicated set of dependencies in my repository, as a sort of quick sanity check on that codebase. I used a combination of `sed` and `grep` and got this info relatively easily, if a bit hackishly.
2) A better idea of which gems have long dependency trees. I can see first level dependencies, but for instance `rails` -> `actionmailer` -> `actionpack` -> `rack-test` -> `rack` is obscured. I do not see a way at the moment to tell precisely how many gems come along with, say, `pry`.

If there's interest in this possibly becoming part of the `viz` command or a standalone command, I'm willing to drum up some code for a deeper discussion. If this is outside the scope of core bundler, I'd rather know up front. Thanks!

_Copied from original issue: bundler/bundler-features#114_

**Comment by LynnCo** [comment]
_From @jmmastey on March 26, 2016 16:15_

Also possibly a valid fix for bundler/bundler#4359

**Comment by LynnCo** [comment]
_From @jmmastey on April 6, 2016 0:59_

Hey all (@segiddins mainly). Any thoughts on this? I'm at a four day hackathon that will be my primary chance to put time into this later this week and I'd be interested to know if it's worth pursuing. Thanks!

**Comment by LynnCo** [comment]
_From @segiddins on April 6, 2016 1:32_

This in a plugin would be awesome!

**Comment by LynnCo** [comment]
_From @jmmastey on April 15, 2016 21:38_

So I wrote what I think is a good first start at the hackathon:

https://github.com/jmmastey/bundler-stats

It works and I've been able to use it to get good info out of my existing projects. However, I think there's still lots of room to grow in the output. Totally open to suggestions on other output.

Should I leave this bug or close?

**Comment by jmmastey** [comment]
Hey @LynnCo, thanks for the upgrade. Since there's a plugin already (see April 15 comment), I'd love feedback but I'm not sure there that falls as a feature request.

Thanks :)

**Comment by LynnCo** [comment]
👍

**Comment by LynnCo** [comment]
We'll likely have feedback when we start working in the Plugin system release (1.13 or 1.14 maybe)
