### ISSUE TITLE
Option to specify directory on `bundle gem`

### ISSUE THREAD

**Issue by lynnco** [bundler/bundler#4537]
_From @zeiv on April 14, 2016 19:13_

I use GitHub a lot.  Usually I will create my repo online so GitHub can generate my README and LICENSE and generally make life easier, then clone it onto my machine and start developing.  When I'm creating a new gem however, Bundler also makes it own directory.  Often, what I want to name my gem is _not_ the same as what I want to name my repository.  So, here is what I propose:
- A flag such as `bundle gem my-gem-name --dir my-existing-gem-repo` to specify that Bundler should generate the gem in that directory.
- **And/Or** a flag to simply have the gem generated in the current directory: `bundle gem my-gem --current-dir`

Thoughts?

_Copied from original issue: bundler/bundler-features#117_

**Comment by LynnCo** [comment]
_From @segiddins on April 14, 2016 20:37_

I think this is straying out of `bundle gem` territory and more towards standalone tools like `ore`

**Comment by LynnCo** [comment]
_From @zeiv on April 16, 2016 17:16_

I agree that Bundler should not focus on gem bootstrapping, however I don't think the option to specify a directory is a huge step outside the minimal functionality that Bundler does provide.  Especially when you consider the other gem boilerplate functionality that Bundler _does_ provide, such as `--bin` and `--ext`.  Adding this option would only involve a small amount of code, as well.

**Comment by segiddins** [comment]
I don't think we'll  be adding more options to `bundle gem`, sorry.

**Comment by 00dav00** [comment]
I think this would be very useful, found myself in the need for this today since I usually create the remote first, clone and then start coding. 
Would you reconsider this if a PR is provided? @segiddins @colby-swandale

**Comment by indirect** [comment]
@00dav00 i think you can get the same effect with `cd ..; bundle gem dirname; cd dirname`, does that not work for you for some reason?
