### ISSUE TITLE
Option to annotate the gemfile

### ISSUE THREAD

**Issue by lynncyrin** [bundler/bundler#4538]
_From @jakeonrails on February 4, 2016 23:18_

Hi,

I think it would be useful to have a way to annotate a Gemfile with comments describing the gems included in the Gemfile, taken from the short description field in a gem's gemspec.

I am happy to write the code to make this happen but I know nothing about the bundler codebase, and seeing as it is quite large, could really use a pointer toward the place in the code that would make the most sense to implement this.

_Copied from original issue: bundler/bundler-features#109_

**Comment by LynnCo** [comment]
_From @segiddins on February 4, 2016 23:48_

This sounds more like a plugin than core bundler functionality to me, to be honest.

**Comment by LynnCo** [comment]
_From @jakeonrails on February 5, 2016 1:24_

Is there some documentation somewhere for how to build a plugin? I can't find anything on the bundler homepage and it's not searchable (AFAIK)

Also, for a tool such as this, I would think it would need access to the metadata bundler retrieves when it fetches stuff from rubygems. Having this thing run as a plugin would mean having to make a whole separate series of requests to rubygems, right? Or does the plugin system have a hook that I could tap into to fetch this data?

**Comment by LynnCo** [comment]
_From @segiddins on February 5, 2016 1:42_

You can name an executable `bundle-foo` and you're always free to `require 'bundler'` ;)
