### ISSUE TITLE
Enforcing Bundler version check?

### ISSUE THREAD

**Issue by LynnCo** [bundler/bundler#4539]
_From @Fryie on December 14, 2015 15:36_

Apologies if this has been asked before, I couldn't find anything in particular.

I know it has been discussed that Bundler should not try to enforce a particular version (see bundler/bundler#3697). I'd actually want to go in the opposite direction, making the version check stricter (at least as an opt-in feature). The reason is that when bugs such as https://github.com/bundler/bundler/issues/4147 arise only on CI but not on anyone's local dev machine or in production etc., it's harder to find out what caused the issue.

Ideally, I would like to enforce the Bundler version used on a project somehow, but to my understanding the BUNDLED_WITH:
- only works in one direction (using a *newer* version seems to be fine?)
- and only generates a warning instead of an error?

(I could not find any comprehensive documentation on this feature, so I might have the wrong impression. In my case, anyway, there was a "BUNDLED_WITH" section in the Gemfile.lock, but the CI server didn't complain about using a different Bundler version)

Ideally, it would even be possible to somehow install (and use) the correct Bundler version based on the Gemfile.lock, but I guess this would not be trivial to do.

_Copied from original issue: bundler/bundler-features#103_

**Comment by LynnCo** [comment]
_From @segiddins on December 14, 2015 19:0_

The postit gem does just that.

**Comment by LynnCo** [comment]
_From @Fryie on December 14, 2015 19:11_

Thanks. Could you provide some more information? The repository seems fairly empty so far.

**Comment by LynnCo** [comment]
_From @segiddins on December 14, 2015 19:25_

`gem install postit`, `postit install` will run `bundle install` using the version of bundler in your lockfile

**Comment by LynnCo** [comment]
_From @Fryie on December 15, 2015 11:36_

Thank you. Isn't there a chicken-or-egg problem in there somewhere, though? What if the version of `postit` contains a bug or doesn't yet include some feature that we need? It appears this only kind of shifts the problem around, although I can see that with a gem that's much simpler than Bundler the likelihood of a failure such as described above is of course much smaller.

**Comment by LynnCo** [comment]
_From @segiddins on December 15, 2015 19:32_

All postit does is download bundler.

**Comment by LynnCo** [comment]
_From @Fryie on December 15, 2015 19:41_

That's clearly not true. It also e.g. parses the Gemfile.lock to determine the bundler version among other things. That format could change in the future.

**Comment by LynnCo** [comment]
_From @segiddins on December 15, 2015 19:47_

Seeing as I'm the person who introduced the bundler version to the lockfile and the person who maintains postit and bundler, it's about as good a guarantee as you can get.

**Comment by segiddins** [comment]
Closing since bundler now includes postit (behind a feature flag at the moment)
