### ISSUE TITLE
Remember alternative Gemfile

### ISSUE THREAD

**Issue by lynncyrin** [bundler/bundler#4541]
_From @ineiti on May 14, 2015 5:12_

When I use an alternative Gemfile like

```
bundle install --gemfile Gemfile.dev
```

I'd like the `Gemfile.dev.lock` be used in any `require 'bundler/setup'`

Usecase:

for my development, I like having `path:` in the Gemfile, but not for deployment. So I made a second Gemfile and I am trying to use that one, but it always takes the gems from `Gemfile.lock`

_Copied from original issue: bundler/bundler-features#86_

**Comment by LynnCo** [comment]
_From @segiddins on May 14, 2015 5:14_

You can use the `BUNDLER_GEMFILE` environment variable to this effect

**Comment by LynnCo** [comment]
_From @ineiti on May 14, 2015 7:0_

OK - that might work. But I still it would be more logical to continue the way of https://github.com/bundler/bundler/pull/3320 and also use the config:gemfile for ```bundler/setup```.

**Comment by LynnCo** [comment]
_From @ineiti on May 14, 2015 7:30_

Now a step further. If I do first

```
bundle config --local gemfile Gemfile.dev
```

everything works as expected. But one might wonder whether the ```--gemfile``` option in ```bundle install``` shouldn't set that configuration by itself.

**Comment by LynnCo** [comment]
_From @asymmetric on July 2, 2015 19:14_

@ineiti, according to [this issue](https://github.com/bundler/bundler-features/issues/26):

> In Bundler 2.0, flags passed to commands will no longer be remembered, and instead should be set using `bundle config` if they should apply to every run

**Comment by segiddins** [comment]
I think we can close this -- it won't apply in bundler 2 since no flags will be remembered, and the likelihood of us fixing it for a final 1.x release is looking exceedingly small

**Comment by segiddins** [comment]
Closing for the reasons stated above.
