### ISSUE TITLE
Add an "add" command to add gems to the Gemfile

### ISSUE THREAD

**Issue by LynnCo** [bundler/bundler#4546]
_From @ryanstout on October 31, 2013 22:48_

Similar to https://github.com/DruRly/gemrat and NPM, it would be really useful to be able to say

    bundle add nokogiri

and have the gem added to the end of the Gemfile, then bundled.  With a lot of projects, it seems like a very common workflow to add gems without version numbers.  (I see bundler has inject is included, but it requires a version number.  Also, add seems like a better name)

I can implement this as a pull request, I wanted to discuss it before I went to build it however.  (As suggested in the development guide)

_Copied from original issue: bundler/bundler-features#32_

**Comment by LynnCo** [comment]
_From @indirect on October 31, 2013 23:18_

When I wrote inject (which is designed to be used by hosting companies, not individuals), I planned to add an `add` command at some point. The tricky part is what kind of version constraint to default to. In general, it is a good idea to at very least add a constraint like `~> X.0` where X is the current major version.

**Comment by LynnCo** [comment]
_From @ryanstout on November 1, 2013 3:34_

Maybe my use case is different from most people, but typically I just want to add   gem "gemname"  without a version qualifier.  What's the main reason you typically add a major version number?  Is that so you can do bundle update without worrying about major changes?

Thanks

**Comment by LynnCo** [comment]
_From @indirect on November 1, 2013 15:50_

We recommend at least a major (and possibly a minor) constraint, simply because a gem with no constraint at all frequently causes surprised users when they get a valid result that they did not expect, like one gem with a very old version. Bundler has to make tradeoffs between gems that disagree, and it can't know which versions you care about unless you tell it. That also allows bundle updates with less worry about everything breaking.

**Comment by LynnCo** [comment]
_From @ryanstout on November 3, 2013 23:7_

Interesting, thats a different use case than how the teams I've worked with do things.  Usually we just bundle update gems individually.  What do you think about doing
    bundle add gemname [version]

where version is optional?

**Comment by LynnCo** [comment]
_From @radar on November 3, 2013 23:13_

Definitely agree that a bundle add command would be extremely useful. It should add the latest version of the gem unless a version constraint is specified (with -v, of course)

**Comment by LynnCo** [comment]
_From @ryanstout on November 3, 2013 23:22_

@radar So are you suggesting having it add: gem 'gem_name', 'version'  or just have it default to not specifying a version?  I guess the thing I always liked about bundler was I could let it handle the gem version in most cases. :-)

**Comment by LynnCo** [comment]
_From @radar on November 3, 2013 23:26_

Default to specifying the latest non-RC gem version unless otherwise specified. I've seen super weird behaviour when not specifying dependencies, the kind of which Andre talked about already.

**Comment by LynnCo** [comment]
_From @ryanstout on November 3, 2013 23:29_

Ok.  So if you guys are interested, I can add it, or @indirect it might be faster for you if you have time, since you implemented inject.  Thanks.

**Comment by LynnCo** [comment]
_From @ryanstout on November 3, 2013 23:30_

And by add it, I mean submit a pull request :-)

**Comment by LynnCo** [comment]
_From @ognevsky on November 13, 2013 8:36_

I've added this feature https://github.com/bundler/bundler/pull/2709

**Comment by LynnCo** [comment]
_From @RochesterinNYC on March 13, 2016 23:47_

@indirect @segiddins 

Is this something that we still want to pursue? I'd be interested in (re)implementing it.

**Comment by b-ggs** [comment]
@RochesterinNYC @segiddins @indirect Hey, guys. I'm interested in implementing this feature. Is it alright if I pick this up from where it ended?

**Comment by RochesterinNYC** [comment]
@b-ggs go ahead! Please keep us updated and definitely ask for help as needed.
