### ISSUE TITLE
Add --all flag to bundler update

### ISSUE THREAD

**Issue by lynnco** [bundler/bundler#4553]
_From @xaviershay on August 21, 2013 3:0_

Print usage when bundle update is run without arguments -- many people think that they should run bundle update after git pull, but that mostly just messes everything up.

From https://github.com/bundler/bundler/issues/2279

_Copied from original issue: bundler/bundler-features#18_

**Comment by LynnCo** [comment]
_From @jlsuttles on September 13, 2013 23:38_

So the current functionality when one runs `bundle update` should happen when one runs `bundle update --all` and `bundle update` should just print usage instructions.

**Comment by LynnCo** [comment]
_From @indirect on September 14, 2013 4:55_

Yup. Since this change breaks backwards compatibility, pull requests should be sent to the 2-0-dev branch instead of master.

**Comment by bronzdoc** [comment]
https://github.com/bundler/bundler/pull/2646 closed this
