### ISSUE TITLE
bundle gem --test should include a cucumber option

### ISSUE THREAD

**Issue by LynnCo** [bundler/bundler#4554]
_From @jorge428 on August 17, 2013 3:18_

The rspec & minitest options are great - why not cucumber too? It could generate something like

features/
features/test_gem.feature
features/step_definitions/
features/step_definitions/test_gem_steps.rb
features/support/

Are there any objections to this and/or have people tried it before?

_Copied from original issue: bundler/bundler-features#15_

**Comment by LynnCo** [comment]
_From @xaviershay on August 17, 2013 15:24_

My first instinct is to avoid expressing opinions on other gems where possible. It increases our maintenance surface area by including one more gem we have to keep up to date on.

I'd probably actually like to move bundle gem out of core entirely, though we don't have a good way of doing that currently. A dependency management tool shouldn't be in the business of template generation.

Interested in other opinions.

**Comment by LynnCo** [comment]
_From @jorge428 on August 19, 2013 4:55_

Totally understandable.


> A dependency management tool shouldn't be in the business of template generation.

Agreed.


> I'd probably actually like to move bundle gem out of core entirely, though we don't have a good way of doing that currently. 

Would you mind if another gem came into existence with the express purpose of doing gem skeleton generation?
I guess I don't really understand what you mean by "we don't have a good way of doing that currently."

**Comment by LynnCo** [comment]
_From @indirect on August 19, 2013 6:57_

It would be nice to have an optional gem (named, say, bundler-gem) that handled the generation via a bundler subcommand. Would you be interested in working on the gem that generates gem templates?

**Comment by LynnCo** [comment]
_From @jorge428 on August 21, 2013 15:48_

Interested, yes, but I don't really have experience with ruby templates. Always willing to learn, though, so if it's something people besides me want to see happen, count me in.

If bundler's philosophy is to be a gem management system and only that, I'm not sure why it should be bundler-gem and not something else entirely. At the same time, a gem template generator by any other name would be as useful, so I don't really care what it's called.

**Comment by LynnCo** [comment]
_From @indirect on August 21, 2013 19:27_

I don't really care what it's called either, but bundler-gem would mean that people could keep using the `bundle gem foo` command to create gems. That was my only reasoning.

**Comment by segiddins** [comment]
👎 from me -- extreme customizability should be kept to purpose-built gems such as Ore

**Comment by LynnCo** [comment]
If the original requester wants to walk through justifying this feature request to the team then we can re-open this, but for the moment I feel its better closed
