### ISSUE TITLE
Allow ruby version requirement strings

### ISSUE THREAD

**Issue by LynnCo** [bundler/bundler#4555]
_From @sodabrew on August 13, 2013 5:18_

This would be useful:

```ruby
ruby '~> 1.9.3'
```

Previously: https://github.com/bundler/bundler/issues/2213
PR submitted at: https://github.com/bundler/bundler/issues/2228

_Copied from original issue: bundler/bundler-features#13_

**Comment by LynnCo** [comment]
_From @indirect on August 13, 2013 7:57_

As discussed there, this is arguably a bad idea unless the lockfile contains the ruby version. Adding the ruby version to the lockfile means Bundler 2 at the earliest.

**Comment by LynnCo** [comment]
_From @sheerun on October 17, 2013 13:0_

It is must-have to 2.0

**Comment by LynnCo** [comment]
_From @donv on April 18, 2015 6:7_

:+1:  for this.  A very important feature.  And yes, the lock file must contain the locked version just as with the gem versions.

**Comment by LynnCo** [comment]
_From @indirect on April 18, 2015 6:8_

If it's so important to you, maybe you should sent a pull request!

**Comment by segiddins** [comment]
This is implemented in 1.12

**Comment by sodabrew** [comment]
Awesome! 🎆
