### ISSUE TITLE
Installing json 1.8.3 on Ruby 2.3.1 on Travis results in error.

### ISSUE THREAD

**Issue by JonRowe** [bundler/bundler#4557]
For some reason Bundler `~> 1.12.0` can't install `json-1.8.3` on TravisCI. See https://travis-ci.org/rspec/rspec-mocks/jobs/128825648 as an example, the only way I've been able to get RSpecs build to pass is to pin bundler to the latest 1.11 release.

**Comment by segiddins** [comment]
Just a hunch, but I guess this would pass without the `--standalone`?

**Comment by JonRowe** [comment]
I'll put that up for a build as a spike, but it would be nice if this could be fixed, `--standalone` saves us build time.

**Comment by parndt** [comment]
+1 I also have this issue while running with `--standalone`

**Comment by segiddins** [comment]
try https://github.com/bundler/bundler/issues/4558, it should fix it 😁

**Comment by JonRowe** [comment]
That does work for us

**Comment by JonRowe** [comment]
(not as something we can use properly though, as it involves manually packaging the gem to ship up to travis which isn't something I want to rely on)

**Comment by segiddins** [comment]
@JonRowe of course, it'll get bundled into a release at some point, just wanted to verify it actually fixed your bug.
