### ISSUE TITLE
`bundle platform` returns unexpected output for ruby

### ISSUE THREAD

**Issue by dgodd** [bundler/bundler#4562]
To reproduce

Install ruby version 2.2.3

Gemfile
```
ruby '~> 2.2.0'
```

and run `bundle platform --ruby` 

The output is

`2.2.0`

I would have expected either `~> 2.2.0` or `2.2.3` or possibly the most recent version of ruby to exist (probably not really) ; but I would not have expected `2.2.0`.

**Comment by segiddins** [comment]
That would've been an incompatible change to include the `~>`. If you want it to update to `2.2.3`, run `bundle update --ruby` while running 2.2.3

**Comment by LynnCo** [comment]
@dgodd it looks like segiddins has a working suggestion for your problem, so I'm going to close this. Tell us if you need it reopened
