### ISSUE TITLE
Unfortunately, an unexpected error occurred, and Bundler cannot continue.

### ISSUE THREAD

**Issue by next2014** [bundler/bundler#4563]
First, try this link to see if there are any existing issue reports for this error:
https://github.com/bundler/bundler/search?q=Permission+denied+-+%2FUsers%2Fnext%2F.bundle%2Fcache%2Fcompact_index%2Frubygems.org.443.29b0360b937aa4d161703e6160654e47%2Fversions&type=Issues

**Comment by segiddins** [comment]
This is a duplicate issue -- please search the issue tracker to find others like it
