### ISSUE TITLE
Bundler Annotates RUBY_VERSION But Doesn't Change BUNDLED_WITH

### ISSUE THREAD

**Issue by hillmandj** [bundler/bundler#4573]
When working collaboratively on a project, if someone has the latest version of `bundler` the `RUBY_VERSION` gets annotated. If someone else has an earlier version of `bundler` (in my case 1.11.2) the `RUBY_VERSION` is removed, but `BUNDLED_WITH` is unchanged and still indicates the latest version.

This is confusing because it obscures the solution to the problem: 'update your bundler'. Any way to fix this? Or am I missing something?

**Comment by segiddins** [comment]
A warning should be printed, and versions of bundler after 1.12 will be resilient against new sections being added from the lockfile. Nothing we can do about the ruby version being removed for old versions though. Best bet is to upgrade.

**Comment by indirect** [comment]
Like @segiddins said, we have noticed this problem and implemented a fix for it... but that means only Bundler 1.12 and above will be able to preserve new/unknown lockfile sections.
