### ISSUE TITLE
bundler in docker with alpine is messy

### ISSUE THREAD

**Issue by grosser** [bundler/bundler#4575]
atm I have to jump through these hoops to get something bundled ... not fun ...

 - io/console needs a gem with native extensions ... and is not necessary
 - root warning (not that bad, but maybe there is a workaround like not spamming if root is the only installed user)
 - ri/rdoc should not be required (I guess this is a rubygems issue ...)

```
FROM alpine

RUN apk add --update ruby

ENV BUNDLER_VERSION 1.12.3
RUN gem install bundler -v $BUNDLER_VERSION --no-ri --no-rdoc

# bundler wants some library that needs core extensions ... but it won't compile
RUN mkdir /usr/lib/ruby/gems/2.2.0/gems/bundler-$BUNDLER_VERSION/lib/io
RUN touch /usr/lib/ruby/gems/2.2.0/gems/bundler-$BUNDLER_VERSION/lib/io/console.rb

# bundler does not want to install as root
RUN bundle config --global silence_root_warning 1

RUN mkdir /app
WORKDIR /app

ADD Gemfile .
ADD Gemfile.lock .
RUN bundle
```

**Comment by envygeeks** [comment]
@gross I think this is an upstream problem.  Those packages should have come with your Ruby (and there is an open ticket on Alpine I created a year ago about it.) They don't on Alpine, you have to manually add them (as they belong to Stdlib and it's not out of the wild to assume they should be there.)  Here are the packages we install to get it done: https://github.com/jekyll/docker/blob/master/opts.yml#L56

**Comment by LynnCo** [comment]
@grosser did @envygeeks's suggestion work for you?

**Comment by grosser** [comment]
No, also fails with alpine edge (3.4)

A rescue with a warning would be a nice workaround ... or only loading it when needed

**Comment by grosser** [comment]
@LynnCo please remove  'more-information-needed' label

**Comment by envygeeks** [comment]
@grosser this is an upstream Alpine problem, I'll fix your Dockerfile for you so that you can get Docker:

```dockerfile
FROM alpine
ENV BUNDLER_VERSION 1.12.3
RUN \
  apk --update add ruby ruby-io-console ruby-irb ruby-json ruby-rake ruby-rdoc  && \
  gem install bundler -v "$BUNDLER_VERSION" --no-document && \
  bundle config --global silence_root_warning 1 && \
  mkdir /app

WORKDIR /app
ADD Gemfile.lock .
ADD Gemfile .
RUN bundle
```

See: http://bugs.alpinelinux.org/issues/4604

**Comment by grosser** [comment]
I know how to fix it, but I was hoping bundler could also fix it by default since production apps don't need ruby-full / io-console / irb etc things ...

**Comment by envygeeks** [comment]
@grosser I think they shouldn't.  If you don't have a dependency they need (and one that should come with Ruby by default -- as it is an stdlib gem) then I think what it's doing is good, they should throw.

**Comment by grosser** [comment]
But bundler does not need it / only needs it when doing interactive things
(I'd guess that's why it is missing from alpine ruby) ... so don't depend
on it ?

**Comment by envygeeks** [comment]
@grosser good point.

**Comment by segiddins** [comment]
Since `io/console` is required in Thor, the fix would need to go in there

**Comment by grosser** [comment]
atm using ruby:2.3.1-alpine which does not have these issues ... and there are other good know workarounds ... so most likely nobody is going to fix this :)

**Comment by grosser** [comment]
Same issue happens on amazon linux ... would make life easier if it rescued and warned

**Comment by segiddins** [comment]
As I posted upthread, this is an issue with Thor rather than bundler, and a fix would have to go in there
