### ISSUE TITLE
Gem::Exception: can't find executable

### ISSUE THREAD

**Issue by envygeeks** [bundler/bundler#4576]
```
/var/lib/gems/2.3.0/gems/bundler-1.12.3/lib/bundler/rubygems_integration.rb:373:in `block in replace_bin_path': can't find executable bundle (Gem::Exception)
    from /usr/local/lib/site_ruby/2.3.0/rubygems.rb:278:in `activate_bin_path'
    from /usr/local/bin/bundle:22:in `<main>'
```

Even `Gem.bin_path("bundle")` raises the same error.

**Comment by tnzk** [comment]
Just ran into this problem when starting `foreman start` on a Docker container based on `ruby:2.3.1-alpine`.

[Downgrading rubygems to 2.6.1 and re-installing bundler](https://github.com/bundler/bundler/issues/4402#issuecomment-205464710) helped me.

**Comment by envygeeks** [comment]
@tnzk we had to downgrade too for the time being.

**Comment by segiddins** [comment]
Could anyone share a script to reproduce the issue? Thanks!

**Comment by envygeeks** [comment]
@segiddins Any Ubuntu 16.04 box with System Ruby and RubyGems-Integration (upgraded to the latest RubyGems) can replicate the issue with the current script:

```
printf "source 'https://rubygems.org'\ngem 'pry'" > Gemfile; bundle install --path vendor/bundle -j 128; pry -c 'Gem.bin_path("bundle")'
Using slop 3.6.0
Using coderay 1.1.1
Using bundler 1.12.4
Using method_source 0.8.2
Using pry 0.10.3
Bundle complete! 1 Gemfile dependency, 5 gems now installed.
Bundled gems are installed into ./vendor/bundle.
/home/jordon/development/envygeeks/test/vendor/bundle/ruby/2.3.0/gems/pry-0.10.3/lib/pry/cli.rb:207:in `eval': can't find executable  (Gem::Exception)
	from /var/lib/gems/2.3.0/gems/bundler-1.12.4/lib/bundler/rubygems_integration.rb:387:in `block in replace_bin_path'
	from (eval):1:in `block in <top (required)>'
	from /home/jordon/development/envygeeks/test/vendor/bundle/ruby/2.3.0/gems/pry-0.10.3/lib/pry/cli.rb:207:in `eval'
	from /home/jordon/development/envygeeks/test/vendor/bundle/ruby/2.3.0/gems/pry-0.10.3/lib/pry/cli.rb:207:in `block in <top (required)>'
	from /home/jordon/development/envygeeks/test/vendor/bundle/ruby/2.3.0/gems/pry-0.10.3/lib/pry/cli.rb:83:in `block in parse_options'
	from /home/jordon/development/envygeeks/test/vendor/bundle/ruby/2.3.0/gems/pry-0.10.3/lib/pry/cli.rb:83:in `each'
	from /home/jordon/development/envygeeks/test/vendor/bundle/ruby/2.3.0/gems/pry-0.10.3/lib/pry/cli.rb:83:in `parse_options'
	from /home/jordon/development/envygeeks/test/vendor/bundle/ruby/2.3.0/gems/pry-0.10.3/bin/pry:16:in `<top (required)>'
	from /home/jordon/development/envygeeks/test/vendor/bundle/ruby/2.3.0/bin/pry:22:in `load'
	from /home/jordon/development/envygeeks/test/vendor/bundle/ruby/2.3.0/bin/pry:22:in `<main>'
```

The source:

```bash
printf "source 'https://rubygems.org'\ngem 'pry'" > Gemfile; bundle install --path vendor/bundle -j 128; pry -c 'Gem.bin_path("bundle")'
```

**Comment by envygeeks** [comment]
The problem lies when Bundler adjusts the bin path, for some reason it's not finding the right Gem, for us we fixed it within a few of our scripts that couldn't be downgraded by replacing the path with BUNDLE_ORIG_PATH which fixes the issue with getting to system gems (which wasn't a problem before.)

I also noticed that even though `BUNDLE_DISABLE_SHARED_GEMS: true` it still only adds the bundle path rather than all the paths and the bundle path first, which is where this problem lies, we no longer have any path but bundler's path.

**Comment by segiddins** [comment]
I don't have a Ubuntu box handy, so someone else will have to try and make a PR for this, sorry

**Comment by tk8817** [comment]
@segiddins I think most folks are feeling the pain of this bug when using the official Ruby docker images (https://hub.docker.com/_/ruby/). This can be reproduced in Ubuntu & Debian, it is more so related to the Bundler & RubyGems versions than anything else.

**Comment by segiddins** [comment]
@tk8817 I've been unable to reproduce it locally on OS X with _any_ version combo of RubyGems and Bundler, so someone running into the bug will have to debug it

**Comment by abmxer** [comment]
@tk8817 Yes, I was having this problem using official docker image ruby:2.3.1. Its something related to the bundler version 1.12.4. For any reason, the docker image should be installing the last bundler version (1.12.5), but after create/start the container had bundler version 1.12.4.

So I upgraded the bundler version (1.12.5) manually and it worked.

```

14:46:47 - INFO - Guard::RSpec is running
14:46:47 - INFO - Guard is now watching at '/usr/src/app'
14:46:52 - INFO - Running: spec/models/course_spec.rb
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.12.4/lib/bundler/rubygems_integration.rb:373:in `block in replace_bin_path': can't find executable bundle (Gem::Exception)
        from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems.rb:278:in `activate_bin_path'
        from /usr/local/bin/bundle:22:in `<main>'
14:46:52 - ERROR - Failed: "bundle exec rspec -f progress -r /usr/local/bundle/gems/guard-rspec-4.7.2/lib/guard/rspec_formatter.rb -f Guard::RSpecFormatter --failure-exit-code 2  spec/models/course_spec.rb" (exit code: 1)

[1] guard(main)> 
[1] guard(main)> 
^Z
[1]+  Stopped                 guard
root@64cd6fce3251:/usr/src/app# bundle --version
Bundler version 1.12.4
root@64cd6fce3251:/usr/src/app# gem install bundler
Fetching: bundler-1.12.5.gem (100%)
Successfully installed bundler-1.12.5
1 gem installed
root@64cd6fce3251:/usr/src/app# bundle --version                                                                                                                          
Bundler version 1.12.5
root@64cd6fce3251:/usr/src/app# guard 
19:12:01 - INFO - Guard::RSpec is running
19:12:03 - INFO - Guard is now watching at '/usr/src/app'
19:12:06 - INFO - Running: spec/models/course_spec.rb
.

Finished in 0.36932 seconds (files took 10.77 seconds to load)
1 example, 0 failures


[1] guard(main)> 

```

**Comment by glennpratt** [comment]
I'm hitting this issue. I tried a combination of bundler, ruby and rubygems version. For me, this bug happens consistently with rubygems > 2.6.1. Downgrading resolves it.

```
rvm install rubygems 2.6.1 --force
```

**Comment by envygeeks** [comment]
It never occurred to me this might be a RubyGems problem, but that's probably because we can't even upgrade past 2.6.1 because we run into https://github.com/rubygems/rubygems/issues/1602

**Comment by glennpratt** [comment]
This may be a dup of #4402

**Comment by envygeeks** [comment]
I'm pretty sure 4602 comes after 4576.

**Comment by glennpratt** [comment]
Sure, just pointing out parallel conversation.

**Comment by pmantaj** [comment]
I ran into this problem when starting foreman start on a Docker container based on `ruby:2.3.1`
I just put below line to a `Dockerfile`:

`RUN gem install bundler`

New bundler installation put the bundler exec file to the path: `/usr/local/bundler/bin` and error disappeared. The same path was set in the `BUNDLE_BIN` environment variable in the ruby:2.3.1 image but the bundler was installed in the `/usr/local/bin` path by default.

**Comment by leifg** [comment]
@pmantaj I tried putting that in my Dockerfile after bundle install, that did not work. It works however when I log into the container and execute `gem install bundler`. For some reason the context is different.

**Comment by egbertp** [comment]
@pmantaj Thanks for sharing! 

I'm running inside a Docker container based on ruby:2.3.1-alpine. Installing bundler in the Dockerfile solved the problem. Thanks again!

**Comment by programmerdave** [comment]
If anyone needs a temporary work around, this answer works perfectly for me: https://github.com/bundler/bundler/issues/4602#issuecomment-233619696

**Comment by segiddins** [comment]
This is because the given reproduction example is mis-using `Gem.bin_path`

> `printf "source 'https://rubygems.org'\ngem 'pry'" > Gemfile; bundle install --path vendor/bundle -j 128; bundle exec pry -c 'Gem.bin_path("bundle")'`

Will attempt to get the bin path for a gem _named_ `bundle`, and in fact RubyGems now requires passing 2 args to `Gem.bin_path(gem_name, exec_name)`. You should be using `Gem.bin_path("bundler", "bundle")`
