### ISSUE TITLE
will not download bundler

### ISSUE THREAD

**Issue by jmchugh2** [bundler/bundler#4578]
---------
- What did you do?

  I ran the command `/usr/bin/bundle install`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what actually happened was...

Error details

    NoMethodError: undefined method `add_root_vertex' for Molinillo::DependencyGraph:[]:Molinillo::DependencyGraph
      /usr/lib/ruby/vendor_ruby/bundler/resolver.rb:194:in `block in initialize'
      /usr/lib/ruby/vendor_ruby/bundler/resolver.rb:194:in `initialize'
      /usr/lib/ruby/vendor_ruby/bundler/resolver.rb:181:in `new'
      /usr/lib/ruby/vendor_ruby/bundler/resolver.rb:181:in `resolve'
      /usr/lib/ruby/vendor_ruby/bundler/definition.rb:200:in `resolve'
      /usr/lib/ruby/vendor_ruby/bundler/definition.rb:166:in `missing_specs'
      /usr/lib/ruby/vendor_ruby/bundler/installer.rb:70:in `block in run'
      /usr/lib/ruby/vendor_ruby/bundler/ui/shell.rb:76:in `silence'
      /usr/lib/ruby/vendor_ruby/bundler/installer.rb:67:in `run'
      /usr/lib/ruby/vendor_ruby/bundler/installer.rb:18:in `install'
      /usr/lib/ruby/vendor_ruby/bundler/cli/install.rb:107:in `run'
      /usr/lib/ruby/vendor_ruby/bundler/cli.rb:162:in `install'
      /usr/lib/ruby/vendor_ruby/thor/command.rb:27:in `run'
      /usr/lib/ruby/vendor_ruby/thor/invocation.rb:126:in `invoke_command'
      /usr/lib/ruby/vendor_ruby/thor.rb:359:in `dispatch'
      /usr/lib/ruby/vendor_ruby/thor/base.rb:440:in `start'
      /usr/lib/ruby/vendor_ruby/bundler/cli.rb:10:in `start'
      /usr/bin/bundle:20:in `block in <main>'
      /usr/lib/ruby/vendor_ruby/bundler/friendly_errors.rb:7:in `with_friendly_errors'
      /usr/bin/bundle:18:in `<main>'

Environment

    Bundler   1.10.6
    Rubygems  2.4.5.1
    Ruby      2.2.3p173 (2015-08-18 revision 0) [x86_64-linux-gnu]
    GEM_HOME  /var/lib/gems/2.2.0
    GEM_PATH  /var/lib/gems/2.2.0:/root/.gem/ruby/2.2.0:/usr/lib/x86_64-linux-gnu/rubygems-integration/2.2.0:/usr/share/rubygems-integration/2.2.0:/usr/share/rubygems-integration/2.2:/usr/share/rubygems-integration/all
    Git       2.8.1

**Comment by RochesterinNYC** [comment]
Does this issue persist with the latest version of Bundler? (`v1.12.3`)

**Comment by jmchugh2** [comment]
I'm not sure what version.This is the url of the instructions I was following. Installing Metasploit in Ubuntu and Debian. This is the instructions for the installation of the bundler.cd metasploit-framework

# If using RVM set the default gem set that is create when you navigate in to the folder
rvm --default use ruby-2.1.6@metasploit-framework

gem install bundler
bundle install. 

Thanks for your help.
James

  
|  
|   |  
Installing Metasploit in Ubuntu and Debian
   |  |

  |

 
 

    On Saturday, May 14, 2016 11:34 AM, James Wen <notifications@github.com> wrote:
 

 Does this issue persist with the latest version of Bundler? (v1.12.3)—

**Comment by sstern6** [comment]
Per @RochesterinNYC ask, if you type in `bundler -v` to check the version of your current implementation of bundler might help knowing.  Also, an issue found here suggests there is a bug using certain ruby versions. Just a thought.

https://github.com/rapid7/metasploit-framework/issues/6630

**Comment by LynnCo** [comment]
@jmchugh2 do you still need help resolving this issue?

**Comment by jmchugh2** [comment]
no, everything is fine. thank you,James 

    On Thursday, June 9, 2016 2:26 AM, Lynn Cyrin <notifications@github.com> wrote:
 

 @jmchugh2 do you still need help resolving this issue?—
