### ISSUE TITLE
Bundler fails to parse a gemspec line when it appears in a gemfile that is evaled inside of another gemfile

### ISSUE THREAD

**Issue by stupakov** [bundler/bundler#4584]
Bundler version: 1.12.4
OS: observed on OS X 10.10.5 AND on Ubuntu 14.04.1
Description:
Bundler fails to parse a gemspec line when it appears in a gemfile that is evaled inside of another gemfile
Reproducing: The minimum setup for reproducing this bug can be found in the simple example at https://github.com/stupakov/bundler-bug

Failure output:

```
[!] There was an error parsing `Gemfile`:
[!] There was an error parsing `Gemfile-other`: No such file or directory - gems/mygem/mygem.gemspec. Bundler cannot continue.

 #  from Gemfile-other:1
 #  -------------------------------------------
 >  gemspec path: 'gems/mygem'
 #  -------------------------------------------
. Bundler cannot continue.

 #  from /Users/myusername/workspace/bundler-bug/Gemfile:1
 #  -------------------------------------------
 >  eval_gemfile 'Gemfile-other'
 #  -------------------------------------------
```

**Comment by RochesterinNYC** [comment]
I investigated this briefly and the root cause of the issue is that the `gemfile` parameter passed to `eval_gemfile` at https://github.com/bundler/bundler/blob/master/lib/bundler/dsl.rb#L36 on the second invocation is simply the string `Gemfile-other` when it should be an absolute path.

**Comment by RochesterinNYC** [comment]
Example work-around that illustrates the problem:

Changing the `eval_gemfile` line in the `Gemfile` to
```
eval_gemfile(File.dirname(__FILE__) + '/Gemfile-Other')
```
enables a successful `bundle install`.
