### ISSUE TITLE
bundle exec rake on jruby 1.7.19 running in --1.8 mode

### ISSUE THREAD

**Issue by ms-ati** [bundler/bundler#4586]
It appears that Bundler 1.12.4 cannot exec rake 10.5.0 on jruby 1.7.19 running in --1.8 mode. This happens to be the configuration used in Travis CI for `jruby-18mode`.

To reproduce locally:

```
rvm get stable
rvm install jruby-1.7.19
rvm use jruby-1.7.19@new-gemset-name --create
gem install rake -v 10.5.0
bundle exec rake
```

The result:

```
- What did you do?

  I ran the command `/Users/msiegel/.rvm/gems/jruby-1.7.19@docile/bin/bundle exec rake`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what actually happened was...


Error details

    TypeError: can't convert Array into String
      org/jruby/RubyKernel.java:1766:in `exec'
      /Users/msiegel/.rvm/gems/jruby-1.7.19@docile/gems/bundler-1.12.4/lib/bundler/cli/exec.rb:44:in `kernel_exec'
      /Users/msiegel/.rvm/gems/jruby-1.7.19@docile/gems/bundler-1.12.4/lib/bundler/cli/exec.rb:26:in `run'
      /Users/msiegel/.rvm/gems/jruby-1.7.19@docile/gems/bundler-1.12.4/lib/bundler/cli.rb:304:in `exec'
      org/jruby/RubyKernel.java:2222:in `send'
      /Users/msiegel/.rvm/gems/jruby-1.7.19@docile/gems/bundler-1.12.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /Users/msiegel/.rvm/gems/jruby-1.7.19@docile/gems/bundler-1.12.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /Users/msiegel/.rvm/gems/jruby-1.7.19@docile/gems/bundler-1.12.4/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /Users/msiegel/.rvm/gems/jruby-1.7.19@docile/gems/bundler-1.12.4/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /Users/msiegel/.rvm/gems/jruby-1.7.19@docile/gems/bundler-1.12.4/lib/bundler/cli.rb:11:in `start'
      /Users/msiegel/.rvm/gems/jruby-1.7.19@docile/gems/bundler-1.12.4/exe/bundle:27:in `(root)'
      /Users/msiegel/.rvm/gems/jruby-1.7.19@docile/gems/bundler-1.12.4/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
      /Users/msiegel/.rvm/gems/jruby-1.7.19@docile/gems/bundler-1.12.4/exe/bundle:19:in `(root)'
      org/jruby/RubyKernel.java:1082:in `load'
      /Users/msiegel/.rvm/gems/jruby-1.7.19@docile/bin/bundle:23:in `(root)'

Environment

  Bundler   1.12.4
  Rubygems  2.4.5
  Ruby      1.8.7 (2015-01-29 patchlevel 376) [java]
  GEM_HOME  /Users/msiegel/.rvm/gems/jruby-1.7.19@docile
  GEM_PATH  /Users/msiegel/.rvm/gems/jruby-1.7.19@docile:/Users/msiegel/.rvm/gems/jruby-1.7.19@global
  RVM       1.27.0 (latest)
  Git       2.8.2
  rubygems-bundler (1.4.4)

      Bundler settings

  orig_path
    Set via BUNDLE_ORIG_PATH: "/Users/msiegel/.rvm/gems/jruby-1.7.19@docile/bin:/Users/msiegel/.rvm/gems/jruby-1.7.19@global/bin:/Users/msiegel/.rvm/rubies/jruby-1.7.19/bin:/Users/msiegel/.rvm/bin:/opt/homebrew-cask/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin:/usr/local/sbin:/usr/local/bin:~/bin:/Users/msiegel/.jenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
  orig_gem_path
    Set via BUNDLE_ORIG_GEM_PATH: "/Users/msiegel/.rvm/gems/jruby-1.7.19@docile:/Users/msiegel/.rvm/gems/jruby-1.7.19@global"
  bin_path
    Set via BUNDLE_BIN_PATH: "/Users/msiegel/.rvm/gems/jruby-1.7.19@docile/gems/bundler-1.12.4/exe/bundle"
  gemfile
    Set via BUNDLE_GEMFILE: "/Users/msiegel/Documents/opensource/docile/Gemfile"
```

Please note that I checked, and this doesn't appear to be related to #1844, even though they have similar text.

**Comment by ms-ati** [comment]
To anyone who encounters this bug by trying to support Ruby 1.8 versions: use rake version `~> 10.4.2` instead, which seems to work.

**Comment by ms-ati** [comment]
Update: it appears that the problem actually has nothing to do with rake version, so the above comment about 10.4.2 is wrong. As far as I can tell, bundler 1.12.4 is broken in `bundle exec` on jruby-18mode, period.

Does anyone know any more?

**Comment by segiddins** [comment]
`bundle exec rake` works just fine for me under jruby

**Comment by ms-ati** [comment]
Hi @segiddins I apologize for not clarifying, this is *jruby*, in *1.8* mode. That's equivalent to the travis ci config `jruby-18mode`, and you should add this environment variable locally to produce the behavior:

```bash
export JRUBY_OPTS="--1.8"
```

If you still can't reproduce, please see my failing builds from the Docile gem, for example: https://travis-ci.org/ms-ati/docile/jobs/131159524

**Comment by segiddins** [comment]
`warning: --1.8 ignored`

**Comment by ms-ati** [comment]
@segiddins: what version of jruby are you using? Is it not 1.7.19?

**Comment by segiddins** [comment]
ah missed that, it's whatever the latest version is

**Comment by ms-ati** [comment]
Can you reproduce the issue in jruby 1.7.19 in 1.8 mode? Do you know on what exact jruby version it was working for you in 1.8 mode?

If so, that would make me think I should report to travis project to upgrade the jruby in jruby-18mode?

**Comment by segiddins** [comment]
I don't know what jruby 1.8 mode even is 😁

**Comment by ojab** [comment]
Looks like JRuby in 1.8 mode has buggy Kernel.exec, i. e. it does not support 'If command is a two-element array, the first element is the command to be executed, and the second argument is used as the argv[0] value, which may show up in process listings. ' part (fails with `TypeError: can't convert Array into String`).
Filled https://github.com/bundler/bundler/pull/4790 to fix it.
