### ISSUE TITLE
bundler failing under invokedynamic

### ISSUE THREAD

**Issue by abiacco** [bundler/bundler#4587]
Not sure this is a bundler issue, but i'm posting the issue just in case it is.

jruby 9.1.0.0
bundler 1.12.2
java 8u77
centos 6.7 x64
war running under tomcat

I'm trying to test my app under invokedynamic (-Djruby.compile.invokedynamic=true), upon trying to start the app in tomcat I get the log below. Not sure why it's taking the mysql2 gem of the ruby platform block into consideration being this is a jruby env. For the mysql section of my jruby platform block the relevant section is: 

platforms :jruby do
  gem 'activerecord-jdbc-adapter',      '1.3.20'
  gem 'jdbc-mysql',                     '5.1.38',   :require=>false
  gem 'activerecord-jdbcmysql-adapter', '1.3.20'
  gem 'jruby-rack-worker', '0.10.1', :require => nil
end

Without invokedynamic it works fine.

2016-05-18 14:02:31:262 INFO  jruby.rack - jruby 9.1.0.0 (2.3.0) 2016-05-02 a633c63 Java HotSpot(TM) 64-Bit Server VM 25.77-b03 on 1.8.0_77-b03 +indy +jit [linux-x86_64]
2016-05-18 14:02:31:270 INFO  jruby.rack - using a shared (threadsafe!) runtime
2016-05-18 14:02:59:503 INFO  jruby.rack - An exception happened during JRuby-Rack startup

[!] There was an error parsing `Gemfile`: You cannot specify the same gem twice with different version requirements.
You specified: rails (= 4.2.6) and mysql2 (= 0.3.18). Bundler cannot continue.

 #  from /path/to/Gemfile:40
 #  -------------------------------------------
 #  platforms :ruby do
 >    gem 'mysql2', '0.3.18'
 #    gem 'dalli' # Memcached
 #  -------------------------------------------
--- System
jruby 9.1.0.0 (2.3.0) 2016-05-02 a633c63 Java HotSpot(TM) 64-Bit Server VM 25.77-b03 on 1.8.0_77-b03 +indy +jit
 [linux-x86_64]
Time: 2016-05-18 14:02:59 -0600
Server: HD-app-0x
jruby.home: uri:classloader://META-INF/jruby.home

--- Context Init Parameters:
QUEUES = general,email-summary,email-newsletter
gem.path = /WEB-INF/vendor/bundle
jruby.max.runtimes = 1
jruby.min.runtimes = 1
jruby.rack.error.app = require 'jruby/rack/error_app'; run JRuby::Rack::ErrorApp.new
jruby.rack.logging = log4j
jruby.worker = delayed_job
public.root = /
rails.env = dev

--- Backtrace
Bundler::Dsl::DSLError:
[!] There was an error parsing `Gemfile`: You cannot specify the same gem twice with different version requirem
ents.
You specified: rails (= 4.2.6) and mysql2 (= 0.3.18). Bundler cannot continue.

 #  from /path/to/Gemfile:40
 #  -------------------------------------------
 #  platforms :ruby do
 >    gem 'mysql2', '0.3.18'
 #    gem 'dalli' # Memcached
 #  -------------------------------------------

  eval_gemfile at /path/to/vendor/bundle/gems/bundler-
1.12.2/lib/bundler/dsl.rb:45
      evaluate at /path/to/vendor/bundle/gems/bundler-
1.12.2/lib/bundler/dsl.rb:11
         build at /path/to/vendor/bundle/gems/bundler-
1.12.2/lib/bundler/definition.rb:25
    definition at /path/to/vendor/bundle/gems/bundler-
1.12.2/lib/bundler.rb:123
         setup at /path/to/vendor/bundle/gems/bundler-
1.12.2/lib/bundler.rb:91
         <top> at /path/to/vendor/bundle/gems/bundler-
1.12.2/lib/bundler/setup.rb:19
       require at org/jruby/RubyKernel.java:944
        (root) at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:1
         <top> at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:133
       require at org/jruby/RubyKernel.java:944
        (root) at /path/to/config/boot.rb:4
        (root) at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:1
       require at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55
         <top> at uri:classloader:/jruby/rack/rails/environment3.rb:23

--- RubyGems
Gem.dir: /path/to/vendor/bundle
Gem.path:
/path/to/vendor/bundle
Activated gems:
  bundler-1.12.2

--- Bundler
Bundler.bundle_path: /path/to/vendor/bundle
Bundler.root: /path/to
Gemfile: /path/to/Gemfile
Settings:
  gemfile = /path/to/Gemfile
  without = deployment:development:doc:test
  orig_path = /sbin:/usr/sbin:/bin:/usr/bin
  orig_gem_path = /path/to/vendor/bundle

**Comment by abiacco** [comment]
This does not fail under jruby 9.0.5.0 w/bundler 1.11.2

**Comment by abiacco** [comment]
Does not fail under jruby 9.0.5.0 w/bundler 1.12.2 either.

**Comment by abiacco** [comment]
Fails under 9.1.0.0 w/bundler 1.11.2, so it's 9.1.0.0 specific, though with 1.11.2 the gem error now references jruby-jars instead of mysql2

org.jruby.rack.RackInitializationException:
[!] There was an error parsing `Gemfile`: You cannot specify the same gem twice with different version requirements.
You specified: rails (= 4.2.6) and jruby-jars (= 9.1.0.0). Bundler cannot continue.

 #  from /path/to/Gemfile:35
 #  -------------------------------------------
 #    #gem 'bouncy-castle-java', '1.5.0147'
 >    gem 'jruby-jars', '9.1.0.0'
 #  end
 #  -------------------------------------------

**Comment by kares** [comment]
make sure you `bundle install` under latest (1.12.5), if you're also using MRI same there. might help!

**Comment by indirect** [comment]
As far as I know, anything that breaks when invokedynamic is turned on is a big in JRuby. Please report this to them, but feel free to let us know if there is a bug in Bundler.
