### ISSUE TITLE
I am trying to install Gems using bundler 1.12.2. I get the following error

### ISSUE THREAD

**Issue by rabin997** [bundler/bundler#4588]
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?
  
  I ran the command `C:\Ruby193\bin/bundle update`
- What did you expect to happen?
  
  I expected Bundler to...
- What happened instead?
  
  Instead, what actually happened was...

Error details

```
NoMemoryError: failed to allocate memory
  C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/package/tar_reader/entry.rb:126:in `read'
  C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/package/tar_reader/entry.rb:126:in `read'
  C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/format.rb:73:in `block (2 levels) in from_io'
  C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/package/tar_reader.rb:64:in `block in each'
  C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/package/tar_reader.rb:55:in `loop'
  C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/package/tar_reader.rb:55:in `each'
  C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/package/tar_input.rb:137:in `block (2 levels) in each'
  C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/package/tar_reader.rb:28:in `new'
  C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/package/tar_input.rb:136:in `block in each'
  C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/package/tar_reader.rb:64:in `block in each'
  C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/package/tar_reader.rb:55:in `loop'
  C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/package/tar_reader.rb:55:in `each'
  C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/package/tar_input.rb:131:in `each'
  C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/format.rb:66:in `block in from_io'
  C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/package/tar_input.rb:21:in `open'
  C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/package.rb:44:in `open'
  C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/format.rb:62:in `from_io'
  C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/format.rb:46:in `block in from_file_by_path'
  C:/Ruby193/lib/ruby/1.9.1/open-uri.rb:35:in `open'
  C:/Ruby193/lib/ruby/1.9.1/open-uri.rb:35:in `open'
  C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/format.rb:45:in `from_file_by_path'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/bundler-1.12.2/lib/bundler/rubygems_integration.rb:236:in `gem_from_path'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/bundler-1.12.2/lib/bundler/rubygems_integration.rb:241:in `spec_from_gem'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/bundler-1.12.2/lib/bundler/source/rubygems.rb:116:in `install'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/bundler-1.12.2/lib/bundler/installer/gem_installer.rb:57:in `install'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/bundler-1.12.2/lib/bundler/installer/gem_installer.rb:15:in `install_from_spec'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/bundler-1.12.2/lib/bundler/installer/parallel_installer.rb:89:in `block in worker_pool'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/bundler-1.12.2/lib/bundler/worker.rb:65:in `call'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/bundler-1.12.2/lib/bundler/worker.rb:65:in `apply_func'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/bundler-1.12.2/lib/bundler/worker.rb:60:in `block in process_queue'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/bundler-1.12.2/lib/bundler/worker.rb:57:in `loop'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/bundler-1.12.2/lib/bundler/worker.rb:57:in `process_queue'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/bundler-1.12.2/lib/bundler/worker.rb:29:in `block (2 levels) in initialize'
```

Environment

  Bundler   1.12.2
  Rubygems  1.8.29
  Ruby      1.9.3p551 (2014-11-13 revision 0) [i386-mingw32]
  GEM_HOME  C:/Ruby193/lib/ruby/gems/1.9.1
  GEM_PATH  C:/Ruby193/lib/ruby/gems/1.9.1;C:/Users/aler1/.gem/ruby/1.9.1
  Git       not installed
--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/bundler/bundler/search?q=failed+to+allocate+memory&type=Issues

If there aren't any reports for this error yet, please create copy and paste the report template above into a new issue. Don't forget to anonymize any private data! The new issue form is located at:
https://github.com/bundler/bundler/issues/new

Process finished with exit code 1

**Comment by segiddins** [comment]
Can you please share the output of `bundle env`? Thanks!

**Comment by rabin997** [comment]
Thanks for the response. I am not sure what bundle environment is. So I am putting all my error file. Please let me know if this what now you are looking for.

C:\Ruby193\bin\ruby.exe -e $stdout.sync=true;$stderr.sync=true;load($0=ARGV.shift) C:\Ruby193\bin/bundle update
Warning: this Gemfile contains multiple primary sources. Using `source` more than once without a block is a security risk, and may result in installing unexpected gems. To resolve this warning, use a block to indicate which gems should come from the secondary source. To upgrade this warning to an error, run `bundle config disable_multisource true`.
Fetching gem metadata from http://rubygems.org/
Fetching gem metadata from http://cvms1187.nwie.net/geminabox/....
Fetching version metadata from http://rubygems.org/
Fetching version metadata from http://cvms1187.nwie.net/geminabox/...
Fetching version metadata from http://rubygems.org/
Fetching version metadata from http://cvms1187.nwie.net/geminabox/...
Fetching dependency metadata from http://rubygems.org/
Fetching dependency metadata from http://cvms1187.nwie.net/geminabox/..
Resolving dependencies...
Rubygems 1.8.29 is not threadsafe, so your gems will be installed one at a time. Upgrade to Rubygems 2.1.0 or higher to enable parallel gem installation.
Using MessageTracker 1.3.3
Using dish 0.0.6
Using monkey-extender 1.0.20
Using FastLogger 0.2.1
Using NWIEWhich 0.9.2
Using colorize 0.7.7
Using builder 3.2.2
Using diff-lcs 1.2.5
Using multi_json 1.12.1
Using multi_test 0.1.2
Using cs_delegate 1.0.0
Using ffi 1.9.10
Using rubyzip 1.2.0
Using websocket 1.2.3
Using bundler 1.12.2
Using ninuy 1.0.15
Using gherkin 2.12.2
Using childprocess 0.5.9
Using DataProvider 3.0.8
Using cucumber 1.3.20
Using selenium-webdriver 2.45.0
Using CSVDataSource 2.0.6
Using boop 3.8.14
Using ExcelDataSource 1.0.53
Using TaskDSL 4.4.3
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `C:\Ruby193\bin/bundle update`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what actually happened was...


Error details

    NoMemoryError: failed to allocate memory
      C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/package/tar_reader/entry.rb:126:in `read'
      C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/package/tar_reader/entry.rb:126:in `read'
      C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/format.rb:73:in `block (2 levels) in from_io'
      C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/package/tar_reader.rb:64:in `block in each'
      C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/package/tar_reader.rb:55:in `loop'
      C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/package/tar_reader.rb:55:in `each'
      C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/package/tar_input.rb:137:in `block (2 levels) in each'
      C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/package/tar_reader.rb:28:in `new'
      C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/package/tar_input.rb:136:in `block in each'
      C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/package/tar_reader.rb:64:in `block in each'
      C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/package/tar_reader.rb:55:in `loop'
      C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/package/tar_reader.rb:55:in `each'
      C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/package/tar_input.rb:131:in `each'
      C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/format.rb:66:in `block in from_io'
      C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/package/tar_input.rb:21:in `open'
      C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/package.rb:44:in `open'
      C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/format.rb:62:in `from_io'
      C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/format.rb:46:in `block in from_file_by_path'
      C:/Ruby193/lib/ruby/1.9.1/open-uri.rb:35:in `open'
      C:/Ruby193/lib/ruby/1.9.1/open-uri.rb:35:in `open'
      C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/format.rb:45:in `from_file_by_path'
      C:/Ruby193/lib/ruby/gems/1.9.1/gems/bundler-1.12.2/lib/bundler/rubygems_integration.rb:236:in `gem_from_path'
      C:/Ruby193/lib/ruby/gems/1.9.1/gems/bundler-1.12.2/lib/bundler/rubygems_integration.rb:241:in `spec_from_gem'
      C:/Ruby193/lib/ruby/gems/1.9.1/gems/bundler-1.12.2/lib/bundler/source/rubygems.rb:116:in `install'
      C:/Ruby193/lib/ruby/gems/1.9.1/gems/bundler-1.12.2/lib/bundler/installer/gem_installer.rb:57:in `install'
      C:/Ruby193/lib/ruby/gems/1.9.1/gems/bundler-1.12.2/lib/bundler/installer/gem_installer.rb:15:in `install_from_spec'
      C:/Ruby193/lib/ruby/gems/1.9.1/gems/bundler-1.12.2/lib/bundler/installer/parallel_installer.rb:89:in `block in worker_pool'
      C:/Ruby193/lib/ruby/gems/1.9.1/gems/bundler-1.12.2/lib/bundler/worker.rb:65:in `call'
      C:/Ruby193/lib/ruby/gems/1.9.1/gems/bundler-1.12.2/lib/bundler/worker.rb:65:in `apply_func'
      C:/Ruby193/lib/ruby/gems/1.9.1/gems/bundler-1.12.2/lib/bundler/worker.rb:60:in `block in process_queue'
      C:/Ruby193/lib/ruby/gems/1.9.1/gems/bundler-1.12.2/lib/bundler/worker.rb:57:in `loop'
      C:/Ruby193/lib/ruby/gems/1.9.1/gems/bundler-1.12.2/lib/bundler/worker.rb:57:in `process_queue'
      C:/Ruby193/lib/ruby/gems/1.9.1/gems/bundler-1.12.2/lib/bundler/worker.rb:29:in `block (2 levels) in initialize'

Environment
      
  Bundler   1.12.2
  Rubygems  1.8.29
  Ruby      1.9.3p551 (2014-11-13 revision 0) [i386-mingw32]
  GEM_HOME  C:/Ruby193/lib/ruby/gems/1.9.1
  GEM_PATH  C:/Ruby193/lib/ruby/gems/1.9.1;C:/Users/aler1/.gem/ruby/1.9.1
  Git       not installed
--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/bundler/bundler/search?q=failed+to+allocate+memory&type=Issues

If there aren't any reports for this error yet, please create copy and paste the report template above into a new issue. Don't forget to anonymize any private data! The new issue form is located at:
https://github.com/bundler/bundler/issues/new

Process finished with exit code 1

**Comment by segiddins** [comment]
Please run the command `bundle env` and share the output (we need to see your Gemfile). Thanks.

**Comment by rabin997** [comment]
C:\Gherkin\CIQ_EASY>bundle env
io/console not supported; tty will not be manipulated
Warning: this Gemfile contains multiple primary sources. Using `source` more tha
n once without a block is a security risk, and may result in installing unexpect
ed gems. To resolve this warning, use a block to indicate which gems should come
 from the secondary source. To upgrade this warning to an error, run `bundle con
fig disable_multisource true`.
Environment

    Bundler   1.12.0.rc.4
    Rubygems  2.1.9
    Ruby      1.9.3p392 (2013-11-14 revision 39386) [java]
    Git       not installed

Gemfile

    source 'http://cvms1187.nwie.net/geminabox'
    source 'http://rubygems.org/'

    gem 'cucumber', '~> 1.3.18'
    #gem 'gherkin', '= 2.11.6' # 2.11.8 has deprecated eval error messages, and
reverting to 2.11.6 fixes that
    # gem 'pry'

    gem 'DataProvider', '~> 3.0'
    gem 'CSVDataSource', '~> 2.0'
    gem 'ExcelDataSource', '~> 1.0'
    gem 'boop', '~> 3.7'
    gem 'Woof',  '~> 4.1' #path: '../Woof' to use project folder
    gem 'TaskDSL'

**Comment by MarkDBlackwell** [comment]
Here's more information:
```
$ rm -f Gemfile.lock; bundle update
Fetching gem metadata from https://rubygems.org/
Fetching version metadata from https://rubygems.org/
Could not find gem 'bundle-gem-error' in source at `.`.
Source contains 'bundle-gem-error' at: 0.1.0 ruby

$ bundle platform
Your platform is: x86_64-linux

Your app has gems that work on these platforms:
* ruby

Your Gemfile specifies a Ruby version requirement:
* ruby 2.3.1p112

Your current platform satisfies the Ruby version requirement.

$ bundle env
Environment

    Bundler   1.12.4
    Rubygems  2.6.4
    Ruby      2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
    GEM_HOME  /home/mark/.rvm/gems/ruby-2.3.1
    GEM_PATH  /home/mark/.rvm/gems/ruby-2.3.1:/home/mark/.rvm/gems/ruby-2.3.1@global
    RVM       1.27.0 (latest)
    Git       2.1.4
    rubygems-bundler (1.4.4)

Bundler settings

    gem.test
      Set for the current user (/home/mark/.bundle/config): "minitest"
    gem.mit
      Set for the current user (/home/mark/.bundle/config): "true"
    gem.coc
      Set for the current user (/home/mark/.bundle/config): "true"
    orig_path
      Set via BUNDLE_ORIG_PATH: "/home/mark/.rvm/gems/ruby-2.3.1/bin:/home/mark/.rvm/gems/ruby-2.3.1@global/bin:/home/mark/.rvm/rubies/ruby-2.3.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/home/mark/.rvm/bin"
    orig_gem_path
      Set via BUNDLE_ORIG_GEM_PATH: "/home/mark/.rvm/gems/ruby-2.3.1:/home/mark/.rvm/gems/ruby-2.3.1@global"

Gemfile

    source 'https://rubygems.org'
    # ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
    ruby '2.3.1', engine_version: '2.3.1', engine: 'ruby', patchlevel: '112'
    # Specify your gem's dependencies in bundle-gem-error.gemspec
    gemspec

Gemfile.lock

    <No /home/mark/develop/bundle-gem-error/Gemfile.lock found>

bundle-gem-error.gemspec

    # coding: utf-8
    lib = File.expand_path('../lib', __FILE__)
    $LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)
    require 'bundle/gem/error/version'
    Gem::Specification.new do |spec|
    # ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
      spec.required_ruby_version = '2.3.1.112'
      spec.name          = "bundle-gem-error"
      spec.version       = Bundle::Gem::Error::VERSION
      spec.authors       = ["fake"]
      spec.email         = ["fake@example.com"]
      spec.summary       = %q{fake}
      spec.description   = %q{fake2}
      spec.homepage      = "http://fake.example.com"
      spec.license       = "MIT"
      # Prevent pushing this gem to RubyGems.org. To allow pushes either set the 'allowed_push_host'
      # to allow pushing to a single host or delete this section to allow pushing to any host.
      if spec.respond_to?(:metadata)
        spec.metadata['allowed_push_host'] = "TODO: Set to 'http://mygemserver.com'"
      else
        raise "RubyGems 2.0 or newer is required to protect against public gem pushes."
      end
      spec.files         = `git ls-files -z`.split("\x0").reject { |f| f.match(%r{^(test|spec|features)/}) }
      spec.bindir        = "exe"
      spec.executables   = spec.files.grep(%r{^exe/}) { |f| File.basename(f) }
      spec.require_paths = ["lib"]
      spec.add_development_dependency "bundler", "~> 1.12"
      spec.add_development_dependency "rake", "~> 10.0"
      spec.add_development_dependency "minitest", "~> 5.0"
    end
```

**Comment by kyleshevlin** [comment]
If any progress was made on this error, I would be interested. I believe I have run into the same (or at least similar error). I thought it was a lack of memory issue and I enabled a swap file on my server and yet it still errored.

**Comment by lynnco** [comment]
This is the only place this particular error has been reported (which is an achievement, IMO). When we have a resolution plan we'll mention it here.

**Comment by christophermlne** [comment]
I also am having this issue:

$ bundle env

```
Wnvironment

    Bundler   1.13.6
    Rubygems  2.5.1
    Ruby      2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
    Git       1.9.1

Bundler settings

    without
      Set for your local app (/var/www/app/application/.bundle/config): "development:test"

Gemfile

    source 'https://rubygems.org'

    # Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
    gem 'rails', '4.2.4'
    #gem 'sqlite3'

    gem 'devise_token_auth'
    gem 'omniauth' # required for devise_token_auth

    gem 'pg'
    gem 'sass-rails', '~> 5.0'
    gem 'uglifier', '>= 1.3.0'
    gem 'coffee-rails', '~> 4.1.0'
    # gem 'therubyracer', platforms: :ruby

    gem 'rack-cors', :require => 'rack/cors'
    gem 'jsonapi-resources', '0.7.0'

    gem 'jquery-rails'
    gem 'turbolinks'
    gem 'jbuilder', '~> 2.0'

    gem 'form_renderer', :git => 'git@bitbucket.org:christophermilne/form-renderer.git'
    # gem 'bcrypt', '~> 3.1.7'

    gem 'unicorn'

    # Use Capistrano for deployment
    # gem 'capistrano-rails', group: :development

    group :development, :test do
      # Call 'byebug' anywhere in the code to stop execution and get a debugger console
      gem 'byebug'
      gem 'rspec', '~> 3.3.0'
      gem 'faker'
    end

    group :development do
      gem 'web-console', '~> 2.0'
      gem 'spring'
    end

Gemfile.lock

    GIT
      remote: git@bitbucket.org:christophermilne/form-renderer.git
      revision: dc9496b6e3cede51438e5aa6d15027ccc9155d29
      specs:
        form_renderer (0.1.0)

    GEM
      remote: https://rubygems.org/
      specs:
        actionmailer (4.2.4)
          actionpack (= 4.2.4)
          actionview (= 4.2.4)
          activejob (= 4.2.4)
          mail (~> 2.5, >= 2.5.4)
          rails-dom-testing (~> 1.0, >= 1.0.5)
        actionpack (4.2.4)
          actionview (= 4.2.4)
          activesupport (= 4.2.4)
          rack (~> 1.6)
          rack-test (~> 0.6.2)
          rails-dom-testing (~> 1.0, >= 1.0.5)
          rails-html-sanitizer (~> 1.0, >= 1.0.2)
        actionview (4.2.4)
          activesupport (= 4.2.4)
          builder (~> 3.1)
          erubis (~> 2.7.0)
          rails-dom-testing (~> 1.0, >= 1.0.5)
          rails-html-sanitizer (~> 1.0, >= 1.0.2)
        activejob (4.2.4)
          activesupport (= 4.2.4)
          globalid (>= 0.3.0)
        activemodel (4.2.4)
          activesupport (= 4.2.4)
          builder (~> 3.1)
        activerecord (4.2.4)
          activemodel (= 4.2.4)
          activesupport (= 4.2.4)
          arel (~> 6.0)
        activesupport (4.2.4)
          i18n (~> 0.7)
          json (~> 1.7, >= 1.7.7)
          minitest (~> 5.1)
          thread_safe (~> 0.3, >= 0.3.4)
          tzinfo (~> 1.1)
        arel (6.0.3)
        bcrypt (3.1.10)
        binding_of_caller (0.7.2)
          debug_inspector (>= 0.0.1)
        builder (3.2.2)
        byebug (6.0.2)
        coffee-rails (4.1.0)
          coffee-script (>= 2.2.0)
          railties (>= 4.0.0, < 5.0)
        coffee-script (2.4.1)
          coffee-script-source
          execjs
        coffee-script-source (1.9.1.1)
        debug_inspector (0.0.2)
        devise (3.5.3)
          bcrypt (~> 3.0)
          orm_adapter (~> 0.1)
          railties (>= 3.2.6, < 5)
          responders
          thread_safe (~> 0.1)
          warden (~> 1.2.3)
        devise_token_auth (0.1.36)
          devise (~> 3.5.2)
          rails (~> 4.2)
        diff-lcs (1.2.5)
        erubis (2.7.0)
        execjs (2.6.0)
        faker (1.6.1)
          i18n (~> 0.5)
        globalid (0.3.6)
          activesupport (>= 4.1.0)
        hashie (3.4.3)
        i18n (0.7.0)
        jbuilder (2.3.1)
          activesupport (>= 3.0.0, < 5)
          multi_json (~> 1.2)
        jquery-rails (4.0.5)
          rails-dom-testing (~> 1.0)
          railties (>= 4.2.0)
          thor (>= 0.14, < 2.0)
        json (1.8.3)
        jsonapi-resources (0.7.0)
          rails (>= 4.0)
        kgio (2.10.0)
        loofah (2.0.3)
          nokogiri (>= 1.5.9)
        mail (2.6.3)
          mime-types (>= 1.16, < 3)
        mime-types (2.6.2)
        mini_portile (0.6.2)
        minitest (5.8.0)
        multi_json (1.11.2)
        nokogiri (1.6.6.2)
          mini_portile (~> 0.6.0)
        omniauth (1.3.1)
          hashie (>= 1.2, < 4)
          rack (>= 1.0, < 3)
        orm_adapter (0.5.0)
        pg (0.18.3)
        rack (1.6.4)
        rack-cors (0.4.0)
        rack-test (0.6.3)
          rack (>= 1.0)
        rails (4.2.4)
          actionmailer (= 4.2.4)
          actionpack (= 4.2.4)
          actionview (= 4.2.4)
          activejob (= 4.2.4)
          activemodel (= 4.2.4)
          activerecord (= 4.2.4)
          activesupport (= 4.2.4)
          bundler (>= 1.3.0, < 2.0)
          railties (= 4.2.4)
          sprockets-rails
        rails-deprecated_sanitizer (1.0.3)
          activesupport (>= 4.2.0.alpha)
        rails-dom-testing (1.0.7)
          activesupport (>= 4.2.0.beta, < 5.0)
          nokogiri (~> 1.6.0)
          rails-deprecated_sanitizer (>= 1.0.1)
        rails-html-sanitizer (1.0.2)
          loofah (~> 2.0)
        railties (4.2.4)
          actionpack (= 4.2.4)
          activesupport (= 4.2.4)
          rake (>= 0.8.7)
          thor (>= 0.18.1, < 2.0)
        raindrops (0.17.0)
        rake (10.4.2)
        responders (2.1.1)
          railties (>= 4.2.0, < 5.1)
        rspec (3.3.0)
          rspec-core (~> 3.3.0)
          rspec-expectations (~> 3.3.0)
          rspec-mocks (~> 3.3.0)
        rspec-core (3.3.2)
          rspec-support (~> 3.3.0)
        rspec-expectations (3.3.1)
          diff-lcs (>= 1.2.0, < 2.0)
          rspec-support (~> 3.3.0)
        rspec-mocks (3.3.2)
          diff-lcs (>= 1.2.0, < 2.0)
          rspec-support (~> 3.3.0)
        rspec-support (3.3.0)
        sass (3.4.18)
        sass-rails (5.0.4)
          railties (>= 4.0.0, < 5.0)
          sass (~> 3.1)
          sprockets (>= 2.8, < 4.0)
          sprockets-rails (>= 2.0, < 4.0)
          tilt (>= 1.1, < 3)
        spring (1.4.0)
        sprockets (3.3.4)
          rack (~> 1.0)
        sprockets-rails (2.3.3)
          actionpack (>= 3.0)
          activesupport (>= 3.0)
          sprockets (>= 2.8, < 4.0)
        thor (0.19.1)
        thread_safe (0.3.5)
        tilt (2.0.1)
        turbolinks (2.5.3)
          coffee-rails
        tzinfo (1.2.2)
          thread_safe (~> 0.1)
        uglifier (2.7.2)
          execjs (>= 0.3.0)
          json (>= 1.8.0)
        unicorn (5.1.0)
          kgio (~> 2.6)
          raindrops (~> 0.7)
        warden (1.2.4)
          rack (>= 1.0)
        web-console (2.2.1)
          activemodel (>= 4.0)
          binding_of_caller (>= 0.7.2)
          railties (>= 4.0)
          sprockets-rails (>= 2.0, < 4.0)

    PLATFORMS
      ruby

    DEPENDENCIES
      byebug
      coffee-rails (~> 4.1.0)
      devise_token_auth
      faker
      form_renderer!
      jbuilder (~> 2.0)
      jquery-rails
      jsonapi-resources (= 0.7.0)
      omniauth
      pg
      rack-cors
      rails (= 4.2.4)
      rspec (~> 3.3.0)
      sass-rails (~> 5.0)
      spring
      turbolinks
      uglifier (>= 1.3.0)
      unicorn
      web-console (~> 2.0)

    BUNDLED WITH
       1.11.2
```

**Comment by brazen-guff** [comment]
Hi

I'm also seeing this error (using Bundler 1.13.6), and have attached my bundle env output.

[env-output.txt](https://github.com/bundler/bundler/files/618560/env-output.txt)

Any advice gratefully received!

**Comment by segiddins** [comment]
Unable to reproduce -- `Could not reach host cvms1187.nwie.net. Check your network connection and try again.`

**Comment by segiddins** [comment]
Closing -- the error is happening with a very old Ruby & RubyGems version, and is running out of memory in RubyGem's tar handling code, rather than in Bundler code.
