### ISSUE TITLE
Errno::EACCES: Permission denied @ dir_s_mkdir - Bundler error

### ISSUE THREAD

**Issue by prabhu-karan-vine** [bundler/bundler#4590]
Exelogic008:workcloud prabhu_karan$ bundle install
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `/Users/prabhu_karan/.rbenv/versions/2.2.3/bin/bundle install`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what actually happened was...

Error details

    Errno::EACCES: Permission denied @ dir_s_mkdir - /Users/prabhu_karan/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/versions20160519-69099-1pvbmll
      /Users/prabhu_karan/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tmpdir.rb:85:in `mkdir'
      /Users/prabhu_karan/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tmpdir.rb:85:in `block in mktmpdir'
      /Users/prabhu_karan/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tmpdir.rb:129:in `create'
      /Users/prabhu_karan/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tmpdir.rb:85:in `mktmpdir'
      /Users/prabhu_karan/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.12.4/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:29:in `update'
      /Users/prabhu_karan/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.12.4/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:64:in `update'
      /Users/prabhu_karan/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.12.4/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:55:in `update_and_parse_checksums!'
      /Users/prabhu_karan/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.12.4/lib/bundler/fetcher/compact_index.rb:65:in `available?'
      /Users/prabhu_karan/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.12.4/lib/bundler/fetcher/compact_index.rb:15:in `call'
      /Users/prabhu_karan/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.12.4/lib/bundler/fetcher/compact_index.rb:15:in `block in compact_index_request'
      /Users/prabhu_karan/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.12.4/lib/bundler/fetcher.rb:154:in `use_api'
      /Users/prabhu_karan/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.12.4/lib/bundler/source/rubygems.rb:331:in `block in api_fetchers'
      /Users/prabhu_karan/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.12.4/lib/bundler/source/rubygems.rb:331:in `select'
      /Users/prabhu_karan/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.12.4/lib/bundler/source/rubygems.rb:331:in `api_fetchers'
      /Users/prabhu_karan/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.12.4/lib/bundler/source/rubygems.rb:336:in `block in remote_specs'
      /Users/prabhu_karan/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.12.4/lib/bundler/index.rb:10:in `build'
      /Users/prabhu_karan/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.12.4/lib/bundler/source/rubygems.rb:335:in `remote_specs'
      /Users/prabhu_karan/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.12.4/lib/bundler/source/rubygems.rb:82:in `specs'
      /Users/prabhu_karan/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.12.4/lib/bundler/definition.rb:211:in `block (2 levels) in index'
      /Users/prabhu_karan/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.12.4/lib/bundler/definition.rb:209:in `each'
      /Users/prabhu_karan/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.12.4/lib/bundler/definition.rb:209:in `block in index'
      /Users/prabhu_karan/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.12.4/lib/bundler/index.rb:10:in `build'
      /Users/prabhu_karan/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.12.4/lib/bundler/definition.rb:206:in `index'
      /Users/prabhu_karan/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.12.4/lib/bundler/definition.rb:200:in `resolve'
      /Users/prabhu_karan/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.12.4/lib/bundler/definition.rb:140:in `specs'
      /Users/prabhu_karan/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.12.4/lib/bundler/definition.rb:129:in `resolve_remotely!'
      /Users/prabhu_karan/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.12.4/lib/bundler/installer.rb:195:in `resolve_if_need'
      /Users/prabhu_karan/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.12.4/lib/bundler/installer.rb:70:in `run'
      /Users/prabhu_karan/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.12.4/lib/bundler/installer.rb:22:in `install'
      /Users/prabhu_karan/.rbenv/rbenv.d/exec/gem-rehash/rubygems_plugin.rb:27:in `install'
      /Users/prabhu_karan/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.12.4/lib/bundler/cli/install.rb:102:in `run'
      /Users/prabhu_karan/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.12.4/lib/bundler/cli.rb:175:in `install'
      /Users/prabhu_karan/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.12.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /Users/prabhu_karan/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.12.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /Users/prabhu_karan/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.12.4/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /Users/prabhu_karan/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.12.4/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /Users/prabhu_karan/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.12.4/lib/bundler/cli.rb:11:in `start'
      /Users/prabhu_karan/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.12.4/exe/bundle:27:in `block in <top (required)>'
      /Users/prabhu_karan/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.12.4/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
      /Users/prabhu_karan/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.12.4/exe/bundle:19:in `<top (required)>'
      /Users/prabhu_karan/.rbenv/versions/2.2.3/bin/bundle:22:in `load'
      /Users/prabhu_karan/.rbenv/versions/2.2.3/bin/bundle:22:in `<main>'

Environment

  Bundler   1.12.4
  Rubygems  2.6.4
  Ruby      2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin14]
  GEM_HOME  /Users/prabhu_karan/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0
  GEM_PATH  /Users/prabhu_karan/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0:/Users/prabhu_karan/.gem/ruby/2.2.0
  Git       2.8.1

      Bundler settings

  orig_path
    Set via BUNDLE_ORIG_PATH: "/Users/prabhu_karan/.rbenv/versions/2.2.3/bin:/Users/prabhu_karan/.rbenv/libexec:/Users/prabhu_karan/.rbenv/shims:/Users/prabhu_karan/.rbenv/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/git/bin:/usr/local/mysql/bin:/Users/prabhu_karan/.rvm/bin"
--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/bundler/bundler/search?q=Permission+denied+%40+dir_s_mkdir+-+%2FUsers%2Fprabhu_karan%2F.bundle%2Fcache%2Fcompact_index%2Frubygems.org.443.29b0360b937aa4d161703e6160654e47%2Fversions20160519-69099-1pvbmll&type=Issues

If there aren't any reports for this error yet, please create copy and paste the report template above into a new issue. Don't forget to anonymize any private data! The new issue form is located at:
https://github.com/bundler/bundler/issues/new

**Comment by yuu3** [comment]
Please check permission for ~/.bundle directory.
Probably root permission.

1. Delete 
$ sudo mv  ~/.bundle /tmp

2. Try install
$ bundle install

**Comment by RochesterinNYC** [comment]
There are similar issues at #4579 and #4458. Do either of those resolution methods or @yuu3's resolve your issue?

**Comment by jack-michaud** [comment]
@RochesterinNYC - I had an identical permissions problem, @yuu3's solution resolved it. I would feel comfortable with this issue closed!

**Comment by RochesterinNYC** [comment]
Gotcha. Thanks.

**Comment by souzagab** [comment]
For me it was a permission issue with rbenv: 
`sudo chown -R your-user $HOME/.rbenv`
