### ISSUE TITLE
Could not find 'bundler'

### ISSUE THREAD

**Issue by guxiaobai** [bundler/bundler#4592]
Software
  * osx 10.11.4
  * rbenv 1.0.0
  * ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin15]
  * Rails 4.2.6

bundle exec gem list|grep guard

    guard (2.13.0)
    guard-compat (1.2.1)
    guard-rspec (4.6.5)

bundle exec guard -d

    RubyDep: WARNING: Your Ruby has security vulnerabilities! (To disable warnings, set RUBY_DEP_GEM_SILENCE_WARNINGS=1)
    RubyDep: WARNING: Your Ruby is: 2.2.3 (insecure). Recommendation: install 2.2.5 or 2.3.1. (Or, at least to 2.2.4 or 2.3.0)
    00:54:56 - DEBUG - Notiffany: gntp not available (Please add "gem 'ruby_gntp'" to your Gemfile and run your app with "bundle exec".).
    00:54:56 - DEBUG - Notiffany: growl not available (Please add "gem 'growl'" to your Gemfile and run your app with "bundle exec".).
    00:54:56 - DEBUG - Notiffany: terminal_notifier not available (Please add "gem 'terminal-notifier-guard'" to your Gemfile and run your app with "bundle exec".).
    00:54:56 - DEBUG - Notiffany: libnotify not available (Unsupported platform "darwin15.4.0").
    00:54:56 - DEBUG - Notiffany: notifysend not available (Unsupported platform "darwin15.4.0").
    00:54:56 - DEBUG - Notiffany: notifu not available (Unsupported platform "darwin15.4.0").
    00:54:56 - DEBUG - Command execution: {"ALTERNATE_EDITOR"=>"false"} emacsclient --eval '1'
    00:54:56 - DEBUG - Notiffany: emacs not available (Emacs client failed).
    00:54:56 - DEBUG - Notiffany: tmux not available (:tmux notifier is only available inside a TMux session.).
    00:54:56 - DEBUG - Notiffany: file not available (No :path option given).
    00:54:56 - DEBUG - Notiffany is using TerminalTitle to send notifications.
    00:54:56 - DEBUG - Command execution: hash stty
    00:54:56 - DEBUG - Guard starts all plugins
    00:54:56 - DEBUG - Hook :start_begin executed for Guard::RSpec
    00:54:56 - INFO - Guard::RSpec is running
    00:54:56 - DEBUG - Hook :start_end executed for Guard::RSpec
    00:54:56 - INFO - Guard is now watching at '/Users/lemon/Documents/chavis'
    00:54:56 - DEBUG - Start interactor
    00:54:56 - DEBUG - Command execution: stty -g 2>/dev/null
    [1] guard(main)>
    00:54:58 - DEBUG - Interactor was stopped or killed
    00:54:58 - DEBUG - Command execution: stty  2>/dev/null
    00:54:58 - INFO - Run all
    00:54:58 - DEBUG - Hook :run_all_begin executed for Guard::RSpec
    00:54:58 - INFO - Running all specs
    /Users/lemon/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/dependency.rb:315:in `to_specs': Could not find 'bundler' (>= 0) among 98 total gem(s) (Gem::LoadError)
    Checked in 'GEM_PATH=/Users/lemon/Documents/chavis/vendor/bundle/ruby/2.2.0', execute `gem env` for more information
    	from /Users/lemon/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/dependency.rb:324:in `to_spec'
    	from /Users/lemon/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_gem.rb:64:in `gem'
    	from /Users/lemon/.rbenv/versions/2.2.3/bin/bundle:22:in `<main>'
    00:54:58 - ERROR - Failed: "bundle exec rspec -f progress -r /Users/lemon/Documents/chavis/vendor/bundle/ruby/2.2.0/gems/guard-rspec-4.6.5/lib/guard/rspec_formatter.rb -f Guard::RSpecFormatter --failure-exit-code 2  spec" (exit code: 1)

    00:54:58 - DEBUG - Start interactor
    00:54:58 - DEBUG - Command execution: stty -g 2>/dev/null
gem env

    RubyGems Environment:
      - RUBYGEMS VERSION: 2.4.5.1
      - RUBY VERSION: 2.2.3 (2015-08-18 patchlevel 173) [x86_64-darwin15]
      - INSTALLATION DIRECTORY: /Users/lemon/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0
      - RUBY EXECUTABLE: /Users/lemon/.rbenv/versions/2.2.3/bin/ruby
      - EXECUTABLE DIRECTORY: /Users/lemon/.rbenv/versions/2.2.3/bin
      - SPEC CACHE DIRECTORY: /Users/lemon/.gem/specs
      - SYSTEM CONFIGURATION DIRECTORY: /Users/lemon/.rbenv/versions/2.2.3/etc
      - RUBYGEMS PLATFORMS:
        - ruby
        - x86_64-darwin-15
      - GEM PATHS:
         - /Users/lemon/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0
         - /Users/lemon/.gem/ruby/2.2.0
      - GEM CONFIGURATION:
         - :update_sources => true
         - :verbose => true
         - :backtrace => false
         - :bulk_threshold => 1000
         - :sources => ["https://gems.ruby-china.org/"]
      - REMOTE SOURCES:
         - https://gems.ruby-china.org/
      - SHELL PATH:
         - /Users/lemon/.rbenv/versions/2.2.3/bin
         - /usr/local/Cellar/rbenv/1.0.0/libexec
         - /Users/lemon/.rbenv/shims
         - /usr/local/bin
         - /usr/bin
         - /bin
         - /usr/sbin
         - /sbin

https://github.com/guard/guard-rspec/issues/369

**Comment by RochesterinNYC** [comment]
What is the output of `bundle env`?

**Comment by biinari** [comment]
I have the same issue on arch-linux with the following:

* bundler `1.12.0.pre.2` to `1.12.4` inclusive
* rbenv `1.0.0`
* ruby `2.0.0-p247`, `2.3.1`
* rubygems `2.5.1`

ruby versions tested:

```
ruby 2.0.0p247 (2013-06-27 revision 41674) [x86_64-linux]
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
```

Bundler versions `1.12.0.pre.1` and earlier did not exhibit this problem for me.

gem env:

```
RubyGems Environment:
  - RUBYGEMS VERSION: 2.5.1
  - RUBY VERSION: 2.3.1 (2016-04-26 patchlevel 112) [x86_64-linux]
  - INSTALLATION DIRECTORY: /home/bill/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0
  - USER INSTALLATION DIRECTORY: /home/bill/.gem/ruby/2.3.0
  - RUBY EXECUTABLE: /home/bill/.rbenv/versions/2.3.1/bin/ruby
  - EXECUTABLE DIRECTORY: /home/bill/.rbenv/versions/2.3.1/bin
  - SPEC CACHE DIRECTORY: /home/bill/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /home/bill/.rbenv/versions/2.3.1/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /home/bill/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0
     - /home/bill/.gem/ruby/2.3.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - "gem" => "--no-user-install --no-ri --no-rdoc"
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /home/bill/.rbenv/versions/2.3.1/bin
     - /usr/lib/rbenv/libexec
     - /home/bill/.rbenv/plugins/rbenv-binstubs/bin
     - /home/bill/.rbenv/shims
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/bin
     - /opt/cuda/bin
     - /usr/lib/jvm/default/bin
     - /usr/bin/site_perl
     - /usr/bin/vendor_perl
     - /usr/bin/core_perl
     - /usr/local/jdk/bin
     - /home/bill/.gem/ruby/2.1.0/bin
```

I've narrowed down point where the issue is introduced to #4298. Whether the problem is with bundler or with the way guard uses it I'm not yet sure.

**Comment by biinari** [comment]
I have created a minimal repo that demonstrates when the issue occurs for me: https://github.com/biinari/bundler-rbenv-guard-issue

Included outputs from `bundle env`, `gem env`, `bundle exec guard`.

**Comment by chrismo** [comment]
I think I've diagnosed this. It's a lot, so I may be missing stuff.

In 1.12.5 (and prior 1.12 versions), `bundle exec` calls a new method, `kernel_load` if the cmd to execute (`guard` in this case) has a ruby shebang in it. => https://github.com/bundler/bundler/blob/a65a2db118ed714586ac4c56a0584c97bf0305df/lib/bundler/cli/exec.rb#L24

Inside `kernel_load` - "bundler/setup" is required. => https://github.com/bundler/bundler/blob/a65a2db118ed714586ac4c56a0584c97bf0305df/lib/bundler/cli/exec.rb#L62

That drills down into this call stack:
```
/Users/chrismo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler.rb:413:in `configure_gem_home_and_path'
/Users/chrismo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler.rb:60:in `configure'
/Users/chrismo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler.rb:121:in `definition'
/Users/chrismo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler.rb:91:in `setup'
/Users/chrismo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/setup.rb:19:in `<top (required)>'
/Users/chrismo/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Users/chrismo/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Users/chrismo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:62:in `kernel_load'
```
...ending at this bit of code:
```
    def configure_gem_home_and_path
      blank_home = ENV["GEM_HOME"].nil? || ENV["GEM_HOME"].empty?
      if settings[:disable_shared_gems]
        ENV["GEM_PATH"] = ""
      elsif blank_home || Bundler.rubygems.gem_dir != bundle_path.to_s
        possibles = [Bundler.rubygems.gem_dir, Bundler.rubygems.gem_path]
        paths = possibles.flatten.compact.uniq.reject(&:empty?)
        ENV["GEM_PATH"] = paths.join(File::PATH_SEPARATOR)
      end

      configure_gem_home
      bundle_path
    end
```
Since `--path vendor` was used, `:disable_shared_gems` is true, so `ENV['GEM_PATH']` isn't set to `nil` (like it would be in 1.11.2 which doesn't involve any of this setup) but set to empty string.

Once we jump over to the new process, we hit this initial code `load Gem.activate_bin_path('bundler', 'bundle', version)` which leads into this call stack:
```
/Users/chrismo/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/dependency.rb:279:in `matching_specs'
/Users/chrismo/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems.rb:248:in `find_spec_for_exe'
/Users/chrismo/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems.rb:278:in `activate_bin_path'
/Users/chrismo/.rbenv/versions/2.3.1/bin/bundle:22:in `<main>'
```
and no matching specs are found, because when `Gem.path` is setup in `path_support.rb`:
```
    @path = split_gem_path env["GEM_PATH"], @home
```
```
  def split_gem_path gpaths, home
    # FIX: it should be [home, *path], not [*path, home]

    gem_path = []

    if gpaths
      gem_path = gpaths.split(Gem.path_separator)
      # Handle the path_separator being set to a regexp, which will cause
      # end_with? to error
      if gpaths =~ /#{Gem.path_separator}\z/
        gem_path += default_path
      end

      if File::ALT_SEPARATOR then
        gem_path.map! do |this_path|
          this_path.gsub File::ALT_SEPARATOR, File::SEPARATOR
        end
      end

      gem_path << home
    else
      gem_path = default_path
    end

    gem_path.uniq
  end
```
=> https://github.com/rubygems/rubygems/blob/9c1101160d1b7394a4acc96f0e183334d7346dfe/lib/rubygems/path_support.rb#L65 (2.6.4)

If `gpaths` is `""` or `nil` it matters. When `nil` (1.11.2 behavior), then `Gem.path` gets `GEM_HOME` included, which is where `bundler` exists. In this case in 1.12.5, it doesn't, and bundler itself isn't installed in only the `vendor` path ... therefore - kerblooie.

Since kernel_load hits up `bundler/setup` and there's a ton of stuff in there, I don't know of a potential patch - bypassing all of that seems suspect. (cc @segiddins).

**Comment by chrismo** [comment]
changing that code to be `nil` makes this pass - but that code is ooooold ... so no idea how risky that is otherwise.

```ruby
      if settings[:disable_shared_gems]
        ENV["GEM_PATH"] = nil   # <= ...
```

**Comment by segiddins** [comment]
@chrismo a PR changing to to `nil` would be great :D

**Comment by chrismo** [comment]
I ran it locally, and got mixed results on specs, but then again I don't think I've run the whole suite locally recently, so I'll push up a PR in a bit.

**Comment by chrismo** [comment]
First shot tests passing, just pushed up a legit commit with a small method extract and a spec to match. We'll check on it mañana.

**Comment by miros** [comment]
@chrismo Can you please look into #4974. This fix might have changed `bundler install --deployment` behaviour.
