### ISSUE TITLE
Standalone configuration is not acknowledged by `binstub` command

### ISSUE THREAD

**Issue by cupakromer** [bundler/bundler#4594]
Bundler Version: 1.12.4

I noticed some oddities when trying to setup only select binstubs with a standalone configuration. Running `bundle install --binstubs --standalone` adds the following to the binstubs but for all gems:

```ruby
$:.unshift File.expand_path '../../bundle', __FILE__

require 'bundler/setup'
```

However, if the process is to first run `bundle install --standalone` then run `bundle binstub GEM` the produced binstub does not include the standalone path:

```ruby
require "pathname"
ENV["BUNDLE_GEMFILE"] ||= File.expand_path("../../Gemfile",
  Pathname.new(__FILE__).realpath)

require "rubygems"
require "bundler/setup"
```

In this reproduction the produced `.bundle/config` appears as:

```
---
BUNDLE_PATH: bundle
BUNDLE_DISABLE_SHARED_GEMS: true
```

**Comment by segiddins** [comment]
Yup, looking at the code it appears we never actually store whether or not a particular installation is `standalone` or not, and only use the `--standalone` flag. I guess the cleanest solution to this will be to add a standalone flag to `binstubs`?

**Comment by b-ggs** [comment]
Hey, @segiddins! Looking into working on this issue. Just confirming whether adding a `--standalone` flag to `binstubs` will be the final solution for this. Thanks!

**Comment by segiddins** [comment]
I guess? Especially since I believe `bundle install --binstubs` is going away in 2.0

**Comment by cupakromer** [comment]
👍 I'd be happy with needing to pass the specific `--standalone` flag to `bundle binstubs` as a solution. 😸
