### ISSUE TITLE
Bundle Install fails...

### ISSUE THREAD

**Issue by manpreetminhas** [bundler/bundler#4605]
I ran the command 
`/home/ec2-user/.rvm/gems/jruby-1.7.1@scv/bin/bundle install`
 
 I expected Bundler to install the gem dependencies but it gave me the following error

  Instead, what actually happened was...

Error details
    NameError: uninitialized constant OpenSSL::SSL::SSLSocket::SocketForwarder
      org/jruby/RubyModule.java:2677:in `const_missing'
      /home/ec2-user/.rvm/gems/jruby-1.7.1@global/gems/jruby-openssl-0.9.16-java/lib/jopenssl19/openssl/ssl-internal.rb:63:in `SSLSocket'
      /home/ec2-user/.rvm/gems/jruby-1.7.1@global/gems/jruby-openssl-0.9.16-java/lib/jopenssl19/openssl/ssl-internal.rb:61:in `SSL'
      /home/ec2-user/.rvm/gems/jruby-1.7.1@global/gems/jruby-openssl-0.9.16-java/lib/jopenssl19/openssl/ssl-internal.rb:21:in `OpenSSL'
      /home/ec2-user/.rvm/gems/jruby-1.7.1@global/gems/jruby-openssl-0.9.16-java/lib/jopenssl19/openssl/ssl-internal.rb:20:in `(root)'
      org/jruby/RubyKernel.java:1046:in `load'
      /home/ec2-user/.rvm/gems/jruby-1.7.1@global/gems/jruby-openssl-0.9.16-java/lib/openssl/ssl-internal.rb:1:in `(root)'
      org/jruby/RubyKernel.java:1027:in `require'
      /home/ec2-user/.rvm/rubies/jruby-1.7.1/lib/ruby/shared/rubygems/custom_require.rb:36:in `require'
      /home/ec2-user/.rvm/gems/jruby-1.7.1@global/gems/jruby-openssl-0.9.16-java/lib/openssl/ssl-internal.rb:4:in `(root)'
      org/jruby/RubyKernel.java:1027:in `require'
      /home/ec2-user/.rvm/rubies/jruby-1.7.1/lib/ruby/shared/rubygems/custom_require.rb:36:in `require'
      /home/ec2-user/.rvm/rubies/jruby-1.7.1/lib/ruby/1.9/openssl.rb:1:in `(root)'
      org/jruby/RubyKernel.java:1027:in `require'
      /home/ec2-user/.rvm/rubies/jruby-1.7.1/lib/ruby/shared/rubygems/custom_require.rb:36:in `require'
      /home/ec2-user/.rvm/rubies/jruby-1.7.1/lib/ruby/1.9/openssl.rb:28:in `(root)'
      /home/ec2-user/.rvm/gems/jruby-1.7.1@scv/gems/bundler-1.11.2/lib/bundler/vendored_persistent.rb:1:in `(root)'
      /home/ec2-user/.rvm/gems/jruby-1.7.1@scv/gems/bundler-1.11.2/lib/bundler/vendored_persistent.rb:4:in `(root)'
      org/jruby/RubyBasicObject.java:1659:in `__send__'
      /home/ec2-user/.rvm/gems/jruby-1.7.1@scv/gems/bundler-1.11.2/lib/bundler/fetcher.rb:1:in `(root)'
      /home/ec2-user/.rvm/gems/jruby-1.7.1@scv/gems/bundler-1.11.2/lib/bundler/fetcher.rb:1:in `(root)'
      /home/ec2-user/.rvm/gems/jruby-1.7.1@scv/gems/bundler-1.11.2/lib/bundler/cli/install.rb:1:in `(root)'
      /home/ec2-user/.rvm/gems/jruby-1.7.1@scv/gems/bundler-1.11.2/lib/bundler/cli/install.rb:96:in `run'
      /home/ec2-user/.rvm/gems/jruby-1.7.1@scv/gems/bundler-1.11.2/lib/bundler/cli.rb:172:in `install'
      /home/ec2-user/.rvm/gems/jruby-1.7.1@scv/gems/bundler-1.11.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /home/ec2-user/.rvm/gems/jruby-1.7.1@scv/gems/bundler-1.11.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /home/ec2-user/.rvm/gems/jruby-1.7.1@scv/gems/bundler-1.11.2/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      org/jruby/RubyKernel.java:1046:in `load'
      /home/ec2-user/.rvm/gems/jruby-1.7.1@scv/gems/bundler-1.11.2/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      org/jruby/RubyKernel.java:1066:in `eval'
      /home/ec2-user/.rvm/gems/jruby-1.7.1@scv/bin/ruby_executable_hooks:15:in `(root)'

Environment

    Bundler   1.11.2
    Rubygems  1.8.24
    Ruby      1.9.3p327 (2012-12-03 revision 37606) [java]
    GEM_HOME  /home/ec2-user/.rvm/gems/jruby-1.7.1@scv
    GEM_PATH  /home/ec2-user/.rvm/gems/jruby-1.7.1@scv:/home/ec2-user/.rvm/gems/jruby-1.7.1@global
    RVM       1.27.0 (latest)
    Git       2.7.4
    rubygems-bundler (1.4.4)

**Comment by segiddins** [comment]
Do you have SSL properly configured in your ruby install?

**Comment by LynnCo** [comment]
@manpreetminhas

> Do you have SSL properly configured in your ruby install?

**Comment by manpreetminhas** [comment]
Yes I did. The problem somehow was something else. The rails project that I was working on had a dependency on a certain version of Java (1.7.0.79). As soon as I downgraded the java version and did a bundle install again, it worked!!

**Comment by LynnCo** [comment]
@manpreetminhas thanks for following up!
