### ISSUE TITLE
Bundle spawns over 300 processes doing a simple `bundle install --deployment`

### ISSUE THREAD

**Issue by timjrobinson** [bundler/bundler#4609]
When doing `bundle install --deployment` on a simple Gemfile (listed below), it spawns over 300 `/usr/local/rvm/rubies/ruby-2.3.0/bin/ruby` processes. This triggers forkbomb protection on Cloud9 which causes the workspace to be killed. 

Gemfile:
```
source 'https://rubygems.org'
gem 'rails', '4.1.1'
```

Versions:
```
timjrobinson:~/workspace/ruby.rspec (master) $ uname -a
Linux timjrobinson-rubybomb-9716 4.5.4-c9 #1 SMP Tue May 17 06:42:16 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
timjrobinson:~/workspace/ruby.rspec (master) $ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.3 LTS
Release:        14.04
Codename:       trusty
timjrobinson:~/workspace/ruby.rspec (master) $ bundle -v
Bundler version 1.12.4
timjrobinson:~/workspace/ruby.rspec (master) $ ruby -v
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]
timjrobinson:~/workspace/ruby.rspec (master) $ gem -v
2.5.1
```

Console output:
```
timjrobinson:~/workspace/ruby.rspec (master) $ bundle install --no-deployment
Using rake 11.1.2
Using i18n 0.7.0
Using json 1.8.3
Using minitest 5.8.4
Using thread_safe 0.3.5
Using builder 3.2.2
Using erubis 2.7.0
Using rack 1.5.5
Using mime-types 1.25.1
Using polyglot 0.3.5
Using arel 5.0.1.20140414130214
Using hike 1.2.3
Using multi_json 1.11.2
Using bundler 1.12.4
Using thor 0.19.1
Using tilt 1.4.1
Using tzinfo 1.2.2
Using rack-test 0.6.3
Using treetop 1.4.15
Using sprockets 2.12.4
Using activesupport 4.1.1
Using mail 2.5.4
Using actionview 4.1.1
Using activemodel 4.1.1
Using actionpack 4.1.1
Using activerecord 4.1.1
Using actionmailer 4.1.1
Using railties 4.1.1
Using sprockets-rails 2.3.3
Using rails 4.1.1
Bundle complete! 1 Gemfile dependency, 30 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
```

This is running on a test workspace with forkbomb protection disabled, normally this process is killed half way through. All workspaces on Cloud9 run on docker containers running Ubuntu 14.04. 

Is this a bug?
If not why does bundle need to spawn 300 processes to do a simple install? Surely there's a better way.

**Comment by segiddins** [comment]
Can you try and see where in bundler those processes are being spawned? That would really help in figuring out how to fix the issue 😄

**Comment by timjrobinson** [comment]
I'm not a ruby guy unfortunately. I just work at Cloud9 and we've had a number of users report that their workspaces are dying when they run `bundle install` because of this forkbomb protection.

**Comment by colby-swandale** [comment]
HI, i believe this is a duplicate report of #4367. A PR has also been made to address the issue at #4607

**Comment by colby-swandale** [comment]
Can you please test the latest release `1.12.5` to see if your problem has been fixed..

**Comment by munderseth** [comment]
Hi Colby,

I believe this issue has been resolved. I can not reproduce the issue mentioned above using the `1.12.5` version. 

BTW I believe C9 is now defaulting to this version of the bundler for `Rails` Workspaces.

Thanks.
