### ISSUE TITLE
bundle package --all » requiring password 1.12.4

### ISSUE THREAD

**Issue by jufemaiz** [bundler/bundler#4612]
Hi guys,
bumped our bundler version to 1.12.4 and our builds are failing with the following:

```bash
Your user account isn't allowed to install to the system Rubygems.
  You can cancel this installation and run:

      bundle install --path vendor/bundle

  to install the gems into ./vendor/bundle/, or you can enter your password
  and install the bundled gems to Rubygems using sudo.
```

Was there a major change that occurred?

Previously we undertook the following approach:

```bash
bundle package --all
bundle install --local
```

My colleague @sjauld believes it is due to a change that requires gems to be installed, and if the user issuing the command, then password is prompted (which, given ours is a remote machine, is not available).

Given that [bundle package](http://bundler.io/v1.12/bundle_package.html) has no indication that it will attempt to perform any installations of gems to the system (and setting the flag --no-install does not change anything either) we are perplexed as to why bundle package would be attempting to install gems anywhere but ./vendor/cache as per the specification.

**Comment by b-ggs** [comment]
@jufemaiz Can't seem to reproduce this on my machine on 1.12.5

```
╭─boggs@archbook ~/dev/4612-test ‹ruby-2.3.0› ‹node-v4.4.1›
╰─➤  dbundle --version                                                                                                              1 ↵
Bundler version 1.12.5
╭─boggs@archbook ~/dev/4612-test ‹ruby-2.3.0› ‹node-v4.4.1›
╰─➤  cat Gemfile
source 'https://rubygems.org'

gem 'rack', '1.6.3'
╭─boggs@archbook ~/dev/4612-test ‹ruby-2.3.0› ‹node-v4.4.1›
╰─➤  dbundle package --all
Fetching gem metadata from https://rubygems.org/
Fetching version metadata from https://rubygems.org/
Resolving dependencies...
Installing rack 1.6.3
Using bundler 1.12.5
Bundle complete! 1 Gemfile dependency, 2 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
Updating files in vendor/cache
  * rack-1.6.3.gem
╭─boggs@archbook ~/dev/4612-test ‹ruby-2.3.0› ‹node-v4.4.1›
╰─➤  bundle install --local
Using rack 1.6.3
Using bundler 1.12.5
Updating files in vendor/cache
Bundle complete! 1 Gemfile dependency, 2 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
╭─boggs@archbook ~/dev/4612-test ‹ruby-2.3.0› ‹node-v4.4.1›
╰─➤  dbundle exec rackup --version                                                                                                  1 ↵
Rack 1.3 (Release: 1.6.3)
```

Could you confirm if this is still an issue with 1.12.5, or maybe perhaps give more details as to how to reproduce this issue?

**Comment by LynnCo** [comment]
ping @jufemaiz

> Could you confirm if this is still an issue with 1.12.5, or maybe perhaps give more details as to how to reproduce this issue?

**Comment by jufemaiz** [comment]
I will but currently traveling. Will try before flight tonight

On Thursday, 9 June 2016, Lynn Cyrin <notifications@github.com> wrote:

> ping @jufemaiz <https://github.com/jufemaiz>
>
> Could you confirm if this is still an issue with 1.12.5, or maybe perhaps
> give more details as to how to reproduce this issue?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/bundler/bundler/issues/4612#issuecomment-224832556>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AABAYXvGkSZu-6x6S1hQWf-Tc2vRrBfDks5qJ8_dgaJpZM4ImPg1>
> .
>


-- 
–
Joel Courtney
 m: +61 401 501 625
 e: euphemize@gmail.com
 w: http://euphemize.net
 p: http://flic.kr/jufemaiz/
 t: http://twitter.com/jufemaiz

**Comment by RochesterinNYC** [comment]
@jufemaiz Any update on this?

**Comment by b-ggs** [comment]
Closing due to lack of response from reporter.
