### ISSUE TITLE
bundle inatall - error

### ISSUE THREAD

**Issue by cmsunil** [bundler/bundler#4614]
No such file or directory - git clone "git://github.com/rweng/jquery-datatables-rails.git" "D:/Working Folder/vendor/chache/ruby/2.0.0/cache/bundler/git/jquery-datatables-rails-b8d699e208e47fe51869a7aebe3d593ff0672f4a" --bare --no-hardlinks --quiet

**Comment by segiddins** [comment]
Please share the output of `bundle env` and make it a bit more clear what exactly is the issue you're facing? Thanks!

**Comment by cmsunil** [comment]
bundle env

         celluloid (>= 0.15.2)
          rb-fsevent (>= 0.9.3)
          rb-inotify (>= 0.9)
        lumberjack (1.0.9)
        mail (2.5.4)
          mime-types (~> 1.16)
          treetop (~> 1.4.8)
        meta_request (0.3.4)
          callsite (~> 0.0, >= 0.0.11)
          rack-contrib (~> 1.1)
          railties (>= 3.0.0, < 5.0.0)
        metaclass (0.0.4)
        method_source (0.8.2)
        mime-types (1.25.1)
        mini_magick (3.7.0)
          subexec (~> 0.2.1)
        minitest (4.7.5)
        mocha (0.12.7)
          metaclass (~> 0.0.1)
        money (5.1.1)
          i18n (~> 0.6.0)
        money-rails (0.8.1)
          activesupport (>= 3.0)
          money (~> 5.1.0)
          railties (>= 3.0)
        mono_logger (1.1.0)
        multi_json (1.11.1)
        multi_xml (0.5.5)
        mysql2 (0.3.16)
        nenv (0.2.0)
        nested_form (0.3.2)
        net-http-digest_auth (1.4)
        net-http-persistent (2.9.4)
        net-scp (1.2.1)
          net-ssh (>= 2.6.5)
        net-ssh (2.9.1)
        netrc (0.7.9)
        newrelic_rpm (3.9.6.257)
        nokogiri (1.5.11)
        notiffany (0.0.6)
          nenv (~> 0.1)
          shellany (~> 0.0)
        paper_trail (3.0.6)
          activerecord (>= 3.0, < 5.0)
          activesupport (>= 3.0, < 5.0)
        pg (0.17.0)
        polyamorous (0.6.4)
          activerecord (>= 3.0)
        polyglot (0.3.5)
        pry (0.10.1)
          coderay (~> 1.1.0)
          method_source (~> 0.8.1)
          slop (~> 3.4)
        pry-byebug (2.0.0)
          byebug (~> 3.4)
          pry (~> 0.10)
        rack (1.5.2)
        rack-contrib (1.1.0)
          rack (>= 0.9.1)
        rack-protection (1.5.3)
          rack
        rack-test (0.6.2)
          rack (>= 1.0)
        rack_session_access (0.1.1)
          builder (>= 2.0.0)
          rack (>= 1.0.0)
        railroady (1.2.0)
        rails (4.0.7)
          actionmailer (= 4.0.7)
          actionpack (= 4.0.7)
          activerecord (= 4.0.7)
          activesupport (= 4.0.7)
          bundler (>= 1.3.0, < 2.0)
          railties (= 4.0.7)
          sprockets-rails (~> 2.0)
        railties (4.0.7)
          actionpack (= 4.0.7)
          activesupport (= 4.0.7)
          rake (>= 0.8.7)
          thor (>= 0.18.1, < 2.0)
        raindrops (0.13.0)
        rake (10.3.2)
        ransack (1.1.0)
          actionpack (>= 3.0)
          activerecord (>= 3.0)
          polyamorous (~> 0.6.0)
        rb-fsevent (0.9.4)
        rb-inotify (0.9.5)
          ffi (>= 0.5.0)
        redis (3.1.0)
        redis-namespace (1.5.1)
          redis (~> 3.0, >= 3.0.4)
        redis-objects (1.0.1)
          redis (>= 3.0.2)
        ref (1.0.5)
        request_store (1.1.0)
        resque (1.25.1)
          mono_logger (~> 1.0)
          multi_json (~> 1.0)
          redis-namespace (~> 1.2)
          sinatra (>= 0.9.2)
          vegas (~> 0.1.2)
        resque-scheduler (2.3.1)
          redis (>= 3.0.0)
          resque (~> 1.25)
          rufus-scheduler (~> 2.0)
        rest (2.7.2)
          net-http-persistent (>= 2.9.1)
          rest_client (>= 1.7.1)
        rest_client (1.7.3)
          netrc (~> 0.7.7)
        rets (0.9.0)
          http-cookie (~> 1.0.0)
          httpclient (~> 2.6.0)
          nokogiri (~> 1.5)
        ri_cal (0.8.8)
        rr (1.1.2)
        rspec (3.1.0)
          rspec-core (~> 3.1.0)
          rspec-expectations (~> 3.1.0)
          rspec-mocks (~> 3.1.0)
        rspec-core (3.1.7)
          rspec-support (~> 3.1.0)
        rspec-expectations (3.1.2)
          diff-lcs (>= 1.2.0, < 2.0)
          rspec-support (~> 3.1.0)
        rspec-its (1.0.1)
          rspec-core (>= 2.99.0.beta1)
          rspec-expectations (>= 2.99.0.beta1)
        rspec-legacy_formatters (1.0.0)
          rspec-core (>= 3.0.0.beta2)
          rspec-support (>= 3.0.0.beta2)
        rspec-mocks (3.1.3)
          rspec-support (~> 3.1.0)
        rspec-rails (3.1.0)
          actionpack (>= 3.0)
          activesupport (>= 3.0)
          railties (>= 3.0)
          rspec-core (~> 3.1.0)
          rspec-expectations (~> 3.1.0)
          rspec-mocks (~> 3.1.0)
          rspec-support (~> 3.1.0)
        rspec-support (3.1.2)
        ruby-hmac (0.4.0)
        rubyzip (1.1.0)
        rufus-scheduler (2.0.24)
          tzinfo (>= 0.3.22)
        sass (3.2.19)
        sass-rails (4.0.3)
          railties (>= 4.0.0, < 5.0)
          sass (~> 3.2.0)
          sprockets (~> 2.8, <= 2.11.0)
          sprockets-rails (~> 2.0)
        selenium-webdriver (2.45.0)
          childprocess (~> 0.5)
          multi_json (~> 1.0)
          rubyzip (~> 1.0)
          websocket (~> 1.0)
        shellany (0.0.1)
        shoulda-matchers (2.7.0)
          activesupport (>= 3.0.0)
        simple-navigation (3.11.0)
          activesupport (>= 2.3.2)
        simple_form (3.0.2)
          actionpack (~> 4.0)
          activemodel (~> 4.0)
        simplecov (0.10.0)
          docile (~> 1.1.0)
          json (~> 1.8)
          simplecov-html (~> 0.10.0)
        simplecov-html (0.10.0)
        sinatra (1.4.5)
          rack (~> 1.4)
          rack-protection (~> 1.4)
          tilt (~> 1.3, >= 1.3.4)
        slop (3.6.0)
        spring (1.3.6)
        spring-commands-rspec (1.0.4)
          spring (>= 0.9.1)
        sprockets (2.11.0)
          hike (~> 1.2)
          multi_json (~> 1.0)
          rack (~> 1.0)
          tilt (~> 1.1, != 1.3.0)
        sprockets-rails (2.0.1)
          actionpack (>= 3.0)
          activesupport (>= 3.0)
          sprockets (~> 2.8)
        state_machine (1.2.0)
        subexec (0.2.3)
        therubyracer (0.12.0)
          libv8 (~> 3.16.14.0)
          ref
        thor (0.19.1)
        thread_safe (0.3.4)
        tilt (1.4.1)
        timers (4.0.1)
          hitimes
        treetop (1.4.15)
          polyglot
          polyglot (>= 0.3.1)
        tzinfo (0.3.42)
        uglifier (2.0.0)
          execjs (>= 0.3.0)
          multi_json (~> 1.0, >= 1.0.2)
        unf (0.1.3)
          unf_ext
        unf_ext (0.0.6)
        unicorn (4.8.3)
          kgio (~> 2.6)
          rack
          raindrops (~> 0.7)
        vegas (0.1.11)
          rack (>= 1.0.0)
        webrobots (0.1.1)
        websocket (1.2.2)
        xpath (2.0.0)
          nokogiri (~> 1.3)

    PLATFORMS
      ruby

    DEPENDENCIES
      active_interaction (= 1.2.3)
      annotate (>= 2.5.0)
      awesome_print (= 1.2.0)
      bcrypt-ruby (~> 3.1.2)
      better_errors
      binding_of_caller
      bootstrap-sass (~> 3.2.0)
      byebug
      capybara-email
      capybara-screenshot
      capybara-webkit (~> 1.0.0)
      carrierwave (= 0.9.0)
      coffee-rails (~> 4.0.1)
      daemons (= 1.1.9)
      database_cleaner (~> 1.0.0)
      delayed_job_active_record (= 4.0.0)
      draper (= 1.4)
      dropbox-sdk
      escape_utils (= 1.0.0)
      factory_girl_rails
      fog (= 1.18.0)
      guard
      guard-rspec
      haml-rails (= 0.5.1)
      has_scope (= 0.5.1)
      honeybadger (= 1.11.1)
      httparty
      iron_worker_ng
      jquery-datatables-rails!
      jquery-fileupload-rails
      jquery-rails (= 3.0.4)
      jquery-ui-rails (= 4.1.0)
      kaminari (= 0.15.1)
      launchy
      letter_opener
      mechanize!
      meta_request
      mini_magick (= 3.7.0)
      mocha (= 0.12.7)
      money-rails (= 0.8.1)
      mysql2
      nested_form (= 0.3.2)
      newrelic_rpm
      paper_trail (>= 3.0.0.rc2)
      pg (= 0.17.0)
      pry
      pry-byebug
      rack_session_access
      railroady
      rails (= 4.0.7)
      ransack (= 1.1.0)
      redis-objects
      resque (= 1.25.1)
      resque-scheduler (= 2.3.1)
      rets (= 0.9.0)
      ri_cal (= 0.8.8)
      rr
      rspec-its
      rspec-legacy_formatters
      rspec-rails
      ruby-rets!
      rubyzip (= 1.1.0)
      sass-rails (~> 4.0.1)
      selenium-webdriver (= 2.45)
      shoulda-matchers
      simple-navigation (= 3.11.0)
      simple_form (~> 3.0.1)
      simplecov
      spring-commands-rspec
      sprockets-rails (~> 2.0.0)
      state_machine (= 1.2.0)
      therubyracer (= 0.12.0)
      uglifier (= 2.0.0)
      unf (= 0.1.3)
      unicorn

**Comment by b-ggs** [comment]
@cmsunil Could you perhaps give us steps to reproduce this issue? Thanks!

**Comment by LynnCo** [comment]
ping @cmsunil

> Could you perhaps give us steps to reproduce this issue? Thanks!

**Comment by cmsunil** [comment]
This happend when i was using a old project.

I did the bundle Install

Regards,

Sunil

**Comment by segiddins** [comment]
Unfortunately, that's not enough information for us to reproduce -- if you're still experiencing the issue, please share step-by-step commands we can copy/paste (or a script) that reproduces the problem. Thank!
