### ISSUE TITLE
Possibly Print out the exception for Bundler::GemRequireError

### ISSUE THREAD

**Issue by spazworm** [bundler/bundler#4615]
Hi guys,

Just a quick suggestion that maybe the line
[(https://github.com/bundler/bundler/blob/495dc7e0631cfb5cdac685250fcb41c090dfa610/lib/bundler/runtime.rb#L90)]
could include the exception in the message? I was debugging a problem with one of our in house gem yesterday, I added the exception to the message and it really was really helpful for me. Not sure if it would be the case for everyone but thought I would suggest it just in case.

**Comment by segiddins** [comment]
Is should be printed out as of https://github.com/bundler/bundler/pull/3967

**Comment by spazworm** [comment]
Oh yes, quite right, I thought we were using the latest version but it seems we weren't :sweat_smile:, sorry for the inconvenience.
