### ISSUE TITLE
Error comand bundle install

### ISSUE THREAD

**Issue by engBrunoSales** [bundler/bundler#4616]
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `/home/brunosales/.rvm/gems/ruby-2.3.0/bin/bundle install`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what actually happened was...

Error details

    Errno::EACCES: Permission denied @ dir_s_mkdir - /home/brunosales/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/versions20160525-4598-ntz0m6
      /home/brunosales/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tmpdir.rb:86:in `mkdir'
      /home/brunosales/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tmpdir.rb:86:in `block in mktmpdir'
      /home/brunosales/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tmpdir.rb:130:in `create'
      /home/brunosales/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tmpdir.rb:86:in `mktmpdir'
      /home/brunosales/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:29:in `update'
      /home/brunosales/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:64:in `update'
      /home/brunosales/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:55:in `update_and_parse_checksums!'
      /home/brunosales/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/fetcher/compact_index.rb:65:in `available?'
      /home/brunosales/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/fetcher/compact_index.rb:15:in `call'
      /home/brunosales/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/fetcher/compact_index.rb:15:in `block in compact_index_request'
      /home/brunosales/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/fetcher.rb:154:in `use_api'
      /home/brunosales/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:331:in `block in api_fetchers'
      /home/brunosales/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:331:in `select'
      /home/brunosales/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:331:in `api_fetchers'
      /home/brunosales/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:336:in `block in remote_specs'
      /home/brunosales/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/index.rb:10:in `build'
      /home/brunosales/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:335:in `remote_specs'
      /home/brunosales/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:82:in `specs'
      /home/brunosales/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/lazy_specification.rb:56:in `__materialize__'
      /home/brunosales/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/spec_set.rb:91:in `block in materialize'
      /home/brunosales/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/spec_set.rb:88:in `map!'
      /home/brunosales/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/spec_set.rb:88:in `materialize'
      /home/brunosales/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/definition.rb:140:in `specs'
      /home/brunosales/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/definition.rb:129:in `resolve_remotely!'
      /home/brunosales/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/installer.rb:195:in `resolve_if_need'
      /home/brunosales/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/installer.rb:70:in `run'
      /home/brunosales/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/installer.rb:22:in `install'
      /home/brunosales/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/cli/install.rb:102:in `run'
      /home/brunosales/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/cli.rb:175:in `install'
      /home/brunosales/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /home/brunosales/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /home/brunosales/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /home/brunosales/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /home/brunosales/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/cli.rb:11:in `start'
      /home/brunosales/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/exe/bundle:27:in `block in <top (required)>'
      /home/brunosales/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
      /home/brunosales/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/exe/bundle:19:in `<top (required)>'
      /home/brunosales/.rvm/gems/ruby-2.3.0/bin/bundle:23:in `load'
      /home/brunosales/.rvm/gems/ruby-2.3.0/bin/bundle:23:in `<main>'
      /home/brunosales/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
      /home/brunosales/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'

Environment
      
  Bundler   1.12.5
  Rubygems  2.5.1
  Ruby      2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]
  GEM_HOME  /home/brunosales/.rvm/gems/ruby-2.3.0
  GEM_PATH  /home/brunosales/.rvm/gems/ruby-2.3.0:/home/brunosales/.rvm/gems/ruby-2.3.0@global
  RVM       1.27.0 (latest)
  Git       1.9.1
  rubygems-bundler (1.4.4)
      
      Bundler settings
      
  orig_path
    Set via BUNDLE_ORIG_PATH: "/home/brunosales/.rvm/gems/ruby-2.3.0/bin:/home/brunosales/.rvm/gems/ruby-2.3.0@global/bin:/home/brunosales/.rvm/rubies/ruby-2.3.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/brunosales/.rvm/bin:/home/brunosales/.rvm/bin:/home/brunosales/.rvm/bin"
  orig_gem_path
    Set via BUNDLE_ORIG_GEM_PATH: "/home/brunosales/.rvm/gems/ruby-2.3.0:/home/brunosales/.rvm/gems/ruby-2.3.0@global"
--- TEMPLATE END ----------------------------------------------------------------

**Comment by hmistry** [comment]
Check out how the other issues with permission errors were resolved, like #4590, #4458, #4431, #4429. Let us know if any of those worked for you.

**Comment by engBrunoSales** [comment]
thats ok

2016-06-19 18:45 GMT-03:00 hmistry <notifications@github.com>:

> Check out how the other issues with permission errors were resolved, like
> #4590 <https://github.com/bundler/bundler/issues/4590>, #4458
> <https://github.com/bundler/bundler/issues/4458>, #4431
> <https://github.com/bundler/bundler/issues/4431>, #4429
> <https://github.com/bundler/bundler/issues/4429>. Let us know if any of
> those worked for you.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/bundler/bundler/issues/4616#issuecomment-227022186>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABrubSSa0K03PRwgY9scRtbAbkKF3Epmks5qNbh9gaJpZM4InH-J>
> .
>



-- 
Atenciosamente,
Bruno Sales
Graduado em Engenharia da Computação

Desenvolvedor I

Telefone: (85) 3034-8989
Celular: (85) 98915-7718
E-mail: bruno.sales@dyad.com.br
Skype: brunosales.dyad
