### ISSUE TITLE
[rfc] Remove separate "frozen" and "deployment"

### ISSUE THREAD

**Issue by indirect** [bundler/bundler#4619]
In Bundler 1.x, the `--deployment` flag is an alias for `--frozen --path vendor/bundle`. Now that we don't save flags, we should provide a documented config option for frozen/deployment mode, and remove the confusing combination flag.

Since 2.x defaults to `--path .bundle`, I propose that we remove the `--path vendor/bundle` part from `--deployment`, and remove `frozen` completely, replacing it everywhere with `deployment`, eg `bundle config deployment true` if you want future commands to throw an error rather than update the Gemfile.

Thoughts?

**Comment by segiddins** [comment]
Sounds reasonable

**Comment by RochesterinNYC** [comment]
Agreed. I haven't yet seen any use cases for `--frozen` that lack the context of deployment.
