### ISSUE TITLE
Versions stored in Gemfile.lock generate different platform output

### ISSUE THREAD

**Issue by schneems** [bundler/bundler#4621]
Previously if you were declaring Ruby in your Gemfile:

```
ruby "2.3.0"
```

When you run `$ bundle platform --ruby` you will get this output with no patchlevel

```ruby
$ bundle _1.11.2_  platform --ruby
ruby 2.3.0
```

Now with 1.12.5 if you've done a `bundle install` that results in your Ruby version being written to the lockfile you'll get:

```
$ bundle _1.12.5_  platform --ruby
ruby 2.3.0p0
```

This is because we are storing the patch version in the Gemfile.lock

```
RUBY VERSION
   ruby 2.3.0p0
```

I've been trying to add support for the Ruby version specifiers to Heroku, but running into problems with our test suite. I finally got it working but this bug is a pretty big breaking change for us. Had to revert the change: https://github.com/heroku/heroku-buildpack-ruby/commit/088683acf9f6edde85179061480ec1850956cc2f

I'm suggesting that we strip the patchlevel from the Gemfile.lock unless it's present in the `ruby` directive. However now that it's out there in the wild, that won't work for everyone who's already got this in their Gemfile.lock, so we'll need to also do some magic in `bundle platform` when reading in older lockfiles with the patchlevel specified.

**Comment by indirect** [comment]
@schneems Heroku actively supports patchlevel requirements via `ruby '1.9.3', :patchlevel => "222"`. What output do you expect in that case?

**Comment by schneems** [comment]
In that case we would expect

```
ruby 1.9.3p0
```

For our cases it's fine to store and echo out the patchlevel if that's what they actually want, but if they haven't specified a patchlevel and bundler is telling us that they need it, then it's breaks.

**Comment by indirect** [comment]
So you're saying that Heroku expects `ruby 1.9.3p222`, but breaks completely on `ruby 2.3.0p0`? Can you elaborate on why one is required and one is required to not be there? Ruby 2.3.0 is in fact p0.

**Comment by indirect** [comment]
Based on the output from `ruby -v` (which always includes patchlevel), it seems like the previous behavior of `ruby 2.3.0` (without a patchlevel) is a bug in our output. Am I understanding correctly that including the patchlevel when we fixed that bug breaks backwards compatibility with Heroku?

**Comment by indirect** [comment]
I've just done some more testing myself, and I am finding it very hard to consider this a bug in Bundler. This is what the Heroku docs site says:

> Heroku supports the following Ruby versions and the associated Rubygems:
> […]
> `2.3.1`: patchlevel 112, Rubygems : `2.5.1`

Based on what you just said above about patch levels being supported, I created a Gemfile based on the documentation:

```ruby
# Gemfile
# frozen_string_literal: true
source "https://rubygems.org"
ruby "2.3.1", :patchlevel => "112"
gem "rack"
```

Then I tried to push the app to Heroku:

```
$  git push heroku master
Counting objects: 7, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (7/7), done.
Writing objects: 100% (7/7), 818 bytes | 0 bytes/s, done.
Total 7 (delta 0), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Ruby app detected
remote: -----> Compiling Ruby/Rack
remote:  !
remote:  !     An error occurred while installing Ruby ruby-2.3.1-p112
remote:  !     For supported Ruby versions see https://devcenter.heroku.com/articles/ruby-support#supported-runtimes
remote:  !     Note: Only the most recent version of Ruby 2.1 is supported on Cedar-14
remote:  !     Command: 'set -o pipefail; curl -L --fail --retry 3 --retry-delay 1 --connect-timeout 3 --max-time 30 https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/cedar-14/ruby-2.3.1-p112.tgz -s -o - | tar zxf - ' failed unexpectedly:
remote:  !     
remote:  !     gzip: stdin: unexpected end of file
remote:  !     tar: Child returned status 1
remote:  !     tar: Error is not recoverable: exiting now
remote:  !
remote: 
remote:  !     Push rejected, failed to compile Ruby app
remote: 
remote: Verifying deploy...
remote: 
remote: !	Push rejected to peaceful-badlands-99637.
remote: 
To https://git.heroku.com/peaceful-badlands-99637.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/peaceful-badlands-99637.git'
```

Can you please clarify how this is a bug in Bundler? The `:patchlevel` option was implemented by Heroku employees, and (as far as I know) it is used literally nowhere else, and as far as I can tell the example above uses it exactly the way Bundler and Heroku docs indicate that it should/can be used.

**Comment by schneems** [comment]
Heroku uses the exact output that bundler gives it. We take the version specifier and build a URL to a binary. We count on the __exact__ output:

![](https://www.dropbox.com/s/7l403p5bdmyt9h4/Screenshot%202016-05-26%2016.33.59.png?dl=1)

That behavior is intentional. @hone wrote the `bundle platform --ruby` code side by side with the Heroku parsing code.

**Comment by indirect** [comment]
My exception, from above, is using Bundler 1.11 and Heroku in the way that the docs say is "correct". But it also has the same problem. So I feel like maybe Heroku needs a better way to find and download Ruby binaries?

**Comment by schneems** [comment]
Those docs are stating the patchlevel of that version. After Ruby 2+ there is only one "patchlevel" per minor version. So it's really on there for legacy reasons

For ruby 2.3.0 you use

```
ruby '2.3.0'
```

We've never encouraged specifying patchlevel, but it works for 1.9 versions.

**Comment by indirect** [comment]
After some internal discussion, the Bundler team considers including the patch level with the version number to be a fixed bug—we included the patch level for Ruby 1.8 through 2.0, and Ruby has always included patch levels in the output from `ruby -v`.

I recommend that you add something like this to the Heroku buildpack, which will not only fix this issue, but also fix the existing bug I noted above: `\`bundle platform --ruby\`.tap{|v| v >= '2.2' ? v.gsub(/p\d+$/, '') : v }`

**Comment by schneems** [comment]
Thanks, i'll work something out. We're already parsing the individual sections. In the future it would maybe be nice to not have to shell out to `bundle platform` as we already have the bundler code `require`-d in memory and we could get a little speed.

We should add a retroactive chaneglog entry in bundler for this behavior unless the change is already documented somewhere.

**Comment by segiddins** [comment]
@schneems no need to shell out, `(Bundler.locked_gems && Bundler.locked_gems.ruby_version) || (Bundler.definition.ruby_version && Bundler.definition.ruby_version.single_version_string)` is literally all `bundle platform` is doing

**Comment by schneems** [comment]
We need that to be wrapped up in an API that is reasonably stable. If we were copy/past-ing logic before it would have broken as this version logic is different from before because previously we weren't looking in the lockfile.

Is this interface reasonably stable?

```ruby
require "bundler/cli/platform"
Bundler::CLI::Platform.new(options).run
```

**Comment by schneems** [comment]
Actually strike that, I remember why we did it that way. We're isolating the user's environment from our own build environment.
