### ISSUE TITLE
Source pinning seems to be ignored during updates

### ISSUE THREAD

**Issue by indirect** [bundler/bundler#4631]
Given a Gemfile where a gem is pinned to a secondary source:

```ruby
source "https://rubygems.org"
source "private" do
  gem "pony"
end
```

It appears that running `bundle update --source pony` (and possibly even just `bundle update`) will install the pony gem from RubyGems if the version available from RubyGems is higher than the version available from the private server.

**Comment by segiddins** [comment]
While you're at it, could you whip up a test for the benefit of future andre?

**Comment by b-ggs** [comment]
This spec seems to pass on the current Bundler `master` branch.

```
  it "will update only from pinned source" do
    install_gemfile <<-G
      source "file://#{gem_repo2}"

      source "file://#{gem_repo1}" do
        gem "thin"
      end
    G

    update_repo2 do
      build_gem "thin", "2.0"
    end

    bundle "update"
    should_be_installed "thin 1.0"
  end
```

**Comment by indirect** [comment]
hooray! @b-ggs, can you open a PR that adds that spec, so we can guarantee this won't break again?

**Comment by b-ggs** [comment]
@indirect Will do! :+1:
