### ISSUE TITLE
 Unfortunately, an unexpected error occurred, and Bundler cannot continue.

### ISSUE THREAD

**Issue by chuganghong** [bundler/bundler#4634]
I ran the command `/usr/local/bin/bundle install --deployment --without development test postgres aws`.
I expected Bundler to install success.
Instead, an error happened.The error message is:

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

Error details

    Errno::ENOENT: No such file or directory - git
      /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.12.5/lib/bundler/source/git/git_proxy.rb:149:in ``'
      /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.12.5/lib/bundler/source/git/git_proxy.rb:149:in `block in git'
      /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.12.5/lib/bundler/shared_helpers.rb:72:in `call'
      /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.12.5/lib/bundler/shared_helpers.rb:72:in `with_clean_git_env'
      /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.12.5/lib/bundler/source/git/git_proxy.rb:149:in `git'
      /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.12.5/lib/bundler/source/git/git_proxy.rb:156:in `block in has_revision_cached?'
      /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.12.5/lib/bundler/shared_helpers.rb:54:in `chdir'
      /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.12.5/lib/bundler/shared_helpers.rb:54:in `block in chdir'
      /usr/local/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
      /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.12.5/lib/bundler/shared_helpers.rb:53:in `chdir'
      /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.12.5/lib/bundler/source/git/git_proxy.rb:204:in `in_path'
      /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.12.5/lib/bundler/source/git/git_proxy.rb:156:in `has_revision_cached?'
      /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.12.5/lib/bundler/source/git/git_proxy.rb:88:in `checkout'
      /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.12.5/lib/bundler/source/git.rb:154:in `specs'
      /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.12.5/lib/bundler/lazy_specification.rb:56:in `__materialize__'
      /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.12.5/lib/bundler/spec_set.rb:91:in `block in materialize'
      /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.12.5/lib/bundler/spec_set.rb:88:in `map!'
      /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.12.5/lib/bundler/spec_set.rb:88:in `materialize'
      /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.12.5/lib/bundler/definition.rb:140:in `specs'
      /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.12.5/lib/bundler/definition.rb:129:in `resolve_remotely!'
      /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.12.5/lib/bundler/installer.rb:195:in `resolve_if_need'
      /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.12.5/lib/bundler/installer.rb:70:in `run'
      /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.12.5/lib/bundler/installer.rb:22:in `install'
      /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.12.5/lib/bundler/cli/install.rb:102:in `run'
      /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.12.5/lib/bundler/cli.rb:175:in `install'
      /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.12.5/lib/bundler/cli.rb:11:in `start'
      /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.12.5/exe/bundle:27:in `block in <top (required)>'
      /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.12.5/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
      /usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.12.5/exe/bundle:19:in `<top (required)>'
      /usr/local/bin/bundle:23:in `load'
      /usr/local/bin/bundle:23:in `<main>'

Environment
      
  Bundler   1.12.5
  Rubygems  2.0.14
  Ruby      2.0.0p353 (2013-11-22 revision 43784) [i686-linux]
  GEM_HOME  /home/git/gitlab/vendor/bundle/ruby/2.0.0
  GEM_PATH  
  Git       not installed
      
      Bundler settings
      
  frozen
    Set for your local app (/home/git/gitlab/.bundle/config): "1"
  path
    Set for your local app (/home/git/gitlab/.bundle/config): "vendor/bundle"
  without
    Set for your local app (/home/git/gitlab/.bundle/config): "development:test:postgres:aws:puma"
  disable_shared_gems
    Set for your local app (/home/git/gitlab/.bundle/config): true
  orig_path
    Set via BUNDLE_ORIG_PATH: "/usr/bin:/bin"

**Comment by colby-swandale** [comment]
Can you please share the output of `bundle env` and is git installed + available to the user?

**Comment by RochesterinNYC** [comment]
@chuganghong any update on this?

**Comment by segiddins** [comment]
Closing due to lack of a response.
