### ISSUE TITLE
--build option for `bundle package`

### ISSUE THREAD

**Issue by chrismwendt** [bundler/bundler#4635]
This is a **feature request** to add a `--build` option to `bundle package` which instructs bundler to build any gems that come from `:git` references in the `Gemfile`.

The motivation for `--build` is to make the format for all gems under `vendor/cache/` consistent - that is, convert them all to binary `.gem` files, rather than leaving some as directories containing the full source code for the respective gem.

If there already is a way to do this, I'd love to hear about it!

- `bundle package` documentation: http://bundler.io/bundle_package.html

**Comment by fran-worley** [comment]
+1 for this, would make deploy git gems to AWS Elastic Beanstalk so much easier!

**Comment by b-ggs** [comment]
I'll be working on this! :+1:

**Comment by indirect** [comment]
I'm not completely sure this makes sense—gems created by checking out a git repo and then running `git build` could have any version. They might have the same version as the last released version of the gem, they might have the version of an unreleased version of the gem, it could be anything. As soon as you create a .gem file, you lose the sha that the git gem was created from.

Beyond that, though, if you have a Gemfile with a git gem in it, building a .gem into `vendor/cache` doesn't help you. Bundler is not able to install a .gem file if the Gemfile lists a gem from a git repo. They're different things. Can you explain more about why you want this feature, given that it creates .gems that Bundler won't (and can't) use?

**Comment by fran-worley** [comment]
@indirect I was looking at this as a way to improve the speed of initialization of EC2 instances when using the new AWS elastic beanstalk container. This would have been ideal but, if as you say Bundler can't use packaged git gems then it's not going to resolve the issue.

**Comment by chrismwendt** [comment]
@indirect Why doesn't building gems during `bundle package` make sense?

> gems created by checking out a git repo and then running git build could have any version

Couldn't you just pin the git SHA in the Gemfile?

> Bundler is not able to install a .gem file if the Gemfile lists a gem from a git repo. 

Perhaps there could be a `:build => true` argument which indicates that the gem was built.

Building dependencies keeps diffs small when updating or adding dependencies and reduces the chance that someone could directly modify the source code under `vendor/`.

**Comment by indirect** [comment]
@chrismo because Bundler will ignore the built gem when you run `bundle install`. Git gems are "installed" by copying a git repo checkout at a specific sha.

I'm not saying that the thing you are asking about is impossible, I'm saying that just building .gems when you run `package --build` will not do even half of what you're describing. Are you aware of that?

**Comment by chrismwendt** [comment]
@indirect There could be a gap in my understanding of the interaction between `package` and `install`, but the documentation makes it sound like `install` will in fact use the built gem.

> The package command will copy the .gem files for your gems in the bundle into ./vendor/cache. Afterward, when you run bundle install, Bundler will use the gems in the cache in preference to the ones on rubygems.org.

http://bundler.io/bundle_package.html

**Comment by indirect** [comment]
@chrismwendt note the language: "in preference to the ones on rubygems.org". Git gems are not on rubygems.org. Git gems are completely different: installed differently, managed differently, cached differently. Creating a .gem file in `vendor/cache` is 100% irrelevant if your gemfile contains `git:` or `github:` for that gem.

**Comment by chrismwendt** [comment]
@indirect Oh, I was expecting bundler to treat git URLs like the `source "https://rubygems.org"` directive, just on a per-dependency basis.

**Comment by indirect** [comment]
@chrismwendt sorry, I don't understand what that means. Git gems come from git repos, not from RubyGems servers. Creating a .gem doesn't change Bundler to look for a .gem instead of a git repo.

**Comment by chrismwendt** [comment]
@indirect I was thinking bundler would first check if a dependency exists under `vendor/cache`, and if not, it would download it from some source (either rubygems or a git URL).

I think that I now understand the implications of the fact that a gem coming from a git URL has an unknown version. bundler has no way to know whether or not a gem under `vendor/cache` is the same as the one at the git URL, even if the git SHA were pinned.

**Comment by indirect** [comment]
@chrismwendt yes. even more than that, though, gems from different types of sources are not cross-compatible, regardless of version. Path gems, git gems, and rubygems gems cannot be provided by a different kind of source, because they are managed, downloaded, installed, and used in fundamentally different ways.

**Comment by chrismwendt** [comment]
I'm closing this issue because it sounds like there must be a better approach, whatever that may be.

**Comment by indirect** [comment]
@fran-worley You have a couple of options there... you could use [Gemstash](https://github.com/bundler/gemstash) to act as a local cache of gems for each `bundle install`, or you could create a tarball of the installed/compiled gems and distribute that tarball to each machine and skip `bundle install` entirely. (That will only work if you can guarantee the OS, CPU architecture, and installed OS libraries are the same on every server, but maybe you can?)

**Comment by indirect** [comment]
@chrismwendt I think what I would recommend today, based on how Bundler works, is to set up your own Gemstash server, create .gem files out of your git gem dependencies, and change your Gemfile to use those .gem files from the Gemstash server instead of from git.

**Comment by chrismwendt** [comment]
@indirect Thanks for the suggestion 😃
