### ISSUE TITLE
Include `bundle env` output in error report template

### ISSUE THREAD

**Issue by LynnCo** [bundler/bundler#4641]
It might be worth it to make https://github.com/bundler/bundler/blob/dbad52b5b477936b25c2c5605247a9e70a0796cb/lib/bundler/friendly_errors.rb#L74 output the same as `bundle env`, to reduce the repetition of asking users for the bundler env output. I'm not actually sure if there's a specific case where we needed the output of bundle env that isn't in the error report template, so this might not actually be solving any problems

**Comment by segiddins** [comment]
This is already done, see https://github.com/bundler/bundler/blob/dca6d26833ddd9d9de658bef7274c8fa21014c44/lib/bundler/friendly_errors.rb#L74

**Comment by LynnCo** [comment]
👍
