### ISSUE TITLE
Getting Rails to work 

### ISSUE THREAD

**Issue by RAJKUMAR18** [bundler/bundler#4644]
hi i am using a debain linux and recently started rails...the **latest version of RUBY** available for debain is **1.9.3** so i **cannot install mime-types-data** on my system .I have installed most of the gems required for running my first RAILS application but BUNDLER is creating a problem help me please....
Following error occurs while installing mime:
## **_Gem::InstallError: mime-types-data requires Ruby version >= 2.0._**
Now.
----------------------------------------`
gem list bundler`

*** LOCAL GEMS ***

bundler (1.12.5, 1.1.4)
-----------------------------------------

> rails server

Bundler could not find compatible versions for gem "bundler":
  In Gemfile:
    rails (= 4.2.6) ruby depends on
      bundler (< 2.0, >= 1.3.0) ruby

  Current Bundler version:
    bundler (1.1.4)

This Gemfile requires a different version of Bundler.
Perhaps you need to update Bundler by running `gem install bundler`?

Please help me get started with RAILS

**Comment by hmistry** [comment]
There are a couple of options I found using Google:
1. use the newer version of Debian 8 (aka Jessie) which uses Ruby 2.1.5
2. install RVM and use it to install the latest version of Ruby and managing your gems - see http://stackoverflow.com/questions/16345465/how-to-install-ruby-2-0-in-debian-6.

Avoid using Ruby 1.9.3 as support for it ended last year.

**Comment by LynnCo** [comment]
@RAJKUMAR18 you'll want to follow @hmistry's comment also consider using more recently updated versions of Ruby and Bundler. I'm going to close this but we can continue working with you if you are still experiencing issues

**Comment by RAJKUMAR18** [comment]
thank you
