### ISSUE TITLE
bundle install comand error

### ISSUE THREAD

**Issue by engBrunoSales** [bundler/bundler#4649]
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `/home/brunosales/.rvm/gems/ruby-2.3.0/bin/bundle install`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what actually happened was...

Error details

    Errno::EPERM: Operation not permitted @ rb_file_s_rename - (/home/brunosales/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/info/jbuilder20160606-9437-51ceo8/jbuilder, /home/brunosales/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/info/jbuilder)
      /home/brunosales/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/fileutils.rb:528:in `rename'
      /home/brunosales/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/fileutils.rb:528:in `block in mv'
      /home/brunosales/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/fileutils.rb:1571:in `block in fu_each_src_dest'
      /home/brunosales/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/fileutils.rb:1587:in `fu_each_src_dest0'
      /home/brunosales/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/fileutils.rb:1569:in `fu_each_src_dest'
      /home/brunosales/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/fileutils.rb:517:in `mv'
      /home/brunosales/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:55:in `block in update'
      /home/brunosales/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
      /home/brunosales/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:29:in `update'
      /home/brunosales/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:64:in `update'
      /home/brunosales/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:73:in `update_info'
      /home/brunosales/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:43:in `block in dependencies'
      /home/brunosales/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/fetcher/compact_index.rb:88:in `block (3 levels) in compact_index_client'
      /home/brunosales/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/worker.rb:65:in `apply_func'
      /home/brunosales/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/worker.rb:60:in `block in process_queue'
      /home/brunosales/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/worker.rb:57:in `loop'
      /home/brunosales/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/worker.rb:57:in `process_queue'
      /home/brunosales/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/worker.rb:29:in `block (2 levels) in initialize'

Environment
      
  Bundler   1.12.5
  Rubygems  2.6.4
  Ruby      2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]
  GEM_HOME  /home/brunosales/.rvm/gems/ruby-2.3.0
  GEM_PATH  /home/brunosales/.rvm/gems/ruby-2.3.0:/home/brunosales/.rvm/gems/ruby-2.3.0@global
  RVM       1.27.0 (latest)
  Git       1.9.1
  rubygems-bundler (1.4.4)
      
      Bundler settings
      
  orig_path
    Set via BUNDLE_ORIG_PATH: "/home/brunosales/.rvm/gems/ruby-2.3.0/bin:/home/brunosales/.rvm/gems/ruby-2.3.0@global/bin:/home/brunosales/.rvm/rubies/ruby-2.3.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/brunosales/.rvm/bin:/home/brunosales/.rvm/bin"
  orig_gem_path
    Set via BUNDLE_ORIG_GEM_PATH: "/home/brunosales/.rvm/gems/ruby-2.3.0:/home/brunosales/.rvm/gems/ruby-2.3.0@global"

**Comment by segiddins** [comment]
@domcleal this looks related to your change as well?

**Comment by domcleal** [comment]
@engBrunoSales could you paste output from `ls -ld /home/brunosales/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/info/jbuilder20160606-9437-51ceo8/jbuilder /home/brunosales/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/info/jbuilder  /home/brunosales/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/info`

**Comment by LynnCo** [comment]
ping @engBrunoSales 

> could you paste output from `ls -ld /home/brunosales/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/info/jbuilder20160606-9437-51ceo8/jbuilder /home/brunosales/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/info/jbuilder  /home/brunosales/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/info`

**Comment by lynnco** [comment]
Closing this pending more feedback from the user. Can reopen it if needed!

**Comment by DSIW** [comment]
I had the same problem. I ran `sudo bundle` before installing chruby. After I installed ruby 2.3.1 via ruby-install and used the local bundle, then the permission denied error occured. It helped to delete the complete directory `~/.bundle`.

**Comment by flniu** [comment]
@DSIW Thank you! Delete `~/.bundle` is really helpful.

**Comment by caipivara** [comment]
@DSIW worked for me too
