### ISSUE TITLE
Could not find gem 'terminal-table (>= 1.6.0)'

### ISSUE THREAD

**Issue by kiddcrs** [bundler/bundler#4653]
ERROR:  Could not find a valid gem 'bundler' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=error: certificate verify failed (https://api.rubygems.org/specs.4.8.gz)

**Comment by LynnCo** [comment]
@kiddcrs can you try to some of the fixes in this thread https://github.com/google/google-api-ruby-client/issues/235? ie. https://github.com/google/google-api-ruby-client/issues/235#issuecomment-191159875 and https://github.com/google/google-api-ruby-client/issues/235#issuecomment-169956795

**Comment by chrismo** [comment]
see also #4478 for a similar SSL case and possible solution.
