### ISSUE TITLE
Can't install bundler - Errno::EACCES: Permission denied

### ISSUE THREAD

**Issue by JARM876** [bundler/bundler#4655]
I have been having an issue installing WPscan for the past three weeks. I kept getting an error message saying "parent directory rewritable but not sticky". No one seems to know how to resolve so I decided to do a clean install and try to track where I went wrong (I am very new to this). After installing everything, I am still getting another error message. Any help would be greatly appreciated!

- What did you do?

  I ran the command `/Users/WPScan/.rvm/gems/ruby-2.3.1@wpscan/bin/bundle install`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what actually happened was...

Error details

    Errno::EACCES: Permission denied @ dir_s_mkdir - /Users/WPScan/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/versions20160607-39594-ww5zsp
      /Users/WPScan/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tmpdir.rb:86:in `mkdir'
      /Users/WPScan/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tmpdir.rb:86:in `block in mktmpdir'
      /Users/WPScan/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tmpdir.rb:130:in `create'
      /Users/WPScan/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tmpdir.rb:86:in `mktmpdir'
      /Users/WPScan/.rvm/gems/ruby-2.3.1@wpscan/gems/bundler-1.12.5/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:29:in `update'
      /Users/WPScan/.rvm/gems/ruby-2.3.1@wpscan/gems/bundler-1.12.5/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:64:in `update'
      /Users/WPScan/.rvm/gems/ruby-2.3.1@wpscan/gems/bundler-1.12.5/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:55:in `update_and_parse_checksums!'
      /Users/WPScan/.rvm/gems/ruby-2.3.1@wpscan/gems/bundler-1.12.5/lib/bundler/fetcher/compact_index.rb:65:in `available?'
      /Users/WPScan/.rvm/gems/ruby-2.3.1@wpscan/gems/bundler-1.12.5/lib/bundler/fetcher/compact_index.rb:15:in `call'
      /Users/WPScan/.rvm/gems/ruby-2.3.1@wpscan/gems/bundler-1.12.5/lib/bundler/fetcher/compact_index.rb:15:in `block in compact_index_request'
      /Users/WPScan/.rvm/gems/ruby-2.3.1@wpscan/gems/bundler-1.12.5/lib/bundler/fetcher.rb:154:in `use_api'
      /Users/WPScan/.rvm/gems/ruby-2.3.1@wpscan/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:331:in `block in api_fetchers'
      /Users/WPScan/.rvm/gems/ruby-2.3.1@wpscan/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:331:in `select'
      /Users/WPScan/.rvm/gems/ruby-2.3.1@wpscan/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:331:in `api_fetchers'
      /Users/WPScan/.rvm/gems/ruby-2.3.1@wpscan/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:336:in `block in remote_specs'
      /Users/WPScan/.rvm/gems/ruby-2.3.1@wpscan/gems/bundler-1.12.5/lib/bundler/index.rb:10:in `build'
      /Users/WPScan/.rvm/gems/ruby-2.3.1@wpscan/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:335:in `remote_specs'
      /Users/WPScan/.rvm/gems/ruby-2.3.1@wpscan/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:82:in `specs'
      /Users/WPScan/.rvm/gems/ruby-2.3.1@wpscan/gems/bundler-1.12.5/lib/bundler/lazy_specification.rb:56:in `__materialize__'
      /Users/WPScan/.rvm/gems/ruby-2.3.1@wpscan/gems/bundler-1.12.5/lib/bundler/spec_set.rb:91:in `block in materialize'
      /Users/WPScan/.rvm/gems/ruby-2.3.1@wpscan/gems/bundler-1.12.5/lib/bundler/spec_set.rb:88:in `map!'
      /Users/WPScan/.rvm/gems/ruby-2.3.1@wpscan/gems/bundler-1.12.5/lib/bundler/spec_set.rb:88:in `materialize'
      /Users/WPScan/.rvm/gems/ruby-2.3.1@wpscan/gems/bundler-1.12.5/lib/bundler/definition.rb:140:in `specs'
      /Users/WPScan/.rvm/gems/ruby-2.3.1@wpscan/gems/bundler-1.12.5/lib/bundler/definition.rb:129:in `resolve_remotely!'
      /Users/WPScan/.rvm/gems/ruby-2.3.1@wpscan/gems/bundler-1.12.5/lib/bundler/installer.rb:195:in `resolve_if_need'
      /Users/WPScan/.rvm/gems/ruby-2.3.1@wpscan/gems/bundler-1.12.5/lib/bundler/installer.rb:70:in `run'
      /Users/WPScan/.rvm/gems/ruby-2.3.1@wpscan/gems/bundler-1.12.5/lib/bundler/installer.rb:22:in `install'
      /Users/WPScan/.rvm/gems/ruby-2.3.1@wpscan/gems/bundler-1.12.5/lib/bundler/cli/install.rb:102:in `run'
      /Users/WPScan/.rvm/gems/ruby-2.3.1@wpscan/gems/bundler-1.12.5/lib/bundler/cli.rb:175:in `install'
      /Users/WPScan/.rvm/gems/ruby-2.3.1@wpscan/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /Users/WPScan/.rvm/gems/ruby-2.3.1@wpscan/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /Users/WPScan/.rvm/gems/ruby-2.3.1@wpscan/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /Users/WPScan/.rvm/gems/ruby-2.3.1@wpscan/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /Users/WPScan/.rvm/gems/ruby-2.3.1@wpscan/gems/bundler-1.12.5/lib/bundler/cli.rb:11:in `start'
      /Users/WPScan/.rvm/gems/ruby-2.3.1@wpscan/gems/bundler-1.12.5/exe/bundle:27:in `block in <top (required)>'
      /Users/WPScan/.rvm/gems/ruby-2.3.1@wpscan/gems/bundler-1.12.5/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
      /Users/WPScan/.rvm/gems/ruby-2.3.1@wpscan/gems/bundler-1.12.5/exe/bundle:19:in `<top (required)>'
      /Users/WPScan/.rvm/gems/ruby-2.3.1@wpscan/bin/bundle:23:in `load'
      /Users/WPScan/.rvm/gems/ruby-2.3.1@wpscan/bin/bundle:23:in `<main>'
      /Users/WPScan/.rvm/gems/ruby-2.3.1@wpscan/bin/ruby_executable_hooks:15:in `eval'
      /Users/WPScan/.rvm/gems/ruby-2.3.1@wpscan/bin/ruby_executable_hooks:15:in `<main>'

Environment
      
  Bundler   1.12.5
  Rubygems  2.5.1
  Ruby      2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
  GEM_HOME  /Users/WPScan/.rvm/gems/ruby-2.3.1@wpscan
  GEM_PATH  /Users/WPScan/.rvm/gems/ruby-2.3.1@wpscan:/Users/WPScan/.rvm/gems/ruby-2.3.1@global
  RVM       1.27.0 (latest)
  Git       2.8.1
  rubygems-bundler (1.4.4)
      
      Bundler settings
      
  without
    Set for your local app (/Users/WPScan/wpscan/.bundle/config): "test"
  orig_path
    Set via BUNDLE_ORIG_PATH: "/Users/WPScan/.rvm/gems/ruby-2.3.1@wpscan/bin:/Users/WPScan/.rvm/gems/ruby-2.3.1@global/bin:/Users/WPScan/.rvm/rubies/ruby-2.3.1/bin:/Users/WPScan/.rvm/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
  orig_gem_path
    Set via BUNDLE_ORIG_GEM_PATH: "/Users/WPScan/.rvm/gems/ruby-2.3.1@wpscan:/Users/WPScan/.rvm/gems/ruby-2.3.1@global"

**Comment by LynnCo** [comment]
@JARM876 check out how the other issues with [permission errors](https://github.com/bundler/bundler/search?q=Permission+denied&type=Issues&utf8=%E2%9C%93) were resolved, like https://github.com/bundler/bundler/issues/4458, https://github.com/bundler/bundler/issues/4431, https://github.com/bundler/bundler/issues/4429

**Comment by LynnCo** [comment]
ping @JARM876 

> check out how the other issues with [permission errors](https://github.com/bundler/bundler/search?q=Permission+denied&type=Issues&utf8=%E2%9C%93) were resolved, like https://github.com/bundler/bundler/issues/4458, https://github.com/bundler/bundler/issues/4431, https://github.com/bundler/bundler/issues/4429

Also try searching the Bundler repo for that error message https://github.com/bundler/bundler/search?q=Permission+denied+%40+dir_s_mkdir&type=Issues&utf8=%E2%9C%93

**Comment by RochesterinNYC** [comment]
Closing as I think there's enough context in @LynnCo's linked issues/search to alleviate this. Please let us know if this isn't the case.

**Comment by byReham** [comment]
it worked after i did ...

sudo chmod 1777 -R /home/rbtlong/.bundle/cache/compact_index

and

sudo chmod 1777 -R /tmp

**Comment by BornaFN** [comment]
Please check permission for your ~/.bundle directory. In most cases like this it is root permission that is not right.

Do the following commands:
$ sudo mv ~/.bundle /tmp
$ bundle install
