### ISSUE TITLE
An error occurred while installing nokogiri (1.6.7.1), and Bundler cannot continue

### ISSUE THREAD

**Issue by Nagarjun123** [bundler/bundler#4656]
Hi i am running bundle install command i specified gem to be installed in .lock file 
It get stuck while downloading nokogiri(1.6.7.1) and throws this error.

**An error occurred while installing nokogiri (1.6.7.1), and Bundler cannot
continue
Make sure that `gem install nokogiri -v '1.6.7.1'` succeeds before bundling.**

I am Using OSX ElCaptain Version 10.11 Beta

![screen shot 2016-06-09 at 12 42 35 pm](https://cloud.githubusercontent.com/assets/13017830/15921502/8a9e9a50-2e3f-11e6-8875-5e2086e78fee.png)

**Comment by LynnCo** [comment]
@Nagarjun123 what happened when you ran `gem install nokogiri -v '1.6.7.1'`, then `bundle install` a second time

**Comment by Nagarjun123** [comment]
Its throwing error attached terminal error.

[NokogiriError.txt](https://github.com/bundler/bundler/files/308427/NokogiriError.txt)

**Comment by hmistry** [comment]
From your error log, it looks like you are missing some system libraries that Nokogiri requires to install. Since you have issues installing Nokogiri directly, the problem lies with Nokogiri and not bundler. See [Nokogiri installation guidelines](http://www.nokogiri.org/tutorials/installing_nokogiri.html) on installing it. If you are able to install Nokogiri directly but have problems with bundler, let us know.

**Comment by LynnCo** [comment]
@Nagarjun123 did you get to resolve these installation errors?

**Comment by iDevSpread** [comment]
as @lynnco mentioned, my solution for this is `sudo install nokogiri -v '1.6.7.1'` which works well for me. Thanks @lynnco for your solutions.

**Comment by jensgeffken** [comment]
this helped thanks a lot...

**Comment by shafiedavalath** [comment]
First try to do this`sudo apt-get install build-essential patch ruby-dev zlib1g-dev liblzma-dev`, then try to install

**Comment by dikonoor** [comment]
comment 12 really helped..Thanks @shafiedavalath

**Comment by Dorian** [comment]
For macOS:

```
gem update --system
xcode-select --install
```

**Comment by FaKeller** [comment]
I just came across this issue with nokogiri 1.8.2 and I installed the dependencies as mentioned by @shafiedavalath, but nokogiri still could not be installed. I solved the issue by installing `openssl`:

```
apt-get install openssl ruby-openssl libssl-dev
```

See [this gist for more details](https://gist.github.com/FaKeller/c0ea09b597e53b31122bb7866a57a629).
