### ISSUE TITLE
Show warning message from when ppid exec basename is Ruby

### ISSUE THREAD

**Issue by lynncyrin** [bundler/bundler#4666]
From: https://github.com/bundler/bundler/issues/2908#issuecomment-43013740

(comment edited slightly)

Bundler could detect when parent process is Ruby, then we could print a helpful message that the user should read the section on "Shelling out" in the manual. This would resolve this issue mentioned in https://github.com/bundler/bundler/issues/2908

``` Ruby
catch e => Bundler::GemNotFound
  if looks_like_my_ppid_exec_basename_is_ruby?
    puts "WARNING: ppid exec basename is Ruby, see Shelling Out on http://bundler.io/v1.6/man/bundle-exec.1.html for details"
  else
    throw e
  end
end
```

(note: this issue may not be relevant to the current version of Bundler)

**Comment by segiddins** [comment]
I honestly can't think of a good way of doing this

**Comment by LynnCo** [comment]
cc @errordeveloper in case you want to figure this out

**Comment by colby-swandale** [comment]
This hasn't been active for a long time. Closing.
