### ISSUE TITLE
multiple platform gems confusing Bundler when switching Rubies

### ISSUE THREAD

**Issue by kares** [bundler/bundler#4672]
at first I thought to be running into #4620 but as I tried to isolate I noticed its smt different.

when there are multiple platform specific gems (with deps changing btwn platforms) Bundler 1.12.5 fails to `bundle install` under a different platform (Ruby).

``` ruby
source 'https://rubygems.org'

gem 'pry-rails', '0.3.4', require: false
gem 'sauce-cucumber', '3.7', require: false
```

`bundle install`ed under JRuby (9.1.2.0) fails to `bundle install` under MRI (2.3.1)

Here's the [**Gemfile.lock**](https://gist.github.com/kares/4a978f3a6eb52fbef97ef55ac3cdb76f) generated under JRuby just try to `bundle install` under MRI, it shall fail with : 

_Your Gemfile.lock is corrupt. The following gem is missing from the DEPENDENCIES section: 'ffi'_

**NOTE:** that it works fine when I remove either gem declaration (keeping just one). 
its something about having multiple platform gems that bundler fails to resolve correctly when switching ...
- pry-rails depends on pry which has platform specific versions
- sauce-cucumber -> sauce -> childprocess -> ffi (has -java as well as "ruby" gem version)

**p.s.** very nice job towards handling platform gems in **1.12.5**, thank you :love_letter: !

**Comment by segiddins** [comment]
I was unable to reproduce this with master, and I've touched a lot of the platform code recently, so it being fixed wouldn't entirely surprise me

**Comment by colby-swandale** [comment]
ping @kares, is still a problem on the latest release?

**Comment by kares** [comment]
1.13.6 failed the same (Your Gemfile.lock is corrupt. ...) but 1.14.4 seems to work under MRI 2.3.3, thanks!
