### ISSUE TITLE
Statistics dashboard in Librato

### ISSUE THREAD

**Issue by LynnCo** [bundler/bundler#4677]
> Thanks to André Mediros, we are collecting Bundler, Ruby, and Rubygems versions in Librato. It would be great to have a dashboard that shows just the versions of Bundler, Rubygems, and Ruby that are being used, so we can see how many users we will be affecting with future compatibility decisions.

> This is an example of platform and version statistics that are super useful, maybe something like this? http://sparkle.psionides.eu/feeds/gitifier/statistics

> We have some partial graphs on the main bundler-api Librato dashboard, but they need to be updated for new versions of Ruby and Bundler. It would also be great to see graphs of how often install is run vs update, as well as graphs of OS, platform, RubyGems version, config settings, and the other data we are collecting.

> We also collect CI system names now, it would be cool to have a graph of CI vs non-CI commands as well as a breakdown of CI system percentages.

**Comment by segiddins** [comment]
Probably belongs on some rubygems.org infra tracker by now?
