### ISSUE TITLE
Add source hooks

### ISSUE THREAD

**Issue by LynnCo** [bundler/bundler#4681]
> Source plugins are hard, because they have to be loaded before the rest of the gemfile can even be evaluated. To begin with, let's require that source plugins must have no dependencies, and must be declared a different way:

```
# this type option maps to the plugin named "bundler-source-svn"
source "svn://svnhub.com/name/repo", type: "svn" do
  gem "my-cool-gem"
end
```

> We can evaluate the Gemfile once with only the `source` method defined, looking for `type` arguments so that we know what source plugins need to be downloaded, installed, and loaded before we can evaluate the entire Gemfile. We will still need to handle cases like `--local` when the source plugin isn't installed.

> Source plugins will need to register themselves with Bundler, but we're not yet sure where the hooks are. Extracting the Path and Git code into source plugins that are simply included with Bundler would be a good start.

**Comment by segiddins** [comment]
Done in https://github.com/bundler/bundler/pull/4674
