### ISSUE TITLE
Drop support for Ruby 2.0 and lower

### ISSUE THREAD

**Issue by lynnco** [bundler/bundler#4685]
> This will mean deleting most of rubygems_integration.rb, and we can finally update to the new hash syntax and even add keyword arguments if we want. Hooray.

Partially satisfied by https://github.com/bundler/bundler/pull/3842. Potentially fully satisfied already?

**Comment by segiddins** [comment]
This has been done on the 2.0 branch for a while. We can go through and remove hacks & adopt new features at our leisure, but I think rushing into doing it before shipping 2.0 would mean a rash of nasty merge conflicts. Closing as already satisfied.
