### ISSUE TITLE
OpenSSL::X509::StoreError  - Duplicate extensions not allowed

### ISSUE THREAD

**Issue by abhaynahar** [bundler/bundler#4686]
Error details

    OpenSSL::X509::StoreError: setting default path failed: problem creating X509 Aux certificate: java.io.IOException: problem parsing cert: java.security.cert.CertificateParsingException: java.io.IOException: Duplicate extensions not allowed
      org/jruby/ext/openssl/X509Store.java:185:in `set_default_paths'
      /Users/abhay/.rvm/rubies/jruby-1.7.20/lib/ruby/shared/jopenssl/load.rb:22:in `(root)'
      org/jruby/RubyKernel.java:1072:in `require'
      /Users/abhay/.rvm/rubies/jruby-1.7.20/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:54:in `require'
      /Users/abhay/.rvm/rubies/jruby-1.7.20/lib/ruby/shared/openssl.rb:1:in `(root)'
      org/jruby/RubyKernel.java:1072:in `require'
      /Users/abhay/.rvm/rubies/jruby-1.7.20/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:54:in `require'
      /Users/abhay/.rvm/rubies/jruby-1.7.20/lib/ruby/shared/openssl.rb:1:in `(root)'
      org/jruby/RubyKernel.java:1072:in `require'
      /Users/abhay/.rvm/rubies/jruby-1.7.20/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:54:in `require'
      /Users/abhay/.rvm/gems/jruby-1.7.20@goshposh_19/gems/bundler-1.9.9/lib/bundler/vendored_persistent.rb:1:in `(root)'
      /Users/abhay/.rvm/gems/jruby-1.7.20@goshposh_19/gems/bundler-1.9.9/lib/bundler/vendored_persistent.rb:4:in `(root)'
      /Users/abhay/.rvm/gems/jruby-1.7.20@goshposh_19/gems/bundler-1.9.9/lib/bundler/fetcher.rb:1:in `(root)'
      /Users/abhay/.rvm/gems/jruby-1.7.20@goshposh_19/gems/bundler-1.9.9/lib/bundler/fetcher.rb:1:in `(root)'
      /Users/abhay/.rvm/gems/jruby-1.7.20@goshposh_19/gems/bundler-1.9.9/lib/bundler/cli/install.rb:1:in `(root)'
      /Users/abhay/.rvm/gems/jruby-1.7.20@goshposh_19/gems/bundler-1.9.9/lib/bundler/cli/install.rb:72:in `run'
      /Users/abhay/.rvm/gems/jruby-1.7.20@goshposh_19/gems/bundler-1.9.9/lib/bundler/cli.rb:155:in `install'
      /Users/abhay/.rvm/gems/jruby-1.7.20@goshposh_19/gems/bundler-1.9.9/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /Users/abhay/.rvm/gems/jruby-1.7.20@goshposh_19/gems/bundler-1.9.9/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /Users/abhay/.rvm/gems/jruby-1.7.20@goshposh_19/gems/bundler-1.9.9/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /Users/abhay/.rvm/gems/jruby-1.7.20@goshposh_19/gems/bundler-1.9.9/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      org/jruby/RubyKernel.java:1091:in `load'
      /Users/abhay/.rvm/gems/jruby-1.7.20@goshposh_19/bin/bundle:23:in `(root)'

Environment

    Bundler   1.9.9
    Rubygems  2.4.6
    Ruby      1.9.3p551 (2015-05-04 revision 48406) [java]
    GEM_HOME  /Users/abhay/.rvm/gems/jruby-1.7.20@goshposh_19
    GEM_PATH  /Users/abhay/.rvm/gems/jruby-1.7.20@goshposh_19:/Users/abhay/.rvm/gems/jruby-1.7.20@global
    RVM       1.26.11 (latest)
    Git       2.3.8 (Apple Git-58)

**Comment by hmistry** [comment]
This looks similar to issue #3795 which was more of a jruby + openssl issue than a bundler issue.
