### ISSUE TITLE
Minimal `bundle install`

### ISSUE THREAD

**Issue by jkeiser** [bundler/bundler#4690]
I'd like to have a truly minimal bundle install. My scenario is, I am using `Gemfile.lock` to lock my software, but sometimes I need to bump the version (and nothing else). When I bump the version, I end up with an invalid `Gemfile`, so I need to `bundle install` to fix it. When I do *that*, it updates all dependencies rather than just my gem, even if they still satisfy my constraints. This breaks some of my testing assumptions.

I read here that I can do `bundle update --source mygem`, so I'll try that ... but it was surprising to me. I expected `bundle install` to update broken deps and install new ones, not update deps that still satisfy.

My understanding is the reason is we have a `locked` type flag on each dep, and if we decide to update an invalid one on bundle install our solution is to unlock it (which unlocks its dependencies). Since the locked flag can't tell the difference between this scenario and `bundle update mygem`, it assumes the latter, which is the issue.

Repro: https://github.com/jkeiser/bundle-repro/tree/bundler-4690

Actual output: https://gist.github.com/jkeiser/108b9b1a55b0bc0506dba6c554ee51fc. Particularly, when upgrading just the foo version, it updates both foo and bar: 

```
> FOO_VERSION=1.0.1 bundle install
Resolving dependencies...
Using bundle-test-bar 2.0.1 (was 2.0.0)
Using bundler 1.12.5
Using bundle-test-foo 1.0.1 (was 1.0.0) from source at `.`
Bundle complete! 1 Gemfile dependency, 3 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
```

Expected output: update `bundle-test-foo` but not `bundle-test-bar`:

```
> FOO_VERSION=1.0.1 bundle install
Resolving dependencies...
Using bundle-test-bar 2.0.0
Using bundler 1.12.5
Using bundle-test-foo 1.0.1 (was 1.0.0) from source at `.`
Bundle complete! 1 Gemfile dependency, 3 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
```

**Comment by segiddins** [comment]
`bundle update --source=gemname` should do it, iirc

**Comment by jkeiser** [comment]
@segiddins yep, I found that. It was surprising, however. Based on past behavior I never expect `bundle install` to touch a dependency unless it no longer satisfies my `Gemfile`. I'd *really* like `bundle install` to behave with Least Surprise, but if I need a `bundle install --minimal` flag, that would be a lot more discoverable :)

**Comment by indirect** [comment]
This honestly sounds like a regression to me. The intended behavior of `install` is to change versions as minimally as possible to allow installation—it should not update child dependencies if the original dependencies will work.

**Comment by jkeiser** [comment]
I put a repro up here:

https://github.com/jkeiser/bundle-repro/tree/bundler-4690

**Comment by jkeiser** [comment]
Basically if the last `bundle list` shows `bundle-test-bar (2.0.1)`, we upgraded dependencies.

**Comment by jkeiser** [comment]
This is with bundler 1.12.5, btw.

**Comment by chrismo** [comment]
@jkeiser prolly being dense, I can't get the repro to work. cloned it, checkout the branch, and neither bundle install nor the .sh script work for me - is this supposed to be the Gemfile? https://github.com/jkeiser/bundle-repro/blob/bundler-4690/Gemfile

**Comment by jkeiser** [comment]
@chrismo updated. `./repro.sh` is what ought to do the repro.

**Comment by jkeiser** [comment]
The top level Gemfile wasn't supposed to be there :)

**Comment by jkeiser** [comment]
This is the output I get from said repro: https://gist.github.com/jkeiser/108b9b1a55b0bc0506dba6c554ee51fc

**Comment by chrismo** [comment]
Thx, got it working.

I don't think this is a regression, since foo 1.0.1 is an updated dependency AND bar is not a listed dependency in the Gemfile (I know, this is weird, keep reading), the children are available for updating as well. `bundle update bundle-test-foo` will also behave the same way.

http://bundler.io/v1.12/man/bundle-install.1.html#CONSERVATIVE-UPDATING
```
Summary: In general, after making a change to the Gemfile(5) , you should first 
try to run bundle install, which will guarantee that no other gems in the Gemfile(5)
are impacted by the change. If that does not work, run bundle update(1).
```
Note it calls out in the _Gemfile_ not the _lockfile_.

The code reasons I've written up previously here: https://github.com/chrismo/bundler-source-hack#why-then-does-the-hack-sometimes-not-work

If you want `bar` to stay put, you gotta declare it as a dependency in the Gemfile, otherwise Bundler treats it as strictly a dependency of `foo` and something "behind the curtain" that you don't need to worry with. (Which in some cases (e.g. rails), you'd _want_ all the children updated by default).

Pulling back some, we're currently working on a PR to port bundler-patch over to Bundler which could give you what you want: #4676.

**Comment by indirect** [comment]
Aha. Yes, that is correct—conservative updating is only conservative for gems that are listed in the Gemfile, so this is not a regression.

@chrismo thanks for investigating!

@jkeiser for right now, you can use `bundler-patch` to give you better control over which gems get updated, and if you have time some feedback on #4676 would be great!

**Comment by chrismo** [comment]
@jkeiser bundler now has some of this functionality, would love your feedback: https://github.com/bundler/bundler-features/issues/122

**Comment by jkeiser** [comment]
@chrismo hmm, I'm not sure I see an option to say "update foo, but leave bar at its current version unless you absolutely have to change it"? I'm not sure how this would prevent a wholesale update of `bar` in all cases where `foo` is updated.

I still would like a way for `bundle install` to do the non-surprising thing, but I'll get around to making a patch for that.

**Comment by chrismo** [comment]
i think i'll respond over on that issue so we can discuss use cases like this.
