### ISSUE TITLE
Bundler 2.0 breaking changes

### ISSUE THREAD

**Issue by segiddins** [bundler/bundler#4695]
This is a list of breaking changes, mostly so I can ensure we have proper deprecation notices. But also generally helpful for release notes and blog posts, etc.
- Removal of `bundle_ruby` (in favor of `bundle platform --ruby`)
- Removal of `Bundler.clean_env` (in favor of `Bundler.original_env`)
- `:rubyforge`, `:gemcutter`, `:rubygems` sources
- Support for Ruby < 2.0
- Support for RubyGems < 2.4?
- global `path` sources
- multiple global gemfile sources
- [removal of `--frozen`](https://github.com/bundler/bundler/issues/4619)
- [inference of ruby version from `gemspec`](https://github.com/bundler/bundler/pull/4321)

**Comment by LynnCo** [comment]
There's a (likely outdated) list of breaking changes on the Yellow board also https://trello.com/b/DioUaKgx/bundler

**Comment by segiddins** [comment]
I can't get Trello to load at the moment ಠ_ಠ

**Comment by LynnCo** [comment]
Thats fair, I want to delete it soon anyway. Here's that list:

- [ ] [Stop auto-remembering any command flags](https://trello.com/c/yGsPNDpg/48-stop-auto-remembering-any-command-flags)
- [ ] [Add docs to config for all current remembered flags](https://trello.com/c/Bcx15aFl/49-add-docs-to-config-for-all-current-remembered-flags)
- [ ] [Default installs to --path ./.bundle/gems](https://trello.com/c/K4zdOFl8/51-default-installs-to-path-bundle-gems)
- [ ] [Block older versions during `bundle update`](https://trello.com/c/hGXbxb0w/70-block-older-versions-during-bundle-update)
- [ ] [Change platform method: separate arch, version, and name](https://trello.com/c/3wbBxOLG/53-change-platform-method-separate-arch-version-and-name)
- [ ] [Give `gems.rb` and `gems.locked` higher priority than the Gemfile counterparts](https://trello.com/c/nzhMlstw/55-give-gems-rb-and-gems-locked-higher-priority-than-the-gemfile-counterparts)
- [ ] [Split gem server sources in the lock file](https://trello.com/c/JlXm2yZy/100-split-gem-server-sources-in-the-lock-file)
- [ ] [Reinstall gem when source changes](https://trello.com/c/kZtjlsld/80-reinstall-gem-when-source-changes)
- [ ] [Investigate merging Bootscale into Bundler.setup](https://trello.com/c/UgnIwJke/113-investigate-merging-bootscale-into-bundler-setup)
- [ ] [Switch Bundler.ui methods to wrap by default](https://trello.com/c/M0oqCoEw/119-switch-bundler-ui-methods-to-wrap-by-default)

**Comment by chrismo** [comment]
Since this is on my brain from today from the conservative updates PR - I think Bundler could support not going to older versions with `bundle update ... --strict` ... but without the `--strict` flag, stay as-is -- I think there are cases where it still needs to be supported.

**Comment by segiddins** [comment]
Closing in favor of @colby-swandale's RFC.
