### ISSUE TITLE
bundler ignores path setting without local .bundle/config file

### ISSUE THREAD

**Issue by Overbryd** [bundler/bundler#4697]
Hello,

I am opening an issue because I think there might be something wrong with path settings.

**Prerequisites:**
```
# Gems have been installed using `bundle install --path ~/.bundle`
$ ls -lah ~/.bundle/ruby/2.3.0/gems/ | grep rake
drwxr-sr-x    7 app      app         4.0K Jun 22 12:53 rake-10.5.0

# The users bundle configuration contains the correct path
$ cat ~/.bundle/config | grep BUNDLE_PATH
BUNDLE_PATH: "/home/app/.bundle"
```

**Problem:**
```
# But `bundle exec command` does not work
$ bundle exec rake -vT
bundler: command not found: rake
Install missing gem executables with `bundle install`

# Although `bundle config path` shows the correct BUNDLE_PATH
$ bundle config path
Settings for `path` in order of priority. The top value will be used
Set for the current user (/home/app/.bundle/config): "/home/app/.bundle"
```

**Additional info:**
```
# Version
$ bundle -v
Bundler version 1.12.5

# The only hiccup/difference to other projects:
# This project has no local .bundle/config file
# But that is something I cannot provide for this instance.
# I configured the BUNDLE_PATH in the users ~/.bundle/config file.
# That is why I expect it to work.
$ cat .bundle/config
cat: can't open '.bundle/config': No such file or directory

$ cat ~/.bundle/config
---
BUNDLE_RETRY: 3
BUNDLE_FROZEN: '1'
BUNDLE_PATH: "/home/app/.bundle"
BUNDLE_CLEAN: true
BUNDLE_DISABLE_SHARED_GEMS: true

$ bundle config path
Settings for `path` in order of priority. The top value will be used
Set for the current user (/home/app/.bundle/config): "/home/app/.bundle"

```

Please tell me if there is other information you need that I can help with to debug this issue.

**Comment by segiddins** [comment]
I couldn't reproduce this.

```shell
$ bundle config --global path ~/Desktop/bundler
$ bundle install
$ bundle exec rake -T
```

**Comment by Overbryd** [comment]
Thank you for looking into this. Well indeed very weird, I also could not find a vanilla reproduction on my Mac.

The issue occured using Alpine Linux 3.4 within a Docker image.
I will try to provide a better reproducible case that does not include my whole project.

**Comment by Overbryd** [comment]
I am back, and I could reproduce it consistently when using the Alpine Linux 3.4 Docker image.
As described in the issue, pretty much everything is standard stuff (latest Ruby version, up to date Rubygems and latest Bundler) except for the local `.bundle/config` that I cannot provide for this image, but I expect a user setting in `~/.bundle/config` should suffice.

All the steps, including the Dockerfile, to reproduce this issue can be found in this repository: https://github.com/Overbryd/bundler-issue-4697

So maybe its this specific combination of things that leads to this issue, I double checked every step I do and except for the mentioned missing local `.bundle/config` I assume I am not doing anything weird.

**Comment by chrismo** [comment]
#4592 might be related?

**Comment by chrismo** [comment]
hmmm, I can recreate in the docker image ... and i don't see disable_shared_gems set to true, so that would preclude the #4592 issues probably ...

**Comment by chrismo** [comment]
I'm not sure this is a bundler problem? 

```
[chrismo@momac bundler-issue-4697 (master)]$ docker run -ti bundler-issue-4697
bash-4.3$ bundle exec rake -vT
bundler: failed to load command: rake (/home/app/gems/bin/rake)
LoadError: cannot load such file -- /usr/lib/ruby/gems/2.3.0/gems/rake-10.4.2/bin/rake
  /home/app/gems/bin/rake:22:in `load'
  /home/app/gems/bin/rake:22:in `<top (required)>'
bash-4.3$ bundle list rake
The gem rake has been deleted. It was installed at:
/usr/lib/ruby/gems/2.3.0/gems/rake-10.4.2
bash-4.3$ gem list rake

*** LOCAL GEMS ***

rake (10.4.2)
bash-4.3$ bundle config
Settings are listed in order of priority. The top value will be used.
path
Set for the current user (/home/app/.bundle/config): "/home/app/gems"

orig_path
Set via BUNDLE_ORIG_PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

bash-4.3$ bundle
Using rake 10.4.2
Using bundler 1.12.5
Bundle complete! 1 Gemfile dependency, 2 gems now installed.
Bundled gems are installed into /home/app/gems.
bash-4.3$ bundle exec rake -vT
rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)
/usr/bin/bundle:22:in `load'
/usr/bin/bundle:22:in `<main>'
(See full trace by running task with --trace)
```

**Comment by chrismo** [comment]
`RUN su` in the Dockerfile may be causing the problem? ... saw a stackoverflow saying to use `USER` not `RUN su app`

http://stackoverflow.com/questions/24549746/switching-users-inside-docker-image-to-a-non-root-user
https://docs.docker.com/engine/reference/builder/#user

**Comment by Overbryd** [comment]
##### Reply to https://github.com/bundler/bundler/issues/4697#issuecomment-227895150

I still think this might be related #4592. Let me elaborate:

As you ran `bash-4.3$ bundle` (bundling again) it creates a local `.bundle/config` file.
If that is present, `bundle exec rake` works as expected. If you remove the local `.bundle/config`, it still has the **--global** config in `~/.bundle/config` that is pointing to `/home/app/gems`. But `bundle exec rake` no longer works.

```
bash-4.3$ bundle exec rake -vT
bundler: failed to load command: rake (/home/app/gems/bin/rake)
LoadError: cannot load such file -- /usr/lib/ruby/gems/2.3.0/gems/rake-10.4.2/bin/rake
  /home/app/gems/bin/rake:22:in `load'
  /home/app/gems/bin/rake:22:in `<top (required)>'

bash-4.3$ bundle config
Settings are listed in order of priority. The top value will be used.
path
Set for the current user (/home/app/.bundle/config): "/home/app/gems"

orig_path
Set via BUNDLE_ORIG_PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

bash-4.3$ ls -lah /home/app/gems/gems/
total 12
drwxr-sr-x    3 app      app         4.0K Jun 22 22:38 .
drwxr-sr-x    9 app      app         4.0K Jun 22 22:38 ..
drwxr-sr-x    7 app      app         4.0K Jun 22 22:38 rake-10.4.2

bash-4.3$ ls -lah /home/app/gems/bin/
total 12
drwxr-sr-x    2 app      app         4.0K Jun 22 22:38 .
drwxr-sr-x    9 app      app         4.0K Jun 22 22:38 ..
-rwxr-xr-x    1 app      app          476 Jun 22 22:38 rake

bash-4.3$ bundle
Using rake 10.4.2
Using bundler 1.12.5
Bundle complete! 1 Gemfile dependency, 2 gems now installed.
Bundled gems are installed into /home/app/gems.
bash-4.3$ bundle config
Settings are listed in order of priority. The top value will be used.
path
Set for the current user (/home/app/.bundle/config): "/home/app/gems"

disable_shared_gems
Set for your local app (/home/app/current/.bundle/config): "true"

orig_path
Set via BUNDLE_ORIG_PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

bash-4.3$ bundle exec rake -vT
rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)
/usr/bin/bundle:22:in `load'
/usr/bin/bundle:22:in `<main>'
(See full trace by running task with --trace)

bash-4.3$ rm .bundle/config 

bash-4.3$ bundle exec rake -vT
bundler: failed to load command: rake (/home/app/gems/bin/rake)
LoadError: cannot load such file -- /usr/lib/ruby/gems/2.3.0/gems/rake-10.4.2/bin/rake
  /home/app/gems/bin/rake:22:in `load'
  /home/app/gems/bin/rake:22:in `<top (required)>'
```

##### Reply to https://github.com/bundler/bundler/issues/4697#issuecomment-227896590

I pushed an update to https://github.com/Overbryd/bundler-issue-4697 that does not use `su <USER> -c` and the problem persists.

I think bundler should respect a `--global` config even if the local `.bundle/config` is missing.

Hopefully I can find some time this week to step into the bundler code, because I still think #4592 might be involved in this behaviour (as bundler is apparently looking at the wrong path).

##### Furthermore

I was wondering about the differences of **global** `~/.bundle/config` and the **local** `.bundle/config`.

```
bash-4.3$ bundle
Using rake 10.4.2
Using bundler 1.12.5
Bundle complete! 1 Gemfile dependency, 2 gems now installed.
Bundled gems are installed into /home/app/gems.

bash-4.3$ diff ~/.bundle/config .bundle/config 
--- /home/app/.bundle/config
+++ .bundle/config
@@ -1,2 +1,2 @@
 ---
-BUNDLE_PATH: "/home/app/gems"
+BUNDLE_DISABLE_SHARED_GEMS: true

bash-4.3$ rm .bundle/config

bash-4.3$ bundle config --global disable_shared_gems true

bash-4.3$ bundle config
Settings are listed in order of priority. The top value will be used.
path
Set for the current user (/home/app/.bundle/config): "/home/app/gems"

disable_shared_gems
Set for the current user (/home/app/.bundle/config): "true"

orig_path
Set via BUNDLE_ORIG_PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
```

**Drumrolls**

```
bash-4.3$ bundle exec rake -vT
rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)
/usr/bin/bundle:22:in `load'
/usr/bin/bundle:22:in `<main>'
(See full trace by running task with --trace)
```

That works. So `BUNDLER_DISABLE_SHARED_GEMS: true` has an effect how the path is being set. 

I suspect this still some problematic behaviour, since setting a `BUNDLE_PATH` configuration for a user should apply it everywhere for the user, regardless of the shared gems setting.

**Comment by chrismo** [comment]
What's your need behind `bash-4.3$ rm .bundle/config`? Dockerfile has this in it, too.

**Comment by chrismo** [comment]
a way you can test if it's #4592 is install 1.11.2 and see if it works fine.

**Comment by Overbryd** [comment]
##### Reply to https://github.com/bundler/bundler/issues/4697#issuecomment-227903768

The idea was to configure bundler with a user configuration. So that the Dockerfile can be used as a standalone for running it somewhere else and as a _volume_ mounted local development environment. Mounting the local application source as a volume will override anything, also bundle configuration. Therefore I would like to rely on the **--global** configuration only.

##### Reply to https://github.com/bundler/bundler/issues/4697#issuecomment-227905968

I did a  `gem install bundler -v 1.11.2` and the issue persisted. So I am now concluding this is not related to #4592.

##### Furthermore

**Using `bundle config --global disable_shared_gems true`** solved the problem for me. So I think we can close this issue here.

**Comment by chrismo** [comment]
cool cool
