### ISSUE TITLE
Error while installing redmine

### ISSUE THREAD

**Issue by raresm79** [bundler/bundler#4698]
hi,

I'm trying to setup redmine 3.3.0 in the following environment:

  Bundler   1.12.5
  Rubygems  1.4.2
  Ruby      2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
  GEM_HOME  /usr/local/lib/ruby/gems/2.3.0
  GEM_PATH  /usr/local/lib/ruby/gems/2.3.0:/root/.gem/ruby/2.3.0
  Git       1.7.1

but when running command $bundler install I get the following error:

[root@ssredmine01 redmine]# bundler install
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your bundle as root will break this application
for all non-root users on this machine.
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `/usr/local/bin/bundler install`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what actually happened was...

Error details

    RuntimeError: can't modify frozen String
      /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/version.rb:191:in `strip!'
      /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/version.rb:191:in `initialize'
      /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/version.rb:178:in `new'
      /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/version.rb:178:in `create'
      /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/lockfile_parser.rb:30:in `<class:LockfileParser>'
      /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/lockfile_parser.rb:15:in `<module:Bundler>'
      /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/lockfile_parser.rb:14:in `<top (required)>'
      /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/definition.rb:2:in `require'
      /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/definition.rb:2:in `<top (required)>'
      /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler.rb:123:in `require'
      /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler.rb:123:in `definition'
      /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli/install.rb:99:in `run'
      /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli.rb:175:in `install'
      /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli.rb:11:in `start'
      /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/exe/bundler:21:in `block in <top (required)>'
      /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
      /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/exe/bundler:19:in `<top (required)>'
      /usr/local/bin/bundler:19:in `load'
      /usr/local/bin/bundler:19:in `<main>'

Environment

  Bundler   1.12.5
  Rubygems  1.4.2
  Ruby      2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
  GEM_HOME  /usr/local/lib/ruby/gems/2.3.0
  GEM_PATH  /usr/local/lib/ruby/gems/2.3.0:/root/.gem/ruby/2.3.0
  Git       1.7.1

      Bundler settings

  orig_path
    Set via BUNDLE_ORIG_PATH: "/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin"
--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/bundler/bundler/search?q=can%27t+modify+frozen+String&type=Issues

If there aren't any reports for this error yet, please create copy and paste the report template above into a new issue. Don't forget                                                                                                         to anonymize any private data! The new issue form is located at:
https://github.com/bundler/bundler/issues/new

I've found similar error messages, but nothing exactly the same and from the other threads I've read this error should be solved in bundler 1.12.5 
I'm not a developer and not really familiar with ruby, I'm just following the install steps from redmine website. 

If someone can throw a tip on how can I get passed this error, I would appreciate it.

Thanks
Rares

**Comment by allenzhao** [comment]
The message is about not running bundler as root. You might want to consider using a different user than root.

**Comment by segiddins** [comment]
@allenzhao that's not the issue... the problem is RubyGems 1.4.2 combined with Ruby 2.3, which means frozen string literals. Thanks for the issue, @raresm79 !
