### ISSUE TITLE
Gem.bin_path references local gem's bin directory

### ISSUE THREAD

**Issue by pnomolos** [bundler/bundler#4705]
I believe issue #2644 may still exist within a very narrow scope.  I have the following set up:

- I'm using rbenv
- A project which uses a local gem via `bundle config local.GEM_NAME`
- binstubs generated in the project
- binstubs generated in the local gem
- I'm using Bundler version 1.12.5

When trying to run `bin/guard` I get the following error:

```
Bundler is using a binstub that was created for a different gem.
This is deprecated, in future versions you may need to `bundle binstub guard` to work around a system/bundle conflict.
```

I have verified the following:

- My PATH does not contain references to either bin directory (so `bin/guard` is indeed pointing at the correct binstub)
- The project's `bin/guard` reference the guard gem directly.  `load Gem.bin_path("guard", "guard")`
- `load Gem.bin_path("guard", "guard")` __doesn't__ reference the same directory that `bundler show guard` does.  Instead, it references the local gem's path.

**Comment by segiddins** [comment]
What's the output of `bundle env`? Can you share a repo that reproduces the issue? Thanks!

**Comment by pnomolos** [comment]
`bundle env` output: https://gist.github.com/pnomolos/f0dc2ace4131fe0347d7a43f888afa35

Unfortunately I don't have a repo that reproduces the issue.  I'll see if I can generate a test case that does so.

**Comment by pnomolos** [comment]
Test project created: https://github.com/pnomolos/testproject

- Clone project
- Run `bundle install` in both directories
- Attempt to run `bin/guard` from the "project" directory.

**Comment by pnomolos** [comment]
An extra note: This is extra annoying with `guard` because that binstub actually calls `_guard-core`, so even if you hardcode the load path in `bin/guard` it'll fail when `_guard-core` is called.

**Comment by pnomolos** [comment]
@segiddins Not sure if you've had a chance to look at this yet, but just wanted to make sure the repo reproduces the issue for you also, and not just me :)

**Comment by segiddins** [comment]
@pnomolos just repro'd it and have a fix locally, just need to test it!

**Comment by pnomolos** [comment]
@segiddins Cool, that was quick! Just wanted to make sure I was being as helpful as possible :)

**Comment by segiddins** [comment]
No you definitely were :D thanks for the excellent report case, it made it super-easy to fix the bug :)
