### ISSUE TITLE
Bundle Install not working

### ISSUE THREAD

**Issue by shankar97** [bundler/bundler#4710]
$ bundle install
Ignoring nokogiri-1.6.7.2 because its extensions are not built.  Try: gem pristine nokogiri --version 1.6.7.2
Ignoring redcarpet-3.3.4 because its extensions are not built.  Try: gem pristine redcarpet --version 3.3.4
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `/usr/local/bin/bundle install`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what actually happened was...

Error details

    Errno::EACCES: Permission denied @ dir_s_mkdir - /home/ubuntu/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/versions20160624-24856-1enpvx6
      /usr/lib/ruby/2.2.0/tmpdir.rb:85:in `mkdir'
      /usr/lib/ruby/2.2.0/tmpdir.rb:85:in `block in mktmpdir'
      /usr/lib/ruby/2.2.0/tmpdir.rb:129:in `create'
      /usr/lib/ruby/2.2.0/tmpdir.rb:85:in `mktmpdir'
      /var/lib/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:29:in `update'
      /var/lib/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:64:in `update'
      /var/lib/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:55:in `update_and_parse_checksums!'
      /var/lib/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/fetcher/compact_index.rb:65:in `available?'
      /var/lib/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/fetcher/compact_index.rb:15:in `call'
      /var/lib/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/fetcher/compact_index.rb:15:in `block in compact_index_request'
      /var/lib/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/fetcher.rb:154:in `use_api'
      /var/lib/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:331:in `block in api_fetchers'
      /var/lib/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:331:in `select'
      /var/lib/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:331:in `api_fetchers'
      /var/lib/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:336:in `block in remote_specs'
      /var/lib/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/index.rb:10:in `build'
      /var/lib/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:335:in `remote_specs'
      /var/lib/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:82:in `specs'
      /var/lib/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/definition.rb:211:in `block (2 levels) in index'
      /var/lib/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/definition.rb:209:in `each'
      /var/lib/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/definition.rb:209:in `block in index'
      /var/lib/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/index.rb:10:in `build'
      /var/lib/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/definition.rb:206:in `index'
      /var/lib/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/definition.rb:200:in `resolve'
      /var/lib/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/definition.rb:140:in `specs'
      /var/lib/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/definition.rb:129:in `resolve_remotely!'
      /var/lib/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/installer.rb:195:in `resolve_if_need'
      /var/lib/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/installer.rb:70:in `run'
      /var/lib/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/installer.rb:22:in `install'
      /var/lib/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/cli/install.rb:102:in `run'
      /var/lib/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/cli.rb:175:in `install'
      /var/lib/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /var/lib/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /var/lib/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /var/lib/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /var/lib/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/cli.rb:11:in `start'
      /var/lib/gems/2.2.0/gems/bundler-1.12.5/exe/bundle:27:in `block in <top (required)>'
      /var/lib/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
      /var/lib/gems/2.2.0/gems/bundler-1.12.5/exe/bundle:19:in `<top (required)>'
      /usr/local/bin/bundle:23:in `load'
      /usr/local/bin/bundle:23:in `<main>'

Environment

  Bundler   1.12.5
  Rubygems  2.4.5.1
  Ruby      2.2.4p230 (2015-12-16 revision 53155) [x86_64-linux-gnu]
  GEM_HOME  /var/lib/gems/2.2.0
  GEM_PATH  /var/lib/gems/2.2.0:/home/ubuntu/.gem/ruby/2.2.0:/usr/share/rubygems-integration/2.2.0:/usr/share/rubygems-integration/all
  Git       1.9.1

      Bundler settings

  orig_path
    Set via BUNDLE_ORIG_PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/bundler/bundler/search?q=Permission+denied+%40+dir_s_mkdir+-+%2Fhome%2Fubuntu%2F.bundle%2Fcache%2Fcompact_index%2Frubygems.org.443.29b0360b937aa4d161703e6160654e47%2Fversions20160624-24856-1enpvx6&type=Issues

If there aren't any reports for this error yet, please create copy and paste the report template above into a new issue. Don't forget to anonymize any private data! The new issue form is located at:
https://github.com/bundler/bundler/issues/new

**Comment by hmistry** [comment]
The error is because `bundler` does not have permissions to access that folder. Please check your folder permissions and try again. Also, check out how the other issues with permission errors were resolved, like #4458, #4429. Let us know if you still have problems after you've got the right folder permissions set.

**Comment by RochesterinNYC** [comment]
Closing as I think there's enough context in @hmistry's linked issues to alleviate this. Please let us know if this isn't the case.
