### ISSUE TITLE
Bundle install error

### ISSUE THREAD

**Issue by mayureshmayur** [bundler/bundler#4722]
D:\MyWork\ruby\vish>bundle install
## --- ERROR REPORT TEMPLATE ------------------------------------------------------
- What did you do?
  
  I ran the command `C:/Ruby22/bin/bundle install`
- What did you expect to happen?
  
  I expected Bundler to...
- What happened instead?
  
  Instead, what actually happened was...

Error details

```
Errno::ENOENT: No such file or directory - git cat-file -e b3d47f9c90ea2f314
```

859b0e92fd30113775f2613
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/source/git/g
it_proxy.rb:133:in ``'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/source/git/g
it_proxy.rb:133:in`block in git'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/shared_helpe
rs.rb:71:in `call'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/shared_helpe
rs.rb:71:in`with_clean_git_env'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/source/git/g
it_proxy.rb:133:in `git'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/source/git/g
it_proxy.rb:140:in`block in has_revision_cached?'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/shared_helpe
rs.rb:53:in `chdir'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/shared_helpe
rs.rb:53:in`block in chdir'
      C:/Ruby22/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/shared_helpe
rs.rb:52:in`chdir'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/source/git/g
it_proxy.rb:178:in `in_path'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/source/git/g
it_proxy.rb:140:in`has_revision_cached?'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/source/git/g
it_proxy.rb:72:in `checkout'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/source/git.r
b:153:in`specs'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/definition.r
b:209:in `block (2 levels) in index'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/definition.r
b:207:in`each'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/definition.r
b:207:in `block in index'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/index.rb:9:i
n`build'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/definition.r
b:204:in `index'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/definition.r
b:198:in`resolve'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/definition.r
b:137:in `specs'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/definition.r
b:126:in`resolve_remotely!'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/installer.rb
:194:in `resolve_if_need'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/installer.rb
:69:in`run'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/installer.rb
:21:in `install'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/cli/install.
rb:105:in`run'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/cli.rb:172:i
n `install'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/vendor/thor/
lib/thor/command.rb:27:in`run'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/vendor/thor/
lib/thor/invocation.rb:126:in `invoke_command'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/vendor/thor/
lib/thor.rb:359:in`dispatch'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/vendor/thor/
lib/thor/base.rb:440:in `start'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/cli.rb:10:in
`start'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/exe/bundle:19:in `block
in <top (required)>'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/friendly_err
ors.rb:7:in`with_friendly_errors'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/exe/bundle:17:in `<top (
required)>'
      C:/Ruby22/bin/bundle:23:in`load'
      C:/Ruby22/bin/bundle:23:in `<main>'

Environment

```
Bundler   1.11.2
Rubygems  2.4.5.1
Ruby      2.2.3p173 (2015-08-18 revision 51636) [i386-mingw32]
GEM_HOME  C:/Ruby22/lib/ruby/gems/2.2.0
GEM_PATH  C:/Ruby22/lib/ruby/gems/2.2.0;C:/Users/Mayuresh/.gem/ruby/2.2.0
Git       not installed
```
## --- TEMPLATE END ---------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this err
or:
https://github.com/bundler/bundler/search?q=No+such+file+or+directory+-+git+cat-
file+-e+b3d47f9c90ea2f314859b0e92fd30113775f2613&type=Issues

If there aren't any reports for this error yet, please create copy and paste the
 report template above into a new issue. Don't forget to anonymize any private d
ata! The new issue form is located at:
https://github.com/bundler/bundler/issues/new

**Comment by segiddins** [comment]
It looks like you're trying to install a git gem without git installed.

**Comment by mayureshmayur** [comment]
D:\MyWork\ruby\vish>bundle
Fetching gem metadata from http://rubygems.org/..........
Fetching version metadata from http://rubygems.org/...
Fetching dependency metadata from http://rubygems.org/..
Resolving dependencies.................
Using rake 10.5.0
Using Ascii85 1.0.2
Using i18n 0.7.0
Using multi_json 1.11.2
Using builder 3.0.4
Using erubis 2.7.0
Using journey 1.0.4
Using rack 1.4.7
Using hike 1.2.3
Using tilt 1.4.1
Using mime-types 1.25.1
Using polyglot 0.3.5
Using arel 3.0.3
Using tzinfo 0.3.46
Using bundler 1.11.2
Using json 1.8.3
Using thor 0.19.1
Using htmlentities 4.3.4
Using nokogiri 1.5.11
Using rubyzip 1.0.0
Using afm 0.2.2
Installing rmagick 2.13.2 with native extensions

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    C:/Ruby22/bin/ruby.exe -r ./siteconf20160626-4660-4tzt6w.rb extconf.rb
checking for Ruby version >= 1.8.5... yes
checking for stdint.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/Ruby22/bin/$(RUBY_BASE_NAME)
C:/Ruby22/lib/ruby/2.2.0/mkmf.rb:456:in `try_do': The compiler failed to generat
e an executable file. (RuntimeError)
You have to install development tools first.
        from C:/Ruby22/lib/ruby/2.2.0/mkmf.rb:587:in `try_cpp'
        from C:/Ruby22/lib/ruby/2.2.0/mkmf.rb:1060:in `block in have_header'
        from C:/Ruby22/lib/ruby/2.2.0/mkmf.rb:911:in `block in checking_for'
        from C:/Ruby22/lib/ruby/2.2.0/mkmf.rb:351:in `block (2 levels) in postpo
ne'
        from C:/Ruby22/lib/ruby/2.2.0/mkmf.rb:321:in `open'
        from C:/Ruby22/lib/ruby/2.2.0/mkmf.rb:351:in `block in postpone'
        from C:/Ruby22/lib/ruby/2.2.0/mkmf.rb:321:in `open'
        from C:/Ruby22/lib/ruby/2.2.0/mkmf.rb:347:in `postpone'
        from C:/Ruby22/lib/ruby/2.2.0/mkmf.rb:910:in `checking_for'
        from C:/Ruby22/lib/ruby/2.2.0/mkmf.rb:1059:in `have_header'
        from extconf.rb:194:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in C:/Ruby22/lib/ruby/gems/2.2.0/gems/rmagick-2.
13.2 for inspection.
Results logged to C:/Ruby22/lib/ruby/gems/2.2.0/extensions/x86-mingw32/2.2.0/rma
gick-2.13.2/gem_make.out
Using bcrypt 3.1.11
Using sass 3.4.21
Using cancan 1.6.10
Using highline 1.7.8
Using jruby-pageant 1.1.1
Using ffi 1.9.10
Using coderay 1.1.1
Using coffee-script-source 1.10.0
Using execjs 2.6.0
Using deep_merge 1.0.1
Using delegates_attributes_to 0.0.1 from git://github.com/pahanix/delegates_attr
ibutes_to.git (at 69704cb@69704cb)
Using descriptive_statistics 2.4.0
Using detect_language 1.0.5
Using orm_adapter 0.5.0
Using diff-lcs 1.1.3
Using multipart-post 2.0.0
Using forgery 0.6.0
Using hashie 2.1.2
Using god 0.13.5 from git://github.com/mojombo/god.git (at a0602dd@a0602dd)
Using hashery 2.1.1
Using jwt 1.4.1
Installing kgio 2.10.0 with native extensions

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    C:/Ruby22/bin/ruby.exe -r ./siteconf20160626-4660-jsj0iz.rb extconf.rb
checking for CLOCK_MONOTONIC in time.h... yes
checking for clockid_t in time.h... yes
checking for clock_gettime() in -lrt... no
checking for t_open() in -lnsl... no
checking for socket() in -lsocket... no
checking for poll() in poll.h... no
checking for getaddrinfo() in sys/types.h,sys/socket.h,netdb.h... no
getaddrinfo required
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/Ruby22/bin/$(RUBY_BASE_NAME)
        --with-rtlib
        --without-rtlib
        --with-nsllib
        --without-nsllib
        --with-socketlib
        --without-socketlib

extconf failed, exit code 1

Gem files will remain installed in C:/Ruby22/lib/ruby/gems/2.2.0/gems/kgio-2.10.
0 for inspection.
Results logged to C:/Ruby22/lib/ruby/gems/2.2.0/extensions/x86-mingw32/2.2.0/kgi
o-2.10.0/gem_make.out
Using ruby-imagespec 0.2.0
Using method_source 0.8.2
Using modernizr-rails 2.7.1
Using multi_xml 0.5.5
Installing mysql2 0.3.16 with native extensions

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    C:/Ruby22/bin/ruby.exe -r ./siteconf20160626-4660-qkrw06.rb extconf.rb
checking for ruby/thread.h... yes
checking for rb_thread_call_without_gvl() in ruby/thread.h... yes
checking for rb_thread_blocking_region()... no
checking for rb_wait_for_single_fd()... yes
checking for rb_hash_dup()... yes
checking for rb_intern3()... yes
checking for mysql_query() in -lmysqlclient... no
checking for main() in -lm... yes
checking for mysql_query() in -lmysqlclient... no
checking for main() in -lz... no
checking for mysql_query() in -lmysqlclient... no
checking for main() in -lsocket... no
checking for mysql_query() in -lmysqlclient... no
checking for main() in -lnsl... no
checking for mysql_query() in -lmysqlclient... no
checking for main() in -lmygcc... no
checking for mysql_query() in -lmysqlclient... no
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/Ruby22/bin/$(RUBY_BASE_NAME)
        --with-mysql-dir
        --without-mysql-dir
        --with-mysql-include
        --without-mysql-include=${mysql-dir}/include
        --with-mysql-lib
        --without-mysql-lib=${mysql-dir}/lib
        --with-mysql-config
        --without-mysql-config
        --with-mysql-dir
        --without-mysql-dir
        --with-mysql-include
        --without-mysql-include=${mysql-dir}/include
        --with-mysql-lib
        --without-mysql-lib=${mysql-dir}/lib
        --with-mysqlclientlib
        --without-mysqlclientlib
        --with-mlib
        --without-mlib
        --with-mysqlclientlib
        --without-mysqlclientlib
        --with-zlib
        --without-zlib
        --with-mysqlclientlib
        --without-mysqlclientlib
        --with-socketlib
        --without-socketlib
        --with-mysqlclientlib
        --without-mysqlclientlib
        --with-nsllib
        --without-nsllib
        --with-mysqlclientlib
        --without-mysqlclientlib
        --with-mygcclib
        --without-mygcclib
        --with-mysqlclientlib
        --without-mysqlclientlib

extconf failed, exit code 1

Gem files will remain installed in C:/Ruby22/lib/ruby/gems/2.2.0/gems/mysql2-0.3
.16 for inspection.
Results logged to C:/Ruby22/lib/ruby/gems/2.2.0/extensions/x86-mingw32/2.2.0/mys
ql2-0.3.16/gem_make.out
Using oauth 0.5.1
Using ruby-rc4 0.1.5
Using ttfunk 1.4.0
Using pg 0.17.1
Using power_assert 0.2.7
Using slop 3.6.0
Using win32console 1.3.2
Installing raindrops 0.16.0 with native extensions

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    C:/Ruby22/bin/ruby.exe -r ./siteconf20160626-4660-1f6bfpa.rb extconf.rb
checking for mmap() in sys/mman.h... no
mmap() not found
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/Ruby22/bin/$(RUBY_BASE_NAME)
        --with-atomic_ops-dir
        --without-atomic_ops-dir
        --with-atomic_ops-include
        --without-atomic_ops-include=${atomic_ops-dir}/include
        --with-atomic_ops-lib
        --without-atomic_ops-lib=${atomic_ops-dir}/lib

extconf failed, exit code 1

Gem files will remain installed in C:/Ruby22/lib/ruby/gems/2.2.0/gems/raindrops-
0.16.0 for inspection.
Results logged to C:/Ruby22/lib/ruby/gems/2.2.0/extensions/x86-mingw32/2.2.0/rai
ndrops-0.16.0/gem_make.out
Using redis 3.0.7
Using riddle 1.5.12
Using rspec-core 2.9.0
Using rspec-mocks 2.9.0
Using websocket 1.2.2
Using simple_captcha 0.1.6 from git://github.com/galetahub/simple-captcha.git (a
t 2602bf1@2602bf1)
Using stringex 1.5.1
Using sqlite3 1.3.9
Using faker 1.4.3
Using i18n-js 2.1.2
Using activesupport 3.2.22.2 from git://github.com/rails/rails.git (at 3-2-stabl
e@54ebd0a)
Using sitemap_generator 5.1.0
Using rack-cache 1.6.1
Using rack-test 0.6.3
Using rack-ssl 1.3.4
Using warden 1.2.6
Using rack-protection 1.5.3
Using vegas 0.1.11
Using sprockets 2.2.3
Using rest-client 1.6.7
Using treetop 1.4.15
Using rdoc 3.12.2
Using xpath 2.0.0
Using sanitize 2.1.0
Using axlsx 2.0.1
Using scorm 1.0.5 from git://github.com/agordillo/scorm.git (at master@b3d47f9)
An error occurred while installing rmagick (2.13.2), and Bundler cannot
continue.
Make sure that `gem install rmagick -v '2.13.2'` succeeds before bundling.

Not able to install some gems like rmagick, mysql2 etc.

**Comment by colby-swandale** [comment]
I'm closing this for now. If you're still experiencing your original issue don't be afraid to re-open this ticket.
