### ISSUE TITLE
Add support to reinstall borked gem, e.g. rmagick, nokogiri

### ISSUE THREAD

**Issue by ioquatix** [bundler/bundler#4723]
Lots of gems either fail to work (e.g. rmagick) or create a lot of noise (e.g. nokogiri) when the system library has been updated but the gem hasn't been changed, i.e. it's still linking against the old version.

Presently, there is no easy way to fix this without understanding how to use the gem command to uninstall and then reinstall the misbehaving gem.

e.g.

    GEM_HOME=./vendor/bundle/ruby/2.3.0/ gem uninstall rmagick
    bundle install

It would be nice if there was a flag to `bundle install` or a `bundle reinstall` or `bundle uninstall` command that would assist with this problem. This is definitely affecting users, e.g. http://stackoverflow.com/questions/12188833/how-to-reinstall-a-gem-using-bundler/38038505#38038505

**Comment by segiddins** [comment]
`bundle install --force` should do just that!

**Comment by indirect** [comment]
A very easy way to use the gem command is to run `bundle exec gem pristine GEMNAME` (and we are working on a `pristine` command for Bundler right now). But `bundle install --force` should also work!

**Comment by ioquatix** [comment]
It's interesting because I tried --force but it still installed the old gem, perhaps from cache, last time I tried.. I'll try again and report back.. not sure fi the issue is closed yet..

**Comment by ioquatix** [comment]
```
% sudo -u http bundle list
...
* nokogiri (1.6.7.2)
...
% sudo -u http bundle exec rake console
WARNING: Nokogiri was built against LibXML version 2.9.2, but has dynamically loaded 2.9.3
[1] pry(main)>
% sudo -u http bundle install --force
... nokogiri not listed ...
% sudo -u http bundle exec rake console
WARNING: Nokogiri was built against LibXML version 2.9.2, but has dynamically loaded 2.9.3
[1] pry(main)>
```

Is it possible that `bundle install --force` is only installing direct dependencies?

**Comment by ioquatix** [comment]
Trying to use `gem pristine`:

```
% sudo -u http bundle exec gem pristine nokogiri
Restoring gems to pristine condition...
Building native extensions.  This could take a while...
ERROR:  While executing gem ... (Gem::Ext::BuildError)
    ERROR: Failed to build gem native extension.

    current directory: /srv/http/business.geozone.co.nz/vendor/bundle/ruby/2.3.0/gems/nokogiri-1.6.7.2/ext/nokogiri
/usr/bin/ruby -r ./siteconf20160627-19412-12kb48q.rb extconf.rb
/usr/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/spec_set.rb:94:in `block in materialize': Could not find nokogiri-1.6.7.2 in any of the sources (Bundler::GemNotFound)
	from /usr/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/spec_set.rb:87:in `map!'
	from /usr/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/spec_set.rb:87:in `materialize'
	from /usr/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/definition.rb:137:in `specs'
	from /usr/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/definition.rb:182:in `specs_for'
	from /usr/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/definition.rb:171:in `requested_specs'
	from /usr/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/environment.rb:18:in `requested_specs'
	from /usr/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:13:in `setup'
	from /usr/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler.rb:92:in `setup'
	from /usr/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/setup.rb:18:in `<top (required)>'
	from /usr/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'

extconf failed, exit code 1

Gem files will remain installed in /srv/http/business.geozone.co.nz/vendor/bundle/ruby/2.3.0/gems/nokogiri-1.6.7.2 for inspection.
Results logged to /srv/http/business.geozone.co.nz/vendor/bundle/ruby/2.3.0/extensions/x86_64-linux/2.3.0/nokogiri-1.6.7.2/gem_make.out
```

**Comment by ioquatix** [comment]
```
% pwd  
/srv/http/business.geozone.co.nz/vendor/bundle/ruby/2.3.0/gems
% ls noko*
nokogiri-1.6.7.2:
appveyor.yml  build_all		   CHANGELOG.ja.rdoc  dependencies.yml	Gemfile  LICENSE.txt   patches	Rakefile   ROADMAP.md		  suppressions	test	  Y_U_NO_GEMSPEC.md
bin	      C_CODING_STYLE.rdoc  CHANGELOG.rdoc     ext		lib	 Manifest.txt  ports	README.md  STANDARD_RESPONSES.md  tasks		test_all
```

So, it's definitely there..

**Comment by ioquatix** [comment]
I've come to the conclusion it's nothing to do with bundler, my apologies. I removed the vendor directory and reinstalled everything.. not change.. something weird in nokogiri?

**Comment by mikegee** [comment]
I had this problem too. `bundle exec gem pristine pg` gives output just like that with `Bundler::GemNotFound`.

I resolved it by hard-coding the version of pg in `Gemfile` then running `bundle up pg`. I suspect `bundle install --force` would have worked too.

**Comment by segiddins** [comment]
`bundle doctor` can now diagnose these issues, for what its worth
