### ISSUE TITLE
`bundler` and `bundle` executables should be the same functionally

### ISSUE THREAD

**Issue by RochesterinNYC** [bundler/bundler#4725]
The `bundler` executable (https://github.com/bundler/bundler/blob/master/exe/bundler) should functionally be the same as the `bundle` executable (https://github.com/bundler/bundler/blob/master/exe/bundle).

Ideally, this would be done in a way that doesn't involve duplication of code and doesn't require updating code in two places when a change is made to the `bundle` executable.

**Comment by segiddins** [comment]
This can easily be done by changing the `bundler` executable to be `load File.expand_path("../bundle", __FILE__)`

**Comment by b-ggs** [comment]
I'll work on this.
