### ISSUE TITLE
Rescue and explain failed `remove_entry_secure`

### ISSUE THREAD

**Issue by indirect** [bundler/bundler#4726]
As revealed by #4722, sometimes `FileUtils.remove_entry_secure` will raise an error like this one:

> ArgumentError: parent directory is world writable, FileUtils#remove_entry_secure does not work; abort: "/home/user/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/versions20160626-2788-14mnsu2" (parent directory mode 40777)

We need to catch this error and explain that it is a security vulnerability to allow your home directory to be world-writable. We should also explain the fix (which is probably (?) to run `chmod o-w ~`). There is a longer description of the times when the error can be raised in the [FileUtils#remove_entry_secure docs](http://ruby-doc.org/stdlib-2.1.2/libdoc/fileutils/rdoc/FileUtils.html#method-c-remove_entry_secure), and a very slightly longer description of the vulnerability at [Mitre](http://www.cve.mitre.org/cgi-bin/cvename.cgi?name=CAN-2005-0448).

**Comment by allenzhao** [comment]
I will work on this
