### ISSUE TITLE
bundler not respecting no_proxy

### ISSUE THREAD

**Issue by HoneyryderChuck** [bundler/bundler#4728]
We have this setup where we have our internal gem server for private gems behind the proxy, and we access rubygems using ssl through the proxy. Until now, we had something like this:

``` ruby
source 'https://rubygems.org'
source 'http://gem.server.local'
```

This worked. Recently we upgraded the frontend to also reroute requests coming from the backend, and these require ssl. So we wanted to change to:

``` ruby
source 'https://rubygems.org'
source 'https://gem.server.frontend'
```

This doesn't work, however, as bundler uses net/http, and default connection doesn't respect no_proxy settings, which is the way other clients (like curl) are not rerouting that request through the proxy.

In order for this to work, one would have to explicitly set the net-http with proxy parameters set to nil:

``` ruby
# instead of
server = Net::HTTP.new(uri.host, uri.port)
# do
server = Net::HTTP.new(uri.host, uri.port, nil, nil)
```

but the `source` directive for the Gemfile doesn't allow to set proxy parameters. 

I already [gave my support in the ruby ticket for this to be fixed internally at the net-http library](https://bugs.ruby-lang.org/issues/11195), but this seems to be a very old issue which won't be fixed that fast. Would a bit more tinkering with the gem source be possible? Like:

``` ruby
source 'https://rubygems.org'
source 'http://gem.server.local', proxy_host: nil
```

**Comment by segiddins** [comment]
I believe the ruby standard library is the correct place to fix this, as bundler itself isn't the one applying the proxy settings

**Comment by HoneyryderChuck** [comment]
https://docs.ruby-lang.org/en/2.1.0/URI/Generic.html#method-i-find_proxy

Ruby does support `no_proxy`, I'd suggest a contained example using the URI library, and debug from there.

**Comment by HoneyryderChuck** [comment]
I just realized that I added this issue, lol. I'll close this, has been fixed for ages.
