### ISSUE TITLE
Bundler 1.3.5 won't override gem source with mirrors

### ISSUE THREAD

**Issue by dinhxuanvu** [bundler/bundler#4736]
I tried to use `bundle config mirror.https://rubygems.org $RUBYGEM_MIRROR` to allow `bundle install` to download gem packages from a mirror instead of the default source repo. However, unfortunately, it doesn't work. I notice that I'm using Bundler 1.3.5 and the 'override gem sources with mirrors' feature is not introduced until Bundler 1.5.0. I wonder if there is a way to override the gem source using Bundler 1.3.5?

**Comment by segiddins** [comment]
We recommend ipdating to the latest bundler version, 1.12.5

**Comment by dinhxuanvu** [comment]
I wish I can but kind of stuck at that version due to some restriction unfortunately. :(

**Comment by indirect** [comment]
@dinhxuanvu Bundler 1.3.5 does not include a way to configure gem mirrors. As you noticed, we introduced mirror configuration in Bundler 1.5.
