### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by davidslee101** [bundler/bundler#4742]
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `/Users/davidlee/.rvm/rubies/ruby-2.3.1/bin/bundle install`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what actually happened was...

Error details

    Errno::EACCES: Permission denied @ dir_s_mkdir - /Users/davidlee/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/versions20160702-71629-1xtkf28
      /Users/davidlee/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tmpdir.rb:86:in `mkdir'
      /Users/davidlee/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tmpdir.rb:86:in `block in mktmpdir'
      /Users/davidlee/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tmpdir.rb:130:in `create'
      /Users/davidlee/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tmpdir.rb:86:in `mktmpdir'
      /Users/davidlee/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.12.5/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:29:in `update'
      /Users/davidlee/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.12.5/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:64:in `update'
      /Users/davidlee/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.12.5/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:55:in `update_and_parse_checksums!'
      /Users/davidlee/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.12.5/lib/bundler/fetcher/compact_index.rb:65:in `available?'
      /Users/davidlee/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.12.5/lib/bundler/fetcher/compact_index.rb:15:in `call'
      /Users/davidlee/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.12.5/lib/bundler/fetcher/compact_index.rb:15:in `block in compact_index_request'
      /Users/davidlee/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.12.5/lib/bundler/fetcher.rb:154:in `use_api'
      /Users/davidlee/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:331:in `block in api_fetchers'
      /Users/davidlee/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:331:in `select'
      /Users/davidlee/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:331:in `api_fetchers'
      /Users/davidlee/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:336:in `block in remote_specs'
      /Users/davidlee/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.12.5/lib/bundler/index.rb:10:in `build'
      /Users/davidlee/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:335:in `remote_specs'
      /Users/davidlee/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:82:in `specs'
      /Users/davidlee/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.12.5/lib/bundler/definition.rb:211:in `block (2 levels) in index'
      /Users/davidlee/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.12.5/lib/bundler/definition.rb:209:in `each'
      /Users/davidlee/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.12.5/lib/bundler/definition.rb:209:in `block in index'
      /Users/davidlee/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.12.5/lib/bundler/index.rb:10:in `build'
      /Users/davidlee/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.12.5/lib/bundler/definition.rb:206:in `index'
      /Users/davidlee/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.12.5/lib/bundler/definition.rb:200:in `resolve'
      /Users/davidlee/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.12.5/lib/bundler/definition.rb:140:in `specs'
      /Users/davidlee/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.12.5/lib/bundler/definition.rb:129:in `resolve_remotely!'
      /Users/davidlee/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.12.5/lib/bundler/installer.rb:195:in `resolve_if_need'
      /Users/davidlee/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.12.5/lib/bundler/installer.rb:70:in `run'
      /Users/davidlee/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.12.5/lib/bundler/installer.rb:22:in `install'
      /Users/davidlee/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.12.5/lib/bundler/cli/install.rb:102:in `run'
      /Users/davidlee/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.12.5/lib/bundler/cli.rb:175:in `install'
      /Users/davidlee/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /Users/davidlee/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /Users/davidlee/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /Users/davidlee/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /Users/davidlee/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.12.5/lib/bundler/cli.rb:11:in `start'
      /Users/davidlee/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.12.5/exe/bundle:27:in `block in <top (required)>'
      /Users/davidlee/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.12.5/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
      /Users/davidlee/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.12.5/exe/bundle:19:in `<top (required)>'
      /Users/davidlee/.rvm/rubies/ruby-2.3.1/bin/bundle:23:in `load'
      /Users/davidlee/.rvm/rubies/ruby-2.3.1/bin/bundle:23:in `<main>'
      /Users/davidlee/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
      /Users/davidlee/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'

Environment
      
  Bundler   1.12.5
  Rubygems  2.5.1
  Ruby      2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
  GEM_HOME  /Users/davidlee/.rvm/gems/ruby-2.3.1
  GEM_PATH  /Users/davidlee/.rvm/gems/ruby-2.3.1:/Users/davidlee/.rvm/gems/ruby-2.3.1@global
  RVM       1.27.0 (latest)
  Git       2.6.2
  rubygems-bundler (1.4.4)
      
      Bundler settings
      
  build.nokogiri
    Set for the current user (/Users/davidlee/.bundle/config): "--use-system-libraries"
  orig_path
    Set via BUNDLE_ORIG_PATH: "/Users/davidlee/.rvm/gems/ruby-2.3.1/bin:/Users/davidlee/.rvm/gems/ruby-2.3.1@global/bin:/Users/davidlee/.rvm/rubies/ruby-2.3.1/bin:/Users/davidlee/.rvm/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Postgres.app/Contents/Versions/latest/bin"
  orig_gem_path
    Set via BUNDLE_ORIG_GEM_PATH: "/Users/davidlee/.rvm/gems/ruby-2.3.1:/Users/davidlee/.rvm/gems/ruby-2.3.1@global"
--- TEMPLATE END ----------------------------------------------------------------

**Comment by allenzhao** [comment]
Seems like you're having a permission issue.
Try running `sudo chown -R davidlee $HOME/.rbenv` then run bundler again.

**Comment by LynnCo** [comment]
@davidslee101 ping

> Seems like you're having a permission issue.
> Try running sudo chown -R davidlee $HOME/.rbenv then run bundler again.

**Comment by davidslee101** [comment]
This worked! Thanks!

**Comment by davidslee101** [comment]
Great! that helped me out thanks everyone
