### ISSUE TITLE
issue on bundle command

### ISSUE THREAD

**Issue by prashantravidarshan** [bundler/bundler#4747]
Hello There

I am using ubuntu 14.04 and working on rvm 2.2.4 .

Here My gemfile.

source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.5'
gem 'carrierwave'
gem 'mini_magick'
gem 'will_paginate', '3.1.0'
gem 'bootstrap-will_paginate', '0.0.10'
gem 'bcrypt', '3.1.11'
gem 'fog'

gem "jquery-rails",'>= 1.0.0'

# Use SCSS for stylesheets
gem 'bootstrap-sass', '~> 3.3.6'
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby
gem 'paypal-sdk-adaptivepayments'
# Use jquery as the JavaScript library
# gem 'jquery-rails','>= 1.0.0'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'
# Use Unicorn as the app server
# gem 'unicorn'
# gem 'will_paginate', ">3.0.pre2"

# gem 'formtastic', git: 'git@github.com:justinfrench/formtastic.git', :branch => 'master'
# gem devise for user Authentication
gem 'devise',      '> 4.1.0'
#gem active_admin for handle the backend of application
gem 'activeadmin', github: 'activeadmin'

#gem geocoder for location
gem 'geocoder'
#gem omniauth-facebook for facebook Authentication
 gem 'omniauth-facebook'
 gem  'omniauth'
 # for Video Thumnail
 gem 'carrierwave-video-thumbnailer' 

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
    # Use sqlite3 as the database for Active Record
gem 'sqlite3'
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
end

group :development do

  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end

group :production do

  gem 'pg'
  
  gem 'rails_12factor'
  
end
gem 'figaro'
gem 'country_select'
gem "nested_form"
 
===================================================

when I am using bundle command it showing me the bellow error.
please review and do the needful

development@development-Inspiron-3542:~/Desktop/projects/hashmat/event$ bundle
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `/home/development/.rvm/gems/ruby-2.2.4/bin/bundle `

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what actually happened was...

Error details

    URI::InvalidURIError: bad URI(is not URI?): http://user:password@host:port
      /home/development/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/uri/rfc3986_parser.rb:66:in `split'
      /home/development/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/uri/rfc3986_parser.rb:72:in `parse'
      /home/development/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/uri/common.rb:226:in `parse'
      /home/development/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/uri/common.rb:713:in `URI'
      /home/development/.rvm/gems/ruby-2.2.4/gems/bundler-1.12.5/lib/bundler/vendor/net/http/persistent.rb:908:in `proxy_from_env'
      /home/development/.rvm/gems/ruby-2.2.4/gems/bundler-1.12.5/lib/bundler/vendor/net/http/persistent.rb:858:in `proxy='
      /home/development/.rvm/gems/ruby-2.2.4/gems/bundler-1.12.5/lib/bundler/vendor/net/http/persistent.rb:528:in `initialize'
      /home/development/.rvm/gems/ruby-2.2.4/gems/bundler-1.12.5/lib/bundler/fetcher.rb:237:in `new'
      /home/development/.rvm/gems/ruby-2.2.4/gems/bundler-1.12.5/lib/bundler/fetcher.rb:237:in `connection'
      /home/development/.rvm/gems/ruby-2.2.4/gems/bundler-1.12.5/lib/bundler/fetcher.rb:81:in `initialize'
      /home/development/.rvm/gems/ruby-2.2.4/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:232:in `new'
      /home/development/.rvm/gems/ruby-2.2.4/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:232:in `block in fetchers'
      /home/development/.rvm/gems/ruby-2.2.4/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:230:in `map'
      /home/development/.rvm/gems/ruby-2.2.4/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:230:in `fetchers'
      /home/development/.rvm/gems/ruby-2.2.4/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:336:in `block in remote_specs'
      /home/development/.rvm/gems/ruby-2.2.4/gems/bundler-1.12.5/lib/bundler/index.rb:10:in `build'
      /home/development/.rvm/gems/ruby-2.2.4/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:335:in `remote_specs'
      /home/development/.rvm/gems/ruby-2.2.4/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:82:in `specs'
      /home/development/.rvm/gems/ruby-2.2.4/gems/bundler-1.12.5/lib/bundler/lazy_specification.rb:56:in `__materialize__'
      /home/development/.rvm/gems/ruby-2.2.4/gems/bundler-1.12.5/lib/bundler/spec_set.rb:91:in `block in materialize'
      /home/development/.rvm/gems/ruby-2.2.4/gems/bundler-1.12.5/lib/bundler/spec_set.rb:88:in `map!'
      /home/development/.rvm/gems/ruby-2.2.4/gems/bundler-1.12.5/lib/bundler/spec_set.rb:88:in `materialize'
      /home/development/.rvm/gems/ruby-2.2.4/gems/bundler-1.12.5/lib/bundler/definition.rb:140:in `specs'
      /home/development/.rvm/gems/ruby-2.2.4/gems/bundler-1.12.5/lib/bundler/definition.rb:129:in `resolve_remotely!'
      /home/development/.rvm/gems/ruby-2.2.4/gems/bundler-1.12.5/lib/bundler/installer.rb:195:in `resolve_if_need'
      /home/development/.rvm/gems/ruby-2.2.4/gems/bundler-1.12.5/lib/bundler/installer.rb:70:in `run'
      /home/development/.rvm/gems/ruby-2.2.4/gems/bundler-1.12.5/lib/bundler/installer.rb:22:in `install'
      /home/development/.rvm/gems/ruby-2.2.4/gems/bundler-1.12.5/lib/bundler/cli/install.rb:102:in `run'
      /home/development/.rvm/gems/ruby-2.2.4/gems/bundler-1.12.5/lib/bundler/cli.rb:175:in `install'
      /home/development/.rvm/gems/ruby-2.2.4/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /home/development/.rvm/gems/ruby-2.2.4/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /home/development/.rvm/gems/ruby-2.2.4/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /home/development/.rvm/gems/ruby-2.2.4/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /home/development/.rvm/gems/ruby-2.2.4/gems/bundler-1.12.5/lib/bundler/cli.rb:11:in `start'
      /home/development/.rvm/gems/ruby-2.2.4/gems/bundler-1.12.5/exe/bundle:27:in `block in <top (required)>'
      /home/development/.rvm/gems/ruby-2.2.4/gems/bundler-1.12.5/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
      /home/development/.rvm/gems/ruby-2.2.4/gems/bundler-1.12.5/exe/bundle:19:in `<top (required)>'
      /home/development/.rvm/gems/ruby-2.2.4/bin/bundle:23:in `load'
      /home/development/.rvm/gems/ruby-2.2.4/bin/bundle:23:in `<main>'
      /home/development/.rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in `eval'
      /home/development/.rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in `<main>'

Environment
      
  Bundler   1.12.5
  Rubygems  2.4.8
  Ruby      2.2.4p230 (2015-12-16 revision 53155) [x86_64-linux]
  GEM_HOME  /home/development/.rvm/gems/ruby-2.2.4
  GEM_PATH  /home/development/.rvm/gems/ruby-2.2.4:/home/development/.rvm/gems/ruby-2.2.4@global
  RVM       1.27.0 (latest)
  Git       1.9.1
  rubygems-bundler (1.4.4)
      
      Bundler settings
      
  orig_path
    Set via BUNDLE_ORIG_PATH: "/home/development/.rvm/gems/ruby-2.2.4/bin:/home/development/.rvm/gems/ruby-2.2.4@global/bin:/home/development/.rvm/rubies/ruby-2.2.4/bin:/home/development/.rvm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
  orig_gem_path
    Set via BUNDLE_ORIG_GEM_PATH: "/home/development/.rvm/gems/ruby-2.2.4:/home/development/.rvm/gems/ruby-2.2.4@global"
--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/bundler/bundler/search?q=bad+URI%28is+not+URI%3F%29%3A+http%3A%2F%2Fuser%3Apassword%40host%3Aport&type=Issues

If there aren't any reports for this error yet, please create copy and paste the report template above into a new issue. Don't forget to anonymize any private data! The new issue form is located at:
https://github.com/bundler/bundler/issues/new

**Comment by LynnCo** [comment]
@prashantravidarshan Github is parsing the gemfile contents as markdown headers, also the issue you created contains a lot of boilerplate

**Comment by LynnCo** [comment]
Closing this due to formatting issues and lack of user response

@prashantravidarshan feel free to follow up when you get the formatting cleaned up!
