### ISSUE TITLE
I've installed Ruby 2.3.1 and rails 5.0 . I'm able to run server on new applications but not on applications which are already existing in my system. I get the following error. 

### ISSUE THREAD

**Issue by vasudhar** [bundler/bundler#4748]
What did you do?

  I ran the command `/Users/vasu/.rvm/gems/ruby-2.2.2@surveil/bin/bundle install`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what actually happened was...

Error details

    Errno::ENOTSUP: Operation not supported @ dir_s_mkdir - /home/lmcoutcomes
      /Users/vasu/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/fileutils.rb:252:in `mkdir'
      /Users/vasu/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/fileutils.rb:252:in `fu_mkdir'
      /Users/vasu/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/fileutils.rb:226:in `block (2 levels) in mkdir_p'
      /Users/vasu/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/fileutils.rb:224:in `reverse_each'
      /Users/vasu/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/fileutils.rb:224:in `block in mkdir_p'
      /Users/vasu/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/fileutils.rb:210:in `each'
      /Users/vasu/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/fileutils.rb:210:in `mkdir_p'
      /Users/vasu/.rvm/gems/ruby-2.2.2@surveil/gems/bundler-1.12.5/lib/bundler.rb:298:in `block in mkdir_p'
      /Users/vasu/.rvm/gems/ruby-2.2.2@surveil/gems/bundler-1.12.5/lib/bundler/shared_helpers.rb:105:in `filesystem_access'
      /Users/vasu/.rvm/gems/ruby-2.2.2@surveil/gems/bundler-1.12.5/lib/bundler.rb:297:in `mkdir_p'
      /Users/vasu/.rvm/gems/ruby-2.2.2@surveil/gems/bundler-1.12.5/lib/bundler/installer.rb:176:in `block in create_bundle_path'
      /Users/vasu/.rvm/gems/ruby-2.2.2@surveil/gems/bundler-1.12.5/lib/bundler/shared_helpers.rb:105:in `filesystem_access'
      /Users/vasu/.rvm/gems/ruby-2.2.2@surveil/gems/bundler-1.12.5/lib/bundler/installer.rb:175:in `create_bundle_path'
      /Users/vasu/.rvm/gems/ruby-2.2.2@surveil/gems/bundler-1.12.5/lib/bundler/installer.rb:58:in `run'
      /Users/vasu/.rvm/gems/ruby-2.2.2@surveil/gems/bundler-1.12.5/lib/bundler/installer.rb:22:in `install'
      /Users/vasu/.rvm/gems/ruby-2.2.2@surveil/gems/bundler-1.12.5/lib/bundler/cli/install.rb:102:in `run'
      /Users/vasu/.rvm/gems/ruby-2.2.2@surveil/gems/bundler-1.12.5/lib/bundler/cli.rb:175:in `install'
      /Users/vasu/.rvm/gems/ruby-2.2.2@surveil/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /Users/vasu/.rvm/gems/ruby-2.2.2@surveil/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /Users/vasu/.rvm/gems/ruby-2.2.2@surveil/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /Users/vasu/.rvm/gems/ruby-2.2.2@surveil/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /Users/vasu/.rvm/gems/ruby-2.2.2@surveil/gems/bundler-1.12.5/lib/bundler/cli.rb:11:in `start'
      /Users/vasu/.rvm/gems/ruby-2.2.2@surveil/gems/bundler-1.12.5/exe/bundle:27:in `block in <top (required)>'
      /Users/vasu/.rvm/gems/ruby-2.2.2@surveil/gems/bundler-1.12.5/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
      /Users/vasu/.rvm/gems/ruby-2.2.2@surveil/gems/bundler-1.12.5/exe/bundle:19:in `<top (required)>'
      /Users/vasu/.rvm/gems/ruby-2.2.2@surveil/bin/bundle:23:in `load'
      /Users/vasu/.rvm/gems/ruby-2.2.2@surveil/bin/bundle:23:in `<main>'
      /Users/vasu/.rvm/gems/ruby-2.2.2@surveil/bin/ruby_executable_hooks:15:in `eval'
      /Users/vasu/.rvm/gems/ruby-2.2.2@surveil/bin/ruby_executable_hooks:15:in `<main>'

Environment
      
  Bundler   1.12.5
  Rubygems  2.4.8
  Ruby      2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]
  GEM_HOME  /home/lmcoutcomes/www/shared/bundle/ruby/2.2.0
  GEM_PATH  
  RVM       1.27.0 (latest)
  Git       2.7.4 (Apple Git-66)
      
      Bundler settings
      
  frozen
    Set for your local app (/Users/vasu/Documents/Outcomes/.bundle/config): "1"
  path
    Set for your local app (/Users/vasu/Documents/Outcomes/.bundle/config): "/home/lmcoutcomes/www/shared/bundle"
  without
    Set for your local app (/Users/vasu/Documents/Outcomes/.bundle/config): "development:test"
  disable_shared_gems
    Set for your local app (/Users/vasu/Documents/Outcomes/.bundle/config): true
  orig_path
    Set via BUNDLE_ORIG_PATH: "/Users/vasu/.rvm/gems/ruby-2.2.2@surveil/bin:/Users/vasu/.rvm/gems/ruby-2.2.2@global/bin:/Users/vasu/.rvm/rubies/ruby-2.2.2/bin:/Users/vasu/.rvm/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin"
  orig_gem_path
    Set via BUNDLE_ORIG_GEM_PATH: "/Users/vasu/.rvm/gems/ruby-2.2.2@surveil:/Users/vasu/.rvm/gems/ruby-2.2.2@global"
--- TEMPLATE END ----------------------------------------------------------------

**Comment by LynnCo** [comment]
@vasudhar A similar error message is reported here https://github.com/bundler/bundler/issues/3990, see if anything in that thread resolves your issue?

**Comment by LynnCo** [comment]
Related to this, https://github.com/bundler/bundler/pull/4408 was about showing an error message for `Errno::ENOTSUP` but I'm not sure why that's not being displayed here

**Comment by LynnCo** [comment]
ping @vasudhar !

> A similar error message is reported here #3990, see if anything in that thread resolves your issue?
