### ISSUE TITLE
undefined method `destination' on an instance of Object

### ISSUE THREAD

**Issue by saizai** [bundler/bundler#4750]
I ran the command `/Users/saizai/.rvm/gems/rbx-3.41@global/bin/bundle update`

Error details

    NoMethodError: undefined method `destination' on an instance of Object.
      core/zed.rb:1368:in `destination (method_missing)'
      core/symbol.rb:151:in `to_proc'
      core/array.rb:93:in `map'
      /Users/saizai/.rvm/gems/rbx-3.41@global/gems/bundler-1.12.5/lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph.rb:232:in `successors'
      /Users/saizai/.rvm/gems/rbx-3.41@global/gems/bundler-1.12.5/lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph.rb:253:in `=='
      core/array.rb:445:in `=='
      core/thread.rb:382:in `detect_recursion'
      core/array.rb:433:in `=='
      core/struct.rb:127:in `=='
      core/thread.rb:382:in `detect_recursion'
      core/struct.rb:126:in `=='
      core/array.rb:643:in `delete'
      /Users/saizai/.rvm/gems/rbx-3.41@global/gems/bundler-1.12.5/lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph.rb:132:in `detach_vertex_named'
      core/array.rb:72:in `each'
      /Users/saizai/.rvm/gems/rbx-3.41@global/gems/bundler-1.12.5/lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph.rb:130:in `detach_vertex_named'
      /Users/saizai/.rvm/gems/rbx-3.41@global/gems/bundler-1.12.5/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:365:in `fixup_swapped_children'
      core/array.rb:72:in `each'
      /Users/saizai/.rvm/gems/rbx-3.41@global/gems/bundler-1.12.5/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:362:in `fixup_swapped_children'
      /Users/saizai/.rvm/gems/rbx-3.41@global/gems/bundler-1.12.5/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:352:in `attempt_to_swap_possibility'
      /Users/saizai/.rvm/gems/rbx-3.41@global/gems/bundler-1.12.5/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:333:in `attempt_to_activate_existing_spec'
      /Users/saizai/.rvm/gems/rbx-3.41@global/gems/bundler-1.12.5/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:318:in `attempt_to_activate'
      /Users/saizai/.rvm/gems/rbx-3.41@global/gems/bundler-1.12.5/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:147:in `process_topmost_state'
      /Users/saizai/.rvm/gems/rbx-3.41@global/gems/bundler-1.12.5/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:72:in `resolve'
      /Users/saizai/.rvm/gems/rbx-3.41@global/gems/bundler-1.12.5/lib/bundler/vendor/molinillo/lib/molinillo/resolver.rb:41:in `resolve'
      /Users/saizai/.rvm/gems/rbx-3.41@global/gems/bundler-1.12.5/lib/bundler/resolver.rb:201:in `start'
      /Users/saizai/.rvm/gems/rbx-3.41@global/gems/bundler-1.12.5/lib/bundler/resolver.rb:184:in `resolve'
      /Users/saizai/.rvm/gems/rbx-3.41@global/gems/bundler-1.12.5/lib/bundler/definition.rb:200:in `resolve'
      /Users/saizai/.rvm/gems/rbx-3.41@global/gems/bundler-1.12.5/lib/bundler/definition.rb:140:in `specs'
      /Users/saizai/.rvm/gems/rbx-3.41@global/gems/bundler-1.12.5/lib/bundler/definition.rb:129:in `resolve_remotely!'
      /Users/saizai/.rvm/gems/rbx-3.41@global/gems/bundler-1.12.5/lib/bundler/installer.rb:195:in `resolve_if_need'
      /Users/saizai/.rvm/gems/rbx-3.41@global/gems/bundler-1.12.5/lib/bundler/installer.rb:70:in `run'
      /Users/saizai/.rvm/gems/rbx-3.41@global/gems/bundler-1.12.5/lib/bundler/installer.rb:22:in `install'
      /Users/saizai/.rvm/gems/rbx-3.41@global/gems/bundler-1.12.5/lib/bundler/cli/update.rb:52:in `run'
      /Users/saizai/.rvm/gems/rbx-3.41@global/gems/bundler-1.12.5/lib/bundler/cli.rb:204:in `update'
      /Users/saizai/.rvm/gems/rbx-3.41@global/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /Users/saizai/.rvm/gems/rbx-3.41@global/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /Users/saizai/.rvm/gems/rbx-3.41@global/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /Users/saizai/.rvm/gems/rbx-3.41@global/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /Users/saizai/.rvm/gems/rbx-3.41@global/gems/bundler-1.12.5/lib/bundler/cli.rb:11:in `start'
      /Users/saizai/.rvm/gems/rbx-3.41@global/gems/bundler-1.12.5/exe/bundle:27:in `__script__'
      /Users/saizai/.rvm/gems/rbx-3.41@global/gems/bundler-1.12.5/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
      /Users/saizai/.rvm/gems/rbx-3.41@global/gems/bundler-1.12.5/exe/bundle:19:in `__script__'
      core/kernel.rb:577:in `load'
      /Users/saizai/.rvm/gems/rbx-3.41@global/bin/bundle:22:in `__script__'
      core/block_environment.rb:147:in `call_on_instance'
      core/kernel.rb:1135:in `eval'
      /Users/saizai/.rvm/gems/rbx-3.41/bin/ruby_executable_hooks:15:in `__script__'
      core/code_loader.rb:505:in `load_script'
      core/code_loader.rb:590:in `load_script'
      core/loader.rb:679:in `script'
      core/loader.rb:862:in `main'

Environment

```
  Bundler   1.12.5
  Rubygems  2.6.2
  Ruby      2.2.2p0 (2016-06-20 revision 0) [x86_64-darwin15.5.0]
  GEM_HOME  /Users/saizai/.rvm/gems/rbx-3.41
  GEM_PATH  /Users/saizai/.rvm/gems/rbx-3.41:/Users/saizai/.rvm/gems/rbx-3.41@global
  RVM       1.27.0 (latest)
  Git       2.6.3 (Apple Git-62)
  rubygems-bundler (1.4.4)
```

      Bundler settings

```
  build.nokogiri
    Set for your local app (/Users/saizai/Google Drive/myl_workspace_sai/MakeYourLaws/.bundle/config): "--use-system-libraries"
    Set for the current user (/Users/saizai/.bundle/config): "--use-system-libraries"
  build.fcgi
    Set for your local app (/Users/saizai/Google Drive/myl_workspace_sai/MakeYourLaws/.bundle/config): "--use-system-libraries"
    Set for the current user (/Users/saizai/.bundle/config): "--use-system-libraries"
  build.libv8
    Set for your local app (/Users/saizai/Google Drive/myl_workspace_sai/MakeYourLaws/.bundle/config): "--with-system-v8"
    Set for the current user (/Users/saizai/.bundle/config): "--with-system-v8"
  bin
    Set for your local app (/Users/saizai/Google Drive/myl_workspace_sai/MakeYourLaws/.bundle/config): "bin"
  orig_path
    Set via BUNDLE_ORIG_PATH: "/Users/saizai/.rvm/gems/rbx-3.41/bin:/Users/saizai/.rvm/gems/rbx-3.41@global/bin:/Users/saizai/.rvm/rubies/rbx-3.41/bin:/Users/saizai/.rvm/bin:/opt/local/bin:/opt/local/sbin:/usr/local/git/bin:/opt/local/bin:/opt/local/sbin:/Users/saizai/Dropbox/android/sdk/tools:/Users/saizai/Dropbox/android/sdk/platform-tools:/usr/local/mysql/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/MacGPG2/bin"
  orig_gem_path
    Set via BUNDLE_ORIG_GEM_PATH: "/Users/saizai/.rvm/gems/rbx-3.41:/Users/saizai/.rvm/gems/rbx-3.41@global"
```

**Comment by saizai** [comment]
See also https://github.com/rubinius/rubinius/issues/3678

**Comment by indirect** [comment]
Hi, thanks for reporting this error. According to the backtrace you provided, the error is occurring inside Rubinius—this doesn't seem to be a Bundler issue. I suggest you ask the Rubinius team about it, and let us know if they say it is somehow an issue with Bundler.

**Comment by saizai** [comment]
@indirect This issue is cross-referenced at the rubinius report above.

**Comment by brixen** [comment]
@indirect here is a gist of Bundler 1.12.3 showing a classic symptom of non-thread-safe Ruby code (an out-of-bounds Tuple access caused by unsynchronized concurrent access to a Hash in this case) https://gist.github.com/brixen/e3c68b51a1581e1f94f10fea5d7ba6fb

Any error running any code on Rubinius is going to include internal Rubinius code interleaved with application or library code. That is not dispositive of where a bug lies.

What I'm seeing on 1.12.5 is multiple threads accessing Digest functions, where Digest is an MRI C-ext. I have not yet successfully debugged this, but introducing a global C-ext lock with `-Xcapi.lock=yes` on Rubinius results in a deadlock. This could obviously be Rubinius, but it could also be Bundler not properly synchronizing concurrent access to a shared resource.

I think closing this bug is premature. Obviously there is an issue open on the Rubinius issue tracker, but it's at least quite likely, if not highly likely, that there are further latent concurrency bugs in Bundler given the recent increased use of threads (I'm seeing ~400 threads created by Bundler when fetching the index).

**Comment by indirect** [comment]
@brixen it's entirely possible that `Digest` is safe to use from multiple threads on MRI and JRuby but not safe to use from multiple threads on Rubinius. If that does turn out to be the case, I'm happy to accept a bug report (or a pull request) for synchronizing access to the `Digest` module when running in Rubinius.

**Comment by brixen** [comment]
@indirect if I understand correctly, you're saying it's up to Rubinius to ensure that Bundler uses thread-safe code. If true, that's an interesting perspective. In general, how do you decide what is thread-safe in Ruby when you are writing code?

From my perspective, there are very few things in Ruby that provide thread-safe guarantees. Queue comes to mind. Matz has explicitly said that classes like Array, Hash, etc would not provide thread-safety guarantees.

Very soon I'll have a mechanism in Rubinius that will show when a thread modifies an object it did not create. Perhaps this will help illuminate code that concurrently modifies shared state.

I don't think it's controversial (outside Ruby) to say that code that concurrently modifies shared state without synchronization is a bug. I'll hope that Ruby programmers agree.

**Comment by thedrow** [comment]
Not sure if it's relevant but JRuby does acquire a mutex when *loading* the Digest module.
https://github.com/jruby/jruby/commit/e29748aee32a8fdd89ae66b66eb10af59ab89df5

**Comment by saizai** [comment]
I've run `rvm upgrade rbx-3.47 rbx-3.51`, uninstalled previous bundler versions, and installed bundler version 1.11.2 per https://github.com/rubinius/rubinius/commit/b30a3aeb678845a3bb39d42539e917caf8f9c870

After doing so, bundle update runs successfully.

I tried running bundler verison 1.13.0.rc.1 on rbx 3.51 before uninstalling it and downgrading to 1.11.2, and that crashed the same as in my original report on this thread. 

So it seems that the downgrade is required at least for now.

I have no idea about the concurrency / thread locking issues discussed above, nor whether it's rubinius or bundler that's buggy, and don't want to get involved in that. 

Just letting y'all know that it does work with rbx 3.51 and bundler 1.11.2 on my system. Since it fixes things for now, my thanks to @brixen. ;-)
