### ISSUE TITLE
The show command could be a lot better

### ISSUE THREAD

**Issue by indirect** [bundler/bundler#4754]
This is the help for the `bundle show` command:

```
$ bundle show --help
Usage:
  bundle show GEM [OPTIONS]

Options:
      [--paths=List the paths of all gems that are required by your gems.rb.], [--no-paths]   
      [--outdated=Show verbose output including whether gems are outdated.], [--no-outdated]  
      [--no-color], [--no-no-color]                                                           # Disable colorization in output
  -r, [--retry=NUM]                                                                           # Specify the number of times you wish to attempt network commands
  -V, [--verbose], [--no-verbose]                                                             # Enable verbose output mode

Description:
  Show lists the names and versions of all gems that are required by your gems.rb. Calling show with [GEM] will list the exact location of that gem on your machine.
```

We don't actually have `--no-paths`, `--no-outdated`, or `--no-verbose` options, so we should remove those if Thor will let us. Showing `--no-color` and `--no-no-color` is... pretty silly. Let's change that to (if we must) `--color` and `--no-color`, or better yet only `--no-color`.

Right now `bundle show` lists gem names, while `bundle show --paths` or `bundle show NAME` shows the paths to gems. Then, confusingly, `bundle show --outdated` shows detailed information including summaries, websites, and whether a gem is up to date or not. We'll probably want to keep the `bundle show --paths` and `bundle show NAME` commands around for the entire 2.x cycle so that tools will work with both Bundler 1 and Bundler 2, but we can make the user-facing commands better for sure.

Let's move `bundle show` to `bundle list` (with an alias of `bundle ls`). That seems to make sense, and gets us firmly into shared territory with `npm list`/`npm ls`.

Let's move `bundle show --outdated` to `bundle info NAME`, and completely remove the `--outdated` option. We already have an outdated command. (Both `brew` and `npm` use `info`. This seems like the right name.) T `bundle info` command without a gem name can either throw an error or print out bundle statistics, like number of Gemfile gems, total number of gems, and maybe... size of the bundle in MB? Sounds nice.

We can also add a `bundle info --path NAME` option to print out the path to a single gem. Later, when Bundler 1.x usage has dropped down to nearly nothing, we can deprecate `bundle show NAME` in favor of `bundle info --path NAME`.

**Comment by segiddins** [comment]
@indirect there was a PR to fix the -no-no-color thing months ago that never got your r+

**Comment by indirect** [comment]
@segiddins that PR has no listed green builds on Travis, is no longer mergable, and the proposer has abandoned it. As I mentioned on the ticket, though, I'm happy for anyone to r+ a mergable version of it with passing specs.

**Comment by borsothy** [comment]
Hey guys! I'm a newcomer to Bundler in terms of contributing. Is that okay if I pick this up?

**Comment by chrismo** [comment]
@borsothy i selfishly would love some assistance on some of the checklist items attached to this issue => https://github.com/bundler/bundler-features/issues/122, though they may be less suited to you if you want something lighter. :)

**Comment by borsothy** [comment]
@chrismo sure, let's see what I can do for you. Heading over to that conversation.

**Comment by borsothy** [comment]
@chrismo can I change my mind? :D I'm not sure I'm prepared for those issues. Not Rubywise, but I have no idea about the Bundler codebase so far :|

**Comment by chrismo** [comment]
oh, absolutely. your time is yours, however you want to contribute is fine by me 😄.  I just wanted to throw those out as something of a higher personal priority in case there was any overlap of interests.

**Comment by lynnco** [comment]
This is being partially addressed by https://github.com/bundler/bundler/pull/5093

**Comment by segiddins** [comment]
@indirect now that we have `bundle info`, should this be closed?

**Comment by segiddins** [comment]
@indirect ping?

**Comment by indirect** [comment]
@segiddins seems like, yeah.
