### ISSUE TITLE
bundle exec temporarily allows access to gems outside of bundle

### ISSUE THREAD

**Issue by mvz** [bundler/bundler#4758]
Short version: Given an installed gem `foo`, running `bundle exec ruby -rfoo -e 'puts "hello"'` will load `foo` even if it's not part of the bundle.

Concretely, I'm encountering issues with this when
- I have `json` 2.0.1 installed
- I have `simplecov` and `json` 1.8 in the bundle
- I have the option `-rsimplecov` in my rspec task
- I run `bundle exec rake`
  The result seems to be that simplecov is loaded before the bundle is activated on the nested execution of ruby, and I get the error:
  `You have already activated json 2.0.1, but your Gemfile requires json 1.8.3. Prepending`bundle exec`to your command may solve this. (Gem::LoadError)`
## Steps to reproduce the problem:
- Install json 2.0.1
- In an empty directory, create a `Gemfile` with the following contents:

```
source 'https://rubygems.org'

gem 'rake',  '~> 11.1'
gem 'rspec', '~> 3.0'
gem 'json',  '~> 1.8'
```
- Also, create a `Rakefile` with the following contents:

```
require 'rspec/core/rake_task'

RSpec::Core::RakeTask.new('spec') do |t|
  t.ruby_opts = ['-rjson -Ilib -w']
end

task default: :spec
```
- Run `bundle exec rake`
### What I expect to happen

RSpec runs and succeeds with 0 examples run.
### What actually happens

I get the following output:

```
/home/matijs/.rbenv/versions/2.3.1/bin/ruby -rjson -Ilib -w -I/home/matijs/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib:/home/matijs/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-support-3.4.1/lib /home/matijs/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb
/home/matijs/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:35:in `block in setup': You have already activated json 2.0.1, but your Gemfile requires json 1.8.3. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)
    from /home/matijs/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:20:in `map'
    from /home/matijs/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:20:in `setup'
    from /home/matijs/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler.rb:95:in `setup'
    from /home/matijs/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/setup.rb:9:in `<top (required)>'
    from /home/matijs/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /home/matijs/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/home/matijs/.rbenv/versions/2.3.1/bin/ruby -rjson -Ilib -w -I/home/matijs/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib:/home/matijs/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-support-3.4.1/lib /home/matijs/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb failed
```

**Comment by indirect** [comment]
@mvz I _think_ (although I am not sure) that this is because RSpec's rake task also `exec`s out to another Ruby process, temporarily freeing Ruby from Bundler long enough for it to load the wrong JSON version. Can you try running `bundle exec ruby -rjson -Ilib -w -S rspec` and show us the results?

**Comment by segiddins** [comment]
@indirect that shouldn't happen, since we ensure that the `-rbundler/setup` is the first thing in `RUBYOPT`, so unless the rake task is prepending to RUBYOPT after we've setup the bundler env, this could be a bug on our end

**Comment by mvz** [comment]
@indirect yes, `bundle exec ruby -rjson -Ilib -w -S rspec` gives the same error:

```
[matijs@bean] bundle exec ruby -rjson -Ilib -w -S rspec
/home/matijs/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:35:in `block in setup': You have already activated json 2.0.1, but your Gemfile requires json 1.8.3. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)
	from /home/matijs/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:20:in `map'
	from /home/matijs/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:20:in `setup'
	from /home/matijs/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler.rb:95:in `setup'
	from /home/matijs/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/setup.rb:9:in `<top (required)>'
	from /home/matijs/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/matijs/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
```

**Comment by soutaro** [comment]
@mvz @segiddins I don't think this is a *bug* of Bundler. This is because `ruby` load libraries given through `-r` command line option before `-r` libs in `RUBYOPT`.

https://bugs.ruby-lang.org/issues/5445

Adding explicitly `-rbundler/setup` in command line seems reasonable workaround for this to me.

**Comment by segiddins** [comment]
What @soutaro posted above agrees 100% with my assessment of the issue as well
