### ISSUE TITLE
Unfortunately, an unexpected error occurred, and Bundler cannot continue.

### ISSUE THREAD

**Issue by PaulcyMboungou** [bundler/bundler#4759]
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `/home/paulcy/.rvm/gems/ruby-2.3.0/bin/bundle install`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what actually happened was...

Error details

    Errno::EACCES: Permission denied @ dir_s_mkdir - /home/paulcy/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/versions20160706-9655-1i7uqnr
      /home/paulcy/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tmpdir.rb:86:in `mkdir'
      /home/paulcy/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tmpdir.rb:86:in `block in mktmpdir'
      /home/paulcy/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tmpdir.rb:130:in `create'
      /home/paulcy/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tmpdir.rb:86:in `mktmpdir'
      /home/paulcy/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:29:in `update'
      /home/paulcy/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:64:in `update'
      /home/paulcy/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:55:in `update_and_parse_checksums!'
      /home/paulcy/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/fetcher/compact_index.rb:65:in `available?'
      /home/paulcy/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/fetcher/compact_index.rb:15:in `call'
      /home/paulcy/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/fetcher/compact_index.rb:15:in `block in compact_index_request'
      /home/paulcy/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/fetcher.rb:154:in `use_api'
      /home/paulcy/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:331:in `block in api_fetchers'
      /home/paulcy/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:331:in `select'
      /home/paulcy/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:331:in `api_fetchers'
      /home/paulcy/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:336:in `block in remote_specs'
      /home/paulcy/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/index.rb:10:in `build'
      /home/paulcy/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:335:in `remote_specs'
      /home/paulcy/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:82:in `specs'
      /home/paulcy/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/definition.rb:211:in `block (2 levels) in index'
      /home/paulcy/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/definition.rb:209:in `each'
      /home/paulcy/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/definition.rb:209:in `block in index'
      /home/paulcy/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/index.rb:10:in `build'
      /home/paulcy/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/definition.rb:206:in `index'
      /home/paulcy/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/definition.rb:200:in `resolve'
      /home/paulcy/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/definition.rb:140:in `specs'
      /home/paulcy/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/definition.rb:129:in `resolve_remotely!'
      /home/paulcy/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/installer.rb:195:in `resolve_if_need'
      /home/paulcy/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/installer.rb:70:in `run'
      /home/paulcy/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/installer.rb:22:in `install'
      /home/paulcy/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/cli/install.rb:102:in `run'
      /home/paulcy/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/cli.rb:175:in `install'
      /home/paulcy/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /home/paulcy/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /home/paulcy/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /home/paulcy/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /home/paulcy/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/cli.rb:11:in `start'
      /home/paulcy/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/exe/bundle:27:in `block in <top (required)>'
      /home/paulcy/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
      /home/paulcy/.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/exe/bundle:19:in `<top (required)>'
      /home/paulcy/.rvm/gems/ruby-2.3.0/bin/bundle:23:in `load'
      /home/paulcy/.rvm/gems/ruby-2.3.0/bin/bundle:23:in `<main>'
      /home/paulcy/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
      /home/paulcy/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'

Environment
      
  Bundler   1.12.5
  Rubygems  2.5.1
  Ruby      2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]
  GEM_HOME  /home/paulcy/.rvm/gems/ruby-2.3.0
  GEM_PATH  /home/paulcy/.rvm/gems/ruby-2.3.0:/home/paulcy/.rvm/gems/ruby-2.3.0@global
  RVM       1.27.0 (latest)
  Git       2.9.0
  rubygems-bundler (1.4.4)
      
      Bundler settings
      
  orig_path
    Set via BUNDLE_ORIG_PATH: "/home/paulcy/.rvm/gems/ruby-2.3.0/bin:/home/paulcy/.rvm/gems/ruby-2.3.0@global/bin:/home/paulcy/.rvm/rubies/ruby-2.3.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/paulcy/.rvm/bin"
  orig_gem_path
    Set via BUNDLE_ORIG_GEM_PATH: "/home/paulcy/.rvm/gems/ruby-2.3.0:/home/paulcy/.rvm/gems/ruby-2.3.0@global"
--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/bundler/bundler/search?q=Permission+denied+%40+dir_s_mkdir+-+%2Fhome%2Fpaulcy%2F.bundle%2Fcache%2Fcompact_index%2Frubygems.org.443.29b0360b937aa4d161703e6160654e47%2Fversions20160706-9655-1i7uqnr&type=Issues

If there aren't any reports for this error yet, please create copy and paste the report template above into a new issue. Don't forget to anonymize any private data! The new issue form is located at:
https://github.com/bundler/bundler/issues/new

**Comment by LynnCo** [comment]
@PaulcyMboungou check out how the other issues with [permission errors](https://github.com/bundler/bundler/search?q=Permission+denied&type=Issues&utf8=%E2%9C%93) were resolved, like https://github.com/bundler/bundler/issues/4458, https://github.com/bundler/bundler/issues/4431, https://github.com/bundler/bundler/issues/4429

Also try searching the Bundler repo for that error message https://github.com/bundler/bundler/search?q=Permission+denied+%40+dir_s_mkdir&type=Issues&utf8=%E2%9C%93 (the search link in the issue template isn't that great)
