### ISSUE TITLE
Problem with Bundle install

### ISSUE THREAD

**Issue by Nidhjin** [bundler/bundler#4760]
Hi everyone,

I am new on Linux but I try to install this application on Mint 17.3 :
FabManager is a Ruby on Rails / AngularJS web application that runs on the following software:
    Ubuntu/Debian
    Ruby 2.3
    Git 1.9.1+
    Redis 2.8.4+
    Sidekiq 3.3.4+
    Elasticsearch 1.7
    PostgreSQL 9.4

I am almost done, but I have this last trouble and I can't fix it by myself despite all my tries and researches ! So frustrated, so I came here to claim some help ! Thanks in advance for helps !

Everything is ok or troubleshooted until step 5. Install bundler in the current RVM gemset

> fablab@fablab-OptiPlex-330 ~/fab-manager $ gem install bundler

> 
> _Successfully installed bundler-1.12.5
> Parsing documentation for bundler-1.12.5
> Done installing documentation for bundler after 6 seconds
> 1 gem installed_

But then, step 6. Install the required ruby gems, I got a "Permission denied" (**see full error below*** **), and if I do it in SUDO most of gems are fine but for some of them, I got this : 

> _Installing test_after_commit 1.0.0
> Gem::InstallError: test_after_commit requires Ruby version >= 2.0.0.
> An error occurred while installing test_after_commit (1.0.0), and Bundler cannot
> continue.
> Make sure that `gem install test_after_commit -v '1.0.0'` succeeds before
> bundling._

So, I tried this :

>  fablab@fablab-OptiPlex-330 ~/fab-manager $ sudo gem install test_after_commit -v '1.0.0'
> _ERROR:  Error installing test_after_commit:
> test_after_commit requires Ruby version >= 2.0.0_
> 

So I checked :

> 
>  fablab@fablab-OptiPlex-330 ~/fab-manager $ ruby -v
> _ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]_

*** (Here is the full Permission error)
> fablab@fablab-OptiPlex-330 ~/fab-manager $ bundle install

> 
> _--- ERROR REPORT TEMPLATE -------------------------------------------------------
> ...
> Error details
> 
>     Errno::EACCES: Permission denied @ dir_s_mkdir - /home/fablab/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/versions20160706-4246-u5y30x
>       /home/fablab/.rbenv/versions/2.3.0/lib/ruby/2.3.0/tmpdir.rb:86:in `mkdir'
>       /home/fablab/.rbenv/versions/2.3.0/lib/ruby/2.3.0/tmpdir.rb:86:in `block in mktmpdir'
>       /home/fablab/.rbenv/versions/2.3.0/lib/ruby/2.3.0/tmpdir.rb:130:in `create'
>       /home/fablab/.rbenv/versions/2.3.0/lib/ruby/2.3.0/tmpdir.rb:86:in `mktmpdir'
>       /home/fablab/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:29:in `update'
>       /home/fablab/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:64:in `update'
>       /home/fablab/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:55:in `update_and_parse_checksums!'
>       /home/fablab/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/fetcher/compact_index.rb:65:in `available?'
>       /home/fablab/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/fetcher/compact_index.rb:15:in `call'
>       /home/fablab/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/fetcher/compact_index.rb:15:in `block in compact_index_request'
>       /home/fablab/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/fetcher.rb:154:in `use_api'
>       /home/fablab/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:331:in `block in api_fetchers'
>       /home/fablab/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:331:in `select'
>       /home/fablab/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:331:in `api_fetchers'
>       /home/fablab/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:336:in `block in remote_specs'
>       /home/fablab/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/index.rb:10:in `build'
>       /home/fablab/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:335:in `remote_specs'
>       /home/fablab/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:82:in `specs'
>       /home/fablab/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/definition.rb:211:in `block (2 levels) in index'
>       /home/fablab/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/definition.rb:209:in `each'
>       /home/fablab/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/definition.rb:209:in `block in index'
>       /home/fablab/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/index.rb:10:in `build'
>       /home/fablab/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/definition.rb:206:in `index'
>       /home/fablab/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/definition.rb:200:in `resolve'
>       /home/fablab/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/definition.rb:140:in `specs'
>       /home/fablab/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/definition.rb:129:in `resolve_remotely!'
>       /home/fablab/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/installer.rb:195:in `resolve_if_need'
>       /home/fablab/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/installer.rb:70:in `run'
>       /home/fablab/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/installer.rb:22:in `install'
>       /home/fablab/.rbenv/rbenv.d/exec/gem-rehash/rubygems_plugin.rb:27:in `install'
>       /home/fablab/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli/install.rb:102:in `run'
>       /home/fablab/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli.rb:175:in `install'
>       /home/fablab/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
>       /home/fablab/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
>       /home/fablab/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
>       /home/fablab/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
>       /home/fablab/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli.rb:11:in `start'
>       /home/fablab/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/exe/bundle:27:in `block in <top (required)>'
>       /home/fablab/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
>       /home/fablab/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/exe/bundle:19:in `<top (required)>'
>       /home/fablab/.rbenv/versions/2.3.0/bin/bundle:23:in `load'
>       /home/fablab/.rbenv/versions/2.3.0/bin/bundle:23:in `<main>'
> 
> **Environment
>       
>   Bundler   1.12.5
>   Rubygems  2.5.1
>   Ruby      2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]
>   GEM_HOME  /home/fablab/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0
>   GEM_PATH  /home/fablab/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0:/home/fablab/.gem/ruby/2.3.0
>   Git       1.9.1**
>       
>       Bundler settings
>       
>   orig_path
>     Set via BUNDLE_ORIG_PATH: "/home/fablab/.rbenv/versions/2.3.0/bin:/home/fablab/.rbenv/libexec:/home/fablab/.rbenv/plugins/ruby-build/bin:/home/fablab/.rbenv/shims:/home/fablab/.rbenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/fablab/.rvm/bin:/home/fablab/.rvm/bin"
> --- TEMPLATE END ----------------------------------------------------------------_

**Comment by LynnCo** [comment]
Can you check out the resolution of some of the other [permissions errors](https://github.com/bundler/bundler/search?utf8=%E2%9C%93&q=Errno+EACCES+Permission+denied+%40+dir_s_mkdir&type=Issues)?

**Comment by LynnCo** [comment]
@Nidhjin Can you check out the resolution of some of the other permissions errors?

**Comment by Nidhjin** [comment]
Thanks for your answer. Yes sure I will do it again with a little more focus :)

**Comment by LynnCo** [comment]
@Nidhjin here's the search I usually use! https://github.com/bundler/bundler/search?q=Errno+EACCES+Permission+denied+%40+dir_s_mkdir&type=Issues&utf8=%E2%9C%93

**Comment by RochesterinNYC** [comment]
Closing as I think there's enough context in the other issues that show up in @LynnCo's recommended search to alleviate this issue. Please let us know if this isn't the case.
