### ISSUE TITLE
Not grabbing old version of Rack for old Ruby versions

### ISSUE THREAD

**Issue by ReinAkane** [bundler/bundler#4761]
Rack 2.0.1 was recently released (after 1.6.4) and 2.0.1 requires Ruby 2.2.2 or newer. Now when I do a bundle install that includes a gem dependent on rack with no version requirements, bundler will try to install 2.0.1 even though I have specified Ruby 1.9.3 in my Gemfile (and am running 1.9.3). My understanding was that bundler handled these situations.

Workaround is to specify a rack version in my Gemfile.

**Comment by segiddins** [comment]
@ReinAkane what version of bundler are you using? This was something we _tried_ to include (in 1.11 if I recall), but there were bugs in the implementation (and some may still exist), and properly resolving requires both using the "new" bundler index supported by 1.12 + and specify a `ruby` requirement in your Gemfile. If you share the output of `bundle env`, we'd be happy to look into it!

**Comment by ReinAkane** [comment]
@segiddins Here's the bundle env output of a larger Gemfile that causes the issue (and worked fine before the new rack version). http://pastebin.com/mga4iw60

Here's the bundle env of a smaller Gemfile that still causes the issue (only requiring rack): http://pastebin.com/Bn9bmTUn

And another one that only requires Capybara (also demonstrates that this isn't purely a rack issue, as it fails on mime-types-data with a similar error): http://pastebin.com/C9D2edki

Thanks

**Comment by segiddins** [comment]
Awesome, thanks for the great bug report! So I _think_ this is what https://github.com/bundler/bundler/pull/4650 is trying to address, but I'll have to double check later

**Comment by segiddins** [comment]
This should either be fixed in 1.13.1 (if you have a `ruby` declared in your Gemfile) or on master otherwise

**Comment by segiddins** [comment]
Should be fixed in 1.13 or 1.14.
