### ISSUE TITLE
Writing `.bundle/config` to project without warnings leads to cryptic errors

### ISSUE THREAD

**Issue by goneflyin** [bundler/bundler#4762]
I discovered this as a result of working on a Rails project with docker that mapped the local project directory to the docker container. 

Using `bundle install --path /gems` or even `bundle check --path /gems` would result in the writing of the `.bundler/config` file:
```
---
BUNDLE_PATH: "/gems"
BUNDLE_DISABLE_SHARED_GEMS: true
```
Because this same directory is used locally as well as within docker, but with different paths, this became confusing because running bundler in the project (where the `.bundle/config` file was written while I was unawares) would lead to a very cryptic error:
```
~/d/w/i/ib git:master ❯❯❯ bundle exec pry
Could not find rake-10.1.1 in any of the sources
Run `bundle install` to install missing gems.
```
I realize the writing of the `.bundle/config` file is a "feature, not a bug" -- but it isn't clear what's happening from the above error. I would recommend possibly including a warning that `BUNDLE_PATH` is set locally in `.bundle/config` if bundle itself fails to run due to missing gems, perhaps?

**Comment by indirect** [comment]
It is definitely confusing that options passed to install are remembered later. Bundler 2.0 (in development in the `2-0-dev` branch) has already removed automatic saving of command flags.

In the meantime, when you run `bundle config`, it will show you where every setting is located.

**Comment by goneflyin** [comment]
Fair enough! I was "unexcited" about the unexpected side effect of modifying my environment when running a command that's purely a status query (`bundle check`) -- I'm really glad to hear that the automatic generation of the `.config` is on the table to be removed in the upcoming major release.

Thanks much!
