### ISSUE TITLE
`bundle` automatically upgrades dependencies for git/github sources

### ISSUE THREAD

**Issue by jbodah** [bundler/bundler#4767]
Noticed an issue (or what I think is an issue) with bundler 1.12.5 where `bundle` was updating git/github-sourced gems. I built a sample repo here for reproducing the problem: https://github.com/jbodah/bundler_issue

## Basic outline:

1. `git`/`github`-source gems using a `tag`
2. `bundle` so your `Gemfile.lock` is generated
3. Remove `tag`s
4. Running `bundle` again will erroneously update the gems in your `Gemfile.lock`

**Comment by segiddins** [comment]
@jbodah I think this is actually the intended behavior -- since the source for the dependency has changed, bundler will go ahead and allow it to be updated

**Comment by jbodah** [comment]
I see, thanks for the response
