### ISSUE TITLE
Configured mirror could failover to the upstream source

### ISSUE THREAD

**Issue by kevintpeng** [bundler/bundler#4769]
I configured a mirror for rubygems.org. I noticed that if I turn my mirror off midway through a `bundle install`, I receive the error, `Could not fetch specs from https://mymirror.com/`. Is it possible to apply a fallback timeout to every request? Something similar to: `bundle config mirror.https://rubygems.org.fallback_timeout 3`

There might be a good reason why this isn't a thing. If so, I'd be interested in hearing why!

**Comment by segiddins** [comment]
Bundler already has `bundle config mirror.all.fallback_timeout`, does that not work for what you want?

**Comment by kevintpeng** [comment]
I guess I was wondering if it was possible to automatically start re-routing requests from the mirror to the upstream, upon the condition that the mirror starts failing. Though thinking back, it might not be reasonable since it could produce unexpected results.

**Comment by indirect** [comment]
I think I'm going to rule that we would like to use the same server for the entire install process—mirrors aren't guaranteed to have their state synced with the upstream server, and so suddenly switching from one to the other could indeed produce unexpected results. Please use the `fallback_timeout` setting to determine how quickly Bundler will switch from trying the mirror to the upstream at the start of a command. 👍
