### ISSUE TITLE
Permissions errors generate a search URL with the user's local paths

### ISSUE THREAD

**Issue by LynnCo** [bundler/bundler#4771]
As displayed by https://github.com/bundler/bundler/issues/4429, https://github.com/bundler/bundler/issues/4429, https://github.com/bundler/bundler/issues/4458 the error message for `Errno::EACCES: Permission denied @ rb_sysopen` often includes the users local directory on the first line (ex `/Users/username/.bundle/...`). This means that [the search url](https://github.com/bundler/bundler/blob/196594bb6992e01ee4654b970f486a37bf0e78fa/lib/bundler/friendly_errors.rb#93) won't return any results. Fixing this either by

* splitting that line on the `-`, or
* moving the user path to the second line of the error message

Would likely save a few users worth of issues.

(side note: I also made another issue https://github.com/bundler/bundler/issues/4647 about this type of error, but this one is simpler)

**Comment by LynnCo** [comment]
A related issue is that github isn't parsing the `:` as plain text, so `Errno::EACCES: Permission denied @ rb_sysopen` gets a lot few results than `Errno EACCES Permission denied @ rb_sysopen` ([with](https://github.com/bundler/bundler/search?utf8=%E2%9C%93&q=Errno%3A%3AEACCES%3A+Permission+denied+%40+dir_s_mkdir&type=Issues) vs [without](https://github.com/bundler/bundler/search?utf8=%E2%9C%93&q=Errno+EACCES++Permission+denied+%40+dir_s_mkdir&type=Issues)). So this change would also likely want to include striping `:` from the url

**Comment by allenzhao** [comment]
I will work on this
:)
