### ISSUE TITLE
Add warning to bundle update when an unlocked gem doesn't move

### ISSUE THREAD

**Issue by chrismo** [bundler/bundler#4774]
...possibly w/ a reason why? The lack of feedback otherwise can be disconcerting, like "did I not do it right?" (The gem may not be able to move due to constraining requirements).

Task spawned from #4676

**Comment by RochesterinNYC** [comment]
Related/similar to #4514

**Comment by chrismo** [comment]
Discussion in https://github.com/bundler/bundler-features/issues/122 ... better than a warning perhaps is attempt a new resolution unlocking dependent gems ... though that could get out of hand. Do we just unlock direct dependencies? Then another layer after that if it doesn't work? That sort of smarts, to root out exactly which gem is holding up the show would be cool, but ... ROI may be low.

**Comment by greysteil** [comment]
This was fixed by https://github.com/bundler/bundler/pull/5904 and can be closed.

@chrismo - I'm about to implement that for Dependabot. Depending how clean it is, we could port it into Bundler later.
