### ISSUE TITLE
Add a --dry-run option to installer (available to bundle install and bundle update)

### ISSUE THREAD

**Issue by chrismo** [bundler/bundler#4776]
Task spawned from #4676

This was initially considered as part of the conservative update work, but the best place to output the text appears to be in the Installer class itself, which would then open this up for bundle install and bundle update.

With outdated and issue #4772, perhaps this flag would be redundant.

**Comment by chrismo** [comment]
re: #4912 - bundle lock is more-or-less a dry-run option ... maybe close this?

**Comment by segiddins** [comment]
Sure 👍🏻
