### ISSUE TITLE
bundler assumes ~/.bundle to be at /.bundle when $HOME is foul

### ISSUE THREAD

**Issue by schnittchen** [bundler/bundler#4778]
This happened to me today:

```
vagrant@vagrant:~$ HOME=foo bundle config --global path value
There was an error while trying to write to `/.bundle/config`. It is likely that you need to grant write permissions for that path.
```

I'd say that touching `/.bundle` is probably never a good idea, unless HOME actually is `/`.

**Comment by schnittchen** [comment]
I even had a situation where bundler happily created /.bundle/config without error, because during provisioning of a vagrant machine as root, then using sudo, somehow privileges for writing to `/` were not properly dropped. Took me hours to figure out this was happening.

**Comment by segiddins** [comment]
Hmm, it seems like maybe we could just raise an exception when `Dir.home` isn't writable by the current user?

**Comment by schnittchen** [comment]
Sounds reasonable to me.

**Comment by allenzhao** [comment]
I'll work on this
@segiddins When should be proper to check the `Dir.home`?  Right before writing to it?

**Comment by segiddins** [comment]
@allenzhao honestly, on start up might be the best place? otherwise in all of the places that expand based on `~`, centralized in a `SharedHelpers` method?
