### ISSUE TITLE
Bundler stopped working randomly.

### ISSUE THREAD

**Issue by fergyfresh** [bundler/bundler#4789]
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `/home/ferg/.rbenv/versions/2.3.1/bin/rake `

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what actually happened was...

Error details

    NoMethodError: undefined method `take_while' for nil:NilClass
      /home/ferg/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:69:in `rescue in kernel_load'
      /home/ferg/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:57:in `kernel_load'
      /home/ferg/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:24:in `run'
      /home/ferg/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli.rb:304:in `exec'
      /home/ferg/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /home/ferg/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /home/ferg/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /home/ferg/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /home/ferg/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli.rb:11:in `start'
      /home/ferg/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/exe/bundle:27:in `block in <top (required)>'
      /home/ferg/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
      /home/ferg/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/exe/bundle:19:in `<top (required)>'
      /home/ferg/.rbenv/versions/2.3.1/bin/bundle:23:in `load'
      /home/ferg/.rbenv/versions/2.3.1/bin/bundle:23:in `<main>'

Environment
      
  Bundler   1.12.5
  Rubygems  2.5.1
  Ruby      2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
  GEM_HOME  /home/ferg/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0
  GEM_PATH  /home/ferg/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0:/home/ferg/.gem/ruby/2.3.0
  Git       1.9.1
      
      Bundler settings
      
  orig_path
    Set via BUNDLE_ORIG_PATH: "/home/ferg/.rbenv/versions/2.3.1/bin:/home/ferg/.rbenv/libexec:/home/ferg/.rbenv/plugins/ruby-build/bin:/home/ferg/.rbenv/plugins/ruby-build/bin:/home/ferg/.rbenv/shims:/home/ferg/.rbenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
  bin_path
    Set via BUNDLE_BIN_PATH: "/home/ferg/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/exe/bundle"
  gemfile
    Set via BUNDLE_GEMFILE: "/home/ferg/carpool/Gemfile"
--- TEMPLATE END ----------------------------------------------------------------

**Comment by fergyfresh** [comment]
Reinstalling everything fixed my problem. I didn't mess with any part of the ruby/rails install though.

**Comment by segiddins** [comment]
Can you run it again with `DEBUG=1`? I'm wondering if something is being raised without a backtrace

**Comment by fergyfresh** [comment]
Sorry I gave up and reinstalled. Issue is gone. Can close issue.
