### ISSUE TITLE
Code of Conduct - styling on page to include margins for readability.

### ISSUE THREAD

**Issue by gusseting** [bundler/bundler#4794]
The Code of Conduct page: http://bundler.io/conduct.html is currently without margins (at least, on a mac on chrome + firefox). It would be great to have this page conform to the rest of the site (eg blog: http://bundler.io/blog/, docs: http://bundler.io/docs.html) and be more readable.

**Comment by LynnCo** [comment]
@gusseting Thanks for reporting! This is the repo for the client side Bundler code though, would you mind making this same issue on the repo for the website? https://github.com/bundler/bundler-site/issues

**Comment by gusseting** [comment]
@LynnCo thanks so much for pointing that out! I've created a new issue, which is being acted on:
https://github.com/bundler/bundler-site/issues/227 so closing this one.
