### ISSUE TITLE
Bundler 1.12.0.pre.2 and newer sets "bundle" as the process's command name

### ISSUE THREAD

**Issue by dgutov** [bundler/bundler#4797]
For example, save this as `test.rb`:

``` rb
#!/usr/bin/env ruby

puts File.read("/proc/#{Process.pid}/comm")
```

Then run:

``` sh
chmod +x test.rb
bundle exec ./test.rb
```

1.12.0.pre.2 and newer outputs `bundle`. 1.12.0.pre.1 and all previous versions (or at least all of them after 1.6.2) output `ruby` there.

Not sure how serious this is, but it broke some monitoring code written by our sysadmins.

**Comment by indirect** [comment]
Thanks for reporting this! We have a fix in the works over at #4589.

**Comment by JuanitoFatas** [comment]
Does #4863 solve this?

**Comment by dgutov** [comment]
@JuanitoFatas Doesn't look like it. Is `1.13.0.rc.2` supposed to contain the fix?

```sh
$ ruby --version
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]
$ bundle --version
Bundler version 1.13.0.rc.2
$ bundle exec ./test.rb
bundle
```

**Comment by segiddins** [comment]
I get an ENOENT when trying to read from `/proc/pid/comm`

**Comment by dgutov** [comment]
@segiddins What's your OS? Try GNU/Linux.

**Comment by segiddins** [comment]
I only have OS X locally

**Comment by dgutov** [comment]
I sure hope that doesn't mean Bundler is only officially supported there.

**Comment by segiddins** [comment]
No, it just means I can't debug this particular issue. As you can see from the specs I added, they all used `ps -o args`. I'd be happy to merge in a fix for linux & the corresponding test coverage

**Comment by dgutov** [comment]
I don't see how it does: unlike OS X, GNU/Linux is very easy (not to mention legal) to run virtualized inside a host using a different OS. And there are cheap as dirt virtual machines one can rent from Amazon, Digital Ocean, etc.

Anyway, you can try using an invocation of `ps`, but maybe it's not portable to OS X either. Here's the updated test file to automate this:

```rb
#!/usr/bin/env ruby

puts `ps -p #{Process.pid} -o comm=`
```

**Comment by segiddins** [comment]
Thanks, that reproduces it! I didn't know of the `command=` argument before.
In the meantime, under bundler >= 1.13.0.rc.2 you can set the `disable_exec_load` setting to opt-out of the new behavior if you rely on having the proper output from `ps`

**Comment by lynnco** [comment]
Ran the test case on os x and got `./test.rb`, so I believe this is fixed on 1.13.1 ?

**Comment by segiddins** [comment]
I don't remember fixing this, but it's possible

**Comment by dgutov** [comment]
The expected value is `ruby`, not `./test.rb`. Isn't it?

**Comment by lynnco** [comment]
@dgutov ah yea, I see you mentioned that in the first post. Can you check to see if anything has changed on your end with Bundler 1.13.1 ?

**Comment by dgutov** [comment]
Nope. No change.

**Comment by colby-swandale** [comment]
This was reported quite some time ago, is this worth fixing? @dgutov have you updated your monitoring to use `bundle` instead now? If we change it back it might break your monitoring again.

**Comment by dgutov** [comment]
> @dgutov have you updated your monitoring to use bundle instead now?

We did not, but updating it won't be hard. We're staying on 1.7.5 because of Puma reloading problems (which also makes the command name of the process switch back and forth between `ruby` and `bundler`, I'm told). I'll have to investigate that, and maybe open a separate issue.

So feel free to close this. I'm worried, however, that the test script behaves differently on GNU/Linux and MacOS. I've double-checked, and the output is `bundle` on my machine. If MacOS outputs `ruby`, that isn't great.
