### ISSUE TITLE
Bundler not aware of various gemrc settings (or alternatively a way to set similar options in Bundler)

### ISSUE THREAD

**Issue by rubin55** [bundler/bundler#4813]
Previously there have been issues reported that Bundler does not honor settings in gemrc (#582, #2565). I would like to re-raise this issue not from a perspective of no-proxy or user-install options, but from the "platform" option.

Particularly on Windows systems, gem will install a binary variant of a native package from the rubygem repository if that is available. If you actually have a devkit set-up (meaning: you can compile your own native gems and don't want the binaries provided in the repository) you can tell gem install to ignore that binary version and install the from-source version by specifying "--platform ruby".

This is particulary important on Windows because In my experience most provided binary packages ("bcrypt" and "pg" come to mind as recent offenders) do not work (meaning: they will install a binary variant of the package and on require, the backtrace party starts. Root causes vary between linker errors and mismatches between bitness (32 vs 64 bit dlls and interpreter mixup)).

Bundler is not aware of settings in gemrc (I'm not sure if Bundler uses gem under the hood) and so doing a 'bundler install' will never give you locally compiled native gems but the provided upstream ones.

Is it possible for Bundler to either 'config' a new setting that sets platform for gems, resulting in compilation, or for bundler to honor gemrc (if it indeed uses gem under the hood)?

To recreate this issue:

* install ruby 2.3.1 x64 on a windows box.
* install devkit (also from RubyInstaller)
* start a command shell (cmd.exe)
* `set GEM_HOME=%HOMEDRIVE%%HOMEPATH%\.gem\ruby\2.3.0`
* `dir %GEM_HOME%\gems`       _(notice no bcrypt package)_
* `gem install bcrypt`
* `dir %GEM_HOME%\gems`       _(notice mingw variant of bcrypt package)_
* in Ruby, require 'bcrypt' == b0rk, backtrace
* `gem uninstall bcrypt`
* `gem install bcrypt --platform ruby`
* `dir %GEM_HOME%\gems`       _(notice regular bcrypt variant: bcrypt-versionnumber)_
* In Ruby, require 'bcrypt' == true

**Comment by segiddins** [comment]
@rubin55 what happens if you just set `Gem.platforms = [Gem::Platform::RUBY]` at the top of your Gemfile?

**Comment by rubin55** [comment]
Added `[Gem::Platform::RUBY]` to the top of the Gemfile. Cleared gems, removed lock file, `bundle install`, no dice :-( Still installing binary versions.

**Comment by segiddins** [comment]
It's exactly what the --platform switch does in RubyGems 😅

**Comment by rubin55** [comment]
Alrighty, well, then I guess it works; would be cool if it would be settable as a bundle config thingie though, I can imagine that people would do this on a more general level then in the Gemfile. But happy to have a way to do it!
