### ISSUE TITLE
Set up Danger to run Rubocop and quality/language checks

### ISSUE THREAD

**Issue by indirect** [bundler/bundler#4827]
The output and error messages are _vastly_ improved over our current system, which requires reading the entire Travis CI log file.

http://danger.systems/

**Comment by segiddins** [comment]
We should also move the quality specs & rubocop to a separate matrix entry, and consider using the danger-rubocop and danger-junit plugins

**Comment by segiddins** [comment]
Also, this probably should wait until 2.0, since danger only supports Ruby 2+

**Comment by allenzhao** [comment]
@segiddins So if I would like to work on this, can I work on the 2.0 branch?

**Comment by segiddins** [comment]
I would personally recommend waiting, as project infrastructure stuff will conflict horribly when we finally get around to merging 2-0-dev into master

**Comment by colby-swandale** [comment]
There hasn't been much interest in this. Closing.
