### ISSUE TITLE
Add a configuration option to disable `BUNDLED WITH`

### ISSUE THREAD

**Issue by connorshea** [bundler/bundler#4829]
At GitLab we package Omnibus with a `Gemfile.lock`, if we have a `BUNDLED WITH` version at the bottom of the file, the test suite fails.

While I realize this is playing with fire, would it be possible to add a configuration option to prevent this from being added every time the `Gemfile.lock` is updated?

**Comment by segiddins** [comment]
@connorshea my gut reaction is that we're incredibly unlikely to add such an option. Can you try and explain why the section is causing you issues, so maybe we can brainstorm some workarounds either in bundler or on your end? Thanks!

**Comment by connorshea** [comment]
After thinking about this more and discussing it, I agree. This probably shouldn't be added and our process should change. I'll close.
