### ISSUE TITLE
Allow forward compatibility with new options by printing a warning instead of an error

### ISSUE THREAD

**Issue by indirect** [bundler/bundler#4833]
If future versions of Bundler add options or values (for `platform`, or `gem`, Bundler.settings, etc), older versions will currently raise an error like "not a valid option". That is technically true for that version of Bundler, but it's confusing if that option is a valid option in a later version.

It would be a better UX to print a warning on options that are not recognized, and suggest updating to a newer version of Bundler if the user needs that option/platform/setting/etc. That both helps users solve their own problem when an option isn't recognized, and makes it possible for older versions of Bundler to parse Gemfiles and print this warning.

**Comment by segiddins** [comment]
Should we do this only for the Gemfile DSL, or also command line options?

**Comment by indirect** [comment]
Good question. Both? This seems like it should probably be a warning normally and an exception in `--deployment` mode. Which I'm starting to think we should rename `--strict` or something. 😝

**Comment by segiddins** [comment]
The more I think about it, the more I'm against this. I think it will make it very easy to write a gemfile or invoke bundler in a way that is very close to correct, and thus lead to confusion and frustration when things don't work as expected.

**Comment by segiddins** [comment]
Done in https://github.com/bundler/bundler/issues/4943
