### ISSUE TITLE
`bundle gem` includes Gemfile.lock in .gitignore

### ISSUE THREAD

**Issue by scottj97** [bundler/bundler#4835]
The Bundler.io docs are clear that I should commit Gemfile.lock to source control. Yet when I create a skeleton gem using `bundle gem foo`, it creates a .gitignore file that includes /Gemfile.lock.

This line should not be in the generated .gitignore.

**Comment by indirect** [comment]
Thanks, you found a bug! It's a documenatation bug, though. The Gemfile.lock should not be checked in to a gem repo: http://yehudakatz.com/2010/12/16/clarifying-the-roles-of-the-gemspec-and-gemfile/

**Comment by scottj97** [comment]
Yes, I just found that...consider this a doc bug then.

**Comment by scottj97** [comment]
Perhaps I'm ignorant about what constitutes an "app" vs a "gem". I'm building a command-line program that I don't expect to be used in any other way (e.g. nobody will 'require' my library).

I was planning to distribute it as a gem. Is that the right approach?

**Comment by indirect** [comment]
Hmm. Did you read the article I linked above? If you're going to allow someone to install your gem via `gem install` or `bundle install`, you absolutely should not check in a lock.
