### ISSUE TITLE
Changing dependencies in a gemspec causes "corrupt Gemfile.lock" :/

### ISSUE THREAD

**Issue by indirect** [bundler/bundler#4838]
If you download [this zip file](http://files.arko.net/2e3E1p1Q1h1w/corrupt-lock-repro.zip), decompress it, cd into the directory, and run `./demo.sh`, you will get this error:

> Your Gemfile.lock is corrupt. The following gems are missing from the DEPENDENCIES section: 'twitter' 'oauth'.

The problem with that error is that all I did was add two gem dependencies to the gemspec of `lita-tweet`, which is depended on by `rubytogether-lita`. :/ I am pretty sure this should not trigger a corrupt lockfile error, and should instead install the newly-added gems and update the lockfile.

Maybe a GSoC student suitable bug? /cc @segiddins @RochesterinNYC

**Comment by segiddins** [comment]
This was tricky but I have a fix for it locally
