### ISSUE TITLE
BUNDLE_MIRROR__URL env var syntax not always valid

### ISSUE THREAD

**Issue by opiethehokie** [bundler/bundler#4843]
$ export BUNDLE_MIRROR__HTTPS://RUBYGEMS.ORG="http://rubygems-mirror.org"
-bash: export: `BUNDLE_MIRROR__HTTPS://RUBYGEMS.ORG=http://rubygems-mirror.org': not a valid identifier

$ bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)

\# export BUNDLE_MIRROR__HTTPS://RUBYGEMS.ORG="http://rubygems-mirror.org"
bash: export: `BUNDLE_MIRROR__HTTPS://RUBYGEMS.ORG=http://rubygems-mirror.org': not a valid identifier

\# bash --version
GNU bash, version 4.3.11(1)-release (x86_64-pc-linux-gnu)

**Comment by indirect** [comment]
This is resolved by #4844, thank you for both the report and the PR!
