### ISSUE TITLE
Can't completely ignore group

### ISSUE THREAD

**Issue by malroc** [bundler/bundler#4848]
I have a gem that can *only* be *downloaded* in production environment.
When I try to use `--without production` syntax, I get an error, since Bundler still tries to download all the gems.
I know this is the expected behavior and it is described in the docs:

http://bundler.io/man/bundle-install.1.html

> While the --without option will skip installing the gems in the specified groups, it will still download those gems and use them to resolve the dependencies of every gem in your Gemfile(5).

But I *really* want to completely ignore this particular gem in development environment. I don't need it to be downloaded. I totally understand all the risks, etc, and *still* need a way to completely ignore some gem (or group) in a particular environment.

**Comment by segiddins** [comment]
Do you have a lockfile present? It shouldn't need to download the gem if it doesn't need to re-resolve

**Comment by malroc** [comment]
@segiddins yes, lockfile is present, and that was working as you describe until I had to create a new rvm gemset. On a clean gemset `bundle install` fails.
Anyway, your tip is a workaround. I know several ways to workaround this behavior. But it would be much better if I wouldn't have to.

**Comment by indirect** [comment]
If Bundler has a lock and doesn't need to re-resolve, the gem will not be downloaded. If Bundler does not have a lock, or has a lock but the Gemfile has changed, it is not an issue of warnings or danger, it is an issue of not being able to resolve the Gemfile unless every gemspec is available.

This isn't us refusing to do something we could do, it's us letting you know that what you want isn't logically possible. :/ If you are okay with different versions of gems in development and production, don't use groups and without, add a conditional to your Gemfile.
