### ISSUE TITLE
Remove "or available on this machine" from GemNotFound error in --path mode

### ISSUE THREAD

**Issue by indirect** [bundler/bundler#4854]
As discussed in #4571, it's confusing that bundler says "or available on this machine" when the bundle is installed using `--path` mode. We should stop printing it under those circumstances. While we're at it, it would be cool to add "or in gems cached in vendor/cache" if the cache exists.

**Comment by segiddins** [comment]
This just uses the `#to_s` of the source. Keep in mind I changed that in the 2.0 branch.

**Comment by nickborromeo** [comment]
@indirect @segiddins can this issue be closed? 😄

**Comment by segiddins** [comment]
I believe so 👍🏻
