### ISSUE TITLE
1.99: the one that complains at you a lot

### ISSUE THREAD

**Issue by indirect** [bundler/bundler#4855]
- [x] hardcode the deprecations flags as turned on
- [x] deprecate `inject` in favor of `add`
- [ ] release final at the same time as 2.0

**Comment by segiddins** [comment]
> hardcode the deprecations flags as turned on

This can just be changing `SharedHelpers.prints_major_deprecations?` to be `return false if !Bundler.settings[:major_deprecations] &&  !Bundler::VERSION.split(".").include?("99")` and can be done now

**Comment by segiddins** [comment]
> deprecate inject in favor of add

this is dependent upon https://github.com/bundler/bundler/issues/4901

**Comment by colby-swandale** [comment]
There won't be a 1.99, so this can be closed. I'll also be writing docs about major releases after 2.0 is out that will cover this as well.
