### ISSUE TITLE
Prerelease X.0.0.rc1 matches spec for < X

### ISSUE THREAD

**Issue by jcoyne** [bundler/bundler#4858]
```
  In Gemfile:
    sufia (= 7.0.0) was resolved to 7.0.0, which depends on
      curation_concerns (~> 1.1) was resolved to 1.1.0, which depends on
        hydra-head (< 11, >= 10.0.0) was resolved to 10.1.0, which depends on
          hydra-core (= 10.1.0) was resolved to 10.1.0, which depends on
            hydra-access-controls (= 10.1.0) was resolved to 10.1.0, which depends on
              active-fedora (< 11, >= 10.0.0.beta1) was resolved to 11.0.0.rc1, which depends on
```

I don't understand how ` active-fedora (< 11, >= 10.0.0.beta1) was resolved to 11.0.0.rc1`, is that right?

Bundler version 1.12.5

**Comment by segiddins** [comment]
Yes, that is correct -- because there is a pre-release requirement, bundler considers prerelease versions, and x.pre is less than x+1

**Comment by jcoyne** [comment]
You said:
> x.pre is less than x+1

But is it also true that
`x.pre is less than x`?

**Comment by jcoyne** [comment]
Is it possible to write gemspec requirement that includes all releases of 8.0.0-10.x.x but will not include 11.0.0.pre?

**Comment by segiddins** [comment]
`>=8,<11.a` should do it

**Comment by jcoyne** [comment]
Thanks. That's quite helpful
