### ISSUE TITLE
Weird behaviour with rc gem

### ISSUE THREAD

**Issue by jacobat** [bundler/bundler#4859]
I'm in a weird situation. I can run:

```sh
$ bundle install --local
...
Bundle complete! 112 Gemfile dependencies, 255 gems now installed.
```

And this works with my current Gemfile and Gemfile.lock. Now if I go and remove some arbitrary gem from the Gemfile I suddenly get:

```sh
$ bundle install --local
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your bundle as root will break this
application for all non-root users on this machine.
Resolving dependencies...
Some gems seem to be missing from your vendor/cache directory.
Bundler could not find compatible versions for gem "active_record_shards":
  In snapshot (Gemfile.lock):
    active_record_shards (= 3.7.0.rc1)

  In Gemfile:
    active_record_shards (= 3.7.0.rc1)

    [a_private_gem] (= 1.8.2) was resolved to 1.8.2, which depends on
      active_record_shards (> 3.2.0)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
```

Where `[a_private_gem]`  is a gem that is not publicly available.

Now if I make a proper active_record_shards-3.7.0 everything suddenly works as expected and I can bundle just fine.

I'm not sure how to easily create a minimal failing test so I'm hoping this will pop a light in someone.

**Comment by jacobat** [comment]
Furthermore if I remove active_record_shards from the Gemfile (it's depended on by other gems) things start working as well even though active_record_shards.3.7.0.rc1 is still in the Gemfile.lock.

**Comment by segiddins** [comment]
What's the output of `bundle env`? I think this will be a hat bug to track down without a reproduction case, sorry.

**Comment by jacobat** [comment]
I'm not even able to reproduce anymore. Closing this out pending further investigation.
