### ISSUE TITLE
Issue while bundle install

### ISSUE THREAD

**Issue by ivancortesromero** [bundler/bundler#4861]
- What did you do?
  
  I ran the command `/Users/fluvip/.rvm/gems/ruby-2.3.1@project/bin/bundle install`
- What did you expect to happen?
  
  I expected Bundler to install gems from Gemfile to specific gemset
- What happened instead?
  
  Instead, what actually happened was this error appeared.

Error details

```
Errno::EIO: Input/output error @ io_fread - /Users/fluvip/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/info/capistrano3-unicorn
  /Users/fluvip/.rvm/gems/ruby-2.3.1@project/gems/bundler-1.12.5/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:77:in `read'
  /Users/fluvip/.rvm/gems/ruby-2.3.1@project/gems/bundler-1.12.5/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:77:in `checksum_for_file'
  /Users/fluvip/.rvm/gems/ruby-2.3.1@project/gems/bundler-1.12.5/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:70:in `update_info'
  /Users/fluvip/.rvm/gems/ruby-2.3.1@project/gems/bundler-1.12.5/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:43:in `block in dependencies'
  /Users/fluvip/.rvm/gems/ruby-2.3.1@project/gems/bundler-1.12.5/lib/bundler/fetcher/compact_index.rb:88:in `block (3 levels) in compact_index_client'
  /Users/fluvip/.rvm/gems/ruby-2.3.1@project/gems/bundler-1.12.5/lib/bundler/worker.rb:65:in `apply_func'
  /Users/fluvip/.rvm/gems/ruby-2.3.1@project/gems/bundler-1.12.5/lib/bundler/worker.rb:60:in `block in process_queue'
  /Users/fluvip/.rvm/gems/ruby-2.3.1@project/gems/bundler-1.12.5/lib/bundler/worker.rb:57:in `loop'
  /Users/fluvip/.rvm/gems/ruby-2.3.1@project/gems/bundler-1.12.5/lib/bundler/worker.rb:57:in `process_queue'
  /Users/fluvip/.rvm/gems/ruby-2.3.1@project/gems/bundler-1.12.5/lib/bundler/worker.rb:29:in `block (2 levels) in initialize'
```

Environment

  Bundler   1.12.5
  Rubygems  2.5.1
  Ruby      2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin14]
  GEM_HOME  /Users/fluvip/.rvm/gems/ruby-2.3.1@project
  GEM_PATH  /Users/fluvip/.rvm/gems/ruby-2.3.1@project:/Users/fluvip/.rvm/gems/ruby-2.3.1@global
  RVM       1.27.0 (latest)
  Git       2.8.1

```
  Bundler settings
```

  orig_path
    Set via BUNDLE_ORIG_PATH: "/Users/fluvip/.rvm/gems/ruby-2.3.1@project/bin:/Users/fluvip/.rvm/gems/ruby-2.3.1@global/bin:/Users/fluvip/.rvm/rubies/ruby-2.3.1/bin:/Users/fluvip/.rvm/bin:/opt/local/lib/postgresql94/bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/usr/local/ec2/ec2-api-tools-1.7.5.1/bin"
  orig_gem_path
    Set via BUNDLE_ORIG_GEM_PATH: "/Users/fluvip/.rvm/gems/ruby-2.3.1@project:/Users/fluvip/.rvm/gems/ruby-2.3.1@global"

**Comment by segiddins** [comment]
This has a friendlier error message in 1.14 -- in the meantime, perhaps deleting that file and trying to `bundle install` again will fix things.
