### ISSUE TITLE
`path` option can't be used in multi-level way

### ISSUE THREAD

**Issue by vbyno** [bundler/bundler#4866]
```
# path/to/gem1/Gemfile
gem 'gem2', path: 'path/to/gem2'

# path/to/gem2/Gemfile
gem 'gem3', path: 'path/to/gem3'

# path/to/gem3/Gemfile
gem `fuubar`
```

```
cd /path/to/gem3/ && bundle install
> Bundle complete!

cd /path/to/gem2/ && bundle install
> Bundle complete!

cd /path/to/gem1/ && bundle install
> Could not find gem 'gem3', which is required by gem 'gem2', in any of the sources.
```
I understand this might be not preferable feature at all. Could you please give a piece of advice how this can be handled (without adding `gem3` dependency directly to `gem1`?

**Comment by segiddins** [comment]
Can you please provide directions for reproducing the issue? It's hard to tell what's going on without seeing the gemspecs in question. Thanks!

**Comment by vbyno** [comment]
@segiddins , here is repository with these three gems and steps to reproduce: https://github.com/vbyno/gems_path_example

**Comment by segiddins** [comment]
Thanks!

**Comment by segiddins** [comment]
From the example, it looks like you'll need to add `../gem3` as a path source? Otherwise, bundler has no idea that there's a gem in that directory

**Comment by vbyno** [comment]
@segiddins , do you suggest adding `../gem3` path to `gem1` Gemfile? Yes, it will fix it. But I would like not to add this dependency explicitly to `gem1` if it already exists in `gem2`.

**Comment by segiddins** [comment]
it's not adding a dependency to `gem1`, it's just telling the Gemfile where to find  `gem3` which it seems you want to pull in via a path source

**Comment by vbyno** [comment]
Hm... But isn't it strange `gem1` doesn't know where to find `gem3`? I mean, it knows where to find `gem2`. And `gem2` knows where to find `gem3`. Why can't `gem1` get this knowledge from `gem2`?

**Comment by indirect** [comment]
Nope, `gem2` knows no such thing. When you put a `Gemfile` in a directory, you are not telling the gem anything at all, you are only telling Bunder that if it runs in that directory it should follow the directions in the `Gemfile`. If another gem uses `gem2`, it will not have any ideas about where to get `gem3`, because gems cannot contain instructions about where to get gems from.

**Comment by vbyno** [comment]
@indirect , thanks for a clarification. I assume Issue can be closed. See no way this can be handled without pointing at `gem3` in `gem1`'s Gemfile or excluding `gem3` dependency from `gem2`. Probably this is impossible without executing `gem2`'s Gemfile which would be silly.
