### ISSUE TITLE
parent directory is world writable,

### ISSUE THREAD

**Issue by daho16** [bundler/bundler#4870]
when i do update for bundle 

parent directory is world writable, FileUtils#remove_entry_secure does not work; abort: "/home/dama/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/versions20160810-16014-1vlzcap" (parent directory mode 40777)

**Comment by segiddins** [comment]
Thanks for the issue! I think it's a duplicate of https://github.com/bundler/bundler/issues/4599, so I'm going to close this one for now.

**Comment by twins16** [comment]
thank's man
