### ISSUE TITLE
Bundler version file?

### ISSUE THREAD

**Issue by jacobbednarz** [bundler/bundler#4883]
Hey,
I work on a few projects that use Bundler and each of them has a different version need. For example:

- ProjectA is an older application and only works with Bundler 1.11.x
- ProjectB is a new hipster app that runs on bleeding edge Bundler.

I know things like `bundle _VERSION_ install` are available however this is something that often gets forgotten and has people throwing their hands up because of the version mismatch issues.

I'm thinking a directive in the Gemfile (similar to [`ruby`](http://bundler.io/v1.3/man/gemfile.5.html#RUBY-ruby-)) that could define the desired version for the project would suffice nicely. Would this be something the Bundler team would be interested in? I'm happy to put up a pull request if everyone is on board with it.

Thanks! :cake:

**Comment by jacobbednarz** [comment]
Thanks for the pointers @segiddins - I didn't manage to find that first time around.

While the postits gem looks to do what I'm after, I'm not too sure about the need to replace `bundle` calls with `postit` calls (please correct me if I've misunderstood this). I'd rather this be handled under the covers and not interrupt the existing developer workflow. I see it's now in bundler behind a feature flag - does this mean that it's going to use the `bundle` calls from now on? Or will it continue using separate `postit` calls?

**Comment by segiddins** [comment]
It's been integrated into bundler itself in the 1.13 release series, behind a feature flag

**Comment by jacobbednarz** [comment]
Thanks, I guess I'll need to get them all onto 1.13 in order to be able to use this.

**Comment by indirect** [comment]
Keep in mind that if you use the feature flag, your projects can stay on older Bundler versions, as long as the machine they are running on has Bundler 1.13+ installed.

**Comment by jacobbednarz** [comment]
Ah great to know @indirect - much appreciated!
