### ISSUE TITLE
SQL Database rake:db:migrate

### ISSUE THREAD

**Issue by markwintch** [bundler/bundler#4890]
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `C:/Ruby21-x64/bin/bundle exec rake:db:migrate`

- What did you expect to happen?

  I expected Bundler to...
RemovePositionDefaults: migrating
Then change columns
Then AddRolesSettings  

- What happened instead?

  Instead, what actually happened was...

Error details

    Errno::EINVAL: Invalid argument - rake:db:migrate
      C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:44:in `exec'
      C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:44:in `kernel_exec'
      C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:29:in `run'
      C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/cli.rb:304:in `exec'
      C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/cli.rb:11:in `start'
      C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/exe/bundle:27:in `block in <top (required)>'
      C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
      C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/exe/bundle:19:in `<top (required)>'
      C:/Ruby21-x64/bin/bundle:23:in `load'
      C:/Ruby21-x64/bin/bundle:23:in `<main>'

Environment

  Bundler   1.12.5
  Rubygems  2.2.5
  Ruby      2.1.9p490 (2016-03-30 revision 54437) [x64-mingw32]
  Git       not installed

      Bundler settings

  without
    Set for your local app (c:/inetpub/wwwroot/redmine/.bundle/config): "development:test:rmagick"
  bin_path
    Set via BUNDLE_BIN_PATH: "C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/exe/bundle"
  gemfile
    Set via BUNDLE_GEMFILE: "c:/inetpub/wwwroot/redmine/Gemfile"
--- TEMPLATE END ----------------------------------------------------------------

**Comment by segiddins** [comment]
I think you meant to run `bundle exec rake db:migrate`, though we should definitely be catching that error and presenting a friendlier one

**Comment by markwintch** [comment]
Oh my, so I had this problem because I put a : where it didn't belong and I
still never caught that error?  I will blame looking at this all day.
Thank you for seeing this oversight on my part.

*Mark Wintch*

Systems Analyst I



*Phone:* 913-309-4503

*Fax:* 1-866-470-0066

*Email:* mwintch@grantham.edu


 [image: Inline image 1]

       Online.* But not alone*.*TM*



Know someone who should hear about Grantham?  Refer a Friend
<http://grantham.edu/refer-a-friend>!

**Comment by markwintch** [comment]
We can go ahead and close this issue.

**Comment by segiddins** [comment]
👍
