### ISSUE TITLE
Gem path loading issue with Bundler.require during "bundle exec rake test"

### ISSUE THREAD

**Issue by Blargel** [bundler/bundler#4899]
I encountered a strange issue after upgrading from version 1.10.6 to 1.12.5 of bundler where the gems are loaded properly when running "bundle exec rackup", but they are not when running "bundle exec rake test". It appears to attempt to load a file in my application's lib/ directory as the gem instead of the actual gem.

I've made an extremely stripped down version that can reproduce the issue here: https://github.com/Blargel/bundler-load-error

Just clone that repo, run "bundle install", and then "bundle exec rake test" and an error will appear. This error in particular seems to be because the lib/sequel.rb file is attempting to patch over a class within the gem, but it's instead being loaded as the gem itself. Renaming the file will fix the error.

I'm running ruby version 2.2.2 and bundler version 1.12.5. This did not happen in bundler version 1.10.6. I didn't test any versions in between.

**Comment by indirect** [comment]
@segiddins any theories about this one?

**Comment by segiddins** [comment]
`Command failed with status (1): [ruby -I"lib" -I"/Users/segiddins/.gem/ruby/2.3.1/gems/rake-10.4.2/lib" "/Users/segiddins/.gem/ruby/2.3.1/gems/rake-10.4.2/lib/rake/rake_test_loader.rb" "test/test*.rb" ]`
The issue here is passing in `-Ilib` which comes before gems in `$LOAD_PATH`

**Comment by segiddins** [comment]
This is behaving as intended. Passing in `-Ilib` ensures the files in `lib` will be required before files in gems.
