### ISSUE TITLE
Fixes for `add` command

### ISSUE THREAD

**Issue by indirect** [bundler/bundler#4901]
- [ ] add an artifice test so we know it works against e.g. the dependency API
- [ ] get gem version list directly from source using fetcher
- [ ] either remove `--source` option or respect it when fetching the list of gem versions
- [ ] handle gem names that aren't present on rubygems.org

**Comment by segiddins** [comment]
@b-ggs any interest in doing this?

**Comment by shuboid** [comment]
Wanna contribute .. Leads will be appreciated.TIA

**Comment by segiddins** [comment]
@shuboid the task items @indirect has posted above should be a good outline of the work that needs to be done

**Comment by colby-swandale** [comment]
Hi @indirect,
I'm working on an implementation of this feature and i have a couple of questions. In terms of the interface is the idea you have along the lines of `bundler add pg '~> 1.5'`?  I assume that we allow users to specify the version and maybe also specify optional groups as a flag like `--group development` as well. Thoughts?

**Comment by hmistry** [comment]
@shuboid Could you let me know if you're working on this feature? If you're not, then I'd like to work on it.

**Comment by denniss** [comment]
Adding the RFC here: 
https://github.com/hmistry/rfcs/blob/bundle-add/text/0000-bundle-add.md

I'm currently giving this a try. Let me know if someone else is already working on this.

**Comment by denniss** [comment]
I think this one can be closed.

**Comment by segiddins** [comment]
Closed by https://github.com/bundler/bundler/pull/5486
