### ISSUE TITLE
`bundle config NAME` is too verbose by default

### ISSUE THREAD

**Issue by BM5k** [bundler/bundler#4913]
And doesn't provide a non-verbose option.

```
Bundler version 1.12.5
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]
rubygems 2.6.6
```

> What you're trying to accomplish

I would like to query the value of a config setting.

> The command you ran

`bundle config my-setting`

> What you expected to happen

return the value associated with `my-setting`, possibly just the value, possibly as `KEY=VALUE`

> What actually happened

Information overload!

**Comment by indirect** [comment]
I think this is a good point. We have added the `--parseable` option for this type of use, and I think it would be useful to add it here.

**Comment by BM5k** [comment]
Yes, that would be perfect, since my end goal was for this to be machine readable.

**Comment by lynnco** [comment]
Relevant PR https://github.com/bundler/bundler/pull/4919

**Comment by colby-swandale** [comment]
Hi 👋 , We have added a `--parseable` option to `bundle config` in the latest release.
