### ISSUE TITLE
Your Ruby engine is jruby, but your Gemfile specified jruby

### ISSUE THREAD

**Issue by dipnlik** [bundler/bundler#4914]
Given the following Gemfile:

```ruby
ruby '2.3.0', engine: :jruby, engine_version: '9.1.2.0'
```

When I run `bundle` using the correct JRuby version, I get an unexpected error message:

> Your Ruby engine is jruby, but your Gemfile specified jruby

I already found out that the error happens because I declared `engine` as `:jruby` instead of `'jruby'`.  Still, I see two possible improvements in Bundler: 1) change the error message to be clear about strings vs. symbols, and/or 2) enable the use of symbols when declaring the engine, to make it consistent with for example declaring gem groups or platforms.

**Comment by indirect** [comment]
That's pretty confusing, thanks for reporting this! We should definitely call `to_s` on those arguments.

**Comment by JuanitoFatas** [comment]
> We should definitely call to_s on those arguments.

I'll work on this!
