### ISSUE TITLE
private method `name_for' called for #<Bundler::Resolver:0x94e35dc>

### ISSUE THREAD

**Issue by messyacid** [bundler/bundler#4920]
I'm getting this error while trying `bundle install`

`Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..

--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `/var/lib/gems/2.2.0/gems/bundler-1.12.5/exe/bundle install`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what actually happened was...

Error details

    NoMethodError: private method `name_for' called for #<Bundler::Resolver:0x94e35dc>
      /usr/lib/ruby/vendor_ruby/molinillo/delegates/specification_provider.rb:31:in `block in name_for'
      /usr/lib/ruby/vendor_ruby/molinillo/delegates/specification_provider.rb:69:in `with_no_such_dependency_error_handling'
      /usr/lib/ruby/vendor_ruby/molinillo/delegates/specification_provider.rb:30:in `name_for'
      /usr/lib/ruby/vendor_ruby/molinillo/resolution.rb:161:in `block (2 levels) in initial_state'
      /usr/lib/ruby/vendor_ruby/molinillo/resolution.rb:161:in `each'
      /usr/lib/ruby/vendor_ruby/molinillo/resolution.rb:161:in `block in initial_state'
      /usr/lib/ruby/vendor_ruby/molinillo/resolution.rb:160:in `tap'
      /usr/lib/ruby/vendor_ruby/molinillo/resolution.rb:160:in `initial_state'
      /usr/lib/ruby/vendor_ruby/molinillo/resolution.rb:106:in `start_resolution'
      /usr/lib/ruby/vendor_ruby/molinillo/resolution.rb:64:in `resolve'
      /usr/lib/ruby/vendor_ruby/molinillo/resolver.rb:42:in `resolve'
      /usr/lib/ruby/vendor_ruby/bundler/resolver.rb:199:in `start'
      /usr/lib/ruby/vendor_ruby/bundler/resolver.rb:182:in `resolve'
      /usr/lib/ruby/vendor_ruby/bundler/definition.rb:200:in `resolve'
      /usr/lib/ruby/vendor_ruby/bundler/definition.rb:140:in `specs'
      /usr/lib/ruby/vendor_ruby/bundler/definition.rb:129:in `resolve_remotely!'
      /usr/lib/ruby/vendor_ruby/bundler/installer.rb:79:in `run'
      /usr/lib/ruby/vendor_ruby/bundler/installer.rb:18:in `install'
      /usr/lib/ruby/vendor_ruby/bundler/cli/install.rb:107:in `run'
      /usr/lib/ruby/vendor_ruby/bundler/cli.rb:162:in `install'
      /usr/lib/ruby/vendor_ruby/thor/command.rb:27:in `run'
      /usr/lib/ruby/vendor_ruby/thor/invocation.rb:126:in `invoke_command'
      /usr/lib/ruby/vendor_ruby/thor.rb:359:in `dispatch'
      /usr/lib/ruby/vendor_ruby/thor/base.rb:440:in `start'
      /usr/lib/ruby/vendor_ruby/bundler/cli.rb:10:in `start'
      /var/lib/gems/2.2.0/gems/bundler-1.12.5/exe/bundle:27:in `block in <main>'
      /usr/lib/ruby/vendor_ruby/bundler/friendly_errors.rb:7:in `with_friendly_errors'
      /var/lib/gems/2.2.0/gems/bundler-1.12.5/exe/bundle:19:in `<main>'

Environment

    Bundler   1.10.6
    Rubygems  2.4.5.1
    Ruby      2.2.3p173 (2015-08-18 revision 0) [i386-linux-gnu]
    GEM_HOME  /var/lib/gems/2.2.0
    GEM_PATH  /var/lib/gems/2.2.0:/root/.gem/ruby/2.2.0:/usr/lib/i386-linux-gnu/rubygems-integration/2.2.0:/usr/share/rubygems-integration/2.2.0:/usr/share/rubygems-integration/2.2:/usr/share/rubygems-integration/all
    Git       2.8.1
--- TEMPLATE END ----------------------------------------------------------------
`

**Comment by JuanitoFatas** [comment]
@messyacid Hi, thanks for the report, could you provide us your Gemfile / Gemfile.lock and how to reproduce your issue? Thank you!

**Comment by segiddins** [comment]
Why is `/var/lib/gems/2.2.0/gems/bundler-1.12.5/exe/bundle install` invoking Bundler 1.10.6?

**Comment by messyacid** [comment]
@Juanito Fatas this is gemfile
`source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.0.0'
# Use sqlite3 as the database for Active Record
gem 'sqlite3'
# Use Puma as the app server
gem 'puma', '~> 3.0'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.2'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 3.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platform: :mri
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'web-console'
  gem 'listen', '~> 3.0.5'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]`


well a bummer I figured out my rails didn't created any Gemfile.lock

**Comment by messyacid** [comment]
@segiddins ahh I don't know why its invoking I am new to rails the command line had this told me to write this issue any details and advice would be welcomed sorry for inconvenience .

**Comment by indirect** [comment]
@messyacid I am very sorry to have to tell you this, but it seems like the problem is coming from your Linux distro's Ruby package. It looks like you will have to install ruby another way (perhaps using rvm.io?) to get a Ruby that does not have these problems.

**Comment by indirect** [comment]
@segiddins I am guessing this is Debian? But I guess it could be Fedora. Check out this part of the backtrace:

```
  /usr/lib/ruby/vendor_ruby/bundler/cli.rb:10:in `start'
  /var/lib/gems/2.2.0/gems/bundler-1.12.5/exe/bundle:27:in `block in <main>'
  /usr/lib/ruby/vendor_ruby/bundler/friendly_errors.rb:7:in `with_friendly_errors'
  /var/lib/gems/2.2.0/gems/bundler-1.12.5/exe/bundle:19:in `<main>'
```

o_O

**Comment by messyacid** [comment]
@Indirect That's Kali 2.0 but I fixed the problem actually it all got messed up after I tried to change some stuff from metasploit but when I reinstalled bundler it's working fine now.Still thanks all for your help.

**Comment by AnkDos** [comment]
@messyacid  Hey there , I am facing the same problem on Kali 2.0 .I tried to Re-install the bundler but did'nt work. How did you solved the problem?
