### ISSUE TITLE
Problem with bundle exec

### ISSUE THREAD

**Issue by ashmaroli** [bundler/bundler#4926]
Hi,
I'm using Bundler 1.12.5 
on Windows 7 x64
having Ruby 2.3.1 installed
and this issue is regarding `bundle exec`

Say I've a rails app freshly generated with Rails 5.0.0.1
I decide to run the rails server with bundle exec
```
$ bundle exec rails s
```
Everything runs as expected. I can view the _Welcome to Rails_ page at localhost.
Now, I hit Ctrl-C
and I get:
```
Exiting
Terminate batch job (Y/N)? 
```
But suddenly I decide to not terminate the server process.
I enter ` N `
I get ` Terminate batch job (Y/N)? ` **again**.
I enter ` N ` again.

But, **_the batch job is terminated anyway._**
:disappointed:

**Comment by indirect** [comment]
Hi, thanks for reporting this issue. Why do you think this is related to `bundle exec`? Bundler does not print the message "Exiting", nor does it print the message "Terminate batch job (Y/N)?". Something else on your machine must be doing that.

**Comment by ashmaroli** [comment]
Oh I see.. then it must be the Windows command prompt itself. Thanks.
