### ISSUE TITLE
PrimitiveFailure: String#valid_encoding? primitive failed

### ISSUE THREAD

**Issue by mvz** [bundler/bundler#4927]
- What did you do?

  I ran the command `/home/matijs/.rbenv/versions/rbx-3.56/bin/bundle `

- What did you expect to happen?

  I expected Bundler to install some gems

- What happened instead?

  Instead, what actually happened was:
  * Bundler produced the output:
  ```
  Fetching https://github.com/mbj/mutant.git
  Fetching gem metadata from https://rubygems.org/
  ```
  * And then it produced this error template.

Error details

    PrimitiveFailure: String#valid_encoding? primitive failed
      core/string.rb:192:in `valid_encoding?'
      core/splitter.rb:17:in `valid_encoding?'
      core/splitter.rb:59:in `split'
      core/string.rb:669:in `split'
      /home/matijs/.rbenv/versions/rbx-3.56/gems/gems/bundler-1.12.5/lib/bundler/vendor/compact_index_client/lib/compact_index_client/cache.rb:93:in `parse_dependency'
      /home/matijs/.rbenv/versions/rbx-3.56/gems/gems/bundler-1.12.5/lib/bundler/vendor/compact_index_client/lib/compact_index_client/cache.rb:87:in `parse_gem'
      core/array.rb:93:in `map'
      /home/matijs/.rbenv/versions/rbx-3.56/gems/gems/bundler-1.12.5/lib/bundler/vendor/compact_index_client/lib/compact_index_client/cache.rb:87:in `parse_gem'
      /home/matijs/.rbenv/versions/rbx-3.56/gems/gems/bundler-1.12.5/lib/bundler/vendor/compact_index_client/lib/compact_index_client/cache.rb:57:in `dependencies'
      core/array.rb:93:in `map'
      /home/matijs/.rbenv/versions/rbx-3.56/gems/gems/bundler-1.12.5/lib/bundler/vendor/compact_index_client/lib/compact_index_client/cache.rb:56:in `dependencies'
      /home/matijs/.rbenv/versions/rbx-3.56/gems/gems/bundler-1.12.5/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:44:in `dependencies'
      core/proc.rb:20:in `call'
      /home/matijs/.rbenv/versions/rbx-3.56/gems/gems/bundler-1.12.5/lib/bundler/fetcher/compact_index.rb:88:in `compact_index_client'
      core/proc.rb:20:in `call'
      /home/matijs/.rbenv/versions/rbx-3.56/gems/gems/bundler-1.12.5/lib/bundler/worker.rb:65:in `apply_func'
      /home/matijs/.rbenv/versions/rbx-3.56/gems/gems/bundler-1.12.5/lib/bundler/worker.rb:60:in `process_queue'
      core/kernel.rb:585:in `loop'
      /home/matijs/.rbenv/versions/rbx-3.56/gems/gems/bundler-1.12.5/lib/bundler/worker.rb:57:in `process_queue'
      /home/matijs/.rbenv/versions/rbx-3.56/gems/gems/bundler-1.12.5/lib/bundler/worker.rb:29:in `initialize'
      core/proc.rb:20:in `call'

Environment
      
  Bundler   1.12.5
  Rubygems  2.6.6
  Ruby      2.3.1p0 (2016-08-19 revision 0) [x86_64-linux-gnu]
  GEM_HOME  /home/matijs/.rbenv/versions/rbx-3.56/gems
  GEM_PATH  /home/matijs/.rbenv/versions/rbx-3.56/gems:/home/matijs/.gem/rbx/2.3
  Git       2.9.3
      
      Bundler settings
      
  shebang
    Set for the current user (/home/matijs/.bundle/config): "ruby"
  gem.coc
    Set for the current user (/home/matijs/.bundle/config): "true"
  gem.mit
    Set for the current user (/home/matijs/.bundle/config): "true"
  gem.test
    Set for the current user (/home/matijs/.bundle/config): "rspec"
  orig_path
    Set via BUNDLE_ORIG_PATH: "/home/matijs/.rbenv/versions/rbx-3.56/bin:/usr/lib/rbenv/libexec:/home/matijs/.rbenv/shims:/home/matijs/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/matijs/bin"

**Comment by indirect** [comment]
Thanks for reporting this! I've never seen that error before. Is it something specific to Rubinius? What causes it? What are your shell encoding settings?

**Comment by mvz** [comment]
> Is it something specific to Rubinius?

Yes. I have just tried the same on a fresh install of MRI 2.2.5, and it causes no problems.

> What causes it?

This happened running `bundle` in my project gir_ffi, when no other gems are installed yet. However, subsequent runs causes segfaults instead of the error above. There were also some errors about system gems not having had their extensions built.

After using gem pristine to fix the system gems, and manually installing all dependencies for my project, `bundle` works fine.

I'm afraid this error may not be easily reproducible :frowning:.

> What are your shell encoding settings?

```
[matijs@bean] locale
LANG=en_IE.utf8
LANGUAGE=
LC_CTYPE="en_IE.utf8"
LC_NUMERIC="en_IE.utf8"
LC_TIME="en_IE.utf8"
LC_COLLATE=C
LC_MONETARY="en_IE.utf8"
LC_MESSAGES="en_IE.utf8"
LC_PAPER="en_IE.utf8"
LC_NAME="en_IE.utf8"
LC_ADDRESS="en_IE.utf8"
LC_TELEPHONE="en_IE.utf8"
LC_MEASUREMENT="en_IE.utf8"
LC_IDENTIFICATION="en_IE.utf8"
LC_ALL=
```

**Comment by indirect** [comment]
Okay. If you see this again, let us know!
