### ISSUE TITLE
Inconsistency with `bundle update` (major vs minor/patch)

### ISSUE THREAD

**Issue by marcandre** [bundler/bundler#4934]
Here's a [test case](https://github.com/marcandre/bundler-cases/blob/f1d57f49cc4871b5eda803825c649f982fd719ac/cases/conservative/very_basic.rb) aiming to illustrate the inconsistency with `bundle update foo` with different `--major`/`minor`/`patch`. The only available gem versions are patches releases, so all three options should all behave the same but they don't for [the `minor` and `patch` options](https://github.com/marcandre/bundler-cases/blob/f1d57f49cc4871b5eda803825c649f982fd719ac/cases/conservative/very_basic.rb#L43-L59).

I feel this inconsistency has to be bug. For sure, it makes it impossible to understand what is supposed to be going on.

Moved from https://github.com/chrismo/bundler-cases/issues/6

**Comment by marcandre** [comment]
FWIW, I strongly disagree with `bundler update foo` changing needlessly `bar`'s version (see #2016), so I'm kind of shooting myself in the foot here by pointing this out 😢 

My christmas wish is that `bundle update` does change whatever you want, but that `bundler` makes an incompatible change for `bundle update a_particular_gem` and mimicks the new behavior of `--minor/patch` instead of bringing those inline with the current behavior.

If I can't get my christmas wish, I am still hoping for a way to do `bundler update foo --whatever-options-you-d-like-me-to-type` that won't change `bar` (no matter what / unless necessary, pick your favorite).

**Comment by indirect** [comment]
@marcandre that is my understanding of our actual plan for Bundler 2.0: make the logic of --minor and --patch the default. We're not sure if we'll manage to ship it in time for it to be your christmas present, though. 😆

**Comment by marcandre** [comment]
OMG! Awesome!

**Comment by chrismo** [comment]
I think in conjunction with the desire for a `--conservative` flag** (great name, hate typing it - too long?) ... we can have a little 1.x cake and eat it too here. 

(** https://github.com/chrismo/bundler-cases/blob/master/cases/conservative/update/conservative_like_install.rb)

Also added PR with your case => https://github.com/chrismo/bundler-cases/pull/12

**Comment by chrismo** [comment]
ha - this may be all that's needed to fix this:

```
--- a/lib/bundler/definition.rb
+++ b/lib/bundler/definition.rb
@@ -103,8 +103,6 @@ module Bundler
       end
       @unlocking ||= @unlock[:ruby] ||= (!@locked_ruby_version ^ !@ruby_version)
 
-      @gem_version_promoter = create_gem_version_promoter
-
       current_platform = Bundler.rubygems.platforms.map {|p| generic(p) }.compact.last
       add_platform(current_platform)
 
@@ -112,6 +110,8 @@ module Bundler
       eager_unlock = expand_dependencies(@unlock[:gems])
       @unlock[:gems] = @locked_specs.for(eager_unlock).map(&:name)
 
+      @gem_version_promoter = create_gem_version_promoter
+
       @source_changes = converge_sources
       @dependency_changes = converge_dependencies
       @local_changes = converge_locals
```
