### ISSUE TITLE
Merge the compact index client into the Bundler repo

### ISSUE THREAD

**Issue by indirect** [bundler/bundler#4935]
Now that Bundler is already a submodule inside RubyGems, we don't need to keep this shared library in a separate repository anymore.
- [x] move vendored compact index client into Bundler lib #5007
- [ ] update compact index client repository readme
- [ ] push an empty gem with a higher version and a post install message that says the library has moved into Bundler (?)

**Comment by colby-swandale** [comment]
@indirect does this still need doing?

**Comment by segiddins** [comment]
Yes
