### ISSUE TITLE
Difficulty contributing to the documentation

### ISSUE THREAD

**Issue by connorshea** [bundler/bundler#4940]
I was looking into contributing some improvements to the documentation for Bundler, but found there wasn't really any documentation (at least that I could find) about contributing to the documentation. I couldn't find anything about how it's generated, where I should go to edit it, etc.

For example I'm not sure why [`bundle_viz.html.md`](https://github.com/bundler/bundler-site/blob/master/source/v1.12/bundle_viz.html.md) is in the bundler-site repo vs. [`bundle-update.ronn`](https://github.com/bundler/bundler/blob/master/man/bundle-update.ronn) in the bundler repo.

Which file format is preferred and where should I go to update things? Presumably the files in `man/`, but is there any intention to merge the documentation so it's all in one central place?

Given how great the Bundler project usually is about these things, I wanted to point out the blindspot. I'd be happy to help if possible.

Apologies if there's an issue about these things already. After searching for a good while I couldn't find anything that discussed this.

**Comment by indirect** [comment]
Thanks for reporting this! It's likely that we should add a section to CONTRIBUTING.md that explicitly calls out the location of various documentation:

 - anything that comes up when you use `--help` is inside the Bundler repo in a .ronn file
 - a few other files, like ISSUES.md, are copied directly out of the repo into the website
 - everything else is generated out of the [/source](https://github.com/bundler/bundler-site/tree/master/source) directory in the bundler-site repo

We should probably also put that information in the bundler-site repo readme, as well as a list of the files that are copied out of the main repo and therefore should be edited there instead.

**Comment by lynnco** [comment]
I parsed this out into a few issues https://github.com/bundler/bundler-site/issues/255, https://github.com/bundler/bundler-site/issues/254, https://github.com/bundler/bundler/issues/4987

**Comment by segiddins** [comment]
This should be addressed by @feministy's amazing work creating https://github.com/bundler/bundler/tree/master/doc/documentation.
