### ISSUE TITLE
run  bundle exec spring binstub --all

### ISSUE THREAD

**Issue by JaymarBallanti** [bundler/bundler#4942]
Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/bundler/bundler/search?q=parent+directory+is+world+writable+but+not+sticky&type=Issues

If there aren't any reports for this error yet, please create copy and paste the report template above into a new issue. Don't forget to anonymize any private data! The new issue form is located at:
https://github.com/bundler/bundler/issues/new
         run  bundle exec spring binstub --all
bundler: command not found: spring
Install missing gem executables with `bundle install`

**Comment by segiddins** [comment]
What's the output of `bundle env`?

**Comment by JaymarBallanti** [comment]
Environment

    Bundler   1.12.5
    Rubygems  2.6.6
    Ruby      2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
    Git       1.9.1

Bundler settings

    bin
      Set for the current user (/home/aymar/.bundle/config): "bin"
    orig_path
      Set via BUNDLE_ORIG_PATH: "/home/aymar/.rbenv/versions/2.3.1/bin:/home/aymar/.rbenv/libexec:/home/aymar/.rbenv/plugins/ruby-build/bin:/home/aymar/.rbenv/plugins/ruby-build/bin:/home/aymar/.rbenv/shims:/home/aymar/.rbenv/bin:/home/aymar/.rbenv/plugins/ruby-build/bin:/home/aymar/.rbenv/shims:/home/aymar/.rbenv/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games"

Gemfile

    source 'https://rubygems.org'


    # Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
    gem 'rails', '~> 5.0.0', '>= 5.0.0.1'
    # Use sqlite3 as the database for Active Record
    gem 'sqlite3'
    # Use Puma as the app server
    gem 'puma', '~> 3.0'
    # Use SCSS for stylesheets
    gem 'sass-rails', '~> 5.0'
    # Use Uglifier as compressor for JavaScript assets
    gem 'uglifier', '>= 1.3.0'
    # Use CoffeeScript for .coffee assets and views
    gem 'coffee-rails', '~> 4.2'
    # See https://github.com/rails/execjs#readme for more supported runtimes
    # gem 'therubyracer', platforms: :ruby

    # Use jquery as the JavaScript library
    gem 'jquery-rails'
    # Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
    gem 'turbolinks', '~> 5'
    # Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
    gem 'jbuilder', '~> 2.5'
    # Use Redis adapter to run Action Cable in production
    # gem 'redis', '~> 3.0'
    # Use ActiveModel has_secure_password
    # gem 'bcrypt', '~> 3.1.7'

    # Use Capistrano for deployment
    # gem 'capistrano-rails', group: :development

    group :development, :test do
      # Call 'byebug' anywhere in the code to stop execution and get a debugger console
      gem 'byebug', platform: :mri
    end

    group :development do
      # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
      gem 'web-console'
      gem 'listen', '~> 3.0.5'
      # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
      gem 'spring'
      gem 'spring-watcher-listen', '~> 2.0.0'
    end

    # Windows does not include zoneinfo files, so bundle the tzinfo-data gem
    gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

Gemfile.lock

    <No /home/aymar/app/Gemfile.lock found>

**Comment by JaymarBallanti** [comment]
have to downgrade bundle install..finally OK.

**Comment by segiddins** [comment]
I was unable to reproduce this with the given Gemfile

> Spring was unable to find your config/application.rb file. Your project root was detected at /Users/segiddins/Desktop/GemfileTest, so spring looked for /Users/segiddins/Desktop/GemfileTest/config/application.rb but it doesn't exist. You can configure the root of your application by setting Spring.application_root in config/spring.rb.

**Comment by JaymarBallanti** [comment]
ok tnx man but i downgraded the version of bundle and it works..

**Comment by Mohammed-Eliass** [comment]
@JaymarBallanti 
I have the same problem , to what version of bundler should I downgrade ?
