### ISSUE TITLE
Bundler is unable to resolve a non-conflicting optimistic dependency.

### ISSUE THREAD

**Issue by freerobby** [bundler/bundler#4945]
I am seeing behavior where specifying `>= x.y.z` seems to have an implied `and < (x+1)`.

I have reproduced this behavior with a blank Rails 5 app, and a single gem dependency which should be compatible with Rails 5.

Here is the gem that requires ActiveResource >= 2.3.8: https://github.com/wistia/wistia-api/blob/master/wistia-api.gemspec#L57

Here is a blank rails 5 app, which requires ActiveResource ~> 5.0.0: https://github.com/freerobby/wistia-api-test/blob/master/Gemfile

By my reading of Gemfile and Gemspec specifications, these are not in conflict. Any version of ActiveResource ~> 5.0.0 should also satisfy >= 2.3.8. However, Bundler is unable to resolve this. If you clone the aforementioned rails app and run "bundle", you will get, among other things:

```
    wistia-api was resolved to 0.1.0, which depends on
      activeresource (> 2.3.8) was resolved to 3.0.0, which depends on
        activemodel (= 3.0.0)
```

Why does ActiveResource >2.3.8 resolve to 3.0.0 in this situation? Attempting to `bundle update` that gem, or its dependencies like ActiveSupport, produces the same problem.

I am running Bundler version 1.12.5

**Comment by chrismo** [comment]
Can you check out this bundler-case, see if it fits your scenario and then execute it locally and gist the results? This case is working for me locally, but it may not recreate your case appropriately.

https://github.com/chrismo/bundler-cases/pull/8

**Comment by chrismo** [comment]
Whoops - sorry - re-read, didn't see you'd linked to the Gemfile - sorry.

**Comment by freerobby** [comment]
Thanks for the quick reply! Sent you a PR for a minimally failing case (it's just wistia-api gem rather than wistia gem). Let me know if I can be helpful here.

**Comment by chrismo** [comment]
I think this is simply a limitation activeresource - no released gem is compatible with other Rails 5 dependencies: https://rubygems.org/gems/activeresource/versions/4.1.0

It looks like [on the master branch they have unreleased dependency version changes that will make it compatible again](https://github.com/rails/activeresource/commit/3ddc00e807ccf4aba43b0d780da0c7e425a2410a).

**Comment by chrismo** [comment]
What's confusing about the VersionConflict output from Bundler is this part:

```
    activeresource (>= 2.3.8) was resolved to 2.3.8, which depends on
      activesupport (= 2.3.8)
```

But if you look at the resolve debug output, it starts with the most recent match (4.1.0) and works through every other version back to 2.3.8, and since 2.3.8 was the last one tried, and NONE of them worked, you get the confusing output of it "was resolved to 2.3.8".

The debug output you'll see it first tries 

```
Creating possibility state for activeresource (>= 2.3.8) (73 remaining)
  Attempting to activate activeresource (4.1.0)
  Activated activeresource at activeresource (4.1.0)
  Requiring nested dependencies (activemodel (~> 4.0), activesupport (~> 4.0), rails-observers (~> 0.1.2))
```

**Comment by chrismo** [comment]
I've update the bundler-cases PR with a case that recreates without any wistia involved, and the command which will dump out the proper output.

https://github.com/chrismo/bundler-cases/pull/8/files

**Comment by freerobby** [comment]
@chrismo Nice sleuthing, and thanks for the prompt investigation and details. I'm close this issue since it's a Rails release problem rather than a Bundler problem. Thanks again for your help.

**Comment by chrismo** [comment]
fwiw, not the first time the version conflict reporting has come up. it's a hard problem to solve i think (not sure) ... but could be there are better ways to report on these problems when version conflicts occur.
