### ISSUE TITLE
Include install instructions for macOS

### ISSUE THREAD

**Issue by fulldecent** [bundler/bundler#4946]
README.md claims:

 > Bundler makes sure Ruby applications run the same code on every machine.

However, further down, the install instructions say:

    gem install bundler

On macOS this produces:

 > ERROR:  While executing gem ... (Gem::FilePermissionError)
 >   You don't have write permissions for the /Library/Ruby/Gems/2.0.0 directory.

Please update the macOS install instructions.

**Comment by segiddins** [comment]
That's an issue with Apple's default Ruby installation, which attempts to install gems into `/Library`, which the user by default does not have access to -- it's not an issue with RubyGems, which is merely installing into the gem home that has been set

**Comment by olleolleolle** [comment]
@fulldecent The Ruby homepage mentions on its [Installing Ruby page](https://www.ruby-lang.org/en/documentation/installation/#homebrew) how to install latest Ruby to get around this issue.

**Comment by lynnco** [comment]
The readme should definitely mention (or at least hint) that OS X users will require different installation instructions. I created two issues for that https://github.com/bundler/bundler/issues/4986 https://github.com/bundler/bundler-site/issues/256. I'm going to close this issue but feel free to use it for discussion / mention any more instructions that do not work by default on OS X!
