### ISSUE TITLE
Unable to gem install bundler. "Operation not permitted @ chmod_internal"

### ISSUE THREAD

**Issue by PyraxV** [bundler/bundler#4948]
So at first I was having problems when trying to do "gem install bundler" as a normal user. It kept saying "Permission denied" so I used "sudo chmod 777 /home/pyrax/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/.codeclimate.yml". I no longer got a permissions error but I now have an error saying "Operation not permitted @ chmod_internal - /home/pyrax/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/.codeclimate.yml". Any help would be appreciated. I'm running Ubuntu 16.04"

Heres a picture of the error:

![geminstall](https://cloud.githubusercontent.com/assets/20305339/18233604/ac2af966-72a0-11e6-9344-98e7425f8c27.png)

**Comment by segiddins** [comment]
This looks like an issue with https://github.com/rubygems/rubygems, but it would be impossible for the rubygems team to debug this without more information about your environment.
