### ISSUE TITLE
[1.13] `bundle lock` command always force unlocks

### ISSUE THREAD

**Issue by indirect** [bundler/bundler#4957]
No matter how many times I run it, the `lock` command always unlocks and resolves again:

```
$ mkdir unlock; cd unlock
$ bundle init
$ bundle lock --verbose
Running `bundle lock    --add-platform  --remove-platform ` with bundler 1.13.0
Found changes from the lockfile, re-resolving dependencies because bundler is unlocking
$ bundle lock --verbose
Running `bundle lock    --add-platform  --remove-platform ` with bundler 1.13.0
Found changes from the lockfile, re-resolving dependencies because bundler is unlocking
```

**Comment by segiddins** [comment]
That is behaving as designed, I believe?

**Comment by indirect** [comment]
@segiddins are you saying it is intended that every single invocation of the `lock` command both force a resolve (even if the resolve is already complete and guaranteed to result in the same lockfile), and also that the flags `--add-plaform` and `--remove-platform` should always be passed to the command?

**Comment by segiddins** [comment]
> and also that the flags --add-plaform and --remove-platform should always be passed to the command

what do you mean? they don't always have to be passes

> it is intended that every single invocation of the lock command both force a resolve

I think the idea was that it would be like running `bundle update`, since if you just wanted `bundle install` you'd use the existing lockfile? I'm not sure exactly the rational used but that's how it's implemented

**Comment by indirect** [comment]
I see. :/ It should be the same as `bundle install` minus the installing of the gems. There's a separate flag to get the semantics of `update`, named `--update`.

**Comment by segiddins** [comment]
We can change the behavior, sure
