### ISSUE TITLE
An unexpected error occurred, and Bundler cannot continue

### ISSUE THREAD

**Issue by sapnasurase** [bundler/bundler#4962]
win@ABCD /c/Sites/Issue
$ bundle install
Fetching source index from https://rubygems.org/
Retrying fetcher due to error (2/4): Net::HTTPServerException 404 "Not Found"
Retrying fetcher due to error (3/4): Net::HTTPServerException 404 "Not Found"
Retrying fetcher due to error (4/4): Net::HTTPServerException 404 "Not Found"
## --- ERROR REPORT TEMPLATE ------------------------------------------------------
- What did you do?
  
  I ran the command `c:/RailsInstaller/Ruby2.2.0/bin/bundle install`
- What did you expect to happen?
  
  I expected Bundler to...
- What happened instead?
  
  Instead, what actually happened was...

Error details

```
Net::HTTPServerException: 404 "Not Found"
  c:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/net/http/response.rb:119:in `er
```

ror!'
      c:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/net/http/response.rb:128:in `va
lue'
      c:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/net/http.rb:915:in`connect'
      c:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
      c:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/net/http.rb:858:in`start'
      c:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/rubygems/request/http_pool.rb:4
2:in `setup_connection'
      c:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/rubygems/request/https_pool.rb:
6:in`setup_connection'
      c:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/rubygems/request/http_pool.rb:3
8:in `make_connection'
      c:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/rubygems/request/http_pool.rb:1
9:in`checkout'
      c:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/rubygems/request.rb:85:in `conn
ection_for'
      c:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/rubygems/request.rb:140:in`per
form_request'
      c:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/rubygems/request.rb:109:in `fet
ch'
      c:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/rubygems/remote_fetcher.rb:352:
in`request'
      c:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/rubygems/remote_fetcher.rb:237:
in `fetch_http'
      c:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/rubygems/remote_fetcher.rb:273:
in`fetch_path'
      c:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bu
ndler/rubygems_integration.rb:573:in `fetch_specs'
      c:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bu
ndler/rubygems_integration.rb:587:in`fetch_all_remote_specs'
      c:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bu
ndler/fetcher/index.rb:8:in `specs'
      c:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bu
ndler/fetcher.rb:111:in`block in specs'
      c:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bu
ndler/fetcher.rb:110:in `each'
      c:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bu
ndler/fetcher.rb:110:in`specs'
      c:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bu
ndler/fetcher.rb:100:in `block in specs_with_retry'
      c:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bu
ndler/retry.rb:38:in`call'
      c:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bu
ndler/retry.rb:38:in `run'
      c:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bu
ndler/retry.rb:28:in`attempt'
      c:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bu
ndler/fetcher.rb:99:in `specs_with_retry'
      c:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bu
ndler/source/rubygems.rb:340:in`block (2 levels) in remote_specs'
      c:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bu
ndler/source/rubygems.rb:338:in `each'
      c:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bu
ndler/source/rubygems.rb:338:in`block in remote_specs'
      c:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bu
ndler/index.rb:9:in `build'
      c:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bu
ndler/source/rubygems.rb:334:in`remote_specs'
      c:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bu
ndler/source/rubygems.rb:81:in `specs'
      c:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bu
ndler/definition.rb:209:in`block (2 levels) in index'
      c:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bu
ndler/definition.rb:207:in `each'
      c:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bu
ndler/definition.rb:207:in`block in index'
      c:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bu
ndler/index.rb:9:in `build'
      c:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bu
ndler/definition.rb:204:in`index'
      c:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bu
ndler/definition.rb:198:in `resolve'
      c:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bu

win@ABCD /c/Sites/Issue
$ gem install bundler
ERROR:  While executing gem ... (Net::HTTPServerException)
    404 "Not Found"

**Comment by lynnco** [comment]
This reads like an internet connection error, did you try it again ?

Also it would be much easier to read the error details as a single code block

**Comment by colby-swandale** [comment]
I'm closing this for now. If you're still experiencing your original issue don't be afraid to re-open this ticket.
