### ISSUE TITLE
Bundle gem doesn't quite generate a usable gem

### ISSUE THREAD

**Issue by izwick-schachter** [bundler/bundler#4964]
If you run `bundle gem mygem` bundler will generate a gem for you. If you want to generate tests by setting gem.test to minitest bundler will also do that for you. But then if you try to run the tests, it seems that the generated `mygem_test.rb` file uses `require 'test_helper'` when it should use `require_relative 'test_helper'`, because it will throw an load error because it can't find `test_helper`

**Comment by segiddins** [comment]
I think the proper thing here will be to properly setup the load path (which iirc rspec does automatically). Since I'm not familiar with minitest, I don't think I'll be able to look into a fix, but a PR would be appreciated!

**Comment by shubham-amura** [comment]
@izwick-schachter  i am interested to solve this , it would be appreciated if you could brief more about the exact issue .thanks. :)

**Comment by shuboid** [comment]
@izwick-schachter i am interested to solve this , it would be appreciated if you could brief more about the exact issue .thanks. :)

**Comment by izwick-schachter** [comment]
@shuboid I can cause this issue by following the following steps:
1. Run `bundle gem mygem`
2. Run `cd mygem/test`
3. Run `ruby mygem_test.rb`

This gives me the error:

```
/home/me/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- test_helper (LoadError)
	from /home/me/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from mygem_test.rb:1:in `<main>'
```

If it makes any difference my bundler config is:

gem.test = minitest
gem.mit = true
gem.coc = true

**Comment by colby-swandale** [comment]
This is working as intended. If you're calling a minispec test using `ruby` you need to set the load path correctly using `ruby -I lib:test test/mygem_test.rb`. The Rakefile also has a task to run your minispec tests.
