### ISSUE TITLE
Bundler cannot resolve right relative paths since version 1.11.2 (Test example attached)

### ISSUE THREAD

**Issue by the-teacher** [bundler/bundler#4966]
Hello, have no idea why it worked for me so long time and why I didn't meet it before, but looks like problem exists.

### My case

I have a rails based CMS. I use it for some projects. Some pojects based on this CMS have to use some specific gems. That is why in my `Gemfile` I use something like this:

```ruby
source 'https://rubygems.org'
gem 'rails'
eval_gemfile "./Gemfiles/#{ ENV['PROJECT_NAME'] }_specific_gems.rb"
```

Also, in my app I have
* a directory for specific Gemfiles (folder has name `Gemfiles`)
* a directory for specific gems (folder has name `gems`)

### The problem

Looks like since version `1.11.2` bundler cannot resolve right paths to my local gems.

When I use paths like this:

```ruby
gem 'gem1', path: './gems/gem1'
```

Bundler gives to me:

```
/PATH/TO/RELEASES/RAILS_CMS/current/Gemfiles/gems/gem1
```

But it should be `/PATH/TO/RELEASES/RAILS_CMS/current/gems/gem1`, and it was so before.

And when I use

```ruby
gem 'gem1', path: '../gems/gem1'
```

Bundler gives to me:

```
/PATH/TO/RELEASES/RAILS_CMS/gems/gem1
```

But actually I expected to get:

```ruby
/PATH/TO/RELEASES/RAILS_CMS/current/gems/gem1 # <= this one is right path, but it's impossible to get it somehow

/PATH/TO/RELEASES/RAILS_CMS/current/Gemfiles/gems/gem1 # <= this one is wrong 
/PATH/TO/RELEASES/RAILS_CMS/gems/gem1           # <= this one is wrong too
```

### TEST CASE

There is simple test case to reproduce my problem

https://github.com/the-forks/bundler_test_case

You can find steps to reproduce in a README.md

PS:
I tried to play with ENV `BUNDLE_GEMFILE`. It didn't help

**Comment by segiddins** [comment]
This was an intentional change. Bundler now expands relative paths relative to the _gemfile being evaluated's directory_ rather than the parent gemfile.

The following diff fixes things!

```diff
diff --git a/Gemfiles/specific_1.rb b/Gemfiles/specific_1.rb
index a9c9f87..afd8c8a 100644
--- a/Gemfiles/specific_1.rb
+++ b/Gemfiles/specific_1.rb
@@ -1,2 +1,2 @@
-gem 'gem1', path: './gems/gem1'
-gem 'gem2', path: './gems/gem2'
\ No newline at end of file
+gem 'gem1', path: './../gems/gem1'
+gem 'gem2', path: './../gems/gem2'
```

**Comment by the-teacher** [comment]
@segiddins Hello!
Thank you for your answer!
Unfortunately it doesn't work. 

If you haven't time to install and reproduce my case there is my video demo where I try to use your recommendation. 
 
https://drive.google.com/file/d/0B1E1Md_wjncLRV9iSHltdnJiRDQ/view?usp=sharing

Thanks for your help and time.

**Comment by the-teacher** [comment]
PS: I can reproduce this problem on my Mac and on my Debian 8.5 server on DigitalOcean & I user RVM.

**Comment by segiddins** [comment]
When applying my change, it passed on my machine, so perhaps another reproduction case is required?

**Comment by the-teacher** [comment]
@segiddins oh. Let me check it yet another time. It's really strange

**Comment by the-teacher** [comment]
@segiddins we tested it with my college on his local machine. He reproduced this bug. Problem exists.

To reproduce this bug you can just use this steps:

```ruby
rm -rf ./bundler_test_case

git clone git@github.com:the-forks/bundler_test_case.git
cd bundler_test_case

gem install bundler -v=1.13.0

bundler _1.13.0_
bundler _1.13.0_
```

Please, try it again. Do you really have not any issues?

**Comment by segiddins** [comment]
```
Fetching gem metadata from https://rubygems.org/.
Fetching version metadata from https://rubygems.org/
Resolving dependencies...
Using gem1 0.1.0 from source at `./../gems/gem1`
Using gem2 0.1.0 from source at `./../gems/gem2`
Using bundler 1.13.0
Bundle complete! 2 Gemfile dependencies, 3 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
```

**Comment by the-teacher** [comment]
@segiddins did you run `bundler _1.13.0_` twice?
it's not a mistype, you need to run it twice.
first time it can find gems - it's ok. But Gemfile.lock will have wrong paths, and on second time `bundler _1.13.0_` should give an error.

Sorry, that I disturb you, but I'm pretty sure that problem exists. 2 friends of mine produced it.

**Comment by the-teacher** [comment]
this is my `Gemfile.lock` after bundle

```ruby
PATH
  remote: ./../gems/gem1
  specs:
    gem1 (0.1.0)

PATH
  remote: ./../gems/gem2
  specs:
    gem2 (0.1.0)

GEM
  remote: https://rubygems.org/
  specs:

PLATFORMS
  ruby

DEPENDENCIES
  gem1!
  gem2!

BUNDLED WITH
   1.13.0
```

but it has to have paths like:

```ruby
PATH
  remote: ./gems/gem1
  specs:
    gem1 (0.1.0)

PATH
  remote: ./gems/gem2
  specs:
    gem2 (0.1.0)
```

**Comment by segiddins** [comment]
Never mind, it finally reproduced

**Comment by segiddins** [comment]
https://github.com/bundler/bundler/pull/4976 should fix this
