### ISSUE TITLE
Gems from optional groups not loaded with v1.13.0

### ISSUE THREAD

**Issue by svbergerem** [bundler/bundler#4969]
diaspora* uses optional groups for postgresql and mysql in the Gemfile. ([Gemfile](https://github.com/diaspora/diaspora/blob/0514545/Gemfile#L65-L70), [Gemfile.lock](https://github.com/diaspora/diaspora/blob/0514545/Gemfile.lock))

When installing gems including those from the optional groups (using `... --with postgresql`) the gems from the optional groups aren't loaded.

`bundle install`: https://travis-ci.org/diaspora/diaspora/jobs/158961200#L268
pg not loaded: https://travis-ci.org/diaspora/diaspora/jobs/158961200#L609

Going back to Bundler v1.12.5 fixed the problem. I'm sorry that I can't provide a minimal example but maybe someone else is able to do that or already knows what might have gone wrong.

**Comment by segiddins** [comment]
Where is your call to `Bundler.require`? Looking at the code, it's never seemed to take into account `--with` and has only ever required gems in the default group unless other groups are specifically passed as args to require

**Comment by besi** [comment]
I think the problem I ran into today is also related to this:
A rollback to v1.12 solved the problem as described here:
https://github.com/fastlane/fastlane/issues/6065#issuecomment-246044617

**Comment by svbergerem** [comment]
@segiddins Thank you! Looks like that fixed our problem: https://github.com/diaspora/diaspora/pull/7090. I'm still wondering why this worked before but at least for us this problem has been fixed.

**Comment by lynnco** [comment]
@segiddins have there been changes in `Bundler.require` in 1.13 that would need to be pointed out in the [blog post](http://bundler.io/blog/) ? I assume this was a use case that "accidentally" worked before but never had a test

**Comment by segiddins** [comment]
None that I can recall, and I don't think a blame turned up a smoking gun

**Comment by segiddins** [comment]
@indirect what's the desired behavior here? Should `Bundler.require` with no groups specified use _only_ the `:default` group, or should it use `Definition#requested_groups`, like `Bundler.setup` does?

**Comment by indirect** [comment]
@segiddins oof, that's a great question. I guess I would expect `require` to match `setup`?

**Comment by rafaelfranca** [comment]
Looking the Bundler.require line generate by the Rails generator it is expected to bundler require only the groups passed as argument to require. For Rails it is because we want to load only the default group and the group matching the environment that the application is being executed. Before when we had an assets group in the default gemfile we explicitly added it as a argument of require.

I think in this case setup and require makes sense to differ in behavior since require will load the code that you may not want.

**Comment by indirect** [comment]
Given the history of `require` defaulting to :default, and requiring all other groups to be passed by name, I think it's reasonable to stick with requiring all groups to be passed by name, even optional groups. 👍🏻

**Comment by segiddins** [comment]
Cool!
