### ISSUE TITLE
Change the github option or add a protocol option to the github option

### ISSUE THREAD

**Issue by zedtux** [bundler/bundler#4978]
> The git source `git://github.com/cubus/jquery-sparkline-rails.git` uses the `git` protocol, which transmits data without encryption. Disable this warning with `bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.

I just got this message today stating that I should use https instead of git, which makes sense.

I have the following line in my Gemfile:

```Gemfile
gem 'jquery-sparkline-rails', github: 'cubus/jquery-sparkline-rails'
```

Which is a really nice way to use a Github repo.

Honestly I do not care the protocol which is used to get that gem, so:

 - Change the protocol of the github to https (recommended)
 - Add a `:protocol` option which allows us to change it

**Comment by segiddins** [comment]
This will be updated in 2.0, or you can see the comment at https://github.com/bundler/bundler/blob/3e3f64f1166c4613329495459793dbd5a714efd3/lib/bundler/dsl.rb#L254 for alternatives

**Comment by zedtux** [comment]
Awesome, thank you @segiddins 👍

**Comment by odedniv** [comment]
Anyone coming here should know that the comment there is kind of misleading, best way to clear the warning and use HTTPS before the update to 2.0 is to opt in to the change with:

```bash
bundle config github.https true
```

Also, the code there says that in the warning, but my current bundler version (1.13.5) tells me to *suppress* the warning instead...

**Comment by san** [comment]
@odedniv Where would I add that line if I want to use this option that you mentioned?

**Comment by odedniv** [comment]
@san it's a bash command. Bundler then creates a config file under `~/.bundler/config` to remember this.

**Comment by joshuapinter** [comment]
Adding to @odedniv's comment, you should probably set this globally since it will be the default in Version 2, which you can do with: 

```bash
$ bundle config --global github.https true
```

This will then create (or amend) a `~/.bundle/config` file (in your home directory), with the following: 

```js
---
BUNDLE_GITHUB__HTTPS: "true"
```

**Comment by gkop** [comment]
@joshuapinter thanks for your solution.

Arguably you ought to also run this in your project directory and commit the local `.bundle/` directory to source control:

```
$ bundle config --local github.https true
```

The reason is that this option goes hand in hand with the changes you have committed to your Gemfile.lock .

Also, I believe it's best practice to use BUNDLE_FROZEN=true when bundling in your deployment build environment. If you use this option, then you must one way or another also ensure that BUNDLE_GITHUB__HTTPS=true is used in your deployment build environment as well.

**Comment by indirect** [comment]
Please don't check in your `.bundle` directory. If you need to apply this setting widely, use the environment variable instead.

**Comment by gkop** [comment]
Why not (just curious)?

Anyhow we can use environment variables, just be sure to export them; you can't get away with just passing BUNDLE_GITHUB__HTTPS=true to bundle install alone, you need to pass it to any commands that need to call `Bundler.require`.

**Comment by Dorian** [comment]
A better solution, so not everybody in your team has to run `bundle config --global github.https true`, add that to your `Gemfile`

```ruby
git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end
```

From bundler's source code: https://github.com/bundler/bundler/blob/3e3f64f1166c4613329495459793dbd5a714efd3/lib/bundler/dsl.rb#L254-L266

**Comment by henrik** [comment]
Any recommendations for `git://` references pointing to private repos on GitHub?

If I leave them as `git://`, it auths automagically. If I change to `https://`, it prompts me for my GitHub details when I bundle. I've seen a suggestion to upt an OAuth token in the URL – is that the recommended way to go about it?

**Comment by mroach** [comment]
@henrik Change line 3 of @Dorian's solution to `"git@github.com:#{repo_name}.git"` and you'll be all set. This will force the use of SSH instead of HTTPS and then your SSH keys work as expected.

**Comment by henrik** [comment]
@mroach Thank you! That's how I have them now – I guess I assumed I had to change them from that to `https://`, but now that I think about it again, of course they are SSH and not `git://`. Great :)

**Comment by ianks** [comment]
After setting `bundle config --global github.https true`, running `bundle` attempts to update the commit ref of the gem. Is there a way to make it not do this?

**Comment by indirect** [comment]
@ianks in retrospect, that option was a bad idea, because it will only apply on one machine—the same gemfile on other machines will try to use http, and it will create an infinite lockfile revert war between the machines with the setting set and the setting not set. I highly recommend that you use this at the top of your gemfile instead:

```ruby
git_source(:github) { |name| "https://github.com/#{name}.git" }
```

(Adjust code as needed based on your usage of the github option).

Back to your original question, the only way I know of off the top of my head is to hand-edit your lockfile at the same time, updating the URL to https.

**Comment by ianks** [comment]
@indirect Yup, I just ended up doing this: `sed -i 's/git:\/\//https:\/\//g' Gemfile.lock`

**Comment by whatcould** [comment]
I had the same issue and fix as @ianks, all the refs are blown away and suddenly my gems are updated!

On MacOS (with BSD sed) I had to run this: `sed -i '' 's/git:\/\//https:\/\//g' Gemfile.lock` Hope that saves somebody a little time. & thanks for the tip!)
