### ISSUE TITLE
"bundle install" deadlock trying to use ":git" with Rails

### ISSUE THREAD

**Issue by wincent** [bundler/bundler#498]
I'm trying to bisect a problem in Rails so want to be able to lock it down to a specific version for testing within an app. So in my `Gemfile` I add:

```
gem 'rails', :git => 'git://github.com/rails/rails.git',
             :ref => 'bd1666ad1de88598ed6f04ceffb8488a77be4385'
```

`bundle check` (1.0.0.rc.1) shows, as expected:

```
$ bundle check
The git source git://github.com/rails/rails.git is not yet checked out. Please run `bundle install` before trying to start your application
```

But `bundle install` tells me to run `bundle install` first:

```
$ bundle install
git://github.com/rails/rails.git (at bd1666a) is not checked out. Please run `bundle install`
```

Similar results if we drop the `:ref` from the `Gemfile`:

```
git://github.com/rails/rails.git (at master) is not checked out. Please run `bundle install`
```

No idea if using a specific version of Rails in this way is supported, but even if it isn't Bundler should never tell somebody running `bundle install` to run `bundle install`.

Workaround for now: use `:path` instead:

```
gem 'rails', :path => 'path/to/local/rails.git'
```

**Comment by thejamespinto** [comment]
@wycats @wincent I'd love to know how to fix the "subtle bug", this actually happens a bit often with me

**Comment by indirect** [comment]
@thejamespinto this bug is four years old, and fixed. if you're seeing a problem with Bundler today, follow [ISSUES](https://github.com/bundler/bundler/blob/master/ISSUES.md).
