### ISSUE TITLE
>=1.13.0.rc.2 does not vendor correctly

### ISSUE THREAD

**Issue by Jeppesen-io** [bundler/bundler#4985]
When running `bundle install --deployment` on >=1.13.0.rc.2, only gems not in $HOME/.rbenv are copied in to `./vendor/bundle`. I see the same in 1.13.0 and 1.13.1.

#### Unexpected behaviour in 1.13.0.rc.2 and above
```
$ rm -rf vendor && bundle _1.13.0.rc.2_ install --deployment
Using rake 11.2.2
Using CFPropertyList 2.3.2
...
```
Notice it does not say 'Fetching gem....'
Looking in vendor dir, `rake` is not found
```
$ find vendor -name rake
$
```

#### Expected behaviour in 1.13.0.rc.1 and below
```
$ rm -rf vendor && bundle _1.13.0.rc.1_ install --deployment
Fetching gem metadata from https://rubygems.org/
Fetching version metadata from https://rubygems.org/
Fetching dependency metadata from https://rubygems.org/
Installing rake 11.2.2
Installing CFPropertyList 2.3.2
...
```
Looking in vendor dir, the `rake` is found

```
$ find vendor -name rake
vendor/bundle/ruby/2.1.0/bin/rake
vendor/bundle/ruby/2.1.0/gems/rake-11.2.2/exe/rake
vendor/bundle/ruby/2.1.0/gems/rake-11.2.2/lib/rake
$
```

**Comment by chrismo** [comment]
This looks to be the same issue reported here: #4974
