### ISSUE TITLE
Move some help files from bundler/bundler site to man/ ?

### ISSUE THREAD

**Issue by lynnco** [bundler/bundler#4988]
An problem illuminated by this issue https://github.com/bundler/bundler/issues/4940 is that it's very confusing whether a particular piece of documentation should be in this repo, or in bundler/bundler-site. Many of those pages might be better if they were inside of  bundler/bundler's `man/`.

Good candidates?
- https://github.com/bundler/bundler-site/blob/master/source/v1.13/bundle_clean.html.haml
- https://github.com/bundler/bundler-site/blob/master/source/v1.13/bundle_check.html.haml

**Comment by segiddins** [comment]
Yes, all the command docs should be manpages

**Comment by feministy** [comment]
i moved over everything that was missing but had a page in bundler site in #5348 - if y'all wouldn't mind giving it a once over that would be aces. thanks!

**Comment by segiddins** [comment]
Done in https://github.com/bundler/bundler/pull/5348
