### ISSUE TITLE
Locked bundle

### ISSUE THREAD

**Issue by barhinn** [bundler/bundler#4993]
- What did you do?

  I ran the command `/Users/user/.rvm/gems/ruby-2.3.0/bin/bundle install`

- What did you expect to happen?

  I expected Bundler to install missing gems

- What happened instead?

  Instead, what happened was it says bundle is locked to rake (11.2.2), but that version could not be found in any of the sources listed in your Gemfile. If you haven't changed sources, that means the author of rake (11.2.2) has removed it. You'll need to update your bundle to a different version of rake (11.2.2) that hasn't been removed in order to install.

Error details

    Errno::EACCES: Permission denied @ dir_s_mkdir - /Users/barhinn/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/versions20160915-65434-16qa3h
      /Users/user/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tmpdir.rb:86:in `mkdir'
      /Users/user/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tmpdir.rb:86:in `block in mktmpdir'
      /Users/user/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tmpdir.rb:130:in `create'
      /Users/user/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tmpdir.rb:86:in `mktmpdir'
      /Users/user/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.1/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:29:in `update'
      /Users/user/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.1/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:64:in `update'
      /Users/user/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.1/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:55:in `update_and_parse_checksums!'
      /Users/user/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.1/lib/bundler/fetcher/compact_index.rb:67:in `available?'
      /Users/user/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.1/lib/bundler/fetcher/compact_index.rb:15:in `call'
      /Users/user/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.1/lib/bundler/fetcher/compact_index.rb:15:in `block in compact_index_request'
      /Users/user/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.1/lib/bundler/fetcher.rb:157:in `use_api'
      /Users/user/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.1/lib/bundler/source/rubygems.rb:332:in `block in api_fetchers'
      /Users/user/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.1/lib/bundler/source/rubygems.rb:332:in `select'
      /Users/user/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.1/lib/bundler/source/rubygems.rb:332:in `api_fetchers'
      /Users/user/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.1/lib/bundler/source/rubygems.rb:337:in `block in remote_specs'
      /Users/user/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.1/lib/bundler/index.rb:10:in `build'
      /Users/user/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.1/lib/bundler/source/rubygems.rb:336:in `remote_specs'
      /Users/user/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.1/lib/bundler/source/rubygems.rb:83:in `specs'
      /Users/user/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.1/lib/bundler/lazy_specification.rb:58:in `__materialize__'
      /Users/user/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.1/lib/bundler/spec_set.rb:91:in `block in materialize'
      /Users/user/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.1/lib/bundler/spec_set.rb:88:in `map!'
      /Users/user/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.1/lib/bundler/spec_set.rb:88:in `materialize'
      /Users/user/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.1/lib/bundler/definition.rb:176:in `specs'
      /Users/user/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.1/lib/bundler/definition.rb:164:in `resolve_remotely!'
      /Users/user/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.1/lib/bundler/installer.rb:225:in `resolve_if_need'
      /Users/user/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.1/lib/bundler/installer.rb:78:in `run'
      /Users/user/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.1/lib/bundler/installer.rb:24:in `install'
      /Users/user/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.1/lib/bundler/cli/install.rb:71:in `run'
      /Users/user/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.1/lib/bundler/cli.rb:189:in `install'
      /Users/user/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /Users/user/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /Users/user/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.1/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /Users/user/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.1/lib/bundler/cli.rb:20:in `dispatch'
      /Users/user/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.1/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /Users/user/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.1/lib/bundler/cli.rb:11:in `start'
      /Users/user/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.1/exe/bundle:34:in `block in <top (required)>'
      /Users/user/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.1/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
      /Users/user/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.1/exe/bundle:26:in `<top (required)>'
      /Users/user/.rvm/gems/ruby-2.3.0/bin/bundle:23:in `load'
      /Users/user/.rvm/gems/ruby-2.3.0/bin/bundle:23:in `<main>'
      /Users/user/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
      /Users/user/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'

Environment
      
  Bundler   1.13.1
  Rubygems  2.5.1
  Ruby      2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
  GEM_HOME  /Users/user/.rvm/gems/ruby-2.3.0
  GEM_PATH  /Users/user/.rvm/gems/ruby-2.3.0:/Users/user/.rvm/gems/ruby-2.3.0@global
  RVM       1.27.0 (latest)
  Git       2.10.0
  rubygems-bundler (1.4.4)

**Comment by edgarlepe** [comment]
I'm getting the same thing with
Rubygems 2.6.6
Bundler 1.13.1
Rake 11.2.2
Ruby 2.3.1
but using rbenv

**Comment by bjhartin** [comment]
Getting the same thing on Ubuntu with:

Rubygems: 2.5.1
Bundler version 1.13.1
Ruby: 2.3.1 (2016-04-26 patchlevel 112) [x86_64-linux]

but not on OSX with:

Rubygems: 2.5.1
Bundler version 1.13.1
Ruby: 2.3.0 (2015-12-25 patchlevel 0) [x86_64-darwin14]
RVM: 1.27.0 (latest)

`gem search aruba -a` shows the gem in question (Aruba 0.14.1) is available, although there is a newer version

**Comment by lynnco** [comment]
@barhinn you mentioned the `that version could not be found in any of the sources listed in your Gemfile` error message, but the problem you are trying to resolve is the `Errno::EACCES: Permission denied @ dir_s_mkdir`, correct?

**Comment by lynnco** [comment]
@edgarlepe @barhinn 

Can you specify which or the two issues mentioned you are experiencing? Preferably with full error messages?

**Comment by lynnco** [comment]
(last comment)

Check out how the other issues with permission errors were resolved, like #4590, #4458, #4431, #4429. Let us know if any of those worked for you.

**Comment by edgarlepe** [comment]
@lynnco I'm getting the error:
```
Bundler gave the error "Your bundle is locked to rake (11.2.2), but that version
could not be found in any of the sources listed in your Gemfile. If you haven't
changed sources, that means the author of rake (11.2.2) has removed it. You'll
need to update your bundle to a different version of rake (11.2.2) that hasn't been
removed in order to install." while processing "/Users/edgarlepe/Developer/app-api/Gemfile".
Perhaps you forgot to run "bundle install"?
```

`bundle install --verbose` output:
```
Running `bundle install --verbose` with bundler 1.13.1
Found no changes, using resolution from the lockfile
Using rake 11.2.2
0:  rake (11.2.2) from /Users/edgarlepe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/specifications/rake-11.2.2.gemspec
Using concurrent-ruby 1.0.2
0:  concurrent-ruby (1.0.2) from /Users/edgarlepe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/specifications/concurrent-ruby-1.0.2.gemspec
Using i18n 0.7.0
0:  i18n (0.7.0) from /Users/edgarlepe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/specifications/i18n-0.7.0.gemspec
Using minitest 5.9.0
0:  minitest (5.9.0) from /Users/edgarlepe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/specifications/minitest-5.9.0.gemspec
Using thread_safe 0.3.5
0:  thread_safe (0.3.5) from /Users/edgarlepe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/specifications/thread_safe-0.3.5.gemspec
Using builder 3.2.2
0:  builder (3.2.2) from /Users/edgarlepe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/specifications/builder-3.2.2.gemspec
Using erubis 2.7.0
0:  erubis (2.7.0) from /Users/edgarlepe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/specifications/erubis-2.7.0.gemspec
Using mini_portile2 2.1.0
0:  mini_portile2 (2.1.0) from /Users/edgarlepe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/specifications/mini_portile2-2.1.0.gemspec
Using pkg-config 1.1.7
0:  pkg-config (1.1.7) from /Users/edgarlepe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/specifications/pkg-config-1.1.7.gemspec
Using rack 2.0.1
0:  rack (2.0.1) from /Users/edgarlepe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/specifications/rack-2.0.1.gemspec
Using nio4r 1.2.1
0:  nio4r (1.2.1) from /Users/edgarlepe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/specifications/nio4r-1.2.1.gemspec
Using websocket-extensions 0.1.2
0:  websocket-extensions (0.1.2) from /Users/edgarlepe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/specifications/websocket-extensions-0.1.2.gemspec
Using mime-types-data 3.2016.0521
0:  mime-types-data (3.2016.0521) from /Users/edgarlepe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/specifications/mime-types-data-3.2016.0521.gemspec
Using arel 7.1.2
0:  arel (7.1.2) from /Users/edgarlepe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/specifications/arel-7.1.2.gemspec
Using byebug 9.0.5
0:  byebug (9.0.5) from /Users/edgarlepe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/specifications/byebug-9.0.5.gemspec
Using ffi 1.9.14
0:  ffi (1.9.14) from /Users/edgarlepe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/specifications/ffi-1.9.14.gemspec
Using rb-fsevent 0.9.7
0:  rb-fsevent (0.9.7) from /Users/edgarlepe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/specifications/rb-fsevent-0.9.7.gemspec
Using method_source 0.8.2
0:  method_source (0.8.2) from /Users/edgarlepe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/specifications/method_source-0.8.2.gemspec
Using pg 0.18.4
0:  pg (0.18.4) from /Users/edgarlepe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/specifications/pg-0.18.4.gemspec
Using puma 3.6.0
0:  puma (3.6.0) from /Users/edgarlepe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/specifications/puma-3.6.0.gemspec
Using bundler 1.13.1
0:  bundler (1.13.1) from /Users/edgarlepe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/specifications/bundler-1.13.1.gemspec
Using thor 0.19.1
0:  thor (0.19.1) from /Users/edgarlepe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/specifications/thor-0.19.1.gemspec
Using spring 1.7.2
0:  spring (1.7.2) from /Users/edgarlepe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/specifications/spring-1.7.2.gemspec
Using tzinfo 1.2.2
0:  tzinfo (1.2.2) from /Users/edgarlepe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/specifications/tzinfo-1.2.2.gemspec
Using nokogiri 1.6.8
0:  nokogiri (1.6.8) from /Users/edgarlepe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/specifications/nokogiri-1.6.8.gemspec
Using rack-test 0.6.3
0:  rack-test (0.6.3) from /Users/edgarlepe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/specifications/rack-test-0.6.3.gemspec
Using sprockets 3.7.0
0:  sprockets (3.7.0) from /Users/edgarlepe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/specifications/sprockets-3.7.0.gemspec
Using websocket-driver 0.6.4
0:  websocket-driver (0.6.4) from /Users/edgarlepe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/specifications/websocket-driver-0.6.4.gemspec
Using mime-types 3.1
0:  mime-types (3.1) from /Users/edgarlepe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/specifications/mime-types-3.1.gemspec
Using rb-inotify 0.9.7
0:  rb-inotify (0.9.7) from /Users/edgarlepe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/specifications/rb-inotify-0.9.7.gemspec
Using activesupport 5.0.0.1
0:  activesupport (5.0.0.1) from /Users/edgarlepe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/specifications/activesupport-5.0.0.1.gemspec
Using loofah 2.0.3
0:  loofah (2.0.3) from /Users/edgarlepe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/specifications/loofah-2.0.3.gemspec
Using mail 2.6.4
0:  mail (2.6.4) from /Users/edgarlepe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/specifications/mail-2.6.4.gemspec
Using listen 3.0.8
0:  listen (3.0.8) from /Users/edgarlepe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/specifications/listen-3.0.8.gemspec
Using rails-dom-testing 2.0.1
0:  rails-dom-testing (2.0.1) from /Users/edgarlepe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/specifications/rails-dom-testing-2.0.1.gemspec
Using globalid 0.3.7
0:  globalid (0.3.7) from /Users/edgarlepe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/specifications/globalid-0.3.7.gemspec
Using activemodel 5.0.0.1
0:  activemodel (5.0.0.1) from /Users/edgarlepe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/specifications/activemodel-5.0.0.1.gemspec
Using rails-html-sanitizer 1.0.3
0:  rails-html-sanitizer (1.0.3) from /Users/edgarlepe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/specifications/rails-html-sanitizer-1.0.3.gemspec
Using spring-watcher-listen 2.0.0
0:  spring-watcher-listen (2.0.0) from /Users/edgarlepe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/specifications/spring-watcher-listen-2.0.0.gemspec
Using activejob 5.0.0.1
0:  activejob (5.0.0.1) from /Users/edgarlepe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/specifications/activejob-5.0.0.1.gemspec
Using activerecord 5.0.0.1
0:  activerecord (5.0.0.1) from /Users/edgarlepe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/specifications/activerecord-5.0.0.1.gemspec
Using actionview 5.0.0.1
0:  actionview (5.0.0.1) from /Users/edgarlepe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/specifications/actionview-5.0.0.1.gemspec
Using actionpack 5.0.0.1
0:  actionpack (5.0.0.1) from /Users/edgarlepe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/specifications/actionpack-5.0.0.1.gemspec
Using actioncable 5.0.0.1
0:  actioncable (5.0.0.1) from /Users/edgarlepe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/specifications/actioncable-5.0.0.1.gemspec
Using actionmailer 5.0.0.1
0:  actionmailer (5.0.0.1) from /Users/edgarlepe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/specifications/actionmailer-5.0.0.1.gemspec
Using railties 5.0.0.1
0:  railties (5.0.0.1) from /Users/edgarlepe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/specifications/railties-5.0.0.1.gemspec
Using sprockets-rails 3.2.0
0:  sprockets-rails (3.2.0) from /Users/edgarlepe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/specifications/sprockets-rails-3.2.0.gemspec
Using rails 5.0.0.1
0:  rails (5.0.0.1) from /Users/edgarlepe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/specifications/rails-5.0.0.1.gemspec
Bundle complete! 8 Gemfile dependencies, 48 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
Bundler gave the error "Your bundle is locked to rake (11.2.2), but that version could not be found in any of the sources listed in your Gemfile. If you haven't changed sources, that means the author of rake (11.2.2) has removed it. You'll need to update your bundle to a different version of rake (11.2.2) that hasn't been removed in order to install." while processing "/Users/edgarlepe/Developer/app-api/Gemfile". Perhaps you forgot to run "bundle install"?
```

```
$ bundle show rake
/Users/edgarlepe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.2.2
$ bundle show bundler
/Users/edgarlepe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.1
```

**Comment by chrismo** [comment]
@edgarlepe can you copy in the results of `bundle env` ?

**Comment by yokoto** [comment]
I'm experiencing same issues.
After I ran `bundle exec rake db:create`, 
```
Your bundle is locked to rake (11.3.0), but that version could not be found in any
 of the sources listed in your Gemfile. If you haven't changed sources, that means 
the author of rake (11.3.0) has removed it. You'll need to update your bundle to 
a different version of rake (11.3.0) that hasn't been removed in order to install.
Run `bundle install` to install missing gems.
```

Environment:
rubygems 2.4.5.1
bundler 1.13.1
rake 11.3.0
ruby 2.2.3 (using rbenv)

**Comment by lynnco** [comment]
Closing this issue in favor of https://github.com/bundler/bundler/issues/5068
