### ISSUE TITLE
Error Create App in Ruby on Rails

### ISSUE THREAD

**Issue by rizaldimaulidia** [bundler/bundler#4995]
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/exe/bundle install`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what happened was...

Error details

    Errno::EACCES: Permission denied @ dir_s_mkdir - /home/rizaldi/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/versions20160916-20678-1xg46m6
      /usr/local/lib/ruby/2.3.0/tmpdir.rb:86:in `mkdir'
      /usr/local/lib/ruby/2.3.0/tmpdir.rb:86:in `block in mktmpdir'
      /usr/local/lib/ruby/2.3.0/tmpdir.rb:130:in `create'
      /usr/local/lib/ruby/2.3.0/tmpdir.rb:86:in `mktmpdir'
      /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:29:in `update'
      /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:64:in `update'
      /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:55:in `update_and_parse_checksums!'
      /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/fetcher/compact_index.rb:67:in `available?'
      /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/fetcher/compact_index.rb:15:in `call'
      /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/fetcher/compact_index.rb:15:in `block in compact_index_request'
      /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/fetcher.rb:157:in `use_api'
      /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/source/rubygems.rb:332:in `block in api_fetchers'
      /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/source/rubygems.rb:332:in `select'
      /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/source/rubygems.rb:332:in `api_fetchers'
      /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/source/rubygems.rb:337:in `block in remote_specs'
      /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/index.rb:10:in `build'
      /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/source/rubygems.rb:336:in `remote_specs'
      /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/source/rubygems.rb:83:in `specs'
      /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/definition.rb:263:in `block (2 levels) in index'
      /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/definition.rb:261:in `each'
      /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/definition.rb:261:in `block in index'
      /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/index.rb:10:in `build'
      /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/definition.rb:258:in `index'
      /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/definition.rb:252:in `resolve'
      /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/definition.rb:176:in `specs'
      /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/definition.rb:164:in `resolve_remotely!'
      /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/installer.rb:225:in `resolve_if_need'
      /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/installer.rb:78:in `run'
      /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/installer.rb:24:in `install'
      /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/cli/install.rb:71:in `run'
      /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/cli.rb:189:in `install'
      /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/cli.rb:20:in `dispatch'
      /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/cli.rb:11:in `start'
      /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/exe/bundle:34:in `block in <main>'
      /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
      /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/exe/bundle:26:in `<main>'

Environment
      
  Bundler   1.13.1
  Rubygems  2.5.1
  Ruby      2.3.1p112 (2016-04-26 revision 54768) [i686-linux]
  GEM_HOME  /usr/local/lib/ruby/gems/2.3.0
  GEM_PATH  /usr/local/lib/ruby/gems/2.3.0:/home/rizaldi/.gem/ruby/2.3.0
  Git       1.9.1
--- TEMPLATE END ----------------------------------------------------------------

**Comment by hmistry** [comment]
The error is because bundler does not have permissions to access that folder. Please check your folder permissions and try again. 

Also, check out how the other issues with permission errors were resolved, like #4458, #4429. Let us know if you still have problems after you've got the right folder permissions set.

**Comment by rizaldi-github** [comment]
I have solved that's problem. I tried to sign in as root in my terminal (linux ubuntu) before I create an app. 

Whether it's okay if I sign in as root first before making app?

**Comment by hmistry** [comment]
Typically we avoid having to sign in as `root`. We use a ruby manager like [rvm](https://rvm.io) or [rbenv](https://github.com/rbenv/rbenv) to install and manage ruby versions and their respective gems without needing to sign in as `root`.

**Comment by lynnco** [comment]
@hmistry
