### ISSUE TITLE
Bundler error

### ISSUE THREAD

**Issue by brownstaar** [bundler/bundler#4996]
- What did you do?

  I ran the command `/Users/Hisham/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.3/exe/bundle install`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what actually happened was...

Error details

    Errno::EACCES: Permission denied @ rb_sysopen - /Users/Hisham/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/versions
      /Users/Hisham/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.3/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:44:in `initialize'
      /Users/Hisham/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.3/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:44:in `open'
      /Users/Hisham/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.3/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:44:in `open'
      /Users/Hisham/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.3/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:44:in `update'
      /Users/Hisham/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.3/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:64:in `update'
      /Users/Hisham/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.3/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:55:in `update_and_parse_checksums!'
      /Users/Hisham/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.3/lib/bundler/fetcher/compact_index.rb:65:in `available?'
      /Users/Hisham/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.3/lib/bundler/fetcher/compact_index.rb:15:in `call'
      /Users/Hisham/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.3/lib/bundler/fetcher/compact_index.rb:15:in `block in compact_index_request'
      /Users/Hisham/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.3/lib/bundler/fetcher.rb:154:in `use_api'
      /Users/Hisham/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.3/lib/bundler/source/rubygems.rb:331:in `block in api_fetchers'
      /Users/Hisham/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.3/lib/bundler/source/rubygems.rb:331:in `select'
      /Users/Hisham/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.3/lib/bundler/source/rubygems.rb:331:in `api_fetchers'
      /Users/Hisham/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.3/lib/bundler/source/rubygems.rb:336:in `block in remote_specs'
      /Users/Hisham/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.3/lib/bundler/index.rb:10:in `build'
      /Users/Hisham/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.3/lib/bundler/source/rubygems.rb:335:in `remote_specs'
      /Users/Hisham/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.3/lib/bundler/source/rubygems.rb:82:in `specs'
      /Users/Hisham/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.3/lib/bundler/definition.rb:211:in `block (2 levels) in index'
      /Users/Hisham/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.3/lib/bundler/definition.rb:209:in `each'
      /Users/Hisham/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.3/lib/bundler/definition.rb:209:in `block in index'
      /Users/Hisham/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.3/lib/bundler/index.rb:10:in `build'
      /Users/Hisham/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.3/lib/bundler/definition.rb:206:in `index'
      /Users/Hisham/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.3/lib/bundler/definition.rb:200:in `resolve'
      /Users/Hisham/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.3/lib/bundler/definition.rb:140:in `specs'
      /Users/Hisham/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.3/lib/bundler/definition.rb:129:in `resolve_remotely!'
      /Users/Hisham/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.3/lib/bundler/installer.rb:195:in `resolve_if_need'
      /Users/Hisham/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.3/lib/bundler/installer.rb:70:in `run'
      /Users/Hisham/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.3/lib/bundler/installer.rb:22:in `install'
      /usr/local/Cellar/rbenv/1.0.0/rbenv.d/exec/gem-rehash/rubygems_plugin.rb:27:in `install'
      /Users/Hisham/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.3/lib/bundler/cli/install.rb:102:in `run'
      /Users/Hisham/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.3/lib/bundler/cli.rb:175:in `install'
      /Users/Hisham/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /Users/Hisham/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /Users/Hisham/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.3/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /Users/Hisham/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.3/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /Users/Hisham/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.3/lib/bundler/cli.rb:11:in `start'
      /Users/Hisham/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.3/exe/bundle:27:in `block in <main>'
      /Users/Hisham/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.3/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
      /Users/Hisham/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.3/exe/bundle:19:in `<main>'

Environment
      
  Bundler   1.12.3
  Rubygems  2.5.1
  Ruby      2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
  GEM_HOME  /Users/Hisham/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0
  GEM_PATH  /Users/Hisham/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0:/Users/Hisham/.gem/ruby/2.3.0
  RVM       1.27.0 (latest)
  Git       2.3.8 (Apple Git-58)
      
      Bundler settings
      
  orig_path
    Set via BUNDLE_ORIG_PATH: "/Users/Hisham/.rbenv/versions/2.3.0/bin:/usr/local/Cellar/rbenv/1.0.0/libexec:/Users/Hisham/.rbenv/shims:/usr/local/git/bin:/usr/local/bin:/usr/local/sbin:/usr/local/git/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/Hisham/.rvm/bin"
--- TEMPLATE END ----------------------------------------------------------------

**Comment by hmistry** [comment]
The error is because bundler does not have permissions to access that folder. Please check your folder permissions and try again.

See the solutions in the other issues with permission errors were resolved, like #4458, #4429, and #4431. One user found upgrading Bundler >1.12.4 worked for them. Let us know if you still have problems after you've got the right folder permissions set and using a newer version of bundler.

**Comment by lynnco** [comment]
Closing as @hmistry's comment is the most likely resolution. @brownstaar please follow up with us if you are still experiencing issues.
