### ISSUE TITLE
missing lots of gems in cache after 1.12.5->1.13.1

### ISSUE THREAD

**Issue by abiacco** [bundler/bundler#4997]
- What did you do?

$JRUBY_HOME/bin/bundle install --path=/data/build/New-Dashboard/vendor/bundle
$JRUBY_HOME/bin/bundle package --all

- What did you expect to happen?

Create all gems in cache

- What happened instead?

Not all gems put in cache

**.bundle/config**
    ---
BUNDLE_PATH: "/data/build/New-Dashboard/vendor/bundle"
BUNDLE_DISABLE_SHARED_GEMS: "true"
BUNDLE_CACHE_ALL: "true"

When upgrading from 1.12.5 to 1.13.1 (tried 1.13.0 also with same results) and running the above commands, the package command is not caching all of my gems.
I'm on CentOS 6.8, jruby 9.1.5.0, java 8u101

**1.12.5**
ls -1 vendor/cache | wc -l
163
ls -1 vendor/bundle/jruby/2.3.0/gems | wc -l
159

The difference of 4 in the cache directory is 3 git path gems and the json gem from jruby.

**1.13.1**
ls -1 vendor/cache | wc -l
110
ls -1 vendor/bundle/jruby/2.3.0/gems | wc -l
155

The difference from 159 to 155 in bundle now is that the following gems are missing (i do have these in my jruby install so this difference might be expected in the new version):

jruby-jars
jruby-rack
rubyzip
warbler

As you can see, the cache gems have gone from 163 to 110, a boatload are missing.
It does show them in the output of the package command as:
**Using gem_name**
but then does not list the missing ones after
**Updating files in vendor/cache**

One other thing to note (whether it matters or not), at the end of the package output i get:
**Could not find jruby-jars-9.1.5.0.gem for installation**
which i never saw before.

Any help is appreciated

-Tony

**Comment by chrismo** [comment]
Sorry about that. We're aware of the problem and a PR is in-progress: #4992.
