### ISSUE TITLE
Problems with bundle install in bash Ubuntu windows 10

### ISSUE THREAD

**Issue by Mr-kto** [bundler/bundler#4999]
- What did you do?

  I ran the command `/home/TarasKovalenko/.rvm/gems/ruby-2.3.0/bin/bundle install`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what happened was...

Error details

 

>    ArgumentError: parent directory is world writable but not sticky
>       /home/TarasKovalenko/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tmpdir.rb:93:in `ensure in mktmpdir'
>       /home/TarasKovalenko/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tmpdir.rb:95:in `mktmpdir'
>       /home/TarasKovalenko/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.1/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:29:in `update'
>       /home/TarasKovalenko/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.1/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:64:in `update'
>       /home/TarasKovalenko/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.1/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:55:in `update_and_parse_checksums!'
>       /home/TarasKovalenko/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.1/lib/bundler/fetcher/compact_index.rb:67:in `available?'
>       /home/TarasKovalenko/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.1/lib/bundler/fetcher/compact_index.rb:15:in `call'
>       /home/TarasKovalenko/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.1/lib/bundler/fetcher/compact_index.rb:15:in `block in compact_index_request'
>       /home/TarasKovalenko/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.1/lib/bundler/fetcher.rb:157:in `use_api'
>       /home/TarasKovalenko/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.1/lib/bundler/source/rubygems.rb:332:in `block in api_fetchers'
>       /home/TarasKovalenko/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.1/lib/bundler/source/rubygems.rb:332:in `select'
>       /home/TarasKovalenko/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.1/lib/bundler/source/rubygems.rb:332:in `api_fetchers'
>       /home/TarasKovalenko/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.1/lib/bundler/source/rubygems.rb:337:in `block in remote_specs'
>       /home/TarasKovalenko/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.1/lib/bundler/index.rb:10:in `build'
>       /home/TarasKovalenko/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.1/lib/bundler/source/rubygems.rb:336:in `remote_specs'
>       /home/TarasKovalenko/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.1/lib/bundler/source/rubygems.rb:83:in `specs'
>       /home/TarasKovalenko/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.1/lib/bundler/definition.rb:263:in `block (2 levels) in index'
>       /home/TarasKovalenko/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.1/lib/bundler/definition.rb:261:in `each'
>       /home/TarasKovalenko/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.1/lib/bundler/definition.rb:261:in `block in index'
>       /home/TarasKovalenko/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.1/lib/bundler/index.rb:10:in `build'
>       /home/TarasKovalenko/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.1/lib/bundler/definition.rb:258:in `index'
>       /home/TarasKovalenko/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.1/lib/bundler/definition.rb:252:in `resolve'
>       /home/TarasKovalenko/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.1/lib/bundler/definition.rb:176:in `specs'
>       /home/TarasKovalenko/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.1/lib/bundler/definition.rb:164:in `resolve_remotely!'
>       /home/TarasKovalenko/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.1/lib/bundler/installer.rb:225:in `resolve_if_need'
>       /home/TarasKovalenko/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.1/lib/bundler/installer.rb:78:in `run'
>       /home/TarasKovalenko/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.1/lib/bundler/installer.rb:24:in `install'
>       /home/TarasKovalenko/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.1/lib/bundler/cli/install.rb:71:in `run'
>       /home/TarasKovalenko/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.1/lib/bundler/cli.rb:189:in `install'
>       /home/TarasKovalenko/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
>       /home/TarasKovalenko/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
>       /home/TarasKovalenko/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.1/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
>       /home/TarasKovalenko/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.1/lib/bundler/cli.rb:20:in `dispatch'
>       /home/TarasKovalenko/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.1/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
>       /home/TarasKovalenko/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.1/lib/bundler/cli.rb:11:in `start'
>       /home/TarasKovalenko/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.1/exe/bundle:34:in `block in <top (required)>'
>       /home/TarasKovalenko/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.1/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
>       /home/TarasKovalenko/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.1/exe/bundle:26:in `<top (required)>'
>       /home/TarasKovalenko/.rvm/gems/ruby-2.3.0/bin/bundle:23:in `load'
>       /home/TarasKovalenko/.rvm/gems/ruby-2.3.0/bin/bundle:23:in `<main>'
>       /home/TarasKovalenko/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
>       /home/TarasKovalenko/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'

Environment
```
  Bundler   1.13.1
  Rubygems  2.5.1
  Ruby      2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]
  GEM_HOME  /home/TarasKovalenko/.rvm/gems/ruby-2.3.0
  GEM_PATH  /home/TarasKovalenko/.rvm/gems/ruby-2.3.0:/home/TarasKovalenko/.rvm/gems/ruby-2.3.0@global
  RVM       1.27.0 (latest)
  Git       1.9.1
  rubygems-bundler (1.4.4)
```

**Comment by Mr-kto** [comment]
just install a older version of bundler
first `gem uninstall bundler `and say yes to all and next use
`gem install bundler -v 1.12.3`

[https://github.com/bundler/bundler/issues/4599](https://github.com/bundler/bundler/issues/4599)

**Comment by lynnco** [comment]
This is a known issue, sorry :( https://github.com/bundler/bundler/issues/4599#issuecomment-234497615
