### ISSUE TITLE
V1.13.1 breaks passenger compile-agent

### ISSUE THREAD

**Issue by KateWilkins** [bundler/bundler#5000]
After installing 1.3.1 I'm no longer able to compile-agent with passenger (5.0.30), if I revert back to 12.5.0 it compiles just fine.

[root@callisto]# passenger-config compile-agent
/usr/local/rvm/gems/ruby-2.3.1/gems/bundler-1.13.1/lib/bundler/rubygems_ext.rb:45:in `full_gem_path': uninitialized constant Bundler::Plugin::API (NameError)
Did you mean?  Bundler::Plugin::API
	from /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/basic_specification.rb:41:in `contains_requirable_file?'
	from /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `block in require'
	from /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:67:in `each'
	from /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:67:in `find'
	from /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:67:in `require'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/bundler-1.13.1/lib/bundler/rubygems_ext.rb:45:in `full_gem_path'
	from /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1328:in `block in add_self_to_load_path'
	from /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1327:in `map'
	from /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1327:in `add_self_to_load_path'
	from /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1240:in `activate'
	from /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1271:in `block in activate_dependencies'
	from /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1257:in `each'
	from /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1257:in `activate_dependencies'
	from /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1239:in `activate'
	from /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_gem.rb:48:in `gem'
	from /usr/local/rvm/gems/ruby-2.3.1/bin/passenger-config:22:in `<main>'
	from /usr/local/rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
	from /usr/local/rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'

**Comment by segiddins** [comment]
Can you see if this is fixed by https://github.com/bundler/bundler/pull/4981?

**Comment by KateWilkins** [comment]
Hi Samuel,

Yes, I can confirm that #4981 fixes this problem.
