### ISSUE TITLE
Why is bundler added as a development dependency to the gem template?

### ISSUE THREAD

**Issue by roberts1000** [bundler/bundler#5004]
When I run `bundle gem new_gem` to create a new gem, bundler adds

    spec.add_development_dependency "bundler", "~> 1.13" 

to the gemspec file.  Why is this line needed?  It seems a little circular because bundler would already have to be installed in order to bundle the gem in the first place.  Is the intent to draw attention to the version of bundler that should be paired with the gem for development?  Regular Rails apps typically don't specify the bundler gem version so I'm trying to figure out how it helps. 

FWIW, when I run `rails plugin new new_gem` to compare how Rails does it, bundler isn't added to the gemspec.

I ran into a problem today with our CI Pipeline that deploys regular Rails applications.  I modified the CI Pipeline to build Rails engines as well.  When I did that, I realized our CI pipeline enforces a bundler version on the apps.  The builds died because the CI Pipeline wanted `~> 1.12` and the engine wanted `~> 1.13`.  It seems like I should be able to remove the dependency on bundler from the gemspec, but I'm wondering why it's there in the first place.

**Comment by segiddins** [comment]
It's there to make developers aware that they are expected to have bundler installed in order to work on developing the gem

**Comment by lynnco** [comment]
Closing as the question has been answered, feel free to continue discussing though

**Comment by indirect** [comment]
@roberts1000 to add a little additional detail, any gem created with `bundle gem` can be installed by `gem install foo` which means Bundler might not be installed. Since the rake tasks and various other parts of the development workflow depend on the Bundler gem being installed, it's a development dependency. HTH.

**Comment by roberts1000** [comment]
Thank you for the information.
