### ISSUE TITLE
Support compact index servers without MD5-based ETags

### ISSUE THREAD

**Issue by abstrctn** [bundler/bundler#5011]
I've been trying out storing versions of the compact index files for private gems on static servers like S3 and Google Cloud Storage, and ran into an issue with the Compact Index Client updater where it expects the file responses to include [MD5-based ETags](https://github.com/bundler/bundler/blob/03633e15bfb4763ab7015f4abe6ca4ec1938d759/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb#L67-L78).

Google Cloud Storage in particular uses CRC32c to compute ETags in several of their API responses: https://cloud.google.com/storage/docs/hashes-etags It does return an MD5 checksum, but it's base64-encoded and in the `X-Goog-Hash` header, instead of the ETag header.

```
ETag: CLiEoqOXlc8CEAE=
X-Goog-Hash: crc32c=wvTPZQ==,md5=9xrnefvGJXkjMSA/1ZB3GQ==
```

Most servers do use MD5, so I realize this is edge casey, but since MD5 isn't a requirement of ETags I wonder if it's worth building in a fallback to the downloader in one or both of these places:
1. If the `Range` header asks for new content but there isn't any (the expected case when the local cache is up to date), and `If-None-Match` doesn't match the server's ETag (which would happen on any server that doesn't use MD5), servers can respond with 416 Range Not Satisfiable and an empty body.
   
   Currently, that falls into [this case](https://github.com/bundler/bundler/blob/03633e15bfb4763ab7015f4abe6ca4ec1938d759/lib/bundler/fetcher/downloader.rb#L36) where an error is raised. Would you consider handling that case like `Net::HTTPNotModified` is currently handled? The downside is there are other cases where that response code might arise that actually are errors, but `index.rubygems.org` at least doesn't seem to use 416s, so it doesn't seem a widespread risk.
2. Bundler also [checks the ETag](https://github.com/bundler/bundler/blob/03633e15bfb4763ab7015f4abe6ca4ec1938d759/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb#L54) against the locally-computed checksum before accepting any new data, which will always fail if the server doesn't use MD5. I don't have a good suggestion for what to do here, since ETags aren't transparent about how they're computed, and at any rate, anticipating different types seems problematic.
   
   Some possibilities (all problematic) would be handling the `X-Goog-Hash` header as an alternative to the ETag. Ugly given its specificity to Google, but doable:
   
   ```
   response["ETag"] = "\"#{response["X-Goog-Hash"].match(/md5=(.*)/)[1].unpack("m0").first.unpack("H*").first}\"" if response["X-Goog-Hash"]
   ```
   
   Or skipping checksum validation if the the ETag clearly isn't an MD5 hash.

Thanks! Would love to hear your thoughts.

**Comment by segiddins** [comment]
MD5 etags are necessary as that's the checksum used in the `/versions` endpoint

**Comment by fotanus** [comment]
I suppose the easiest to handle this issue is having the etag tested two times: First one evaluates it as the MD5 we expect. If it fails, we can base64decode it and evaluate it again. Should be easy to support the two standards with little code and testing, and for real errors it should not take a lot of resources. What do you think @segiddins ?

**Comment by segiddins** [comment]
@fotanus that wouldn't solve this particular case, since the etag is actually a different hash entirely :/

**Comment by indirect** [comment]
Because this feature request would require completely changing the internals of how the compact index is implemented, I'm going to close this ticket, at least for now. For users who are unable to calculate MD5 checksums, please use the `--full-index` flag to fall back on the (slower) full index.
