### ISSUE TITLE
bundle clean --dry-run does not list unused gems

### ISSUE THREAD

**Issue by hmistry** [bundler/bundler#5017]
I ran `bundle clean --dry-run` expecting to see a list of unused gems (or specifically gem versions) for current Gemfile to double check before I clean them but all I got was this:

```
H-MacBook-Pro:loop_server hm$ bundle clean --dry-run
Cleaning all the gems on your system is dangerous! If you're sure you want to remove every system gem not in this bundle, run `bundle clean --force`.

H-MacBook-Pro:loop_server hm$ bundle env
Environment

    Bundler   1.12.3
    Rubygems  2.5.1
    Ruby      2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin14]
    GEM_HOME  /Users/hm/.rvm/gems/ruby-2.3.0@loop_server
    GEM_PATH  /Users/hm/.rvm/gems/ruby-2.3.0@loop_server:/Users/hm/.rvm/gems/ruby-2.3.0@global
    RVM       1.27.0 (latest)
    Git       2.7.4 (Apple Git-66)
    rubygems-bundler (1.4.4)

```

Is that the normal behavior of `bundle clean`?

**Comment by chrismo** [comment]
It is in this case, because you weren't in a directory set to a local `--path` and you didn't specify `--force`. The code to check for the `--force` exits out before the clean is attempted. See https://github.com/bundler/bundler/blob/master/lib/bundler/cli/clean.rb#L22

**Comment by hmistry** [comment]
Thanks @chrismo. You're correct in having to use both `--force` and `--dry-run` to get the listing because I don't have `path` set.
