### ISSUE TITLE
Bundle locked to rake (11.2.2)?

### ISSUE THREAD

**Issue by BytesDirect** [bundler/bundler#5019]
Hi, I was following [http://www.darkoperator.com/installing-metasploit-in-ubunt/] this guide, and when I started msfconsole, I got this error:
 `user@user-pc-SATELLITE-C55-A:~$ msfconsole
Your bundle is locked to rake (11.2.2), but that version could not be found in any of the sources listed in your Gemfile. If you haven't changed sources, that means the author of rake (11.2.2) has removed it. You'll need to update your bundle to a different version of rake (11.2.2) that hasn't been removed in order to install.
Run `bundle install` to install missing gems.
user@user-pc-SATELLITE-C55-A:~$ .
`                                                                        
 I am currently running Ubuntu 16.04 LTS.

Any help would be appreciated! Thanks in advance.
`

**Comment by chrismo** [comment]
This looks like the same issue as #5018?

**Comment by BytesDirect** [comment]
Oh, I didn't realize there was the same issue (I'm new to github!). Thanks!

**Comment by BytesDirect** [comment]
Ooops

**Comment by chrismo** [comment]
No worries! And it was a genuine question on my part, sometimes similar issues aren't always the same, so if it looks the same to you then I'll close this one in favor of 5018.
