### ISSUE TITLE
Investigate why breaking `--path` in 4701 did not fail specs in CI.

### ISSUE THREAD

**Issue by chrismo** [bundler/bundler#5025]
In working on #4992, I realized I could get many install/path_spec.rb failures locally after the bug had been introduced in #4701, but none of them failed in CI. It might be worth getting to the bottom of that if there are reasons specs _should_ fail in CI that don't.

**Comment by segiddins** [comment]
Closing because there hasn't been any progress on this, but as always added test coverage would be welcome!
