### ISSUE TITLE
Reorganize documentation

### ISSUE THREAD

**Issue by lynncyrin** [bundler/bundler#5026]
- [ ] add `doc/` folder, for documentation about Bundler as a project (that is, not individual commands)
- [ ] add https://github.com/bundler/bundler/issues/4135 (release documentation)
- [ ] move everything into `docs/` except `README.md`
- [ ] add / update documentation about the documentation files / folders
- [ ] mention that `bundler` maps directly to `bundle`
- [ ] point out the documentation cop https://github.com/bundler/bundler/pull/4343
- [ ] mention how the different doc files map to [bundler.io](http://bundler.io) and `bundle help` (ref: https://github.com/bundler/bundler/issues/4987)
- [ ] add all the above changes to [bundler/bundler-site](https://github.com/bundler/bundler-site) where appropriate

**Comment by indirect** [comment]
I would vote to add a contributing section near the top of the README that references/links to the full-on contributing guide.

**Comment by lynnco** [comment]
Here's an example patch diff https://github.com/bundler/bundler/compare/v1.13.1...v1.13.2

**Comment by feministy** [comment]
@lynnco i can start tackling these! at first glance, the order you have them in seems to work for me. have you started work on any of this, or is it ok with you if i start working from the top down?

**Comment by lynnco** [comment]
@feministy I haven't started on this! You can go for it however you want

**Comment by feministy** [comment]
in progress! https://github.com/feministy/bundler/tree/docs-reorg

**Comment by segiddins** [comment]
@feministy are you done with this?

**Comment by feministy** [comment]
not yet - there are a big chunk of things that still need to be done. if it's cluttering the issues list we can close it out and i'll look back on it for reference :)

**Comment by arbonap** [comment]
hi @feministy 👋🏽 i'd be happy to help and take any of these doc-related changes off of your plate.

**Comment by colby-swandale** [comment]
It seems like most, if not all of these items have been completed. This should be ok to close.
