### ISSUE TITLE
bin/console works wrong in Mac finder

### ISSUE THREAD

**Issue by rikkimongoose** [bundler/bundler#5030]
Bundler: 1.12.5
MacOS: 10.11.6
Finder: 10.11.4

Autogenerated **bin/console** file in MacOS fails to execute if browse to it with MacOS Finder.

It fails with following error:

_/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file --_

The reason is Finder executes all scripts in context of ~ directory. So, Dir.pwd contain "Users/username/". But, for example, File.dirname(**FILE**) stores right path.

My quick fix is adding the following line at **bin/console** file:

``` ruby
$LOAD_PATH.unshift File.expand_path('../../lib', __FILE__) # add this line for MacOS support

require "bundler/setup"
```

I guess, it should be fixed at https://github.com/bundler/bundler/blob/master/lib/bundler/templates/newgem/bin/console.tt

**Comment by segiddins** [comment]
A PR making that change would be perfect, thanks!

**Comment by colby-swandale** [comment]
This has not been active for a long time. If this is an issue that anyone would like to fix, then please open a PR. But i'm going to close this ticket.
