### ISSUE TITLE
`bundle install` causes SystemStackError: stack level too deep

### ISSUE THREAD

**Issue by josephfrazier** [bundler/bundler#5034]
- What did you do?

```shell
git clone https://gitlab.com/gitlab-org/gitlab-ce/
cd gitlab-ce
git checkout 3b55460dd79f0997e1714f7aa1bf821fcf17086a # master, at the time of writing
/usr/local/bin/bundle install --without mysql production --jobs 4
```

- What did you expect to happen?

  I expected Bundler to install my gems.

- What happened instead?

  Instead, what happened was a `SystemStackError: stack level too deep`:

Error details

<details>

    SystemStackError: stack level too deep
      /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1509:in `rescue in add_bindir`
      /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1501:in `add_bindir`
      /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:354:in `files`
      /usr/local/lib/ruby/site_ruby/2.3.0/rubygems.rb:1256:in `remove_unresolved_default_spec`
      /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:45:in `require`
      /usr/local/lib/ruby/site_ruby/2.3.0/bundler/cli.rb:410:in `gem`
      /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:46:in `require`

      (many repetitions of the previous two lines)

      /usr/local/lib/ruby/site_ruby/2.3.0/bundler/cli.rb:410:in `gem`
      /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:46:in `require`
      /usr/local/lib/ruby/site_ruby/2.3.0/bundler/cli.rb:186:in `install`
      /usr/local/lib/ruby/site_ruby/2.3.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run`
      /usr/local/lib/ruby/site_ruby/2.3.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command`
      /usr/local/lib/ruby/site_ruby/2.3.0/bundler/vendor/thor/lib/thor.rb:359:in `dispatch`
      /usr/local/lib/ruby/site_ruby/2.3.0/bundler/cli.rb:20:in `dispatch`
      /usr/local/lib/ruby/site_ruby/2.3.0/bundler/vendor/thor/lib/thor/base.rb:440:in `start`
      /usr/local/lib/ruby/site_ruby/2.3.0/bundler/cli.rb:11:in `start`
      /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/exe/bundle:34:in `block in <top (required)>`
      /usr/local/lib/ruby/site_ruby/2.3.0/bundler/friendly_errors.rb:100:in `with_friendly_errors`
      /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/exe/bundle:26:in `<top (required)>`
      /usr/local/bin/bundle:22:in `load`
      /usr/local/bin/bundle:22:in `<main>`
</details>

Environment

  Bundler   1.13.1
  Rubygems  2.6.7
  Ruby      2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
  Git       2.10.0
  OpenSSL   OpenSSL 1.0.2j  26 Sep 2016

Bundler settings

- retry

  Set for the current user (/Users/josephfrazier/.bundle/config): "3"

- build.eventmachine

  Set for the current user (/Users/josephfrazier/.bundle/config): "--with-cppflags=-I/usr/local/opt/openssl/include"

**Comment by segiddins** [comment]
I can't reproduce this locally. Can you please share the contents of `/usr/local/bin/bundle`? Thanks!

**Comment by josephfrazier** [comment]
Oops, I think I brought this upon myself while trying to fix https://github.com/Homebrew/homebrew-core/issues/5413

Switching to a `chruby`-based installation seems to have fixed things. Thanks for the quick response!
