### ISSUE TITLE
Option to resolve bundle from executable file location

### ISSUE THREAD

**Issue by strigonLeader** [bundler/bundler#5039]
I would like to write applications that use bundler, have local gems installed using `bundler install --deployment` and have the executables of the application be executable on their own from any working directory.

Currently my executable starts with `require 'bundle/setup'` which should populate the LOAD_PATH with the locations of the bundle's gem bins, but this looks for the Gemfile from the current working directory. It would be nice to have some option to search up from the location of the executable file so that the related bundle for that file is used.

Doing this sort of thing hacks the functionality in by overriding the BUNDLE_GEMFILE variable, but it would be nice to pass a flag into setup instead or have some alternate 'bundle/executable' require

``` ruby
require 'pathname'
filepath = Pathname.new __FILE__
filepath.realpath.ascend do |path|
    if (path += 'Gemfile').exist?
        ENV["BUNDLE_GEMFILE"] = path.to_s
        break
    end
end
require 'bundler/setup'
```

It's not a large feature but maybe I'm missing something in how to use bundler properly, so some sort of feedback would appreciated before I try to submit any pull request.

**Comment by segiddins** [comment]
Setting `BUNDLE_GEMFILE` is indeed the official way of doing this

**Comment by segiddins** [comment]
`require 'bundle/setup'` will already search up (see `Bundler::SharedHelpers.find_gemfile`).
