### ISSUE TITLE
Modern bundler versions cannot find Nokogiri v1.6.8.1

### ISSUE THREAD

**Issue by tom-lord** [bundler/bundler#5046]
This is a really bizarre bug, so apologies for the odd description...

Nokogiri v1.6.8.1 was released recently. If you run `gem list nokogiri --remote`, you find the following:

    nokogiri (1.6.8.1 ruby java x64-mingw32 x86-mingw32, 1.6.1 x86-mswin32-60, 1.4.4.1 x86-mswin32)

Now suppose you have a `Gemfile.lock` that specifies version 1.6.8.1 of the gem.

If you are using bundler version **<= 1.12.0.pre2**, then everything works as expected; nokogiri is installed.

However, if you are using version **>=1.12.0.rc**, then you get the following error message:

> Your bundle is locked to nokogiri (1.6.8.1), but that version could not be found in any of the sources listed in your Gemfile. If you haven't changed sources, that means the author of nokogiri (1.6.8.1)
has removed it. You'll need to update your bundle to a different version of nokogiri (1.6.8.1) that hasn't been removed in order to install.

(Or in earlier versions, a shorter message: *"Could not find nokogiri-1.6.8.1 in any of the sources"*)

Version 1.6.8 can be found and installs fine; the issue only seems to be with the latest version, 1.6.8.1.

At this point, I don't know exactly what the cause is, or what ruby gems this affects, but I suspect it has something to do with [this commit](https://github.com/bundler/bundler/commit/9ed4cbc4ae90f726836089530da3069db99b5a41), associated to [this issue](https://github.com/bundler/bundler/pull/4358), as mentioned in the CHANGELOG as *"Download gem metadata from globally distributed CDN endpoints"*. Or perhaps it's actually a bug on RubyGems, rather than bundler?!....

**Comment by chrismo** [comment]
Can you share your `bundle env` results and/or a reproducible case (see also [ISSUES](https://github.com/bundler/bundler/blob/master/ISSUES.md))?

**Comment by tom-lord** [comment]
I don't know much about the internals of bundler, so this could be a red herring.... But I also found that `v1.6.8.1` is not mentioned in the cache file (`~/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/info/nokogiri`):

```
# .......
1.6.7.1-x86-mingw32 mini_portile2:~> 2.0.0.rc2|checksum:
1.6.8.rc1-java |checksum:
1.6.8.rc1 mini_portile2:~> 2.0.0|checksum:
1.6.8.rc1-x64-mingw32 mini_portile2:~> 2.0.0|checksum:
1.6.8.rc1-x86-mingw32 mini_portile2:~> 2.0.0|checksum:
1.6.8.rc2-java |checksum:cbd04fde3289fad161df27d15059531277fe3b6b4455dc9416774cc1228185b5,ruby:>= 0,rubygems:> 1.3.1
1.6.8.rc2-x64-mingw32 mini_portile2:~> 2.1.0|checksum:1585c537c9e9dd7482e1692b4d4655d63b66238c29932d9a7e3d33608fb1eba3,ruby:< 2.4, >= 1.9.2,rubygems:> 1.3.1
1.6.8.rc2-x86-mingw32 mini_portile2:~> 2.1.0|checksum:20a582b4d26ba929b320fd78bf8eecf10a605636754ce4206a81be6b597410b7,ruby:< 2.4, >= 1.9.2,rubygems:> 1.3.1
1.6.8.rc2 mini_portile2:~> 2.1.0|checksum:cbd04fde3289fad161df27d15059531277fe3b6b4455dc9416774cc1228185b5,ruby:>= 1.9.2,rubygems:> 1.3.1
1.6.7.2-java |checksum:628f7ca619320f91115d8e7716d088d35fe6cc1daa751895eeee0ae368a07203,ruby:>= 0,rubygems:>= 0
1.6.7.2-x64-mingw32 mini_portile2:~> 2.0.0.rc2|checksum:628f7ca619320f91115d8e7716d088d35fe6cc1daa751895eeee0ae368a07203,ruby:< 2.3, >= 1.9.2,rubygems:>= 0
1.6.7.2-x86-mingw32 mini_portile2:~> 2.0.0.rc2|checksum:0dc58ade97d0cbd2c8e2c317ea4db2bfd81f9b2e3244916ed3398772b94a5cff,ruby:< 2.3, >= 1.9.2,rubygems:>= 0
1.6.7.2 mini_portile2:~> 2.0.0.rc2|checksum:0dc58ade97d0cbd2c8e2c317ea4db2bfd81f9b2e3244916ed3398772b94a5cff,ruby:>= 1.9.2,rubygems:>= 0
1.6.8.rc3-java |checksum:fc13af98eb27bd535558a6607dfbc938969f13618fcb3056292d423fe9972ca7,ruby:>= 0,rubygems:> 1.3.1
1.6.8.rc3-x64-mingw32 mini_portile2:~> 2.1.0,pkg-config:~> 1.1.7|checksum:fc13af98eb27bd535558a6607dfbc938969f13618fcb3056292d423fe9972ca7,ruby:< 2.4, >= 1.9.2,rubygems:> 1.3.1
1.6.8.rc3-x86-mingw32 mini_portile2:~> 2.1.0,pkg-config:~> 1.1.7|checksum:9ee6b9beab1728af6044ecf8ec411424383156881fb268baf157ab3dea613f3e,ruby:< 2.4, >= 1.9.2,rubygems:> 1.3.1
1.6.8.rc3 mini_portile2:~> 2.1.0,pkg-config:~> 1.1.7|checksum:fc13af98eb27bd535558a6607dfbc938969f13618fcb3056292d423fe9972ca7,ruby:>= 1.9.2,rubygems:> 1.3.1
1.6.8-java |checksum:8f7fa3321c0ebdc3170ab1f1da69c61a4af7ebadb7a18d6d9a55441dc1177b7d,ruby:>= 0,rubygems:>= 0
1.6.8-x64-mingw32 mini_portile2:~> 2.1.0,pkg-config:~> 1.1.7|checksum:26a5c1c02ed90c36549cd03b459e4ba6b9e2cf1f6a69b3619215bf51daec15dc,ruby:< 2.4, >= 1.9.2,rubygems:>= 0
1.6.8-x86-mingw32 mini_portile2:~> 2.1.0,pkg-config:~> 1.1.7|checksum:8f7fa3321c0ebdc3170ab1f1da69c61a4af7ebadb7a18d6d9a55441dc1177b7d,ruby:< 2.4, >= 1.9.2,rubygems:>= 0
1.6.8 mini_portile2:~> 2.1.0,pkg-config:~> 1.1.7|checksum:26a5c1c02ed90c36549cd03b459e4ba6b9e2cf1f6a69b3619215bf51daec15dc,ruby:>= 1.9.2,rubygems:>= 0

```

**Comment by tom-lord** [comment]
Here is a trivial repository I have created to demonstrate the issue:

https://github.com/tom-lord/nokogiri_bundler_poc

As you can see, I ran `bundle` with an *old version* to reproduce this. Here was my `bundle env` at the time:

Environment

>     Bundler   1.11.2
>     Rubygems  2.6.7
>     Ruby      2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]
>     GEM_HOME  /home/tom/.rvm/gems/ruby-2.3.0
>     GEM_PATH  /home/tom/.rvm/gems/ruby-2.3.0:/home/tom/.rvm/gems/ruby-2.3.0@global
>     RVM       1.27.0 (master)
>     Git       2.7.4
>     rubygems-bundler (1.4.4)
> 
> Bundler settings
> 
>     gem.test
>       Set for the current user (/home/tom/.bundle/config): "rspec"
>     gem.mit
>       Set for the current user (/home/tom/.bundle/config): "false"
>     gem.coc
>       Set for the current user (/home/tom/.bundle/config): "false"
> 
> Gemfile
> 
>     source "https://rubygems.org"
>     
>     gem 'nokogiri'
> 
> Gemfile.lock
> 
>     GEM
>       remote: https://rubygems.org/
>       specs:
>         mini_portile2 (2.1.0)
>         nokogiri (1.6.8.1)
>           mini_portile2 (~> 2.1.0)
>     
>     PLATFORMS
>       ruby
>     
>     DEPENDENCIES
>       nokogiri
>     
>     BUNDLED WITH
>        1.11.2
> 

I then updated my `bundler` version to the latest. Here it is again:

Environment

>     Bundler   1.13.2
>     Rubygems  2.6.7
>     Ruby      2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]
>     GEM_HOME  /home/tom/.rvm/gems/ruby-2.3.0
>     GEM_PATH  /home/tom/.rvm/gems/ruby-2.3.0:/home/tom/.rvm/gems/ruby-2.3.0@global
>     RVM       1.27.0 (master)
>     Git       2.7.4
>     rubygems-bundler (1.4.4)
> 
> Bundler settings
> 
>     gem.test
>       Set for the current user (/home/tom/.bundle/config): "rspec"
>     gem.mit
>       Set for the current user (/home/tom/.bundle/config): "false"
>     gem.coc
>       Set for the current user (/home/tom/.bundle/config): "false"
> 
> Gemfile
> 
>     source "https://rubygems.org"
>     
>     gem 'nokogiri'
> 
> Gemfile.lock
> 
>     GEM
>       remote: https://rubygems.org/
>       specs:
>         mini_portile2 (2.1.0)
>         nokogiri (1.6.8.1)
>           mini_portile2 (~> 2.1.0)
>     
>     PLATFORMS
>       ruby
>     
>     DEPENDENCIES
>       nokogiri
>     
>     BUNDLED WITH
>        1.11.2
> 

Now, when I run `gem uninstall nokogiri`, followed by `bundle`, I get the error described above:

> Fetching gem metadata from https://rubygems.org/.............
> Fetching version metadata from https://rubygems.org/.
> Your bundle is locked to nokogiri (1.6.8.1), but that version could not be found in any of the sources listed in your Gemfile. If you haven't changed sources, that means the author of nokogiri (1.6.8.1)
> has removed it. You'll need to update your bundle to a different version of nokogiri (1.6.8.1) that hasn't been removed in order to install.

Hopefully that's enough detail for you :)

**Comment by chrismo** [comment]
If I uninstall the system gem before re-running `bundle` with 1.11.2 or 1.13.2, neither version can find the gem. 

Does the linked https://github.com/chrismo/bundler-cases/issues/18 accurately recreate your case?

**Comment by dwradcliffe** [comment]
Try again, it should work now. We had an incident yesterday and we have some bad caches for a few things. I've purged the cache for this gem. Sorry for the trouble!

**Comment by chrismo** [comment]
thx @dwradcliffe - i got my head confused and my own test case was invalid, problem with faking too many things out.

**Comment by tom-lord** [comment]
:+1: Thanks both, I'll check if things are working fine at work tomorrow, but thanks for looking into this so quickly.

**Comment by superzadeh** [comment]
Anychange this could be happening again right now?

**Comment by tom-lord** [comment]
Can you reproduce it from the repo I created above? (https://github.com/tom-lord/nokogiri_bundler_poc) I just tried to, but it seems to work fine for me.

If you can reproduce it, please post your `bundle env` so we can hopefully reproduce it too.

**Comment by HaganMcPhail** [comment]
@superzadeh we seem to be having the same issue. When you run bundle env, what version of Bundler is listed at the top? Also, what version does "BUNDLED WITH" produce at the bottom?

**Comment by mtompkins** [comment]
I'm seeing this behavior on Ubuntu 16.10:
```
Environment

    Bundler   1.12.5
    Rubygems  2.5.1
    Ruby      2.3.1p112 (2016-04-26 revision 0) [x86_64-linux-gnu]
    Git       2.9.3

    BUNDLED WITH
       1.14.5
```

**Comment by patrickgomes1968** [comment]
Hi, I'm a noob so please bear with me:
Exception: 
 `Your bundle is locked to nokogiri (1.6.7.1-x86-mingw32), but that version could not be found in any of the sources listed in your Gemfile. If you haven't changed sources, that means the author of nokogiri (1.6.7.1-x86-mingw32) has removed it. You'll need to update your bundle to a different version of nokogiri (1.6.7.1-x86-mingw32) that hasn't been removed in order to install.`

```
Environment

    Bundler   1.13.7
    Rubygems  2.5.2
    Ruby      2.3.3p222 (2016-11-21 revision 56859) [i386-mingw32]
    Git       2.12.2.windows.2
   BUNDLED WITH
         1.10.6
```
Perhaps relevant, bundler returned this issue:
```
Gem::InstallError: nokogiri requires Ruby version < 2.3, >= 1.9.2.
An error occurred while installing nokogiri (1.6.7.1), and Bundler cannot
continue.
Make sure that `gem install nokogiri -v '1.6.7.1'` succeeds before bundling.
```
I changed the version referenced in the gemlock file from 1.6.7.1 to 1.7.1 (which i have installed) and bundler succeeded. Then I tried to run `rake db_migrate` but  got an exception that advised me to prepend that with `bundle exe`c. I did (run `bundle exec rake db:migrate`) but get 
`The system cannot find the path specified.`
When I try to start the rails server, I get this message:
`C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/sqlite3-1.3.11-x86-mingw32/lib/sqlite3.rb:6:in `require': cannot load such file -- sqlite3/sqlite3_native (LoadError)
`
Are these two separate issues? How can resolve either/both?

**Comment by wainersm** [comment]
I'm getting same here today:
```
wainersm@wainersm-laptop:~/projects/oss/logstash/build$ rake artifact:tar
(in /home/wainersm/projects/oss/logstash)
Could not find nokogiri-1.7.2-java in any of the sources
Run `bundle install` to install missing gems.
wainersm@wainersm-laptop:~/projects/oss/logstash/build$ bundle show nokogiri
/home/wainersm/.rvm/gems/jruby-1.7.26/gems/nokogiri-1.7.2-java
```

From previous comments it's not clear (to me) how to solve it.

**Comment by tom-lord** [comment]
@wainersm 

> Run `bundle install` to install missing gems.

I think that's quite clear...

**Comment by tom-lord** [comment]
@wainersm What if you run `bundle exec rake artifact:tar`?

**Comment by wainersm** [comment]
@tom-lord ```bundle install``` didn't work. Neither ```bundle exec rake artifact:tar```
I also deleted nokogiri (```gem uninstall nokogiri```) then installed it back (with bundle). No way, still not working.

**Comment by karthikpamidimarri** [comment]
I am also getting same error here today 

> Could not find nokogiri-1.6.8.1 in any of the sources
Below is the environment information
**## Environment
Bundler   1.15.1
Rubygems  2.4.8
Ruby      2.2.6p396 (2016-11-15 revision 56800) [x86_64-linux]
GEM_HOME  /home/kk/.rvm/gems/ruby-2.2.6@migrocer
GEM_PATH  /home/kk/.rvm/gems/ruby-2.2.6@migrocer:/home/kk/.rvm/gems/ruby-2.2.6@global
RVM       1.29.1 (master)
Git       2.7.4
Platform  x86_64-linux
rubygems-bundler (1.4.4)**

**Comment by ryan-sattler** [comment]
I am getting the same error today, for both bundler 1.14.4 and 1.16.0.pre.1, and for various versions of Nokogiri (1.7.0.1, 1.7.2, 1.8.0). Current env:

## Environment

```
Bundler   1.16.0.pre.1
RubyGems  2.6.11
Ruby      2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
GEM_HOME  /Users/ryan.sattler/.gem/ruby/2.4.1
GEM_PATH  /Users/ryan.sattler/.gem/ruby/2.4.1:/Users/ryan.sattler/.rubies/ruby-2.4.1/lib/ruby/gems/2.4.0
Git       2.13.4
Platform  x86_64-darwin-16
OpenSSL   OpenSSL 1.0.2k  26 Jan 2017
```

## Bundler Build Metadata

```
Built At          2017-09-05
Git SHA           5ffc8b010
Released Version  true
```
...
gem 'nokogiri', '1.7.0.1'
...
nokogiri (1.7.0.1)
...

BUNDLED WITH
   1.16.0.pre.1

Is there anything I can do?

**Comment by colby-swandale** [comment]
Please open an new issue with the details of your problem, you can follow Bundler's [ISSUES](https://github.com/bundler/bundler/blob/master/doc/contributing/ISSUES.md) guide for more information.

**Comment by ryan-sattler** [comment]
@colby-swandale Ok, opened #6006
