### ISSUE TITLE
https://github.com/bundler/bundler/search?q=Permission+denied+-+%2FUsers%2Fkushrustagi%2F.bundle%2Fcache%2Fcompact_index%2Frubygems.org.443.29b0360b937aa4d161703e6160654e47%2Fversions20161004-19406-1tzg0hj&type=Issues

### ISSUE THREAD

**Issue by kushrp** [bundler/bundler#5047]
➜  resume-template-gh-pages 2 bundle install     
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `/usr/local/bin/bundle install`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what happened was...

Error details

    Errno::EACCES: Permission denied - /Users/kushrustagi/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/versions20161004-19406-1tzg0hj
      /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tmpdir.rb:85:in `mkdir'
      /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tmpdir.rb:85:in `block in mktmpdir'
      /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tmpdir.rb:142:in `create'
      /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tmpdir.rb:85:in `mktmpdir'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.2/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:29:in `update'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.2/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:64:in `update'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.2/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:55:in `update_and_parse_checksums!'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.2/lib/bundler/fetcher/compact_index.rb:67:in `available?'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.2/lib/bundler/fetcher/compact_index.rb:15:in `call'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.2/lib/bundler/fetcher/compact_index.rb:15:in `block in compact_index_request'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.2/lib/bundler/fetcher.rb:157:in `use_api'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.2/lib/bundler/source/rubygems.rb:332:in `block in api_fetchers'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.2/lib/bundler/source/rubygems.rb:332:in `select'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.2/lib/bundler/source/rubygems.rb:332:in `api_fetchers'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.2/lib/bundler/source/rubygems.rb:337:in `block in remote_specs'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.2/lib/bundler/index.rb:10:in `build'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.2/lib/bundler/source/rubygems.rb:336:in `remote_specs'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.2/lib/bundler/source/rubygems.rb:83:in `specs'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.2/lib/bundler/lazy_specification.rb:61:in `__materialize__'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.2/lib/bundler/spec_set.rb:91:in `block in materialize'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.2/lib/bundler/spec_set.rb:88:in `map!'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.2/lib/bundler/spec_set.rb:88:in `materialize'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.2/lib/bundler/definition.rb:174:in `specs'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.2/lib/bundler/definition.rb:162:in `resolve_remotely!'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.2/lib/bundler/installer.rb:225:in `resolve_if_need'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.2/lib/bundler/installer.rb:78:in `run'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.2/lib/bundler/installer.rb:24:in `install'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.2/lib/bundler/cli/install.rb:71:in `run'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.2/lib/bundler/cli.rb:189:in `install'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.2/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.2/lib/bundler/cli.rb:20:in `dispatch'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.2/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.2/lib/bundler/cli.rb:11:in `start'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.2/exe/bundle:34:in `block in <top (required)>'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.2/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.2/exe/bundle:26:in `<top (required)>'
      /usr/local/bin/bundle:23:in `load'
      /usr/local/bin/bundle:23:in `<main>'

Environment
      
  Bundler   1.13.2
  Rubygems  2.0.14.1
  Ruby      2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
  GEM_HOME  /Library/Ruby/Gems/2.0.0
  GEM_PATH  /Library/Ruby/Gems/2.0.0:/Users/kushrustagi/.gem/ruby/2.0.0:/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/gems/2.0.0
  Git       2.6.1
--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/bundler/bundler/search?q=Permission+denied+-+%2FUsers%2Fkushrustagi%2F.bundle%2Fcache%2Fcompact_index%2Frubygems.org.443.29b0360b937aa4d161703e6160654e47%2Fversions20161004-19406-1tzg0hj&type=Issues

If there aren't any reports for this error yet, please create copy and paste the report template above into a new issue. Don't forget to anonymize any private data! The new issue form is located at:
https://github.com/bundler/bundler/issues/new

What's the issue?

**Comment by lynnco** [comment]
@kushrp look into how the other issue with permission errors were resolved https://github.com/bundler/bundler/search?q=Errno+EACCES+Permission+denied&type=Issues&utf8=%E2%9C%93
