### ISSUE TITLE
Platform check breaks deployment check

### ISSUE THREAD

**Issue by indirect** [bundler/bundler#5050]
When running Bundler directly from a git checkout at 524f2d49dfd9270a3d6cce5b1e0950bb9bb4ae2b, the platform check short-circuits the deployment mode check for a lockfile. It's supposed to print an error explaining how to use `--no-deployment` to escape, but instead it just prints a platform error:

```
$ git clone https://github.com/trevorturk/bundler-test-5006
$ cd bundler-test-5006
$ rm Gemfile.lock
$ bundle config frozen true
$ dbundle install
Your bundle only supports platforms [] but your local platforms are ["ruby", "x86_64-darwin-15"], and there's no compatible match between those two lists.
```

Expected output (and current output from 1.13.2):

```
$ dbundle install
You are trying to install in deployment mode after changing
your Gemfile. Run `bundle install` elsewhere and add the
updated Gemfile.lock to version control.

If this is a development machine, remove the /Users/andre/src/bundler/testcases/5044/bundler-test-5006/Gemfile freeze 
by running `bundle install --no-deployment`.

You have added to the Gemfile:
* source: rubygems repository https://rubygems.org/
* sinatra-sequel
```

**Comment by segiddins** [comment]
https://github.com/bundler/bundler/blob/e499c51567df8ced0bad655bdf969453a3362032/lib/bundler/cli/install.rb#L35 should probably check Bundler.settings instead of options
 if anyone wants to pull together a quick PR with test coverage

**Comment by agis-** [comment]
This seems fixed in master.

**Comment by segiddins** [comment]
Even so, we probably should add test coverage

**Comment by segiddins** [comment]
Closing since it's fixed, but added test coverage would of course be welcome!
