### ISSUE TITLE
Making bundler/inline act more like `bundle install`

### ISSUE THREAD

**Issue by janko-m** [bundler/bundler#5063]
First of all, thank you for all your hard work on Bundler, I'm always excited to see so many improvements with each release! And thanks for the `bundler/inline` feature, it's really useful! ❤️ 

My main reason why I'm excited about `bundler/inline` is that it means that now you can write a "minimal self-contained example that reproduces the bug" into a single file. However, I can't get it to quite work the way that I want to.

If I call `gemfile do ... end`, then it will fail if there is a gem version that isn't installed. But if I call `gemfile(true) do ... end`, then Bundler seems to _always_ perform the whole RubyGems searching process, even if all versions are already installed. 

What I would like is for `bundler/inline` to act more like `bundle install`, that if all necessary gems are already installed, that no HTTP requests need to be made. I guess it's not that easy to just reuse the `bundle install` functionality since as far as I remember the `bundler/inline` feature doesn't create a `Gemfile.lock`. But I think that this improvement to `bundler/inline` would make it really straightforward to use for reproducing bugs 😃

**Comment by segiddins** [comment]
What bundler version are you running? In theory it does this in 1.13. What's a Gemfile we can use to reproduce this?

**Comment by janko-m** [comment]
@segiddins Yes, this is on Bundler 1.13.2, here is the script:

```rb
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"
  gem "activerecord"
end
```

Holy crap, fetching metadata from RubyGems is so fast now 💨

**Comment by segiddins** [comment]
I can't reproduce this -- uninstalling active record and then running the given script does seem to install the gem

**Comment by janko-m** [comment]
@segiddins Yes, for me the gem is also successfully installed. The issue is that now, once ActiveRecord is installed locally, when I run the script again, I would like `gemfile(true)` not to make the RubyGems lookup, because it can detect that it's already installed locally (exactly like `bundle install` does).

However, even when all the gem versions are already installed, `gemfile(true)` seems to do the RubyGems lookup anyway, and afterwards just uses the gems that are already installed locally. And if I don't pass `true` to `gemfile()`, it will never do any lookups and fail if the specified gems aren't isn't installed.

I would like that `bundler/inline` provides the middle ground just like `bundle install`: first check if all gem versions are already installed, and in that case don't do any RubyGems lookups, otherwise do the RubyGems lookup to download the missing gems.

**Comment by segiddins** [comment]
Ah sorry I didn't understand that it unnecessarily making network requests without an explicit `true` passed was the issue

**Comment by ioquatix** [comment]
I'd like to add to this bug report. It seems like the inline functionality needs to be able to work in isolation. It might make sense, that rather than just true/false flags for install, but providing a path, would make more sense. In some cases, it's not possible for bundler/inline to install system-wide gems.

For example, 

```ruby
#!/usr/bin/env ruby

require "bundler/inline"

ENV['BUNDLE_PATH'] = "vendor/bundle"

gemfile(true) do
	source "https://rubygems.org"
	gem "utopia", "~> 1.9.10"
end

Utopia::Command::Top.parse("utopia", "server", "create").invoke
```

Gives the following output:

```
% ./setup.rb
Fetching gem metadata from https://rubygems.org/..............
Fetching version metadata from https://rubygems.org/.
Resolving dependencies...


Your user account isn't allowed to install to the system RubyGems.
  You can cancel this installation and run:

      bundle install --path vendor/bundle

  to install the gems into ./vendor/bundle/, or you can enter your password
  and install the bundled gems to RubyGems using sudo.

  Password: 
```

But I feel like there should be some way for this to work.

**Comment by segiddins** [comment]
Inline is only intended to use system gems

**Comment by ioquatix** [comment]
@segiddins but it can install from github and this is a common use-case by rails. It would be nicer if it installed to a local only directory if possible. But if not I understand.

**Comment by ioquatix** [comment]
If `bundler/inline` respected `BUNDLE_PATH` that would be awesome.

**Comment by colby-swandale** [comment]
can this be closed?

**Comment by ioquatix** [comment]
Yes, it could be. Is it still an issue? I think so.

**Comment by segiddins** [comment]
I think it's intended that `bundler/inline` not respect the `BUNDLE_PATH` setting.

**Comment by ioquatix** [comment]
Why is it intended to work that way?

**Comment by segiddins** [comment]
Because it only is for pulling from / installing into system gems

**Comment by janko-m** [comment]
I might be mistaken, but I don't think `bundler/inline` not respecting `BUNDLE_PATH` is related to the original issue.

The original issue is that I didn't find a way for `bundler/inline` to make HTTP requests only when they're needed. `gemfile(true)` will always make HTTP requests, even if all gems are installed locally, while `gemfile` will never make HTTP requests, even if some gems are missing.

I wished for a way for the `bundler/inline` feature to act like `bundle install` in this regard; that if some gems are not installed, it makes HTTP requests to rubygems.org, but if all gems are installed locally, it makes no HTTP requests. Currently I need to have `gemfile(true)` when I run the script for the first time, and then remove `true` if I don't want each subsequent execution of that Ruby file to have the overhead of all the HTTP requests to rubygems.org made by Bundler, which are unnecessary since all of the specified gems are already installed locally.

**Comment by indirect** [comment]
I was under the impression that we changed this so that `gemfile` check for the gems in system gems and only make HTTP requests if the gems are not already installed, and `gemfile(false)` will now avoid making HTTP requests at all, erroring out if the gems are missing. Maybe @segiddins can clarify?

**Comment by segiddins** [comment]
Yeah, I seem to recall fixing that issue a while back

**Comment by janko-m** [comment]
@indirect You're right, when I try on the latest version of Bundler the issue is fixed. Thank you!

**Comment by ioquatix** [comment]
Is it worth opening a PR for `bundler/inline` respecting BUNDLE_PATH or is this not considered a useful feature/addition?

**Comment by indirect** [comment]
@ioquatix if the "standalone ruby script" depends on a single path, unique to that script, it feels kind of like it's defeating the point of inline to me. If you feel strongly that it would be a benefit, I suggest opening a new issue, or better yet writing [a Bundler RFC](https://github.com/bundler/rfcs)

**Comment by ioquatix** [comment]
@indirect It probably makes sense to make a separate issue for this as the original issue was resolved but my addendum was not really addressed or understood. As long as a PR would be fairly considered, I'd be happy just to work at that level, it's not a big change actually.
