### ISSUE TITLE
github.https option changes the Gemfile.lock

### ISSUE THREAD

**Issue by lucaspiller** [bundler/bundler#5066]
When setting the `github.https` option to true it changes the `Gemfile.lock` to point to the new Git URL, with https, after running `bundle install` e.g.:

```ruby
diff --git a/Gemfile.lock b/Gemfile.lock
index 3b6a0f0..c8af4e7 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -1,6 +1,6 @@
 GIT
-  remote: git://github.com/activeadmin/activeadmin.git
-  revision: cc178ad0ebe1b74729eeaa59d5c7ad9b82ed7837
+  remote: https://github.com/activeadmin/activeadmin.git
+  revision: f8926831429fe635d26ac8043ea5d676fb6ee637
   specs:
     activeadmin (1.0.0.pre4)
       arbre (~> 1.0, >= 1.0.2)
```

When deploying with this, bundler raises an error, as apparently the `Gemfile.lock` has been changed and not committed:

```
00:11 bundler:install
      01 /opt/rbenv/bin/rbenv exec bundle install --path /opt/apps/myapp/shared/bundle --without development test --deployment --quiet
      01 You are trying to install in deployment mode after changing
      01 your Gemfile. Run `bundle install` elsewhere and add the
      01 updated Gemfile.lock to version control.
      01
      01 You have added to the Gemfile:
      01 * source: git://github.com/activeadmin/activeadmin.git (at master)
      01
      01 You have deleted from the Gemfile:
      01 * source: https://github.com/activeadmin/activeadmin.git (at master@f892683)
```

What I'd expect to happen: Setting the `github.https` option doesn't change the Gemfile.lock.

```
$ bundler --version
Bundler version 1.13.2
$ gem --version
ruby 2.5.1
$ ruby --version
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
```

**Comment by segiddins** [comment]
This is the intended behavior -- we would've loved to have changed the default, but it would've broken deployment. So we made it an option.

**Comment by lucaspiller** [comment]
So basically if somebody needs to use the github.https option, then everybody and all the servers on the project need to use it as well? Or forever be committing the Gemfile.lock?

**Comment by segiddins** [comment]
Or locally override it for particular projects using the --local flag to bundle config, or re-define the github git shortcut in your gemfile

**Comment by indirect** [comment]
Good news! you can already make this a setting in your Gemfile. There’s an example of how to do it here: https://github.com/bundler/bundler/blob/master/lib/bundler/dsl.rb#L263

In Bundler 2, https will be the default.
