### ISSUE TITLE
Bundler v1.13.2 regression with Vlad

### ISSUE THREAD

**Issue by fgi** [bundler/bundler#5072]
I use Vlad 2.7.0 and just upgraded Bundler to 1.13.2.

I have following error when bundler is loaded for a rake task:
```
$ rake -T
rake aborted!
NameError: uninitialized constant Vlad::CommandFailedError
/home/rails/.rvm/gems/ruby-2.3.1@my-app/gems/bundler-1.13.2/lib/bundler/deployment.rb:18:in `define_task'
```

The issue is introduced in commit #4998 

`Vlad::CommandFailedError`has been removed from Vlad since v2.0.0. It does not exist anymore:
https://github.com/seattlerb/vlad/commit/548deb834e27683cde23897d22c9f0b4cd87cac0

But `Rake::CommandFailedError` does exist in a Vlad dependency gem from the same team called rake-remote_task: 
https://github.com/seattlerb/rake-remote_task

Bundler seems to work fine with Vlad without this change. Is there any particular raison for this commit to occur?
If not, would it be possible to revert it?

Thanks.

**Comment by segiddins** [comment]
@srbaker any interest in looking into this?

**Comment by salemine** [comment]
I left a comment with this commit to explain this: https://github.com/bundler/bundler/commit/c5a889ce865cc0314597e9de11e2bee366e797ac

**Comment by lynnco** [comment]
That change was reverted in [1.13.4](https://github.com/bundler/bundler/commit/f084b9043fd631f469f9fffde9be70ee067bccb1), closing!

**Comment by fgi** [comment]
The issue is resolved, no error anymore.
Many thanks.
