### ISSUE TITLE
outdated shouldn't say "Bundle up to date!" if results are just filtered out.

### ISSUE THREAD

**Issue by chrismo** [bundler/bundler#5076]
See this case: https://github.com/chrismo/bundler-cases/blob/master/cases/issues/bundler-5076.rb

If your gem file only has a major increment available, and the `--minor` or `--patch` options are fed to it, it filters out the major update, but then still says, "Bundle up to date!" which isn't true.

**Comment by chrismo** [comment]
... just not sure what it _should_ say. Maybe "No %{level} updates available" or somesuch.

**Comment by segiddins** [comment]
> ... just not sure what it should say. Maybe "No %{level} updates available" or somesuch.

sounds reasonable to me

**Comment by chrismo** [comment]
good - that's what i went with :) you can review on #5061.
