### ISSUE TITLE
uninitialized constant FriendlyErrors w/ JRuby 1.7.26

### ISSUE THREAD

**Issue by perlun** [bundler/bundler#5080]
I get this error when running specs after updating Bundler to 1.13.3:

```
NameError: uninitialized constant FriendlyErrors
         const_missing at org/jruby/RubyModule.java:2719
  with_friendly_errors at /Users/plundberg/.rvm/gems/jruby-1.7.26/gems/bundler-1.13.3/lib/bundler/friendly_errors.rb:102
                (root) at /Users/plundberg/.rvm/gems/jruby-1.7.26/gems/bundler-1.13.3/exe/bundle:26
                  load at org/jruby/RubyKernel.java:1059
                (root) at /Users/plundberg/.rvm/gems/jruby-1.7.26/bin/bundle:1
                  eval at org/jruby/RubyKernel.java:1079
                (root) at /Users/plundberg/.rvm/gems/jruby-1.7.26/bin/bundle:23
```

**Comment by segiddins** [comment]
Given that we're inside the `FriendlyErrors` module, I'm not quite sure how that's possible? https://github.com/bundler/bundler/blob/v1.13.3/lib/bundler/friendly_errors.rb#L7

**Comment by chrismo** [comment]
Line 102 on 1-13-stable looks like it's just outside the end of the module declaration. https://github.com/bundler/bundler/blob/1-13-stable/lib/bundler/friendly_errors.rb#L102 - I would presume that the module had already been loaded ... but maybe there's something JRuby specific about this case?

**Comment by colby-swandale** [comment]
ping @perlun

**Comment by colby-swandale** [comment]
I'm closing this for now. If you're still experiencing your original issue don't be afraid to re-open this ticket.

**Comment by corbanmailloux** [comment]
I seem to be experiencing this as well with JRuby 1.7.23 on Mac OSx 10.14.6 and bundler v1.17.3.

I have a project that uses Rake and I'm getting this error at initialization time before my rake logic has even started:
```
NameError: uninitialized constant FriendlyErrors
         const_missing at org/jruby/RubyModule.java:2745
  with_friendly_errors at /Users/corbanmailloux/.rvm/gems/jruby-1.7.23@cpw/gems/bundler-1.17.3/lib/bundler/friendly_errors.rb:128
                (root) at /Users/corbanmailloux/.rvm/gems/jruby-1.7.23@cpw/gems/bundler-1.17.3/exe/bundle:22
                  load at org/jruby/RubyKernel.java:1059
                (root) at /Users/corbanmailloux/.rvm/gems/jruby-1.7.23@cpw/bin/bundle:1
                  eval at org/jruby/RubyKernel.java:1079
                (root) at /Users/corbanmailloux/.rvm/gems/jruby-1.7.23@cpw/bin/jruby_executable_hooks:24
```

This didn't used to happen, and I'm trying to figure out what exactly changed to start causing it. I'm questioning if some gem or dependency was upgraded, but this appears to be an issue inside of bundler.
I've tried reinstalling JRuby, reinstalling Bundler, `bundle pristine`, downgrading Bundler to v1.16, and creating new gemsets. So far nothing has helped.

**Comment by deivid-rodriguez** [comment]
Unfortunately jruby 1.7 is too old, would you be able to upgrade your jruby version? One thing you could also try would be to remove the `rubygems-bundler` gem through `gem uninstall rubygems-bundler`.

**Comment by corbanmailloux** [comment]
We are working on upgrading the JRuby version in use for this project, but currently it's stuck at 1.7.
I tried removing the suggested gem and saw no change.
