### ISSUE TITLE
Change bundle outdated --strict options for 2.0

### ISSUE THREAD

**Issue by chrismo** [bundler/bundler#5081]
`outdated` would be more consistent to change `--strict` to `--filter-strict` and `--update-strict` to `--strict`. See #5061.

**Comment by chrismo** [comment]
Another option is to remove --strict/--filter-strict altogether, change the default behavior to show both the newest gem version that adheres to declared requirement AND newest gem version overall.

**Comment by chrismo** [comment]
In addition to showing both, don't just show the gem name, but show the name and declared requirement (if any) in the gemfile.

**Comment by segiddins** [comment]
@chrismo any interest in doing this for 2.0?

**Comment by indirect** [comment]
I would prefer to remove all of the flags and show all the things. 👍

**Comment by segiddins** [comment]
@chrismo any interest in tackling that?

**Comment by segiddins** [comment]
I'm actually a bit unclear on what needs to change here. Are we just wholesale removing the options without any other changes? If not, can someone share a diff of the desired behavior? I'm really not familiar with the `outdated` command

**Comment by chrismo** [comment]
Sorry I didn't see your posts - I haven't been able to keep up with Bundler emails. I'm not going to have any bandwidth in the near future. 

We have two options here - one is to just remove these flags from this command and enhance the output to show (a) the version that would be resolved to with bundle update AND (b) the latest available version regardless of declared requirements. This is cooler, but more work.

The other option, is to keep the flags more consistent with bundle update, because when I added my code, `bundle update` did NOT have a `--strict` option, so I used it ... but `bundle outdated` DID have a pre-existing `--strict` option (though it meant something different).

My desire for 2.0 was to just rename flags, but that would actually change what `--strict` actually does. Just swapping the names should be easy to do.

**Comment by indirect** [comment]
@chrismo thanks for the update!

@segiddins let's rename --strict to --filter-strict and rename the current --update-strict to --strict. In another ticket, later, we can expand the way outdated works to not need as many flags to show the relevant info.

**Comment by segiddins** [comment]
Closed by #6030.
