### ISSUE TITLE
Remove bundle show --outdated for 2.0?

### ISSUE THREAD

**Issue by chrismo** [bundler/bundler#5082]
`bundle show --outdated` is a minimal, duplicate implementation of `bundle outdated` ... perhaps we should just remove that flag (and/or change it to redirect to the outdated command). See #5061.

**Comment by chrismo** [comment]
ah, this is a dupe of a thing within #4754.

**Comment by lynnco** [comment]
#4754 is a bit busy, so I think its reasonable to leave this as a single todo list item

**Comment by segiddins** [comment]
`bundle show` is gone in 2.0
