### ISSUE TITLE
Not able to use outdated --groups 

### ISSUE THREAD

**Issue by ryanfox1985** [bundler/bundler#5083]
Hi,

I tried to use the latest version of bundler 1.13.3 that already have merged my PR(https://github.com/bundler/bundler/pull/4841) and it's not working the command with new options, the output is:
```
$ bundle outdated --groups
Unknown switches '--groups'
```

Regards.

**Comment by lynnco** [comment]
At a glance, it seems I tagged your PR with 1.14 so it should not be in 1.13.3 yet

**Comment by segiddins** [comment]
Yup, it will ship with 1.14 -- in general, we don't backport new features in patch releases.
