### ISSUE TITLE
undefined method `start_with?' for nil:NilClass

### ISSUE THREAD

**Issue by mdumke** [bundler/bundler#5084]
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `/home/ubuntu/.rvm/gems/ruby-2.3.0@rails5/gems/bundler-1.13.3/exe/bundle exec spring binstub --all`

- What did you expect to happen?

  I expected Bundler to install the binstubs for a newly created rails5 project.

- What happened instead?

  Instead, what happened was the following error.

Error details

    NoMethodError: undefined method `start_with?' for nil:NilClass
      /home/ubuntu/.rvm/gems/ruby-2.3.0@rails5/gems/bundler-1.13.3/lib/bundler/cli/exec.rb:95:in `block in ruby_shebang?'
      /home/ubuntu/.rvm/gems/ruby-2.3.0@rails5/gems/bundler-1.13.3/lib/bundler/cli/exec.rb:95:in `any?'
      /home/ubuntu/.rvm/gems/ruby-2.3.0@rails5/gems/bundler-1.13.3/lib/bundler/cli/exec.rb:95:in `ruby_shebang?'
      /home/ubuntu/.rvm/gems/ruby-2.3.0@rails5/gems/bundler-1.13.3/lib/bundler/cli/exec.rb:26:in `run'
      /home/ubuntu/.rvm/gems/ruby-2.3.0@rails5/gems/bundler-1.13.3/lib/bundler/cli.rb:332:in `exec'
      /home/ubuntu/.rvm/gems/ruby-2.3.0@rails5/gems/bundler-1.13.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /home/ubuntu/.rvm/gems/ruby-2.3.0@rails5/gems/bundler-1.13.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /home/ubuntu/.rvm/gems/ruby-2.3.0@rails5/gems/bundler-1.13.3/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /home/ubuntu/.rvm/gems/ruby-2.3.0@rails5/gems/bundler-1.13.3/lib/bundler/cli.rb:20:in `dispatch'
      /home/ubuntu/.rvm/gems/ruby-2.3.0@rails5/gems/bundler-1.13.3/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /home/ubuntu/.rvm/gems/ruby-2.3.0@rails5/gems/bundler-1.13.3/lib/bundler/cli.rb:11:in `start'
      /home/ubuntu/.rvm/gems/ruby-2.3.0@rails5/gems/bundler-1.13.3/exe/bundle:34:in `block in <main>'
      /home/ubuntu/.rvm/gems/ruby-2.3.0@rails5/gems/bundler-1.13.3/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
      /home/ubuntu/.rvm/gems/ruby-2.3.0@rails5/gems/bundler-1.13.3/exe/bundle:26:in `<main>'

Environment
      
  Bundler   1.13.3
  Rubygems  2.5.1
  Ruby      2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]
  GEM_HOME  /home/ubuntu/.rvm/gems/ruby-2.3.0@rails5
  GEM_PATH  /home/ubuntu/.rvm/gems/ruby-2.3.0@rails5:/home/ubuntu/.rvm/gems/ruby-2.3.0@global
  RVM       1.27.0 (latest)
  Git       2.7.4
  rubygems-bundler (1.4.4)
      
      Bundler settings
      
  bin_path
    Set via BUNDLE_BIN_PATH: "/home/ubuntu/.rvm/gems/ruby-2.3.0@rails5/gems/bundler-1.13.3/exe/bundle"
  gemfile
    Set via BUNDLE_GEMFILE: "/home/ubuntu/somefolder/someproject/Gemfile"
--- TEMPLATE END ----------------------------------------------------------------

**Comment by mdumke** [comment]
After a bit of debugging I figured out that my spring-executable existed but was empty for some reason. A re-install fixed the problem for me.

**Comment by segiddins** [comment]
Can you share a project we can use to reproduce the issue? Thanks!

**Comment by mdumke** [comment]
I'm afraid the error was not specific to any project but occured after running the `rails new` command. Apparently the problem was that the `ruby_shebang?` method in  `/lib/bundler/cli/exec.rb` tried to extract the first line of `/home/ubuntu/.rvm/gems/ruby-2.3.0@rails5/bin/spring`. In my case the spring-file existed but was empty for some reason (perhaps some network issue during installation), so the `first_line`-variable was nil. Bundler correctly checks for the existence of the spring-file but then assumes it is non-empty.

**Comment by segiddins** [comment]
Ah. A PR fixing that would be great!

**Comment by lynnco** [comment]
@mdumke given that an empty spring-file is an issue itself, what do you think would be a good option here? A "<FILENAME> is empty" warning message, then continuing?
