### ISSUE TITLE
Version as an optional parameter for bundle inject 

### ISSUE THREAD

**Issue by fredrb** [bundler/bundler#5086]
As for now, `bundle inject` requires a `version` parameter with no default value. 

`Usage: "bundle inject GEM VERSION ..."`

From my point of view, it makes sense to run: 
`bundle inject 'rake'`
and get the latest version of the gem. 

Also, `CLI::Inject` class is already expecting `nil` as a feasible parameter for `version`. But this will never happend because `version` is specified as a required parameter. 
```ruby
    def initialize(options, name, version, gems)
      @options = options
      @name = name
      @version = version || last_version_number
      @group = options[:group]
      @source = options[:source]
      @gems = gems
    end

```

**Comment by indirect** [comment]
I think this would be provided by https://github.com/bundler/bundler/issues/4901, so I will close this ticket in favor of that one.
