### ISSUE TITLE
Track progress of bundler benchmarks added to ruby-bench

### ISSUE THREAD

**Issue by hmistry** [bundler/bundler#5088]
The purpose of this issue is to document this work was done and to track progress for metrics added to bundler's ruby-bench benchmarks. Benchmarks for `bundle install`, `bundle outdated`, and `bundle lock` have been added in the following [PR](https://github.com/ruby-bench/ruby-bench-suite/pull/71). The PR has been merged but the benchmarks doesn't show up on the website.

**Comment by lynnco** [comment]
@hmistry does this issue relate to https://github.com/rubygems/rubygems.org/pull/1390 ?

**Comment by hmistry** [comment]
@lynnco No it's not related to that. This was to add more benchmarks for bundler on [rubybench.org](https://rubybench.org/bundler/bundler/releases).

I hope it's ok to make this issue. I thought that way it's not forgotten that the work is done, only missing the last step of making it live on Rubybench website.

**Comment by lynnco** [comment]
@hmistry I wasn't specifically aware of anything needing to be done with rubybench.org, so yes it was a good issue to make 👍

**Comment by colby-swandale** [comment]
Is this still being worked on?

**Comment by hmistry** [comment]
@colby-swandale The PR was merged - so it's done. For reference: https://github.com/ruby-bench/ruby-bench-suite/pull/71
