### ISSUE TITLE
error

### ISSUE THREAD

**Issue by tmasri** [bundler/bundler#5091]
- What did you do?

  I ran the command `/usr/local/bin/bundle install`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what happened was...

Error details

    Errno::EACCES: Permission denied @ dir_s_mkdir - /home/t/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/versions20161014-13436-11fzl9m
      /usr/lib/ruby/2.3.0/tmpdir.rb:86:in `mkdir'
      /usr/lib/ruby/2.3.0/tmpdir.rb:86:in `block in mktmpdir'
      /usr/lib/ruby/2.3.0/tmpdir.rb:130:in `create'
      /usr/lib/ruby/2.3.0/tmpdir.rb:86:in `mktmpdir'
      /var/lib/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:29:in `update'
      /var/lib/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:64:in `update'
      /var/lib/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:55:in `update_and_parse_checksums!'
      /var/lib/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/fetcher/compact_index.rb:67:in `available?'
      /var/lib/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/fetcher/compact_index.rb:15:in `call'
      /var/lib/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/fetcher/compact_index.rb:15:in `block in compact_index_request'
      /var/lib/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/fetcher.rb:157:in `use_api'
      /var/lib/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/source/rubygems.rb:332:in `block in api_fetchers'
      /var/lib/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/source/rubygems.rb:332:in `select'
      /var/lib/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/source/rubygems.rb:332:in `api_fetchers'
      /var/lib/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/source/rubygems.rb:337:in `block in remote_specs'
      /var/lib/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/index.rb:10:in `build'
      /var/lib/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/source/rubygems.rb:336:in `remote_specs'
      /var/lib/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/source/rubygems.rb:83:in `specs'
      /var/lib/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/definition.rb:263:in `block (2 levels) in index'
      /var/lib/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/definition.rb:261:in `each'
      /var/lib/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/definition.rb:261:in `block in index'
      /var/lib/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/index.rb:10:in `build'
      /var/lib/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/definition.rb:258:in `index'
      /var/lib/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/definition.rb:252:in `resolve'
      /var/lib/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/definition.rb:176:in `specs'
      /var/lib/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/definition.rb:164:in `resolve_remotely!'
      /var/lib/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/installer.rb:225:in `resolve_if_need'
      /var/lib/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/installer.rb:78:in `run'
      /var/lib/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/installer.rb:24:in `install'
      /var/lib/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/cli/install.rb:71:in `run'
      /var/lib/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/cli.rb:189:in `install'
      /var/lib/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /var/lib/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /var/lib/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /var/lib/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/cli.rb:20:in `dispatch'
      /var/lib/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /var/lib/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/cli.rb:11:in `start'
      /var/lib/gems/2.3.0/gems/bundler-1.13.1/exe/bundle:34:in `block in <top (required)>'
      /var/lib/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
      /var/lib/gems/2.3.0/gems/bundler-1.13.1/exe/bundle:26:in `<top (required)>'
      /usr/local/bin/bundle:23:in `load'
      /usr/local/bin/bundle:23:in `<main>'

**Comment by lynnco** [comment]
@tmasri Look into how the other issues with permission errors were resolved https://github.com/bundler/bundler/search?q=Errno+EACCES+Permission+denied&type=Issues&utf8=%E2%9C%93. We'll be improving the permissions handling for Bundler 1.14
