### ISSUE TITLE
Can't install via bundle 

### ISSUE THREAD

**Issue by roushanj** [bundler/bundler#5092]
Installation can't be done using bundle if you are root user, bundle installation can only be done if you are non root user .
![screenshot from 2016-10-15 22-23-41](https://cloud.githubusercontent.com/assets/12628507/19411814/1aed171c-9326-11e6-8f0d-68128758c69c.png)

**Comment by segiddins** [comment]
Please share the full output of the error template

**Comment by lynnco** [comment]
@roushanj

> Please share the full output of the error template

And as text, not a picture

**Comment by segiddins** [comment]
Closing due to lack of response

**Comment by roushanj** [comment]
i m sorry to reply so late......

but apparently i solved the problem

thank you for your concern...
