### ISSUE TITLE
Bundle create a new folder inside Rails 5 project

### ISSUE THREAD

**Issue by AhmedNadar** [bundler/bundler#5096]
Today, Installed Ruby 2.3.1 and Rails 5.0.0.1. When I create a new project and run `bundle install`, bundler create a new folder where it storage or keep all gems locally with the project name.
For example. when I run `rails new simple_app`, and run `bundle install` it creates the following ["/usr/localexport/] folders and inside `localexport` [bin, build_info, cache, doc, extensions, gems, specifications].
I don't know why it does that!?

When I run the application I get the following error:
```
rails aborted!
SyntaxError: (eval):2: unexpected fraction part after numeric literal
...localexport/gems/rb-fsevent-0.9.7"
```

**Comment by segiddins** [comment]
@AhmedNadar can you please provide a list of steps to reproduce the issue that we can run locally? Thanks!

**Comment by AhmedNadar** [comment]
@segiddins I wasn't able to solve it until I uninstalled Ruby, Rails, HomeBrew, rbenv and RubyGems. It turns out that may local location for RubyGem was `./urs/localexport/...` therefor every time I create a new rails app it creates `./usr/localexport/` folder. 
Now it is fixed. Thanks!
