### ISSUE TITLE
bundle outdated seems to always run with "--strict"

### ISSUE THREAD

**Issue by NielsKSchjoedt** [bundler/bundler#5098]
In the latest version of bundler (1.13), when I run `bundle outdated` it reports no gems as outdated, even though I have a lot! This is as if the `--strict` option was provided - but it's not.

If I downgrade to bundler version 1.12, then it works normally

**Comment by chrismo** [comment]
This could be #4979 - can you check that issue and see if it describes what you are seeing?

**Comment by chrismo** [comment]
folks reports on #4979 also say it works in 1.12. I'm closing this issue as a duplicate of #4979.
