### ISSUE TITLE
jekyll serve error

### ISSUE THREAD

**Issue by Paladinhanxiao** [bundler/bundler#5109]
D:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/
resolver.rb:354:in `block in verify_gemfile_dependencies_are_found!': Could not
find gem 'minima (~> 2.0) x86-mingw32' in any of the gem sources listed in your
Gemfile or available on this machine. (Bundler::GemNotFound)
        from D:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.11.2
/lib/bundler/resolver.rb:330:in `each'
        from D:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.11.2
/lib/bundler/resolver.rb:330:in `verify_gemfile_dependencies_are_found!'
        from D:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.11.2
/lib/bundler/resolver.rb:199:in `start'
        from D:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.11.2
/lib/bundler/resolver.rb:183:in `resolve'
        from D:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.11.2
/lib/bundler/definition.rb:198:in `resolve'
        from D:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.11.2
/lib/bundler/definition.rb:137:in `specs'
        from D:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.11.2
/lib/bundler/definition.rb:182:in `specs_for'
        from D:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.11.2
/lib/bundler/definition.rb:171:in `requested_specs'
        from D:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.11.2
/lib/bundler/environment.rb:18:in `requested_specs'
        from D:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.11.2
/lib/bundler/runtime.rb:13:in `setup'
        from D:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.11.2
/lib/bundler.rb:92:in `setup'
        from D:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/jekyll-3.3.0/l
ib/jekyll/plugin_manager.rb:36:in `require_from_bundler'
        from D:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/jekyll-3.3.0/e
xe/jekyll:9:in `<top (required)>'
        from D:/RailsInstaller/Ruby2.2.0/bin/jekyll:23:in `load'
        from D:/RailsInstaller/Ruby2.2.0/bin/jekyll:23:in `<main>'

**Comment by Paladinhanxiao** [comment]
gem install minima

**Comment by segiddins** [comment]
Hi! It looks like you're running a very old version of bundler. Can you try updating and then running `bundle install`? Thanks!

**Comment by lynnco** [comment]
@Paladinhanxiao

> Hi! It looks like you're running a very old version of bundler. Can you try updating and then running bundle install? Thanks!

**Comment by Paladinhanxiao** [comment]
Thanks,This exception is caused because minima not install
