### ISSUE TITLE
command: which bundle

### ISSUE THREAD

**Issue by hilen** [bundler/bundler#5118]
I run the `which bundler`, I will get `/Users/hilen/.rbenv/shims/bundler`
But I run the `which bundle` and I get the message:
```
bundle () {
	run_with_bundler bundle "$@"
}
```

What does it mean ?

**Comment by colby-swandale** [comment]
You have a function that is being loaded in your terminal shell that is defining a function called `bundle` that is taking precedence over bundler's `bundle` command. Check any dot files like `.zshrc`, `.bashrc` for the function.

Make sure to close this issue as this is not actually an issue with bundler itself.

**Comment by hilen** [comment]
Thanks for the replay, I've been found the function.
