### ISSUE TITLE
unexpected error occurred, and Bundler cannot continue.

### ISSUE THREAD

**Issue by jwvincent** [bundler/bundler#5125]
Environment
      
  Bundler   1.12.5
  Rubygems  2.5.1
  Ruby      2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]
  GEM_HOME  /home/xxx/xxx/xxx/gems/.bundle/gems/ruby/2.3.0
  GEM_PATH  
  RVM       1.27.0 (latest)
  Git       1.9.1
      
      Bundler settings
      
  path
    Set for your local app (/home/xxx/xxx/xxx/gems/.bundle/config): ".bundle/gems"
  bin
    Set for your local app (/home/xxx/xxx/xxx/gems/.bundle/config): ".bundle/bin"
  disable_shared_gems
    Set for your local app (/home/xxx/xxx/xxx/gems/.bundle/config): true
  orig_path
    Set via BUNDLE_ORIG_PATH: "/home/xxx/bin:/home/xxx/xxx/xxx/xxx:/home/xxx/bin/scripts:/home/jvincent/bin:/home/xxx/xxx/xxx/bin:/home/xxx/software/hadoop-2.7.3/bin/:/home/xxx/.rvm/gems/ruby-2.3.0/bin:/home/xxx/.rvm/gems/ruby-2.3.0@global/bin:/home/xxx/.rvm/rubies/ruby-2.3.0/bin:/home/xxx/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/xxx/.rvm/bin:/home/xxx/.rvm/bin:.:/home/xxx/.rvm/bin"
  orig_gem_path
    Set via BUNDLE_ORIG_GEM_PATH: "/home/xxx/.rvm/gems/ruby-2.3.0:/home/xxx/.rvm/gems/ruby-2.3.0@global"

**Comment by segiddins** [comment]
Please share the entirety of the error report that Bundler is printing

**Comment by jwvincent** [comment]
I solved this issue by changing the default ruby verison.
