### ISSUE TITLE
Bundler::Molinillo::DependencyGraph::Action responds to #name with RuntimeError

### ISSUE THREAD

**Issue by emschwar** [bundler/bundler#5126]
From time to time I need to troll through ObjectSpace and look at the names of various modules. Recently, I started getting the following error:

```ruby
Bundler::Molinillo::DependencyGraph::Action.name # => raises RuntimeError: Abstract
```

Now, it's certainly fair to say that I should be more careful, and in fact, I've wrapped my code with a begin/rescue block to make sure that any methods I call on unknown modules are protected against exceptions, but I do think it's fairly reasonable to assume that I can call `#name` on a random `Module` and get a value of some kind back.

**Comment by segiddins** [comment]
Arg, you're right. Please open an issue/PR up at https://github.com/CocoaPods/Molinillo to change that method to `action_name`
