### ISSUE TITLE
Permission Denied - ran as root

### ISSUE THREAD

**Issue by willydistfb** [bundler/bundler#5130]
Hi, I am having the same issue as #4429.
Looking for a fix as I have already checked through all the similar threads; the only fixes I could find were "uninstall & reinstall bundler" and "make sure you have read permission on the file in question."

Unfortunately, I have tried uninstalling & reinstalling bundler, and this does not fix the issue for me.
I have also tried to `sudo chmod a+r .bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/versions` the appropriate version file, and this does not fix the issue, either.

Please help so I can continue working on rails applications.
Also in future releases, I hope that bundler will actually stop if you try to run as root.... I remember that, when I ran it as root, it basically told me, "You're about to mess everything up!" but didn't provide any way for me to cancel or abort the operation... Kinda frustrating.

But anyway thanks for your time.

**Comment by lynnco** [comment]
@willydistfb 

For the permissions error, I believe deleting `.bundle` is also a suggested resolution. I really don't have any other suggestions on this beyond the ones mentioned in [the other issues](https://github.com/bundler/bundler/search?q=Permission+denied+%40+dir_s_mkdir&type=Issues&utf8=%E2%9C%93)

> I hope that bundler will actually stop if you try to run as root

I believe this is covered by https://github.com/bundler/bundler/issues/5113 and https://github.com/bundler/bundler/pull/4956

**Comment by lynnco** [comment]
Closing due to waiting on user response. Feel free to ping a team member to re-open this issue if needed!
