### ISSUE TITLE
Incorrect "version could not be found in any of the sources" error

### ISSUE THREAD

**Issue by makstaks** [bundler/bundler#5141]
I'm using bundler version **1.13.6** and included gem 'stripe' in my Gemfile which gets version (1.56.0)

After a successful bundle install, I ran `rails console`and received this error:

> Your bundle is locked to unf_ext (0.0.7.2), but that version could not be found in any of the sources listed in your Gemfile. If you haven't changed sources, that means the author of unf_ext (0.0.7.2) has removed it. You'll need to update your bundle to a different version of unf_ext (0.0.7.2) that hasn't been removed in order to install.

**Actions taken**
1. Checked rubygems.org and confirmed that the gem has not been yanked.  
2. Tried bundle install --full-index, made no difference.
3.  Removed stripe gem and dependencies and did a fresh install, made no difference.

The only thing that made a difference was downgrading my bundler gem to 1.12.0

Note: I haven't tried other bundler versions yet.

**Update**
1. I restarted my computer and now bundler version 1.13.6 installs the stripe gem and I can run rails console.  It doesn't explain why I was getting the error message, it would be good to know how to better handle such an error.

**Comment by segiddins** [comment]
Please share the full output of `bundle env`

**Comment by segiddins** [comment]
Closing due to lack of response.
