### ISSUE TITLE
Unsynchronized, concurrent modification of Set instance

### ISSUE THREAD

**Issue by brixen** [bundler/bundler#5142]
- What did you do?

  I ran the command `/source/rubinius/rubinius/gems/bin/bundle update` on Rubinius 3.64.

- What did you expect to happen?

  I expected Bundler to update the gems for a new Rails 5.0 application.

- What happened instead?

  Instead, what happened was Bundler failed due to an invalid modification of a Hash structure underlying a Set instance.

Unless Ruby has recently changed the concurrency guarantees of Set, it makes no guarantee of correctness under concurrent, unsynchronized modification.

Error details

    Rubinius::ObjectBoundsExceededError: Tuple::copy_from: index 10 out of bounds for size 9
      core/hash.rb:216:in `insert'
      core/hash.rb:411:in `[]='
      /source/rubinius/rubinius/gems/gems/rubysl-set-2.0.1/lib/rubysl/set/set.rb:229:in `add'
      /source/rubinius/rubinius/gems/gems/rubysl-set-2.0.1/lib/rubysl/set/set.rb:240:in `add?'
      /Users/brianshirai/.gem/rbx/3.64/gems/bundler-1.13.6/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:64:in `update'
      /Users/brianshirai/.gem/rbx/3.64/gems/bundler-1.13.6/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:73:in `update_info'
      /Users/brianshirai/.gem/rbx/3.64/gems/bundler-1.13.6/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:44:in `dependencies'
      core/proc.rb:20:in `call'
      /Users/brianshirai/.gem/rbx/3.64/gems/bundler-1.13.6/lib/bundler/fetcher/compact_index.rb:86:in `compact_index_client'
      core/proc.rb:20:in `call'
      /Users/brianshirai/.gem/rbx/3.64/gems/bundler-1.13.6/lib/bundler/worker.rb:65:in `apply_func'
      /Users/brianshirai/.gem/rbx/3.64/gems/bundler-1.13.6/lib/bundler/worker.rb:60:in `process_queue'
      core/kernel.rb:585:in `loop'
      /Users/brianshirai/.gem/rbx/3.64/gems/bundler-1.13.6/lib/bundler/worker.rb:57:in `process_queue'
      /Users/brianshirai/.gem/rbx/3.64/gems/bundler-1.13.6/lib/bundler/worker.rb:29:in `initialize'
      core/proc.rb:20:in `call'

Environment

  Bundler   1.13.6
  Rubygems  2.6.6
  Ruby      2.3.1p0 (2016-10-31 revision 0) [x86_64-darwin16.0.0]
  GEM_HOME  /Users/brianshirai/.gem/rbx/3.64
  GEM_PATH  /Users/brianshirai/.gem/rbx/3.64:/source/rubinius/rubinius/gems
  Git       2.5.3

      Bundler settings

  gem.test
    Set for the current user (/Users/brianshirai/.bundle/config): "false"
  gem.mit
    Set for the current user (/Users/brianshirai/.bundle/config): "false"
  gem.coc
    Set for the current user (/Users/brianshirai/.bundle/config): "true"
  build.eventmachine
    Set for the current user (/Users/brianshirai/.bundle/config): "--with-cppflags=-I/usr/local/opt/openssl/include"

**Comment by segiddins** [comment]
@brixen I'm working on this now. Is there a list of the primitives that are actually thread-safe, as opposed to being dependent on the GIL to be so?

**Comment by brixen** [comment]
@segiddins thank you for working on this! ❤️ 

The best approach I can suggest is to assume that *nothing* is thread-safe unless it explicitly says it is made to be thread-safe and documents the invariants it enforces (eg Queue).

Unfortunately, the vast majority of MRI documentation is not well written for understanding concurrency. But I'd suggest that is largely because MRI was never intended to *do* concurrency. So, you need to fall back on general principles.

Here's the "concurrency sanity" refrain: *Sharing state is fine; mutating state is fine; mutating shared state is NOT fine.*

If an object is changed from more than one thread, synchronize around that change.

Finally, **the GIL does not make things thread-safe**. The GIL is not formally specified. The GIL is actually a zillion places in the C code where a lock is released or acquired. That code can change at any time and it has and it will. **The GIL does not make things thread-safe.** **The GIL does not make things thread-safe.** **The GIL does not make things thread-safe.** I sound like a broken record because this is so critical.

No discussion about thread safety should mention the GIL. Thread-safety is a property of specific pieces of code based on specific invariants that are guaranteed to be maintained. For the benefit of everyone who uses Ruby and everyone who tries to make Ruby better for people, discussions of thread-safety must not rely on the GIL.

**Comment by segiddins** [comment]
Yes, and that's why I'm saying I want to know what is _actually_ thread-safe, rather than relying upon "this works in MRI" as my benchmark. I presume that `Mutex`, `Thread`, and `Queue` should all be good to rely upon. I've already made a PR fixing the Set mutation by putting it behind a mutex, but am occasionally running into a modify-after-free that's failing to print out backtraces.

**Comment by brixen** [comment]
@segiddins I cannot give you a list of what is thread-safe as I don't know of one that exists. So my best information is: 1. NOT the GIL; and 2. specific documentation for specific classes / methods.

This means that for every piece of code that *could* be run by more than one thread, *every* operation that does not explicitly document invariants under concurrent modification must be synchronized.

I'd be happy to help you look at specific code.
