### ISSUE TITLE
Bundler versioning and upgrade warning should respect SemVer

### ISSUE THREAD

**Issue by mtgrosser** [bundler/bundler#5143]
> Warning: the running version of Bundler (1.13.1) is older than the version that created the lockfile (1.13.5). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.

According to SemVer, PATCH version changes should be backwards compatible. Therefore, the bundler upgrade warning should only be displayed when there are backwards-incompatible changes. The current warning pops up on every new patch release, and is quite distracting in the daily workflow. With regard to bundler's current versioning scheme, the warning should only be displayed on MINOR version differences.

**Comment by segiddins** [comment]
We fix critical bugs and regressions in patch releases, that is why we print the warning.

**Comment by lynnco** [comment]
To be clear, our PATCH version changes are in fact backwards compatible. Also, to my knowledge, SemVar says nothing about version upgrade messages. If you think it should, you should [talk to them about it!](https://github.com/mojombo/semver/issues)

Go resolve this on that end, then get back to us! ^_^
