### ISSUE TITLE
Add support for minitest/spec

### ISSUE THREAD

**Issue by zotherstupidguy** [bundler/bundler#5150]
Provide minitest/spec commandline interface via `bundler gem --test=minitest/spec my_gem`

Seems to https://github.com/bundler/bundler/blob/33d2f67d56fe8bf00b0189c26125d27527ef1516/lib/bundler/cli/gem.rb#L36 is a good place to start.

**Comment by segiddins** [comment]
I don't think this is something we're interested in providing -- `bundle gem` is meant to be as minimal as possible. If you're looking for more extensive customizability options, I recommend you look at other projects such as ore.
