### ISSUE TITLE
Custom-gem-generator Interface

### ISSUE THREAD

**Issue by zotherstupidguy** [bundler/bundler#5151]
When a ruby framework wants to include its own gem generator it usually resort to using a tool like Thor, yet it is best if Bundler become the goto for such usecase as it would provide an interface for other ruby projects to inherit from and customize according to their needs. This would maintain a level consistency among ruby frameworks.

Thoughts?

**Comment by lynnco** [comment]
@zotherstupidguy can you provide more clarity / context on this request?

**Comment by lynnco** [comment]
Potentially related to https://github.com/bundler/bundler/issues/5156 ?

**Comment by segiddins** [comment]
This is something the bundler project is explicitly not interested in providing -- `bundle gem` is meant to be super-opinionated and easy for us to maintain, anything more should be handled by tooling explicitly about creating new gems.

**Comment by zotherstupidguy** [comment]
@lynnco @segiddins bundle gem can remain super-opinionated about the interface it declares, but that interface it should stand in the way of customizing the generated gems, I am sure that some ruby magic can come into play to get this done probably, especially that bundler includes gem generation as a functionality, thus either it is done probably or it should be removed out.

I imagine frameworks like Rails, Padrino, Hanami, etc. make use of a bundler interface(class or module) for gem generation, and add their sauce. As Bundler uses thor under the hood it would be neat to get things started for framework developers and they don't have to struggle making sure that their generated gems are bundler compliant.

**Comment by segiddins** [comment]
This isn't something that bundler wants to be involved in. We'll leave it to projects like ore to support extreme customization, and continue to offer `bundle gem` as a highly opinionated, bare-bones scaffolding option that no one is forced to use if they disagree with its choices.
