### ISSUE TITLE
"TODO" in gemspec template breaks methadone on generation

### ISSUE THREAD

**Issue by mbigras** [bundler/bundler#5156]
Hi all!

I've been working on a methadone [issue](https://github.com/davetron5000/methadone/issues/103), where methadone is using `bundle gem` to generate a gemspec [here](https://github.com/davetron5000/methadone/blob/master/bin/methadone#L26) but it breaks for two reasons:

1.Bundle isn't happy about `TODO` in the gemspec, it needs to be `todo` or some other nonecaps thing.
2. The `spec.homepage` need to either be empty or some site-like pattern like `https://rubygems.org`

I think it's from [lines 12-14](https://github.com/bundler/bundler/blob/b3cb9516aaf83cf865c9ed76c52ec4d0d182015f/lib/bundler/templates/newgem/newgem.gemspec.tt#L12) in the newgem template that `bundle gem` uses.

There result is you need to go in and make some replacements before you can get methadone to work.

Is this intentional? Looking forward to hearing from you 😄 

also great job @indirect in your [ruby conf](https://www.youtube.com/watch?v=4DqzaqeeMgY) video! it was a fun and informative watch 👍

**Comment by lynnco** [comment]
@mbigras rubygems does gemspec validation, which includes a regex for `TODO` or `FIXME` [(src)](https://github.com/rubygems/rubygems/blob/61b1ed574fc06ec8a704d3b9441a2543ffbd64df/lib/rubygems/specification.rb#L2806-L2808). and `spec.homepage` does a similar thing a few lines down. So yes, its intentional.

Looking over the methadone issue though, it looks like ideally you want to use a `bundle gem` flag that creates a new gem that's "ready to go" ? (thinking about this is why I preemptively added the feature request label, heh)

**Comment by segiddins** [comment]
`bundle gem` purposely leaves the TODOs in, as well as things to complete in the README, etc. if you're looking for a more customizable way to automate create gems, there are several options , including something called ore, I believe.

**Comment by mbigras** [comment]
Hi @lynnco @segiddins!

Thank you for getting back to me. Okay I just wanted to check, it makes sense for the TODOs to be the default behavior and to check the homepage for a valid url.

A `--no-todos` switch and a `--default-website` switch (that would read the a site from `~/.bundle/config`) could be cool, but super low priority :P maybe hense the triage flag.

I made a small script for anyone interested:

```rb
public_site = "https:\/\/github.com/mbigras"
gemspec = Dir['*.gemspec'].first

gemspec_contents = File.open(gemspec).read
transformed_gemspec_contents = gemspec_contents
.gsub(/TODO: /, '')
.gsub(/^.*\('rake'\)\n/, '')
.gsub(/Put your.*here\./, public_site)

File.write(gemspec, transformed_gemspec_contents)
```
