### ISSUE TITLE
How to update bundler itself to version in gemlock

### ISSUE THREAD

**Issue by StevePotter** [bundler/bundler#5159]
This is for our CI system.  They have a bundler version preinstalled that is slightly older than the one we used to create our Gemfile.lock.  I'd like to add a command to update the bundler version to the one after "Bundled With" at the bottom of the Gemlock.  I scanned the docs and web and didn't find anything.  Is this easily achievable?

**Comment by segiddins** [comment]
You can use the `postit`  gem or the `BUNDLE_ENABLE_TRAMPOLINE` environment variable (https://github.com/bundler/bundler/blob/master/lib/bundler/postit_trampoline.rb#L15)

**Comment by StevePotter** [comment]
Thanks @segiddins !
