### ISSUE TITLE
Document Git HTTPS authentication via env/config

### ISSUE THREAD

**Issue by indirect** [bundler/bundler#5172]
[Storing Git HTTP source credentials in the config](https://github.com/bundler/bundler/pull/3898) was added in 1.11, but it's not documented in [the bundle config manpage](https://github.com/bundler/bundler/blob/master/man/bundle-config.ronn#L211) or [the sources section of the Gemfile manpage](https://github.com/bundler/bundler/blob/master/man/gemfile.5.ronn#L36). Let's document it.

**Comment by seanarnold** [comment]
I've added a PR for documenting the `bundle config` addition.

**Comment by segiddins** [comment]
Closed by https://github.com/bundler/bundler/issues/5173.
