### ISSUE TITLE
Store a Gemfile checksum in Gemfile.lock

### ISSUE THREAD

**Issue by ChaeOkay** [bundler/bundler#5177]
Store a Gemfile checksum in Gemfile.lock, so we can skip the resolver when unchanged

- [x] Generate checksum of Gemfile
- [x] Store checksum in Gemfile.lock
- [ ] Compare checksums to determine if Gemfile has changed, and if not, skip the resolver
- [ ] Add tests

References [Tasks anyone can claim](https://github.com/bundler/bundler/issues/4871)

**Comment by ChaeOkay** [comment]
Working on this with @CoralineAda

**Comment by lynnco** [comment]
@ChaeOkay @CoralineAda let me know if I can find some info / help for you! I figure you'll make a PR when you're ready ^_^

**Comment by colby-swandale** [comment]
ping @ChaeOkay, is still being worked on?

**Comment by ChaeOkay** [comment]
@colby-swandale apologies for not messaging earlier, unfortunately not at this time.

**Comment by alextaylor000** [comment]
I can pick this up @colby-swandale, I've been hunting for something to work on 😄

**Comment by colby-swandale** [comment]
Awesome! I think @hmistry is currently working on something like this currently?

**Comment by hmistry** [comment]
@alextaylor000 Yep I'm working on this. At this point, it's an exploration feature. 
@colby-swandale thanks.

**Comment by colby-swandale** [comment]
@alextaylor000 i'll update #4871 with some new issues that you're welcome to work on

**Comment by alextaylor000** [comment]
Ok, no worries :)
