### ISSUE TITLE
bundler does Ruby string interpolation on Gemfile leading to arbitrary Ruby code execution

### ISSUE THREAD

**Issue by justinsteven** [bundler/bundler#5178]
This is a bit strange

```text
$ cd $(mktemp -d)
$ echo 'gem="#{`cowsay bundler stahp >&2`}"' > Gemfile
$ bundle install
 _______________
< bundler stahp >
 ---------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||
The Gemfile specifies no dependencies
Resolving dependencies...
Bundle complete! 0 Gemfile dependencies, 1 gem now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
```

A user who `bundle installs` a malicious Gemfile is already in for a world of hurt, but is this expected behaviour? I'm fully expecting to hear "yes, it is expected behaviour" and "there are so many ways a malicious Gemfile can hurt you, this is not strange or dangerous"

**Comment by chrismo** [comment]
At least to the extent that it is expected that `instance_eval`-ing the contents of the Gemfile leaves a pretty open door, yes: https://github.com/bundler/bundler/blob/master/lib/bundler/dsl.rb#L40-L41 :)

Given the history here and, as you say, installing gems which can invoke native build scripts and post-install fu are pretty fraught with general peril, I doubt it'd be worth the trouble to be more selective in how the contents of the Gemfile are processed.

But, I also suppose one could argue that `instance_eval` is an overly-convenient way to go about things here.

**Comment by justinsteven** [comment]
Ah. Right. Gemfiles are basically entirely executed as Ruby. I thought I was being clever in using string interpolation.

```text
% echo '`cowsay oh I see now >&2`' > Gemfile 
% bundle install
 ______________
< oh I see now >
 --------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||
The Gemfile specifies no dependencies
Bundle complete! 0 Gemfile dependencies, 1 gem now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
```

**Comment by indirect** [comment]
For the record, we have definitely talked about creating a Gemfile parser/interpreter in the future that does not use `instance_eval`. The catch is that if we do that, many people/companies will no longer be able to do unusual or sketchy things in their Gemfiles—that's good, in that there's less sketchy stuff happening, but that's bad in that then those people will want us to fix their problem a different way. Right now `instance_eval` is the sweet spot for giving people flexibility while keeping most people on the same page.
