### ISSUE TITLE
bundle update fails - it has worked fine before...

### ISSUE THREAD

**Issue by antwerpenR** [bundler/bundler#5179]
- What did you do?

  I ran the command `/Users/centerstage/.rbenv/versions/2.3.1/bin/bundle update`

- What did you expect to happen?

  I expected Bundler to...update cocoapods and fastlane - this has worked fine before.

- What happened instead?

  Instead, what happened was...

Error details

    Errno::EACCES: Permission denied @ rb_file_s_rename - (/var/folders/sz/rgl2y25919394t9bry13rg740000gs/T/bundler-compact-index-20161116-58163-1md1gk9/versions, /Users/centerstage/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/versions)
      /Users/centerstage/.rbenv/versions/2.3.1/lib/ruby/2.3.0/fileutils.rb:528:in `rename'
      /Users/centerstage/.rbenv/versions/2.3.1/lib/ruby/2.3.0/fileutils.rb:528:in `block in mv'
      /Users/centerstage/.rbenv/versions/2.3.1/lib/ruby/2.3.0/fileutils.rb:1571:in `block in fu_each_src_dest'
      /Users/centerstage/.rbenv/versions/2.3.1/lib/ruby/2.3.0/fileutils.rb:1587:in `fu_each_src_dest0'
      /Users/centerstage/.rbenv/versions/2.3.1/lib/ruby/2.3.0/fileutils.rb:1569:in `fu_each_src_dest'
      /Users/centerstage/.rbenv/versions/2.3.1/lib/ruby/2.3.0/fileutils.rb:517:in `mv'
      /Users/centerstage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:55:in `block in update'
      /Users/centerstage/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
      /Users/centerstage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:29:in `update'
      /Users/centerstage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:65:in `update'
      /Users/centerstage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:56:in `update_and_parse_checksums!'
      /Users/centerstage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/fetcher/compact_index.rb:67:in `available?'
      /Users/centerstage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/fetcher/compact_index.rb:15:in `call'
      /Users/centerstage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/fetcher/compact_index.rb:15:in `block in compact_index_request'
      /Users/centerstage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/fetcher.rb:157:in `use_api'
      /Users/centerstage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:332:in `block in api_fetchers'
      /Users/centerstage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:332:in `select'
      /Users/centerstage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:332:in `api_fetchers'
      /Users/centerstage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:337:in `block in remote_specs'
      /Users/centerstage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/index.rb:10:in `build'
      /Users/centerstage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:336:in `remote_specs'
      /Users/centerstage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:83:in `specs'
      /Users/centerstage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.rb:261:in `block (2 levels) in index'
      /Users/centerstage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.rb:259:in `each'
      /Users/centerstage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.rb:259:in `block in index'
      /Users/centerstage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/index.rb:10:in `build'
      /Users/centerstage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.rb:256:in `index'
      /Users/centerstage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.rb:250:in `resolve'
      /Users/centerstage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.rb:174:in `specs'
      /Users/centerstage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.rb:162:in `resolve_remotely!'
      /Users/centerstage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/installer.rb:225:in `resolve_if_need'
      /Users/centerstage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/installer.rb:78:in `run'
      /Users/centerstage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/installer.rb:24:in `install'
      /usr/local/Cellar/rbenv/1.0.0/rbenv.d/exec/gem-rehash/rubygems_plugin.rb:27:in `install'
      /Users/centerstage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli/update.rb:61:in `run'
      /Users/centerstage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:228:in `update'
      /Users/centerstage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /Users/centerstage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /Users/centerstage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /Users/centerstage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:20:in `dispatch'
      /Users/centerstage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /Users/centerstage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:11:in `start'
      /Users/centerstage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/exe/bundle:34:in `block in <top (required)>'
      /Users/centerstage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
      /Users/centerstage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/exe/bundle:26:in `<top (required)>'
      /Users/centerstage/.rbenv/versions/2.3.1/bin/bundle:23:in `load'
      /Users/centerstage/.rbenv/versions/2.3.1/bin/bundle:23:in `<main>'

Environment
      
  Bundler   1.13.6
  Rubygems  2.5.1
  Ruby      2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]
  GEM_HOME  /Users/centerstage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0
  GEM_PATH  /Users/centerstage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0:/Users/centerstage/.gem/ruby/2.3.0
  Git       2.7.2
--- TEMPLATE END ----------------------------------------------------------------

**Comment by colby-swandale** [comment]
Bundler doesn't appear to have the permissions to perform the operation it needs to. Did you run Bundler with `root` privileges at any point? Are you running Bundler with a user that have access to `/Users/centerstage/.bundle/`?

Check the permissions at `/Users/centerstage/.bundle` to make sure they're appropriately set.

**Comment by antwerpenR** [comment]
Thanks!  That was exactly the problem.  Not sure how it happened but the .bundle directory and some of the contents were owned by `root`.....so I `chown`ed them back to centerstage and it works fine.  Appreciate the support.

**Comment by colby-swandale** [comment]
no worries, make sure to close the ticket if you're done.
