### ISSUE TITLE
Move `bundle viz` into a plugin

### ISSUE THREAD

**Issue by kerrizor** [bundler/bundler#5180]
`bundle viz` generates a basic ERD graph using `graphviz`. While useful, it could be improved, which would expand its scope and footprint. More realistically, it is a neat feature that could be split off into its own project and loaded using the new plugin API. To that end, I'd like to do the following:

- [ ] split existing functionality into a new `bundler-viz` project
- [ ] load `bundler-viz` using plugin API

This would remove the `graphviz` dependency from bundler core, allow for forward development to improve bundler visualization tools, and provide a roadmap for future bundler plugin development by interested parties.

cc @lynnco and @indirect

**Comment by segiddins** [comment]
Since this is technically a breaking change, it'll have to come in a major version bump

**Comment by kerrizor** [comment]
@segiddins agreed. I'm unsure as to the roadmap for the project, but would a dep warning for the next release SOP?

**Comment by kerrizor** [comment]
@segiddins alternatively, we could keep the current implementation as a fallback if a new plugin version was not installed, and print a dep notice about the plugin to point it out?

**Comment by segiddins** [comment]
Yeah, that could work. Only danger being the user having a different `bundle-viz` executable in their path

**Comment by indirect** [comment]
Since we’re already planing major version bump in the near-ish future, this seems good to me 👍

**Comment by kerrizor** [comment]
@roseaboveit and I knocked out a straight port of the `viz` code into a new plugin gem here https://rubygems.org/gems/bundler-dependency_graph

It is mostly an MVP that let us get a working example of a `Bundler::Plugin::API` based project, as no one could point us towards any that currently exist in the wild. In the process, we found a number of issues with the API which we'll tag in other issues. Our goal is to reach a level of feature parity with `viz` before proposing a removal PR against an eventual 2.0 release.

**Comment by segiddins** [comment]
Hey, I'm trying to get a sense of our progress on 2.0, so what's the status of the plugin `bundle viz` command?

**Comment by indirect** [comment]
IMO, we can extract the existing `viz` command into the `bundler/bundle-viz` repo, ship it as the gem`bundle-viz`, and then this plugin work can continue 👍

**Comment by fatkodima** [comment]
I've made up-to-date extraction here https://github.com/fatkodima/bundler-visualize
Let me know, what you think.

**Comment by deivid-rodriguez** [comment]
Thanks @fatkodima!

The work left to be done is to decide on the final name for the repository and the actual command, to decide whether it should live under the bundler organization or whether an external plugin is also fine, and to verify everything is working properly and provide a smooth deprecation path.

So, since the plugin has already been extracted which was the point of this ticket, I'm going to close it, and move further discussion to https://github.com/bundler/bundler/issues/7041.
