### ISSUE TITLE
Parallel job exception for install on jruby-9.1.6.0 + bundler 1.13.1

### ISSUE THREAD

**Issue by willemave** [bundler/bundler#5182]
Works fine with `--jobs=1` but not with jobs > 1.

full error: https://gist.github.com/willemave/56ea31648b6dcb6402f61807d8fc7c0f

stop of stack:
    Java::JavaLang::LinkageError: loader (instance of  org/jruby/util/OneShotClassLoader): attempted  duplicate class definition for name: "org/jruby/runtime/scopes/DynamicScope14"
      java.lang.ClassLoader.defineClass1(Native Method)
      java.lang.ClassLoader.defineClass(ClassLoader.java:763)
      org.jruby.util.OneShotClassLoader.defineClass(OneShotClassLoader.java:17)
      org.jruby.runtime.scope.DynamicScopeGenerator.defineClass(DynamicScopeGenerator.java:313)
      org.jruby.runtime.scope.DynamicScopeGenerator.generate(DynamicScopeGenerator.java:258)
      org.jruby.parser.StaticScope.acquireConstructor(StaticScope.java:197)
      org.jruby.parser.StaticScope.construct(StaticScope.java:180)
      org.jruby.runtime.DynamicScope.newDynamicScope(DynamicScope.java:53)
      org.jruby.runtime.DynamicScope.newDynamicScope(DynamicScope.java:96)

**Comment by segiddins** [comment]
I'm not seeing any bundler code at all in that backtrace?

**Comment by willemave** [comment]
Yeah internal to jruby, closing.

**Comment by perlun** [comment]
Dupe of #5202 btw. Fixed in jruby 9.1.7.0 which is unfortunately unreleased yet.
