### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by anjaneyulub** [bundler/bundler#5194]
https://github.com/bundler/bundler/search?q=Permission+denied+-+%28%2Ftmp%2Fbundler-compact-index-20161120-13890-10pz5bt%2Fversions%2C+%2Fhome%2Fanjaneyulu%2F.bundle%2Fcache%2Fcompact_index%2Frubygems.org.443.29b0360b937aa4d161703e6160654e47%2Fversions%29&type=Issues

**Comment by colby-swandale** [comment]
Can you please follow the [ISSUE guide](https://github.com/bundler/bundler/blob/master/ISSUES.md) on how to report an error with Bundler. This will help us resolve your problem a lot quicker.

**Comment by lynnco** [comment]
@anjaneyulub follow @colby-swandale's directions above when creating an issue if you would like assistance! I'm going to close this one as it doesn't contain any actionable information
