### ISSUE TITLE
Silently creates config that changes default

### ISSUE THREAD

**Issue by wconrad** [bundler/bundler#5195]
Given ruby-2.3.2, bundler 1.13.6, and no .bundler/config file,

When I use the `--without- switch:

    bundle install --without development

Then bundler silently creates a .bundle/config which makes the `--without` switch the default:

    $ cat .bundle/config 
    ---
    BUNDLE_WITHOUT: "development"

Once that configuration file exists, doing `bundle install` without any switches no longer installs all of the project's gems.  This surprised me.

* Is it expected behavior that when a config file is created it makes the --without switch the default?
* If so, should bundler issue a notice that it is doing so?

**Comment by segiddins** [comment]
It is expected behavior that options are remembered, which will change in bundler 2. http://bundler.io/v1.12/man/bundle-install.1.html#REMEMBERED-OPTIONS

**Comment by wconrad** [comment]
Very well.  I'm glad that behavior is changing.  Thanks for the quick response, and for maintaining one of my favorite tools.
