### ISSUE TITLE
Problem while running rails server

### ISSUE THREAD

**Issue by varkeyvincentindia** [bundler/bundler#5197]
Whenever I Run 'rails server' command I confront an error report like [Could not find gem 'uglifier (>= 1.3.0) x86-mingw32' in any of the gem sources listed in your Gemfile or available on this machine.].Even if Install the required gem new error is raised for another missing gem .
How can I solve this issue , How can I install all the missing gems ?

**Comment by colby-swandale** [comment]
Are there any issues being printed when you run `bundle install` in your rails project? Can you also add the output of `bundle env`.

**Comment by lynnco** [comment]
@varkeyvincentindia ping

Are there any issues being printed when you run bundle install in your rails project? Can you also add the output of bundle env.

**Comment by segiddins** [comment]
Closing due to lack of response.
