### ISSUE TITLE
used to work, but now doesn't, but still work on my other comp

### ISSUE THREAD

**Issue by brothman01** [bundler/bundler#5198]
error I get is:
```
$ ruby wpscan.rb
Could not find gem 'typhoeus (>= 1.0.0)' in any of the gem sources listed in your Gemfile or available on this machine.
Run `bundle install` to install missing gems.

```
I ran that command and it did not work.  What should I do instead?

**Comment by segiddins** [comment]
Please follow the instructions in https://github.com/bundler/bundler/blob/master/ISSUES.md and share the information requested there

**Comment by brothman01** [comment]
I don't mean to complain, but it seems like I would have to know the problem already to follow the directions and share the information.  I think this is right:

```
Environment
      
  Bundler   1.13.6
  Rubygems  2.5.1
  Ruby      2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]
  GEM_HOME  /Users/ben/.rvm/gems/ruby-2.3.1@wpscan
  GEM_PATH  /Users/ben/.rvm/gems/ruby-2.3.1@wpscan:/Users/ben/.rvm/gems/ruby-2.3.1@global
  RVM       1.27.0 (latest)
  Git       2.7.4 (Apple Git-66)
  rubygems-bundler (1.4.4)
      
      Bundler settings
      
  without
    Set for your local app (/Users/ben/wpscan/.bundle/config): "test"
--- TEMPLATE END ----------------------------------------------------------------
```

I installed Bundler a few months ago and it worked as expected until a few days ago, but tonight it is not working.  How do I fix this?

**Comment by segiddins** [comment]
What's in `wpscan.rb`? It's hard to know what the problem is without any of this context

**Comment by brothman01** [comment]
https://github.com/wpscanteam/wpscan

**Comment by brothman01** [comment]
oh and in the error message it says to 'try this link to see if there are any existing issue reports for this error:' and there are not, but Permission+denied+%40+rb_file_s_rename is at the beginning of the search string.. so do I find that file and change permissions or something?

**Comment by segiddins** [comment]
I'm not seeing `require "bundler/setup"` or anything being called there, so I'm unsure where bundler's even coming into play ehre

**Comment by brothman01** [comment]
hmm, it was when I tried to reinstall ruby.  First I tried to upgrade Ruby and decided to use rvm.  I uninstallled RVM and then reinstalled it and used it to upgrade Ruby.  The Ruby upgrade seemed to work, but then when I tried to run a Ruby script (wpscan) an error message printed instead:

```
Could not find gem 'typhoeus (>= 1.0.0)' in any of the gem sources listed in your Gemfile or available on this machine.
Run `bundle install` to install missing gems.
```

so the only reason I think Bundler is involved in this at all is that it was mentioned in the error message so Ruby must be trying unsuccessfully to use Bundler, failing and printing that error.  Do I need to completely uninstall and reinstall Bundler or something?

**Comment by segiddins** [comment]
can you try one more thin, and run with `DEBUG=1`?

**Comment by brothman01** [comment]
```
$ ruby wpscan.rb www.benrothman.org DEBUG=1
Could not find gem 'typhoeus (>= 1.0.0)' in any of the gem sources listed in your Gemfile or available on this machine.
Run `bundle install` to install missing gems.
```

**Comment by brothman01** [comment]
```
$ bundle install DEBUG=1
ERROR: "bundle install" was called with arguments ["DEBUG=1"]
Usage: "bundle install [OPTIONS]"
```

**Comment by segiddins** [comment]
`DEBUG=1 bundle install`

**Comment by lynnco** [comment]
@brothman01 

> `DEBUG=1 bundle install`

**Comment by brothman01** [comment]
it works now for some reason.  I reinstalled several packages, and at least one of those must have been a dependancy for Bundler.  Actually I think this may have been an RVM problem that just looked like it was from Bundler. Sorry for the unnecessary ticket

**Comment by brothman01** [comment]
so resolved.  Ia there a more official way to close this issue?
