### ISSUE TITLE
JRuby 9.1.6.0: attempted  duplicate class definition for name: "org/jruby/runtime/scopes/DynamicScope15"

### ISSUE THREAD

**Issue by perlun** [bundler/bundler#5202]
- What did you do?

  I ran the command `/Users/plundberg/.rvm/gems/jruby-9.1.6.0/bin/bundle install`

- What did you expect to happen?

  I expected Bundler to install the gems for my app.

- What happened instead?

  Instead, what happened was the error below. This is *specifically* something I've started seeing since upgrading to JRuby 9.1.6.0 (9.1.5.0 works fine).

If I change the `--jobs` parameter to 1, it works. So this seems like a reentrancy issue or something in JRuby. (Note: I am well aware that **this is unlikely to be a bug in bundler**, but let's keep it here for now anyway.)

/cc @headius 

Error details

    Java::JavaLang::LinkageError: loader (instance of  org/jruby/util/OneShotClassLoader): attempted  duplicate class definition for name: "org/jruby/runtime/scopes/DynamicScope15"
      java.lang.ClassLoader.defineClass1(Native Method)
      java.lang.ClassLoader.defineClass(ClassLoader.java:763)
      org.jruby.util.OneShotClassLoader.defineClass(OneShotClassLoader.java:17)
      org.jruby.runtime.scope.DynamicScopeGenerator.defineClass(DynamicScopeGenerator.java:313)
      org.jruby.runtime.scope.DynamicScopeGenerator.generate(DynamicScopeGenerator.java:258)
      org.jruby.parser.StaticScope.acquireConstructor(StaticScope.java:197)
      org.jruby.parser.StaticScope.construct(StaticScope.java:180)
      org.jruby.runtime.DynamicScope.newDynamicScope(DynamicScope.java:53)
      org.jruby.runtime.DynamicScope.newDynamicScope(DynamicScope.java:96)
      org.jruby.internal.runtime.methods.InterpretedIRMethod.pre(InterpretedIRMethod.java:62)
      org.jruby.internal.runtime.methods.InterpretedIRMethod.INTERPRET_METHOD(InterpretedIRMethod.java:160)
      org.jruby.internal.runtime.methods.InterpretedIRMethod.call(InterpretedIRMethod.java:148)
      org.jruby.RubyClass.finvoke(RubyClass.java:531)
      org.jruby.RubyBasicObject.send19(RubyBasicObject.java:1668)
      org.jruby.RubyKernel.send19(RubyKernel.java:1991)
      org.jruby.RubyKernel$INVOKER$s$send19.call(RubyKernel$INVOKER$s$send19.gen)
      org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:208)
      org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:193)
      org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:324)
      org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
      org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:84)
      org.jruby.internal.runtime.methods.InterpretedIRMethod.INTERPRET_METHOD(InterpretedIRMethod.java:161)
      org.jruby.internal.runtime.methods.InterpretedIRMethod.call(InterpretedIRMethod.java:148)
      org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:200)
      org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:161)
      org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:315)
      org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
      org.jruby.internal.runtime.methods.InterpretedIRMethod.INTERPRET_METHOD(InterpretedIRMethod.java:104)
      org.jruby.internal.runtime.methods.InterpretedIRMethod.call(InterpretedIRMethod.java:91)
      org.jruby.ir.runtime.IRRuntimeHelpers.instanceSuper(IRRuntimeHelpers.java:970)
      org.jruby.ir.instructions.InstanceSuperInstr.interpret(InstanceSuperInstr.java:69)
      org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:356)
      org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
      org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:84)
      org.jruby.internal.runtime.methods.InterpretedIRMethod.INTERPRET_METHOD(InterpretedIRMethod.java:161)
      org.jruby.internal.runtime.methods.InterpretedIRMethod.call(InterpretedIRMethod.java:148)
      org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:200)
      org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:338)
      org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:163)
      org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:315)
      org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
      org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:84)
      org.jruby.internal.runtime.methods.InterpretedIRMethod.INTERPRET_METHOD(InterpretedIRMethod.java:161)
      org.jruby.internal.runtime.methods.InterpretedIRMethod.call(InterpretedIRMethod.java:148)
      org.jruby.RubyClass.finvoke(RubyClass.java:531)
      org.jruby.RubyBasicObject.send19(RubyBasicObject.java:1668)
      org.jruby.RubyKernel.send19(RubyKernel.java:1991)
      org.jruby.RubyKernel$INVOKER$s$send19.call(RubyKernel$INVOKER$s$send19.gen)
      org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:208)
      org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:358)
      org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:195)
      org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:324)
      org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
      org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:84)
      org.jruby.internal.runtime.methods.InterpretedIRMethod.INTERPRET_METHOD(InterpretedIRMethod.java:161)
      org.jruby.internal.runtime.methods.InterpretedIRMethod.call(InterpretedIRMethod.java:148)
      org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:200)
      org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:338)
      org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:163)
      org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:315)
      org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
      org.jruby.internal.runtime.methods.InterpretedIRMethod.INTERPRET_METHOD(InterpretedIRMethod.java:104)
      org.jruby.internal.runtime.methods.InterpretedIRMethod.call(InterpretedIRMethod.java:91)
      org.jruby.ir.runtime.IRRuntimeHelpers.instanceSuper(IRRuntimeHelpers.java:970)
      org.jruby.ir.instructions.InstanceSuperInstr.interpret(InstanceSuperInstr.java:69)
      org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:356)
      org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
      org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:84)
      org.jruby.internal.runtime.methods.InterpretedIRMethod.INTERPRET_METHOD(InterpretedIRMethod.java:161)
      org.jruby.internal.runtime.methods.InterpretedIRMethod.call(InterpretedIRMethod.java:148)
      org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:200)
      org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:338)
      org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:163)
      org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:315)
      org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
      org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:78)
      org.jruby.internal.runtime.methods.InterpretedIRMethod.INTERPRET_METHOD(InterpretedIRMethod.java:133)
      org.jruby.internal.runtime.methods.InterpretedIRMethod.call(InterpretedIRMethod.java:120)
      org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:192)
      org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:129)
      org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:340)
      org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
      org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:84)
      org.jruby.internal.runtime.methods.InterpretedIRMethod.INTERPRET_METHOD(InterpretedIRMethod.java:161)
      org.jruby.internal.runtime.methods.InterpretedIRMethod.call(InterpretedIRMethod.java:148)
      org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:200)
      org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:161)
      org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:315)
      org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
      org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java:132)
      org.jruby.runtime.InterpretedIRBlockBody.commonYieldPath(InterpretedIRBlockBody.java:141)
      org.jruby.runtime.IRBlockBody.doYield(IRBlockBody.java:182)
      org.jruby.runtime.BlockBody.yield(BlockBody.java:110)
      org.jruby.runtime.Block.yield(Block.java:167)
      org.jruby.ext.zlib.RubyGzipFile.wrapBlock(RubyGzipFile.java:70)
      org.jruby.ext.zlib.RubyGzipFile.wrap19(RubyGzipFile.java:96)
      org.jruby.ext.zlib.RubyGzipFile$INVOKER$s$0$1$wrap19.call(RubyGzipFile$INVOKER$s$0$1$wrap19.gen)
      org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:204)
      org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:171)
      org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:177)
      org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:333)
      org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
      org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java:132)
      org.jruby.runtime.InterpretedIRBlockBody.commonYieldPath(InterpretedIRBlockBody.java:141)
      org.jruby.runtime.IRBlockBody.doYield(IRBlockBody.java:182)
      org.jruby.runtime.BlockBody.yield(BlockBody.java:110)
      org.jruby.runtime.Block.yield(Block.java:167)
      org.jruby.ir.runtime.IRRuntimeHelpers.yield(IRRuntimeHelpers.java:450)
      org.jruby.ir.instructions.YieldInstr.interpret(YieldInstr.java:83)
      org.jruby.ir.interpreter.StartupInterpreterEngine.processOtherOp(StartupInterpreterEngine.java:187)
      org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:111)
      org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:84)
      org.jruby.internal.runtime.methods.InterpretedIRMethod.INTERPRET_METHOD(InterpretedIRMethod.java:161)
      org.jruby.internal.runtime.methods.InterpretedIRMethod.call(InterpretedIRMethod.java:148)
      org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:171)
      org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:177)
      org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:333)
      org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
      org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:84)
      org.jruby.internal.runtime.methods.InterpretedIRMethod.INTERPRET_METHOD(InterpretedIRMethod.java:161)
      org.jruby.internal.runtime.methods.InterpretedIRMethod.call(InterpretedIRMethod.java:148)
      org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:200)
      org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:161)
      org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:315)
      org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
      org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java:132)
      org.jruby.runtime.InterpretedIRBlockBody.commonYieldPath(InterpretedIRBlockBody.java:141)
      org.jruby.runtime.IRBlockBody.doYield(IRBlockBody.java:182)
      org.jruby.runtime.BlockBody.yield(BlockBody.java:110)
      org.jruby.runtime.Block.yield(Block.java:167)
      org.jruby.ir.runtime.IRRuntimeHelpers.yield(IRRuntimeHelpers.java:450)
      org.jruby.ir.instructions.YieldInstr.interpret(YieldInstr.java:83)
      org.jruby.ir.interpreter.StartupInterpreterEngine.processOtherOp(StartupInterpreterEngine.java:187)
      org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:111)
      org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:84)
      org.jruby.internal.runtime.methods.InterpretedIRMethod.INTERPRET_METHOD(InterpretedIRMethod.java:161)
      org.jruby.internal.runtime.methods.InterpretedIRMethod.call(InterpretedIRMethod.java:148)
      org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:348)
      org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:173)
      org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:177)
      org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:333)
      org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
      org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java:132)
      org.jruby.runtime.InterpretedIRBlockBody.commonYieldPath(InterpretedIRBlockBody.java:141)
      org.jruby.runtime.IRBlockBody.doYield(IRBlockBody.java:182)
      org.jruby.runtime.BlockBody.yield(BlockBody.java:110)
      org.jruby.runtime.Block.yield(Block.java:167)
      org.jruby.RubyIO.ensureYieldClose(RubyIO.java:1148)
      org.jruby.RubyIO.open(RubyIO.java:1141)
      org.jruby.RubyKernel.open19(RubyKernel.java:306)
      org.jruby.RubyKernel$INVOKER$s$0$3$open19.call(RubyKernel$INVOKER$s$0$3$open19.gen)
      org.jruby.internal.runtime.methods.AliasMethod.call(AliasMethod.java:101)
      org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:298)
      org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:79)
      org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:83)
      org.jruby.ir.instructions.CallBase.interpret(CallBase.java:428)
      org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:356)
      org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:159)
      org.jruby.internal.runtime.methods.InterpretedIRMethod.INTERPRET_METHOD(InterpretedIRMethod.java:100)
      org.jruby.internal.runtime.methods.InterpretedIRMethod.call(InterpretedIRMethod.java:91)
      org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:77)
      org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:83)
      org.jruby.ir.instructions.CallBase.interpret(CallBase.java:428)
      org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:356)
      org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
      org.jruby.internal.runtime.methods.InterpretedIRMethod.INTERPRET_METHOD(InterpretedIRMethod.java:104)
      org.jruby.internal.runtime.methods.InterpretedIRMethod.call(InterpretedIRMethod.java:91)
      org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:77)
      org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:83)
      org.jruby.ir.instructions.CallBase.interpret(CallBase.java:428)
      org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:356)
      org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
      org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:78)
      org.jruby.internal.runtime.methods.InterpretedIRMethod.INTERPRET_METHOD(InterpretedIRMethod.java:133)
      org.jruby.internal.runtime.methods.InterpretedIRMethod.call(InterpretedIRMethod.java:120)
      org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:192)
      org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:129)
      org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:340)
      org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
      org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:78)
      org.jruby.internal.runtime.methods.InterpretedIRMethod.INTERPRET_METHOD(InterpretedIRMethod.java:133)
      org.jruby.internal.runtime.methods.InterpretedIRMethod.call(InterpretedIRMethod.java:120)
      org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:192)
      org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:129)
      org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:340)
      org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
      org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:90)
      org.jruby.internal.runtime.methods.InterpretedIRMethod.INTERPRET_METHOD(InterpretedIRMethod.java:189)
      org.jruby.internal.runtime.methods.InterpretedIRMethod.call(InterpretedIRMethod.java:176)
      org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:208)
      org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:193)
      org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:324)
      org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
      org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:90)
      org.jruby.internal.runtime.methods.InterpretedIRMethod.INTERPRET_METHOD(InterpretedIRMethod.java:189)
      org.jruby.internal.runtime.methods.InterpretedIRMethod.call(InterpretedIRMethod.java:176)
      org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:208)
      org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:193)
      org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:324)
      org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
      org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:78)
      org.jruby.internal.runtime.methods.InterpretedIRMethod.INTERPRET_METHOD(InterpretedIRMethod.java:133)
      org.jruby.internal.runtime.methods.InterpretedIRMethod.call(InterpretedIRMethod.java:120)
      org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:192)
      org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:129)
      org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:340)
      org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
      org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:78)
      org.jruby.internal.runtime.methods.InterpretedIRMethod.INTERPRET_METHOD(InterpretedIRMethod.java:133)
      org.jruby.internal.runtime.methods.InterpretedIRMethod.call(InterpretedIRMethod.java:120)
      org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:192)
      org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:129)
      org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:340)
      org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
      org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java:132)
      org.jruby.runtime.InterpretedIRBlockBody.commonYieldPath(InterpretedIRBlockBody.java:141)
      org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:69)
      org.jruby.runtime.Block.call(Block.java:126)
      org.jruby.RubyProc.call(RubyProc.java:324)
      org.jruby.RubyProc.call19(RubyProc.java:308)
      org.jruby.RubyProc$INVOKER$i$0$0$call19.call(RubyProc$INVOKER$i$0$0$call19.gen)
      org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:212)
      org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:208)
      org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:193)
      org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:324)
      org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:159)
      org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:90)
      org.jruby.internal.runtime.methods.InterpretedIRMethod.INTERPRET_METHOD(InterpretedIRMethod.java:185)
      org.jruby.internal.runtime.methods.InterpretedIRMethod.call(InterpretedIRMethod.java:176)
      org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:208)
      org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:193)
      org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:324)
      org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:159)
      org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java:132)
      org.jruby.runtime.InterpretedIRBlockBody.yieldDirect(InterpretedIRBlockBody.java:109)
      org.jruby.runtime.IRBlockBody.yieldSpecific(IRBlockBody.java:76)
      org.jruby.runtime.Block.yieldSpecific(Block.java:136)
      org.jruby.RubyKernel.loop(RubyKernel.java:1299)
      org.jruby.RubyKernel$INVOKER$s$0$0$loop.call(RubyKernel$INVOKER$s$0$0$loop.gen)
      org.jruby.internal.runtime.methods.JavaMethod$JavaMethodZeroBlock.call(JavaMethod.java:497)
      org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:77)
      org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:83)
      org.jruby.ir.instructions.CallBase.interpret(CallBase.java:428)
      org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:356)
      org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:159)
      org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:84)
      org.jruby.internal.runtime.methods.InterpretedIRMethod.INTERPRET_METHOD(InterpretedIRMethod.java:157)
      org.jruby.internal.runtime.methods.InterpretedIRMethod.call(InterpretedIRMethod.java:148)
      org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:200)
      org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:161)
      org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:315)
      org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:159)
      org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java:132)
      org.jruby.runtime.InterpretedIRBlockBody.callDirect(InterpretedIRBlockBody.java:102)
      org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:67)
      org.jruby.runtime.Block.call(Block.java:126)
      org.jruby.RubyProc.call(RubyProc.java:324)
      org.jruby.RubyProc.call(RubyProc.java:249)
      org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:104)
      java.lang.Thread.run(Thread.java:745)

### Environment

    Bundler   1.13.6
    Rubygems  2.6.8
    Ruby      2.3.1p0 (2016-11-09 revision 54768) [java]
    GEM_HOME  /Volumes/extra/git/some-app/workers/gems/jruby/2.3.0
    GEM_PATH
    RVM       1.27.0 (master)
    Git       2.10.0

### Bundler settings

    gem.coc
      Set for the current user (/Users/plundberg/.bundle/config): "true"
    gem.mit
      Set for the current user (/Users/plundberg/.bundle/config): "false"
    gem.test
      Set for the current user (/Users/plundberg/.bundle/config): "rspec"
    local.uxfactory-elastic
      Set for the current user (/Users/plundberg/.bundle/config): "/Users/plundberg/git/ecraft/uxfactory-elastic"
    disable_local_branch_check
      Set for the current user (/Users/plundberg/.bundle/config): "true"
    https://gem.fury.io/ecraft-gems/
      Set for the current user (/Users/plundberg/.bundle/config): "<removed>"
    build.nokogiri
      Set for the current user (/Users/plundberg/.bundle/config): "--use-system-libraries"
    path
      Set for your local app (/Volumes/extra/git/some-app/.bundle/config): "workers/gems"
    jobs
      Set for your local app (/Volumes/extra/git/some-app/.bundle/config): "7"
    disable_shared_gems
      Set for your local app (/Volumes/extra/git/some-app/.bundle/config): true

**Comment by perlun** [comment]
@bundlerbot - anyone?

**Comment by olleolleolle** [comment]
I can reproduce this issue with jruby-9.1.6.0, when I:

- didn't have a directory `workers/gems` 
- and I didn't have the bundle config setting `disable_shared_gems` nor `frozen`

`bundle install --jobs 7 --path workers/gems --deployment`

To get there, I edited the local `.bundle/config` and removed these lines:

```
BUNDLE_FROZEN: "1"
BUNDLE_DISABLE_SHARED_GEMS: "true"
```

**Comment by segiddins** [comment]
Looking at the call stack, this is possibly a problem with psych? I'm unsure how bundler could be causing this issue

**Comment by olleolleolle** [comment]
@segiddins The JRuby channel right now has discussion on IR code-gen having optimization issues with 9.1.6.0.

**Comment by enebo** [comment]
@segiddins 9.1.7.0 will fix this.  We made a boo boo: https://github.com/jruby/jruby/pull/4285

**Comment by olleolleolle** [comment]
So, @perlun: `--jobs 1` as a work-around until 9.1.7.0 is out.

**Comment by segiddins** [comment]
@olleolleolle thanks for the update!

**Comment by perlun** [comment]
@enebo @olleolleolle - thanks for the details and all your hard work! Yeah, `--jobs 1` works but I'm a bit conservative and lazy so I'll just stick with 9.1.5.0 until 9.1.7.0 is available in all its glory. 😇
