### ISSUE TITLE
Regenerating missing extensions on bundle install

### ISSUE THREAD

**Issue by kirs** [bundler/bundler#5210]
Assuming my bundle path is `./vendor/bundle`:
```
$ bundle config
Settings are listed in order of priority. The top value will be used.
path
Set for the current user (/Users/kir/.bundle/config): "./vendor/bundle"

$ bundle -v
Bundler version 1.13.6
$ ruby -v
ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin16]
```

Imagine that my `vendor/bundle/extensions` somehow get corrupted:

```
$ rm -rf vendor/bundle/extensions
```

## Expected

I expect that `bundle install` would recover from that state.

## Actual

Now to get `vendor/bundle/extensions` recovered, I have to completely remove `vendor/bundle`. Only then Bundler will download all the gems from the scratch and rebuild the extensions.

## Proposal

We don't have to delete all gems and download them again to just rebuild the extensions.
Should we make `bundle install` check if extentions need to be built?
I'll be happy to work on that.

@indirect

**Comment by segiddins** [comment]
If at all possible, bundler should re-build extensions when needed. In the meantime, `bundle install --force` should be a workaround to reinstall the extensions

**Comment by kirs** [comment]
Thanks! Would you accept a patch that makes bundle install rebuild
extensions by default?

On Nov 27, 2016 10:58 PM, "Samuel Giddins" <notifications@github.com> wrote:

If at all possible, bundler should re-build extensions when needed. In the
meantime, bundle install --force should be a workaround to reinstall the
extensions

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/bundler/bundler/issues/5210#issuecomment-263178532>,
or mute
the thread

**Comment by indirect** [comment]
Sooo... `bundle install` used to _always_ rebuild extensions, and it was a huge problem for a lot of people. Please make sure that you don't accidentally revert the changes that fixed that problem. :) (One of the PRs for that problem is here: https://github.com/bundler/bundler/pull/4082)
