### ISSUE TITLE
Bundler is rewriting my local config

### ISSUE THREAD

**Issue by atrauzzi** [bundler/bundler#5212]
I'm currently running bundle through a container using docker for Windows.  I have a `.bundle/config` file in my project that specifies a `BUNDLE_PATH`:

```
---
BUNDLE_PATH: "./bundles"
BUNDLE_DISABLE_SHARED_GEMS: "true"
```

Unfortunately, every time I run `bundle install` or even just `bundle` in the container, the file gets rewritten with some concering quotes which seem to be preventing it from successfully installing:

```
---
BUNDLE_PATH: "\"./bundles\" "
BUNDLE_DISABLE_SHARED_GEMS: "true"
```

Is there any way I can tell bundler to not touch the config file and just read it as-is?  Moreover, I'd love some insights into what's going on here and why bundler feels the need to rewrite the config file on run.

**Comment by segiddins** [comment]
Can you please provide the information requested in https://github.com/bundler/bundler/blob/master/ISSUES.md? Thanks!

**Comment by lynnco** [comment]
@atrauzzi ping

> Can you please provide the information requested in https://github.com/bundler/bundler/blob/master/ISSUES.md? Thanks!

**Comment by atrauzzi** [comment]
Sorry, I don't really have the time to provide you with a wall of text.  If you guys have a specific question, feel free to ask and I'll give any specific detail or subset that you need.
