### ISSUE TITLE
Automatically retry single gem installs?

### ISSUE THREAD

**Issue by lynnco** [bundler/bundler#5223]
This issue https://github.com/bundler/bundler/issues/4656 is one I've run into myself fairly often. More often than not, it was solved by something like

```
bundle install
gem install YOURGEM
bundle install
```

Which is exactly what the error message recommends. This makes me wonder if it would be possible to try this single gem install automatically, to save the user some effort.

I'm quite sure there is a reason bundler doesn't currently do this, so I'm fine with just being informed and having this closed

**Comment by segiddins** [comment]
nothing stopping us from doing

```ruby
Bundler.with_clean_env do
  `#{Gem.ruby} -S gem install #{name} #{version}
end
```

when it fails, and I can't think of a reason that would be a terrible idea? only thing might be that it will stop us getting issues if we somehow break bundler's own installer

**Comment by segiddins** [comment]
I think we'll close this as undesired, and push ourselves to make `bundle install` always work :) Otherwise we'd never find out when things in bundler break
