### ISSUE TITLE
Unexpected Bundler error

### ISSUE THREAD

**Issue by daniagudelo** [bundler/bundler#5229]
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `/usr/local/rvm/gems/ruby-1.9.3-p551@global/bin/bundle install`

- What did you expect to happen?

  I expected Bundler to install the gems in my Gemfile

- What happened instead?

  Instead, what happened was that I got this error

Error details

    ArgumentError: parent directory is world writable, FileUtils#remove_entry_secure does not work; abort: "/tmp/bundler-compact-index-20161205-3161-4n9ls6" (parent directory mode 40777)
      /usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/fileutils.rb:708:in `remove_entry_secure'
      /usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/tmpdir.rb:85:in `ensure in mktmpdir'
      /usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/tmpdir.rb:85:in `mktmpdir'
      /usr/local/rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.13.6/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:29:in `update'
      /usr/local/rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.13.6/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:65:in `update'
      /usr/local/rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.13.6/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:56:in `update_and_parse_checksums!'
      /usr/local/rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.13.6/lib/bundler/fetcher/compact_index.rb:67:in `available?'
      /usr/local/rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.13.6/lib/bundler/fetcher/compact_index.rb:15:in `call'
      /usr/local/rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.13.6/lib/bundler/fetcher/compact_index.rb:15:in `block in compact_index_request'
      /usr/local/rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.13.6/lib/bundler/fetcher.rb:157:in `use_api'
      /usr/local/rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:332:in `block in api_fetchers'
      /usr/local/rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:332:in `select'
      /usr/local/rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:332:in `api_fetchers'
      /usr/local/rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:337:in `block in remote_specs'
      /usr/local/rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.13.6/lib/bundler/index.rb:10:in `build'
      /usr/local/rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:336:in `remote_specs'
      /usr/local/rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:83:in `specs'
      /usr/local/rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.13.6/lib/bundler/lazy_specification.rb:61:in `__materialize__'
      /usr/local/rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.13.6/lib/bundler/spec_set.rb:91:in `block in materialize'
      /usr/local/rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.13.6/lib/bundler/spec_set.rb:88:in `map!'
      /usr/local/rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.13.6/lib/bundler/spec_set.rb:88:in `materialize'
      /usr/local/rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.13.6/lib/bundler/definition.rb:174:in `specs'
      /usr/local/rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.13.6/lib/bundler/definition.rb:162:in `resolve_remotely!'
      /usr/local/rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.13.6/lib/bundler/installer.rb:225:in `resolve_if_need'
      /usr/local/rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.13.6/lib/bundler/installer.rb:78:in `run'
      /usr/local/rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.13.6/lib/bundler/installer.rb:24:in `install'
      /usr/local/rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.13.6/lib/bundler/cli/install.rb:71:in `run'
      /usr/local/rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.13.6/lib/bundler/cli.rb:189:in `install'
      /usr/local/rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /usr/local/rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /usr/local/rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /usr/local/rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.13.6/lib/bundler/cli.rb:20:in `dispatch'
      /usr/local/rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /usr/local/rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.13.6/lib/bundler/cli.rb:11:in `start'
      /usr/local/rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.13.6/exe/bundle:34:in `block in <top (required)>'
      /usr/local/rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.13.6/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
      /usr/local/rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.13.6/exe/bundle:26:in `<top (required)>'
      /usr/local/rvm/gems/ruby-1.9.3-p551@global/bin/bundle:23:in `load'
      /usr/local/rvm/gems/ruby-1.9.3-p551@global/bin/bundle:23:in `<main>'
      /usr/local/rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `eval'
      /usr/local/rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `<main>'

Environment
      
  Bundler   1.13.6
  Rubygems  2.4.3
  Ruby      1.9.3p551 (2014-11-13 revision 48407) [x86_64-linux]
  GEM_HOME  /usr/local/rvm/gems/ruby-1.9.3-p551
  GEM_PATH  /usr/local/rvm/gems/ruby-1.9.3-p551:/usr/local/rvm/gems/ruby-1.9.3-p551@global
  RVM       1.26.11 (latest)
  Git       1.9.1
  rubygems-bundler (1.4.4)
--- TEMPLATE END ----------------------------------------------------------------

Thanks a lot!

**Comment by segiddins** [comment]
This has a nicer error message on `master`

**Comment by daniagudelo** [comment]
I'm sorry, but I don't understand.

Thank you!

**Comment by lynnco** [comment]
@daniagudelo there's an issue with your local setup that is causing bundle to produce that error, and the current main branch of bundler's code has a better error message to help you resolve it.

That main branch will be resolved soon as `1.14`, or you can try installing bundler from github
