### ISSUE TITLE
"bundle install" hangs

### ISSUE THREAD

**Issue by Arnaut-Billings** [bundler/bundler#5239]
My system info:

`
$ uname -a
CYGWIN_NT-6.1-WOW 2.6.0(0.304/5/3) 2016-08-31 14:27 i686 Cygwin
`
`
$ ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [i386-cygwin]
`
`
$ bundle -v
Bundler version 1.13.6
`

My gem file:

[Gemfile.txt](https://github.com/bundler/bundler/files/640306/Gemfile.txt)

When I do "bundle install --verbose" I get the following snippet:

[snip a lot of output]
Fetching dependency metadata from http://rubygems.org/
HTTP GET http://index.rubygems.org/api/v1/dependencies
HTTP 200 OK http://index.rubygems.org/api/v1/dependencies
Query List: ["celluloid-gems", "faraday-middleware"]
Query Gemcutter Dependency Endpoint API: celluloid-gems,faraday-middleware
HTTP GET http://index.rubygems.org/api/v1/dependencies?gems=celluloid-gems%2Cfaraday-middleware
HTTP 200 OK http://index.rubygems.org/api/v1/dependencies?gems=celluloid-gems%2Cfaraday-middleware
Query List: []
[hangs here]

When I do Ctrl + C, I get the following:

/home/Arnaut/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/source/git/git_proxy.rb:161:in ``': Resource temporarily unavailable - git (Errno::EAGAIN)
        from /home/Arnaut/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/source/git/git_proxy.rb:161:in `block (2 levels) in git'
        from /home/Arnaut/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/source/git/git_proxy.rb:233:in `block in capture_and_filter_stderr'
        from /home/Arnaut/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tempfile.rb:295:in `open'
        from /home/Arnaut/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/source/git/git_proxy.rb:231:in `capture_and_filter_stderr'
        from /home/Arnaut/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/source/git/git_proxy.rb:161:in `block in git'
        from /home/Arnaut/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/shared_helpers.rb:72:in `with_clean_git_env'
        from /home/Arnaut/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/source/git/git_proxy.rb:160:in `git'
        from /home/Arnaut/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/source/git/git_proxy.rb:88:in `full_version'
        from /home/Arnaut/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/env.rb:78:in `git_version'
        from /home/Arnaut/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/env.rb:22:in `report'
        from /home/Arnaut/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/friendly_errors.rb:74:in `request_issue_report_for'
        from /home/Arnaut/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/friendly_errors.rb:40:in `log_error'
        from /home/Arnaut/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/friendly_errors.rb:102:in `rescue in with_friendly_errors'
        from /home/Arnaut/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
        from /home/Arnaut/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/exe/bundle:26:in `<top (required)>'
        from /home/Arnaut/.rvm/gems/ruby-2.3.1/bin/bundle:23:in `load'
        from /home/Arnaut/.rvm/gems/ruby-2.3.1/bin/bundle:23:in `<main>'

**Comment by segiddins** [comment]
Do you have `git` installed locally?

**Comment by Arnaut-Billings** [comment]
Yes. But I had a wrapper script around it that forced the local .git/config file to have a user name and email if it did anything other than clone/version. I removed that wrapper and did a "build install --verbose" using the /usr/bin/git.  Right now it's stuck at:

[snip a lot of output]
Looking up gems ["faraday-middleware", "celluloid-gems"]
Fetching dependency metadata from http://rubygems.org/
Looking up gems ["faraday-middleware", "celluloid-gems"]

**Comment by segiddins** [comment]
What's the output of `git --version` for you? Because Bundler appears to be hanging in the error report

**Comment by Arnaut-Billings** [comment]
$ git --version
git version 2.8.3

**Comment by segiddins** [comment]
Very strange. I have no idea what could be causing this

**Comment by Arnaut-Billings** [comment]
Is there a log file I can look at. I did a quick google for one, I couldn't find it. I tried searching ~/.bundle directory, but I didn't find one for installs.

**Comment by segiddins** [comment]
The log is the backtrace that you shared above

**Comment by Arnaut-Billings** [comment]
Any pointers on how I can debug this? For example, running the scripts one by one manually.

**Comment by segiddins** [comment]
I can't think of anything off the top of my head, sorry

**Comment by cabello** [comment]
I am having the same problem:
- `$ uname -a Darwin Computer.local 16.3.0 Darwin Kernel Version 16.3.0: Thu Nov 17 20:23:58 PST 2016; root:xnu-3789.31.2~1/RELEASE_X86_64 x86_64`
- `$ ruby -v ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]`
- `$ bundler -v Bundler version 1.13.6`

When I run in verbose mode it gets stuck on the same step:
```
Fetching dependency metadata from https://rubygems.org/
HTTP GET https://index.rubygems.org/api/v1/dependencies
HTTP 200 OK https://index.rubygems.org/api/v1/dependencies
Query List: ["celluloid-gems", "rubysl-json", "faraday-middleware"]
Query Gemcutter Dependency Endpoint API: celluloid-gems,rubysl-json,faraday-middleware
HTTP GET https://index.rubygems.org/api/v1/dependencies?gems=celluloid-gems%2Crubysl-json%2Cfaraday-middleware
HTTP 200 OK https://index.rubygems.org/api/v1/dependencies?gems=celluloid-gems%2Crubysl-json%2Cfaraday-middleware
Query List: []
```

I tried 1.13.6, 1.13.7, 1.14, I can still do bundle install in other projects with other dependencies.

**Comment by colby-swandale** [comment]
ping @Arnaut-Billings is still a problem you're experiencing

**Comment by cabello** [comment]
The way I "solved" this issue was by cleaning up my installation and installing from scratch, I don't recall now but I believe while using brew and or rvm, I removed the ruby versions, and installed them one by one, after that major reset, everything worked as expected with any bundler version.

**Comment by colby-swandale** [comment]
I'm closing this for now. If you're still experiencing your original issue don't be afraid to reopen this ticket.
