### ISSUE TITLE
Feature request: bundle pristine

### ISSUE THREAD

**Issue by jacquescrocker** [bundler/bundler#524]
While debugging something in a rails project, thanks to the awesomeness of `bundle open` I tend to litter my dependencies with logging and debugger statements so I can trace things. At the end, I run `gem pristine --all` to take care of gems I may have hacked up to do. Would be very awesome if bundler also provided a `pristine` command that would revert the bundle to its original state.

**Comment by x-yuri** [comment]
> and then git reset --hard sha1 on each of the git repos

First, `sha1` may supposedly be omitted. Then, AFAICS `<gem>.gemspec` file is modified right after installing a gem, so @jeremy's way is probably better.
