### ISSUE TITLE
Errno::EPERM: Operation not permitted @ utime_internal

### ISSUE THREAD

**Issue by gurramsrikanth** [bundler/bundler#5242]
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `/home/srikanth/.rvm/gems/ruby-2.3.1@global/bin/bundle install`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what happened was...

Error details

    Errno::EPERM: Operation not permitted @ utime_internal - /home/srikanth/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/versions
      /home/srikanth/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/fileutils.rb:1402:in `utime'
      /home/srikanth/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/fileutils.rb:1402:in `copy_metadata'
      /home/srikanth/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/fileutils.rb:475:in `block in copy_entry'
      /home/srikanth/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/fileutils.rb:1504:in `wrap_traverse'
      /home/srikanth/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/fileutils.rb:469:in `copy_entry'
      /home/srikanth/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/fileutils.rb:530:in `rescue in block in mv'
      /home/srikanth/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/fileutils.rb:527:in `block in mv'
      /home/srikanth/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/fileutils.rb:1571:in `block in fu_each_src_dest'
      /home/srikanth/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/fileutils.rb:1587:in `fu_each_src_dest0'
      /home/srikanth/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/fileutils.rb:1569:in `fu_each_src_dest'
      /home/srikanth/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/fileutils.rb:517:in `mv'
      /home/srikanth/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.13.6/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:55:in `block in update'
      /home/srikanth/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
      /home/srikanth/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.13.6/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:29:in `update'
      /home/srikanth/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.13.6/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:65:in `update'
      /home/srikanth/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.13.6/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:56:in `update_and_parse_checksums!'
      /home/srikanth/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.13.6/lib/bundler/fetcher/compact_index.rb:67:in `available?'
      /home/srikanth/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.13.6/lib/bundler/fetcher/compact_index.rb:15:in `call'
      /home/srikanth/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.13.6/lib/bundler/fetcher/compact_index.rb:15:in `block in compact_index_request'
      /home/srikanth/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.13.6/lib/bundler/fetcher.rb:157:in `use_api'
      /home/srikanth/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:332:in `block in api_fetchers'
      /home/srikanth/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:332:in `select'
      /home/srikanth/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:332:in `api_fetchers'
      /home/srikanth/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:337:in `block in remote_specs'
      /home/srikanth/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.13.6/lib/bundler/index.rb:10:in `build'
      /home/srikanth/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:336:in `remote_specs'
      /home/srikanth/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:83:in `specs'
      /home/srikanth/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.13.6/lib/bundler/definition.rb:261:in `block (2 levels) in index'
      /home/srikanth/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.13.6/lib/bundler/definition.rb:259:in `each'
      /home/srikanth/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.13.6/lib/bundler/definition.rb:259:in `block in index'
      /home/srikanth/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.13.6/lib/bundler/index.rb:10:in `build'
      /home/srikanth/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.13.6/lib/bundler/definition.rb:256:in `index'
      /home/srikanth/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.13.6/lib/bundler/definition.rb:250:in `resolve'
      /home/srikanth/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.13.6/lib/bundler/definition.rb:174:in `specs'
      /home/srikanth/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.13.6/lib/bundler/definition.rb:162:in `resolve_remotely!'
      /home/srikanth/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.13.6/lib/bundler/installer.rb:225:in `resolve_if_need'
      /home/srikanth/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.13.6/lib/bundler/installer.rb:78:in `run'
      /home/srikanth/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.13.6/lib/bundler/installer.rb:24:in `install'
      /home/srikanth/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.13.6/lib/bundler/cli/install.rb:71:in `run'
      /home/srikanth/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.13.6/lib/bundler/cli.rb:189:in `install'
      /home/srikanth/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /home/srikanth/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /home/srikanth/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /home/srikanth/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.13.6/lib/bundler/cli.rb:20:in `dispatch'
      /home/srikanth/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /home/srikanth/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.13.6/lib/bundler/cli.rb:11:in `start'
      /home/srikanth/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.13.6/exe/bundle:34:in `block in <top (required)>'
      /home/srikanth/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.13.6/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
      /home/srikanth/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.13.6/exe/bundle:26:in `<top (required)>'
      /home/srikanth/.rvm/gems/ruby-2.3.1@global/bin/bundle:22:in `load'
      /home/srikanth/.rvm/gems/ruby-2.3.1@global/bin/bundle:22:in `<main>'
      /home/srikanth/.rvm/gems/ruby-2.3.1@global/bin/ruby_executable_hooks:15:in `eval'
      /home/srikanth/.rvm/gems/ruby-2.3.1@global/bin/ruby_executable_hooks:15:in `<main>'

Environment
      
  Bundler   1.13.6
  Rubygems  2.6.8
  Ruby      2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
  GEM_HOME  /home/srikanth/.rvm/gems/ruby-2.3.1@global
  RVM       1.27.0 (latest)
  Git       2.7.4
  rubygems-bundler (1.4.4)
--- TEMPLATE END ----------------------------------------------------------------

**Comment by segiddins** [comment]
This should have a better error message using `master`
