### ISSUE TITLE
"Could not find... in any of the sources"

### ISSUE THREAD

**Issue by pcragone** [bundler/bundler#5243]
I keep getting this error on multiple gems in my Gemfile.  I have no idea what went wrong or what happened to make thing stop working, but when I run any command, I'm told a gem is missing, and to run `bundle install` - nice and convenient, it gives me the solution!  So I run `bundle install`, and instead get an error like this:

```
Could not find bootstrap-sass-3.3.6 in any of the sources
```

This is actually immediately preceded by the line:
```
Fetching dependency metadata from https://rubygems.org/.
```

Which to me would suggest that it looked at rubygems.org, and couldn't find it.  Except it's right here: `https://rubygems.org/gems/bootstrap-sass/versions/3.3.6`

Any thoughts on how to resolve this?

**Comment by segiddins** [comment]
Please share the information requested in https://github.com/bundler/bundler/blob/master/ISSUES.md so we can take a look at what's going on. Thanks!

**Comment by pcragone** [comment]
Followed a bunch of the instructions there to no avail - can you give me a hint as to what you're looking for?  I don't know what's causing this problem, so I can't really give you a script to replicate it (the problem is with running `bundle install`, as I described above)

**Comment by pcragone** [comment]
I was able to fix it after running this:
```
git config --global url."https://".insteadOf git://
```

I'm not sure if there's a note somewhere, but that should probably be thrown in the error message

**Comment by segiddins** [comment]
Without the information requested there, we'll be unable to debug.

**Comment by lynnco** [comment]
!

> I was able to fix it

Closing as resolved

**Comment by lynnco** [comment]
@pcragone what @segiddins was asking for was the information in the last section of ISSUES.md https://github.com/bundler/bundler/blob/master/ISSUES.md#reporting-unresolved-problems. If you provide that, we can make a new issue that'll help fix this for other people!
