### ISSUE TITLE
Bundler on WSL

### ISSUE THREAD

**Issue by cnight** [bundler/bundler#5244]
I am trying to use bundler on Windows Subsystem for Linux and I get the following error when building native extensions:

```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

/home/cnight/.rbenv/versions/2.2.0/bin/ruby -r
./siteconf20161209-1589-lkr9to.rb extconf.rb
Cannot allocate memory - /home/cnight/.rbenv/versions/2.2.0/bin/ruby -r
./siteconf20161209-1589-lkr9to.rb extconf.rb 2>&1

Gem files will remain installed in
/home/cnight/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/json-1.8.3 for
inspection.
Results logged to
/home/cnight/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/extensions/x86_64-linux/2.2.0-static/json-1.8.3/gem_make.out

An error occurred while installing json (1.8.3), and Bundler cannot
continue.
Make sure that `gem install json -v '1.8.3'` succeeds before bundling.
```

Here are the contents of the gem_make.out file:

```
/home/cnight/.rbenv/versions/2.2.0/bin/ruby -r ./siteconf20161209-1762-42as7l.rb extconf.rb
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
make: Nothing to be done for `all'.

make "DESTDIR=" install
```

However, I  am able to install all of the gems with native extensions using the gem command:

```
$ gem install json -v1.8.3
Building native extensions.  This could take a while...
/home/cnight/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rubygems/ext/builder.rb:73: warning: Insecure world writable dir /home/cnight/.rbenv/versions in PATH, mode 040777
Successfully installed json-1.8.3
Parsing documentation for json-1.8.3
Installing ri documentation for json-1.8.3
Done installing documentation for json after 1 seconds
1 gem installed
```

I have gone through the troubleshooting procedures in issues.md, the bundle env is:

Environment

    Bundler   1.13.6
    Rubygems  2.4.5
    Ruby      2.2.0p0 (2014-12-25 revision 49005) [x86_64-linux]
    Git       2.11.0

Gemfile

    source 'https://rubygems.org'

    gem 'rails', '4.2.4'
    gem 'mysql'
    gem 'jquery-rails'
    #gem 'jbuilder', '~> 2.0'

    group :development, :test do
        gem 'spring', group: :development
        gem 'byebug'
        gem 'web-console', '~> 2.0'
    end

    group :devserver, :production do
        gem 'unicorn'
        gem 'unicorn-worker-killer'
    end

    gem 'protected_attributes'
    gem 'bcrypt', '~> 3.1.7'
    gem 'mini_magick'
    gem 'pdfkit'

Gemfile.lock

    <No /mnt/c/Users/cnight/Projects/srh/srh2/Gemfile.lock found>

**Comment by segiddins** [comment]
I'm not seeing the platform in your Gemfile, what does `Gem::Platform.local` return?

**Comment by cnight** [comment]
#<Gem::Platform:0x3fffece19084 @cpu="x86_64", @os="linux", @version=nil>

**Comment by cnight** [comment]
An update on this:  I reverted the bundler gem to version 1.10.5 and was able to run bundle install on the same project without any issues.

Strangely though, after installing the bundle with 1.10.5 I then updated to bundler 1.13.6 again and was able to install the bundle to a different location without errors, but only if the location was part of the native linux FS.  Trying to bundle to the mounted windows FS (/mnt/c/...) would still give the "cannot allocate memory" error.

1.10.5 is able to install to both the linux and windows FS without errors.

**Comment by segiddins** [comment]
Is this issue still present with 1.16.0.pre.1?

**Comment by cnight** [comment]
I have stopped installing gems to the mounted windows FS in WSL to avoid this issue.

To test though, I tried installed the same bundle that originally caused this issue to the mounted windows FS with 2 versions of bundler:  1.15.3 and 1.16.0.pre.2  Glad to report it works with both versions!  But, native entensions build very slow, but this could very likely be WSL's fault.

**Comment by segiddins** [comment]
Glad to hear things are working!
