### ISSUE TITLE
Document why `bundle exec` can modify `Gemfile.lock`

### ISSUE THREAD

**Issue by DerGuteMoritz** [bundler/bundler#5245]
I'm a little surprised by `bundle exec` modifying `Gemfile.lock`. Shouldn't it just make the locked gem versions available to the executed command? Granted, [its documentation](http://bundler.io/v1.13/man/bundle-exec.1.html) only mentions that it's "making all gems specified in the Gemfile(5) available to require in Ruby programs" but that would kind of obviate the purpose of the whole locking mechanism. It also goes on to allude that you'd need to run `bundle install` before using it, so I've deduced that `bundle exec` should essentially only care about what's specified in `Gemfile.lock` and certainly not implicitly update it to match whatever is specified in `Gemfile`. I also found #3722 which states that "[s]imply using an application, by running bundle exec commands or by running bin/rails and the like, will not change the lockfile". This seems to be contradicted by the behavior I'm observing:

```
$ mkdir example
$ cd example
$ echo "gem 'rake'" > Gemfile
$ bundle install
Resolving dependencies...
Using rake 12.0.0
Using bundler 1.13.6
Bundle complete! 1 Gemfile dependency, 2 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
$ md5sum Gemfile.lock
376485fba04b5aa22011625ee117d4cc  Gemfile.lock
$ bundle exec rake --version
rake, version 12.0.0
$ md5sum Gemfile.lock
376485fba04b5aa22011625ee117d4cc  Gemfile.lock
```

So far, so good. Now when I change my `Gemfile`:

```
$ echo "gem 'rake', '11.3.0'" > Gemfile 
$ bundle exec rake --version            
rake, version 11.3.0
$ md5sum Gemfile.lock 
28b0a6bb380931fc0091560331dda428  Gemfile.lock
```

Note that I didn't explicitly ask to update my `Gemfile.lock` so I figured it should still use version 12.0.0 of the `rake` gem, but apparently the `Gemfile.lock` is implicitly updated. Is this expected behavior? If so, I would suggest to at least document this explicitly for `bundle exec`. Even nicer would be an option to turn this behavior off.

**Comment by DerGuteMoritz** [comment]
Another command I noticed this behavior with is `bundle check`. It already has the `--dry-run` option which seems to turn off the implicit update of `Gemfile.lock`. Oddly, its documentation says "Locks the Gemfile" which to me sounds like it should do the opposite of what it actually does. Should I file this as a separate ticket?

**Comment by hmistry** [comment]
Thank you for bringing this to our attention and I really appreciate you digging into it some before posting the issue. No need to file another issue for `bundle check` as the behavior is related.

I see your point and the intent of the PR but I'm going to pass this on to some one who is more familiar with the history of bundler to chime in regarding this matter.

@segiddins, @indirect is this behavior correct and do we need to update our documentation to reflect this?

**Comment by segiddins** [comment]
This behavior is intentional -- `bundle exec` will implicitly update the lockfile if the gemfile & lockfile do not match

**Comment by DerGuteMoritz** [comment]
OK so I guess this should be reflected in the documentation then. What's the rationale for this behavior? If I understood this, I'd be happy to contribute a corresponding patch.

In the meantime I found that it's possible to make `bundle exec` abort with an (albeit slightly misleading) error in this situation by running it in an environment where `BUNDLE_FROZEN=1` is set. I haven't yet tried this for other commands.

**Comment by segiddins** [comment]
The rational is that bundler needs the gemfile to determine things such as groups, autorequire, platforms etc for a gem, as that info isn't stored in the lockfile. So it needs to gemfile and the lockfile to be in sync to be able to `bundle exec`

**Comment by lynnco** [comment]
@DerGuteMoritz I assigned this to you o7, let us know if you want to let someone else take it

**Comment by DerGuteMoritz** [comment]
Hey folks, I've taken a stab at it but couldn't find a concise enough patch given the time I can spend on this. That is, I ended up changing many thing in numerous places which lead me to believe that somebody with a more encompassing knowledge of the whole system is probably more qualified to provide a pointedly formulated patch. My apologies and good luck!

**Comment by dcarral** [comment]
Interesting thread here ;)

Question @DerGuteMoritz: when you wrote “numerous places”, did you mean all of them being documentation-related?

**Comment by rubymorillo** [comment]
@segiddins can you confirm that `bundle exec` does modify the lockfile when running `bundle check`? Want to make sure I'm writing the correct thing on the man page. Thx!

**Comment by segiddins** [comment]
`bundle exec` and `bundle check` are two different commands. Exec calls `Bundler.load.setup`, the `Bundler.load` call will call `Definition#lock`, which will re-write the lockfile if the contents have changed. I don't believe that check ever calls `Definition#lock`

**Comment by rubymorillo** [comment]
@segiddins ok, I think I got it. [This comment states something](https://github.com/bundler/bundler/issues/5245#issuecomment-292472336) about `bundle check` and how certain behavior is related (to the issue presented with `bundle exec`). Is that the case? If not, what am I missing? I'm just trying to understand what the ask is for updating the check man page

**Comment by segiddins** [comment]
my apologies, I was going off the top of my head. https://github.com/bundler/bundler/blob/master/lib/bundler/cli/check.rb#L36 shows we do indeed on after a successful `bundle check` as well

**Comment by segiddins** [comment]
Closed by https://github.com/bundler/bundler/pull/5882
