### ISSUE TITLE
No such file or directory @ dir_s_mkdir - //"vender/bundle

### ISSUE THREAD

**Issue by saviocamacam** [bundler/bundler#5246]
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `C:/Ruby22/bin/bundle install`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what happened was...

Error details

    Errno::ENOENT: No such file or directory @ dir_s_mkdir - //"vender/bundle
      C:/Ruby22/lib/ruby/2.2.0/fileutils.rb:252:in `mkdir'
      C:/Ruby22/lib/ruby/2.2.0/fileutils.rb:252:in `fu_mkdir'
      C:/Ruby22/lib/ruby/2.2.0/fileutils.rb:226:in `block (2 levels) in mkdir_p'
      C:/Ruby22/lib/ruby/2.2.0/fileutils.rb:224:in `reverse_each'
      C:/Ruby22/lib/ruby/2.2.0/fileutils.rb:224:in `block in mkdir_p'
      C:/Ruby22/lib/ruby/2.2.0/fileutils.rb:210:in `each'
      C:/Ruby22/lib/ruby/2.2.0/fileutils.rb:210:in `mkdir_p'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler.rb:310:in `block in mkdir_p'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/shared_helpers.rb:105:in `filesystem_access'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler.rb:309:in `mkdir_p'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/installer.rb:206:in `block in create_bundle_path'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/shared_helpers.rb:105:in `filesystem_access'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/installer.rb:205:in `create_bundle_path'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/installer.rb:66:in `run'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/installer.rb:24:in `install'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/cli/install.rb:71:in `run'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/cli.rb:189:in `install'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/cli.rb:20:in `dispatch'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/cli.rb:11:in `start'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/exe/bundle:34:in `block in <top (required)>'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/exe/bundle:26:in `<top (required)>'
      C:/Ruby22/bin/bundle:23:in `load'
      C:/Ruby22/bin/bundle:23:in `<main>'

Environment

  Bundler   1.13.6
  Rubygems  2.4.5.1
  Ruby      2.2.5p319 (2016-04-26 revision 54774) [i386-mingw32]
  GEM_HOME  ///"vender/bundle/" /ruby/2.2.0
  GEM_PATH
  Git       not installed

      Bundler settings

  path
    Set for your local app (C:/Users/savio/git/ProjetoTCC/veraneio/.bundle/config): "\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"vender/bundle\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\" "
  disable_shared_gems
    Set for your local app (C:/Users/savio/git/ProjetoTCC/veraneio/.bundle/config): true
--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/bundler/bundler/search?q=No+such+file+or+directory+%40+dir_s_mkdir+-+%2F%2F%22vender%2Fbundle&type=Issues

If there aren't any reports for this error yet, please create copy and paste the report template above into a new issue. Don't forget to anonymize any private data! The new issue form is located at:
https://github.com/bundler/bundler/issues/new

**Comment by hmistry** [comment]
Check if the GEM_HOME paths is valid in bundle config. It seems that bundler is looking for a `//"vender/bundle"` path but is not able to find it.

**Comment by saviocamacam** [comment]
I delete the file because had an path totally wrong. It's solved.
