### ISSUE TITLE
No such file or directory @ dir_s_mkdir

### ISSUE THREAD

**Issue by GYTO** [bundler/bundler#5249]
Windows 10

$ bundle install
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `J:/RailsInstaller/Ruby2.2.0/bin/bundle install`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what happened was...

Error details

    Errno::EINVAL: Invalid argument @ dir_s_mkdir - J:/"
      J:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/fileutils.rb:252:in `mkdir'
      J:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/fileutils.rb:252:in `fu_mkdir'
      J:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/fileutils.rb:226:in `block (2 levels) in mkdir_p'
      J:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/fileutils.rb:224:in `reverse_each'
      J:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/fileutils.rb:224:in `block in mkdir_p'
      J:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/fileutils.rb:210:in `each'
      J:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/fileutils.rb:210:in `mkdir_p'
      J:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler.rb:310:in `block in mkdir_p'
      J:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/shared_helpers.rb:105:in `filesystem_access'
      J:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler.rb:309:in `mkdir_p'
      J:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/installer.rb:206:in `block in create_bundle_path'
      J:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/shared_helpers.rb:105:in `filesystem_access'
      J:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/installer.rb:205:in `create_bundle_path'
      J:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/installer.rb:66:in `run'
      J:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/installer.rb:24:in `install'
      J:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/cli/install.rb:71:in `run'
      J:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/cli.rb:189:in `install'
      J:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      J:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      J:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      J:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/cli.rb:20:in `dispatch'
      J:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      J:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/cli.rb:11:in `start'
      J:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/exe/bundle:34:in `block in <top (required)>'
      J:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
      J:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/exe/bundle:26:in `<top (required)>'
      J:/RailsInstaller/Ruby2.2.0/bin/bundle:22:in `load'
      J:/RailsInstaller/Ruby2.2.0/bin/bundle:22:in `<main>'
      J:/RailsInstaller/Ruby2.2.0/bin/ruby_executable_hooks:15:in `eval'
      J:/RailsInstaller/Ruby2.2.0/bin/ruby_executable_hooks:15:in `<main>'

Environment

  Bundler   1.13.6
  Rubygems  2.6.3
  Ruby      2.2.4p230 (2015-12-16 revision 53155) [i386-mingw32]
  GEM_HOME  J:/"/"vendor/bundle/" /" /ruby/2.2.0
  GEM_PATH
  Git       2.7.3.windows.1

      Bundler settings

  gem.test
    Set for the current user (C:/Users/Roman/.bundle/config): "false"
  gem.mit
    Set for the current user (C:/Users/Roman/.bundle/config): "false"
  gem.coc
    Set for the current user (C:/Users/Roman/.bundle/config): "false"
  path
    Set for your local app (J:/Projects/ocwatchguy/.bundle/config): "\\\"\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"vendor/bundle\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\" \\\" "
  disable_shared_gems
    Set for your local app (J:/Projects/ocwatchguy/.bundle/config): true
--- TEMPLATE END ----------------------------------------------------------------

**Comment by segiddins** [comment]
Can you please share the contents of `J:/Projects/ocwatchguy/.bundle/config`? It looks like that config file has been corrupted / mis-serialized?

**Comment by lynnco** [comment]
ping @GYTO 

> Can you please share the contents of J:/Projects/ocwatchguy/.bundle/config? It looks like that config file has been corrupted / mis-serialized?

**Comment by colby-swandale** [comment]
I'm closing this for now. If you're still experiencing your original issue don't be afraid to re-open this ticket.

**Comment by GYTO** [comment]
Sorry, I totally forgot about this issue
