### ISSUE TITLE
Errno::EACCES: Permission denied

### ISSUE THREAD

**Issue by leonp** [bundler/bundler#5254]
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `/usr/local/bin/bundle install`

- What did you expect to happen?

  I expected Bundler to install the contentful-data-import jekyll plugin and its dependencies

- What happened instead?

  Instead, what happened was I got this error.

Error details

    Errno::EACCES: Permission denied - (/var/folders/29/pdzzx0h55kgfl6983zj78sf80000gn/T/bundler-compact-index-20161213-1450-12nqye2/versions, /Users/[my user name]/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/versions)
      /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:519:in `rename'
      /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:519:in `block in mv'
      /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1558:in `block in fu_each_src_dest'
      /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1574:in `fu_each_src_dest0'
      /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1556:in `fu_each_src_dest'
      /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:508:in `mv'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:55:in `block in update'
      /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tmpdir.rb:88:in `mktmpdir'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:29:in `update'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:65:in `update'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:56:in `update_and_parse_checksums!'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler/fetcher/compact_index.rb:67:in `available?'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler/fetcher/compact_index.rb:15:in `call'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler/fetcher/compact_index.rb:15:in `block in compact_index_request'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler/fetcher.rb:157:in `use_api'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:332:in `block in api_fetchers'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:332:in `select'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:332:in `api_fetchers'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:337:in `block in remote_specs'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler/index.rb:10:in `build'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:336:in `remote_specs'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:83:in `specs'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler/definition.rb:261:in `block (2 levels) in index'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler/definition.rb:259:in `each'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler/definition.rb:259:in `block in index'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler/index.rb:10:in `build'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler/definition.rb:256:in `index'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler/definition.rb:250:in `resolve'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler/definition.rb:174:in `specs'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler/definition.rb:162:in `resolve_remotely!'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler/installer.rb:225:in `resolve_if_need'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler/installer.rb:78:in `run'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler/installer.rb:24:in `install'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler/cli/install.rb:71:in `run'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler/cli.rb:189:in `install'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler/cli.rb:20:in `dispatch'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler/cli.rb:11:in `start'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/exe/bundle:34:in `block in <top (required)>'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/exe/bundle:26:in `<top (required)>'
      /usr/local/bin/bundle:23:in `load'
      /usr/local/bin/bundle:23:in `<main>'

Environment

  Bundler   1.13.6
  Rubygems  2.0.14.1
  Ruby      2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
  GEM_HOME  /Library/Ruby/Gems/2.0.0
  GEM_PATH  /Library/Ruby/Gems/2.0.0:/Users/[my user name]/.gem/ruby/2.0.0:/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/gems/2.0.0
  Git       2.6.3
--- TEMPLATE END ----------------------------------------------------------------

**Comment by hmistry** [comment]
See the other [Permission denied issues](https://github.com/bundler/bundler/search?utf8=✓&q=Permission+denied&type=Issues). A suite of permission errors have been addressed by #5007 which will release in Bundler 1.14.

Let us know if you're still having trouble and none of those solutions worked for you.

**Comment by lynnco** [comment]
Closing as duplicate
