### ISSUE TITLE
Am facing error while trying bundle install command

### ISSUE THREAD

**Issue by Abhilashcd** [bundler/bundler#5257]
```
C:\fuzzapi-master\bin>bundle install
Fetching https://github.com/lalithr95/API-fuzzer.git

Retrying `git clone "https://github.com/lalithr95/API-fuzzer.git" "C:/Ruby23/lib
/ruby/gems/2.3.0/cache/bundler/git/API-fuzzer-0e162813079405b4aacdf29e0de5008bca
020ede" --bare --no-hardlinks --quiet` due to error (2/4): Errno::ENOENT No such
 file or directory - git clone "https://github.com/lalithr95/API-fuzzer.git" "C:
/Ruby23/lib/ruby/gems/2.3.0/cache/bundler/git/API-fuzzer-0e162813079405b4aacdf29
e0de5008bca020ede" --bare --no-hardlinks --quiet
Retrying `git clone "https://github.com/lalithr95/API-fuzzer.git" "C:/Ruby23/lib
/ruby/gems/2.3.0/cache/bundler/git/API-fuzzer-0e162813079405b4aacdf29e0de5008bca
020ede" --bare --no-hardlinks --quiet` due to error (3/4): Errno::ENOENT No such
 file or directory - git clone "https://github.com/lalithr95/API-fuzzer.git" "C:
/Ruby23/lib/ruby/gems/2.3.0/cache/bundler/git/API-fuzzer-0e162813079405b4aacdf29
e0de5008bca020ede" --bare --no-hardlinks --quiet
Retrying `git clone "https://github.com/lalithr95/API-fuzzer.git" "C:/Ruby23/lib
/ruby/gems/2.3.0/cache/bundler/git/API-fuzzer-0e162813079405b4aacdf29e0de5008bca
020ede" --bare --no-hardlinks --quiet` due to error (4/4): Errno::ENOENT No such
 file or directory - git clone "https://github.com/lalithr95/API-fuzzer.git" "C:
/Ruby23/lib/ruby/gems/2.3.0/cache/bundler/git/API-fuzzer-0e162813079405b4aacdf29
e0de5008bca020ede" --bare --no-hardlinks --quiet
```

--- ERROR REPORT TEMPLATE ------
-------------------------------------------------
- What did you do?

  I ran the command `C:/Ruby23/bin/bundle install`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what happened was...

Error details

    Errno::ENOENT: No such file or directory - git clone "https://github.com/lal
ithr95/API-fuzzer.git" "C:/Ruby23/lib/ruby/gems/2.3.0/cache/bundler/git/API-fuzz
er-0e162813079405b4aacdf29e0de5008bca020ede" --bare --no-hardlinks --quiet
      C:/Ruby23/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/source/git/g
it_proxy.rb:161:in ``'
      C:/Ruby23/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/source/git/g
it_proxy.rb:161:in `block (2 levels) in git'
      C:/Ruby23/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/source/git/g
it_proxy.rb:233:in `block in capture_and_filter_stderr'
      C:/Ruby23/lib/ruby/2.3.0/tempfile.rb:295:in `open'
      C:/Ruby23/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/source/git/g
it_proxy.rb:231:in `capture_and_filter_stderr'
      C:/Ruby23/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/source/git/g
it_proxy.rb:161:in `block in git'
      C:/Ruby23/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/shared_helpe
rs.rb:72:in `with_clean_git_env'
      C:/Ruby23/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/source/git/g
it_proxy.rb:160:in `git'
      C:/Ruby23/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/source/git/g
it_proxy.rb:152:in `block in git_retry'
      C:/Ruby23/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/retry.rb:39:
in `run'
      C:/Ruby23/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/retry.rb:29:
in `attempt'
      C:/Ruby23/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/source/git/g
it_proxy.rb:151:in `git_retry'
      C:/Ruby23/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/source/git/g
it_proxy.rb:103:in `checkout'
      C:/Ruby23/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/source/git.r
b:293:in `fetch'
      C:/Ruby23/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/source/git.r
b:155:in `specs'
      C:/Ruby23/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.r
b:261:in `block (2 levels) in index'
      C:/Ruby23/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.r
b:259:in `each'
      C:/Ruby23/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.r
b:259:in `block in index'
      C:/Ruby23/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/index.rb:10:
in `build'
      C:/Ruby23/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.r
b:256:in `index'
      C:/Ruby23/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.r
b:250:in `resolve'
      C:/Ruby23/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.r
b:174:in `specs'
      C:/Ruby23/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.r
b:162:in `resolve_remotely!'
      C:/Ruby23/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/installer.rb
:225:in `resolve_if_need'
      C:/Ruby23/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/installer.rb
:78:in `run'
      C:/Ruby23/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/installer.rb
:24:in `install'
      C:/Ruby23/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli/install.
rb:71:in `run'
      C:/Ruby23/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:189:i
n `install'
      C:/Ruby23/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/
lib/thor/command.rb:27:in `run'
      C:/Ruby23/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/
lib/thor/invocation.rb:126:in `invoke_command'
      C:/Ruby23/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/
lib/thor.rb:359:in `dispatch'
      C:/Ruby23/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:20:in
 `dispatch'
      C:/Ruby23/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/
lib/thor/base.rb:440:in `start'
      C:/Ruby23/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:11:in
 `start'
      C:/Ruby23/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/exe/bundle:34:in `block
in <top (required)>'
      C:/Ruby23/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/friendly_err
ors.rb:100:in `with_friendly_errors'
      C:/Ruby23/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/exe/bundle:26:in `<top (
required)>'
      C:/Ruby23/bin/bundle:22:in `load'
      C:/Ruby23/bin/bundle:22:in `<main>'

Environment

  Bundler   1.13.6
  Rubygems  2.6.7
  Ruby      2.3.0p0 (2015-12-25 revision 53290) [i386-mingw32]
  GEM_HOME  C:/Ruby23/lib/ruby/gems/2.3.0
  GEM_PATH  C:/Ruby23/lib/ruby/gems/2.3.0;C:/Users/aujas/.gem/ruby/2.3.0
  Git       not installed
--- TEMPLATE END ---------------------------------------------------------------
-

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this err
or:
https://github.com/bundler/bundler/search?q=No+such+file+or+directory+-+git+clon
e+%22https+%2F%2Fgithub.com%2Flalithr95%2FAPI-fuzzer.git%22+%22C+%2FRuby23%2Flib
%2Fruby%2Fgems%2F2.3.0%2Fcache%2Fbundler%2Fgit%2FAPI-fuzzer-0e162813079405b4aacd
f29e0de5008bca020ede%22+--bare+--no-hardlinks+--quiet&type=Issues

If there aren't any reports for this error yet, please create copy and paste the
 report template above into a new issue. Don't forget to anonymize any private d
ata! The new issue form is located at:
https://github.com/bundler/bundler/issues/new

**Comment by segiddins** [comment]
You don't have git installed and are trying to use git gems, though this should have a better error message

**Comment by shardulparab97** [comment]
It is because you don't have git installed.
Install Git and add it to the PATH system variable.(Please check that this step is done properly)

**Comment by lynnco** [comment]
Considering this resolved pending feedback from @Abhilashcd

**Comment by Abhilashcd** [comment]
segiddins & shardulparab97  thanks for the help.
