### ISSUE TITLE
Bundle Error

### ISSUE THREAD

**Issue by foxesden** [bundler/bundler#5258]
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `/usr/local/rvm/gems/ruby-2.3.0/bin/bundle `

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what happened was...

Error details

    ThreadError: can't create Thread: Resource temporarily unavailable
      /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/timeout.rb:81:in `start'
      /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/timeout.rb:81:in `block in timeout'
      /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/timeout.rb:101:in `timeout'
      /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/net/http.rb:878:in `connect'
      /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
      /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/net/http.rb:858:in `start'
      /usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/net/http/persistent.rb:700:in `start'
      /usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/net/http/persistent.rb:965:in `reset'
      /usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/net/http/persistent.rb:628:in `connection_for'
      /usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/net/http/persistent.rb:994:in `request'
      /usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/fetcher/downloader.rb:48:in `request'
      /usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/fetcher/downloader.rb:16:in `fetch'
      /usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/fetcher/compact_index.rb:115:in `call'
      /usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:42:in `block in update'
      /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
      /usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:29:in `update'
      /usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:65:in `update'
      /usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:73:in `update_info'
      /usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:44:in `block in dependencies'
      /usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/fetcher/compact_index.rb:86:in `block (3 levels) in compact_index_client'
      /usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/worker.rb:65:in `apply_func'
      /usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/worker.rb:60:in `block in process_queue'
      /usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/worker.rb:57:in `loop'
      /usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/worker.rb:57:in `process_queue'
      /usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/worker.rb:29:in `block (2 levels) in initialize'

Environment
      
  Bundler   1.13.6
  Rubygems  2.5.1
  Ruby      2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]
  GEM_HOME  /usr/local/rvm/gems/ruby-2.3.0
  GEM_PATH  /usr/local/rvm/gems/ruby-2.3.0:/usr/local/rvm/gems/ruby-2.3.0@global
  RVM       1.27.0 (latest)
  Git       1.7.1
  rubygems-bundler (1.4.4)
      
      Bundler settings
      
  git.allow_insecure
    Set for the current user (/home/sam/.bundle/config): "true"
--- TEMPLATE END ----------------------------------------------------------------

**Comment by foxesden** [comment]
Hi,
Received the following error whilt trying to install huginn on Centos 6.5

**Comment by segiddins** [comment]
We should probably handle this in `Bundler::Worker` by failing gracefully when creating a new thread fails

**Comment by segiddins** [comment]
Done in https://github.com/bundler/bundler/pull/5278, included in 1.14.
