### ISSUE TITLE
Same gem twice coming from different sources: from source at `.` and source at `.`

### ISSUE THREAD

**Issue by voxik** [bundler/bundler#5263]
Trying to execute vagrant-libvirt test suite with Bundler 1.13.6, I observer following error:

```
$ bundle exec rspec2 spec
bundler: failed to load command: rspec2 (/usr/bin/rspec2)
Bundler::Dsl::DSLError: 
[!] There was an error parsing `Gemfile`: You cannot specify the same gem twice coming from different sources.
You specified that vagrant-libvirt (>= 0) should come from source at `.` and source at `.`
. Bundler cannot continue.
 #  from /builddir/build/BUILD/vagrant-libvirt-0.0.36/usr/share/vagrant/gems/gems/vagrant-libvirt-0.0.36/Gemfile:24
 #  -------------------------------------------
 #  group :plugins do
 >    gem 'vagrant-libvirt', :path => '.'
 #  end
 #  -------------------------------------------
  /usr/share/gems/gems/bundler-1.13.6/lib/bundler/dsl.rb:118:in `gem'
  /builddir/build/BUILD/vagrant-libvirt-0.0.36/usr/share/vagrant/gems/gems/vagrant-libvirt-0.0.36/Gemfile:24:in `block in eval_gemfile'
  /usr/share/gems/gems/bundler-1.13.6/lib/bundler/dsl.rb:214:in `group'
  /builddir/build/BUILD/vagrant-libvirt-0.0.36/usr/share/vagrant/gems/gems/vagrant-libvirt-0.0.36/Gemfile:23:in `eval_gemfile'
  /usr/share/gems/gems/bundler-1.13.6/lib/bundler/dsl.rb:41:in `instance_eval'
  /usr/share/gems/gems/bundler-1.13.6/lib/bundler/dsl.rb:41:in `eval_gemfile'
  /usr/share/gems/gems/bundler-1.13.6/lib/bundler/dsl.rb:11:in `evaluate'
  /usr/share/gems/gems/bundler-1.13.6/lib/bundler/definition.rb:33:in `build'
  /usr/share/gems/gems/bundler-1.13.6/lib/bundler.rb:127:in `definition'
  /usr/share/gems/gems/bundler-1.13.6/lib/bundler.rb:93:in `setup'
  /usr/share/gems/gems/bundler-1.13.6/lib/bundler/setup.rb:20:in `<top (required)>'
  /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
  /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
```

This is the Gemfile in question [1]. It seems that one definition is the explicit call to "gemspec", while the second definition is the explicit "gem" call. I agree that the construct is a bit weird, on the other hand, bundler complaining about the different source is weird as well, since the source is obviously the same. What would be the right solution here?

I noticed, that vagrant-libvirt upstream is using Bundler 1.12.x so far, so they haven't encounter the issue yet.

[1] https://github.com/vagrant-libvirt/vagrant-libvirt/blob/master/Gemfile#L24

**Comment by segiddins** [comment]
The source is different, one is a `source::path` and the other is `source::gemspec ` and I believe bundler is correct to disallow both

**Comment by voxik** [comment]
If the ```source::path``` pointed to something different then the '.', I'd agree, but if they are resolved to the same path?

**Comment by segiddins** [comment]
They still have different behavior

**Comment by voxik** [comment]
Do they? How could I tell? But honestly, I really don't understand what is the purpose of the "plugins" group. I'd say it is not needed at all. On the other hand, it probably was not introduced just by accident ...

**Comment by lynnco** [comment]
It seems like the error message could be better, and also vagrant-libvirt is using bundler in a very non-standard way

I made an issue for the error messaging https://github.com/bundler/bundler/issues/5289

@voxik you may want to investigate removing the plugins group, and creating that as a PR against vagrant-libvirt

**Comment by torras** [comment]
The `:plugins` group is a group used by vagrant when it gets executed by bundler, and loads as vagrant plugin every gem indicated in there.

A possible workaround could be using `gemspec` in the `:plugins` group, instead of `paht: '.'`, like this: https://gist.github.com/torras/3cc2159105fbfb7d7f5d63967ab045c8
