### ISSUE TITLE
bundler: failed to load command: pod after running bundle install for CocoaPods repo

### ISSUE THREAD

**Issue by benasher44** [bundler/bundler#5264]
Hi! We recently started running into this issue shown in full in this travis log, and we can't seem to pin it to a change local to CP configuration:

https://travis-ci.org/CocoaPods/CocoaPods/jobs/184771287

You can reproduce it locally by doing the following (using mac system ruby, which is 2.0.0p648):
1. Clone the CocoaPods repo
2. Checkout master (currently e379f7f45ece67bf6fc4feff3f396808b11f0e8a)
3. Run `bundle install --path=vendor/bundle`
4. Run `bundle exec pod env`

The last command results in the following error:
```
/Users/basher/.rvm/gems/ruby-2.0.0-p648/gems/bundler-1.13.6/lib/bundler/rubygems_integration.rb:336:in `block (2 levels) in replace_gem': cocoapods is not part of the bundle. Add it to Gemfile. (Gem::LoadError
```

Thanks for your help!

**Comment by segiddins** [comment]
Running `bundle install` from that commit, I get

```
Bundler could not find compatible versions for gem "cocoapods-downloader":
  In snapshot (Gemfile.lock):
    cocoapods-downloader (= 1.1.2)

  In Gemfile:
    cocoapods-downloader

    cocoapods was resolved to 1.2.0.beta.1, which depends on
      cocoapods-downloader (< 2.0, >= 1.1.3)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
```

**Comment by benasher44** [comment]
Whoops! Turns out it was just the lockfile bump wasn't committed. Closing. Thanks @segiddins!

**Comment by segiddins** [comment]
We still shouldn't be giving that incorrect error message
