### ISSUE TITLE
GitHub sources are checked out with git://

### ISSUE THREAD

**Issue by siegy22** [bundler/bundler#5265]
Hi there!

I saw this since the warning was introduced when using the git protocol to fetch dependencies with bundler. It's probably good to show this error message but I'm a fan of the `github: ` option when using `gem`.

Example:

```ruby
gem 'something', github: 'dude/something'
```

This will write something like this into the lock file:

```
GIT
  remote: git://github.com/dude/something.git
  revision: e9a5a089355067232d61bb11475a5f4da13854d3
  specs:
    something (0.0.1)
      ...
      ...
```

So I think we should change the github option to use either https or even ssh to clone the repo. Because when I use the GitHub flag, I don't want to see the error message that I checked out the repo with the git protocol.

Cheers, keep up the good work :+1:

**Comment by segiddins** [comment]
We have done this for 2.0, but it's a backwards incompatible change to make for 1.x. You can redefine the `github` git shortcut, or use the full `git` option in the meantime.

**Comment by siegy22** [comment]
Wow, nice reaction time! :smile:

Oh I see. Thank you!

**Comment by siegy22** [comment]
@segiddins What's the plan for the 2.0 release? Next year or even later?

**Comment by segiddins** [comment]
As soon as we can get it finished, see https://github.com/bundler/bundler/issues/4856 for progress

**Comment by siegy22** [comment]
Okay, thanks! 
If I can help with anything, message me.
