### ISSUE TITLE
Unexpected error occured

### ISSUE THREAD

**Issue by koffisani** [bundler/bundler#5271]
I'm facing issues when installing jekyll on Ubuntu 16.04. It throws the following message : 

> --- ERROR REPORT TEMPLATE -------------------------------------------------------
>- What did you do?
>
 > I ran the command `/usr/local/bin/bundle install`
>
>- What did you expect to happen?
>
>  I expected Bundler to...
>
>- What happened instead?
>
>  Instead, what happened was...
>
>
>Error details
>
 >  Errno::EPERM: Operation not permitted @ utime_internal - /home/koffisani/.bundle/cache/compact_index/rubygems.org.80.9e8aca59a0c3a407fba89eb64623162d/versions
      /usr/lib/ruby/2.3.0/fileutils.rb:1402:in `utime'
      /usr/lib/ruby/2.3.0/fileutils.rb:1402:in `copy_metadata'
      /usr/lib/ruby/2.3.0/fileutils.rb:475:in `block in copy_entry'
      /usr/lib/ruby/2.3.0/fileutils.rb:1504:in `wrap_traverse'
      /usr/lib/ruby/2.3.0/fileutils.rb:469:in `copy_entry'
      /usr/lib/ruby/2.3.0/fileutils.rb:530:in `rescue in block in mv'
      /usr/lib/ruby/2.3.0/fileutils.rb:527:in `block in mv'
      /usr/lib/ruby/2.3.0/fileutils.rb:1571:in `block in fu_each_src_dest'
      /usr/lib/ruby/2.3.0/fileutils.rb:1587:in `fu_each_src_dest0'
      /usr/lib/ruby/2.3.0/fileutils.rb:1569:in `fu_each_src_dest'
      /usr/lib/ruby/2.3.0/fileutils.rb:517:in `mv'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:55:in `block in update'
      /usr/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:29:in `update'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:65:in `update'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:56:in `update_and_parse_checksums!'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/fetcher/compact_index.rb:67:in `available?'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/fetcher/compact_index.rb:15:in `call'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/fetcher/compact_index.rb:15:in `block in compact_index_request'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/fetcher.rb:157:in `use_api'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:332:in `block in api_fetchers'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:332:in `select'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:332:in `api_fetchers'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:337:in `block in remote_specs'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/index.rb:10:in `build'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:336:in `remote_specs'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:83:in `specs'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.rb:261:in `block (2 levels) in index'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.rb:259:in `each'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.rb:259:in `block in index'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/index.rb:10:in `build'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.rb:256:in `index'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.rb:250:in `resolve'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.rb:174:in `specs'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.rb:162:in `resolve_remotely!'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/installer.rb:225:in `resolve_if_need'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/installer.rb:78:in `run'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/installer.rb:24:in `install'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli/install.rb:71:in `run'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:189:in `install'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:20:in `dispatch'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:11:in `start'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/exe/bundle:34:in `block in <top (required)>'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/exe/bundle:26:in `<top (required)>'
      /usr/local/bin/bundle:23:in `load'
      /usr/local/bin/bundle:23:in `<main>'

>Environment
>     
>  Bundler   1.13.6
>  Rubygems  2.5.1
>  Ruby      2.3.1p112 (2016-04-26 revision 0) [x86_64-linux-gnu]
>  GEM_HOME  /var/lib/gems/2.3.0
>  GEM_PATH  /var/lib/gems/2.3.0:/home/koffisani/.gem/ruby/2.3.0:/usr/lib/x86_64-linux-gnu/rubygems-integration/2.3.0:/usr/share/rubygems-integration/2.3.0:/usr/share/rubygems-integration/all
>  Git       2.7.4
>--- TEMPLATE END ----------------------------------------------------------------

I've tried the solution suggested [here](https://github.com/bundler/bundler/issues/5269), but that hasn't solved my problem. Can anyone help me fix this ?

**Comment by colby-swandale** [comment]
Double check to make sure that Bundler has the appropriate permissions to read/write to `/home/koffisani/.bundle` including any sub files & folders.

Are you running Bundler as a unprivileged user or as `root`?

**Comment by koffisani** [comment]
My `/home/koffisani/.bundle` folder is in 777 mod. I'm running as unprivileged user. Even when I tried with root, I get this error preceded by this warning message : `Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your bundle as root will break this
application for all non-root users on this machine.`
Output when running as root : 
> Fetching gem metadata from http://rubygems.org/...........
Fetching version metadata from http://rubygems.org/..
Fetching dependency metadata from http://rubygems.org/.
Resolving dependencies...
Using i18n 0.7.0
Using json 1.8.3
Using minitest 5.10.1
Using thread_safe 0.3.5
Using public_suffix 2.0.4
Using coffee-script-source 1.12.2
Using execjs 2.7.0
Using colorator 1.1.0
Installing ffi 1.9.14 with native extensions
Using multipart-post 2.0.0
Using forwardable-extended 2.6.0
Using gemoji 2.1.0
Using net-dns 0.8.0
Using sass 3.4.23
Using rb-fsevent 0.9.8
Using kramdown 1.11.1
Using liquid 3.0.6
Using mercenary 0.3.6
Using rouge 1.11.1
Using safe_yaml 1.0.4
Using mini_portile2 2.1.0
Using jekyll-paginate 1.1.0
Using jekyll-swiss 0.4.0
Using minima 2.0.0
Using unicode-display_width 1.1.2
Using bundler 1.13.6
Using tzinfo 1.2.2
Using addressable 2.5.0
Using coffee-script 2.4.1
>Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
>
    current directory: /var/lib/gems/2.3.0/gems/ffi-1.9.14/ext/ffi_c
    /usr/bin/ruby2.3 -r ./siteconf20161223-26497-1vwidb2.rb extconf.rb
    mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h
> 
> extconf failed, exit code 1
> 
> Gem files will remain installed in /var/lib/gems/2.3.0/gems/ffi-1.9.14 for inspection.
> Results logged to /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/ffi-1.9.14/gem_make.out
>
> An error occurred while installing ffi (1.9.14), and Bundler cannot continue.
Make sure that `gem install ffi -v '1.9.14'` succeeds before bundling.

That's it.

**Comment by colby-swandale** [comment]
Looks like Bundler can now read/write to the folder from the original comment but It now looks like you're missing the Ruby headers. IIRC you need to install the `ruby-dev` package, then try again.

**Comment by koffisani** [comment]
Right, thanks @colby-swandale. I installed successively `ruby2.3-dev` and its dependences (nokogiri, libz-dev) and it finally goes fine. Thank you.
