### ISSUE TITLE
    Errno::EACCES: Permission denied @ rb_file_s_rename - 

### ISSUE THREAD

**Issue by tau150** [bundler/bundler#5272]
bundle install
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `/Users/Santi/.rbenv/versions/2.3.3/bin/bundle install`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what happened was...

Error details

    Errno::EACCES: Permission denied @ rb_file_s_rename - (/var/folders/_2/cwkt7tsj6pgc7ll0lbwgzrbw0000gn/T/bundler-compact-index-20161222-58582-1gh34ur/versions, /Users/Santi/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/versions)
      /Users/Santi/.rbenv/versions/2.3.3/lib/ruby/2.3.0/fileutils.rb:528:in `rename'
      /Users/Santi/.rbenv/versions/2.3.3/lib/ruby/2.3.0/fileutils.rb:528:in `block in mv'
      /Users/Santi/.rbenv/versions/2.3.3/lib/ruby/2.3.0/fileutils.rb:1571:in `block in fu_each_src_dest'
      /Users/Santi/.rbenv/versions/2.3.3/lib/ruby/2.3.0/fileutils.rb:1587:in `fu_each_src_dest0'
      /Users/Santi/.rbenv/versions/2.3.3/lib/ruby/2.3.0/fileutils.rb:1569:in `fu_each_src_dest'
      /Users/Santi/.rbenv/versions/2.3.3/lib/ruby/2.3.0/fileutils.rb:517:in `mv'
      /Users/Santi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:55:in `block in update'
      /Users/Santi/.rbenv/versions/2.3.3/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
      /Users/Santi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:29:in `update'
      /Users/Santi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:65:in `update'
      /Users/Santi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:56:in `update_and_parse_checksums!'
      /Users/Santi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/fetcher/compact_index.rb:67:in `available?'
      /Users/Santi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/fetcher/compact_index.rb:15:in `call'
      /Users/Santi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/fetcher/compact_index.rb:15:in `block in compact_index_request'
      /Users/Santi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/fetcher.rb:157:in `use_api'
      /Users/Santi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:332:in `block in api_fetchers'
      /Users/Santi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:332:in `select'
      /Users/Santi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:332:in `api_fetchers'
      /Users/Santi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:337:in `block in remote_specs'
      /Users/Santi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/index.rb:10:in `build'
      /Users/Santi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:336:in `remote_specs'
      /Users/Santi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:83:in `specs'
      /Users/Santi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.rb:261:in `block (2 levels) in index'
      /Users/Santi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.rb:259:in `each'
      /Users/Santi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.rb:259:in `block in index'
      /Users/Santi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/index.rb:10:in `build'
      /Users/Santi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.rb:256:in `index'
      /Users/Santi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.rb:250:in `resolve'
      /Users/Santi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.rb:174:in `specs'
      /Users/Santi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.rb:162:in `resolve_remotely!'
      /Users/Santi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/installer.rb:225:in `resolve_if_need'
      /Users/Santi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/installer.rb:78:in `run'
      /Users/Santi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/installer.rb:24:in `install'
      /usr/local/Cellar/rbenv/1.1.0/rbenv.d/exec/gem-rehash/rubygems_plugin.rb:27:in `install'
      /Users/Santi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli/install.rb:71:in `run'
      /Users/Santi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:189:in `install'
      /Users/Santi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /Users/Santi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /Users/Santi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /Users/Santi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:20:in `dispatch'
      /Users/Santi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /Users/Santi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:11:in `start'
      /Users/Santi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/exe/bundle:34:in `block in <top (required)>'
      /Users/Santi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
      /Users/Santi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/exe/bundle:26:in `<top (required)>'
      /Users/Santi/.rbenv/versions/2.3.3/bin/bundle:22:in `load'
      /Users/Santi/.rbenv/versions/2.3.3/bin/bundle:22:in `<main>'

Environment

  Bundler   1.13.6
  Rubygems  2.5.2
  Ruby      2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin16]
  GEM_HOME  /Users/Santi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0
  GEM_PATH  /Users/Santi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0:/Users/Santi/.gem/ruby/2.3.0
  Git       2.6.4
--- TEMPLATE END ----------------------------------------------------------------

**Comment by colby-swandale** [comment]
Please make sure that Bundler has the appropriate permissions to read/write to `/Users/Santi/.bundle` and any sub folder & directory.

**Comment by hmistry** [comment]
See the other [Permission denied issues](https://github.com/bundler/bundler/search?utf8=✓&q=Permission+denied&type=Issues). A suite of permission errors have been addressed by #5007 which will release in Bundler 1.14.

Let us know if you're still having trouble and none of those solutions worked for you.

**Comment by lynnco** [comment]
Closing as duplicate
