### ISSUE TITLE
Install gems from HTTP

### ISSUE THREAD

**Issue by Paxa** [bundler/bundler#5275]
Is it possible to install gems from http?
```ruby
gem 'activerecord-jdbc-adapter', http: 'https://github.com/jruby/activerecord-jdbc-adapter/archive/71a44e5258ebaad93d8d190a7cecf491e2ddb0ae.zip'
```

That repo size is 132mb, download from github: 16mb, create gem & upload to S3: 393Kb
For other big projects gonna be big difference too

**Comment by segiddins** [comment]
This is not currently possible, we recommend making releases of gems instead of using git gems when this problem arises.
