### ISSUE TITLE
Please make a release that supports :mri_24

### ISSUE THREAD

**Issue by amatsuda** [bundler/bundler#5281]
Now that ruby 2.4.0 has been released, we're in need of a released version of bundler that includes #5170 🙏 
Thank you!

**Comment by segiddins** [comment]
@indirect do you think this is worth a patch to 1.13?

**Comment by indirect** [comment]
@segiddins yeah, I'm down with a patch and a release ASAP.

**Comment by segiddins** [comment]
@indirect will do in a few hours then

**Comment by segiddins** [comment]
1.13.7 released!

**Comment by amatsuda** [comment]
@segiddins Thank you so much!
