### ISSUE TITLE
`bundle update` removes some platform gems

### ISSUE THREAD

**Issue by matthewd** [bundler/bundler#5285]
https://github.com/rails/rails/pull/27459

In https://github.com/rails/rails/commit/774be3ea3b9d25ab69daf11c5071deaf053d7d5b, I [made an unrelated change to the Gemfile and then] ran `bundle update`.

The resulting Gemfile.lock still contained `*-mingw32` entries for a number of other gems, but dropped them for `ffi`.

A few minutes later, I did https://github.com/rails/rails/commit/05b5de6710ed4147446a9a4dd4a674fe9cff02dc on another branch. That one bumped the versions on some triple-platform gems (`pg`, `mysql2`), reduced `eventmachine` to a single entry, and left others untouched -- including `ffi`(!).

Am I doing something dumb? :confused:

:heart: :heart: :heart:

ruby 2.4.0 / gem 2.6.8 / bundler 1.13.7

**Comment by segiddins** [comment]
I believe this is fixed on `master`

**Comment by matthewd** [comment]
Confirm; `bundle update` from the same starting point produces a more expected result when using master, and when run on the above file, it correctly filled in the gap (https://github.com/rails/rails/commit/aa3cc7db3a3530ec071402067bba1a38e6f6d800).

Sorry, I had a (not very good, apparently) look for an existing issue/PR, but didn't check master. 😞
