### ISSUE TITLE
LoadError: cannot load such file -- bcrypt_ext

### ISSUE THREAD

**Issue by veganstraightedge** [bundler/bundler#5286]
This is in a Rails app which is unfortunately in a private repo.

It uses Scripts To Rule Them All style scripts with almost nothing changed from the examples in the repo: https://github.com/github/scripts-to-rule-them-all

On my dev machine, everything Just Works™.

On the dev machines of two of people on the team, it explodes when `script/update` runs. Specifically during "Updating db…".

https://github.com/github/scripts-to-rule-them-all/blob/master/script/update#L13

***

Gems are bundled into `/vendor` in `script/bootstrap` which `script/udpate` calls before doing anything else.

https://github.com/github/scripts-to-rule-them-all/blob/master/script/bootstrap#L28-L33

***

Like I said, it works for me, but not for two other folks. If you need to clone it to debug it, ping me for an invite.

**Comment by segiddins** [comment]
Please follow the steps the debug outlined in https://github.com/bundler/bundler/blob/master/ISSUES.md and share the information requested there. Thanks!

**Comment by lynnco** [comment]
ping @veganstraightedge 

> Please follow the steps the debug outlined in https://github.com/bundler/bundler/blob/master/ISSUES.md and share the information requested there. Thanks!

**Comment by veganstraightedge** [comment]
I ended up un-vendoring the bundled gems. That fixed their problems.
