### ISSUE TITLE
Document all settings

### ISSUE THREAD

**Issue by segiddins** [bundler/bundler#5288]
A list of undocumented settings is at https://github.com/bundler/bundler/blob/master/spec/quality_spec.rb#L195, all of them should be removed from the list of exemptions

**Comment by nickborromeo** [comment]
@segiddins can I clarify, what do you mean by 
>  all of them should be removed from the list of exemptions

Where can one find this list?

**Comment by segiddins** [comment]
The array linked to above in the quality spec
