### ISSUE TITLE
NoMethodError: undefined method `<' for nil:NilClass

### ISSUE THREAD

**Issue by akannur** [bundler/bundler#5291]
--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/bundler/bundler/search?q=undefined+method+%60%3C%27+for+nil+NilClass&type=Issues

If there aren't any reports for this error yet, please create copy and paste the report template above into a new issue. Don't forget to anonymize any private data! The new issue form is located at:
https://github.com/bundler/bundler/issues/new

**Comment by segiddins** [comment]
Please share the entire issue report

**Comment by segiddins** [comment]
Closing due to lack of response.
