### ISSUE TITLE
Consider renaming `Bundler::Molinillo::DependencyGraph::Action.name`

### ISSUE THREAD

**Issue by backus** [bundler/bundler#5292]
Some tooling expects classes to uphold the contract of `Class#name`. Bundler introduces some issues because the following classes do not uphold the contract of `Class#name` returning a string that can be used to resolved to a constant:

- `Bundler::Molinillo::DependencyGraph::Tag`
- `Bundler::Molinillo::DependencyGraph::SetPayload`
- `Bundler::Molinillo::DependencyGraph::DetachVertexNamed`
- `Bundler::Molinillo::DependencyGraph::AddVertex`
- `Bundler::Molinillo::DependencyGraph::AddEdgeNoCircular`

I'd be happy to open a small PR which renames `Action.name` (and descendants) to something like `Action.action_name`

**Comment by segiddins** [comment]
I believe this change has already been made in Molinillo

**Comment by segiddins** [comment]
This is fixed in the 1.14 series.

**Comment by backus** [comment]
Thanks @segiddins!
