### ISSUE TITLE
bundle install --deployment got "Could not locate Gemfile"

### ISSUE THREAD

**Issue by agate** [bundler/bundler#5293]
Hi,

I am trying to build a docker image. And my Dockerfile is like this.

```
RUN mkdir -p /tmp/bundle
ADD Gemfile.lock /tmp/bundle/Gemfile.lock
RUN cd /tmp/bundle && bundle install --deployment --path=/bundle
```

I only add Gemfile.lock (without Gemfile). It's because there are some complicated requirements in the original Gemfile. So it can not work alone in docker.

So I have some questions:
* Why under deployment mode I got the error: "Could not locate Gemfile"
* Does `--deployment` mode still need **Gemfile** ? If so, is that possible to generate a **Gemfile** based on **Gemfile.lock**?

**Comment by segiddins** [comment]
You still need to add your gemfile, bundler requires both the gemfile and the lockfile to work.

**Comment by agate** [comment]
@segiddins is there a way to reverse Gemfile.lock to Gemfile?

**Comment by agate** [comment]
Can I just use the gems under `DEPENDENCIES` in Gemfile.lock?

**Comment by segiddins** [comment]
@agate there is not, as information in the gemfile such as groups, platforms, install conditionals are not stored in the lockfile

**Comment by agate** [comment]
Aha! That make sense. Thanks for the explanation. I don't have those special info in my original Gemfile. I can simply read the `DEPENDENCIES` in Gemfile.lock and revert it. So I wrote a gem for this.

* https://github.com/agate/gemfile_lock_to_gemfile
* https://rubygems.org/gems/gemfile_lock_to_gemfile

**Comment by segiddins** [comment]
Cool!
