### ISSUE TITLE
gem error

### ISSUE THREAD

**Issue by pallavi16** [bundler/bundler#5299]
Error details

    Errno::EACCES: Permission denied @ rb_file_s_rename - (/var/folders/vj/dkscdd2x3wbftywhjf9d8lx80000gn/T/bundler-compact-index-20170101-53146-7cinnb/versions, /Users/pallaviaggarwal/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/versions)
      /Users/pallaviaggarwal/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/fileutils.rb:528:in `rename'
      /Users/pallaviaggarwal/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/fileutils.rb:528:in `block in mv'
      /Users/pallaviaggarwal/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/fileutils.rb:1571:in `block in fu_each_src_dest'
      /Users/pallaviaggarwal/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/fileutils.rb:1587:in `fu_each_src_dest0'
      /Users/pallaviaggarwal/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/fileutils.rb:1569:in `fu_each_src_dest'
      /Users/pallaviaggarwal/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/fileutils.rb:517:in `mv'
      /Users/pallaviaggarwal/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:55:in `block in update'
      /Users/pallaviaggarwal/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
      /Users/pallaviaggarwal/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:29:in `update'
      /Users/pallaviaggarwal/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:65:in `update'
      /Users/pallaviaggarwal/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:56:in `update_and_parse_checksums!'
      /Users/pallaviaggarwal/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/fetcher/compact_index.rb:67:in `available?'
      /Users/pallaviaggarwal/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/fetcher/compact_index.rb:15:in `call'
      /Users/pallaviaggarwal/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/fetcher/compact_index.rb:15:in `block in compact_index_request'
      /Users/pallaviaggarwal/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/fetcher.rb:157:in `use_api'
      /Users/pallaviaggarwal/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/source/rubygems.rb:332:in `block in api_fetchers'
      /Users/pallaviaggarwal/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/source/rubygems.rb:332:in `select'
      /Users/pallaviaggarwal/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/source/rubygems.rb:332:in `api_fetchers'
      /Users/pallaviaggarwal/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/source/rubygems.rb:337:in `block in remote_specs'
      /Users/pallaviaggarwal/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/index.rb:10:in `build'
      /Users/pallaviaggarwal/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/source/rubygems.rb:336:in `remote_specs'
      /Users/pallaviaggarwal/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/source/rubygems.rb:83:in `specs'
      /Users/pallaviaggarwal/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/definition.rb:261:in `block (2 levels) in index'
      /Users/pallaviaggarwal/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/definition.rb:259:in `each'
      /Users/pallaviaggarwal/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/definition.rb:259:in `block in index'
      /Users/pallaviaggarwal/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/index.rb:10:in `build'
      /Users/pallaviaggarwal/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/definition.rb:256:in `index'
      /Users/pallaviaggarwal/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/definition.rb:250:in `resolve'
      /Users/pallaviaggarwal/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/definition.rb:174:in `specs'
      /Users/pallaviaggarwal/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/definition.rb:162:in `resolve_remotely!'
      /Users/pallaviaggarwal/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/installer.rb:225:in `resolve_if_need'
      /Users/pallaviaggarwal/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/installer.rb:78:in `run'
      /Users/pallaviaggarwal/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/installer.rb:24:in `install'
      /Users/pallaviaggarwal/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/cli/install.rb:71:in `run'
      /Users/pallaviaggarwal/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/cli.rb:189:in `install'
      /Users/pallaviaggarwal/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /Users/pallaviaggarwal/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /Users/pallaviaggarwal/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /Users/pallaviaggarwal/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/cli.rb:20:in `dispatch'
      /Users/pallaviaggarwal/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /Users/pallaviaggarwal/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/cli.rb:11:in `start'
      /Users/pallaviaggarwal/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/exe/bundle:34:in `block in <top (required)>'
      /Users/pallaviaggarwal/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
      /Users/pallaviaggarwal/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/exe/bundle:26:in `<top (required)>'
      /Users/pallaviaggarwal/.rvm/gems/ruby-2.3.3/bin/bundle:22:in `load'
      /Users/pallaviaggarwal/.rvm/gems/ruby-2.3.3/bin/bundle:22:in `<main>'
      /Users/pallaviaggarwal/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
      /Users/pallaviaggarwal/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'

Environment
      
  Bundler   1.13.7
  Rubygems  2.6.8
  Ruby      2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin16]
  GEM_HOME  /Users/pallaviaggarwal/.rvm/gems/ruby-2.3.3
  GEM_PATH  /Users/pallaviaggarwal/.rvm/gems/ruby-2.3.3:/Users/pallaviaggarwal/.rvm/gems/ruby-2.3.3@global
  RVM       1.28.0 (latest)
  Git       2.11.0
  rubygems-bundler (1.4.4)
--- TEMPLATE END ----------------------------------------------------------------

**Comment by hmistry** [comment]
See the other [Permission denied issues](https://github.com/bundler/bundler/search?utf8=✓&q=Permission+denied&type=Issues). A suite of permission errors have been addressed by #5007 which will release in Bundler 1.14.

Let us know if you're still having trouble and none of those solutions worked for you.

**Comment by colby-swandale** [comment]
I'm closing this for now. If you're still experiencing your original issue don't be afraid to re-open this ticket.
