### ISSUE TITLE
rails new failing at bundle install step

### ISSUE THREAD

**Issue by kboone00** [bundler/bundler#5304]
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/exe/bundle install`

- What did you expect to happen?

  I expected Bundler to finish the bundle install step for rails new "app_name"

- What happened instead?

  Instead, what happened was bundle install failed. I tried manually deleting the bundle files in the temp directory and deleting the app folder and reinstalling....

Error details

    Errno::ENOTEMPTY: Directory not empty @ dir_s_rmdir - C:/Users/kbooo/AppData/Local/Temp/bundler-compact-index-20170103-10844-1j399sx
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/fileutils.rb:1444:in `rmdir'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/fileutils.rb:1444:in `block in remove_dir1'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/fileutils.rb:1458:in `platform_support'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/fileutils.rb:1443:in `remove_dir1'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/fileutils.rb:1436:in `remove'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/fileutils.rb:778:in `block in remove_entry'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/fileutils.rb:1493:in `ensure in postorder_traverse'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/fileutils.rb:1493:in `postorder_traverse'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/fileutils.rb:776:in `remove_entry'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/tmpdir.rb:94:in `ensure in mktmpdir'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/tmpdir.rb:94:in `mktmpdir'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:29:in `update'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:65:in `update'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:56:in `update_and_parse_checksums!'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/lib/bundler/fetcher/compact_index.rb:67:in `available?'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/lib/bundler/fetcher/compact_index.rb:15:in `call'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/lib/bundler/fetcher/compact_index.rb:15:in `block in compact_index_request'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/lib/bundler/fetcher.rb:157:in `use_api'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/lib/bundler/source/rubygems.rb:332:in `block in api_fetchers'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/lib/bundler/source/rubygems.rb:332:in `select'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/lib/bundler/source/rubygems.rb:332:in `api_fetchers'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/lib/bundler/source/rubygems.rb:337:in `block in remote_specs'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/lib/bundler/index.rb:10:in `build'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/lib/bundler/source/rubygems.rb:336:in `remote_specs'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/lib/bundler/source/rubygems.rb:83:in `specs'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/lib/bundler/definition.rb:261:in `block (2 levels) in index'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/lib/bundler/definition.rb:259:in `each'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/lib/bundler/definition.rb:259:in `block in index'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/lib/bundler/index.rb:10:in `build'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/lib/bundler/definition.rb:256:in `index'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/lib/bundler/definition.rb:250:in `resolve'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/lib/bundler/definition.rb:174:in `specs'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/lib/bundler/definition.rb:162:in `resolve_remotely!'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/lib/bundler/installer.rb:225:in `resolve_if_need'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/lib/bundler/installer.rb:78:in `run'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/lib/bundler/installer.rb:24:in `install'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/lib/bundler/cli/install.rb:71:in `run'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/lib/bundler/cli.rb:189:in `install'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/lib/bundler/cli.rb:20:in `dispatch'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/lib/bundler/cli.rb:11:in `start'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/exe/bundle:34:in `block in <main>'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/exe/bundle:26:in `<main>'

Environment

  Bundler   1.13.7
  Rubygems  2.6.8
  Ruby      2.2.4p230 (2015-12-16 revision 53155) [i386-mingw32]
  GEM_HOME  C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0
  GEM_PATH  C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0;H:/.gem/ruby/2.2.0
  Git       1.9.4.msysgit.2
--- TEMPLATE END ----------------------------------------------------------------

**Comment by colby-swandale** [comment]
Hi @kboone00, sorry that no one has replied to your issue. Bundler `1.14` was recently released which addresses problems with file permissions and temporary folders. Update Bundler to the latest version and try running `bundle install` again.

If that is still not working then try removing the folder at `C:/Users/kbooo/AppData/Local/Temp/bundler-compact-index-20170103-10844-1j399sx` and run `bundle install` again.

Sorry again for such the long delay.

**Comment by colby-swandale** [comment]
I'm closing this for now. If you're still experiencing your original issue don't be afraid to re-open this ticket.
