### ISSUE TITLE
Erorr

### ISSUE THREAD

**Issue by nguyenmanhtuan93** [bundler/bundler#5305]
$ bundle install
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `/home/amilo/.rvm/gems/ruby-2.3.1/bin/bundle install`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what happened was...

Error details

    ArgumentError: parent directory is world writable but not sticky
      /home/amilo/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tmpdir.rb:93:in `ensure in mktmpdir'
      /home/amilo/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tmpdir.rb:95:in `mktmpdir'
      /home/amilo/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.1/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:29:in `update'
      /home/amilo/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.1/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:64:in `update'
      /home/amilo/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.1/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:55:in `update_and_parse_checksums!'
      /home/amilo/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.1/lib/bundler/fetcher/compact_index.rb:67:in `available?'
      /home/amilo/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.1/lib/bundler/fetcher/compact_index.rb:15:in `call'
      /home/amilo/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.1/lib/bundler/fetcher/compact_index.rb:15:in `block in compact_index_request'
      /home/amilo/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.1/lib/bundler/fetcher.rb:157:in `use_api'
      /home/amilo/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.1/lib/bundler/source/rubygems.rb:332:in `block in api_fetchers'
      /home/amilo/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.1/lib/bundler/source/rubygems.rb:332:in `select'
      /home/amilo/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.1/lib/bundler/source/rubygems.rb:332:in `api_fetchers'
      /home/amilo/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.1/lib/bundler/source/rubygems.rb:337:in `block in remote_specs'
      /home/amilo/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.1/lib/bundler/index.rb:10:in `build'
      /home/amilo/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.1/lib/bundler/source/rubygems.rb:336:in `remote_specs'
      /home/amilo/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.1/lib/bundler/source/rubygems.rb:83:in `specs'
      /home/amilo/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.1/lib/bundler/definition.rb:263:in `block (2 levels) in index'
      /home/amilo/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.1/lib/bundler/definition.rb:261:in `each'
      /home/amilo/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.1/lib/bundler/definition.rb:261:in `block in index'
      /home/amilo/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.1/lib/bundler/index.rb:10:in `build'
      /home/amilo/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.1/lib/bundler/definition.rb:258:in `index'
      /home/amilo/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.1/lib/bundler/definition.rb:252:in `resolve'
      /home/amilo/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.1/lib/bundler/definition.rb:176:in `specs'
      /home/amilo/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.1/lib/bundler/definition.rb:164:in `resolve_remotely!'
      /home/amilo/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.1/lib/bundler/installer.rb:225:in `resolve_if_need'
      /home/amilo/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.1/lib/bundler/installer.rb:78:in `run'
      /home/amilo/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.1/lib/bundler/installer.rb:24:in `install'
      /home/amilo/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.1/lib/bundler/cli/install.rb:71:in `run'
      /home/amilo/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.1/lib/bundler/cli.rb:189:in `install'
      /home/amilo/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /home/amilo/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /home/amilo/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.1/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /home/amilo/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.1/lib/bundler/cli.rb:20:in `dispatch'
      /home/amilo/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.1/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /home/amilo/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.1/lib/bundler/cli.rb:11:in `start'
      /home/amilo/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.1/exe/bundle:34:in `block in <top (required)>'
      /home/amilo/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.1/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
      /home/amilo/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.1/exe/bundle:26:in `<top (required)>'
      /home/amilo/.rvm/gems/ruby-2.3.1/bin/bundle:22:in `load'
      /home/amilo/.rvm/gems/ruby-2.3.1/bin/bundle:22:in `<main>'

Environment
      
  Bundler   1.13.1
  Rubygems  2.6.6
  Ruby      2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
  GEM_HOME  /home/amilo/.rvm/gems/ruby-2.3.1
  GEM_PATH  /home/amilo/.rvm/gems/ruby-2.3.1:/home/amilo/.rvm/gems/ruby-2.3.1@global
  RVM       1.27.0 (latest)
  Git       2.7.4
--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/bundler/bundler/search?q=parent+directory+is+world+writable+but+not+sticky&type=Issues

If there aren't any reports for this error yet, please create copy and paste the report template above into a new issue. Don't forget to anonymize any private data! The new issue form is located at:
https://github.com/bundler/bundler/issues/new

**Comment by segiddins** [comment]
This should be fixed in 1.13.3 and above, please try updating bundler.

**Comment by colby-swandale** [comment]
I'm closing this issue for now. Don't be afraid to re-open this ticket with more information If you're still experiencing your original issue.
