### ISSUE TITLE
when doing bundle install getting this error

### ISSUE THREAD

**Issue by gopirajum** [bundler/bundler#5309]
Unfortunately, an unexpected error occurred, and Bundler cannot continue.
https://github.com/bundler/bundler/search?q=Permission+denied+%40+sys_fail2+-+%28%2Ftmp%2Fbundler-compact-index-20170107-16440-sc54zd%2Fversions%2C+%2Fhome%2Fgopiraju%2F.bundle%2Fcache%2Fcompact_index%2Frubygems.org.443.29b0360b937aa4d161703e6160654e47%2Fversions%29&type=Issues

**Comment by segiddins** [comment]
Please share the entire error template.

**Comment by segiddins** [comment]
Closing due to lack of response
