### ISSUE TITLE
Bundler cannot continue.

### ISSUE THREAD

**Issue by chukwuma30** [bundler/bundler#5313]
https://github.com/bundler/bundler/search?q=Permission+denied+%40+rb_sysopen+-+C       +%2FUsers%2FCHUKWU%7E1%2FAppData%2FLocal%2FTemp%2Fbundler-compact-index-20170110       -15912-65jtxm%2Fversions&type=Issues

**Comment by colby-swandale** [comment]
Please read https://github.com/bundler/bundler/blob/master/ISSUES.md on how to correctly report  an issue.
