### ISSUE TITLE
 Build Log 

### ISSUE THREAD

**Issue by chukwuma30** [bundler/bundler#5314]
After running this command $ git push heroku master
in my App: I got this Message:- 
-----> Ruby app detected

-----> Compiling Ruby/Rails

-----> Using Ruby version: ruby-2.2.6

###### WARNING:

       Removing `Gemfile.lock` because it was generated on Windows.

       Bundler will do a full resolve so native gems are handled properly.

       This may result in unexpected gem versions being used in your app.

       In rare occasions Bundler may not be able to resolve your dependencies at all.

       https://devcenter.heroku.com/articles/bundler-windows-gemfile

-----> Installing dependencies using bundler 1.13.6

       Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4

       Fetching gem metadata from https://rubygems.org/..........

       Fetching version metadata from https://rubygems.org/..

       Fetching dependency metadata from https://rubygems.org/.

       Resolving dependencies...

       Using rake 12.0.0

       Using concurrent-ruby 1.0.4

       Using i18n 0.7.0

       Using minitest 5.10.1

       Using thread_safe 0.3.5

       Using builder 3.2.2

       Using erubis 2.7.0

       Using mini_portile2 2.1.0

       Using rack 2.0.1

       Using nio4r 1.2.1

       Using websocket-extensions 0.1.2

       Using mime-types-data 3.2016.0521

       Using arel 7.1.4

       Using bundler 1.13.6

       Using coffee-script-source 1.12.2

       Using execjs 2.7.0

       Using method_source 0.8.2

       Using thor 0.19.4

       Using multi_json 1.12.1

       Using pg 0.19.0

       Using puma 3.6.2

       Using sass 3.4.23

       Using tilt 2.0.5

       Using turbolinks-source 5.0.0

       Using tzinfo 1.2.2

       Using nokogiri 1.7.0.1

       Using rack-test 0.6.3

       Using websocket-driver 0.6.4

       Using mime-types 3.1

       Using coffee-script 2.4.1

       Using uglifier 3.0.4

       Using sprockets 3.7.1

       Using turbolinks 5.0.1

       Using activesupport 5.0.1

       Using loofah 2.0.3

       Using mail 2.6.4

       Using rails-html-sanitizer 1.0.3

       Using rails-dom-testing 2.0.2

       Using globalid 0.3.7

       Using activemodel 5.0.1

       Using jbuilder 2.6.1

       Using actionview 5.0.1

       Using activejob 5.0.1

       Using activerecord 5.0.1

       Using actionpack 5.0.1

       Using actioncable 5.0.1

       Using actionmailer 5.0.1

       Using railties 5.0.1

       Using sprockets-rails 3.2.0

       Using coffee-rails 4.2.1

       Using jquery-rails 4.2.2

       Using rails 5.0.1

       Using sass-rails 5.0.6

       Bundle complete! 12 Gemfile dependencies, 53 gems now installed.

       Gems in the groups development and test were not installed.

       Bundled gems are installed into ./vendor/bundle.

       Bundle completed (2.95s)

       Cleaning up the bundler cache.

-----> Detecting rake tasks

-----> Preparing app for Rails asset pipeline

       Running: rake assets:precompile

       Asset precompilation completed (1.55s)

       Cleaning assets

       Running: rake assets:clean

###### WARNING:

       You have not declared a Ruby version in your Gemfile.

       To set your Ruby version add this line to your Gemfile:

       ruby '2.2.6'

       # See https://devcenter.heroku.com/articles/ruby-versions for more information.

###### WARNING:

       Removing `Gemfile.lock` because it was generated on Windows.

       Bundler will do a full resolve so native gems are handled properly.

       This may result in unexpected gem versions being used in your app.

       In rare occasions Bundler may not be able to resolve your dependencies at all.

       https://devcenter.heroku.com/articles/bundler-windows-gemfile

###### WARNING:

       No Procfile detected, using the default web server.

       We recommend explicitly declaring how to boot your server process via a Procfile.

       https://devcenter.heroku.com/articles/ruby-default-web-server

-----> Discovering process types

       Procfile declares types     -> (none)

       Default types for buildpack -> console, rake, web, worker

-----> Compressing...

       Done: 28M

-----> Launching...

       Released v8

       https://goldenbicrubyblog.herokuapp.com/ deployed to Heroku

but opening the above url in browser i got this error message:

The page you were looking for doesn't exist.

You may have mistyped the address or the page may have moved.

If you are the application owner check the logs for more information.

Pls i need solution to fix this error message

**Comment by segiddins** [comment]
Please read https://github.com/bundler/bundler/blob/master/ISSUES.md. Since this appears to be a Heroku-specific issue, please contact their support team for assistance.
