### ISSUE TITLE
bundler 1.13.7 does not add hombrew ruby 2.4 built-in gems in LOAD_PATH

### ISSUE THREAD

**Issue by hashar** [bundler/bundler#5317]
I have an application that is meant to work on both ruby 2.2 and ruby 2.4 (it is running on different operating system).  When running `bundle exec` under Homebrew ruby 2.4, the apps eventually fails to load the built in gem `xmlrpc`:

```
$ ruby -e 'require "xmlrpc/client"'
$ 

$ bundle exec ruby -e 'require "xmlrpc/client"'
-e:1:in `require': cannot load such file -- xmlrpc/client (LoadError)
	from -e:1:in `<main>'
$
```

As of ruby2.4, `xmlrpc` is no more a library but a bundled gem [ruby#12160 Extract XMLRPC library to bundled gem](https://bugs.ruby-lang.org/issues/12160). On my system its available under either:

* `/usr/local/lib/ruby/gems/2.4.0/gems/xmlrpc-0.2.1`
* `/usr/local/Cellar/ruby/2.4.0/lib/ruby/gems/2.4.0/gems/xmlrpc-0.2.1`

Under both environment `$LOAD_PATH` refers to the first:
```
~/.gem/gems/bundler-1.13.7/lib   # only under bundle exec
/usr/local/lib/ruby/site_ruby/2.4.0
/usr/local/lib/ruby/site_ruby/2.4.0/x86_64-darwin15
/usr/local/lib/ruby/site_ruby
/usr/local/lib/ruby/vendor_ruby/2.4.0
/usr/local/lib/ruby/vendor_ruby/2.4.0/x86_64-darwin15
/usr/local/lib/ruby/vendor_ruby
/usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0
/usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/x86_64-darwin15
```

The path is properly defined in gem environment:
```
$ gem env envpath
~/.gem/ruby/2.4.0
/usr/local/lib/ruby/gems/2.4.0
/usr/local/Cellar/ruby/2.4.0/lib/ruby/gems/2.4.0
~/.gem
```

I guess bundler strip out the shared gems when running.

With ruby 2.4, one can add `gem 'xmlrpc'` in the `Gemfile`, however that fails under ruby 2.2 because the gem from rubygems wants ruby >= 2.4.  So it is kind of an egg and chicken problem.

What I am wondering is whether Gem or bundler could keep the path to the ruby bundled gem. 

Maybe that is an issue I should fill against homebrew core ? instead.  Regardless any help or tip will be much welcome!

Informations gathered according to ISSUES.md
https://gist.github.com/hashar/c56d25fce6bcc77945b016b3e3846a2e

**Comment by segiddins** [comment]
This is intentional -- `xmlrpc` isn't an actual default gem under 2.4.0. 

```
ruby -e 'puts Gem::Specification.find_by_name("xmlrpc").default_gem?' # false
ruby -e 'puts Gem::Specification.find_by_name("json").default_gem?' # true
```

**Comment by hashar** [comment]
I guess I got entirely confused -:}  Will conditionally add `xmlrpc` whenever running under ruby 2.4+. Thank you a lot!

**Comment by eregon** [comment]
What's a good way to specify the dependency on `xmlrpc` in the Gemfile, but only for Ruby 2.4+ ?

```ruby
gem 'xmlrpc', platform: [:mri_24, :mri_25]
```
would need to change for every release, so that's bad.

```ruby
gem 'xmlrpc'
```
might work on older versions but it's not ideal and bundled gems are not designed to run on older versions before they were extracted of stdlib.

**Comment by segiddins** [comment]
Unsupported API, but

```
gem 'xmlrpc', platform: PLATFORM_MAP.keys.select { |k| k.to_s =~ /\Amri_(\d+)/ && $1 >= '24' }
```
