### ISSUE TITLE
JSON 1.8.3 issue with Ruby 2.3.3 (and others Ruby versions I've tried)

### ISSUE THREAD

**Issue by jb61264** [bundler/bundler#5320]
Overall I am trying to install snorby as detailed here: http://www.ubuntu-howtodoit.com/?p=138
when i run "bundle install" in step 8.6 at the referenced link...I had been getting an error that says:

An error occurred while installing json (1.8.3), and Bundler cannot continue.
Make sure that `gem install json -v '1.8.3'` succeeds before bundling.

So, I installed RVM because I heard that I could use Ruby version 2.3.3 with the json 1.8.3. I made sure that I had set RVM to use Ruby 2.3.3 and then run bundle install from /var/www/html/snorby and I get the following message

--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `/home/myhome/.rvm/gems/ruby-2.3.3/bin/bundle update`

- What did you expect to happen?

  I expected Bundler to update

- What happened instead?

  Instead, what happened was it threw the error that I have copied from the template

Error details

    Errno::EACCES: Permission denied @ rb_file_s_rename - (/tmp/bundler-compact-index-20170111-31212-16gnof1/versions, /home/myhome/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/versions)
      /home/myhome/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/fileutils.rb:528:in `rename'
      /home/myhome/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/fileutils.rb:528:in `block in mv'
      /home/myhome/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/fileutils.rb:1571:in `block in fu_each_src_dest'
      /home/myhome/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/fileutils.rb:1587:in `fu_each_src_dest0'
      /home/myhome/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/fileutils.rb:1569:in `fu_each_src_dest'
      /home/myhome/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/fileutils.rb:517:in `mv'
      /home/myhome/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:55:in `block in update'
      /home/myhome/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
      /home/myhome/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:29:in `update'
      /home/myhome/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:65:in `update'
      /home/myhome/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:56:in `update_and_parse_checksums!'
      /home/myhome/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/fetcher/compact_index.rb:67:in `available?'
      /home/myhome/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/fetcher/compact_index.rb:15:in `call'
      /home/myhome/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/fetcher/compact_index.rb:15:in `block in compact_index_request'
      /home/myhome/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/fetcher.rb:157:in `use_api'
      /home/myhome/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/source/rubygems.rb:332:in `block in api_fetchers'
      /home/myhome/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/source/rubygems.rb:332:in `select'
      /home/myhome/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/source/rubygems.rb:332:in `api_fetchers'
      /home/myhome/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/source/rubygems.rb:337:in `block in remote_specs'
      /home/myhome/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/index.rb:10:in `build'
      /home/myhome/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/source/rubygems.rb:336:in `remote_specs'
      /home/myhome/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/source/rubygems.rb:83:in `specs'
      /home/myhome/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/definition.rb:261:in `block (2 levels) in index'
      /home/myhome/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/definition.rb:259:in `each'
      /home/myhome/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/definition.rb:259:in `block in index'
      /home/myhome/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/index.rb:10:in `build'
      /home/myhome/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/definition.rb:256:in `index'
      /home/myhome/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/definition.rb:250:in `resolve'
      /home/myhome/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/definition.rb:174:in `specs'
      /home/myhome/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/definition.rb:162:in `resolve_remotely!'
      /home/myhome/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/installer.rb:225:in `resolve_if_need'
      /home/myhome/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/installer.rb:78:in `run'
      /home/myhome/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/installer.rb:24:in `install'
      /home/myhome/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/cli/update.rb:61:in `run'
      /home/myhome/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/cli.rb:228:in `update'
      /home/myhome/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /home/myhome/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /home/myhome/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /home/myhome/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/cli.rb:20:in `dispatch'
      /home/myhome/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /home/myhome/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/cli.rb:11:in `start'
      /home/myhome/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/exe/bundle:34:in `block in <top (required)>'
      /home/myhome/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
      /home/myhome/.rvm/gems/ruby-2.3.3/gems/bundler-1.13.7/exe/bundle:26:in `<top (required)>'
      /home/myhome/.rvm/gems/ruby-2.3.3/bin/bundle:22:in `load'
      /home/myhome/.rvm/gems/ruby-2.3.3/bin/bundle:22:in `<main>'
      /home/myhome/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
      /home/myhome/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'

Environment

  Bundler   1.13.7
  Rubygems  2.5.2
  Ruby      2.3.3p222 (2016-11-21 revision 56859) [x86_64-linux]
  GEM_HOME  /home/myhome/.rvm/gems/ruby-2.3.3
  GEM_PATH  /home/myhome/.rvm/gems/ruby-2.3.3:/home/myhome/.rvm/gems/ruby-2.3.3@global
  RVM       1.28.0 (latest)
  Git       2.7.4
  rubygems-bundler (1.4.4)
--- TEMPLATE END ----------------------------------------------------------------

**Comment by colby-swandale** [comment]
Make sure that Bundler has the appropriate permissions to read/write to `/home/myhome/.bundle/`.

There are [plenty of other issues](https://github.com/bundler/bundler/search?utf8=%E2%9C%93&q=Permission+denied&type=Issues) similar to this that can help resolve your issue.

**Comment by colby-swandale** [comment]
I'm closing this for now. If you're still experiencing your original issue don't be afraid to re-open this ticket.
