### ISSUE TITLE
bundle install fails on WSL when using a git repository with a path

### ISSUE THREAD

**Issue by omarqureshi** [bundler/bundler#5322]
I'm currently using Docker for Windows (1.12.6) and WSL on Windows 10 (Linux DESKTOP-DLRRFKC 3.4.0+ #1 PREEMPT Thu Aug 1 17:06:05 CST 2013 x86_64 x86_64 x86_64 GNU/Linux)

I'm having issues when running ```bundle install --path vendor/bundle```, note that this ONLY happens in WSL when writing to NTFS, both in Linux and OSX this works fine

```bash
`git clone --no-checkout --quiet
"/myapp/vendor/bundle/ruby/2.3.0/cache/bundler/git/bootstrap-sass-b9ed78534df7520565c4f55770e38b8d270f127f"
"/myapp/vendor/bundle/ruby/2.3.0/bundler/gems/bootstrap-sass-cf9a9b181fdf"` due
to error (4/4): Bundler::Source::Git::GitCommandError Git error: command `git
clone --no-checkout --quiet
"/myapp/vendor/bundle/ruby/2.3.0/cache/bundler/git/bootstrap-sass-b9ed78534df7520565c4f55770e38b8d270f127f"
"/myapp/vendor/bundle/ruby/2.3.0/bundler/gems/bootstrap-sass-cf9a9b181fdf"` in
directory /myapp has failed. If this error persists you could try removing the
cache directory
'/myapp/vendor/bundle/ruby/2.3.0/cache/bundler/git/bootstrap-sass-b9ed78534df7520565c4f55770e38b8d270f127f'error:
internal error: refs/remotes/origin/2.0-stable is not a valid packed reference!
```

I've put up a repository with an example of what I mean at https://github.com/omarqureshi/not_valid_packed_reference

I'm pretty sure that this is a Git issue and will also be looking to report this to the Git mailing list, however, they may equally say that this is a Docker and/or NTFS issue

The volume mount is the cause of this https://github.com/omarqureshi/not_valid_packed_reference/blob/master/docker-compose.yml#L8

I can get around this by NOT using --path, however, it would be preferable if this just worked on WSL too.

If you'd like any other information, please let me know, otherwise, the Dockerfile should have enough information there to let you know what my setup is like.

**Comment by segiddins** [comment]
I'm honestly not seeing how this could be a bundler issue if the same git command works everywhere else -- it looks like an issue either with git or WSL to me.

**Comment by omarqureshi** [comment]
I personally think it's more of an issue with Git interacting with NTFS, however, given that the use of bundler is the only place that I have experienced this (and I have successfully been using Docker, Git and WSL on other Rails apps before this), it's probably not a bad place to put this issue.

I'll probably try testing this by installing Ruby on WSL and then bundler too.

**Comment by segiddins** [comment]
Can you run the git command successfully outside of bundler?

**Comment by omarqureshi** [comment]
I've tried a ```git clone --no-checkout bootstrap-sass/ other-bootstrap/``` and that seems to work, however, that's not quite the same here

**Comment by omarqureshi** [comment]
What exactly does a bundle install do when given a github repository and a tag?

**Comment by omarqureshi** [comment]
Also, with the example, it makes no difference whether I specify a tag or not.

**Comment by PhilipOakley** [comment]
There was a similar issue recently on Git for Windows with fix https://github.com/dscho/git/commit/2174823bd176818aa072d2137070d81de737831a and a Git test https://github.com/git/git/commit/16615f0fbc445ef958f2453c926526d5e2280700 with fix https://github.com/git/git/commit/7814fbe3f1e7cea1a675408df7b5dd1f5be731cc

Check if it is relevant

**Comment by omarqureshi** [comment]
I'll have a look later on this evening, thanks!

**Comment by colby-swandale** [comment]
I'm closing this for now. If you're still experiencing your original issue don't be afraid to re-open this ticket.
