### ISSUE TITLE
[Feature request] Add BUNDLE_CLEAN_ON_INSTALL option

### ISSUE THREAD

**Issue by christophemaximin** [bundler/bundler#5323]
Hi all, I'm thinking of submitting a PR to add the following behavior:

- if `BUNDLE_CLEAN_ON_INSTALL == true` ...
- whenever `bundle install` or `bundle update` is successfully called, a `clean` would be automatically called.

**Reason why:**
Because I have a project which has `BUNDLE_PATH: "vendor/bundle"`, with `vendor` tracked by git, and it would be nice to automatically get rid of unnecessary gems mistakenly added by developers during development.

Is this option worth adding?

**Comment by segiddins** [comment]
This seems to be similar to the `bundle pristine` feature that has been discussed elsewhere. I believe the `--force` option to install may also be what you're looking for?

**Comment by segiddins** [comment]
Ah sorry, misunderstood the desired feature. You want to remove everything bundler wouldn't be installing from the install directory?

**Comment by christophemaximin** [comment]
yep, `bundle clean` does exactly what I want, however I just want to add an option that would be calling it automatically, so I can stick this option in `.bundle/config` (version controlled) so all developers won't accidentally push un-necessary gems.

**Comment by christophemaximin** [comment]
( You can think of it as a simple  "post bundle install hook" )

**Comment by segiddins** [comment]
One thing to consider -- how will this option interact with installing into the system gem path? Or using `--without` on installation?

**Comment by christophemaximin** [comment]
I suppose it should do exactly what `bundle clean` would do, if it can't clean because of file permissions or other reasons, an error/warning should be correctly thrown (this is my guess as to what happens when you `bundle clean` something you can't).

**Comment by segiddins** [comment]
My concern is more that this will lead to people accidentally deleting gems they don't want to from their local system

**Comment by christophemaximin** [comment]
Ah I see it now, if you share gems between projects (typical case), indeed that would be an issue.
Doing something like what I proposed might be too heavy-handed.
How about some kind of generic "hook" (e.g. `BUNDLE_POST_INSTALL_HOOK`) with which a user can set an arbitrary command to be executed with the same environment variables?
The effect would be the same, but it would be clearer that "you better know what you're doing with when putting something there".

**Comment by tylerhunt** [comment]
@christophemaximin Unless I'm missing something, I believe what you're looking to do can already be accomplished by setting the `BUNDLE_CLEAN` option.

**Comment by christophemaximin** [comment]
@tylerhunt wow, thanks, you are correct!
However... how can I get a complete list of valid bundler options? `BUNDLE_CLEAN` doesn't seem to be documented anywhere, it isn't in the source itself (as a string), I suppose there's some catch-all thing with BUNDLE_* but I just can't find it :/

**Comment by tylerhunt** [comment]
@christophemaximin Correct. Took me a while to trace this down recently, too, but the magic is here: https://github.com/bundler/bundler/blob/b72d6af45a6bc55327c8cdd127b79e7b1fa8ab79/lib/bundler/settings.rb#L221-L225. And this shows the cascade of configuration sources that are checked: https://github.com/bundler/bundler/blob/b72d6af45a6bc55327c8cdd127b79e7b1fa8ab79/lib/bundler/settings.rb#L53-L59

**Comment by segiddins** [comment]
https://github.com/bundler/bundler/blob/d7bafcc38ddc605a5bd5636ae3d40dcb51bf1720/spec/quality_spec.rb#L200 its on the list of settings to document, see https://github.com/bundler/bundler/issues/5288 which is tracking documenting all of those settings.

**Comment by christophemaximin** [comment]
Brilliant, thank you all.
