### ISSUE TITLE
Errno::EACCES: Permission denied @ rb_file_s_rename

### ISSUE THREAD

**Issue by dhniels** [bundler/bundler#5324]
Davids-iMac:~ Dave$ jekyll new /Users/Dave/GitHub/blog
New jekyll site installed in /Users/Dave/GitHub/blog. 
Running bundle install in /Users/Dave/GitHub/blog... 

--- ERROR REPORT TEMPLATE -------------------------------------------------------

Error details

    Errno::EACCES: Permission denied @ rb_file_s_rename - (/var/folders/8j/gkkhjn9j01g8r_jk_77x35gr0000gn/T/bundler-compact-index-20170112-1336-1x8q9yx/versions, /Users/Dave/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/versions)
      /usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/fileutils.rb:462:in `rename'
      /usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/fileutils.rb:462:in `block in mv'
      /usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/fileutils.rb:1454:in `block in fu_each_src_dest'
      /usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/fileutils.rb:1470:in `fu_each_src_dest0'
      /usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/fileutils.rb:1452:in `fu_each_src_dest'
      /usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/fileutils.rb:451:in `mv'
      /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.13.7/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:55:in `block in update'
      /usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/tmpdir.rb:89:in `mktmpdir'
      /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.13.7/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:29:in `update'
      /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.13.7/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:65:in `update'
      /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.13.7/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:56:in `update_and_parse_checksums!'
      /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.13.7/lib/bundler/fetcher/compact_index.rb:67:in `available?'
      /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.13.7/lib/bundler/fetcher/compact_index.rb:15:in `call'
      /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.13.7/lib/bundler/fetcher/compact_index.rb:15:in `block in compact_index_request'
      /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.13.7/lib/bundler/fetcher.rb:157:in `use_api'
      /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.13.7/lib/bundler/source/rubygems.rb:332:in `block in api_fetchers'
      /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.13.7/lib/bundler/source/rubygems.rb:332:in `select'
      /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.13.7/lib/bundler/source/rubygems.rb:332:in `api_fetchers'
      /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.13.7/lib/bundler/source/rubygems.rb:337:in `block in remote_specs'
      /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.13.7/lib/bundler/index.rb:10:in `build'
      /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.13.7/lib/bundler/source/rubygems.rb:336:in `remote_specs'
      /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.13.7/lib/bundler/source/rubygems.rb:83:in `specs'
      /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.13.7/lib/bundler/definition.rb:261:in `block (2 levels) in index'
      /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.13.7/lib/bundler/definition.rb:259:in `each'
      /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.13.7/lib/bundler/definition.rb:259:in `block in index'
      /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.13.7/lib/bundler/index.rb:10:in `build'
      /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.13.7/lib/bundler/definition.rb:256:in `index'
      /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.13.7/lib/bundler/definition.rb:250:in `resolve'
      /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.13.7/lib/bundler/definition.rb:174:in `specs'
      /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.13.7/lib/bundler/definition.rb:162:in `resolve_remotely!'
      /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.13.7/lib/bundler/installer.rb:225:in `resolve_if_need'
      /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.13.7/lib/bundler/installer.rb:78:in `run'
      /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.13.7/lib/bundler/installer.rb:24:in `install'
      /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.13.7/lib/bundler/cli/install.rb:71:in `run'
      /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.13.7/lib/bundler/cli.rb:189:in `install'
      /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.13.7/lib/bundler/cli.rb:20:in `dispatch'
      /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.13.7/lib/bundler/cli.rb:11:in `start'
      /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.13.7/exe/bundle:34:in `block in <top (required)>'
      /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.13.7/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
      /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.13.7/exe/bundle:26:in `<top (required)>'
      /usr/local/bin/bundle:22:in `load'
      /usr/local/bin/bundle:22:in `<main>'

Environment
      
  Bundler   1.13.7
  Rubygems  2.6.8
  Ruby      2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]
  GEM_HOME  /usr/local/lib/ruby/gems/2.4.0
  GEM_PATH  /usr/local/lib/ruby/gems/2.4.0:/Users/Dave/.gem/ruby/2.4.0:/usr/local/Cellar/ruby/2.4.0/lib/ruby/gems/2.4.0
  Git       2.10.1 (Apple Git-78)
--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/bundler/bundler/search?q=Permission+denied+%40+rb_file_s_rename+-+%28%2Fvar%2Ffolders%2F8j%2Fgkkhjn9j01g8r_jk_77x35gr0000gn%2FT%2Fbundler-compact-index-20170112-1336-1x8q9yx%2Fversions%2C+%2FUsers%2FDave%2F.bundle%2Fcache%2Fcompact_index%2Frubygems.org.443.29b0360b937aa4d161703e6160654e47%2Fversions%29&type=Issues

If there aren't any reports for this error yet, please create copy and paste the report template above into a new issue. Don't forget to anonymize any private data! The new issue form is located at:
https://github.com/bundler/bundler/issues/new

**Comment by colby-swandale** [comment]
Make sure that bundler has the appropriate permissions to read/write to `/Users/Dave/.bundle`.

There are [plenty of other issues](https://github.com/bundler/bundler/search?utf8=%E2%9C%93&q=Permission+denied&type=Issues) similar to this that can help resolve your issue.

**Comment by kubido** [comment]
while waiting bundle 1.14 for this fix, my solutions is to downgrade the ruby version to 2.2.0 seems the issue generated if using ruby 2.3.0+

**Comment by indirect** [comment]
@kubido you can already install 1.14 by running `gem install bundler --pre`. please try it out!

**Comment by colby-swandale** [comment]
I'm closing this for now. If you're still experiencing your original issue don't be afraid to re-open this ticket.
