### ISSUE TITLE
'bundle install' error message

### ISSUE THREAD

**Issue by 8gentile** [bundler/bundler#5325]
###-MacBook-Air:practice-problems-2 ###$ bundle install
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `/usr/local/bin/bundle install`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what happened was...

Error details

    Errno::EACCES: Permission denied - (/var/folders/46/zk3rm4015030_28wvvs8nh5c0000gn/T/bundler-compact-index-20170114-5811-1j9q1mc/versions, /Users/###/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/versions)
      /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:519:in `rename'
      /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:519:in `block in mv'
      /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1558:in `block in fu_each_src_dest'
      /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1574:in `fu_each_src_dest0'
      /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1556:in `fu_each_src_dest'
      /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:508:in `mv'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:55:in `block in update'
      /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tmpdir.rb:88:in `mktmpdir'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:29:in `update'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:65:in `update'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:56:in `update_and_parse_checksums!'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler/fetcher/compact_index.rb:67:in `available?'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler/fetcher/compact_index.rb:15:in `call'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler/fetcher/compact_index.rb:15:in `block in compact_index_request'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler/fetcher.rb:157:in `use_api'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:332:in `block in api_fetchers'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:332:in `select'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:332:in `api_fetchers'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:337:in `block in remote_specs'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler/index.rb:10:in `build'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:336:in `remote_specs'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:83:in `specs'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler/lazy_specification.rb:61:in `__materialize__'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler/spec_set.rb:91:in `block in materialize'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler/spec_set.rb:88:in `map!'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler/spec_set.rb:88:in `materialize'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler/definition.rb:174:in `specs'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler/definition.rb:162:in `resolve_remotely!'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler/installer.rb:225:in `resolve_if_need'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler/installer.rb:78:in `run'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler/installer.rb:24:in `install'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler/cli/install.rb:71:in `run'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler/cli.rb:189:in `install'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler/cli.rb:20:in `dispatch'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler/cli.rb:11:in `start'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/exe/bundle:34:in `block in <top (required)>'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/exe/bundle:26:in `<top (required)>'
      /usr/local/bin/bundle:23:in `load'
      /usr/local/bin/bundle:23:in `<main>'

Environment
      
  Bundler   1.13.6
  Rubygems  2.0.14.1
  Ruby      2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
  GEM_HOME  /Library/Ruby/Gems/2.0.0
  GEM_PATH  /Library/Ruby/Gems/2.0.0:/Users/###/.gem/ruby/2.0.0:/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/gems/2.0.0
  Git       2.11.0
--- TEMPLATE END ----------------------------------------------------------------

**Comment by NafaaBout** [comment]
Same here
```
Using rake 10.5.0
Using i18n 0.7.0
Using json 1.8.6
Using minitest 5.10.1
Using thread_safe 0.3.5
Using builder 3.2.3
Using erubis 2.7.0
Using mini_portile2 2.1.0
Using rack 1.6.5
Using mime-types 2.99.3
Using arel 6.0.4
Using execjs 2.7.0
Using awesome_print 1.7.0
Using bundler 1.13.6
Using thor 0.18.1
Using concurrent-ruby 1.0.4
Using sass 3.4.23
Using coderay 1.1.1
Using coffee-script-source 1.10.0
Using colorize 0.8.1
Using connection_pool 2.2.0
Using unf_ext 0.0.7.2
Using dotenv 2.1.1
Using excon 0.51.0
Using multipart-post 2.0.0
Using hashie 3.4.6
Using high_voltage 2.4.0
Using multi_json 1.12.1
Using jwt 1.5.1
Using net-http-digest_auth 1.4
Using net-http-persistent 2.9.4
Using ntlm-http 0.1.1
Using webrobots 0.1.2
Using method_source 0.8.2
Using multi_xml 0.5.5
Using netrc 0.11.0
Using newrelic_rpm 3.16.0.318
Using pg 0.18.4
Using slop 3.6.0
Using puma 3.4.0
Using redis 3.3.0
Using tilt 2.0.5
Using turbolinks-source 5.0.0
Using tzinfo 1.2.2
Installing nokogiri 1.7.0.1 with native extensions
Using rack-test 0.6.3
Using rack-protection 1.5.3
Using mail 2.6.4
Using autoprefixer-rails 6.3.7
Using uglifier 3.0.0
Using sprockets 3.7.1
Using coffee-script 2.4.1
Using unf 0.1.4
Using jeff 1.5.1
Using faraday 0.9.2
Using omniauth 1.3.2
Using pry 0.10.3
Using turbolinks 5.0.0
Using activesupport 4.2.6
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `/home/bytestand/.rvm/gems/ruby-2.2.2@bytestand/bin/bundle install --without test:development`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what happened was...


Error details

    SignalException: SIGTERM
      /home/bytestand/.rvm/gems/ruby-2.2.2@bytestand/gems/bundler-1.13.6/lib/bundler/worker.rb:45:in `pop'
      /home/bytestand/.rvm/gems/ruby-2.2.2@bytestand/gems/bundler-1.13.6/lib/bundler/worker.rb:45:in `deq'
      /home/bytestand/.rvm/gems/ruby-2.2.2@bytestand/gems/bundler-1.13.6/lib/bundler/installer/parallel_installer.rb:121:in `process_specs'
      /home/bytestand/.rvm/gems/ruby-2.2.2@bytestand/gems/bundler-1.13.6/lib/bundler/installer/parallel_installer.rb:92:in `call'
      /home/bytestand/.rvm/gems/ruby-2.2.2@bytestand/gems/bundler-1.13.6/lib/bundler/installer/parallel_installer.rb:74:in `call'
      /home/bytestand/.rvm/gems/ruby-2.2.2@bytestand/gems/bundler-1.13.6/lib/bundler/installer.rb:198:in `install_in_parallel'
      /home/bytestand/.rvm/gems/ruby-2.2.2@bytestand/gems/bundler-1.13.6/lib/bundler/installer.rb:165:in `install'
      /home/bytestand/.rvm/gems/ruby-2.2.2@bytestand/gems/bundler-1.13.6/lib/bundler/installer.rb:80:in `run'
      /home/bytestand/.rvm/gems/ruby-2.2.2@bytestand/gems/bundler-1.13.6/lib/bundler/installer.rb:24:in `install'
      /home/bytestand/.rvm/gems/ruby-2.2.2@bytestand/gems/bundler-1.13.6/lib/bundler/cli/install.rb:71:in `run'
      /home/bytestand/.rvm/gems/ruby-2.2.2@bytestand/gems/bundler-1.13.6/lib/bundler/cli.rb:189:in `install'
      /home/bytestand/.rvm/gems/ruby-2.2.2@bytestand/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /home/bytestand/.rvm/gems/ruby-2.2.2@bytestand/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /home/bytestand/.rvm/gems/ruby-2.2.2@bytestand/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /home/bytestand/.rvm/gems/ruby-2.2.2@bytestand/gems/bundler-1.13.6/lib/bundler/cli.rb:20:in `dispatch'
      /home/bytestand/.rvm/gems/ruby-2.2.2@bytestand/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /home/bytestand/.rvm/gems/ruby-2.2.2@bytestand/gems/bundler-1.13.6/lib/bundler/cli.rb:11:in `start'
      /home/bytestand/.rvm/gems/ruby-2.2.2@bytestand/gems/bundler-1.13.6/exe/bundle:34:in `block in <top (required)>'
      /home/bytestand/.rvm/gems/ruby-2.2.2@bytestand/gems/bundler-1.13.6/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
      /home/bytestand/.rvm/gems/ruby-2.2.2@bytestand/gems/bundler-1.13.6/exe/bundle:26:in `<top (required)>'
      /home/bytestand/.rvm/gems/ruby-2.2.2@bytestand/bin/bundle:23:in `load'
      /home/bytestand/.rvm/gems/ruby-2.2.2@bytestand/bin/bundle:23:in `<main>'
      /home/bytestand/.rvm/gems/ruby-2.2.2@bytestand/bin/ruby_executable_hooks:15:in `eval'
      /home/bytestand/.rvm/gems/ruby-2.2.2@bytestand/bin/ruby_executable_hooks:15:in `<main>'

Environment
      
  Bundler   1.13.6
  Rubygems  2.4.8
  Ruby      2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux]
  GEM_HOME  /home/bytestand/bytestand/vendor/bundle/ruby/2.2.0
  GEM_PATH  
  RVM       1.27.0 (latest)
  Git       1.9.1
      
      Bundler settings
      
  without
    Set for your local app (/home/bytestand/bytestand/.bundle/config): "test:development"
  frozen
    Set for your local app (/home/bytestand/bytestand/.bundle/config): "1"
  path
    Set for your local app (/home/bytestand/bytestand/.bundle/config): "vendor/bundle"
  disable_shared_gems
    Set for your local app (/home/bytestand/bytestand/.bundle/config): true
--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/bundler/bundler/search?q=SIGTERM&type=Issues

If there aren't any reports for this error yet, please create copy and paste the report template above into a new issue. Don't forget to anonymize any private data! The new issue form is located at:
https://github.com/bundler/bundler/issues/new
```

**Comment by colby-swandale** [comment]
@8gentile Check to make sure that `/Users/###/.bundle` has the correct permissions to read/write to. It's recommended to update to the latest version of Bundler to help resolve this issue.

**Comment by colby-swandale** [comment]
Closing this for now, if you're still experiencing your problem don't be afraid to re-open this issue.
