### ISSUE TITLE
problem metasploit and bundler not correctly detected

### ISSUE THREAD

**Issue by lacroutelacroute** [bundler/bundler#5353]
hello

in my computer
i have many bundler installed
gem list bundler

*** LOCAL GEMS ***

bundler (1.14.1, 1.14.0, 1.13.7, 1.13.6, 1.12.0)

metasploit required bundler 1.13.7
for correct functionnality

but
after install from scratch

only bundler 1.13.6 is detected
:/opt/msf-devel/metasploit-framework# rake
WARN: Unresolved specs during Gem::Specification.reset:
      minitest (~> 5.1)
      nokogiri (>= 1.5.9)
      rails-dom-testing (>= 1.0.5, ~> 1.0)
      builder (~> 3.1)
      rake (>= 0.8.7)
      thor (< 2.0, >= 0.18.1)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
[*] Metasploit requires the Bundler gem to be installed
    $ gem install bundler

please help me

**Comment by segiddins** [comment]
@lacroutelacroute can you elaborate a bit on why you think this is a bundler bug? Seems like it might be an issue with metasploit to me

**Comment by lacroutelacroute** [comment]
I do not know at all if this error comes from metasploit or bundler 
is you for you to see

**Comment by segiddins** [comment]
Can you reproduce whatever issue you're seeing without using metasploit?

**Comment by lacroutelacroute** [comment]
no
