### ISSUE TITLE
bundler 1.14 failed to resolve dependencies correctly

### ISSUE THREAD

**Issue by datanoise** [bundler/bundler#5362]
The following Gemfile is resolved correctly by bundler 1.13.x but fails in 1.14.x:

https://gist.github.com/datanoise/a5552e9accfa62e318ce8e6fc0370cb8

The error message doesn't make sense to me:

```
Bundler could not find compatible versions for gem "ruby":
  In Gemfile:
    ruby (>= 1.9.2)

    ruby

    ruby x86-mingw32

    listen (~> 3.0.5) x86-mingw32 was resolved to 3.0.8, which depends on
      rb-inotify (>= 0.9.7, ~> 0.9) was resolved to 0.9.7, which depends on
        ffi (>= 0.5.0) was resolved to 1.9.17, which depends on
          ruby (< 2.5) x86-mingw32

    tzinfo-data x86-mingw32 was resolved to 1.2016.10, which depends on
      ruby (>= 1.8.7) x86-mingw32

    wdm (>= 0.1.0) x86-mingw32 was resolved to 0.1.1, which depends on
      ruby (>= 1.9.2) x86-mingw32

Could not find gem 'ruby (< 2.4) x86-mingw32', which is required by gem 'ffi (>= 0.5.0)', in any of the sources.
```

**Comment by segiddins** [comment]
What's the output of `bundle env`?

**Comment by datanoise** [comment]
`bundle env`:
https://gist.github.com/datanoise/ea2069a2fa8773a4782c1d20594d805b

**Comment by segiddins** [comment]
thanks, this looks like a bug to me (notice it says `ruby (< 2.4)` instead of `< 2.5`

**Comment by segiddins** [comment]
Fix in https://github.com/bundler/bundler/issues/5359 also seems to fix this issue

**Comment by segiddins** [comment]
https://github.com/CocoaPods/Molinillo/pull/59 should fix this

**Comment by burnettk** [comment]
i think the title should say "bundler 1.14" not "bundler 1.4"

**Comment by datanoise** [comment]
yes. my bad. fixed
