### ISSUE TITLE
Facing errors while installing plugin

### ISSUE THREAD

**Issue by mavericksio** [bundler/bundler#5365]
Hi,

I am new to Redmine, and trying to setup Plugins on my own. While installing a plugin I am facing issues and following are the details of error message.

Please take a look at it and help me out.

Thanks in advance.

--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `/opt/bitnami/ruby/bin/bundle config disable_multisource true`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?
  Instead, what actually happened was...
Error details
    Errno::EACCES: Permission denied @ rb_sysopen - /opt/bitnami/ruby/.bundler/config
      /opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/bundler-1.10.4/lib/bundler/settings.rb:210:in `initialize'
      /opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/bundler-1.10.4/lib/bundler/settings.rb:210:in `open'
      /opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/bundler-1.10.4/lib/bundler/settings.rb:210:in `set_key'
      /opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/bundler-1.10.4/lib/bundler/settings.rb:41:in `set_global'
      /opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/bundler-1.10.4/lib/bundler/cli/config.rb:79:in `run'
      /opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/bundler-1.10.4/lib/bundler/cli.rb:296:in `config'
      /opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/bundler-1.10.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/bundler-1.10.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/bundler-1.10.4/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/bundler-1.10.4/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/bundler-1.10.4/lib/bundler/cli.rb:10:in `start'
      /opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/bundler-1.10.4/bin/bundle:20:in `block in <top (required)>'
      /opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/bundler-1.10.4/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
      /opt/bitnami/ruby/lib/ruby/gems/2.1.0/gems/bundler-1.10.4/bin/bundle:18:in `<top (required)>'
      /opt/bitnami/ruby/bin/bundle:23:in `load'
      /opt/bitnami/ruby/bin/bundle:23:in `<main>'

Environment
    Bundler   1.10.4
    Rubygems  2.2.5
    Ruby      2.1.10p492 (2016-04-01 revision 54464) [x86_64-linux]
    GEM_HOME  /opt/bitnami/ruby/lib/ruby/gems/2.1.0
    Git       2.7.4

Bundler settings
    build.nokogiri
      Set for the current user (/opt/bitnami/ruby/.bundler/config): "--with-opt-dir=/opt/bitnami/common "
    build.charlock_holmes
      Set for the current user (/opt/bitnami/ruby/.bundler/config): "--with-icu-dir=/opt/bitnami/common --with-icu-lib=/opt/bitnami/common/lib "
    disable_multisource
      Set for the current user (/opt/bitnami/ruby/.bundler/config): "true"
    bin
      Set for your local app (/opt/bitnami/apps/redmine/htdocs/.bundle/config): "bin"
    no_prune
      Set for your local app (/opt/bitnami/apps/redmine/htdocs/.bundle/config): "true"
    without
      Set for your local app (/opt/bitnami/apps/redmine/htdocs/.bundle/config): "development:test:sqlite"
    config
      Set via BUNDLE_CONFIG: "/opt/bitnami/ruby/.bundler/config"
--- TEMPLATE END ----------------------------------------------------------------

**Comment by olleolleolle** [comment]
@mavericksio Is the `/opt/bitnami/ruby/` folder writable by the user that executes the command?

A side-note on the versions used.

- Bundler 1.10.4, you could upgrade to a slightly newer version, like `gem install bundler -v'1.13.7'`
- Rubygems 2.2.5, you could upgrade to latest, like `gem update --system`

**Comment by mavericksio** [comment]
I executed the commands using sudo.

Now, I am receiving the following error:
[!] There was an error parsing `Gemfile`: 
[!] There was an error parsing `Gemfile`: You cannot specify the same gem twice with different version requirements.
You specified: rubyzip (< 1.0.0) and rubyzip (>= 1.0.0). Bundler cannot continue.
 #  from /opt/bitnami/apps/redmine/htdocs/plugins/usability/Gemfile:1
 #  -------------------------------------------
 >  gem 'rubyzip', '>= 1.0.0'
 #  -------------------------------------------
. Bundler cannot continue.
 #  from /opt/bitnami/apps/redmine/htdocs/Gemfile:117
 #  -------------------------------------------
 #  Dir.glob File.expand_path("../plugins/*/{Gemfile,PluginGemfile}", __FILE__) do |file|
 >    eval_gemfile file
 #  end
 #  -------------------------------------------

**Comment by mavericksio** [comment]
I reinstalled everything as that was much quicker for me.. Thank you for your help.
