### ISSUE TITLE
An error occurred while installing rainbow (2.2.1)

### ISSUE THREAD

**Issue by segantii-alex-falkowski** [bundler/bundler#5370]
Using circleci:

```
gem install bundler
ruby-2.3.3 - #gemset created /opt/circleci/.rvm/gems/ruby-2.3.3@easing-it
ruby-2.3.3 - #generating easing-it
Fetching: bundler-1.14.3.gem ( 78%)Fetching: bundler-1.14.3.gem (100%)
Bundler and RubyGems.org are free for anyone to use, but maintaining them costs more than $25,000 USD every month. Help us cover those costs so that we can keep the gem ecosystem free for everyone: https://ruby.to/support-bundler
Successfully installed bundler-1.14.3
1 gem installed
```

We get the following output:

```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    can't modify frozen String

Gem files will remain installed in
/home/ubuntu/easing-it/vendor/bundle/ruby/2.3.0/gems/rainbow-2.2.1 for
inspection.
Results logged to
/home/ubuntu/easing-it/vendor/bundle/ruby/2.3.0/extensions/x86_64-linux/2.3.0-static/rainbow-2.2.1/gem_make.out

An error occurred while installing rainbow (2.2.1), and Bundler cannot
continue.
Make sure that `gem install rainbow -v '2.2.1'` succeeds before bundling.

bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3  returned exit code 5

Action failed: bundle install
```

This does not happen when we:

```
gem install bundler --version 1.13.7
```

**Comment by colby-swandale** [comment]
Your issue is similar to #5357, attach the output of `bundle env` and make sure that `rubygems` is up to date.

**Comment by segiddins** [comment]
RubyGems 2.6.10 contains a fix for this issue, `gem update --system`.

**Comment by segantii-alex-falkowski** [comment]
Thank's did the trick. Appreciate it :)

**Comment by rachel-carvalho** [comment]
@segantii-alex-falkowski Sorry for the unrelated/noob question, but how did you get CircleCI to actually update RubyGems? I tried to add `gem update --system` to `pre:`, but it didn't work :/

**Comment by olleolleolle** [comment]
@rachel-carvalho  

Here's an unrelated guess at how to configure CircleCI. (Perhaps there's a better community resource elsewhere to get CircleCI help? [CircleCI's docs GitHub repository, perhaps?](https://github.com/circleci/circleci-docs))

```yaml
dependencies:
  pre:
    - gem update --system
```

[Source](https://circleci.com/docs/bundler-latest/)

**Comment by rachel-carvalho** [comment]
@olleolleolle that's exactly what I tried and it doesn't work because it's too soon: `pre` happens before installing ruby. I ended up freezing the offending gem (`rainbow`) until we update to ruby 2.4, which seems to solve the problem.

**Comment by jaysonesmith** [comment]
I have a pretty simple circle file so I've successfully done it with:

```
dependencies:
  override:
    - gem update --system
    - bundle install
```

Thank you for the information!

**Comment by kev112** [comment]
I updated rubygems but it still doesn't work

**Comment by colby-swandale** [comment]
@kev112 please follow [ISSUES.md](https://github.com/bundler/bundler/blob/master/doc/contributing/ISSUES.md) and open a new issue.
