### ISSUE TITLE
bundle show functionality

### ISSUE THREAD

**Issue by colby-swandale** [bundler/bundler#5375]
I'm not sure if this is intended functionality but i think there are a couple of bugs/unintended functionality in the `bundle show` command.

### Outdated Status
Example:
```
source "https://rubygems.org"

gem 'rack', '~> 1.6.5'
```
```
GEM
  remote: https://rubygems.org/
  specs:
    rack (1.6.5)

PLATFORMS
  ruby

DEPENDENCIES
  rack (~> 1.6.5)

BUNDLED WITH
   1.14.0
```
The outdated status continues to remain as "Up to date" even though [Rack 2.0.1](https://rubygems.org/gems/rack) exists 
```
* rack (1.6.5)
	Summary:  a modular Ruby webserver interface
	Homepage: http://rack.github.io/
	Status:   Up to date
```

### Bundle show updates the lockfile
```
source "https://rubygems.org"

gem 'rack'
```
```
GEM
  remote: https://rubygems.org/
  specs:
    rack (1.6.5)

PLATFORMS
  ruby

DEPENDENCIES
  rack

BUNDLED WITH
   1.14.0
```
```
› bundle show --outdated
Fetching remote specs for outdated check...

Gems included by the bundle:
* bundler (1.14.0)
	Summary:  The best way to manage your application's dependencies
	Homepage: http://bundler.io
	Status:   Up to date
* rack (2.0.1)
	Summary:  a modular Ruby webserver interface
	Homepage: http://rack.github.io/
	Status:   Up to date
› cat Gemfile.lock
GEM
  remote: https://rubygems.org/
  specs:
    rack (2.0.1)

PLATFORMS
  ruby

DEPENDENCIES
  rack

BUNDLED WITH
   1.14.0
```
When i run `bundle show --outdated` the version of rack is updated to the latest version (2.0.1 at the time of writing). I think this is quiet dangerous behavior for a number of reasons:
* The documentation for `--outdated` mentions nothing about updating gems. For reference this is the current documentation for `--outdated`: "Show verbose output including whether gems are outdated."
* I was not notified by Blunder that gems were being updated
* As the user i was not expecting to update any gems, that's what `bundle update` is for

**Comment by segiddins** [comment]
The latter is definitely a major bug. The first thing might not be since the version isn't compatible with the dependency in the gemfile.

**Comment by colby-swandale** [comment]
I'm going to close this as the latter issue has been fixed and the first one seems like it's working as intended.
