### ISSUE TITLE
Bundler 1.14 is no longer correctly producing compatible version output for Ruby 1.8.7

### ISSUE THREAD

**Issue by JonRowe** [bundler/bundler#5381]
On Ruby 1.8.7 Bundler 1.14 no longer produces the correct "compatible version" output. Producing this:

```
Bundler could not find compatible versions for gem "ruby":
  In Gemfile:
    ruby
    rails (~> 3.2.17) was resolved to 3.2.22.5, which depends on
      ruby (>= 1.8.7)
    rails (~> 3.2.17) was resolved to 3.2.22.5, which depends on
      ruby (>= 1.8.7)
    rails (~> 3.2.17) was resolved to 3.2.22.5, which depends on
      ruby (>= 1.8.7)
    rails (~> 3.2.17) was resolved to 3.2.22.5, which depends on
      ruby (>= 1.8.7)
    rails (~> 3.2.17) was resolved to 3.2.22.5, which depends on
      ruby (>= 1.8.7)
    rails (~> 3.2.17) was resolved to 3.2.22.5, which depends on
      ruby (>= 1.8.7)
    rails (~> 3.2.17) was resolved to 3.2.22.5, which depends on
      ruby (>= 1.8.7)
    rails (~> 3.2.17) was resolved to 3.2.22.5, which depends on
      ruby (>= 1.8.7)
    rails (~> 3.2.17) was resolved to 3.2.22.5, which depends on
      ruby (>= 1.8.7)
    rails (~> 3.2.17) was resolved to 3.2.22.5, which depends on
      ruby (>= 1.8.7)
    rails (~> 3.2.17) was resolved to 3.2.22.5, which depends on
      ruby (>= 1.8.7)
    rails (~> 3.2.17) was resolved to 3.2.22.5, which depends on
      ruby (>= 1.8.7)
Could not find gem 'ruby (>= 1.9.2)', which is required by gem 'rails (~>
3.2.17)', in any of the sources.
```

When the actual gem at fault was `rest-client` a dependency of `relish` which required 1.9.2, this makes it very hard to debug what dependency is conflicting. Switching back to `1.13.x` solved this and correctly produced:

`rest-client-1.8.0 requires ruby version >= 1.9.2, which is incompatible with the current version, ruby 1.8.7p374`

This can be seen on the `rspec-rails` builds for 1.8.7, and the inclusion of `rails` is not significant, (I've seen it say rails, rake, diff-lcs, amongst others). (An example build is here https://travis-ci.org/rspec/rspec-rails/jobs/196450105)

**Comment by segiddins** [comment]
Please share the information requested in https://github.com/bundler/bundler/blob/master/doc/contributing/ISSUES.md

**Comment by JonRowe** [comment]
All that information is provided via the Travis link and associated commit

**Comment by segiddins** [comment]
Still, please provide the information in this issue so those looking to help out with it have all the information in one place

**Comment by JonRowe** [comment]
> What you're trying to accomplish
Install gems on 1.8.7.

> The command you ran
`bundle install`

> What you expected to happen
The command to install gems or produce an accurate report of broken dependencies.

> What actually happened
The command produced an incorrect report for broken dependencies.

> The exception backtrace(s), if any
```
Bundler could not find compatible versions for gem "ruby":
  In Gemfile:
    ruby
    rails (~> 3.2.17) was resolved to 3.2.22.5, which depends on
      ruby (>= 1.8.7)
    rails (~> 3.2.17) was resolved to 3.2.22.5, which depends on
      ruby (>= 1.8.7)
    rails (~> 3.2.17) was resolved to 3.2.22.5, which depends on
      ruby (>= 1.8.7)
    rails (~> 3.2.17) was resolved to 3.2.22.5, which depends on
      ruby (>= 1.8.7)
    rails (~> 3.2.17) was resolved to 3.2.22.5, which depends on
      ruby (>= 1.8.7)
    rails (~> 3.2.17) was resolved to 3.2.22.5, which depends on
      ruby (>= 1.8.7)
    rails (~> 3.2.17) was resolved to 3.2.22.5, which depends on
      ruby (>= 1.8.7)
    rails (~> 3.2.17) was resolved to 3.2.22.5, which depends on
      ruby (>= 1.8.7)
    rails (~> 3.2.17) was resolved to 3.2.22.5, which depends on
      ruby (>= 1.8.7)
    rails (~> 3.2.17) was resolved to 3.2.22.5, which depends on
      ruby (>= 1.8.7)
    rails (~> 3.2.17) was resolved to 3.2.22.5, which depends on
      ruby (>= 1.8.7)
    rails (~> 3.2.17) was resolved to 3.2.22.5, which depends on
      ruby (>= 1.8.7)
Could not find gem 'ruby (>= 1.9.2)', which is required by gem 'rails (~>
3.2.17)', in any of the sources.
```

> Your Gemfile
https://github.com/rspec/rspec-rails/blob/0e83a478604cbca4337669e55c626e690803e5af/Gemfile

> Your Gemfile.lock
None.

> Your Bundler configuration settings (run bundle config)
```
Settings are listed in order of priority. The top value will be used.
build.nokogiri
Set for the current user (/Users/jon/.bundle/config): "--use-system-libraries"

bin
Set for your local app (/Users/jon/Code/Gems/rspec-rails/.bundle/config): "bin"
```

> What version of bundler you are using (run bundle -v)
`Bundler version 1.14.3`

>What version of Ruby you are using (run ruby -v)
`ruby 1.8.7 (2012-10-12 patchlevel 371) [x86_64-linux]`

>What version of Rubygems you are using (run gem -v)
`2.0.17`

> Whether you are using RVM, and if so what version (run rvm -v)
`rvm 1.26.10 (latest-minor) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]`

> Whether you have the rubygems-bundler gem, which can break gem executables (run gem list rubygems-bundler)
No

> Whether you have the open_gem gem, which can cause rake activation conflicts (run gem list open_gem)
No

**Comment by segiddins** [comment]
I get different errors using bundler 1.13.x, 1.14.x, and 1.15.x, none of which are the error you've reported

**Comment by segiddins** [comment]
Closing due to lack of followup
