### ISSUE TITLE
Docs guides links broken by the version number

### ISSUE THREAD

**Issue by oinak** [bundler/bundler#5394]
Linked from docs page but not working:
http://bundler.io/v1.14/guides/creating_gem.html

Working but not linked:
http://bundler.io/v1.13/guides/creating_gem.html

**Comment by Shekharrajak** [comment]
There should be same content in v1.14 ?

**Comment by oinak** [comment]
I think there should be _some_ content, or not links to them from http://bundler.io/docs.html

**Comment by segiddins** [comment]
This is a bug with the website, not the bundler CLI

**Comment by segiddins** [comment]
This will be fixed by https://github.com/bundler/bundler-site/pull/292
