### ISSUE TITLE
Allow bundle-update to only update the lock file without updating gems

### ISSUE THREAD

**Issue by sschuberth** [bundler/bundler#5395]
It would be nice if there was an option to `update` to only update the dependencies in the lock file, but not actually update / install any gems. One use case for this is mentioned at [StackOverflow](http://stackoverflow.com/q/26335777/1127485). Another use case is:

I want to create a lock file that is valid for different platforms. As `PLATFORMS` are listed as part of the lock file, e.g. `x64-mingw32` is added when running `install` under Windows. If I want the lock file to work on Linux, too, I need to run `update` on some Linux machine to add its platform identifier to the lock file. But I don't want to "pollute" that Linux machine with installing gems.

**Comment by sschuberth** [comment]
Meanwhile, I learned about `lock --add-platform`, but that's a bit inconvenient to use as it requires to explicitly specify the platform instead of defaulting to the local one.

**Comment by segiddins** [comment]
`bundle lock --update`
