### ISSUE TITLE
Issue with Jruby ........... used "jruby -S bundle install"----------- got the below error

### ISSUE THREAD

**Issue by divyaravva** [bundler/bundler#5402]
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `/usr/local/rvm/gems/ruby-1.9.3-p362@xyz/bin/bundle install`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what happened was...

Error details

    URI::InvalidURIError: bad URI(is not URI?): http://{your_user_id}:{your_password}@proxy-host:proxy-port/
      /usr/share/jruby/lib/ruby/1.9/uri/common.rb:176:in `split'
      /usr/share/jruby/lib/ruby/1.9/uri/common.rb:210:in `parse'
      /usr/share/jruby/lib/ruby/1.9/uri/common.rb:747:in `parse'
      /usr/share/jruby/lib/ruby/1.9/uri/common.rb:994:in `URI'
      /usr/local/rvm/gems/ruby-1.9.3-p362@xyz/gems/bundler-1.13.6/lib/bundler/vendor/net/http/persistent.rb:908:in `proxy_from_env'
      /usr/local/rvm/gems/ruby-1.9.3-p362@xyz/gems/bundler-1.13.6/lib/bundler/vendor/net/http/persistent.rb:858:in `proxy='
      /usr/local/rvm/gems/ruby-1.9.3-p362@xyz/gems/bundler-1.13.6/lib/bundler/vendor/net/http/persistent.rb:528:in `initialize'
      /usr/local/rvm/gems/ruby-1.9.3-p362@xyz/gems/bundler-1.13.6/lib/bundler/fetcher.rb:240:in `connection'
      /usr/local/rvm/gems/ruby-1.9.3-p362@xyz/gems/bundler-1.13.6/lib/bundler/fetcher.rb:84:in `initialize'
      /usr/local/rvm/gems/ruby-1.9.3-p362@xyz/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:234:in `fetchers'
      org/jruby/RubyArray.java:2414:in `map'
      /usr/local/rvm/gems/ruby-1.9.3-p362@xyz/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:232:in `fetchers'
      /usr/local/rvm/gems/ruby-1.9.3-p362@xyz/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:337:in `remote_specs'
      /usr/local/rvm/gems/ruby-1.9.3-p362@xyz/gems/bundler-1.13.6/lib/bundler/index.rb:10:in `build'
      /usr/local/rvm/gems/ruby-1.9.3-p362@xyz/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:336:in `remote_specs'
      /usr/local/rvm/gems/ruby-1.9.3-p362@xyz/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:83:in `specs'
      /usr/local/rvm/gems/ruby-1.9.3-p362@xyz/gems/bundler-1.13.6/lib/bundler/definition.rb:261:in `index'
      org/jruby/RubyArray.java:1613:in `each'
      /usr/local/rvm/gems/ruby-1.9.3-p362@xyz/gems/bundler-1.13.6/lib/bundler/definition.rb:259:in `index'
      /usr/local/rvm/gems/ruby-1.9.3-p362@xyz/gems/bundler-1.13.6/lib/bundler/index.rb:10:in `build'
      /usr/local/rvm/gems/ruby-1.9.3-p362@xyz/gems/bundler-1.13.6/lib/bundler/definition.rb:256:in `index'
      /usr/local/rvm/gems/ruby-1.9.3-p362@xyz/gems/bundler-1.13.6/lib/bundler/definition.rb:250:in `resolve'
      /usr/local/rvm/gems/ruby-1.9.3-p362@xyz/gems/bundler-1.13.6/lib/bundler/definition.rb:174:in `specs'
      /usr/local/rvm/gems/ruby-1.9.3-p362@xyz/gems/bundler-1.13.6/lib/bundler/definition.rb:162:in `resolve_remotely!'
      /usr/local/rvm/gems/ruby-1.9.3-p362@xyz/gems/bundler-1.13.6/lib/bundler/installer.rb:225:in `resolve_if_need'
      /usr/local/rvm/gems/ruby-1.9.3-p362@xyz/gems/bundler-1.13.6/lib/bundler/installer.rb:78:in `run'
      /usr/local/rvm/gems/ruby-1.9.3-p362@xyz/gems/bundler-1.13.6/lib/bundler/installer.rb:24:in `install'
      /usr/local/rvm/gems/ruby-1.9.3-p362@xyz/gems/bundler-1.13.6/lib/bundler/cli/install.rb:71:in `run'
      /usr/local/rvm/gems/ruby-1.9.3-p362@xyz/gems/bundler-1.13.6/lib/bundler/cli.rb:189:in `install'
      /usr/local/rvm/gems/ruby-1.9.3-p362@xyz/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /usr/local/rvm/gems/ruby-1.9.3-p362@xyz/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /usr/local/rvm/gems/ruby-1.9.3-p362@xyz/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /usr/local/rvm/gems/ruby-1.9.3-p362@xyz/gems/bundler-1.13.6/lib/bundler/cli.rb:20:in `dispatch'
      /usr/local/rvm/gems/ruby-1.9.3-p362@xyz/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /usr/local/rvm/gems/ruby-1.9.3-p362@xyz/gems/bundler-1.13.6/lib/bundler/cli.rb:11:in `start'
      /usr/local/rvm/gems/ruby-1.9.3-p362@xyz/gems/bundler-1.13.6/exe/bundle:34:in `(root)'
      /usr/local/rvm/gems/ruby-1.9.3-p362@xyz/gems/bundler-1.13.6/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
      /usr/local/rvm/gems/ruby-1.9.3-p362@xyz/gems/bundler-1.13.6/exe/bundle:26:in `(root)'
      org/jruby/RubyKernel.java:1059:in `load'
      /usr/local/rvm/gems/ruby-1.9.3-p362@xyz/bin/bundle:23:in `(root)'

Environment
      
  Bundler   1.13.6
  Rubygems  2.4.8
  Ruby      1.9.3p551 (2015-10-23 revision 48406) [java]
  GEM_HOME  /usr/local/rvm/gems/ruby-1.9.3-p362@xyz
  GEM_PATH  /usr/local/rvm/gems/ruby-1.9.3-p362@xyz:/usr/local/rvm/gems/ruby-1.9.3-p362@global
  RVM       1.27.0 (latest)
  Git       2.7.4
  rubygems-bundler (1.4.4)
--- TEMPLATE END ----------------------------------------------------------------

**Comment by olleolleolle** [comment]
Hello!

Here are some diagnostic questions for you.

Does your shell environment variable `$HTTP_PROXY` have those proxy details in them? Something akin to `http://{your_user_id}:{your_password}@proxy-host:proxy-port/`? (Or was that you who redacted the report page for privacy?)

Can you print the HTTP_PROXY env variable with `echo $HTTP_PROXY` in a shell where you suffered this error?

**Comment by colby-swandale** [comment]
ping @divyaravva 

Are you still experiencing your reported issue?

**Comment by colby-swandale** [comment]
I'm closing this for now. If you're still experiencing your original issue don't be afraid to re-open this ticket.
