### ISSUE TITLE
Run bundler within Docker

### ISSUE THREAD

**Issue by j4zzcat** [bundler/bundler#5404]
Add support for Dockerizing. This feature will allow Bundler to launch itself within existing or auto-generated docker image. For example,  `bundler exec --docker testbed spec` will launch the specified docker image and run the command within it, i.e. `docker run --rm -it -v $(pwd):/app testbed /bin/bash -c "bundler exec rspec"` .

**Comment by colby-swandale** [comment]
i can't speak for the core team but this sounds very out of scope of Bundler and not something they would want to support.

**Comment by Zorbash** [comment]
I think this needs the [feature-request](https://github.com/bundler/bundler/labels/type%3A%20feature-request) label.

**Comment by MrOutis** [comment]
you can create a workaround with bash.
```bash
#!/usr/bin/env bash

in_docker() {
  docker-compose \
    --file ${PWD}/docker-compose.yml \
    --file ${PWD}/docker-compose.override.yml \
    ${@}
}

execute() {
  in_docker exec web bundle ${@}
}

run() {
  in_docker run --rm web bundle ${@}
}

errlog=~/bin/shims/.stderr.log

execute ${@} 2> >(tee ${errlog} >&2)
grep 'No container found' ${errlog} > /dev/null \
  && echo "Lifting up and running ${@}..." \
  && run ${@}
```

**Comment by mcmire** [comment]
I agree that this seems out of scope for Bundler. I've found that Docker Compose and binstubs works pretty well for any situation involving Docker and Bundler. @MrOutis's solution seems like a good one, too.

**Comment by colby-swandale** [comment]
Thanks for making a suggestion on improving bundler. Unfortunately we're not looking to add docker support into Bundler. I suggest using the existing docker toolchain available to help run bundler inside docker.
