### ISSUE TITLE
issues when trying to install rake

### ISSUE THREAD

**Issue by Rupalihadke** [bundler/bundler#5407]
## Environment

```
Bundler   1.14.3
Rubygems  2.5.1
Ruby      2.3.0p0 (2015-12-25 revision 53290) [i686-linux]
GEM_HOME  /home/rupali/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0
GEM_PATH  /home/rupali/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0:/home/rupali/.gem/ruby/2.3.0
Git       2.7.4
Platform  x86-linux
OpenSSL   OpenSSL 1.0.2g  1 Mar 2016
```
```

--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

**Comment by hmistry** [comment]
@Rupalihadke please post the entire Error Report template with the error backtrace, gemfile, and questions answered so we can try to reproduce the error and investigate what's going on. See the [ISSUES guide](https://github.com/bundler/bundler/blob/master/doc/contributing/ISSUES.md) for more info.

**Comment by colby-swandale** [comment]
ping @Rupalihadke

**Comment by colby-swandale** [comment]
I'm closing this for now. If you're still experiencing your original issue don't be afraid to re-open this ticket.
