### ISSUE TITLE
A different version of a gem runs in production than in development

### ISSUE THREAD

**Issue by betesh** [bundler/bundler#5419]
I ran into an issue where the json gem was a different version in production then in development.

Here's a simple example to demonstrate how this happened.

    $ cat Gemfile
    source 'https://rubygems.org'

    gem 'jwt'

    group :test do
      gem 'simplecov'
    end

    $ cat Gemfile.lock 
    GEM
      remote: https://rubygems.org/
      specs:
        docile (1.1.5)
        json (2.0.3)
        jwt (1.5.6)
        simplecov (0.13.0)
          docile (~> 1.1.0)
          json (>= 1.8, < 3)
          simplecov-html (~> 0.10.0)
        simplecov-html (0.10.0)

    PLATFORMS
      ruby

    DEPENDENCIES
      jwt
      simplecov

    BUNDLED WITH
       1.13.7

Since the json gem is part of a standard Ruby installation, jwt is able to use it without listing it as a dependency.  `Bundler.setup` doesn't prevent jwt code from using `require 'json'` without it in the Gemfile.

However, it will use whatever version comes with Ruby (json 1.8.7 if you're using Ruby 2.3.0) unless json is listed in Gemfile.lock.  In the example above, json is in Gemfile.lock for test but not for production.  This is very dangerous!  My tests all pass, but the same code does unexpected things in production.

To be fair, one could argue that this is a bug in jwt, not in bundler.  However, it's a very easy mistake for a gem developer to make, and jwt is not the only one in my Gemfile guilty of this.  Other gems with the same issue include pg, mime-types, rack, graphql, aws-sdk-core, and just about every component of rails.  So even if I were to open an issue on each of these projects, the list would keep on coming since it's such an easy mistake to make.

I propose that bundler should mitigate this.  The solution I can think of (there may be other ways bundler can solve this problem) is for bundler to enforce that if a gem is in Gemfile.lock, even if it's in an excluded group, no other version of that gem can be required (i.e. fail when `Bundler.setup` or `require 'json'` is called in production--whichever comes second).

**Comment by segiddins** [comment]
Bundler actually can't do that -- those files are already on the `$LOAD_PATH` and are requirable even with rubygems disabled

**Comment by colby-swandale** [comment]
It looks like this issue has been answered. Closing this for now.

**Comment by betesh** [comment]
I'm not convinced that just because they are on the `$LOAD_PATH` means we can't lock down the gem version.  Rubygems already overrides `Kernel.require` [here](https://github.com/rubygems/rubygems/blob/439c4464890958fec17b3aa65b9d3a4dbdd3bf90/lib/rubygems/core_ext/kernel_require.rb#L39) and the same methodology could work here.

Telling me it can't be done is very different than showing me why it can't be done.

**Comment by indirect** [comment]
@betesh first, a small warning: please keep the conversation respectful and positive. You're not over the line yet, but you're trending in that direction. Keep in mind that we are helping you for free, without any obligation to do so.

With that out of the way, can you describe how this results in a different version of a gem being used in development vs in production? Built-in gems are always the same version on the same version of Ruby. The only way I can think of for this to result in different versions of the JSON gem is for you to be using different versions of Ruby in development and in production. If that's true, I recommend adding a `ruby` entry to your Gemfile, so that Bundler will raise an exception if your application is loaded on a different version of Ruby.

**Comment by betesh** [comment]
> please keep the conversation respectful and positive

I apologize and have removed that portion of my comment.

> can you describe how this results in a different version of a gem being used in development vs in production?

I thought I did that pretty well in the description.  Please tell me which part is unclear and I will do my best to clarify.

**Comment by indirect** [comment]
Thanks for the reply. After re-reading your additional comment, I think I understand now. I am not sure if it's possible to address the problem in a meaningful way... because the Ruby stdlib includes a version of the json gem, the only way to prevent loading that gem would be to remove the stdlib dir from the load path. That would break other code that requires other stdlib files, like Time or Date or FileUtils.

Monkey patching require to actively block gems that aren't in the gemfile creates a situation where we somehow have to know the string path for every file from every gem that _isn't_ in the gemfile, just to be able to block requiring them. I can't think of any practical way to do that inside the constraints of bundler at runtime, either. :/

**Comment by betesh** [comment]
> Monkey patching require to actively block gems that aren't in the gemfile creates a situation where we somehow have to know the string path for every file from every gem that *isn't* in the gemfile

I'm not suggesting removing json from the load path when it's not in the Gemfile at all, only when it's in Gemfile.lock.  Wouldn't it be possible to detect such a case?  And just to change the behavior if the argument to require is the gem name, not if it's an exact path?

**Comment by indirect** [comment]
Unfortunately, only gems installed by rubygems have one load path entry per gem. Gems that ship with ruby itself are placed in the same directory as every other stdlib, and so removing built-in json from the load path would mean also removing every other stdlib from the load path. That does not seem viable to me. :/

As for patching require to guard against gems in the lockfile that have been skipped by a --without command, I would very much like to be able to do it, but I am extremely confident that if we shipped such a check, we would immediately face bug reports claiming that we should expand the check to also block any file included in that gem, which I also don't think is tenable.

I agree with you that this situation breaks the promise made by Bundler to guarantee the same versions, and that is very distressing to me. :( I'm not okay shipping a hacky half fix, and I can't figure out any way to have a true fix.

I guess the workaround I can recommend for now is to add json to your gemfile directly, which will guarantee versions on every machine. Sorry we can't do more, at the moment anyway.

**Comment by betesh** [comment]
> I am extremely confident that if we shipped such a check, we would immediately face bug reports claiming that we should expand the check to also block any file included in that gem, which I also don't think is tenable.

Is that information (the list of all files included in that gem) easily accessible from the gemspec?  The challenge I see with this is if the `require`-ed file is on the LOAD_PATH, how would we know whether the gem would have been above or below it had the gem be included.  I think if we can answer that question, we may have a thorough solution.

**Comment by betesh** [comment]
Just one last question:

Does the bundler team recommend that gems that use json or other stdlib gems list them in their gemspec?  If you could publish some guidance on this issue, it would make gem developers more aware of how they could prevent their users from running into this issue in production.

For example, it's a lot easier for ActiveSupport to add json to its gemspec then for ActiveSupport users everywhere to add it to their Gemfile.

Thank you!

**Comment by indirect** [comment]
@betesh unfortunately the list of every single possible file that could be required is not easily obtained from the gemspec. It would likely require actually recursively listing every directory of the installed gem. :(

As for stdlib gems, YES, please always list gems you will use in the Gemfile, even if they are stdlib gems. We have done huge amounts of work to make Bundler correctly handle versioning for default/builtin gems, but the code is only activated if the gem is in a group that is being included.

**Comment by betesh** [comment]
For reference, a few issues where removing json from a gemspec was discussed, and, in many cases, implemented, under the impression that since it's in stdlib, there's no reason it needs to be in the gemspec:

https://github.com/colszowka/simplecov/issues/511
https://github.com/colszowka/simplecov/pull/491
https://github.com/rails/rails/pull/23453
https://github.com/aws/aws-sdk-ruby/issues/432
https://github.com/ai/autoprefixer-rails/pull/86
https://github.com/mperham/sidekiq/issues/2743

**Comment by indirect** [comment]
ugh :( the version that ships in the stdlib changes with every ruby release. If a gem uses json, it needs to declare it as a dependency for Bundler to be able to guarantee a version. If a gem uses json without declaring a dependency, it's hard verging on impossible for Bundler to guarantee matching versions of json across multiple machines and rubies.

**Comment by indirect** [comment]
In that sense, removing it from the gemspec is agreeing to let the version float to whatever ships with Ruby—just like we do with other stdlibs, even when they are changed. If a gem chooses to treat JSON as a stdlib, rather than a gem, it is then outside of Bundler's control. :/

**Comment by betesh** [comment]
>  If a gem chooses to treat JSON as a stdlib, rather than a gem, it is then outside of Bundler's control. :/

Agreed.  And that would be harmless if that were consistent across environments, which is only possible if **all** gems in your Gemfile agree to treat it as stdlib.

And the only way bundler could enforce that is by refusing to handle versioning of stdlib gems, which would cause a whole lot more problems then it solves.
