### ISSUE TITLE
`bundle outdated` doesn't show some outdated gems when using `--local`

### ISSUE THREAD

**Issue by mvz** [bundler/bundler#5430]
With version 1.14.4 of Bundler, some outdated gems are not shown when using the `--local` option:

```
$ bundle show parser
/home/matijs/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/parser-2.3.3.1
$ gem list '^parser$'
*** LOCAL GEMS ***

parser (2.4.0.0, 2.3.3.1)
$ bundle outdated
Fetching gem metadata from https://rubygems.org/........
Fetching version metadata from https://rubygems.org/.
Resolving dependencies...

Outdated gems included in the bundle:
  * childprocess (newest 0.6.1, installed 0.5.9)
  * cucumber-core (newest 2.0.0, installed 1.5.0)
  * parser (newest 2.4.0.0, installed 2.3.3.1)
  * slop (newest 4.4.1, installed 3.6.0)
```

With bundle version 1.13.7, bundler does detect the outdated gems when using the `--local` option, i.e., after removing 1.14.4, I get:
```
$ bundle outdated --local
Resolving dependencies...

Outdated gems included in the bundle:
  * childprocess (newest 0.6.1, installed 0.5.9)
  * cucumber-core (newest 2.0.0, installed 1.5.0)
  * parser (newest 2.4.0.0, installed 2.3.3.1)
  * slop (newest 4.4.1, installed 3.6.0)
```

I'll add a repro script once I have an issue number.

**Comment by mvz** [comment]
A simple script to reproduce this is here: https://gist.github.com/mvz/b4d55c88279a4e809c6c2ae09bf20b8a

**Comment by indirect** [comment]
By definition, `--local` is not allowed to talk to the rubygems servers, so the usefulness of the outdated command seems very limited. Can you explain your use case, and what this enables you to do that you can't do without it?

**Comment by mvz** [comment]
Well, first off, the `--local` version is a lot faster and allows offline use.

I have a script that iterates over all my projects and does two health checks: It checks whether everything is committed to git, and it checks for outdated gems with the `--local` flag. This would be tedious to run without `--local`.

I generally do one of two things:
* I update dependencies in one project and then run my script to see if I need to look at any others.
* Update all gems using `gem update` and then run my script to see which projects need attention.

If there are many projects that are outdated, I usually run `bundle update --local` on all of them using a script, and then check again.

**Comment by indirect** [comment]
Wow, that's a clever use of outdated that I had never thought of. I always use `--path .bundle` in order to keep installed sets of gems small, which makes the strategy you're describing impossible. Thanks for explaining! Hopefully we can get `outdated --local` fixed soon.

**Comment by denniss** [comment]
I think I got it to work properly when --local is used. @mvz Can you review?

**Comment by mvz** [comment]
@denniss I'm not sure how the changed code is different? Is this something tricky to do with returning from a block?

**Comment by denniss** [comment]
I believe so. That return from proc exits the method immediately.

**Comment by mvz** [comment]
Thanks, @denniss, I can't wait for the next Bundler release to try this out :-).

**Comment by mvz** [comment]
This works fine in version 1.14.6! Thanks again, @denniss.
