### ISSUE TITLE
Invalid Github URL in README

### ISSUE THREAD

**Issue by danielpclark** [bundler/bundler#5438]
Bundler version 1.14.3

With using
```
bundle gem example
```
The `README.md` file under contributions shows as:

```
https://github.com/Daniel P. Clark/example
```

This is taken from `git config --get user.name` (I believe)

The command that should be used is `git config --get github.user` which would result in:

```
https://github.com/danielpclark/example
```

**Comment by olleolleolle** [comment]
(Snooping around: These are the locations where the data is dug up and used.)

https://github.com/bundler/bundler/blob/master/lib/bundler/cli/gem.rb#L32

https://github.com/bundler/bundler/blob/master/lib/bundler/templates/newgem/README.md.tt#L35

Would you want to author a PR about this?

**Comment by danielpclark** [comment]
Sure, I'd love to!
