### ISSUE TITLE
`bundle inject` must use options

### ISSUE THREAD

**Issue by Shekharrajak** [bundler/bundler#5452]
User may want to add gem like this in the Gemfile : 
```
gem 'bootstrap', '> 0', :group => [:development], :source => 'https://rubygems.org'
```
using this command : 

```
$ bundle inject "bootstrap" ">0" --source=https://rubygems.org --group=development
```
currently we get this msg as output: 

```
Unknown switches '--source=https://rubygems.org, --group=development'
```

**Comment by Shekharrajak** [comment]
I am working on this.

**Comment by indirect** [comment]
Great! Please support these options inside a new command named `bundle add`. The `inject` command was never intended to support options. Thank you. :)

**Comment by colby-swandale** [comment]
@indirect do you want to approve  the [bundle add](https://github.com/hmistry/rfcs/blob/db5e1637e233407f3634d1704a7be2066d5ed309/text/0000-bundle-add.md) RFC? This could serve as a really helpful guide.

**Comment by indirect** [comment]
I'd love for there to be more discussion on it! If anyone has ideas. I'm also super happy to have an implementation that we can try out and give feedback on 👍 So maybe we should consider the RFC "provisionally approved" and move forward from there.

**Comment by colby-swandale** [comment]
Great, i'll go over it and add anything i can.

**Comment by Shekharrajak** [comment]
I have read `bundle add` discussions in PRs and RFC. I see some `attr` in bundle [`inject`](https://github.com/bundler/bundler/blob/master/lib/bundler/cli/inject.rb#L4) So I think inject must be for installing single gem with source and/or group options.

Using `bundle add` user must be able to add multiple gem with these options(it can have different source and group for each gem).

**Comment by colby-swandale** [comment]
@Shekharrajak i would leave the adding multiple gems alone for now and just work on adding a single gem with options.

**Comment by Shekharrajak** [comment]
Thanks @indirect @colby-swandale for discussion. I have oped a PR https://github.com/bundler/bundler/issues/5456 . I am getting some error in testcases. I hope I will fix them soon.
