### ISSUE TITLE
Using different git branches depending on deployment

### ISSUE THREAD

**Issue by tjbp** [bundler/bundler#5453]
My project uses a selection of private gems that are developed in tandem with the project. I have the Gemfile lines pointed to the stable branches of those gem repos, but now I need to deploy the project to a staging server and use the development branches of those gems.

I've tried repeating the gems in development and production groups but with the respective branches and bundler complains. Is there a pattern in the Gemfile I'm missing that would allow for this, or is this a reasonable justification for allowing gems to be repeated (albeit in separate groups)? Currently this is being handled by using different Gemfiles depending on the deployment, which is undesirable for obvious reasons (eg. rendering Gemfile.lock largely pointless).

**Comment by colby-swandale** [comment]
We don't allow gems being specified more than once in a Gemfile and we're not looking to change that behaviour.
