### ISSUE TITLE
Bundle update failing with incorrect failure message

### ISSUE THREAD

**Issue by brendon9x** [bundler/bundler#5457]
Recently (apparently since 1.14), bundler has intermittently failed to `bundle update` in many of our repositories.  The headline error is usually of the format:

```
Bundler could not find compatible versions for gem "actionmailer":
  In Gemfile:
    actionmailer (= 5.0.0.1)
```

Sometimes it is activesupport.  I have come across times when this error can be masking a real conflict, but in the GIST provided (https://gist.github.com/brendon9x/c9990838dbbf23c8417c386e53b3d40c) there doesn't appear to be a genuine problem with the constraints.  Importantly, bundle update works in all versions we tested prior to the 1.14 series.

This is the output from bundler 1.14.3:

```
Fetching https://github.com/jawspeak/zipruby-compatibility-with-rubyzip-fork.git
Fetching gem metadata from https://rubygems.intellectionsoftware.com/....
Fetching gem metadata from https://rubygems.org/..........
Fetching version metadata from https://rubygems.intellectionsoftware.com/...
Fetching version metadata from https://rubygems.org/...
Fetching version metadata from https://rubygems.intellectionsoftware.com/...
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rubygems.intellectionsoftware.com/..
Fetching dependency metadata from https://rubygems.org/.
Resolving dependencies............................
Bundler could not find compatible versions for gem "activesupport":
  In Gemfile:
    rspec-rails (~> 3.5) was resolved to 3.5.2, which depends on
      actionpack (>= 3.0) was resolved to 5.0.1, which depends on
        activesupport (= 5.0.0.1)

    rspec-rails (~> 3.5) was resolved to 3.5.2, which depends on
      railties (>= 3.0) was resolved to 5.0.1, which depends on
        activesupport (= 5.0.1)

    rspec-rails (~> 3.5) was resolved to 3.5.2, which depends on
      railties (>= 3.0) was resolved to 5.0.1, which depends on
        activesupport (= 5.0.1)

    rspec-rails (~> 3.5) was resolved to 3.5.2, which depends on
      activesupport (>= 3.0)
Bundler could not find compatible versions for gem "rack":
  In Gemfile:
    rack (~> 2.0)

    rack-test (~> 0.6.3) was resolved to 0.6.3, which depends on
      rack (>= 1.0)

    semvergen (~> 1.9.1) was resolved to 1.9.1, which depends on
      geminabox (~> 0.12) was resolved to 0.12.0, which depends on
        sinatra (>= 1.2.7) was resolved to 1.2.7, which depends on
          rack (~> 1.1)

    thin (~> 1.5) was resolved to 1.7.0, which depends on
      rack (< 3, >= 1)
```

For now, we are locking bundler to 1.13 to work around.  But others have got it around it by adding these two lines to our Gemfile:

```
gem "actionmailer", "~> 3.2"
gem "activesupport", "~> 3.2"
```

Perhaps the errors only occur if the constraints are imported transitively?

**Comment by segiddins** [comment]
Can you see if `master` improves things? I think a small change made to the resolver has improved resolving gemfiles that use `gemspec`

**Comment by olleolleolle** [comment]
@brendon9x Ha! Small world. 

Here's a blog post about getting latest Bundler onto your machine. http://ollehost.dk/blog/2017/02/19/how-to-use-very-latest-bundler-in-travis/

**Comment by brendon9x** [comment]
@olleolleolle Small world indeed!  Thanks - I was mid-cloning the repo.

**Comment by brendon9x** [comment]
Hi @olleolleolle @segiddins – I can confirm that this issue is fixed in master!  And it's seems considerably faster than 1.13.7.

**Comment by brendon9x** [comment]
I consider this speediest bug resolution I've ever experienced. 10 minutes.  Do you have an idea on 1.14.5 release date?

**Comment by olleolleolle** [comment]
@brendon9x The [1.14.5 milestone](https://github.com/bundler/bundler/milestone/42) is finished.

**Comment by segiddins** [comment]
Awesome! 1.14.5 will happen as soon as I have a whole half hour free :)
