### ISSUE TITLE
`bundle gem` fails when git is not available

### ISSUE THREAD

**Issue by jsch0221** [bundler/bundler#5458]
Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/bundler/bundler/search?q=No+such+file+or+directory+-+git&type=Issues

If there aren't any reports for this error yet, please create copy and paste the report template above into a new issue. Don't forget to anonymize any private data! The new issue form is located at:
https://github.com/bundler/bundler/issues/new
[sa16032@localhost ~]$ /usr/local/bin/bundle gem lemonade_stand
Creating gem 'lemonade_stand'...
--- ERROR REPORT TEMPLATE -------------------------------------------------------
# Error Report

## Questions

Please fill out answers to these questions, it'll help us figure out
why things are going wrong.

  I ran the command `/usr/local/bin/bundle gem lemonade_stand`

  I expected Bundler to create lemonade_stand/Gemfile, Rakefile, LICENSE.txt, READM.md, gitignore, lemonade_stand.gemspec,    lemonade_stand/lib/lemonade_stand.rb, version.rb, and  initialize git repo in /users/

  Instead, what happened was 'Unexpected error' and an error-report template

  I tried running the command as root, but there was no change. 

## Backtrace
```
Errno::ENOENT: No such file or directory - git
  /usr/local/share/gems/gems/bundler-1.14.4/lib/bundler/cli/gem.rb:32:in ``'
  /usr/local/share/gems/gems/bundler-1.14.4/lib/bundler/cli/gem.rb:32:in `run'
  /usr/local/share/gems/gems/bundler-1.14.4/lib/bundler/cli.rb:433:in `run'
  /usr/local/share/gems/gems/bundler-1.14.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
  /usr/local/share/gems/gems/bundler-1.14.4/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
  /usr/local/share/gems/gems/bundler-1.14.4/lib/bundler/cli.rb:20:in `dispatch'
  /usr/local/share/gems/gems/bundler-1.14.4/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
  /usr/local/share/gems/gems/bundler-1.14.4/lib/bundler/cli.rb:11:in `start'
  /usr/local/share/gems/gems/bundler-1.14.4/exe/bundle:32:in `block in <top (required)>'
  /usr/local/share/gems/gems/bundler-1.14.4/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
  /usr/local/share/gems/gems/bundler-1.14.4/exe/bundle:24:in `<top (required)>'
  /usr/local/bin/bundle:22:in `load'
  /usr/local/bin/bundle:22:in `<main>'
```

## Environment

```
Bundler   1.14.4
Rubygems  2.6.10
Ruby      2.0.0p598 (2014-11-13 revision 0) [x86_64-linux]
Git       not installed
Platform  x86_64-linux

**Comment by hmistry** [comment]
It looks like the error is due to git not installed on your system. Please install git and try again.

**Comment by jsch0221** [comment]
That was the problem.  I installed git and it's now working.  Thank you.

**Comment by colby-swandale** [comment]
I'm going to keep this issue open because `bundler gem` shouldn't be assuming the user has `git` installed and needs to properly handle that scenario. I'll work on this.

**Comment by hmistry** [comment]
@colby-swandale I was thinking the same thing. Perhaps something like a prerequisites check and giving simple errors that something is not installed instead of a backtrace.

**Comment by segiddins** [comment]
@hmistry sounds good to me!

**Comment by Shekharrajak** [comment]
Sorry, I read the discussion but didn't see that `colby-swandale self-assigned this` . I just opened a PR, fixing this issue.

**Comment by colby-swandale** [comment]
@segiddins IMO (and as i mentioned in the #5466) `git` shouldn't be a requirement. There are users who other VCSs other then Git. If Git is not installed we should be setting sensible defaults instead of breaking/raising errors.
