### ISSUE TITLE
Mismatch in Gemfile.lock remote property leads to bundle install failure

### ISSUE THREAD

**Issue by askldjd** [bundler/bundler#5465]
This bug is observed since 1.14.5. 

During development, our [Gemfile](https://github.com/askldjd/caseflow/blob/master/Gemfile#L1) targets rubygems.org. During deployment, our [Gemfile](https://github.com/askldjd/caseflow/blob/master/Gemfile#L1) may target a local gem caching server (using gemstash) for reliability.

In our scenario, `GEM_SERVER_URL` is not defined during development time, so it falls back to rubygems.org. Since developers generate the Gemfile.lock file, naturally, it will use rubygems.org as the [`remote` property](https://github.com/askldjd/caseflow/blob/master/Gemfile.lock#L47). During deployment, we define `GEM_SERVER_URL` to a local server before performing `bundle install --deployment`.

Since 1.14.5, the bundler will not allow `bundle install` to proceed unless the `remote` property matches between the Gemfile and Gemfile.lock. When we target a local gem server and perform `bundle install --deployment`, it outputs the following message:
```
You are trying to install in deployment mode after changing your Gemfile. Run `bundle install` elsewhere and add the updated Gemfile.lock to version control.
```

This new behavior is introduced in 1.14.5. As workaround, we have now rollback to 1.14.4.

If this behavior is by design, how would we work around it?

**Comment by colby-swandale** [comment]
You can set the config option `mirror.SOURCE_URL MIRROR_UR` in your deployment env to use the MIRROR_URL when fetching gems from the `SOURCE_URL` (this case being rubygems.org`).  See [bundler config](https://bundler.io/v1.14/man/bundle-config.1.html) for more information.

**Comment by olleolleolle** [comment]
I can add that if the Gemfile had a source with credentials (the "authority" part of its URI) and the lock file didn't, the same new trouble situation would apply. Before 1.14.5, this (admittedly weird) setup caused no trouble.

**Comment by askldjd** [comment]
Thank you all, I will give the `mirror.SOURCE_URL` option a try.

**Comment by colby-swandale** [comment]
ping @askldjd, did the Bundler config option work?

**Comment by askldjd** [comment]
@colby-swandale Sorry, running a bit behind schedule. I will get you an answer by this week.

**Comment by kierachell** [comment]
Adding `mirror` configuration does not work if the mirror is not available in the development environment:
```
Fetching source index from <internal IP>

Retrying fetcher due to error (2/4): Bundler::HTTPError Could not fetch specs from <internal IP>
Retrying fetcher due to error (3/4): Bundler::HTTPError Could not fetch specs from <internal IP>
Retrying fetcher due to error (4/4): Bundler::HTTPError Could not fetch specs from <internal IP>
Could not fetch specs from
<internal IP>
vhaisavovka0x@VACOLTVOVKA:caseflow-efolder>bundle config
Settings are listed in order of priority. The top value will be used.
mirror.http://rubygems.org/
Set for the current user (/Users/vhaisavovka0x/.bundle/config): "<internal IP>"
```

Either that or bundle install just fails completely. Also, running `bundle install --deployment` fails if the mirror is configured because `remote` property in `Gemfile.lock` is different between the environments (error show in the original ticket).

**Comment by colby-swandale** [comment]
I'm closing this for now. If you're still experiencing your original issue don't be afraid to re-open this ticket.

**Comment by askldjd** [comment]
Final note:

@kierachell and I were not able get `mirror` config working. We worked around this issue by doing a find/replace in the gemfile during deployment time.

Here's the snippet of our ansible code that does this.
```
- name: config gem server
  replace:
    dest: "{{ app_src }}/Gemfile.lock"
    regexp: "remote: https://rubygems.org/"
    replace: "remote: {{ gem_server[deploy_env] | default('https://rubygems.org/') }}"
```
