### ISSUE TITLE
--without installs all gems

### ISSUE THREAD

**Issue by dare05** [bundler/bundler#5469]
I'm using Ruby 2.2 on Windows 7 machine and have gems in several groups. When I do something like:

`bundle install --without test`

All the gems get installed (even those inside the "test" group and this is the ONLY group they are in) and get added in Gemfile.lock. When I do `Bundle.setup`, however, the gems inside `test` don't get added to the load path.

Is this a normal behavior? I thought that `--without` does not install the gems at all.

**Comment by colby-swandale** [comment]
Bundler will install gems whenever it needs to resolve dependencies regardless of the `--without` option. Some examples of when this happens include:

* When your project does't have a `Gemfile.lock`
* When you add a new gem to the `Gemfile`

**Comment by colby-swandale** [comment]
I'm closing this for now, if you have any more questions don't be afraid to reopen this issue.
