### ISSUE TITLE
Bundler no longer preloading Date class after 1.14.4

### ISSUE THREAD

**Issue by cdoughty-r7** [bundler/bundler#5470]
As of 1.14.5 we started getting an error due to us using the Date class in our gemspec.

Here's a slimmed down instruction set and two files to reproduce:

- Gemfile

```
source 'https://rubygems.org'

gemspec name: 'newgem'
```

- newgem.gemspec

```
Gem::Specification.new do |s|
  s.name        = 'newgem'
  s.version     = '1.0.0'
  s.date        = Date.today.to_s
  s.summary     = "A gem test"
  s.description = "A gem test"
  s.authors     = ["none"]
end
```

Steps to reproduce failure: 
```
$ gem uninstall --all --ignore-dependencies --executables --force bundler
$ gem install bundler -v 1.14.5 --no-document
$ bundle exec bundle install

[!] There was an error parsing `Gemfile`:
[!] There was an error while loading `newgem.gemspec`: uninitialized constant Date. Bundler cannot continue.

 #  from /path/to/file/newgem/newgem.gemspec:4
 #  -------------------------------------------
 #    s.version     = '1.0.0'
 >    s.date        = Date.today.to_s
 #    s.summary     = "A gem test"
 #  -------------------------------------------
. Bundler cannot continue.

 #  from /path/to/file/newgem/Gemfile:3
 #  -------------------------------------------
 #
 >  gemspec name: 'newgem'
 #  -------------------------------------------

```

Now do the same thing with bundler versions 1.12.5 or 1.14.4 and notice the issue does not occur (in other words bundle install will work as designed).

Obviously this is easy to work around with a "require 'date'" line at the top of the gemspec, but the larger issue is that this is broken backwards compatibility and then there's the question of what changed to cause this of course.

**Comment by segiddins** [comment]
Since `date` is a gem in ruby 2.5, Bundler can no longer require it (it would mean that users couldn't actually get the version of the date gen they asked for in their gemfiles)

**Comment by colby-swandale** [comment]
ping @cdoughty-r7

**Comment by cdoughty-r7** [comment]
If the work around is the one I suggested (require date) then this can be closed.  The issue was only opened because this was unexpected and undocumented behavior.
