### ISSUE TITLE
Net::HTTPServerException: 407 "Proxy Authentication Required"

### ISSUE THREAD

**Issue by santoshkumarsuru** [bundler/bundler#5475]
- What did you do?

  I ran the command `D:/Rails/ruby-2.1.9/bin/bundle install`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what happened was...

Error details

    Net::HTTPServerException: 407 "Proxy Authentication Required"
      D:/Rails/ruby-2.1.9/lib/ruby/2.1.0/net/http/response.rb:119:in `error!'
      D:/Rails/ruby-2.1.9/lib/ruby/2.1.0/net/http/response.rb:128:in `value'
      D:/Rails/ruby-2.1.9/lib/ruby/2.1.0/net/http.rb:915:in `connect'
      D:/Rails/ruby-2.1.9/lib/ruby/2.1.0/net/http.rb:863:in `do_start'
      D:/Rails/ruby-2.1.9/lib/ruby/2.1.0/net/http.rb:858:in `start'
      D:/Rails/ruby-2.1.9/lib/ruby/2.1.0/rubygems/request.rb:96:in `connection_for'
      D:/Rails/ruby-2.1.9/lib/ruby/2.1.0/rubygems/request.rb:122:in `fetch'
      D:/Rails/ruby-2.1.9/lib/ruby/2.1.0/rubygems/remote_fetcher.rb:343:in `request'
      D:/Rails/ruby-2.1.9/lib/ruby/2.1.0/rubygems/remote_fetcher.rb:237:in `fetch_http'
      D:/Rails/ruby-2.1.9/lib/ruby/2.1.0/rubygems/remote_fetcher.rb:272:in `fetch_path'
      D:/Rails/ruby-2.1.9/lib/ruby/gems/2.1.0/gems/bundler-1.13.1/lib/bundler/rubygems_integration.rb:640:in `fetch_specs'
      D:/Rails/ruby-2.1.9/lib/ruby/gems/2.1.0/gems/bundler-1.13.1/lib/bundler/rubygems_integration.rb:650:in `fetch_all_remote_specs'
      D:/Rails/ruby-2.1.9/lib/ruby/gems/2.1.0/gems/bundler-1.13.1/lib/bundler/fetcher/index.rb:9:in `specs'
      D:/Rails/ruby-2.1.9/lib/ruby/gems/2.1.0/gems/bundler-1.13.1/lib/bundler/fetcher.rb:128:in `block in specs'
      D:/Rails/ruby-2.1.9/lib/ruby/gems/2.1.0/gems/bundler-1.13.1/lib/bundler/fetcher.rb:127:in `each'
      D:/Rails/ruby-2.1.9/lib/ruby/gems/2.1.0/gems/bundler-1.13.1/lib/bundler/fetcher.rb:127:in `specs'
      D:/Rails/ruby-2.1.9/lib/ruby/gems/2.1.0/gems/bundler-1.13.1/lib/bundler/fetcher.rb:112:in `block in specs_with_retry'
      D:/Rails/ruby-2.1.9/lib/ruby/gems/2.1.0/gems/bundler-1.13.1/lib/bundler/retry.rb:39:in `call'
      D:/Rails/ruby-2.1.9/lib/ruby/gems/2.1.0/gems/bundler-1.13.1/lib/bundler/retry.rb:39:in `run'
      D:/Rails/ruby-2.1.9/lib/ruby/gems/2.1.0/gems/bundler-1.13.1/lib/bundler/retry.rb:29:in `attempt'
      D:/Rails/ruby-2.1.9/lib/ruby/gems/2.1.0/gems/bundler-1.13.1/lib/bundler/fetcher.rb:111:in `specs_with_retry'
      D:/Rails/ruby-2.1.9/lib/ruby/gems/2.1.0/gems/bundler-1.13.1/lib/bundler/source/rubygems.rb:342:in `block (2 levels) in remote_specs'
      D:/Rails/ruby-2.1.9/lib/ruby/gems/2.1.0/gems/bundler-1.13.1/lib/bundler/source/rubygems.rb:340:in `each'
      D:/Rails/ruby-2.1.9/lib/ruby/gems/2.1.0/gems/bundler-1.13.1/lib/bundler/source/rubygems.rb:340:in `block in remote_specs'
      D:/Rails/ruby-2.1.9/lib/ruby/gems/2.1.0/gems/bundler-1.13.1/lib/bundler/index.rb:10:in `build'
      D:/Rails/ruby-2.1.9/lib/ruby/gems/2.1.0/gems/bundler-1.13.1/lib/bundler/source/rubygems.rb:336:in `remote_specs'
      D:/Rails/ruby-2.1.9/lib/ruby/gems/2.1.0/gems/bundler-1.13.1/lib/bundler/source/rubygems.rb:83:in `specs'
      D:/Rails/ruby-2.1.9/lib/ruby/gems/2.1.0/gems/bundler-1.13.1/lib/bundler/definition.rb:263:in `block (2 levels) in index'
      D:/Rails/ruby-2.1.9/lib/ruby/gems/2.1.0/gems/bundler-1.13.1/lib/bundler/definition.rb:261:in `each'
      D:/Rails/ruby-2.1.9/lib/ruby/gems/2.1.0/gems/bundler-1.13.1/lib/bundler/definition.rb:261:in `block in index'
      D:/Rails/ruby-2.1.9/lib/ruby/gems/2.1.0/gems/bundler-1.13.1/lib/bundler/index.rb:10:in `build'
      D:/Rails/ruby-2.1.9/lib/ruby/gems/2.1.0/gems/bundler-1.13.1/lib/bundler/definition.rb:258:in `index'
      D:/Rails/ruby-2.1.9/lib/ruby/gems/2.1.0/gems/bundler-1.13.1/lib/bundler/definition.rb:252:in `resolve'
      D:/Rails/ruby-2.1.9/lib/ruby/gems/2.1.0/gems/bundler-1.13.1/lib/bundler/definition.rb:176:in `specs'
      D:/Rails/ruby-2.1.9/lib/ruby/gems/2.1.0/gems/bundler-1.13.1/lib/bundler/definition.rb:164:in `resolve_remotely!'
      D:/Rails/ruby-2.1.9/lib/ruby/gems/2.1.0/gems/bundler-1.13.1/lib/bundler/installer.rb:225:in `resolve_if_need'
      D:/Rails/ruby-2.1.9/lib/ruby/gems/2.1.0/gems/bundler-1.13.1/lib/bundler/installer.rb:78:in `run'
      D:/Rails/ruby-2.1.9/lib/ruby/gems/2.1.0/gems/bundler-1.13.1/lib/bundler/installer.rb:24:in `install'
      D:/Rails/ruby-2.1.9/lib/ruby/gems/2.1.0/gems/bundler-1.13.1/lib/bundler/cli/install.rb:71:in `run'
      D:/Rails/ruby-2.1.9/lib/ruby/gems/2.1.0/gems/bundler-1.13.1/lib/bundler/cli.rb:189:in `install'
      D:/Rails/ruby-2.1.9/lib/ruby/gems/2.1.0/gems/bundler-1.13.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      D:/Rails/ruby-2.1.9/lib/ruby/gems/2.1.0/gems/bundler-1.13.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      D:/Rails/ruby-2.1.9/lib/ruby/gems/2.1.0/gems/bundler-1.13.1/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      D:/Rails/ruby-2.1.9/lib/ruby/gems/2.1.0/gems/bundler-1.13.1/lib/bundler/cli.rb:20:in `dispatch'
      D:/Rails/ruby-2.1.9/lib/ruby/gems/2.1.0/gems/bundler-1.13.1/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      D:/Rails/ruby-2.1.9/lib/ruby/gems/2.1.0/gems/bundler-1.13.1/lib/bundler/cli.rb:11:in `start'
      D:/Rails/ruby-2.1.9/lib/ruby/gems/2.1.0/gems/bundler-1.13.1/exe/bundle:34:in `block in <top (required)>'
      D:/Rails/ruby-2.1.9/lib/ruby/gems/2.1.0/gems/bundler-1.13.1/lib/bundler/friendly_errors.rb:100:in`with_friendly_errors'
      D:/Rails/ruby-2.1.9/lib/ruby/gems/2.1.0/gems/bundler-1.13.1/exe/bundle:26:in `<top (required)>'
      D:/Rails/ruby-2.1.9/bin/bundle:23:in `load'
      D:/Rails/ruby-2.1.9/bin/bundle:23:in `<main>'

Environment

  Bundler   1.13.1
  Rubygems  2.2.5
  Ruby      2.1.9p490 (2016-03-30 revision 54437) [i386-mingw32]
  GEM_HOME  D:/Rails/ruby-2.1.9/lib/ruby/gems/2.1.0
  GEM_PATH  D:/Rails/ruby-2.1.9/lib/ruby/gems/2.1.0;P:/.gem/ruby/2.1.0
  Git       1.8.1.msysgit.1

**Comment by colby-swandale** [comment]
Thanks for the report! As the error suggests you need to authenticate to your proxy server. But there should be a friendly error for this.

**Comment by santoshkumarsuru** [comment]
Yeah.. i my local i dont have any proxy authentication but still getting this

**Comment by colby-swandale** [comment]
can you share the output of `bundle env`

**Comment by santoshkumarsuru** [comment]
Environment

    Bundler   1.13.1
    Rubygems  2.6.10
    Ruby      2.1.9p490 (2016-03-30 revision 54437) [i386-mingw32]
    Git       1.8.1.msysgit.1

Gemfile

    source 'https://rubygems.org'


    # Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
    gem 'rails', '4.2.2'
    # Use sqlite3 as the database for Active Record
    gem 'sqlite3'
    # Use SCSS for stylesheets
    gem 'sass-rails', '~> 5.0'
    # Use Uglifier as compressor for JavaScript assets
    gem 'uglifier', '>= 1.3.0'
    # Use CoffeeScript for .coffee assets and views
    gem 'coffee-rails', '~> 4.1.0'
    # See https://github.com/rails/execjs#readme for more supported runtimes
    # gem 'therubyracer', platforms: :ruby

    # Use jquery as the JavaScript library
    gem 'jquery-rails'
    # Turbolinks makes following links in your web application faster. Read more
: https://github.com/rails/turbolinks
    gem 'turbolinks'
    # Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
    gem 'jbuilder', '~> 2.0'
    # bundle exec rake doc:rails generates the API under doc/api.
    gem 'sdoc', '~> 0.4.0', group: :doc

    # Use ActiveModel has_secure_password
    # gem 'bcrypt', '~> 3.1.7'

    # Use Unicorn as the app server
    # gem 'unicorn'

    # Use Capistrano for deployment
    # gem 'capistrano-rails', group: :development

    group :development, :test do
      # Call 'byebug' anywhere in the code to stop execution and get a debugger
console
      gem 'byebug'

      # Access an IRB console on exception pages or by using <%= console %> in v
iews
      gem 'web-console', '~> 2.0'
    end

    # Windows does not include zoneinfo files, so bundle the tzinfo-data gem
    gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

Gemfile.lock

    <No D:/Rails/Projects/TestApp/Gemfile.lock found>

**Comment by colby-swandale** [comment]
Can you update bundler to the latest version and let us know if this error continues to occur. Thanks.

**Comment by colby-swandale** [comment]
ping @santoshkumarsuru

**Comment by santoshkumarsuru** [comment]
hi colby-swandale,
I tried by updating bundler to latest.. still same issue

**Comment by colby-swandale** [comment]
can you run `bundle install` with the `--verbose` flag and paste the output

**Comment by colby-swandale** [comment]
ping @santoshkumarsuru

**Comment by colby-swandale** [comment]
I'm closing this for now. If you're still experiencing your original issue don't be afraid to re-open this ticket.
