### ISSUE TITLE
:github in Gemfile causes a fetch over git instead of HTTPS

### ISSUE THREAD

**Issue by YtvwlD** [bundler/bundler#5476]
If I create a Gemfile with the following contents:

```
source 'https://rubygems.org'
gem 'somegem', :github => 'someuser/somerepo'
```

Bundler will clone git://github.com/someuser/somerepo.git instead of https://github.com/someuser/somerepo.git. It sometimes warns about this:

```
The git source `git://github.com/someuser/somerepo.git` uses the `git` protocol, which transmits data without encryption. Disable this warning with `bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.
```

[The documentation does mention this issue.](https://bundler.io/git.html#security)
My workaround is adding this at the beginning of a Gemfile:

```
git_source(:github){ |repo_name| "https://github.com/#{repo_name}.git" }
```

It would be great if HTTPS was the default for fetching things from Github.

**Comment by segiddins** [comment]
It will be true default in bundler 2, we can't change before then

**Comment by YtvwlD** [comment]
That's great to hear.
But what prevents you from before? Github supports cloning over HTTPS just fine.

**Comment by segiddins** [comment]
It's a backwards-incompatible change because it will break existing lockfiles by causing unwanted diffs
