### ISSUE TITLE
Bundler does not work in paths that contain ":" (the colon character)

### ISSUE THREAD

**Issue by glebm** [bundler/bundler#5485]
Not sure if the culprit is bundler or rubygems, but:

```console
$ bundle -v
Bundler version 1.14.5
$ pwd
/var/www/mlforums/versions/2017-02-28T23:35:32.512069Z
$ cat .bundle/config
---
BUNDLE_FROZEN: "1"
BUNDLE_PATH: "vendor/bundle"
BUNDLE_JOBS: "2"
BUNDLE_WITHOUT: "development:test"
BUNDLE_DISABLE_SHARED_GEMS: "true"
$ bundle exec gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 2.6.8
  - RUBY VERSION: 2.4.0 (2016-12-24 patchlevel 0) [x86_64-linux]
  - INSTALLATION DIRECTORY: /var/www/mlforums/versions/2017-02-28T23:35:32.512069Z/vendor/bundle/ruby/2.4.0
  - USER INSTALLATION DIRECTORY: /home/mlforums/.gem/ruby/2.4.0
  - RUBY EXECUTABLE: /home/mlforums/.rbenv/versions/2.4.0/bin/ruby
  - EXECUTABLE DIRECTORY: /var/www/mlforums/versions/2017-02-28T23:35:32.512069Z/vendor/bundle/ruby/2.4.0/bin
  - SPEC CACHE DIRECTORY: /home/mlforums/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /home/mlforums/.rbenv/versions/2.4.0/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /var/www/mlforums/versions/2017-02-28T23:35:32.512069Z/vendor/bundle/ruby/2.4.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /var/www/mlforums/versions/2017-02-28T23
     - 35
     - 32.512069Z/vendor/bundle/ruby/2.4.0/bin
     - /var/www/mlforums/versions/2017-02-28T23
     - 35
     - 32.512069Z/vendor/bundle/ruby/2.4.0/bin
     - /home/mlforums/.rbenv/versions/2.4.0/bin
     - /home/mlforums/.rbenv/libexec
     - /home/mlforums/.rbenv/plugins/ruby-build/bin
     - /home/mlforums/.rbenv/shims
     - /home/mlforums/.rbenv/bin
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/sbin
     - /usr/bin
     - /sbin
     - /bin
     - /usr/games
     - /usr/local/games
```

Note the `SHELL PATH` above.

`bundle exec` then fails:

```console
$ bundle install -j2 --path vendor/bundle --deployment --without development test
$ bundle exec puma
bundler: command not found: puma
Install missing gem executables with `bundle install`
```

If I rename the directory to not contain `:`, `bundle exec puma` succeeds

**Comment by segiddins** [comment]
Is `:` the path separator on your system? ie. `ruby -e "puts File::PATH_SEPARATOR"`

**Comment by glebm** [comment]
Yes

**Comment by segiddins** [comment]
Then you'd need to escape the `:` in your path if you don't want it to represent a path separator -- but I don't even know if that will work i.e. for a shell?

**Comment by glebm** [comment]
I think that SHELL PATH entry is added by bundler and bundler does not escape it?
Another interesting observation is that bundler seems to add the entry twice.

**Comment by segiddins** [comment]
What is the output of `echo $PATH`?

**Comment by glebm** [comment]
```
$ echo $PATH
/home/mlforums/bin:/home/mlforums/.local/bin:/home/mlforums/.rbenv/shims:/home/mlforums/.rbenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
```

**Comment by segiddins** [comment]
@colby-swandale any thoughts on the UX for this?

**Comment by colby-swandale** [comment]
Do we want to raise an error and return non-zero code if `pwd` contains an `:` or just raise a warning saying stuff may break?

**Comment by glebm** [comment]
@colby-swandale +1 on the first options, however please not that it's not the `pwd` that contains the `:` in my example, it's the bundle path (`vendor/bundle`, `.bundle`, etc)

**Comment by colby-swandale** [comment]
@glebm sorry my bad, you're right.

**Comment by ajwann** [comment]
Hey guys, I'd like to take a crack at this. I do have one question before I get started though, in @glebm's bundle config, several paths contain a ```:```  character. Do we only care about the bundle bin path? It seems to me that we would want to return an error if any path contained a ```:```.

**Comment by ajwann** [comment]
If I understand the problem correctly, we just need to take a look at the rubygems bin directory path (```Gem.binder```) when the user calls ```bundle exec```, and exit with a non-zero status code an warning message.

I've made some changes to the ```exec``` method in ```cli.rb```, and put up a [test branch](https://github.com/ajwann/bundler/blob/warn-if-path-contains-colon/lib/bundler/cli.rb#L390).

I'd love some feedback about whether or not I'm on the right track.

**Comment by colby-swandale** [comment]
Hi @ajwann thanks for helping out!

> Do we only care about the bundle bin path?

Yes because the `PATH`  env var uses the `:` char as a separator,  bundle install will work as usual

> It seems to me that we would want to return an error if any path (or perhaps just the results of pwd or echo $PATH) contained a :.

I suggest just checking if the `bundle path` contains the `:` char and raise an error there. See https://github.com/bundler/bundler/blob/master/lib/bundler/shared_helpers.rb#L272
