### ISSUE TITLE
Uninitialized constant Bundler

### ISSUE THREAD

**Issue by hawkish** [bundler/bundler#5488]
The issue solved in 1.13.4: fix for **uninitialized constant Bundler::Plugin::API::Source error** has been reintroduced. I'm getting the very same error with the newest version 1.14.5 - and if I delete 1.14.5 and revert to version 1.13.4, the lane succeeds without error.

In my case I get the error using fastlane with the cocoapods action.

**Comment by segiddins** [comment]
It should be fixed on bundler master right now

**Comment by colby-swandale** [comment]
Bundler `1.14.6` was just released to Rubygems which addresses this issue.
