### ISSUE TITLE
NameError for Resolv::IPv4 after 1.14.5 upgrade

### ISSUE THREAD

**Issue by eserdiouk-primex** [bundler/bundler#5489]
After the upgrade to 1.14.5, our ActiveRecord subclasses started throwing errors for Resolv::IPv4 references. For instance, given a "Device" subclass:

class Device < ActiveRecord::Base

a statement:

validates_format_of :primary_network_ip_address, with: Resolv::IPv4::Regex, allow_nil: true

triggers an error:
"Unable to load application: NameError: uninitialized constant Device::Resolv"

An explicit "include" for "Resolv" fixes the problem. However, it worked fine without such "include" in 1.14.4.

**Comment by segiddins** [comment]
Do you require Resolv anywhere in your application?

**Comment by agoodno** [comment]
(I work with @eserdiouk-primex and I'm following up on this issue) This error is coming from a Rails 4.1.5 application running on Ruby 2.1.1. We don't explicitly require Resolv anywhere because it comes from the standard library. https://ruby-doc.org/stdlib-2.1.1/libdoc/resolv/rdoc/Resolv/IPv4.html

**Comment by segiddins** [comment]
You still need to require things in the standard library, ruby doesn't provide all those features by default

**Comment by agoodno** [comment]
Be that as it may, that doesn't answer the question about what changed from one bundler version to the other.

**Comment by segiddins** [comment]
For Ruby 2.5 compatibility, we have to avoid eagerly requiring more things, because more and more of the stdlib is being gem-ified

**Comment by agoodno** [comment]
Understood. Thanks.
