### ISSUE TITLE
fatal: No live threads left. Deadlock?

### ISSUE THREAD

**Issue by donmayun** [bundler/bundler#5491]
fatal: No live threads left. Deadlock?
2 threads, 2 sleeps current:0x000000013905d0 main thread:0x000000013905d0
* #<Thread:0x000000013c3998 sleep_forever>
   rb_thread_t:0x000000013905d0 native:0x007f6d6316c700 int:0
   /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.5/lib/bundler/worker.rb:43:in `pop'
   /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.5/lib/bundler/worker.rb:43:in `deq'
   /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.5/lib/bundler/installer/parallel_installer.rb:131:in `process_specs'
   /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.5/lib/bundler/installer/parallel_installer.rb:102:in `call'
   /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.5/lib/bundler/installer/parallel_installer.rb:77:in `call'
   /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.5/lib/bundler/installer.rb:199:in `install_in_parallel'
   /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.5/lib/bundler/installer.rb:166:in `install'
   /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.5/lib/bundler/installer.rb:80:in `run'
   /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.5/lib/bundler/installer.rb:24:in `install'
   /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.5/lib/bundler/cli/install.rb:70:in `run'
   /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.5/lib/bundler/cli.rb:181:in `block in install'
   /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.5/lib/bundler/settings.rb:99:in `temporary'
   /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.5/lib/bundler/cli.rb:180:in `install'
   /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
   /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
   /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.5/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
   /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.5/lib/bundler/cli.rb:20:in `dispatch'
   /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.5/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
   /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.5/lib/bundler/cli.rb:11:in `start'
   /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.5/exe/bundle:32:in `block in <top (required)>'
   /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.5/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
   /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.5/exe/bundle:24:in `<top (required)>'
   /usr/local/rvm/gems/ruby-2.4.0/bin/bundle:22:in `load'
   /usr/local/rvm/gems/ruby-2.4.0/bin/bundle:22:in `<main>'
   /usr/local/rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
   /usr/local/rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'
* #<Thread:0x0000000934f9f0@Parallel Installer Worker #0@/usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.5/lib/bundler/worker.rb:88 sleep_forever>
   rb_thread_t:0x00000009351ef0 native:0x007f6d5506d700 int:0
   /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.5/lib/bundler/worker.rb:56:in `pop'
   /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.5/lib/bundler/worker.rb:56:in `block in process_queue'
   /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.5/lib/bundler/worker.rb:55:in `loop'
   /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.5/lib/bundler/worker.rb:55:in `process_queue'
   /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.5/lib/bundler/worker.rb:88:in `block (2 levels) in create_threads'

  /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.5/lib/bundler/worker.rb:43:in `pop'
  /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.5/lib/bundler/worker.rb:43:in `deq'
  /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.5/lib/bundler/installer/parallel_installer.rb:131:in `process_specs'
  /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.5/lib/bundler/installer/parallel_installer.rb:102:in `call'
  /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.5/lib/bundler/installer/parallel_installer.rb:77:in `call'
  /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.5/lib/bundler/installer.rb:199:in `install_in_parallel'
  /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.5/lib/bundler/installer.rb:166:in `install'
  /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.5/lib/bundler/installer.rb:80:in `run'
  /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.5/lib/bundler/installer.rb:24:in `install'
  /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.5/lib/bundler/cli/install.rb:70:in `run'
  /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.5/lib/bundler/cli.rb:181:in `block in install'
  /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.5/lib/bundler/settings.rb:99:in `temporary'
  /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.5/lib/bundler/cli.rb:180:in `install'
  /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
  /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.5/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
  /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.5/lib/bundler/cli.rb:20:in `dispatch'
  /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.5/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
  /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.5/lib/bundler/cli.rb:11:in `start'
  /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.5/exe/bundle:32:in `block in <top (required)>'
  /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.5/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
  /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.5/exe/bundle:24:in `<top (required)>'
  /usr/local/rvm/gems/ruby-2.4.0/bin/bundle:22:in `load'
  /usr/local/rvm/gems/ruby-2.4.0/bin/bundle:22:in `<main>'
  /usr/local/rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
  /usr/local/rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'
```

## Environment

```
Bundler   1.14.5
Rubygems  2.6.10
Ruby      2.4.0p0 (2016-12-24 revision 57164) [x86_64-linux]
GEM_HOME  /usr/local/rvm/gems/ruby-2.4.0
GEM_PATH  /usr/local/rvm/gems/ruby-2.4.0:/usr/local/rvm/gems/ruby-2.4.0@global
RVM       1.29.1 (latest)
Git       1.7.1
Platform  x86_64-linux
OpenSSL   OpenSSL 1.0.1e 11 Feb 2013
rubygems-bundler (1.4.4)
```

## Bundler settings

**Comment by donmayun** [comment]
Gemfile


source 'https://rubygems.org'

if Gem::Version.new(Bundler::VERSION) < Gem::Version.new('1.5.0')
  abort "Redmine requires Bundler 1.5.0 or higher (you're using #{Bundler::VERSION}).\nPlease update with 'gem update bundler'."
end

gem "rails", "4.2.7.1"
gem "addressable", "2.4.0" if RUBY_VERSION < "2.0"
gem "jquery-rails", "~> 3.1.4"
gem "coderay", "~> 1.1.1"
gem "builder", ">= 3.0.4"
gem "request_store", "1.0.5"
gem "mime-types", (RUBY_VERSION >= "2.0" ? "~> 3.0" : "~> 2.99")
gem "protected_attributes"
gem "actionpack-action_caching"
gem "actionpack-xml_parser"
gem "roadie-rails"
gem "mimemagic"

**Comment by kburman** [comment]
I had a similar issue today. I have tried changing bundler but no effect.
Then I tried running
`bundle --jobs=1`
Same error again. So I ran 
`bundle check`
then installed the missing dependencies
`gem install ...`
then I ran `bundle install` it worked

**Comment by donmayun** [comment]
Not work yet.
After `bundle check`,I installed 'rbpdf 1.9.0', then I `bundle instll`, but it's still report this issue!

**Comment by donmayun** [comment]
I think i solve my issue but this one.
I uninstalled rvm  with any version ,and reinstall one stable versin `2.2.6`，at last `bundle install `,it worked!
