### ISSUE TITLE
NoMethodError: undefined method `<' for nil:NilClass

### ISSUE THREAD

**Issue by marcskms** [bundler/bundler#5497]
NoMethodError: undefined method `<' for nil:NilClass
  /Users/marcsimiakos/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.5/lib/bundler/definition.rb:309:in `lock'
  /Users/marcsimiakos/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.5/lib/bundler/installer.rb:230:in `lock'
  /Users/marcsimiakos/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.5/lib/bundler/installer.rb:82:in `run'
  /Users/marcsimiakos/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.5/lib/bundler/installer.rb:24:in `install'
  /Users/marcsimiakos/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.5/lib/bundler/cli/install.rb:70:in `run'
  /Users/marcsimiakos/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.5/lib/bundler/cli.rb:181:in `block in install'
  /Users/marcsimiakos/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.5/lib/bundler/settings.rb:99:in `temporary'
  /Users/marcsimiakos/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.5/lib/bundler/cli.rb:180:in `install'
  /Users/marcsimiakos/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /Users/marcsimiakos/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
  /Users/marcsimiakos/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.5/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
  /Users/marcsimiakos/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.5/lib/bundler/cli.rb:20:in `dispatch'
  /Users/marcsimiakos/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.5/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
  /Users/marcsimiakos/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.5/lib/bundler/cli.rb:11:in `start'
  /Users/marcsimiakos/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.5/exe/bundle:32:in `block in <top (required)>'
  /Users/marcsimiakos/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.5/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
  /Users/marcsimiakos/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.5/exe/bundle:24:in `<top (required)>'
  /Users/marcsimiakos/.rbenv/versions/2.3.3/bin/bundle:22:in `load'
  /Users/marcsimiakos/.rbenv/versions/2.3.3/bin/bundle:22:in `<main>'
```

## Environment

```
Bundler   1.14.5
Rubygems  2.5.2
Ruby      2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin16]
GEM_HOME  /Users/marcsimiakos/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0
GEM_PATH  /Users/marcsimiakos/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0:/Users/marcsimiakos/.gem/ruby/2.3.0
Git       2.12.0
Platform  x86_64-darwin-16
OpenSSL   OpenSSL 1.0.2k  26 Jan 2017
```
```

--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/bundler/bundler/search?q=undefined+method+%60%3C%27+for+nil+NilClass&type=Issues

If there aren't any reports for this error yet, please create copy and paste the report template above into a new issue. Don't forget to anonymize any private data! The new issue form is located at:
https://github.com/bundler/bundler/issues/new

**Comment by Gauravano** [comment]
hi @marcskms I have encountered the same error. Can you share how you resolved it? Thanks.

**Comment by amitsin6h** [comment]
@Gauravano are you able to solve? same error with me
