### ISSUE TITLE
More semantic colors in bundle update

### ISSUE THREAD

**Issue by brchristian** [bundler/bundler#5506]
One thing I have noticed in recent versions of bundler is helpful colors in the command line. Overall I think this is great. However I noticed that the comparison of old gems to new ones is green _even when the gem version is regressing_. Here’s a screenshot:

<img width="310" alt="screen shot 2017-03-07 at 11 18 46 am" src="https://cloud.githubusercontent.com/assets/2460418/23673674/000a31e2-0328-11e7-9869-a64d3d368ab2.png">

Notice that all of these gems have gone backwards!

I would suggest a color like yellow/amber for all decrementing gems, as this will (I think appropriately) direct the user’s attention to these items and make sure that there are not any unintentional regressions.

Happy to submit a PR if there is interest in this.

**Comment by segiddins** [comment]
I think this would be really cool!

**Comment by indirect** [comment]
👍

**Comment by colby-swandale** [comment]
closing this, use the PR instead for any feedback.

**Comment by segiddins** [comment]
We'll close the feature request when the PR is merged
