### ISSUE TITLE
Add Code of Conduct content to README template

### ISSUE THREAD

**Issue by robcole** [bundler/bundler#5512]
When the Code of Conduct is set to be included when creating a new gem, 
it would be helpful to additionally have this added to the README, using similar 
language as Bundler and other gem's (rails, etc) language. This helps 
raise the visibility of the Code of Conduct in gems where it is included.

**Comment by robcole** [comment]
Hey bundler team, sorry for the confusion here. I was trying to follow https://github.com/bundler/bundler/blob/master/doc/development/NEW_FEATURES.md for this, but the inability to add tags to issues made me uncertain if we're supposed to create the issue on the main repo on our fork. So I did both.

Hope the test case here and the general direction are something that works as a simple feature request - this stemmed from a recent discussion with a few other rubyists, and we were curious why the Code of Conduct is included, but not referenced in the README in the same way it is on the bundler page, the rails page, and others.

**Comment by snuggs** [comment]
I think this is a great addition @robcole! 👍 . I got a CoC in my new gem project. Possibly I set some global feature a while back. I thought it was bundler. ¯\_(ツ)_/¯

**Comment by segiddins** [comment]
👍🏻 sounds like a good idea
