### ISSUE TITLE
bundler-1.14.6, Could not find gem 'jdbc-mysql' in any of the gem sources listed in your Gemfile. (Bundler::GemNotFound)

### ISSUE THREAD

**Issue by Amand** [bundler/bundler#5528]
Hi,

I re-installed the environment and got the new bundler version-1.14.6. Same script was working with no issues before this update. There is a jdbc-mysql gem installed for jruby but execution still throws an error- 

/opt/jruby/jruby-9.0.5.0/lib/ruby/gems/shared/gems/bundler-1.14.6/lib/bundler/resolver.rb:386:in `block in verify_gemfile_dependencies_are_found!': Could not find gem 'jdbc-mysql' in any of the gem sources listed in your Gemfile. (Bundler::GemNotFound)

Here are more details:
JRuby Gems*********************************************
+ jruby -S gem list
builder (3.2.3)
bundler (1.14.6)
childprocess (0.6.2)
connection_pool (2.2.1)
cucumber (2.4.0)
cucumber-core (1.5.0)
cucumber-wire (0.0.1)
data_magic (1.0)
diff-lcs (1.3)
domain_name (0.5.20170223)
faker (1.7.3)
ffi (1.9.18 java)
fig_newton (0.14)
fire_poll (1.2.0)
gherkin (4.0.0)
headless (2.3.1)
http-cookie (1.0.3)
i18n (0.8.1)
jar-dependencies (0.2.3)
jdbc-mysql (5.1.40)
jruby-openssl (0.9.15 java)
json (2.0.3 java, 1.8.0 java)
jwt (1.5.6)
mime-types (3.1)
mime-types-data (3.2016.0521)
minitest (5.4.1)
multi_json (1.12.1)
multi_test (0.1.2)
net-http-persistent (3.0.0)
netrc (0.11.0)
nokogiri (1.7.0.1 java)
page-object (2.1.1)
page_navigation (0.10)
power_assert (0.2.3)
psych (2.0.15 java)
racc (1.4.13 java)
rake (12.0.0, 10.1.0)
rdoc (4.1.2)
rest-client (2.0.1)
rspec (3.5.0)
rspec-core (3.5.4)
rspec-expectations (3.5.0)
rspec-mocks (3.5.0)
rspec-support (3.5.0)
rubyzip (1.2.1)
selenium-webdriver (3.3.0)
splunk-sdk-ruby (1.0.5)
test-unit (3.0.3)
thread_safe (0.3.6 java)
tzinfo (1.2.2)
unf (0.1.4 java)
watir (6.2.0)
watir-webdriver (0.9.9)
websocket (1.2.4)
yml_reader (0.7)

+ jruby -S bundle env
## Environment

```
Bundler   1.14.6
Rubygems  2.4.8
Ruby      2.2.3p0 (2016-01-26 revision 51636) [java]
Git       2.4.1
Platform  universal-java-1.8
```
```

## Gemfile

### Gemfile

```ruby
source 'https://rubygems.org'

gem 'cucumber'
gem 'rspec'
gem 'json'
gem 'rest-client'
gem 'data_magic'
gem 'jdbc-mysql'
gem 'watir-webdriver'
gem 'splunk-sdk-ruby'
gem 'headless'
gem 'nokogiri'
gem 'fire_poll'
gem 'page-object'
gem 'rake'
gem 'jwt'
```

### Gemfile.lock

```
<No /var/opt/jenkins/workspace/Gemfile.lock found>
```

**Comment by colby-swandale** [comment]
I'm able to install the bundle without any issues.

**Comment by colby-swandale** [comment]
can you update rubygems and let us know if the problem still occurs

**Comment by Amand** [comment]
I tried switching the bundler and rake versions as I am getting this error only when I am executing rake tasks. If I execute same tests without rake it works with no issues. I have tried with bundler versions from 1.13.0 to 1.14.6 and rake version from 11.3.0 to 12.0.0 but getting same issue.

Rake task gives below error complaining about could not find gem -

$ jruby -S rake features:apis
/opt/jruby/jruby-9.0.5.0/bin/jrubyjruby -S bundle exec cucumber features/feature1.feature features/feature2.feature features/feature3.feature features/feature4.feature features/feature5.feature
Could not find gem 'jdbc-mysql' in any of the gem sources listed in your Gemfile or available on this machine.
Run `bundle install` to install missing gems.

If I execute this cmd directly by taking out "bundle exec" from above cmd that rake executes, tests execute with no issues-

/opt/jruby/jruby-9.0.5.0/bin/jrubyjruby -S cucumber features/feature1.feature features/feature2.feature features/feature3.feature features/feature4.feature features/feature5.feature

Not sure if it's rake or bundler issue?

**Comment by colby-swandale** [comment]
have you run `bundle install`? In your first first comment you're missing the Gemfile.lock which tells me you haven't run it?

**Comment by colby-swandale** [comment]
ping @Amand is still a problem for you?

**Comment by colby-swandale** [comment]
I'm closing this for now. If you're still experiencing your original issue don't be afraid to re-open this ticket.

**Comment by nathantech2005** [comment]
Can you re-open this. This is a pretty big deal when it comes to running Jruby.
![screen shot 2018-05-24 at 4 26 05 pm](https://user-images.githubusercontent.com/4573756/40511928-3bf47ab0-5f6f-11e8-90ed-d3308d468413.png)
