### ISSUE TITLE
bundle config local: doesn't use local repo

### ISSUE THREAD

**Issue by perlun** [bundler/bundler#5530]
I am trying to use the `bundle config local` approach to be able to work with a local copy of a gem I am authoring.

Here is the command I've used:

```shell
$ bundle config local.ecraft-web_api ~/git/ecraft/ecraft-web_api/
```

However, `bundle install` doesn't list this path in its output, and `bundle update` doesn't seem to take it in as well.

```
Using ecraft-web_api 2.0.3
```

I added an exception to the first line of the gem, which is not raised, so I'm quite sure it doesn't use my local version of the gem.

My Gemfile (except):

```ruby
source 'https://private-gem-url/' do
  gem 'ecraft-web_api', branch: 'feature/add-authorization-support'         # Version specified in gemspec
end
```

Here is my Bundler and Ruby version:

```shell
$ bundle -v
Bundler version 1.14.6
$ ruby -v
ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin16]
```

**Comment by segiddins** [comment]
You need to use it as a git gem rather than from a RubyGems source, but we definitely should be printing an error for using `branch` with a RubyGems source

**Comment by perlun** [comment]
> You need to use it as a git gem rather than from a RubyGems source

Ah, OK! The use case I have is it is developed as a git gem, but every now and then being published as a Rubygem. But when making changes to the gem, it's nice to be able to tweak the gem locally and test it in its dependant.

Since the GitHub repo in question is private, it makes it harder for CI etc if I would specify the gem source to be the GitHub repo, the CI user will not have access to that repo.

**Comment by segiddins** [comment]
Closed by https://github.com/bundler/bundler/issues/5559

**Comment by perlun** [comment]
Thanks @segiddins and @colby-swandale!
