### ISSUE TITLE
Retrying fetcher due to error (2/4): Net::HTTPServerException 407 "Proxy Authentication Required"

### ISSUE THREAD

**Issue by kanhaiyakr** [bundler/bundler#5535]
Retrying fetcher due to error (2/4): Net::HTTPServerException 407 "Proxy Authentication Required"
Retrying fetcher due to error (3/4): Net::HTTPServerException 407 "Proxy Authentication Required"
Retrying fetcher due to error (4/4): Net::HTTPServerException 407 "Proxy Authentication Required"--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `C:/Ruby22/bin/bundle `

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what happened was...

Error details

    Net::HTTPServerException: 407 "Proxy Authentication Required"
      C:/Ruby22/lib/ruby/2.2.0/net/http/response.rb:119:in `error!'
      C:/Ruby22/lib/ruby/2.2.0/net/http/response.rb:128:in `value'
      C:/Ruby22/lib/ruby/2.2.0/net/http.rb:915:in `connect'
      C:/Ruby22/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
      C:/Ruby22/lib/ruby/2.2.0/net/http.rb:858:in `start'
      C:/Ruby22/lib/ruby/2.2.0/rubygems/request/http_pool.rb:42:in `setup_connection'
      C:/Ruby22/lib/ruby/2.2.0/rubygems/request/https_pool.rb:6:in `setup_connection'
      C:/Ruby22/lib/ruby/2.2.0/rubygems/request/http_pool.rb:38:in `make_connection'
      C:/Ruby22/lib/ruby/2.2.0/rubygems/request/http_pool.rb:19:in `checkout'
      C:/Ruby22/lib/ruby/2.2.0/rubygems/request.rb:85:in `connection_for'
      C:/Ruby22/lib/ruby/2.2.0/rubygems/request.rb:140:in `perform_request'
      C:/Ruby22/lib/ruby/2.2.0/rubygems/request.rb:109:in `fetch'
      C:/Ruby22/lib/ruby/2.2.0/rubygems/remote_fetcher.rb:352:in `request'
      C:/Ruby22/lib/ruby/2.2.0/rubygems/remote_fetcher.rb:237:in `fetch_http'
      C:/Ruby22/lib/ruby/2.2.0/rubygems/remote_fetcher.rb:273:in `fetch_path'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/lib/bundler/rubygems_integration.rb:668:in `fetch_specs'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/lib/bundler/rubygems_integration.rb:678:in `fetch_all_remote_specs'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/lib/bundler/fetcher/index.rb:9:in `specs'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/lib/bundler/fetcher.rb:128:in `block in specs'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/lib/bundler/fetcher.rb:127:in `each'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/lib/bundler/fetcher.rb:127:in `specs'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/lib/bundler/fetcher.rb:112:in `block in specs_with_retry'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/lib/bundler/retry.rb:39:in `call'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/lib/bundler/retry.rb:39:in `run'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/lib/bundler/retry.rb:29:in `attempt'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/lib/bundler/fetcher.rb:111:in `specs_with_retry'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/lib/bundler/source/rubygems.rb:342:in `block (2 levels) in remote_specs'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/lib/bundler/source/rubygems.rb:340:in `each'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/lib/bundler/source/rubygems.rb:340:in `block in remote_specs'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/lib/bundler/index.rb:10:in `build'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/lib/bundler/source/rubygems.rb:336:in `remote_specs'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/lib/bundler/source/rubygems.rb:83:in `specs'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/lib/bundler/definition.rb:261:in `block (2 levels) in index'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/lib/bundler/definition.rb:259:in `each'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/lib/bundler/definition.rb:259:in `block in index'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/lib/bundler/index.rb:10:in `build'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/lib/bundler/definition.rb:256:in `index'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/lib/bundler/definition.rb:250:in `resolve'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/lib/bundler/definition.rb:174:in `specs'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/lib/bundler/definition.rb:162:in `resolve_remotely!'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/lib/bundler/installer.rb:225:in `resolve_if_need'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/lib/bundler/installer.rb:78:in `run'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/lib/bundler/installer.rb:24:in `install'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/lib/bundler/cli/install.rb:71:in `run'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/lib/bundler/cli.rb:189:in `install'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/lib/bundler/cli.rb:20:in `dispatch'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/lib/bundler/cli.rb:11:in `start'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/exe/bundle:34:in `block in <top (required)>'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
      C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.13.7/exe/bundle:26:in `<top (required)>'
      C:/Ruby22/bin/bundle:23:in `load'
      C:/Ruby22/bin/bundle:23:in `<main>'

Environment

  Bundler   1.13.7
  Rubygems  2.4.5.2
  Ruby      2.2.6p396 (2016-11-15 revision 56800) [i386-mingw32]
  GEM_HOME  C:/Ruby22/lib/ruby/gems/2.2.0
  GEM_PATH  C:/Ruby22/lib/ruby/gems/2.2.0;C:/Users/ee209816/.gem/ruby/2.2.0
  Git       2.11.0.windows.1

      Bundler settings

  git.allow_insecure
    Set for the current user (C:/Users/ee209816/.bundle/config): "true"
  without
    Set for your local app (D:/New folder/LiveServer/redmine-3.3.2/.bundle/config): "development:xapian:rmagick"
--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/bundler/bundler/search?q=407+%22Proxy+Authentication+Required%22&type=Issues

If there aren't any reports for this error yet, please create copy and paste the report template above into a new issue. Don't forget to anonymize any private data! The new issue form is located at:
https://github.com/bundler/bundler/issues/new

**Comment by colby-swandale** [comment]
Are you behind any network proxy?

**Comment by colby-swandale** [comment]
ping @kanhaiyakr

**Comment by colby-swandale** [comment]
I'm closing this for now. If you're still experiencing your original issue don't be afraid to re-open this ticket.
