### ISSUE TITLE
bundler installs wrong platform specific gem for sys-proctable

### ISSUE THREAD

**Issue by djberg96** [bundler/bundler#5536]
Bundler version 1.14.6
Darwin Kernel Version 15.6.0
ruby 2.3.1p112

```
>gem install sys-proctable

Unable to use the platform-specific (universal-darwin) version of sys-proctable (1.1.3) because it has different dependencies from the universal-aix5 version. To use the platform-specific version of the gem, run `bundle config specific_platform true` and install again.
Installing sys-proctable 1.1.3 (universal-aix5)
Using bundler 1.14.6
Bundle complete! 1 Gemfile dependency, 2 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
```

I have no idea what the thinking is here, but it's not correct. It certainly shouldn't be installing the AIX gem for Darwin.

Each platform for the sys-proctable gem has a specific, universal gem. This is for two reasons - first, different platforms have different dependencies. Notably, some require `ffi` while others do not. Secondly, one of the platforms (HP-UX) is a C extension. When I create each gem, it only contains the files it needs for the platform, not every file for every platform.

Note that this does not happen in 1.13.x.

**Comment by jrafanie** [comment]
Here's an example [gist](https://gist.github.com/jrafanie/593a16e55f65e1b6e0fb25681e2f073a) with ruby 2.4.1 and bundler 1.14.6

**Comment by segiddins** [comment]
What's the output of `bundle env` and why do you believe this behavior is incorrect and are you looking for the `specific_platform` flag?

**Comment by djberg96** [comment]
```
bundle env

Bundler   1.14.6
Rubygems  2.6.6
Ruby      2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
Git       2.9.2
Platform  x86_64-darwin-15
```

However, after upgrading to Rubygems 2.6.11, the error changes to:

```
>bundle install
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/.
Could not find sys-proctable-1.1.3-universal-aix-5 in any of the sources
```

So, with an updated version of Rubygems, at least it doesn't install the older version. However, it should "just work", since the platform information is in the gem spec.

**Comment by segiddins** [comment]
That's not the full env output? I'm not seeing e.g. The lockfile and gemfile

**Comment by djberg96** [comment]
@segiddins I've updated the output. I also noticed that with Bundler 1.13.x I get:

Your Gemfile.lock is corrupt. The following gem is missing from the DEPENDENCIES section: 'fyi'. Which is odd since I don't have a Gemfile.lock.

**Comment by caseyhelbling** [comment]
Under bundler version 1.14.3, I noticed this issue as well. There is also some weirdness in that it toggles the Gemfile.lock version between two formats... 

```
-    sys-proctable (1.1.3-universal-aix-5)
+    sys-proctable (1.1.3-universal-aix5)
```

bundle install on a different system with Bundler version 1.13.7 I also get Gefile.lock is corrupt...

**Comment by endlos** [comment]
As a workaround this tells bundle to use the platform-specific version of the gem: 
`bundle config specific_platform true`
Then install again and it should work.

**Comment by djberg96** [comment]
@endlos Thanks, I've added a note in the README for now.

**Comment by paddor** [comment]
Bundler puts `    sys-proctable (1.1.4-universal-aix-5)` into my Gemfile.lock as well, although it's Linux and the actually installed gem is:

```
$ gem list sys-proctable

*** LOCAL GEMS ***

sys-proctable (1.1.4 universal-linux)
```

I did `bundle config linux true` and even changed my Gemfile.lock to contain `sys-proctable (1.1.4-universal-linux)`, but when I run `bundle update`, it reverts back to `sys-proctable (1.1.4-universal-aix-5)`.

In an `bundle exec irb`, `require 'sys/proctable'; Sys::ProcTable.ps` works though. So should I ignore it?

**Comment by segiddins** [comment]
yes

**Comment by pglombardo** [comment]
Unfortunately I'm also having this problem fairly consistently (at least only locally so far).  Happens on my Mac and on Ubuntu running in a VMWare VM.

`bundle env` output:
https://gist.github.com/pglombardo/6a92942b3aadf3eeeddd85f155896487

Happening for this gem which has sys-proctable as a gemspec dependency: https://github.com/instana/ruby-sensor

Thanks for the great gems both bundler & sys-proctable.

**Comment by segiddins** [comment]
Closing because `specific_platform` fixes the issue, and it will become the default behavior imminently.

**Comment by pglombardo** [comment]
@segiddins Unfortunately, in the current version of bundler `1.15.4`, `specific_platform` doesn't fix the issue:
<img width="609" alt="screen shot 2017-09-08 at 20 18 39" src="https://user-images.githubusercontent.com/395132/30225568-3c1f0454-94d3-11e7-9a2c-f97349cae4dc.png">

Do you mean that this will work in an upcoming version?

**Comment by segiddins** [comment]
@pglombardo what's not working?

**Comment by pglombardo** [comment]
The problem identified in this issue

> bundler installs wrong platform specific gem for sys-proctable

and the "fix" you stated

> Closing because `specific_platform` fixes the issue, and it will become the default behavior imminently.

I tried using `specific_platform` with latest bundler release [to no avail](https://github.com/bundler/bundler/issues/5536#issuecomment-328178421).

Am I missing something?
