### ISSUE TITLE
bundler: failed to load command: rspec (/usr/local/bin/rspec) Gem::Exception: can't find executable rspec

### ISSUE THREAD

**Issue by shwethamn** [bundler/bundler#5537]
bundler: failed to load command: rspec (/usr/local/bin/rspec)
Gem::Exception: can't find executable rspec
  /var/lib/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/rubygems_integration.rb:408:in `block in replace_bin_path'
  /var/lib/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/rubygems_integration.rb:425:in `block in replace_bin_path'
  /usr/local/bin/rspec:22:in `<top (required)>'

**Comment by shwethamn** [comment]
Rename the Gemfile.lock and done bundle install. still the problem is not solved. Can anyone help me for this problem . i am unable to run "bundle exec rspec

**Comment by segiddins** [comment]
What is the output of `bundle env`?

**Comment by shwethamn** [comment]
bundler: failed to load command: rspec (/usr/local/bin/rspec)
Gem::Exception: can't find executable rspec

/var/lib/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/rubygems_integration.rb:409:in
`block in replace_bin_path'

/var/lib/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/rubygems_integration.rb:426:in
`block in replace_bin_path'
  /usr/local/bin/rspec:22:in `<top (required)>'


Thanks and Regards
Shwetha M N

**Comment by segiddins** [comment]
@shwethamn please share the output of `bundle env`

**Comment by colby-swandale** [comment]
I'm closing this for now. If you're still experiencing your original issue don't be afraid to re-open this ticket.

**Comment by benoittgt** [comment]
Hello. I'm having quite similar issue on circleci.

When I connect on ssh on circleci : 
```sh
$ bundle env
## Environment

Bundler   1.15.4
Rubygems  2.6.12
Ruby      2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
GEM_HOME  /usr/local/bundle
GEM_PATH
Git       2.1.4
Platform  x86_64-linux
OpenSSL   OpenSSL 1.0.1t  3 May 2016
```

My command:
```sh
#!/bin/bash -eo pipefail
pwd
mkdir /tmp/test-results
TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"
bundle exec rspec --format progress \
                --format RspecJunitFormatter \
                --out /tmp/test-results/rspec.xml \
                --format progress \
                $TEST_FILES

/home/circleci/appaloosa
Run options: --seed 21195
/home/circleci/appaloosa/spec/services/***_service/***/service_builder_spec.rb:3: warning: toplevel constant *** referenced by **Service::***
bundler: failed to load command: rspec (/home/circleci/appaloosa/vendor/bundle/ruby/2.4.0/bin/rspec)
NameError: uninitialized constant ***::ServiceBuilder
  /home/circleci/appaloosa/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.1.2/lib/bootsnap/load_path_cache/core_ext/active_support.rb:53:in `block in load_missing_constant'
  /home/circleci/appaloosa/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.1.2/lib/bootsnap/load_path_cache/core_ext/active_support.rb:11:in `block in with_bootsnap_fallback'
...
```

So `bundler: failed to load command: rspec (/home/circleci/appaloosa/vendor/bundle/ruby/2.4.0/bin/rspec)` but when I connect with ssh on the machine I have no issue to run the test. Is their a way to understand what is happening?

**Comment by colby-swandale** [comment]
@benoittgt please open a new issue with the details of your problem, you can find more details in our [ISSUES](https://github.com/bundler/bundler/blob/master/doc/contributing/ISSUES.md) guide.
