### ISSUE TITLE
incompatible library

### ISSUE THREAD

**Issue by smithWEBtek** [bundler/bundler#5543]
## Environment

```
Bundler   1.14.6
Rubygems  2.6.10
Ruby      2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin16]
GEM_HOME  /Users/BradSmith/.rvm/gems/ruby-2.3.0
GEM_PATH  /Users/BradSmith/.rvm/gems/ruby-2.3.0:/Users/BradSmith/.rvm/gems/ruby-2.3.0@global
RVM       1.29.1 (latest)
Git       2.6.2
Platform  x86_64-darwin-16
OpenSSL   OpenSSL 1.0.2k  26 Jan 2017
rubygems-bundler (1.4.4)
```

## Bundler settings

```
gem.test
  Set for the current user (/Users/BradSmith/.bundle/config): "rspec"
gem.mit
  Set for the current user (/Users/BradSmith/.bundle/config): "true"
gem.coc
  Set for the current user (/Users/BradSmith/.bundle/config): "true"
```

--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/bundler/bundler/search?q=incompatible+library+version+-+%2FUsers%2FBradSmith%2F.rvm%2Fgems%2Fruby-2.3.0%2Fgems%2Fpsych-2.2.4%2Flib%2Fpsych.bundle&type=Issues

If there aren't any reports for this error yet, please create copy and paste the report template above into a new issue. Don't forget to anonymize any private data! The new issue form is located at:
https://github.com/bundler/bundler/issues/new

**Comment by colby-swandale** [comment]
Please follow [ISSUES](https://github.com/bundler/bundler/blob/master/doc/contributing/ISSUES.md) on how to correctly report an issue with Bundler.

**Comment by smithWEBtek** [comment]
thanks for quick reply, sorry I was in a hurry and just pasted in the response from console.  I got some help from another developer who helped me navigate reinstalling my gemset among other things. I'm not exactly sure of the root cause, but I'm back up and running now.
