### ISSUE TITLE
WPSCAN:  > [!] undefined method `cells' for #<Array:0x00000002d54ba0>

### ISSUE THREAD

**Issue by faun88** [bundler/bundler#5544]
Whilst trying to run WPSCAN but encountered the following error every time:

> [!] undefined method `cells' for #<Array:0x00000002d54ba0>

After some googling, I tried to install bundler by using the following commands:
```
gem install bundler
bundle install --without test
```

But unfortunatly, I receive the error below:

> -- ERROR REPORT TEMPLATE -------------------------------------------------------
> - What did you do?
> 
>   I ran the command `/usr/bin/bundle install --without test`
> 
> - What did you expect to happen?
> 
>   I expected Bundler to...
> 
> - What happened instead?
> 
>   Instead, what actually happened was...
> 
> 
> Error details
> 
>     NoMethodError: private method `name_for' called for #<Bundler::Resolver:0x000000041d5610>
>       /usr/lib/ruby/vendor_ruby/molinillo/delegates/specification_provider.rb:31:in `block in name_for'
>       /usr/lib/ruby/vendor_ruby/molinillo/delegates/specification_provider.rb:69:in `with_no_such_dependency_error_handling'
>       /usr/lib/ruby/vendor_ruby/molinillo/delegates/specification_provider.rb:30:in `name_for'
>       /usr/lib/ruby/vendor_ruby/molinillo/resolution.rb:161:in `block (2 levels) in initial_state'
>       /usr/lib/ruby/vendor_ruby/molinillo/resolution.rb:161:in `each'
>       /usr/lib/ruby/vendor_ruby/molinillo/resolution.rb:161:in `block in initial_state'
>       /usr/lib/ruby/vendor_ruby/molinillo/resolution.rb:160:in `tap'
>       /usr/lib/ruby/vendor_ruby/molinillo/resolution.rb:160:in `initial_state'
>       /usr/lib/ruby/vendor_ruby/molinillo/resolution.rb:106:in `start_resolution'
>       /usr/lib/ruby/vendor_ruby/molinillo/resolution.rb:64:in `resolve'
>       /usr/lib/ruby/vendor_ruby/molinillo/resolver.rb:42:in `resolve'
>       /usr/lib/ruby/vendor_ruby/bundler/resolver.rb:199:in `start'
>       /usr/lib/ruby/vendor_ruby/bundler/resolver.rb:182:in `resolve'
>       /usr/lib/ruby/vendor_ruby/bundler/definition.rb:200:in `resolve'
>       /usr/lib/ruby/vendor_ruby/bundler/definition.rb:140:in `specs'
>       /usr/lib/ruby/vendor_ruby/bundler/definition.rb:129:in `resolve_remotely!'
>       /usr/lib/ruby/vendor_ruby/bundler/installer.rb:79:in `run'
>       /usr/lib/ruby/vendor_ruby/bundler/installer.rb:18:in `install'
>       /usr/lib/ruby/vendor_ruby/bundler/cli/install.rb:107:in `run'
>       /usr/lib/ruby/vendor_ruby/bundler/cli.rb:162:in `install'
>       /usr/lib/ruby/vendor_ruby/thor/command.rb:27:in `run'
>       /usr/lib/ruby/vendor_ruby/thor/invocation.rb:126:in `invoke_command'
>       /usr/lib/ruby/vendor_ruby/thor.rb:359:in `dispatch'
>       /usr/lib/ruby/vendor_ruby/thor/base.rb:440:in `start'
>       /usr/lib/ruby/vendor_ruby/bundler/cli.rb:10:in `start'
>       /usr/bin/bundle:20:in `block in <main>'
>       /usr/lib/ruby/vendor_ruby/bundler/friendly_errors.rb:7:in `with_friendly_errors'
>       /usr/bin/bundle:18:in `<main>'
> 
> Environment
> 
>     Bundler   1.10.6
>     Rubygems  2.4.5.1
>     Ruby      2.2.4p230 (2015-12-16 revision 0) [x86_64-linux-gnu]
>     GEM_HOME  /var/lib/gems/2.2.0
>     GEM_PATH  /var/lib/gems/2.2.0:/root/.gem/ruby/2.2.0:/usr/lib/x86_64-linux-gnu/rubygems-integration/2.2.0:/usr/share/rubygems-integration/2.2.0:/usr/share/rubygems-integration/2.2:/usr/share/rubygems-integration/all
>     Git       2.11.0
> 
> Bundler settings
> 
>     without
>       Set for your local app (/root/wpscan/.bundle/config): "test"
> --- TEMPLATE END ----------------------------------------------------------------
> 
> Unfortunately, an unexpected error occurred, and Bundler cannot continue.

Anyone knows how to fix this?

Ps:

Kali version: 2016.2
WPscan version 2.9

**Comment by colby-swandale** [comment]
Hi, I suggest updating to the latest version Bundler & RubyGems. Let us know if you're still encountering your problem.

**Comment by colby-swandale** [comment]
ping @faun88

**Comment by faun88** [comment]
To my best knowledge, both were already last versions. I fixed it by installing the latest version of Kali.
