### ISSUE TITLE
`bundle config mirror.https://rubygems.org` not work, but `http` works

### ISSUE THREAD

**Issue by pd4d10** [bundler/bundler#5558]
```sh
bundle config mirror.https://rubygems.org https://rubygems-mirror.org
```

not work, still download packages from rubygems.org. but

```sh
bundle config mirror.http://rubygems.org https://rubygems-mirror.org
```

works.

Is this work as expected?

I found the document at [Bundler documentation](https://bundler.io/v1.14/man/bundle-config.1.html#MIRRORS-OF-GEM-SOURCES). It use `http` when setting `SOURCE_URL`, but use `https` when setting `SOURCE_URL.fallback_timeout`. Feel a little confused.

why not config mirror in this way:

```sh
bundle config mirror.source_url https://rubygems-mirror.org
```

Just curious 😀

## Environment

```
Bundler   1.14.6
Rubygems  2.5.1
Ruby      2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
Git       2.11.0
Platform  x86_64-darwin-15
```

**Comment by colby-swandale** [comment]
Sorry you're having trouble with Bundler, Is there any more information you can share? Using `https` in the source and the mirror url does work.

What's the output of `bundle config` ?

**Comment by colby-swandale** [comment]
This works as expected for me:

```
› bundle config
Settings are listed in order of priority. The top value will be used.
mirror.https://rubygems.org/
Set for the current user (/Users/c/.bundle/config): "https://gems.ruby-china.org"

disable_shared_gems
Set for your local app (/Users/c/Desktop/Projects/testapp/.bundle/config): "1"

› GEM_PATH=test BUNDLE_PATH=test bundle install
Fetching gem metadata from https://gems.ruby-china.org/...
Fetching version metadata from https://gems.ruby-china.org/..
Installing rack 1.6.5
Using bundler 1.14.6
Bundle complete! 1 Gemfile dependency, 2 gems now installed.
Bundled gems are installed into ./test.
›
```

Can you paste the output of `bundle install --verbose`

Do you have any fallback sources configured? ie: fallback to `rubygems.org`?

**Comment by pd4d10** [comment]
I think maybe I've understand how `bundle config` works

My project's `Gemfile`:
```
source 'http://rubygems.org'
gem 'scss_lint'
```

This command:
```sh
bundle config mirror.https://rubygems.org https://xxx.org
```
means `bundle` will replace `https://rubygems.org` to `https://xxx.org` in `Gemfile`, but will not replace `http://rubygems.org`, so it won't work for this case

So if I want to make both `http` and `https` replaced with specific mirror, I need to config them both. Is that right?

Thanks for your assistance!

**Comment by segiddins** [comment]
> So if I want to make both http and https replaced with specific mirror, I need to config them both. Is that right?

Yes, that is correct
