### ISSUE TITLE
URI::InvalidURIError: bad URI(is not URI?)

### ISSUE THREAD

**Issue by lcesar33** [bundler/bundler#5563]
I was using jruby 9.1.2 and after upgrade to 9.1.8 I have errors when I try to install missing gems.
I've installed last bundler version: 1.14.6 and I receive next error when trying to install missing gems:

URI::InvalidURIError: bad URI(is not URI?): http://xxxx.xxx@xxxx.xx:xxx@proxy.hq.xxx.ie:8080
  C:/jruby-9.1.8.0/lib/ruby/stdlib/uri/rfc3986_parser.rb:67:in `split'
  C:/jruby-9.1.8.0/lib/ruby/stdlib/uri/rfc3986_parser.rb:72:in `parse'
  C:/jruby-9.1.8.0/lib/ruby/stdlib/uri/common.rb:227:in `parse'
  C:/jruby-9.1.8.0/lib/ruby/stdlib/uri/common.rb:714:in `URI'
  C:/jruby-9.1.8.0/lib/ruby/gems/shared/gems/bundler-1.14.6/lib/bundler/vendor/net-http-persistent/lib/net/http/persistent.rb:908:in `proxy_from_env'
  C:/jruby-9.1.8.0/lib/ruby/gems/shared/gems/bundler-1.14.6/lib/bundler/vendor/net-http-persistent/lib/net/http/persistent.rb:858:in `proxy='
  C:/jruby-9.1.8.0/lib/ruby/gems/shared/gems/bundler-1.14.6/lib/bundler/vendor/net-http-persistent/lib/net/http/persistent.rb:528:in `initialize'
  C:/jruby-9.1.8.0/lib/ruby/gems/shared/gems/bundler-1.14.6/lib/bundler/fetcher.rb:240:in `connection'
  C:/jruby-9.1.8.0/lib/ruby/gems/shared/gems/bundler-1.14.6/lib/bundler/fetcher.rb:84:in `initialize'
  C:/jruby-9.1.8.0/lib/ruby/gems/shared/gems/bundler-1.14.6/lib/bundler/source/rubygems.rb:235:in `block in fetchers'
  org/jruby/RubyArray.java:2486:in `map'
  C:/jruby-9.1.8.0/lib/ruby/gems/shared/gems/bundler-1.14.6/lib/bundler/source/rubygems.rb:233:in `fetchers'
  C:/jruby-9.1.8.0/lib/ruby/gems/shared/gems/bundler-1.14.6/lib/bundler/source/rubygems.rb:346:in `block in remote_specs'
  C:/jruby-9.1.8.0/lib/ruby/gems/shared/gems/bundler-1.14.6/lib/bundler/index.rb:10:in `build'
  C:/jruby-9.1.8.0/lib/ruby/gems/shared/gems/bundler-1.14.6/lib/bundler/source/rubygems.rb:345:in `remote_specs'
  C:/jruby-9.1.8.0/lib/ruby/gems/shared/gems/bundler-1.14.6/lib/bundler/source/rubygems.rb:82:in `specs'
  C:/jruby-9.1.8.0/lib/ruby/gems/shared/gems/bundler-1.14.6/lib/bundler/lazy_specification.rb:75:in `__materialize__'
  C:/jruby-9.1.8.0/lib/ruby/gems/shared/gems/bundler-1.14.6/lib/bundler/spec_set.rb:83:in `block in materialize'
  org/jruby/RubyArray.java:2518:in `map!'
  C:/jruby-9.1.8.0/lib/ruby/gems/shared/gems/bundler-1.14.6/lib/bundler/spec_set.rb:80:in `materialize'
  C:/jruby-9.1.8.0/lib/ruby/gems/shared/gems/bundler-1.14.6/lib/bundler/definition.rb:176:in `specs'
  C:/jruby-9.1.8.0/lib/ruby/gems/shared/gems/bundler-1.14.6/lib/bundler/definition.rb:164:in `resolve_remotely!'
  C:/jruby-9.1.8.0/lib/ruby/gems/shared/gems/bundler-1.14.6/lib/bundler/installer.rb:226:in `resolve_if_need'
  C:/jruby-9.1.8.0/lib/ruby/gems/shared/gems/bundler-1.14.6/lib/bundler/installer.rb:78:in `run'
  C:/jruby-9.1.8.0/lib/ruby/gems/shared/gems/bundler-1.14.6/lib/bundler/installer.rb:24:in `install'
  C:/jruby-9.1.8.0/lib/ruby/gems/shared/gems/bundler-1.14.6/lib/bundler/cli/install.rb:70:in `run'
  C:/jruby-9.1.8.0/lib/ruby/gems/shared/gems/bundler-1.14.6/lib/bundler/cli.rb:181:in `block in install'
  C:/jruby-9.1.8.0/lib/ruby/gems/shared/gems/bundler-1.14.6/lib/bundler/settings.rb:99:in `temporary'
  C:/jruby-9.1.8.0/lib/ruby/gems/shared/gems/bundler-1.14.6/lib/bundler/cli.rb:180:in `install'
  C:/jruby-9.1.8.0/lib/ruby/gems/shared/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  C:/jruby-9.1.8.0/lib/ruby/gems/shared/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
  C:/jruby-9.1.8.0/lib/ruby/gems/shared/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
  C:/jruby-9.1.8.0/lib/ruby/gems/shared/gems/bundler-1.14.6/lib/bundler/cli.rb:20:in `dispatch'
  C:/jruby-9.1.8.0/lib/ruby/gems/shared/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
  C:/jruby-9.1.8.0/lib/ruby/gems/shared/gems/bundler-1.14.6/lib/bundler/cli.rb:11:in `start'
  C:/jruby-9.1.8.0/lib/ruby/gems/shared/gems/bundler-1.14.6/exe/bundle:32:in `block in (root)'
  C:/jruby-9.1.8.0/lib/ruby/gems/shared/gems/bundler-1.14.6/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
  C:/jruby-9.1.8.0/lib/ruby/gems/shared/gems/bundler-1.14.6/exe/bundle:24:in `<main>'
  org/jruby/RubyKernel.java:979:in `load'
  C:/Users/srvradminclp/RubymineProjects/sbci_loans_system/bin/bundle:3:in `<main>'
```

## Environment

```
Bundler   1.14.6
Rubygems  2.6.8
Ruby      2.3.1p0 (2017-03-06 revision 54768) [java]
GEM_HOME  C:/jruby-9.1.8.0/lib/ruby/gems/shared
GEM_PATH  C:/jruby-9.1.8.0/lib/ruby/gems/shared;C:/Users/srvradminclp/.gem/jruby/2.3.0
Git       2.7.4.windows.1
Platform  universal-java-1.8
OpenSSL   JRuby-OpenSSL 0.9.20
```

## Bundler settings

```
gemfile
  Set via BUNDLE_GEMFILE: "C:/Users/srvradminclp/RubymineProjects/sbci_loans_system/Gemfile"
```

**Comment by olleolleolle** [comment]
(As a first small step, does it improve your situation to `gem update --system`?)

**Comment by lcesar33** [comment]
Thanks Olle, the issue has been fixed.
I believe the problem was related with permissions, I was executing the bundle install from rubymine, when I've executed from a command window of my application bin folder it has worked.
Many thanks and Regards.
