### ISSUE TITLE
Private github gems via HTTPS

### ISSUE THREAD

**Issue by hjhart** [bundler/bundler#5567]
I'm trying to migrate my Gemfile from the insecure git protocol to the HTTPS protocol. Specifically, my gems that are private repositories on github.

```
# From this:
gem 'private_repo', git: 'git@github.com:hjhart/private_repo.git'

# To this:
gem 'private_repo', git: "https://#{ENV['GITHUB_TOKEN']}@github.com/hjhart/private_repo"
```

Unfortunately, I later found out that the (hopefully) obfuscated GITHUB_TOKEN environment variable was showing up in the `Gemfile.lock`, which we're checking in, which I'd like to avoid. :)

```
GIT
  remote: https://my-super-secret-github-token-here@github.com/hjhart/private_repo
  revision: 91e2a451cad57bc2d21adfd0116443ae75cbbc41
  specs:
    activesupport
    addressable  
```

Is there a best practice for using HTTPS with gems that require authentication? It's also important that this can be done in a non-interactive fashion (do not ask me for my username or password), for deploys and for a CI system.

**Comment by colby-swandale** [comment]
The best practice is to use `bundle config` to store your credentials. See the [Gemfile documentation](http://bundler.io/man/gemfile.5.html#CREDENTIALS-credentials) re: credentials.

**Comment by segiddins** [comment]
Either use bundle config or a [git credential store](https://git-scm.com/docs/git-credential-store) (like a system keychain)

**Comment by hjhart** [comment]
Thanks guys! Much appreciated. I wrote a blog post with a little more detail here: http://hjhart.github.io/2017/04/05/using-bundler-to-securely-install-your-private-github-gems.html

**Comment by indirect** [comment]
thanks for the blog post, @hjhart!
