### ISSUE TITLE
Indirect dependencies fail to resolve correct version of gem

### ISSUE THREAD

**Issue by ioquatix** [bundler/bundler#5573]
I have published two gems.

- `async` depends on `nio4r`
- `async-dns` depends on `async`

`nio4r` has two versions: 1.x which is available for MRI 2.0+ and 2.x which is available for MRI 2.2.6+ only.

On travis, tests for `async` work fine for all versions of MRI 2.x

https://travis-ci.org/socketry/async

It correctly installs `nio4r` depending on Ruby version and availability.

However, `async-dns` which only depends on `async`, doesn't work the same way. It fails to install the correct version of `nio4r` for older MRI versions, instead insisting to install `nio4r` 2.0 which obviously fails.

https://travis-ci.org/socketry/async-dns/jobs/220522083

I feel that this should work, where testing `async-dns` on MRI 2.0 should work the same as testing `async`, in terms of what version of `nio4r` is selected.

Let me know if you need any more information or help to figure this one out.

**Comment by ioquatix** [comment]
Okay, I found simply updating the travis configuration to trusty appears to have resolved this issue. I'm not sure why. I'll leave this issue just in case there is something else going on here, but feel free to close it as this issue is now effectively solved.

**Comment by segiddins** [comment]
Please add the output of `bundle env` when things were both failing and passing, thank you!

**Comment by ioquatix** [comment]
Uh, I'm sorry, but what would be the best way to do it in travis?

**Comment by segiddins** [comment]
Add `bundle env` to the `install` section before `bundle install`?

**Comment by ioquatix** [comment]
Okay, here is the build matrix when working on trusty, with `bundle env` output.

https://travis-ci.org/socketry/async-dns/builds/220536182 

Here is the build matrix when not working, with `bundle env` output.

https://travis-ci.org/socketry/async-dns/builds/220538839

**Comment by segiddins** [comment]
It looks like it's failing with Bundler 1.7.9 and passing with Bundler 1.14.6, so it seems we've fixed the issue as some point.

**Comment by ioquatix** [comment]
Awesome, that does appear to be the case. Thanks so much for your time investigating this issue.
