### ISSUE TITLE
Trampoline logic is wrong

### ISSUE THREAD

**Issue by jules2689** [bundler/bundler#5597]
`ENV["BUNDLE_TRAMPOLINE_FORCE"] && !ENV["BUNDLE_TRAMPOLINE_DISABLE"]` implies that we need to FORCE and not DISABLE, whereas the logic should be FORCE or not DISABLE.

This means that users have not been running updated bundler since 1.14.0. This affects all versions `>= 1.14.0.pre.1`

Originally introduced in this PR: https://github.com/bundler/bundler/pull/4894

cc @segiddins @indirect

**Comment by segiddins** [comment]
Nope, the intention is for bundler 1.x it must be forced and not disabled

**Comment by jules2689** [comment]
For posterity, I thought the logic was wrong. I was wrong.

We want to force trampoline unless using bundler 2.x. The issue I was seeing is that RubyGems wasn't enabling `1.15.0.pre.1` because it is a `pre` version. In this case, we need to set `BUNDLE_TRAMPOLINE_FORCE=true`

**Comment by segiddins** [comment]
In that case, what you really want is `gem "bundler", ">= 0.a"` before `require "bundler/setup"`. Or manually setting the load path. Or using `bundle exec`, since binstubs will activate prerelease versions by default.

**Comment by jules2689** [comment]
We had `gem "bundler"` which didn't work, but `gem "bundler", ">= 0.a"` worked. :+1: Thanks
