### ISSUE TITLE
Add `transitive_gemfile: true` option to git/github/path sources in Gemfile API

### ISSUE THREAD

**Issue by lamont-granquist** [bundler/bundler#5615]
The idea here would be to optionally, off-by-default, opt-in merge Gemfiles when using sources of gems which will likely expose that information.

So in the parent Gemfile you could have:

```ruby
source "https://rubygems.org"

gem "chef", path: "..", transitive_gemfile: true
gem "halite", git: "https://github.com/poise/halite", branch: "master", transitive_gemfile: true
```

The point here is that I want to check this into the chef repo in order to run the halite gems tests against PRs of chef.  I very deliberately desired this to not be in the Gemfile and Gemfile.lock of the chef repo itself, since I do not want to create the mega-closure over all of chef's gems along with all the external test gems, and all of their development dependencies (very often these wind up conflicting).  I do need the development gems of the transitive gemfiles installed (at least if I don't use --without, and I suspect the right behavior is to take the --without arguments and apply them to the transitive gemfile), and would also like to use the Gemfile.lock to equality pin the versions if the Gemfile.lock is checked into the repo or path. 

I can kinda-sorta do this now via having a gemfile which does this:

```ruby
source 'https://rubygems.org'

gemspec(name: 'chef', path: "../")

gem 'rake'
gem 'rspec-command'
gem 'poise', git: 'https://github.com/poise/poise'
gem 'poise-boiler', git: 'https://github.com/poise/poise-boiler'
gem 'halite', git: 'https://github.com/poise/halite'

# Test fixture gems
Dir[File.expand_path('../halite_test_gems/*', __FILE__)].each do |path|
  gem File.basename(path), path: path
end
```

But I have to manually duplicate all the dev/test gems of halite, along with halite's test fixture gems (which are not pushed to rubygems, so I have to manually copypasta them into the chef repo).

Does this sound like a reasonable proposal / API shape?  I'll do the work if it seems reasonable...

NOTE:  if this ever does get turned into a RFC it should be noted what to do about transitive deps that pull in transitive deps and loop detection and conflicts.

**Comment by segiddins** [comment]
Please open an issue in https://github.com/bundler/rfcs, I think this is a big enough feature it would require a full proposal

**Comment by lamont-granquist** [comment]
looks like we've decided, at least for now, not to go down this road...

**Comment by lamont-granquist** [comment]
looks like `bundle inject` does something almost like what i was looking for here.  if you try to pin a gem which is already specified in the gemfile, though, you can wind up with an error like this:

```
[!] There was an error parsing `injected gems`: You cannot specify the same gem twice with different version requirements.
You specified: berkshelf (>= 0) and berkshelf (~> 6.0.1). Bundler cannot continue.
```

if it would be able to apply both the gem requirements (since they don't conflict) and then instead of injecting a single gem, but to loop over all the gems in a lockfile that would be a possible solution to this problem.

the way that multiple gem statements conflict even though they might be solvable seems to be a limitation of the gem DSL thol.
