### ISSUE TITLE
`bundler env` should show bundler's shebang if it differs from the first found ruby

### ISSUE THREAD

**Issue by evaryont** [bundler/bundler#5616]
I was starting to tear my hair out today in a crazy debugging situation. I ran `gem install bundler` on OSX, and then trying to install various gems. However, I got ruby version incompatibilities: our rails app specifies ruby 2.3, but bundler reported ruby 2.0.

It turns out that rubygem's had written the bundler binstub with OSX's system ruby for it's shebang, and not the ruby installed with Homebrew. It would have been faster to debug if I had realized the discrepancy earlier.

**Comment by segiddins** [comment]
Can you give an example of the relevant shebangs and ruby executable path?
