### ISSUE TITLE
Remove relative path enforcement on --cache-path

### ISSUE THREAD

**Issue by mal** [bundler/bundler#5627]
Would it be possible to remove the check done on `--cache-path` [here](https://github.com/bundler/bundler/blob/28e67dc7e4b9e3a6c67524597f7cd64e12ddbf6d/lib/bundler/settings.rb#L218)?

Used in conjunction with `--no-prune` it would then be possible to more easily maintain a central cache of `gem` files useable by multiple local apps. In the case where apps have many common libraries (that are often, if not always, in sync) this is quite useful.

**Comment by segiddins** [comment]
@indirect given you added the customizable cache path and the commit doesn't seem to justify why only relative paths are allowed, I think this is for you to answer

**Comment by indirect** [comment]
Oh man, I have no idea what I was thinking. It seems fine to allow absolute paths to me? I guess, for what it's worth, in Bundler 2.0 there will be a user-wide shared cache of .gems by default.

**Comment by colby-swandale** [comment]
are we breaking backwards compatibility if we take that exception out?

**Comment by segiddins** [comment]
Nah, it's the other direction that would be a problem. Allowing users to do something they couldn't before (adding a "feature") is never breaking backwards compatibility
