### ISSUE TITLE
A Gemfile DSL addition to allow access to the git repo properties

### ISSUE THREAD

**Issue by MOZGIII** [bundler/bundler#5632]
I'd like to propose a new feature: a Gemfile DSL addition to allow access to the current git repo properties.

I need to somehow detect whether the current git repository is configured to use GIT+SSH or GIT+HTTPS scheme to interact with repo repos. I need this because our devs usually use ssh to work with private repositories, while CI is intended to be used with https.

So, in my custom source definition I need to intellectually set the repo to use ssh for devs if the current repo has an ssh scheme for it's origin remote, and to use https if it's using ssh.

I cound've easily implemented this on my own, but we have a few project now, so, in case you like the idea, just updating bundler (OR adding a plugin to it, if plugins allow this kind of extensibility already) will be a better solution than dropping a pile of not very related code to the Gemfile in each of them.

**Comment by MOZGIII** [comment]
@indirect This is another opportunity to test blundler's plugin system, so I summon you here. What do you think? Will plugin system allow this in it's current state?

**Comment by segiddins** [comment]
This seems like the sort of thing the `insteadOf` git config is for (see http://stackoverflow.com/questions/9611561/how-do-i-clone-a-gist-using-https-instead-of-git#15800103)

**Comment by MOZGIII** [comment]
I know about `insteadOf` and other ways to rewrite git sources for bundler. Yeah, this would really do the trick, and we probably don't need that kind of stuff in bundler core. Though, it might be good "test dummy" idea for a (theoretical?) plugin implementation.

**Comment by segiddins** [comment]
I'm going to close this as something the core team isn't planning on implementing, but feel free to try and implement a plugin to do this!
