### ISSUE TITLE
SemVer version specifier

### ISSUE THREAD

**Issue by fulldecent** [bundler/bundler#5640]
I want to require a version of a package:

* I need at least 1.2.4
* I need something compatible with 1.2.4 (i.e. < 2.0)
* Assume the package uses SemVer (because this is 2017)

This is, or should be, the most common user requirement for bundler but it is the most complicated one to set up.

Bundler should have an operator that expresses this. And users should be encouraged to use it.

---

Compare to the help docs for Bundler at http://bundler.io/v1.3/rationale.html

> rack ~> 1.2.1 (which means >= 1.2.1 and < 1.3.0)

Why on earth would anybody want rack 1.2.1 but not want 1.3.0 (which should be compatible)? This is such an academic example but it is the basis of Bundler's documentation. Yes it should be possible to specify such a dependency but it should be documented in an "Other stuff you might want to do (but probably not)" section.

**Comment by segiddins** [comment]
Bundler uses the `Gem::Requirement` operators from RubyGems -- it seems highly unlikely to me that we'll ever be able to add more in RG due to backwards compatibility concerns

**Comment by fulldecent** [comment]
Thank you, submitted upstream at https://github.com/rubygems/rubygems/issues/1919
