### ISSUE TITLE
Output to new Gemfile

### ISSUE THREAD

**Issue by kevintraver** [bundler/bundler#5641]
Is there a way export the current list from the Gemfile.lock into a new Gemfile?

Would be super handy if `bundle show` could be formatted to be used in a new Gemfile.

**Comment by segiddins** [comment]
Bundler doesn't currently have this functionality, particularly because information such as groups, platform and install conditionals are not stored in the lockfile and must be read from the Gemfile

**Comment by colby-swandale** [comment]
I'm closing this as the main question has been answered. Feel free to open a new issue if you have any more questions.
