### ISSUE TITLE
CGI escaped username and passwords with bundle config

### ISSUE THREAD

**Issue by giovdk21** [bundler/bundler#5643]
Please see: https://github.com/bundler/bundler/issues/4288

> Let's specifically call out that usernames and passwords need to already be CGI escaped.
_(comment by indirect)_ 

I've been having the same problem using bundle config bitbucket.org user:pwd (http://bundler.io/man/bundle-config.1.html)

Could the documentation be updated by specifying that also in relation to the "bundle config" command / env. variables?

Thanks

**Comment by segiddins** [comment]
Yup, we definitely should call this out at https://github.com/bundler/bundler/blob/master/man/bundle-config.ronn#L291!

**Comment by mikegee** [comment]
This issue is resolved since https://github.com/bundler/bundler/pull/5883 was merged.
