### ISSUE TITLE
Problem with cld3

### ISSUE THREAD

**Issue by Zirconiumirish** [bundler/bundler#5655]
Hi i'm trying to install mastodon but I can't get it working
When i'm executing this : "bundle install --deployment --without development test"

I have this :

```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/cld3-3.1.1/ext/cld3
/home/mastodon/.rbenv/versions/2.4.1/bin/ruby -r ./siteconf20170511-4080-1hph5bn.rb
extconf.rb
sh: 1: protoc: not found
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/home/mastodon/.rbenv/versions/2.4.1/bin/$(RUBY_BASE_NAME)
	--with-protobuf-config
	--without-protobuf-config
	--with-pkg-config
	--without-pkg-config
/home/mastodon/.rbenv/versions/2.4.1/lib/ruby/2.4.0/fileutils.rb:287:in `link': No such file
or directory @ rb_file_s_link - (feature_extractor.pb.h, cld_3/protos/feature_extractor.pb.h)
(Errno::ENOENT)
	from /home/mastodon/.rbenv/versions/2.4.1/lib/ruby/2.4.0/fileutils.rb:287:in `block in ln'
from /home/mastodon/.rbenv/versions/2.4.1/lib/ruby/2.4.0/fileutils.rb:1476:in
`fu_each_src_dest0'
	from /home/mastodon/.rbenv/versions/2.4.1/lib/ruby/2.4.0/fileutils.rb:285:in `ln'
	from extconf.rb:27:in `block in <main>'
	from extconf.rb:25:in `each'
	from extconf.rb:25:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found
here:

/home/mastodon/live/vendor/bundle/ruby/2.4.0/extensions/x86_64-linux/2.4.0-static/cld3-3.1.1/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in
/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/cld3-3.1.1 for inspection.
Results logged to
/home/mastodon/live/vendor/bundle/ruby/2.4.0/extensions/x86_64-linux/2.4.0-static/cld3-3.1.1/gem_make.out

An error occurred while installing cld3 (3.1.1), and Bundler cannot continue.
Make sure that `gem install cld3 -v '3.1.1'` succeeds before bundling.
```

Thanks for your help

**Comment by colby-swandale** [comment]
Hi, This does not appear to be an issue with Bundler itself. It appears to be a build error in the `cld3` gem. I recommend opening an issue with the project to help resolve your problem.

**Comment by adamc199** [comment]
Any luck on this? I'm having the same issue

**Comment by Zirconiumirish** [comment]
Yes I finally succeed 👍 

git clone https://github.com/rbenv/rbenv.git ~/.rbenv
echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
echo 'eval "$(rbenv init -)"' >> ~/.bashrc
source ~/.bashrc


git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build

rbenv install 2.4.1


rbenv global 2.4.1


echo "gem: --no-document" > ~/.gemrc


gem install bundler --no-ri

**Comment by colby-swandale** [comment]
I'm closing this for now.

**Comment by notunderground** [comment]
sudo apt-get install protobuf-compiler

this solved it for me.

**Comment by dfl1955** [comment]
But not me, I am told protobuf-compiler is up to date and I still get the cld3 compile error

**Comment by jackpetraitis** [comment]
I had to install libprotobuf-dev in addition to protobuf-compiler

**Comment by philnelson** [comment]
I have installed both libprotobuf-dev protobuf-compiler via apt and the error persists.

**Comment by outragedhuman** [comment]
Also tried installing both, still getting the error. 

gem install cld3 -v '3.2.2' 

works fine on its own though. Seems like this is a Mastodon problem?

**Comment by pawelngei** [comment]
For me following https://github.com/akihikodaki/cld3-ruby/issues/3#issuecomment-300374429 helped. I needed to:

  $ sudo apt-get install pkg-config

**Comment by plank-tools** [comment]
So, to summarize 

`$ sudo apt-get install -y protobuf-compiler libprotobuf-dev pkg-config`

**Comment by peggles2** [comment]
What if its on a mac?

**Comment by VyrCossont** [comment]
> What if its on a mac?

@peggles2: `brew install protobuf-c` will get you the equivalent software, including the protobuf compiler, the C support library and headers, and `pkg-config`.

If you're installing the same version of Mastodon I am, the next thing you'll hit will probably be the `ruby-idn` gem failing to compile. You can correct this by running `brew install libidn`, followed by `bundle config build.idn-ruby --with-idn-dir="$(brew --prefix)"` if you've installed Homebrew somewhere Bundler doesn't normally look for libraries, and then `bundle install` again.

**Comment by ArisuOngaku** [comment]
On archlinux, install package `protobuf`

**Comment by SamalaSumanth0262** [comment]
@peggles2  Saved me .. 👍
