### ISSUE TITLE
bundle exec command specs breaking on local dev environment

### ISSUE THREAD

**Issue by colby-swandale** [bundler/bundler#5657]
Gist: https://gist.github.com/colby-swandale/6173b0221ad91a2168ef27b5c08dd089

Whenever i run the `spec/commands/exec_spec.rb` tests either it be the individual file or the entire suite, some of the specs will not pass for me.

\cc @segiddins

**Comment by segiddins** [comment]
Ahhhh, I think I know the issue. Will look into it tomorrow
