### ISSUE TITLE
Bundler.setup doesn't work with `bundle exec`

### ISSUE THREAD

**Issue by qcam** [bundler/bundler#5661]
From #5659.

I encountered an issue while using `Bundler.setup` with `bundle exec`

```rb
# test.rb
require 'rubygems'
require 'bundler'

Bundler.setup(:default, :development) # make sure only :development gems are require-able.

require 'foo'
Foo
```

Let's say I have gem `foo` in Gemfile with `:production` group, assume there is a `Foo` constant in it.

When I ran `bundle exec ruby ./test.rb`, it turned out `Foo` can be loaded, while it should not.

**Comment by segiddins** [comment]
I believe `bundle exec` will setup all groups that you haven't configured with `bundle config without`, and if you want more granular control at runtime you need to call `Bundler.setup` yourself rather than using `bundle exec`

**Comment by qcam** [comment]
@segiddins thanks for taking your time looking at my issue. I appreciate that.

> I believe `bundle exec` will setup all groups that you haven't configured with bundle config without

Is this behavior intentionally by design? I am wondering if this would cause any false positive, if a gem is grouped in a specific environment can be required on another?

You're right that I can use `bundle config without`. Anyway, could we have it documented in [Bundler Workflow](http://bundler.io/v1.12/bundler_workflow.html)? I think it might help users aware of the consequences of running `bundle install` without `without` configured.

My actually Gemfile is like this, with `puma` set in `production`.

```rb
ruby '2.2.2'
source 'https://rubygems.org'

gem 'rake'
gem 'rack'
gem 'sinatra'
gem 'puma', group: :production
```

And when I run `bundle exec rackup` on development, after running `bundle install` as usual, Puma was booted instead of the default Rack handler.

Definitely this is not Bundler's fault but would you be able to suggest me a way to make `puma` un-require-able in this case? I don't really want to write my own `bundle exec` to be honest.

Thank you.

**Comment by segiddins** [comment]
> Is this behavior intentionally by design? I am wondering if this would cause any false positive, if a gem is grouped in a specific environment can be required on another?

Yes, I believe that is intentional (it's definitely worked that way as long as I've been working on bundler)

> would you be able to suggest me a way to make puma un-require-able in this case

optional groups

**Comment by colby-swandale** [comment]
I'm closing this, feel free to re-open this issue if you have any more questions.
