### ISSUE TITLE
Packaging built extensions

### ISSUE THREAD

**Issue by jarro2783** [bundler/bundler#5668]
We use `bundle package` in CI, and have our hosts install gems using `bundle install --deployment` to reduce our dependency on rubygems.org. The problem is that they still try to compile native gems. Ideally we would like to not have GCC installed on production machines. We would also like new hosts to be quick to start. This means they can't spend a long time building native extensions.

Is it possible to package the already built native extensions so that we don't have to build them on each host?

**Comment by segiddins** [comment]
What's the output of `bundle env` on CI and on the VM?

**Comment by jarro2783** [comment]
Here it is on the host: https://ptpb.pw/2Arl

The diff between that and CI is:

    --- /dev/fd/63	2017-05-17 19:35:40.703056879 -0400
    +++ /dev/fd/62	2017-05-17 19:35:40.703056879 -0400
    @@ -3,28 +3,29 @@
     
     ```
     Bundler   1.14.6
    -Rubygems  2.6.10
    +Rubygems  2.6.12
     Ruby      2.1.5p273 (2014-11-13 revision 48405) [x86_64-linux]
    -Git       2.7.4
    +GEM_HOME  /usr/local/bundle
    +GEM_PATH  
    +Git       2.1.4
     Platform  x86_64-linux
    -rubygems-bundler (1.4.4)
     ```
     
     ## Bundler settings
     
     ```
    -frozen
    -  Set for your local app (/etc/puppet/.bundle/config): "1"
     path
    -  Set for your local app (/etc/puppet/.bundle/config): "vendor/bundle"
    +  Set for the current user (/root/.bundle/config): "/usr/local/bundle"
     bin
    -  Set for your local app (/etc/puppet/.bundle/config): "bin"
    -without
    -  Set for your local app (/etc/puppet/.bundle/config): "development:deployment"
    -with
    -  Set for your local app (/etc/puppet/.bundle/config): "production"
    +  Set for the current user (/root/.bundle/config): "/usr/local/bundle/bin"
    +cache_all_platforms
    +  Set for your local app (/usr/local/bundle/config): "true"
    +cache_all
    +  Set for your local app (/usr/local/bundle/config): "true"
     disable_shared_gems
    -  Set for your local app (/etc/puppet/.bundle/config): "true"
    +  Set for your local app (/usr/local/bundle/config): "true"
    +app_config
    +  Set via BUNDLE_APP_CONFIG: "/usr/local/bundle"
     ```
    
    ## Gemfile

**Comment by jarro2783** [comment]
Also is it possible to precompile a gem so that bundle will install the precompiled gem instead of trying to compile it when I run `bundle package`?

**Comment by MrOutis** [comment]
This would help me closing: https://github.com/bundler/bundler/issues/5669

**Comment by segiddins** [comment]
I don't think `bundle package` is intended to package any more than the `.gem` files -- if you want to "package" extensions, I recommend installing into a local path that you commit to git.

**Comment by jarro2783** [comment]
:o: is that the best you have to offer? Are you seriously telling me to commit binaries to git? That doesn't even work when we have 3 distros with different link time dependencies.

**Comment by segiddins** [comment]
Well, you're asking for a way to package binaries... `bundle package` literally just copies the `.gem` files you've downloaded

**Comment by jarro2783** [comment]
So basically ruby has no tool to generate a list of dependencies and bundle the whole thing into a complete package with built extensions. 25 years later and this language still isn't production ready...

**Comment by segiddins** [comment]
@jarro2783 the tone you're taking is coming off as rather rude, and I can assure you that it is not the way to get the Bundler team to help you

**Comment by indirect** [comment]
@jarro2783 hi.

First, let's talk about your tone. Bundler has a [code of conduct](https://github.com/bundler/bundler/blob/master/CODE_OF_CONDUCT.md) that you are required to follow in this issue tracker, and any other space belonging to this project. You're getting pretty close to violating the code of conduct, so this is your one warning.

Next, let's talk about the feature you're asking for: it sounds like you're saying you want `bundle package` to somehow compile binaries for you in a way that will allow them to be copied directly to three different distros and somehow work on all three without any further compilation. Unfortunately, that is not what `bundle package` does.

If you'd like to precompile your gems, you're welcome to use `bundle install --path DEST` and then copy the destination directory to other machines with the same build environment.

**Comment by jarro2783** [comment]
I'm sorry I'm frustrated by a language that frequently causes me problems, and by a tool (Puppet) that has chosen to package itself in a rather bizarre way.

I'm trying to use bundler to build a deployment package for the one thing we can't use Puppet for, which is installing Puppet itself. This actually works quite well apart from native extensions, and only because in an ideal world we wouldn't have gcc on a production host. On top of that the latest `facter` is not a gem (even though the Puppet gem still depends on the old version with a few known bugs), so I'm at a complete loss as to how to package it.

Thanks for the advice about `bundle install --path`. Maybe I will be able to massage the right things into the right place somehow.

**Comment by jrynyt** [comment]
@indirect could you go into a little more detail on precompiling and copying please? I'm also trying to copy the entire bundle directory from one system to another (same arch), including the compiled extensions, but not having any luck. Ultimate goal is to save many minutes on builds by not having to resolve dependencies, download, install, and recompile extensions. I can't find any documentation anywhere on how to do that.

If I copy the DEST from `bundle install --path DEST` to become another system's `vendor/bundle`, I get:
```
$ bundle check
https://github.com/jeffreylouden/gemoji.git (at master@0325927) is not yet checked out. Run `bundle install` first.

$ bundle install --local --deployment
Could not find nokogiri-1.7.0.1 in any of the sources

$ bundle install --deployment
Ignoring binding_of_caller-0.7.2 because its extensions are not built.  Try: gem pristine binding_of_caller --version 0.7.2
... etc for all those with extensions
```


If I copy DEST to a different location:
```
$ bundle install --local --path ../new-DEST
Could not find nokogiri-1.7.0.1 in any of the sources

$ bundle install --path /new-DEST
Ignoring binding_of_caller-0.7.2 because its extensions are not built.  Try: gem pristine binding_of_caller --version 0.7.2
... for all those with extensions
```

even though
```
$ ls -ld /new-DEST/ruby/2.3.0/gems/nokogiri-1.7.0.1/
drwxr-xr-x. 9 centos centos 4096 Apr 26 21:21 /new-DEST/ruby/2.3.0/gems/nokogiri-1.7.0.1/
```

thanks

**Comment by micheelengronne** [comment]
I would be interested in a way to precompile extensions and download them when needed.

pip can do that with wheel on python. https://pip.pypa.io/en/stable/reference/pip_wheel/

Wheel can precompile extensions and pip can install packages without compiling and looking the compiled extensions in a directory or url (url is great, you can have a binaries repository).

If we have to compile and check extensions on git, we defeat the purpose of git (not good for binaries and big files) and we need to install git in production.

git in production is a security issue as it stores absolutely every information about the source code (ready to help an attacker).
