### ISSUE TITLE
Use bundler which seperate use binary extension gem with normally gem.

### ISSUE THREAD

**Issue by zw963** [bundler/bundler#5669]
I have one issue when I use bundler with docker, following is my propose:

1.  For make one `RUN` command in Dockerfile Reusable, I hope make ``RUN bundle install --binstubs --retry=5`` in seperate step to run.

2. Some rails gem, need some build dependency,  e.g. `nio4r`, `pg`, `nokogiri`, `therubyracer`, This means
when run ``bundle install`` in previous step, we need install lots of packages which make those gem can
installed

For make my image more small, and docker layer reuseable, I think following is a better solution:

```Dockerfile

# install nio4r, therubyracer nokogiri, which alomost not to update, so in seperate step.
RUN build_packages='make gcc g++ patch git' && \
        apt-get update && \
        apt-get install -qq -y --no-install-recommends $build_packages && \
        rm -rf /var/lib/apt/lists/* && \
        bundle update nio4r --source=nio4r --conservative && \
        bundle update therubyracer --source=therubyracer --conservative && \
        bundle update nokogiri --source=nokogiri --conservative && \
        apt-get purge -y --auto-remove $build_packages

# this step, frequently changed, so in seprate step.
RUN bundle install --binstubs --retry=5
```

### What I expect behavior is:

- In the first run step, I want to just install the exact version several gem which locked in Gemfile.lock.
What i expect behavior is `bundle install just several gem`, not `bundle update several gem`.

- in second step, I want to install all others gems locked with Gemfile.lock to project directory.

### Current behavior
In first step, 
```rb
        bundle update nio4r --source=nio4r --conservative && \
        bundle update therubyracer --source=therubyracer --conservative && \
        bundle update nokogiri --source=nokogiri --conservative && \
``` 

it install almost all gem, which make seperate those two step have no sense ...
In fact, because no postgre dependency. first step is failed because headers file missing..

I want to know,  whether I do some thing wrong ?  wrong usage ?

**Comment by colby-swandale** [comment]
Hi, sorry that no one has replied to this. Too be honest no one on the core team uses Docker, so we're not really able to provide an answer to your problem.

**Comment by zw963** [comment]
Finally, I have to install all my gem within one step bundle install with install all necessory dependency.

With this [dockerfile-wget](https://github.com/zw963/dockerfile-wget), I resolve the problem, though, some
special step need to be created ...

**Comment by colby-swandale** [comment]
I'm going to close this issue, if you any more questions feel free to open a new issue.
