### ISSUE TITLE
bundle env has bad markdown syntax

### ISSUE THREAD

**Issue by BrianHawley** [bundler/bundler#5677]
When I run `bundle env`, it outputs in Markdown syntax. However, there's an error in the syntax. For example, here's the beginning of the output:

## Environment

```
Bundler   1.15.0
Rubygems  2.6.12
Ruby      2.0.0p648 (2015-12-16 revision 53162) [x86_64-darwin16.6.0]
GEM_HOME  /Users/bhawley/.rvm/gems/ruby-2.0.0-p648@oceans
GEM_PATH  /Users/bhawley/.rvm/gems/ruby-2.0.0-p648@oceans:/Users/bhawley/.rvm/gems/ruby-2.0.0-p648@global
RVM       1.29.1 (master)
Git       2.13.0
Platform  x86_64-darwin-16
rubygems-bundler (1.4.4)
```
```

## Gemfile

### Gemfile

```ruby
source 'https://rubygems.org'
```

It continues from there. The problem is the extra "```" after the Environment block (there are two of them), which messes up the syntax of the Gemfile following it.

**Comment by BrianHawley** [comment]
It's notable that my output didn't contain a "Bundler settings" section between "Environment" and "Gemfile". Perhaps it included the closing "```" of that section, without including the rest.

**Comment by segiddins** [comment]
I'm guessing thats the cause, thanks for pointing this out!

**Comment by segiddins** [comment]
https://github.com/bundler/bundler/pull/5679 should fix this
