### ISSUE TITLE
Bundler fails to resolve version dependencies

### ISSUE THREAD

**Issue by vfonic** [bundler/bundler#5682]
When I run `bundle update` it fails with `Bundler could not find compatible versions for gem "actionpack"` even though there are compatible versions of `actionpack` gem, all 5.0.x versions.

Here's the error message:

> Bundler could not find compatible versions for gem "actionpack":
>   In Gemfile:
>
>     spree was resolved to 3.3.0.beta, which depends on
>       spree_core (= 3.3.0.beta) was resolved to 3.3.0.beta, which depends on
>         rails (~> 5.0.0) was resolved to 5.0.0, which depends on
>           actionpack (= 5.0.0)
> 
>     spree_auth_devise was resolved to 3.2.0.beta, which depends on
>       devise (~> 4.3.0) was resolved to 4.3.0, which depends on
>         railties (< 5.2, >= 4.1.0) was resolved to 5.1.1, which depends on
>           actionpack (= 5.1.1)
> 
>     spree_auth_devise was resolved to 3.2.0.beta, which depends on
>       devise (~> 4.3.0) was resolved to 4.3.0, which depends on
>         railties (< 5.2, >= 4.1.0) was resolved to 5.1.1, which depends on
>           actionpack (= 5.1.1)
> 
>     spree_auth_devise was resolved to 3.2.0.beta, which depends on
>       devise (~> 4.3.0) was resolved to 4.3.0, which depends on
>         railties (< 5.2, >= 4.1.0) was resolved to 5.1.1, which depends on
>           actionpack (= 5.1.1)
> 
> Bundler could not find compatible versions for gem "activesupport":
>   In Gemfile:
>
>     spree_shopify_importer was resolved to 0.1.0, which depends on
>       activeresource was resolved to 5.0.0, which depends on
>         activesupport (< 6, >= 5.0)
> 
>     spree_auth_devise was resolved to 3.2.0.beta, which depends on
>       devise (~> 4.3.0) was resolved to 4.3.0, which depends on
>         railties (< 5.2, >= 4.1.0) was resolved to 4.1.0, which depends on
>           activesupport (= 4.1.0)

Here's the gist to `bundle env`:
https://gist.github.com/vfonic/e57fa99f98893a8567f2913043bb5bb3

This is the repo with the issues:
https://github.com/spark-solutions/spree_shopify_importer/

**Comment by segiddins** [comment]
I couldn't reproduce the issue in the given repo, running `bundle install && bundle update`

**Comment by vfonic** [comment]
@segiddins I can't reproduce the error anymore as well. No idea what was causing the issue yesterday.

Thanks for checking out! I'll reopen the issue if I encounter the error again.
