### ISSUE TITLE
Remove `github` shortcut, with warning in 1.99 that points to docs

### ISSUE THREAD

**Issue by indirect** [bundler/bundler#5699]
Rails apps already generate with a `git_source` directive because of the github HTTPS thing, so this isn't even a big change at this point. On top of that, I buy the argument that we can let users handle their own shortcuts, putting github/gitlab/bitbucket/etc on an equal footing. Let's get rid of our own hardcoded github shortcut and let users set up whatever make sense for them.

I'm also toying around with the idea of adding `git_source(:github) { |name| "https://github.com/#{name}.git" }` to the Gemfile generated by `init`, with a comment explaining that you should change the name and the URL to match whatever git host you use.

**Comment by grosser** [comment]
maybe just remove it ... using a git source is not that common and the few extra characters don't hurt that much
