### ISSUE TITLE
Bundler::ORIGINAL_ENV still contains bundler knownledge when using `bundle exec`

### ISSUE THREAD

**Issue by grosser** [bundler/bundler#5700]
`bundle exec ruby -e 'puts Bundler::ORIGINAL_ENV'`
has RUBYOPT / BUNDLE_GEMFILE / BUNDLE_BIN_PATH etc

.clean_env peviously solved that, but was declared deprecated in https://github.com/bundler/bundler/pull/4702#issuecomment-305876033

for `bundle exec ruby` and alternative would be `ruby -rbundler/setup` ... but that does not work for `rake` and other gem binaries

@indirect @segiddins

**Comment by segiddins** [comment]
Reproduced. Seems like a bug to me

**Comment by segiddins** [comment]
I think https://github.com/bundler/bundler/pull/5701 should address this, if you want to try it out

**Comment by grosser** [comment]
works!
