### ISSUE TITLE
Errors are printed to standard output

### ISSUE THREAD

**Issue by p-salido** [bundler/bundler#5709]
This message:

`Could not find gem 'ruby (~> 2.3.1.0)' in any of the gem sources listed in your Gemfile.`

... is printed in red color but is printed to standard output. When piping or redirecting output of a command like `bundle outdated` this error message gets redirected with the rest of the output. Being an error message it should be printed to standard error stream and show up when output is redirected.

<pre>
% bundle -v
Bundler version 1.15.1
</pre>

**Comment by segiddins** [comment]
This will be changed in bundler 2 by default to print to stderr, or you can use bundler master and configure the error_on_stderr setting
