### ISSUE TITLE
Inspect or clean up the working tree at

### ISSUE THREAD

**Issue by rogoit** [bundler/bundler#5710]
/var/folders/_r/xlnbsv0x6kn2n51l4942ly2c0000gn/T/ruby-build.20170611025745.26672 ~/development/nevercodealone/ncaUserBundle
HTTP/1.1 200 OK
Content-Type: binary/octet-stream
Content-Length: 12643369
Connection: keep-alive
Date: Sun, 11 Jun 2017 00:57:47 GMT
Last-Modified: Mon, 01 May 2017 07:19:53 GMT
ETag: "37b77eb82aeb048842f3daec3fed46b1"
Accept-Ranges: bytes
Server: AmazonS3
X-Cache: Miss from cloudfront
Via: 1.1 9d087ae042196d42f77dddb98f17f1fd.cloudfront.net (CloudFront)
X-Amz-Cf-Id: PAtBOurcF95VjXouXg_QbsuX2Q4qmDEGtny0HIH6sbaCUjEnUF9jZg==

/var/folders/_r/xlnbsv0x6kn2n51l4942ly2c0000gn/T/ruby-build.20170611025745.26672/rubinius-3.75 /var/folders/_r/xlnbsv0x6kn2n51l4942ly2c0000gn/T/ruby-build.20170611025745.26672 ~/development/nevercodealone/ncaUserBundle
Warning: the running version of Bundler is older than the version that created the lockfile. We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `/usr/local/bin/bundle --path=vendor/bundle`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what actually happened was...

Error details

    Errno::EACCES: Permission denied @ dir_s_mkdir - /Users/rolandgolla/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/versions20170611-26861-d9lbwh
      /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/tmpdir.rb:85:in `mkdir'
      /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/tmpdir.rb:85:in `block in mktmpdir'
      /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/tmpdir.rb:129:in `create'
      /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/tmpdir.rb:85:in `mktmpdir'
      /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:29:in `update'
      /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:64:in `update'
      /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:55:in `update_and_parse_checksums!'
      /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/fetcher/compact_index.rb:65:in `available?'
      /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/fetcher/compact_index.rb:15:in `call'
      /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/fetcher/compact_index.rb:15:in `block in compact_index_request'
      /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/fetcher.rb:154:in `use_api'
      /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:331:in `block in api_fetchers'
      /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:331:in `select'
      /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:331:in `api_fetchers'
      /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:336:in `block in remote_specs'
      /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/index.rb:10:in `build'
      /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:335:in `remote_specs'
      /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:82:in `specs'
      /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/lazy_specification.rb:56:in `__materialize__'
      /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/spec_set.rb:91:in `block in materialize'
      /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/spec_set.rb:88:in `map!'
      /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/spec_set.rb:88:in `materialize'
      /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/definition.rb:140:in `specs'
      /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/definition.rb:129:in `resolve_remotely!'
      /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/installer.rb:195:in `resolve_if_need'
      /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/installer.rb:70:in `run'
      /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/installer.rb:22:in `install'
      /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/cli/install.rb:102:in `run'
      /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/cli.rb:175:in `install'
      /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/cli.rb:11:in `start'
      /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/exe/bundle:27:in `block in <top (required)>'
      /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
      /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/exe/bundle:19:in `<top (required)>'
      /usr/local/bin/bundle:23:in `load'
      /usr/local/bin/bundle:23:in `<main>'

Environment
      
  Bundler   1.12.5
  Rubygems  2.4.5.1
  Ruby      2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin15]
  GEM_HOME  /private/var/folders/_r/xlnbsv0x6kn2n51l4942ly2c0000gn/T/ruby-build.20170611025745.26672/rubinius-3.75/vendor/bundle/ruby/2.2.0
  GEM_PATH  
  Git       2.9.3
      
      Bundler settings
      
  no_prune
    Set for your local app (/private/var/folders/_r/xlnbsv0x6kn2n51l4942ly2c0000gn/T/ruby-build.20170611025745.26672/rubinius-3.75/.bundle/config): "true"
  path
    Set for your local app (/private/var/folders/_r/xlnbsv0x6kn2n51l4942ly2c0000gn/T/ruby-build.20170611025745.26672/rubinius-3.75/.bundle/config): "vendor/bundle"
  disable_shared_gems
    Set for your local app (/private/var/folders/_r/xlnbsv0x6kn2n51l4942ly2c0000gn/T/ruby-build.20170611025745.26672/rubinius-3.75/.bundle/config): true
  orig_path
    Set via BUNDLE_ORIG_PATH: "/usr/local/Cellar/rbenv/1.1.0/libexec:/opt/local/bin:/opt/local/sbin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/git/bin:/opt/ImageMagick/bin:/Users/rolandgolla/.rvm/bin"
--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/bundler/bundler/search?q=Permission+denied+%40+dir_s_mkdir+-+%2FUsers%2Frolandgolla%2F.bundle%2Fcache%2Fcompact_index%2Frubygems.org.443.29b0360b937aa4d161703e6160654e47%2Fversions20170611-26861-d9lbwh&type=Issues

If there aren't any reports for this error yet, please create copy and paste the report template above into a new issue. Don't forget to anonymize any private data! The new issue form is located at:
https://github.com/bundler/bundler/issues/new

**Comment by segiddins** [comment]
Please fill out the error template

**Comment by beekingmala29** [comment]
https://github.com/bundler/bundler/search?q=Permission+denied+%40+dir_s_mkdir+-%%%%2FUsers%2Frolandgolla%2F กำ% 2Fcache% 2Fcompact_index% 2Frubygems.org.443.29b0360b937aa4d161703e6160654e47% 2Fversions20170611-26861-d9lbwh & type = ปัญหา

**Comment by rogoit** [comment]
This is the content of my error template

**Comment by segiddins** [comment]
Please fill out he questions at the top so we can understand the issue that you're facing.
