### ISSUE TITLE
Je Permission

### ISSUE THREAD

**Issue by beekingmala29** [bundler/bundler#5711]
https://github.com/bundler/bundler/search?q=Permission+denied+%40+dir_s_mkdir+-%%%%2FUsers%2Frolandgolla%2F กำ% 2Fcache% 2Fcompact_index% 2Frubygems.org.443.29b0360b937aa4d161703e6160654e47% 2Fversions20170611-26861-d9lbwh & type = ปัญหา

**Comment by colby-swandale** [comment]
Hi, can you please follow the [ISSUES](https://github.com/bundler/bundler/blob/master/doc/contributing/ISSUES.md) guide, it really helps us to try and resolve your problem.
