### ISSUE TITLE
Add a PR template to answer all of André's inevitable questions

### ISSUE THREAD

**Issue by segiddins** [bundler/bundler#5715]
@indirect, we discussed this in slack. If you'd like to add a template to pester me instead of doing so manually, go ahead!

**Comment by indirect** [comment]
@segiddins here are the questions I think we should answer about any PR, please add this to the dotfile that gets used as the PR template, formatted as you think appropriate:

```
What was the end-user problem that led to this PR?
Was was your diagnosis of that problem?
What is your fix for the problem, implemented in this PR?
Why did you choose that fix out of the possible options?
```
