### ISSUE TITLE
Feature: Check permissions on Bundler home directory in doctor command 

### ISSUE THREAD

**Issue by colby-swandale** [bundler/bundler#5786]
We should have a check in `bundle doctor` for the file/folder permissions in the Bundler home directory.

We should print a warning if there are any files/folders that is owned by another user but is readable/writable but prints an error when a file cannot be read or written to.

See: #5691

**Comment by indirect** [comment]
👍🏻

**Comment by gxespino** [comment]
Working on this issue - should be fun!

**Comment by ajwann** [comment]
@gxespino are you still working on this? If not, do you mind if I try my hand at it?

**Comment by gxespino** [comment]
Sure don't! Have fun!

**Comment by ajwann** [comment]
@colby-swandale I'm working on this right now and will hopefully have a WIP PR up in an hour or two.

**Comment by ajwann** [comment]
Just so I understand this correctly, you want the doctor command to check inside the ```Bundler.home``` directory, find every file not owned by the current user (I was going to use ```Process.uid``` to determine current user), and then check to see if those files are writable. If they are writable, you want Bundler to attempt to write to each of those files to see if an exception is thrown.

Does this sound correct?

**Comment by colby-swandale** [comment]
This has been merged in #6129
