### ISSUE TITLE
Bundler 2.0 supported Ruby and RubyGems versions

### ISSUE THREAD

**Issue by indirect** [bundler/bundler#5789]
As we close in on the Bundler 2.0 release, we need to decide which Ruby and RubyGems versions we're going to support. First, some background information:

* Rails 5 requires Ruby 2.2.2+
* ruby-core has EOLed Ruby 2.1, and it will never get another patch
* ruby-core has placed Ruby 2.2 in "security maintenance", and will no longer fix bugs
* macOS 10.13 High Sierra ships with Ruby 2.3.3 and RubyGems 2.5.2

As a result of these things combined, I would like to propose that Bundler 2.0 ship with support for:

* Ruby 2.3.x with RubyGems 2.5.x
* Ruby 2.4.x with RubyGems 2.6.x

In the same spirit, I propose these policies for future version support:

1. Bundler will aim to support all future versions of Ruby and RubyGems at release or before.
2. Bundler will stop supporting Ruby versions at the same time as ruby-core moves them to "security maintenance phase".

If you have feelings about this, please chime in! Thanks, everyone.

**Comment by duckinator** [comment]
I completely agree with this approach. Supporting fewer versions would vastly simplify maintenance, and significantly reduce CI test time.

Currently, tests on Travis CI [take over an hour to run](https://travis-ci.org/bundler/bundler/builds/244375917), and are run for 37 Ruby/RubyGems version combinations &mdash; including a RubyGems version from 2011 and a Ruby version from 2008.

(And whenever CI testing for Windows is added, I would expect that to roughly double.)

**Comment by hmistry** [comment]
I agree with this direction as it's time to reduce legacy overhead and keep moving forward with ruby versions. We have v1.15 to cover all rubies <=2.2 and it's a fairly recent release with lots of improvements over the years. In a couple of yrs it may not matter as ruby is now on a yearly release schedule and will expire support for ruby 2.2 in less than a year. It's only this one year where we're being a bit aggressive and might see a reduced conversion rate to Bundler 2.0 or it might force people to migrate to ruby 2.3+ so they can use Bundler 2.0.

I also like that you'll be staying in sync with Ruby version support cycles from now on to prevent massive legacy support. Are rubygems support cycles also synchronized with ruby versions as well so we reduce the permutations? (I couldn't find it's requirements)

My vote... let's do it. 😃

**Comment by jules2689** [comment]
I think Rails has a great support schedule, so I'm glad to see Bundler adopting similar. Supporting such outdated Rubies and RubyGems drastically increases support debt and technical debt (with littered if/elses in the codebase). This in turn prevents the Bundler team and contributors from moving fast and makes it more difficult to provide a quality tool.

So vote :+1: yes as well

**Comment by colby-swandale** [comment]
This has been accepted by the Bundler core team, thanks everyone for your input.
