### ISSUE TITLE
Bundler versions

### ISSUE THREAD

**Issue by gavinlaking** [bundler/bundler#5794]
Bundler is now complaining:
```
The latest bundler is 1.15.1, but you are currently running 1.15.0.
To update, run `gem install bundler`
```
I shouldn't need to update the patch level of bundler in order to correctly determine the dependencies of my applications. I could understand this change for major version changes (e.g. breaking api changes) of bundler, but not minor changes and bug fixes.

As it transpires, the latest changes to bundler do not appear to affect `bundle install` functionality at all, so this 'enforcement' of version makes bundler no better than gems which improperly remove functionality between patch/minor versions and cause "dependency hell".

**Comment by colby-swandale** [comment]
@gavinlaking while we appreciate you raising this concern please watch your tone, your comment is coming off as quite rude.

**Comment by gavinlaking** [comment]
My apologies, this wasn't my intention.

I suppose my concern is that in a reproducible build environment, whereby the Gemfile.lock file has a hard coded bundler version, and the build script installs bundler, I as a user would not be able to complete my build without first changing either the Gemfile.lock, or installing a specific version of bundler. Both of these options are additional considerations which reduce the flexibility and power that bundler affords.

Thoughts?

**Comment by segiddins** [comment]
You're free to ignore the warning. But we regularly get bug reports from people who are running outdated Bundler versions, where we've already shipped fixes. We're a small team and can only ever really support one version at a time, so we want you to be on our best, most supported version.

**Comment by segiddins** [comment]
There's been no further discussion for the past month, closing.

**Comment by mkllnk** [comment]
Sad to see this closed, but understanding that you don't have the resources.

We actually like to lock the bundler version as well so that it is the same on the dev machine, on CI, on staging and production. This message can lead someone to believe they should update even though there are no problems with the current version. It would be nice to have a configuration option to deactivate the warning.

But if I were so keen, I should probably submit a pull request... ;-)
