### ISSUE TITLE
How to save the descriptors of the points which are in the 3D point clouds?

### ISSUE THREAD

**Issue by Shangareer** [bundler/bundler#5796]
Hi, friends. 
I want to save the descriptors of the points which are in the 3D point clouds to a TXT file. I find that the  process of saving the coordinates of the 3D points is written in the "BASE PATH/src/BundleIO.cpp" from line 822(yours may be diffirent). So the process of saving the SIFT feature descriptors can also be written in this cpp file, I think. However, I can't find which parameters I should use to do this. Is there anyone who has done the same job or has any idea? Please give me some advice. Thanks.

**Comment by segiddins** [comment]
I don't think this issue has anything to do with Bundler, the Ruby dependency manager for gems.

**Comment by Shangareer** [comment]
Oh, sorry, there is another open source library that is also named "bundler". I had intended to ask questions on its GitHub page but entered in this page by mistake due to my carelessness. Thanks for reply and reminding.  :)
