### ISSUE TITLE
New gem gemspec template assumes `git` on users systems

### ISSUE THREAD

**Issue by jakehow** [bundler/bundler#5810]
Currently the newgem template, used when a gem author runs `bundle gem newgem` produces a gemspec that assumes git is on a users system. 

Source: https://github.com/bundler/bundler/blob/master/lib/bundler/templates/newgem/newgem.gemspec.tt#L28-L30

Why Change?
============

This bit of code is currently being cargo-culted into a lot of gems which causes issues when you try to install a gem from source in an environment without git (read: its not possible without forking the gem).  We bump up against this when trying to bundle gems (from source) who have kept this code in docker containers which do not have git, but I am sure there are other situations out there with the same problem.

There is no reason to have a git requirement here, and the current code actually does not implement the spirit of what the `files` attribute expects.  The [docs](http://guides.rubygems.org/specification-reference/#files) for `files` read: 

> Only add files you can require to this list, not directories, etc.

Currently the code adds everything that is known by git and not in test,spec,features dirs to the array.

Possible Fixes
===========

There should be a pure ruby way to get the job done.  In our gems we use code like the following:

```ruby
spec.files         = Dir.glob("{bin,lib}/**/*")
```

Being this explicit, may cause more support since you are no longer grabbing every file in the project, but is more in line with what the expectation of rubygems is around the files array (according to the docs).  If the desire is to keep an identical value, it should be doable without shelling out to git.

Happy to open a PR if there is an acceptable strategy here.  Thanks

**Comment by indirect** [comment]
We specifically use git in order to respect gitignore files when building .gems. Back when we used Dir.glob it was very common for released gem packages to include the .gem files from previous versions, logs, temporary files, and other random crap. Because of that, this feature is effectively asking us to put a higher priority on docker images without git than we put on actual built .gem files.

The Bundler team's current suggested workaround for this issue is to install git in your docker images.

**Comment by indirect** [comment]
(One other possible workaround is to run `bundle package` on a machine with git, and copy the resulting `vendor/cache` to the machine without git. That will work for git gems.)

**Comment by segiddins** [comment]
>The Bundler team's current suggested workaround for this issue

Might I add, another suggestion is to either (a) edit the gemspec (b) not use `bundle gem`, since it is _intentionally_ a highly opinionated set of defaults (c) or run `gem build` if you want a completely self-contained gem

**Comment by jakehow** [comment]
@indirect I think maybe there is a little misunderstanding. I think there are perfectly workable solutions that handle your concerns, and do not prioritize docker over the default use case.

I hope I made it clear in my note I understand the intention. The workaround is not a usable one for a whole host of reasons,  currently we just fork any gem that is cargo-culting this and use the fork or try to get it upstreamed.

@segiddins We are running `bundle install` for our applications, so ideally our Gemfiles would just work. 

Like I mentioned, if you want identical behavior:  

> respect gitignore files when building .gems

it certainly seems possible and easy in pure ruby.

NB: my stricter example also does not have the issues you mentioned, but a user may be more likely to need to alter it if they are using a nonstandard gem layout.

**Comment by jakehow** [comment]
@indirect to be clear, the suggested work around of putting git everywhere is the one that doesn't work.  Having extra build steps, forking gems, etc is the status quo of what we are doing now.

Came here b/c I am sure others are experiencing this and the problem seems to be an easy fix w/ no downsides.

**Comment by segiddins** [comment]
I'm sorry, but I honestly don't understand why just changing the generated `.gemspec` doesn't work for you, if you'd rather it not use git?

**Comment by jakehow** [comment]
@segiddins we do change it in our gems, most authors don't.  The issue arises when third party gems we depend on use the generated code.*

* and are slow at releasing, in between releases, we are using a branch, etc,etc

**Comment by deivid-rodriguez** [comment]
What about adding a explicit list by default?

From the generated gem template:

```
$ git ls-files
.gitignore
.rspec
.travis.yml
CODE_OF_CONDUCT.md
Gemfile
LICENSE.txt
README.md
Rakefile
bin/console
bin/setup
lib/test_gem.rb
lib/test_gem/version.rb
spec/spec_helper.rb
spec/test_gem_spec.rb
test_gem.gemspec
```

I think only `test_gem.gemspec`, `lib/test_gem.rb`, `lib/test_gem/version.rb`, `LICENSE.txt`
and `README.md` (and maybe the Code of Conduct?) should be shipped. It seems like a small enough list to start explicit.

This might have the opposite effect of gem authors including "too few files" instead of "too much", but the gem wouldn't really work if they do that, so it would only probably happen in the very first releases (when only the gem author is using the gem). Once they figure this out and the file list starts to grow, they can make the conscious choice of switching to a `Dir.glob` pattern that makes sense for their gem layout, or whatever solution they want to use to build their "gem manifest".

**Comment by deivid-rodriguez** [comment]
> it certainly seems possible and easy in pure ruby.

I agree it seems possible to implement gitignore pattern matching in pure Ruby. I disagree on the "easy" part. Definitely not a one liner like the other solutions currently being used.

For reference:

* The spec: https://git-scm.com/docs/gitignore#_pattern_format.
* A ruby built-in that could help: http://ruby-doc.org/core-2.4.1/File.html#method-c-fnmatch.
* An implementation: https://github.com/highb/pathspec-ruby. Haven't looked at the code, so not sure how well it works. I know Hound uses it, but it doesn't seem very popular. It's a port of https://github.com/cpburnz/python-path-specification to Ruby.

**Comment by indirect** [comment]
Thanks for the discussion, everyone. As @deivid-rodriguez points out, it is neither simple nor easy to re-implement gitignore matching in pure Ruby. It's nice to know that there's a gem that can do it, but Bundler can't have gem dependencies, so we would either have to vendor the pathspec code or write our own implementation.

@jakehow I'm open to the possibility of replacing the system call to git with Ruby code instead, but I don't believe any of the Bundler team is currently interested in implementing that. If you can provide a PR that provides identical functionality in pure Ruby, we'll consider it.

**Comment by jakehow** [comment]
@indirect wanted to note, I will take a stab at it.

Didn't mean to imply I thought implementing the whole spec is easy, but I will try my hand, and check out the lib :)

Do you think getting out of the box equivalence is good enough or you think downstream tooling is relying on `git ls` being there?  Are people using this template for things other than bootstrapping a new gem project?

**Comment by colby-swandale** [comment]
This has been inactive for a while now so I'm going to close this.

**Comment by deivid-rodriguez** [comment]
@jakehow Sorry your questions were never answered...

> Do you think getting out of the box equivalence is good enough or you think downstream tooling is relying on git ls being there? Are people using this template for things other than bootstrapping a new gem project?

IMO, yes, I think out of the box equivalence is good enough.

**Comment by jakehow** [comment]
@deivid-rodriguez I've just been making PRs to undo this whenever I come across it in a downstream gem, since gem maintainers typically don't have an opinion on it.  It would be nice if this was removed, but not a battle I felt like was worth spending time on and moved on...
