### ISSUE TITLE
Error:"Bundler cannot continue"

### ISSUE THREAD

**Issue by vag6a** [bundler/bundler#5824]
............
  rails (~> 5.1.2)
  sass-rails (~> 5.0)
  selenium-webdriver
  spring
  spring-watcher-listen (~> 2.0.0)
  sqlite3
  turbolinks (~> 5)
  tzinfo-data
  uglifier (>= 1.3.0)
  web-console (>= 3.3.0)

BUNDLED WITH
   1.15.1
```

--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

**Comment by segiddins** [comment]
Please share the entire issue template, thank you!
