### ISSUE TITLE
`install` is ~4x slower than `check`

### ISSUE THREAD

**Issue by indirect** [bundler/bundler#5842]
As requested, here's a ticket with an example of how much slower `install` is than `check`, even when both commands are (theoretically) doing the same amount of work. For the record, in the no-op case I think it's fine for the `install` command to print "Bundle installed and ready. ✨" or something along those lines, instead of printing out "Using..." lines for every gem.

```
$ time bundle check
The Gemfile's dependencies are satisfied

real    0m0.614s
user    0m0.555s
sys     0m0.035s
```

```
$ time bundle install --quiet

real    0m2.182s
user    0m2.015s
sys     0m0.105s
```

Repro repo: https://gist.github.com/indirect/6f60f0db1e2f86804ca3ac7c01f2afc4

**Comment by segiddins** [comment]
> For the record, in the no-op case I think it's fine for the install command to print "Bundle installed and ready. ✨" or something along those lines, instead of printing out "Using..." lines for every gem.

Don't think I'll do this, as we get rid of the no-op using lines on 2.0 anyways 🌠
