### ISSUE TITLE
Different behavior between bundler 1.15.x and 1.14.6: wrong file required

### ISSUE THREAD

**Issue by Confusion** [bundler/bundler#5845]
I have the following situation, where Bundler 1.15.x fails in an unexpected way, while 1.14.6 work as expected. The error is
````
  Gem Load Error is: uninitialized constant SomeConstantDefinedInGem1
  Backtrace for gem load error is:
  /path/to/gem1-2.0.0/lib/xsd.rb:4:in `<top (required)>'
  /path/to/gem2-1.1.0/lib/gem2.rb:13:in `<top (required)>'
````
The failing line in `gem2.rb` contains a 
````
require 'xsd'
````
and since gem2 contains an `xsd.rb` on the same level as the `gem2.rb`, I would expect that file to be required. With Bundler 1.14.6 that is also the case and that file is being required. With bundler 1.15.x a file `xsd.rb` in a different gem, `gem1` (not named `xsd`) is being required.

We are not pushing the `gem1-2.0.0/lib` path onto the LOAD_PATH or anything like that, but perhaps Bundler 1.15.x does? Or for some reason it thinks there is a gem called 'xsd', because there is a file `xsd.rb` in the lib directory of a gem?

**Comment by colby-swandale** [comment]
Can you share your `bundle env`? We're not really able to help resolve your issue without a way for us to reproduce the problem ourselves. Thanks.

**Comment by colby-swandale** [comment]
ping @Confusion

**Comment by Confusion** [comment]
Sorry for not responding, don't have much free time currently. I was trying to come up with a minimal reproduction, but didn't succeed so far. The `bundle env` references a bunch of our internal gems, so I'm afraid it won't be much help, as you can't reproduce the situation from that.

**Comment by Confusion** [comment]
I was wrong. The two gems were supposed to be identical except for some code differences, but for some reason one actually does specify `s.require_paths = ['lib']` in the gemspec.
