### ISSUE TITLE
Difference between 1.14.6 and 1.15.1 - Not finding a compatible dependency (multi_json)

### ISSUE THREAD

**Issue by jramnani** [bundler/bundler#5846]
I have a Gemfile that works in Bundler `1.14.6` and not in `1.15.1`, and I'm not sure why.

Here is the error message I get when running `bundle install` using version `1.15.1`:

```
Downloading pygments.rb-1.1.2 revealed dependencies not in the API or the lockfile (multi_json (>= 1.0.0)).
Either installing with `--full-index` or running `bundle update pygments.rb` should fix the problem.
```

Here is my Bundler environment from using the `bundle env` command:

```
The git source `git://github.com/mylesmegyesi/jekyll-s3-upload.git` uses the `git` protocol, which transmits data without encryption. Disable this warning with `bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.
```

## Environment

```
Bundler   1.15.1
Rubygems  2.2.2
Ruby      2.1.5p273 (2014-11-13 revision 48405) [x86_64-darwin16.0]
GEM_HOME  /usr/local/var/rbenv/versions/2.1.5/gemsets/bundler-test
GEM_PATH  /usr/local/var/rbenv/versions/2.1.5/gemsets/bundler-test:/usr/local/var/rbenv/versions/2.1.5/gemsets/global:/usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0
Git       2.13.0
Platform  x86_64-darwin-16
```

### Gemfile

```ruby
source 'https://rubygems.org'

group :development do
  gem 'activesupport',        '4.2.1'
  gem 'compass',              '1.0.3'
  gem 'jekyll',               '2.5.3'
  gem 'loofah',               '2.0.2'
  gem 'rake',                 '10.4.2'
  gem 'RedCloth',             '4.2.9'
  gem 'rugged',               '0.22.2'
  gem 'uglifier',             '2.7.1'
  gem 'pry'
end

group :jekyll_plugins do
  gem 'jekyll-archives',      '2.0.0'
  gem 'jekyll-assets',        '0.14.0'
  gem 'jekyll-contentblocks', '1.2.0'
  gem 'jekyll-redirect-from', '0.6.2'
  gem 'jekyll-sitemap',       '0.8.1'
  gem 'jekyll-s3-upload',     github: 'mylesmegyesi/jekyll-s3-upload', ref: '23e5457dcf2d1068e18463d399b38a4f9d5c340b'
end
```

### Gemfile.lock

```
GIT
  remote: git://github.com/mylesmegyesi/jekyll-s3-upload.git
  revision: 23e5457dcf2d1068e18463d399b38a4f9d5c340b
  ref: 23e5457dcf2d1068e18463d399b38a4f9d5c340b
  specs:
    jekyll-s3-upload (0.0.1)
      activesupport (>= 3.0.0)
      aws-sdk (~> 2.0.45)
      dotenv (~> 2.0.1)
      rack (~> 1.6.1)

GEM
  remote: https://rubygems.org/
  specs:
    RedCloth (4.2.9)
    activesupport (4.2.1)
      i18n (~> 0.7)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.3, >= 0.3.4)
      tzinfo (~> 1.1)
    addressable (2.3.8)
    aws-sdk (2.0.48)
      aws-sdk-resources (= 2.0.48)
    aws-sdk-core (2.0.48)
      builder (~> 3.0)
      jmespath (~> 1.0)
      multi_json (~> 1.0)
    aws-sdk-resources (2.0.48)
      aws-sdk-core (= 2.0.48)
    blankslate (2.1.2.4)
    builder (3.2.2)
    celluloid (0.16.0)
      timers (~> 4.0.0)
    chunky_png (1.3.4)
    classifier-reborn (2.0.3)
      fast-stemmer (~> 1.0)
    coderay (1.1.0)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.9.1.1)
    colorator (0.1)
    compass (1.0.3)
      chunky_png (~> 1.2)
      compass-core (~> 1.0.2)
      compass-import-once (~> 1.0.5)
      rb-fsevent (>= 0.9.3)
      rb-inotify (>= 0.9)
      sass (>= 3.3.13, < 3.5)
    compass-core (1.0.3)
      multi_json (~> 1.0)
      sass (>= 3.3.0, < 3.5)
    compass-import-once (1.0.5)
      sass (>= 3.2, < 3.5)
    dotenv (2.0.2)
    execjs (2.5.2)
    fast-stemmer (1.0.2)
    fastimage (1.7.0)
      addressable (~> 2.3, >= 2.3.5)
    ffi (1.9.8)
    hike (1.2.3)
    hitimes (1.2.2)
    i18n (0.7.0)
    jekyll (2.5.3)
      classifier-reborn (~> 2.0)
      colorator (~> 0.1)
      jekyll-coffeescript (~> 1.0)
      jekyll-gist (~> 1.0)
      jekyll-paginate (~> 1.0)
      jekyll-sass-converter (~> 1.0)
      jekyll-watch (~> 1.1)
      kramdown (~> 1.3)
      liquid (~> 2.6.1)
      mercenary (~> 0.3.3)
      pygments.rb (~> 0.6.0)
      redcarpet (~> 3.1)
      safe_yaml (~> 1.0)
      toml (~> 0.1.0)
    jekyll-archives (2.0.0)
      jekyll (~> 2.4)
    jekyll-assets (0.14.0)
      fastimage (~> 1.6)
      jekyll (~> 2.0)
      mini_magick (~> 4.1)
      sass (~> 3.2)
      sprockets (~> 2.10)
      sprockets-helpers
      sprockets-sass
    jekyll-coffeescript (1.0.1)
      coffee-script (~> 2.2)
    jekyll-contentblocks (1.2.0)
      jekyll
    jekyll-gist (1.2.1)
    jekyll-paginate (1.1.0)
    jekyll-redirect-from (0.6.2)
      jekyll (~> 2.0)
    jekyll-sass-converter (1.3.0)
      sass (~> 3.2)
    jekyll-sitemap (0.8.1)
    jekyll-watch (1.2.1)
      listen (~> 2.7)
    jmespath (1.3.0)
    json (1.8.6)
    kramdown (1.7.0)
    liquid (2.6.2)
    listen (2.10.0)
      celluloid (~> 0.16.0)
      rb-fsevent (>= 0.9.3)
      rb-inotify (>= 0.9)
    loofah (2.0.2)
      nokogiri (>= 1.5.9)
    mercenary (0.3.5)
    method_source (0.8.2)
    mini_magick (4.2.7)
    mini_portile (0.6.2)
    minitest (5.7.0)
    multi_json (1.11.0)
    nokogiri (1.6.6.2)
      mini_portile (~> 0.6.0)
    parslet (1.5.0)
      blankslate (~> 2.0)
    posix-spawn (0.3.13)
    pry (0.10.1)
      coderay (~> 1.1.0)
      method_source (~> 0.8.1)
      slop (~> 3.4)
    pygments.rb (1.1.2)
      posix-spawn (~> 0.3.6)
      yajl-ruby (~> 1.2.0)
    rack (1.6.1)
    rake (10.4.2)
    rb-fsevent (0.9.5)
    rb-inotify (0.9.5)
      ffi (>= 0.5.0)
    redcarpet (3.2.3)
    rugged (0.22.2)
    safe_yaml (1.0.4)
    sass (3.4.14)
    slop (3.6.0)
    sprockets (2.12.3)
      hike (~> 1.2)
      multi_json (~> 1.0)
      rack (~> 1.0)
      tilt (~> 1.1, != 1.3.0)
    sprockets-helpers (1.1.0)
      sprockets (~> 2.0)
    sprockets-sass (2.0.0.beta2)
      sprockets (~> 2.0)
      tilt (~> 1.1)
    thread_safe (0.3.5)
    tilt (1.4.1)
    timers (4.0.1)
      hitimes
    toml (0.1.2)
      parslet (~> 1.5.0)
    tzinfo (1.2.2)
      thread_safe (~> 0.1)
    uglifier (2.7.1)
      execjs (>= 0.3.0)
      json (>= 1.8.0)
    yajl-ruby (1.2.2)

PLATFORMS
  ruby

DEPENDENCIES
  RedCloth (= 4.2.9)
  activesupport (= 4.2.1)
  compass (= 1.0.3)
  jekyll (= 2.5.3)
  jekyll-archives (= 2.0.0)
  jekyll-assets (= 0.14.0)
  jekyll-contentblocks (= 1.2.0)
  jekyll-redirect-from (= 0.6.2)
  jekyll-s3-upload!
  jekyll-sitemap (= 0.8.1)
  loofah (= 2.0.2)
  pry
  rake (= 10.4.2)
  rugged (= 0.22.2)
  uglifier (= 2.7.1)
```

**Comment by jramnani** [comment]
Running `bundle update pygments.rb` as suggested by Bundler will downgrade `pygments.rb` to version `0.6.3` from `1.1.2`, and then will give me an error on `sprockets-sass`:

```
Downloading sprockets-sass-2.0.0.beta2 revealed dependencies not in the API or the lockfile (sprockets (< 4.0, >= 2.0)).
Either installing with `--full-index` or running `bundle update sprockets-sass` should fix the problem.
```

Running `bundle update sprockets-sass` as suggested, shows the following dependency conflict:

```
Bundler could not find compatible versions for gem "pygments.rb":
  In snapshot (Gemfile.lock):
    pygments.rb (= 1.1.2)

  In Gemfile:
    jekyll-contentblocks (= 1.2.0) was resolved to 1.2.0, which depends on
      jekyll was resolved to 2.5.3, which depends on
        pygments.rb (~> 0.6.0)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
```

When I run `bundle update` it resolves this final conflict, and the environment builds.  However, when I try to run my program, `jekyll serve -w --drafts`, I get an error because Bundler is using an old version of `pygments.rb`.  It's using `0.6.3` instead of `1.1.2`.  From reading the error message above, I assume I'm getting `pygments.rb` version `0.6.3` because `jekyll (2.5.3)` still depends on it?

I suppose my question ends up being: Why do the existing project dependencies work in 1.14.x, but not in 1.15.x?

Thank you for those error messages, btw.  They were helpful in getting to this point.

**Comment by segiddins** [comment]
The issue is your lockfile is essentially corrupted -- it's missing the dependencies for some of your gems. Those commands are just suggestions, once a lockfile gets corrupted by a buggy version of bundler, the only 100% foolproof way of fixing is doing so by hand.

**Comment by jramnani** [comment]
Thank you for responding. :)  Some follow-up questions:

* Is this a case where version 1.15.x is being more strict about the state of the lock file than 1.14?
* Can I print out a tree of dependencies from my Gemfile so I might see where the problem is?  Perhaps what I'm asking for is already available as `bundle viz`?
* My Bundler skills are pretty rusty.  To fix this error will I need to edit the `Gemfile.lock` file directly, or will it be good enough to delete the lock file and run `bundle lock` to generate a new one?

**Comment by chrismo** [comment]
For you 3rd question, I'd suggest saving off the current Gemfile.lock (or commit to source control), then do `bundle lock` and diff the two. A brand new install will grab the latest versions of gems that match the stated requirements in your Gemfile, which could be very different (including a major version upgrade). Probably the bulk of the changes won't matter, but that may draw out the offending corruption.

**Comment by segiddins** [comment]
> Is this a case where version 1.15.x is being more strict about the state of the lock file than 1.14?

Yeah, it's us trying to fix other bugs and generally avoid deadlocks when installing

> Can I print out a tree of dependencies from my Gemfile so I might see where the problem is? Perhaps what I'm asking for is already available as bundle viz?

`bundle viz` in this case will fail, but we _should_ be printing out where the problem is when this sort of installation error happens, and I'll make that change now ;)

Otherwise, I recommend reading through the lockfile to see what required the gem that's failing to install

> My Bundler skills are pretty rusty. To fix this error will I need to edit the Gemfile.lock file directly, or will it be good enough to delete the lock file and run bundle lock to generate a new one?

Honestly, I recommend deleting the lockfile and starting from scratch, you can add more specific version requirements to your Gemfile if necessary to get the versions you need

**Comment by segiddins** [comment]
In this case:

```
Downloading pygments.rb-1.1.2 revealed dependencies not in the API or the
lockfile (multi_json (>= 1.0.0)).
Either installing with `--full-index` or running `bundle update pygments.rb`
should fix the problem.

In Gemfile:
  jekyll-archives was resolved to 2.0.0, which depends on
    jekyll was resolved to 2.5.3, which depends on
      pygments.rb
```

**Comment by segiddins** [comment]
https://github.com/bundler/bundler/pull/5850 should make the error message slightly more helpful!

**Comment by jramnani** [comment]
I've been able to fix the issue with my Gemfile by deleting the lock file, generating a new one, and fixing any issues that came up during that process.  Part of the fix for me was upgrading Jekyll to a version that was compatible with `pygments.rb (1.1.2)`.  Actually, I think later versions of Jekyll remove their explicit dependency on `pygments.rb (0.6.0)` which makes this easier after the upgrade.

Thank you very much for helping me with this issue.  Thanks, also for submitting #5850 since that will save people a bunch of time going forward.

We can close this, if you like. Or keep it open until #5850 gets merged.

**Comment by segiddins** [comment]
Awesome, glad to hear it!
