### ISSUE TITLE
Special-case `binstubs bundler` for the app's bundler version

### ISSUE THREAD

**Issue by indirect** [bundler/bundler#5876]
Once Bundler 2 ships, each application will depend on a 1.x or 2.x version of Bundler. One way to ensure that the application will always get the version of Bundler that it needs is with an application-and-bundler-version specific binstub. Let's make it so that `bundle binstubs bundler` will generate a binstub for the correct version of Bundler, and simply running `bin/bundle` will always provide the correct version of Bundler.

**Comment by segiddins** [comment]
Should we also change the normal binstubs (that call `require "bundler/setup"`) to make sure the correct bundler version is activated?

**Comment by indirect** [comment]
Good question. I'm not sure, but it sounds like probably we will want this, yes. Ideally in a dynamic way, so that the binstubs don't need to be regenerated after the app migrates from Bundler 1 to Bundler 2? But if we can't do that, we should provide a command that iterates over all existing binstubs and upgrades them from Bundler 1 to Bundler 2.

**Comment by segiddins** [comment]
`bundle binstubs ... --force` will always overwrite binstubs with the newest version
