### ISSUE TITLE
Intermittent `NameError: uninitialized constant Bundler::RubyGemsGemInstaller` during bundle install

### ISSUE THREAD

**Issue by dgodd** [bundler/bundler#5886]
Very infrequently when running 
```
$ bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
```
we receive an error similar to the below
```
Installing daemons 1.2.3
Installing eventmachine 1.0.7 with native extensions
Installing rack 1.5.2
Using bundler 1.14.3
NameError: uninitialized constant Bundler::RubyGemsGemInstaller
An error occurred while installing eventmachine (1.0.7), and Bundler cannot continue.
```

It does not appear to be related to which gems are being installed, but the error `NameError: uninitialized constant Bundler::RubyGemsGemInstaller` is consistent

I have tried to investigate and to come up with an even remotely repeatable scenario to no avail.

The closest I have come is to a suspicion that it might be related to `autoload` and the `-j4` flag. Hopefully this suspicion is wrong, and someone with more knowledge of bundler can discover a fix.

**Comment by segiddins** [comment]
Please share the output on `bundle env` and ensure you're running the latest released version of Bundler 1.15.2.

**Comment by dgodd** [comment]
I have data for 1.15.1 ; I will start running tests against 1.15.2 and report back when I have data

```
$ bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin --jobs=4 --retry=4 --deployment
```
Installing rack 1.5.2
Installing tilt 1.4.1
Using bundler 1.15.1
NameError: uninitialized constant Bundler::RubyGemsGemInstaller
An error occurred while installing tilt (1.4.1), and Bundler cannot continue.
Make sure that `gem install tilt -v '1.4.1'` succeeds before bundling.
```

Bundle env was done on the same setup but at a later time
```
bundle env
```

## Environment
```
Bundler   1.15.1
Rubygems  2.6.11
Ruby      2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
GEM_HOME  /tmp/app/vendor/bundle/ruby/2.4.0
GEM_PATH  /tmp/app/vendor/bundle/ruby/2.4.0:/tmp/app/.cloudfoundry/0/bundler-1.15.1
Git       1.9.1
Platform  x86_64-linux
```
## Bundler settings
```
gemfile
Set via BUNDLE_GEMFILE: "/tmp/app/Gemfile"
config
Set via BUNDLE_CONFIG: "/tmp/app/.bundle/config"
```
## Gemfile
### Gemfile
```ruby
source 'https://rubygems.org'
gem 'sinatra'
```
### Gemfile.lock
```
GEM
remote: https://rubygems.org/
specs:
rack (1.5.2)
rack-protection (1.5.0)
rack
sinatra (1.4.3)
rack (~> 1.4)
rack-protection (~> 1.4)
tilt (~> 1.3, >= 1.3.4)
tilt (1.4.1)
PLATFORMS
ruby
DEPENDENCIES
sinatra
BUNDLED WITH
1.10.6
```

**Comment by sclevine** [comment]
Some broader context: @dgodd and I are on the team that maintains the Cloud Foundry Ruby Buildpack. Users of the buildpack have been reporting this error for a number of months, and repeated investigations have ruled out causes outside of Bundler, in our opinion.

@RochesterinNYC is a former contributor to the buildpack and participated in one of those investigations.

Additional context, including the failure with 1.15.1, is available here: https://github.com/cloudfoundry/ruby-buildpack/issues/72

**Comment by dgodd** [comment]
Here is the output whilst using Bundler 1.15.3

```
$ bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin --jobs=4 --retry=4 --deployment

          Using bundler 1.15.3
          Installing tilt 1.4.1
          Installing rack 1.5.2
          Make sure that `gem install tilt -v '1.4.1'` succeeds before bundling.
          Installing rack 1.5.2
          sinatra was resolved to 1.4.3, which depends on
          Installing tilt 1.4.1
          NameError: uninitialized constant Bundler::RubyGemsGemInstaller
          In Gemfile:
          tilt
          NameError: uninitialized constant Bundler::RubyGemsGemInstaller
          Make sure that `gem install tilt -v '1.4.1'` succeeds before bundling.
```

**Comment by segiddins** [comment]
I thought autoload was supposed to be thread safe in Ruby 2+?

**Comment by dgodd** [comment]
http://blade.nagaokaut.ac.jp/cgi-bin/scat.rb/ruby/ruby-core/77362 suggests that autoload is still unsafe. I just did a quick test myself, and ran the code in that url on ruby 2.3.1p112

```
irb(main):001:0> Thread.abort_on_exception = true
=> true
irb(main):002:0>
irb(main):003:0* loop do
irb(main):004:1*   class Foo
irb(main):005:2>     autoload :Bar, 'bar.rb'
irb(main):006:2>   end
irb(main):007:1>
irb(main):008:1*   go = false
irb(main):009:1>   threads = (1..50).map {Thread.new { 1 until go; Foo.const_get(:Bar); print '.' }}
irb(main):010:1>   go = true
irb(main):011:1>   threads.each(&:join)
irb(main):012:1>   puts
irb(main):013:1>
irb(main):014:1*   self.class.send :remove_const, :Foo
irb(main):015:1> end
..................................................
NameError: uninitialized constant Foo::Bar
Did you mean?  Foo::Bar
	from (irb):9:in `const_get'
	from (irb):9:in `block (3 levels) in irb_binding'
irb(main):016:0> (irb):9:in `const_get': uninitialized constant Foo::Bar (NameError)
Did you mean?  Foo::Bar
	from (irb):9:in `block (3 levels) in irb_binding'
```

bar.rb
```
class Foo
  class Bar

  end
end
```

**Comment by segiddins** [comment]
https://bugs.ruby-lang.org/issues/11384 suggests its a bug that ruby-core have fixed

**Comment by reneighbor** [comment]
Here is the `bundler env` output from an environment where this occurred:

vcap@f7f0100c-943d-4ed2-7fce-8c00:~$ bundle env
## Environment

```
Bundler   1.15.1
Rubygems  2.6.11
Ruby      2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
GEM_PATH  /home/vcap/app/vendor/bundle/ruby/2.4.0:/0/bundler-1.15.1
Git       1.9.1
Platform  x86_64-linux
```

## Bundler settings

```
retry
  Set for your local app (/home/vcap/app/.bundle/config): "4"
  Set for the current user (/home/vcap/app/.bundle/config): "4"
frozen
  Set for your local app (/home/vcap/app/.bundle/config): "1"
  Set for the current user (/home/vcap/app/.bundle/config): "1"
path
  Set for your local app (/home/vcap/app/.bundle/config): "vendor/bundle"
  Set for the current user (/home/vcap/app/.bundle/config): "vendor/bundle"
bin
  Set for your local app (/home/vcap/app/.bundle/config): "vendor/bundle/bin"
  Set for the current user (/home/vcap/app/.bundle/config): "vendor/bundle/bin"
jobs
  Set for your local app (/home/vcap/app/.bundle/config): "4"
  Set for the current user (/home/vcap/app/.bundle/config): "4"
without
  Set for your local app (/home/vcap/app/.bundle/config): "development:test"
  Set for the current user (/home/vcap/app/.bundle/config): "development:test"
disable_shared_gems
  Set for your local app (/home/vcap/app/.bundle/config): "true"
  Set for the current user (/home/vcap/app/.bundle/config): "true"
```

## Gemfile

### Gemfile

```ruby
source 'https://rubygems.org'

gem 'sinatra'
```

### Gemfile.lock

```
GEM

**Comment by segiddins** [comment]
Closing due to lack of response

**Comment by volkanunsal** [comment]
I'm seeing the same intermittent error in 2.3.3.
