### ISSUE TITLE
Bundler issue

### ISSUE THREAD

**Issue by sandeepmamidi** [bundler/bundler#5894]
BUNDLED WITH
   1.14.6
```

--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/bundler/bundler/search?q=undefined+method+%60include%3F%27+for+nil+NilClass&type=Issues

If there aren't any reports for this error yet, please create copy and paste the report template above into a new issue. Don't forget to anonymize any private data! The new issue form is located at:
https://github.com/bundler/bundler/issues/new
ERROR: Service 'web' failed to build: The command '/bin/sh -c bundle install' returned a non-zero code: 1

**Comment by Zorbash** [comment]
@sandeepmamidi Can you please provide some more info? Mind following 
this guide?
https://github.com/bundler/bundler/blob/master/doc/contributing/ISSUES.md#reporting-unresolved-problems

**Comment by sandeepmamidi** [comment]
@Zorbash 
after executing "bundle env" below is the output 
 
$ bundle env
Bundler 1.3.5
Ruby 1.9.3 (2013-11-22 patchlevel 484) [x86_64-linux]
Rubygems 2.6.12
GEM_HOME


Gemfile
<No Gemfile found>


Gemfile.lock
<No Gemfile.lock found>

**Comment by colby-swandale** [comment]
@sandeepmamidi can you please attach the entire output of the `bundle env` command

**Comment by sandeepmamidi** [comment]
@colby-swandale 

i am attaching the command in text file
[bundle_env .txt](https://github.com/bundler/bundler/files/1169791/bundle_env.txt)

**Comment by colby-swandale** [comment]
@sandeepmamidi you're using a very old version of Bundler. Can you please update to the latest version and let us know if you're still getting your error.

You can update to the latest version using RubyGems:
```
gem install bundler
```

**Comment by sandeepmamidi** [comment]
@colby-swandale 
after upgrading the bundler also i am getting similar issue

docker env
# bundle env
## Environment

```
Bundler   1.15.3
Rubygems  2.6.12
Ruby      1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]
Git       1.9.1
Platform  x86_64-linux
OpenSSL   OpenSSL 1.0.1f 6 Jan 2014
```

**Comment by sandeepmamidi** [comment]
@colby-swandale 


BUNDLED WITH
   1.14.6
```

--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/bundler/bundler/search?q=undefined+method+%60include%3F%27+for+nil+NilClass&type=Issues

If there aren't any reports for this error yet, please create copy and paste the report template above into a new issue. Don't forget to anonymize any private data! The new issue form is located at:
https://github.com/bundler/bundler/issues/new
ERROR: Service 'web' failed to build: The command '/bin/sh -c bundle install' returned a non-zero code: 1

**Comment by colby-swandale** [comment]
Unfortunately this does not help. You need to attach _everything_ that bundler prints in the console when you run `bundle install` including the error template this is pasted between:

`````
--- ERROR REPORT TEMPLATE -------------------------------------------------------
...
--- TEMPLATE END ----------------------------------------------------------------
````

**Comment by sandeepmamidi** [comment]
@Zorbash 

# sh repro-1489.sh
+ mkdir -p /tmp/repro-1489
+ cd /tmp/repro-1489
+ bundle env
## Environment

```
Bundler   1.15.3
Rubygems  2.6.12
Ruby      1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]
Git       1.9.1
Platform  x86_64-linux
OpenSSL   OpenSSL 1.0.1f 6 Jan 2014
```

## Gemfile

### Gemfile

```ruby
source "http://rubygems.org"
gem '', git: 'https://github.com/square/cane.git'
```

### Gemfile.lock

```
<No /tmp/repro-1489/Gemfile.lock found>
```
+ export GIT_DIR=bla
+ export GIT_WORK_TREE=bla
+ cat
+ bundle install
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.
Fetching https://github.com/square/cane.git
fatal: unable to access 'https://github.com/square/cane.git/': Received HTTP code 403 from proxy after CONNECT

Retrying `git fetch --force --quiet --tags 'https://github.com/square/cane.git' "refs/heads/*:refs/heads/*"` due to error (2/4): Bundler::Source::Git::GitCommandError Git error: command `git fetch --force --quiet --tags 'https://github.com/square/cane.git' "refs/heads/*:refs/heads/*"` in directory /var/lib/gems/1.9.1/cache/bundler/git/cane-3eac954109f26bd06d9e1674cce430bc14a50eec has failed.
If this error persists you could try removing the cache directory '/var/lib/gems/1.9.1/cache/bundler/git/cane-3eac954109f26bd06d9e1674cce430bc14a50eec'fatal: unable to access 'https://github.com/square/cane.git/': Received HTTP code 403 from proxy after CONNECT

Retrying `git fetch --force --quiet --tags 'https://github.com/square/cane.git' "refs/heads/*:refs/heads/*"` due to error (3/4): Bundler::Source::Git::GitCommandError Git error: command `git fetch --force --quiet --tags 'https://github.com/square/cane.git' "refs/heads/*:refs/heads/*"` in directory /var/lib/gems/1.9.1/cache/bundler/git/cane-3eac954109f26bd06d9e1674cce430bc14a50eec has failed.
If this error persists you could try removing the cache directory '/var/lib/gems/1.9.1/cache/bundler/git/cane-3eac954109f26bd06d9e1674cce430bc14a50eec'fatal: unable to access 'https://github.com/square/cane.git/': Received HTTP code 403 from proxy after CONNECT

Retrying `git fetch --force --quiet --tags 'https://github.com/square/cane.git' "refs/heads/*:refs/heads/*"` due to error (4/4): Bundler::Source::Git::GitCommandError Git error: command `git fetch --force --quiet --tags 'https://github.com/square/cane.git' "refs/heads/*:refs/heads/*"` in directory /var/lib/gems/1.9.1/cache/bundler/git/cane-3eac954109f26bd06d9e1674cce430bc14a50eec has failed.
If this error persists you could try removing the cache directory '/var/lib/gems/1.9.1/cache/bundler/git/cane-3eac954109f26bd06d9e1674cce430bc14a50eec'fatal: unable to access 'https://github.com/square/cane.git/': Received HTTP code 403 from proxy after CONNECT

Git error: command `git fetch --force --quiet --tags
'https://github.com/square/cane.git' "refs/heads/*:refs/heads/*"` in directory
/var/lib/gems/1.9.1/cache/bundler/git/cane-3eac954109f26bd06d9e1674cce430bc14a50eec
has failed.
If this error persists you could try removing the cache directory
'/var/lib/gems/1.9.1/cache/bundler/git/cane-3eac954109f26bd06d9e1674cce430bc14a50eec'

**Comment by sandeepmamidi** [comment]
@colby-swandale 

i am running this command from putty i am not getting the full response

**Comment by colby-swandale** [comment]
I can see 2 issues here. One is that you have a gem in the Gemfile with an empty string in the name. But the issue you're running into that Bundler is complaining about is that you have a network proxy that is not allowing git to clone the repository from Github to your local machine.

```
Received HTTP code 403 from proxy after CONNECT
```

You will have to investigate how to authenticate to your proxy to let Bundler clone the repository.

**Comment by sandeepmamidi** [comment]
@colby-swandale 
when i am running git clone command it is getting without any issue
when i am using bundler it is not downloading. struck with that.

**Comment by Zorbash** [comment]
@sandeepmamidi are you running the `git clone https://github.com/square/cane.git` or `git clone git@github.com:square/cane.git`?

The proxy in your network might only be affecting HTTPS requests, the thing is that as @colby-swandale said above, even without a proxy you'd get:

```
Could not find gem '' in https://github.com/square/cane.git (at master@cf214b3).
Source does not contain any versions of ''
```

**Comment by colby-swandale** [comment]
ping @sandeepmamidi

**Comment by sandeepmamidi** [comment]
@colby-swandale 
There are multiple issues with that machine so we have formatted the machine. let me check once again and if the same issue persist i will re-open the issue.
