### ISSUE TITLE
Error in bundler update

### ISSUE THREAD

**Issue by riccardo79** [bundler/bundler#5898]
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `/usr/bin/bundle update`

Error details

    NoMethodError: private method `name_for' called for #<Bundler::Resolver:0x000000030807e8>
      /usr/lib/ruby/vendor_ruby/molinillo/delegates/specification_provider.rb:31:in `block in name_for'
      /usr/lib/ruby/vendor_ruby/molinillo/delegates/specification_provider.rb:69:in `with_no_such_dependency_error_handling'
      /usr/lib/ruby/vendor_ruby/molinillo/delegates/specification_provider.rb:30:in `name_for'
      /usr/lib/ruby/vendor_ruby/molinillo/resolution.rb:161:in `block (2 levels) in initial_state'
      /usr/lib/ruby/vendor_ruby/molinillo/resolution.rb:161:in `each'
      /usr/lib/ruby/vendor_ruby/molinillo/resolution.rb:161:in `block in initial_state'
      /usr/lib/ruby/vendor_ruby/molinillo/resolution.rb:160:in `tap'
      /usr/lib/ruby/vendor_ruby/molinillo/resolution.rb:160:in `initial_state'
      /usr/lib/ruby/vendor_ruby/molinillo/resolution.rb:106:in `start_resolution'
      /usr/lib/ruby/vendor_ruby/molinillo/resolution.rb:64:in `resolve'
      /usr/lib/ruby/vendor_ruby/molinillo/resolver.rb:42:in `resolve'
      /usr/lib/ruby/vendor_ruby/bundler/resolver.rb:199:in `start'
      /usr/lib/ruby/vendor_ruby/bundler/resolver.rb:182:in `resolve'
      /usr/lib/ruby/vendor_ruby/bundler/definition.rb:200:in `resolve'
      /usr/lib/ruby/vendor_ruby/bundler/definition.rb:140:in `specs'
      /usr/lib/ruby/vendor_ruby/bundler/definition.rb:129:in `resolve_remotely!'
      /usr/lib/ruby/vendor_ruby/bundler/installer.rb:79:in `run'
      /usr/lib/ruby/vendor_ruby/bundler/installer.rb:18:in `install'
      /usr/lib/ruby/vendor_ruby/bundler/cli/update.rb:51:in `run'
      /usr/lib/ruby/vendor_ruby/bundler/cli.rb:187:in `update'
      /usr/lib/ruby/vendor_ruby/thor/command.rb:27:in `run'
      /usr/lib/ruby/vendor_ruby/thor/invocation.rb:126:in `invoke_command'
      /usr/lib/ruby/vendor_ruby/thor.rb:369:in `dispatch'
      /usr/lib/ruby/vendor_ruby/thor/base.rb:444:in `start'
      /usr/lib/ruby/vendor_ruby/bundler/cli.rb:10:in `start'
      /usr/bin/bundle:20:in `block in <main>'
      /usr/lib/ruby/vendor_ruby/bundler/friendly_errors.rb:7:in `with_friendly_errors'
      /usr/bin/bundle:18:in `<main>'

Environment

    Bundler   1.10.6
    Rubygems  2.4.5.1
    Ruby      2.2.4p230 (2015-12-16 revision 0) [x86_64-linux-gnu]
    GEM_HOME  /var/lib/gems/2.2.0
    GEM_PATH  /var/lib/gems/2.2.0:/root/.gem/ruby/2.2.0:/usr/lib/x86_64-linux-gnu/rubygems-integration/2.2.0:/usr/share/rubygems-integration/2.2.0:/usr/share/rubygems-integration/2.2:/usr/share/rubygems-integration/all
    Git       2.13.2
--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/bundler/bundler/search?q=private+method+%60name_for%27+called+for+%23%3CBundler%3A%3AResolver%3A0x000000030807e8%3E&type=Issues

If there aren't any reports for this error yet, please create copy and paste the report template above into a new issue. Don't forget to anonymize any private data! The new issue form is located at:
https://github.com/bundler/bundler/issues/new

**Comment by segiddins** [comment]
Can you try with the latest Bundler, 1.15.3, please? Thank you!

**Comment by riccardo79** [comment]
I upgraded to v. 1.13.6 but the error disappeared.
Thanks
