### ISSUE TITLE
bundler and CI

### ISSUE THREAD

**Issue by lucabartoletti** [bundler/bundler#5899]
Hi, I use bundler to run fastlane in my iOS project. I work in a team so we share the Gemfile.lock in the repo.

We also have a CI machine that runs Jenkins. The problem we are experiencing is that sometimes when the CI machine checkout the repo and than the Gemfile.lock changes itself just after the checkout of the repo. I assume this is due to a versioning difference between the CI machine and what is specified in the Gemfile.lock.

In our build steps we have checks to verify that the git repo is clean before building it, so if the gem file is changed the build fails

What is the suggested way to keep the CI machine up to date and avoid the Gemfile.lock to change itself?

**Comment by segiddins** [comment]
Please share the information requested in http://bundler.io/doc/contributing/issues.html so we can try and understand what the issue is, thank you!

**Comment by arbonap** [comment]
hi @lucabartoletti, has your issue been resolved? how's it going?

**Comment by segiddins** [comment]
Closing due to lack of response
