### ISSUE TITLE
Adding --gemfile= selection as an argument to exec

### ISSUE THREAD

**Issue by lloeki** [bundler/bundler#5924]
I was trying to fix [this](https://github.com/vim-syntastic/syntastic/issues/2051) in a way that doesn't involve gruesome hacks and matryoshka wrappers by going something along [this route](https://github.com/vim-syntastic/syntastic#faqconfig) (4.9). Here's what I found:

- setting `BUNDLE_GEMFILE=where/is/Gemfool` and running `bundle exec rubocop -c where/is/.rubocop.yml where/is/my/file.rb` works but requires setting an env var which is impractical and cannot be done without side effects in some cases (e.g multiple projects open in a single vim instance)
- `cd`'ing into `where/is/my` and running `bundle exec rubocop file.rb` works but requires changing the pwd which cannot be done without side effects in some cases (vim plugins don't like things like `autochdir`)
- `bundle install --gemfile=Gemfool` is a thing when it can use `BUNDLE_GEMFILE` already, so *“there's BUNDLE_GEMFILE, use that”* doesn't seem to carry much weight
- running `env BUNDLE_GEMFILE=where/is/Gemfool bundle exec rubocop -c where/is/.rubocop.yml where/is/my/file.rb` works but may be hard to set as a command without side effects (vim-syntastic) so why is there `--gemfile=` for `install`? Also, maybe unix/shell dependent?
- `bundle exec` can already take an optional argument (`[--keep-file-descriptors]`) so it's not like it can't take more, so not accepting one more doesn't seem to carry much weight either

So what do you think about adding `--gemfile=` to `bundle exec`, and possibly the other commands too for consistency?

**Comment by pvsukale** [comment]
@colby-swandale I am a first-time contributor. Can I start working on this?

**Comment by colby-swandale** [comment]
Sure! let us know if you have any questions.

**Comment by blackst0ne** [comment]
Any updates on this? :slightly_smiling_face:  

@pvsukale have you started to work on this proposal?

**Comment by pvsukale** [comment]
Sorry. Was busy with college work. Will start working on this tonight.
Is this okay?

**Comment by blackst0ne** [comment]
@pvsukale sure. Take your time! 

I just wanted to be sure you're in business. :slightly_smiling_face:

**Comment by ankitkataria** [comment]
@colby-swandale if this issue is still open, can I work on this? I'm a first-time contributor. :smile:

**Comment by prithvi16** [comment]
Hey @ankitkataria . I am not working on this due to some problems. I should have mentioned this earlier :smile: .

**Comment by alex0112** [comment]
Is this still open?  Looking for an issue to work on, but it looks like there's a merged PR.

**Comment by ankitkataria** [comment]
@alex0112 Yeah, I've already solved this one.

**Comment by jarl-dk** [comment]
Seems like this feature is not documented...

**Comment by deivid-rodriguez** [comment]
Documentation PR appreciated.
