### ISSUE TITLE
Isolation from system gems

### ISSUE THREAD

**Issue by gerases** [bundler/bundler#5925]
Hi,

I have puppet 3.5 installed under `/usr/share` and puppet 4 installed in my home dir using bundler. When I run `bundler rspec`, somehow the systemwide puppet gets into play. If I remove /usr/share from LOAD_PATH from within rspec, everything works fine. I'm new to bundler, so I may miss some simple detail.

What's the best way to isolate from the system libs / gems?

Thanks!

**Comment by segiddins** [comment]
You can specify a local install path for bundler to use instead of system gems by running `bundle install --path .bundle`

**Comment by gerases** [comment]
I think you misunderstood me. What happens is that there's a version of puppet in /usr/share, but it wasn't bundler that installed it. It was installed through yum as an rpm. I'm trying to isolate my environment from that version.

**Comment by segiddins** [comment]
Yes, when bundler uses the `--path` option, it will not consider _any_ system gems

**Comment by gerases** [comment]
Cool, I'll give it a shot soon.

**Comment by gerases** [comment]
Yep, that worked!

Is `.bundle` a special location? Or could I have have said `--path blah`? In that case how would `bundler` know where to look for the installed gems?

**Comment by colby-swandale** [comment]
> Is .bundle a special location? Or could I have have said --path blah
It accepts any path

> Also, is bundler looking for the Gemfile in the home dir
It doesn't explicitly check the home dir, it will look for the Gemfile in the current directory and traverse up each parent directory to see if it can find one.
