### ISSUE TITLE
Bundler error help wanna install metaspoit

### ISSUE THREAD

**Issue by Fahim43** [bundler/bundler#5930]
bundle and all other dependencies are installing......
Fetching gem metadata from https://rubygems.org/.
Retrying fetcher due to error (2/4): IOError uninitialized stream.
Retrying fetcher due to error (3/4): IOError uninitialized stream..
Retrying fetcher due to error (4/4): IOError uninitialized stream.
--- ERROR REPORT TEMPLATE -------------------------------------------------------

**Comment by colby-swandale** [comment]
Hi, can you please copy the full error report otherwise we won't be able to help solve your problem.

**Comment by Fahim43** [comment]
No thanks for your quick response and support but the problem has been
solved now.
But there's a new one can u tell me how to install goldeneye properly in
termux plzzzzzzzzz
