### ISSUE TITLE
Ability to cache only some gems

### ISSUE THREAD

**Issue by airblade** [bundler/bundler#5931]
I have a Rails app which depends on a couple of private gems.  These gems are not on GitHub; they are on my file system.

To deploy my app I need to get the private gems onto the server.  I could either push them to the server and install them beforehand, like a private version of `bundle exec rake release`, or include them in my app's repo so they are deployed with my app.  As there are only two private gems I don't feel it's worth running a private gem server.

The first option would mean cluttering up the private gems with knowledge of deployment servers, which doesn't appeal.

The second option requires copying the private `.gem` files into my app's `vendor/cache` directory and updating the `Gemfile`:

```
# 1. Gemfile - before
gem 'my-private-gem', '~> 1.0.0', path: '~/code/src/my-private-gem'

# 2. Either:
$ bundle package --all
$ rm vendor/cache/{all,other,gems}.gem

# or:
$ mkdir vendor/cache
$ cp ~/code/src/my-private-gem/pkg/my-private-gem-1.0.0.gem vendor/cache

# 3. Gemfile - remove the path option
gem 'my-private-gem', '~> 1.0.0'

# 4. Install without adding the others gems to vendor/cache
$ bundle install --no-cache
```

I don't want to add all the gems to `vendor/cache` because it would bloat my app's repo unnecessarily, and it would feel like the tail wagging the dog.

I think this would be neater with the following process, [suggested by @indirect](https://github.com/bundler/bundler/issues/1795#issuecomment-8827226):

> After thinking about this more, I think the best UI for this looks something more like this:
> 
> - Gems already in `vendor/cache` are updated automatically during install
> - Gems not in `vendor/cache` are not added automatically during install
> - Adding all gems to `vendor/cache` is done by running `bundle cache`
> - Adding a specific gem to `vendor/cache` is done by running `bundle cache foo`

Hope that makes sense!

**Comment by airblade** [comment]
I have also found that having some but not all gems in `vendor/cache` prevents `bundle install --deployment` from working: it fails with `Some gems seem to be missing from your vendor/cache directory.`.

My workaround is to use this instead:

```
bundle install --no-cache --path vendor/bundle --without development:test
```

**Comment by colby-swandale** [comment]
Is there a particular reason the `path` option in the Gemfile is not suitable to your needs?

**Comment by airblade** [comment]
You mean copy the private `.gem` files up to a known location on the server beforehand, and point to that location with the `path` option in the `:production` group in the Gemfile?  I.e. the first option I suggested (and dismissed ;) )?

**Comment by colby-swandale** [comment]
i mean, just have the gem source as part of the app and use `path` to specify it's location. such as:

```
gem 'my_private_gem`, path: 'ext/my_private_gem`
```

**Comment by airblade** [comment]
Oh, because they are independent chunks of functionality that are used by other apps too.

**Comment by airblade** [comment]
I have found that it's a bit clunky using the `--no-cache` flag on every `bundle install` so instead my `Gemfile` now installs from private repos on GitHub using a personal access token.
