### ISSUE TITLE
error while "bundle update gollum-lib"

### ISSUE THREAD

**Issue by bkshtha** [bundler/bundler#5932]
ran following command:

#sudo -u git -H env PATH=$PATH && bundle install --full-index --deployment --without development test  postgres aws

.........
..........

Using omniauth-kerberos 0.3.0
Using ruby-saml 1.0.0
Using actionpack 4.1.12
Using activerecord 4.1.12
Using rails-observers 0.1.2
Using carrierwave 0.9.0
Using state_machines-activemodel 0.3.0
Using task_list 1.0.2
Using grape 0.13.0
Using sidetiq 0.6.3
Using omniauth-facebook 3.0.0
Using omniauth-github 1.1.2
Using omniauth-gitlab 1.0.0
Using omniauth-google-oauth2 0.2.6
Using fog-brightbox 0.9.0
Using fog-sakuracloud 1.0.1
Using fog-softlayer 0.4.7
Using fog-profitbricks 0.0.5
Using fog-radosgw 0.0.4
Using fog-terremark 0.1.0
Using fog-voxel 0.1.0

<<ERROR:>>
Downloading gollum-lib-4.0.3 revealed dependencies not in the API or the lockfile (rouge (~> 1.7.4)).
Either installing with `--full-index` or running `bundle update gollum-lib` should fix the problem.

then run following command as instructed above

#bundle update gollum-lib

then Following log error.

GEM
  remote: https://rubygems.org/
  specs:
    CFPropertyList (2.3.1)
    RedCloth (4.2.9)
    ace-rails-ap (2.0.1)
    actionmailer (4.1.12)
      actionpack (= 4.1.12)
      actionview (= 4.1.12)
      mail (~> 2.5, >= 2.5.4)
    actionpack (4.1.12)
      actionview (= 4.1.12)
      activesupport (= 4.1.12)
      rack (~> 1.5.2)
      rack-test (~> 0.6.2)
    actionview (4.1.12)
      activesupport (= 4.1.12)
      builder (~> 3.1)
      erubis (~> 2.7.0)
    activemodel (4.1.12)
      activesupport (= 4.1.12)
      builder (~> 3.1)
    activerecord (4.1.12)
      activemodel (= 4.1.12)
      activesupport (= 4.1.12)
      arel (~> 5.0.0)
    activerecord-deprecated_finders (1.0.4)
    activerecord-session_store (0.1.1)
      actionpack (>= 4.0.0, < 5)
      activerecord (>= 4.0.0, < 5)
      railties (>= 4.0.0, < 5)
    activeresource (4.0.0)
      activemodel (~> 4.0)
      activesupport (~> 4.0)
      rails-observers (~> 0.1.1)
    activesupport (4.1.12)
      i18n (~> 0.6, >= 0.6.9)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.1)
      tzinfo (~> 1.1)
    acts-as-taggable-on (3.5.0)
      activerecord (>= 3.2, < 5)
    addressable (2.3.8)
    after_commit_queue (1.1.0)
      rails (>= 3.0)
    annotate (2.6.10)
      activerecord (>= 3.2, <= 4.3)
      rake (~> 10.4)
    arel (5.0.1.20140414130214)
    asana (0.0.6)
      activeresource (>= 3.2.3)
    asciidoctor (1.5.2)
    ast (2.1.0)
    astrolabe (1.3.1)
      parser (~> 2.2)
    attr_encrypted (1.3.4)
      encryptor (>= 1.3.0)
    attr_required (1.0.0)
    autoprefixer-rails (5.2.1.2)
      execjs
      json
    awesome_print (1.2.0)
    axiom-types (0.1.1)
      descendants_tracker (~> 0.0.4)
      ice_nine (~> 0.11.0)
      thread_safe (~> 0.3, >= 0.3.1)
    babosa (1.0.2)
    bcrypt (3.1.10)
    benchmark-ips (2.3.0)
    better_errors (1.0.1)
      coderay (>= 1.0.0)
      erubis (>= 2.6.6)
    binding_of_caller (0.7.2)
      debug_inspector (>= 0.0.1)
    bootstrap-sass (3.3.5)
      autoprefixer-rails (>= 5.0.0.1)
      sass (>= 3.2.19)
    brakeman (3.0.1)
      erubis (~> 2.6)
      fastercsv (~> 1.5)
      haml (>= 3.0, < 5.0)
      highline (~> 1.6.20)
      multi_json (~> 1.2)
      ruby2ruby (~> 2.1.1)
      ruby_parser (~> 3.5.0)
      sass (~> 3.0)
      terminal-table (~> 1.4)
    browser (1.0.0)
    builder (3.2.2)
    bullet (4.14.9)
      activesupport (>= 3.0.0)
      uniform_notifier (~> 1.9.0)
    byebug (6.0.2)
    cal-heatmap-rails (0.0.1)
    capybara (2.4.4)
      mime-types (>= 1.16)
      nokogiri (>= 1.3.3)
      rack (>= 1.0.0)
      rack-test (>= 0.5.4)
      xpath (~> 2.0)
    capybara-screenshot (1.0.11)
      capybara (>= 1.0, < 3)
      launchy
    carrierwave (0.9.0)
      activemodel (>= 3.2.0)
      activesupport (>= 3.2.0)
      json (>= 1.7)
    celluloid (0.16.0)
      timers (~> 4.0.0)
    charlock_holmes (0.7.3)
    chunky_png (1.3.4)
    cliver (0.3.2)
    coderay (1.1.0)
    coercible (1.0.0)
      descendants_tracker (~> 0.0.1)
    coffee-rails (4.1.0)
      coffee-script (>= 2.2.0)
      railties (>= 4.0.0, < 5.0)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.9.1.1)
    colored (1.2)
    colorize (0.5.8)
    connection_pool (2.2.0)
    coveralls (0.8.2)
      json (~> 1.8)
      rest-client (>= 1.6.8, < 2)
      simplecov (~> 0.10.0)
      term-ansicolor (~> 1.3)
      thor (~> 0.19.1)
    crack (0.4.2)
      safe_yaml (~> 1.0.0)
    creole (0.3.8)
    d3_rails (3.5.6)
      railties (>= 3.1.0)
    daemons (1.2.3)
    database_cleaner (1.4.1)
    debug_inspector (0.0.2)
    debugger-ruby_core_source (1.3.8)
    default_value_for (3.0.1)
      activerecord (>= 3.2.0, < 5.0)
    descendants_tracker (0.0.4)
      thread_safe (~> 0.3, >= 0.3.1)
    devise (3.5.2)
      bcrypt (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 3.2.6, < 5)
      responders
      thread_safe (~> 0.1)
      warden (~> 1.2.3)
    devise-async (0.9.0)
      devise (~> 3.2)
    devise-two-factor (2.0.0)
      activesupport
      attr_encrypted (~> 1.3.2)
      devise (~> 3.5.0)
      railties
      rotp (~> 2)
    diff-lcs (1.2.5)
    diffy (3.0.7)
    docile (1.1.5)
    domain_name (0.5.24)
      unf (>= 0.0.5, < 1.0.0)
    doorkeeper (2.1.4)
      railties (>= 3.2)
    dropzonejs-rails (0.7.1)
      rails (> 3.1)
    email_reply_parser (0.5.8)
    email_spec (1.6.0)
      launchy (~> 2.1)
      mail (~> 2.2)
    encryptor (1.3.0)
    enumerize (0.7.0)
      activesupport (>= 3.2)
    equalizer (0.0.11)
    erubis (2.7.0)
    escape_utils (1.1.0)
    eventmachine (1.0.8)
    excon (0.45.4)
    execjs (2.6.0)
    expression_parser (0.9.0)
    factory_girl (4.3.0)
      activesupport (>= 3.0.0)
    factory_girl_rails (4.3.0)
      factory_girl (~> 4.3.0)
      railties (>= 3.0.0)
    faraday (0.9.2)
      multipart-post (>= 1.2, < 3)
    faraday_middleware (0.10.0)
      faraday (>= 0.7.4, < 0.10)
    fastercsv (1.5.5)
    ffaker (2.0.0)
    ffi (1.9.10)
    fission (0.5.0)
      CFPropertyList (~> 2.2)
    flay (2.6.1)
      ruby_parser (~> 3.0)
      sexp_processor (~> 4.0)
    flog (4.3.2)
      ruby_parser (~> 3.1, > 3.1.0)
      sexp_processor (~> 4.4)
    flowdock (0.7.0)
      httparty (~> 0.7)
      multi_json
    fog (1.25.0)
      fog-brightbox (~> 0.4)
      fog-core (~> 1.25)
      fog-json
      fog-profitbricks
      fog-radosgw (>= 0.0.2)
      fog-sakuracloud (>= 0.0.4)
      fog-softlayer
      fog-terremark
      fog-vmfusion
      fog-voxel
      fog-xml (~> 0.1.1)
      ipaddress (~> 0.5)
      nokogiri (~> 1.5, >= 1.5.11)
      opennebula
    fog-brightbox (0.9.0)
      fog-core (~> 1.22)
      fog-json
      inflecto (~> 0.0.2)
    fog-core (1.32.1)
      builder
      excon (~> 0.45)
      formatador (~> 0.2)
      mime-types
      net-scp (~> 1.1)
      net-ssh (>= 2.1.3)
    fog-json (1.0.2)
      fog-core (~> 1.0)
      multi_json (~> 1.10)
    fog-profitbricks (0.0.5)
      fog-core
      fog-xml
      nokogiri
    fog-radosgw (0.0.4)
      fog-core (>= 1.21.0)
      fog-json
      fog-xml (>= 0.0.1)
    fog-sakuracloud (1.0.1)
      fog-core
      fog-json
    fog-softlayer (0.4.7)
      fog-core
      fog-json
    fog-terremark (0.1.0)
      fog-core
      fog-xml
    fog-vmfusion (0.1.0)
      fission
      fog-core
    fog-voxel (0.1.0)
      fog-core
      fog-xml
    fog-xml (0.1.2)
      fog-core
      nokogiri (~> 1.5, >= 1.5.11)
    font-awesome-rails (4.4.0.0)
      railties (>= 3.2, < 5.0)
    foreman (0.78.0)
      thor (~> 0.19.1)
    formatador (0.2.5)
    fuubar (2.0.0)
      rspec (~> 3.0)
      ruby-progressbar (~> 1.4)
    gemnasium-gitlab-service (0.2.6)
      rugged (~> 0.21)
    gemojione (2.0.1)
      json
    get_process_mem (0.2.0)
    gherkin-ruby (0.3.2)
    github-linguist (4.7.0)
      charlock_holmes (~> 0.7.3)
      escape_utils (~> 1.1.0)
      mime-types (>= 1.19)
      rugged (>= 0.23.0b)
    github-markup (1.3.3)
    gitlab-flowdock-git-hook (1.0.1)
      flowdock (~> 0.7)
      gitlab-grit (>= 2.4.1)
      multi_json
    gitlab-grit (2.7.3)
      charlock_holmes (~> 0.6)
      diff-lcs (~> 1.1)
      mime-types (~> 1.15)
      posix-spawn (~> 0.3)
    gitlab_emoji (0.1.1)
      gemojione (~> 2.0)
    gitlab_git (7.2.20)
      activesupport (~> 4.0)
      charlock_holmes (~> 0.7.3)
      github-linguist (~> 4.7.0)
      rugged (~> 0.23.3)
    gitlab_meta (7.0)
    gitlab_omniauth-ldap (1.2.1)
      net-ldap (~> 0.9)
      omniauth (~> 1.0)
      pyu-ruby-sasl (~> 0.0.3.1)
      rubyntlm (~> 0.3)
    gollum-grit_adapter (1.0.0)
      gitlab-grit (~> 2.7, >= 2.7.1)
    gollum-lib (4.0.3)
      github-markup (~> 1.3.3)
      gollum-grit_adapter (~> 1.0)
      nokogiri (~> 1.6.4)
      rouge (~> 1.10.1)
      sanitize (~> 2.1.0)
      stringex (~> 2.5.1)
    gon (5.0.4)
      actionpack (>= 2.3.0)
      json
    grape (0.13.0)
      activesupport
      builder
      hashie (>= 2.1.0)
      multi_json (>= 1.3.2)
      multi_xml (>= 0.5.2)
      rack (>= 1.3.0)
      rack-accept
      rack-mount
      virtus (>= 1.0.0)
    grape-entity (0.4.8)
      activesupport
      multi_json (>= 1.3.2)
    haml (4.0.7)
      tilt
    haml-rails (0.9.0)
      actionpack (>= 4.0.1)
      activesupport (>= 4.0.1)
      haml (>= 4.0.6, < 5.0)
      html2haml (>= 1.0.1)
      railties (>= 4.0.1)
    hashie (3.4.2)
    highline (1.6.21)
    hike (1.2.3)
    hipchat (1.5.2)
      httparty
      mimemagic
    hitimes (1.2.3)
    html-pipeline (1.11.0)
      activesupport (>= 2)
      nokogiri (~> 1.4)
    html2haml (2.0.0)
      erubis (~> 2.7.0)
      haml (~> 4.0.0)
      nokogiri (~> 1.6.0)
      ruby_parser (~> 3.5)
    http-cookie (1.0.2)
      domain_name (~> 0.5)
    http_parser.rb (0.5.3)
    httparty (0.13.5)
      json (~> 1.8)
      multi_xml (>= 0.5.2)
    httpclient (2.6.0.1)
    i18n (0.7.0)
    ice_cube (0.11.1)
    ice_nine (0.11.1)
    inflecto (0.0.2)
    ipaddress (0.8.0)
    jquery-atwho-rails (1.3.2)
    jquery-rails (3.1.3)
      railties (>= 3.0, < 5.0)
      thor (>= 0.14, < 2.0)
    jquery-scrollto-rails (1.4.3)
      railties (> 3.1, < 5.0)
    jquery-turbolinks (2.0.2)
      railties (>= 3.1.0)
      turbolinks
    jquery-ui-rails (4.2.1)
      railties (>= 3.2.16)
    json (1.8.3)
    jwt (1.5.1)
    kaminari (0.16.3)
      actionpack (>= 3.0.0)
      activesupport (>= 3.0.0)
    kgio (2.9.3)
    launchy (2.4.3)
      addressable (~> 2.3)
    letter_opener (1.1.2)
      launchy (~> 2.2)
    listen (2.10.1)
      celluloid (~> 0.16.0)
      rb-fsevent (>= 0.9.3)
      rb-inotify (>= 0.9)
    macaddr (1.7.1)
      systemu (~> 2.6.2)
    mail (2.6.3)
      mime-types (>= 1.16, < 3)
    mail_room (0.6.1)
    method_source (0.8.2)
    mime-types (1.25.1)
    mimemagic (0.3.0)
    mini_portile (0.6.2)
    minitest (5.7.0)
    mousetrap-rails (1.4.6)
    multi_json (1.11.2)
    multi_xml (0.5.5)
    multipart-post (2.0.0)
    mysql2 (0.3.20)
    nested_form (0.3.2)
    net-ldap (0.11)
    net-scp (1.2.1)
      net-ssh (>= 2.6.5)
    net-ssh (2.9.2)
    netrc (0.10.3)
    newrelic-grape (2.0.0)
      grape
      newrelic_rpm
    newrelic_rpm (3.9.4.245)
    nokogiri (1.6.6.2)
      mini_portile (~> 0.6.0)
    nprogress-rails (0.1.6.7)
    oauth (0.4.7)
    oauth2 (1.0.0)
      faraday (>= 0.8, < 0.10)
      jwt (~> 1.0)
      multi_json (~> 1.3)
      multi_xml (~> 0.5)
      rack (~> 1.2)
    octokit (3.7.1)
      sawyer (~> 0.6.0, >= 0.5.3)
    omniauth (1.2.2)
      hashie (>= 1.2, < 4)
      rack (~> 1.0)
    omniauth-bitbucket (0.0.2)
      multi_json (~> 1.7)
      omniauth (~> 1.1)
      omniauth-oauth (~> 1.0)
    omniauth-facebook (3.0.0)
      omniauth-oauth2 (~> 1.2)
    omniauth-github (1.1.2)
      omniauth (~> 1.0)
      omniauth-oauth2 (~> 1.1)
    omniauth-gitlab (1.0.0)
      omniauth (~> 1.0)
      omniauth-oauth2 (~> 1.0)
    omniauth-google-oauth2 (0.2.6)
      omniauth (> 1.0)
      omniauth-oauth2 (~> 1.1)
    omniauth-kerberos (0.3.0)
      omniauth-multipassword
      timfel-krb5-auth (~> 0.8)
    omniauth-multipassword (0.4.2)
      omniauth (~> 1.0)
    omniauth-oauth (1.1.0)
      oauth
      omniauth (~> 1.0)
    omniauth-oauth2 (1.3.1)
      oauth2 (~> 1.0)
      omniauth (~> 1.2)
    omniauth-saml (1.4.1)
      omniauth (~> 1.1)
      ruby-saml (~> 1.0.0)
    omniauth-shibboleth (1.2.1)
      omniauth (>= 1.0.0)
    omniauth-twitter (1.2.1)
      json (~> 1.3)
      omniauth-oauth (~> 1.1)
    omniauth_crowd (2.2.3)
      activesupport
      nokogiri (>= 1.4.4)
      omniauth (~> 1.0)
    opennebula (4.12.1)
      json
      nokogiri
      rbvmomi
    org-ruby (0.9.12)
      rubypants (~> 0.2)
    orm_adapter (0.5.0)
    paranoia (2.1.3)
      activerecord (~> 4.0)
    parser (2.2.2.6)
      ast (>= 1.1, < 3.0)
    pg (0.18.2)
    poltergeist (1.6.0)
      capybara (~> 2.1)
      cliver (~> 0.3.1)
      multi_json (~> 1.0)
      websocket-driver (>= 0.2.0)
    posix-spawn (0.3.11)
    powerpack (0.0.9)
    pry (0.10.1)
      coderay (~> 1.1.0)
      method_source (~> 0.8.1)
      slop (~> 3.4)
    pry-rails (0.3.4)
      pry (>= 0.9.10)
    pyu-ruby-sasl (0.0.3.3)
    quiet_assets (1.0.3)
      railties (>= 3.1, < 5.0)
    rack (1.5.5)
    rack-accept (0.4.5)
      rack (>= 0.4)
    rack-attack (4.3.0)
      rack
    rack-cors (0.4.0)
    rack-mount (0.8.3)
      rack (>= 1.0.0)
    rack-oauth2 (1.0.10)
      activesupport (>= 2.3)
      attr_required (>= 0.0.5)
      httpclient (>= 2.4)
      multi_json (>= 1.3.6)
      rack (>= 1.1)
    rack-protection (1.5.3)
      rack
    rack-test (0.6.3)
      rack (>= 1.0)
    rails (4.1.12)
      actionmailer (= 4.1.12)
      actionpack (= 4.1.12)
      actionview (= 4.1.12)
      activemodel (= 4.1.12)
      activerecord (= 4.1.12)
      activesupport (= 4.1.12)
      bundler (>= 1.3.0, < 2.0)
      railties (= 4.1.12)
      sprockets-rails (~> 2.0)
    rails-observers (0.1.2)
      activemodel (~> 4.0)
    railties (4.1.12)
      actionpack (= 4.1.12)
      activesupport (= 4.1.12)
      rake (>= 0.8.7)
      thor (>= 0.18.1, < 2.0)
    rainbow (2.0.0)
    raindrops (0.15.0)
    rake (10.4.2)
    raphael-rails (2.1.2)
    rb-fsevent (0.9.5)
    rb-inotify (0.9.5)
      ffi (>= 0.5.0)
    rblineprof (0.3.6)
      debugger-ruby_core_source (~> 1.3)
    rbvmomi (1.8.2)
      builder
      nokogiri (>= 1.4.1)
      trollop
    rdoc (3.12.2)
      json (~> 1.4)
    redcarpet (3.3.3)
    redis (3.2.1)
    redis-actionpack (4.0.0)
      actionpack (~> 4)
      redis-rack (~> 1.5.0)
      redis-store (~> 1.1.0)
    redis-activesupport (4.1.1)
      activesupport (~> 4)
      redis-store (~> 1.1.0)
    redis-namespace (1.5.2)
      redis (~> 3.0, >= 3.0.4)
    redis-rack (1.5.0)
      rack (~> 1.5)
      redis-store (~> 1.1.0)
    redis-rails (4.0.0)
      redis-actionpack (~> 4)
      redis-activesupport (~> 4)
      redis-store (~> 1.1.0)
    redis-store (1.1.6)
      redis (>= 2.2)
    request_store (1.2.0)
    rerun (0.10.0)
      listen (~> 2.7, >= 2.7.3)
    responders (1.1.2)
      railties (>= 3.2, < 4.2)
    rest-client (1.8.0)
      http-cookie (>= 1.0.2, < 2.0)
      mime-types (>= 1.16, < 3.0)
      netrc (~> 0.7)
    rinku (1.7.3)
    rotp (2.1.1)
    rouge (1.10.1)
    rqrcode (0.7.0)
      chunky_png
    rqrcode-rails3 (0.1.7)
      rqrcode (>= 0.4.2)
    rspec (3.3.0)
      rspec-core (~> 3.3.0)
      rspec-expectations (~> 3.3.0)
      rspec-mocks (~> 3.3.0)
    rspec-core (3.3.2)
      rspec-support (~> 3.3.0)
    rspec-expectations (3.3.1)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.3.0)
    rspec-mocks (3.3.2)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.3.0)
    rspec-rails (3.3.3)
      actionpack (>= 3.0, < 4.3)
      activesupport (>= 3.0, < 4.3)
      railties (>= 3.0, < 4.3)
      rspec-core (~> 3.3.0)
      rspec-expectations (~> 3.3.0)
      rspec-mocks (~> 3.3.0)
      rspec-support (~> 3.3.0)
    rspec-support (3.3.0)
    rubocop (0.28.0)
      astrolabe (~> 1.3)
      parser (>= 2.2.0.pre.7, < 3.0)
      powerpack (~> 0.0.6)
      rainbow (>= 1.99.1, < 3.0)
      ruby-progressbar (~> 1.4)
    ruby-fogbugz (0.2.1)
      crack (~> 0.4)
    ruby-progressbar (1.7.5)
    ruby-saml (1.0.0)
      nokogiri (>= 1.5.10)
      uuid (~> 2.3)
    ruby2ruby (2.1.4)
      ruby_parser (~> 3.1)
      sexp_processor (~> 4.0)
    ruby_parser (3.5.0)
      sexp_processor (~> 4.1)
    rubyntlm (0.5.2)
    rubypants (0.2.0)
    rugged (0.23.3)
    safe_yaml (1.0.4)
    sanitize (2.1.0)
      nokogiri (>= 1.4.4)
    sass (3.2.19)
    sass-rails (4.0.5)
      railties (>= 4.0.0, < 5.0)
      sass (~> 3.2.2)
      sprockets (~> 2.8, < 3.0)
      sprockets-rails (~> 2.0)
    sawyer (0.6.0)
      addressable (~> 2.3.5)
      faraday (~> 0.8, < 0.10)
    sdoc (0.3.20)
      json (>= 1.1.3)
      rdoc (~> 3.10)
    seed-fu (2.3.5)
      activerecord (>= 3.1, < 4.3)
      activesupport (>= 3.1, < 4.3)
    select2-rails (3.5.9.3)
      thor (~> 0.14)
    settingslogic (2.0.9)
    sexp_processor (4.6.0)
    sham_rack (1.3.6)
      rack
    shoulda-matchers (2.8.0)
      activesupport (>= 3.0.0)
    sidekiq (3.3.0)
      celluloid (>= 0.16.0)
      connection_pool (>= 2.0.0)
      json
      redis (>= 3.0.6)
      redis-namespace (>= 1.3.1)
    sidetiq (0.6.3)
      celluloid (>= 0.14.1)
      ice_cube (= 0.11.1)
      sidekiq (>= 3.0.0)
    simple_oauth (0.1.9)
    simplecov (0.10.0)
      docile (~> 1.1.0)
      json (~> 1.8)
      simplecov-html (~> 0.10.0)
    simplecov-html (0.10.0)
    sinatra (1.4.6)
      rack (~> 1.4)
      rack-protection (~> 1.4)
      tilt (>= 1.3, < 3)
    six (0.2.0)
    slack-notifier (1.2.1)
    slop (3.6.0)
    spinach (0.8.10)
      colorize
      gherkin-ruby (>= 0.3.2)
      json
    spinach-rails (0.2.1)
      capybara (>= 2.0.0)
      railties (>= 3)
      spinach (>= 0.4)
    spring (1.3.6)
    spring-commands-rspec (1.0.4)
      spring (>= 0.9.1)
    spring-commands-spinach (1.0.0)
      spring (>= 0.9.1)
    spring-commands-teaspoon (0.0.2)
      spring (>= 0.9.1)
    sprockets (2.12.4)
      hike (~> 1.2)
      multi_json (~> 1.0)
      rack (~> 1.0)
      tilt (~> 1.1, != 1.3.0)
    sprockets-rails (2.3.2)
      actionpack (>= 3.0)
      activesupport (>= 3.0)
      sprockets (>= 2.8, < 4.0)
    stamp (0.6.0)
    state_machines (0.4.0)
    state_machines-activemodel (0.3.0)
      activemodel (~> 4.1)
      state_machines (>= 0.4.0)
    state_machines-activerecord (0.3.0)
      activerecord (~> 4.1)
      state_machines-activemodel (>= 0.3.0)
    stringex (2.5.2)
    systemu (2.6.5)
    task_list (1.0.2)
      html-pipeline
    teaspoon (1.0.2)
      railties (>= 3.2.5, < 5)
    teaspoon-jasmine (2.2.0)
      teaspoon (>= 1.0.0)
    term-ansicolor (1.3.2)
      tins (~> 1.0)
    terminal-table (1.5.2)
    test_after_commit (0.2.7)
      activerecord (>= 3.2)
    thin (1.6.3)
      daemons (~> 1.0, >= 1.0.9)
      eventmachine (~> 1.0)
      rack (~> 1.0)
    thor (0.19.1)
    thread_safe (0.3.5)
    tilt (1.4.1)
    timers (4.0.4)
      hitimes
    timfel-krb5-auth (0.8.3)
    tinder (1.10.1)
      eventmachine (~> 1.0)
      faraday (~> 0.9.0)
      faraday_middleware (~> 0.9)
      hashie (>= 1.0)
      json (~> 1.8.0)
      mime-types
      multi_json (~> 1.7)
      twitter-stream (~> 0.1)
    tins (1.6.0)
    trollop (2.1.2)
    turbolinks (2.5.3)
      coffee-rails
    twitter-stream (0.1.16)
      eventmachine (>= 0.12.8)
      http_parser.rb (~> 0.5.1)
      simple_oauth (~> 0.1.4)
    tzinfo (1.2.2)
      thread_safe (~> 0.1)
    uglifier (2.7.2)
      execjs (>= 0.3.0)
      json (>= 1.8.0)
    underscore-rails (1.4.4)
    unf (0.1.4)
      unf_ext
    unf_ext (0.0.7.1)
    unicorn (4.8.3)
      kgio (~> 2.6)
      rack
      raindrops (~> 0.7)
    unicorn-worker-killer (0.4.3)
      get_process_mem (~> 0)
      unicorn (~> 4)
    uniform_notifier (1.9.0)
    uuid (2.3.8)
      macaddr (~> 1.0)
    version_sorter (2.0.0)
    virtus (1.0.5)
      axiom-types (~> 0.1)
      coercible (~> 1.0)
      descendants_tracker (~> 0.0, >= 0.0.3)
      equalizer (~> 0.0, >= 0.0.9)
    warden (1.2.3)
      rack (>= 1.0)
    webmock (1.21.0)
      addressable (>= 2.3.6)
      crack (>= 0.3.2)
    websocket-driver (0.6.2)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.2)
    wikicloth (0.8.1)
      builder
      expression_parser
      rinku
    xpath (2.0.0)
      nokogiri (~> 1.3)

PLATFORMS
  ruby

DEPENDENCIES
  RedCloth (~> 4.2.9)
  ace-rails-ap (~> 2.0.1)
  activerecord-deprecated_finders (~> 1.0.3)
  activerecord-session_store (~> 0.1.0)
  acts-as-taggable-on (~> 3.4)
  addressable (~> 2.3.8)
  after_commit_queue
  annotate (~> 2.6.0)
  asana (~> 0.0.6)
  asciidoctor (~> 1.5.2)
  attr_encrypted (~> 1.3.4)
  awesome_print (~> 1.2.0)
  babosa (~> 1.0.2)
  benchmark-ips
  better_errors (~> 1.0.1)
  binding_of_caller (~> 0.7.2)
  bootstrap-sass (~> 3.0)
  brakeman (= 3.0.1)
  browser (~> 1.0.0)
  bullet
  byebug
  cal-heatmap-rails (~> 0.0.1)
  capybara (~> 2.4.0)
  capybara-screenshot (~> 1.0.0)
  carrierwave (~> 0.9.0)
  charlock_holmes (~> 0.7.3)
  coffee-rails (~> 4.1.0)
  colored (~> 1.2)
  colorize (~> 0.5.8)
  coveralls (~> 0.8.2)
  creole (~> 0.3.6)
  d3_rails (~> 3.5.5)
  database_cleaner (~> 1.4.0)
  default_value_for (~> 3.0.0)
  devise (~> 3.5.2)
  devise-async (~> 0.9.0)
  devise-two-factor (~> 2.0.0)
  diffy (~> 3.0.3)
  doorkeeper (~> 2.1.3)
  dropzonejs-rails (~> 0.7.1)
  email_reply_parser (~> 0.5.8)
  email_spec (~> 1.6.0)
  enumerize (~> 0.7.0)
  factory_girl_rails (~> 4.3.0)
  ffaker (~> 2.0.0)
  flay
  flog
  fog (~> 1.25.0)
  font-awesome-rails (~> 4.2)
  foreman
  fuubar (~> 2.0.0)
  gemnasium-gitlab-service (~> 0.2)
  github-linguist (~> 4.7.0)
  github-markup (~> 1.3.1)
  gitlab-flowdock-git-hook (~> 1.0.1)
  gitlab_emoji (~> 0.1)
  gitlab_git (~> 7.2.20)
  gitlab_meta (= 7.0)
  gitlab_omniauth-ldap (~> 1.2.1)
  gollum-lib (~> 4.0.2)
  gon (~> 5.0.0)
  grape (~> 0.13.0)
  grape-entity (~> 0.4.2)
  haml-rails (~> 0.9.0)
  hipchat (~> 1.5.0)
  html-pipeline (~> 1.11.0)
  httparty (~> 0.13.3)
  jquery-atwho-rails (~> 1.3.2)
  jquery-rails (~> 3.1.3)
  jquery-scrollto-rails (~> 1.4.3)
  jquery-turbolinks (~> 2.0.1)
  jquery-ui-rails (~> 4.2.1)
  kaminari (~> 0.16.3)
  letter_opener (~> 1.1.2)
  mail_room (~> 0.6.1)
  minitest (~> 5.7.0)
  mousetrap-rails (~> 1.4.6)
  mysql2 (~> 0.3.16)
  nested_form (~> 0.3.2)
  newrelic-grape
  newrelic_rpm (~> 3.9.4.245)
  nprogress-rails (~> 0.1.6.7)
  oauth2 (~> 1.0.0)
  octokit (~> 3.7.0)
  omniauth (~> 1.2.2)
  omniauth-bitbucket (~> 0.0.2)
  omniauth-facebook (~> 3.0.0)
  omniauth-github (~> 1.1.1)
  omniauth-gitlab (~> 1.0.0)
  omniauth-google-oauth2 (~> 0.2.0)
  omniauth-kerberos (~> 0.3.0)
  omniauth-saml (~> 1.4.0)
  omniauth-shibboleth (~> 1.2.0)
  omniauth-twitter (~> 1.2.0)
  omniauth_crowd
  org-ruby (~> 0.9.12)
  paranoia (~> 2.0)
  pg (~> 0.18.2)
  poltergeist (~> 1.6.0)
  pry-rails
  quiet_assets (~> 1.0.2)
  rack-attack (~> 4.3.0)
  rack-cors (~> 0.4.0)
  rack-oauth2 (~> 1.0.5)
  rails (= 4.1.12)
  raphael-rails (~> 2.1.2)
  rblineprof
  rdoc (~> 3.6)
  redcarpet (~> 3.3.3)
  redis-rails (~> 4.0.0)
  request_store (~> 1.2.0)
  rerun (~> 0.10.0)
  rqrcode-rails3 (~> 0.1.7)
  rspec-rails (~> 3.3.0)
  rubocop (~> 0.28.0)
  ruby-fogbugz (~> 0.2.1)
  sanitize (~> 2.0)
  sass-rails (~> 4.0.5)
  sdoc (~> 0.3.20)
  seed-fu (~> 2.3.5)
  select2-rails (~> 3.5.9)
  settingslogic (~> 2.0.9)
  sham_rack
  shoulda-matchers (~> 2.8.0)
  sidekiq (= 3.3.0)
  sidetiq (~> 0.6.3)
  simplecov (~> 0.10.0)
  sinatra (~> 1.4.4)
  six (~> 0.2.0)
  slack-notifier (~> 1.2.0)
  spinach-rails (~> 0.2.1)
  spring (~> 1.3.6)
  spring-commands-rspec (~> 1.0.4)
  spring-commands-spinach (~> 1.0.0)
  spring-commands-teaspoon (~> 0.0.2)
  sprockets (~> 2.12.3)
  stamp (~> 0.6.0)
  state_machines-activerecord (~> 0.3.0)
  task_list (~> 1.0.2)
  teaspoon (~> 1.0.0)
  teaspoon-jasmine (~> 2.2.0)
  test_after_commit (~> 0.2.2)
  thin (~> 1.6.1)
  tinder (~> 1.10.0)
  turbolinks (~> 2.5.0)
  uglifier (~> 2.7.2)
  underscore-rails (~> 1.4.4)
  unf (~> 0.1.4)
  unicorn (~> 4.8.2)
  unicorn-worker-killer (~> 0.4.2)
  version_sorter (~> 2.0.0)
  virtus (~> 1.0.1)
  webmock (~> 1.21.0)
  wikicloth (= 0.8.1)

BUNDLED WITH
   1.10.6
```

--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/bundler/bundler/search?q=No+live+threads+left.+Deadlock%3F&type=Issues

If there aren't any reports for this error yet, please create copy and paste the report template above into a new issue. Don't forget to anonymize any private data! The new issue form is located at:
https://github.com/bundler/bundler/issues/new

Please help to resolve the issue.

**Comment by colby-swandale** [comment]
It looks like your trying to `bundle install` from a fairly old Gemfile.lock, What's the output of `bundle env`?

Too be honest the best solution is to probably delete the `Gemfile.lock`, re-run `bundle install` and fix the versions afterwards.

**Comment by bkshtha** [comment]
Thank you for your reply.

I resolve the issue later by degrading version of bundle from 1.15 to 1.12.5.

**Comment by colby-swandale** [comment]
I'm closing this for now. If you have any more questions don't be afraid to re-open this issue.
