### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by augmen** [bundler/bundler#5935]
I have install bundler `gem install bundler` then clone a GitHub project then cd project dir . The run the command `bundle install ` as sudo user . got this error

![screen shot 2017-08-08 at 11 11 01](https://user-images.githubusercontent.com/11497036/29057814-8df1b518-7c2a-11e7-93e8-36d9cbdd5047.png)

**Comment by colby-swandale** [comment]
Hi, you will need to check your local environment, your shell is unable to find `bundler` executable.

**Comment by augmen** [comment]
how to do that ?

**Comment by augmen** [comment]
shall i need to change the path ?

**Comment by augmen** [comment]
i tried to run bundle in the root directory `bundle install & add` game file using the command `git add Gemfile Gemfile.lock` but got this error
![screen shot 2017-08-08 at 11 44 24](https://user-images.githubusercontent.com/11497036/29058648-15014bfa-7c2f-11e7-868c-d76cef2282ad.png)

**Comment by colby-swandale** [comment]
@augmen Bundler is saying that it cannot locate the `Gemfile`, which it needs to install your gems. I  suggest you go through the guides we have available at [bundler.io](http://bundler.io/v1.15/guides/using_bundler_in_applications.html) that will help guide you on how to use Bundler.

**Comment by augmen** [comment]
Yeh, but could not understand the right command

**Comment by augmen** [comment]
can you guide us the specific page ?

**Comment by colby-swandale** [comment]
You can find the guides at http://bundler.io/docs.html, i also linked the one you probably need in the previous comment

**Comment by augmen** [comment]
i find two bundler version installed in root directory. And there is no gem file in bundler. I run the command `gem install bundler` but failed to get the gem file .
![screen shot 2017-08-08 at 12 22 54](https://user-images.githubusercontent.com/11497036/29059711-7c00eebe-7c34-11e7-8897-1e29089762ff.png)

**Comment by colby-swandale** [comment]
I guessing you're trying to install your applications dependencies, you're application has the Gemfile, you need to `cd` your application and then run `bundle install`.

**Comment by augmen** [comment]
cd the application as non root user and run the command `bundle install` got this 
![screen shot 2017-08-08 at 11 11 01](https://user-images.githubusercontent.com/11497036/29060488-9fe7fa72-7c37-11e7-92bb-42d44bd292d1.png)

**Comment by colby-swandale** [comment]
You will need to check your local environment to setup your ruby env so you can execute `env` and `bundler`. We can't help too much with this.

**Comment by augmen** [comment]
ok thanks.  please let su know whether the gemfile should be in bundler directory / gems directory ?

**Comment by colby-swandale** [comment]
the Gemfile should be in your application directory.

**Comment by colby-swandale** [comment]
I'm closing this for now. If you have any more questions don't be afraid to re-open this issue.
