### ISSUE TITLE
Bundle install should use $(pwd)/.gitconfig if it exists

### ISSUE THREAD

**Issue by ghost** [bundler/bundler#5936]
Currently, `bundle install` uses the user's git config in `~/.gitconfig`. As `git config --local` will save git settings into the local repo, `bundle install` and friends should respect the user's configurations for that repo.

This could also be a --flag.

Thanks!

**Comment by segiddins** [comment]
I believe Bundler just shells out to git, so it should be behaving the same as git does (the git dirs are stored globally, and not associated with any single project)
