### ISSUE TITLE
https://github.com/bundler/bundler/search?q=No+such+file+or+directory+-+git+clone+%22git+%2F%2Fgithub.com%2Fgooddata%2Frubocop-junit-formatter.git%22+%22C+%2FRuby24-x64%2Flib%2Fruby%2Fgems%2F2.4.0%2Fcache%2Fbundler%2Fgit%2Frubocop-junit-formatter-c732e55137f3303bfabeb5d9e56f963220dfb56f%22+--bare+--no-hardlinks+--quiet&type=Issues

### ISSUE THREAD

**Issue by gkanilkumar** [bundler/bundler#5937]
https://github.com/bundler/bundler/search?q=No+such+file+or+directory+-+git+clone+%22git+%2F%2Fgithub.com%2Fgooddata%2Frubocop-junit-formatter.git%22+%22C+%2FRuby24-x64%2Flib%2Fruby%2Fgems%2F2.4.0%2Fcache%2Fbundler%2Fgit%2Frubocop-junit-formatter-c732e55137f3303bfabeb5d9e56f963220dfb56f%22+--bare+--no-hardlinks+--quiet&type=Issues

**Comment by segiddins** [comment]
Please share the entire output of the error template, thanks!
