### ISSUE TITLE
Potential defects for `bundle vis` with ruby-head

### ISSUE THREAD

**Issue by hsbt** [bundler/bundler#5939]
I got test fails with `viz_spec.rb` with ruby-head that version is `ruby 2.5.0dev (2017-08-08 trunk 59529) [x86_64-darwin16]`

```
       ArgumentError: unknown keyword: png
         /path/to/bundler/bundler/tmp/gems/system/gems/ruby-graphviz-1.2.3/lib/graphviz.rb:441:in `output'
         /path/to/bundler/bundler/lib/bundler/graph.rb:142:in `run'
(snip)
```

It happens https://github.com/glejeune/Ruby-Graphviz/blob/master/lib/graphviz.rb#L441 throw https://github.com/bundler/bundler/blob/master/lib/bundler/graph.rb#L142 .

I think it's breaking changes of Ruby 2.5 for keyword args behavior. I'm going to triage this defects on ruby core tracker.

**Comment by hsbt** [comment]
note: https://bugs.ruby-lang.org/issues/13793

**Comment by segiddins** [comment]
This looks like a ruby bug rather than a Bundler issue

**Comment by hsbt** [comment]
This issue is fixed ruby core upstream: https://bugs.ruby-lang.org/projects/ruby-trunk/repository/revisions/59556
