### ISSUE TITLE
provide a --path flag for outdated

### ISSUE THREAD

**Issue by asafigan** [bundler/bundler#5943]
Provide a --path flag for outdated so that I can check for outdated gems installed at a different location.

**Comment by chrismo** [comment]
You might have some success with setting BUNDLE_PATH (not that you shouldn't want `--path` added)...

**Comment by segiddins** [comment]
We're trying to move away from adding all of the flags to every command, so I would recommend setting `BUNDLE_PATH` for now

**Comment by asafigan** [comment]
ok I will try that.

**Comment by colby-swandale** [comment]
I'm closing this for now. If you have any more question feel free to open a new issue.
