### ISSUE TITLE
Changing order of source blocks changes which gems are loaded from which source

### ISSUE THREAD

**Issue by isen0011** [bundler/bundler#5945]
When I have a Gemfile that looks like this:
```
source 'https://rubygems.org' do
  ruby '2.4.1'
  gem 'rails', '~> 5.1.2'
end

source "https://artifactory.umn.edu/artifactory/api/gems/asr-rubygems/" do
  gem "lastpassify"
end
```

Bundler tries to load minitest (sub-requirement of rails) from the second source server:
```
Gem::RemoteFetcher::FetchError: too many connection resets
(https://isen0011:REDACTED@artifactory.umn.edu/artifactory/api/gems/asr-rubygems/gems/minitest-5.10.3.gem)
```

But, if I change the order of the two source statements, so the Gemfile looks like this:
```
source "https://artifactory.umn.edu/artifactory/api/gems/asr-rubygems/" do
  gem "lastpassify"
end

source 'https://rubygems.org' do
  ruby '2.4.1'
  gem 'rails', '~> 5.1.2'
end
```
...everything installs correctly, with minitest loading from rubygems.org

[repro script](https://gist.github.com/isen0011/02007020a715bffc46d7558fd6b7570c).
Note that I am using our internal artifactory server as a source for one of the two gems, which would need to be changed to make this work for anyone outside our organization.

**Comment by segiddins** [comment]
All I get is

```
Could not fetch specs from
https://artifactory.umn.edu/artifactory/api/gems/asr-rubygems/
```

**Comment by colby-swandale** [comment]
ping @isen0011

**Comment by segiddins** [comment]
This will be fixed in Bundler 2 by https://github.com/bundler/bundler/pull/5985, so I'm going to close this out. Thanks for reporting it!
