### ISSUE TITLE
uninitialized constant Bundler::RubygemsIntegration::YamlLibrarySyntaxError

### ISSUE THREAD

**Issue by KavehRS** [bundler/bundler#5946]
I ran the command `/home/i/bin/bundle install`
  I expected Bundler to do "`bundle install`" after that run Jekyllrb and View the result of editing .
  Instead, what actually happened was did not work and show this error

> 
> Error details
> 
>     NameError: uninitialized constant Bundler::RubygemsIntegration::YamlLibrarySyntaxError
> Did you mean?  Bundler::YamlSyntaxError
>       /usr/lib/ruby/vendor_ruby/bundler/rubygems_integration.rb:71:in `rescue in configuration'
>       /usr/lib/ruby/vendor_ruby/bundler/rubygems_integration.rb:65:in `configuration'
>       /usr/lib/ruby/vendor_ruby/bundler/fetcher.rb:224:in `connection'
>       /usr/lib/ruby/vendor_ruby/bundler/fetcher.rb:72:in `initialize'
>       /usr/lib/ruby/vendor_ruby/bundler/source/rubygems.rb:231:in `new'
>       /usr/lib/ruby/vendor_ruby/bundler/source/rubygems.rb:231:in `block in fetchers'
>       /usr/lib/ruby/vendor_ruby/bundler/source/rubygems.rb:229:in `map'
>       /usr/lib/ruby/vendor_ruby/bundler/source/rubygems.rb:229:in `fetchers'
>       /usr/lib/ruby/vendor_ruby/bundler/source/rubygems.rb:335:in `block in remote_specs'
>       /usr/lib/ruby/vendor_ruby/bundler/index.rb:9:in `build'
>       /usr/lib/ruby/vendor_ruby/bundler/source/rubygems.rb:334:in `remote_specs'
>       /usr/lib/ruby/vendor_ruby/bundler/source/rubygems.rb:81:in `specs'
>       /usr/lib/ruby/vendor_ruby/bundler/definition.rb:209:in `block (2 levels) in index'
>       /usr/lib/ruby/vendor_ruby/bundler/definition.rb:207:in `each'
>       /usr/lib/ruby/vendor_ruby/bundler/definition.rb:207:in `block in index'
>       /usr/lib/ruby/vendor_ruby/bundler/index.rb:9:in `build'
>       /usr/lib/ruby/vendor_ruby/bundler/definition.rb:204:in `index'
>       /usr/lib/ruby/vendor_ruby/bundler/definition.rb:198:in `resolve'
>       /usr/lib/ruby/vendor_ruby/bundler/definition.rb:137:in `specs'
>       /usr/lib/ruby/vendor_ruby/bundler/definition.rb:126:in `resolve_remotely!'
>       /usr/lib/ruby/vendor_ruby/bundler/installer.rb:194:in `resolve_if_need'
>       /usr/lib/ruby/vendor_ruby/bundler/installer.rb:69:in `run'
>       /usr/lib/ruby/vendor_ruby/bundler/installer.rb:21:in `install'
>       /usr/lib/ruby/vendor_ruby/bundler/cli/install.rb:105:in `run'
>       /usr/lib/ruby/vendor_ruby/bundler/cli.rb:172:in `install'
>       /usr/lib/ruby/vendor_ruby/thor/command.rb:27:in `run'
>       /usr/lib/ruby/vendor_ruby/thor/invocation.rb:126:in `invoke_command'
>       /usr/lib/ruby/vendor_ruby/thor.rb:359:in `dispatch'
>       /usr/lib/ruby/vendor_ruby/thor/base.rb:440:in `start'
>       /usr/lib/ruby/vendor_ruby/bundler/cli.rb:10:in `start'
>       /home/i/.rvm/gems/ruby-2.4.0/gems/bundler-1.15.3/exe/bundle:30:in `block in <top (required)>'
>       /usr/lib/ruby/vendor_ruby/bundler/friendly_errors.rb:7:in `with_friendly_errors'
>       /home/user/.rvm/gems/ruby-2.4.0/gems/bundler-1.15.3/exe/bundle:22:in `<top (required)>'
>       /home/user/bin/bundle:22:in `load'
>       /home/user/bin/bundle:22:in `<main>'
> 
> Environment
> 
>     Bundler   1.11.2
>     Rubygems  2.5.1
>     Ruby      2.3.1p112 (2016-04-26 revision 0) [x86_64-linux-gnu]
>     GEM_HOME  /home/user/.rvm/gems/ruby-2.4.0
>     GEM_PATH  /home/user/.rvm/gems/ruby-2.4.0:/home/i/.rvm/gems/ruby-2.4.0@global
>     RVM       1.29.2 (manual)
>     Git       2.7.4
>     rubygems-bundler (1.4.4)
>

**Comment by segiddins** [comment]
Can you try with the latest Bundler, 1.15.3? Thanks!

**Comment by KavehRS** [comment]
I updated the Bundler, but after updating it again, Like the past in 1.11.2
after that i uninstall bundler  (`gem uninstall bundler -v 1.11.2`)
and install again (`gem install bundler -v 1.15.3`)
but again after (`bundle install`) The same mistake the past gave, and say : 

> Environment
> Bundler   1.11.2
> Rubygems  2.5.1
> Ruby      2.3.1p112 (2016-04-26 revision 0) [x86_64-linux-gnu]
> GEM_HOME  /home/user/.rvm/gems/ruby-2.4.0
> GEM_PATH  /home/user/.rvm/gems/ruby-2.4.0:/home/i/.rvm/gems/ruby-2.4.0@global
> RVM       1.29.2 (manual)
> Git       2.7.4
> rubygems-bundler (1.4.4)
>

**Comment by segiddins** [comment]
That's still invoking Bundler 1.11.2
