### ISSUE TITLE
Bundler prints some warnings to standard output

### ISSUE THREAD

**Issue by zetetic** [bundler/bundler#5952]
For example, running `bundle exec some_command` when an outdated Bundler is installed produces output like:

```
The latest bundler is 1.15.3, but you are currently running 1.15.1.
To update, run `gem install bundler`
```

That is a helpful message to be sure, but the warning message is printed to STDOUT instead of STDERR, which is problematic if you are trying to consume the output of `some_command`. I could (almost) see Bundler being lax about where the output for Bundlers own commands like `bundle install` get printed, but `bundle exec` is there to provide a way to run Bundler-enabled scripts, which quite reasonably should not expect their output stream to contain messages from Bundler.

**Comment by colby-swandale** [comment]
Bundler will print warnings to stderr in version 2

**Comment by segiddins** [comment]
Also, in `1.15.3`, that warning won't be printed at all when running `bundle exec`
