### ISSUE TITLE
Add gem load paths with their realpath and not their regular path

### ISSUE THREAD

**Issue by grosser** [bundler/bundler#5953]
Rails adds engine load paths as realpath ... require_relative also uses the realpath ... mixing this with bundler/setup results in double requires since the load path at first is all symlinked folders and then rails adds realpaths which makes regular requires break ... and require_relative does the same.

Atm using this workaround:

```
# Gemfile
require_relative 'lib/bundler_realpath'
 
# lib/bundler_realpath.rb
# https://grosser.it/2017/08/19/bundler-rails-realpath-expand_path-and-symlinked-vendorbundle-cause-already-loaded-errors
Bundler::Runtime.prepend(Module.new do
  def setup(*)
    super
  ensure
    linked_bundle = File.expand_path(Bundler.bundle_path)
    real_bundle = File.realpath(Bundler.bundle_path)
    if linked_bundle != real_bundle
      $LOAD_PATH.each_with_index do |path, i|
        $LOAD_PATH[i] = path.sub(linked_bundle, real_bundle)
      end
    end
  end
end)
```

**Comment by segiddins** [comment]
Can you please share a script that we can use to reproduce the issue, thanks!

**Comment by grosser** [comment]
https://github.com/grosser/bundle-relative

**Comment by segiddins** [comment]
I'm guessing you'd run into the same issue even using plain RubyGems and setting `GEM_HOME` to a symlink as well?

**Comment by grosser** [comment]
any symbolic link in the load path would do that ... usually system gems etc are stable so they would not be symlinks ... for deployment is can make sense to symlink a shared vendor/bundle to speedup bundling and then this issue happens.

**Comment by segiddins** [comment]
my point is more that this is not specific to Bundler, but would also happen when using plain RubyGems

**Comment by grosser** [comment]
yes.

what I'm suggesting is that bundler should add 'realpath' to load paths
(like rails does) to prevent this kind of issue.

**Comment by segiddins** [comment]
shouldn't that fix go in RubyGems, by making `full_gem_path` _always_ return the realpath?

**Comment by grosser** [comment]
hmm that could be even better ...

**Comment by colby-swandale** [comment]
@grosser would you be able to open an issue in https://github.com/rubygems/rubygems with the details of this issue please.

**Comment by grosser** [comment]
opened https://github.com/rubygems/rubygems/issues/2005

**Comment by colby-swandale** [comment]
I'm closing this issue, new comments should be posted to https://github.com/rubygems/rubygems/issues/2005
