### ISSUE TITLE
Gem::RemoteFetcher::FetchError: EOFError: end of file reached

### ISSUE THREAD

**Issue by zedtux** [bundler/bundler#5962]
### What you're trying to accomplish

This issue happens on the our CI when I'm pushing some code and the build ran.
We are using Docker with a Dockerfile in order to build the image on the server and then run the tests inside.

So we are using a private gem server (mirroring external gems and hosting internal private gems) and I noticed that this issue started to popup when the server has been moved from a vlan to another.
I don't know if this is the source of the issue or not.

Another thing is we are using a proxy in the company. The Dockerfile is setting the `HTTPS_PROXY` and the `https_proxy` env variable before to run the command.

Also, this error happen for a different gem file on different builds (in this ticket, the failing gem is `json` but the next build will be another gem).

### The command you ran

The error occurs on the build step, after having installed the system dependencies (apt-get) we are running the following command:

```
bundle install --jobs $(nproc) --without production
```

### What you expected to happen

Gems installation goes fine and I can finish the Docker image building and run the tests suite.

### What actually happened

The bundler command fails throwing a `EOFError` error.

### The exception backtrace(s), if any

```
Step 21 : RUN bundle install --jobs $(nproc) --without production
 ---> Running in 3998149c4f41
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.
Fetching gem metadata from http://gems.my-company.com/......
Fetching version metadata from http://gems.my-company.com/..
Resolving dependencies...
Installing aasm 4.11.1
Installing rake 11.3.0
Installing i18n 0.8.6
Installing builder 3.2.3
Installing thread_safe 0.3.6
Installing erubis 2.7.0
Installing mini_portile2 2.2.0
Installing arel 6.0.4
Using bundler 1.14.3
Installing ast 2.3.0
Installing concurrent-ruby 1.0.5
Installing thor 0.19.4
Installing mimemagic 0.3.2
Installing httpclient 2.8.2.4
Installing powerpack 0.1.1
Installing rspec-support 3.5.0
Installing ruby-progressbar 1.8.1
Installing yard 0.9.5
Gem::RemoteFetcher::FetchError: EOFError: end of file reached
(http://gems.my-company.com/gems/json-1.8.6.gem)
An error occurred while installing json (1.8.6), and Bundler cannot continue.
Make sure that `gem install json -v '1.8.6'` succeeds before bundling.
The command '/bin/sh -c bundle install --jobs $(nproc) --without production' returned a non-zero code: 5
ERROR: Build failed: exit code 5
```

### Everything output by running bundle env

<details>
 <summary>Details</summary>

## Environment

```
Bundler   1.14.3
Rubygems  2.4.8
Ruby      2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux]
GEM_HOME  /usr/local/bundle
GEM_PATH  
Git       2.1.4
Platform  x86_64-linux
```

## Bundler settings

```
path
  Set for the current user (/root/.bundle/config): "/usr/local/bundle"
bin
  Set for the current user (/root/.bundle/config): "/usr/local/bundle/bin"
app_config
  Set via BUNDLE_APP_CONFIG: "/usr/local/bundle"
```

### Gemfile

```ruby
source 'http://gems.my-company.com'

# Specify your gem's dependencies in fundlook_regulators.gemspec
gemspec
```

### Gemfile.lock

```
<No /gem/Gemfile.lock found>
```

### fundlook_regulators.gemspec

```ruby
# coding: utf-8
lib = File.expand_path('../lib', __FILE__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)
require 'mygem/version'

Gem::Specification.new do |spec|
  spec.name          = 'mygem'
  spec.version       = Mygem::VERSION
  spec.authors       = ['me']
  spec.email         = ['me@my-company.com']

  spec.summary       = 'mygem'
  spec.description   = 'mygem.'
  spec.homepage      = 'http://github.com/me/mygem'

  # Prevent pushing this gem to RubyGems.org. To allow pushes either set the
  # 'allowed_push_host' to allow pushing to a single host or delete this section
  # to allow pushing to any host.
  if spec.respond_to?(:metadata)
    spec.metadata['allowed_push_host'] = 'http://gems.my-company.com'
  end

  spec.files = Dir['CHANGELOG.md', 'README.md', 'Gemfile',
                   'Rakefile', '.*', '*.gemspec', 'bin/*',
                   'lib/**/*', 'app/**/*'].select { |f| File.file?(f) }
  spec.bindir        = 'exe'
  spec.executables   = spec.files.grep(%r{^exe/}) { |f| File.basename(f) }
  spec.require_paths = ['lib']

  spec.required_ruby_version = '>= 2.0.0'

  spec.add_dependency 'rails', '~> 4.2.7.1'
  spec.add_dependency 'paperclip', '~> 5.1.0'
  spec.add_dependency 'aasm', '~> 4.11.1'

  spec.add_development_dependency 'bundler', '~> 1.14.3'
  spec.add_development_dependency 'rake', '~> 11.3.0'
  spec.add_development_dependency 'json', '~> 1.8.3'
  spec.add_development_dependency 'rspec', '~> 3.5.0'
  spec.add_development_dependency 'redcarpet', '~> 3.3.4' # Yard requirement
  spec.add_development_dependency 'yard', '~> 0.9.5'
  spec.add_development_dependency 'geminabox', '~> 0.13.4'
  spec.add_development_dependency 'rubocop', '~> 0.46.0'
end
```
</details>

**Comment by zedtux** [comment]
Another information, while the failing builds are for internal gems, our Rails projects are building correctly, without any error from Bundler!

**Comment by segiddins** [comment]
Your server isn't returning a complete file. Does running the suggested `gem install` command succeed?

**Comment by zedtux** [comment]
Thank you @segiddins for your comment. Yes, we did `curl` the file and check the `md5sum` prints and all work fine.

I was thinking that the issue happens when there several parallel gems downloaded at the same time, so I did try with a shell script to curl multiple gems at the same time, but didn't got any issues, and I also tried to use only 1 job at a time (`--jobs 1`) but steel the same issue.

**Comment by zedtux** [comment]
Could it be that my issue is related to [this](https://stackoverflow.com/questions/17863217/bundle-install-fetcherror-eoferror)?
How to check that?

**Comment by zedtux** [comment]
We fixed the issue, finally ! :)

So the issue was that in the Dockerfile we were setting 4 environment variables in order to setup the proxy so that `apt-get` was able to reach the Internet, but then we weren't reseting all those 4 variables (see the attached screenshot for a better understanding).

![screen shot 2017-08-22 at 10 10 09](https://user-images.githubusercontent.com/478564/29555189-2398cfaa-8722-11e7-9b7d-b36b3b4b1dcc.png)
