### ISSUE TITLE
Bundler choose wrong ruby version in folder path

### ISSUE THREAD

**Issue by benoittgt** [bundler/bundler#5966]
Hello

I have an issue on circleci with ruby2.4.1:

```sh
$ bundle env
## Environment

Bundler   1.15.4
Rubygems  2.6.12
Ruby      2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
GEM_HOME  /usr/local/bundle
GEM_PATH
Git       2.1.4
Platform  x86_64-linux
OpenSSL   OpenSSL 1.0.1t  3 May 2016

```
and
```sh
$ bundle show rspec
/home/circleci/app/vendor/bundle/ruby/2.4.0/gems/rspec-3.5.0
```

My command to run bundler is `bundle install --jobs=4 --retry=3 --path vendor/bundle`

What can happen that let bundler choose 2.4.0?

**Comment by segiddins** [comment]
I'm sorry, I don't quite understand what the issue is?

**Comment by benoittgt** [comment]
Sorry @segiddins 

Why gems are installed in folder with `ruby/2.4.0/gem` when I have 2.4.1 as ruby version.

**Comment by segiddins** [comment]
Because it's the 2.4.0 ABI

**Comment by benoittgt** [comment]
I was confused by local install with rvm where the ruby version is set in the path by rvm.

Thanks for the help.
