### ISSUE TITLE
PathError in jruby warfile

### ISSUE THREAD

**Issue by torcido** [bundler/bundler#5975]
I suspect that a recent change in bundler 1.15.4 to fix issue #5485 has broken bundler when executed inside a war file created with jruby.

The particular error we're seeing is:

```
(PathError) Your bundle path contains a ':', which is the path separator for your system. Bundler cannot function correctly when the Bundle path contains the system's PATH separator. Please change your bundle path to not include ':'.
Your current bundle path is 'uri:classloader:/WEB-INF/gems'.
```

This only fails on Linux (or Unix-type systems), where the path separator is a colon. It works fine on Windows.

Is there a way we can exclude path components matching that uri: pattern, or else somehow detect that we're running from within a war file and turn off that error?

**Comment by segiddins** [comment]
Can you point us to how RubyGems splits paths on Jruby to allow that to work? It should be possible to use the same logic

**Comment by torcido** [comment]
I think that jruby creates Gem.path_separator as a regex, and RubyGems splits on that.

**Comment by torcido** [comment]
When running from a war file, here's what I get:

```
> Gem.path_separator
=> /(?<!jar:file|jar|file|classpath|uri:classloader|uri|http|https):/
```

**Comment by segiddins** [comment]
So I think what we have to do is `raise ... if ENV["PATH"].split(Gem.path_separator).size > 1`

**Comment by torcido** [comment]
I think you mean `if Bundler.bundle_path.to_s.split(Gem.path_separator).size > 1` rather than `if ENV["PATH"]...`.

I guess the more difficult part of the change will be how to describe the rules in the error message. It doesn't read well to say `Your bundle path contains a '(?-mix:(?<!jar:file|jar|file|classpath|uri:classloader|uri|http|https):)'`.

You could say `Your bundle path contains text matching /(?<!jar:file|jar|file|classpath|uri:classloader|uri|http|https):/`. If you're not running in a war file, it would read `Your bundle path contains text matching ":"`. It's not terrible, but is it clear?
