### ISSUE TITLE
bundle update adds dependencies of newer gem versions to Gemfile.lock

### ISSUE THREAD

**Issue by Aqualon** [bundler/bundler#5987]
Consider this Gemfile

```
source 'http://rubygems.org'

gem 'capistrano-notifier'
gem 'capistrano'
```

This will resolve to capistrano 2.15.9 on bundle install, because capistrano-notifier has version constraint of `>= 2, < 3`.

If I run bundle update afterwards, I get sshkit gem added to Gemfile.lock, which is a dependency of capistrano 3, but not 2.

```
diff --git a/Gemfile.lock b/Gemfile.lock
index 7048919..c3346b1 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -71,6 +71,9 @@ GEM
       nokogiri (>= 1.6)
     rails-html-sanitizer (1.0.3)
       loofah (~> 2.0)
+    sshkit (1.14.0)
+      net-scp (>= 1.1.2)
+      net-ssh (>= 2.8.0)
     thread_safe (0.3.6)
     tzinfo (1.2.3)
       thread_safe (~> 0.1)
```

If I restrict capistrano to version 2 in the Gemfile this doesn't happen.

So to me it looks liker bundler considers dependencies of the latest capistrano version, if there is no version restriction defined in Gemfile, but does not remove them if the final version of capistrano used is restricted by another gem.

Bundler version used was 1.15.4

**Comment by segiddins** [comment]
This appears to be fixed on `master`, which uses Molinillo 0.6.0, versus 1.15 which used 0.5.
