### ISSUE TITLE
Bundle console Unexpected error

### ISSUE THREAD

**Issue by Gururaj030** [bundler/bundler#5988]
### hi_source_registry_service_client.gemspec

```ruby
lib = File.expand_path('../lib', __FILE__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)
require 'hi_source_registry_service_client/version'

Gem::Specification.new do |spec|
  spec.name = 'hi_source_registry_service_client'
  spec.version = HiSourceRegistryService::VERSION
  spec.authors = ['HealtheIntent Infrastructure Dark Knight']
  spec.email = ['DL_Dark_Knight@cerner.com']
  spec.description = %q{Models and client for the HealtheIntent Source Registry service.}
  spec.summary = %q{Models and client for the HealtheIntent Source Registry service.}
  spec.homepage = 'https://github.cerner.com/hi-infra/hi_source_registry_service_client'

  spec.files = Dir['{app,config,lib}/**/*']
  spec.test_files = Dir['spec/**/*']
  spec.require_paths = ['lib']

  spec.required_ruby_version = '>= 2.0.0'
  spec.add_dependency 'hi-service_client', '~> 4.0'
end
```

--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/bundler/bundler/search?q=uninitialized+constant+RollOut++Logging&type=Issues

If there aren't any reports for this error yet, please create copy and paste the report template above into a new issue. Don't forget to anonymize any private data! The new issue form is located at:
https://github.com/bundler/bundler/issues/new

**Comment by colby-swandale** [comment]
Sorry that you're having a problem with Bundle. Unfortunately, the information that you have provided isn't enough for us to tell what went wrong, or how to fix it. Please follow the instructions in [ISSUES](https://github.com/bundler/bundler/blob/master/doc/contributing/ISSUES.md) and report back so that we can try to help.

**Comment by colby-swandale** [comment]
ping @Gururaj030

**Comment by colby-swandale** [comment]
I'm closing this for now. If you're still experiencing your original issue don't be afraid to re-open this ticket.
