### ISSUE TITLE
There was an error accessing

### ISSUE THREAD

**Issue by mhadiahmed** [bundler/bundler#5990]
```
There was an error accessing
`/home/mhadi/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/versions`.
The underlying system error is Errno::EPERM: Operation not permitted @
rb_file_s_rename -
(/tmp/bundler-compact-index-20170831-15666-1on94rh/versions,
/home/mhadi/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/versions)
```
after execute this commands 

```
sudo chmod 1777 -R /home/mhadi/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47
```
and 
```
sudo chmod 1777 -R /tmp
```

it show this 

```
There was an error accessing
`/home/mhadi/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/versions`.
The underlying system error is Errno::EPERM: Operation not permitted @
rb_file_s_rename -
(/tmp/bundler-compact-index-20170831-15687-39acgn/versions,
/home/mhadi/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/versions)
```

**Comment by colby-swandale** [comment]
Can you attach the output of `bundle env`. Which command were running as well when you got this error?

Something you can try to do is delete `/home/mhadi/.bundle/cache/` and `/tmp/bundler-compact-index-20170831-15687-39acgn` and then try again.

**Comment by colby-swandale** [comment]
@mhadiahmed were you able to resolve your issue? The issue seems to be the user that is running `bundle install` doesn't have access to `/home/mhadi/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47`.

**Comment by colby-swandale** [comment]
I'm closing this for now. If you're still experiencing your original issue don't be afraid to re-open this ticket.
