### ISSUE TITLE
Enable GemVersionPromoter for all cases

### ISSUE THREAD

**Issue by chrismo** [bundler/bundler#5993]
These lines show that the GemVersionPromoter is completely skipped in the default `--major` case to not risk screwing with stuff in 1.x. 

https://github.com/bundler/bundler/blob/master/lib/bundler/resolver.rb#L124-L130

Not a big deal, but better to do for 2.x earlier rather than later.

**Comment by segiddins** [comment]
I wonder what the performance implications of this are?
