### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by cbfiddle** [bundler/bundler#5996]
I need help trying to figure why I am getting the "command not found" error when I try to do:

bundle exec middleman

This used to work, but I needed to reinstall bundler (probably after an OS upgrade) and since then it no longer works.
"bundle check" does not report any errors.
There is an executable script "middleman" in /Library/Ruby/Gems/2.0.0/gems/middleman-core-3.4.0/bin.
/Library/Ruby/Gems/2.0.0/gems/middleman-core-3.4.0 is one of the paths shown by bundle show --paths.

bundle -- version says: 1.15.4

By the way, I know nothing whatsoever about Ruby. I just want to use middleman!

Thank you.

**Comment by segiddins** [comment]
Please share the output of `bundle env`

**Comment by cbfiddle** [comment]
## Environment

```
Bundler   1.15.4
Rubygems  2.0.14.1
Ruby      2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
Git       2.11.0 (Apple Git-81)
Platform  universal-darwin-16
OpenSSL   OpenSSL 0.9.8zc 19 Mar 2015
```

## Gemfile

### Gemfile

```ruby
# If you do not have OpenSSL installed, update
# the following line to use "http://" instead
source 'https://rubygems.org'

gem "middleman", "~>3.4.0"

# Live-reloading plugin
gem "middleman-livereload", "~> 3.1.0"

# For faster file watcher updates on Windows:
gem "wdm", "~> 0.1.0", :platforms => [:mswin, :mingw]

# Windows does not come with time zone data
gem "tzinfo-data", platforms: [:mswin, :mingw, :jruby]
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    activesupport (4.2.4)
      i18n (~> 0.7)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.3, >= 0.3.4)
      tzinfo (~> 1.1)
    capybara (2.4.4)
      mime-types (>= 1.16)
      nokogiri (>= 1.3.3)
      rack (>= 1.0.0)
      rack-test (>= 0.5.4)
      xpath (~> 2.0)
    chunky_png (1.3.4)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.9.1.1)
    compass (1.0.3)
      chunky_png (~> 1.2)
      compass-core (~> 1.0.2)
      compass-import-once (~> 1.0.5)
      rb-fsevent (>= 0.9.3)
      rb-inotify (>= 0.9)
      sass (>= 3.3.13, < 3.5)
    compass-core (1.0.3)
      multi_json (~> 1.0)
      sass (>= 3.3.0, < 3.5)
    compass-import-once (1.0.5)
      sass (>= 3.2, < 3.5)
    em-websocket (0.5.1)
      eventmachine (>= 0.12.9)
      http_parser.rb (~> 0.6.0)
    erubis (2.7.0)
    eventmachine (1.0.8)
    execjs (2.6.0)
    ffi (1.9.10)
    haml (4.0.7)
      tilt
    hike (1.2.3)
    hooks (0.4.1)
      uber (~> 0.0.14)
    http_parser.rb (0.6.0)
    i18n (0.7.0)
    json (1.8.3)
    kramdown (1.8.0)
    listen (3.0.3)
      rb-fsevent (>= 0.9.3)
      rb-inotify (>= 0.9)
    middleman (3.4.0)
      coffee-script (~> 2.2)
      compass (>= 1.0.0, < 2.0.0)
      compass-import-once (= 1.0.5)
      execjs (~> 2.0)
      haml (>= 4.0.5)
      kramdown (~> 1.2)
      middleman-core (= 3.4.0)
      middleman-sprockets (>= 3.1.2)
      sass (>= 3.4.0, < 4.0)
      uglifier (~> 2.5)
    middleman-core (3.4.0)
      activesupport (~> 4.1)
      bundler (~> 1.1)
      capybara (~> 2.4.4)
      erubis
      hooks (~> 0.3)
      i18n (~> 0.7.0)
      listen (~> 3.0.3)
      padrino-helpers (~> 0.12.3)
      rack (>= 1.4.5, < 2.0)
      thor (>= 0.15.2, < 2.0)
      tilt (~> 1.4.1, < 2.0)
    middleman-livereload (3.1.1)
      em-websocket (>= 0.2.0)
      middleman-core (>= 3.0.2)
      multi_json (~> 1.0)
      rack-livereload
    middleman-sprockets (3.4.2)
      middleman-core (>= 3.3)
      sprockets (~> 2.12.1)
      sprockets-helpers (~> 1.1.0)
      sprockets-sass (~> 1.3.0)
    mime-types (2.6.1)
    mini_portile (0.6.2)
    minitest (5.8.0)
    multi_json (1.11.2)
    nokogiri (1.6.6.2)
      mini_portile (~> 0.6.0)
    padrino-helpers (0.12.5)
      i18n (~> 0.6, >= 0.6.7)
      padrino-support (= 0.12.5)
      tilt (~> 1.4.1)
    padrino-support (0.12.5)
      activesupport (>= 3.1)
    rack (1.6.4)
    rack-livereload (0.3.16)
      rack
    rack-test (0.6.3)
      rack (>= 1.0)
    rb-fsevent (0.9.5)
    rb-inotify (0.9.5)
      ffi (>= 0.5.0)
    sass (3.4.18)
    sprockets (2.12.4)
      hike (~> 1.2)
      multi_json (~> 1.0)
      rack (~> 1.0)
      tilt (~> 1.1, != 1.3.0)
    sprockets-helpers (1.1.0)
      sprockets (~> 2.0)
    sprockets-sass (1.3.1)
      sprockets (~> 2.0)
      tilt (~> 1.1)
    thor (0.19.1)
    thread_safe (0.3.5)
    tilt (1.4.1)
    tzinfo (1.2.2)
      thread_safe (~> 0.1)
    uber (0.0.14)
    uglifier (2.7.2)
      execjs (>= 0.3.0)
      json (>= 1.8.0)
    xpath (2.0.0)
      nokogiri (~> 1.3)

PLATFORMS
  ruby

DEPENDENCIES
  middleman (~> 3.4.0)
  middleman-livereload (~> 3.1.0)
  tzinfo-data
  wdm (~> 0.1.0)

BUNDLED WITH
   1.10.6

**Comment by segiddins** [comment]
> This used to work, but I needed to reinstall bundler (probably after an OS upgrade) and since then it no longer works.


In what way does it not work?

**Comment by cbfiddle** [comment]
"command not found"

**Comment by arbonap** [comment]
@cbfiddle could you please paste the stacktrace you're getting?

**Comment by segiddins** [comment]
Please share the full output of the command you're trying to run, otherwise it's hard to tell what's actually happening

**Comment by cbfiddle** [comment]
Here is the command and the output:

```
$ bundle exec middleman
bundler: command not found: middleman
Install missing gem executables with `bundle install`
```
There is no stack trace.

**Comment by segiddins** [comment]
did you run `bundle install` as suggested?

**Comment by cbfiddle** [comment]
I had not done that, because bundle check said everything was fine.
So I have now run bundle install, and as expected, it also says the bundle is complete.
The problem remains.

**Comment by segiddins** [comment]
can you run the following for me: `ruby -rbundler/setup -e 'puts Gem.bin_path("middleman", "middleman"); puts ENV["PATH"]` ?

**Comment by cbfiddle** [comment]
```
$ ruby -rbundler/setup -e 'puts Gem.bin_path("middleman", "middleman"); puts ENV["PATH"]'
/Library/Ruby/Gems/2.0.0/gems/middleman-core-3.4.0/bin/middleman
/Library/Ruby/Gems/2.0.0/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/ant/bin:/usr/local/mysql/bin:/Library/Java/JavaVirtualMachines/1.8.0.jdk/Contents/Home/bin:/Users/alan/bin:/SharedApplications/android-sdk-macosx/tools:/Library/Ruby/Gems/2.0.0
```

**Comment by segiddins** [comment]
super weird, there should be a bin stub in `/Library/Ruby/Gems/2.0.0/bin` named `middleman` that loads `Gem.bin_path("middleman", "middleman")`, I'm not sure why it isn't

**Comment by cbfiddle** [comment]
There is no directory "bin" in /Library/Ruby/Gems/2.0.0.

How do I fix this?

**Comment by arbonap** [comment]
Hmmm.... I was reading through similar Middleman's issues, and [came across this](https://github.com/middleman/middleman/issues/1370). This doesn't fix the crux of the problem, but possibly try `gem install middleman`, and then try `bundle exec middleman` as a work around.

**Comment by cbfiddle** [comment]
I tried the following, because I do not want to change middleman versions:

```
$ sudo gem install middleman -v 3.4.0
Fetching: sprockets-3.7.1.gem (100%)
ERROR:  Error installing middleman:
	sprockets requires concurrent-ruby (~> 1.0)
```

**Comment by segiddins** [comment]
ah, so turns out the `middleman` command is in the `middleman-cli` gem, so try `gem install middleman-cli` or `gem pristine middleman-cli` ?

**Comment by cbfiddle** [comment]
I assume you mean `middleman-core`?

I did this:

`sudo gem install middleman-core -v 3.4.0
`

and this:

`sudo gem pristine middleman-core -v 3.4.0
`

There is still no /Library/Ruby/Gems/2.0.0/bin directory (there is a `gems/middleman-core-3.4.0/bin`), but the good news is that it now works!

Thank you for your help.

**Comment by cbfiddle** [comment]
I have to admit I never understood how the above magic fixed my problem, and perhaps it didn't. The problem has reappeared, but with a twist:

- If I run `bundle exec middleman build` from the terminal in my project directory, it works.
- If I invoke `bundle` with the same arguments from a Java application running under the IDEA debugger (connected to the project directory), it works.
- If I run the same Java application that has been packaged as an macOS application, it fails as above (middleman not found).

I modified the Java application to run `bundle env` after a failure, and it produces the same output as I get doing this from the terminal.

I then modified the Java application to run `env` after a failure, and I discovered that when run as a bundled app, the PATH is different. In particular, it does not contain `/usr/local/bin`, which is where the `bundle` program lives.

So, I changed the Java application to add `/usr/local/bin` to the PATH when running `bundle`, and it worked. I also tried running `/usr/local/bin/bundle` from the terminal without `/usr/local/bin` in the PATH, and it failed (the same way).

The upshot seems to be that `bundle` needs something, perhaps itself, to be in the PATH.

Is that a surprise? Seems like a bad idea to me.

**Comment by cbfiddle** [comment]
I think there is a bug here because the behaviors of `bundle exec` and `bundle env` are inconsistent.

In my example, there are two values of PATH:
- /usr/bin:/bin:/usr/sbin:/sbin
- /usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin

There are also two versions of Ruby (this is macOS, which comes with a version of Ruby):
- /usr/bin/ruby [2.0.0p648]
- /usr/local/bin/ruby [2.4.1p111]

`bundle exec` apparently uses PATH to find Ruby and its database. It behaves differently given the two PATHs above.

`bundle env` apparently does not use PATH, because it produces the exact same output for the two PATHs.

One of them must be wrong.

**Comment by rahulaga** [comment]
Thanks for the hint. For me I actually see the bin under `middleman-cli`. So I added this to my PATH and it works now: /Library/Ruby/Gems/2.3.0/gems/middleman-cli-4.2.1/bin

**Comment by segiddins** [comment]
This sounds like a ruby/rubygems installation / path issue to me

**Comment by colby-swandale** [comment]
ping @cbfiddle were you able to resolve your issue.

**Comment by cbfiddle** [comment]
Yes, by ensuring that PATH was set the same in all contexts of use.

**Comment by cbfiddle** [comment]
I have to say that even though I was able to resolve my issue, I think it is a bug that bundle exec and bundle env are inconsistent in their use of PATH. When bundle exec does not do what you want, people are advised to run bundle env. That is useful only if bundle env describes the environment as used by bundle exec, which is not necessarily the case.
