### ISSUE TITLE
Hi I am unable to update gems when I click on install link on popup"RubyMine has detected that some of the gems required for 'STX' are not installed. Install"

### ISSUE THREAD

**Issue by swaminath-k** [bundler/bundler#5998]

**Comment by segiddins** [comment]
This seems like an issue with RedMine, does installing via the command line work?

**Comment by colby-swandale** [comment]
ping @swaminath-k

**Comment by colby-swandale** [comment]
I'm closing this for now. If you're still experiencing your original issue don't be afraid to re-open this ticket.

**Comment by swaminath-k** [comment]
It's working with cmd but I need to update all gems in bulk so what is solution for that
