### ISSUE TITLE
Bundler::CurrentRuby.x64_mingw? method bad?

### ISSUE THREAD

**Issue by MSP-Greg** [bundler/bundler#6000]
My 'daily Ruby' is a MinGW build of trunk.

Since no 'fat binary' gems are compatible with 2.5, my .gemrc file has `--platform ruby` in both install and update.  While recently working on creating a PR for Nokogiri to update it's Appveyor matrix, I ran into an issue.  The method [`Bundler::CurrentRuby.x64_mingw?`](https://github.com/bundler/bundler/blob/57f5ef656bb1845079225dde42b2d91ecb07ee2b/lib/bundler/current_ruby.rb#L69-L71) doesn't seem to work correctly.

Below is the output of several method calls, which isn't affected by my .gemrc file:
```
Bundler.current_ruby.ruby?      false
Bundler.current_ruby.mingw?     false
Bundler.current_ruby.x64_mingw? false
Bundler::WINDOWS                0
Bundler.local_platform          ruby
Gem::Platform::RUBY             ruby
Bundler.local_platform          ruby
Bundler.local_platform.class    String
```

Note that since `Bundler.local_platform` is a string, the `.os` and `.cpu` methods don't exist.

I'm currently using
```
ruby 2.5.0dev (2017-09-02 trunk 59723) [x64-mingw32]
```

I'd do a PR, but there seems to be more than one issue here in the items that are &&'d together in the method.  Happy to help in anyway I can.

EDIT; Discovered the issue because Bundler is not installing two gems in the Gemfile listed as below:
```
gem "racc", ">=1.4.14", :group => [:development, :test], :platform => [:ruby, :mingw, :x64_mingw]
gem "rexical", ">=1.0.5", :group => [:development, :test], :platform => [:ruby, :mingw, :x64_mingw]
```

**Comment by segiddins** [comment]
Please share the output of `gem env` and `bundle env`

**Comment by MSP-Greg** [comment]
```
E:\>gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 2.6.13
  - RUBY VERSION: 2.5.0 (2017-09-03 patchlevel -1) [x64-mingw32]
  - INSTALLATION DIRECTORY: C:/ruby25_64/lib/ruby/gems/2.5.0
  - USER INSTALLATION DIRECTORY: C:/Users/Greg/.gem/ruby/2.5.0
  - RUBY EXECUTABLE: C:/ruby25_64/bin/ruby.exe
  - EXECUTABLE DIRECTORY: C:/ruby25_64/bin
  - SPEC CACHE DIRECTORY: C:/Users/Greg/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: C:/ProgramData
  - RUBYGEMS PLATFORMS:
    - ruby
    - x64-mingw32
  - GEM PATHS:
     - C:/ruby25_64/lib/ruby/gems/2.5.0
     - C:/Users/Greg/.gem/ruby/2.5.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - C:\Windows\system32
     - C:\Windows
     - C:\Windows\System32\Wbem
     - C:\Windows\System32\WindowsPowerShell\v1.0\
     - C:\ruby25_64\bin
     - E:\msys64
     - C:\Program Files (x86)\GNU\GnuPG\pub
     - C:\Program Files\Microsoft SQL Server\130\Tools\Binn\
     - C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common
     - C:\Program Files\Git\cmd
```

E:\>bundle env

## Environment

```
Bundler   1.15.4
Rubygems  2.6.13
Ruby      2.5.0p-1 (2017-09-03 revision 59733) [x64-mingw32]
Git       2.14.1.windows.1
Platform  x64-mingw32
OpenSSL   OpenSSL 1.1.0f  25 May 2017
```

## Bundler settings

```
build.eventmachine
  Set for the current user (C:/Users/Greg/.bundle/config): "--no-document --env-shebang --platform ruby --use-system-libraries --with-ssl-dir=e:/msy
s64/mingw64"
force_ruby_platform
  Set for the current user (C:/Users/Greg/.bundle/config): true
build.nokogiri
  Set for the current user (C:/Users/Greg/.bundle/config): "--use-system-libraries"
retry
  Set for your local app (E:/.bundle/config): 3
jobs
  Set for your local app (E:/.bundle/config): "3"
```

**Comment by segiddins** [comment]
I _think_ this is happening because `force_ruby_platform` is set, but I'll have to check the code to be sure

**Comment by segiddins** [comment]
So `Bundler::WINDOWS` is correctly set to a truthy value since it's based upon `RbConfig::CONFIG["host_os"]`

However, in `Bundler::CurrentRuby`, the predicate methods seem to use `Bundler.local_platform` (which respects `force_ruby_platform`) instead of `Gem::Platform.local`. I'm not sure what the correct answer is here: setting `force_ruby_platform` is telling Bundler to treat your machine _as if it were a "plain ruby" unixy install_, and most people use those predicates to control _native extension activation_, in which the target ABI is what matters, and you're telling bundler to treat your local install like it has a unixy MRI ABI...

**Comment by MSP-Greg** [comment]
> I'm not sure what the correct answer is here

I'm not sure either, as mentioned, I haven't quite wrapped my head around Bundler vs RubyGems, what info is passed from Bundler to RubyGems, what info Bundler 'forces' upon RubyGems, etc.

> setting force_ruby_platform is telling Bundler to treat your machine as if it were a "plain ruby" unixy install

My daily ruby is trunk; I believe that setting is correct, since no one supports trunk (2.5) with 'fat binary gems'.  I need to force install to compile any extension gems that I install.  My trunk build uses the RubyInstaller2 runtime.

I have no idea what you and the others know about Windows, the two build systems, Windows extension gems, etc.

I don't recall coming across a good summary of the above, I'll work on a Wiki page for my (rather out of date) 'ruby-loco' repo.  I'll post a link here when I complete it.

This whole topic may also shed some light on the potential solutions to #5992.  At present, I'm not sure what I consider a reasonable solution to be.  To borrow a common phrase, it's complicated...

**Comment by segiddins** [comment]
https://github.com/bundler/bundler/issues/5992 seems like an unrelated resolver bug

**Comment by MSP-Greg** [comment]
Might be, I don't know what the expectations are.  What should be correct behavior be for the following:

For a specific version of a ruby gem that should be installed, the 'fat binary gem' (pre-compiled) does not support the current ruby version.  The normal uncompiled gem version does.  Should Bundler/RubyGems attempt to install the uncompiled version (and force a compile)?  Note that the compile may fail...

An example would be Nokogiri 1.8.0, [1.8.0-x64-mingw32](https://rubygems.org/gems/nokogiri/versions/1.8.0-x64-mingw32) supports Ruby '< 2.5, >= 2.2', [1.8.0](https://rubygems.org/gems/nokogiri/versions/1.8.0) supports Ruby '>= 2.1.0'

**Comment by segiddins** [comment]
But by specifying `force_ruby_platform`, you're telling bundler to treat your machine _as if the only thing in `Gem.platforms` is "ruby"_, and completely ignore the current platform triple

**Comment by MSP-Greg** [comment]
> completely ignore the current platform triple

Are you referring to the three `Bundler.current_ruby` predicate methods?  I don't Bundler well enough to know what affects what, but having to force this and that is something many users wouldn't be aware of.  I am an edge case, most people aren't using trunk.

Using my example from above re #5992,, @leoarnold is trying to get an install from 'below', I (using trunk) am trying to get an install from above....

Glad I could help clarify the issue.  Okay to close.
