### ISSUE TITLE
Relax version check to not include patch versions

### ISSUE THREAD

**Issue by mgwidmann** [bundler/bundler#6008]
Its a bit annoying to always be seeing minor version updates cause warnings (for those of us who like to keep clear of warnings). 

For example, bundler now warns twice when you're only 1 patch version behind...

```
$ bundle
The latest bundler is 1.15.4, but you are currently running 1.15.3.
To update, run `gem install bundler`
Warning: the running version of Bundler (1.15.3) is older than the version that created the lockfile (1.15.4). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
```

It would be nice not to include patch versions in these warnings...  It shouldn't be necessary since bundler is using semantic versioning...

**Comment by segiddins** [comment]
Please see https://github.com/bundler/bundler/issues/6004 and https://github.com/bundler/bundler/issues/5143 for existing discussion of this.
