### ISSUE TITLE
bundle install Error

### ISSUE THREAD

**Issue by achtadef** [bundler/bundler#6016]
--- ERROR REPORT TEMPLATE -------------------------------------------------------

- What did you do?

  I ran the command `/usr/bin/bundle install`

- What did you expect to happen?

  I expected Bundler to install the missing gems.  

- What happened instead?

  Instead, what happened was the following error: 

Error details

    Errno::EACCES: Permission denied @ rb_file_s_rename - (/tmp/bundler-compact-index-20170908-27623-12iu6pk/versions, /home/~/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/versions)
      /usr/lib/ruby/2.3.0/fileutils.rb:528:in `rename'
      /usr/lib/ruby/2.3.0/fileutils.rb:528:in `block in mv'
      /usr/lib/ruby/2.3.0/fileutils.rb:1571:in `block in fu_each_src_dest'
      /usr/lib/ruby/2.3.0/fileutils.rb:1587:in `fu_each_src_dest0'
      /usr/lib/ruby/2.3.0/fileutils.rb:1569:in `fu_each_src_dest'
      /usr/lib/ruby/2.3.0/fileutils.rb:517:in `mv'
      /usr/lib/ruby/vendor_ruby/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:55:in `block in update'
      /usr/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
      /usr/lib/ruby/vendor_ruby/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:29:in `update'
      /usr/lib/ruby/vendor_ruby/bundler/vendor/compact_index_client/lib/compact_index_client.rb:65:in `update'
      /usr/lib/ruby/vendor_ruby/bundler/vendor/compact_index_client/lib/compact_index_client.rb:56:in `update_and_parse_checksums!'
      /usr/lib/ruby/vendor_ruby/bundler/fetcher/compact_index.rb:67:in `available?'
      /usr/lib/ruby/vendor_ruby/bundler/fetcher/compact_index.rb:15:in `call'
      /usr/lib/ruby/vendor_ruby/bundler/fetcher/compact_index.rb:15:in `block in compact_index_request'
      /usr/lib/ruby/vendor_ruby/bundler/fetcher.rb:157:in `use_api'
      /usr/lib/ruby/vendor_ruby/bundler/source/rubygems.rb:332:in `block in api_fetchers'
      /usr/lib/ruby/vendor_ruby/bundler/source/rubygems.rb:332:in `select'
      /usr/lib/ruby/vendor_ruby/bundler/source/rubygems.rb:332:in `api_fetchers'
      /usr/lib/ruby/vendor_ruby/bundler/source/rubygems.rb:337:in `block in remote_specs'
      /usr/lib/ruby/vendor_ruby/bundler/index.rb:10:in `build'
      /usr/lib/ruby/vendor_ruby/bundler/source/rubygems.rb:336:in `remote_specs'
      /usr/lib/ruby/vendor_ruby/bundler/source/rubygems.rb:83:in `specs'
      /usr/lib/ruby/vendor_ruby/bundler/lazy_specification.rb:61:in `__materialize__'
      /usr/lib/ruby/vendor_ruby/bundler/spec_set.rb:91:in `block in materialize'
      /usr/lib/ruby/vendor_ruby/bundler/spec_set.rb:88:in `map!'
      /usr/lib/ruby/vendor_ruby/bundler/spec_set.rb:88:in `materialize'
      /usr/lib/ruby/vendor_ruby/bundler/definition.rb:174:in `specs'
      /usr/lib/ruby/vendor_ruby/bundler/definition.rb:162:in `resolve_remotely!'
      /usr/lib/ruby/vendor_ruby/bundler/installer.rb:225:in `resolve_if_need'
      /usr/lib/ruby/vendor_ruby/bundler/installer.rb:78:in `run'
      /usr/lib/ruby/vendor_ruby/bundler/installer.rb:24:in `install'
      /usr/lib/ruby/vendor_ruby/bundler/cli/install.rb:71:in `run'
      /usr/lib/ruby/vendor_ruby/bundler/cli.rb:189:in `install'
      /usr/lib/ruby/vendor_ruby/thor/command.rb:27:in `run'
      /usr/lib/ruby/vendor_ruby/thor/invocation.rb:126:in `invoke_command'
      /usr/lib/ruby/vendor_ruby/thor.rb:359:in `dispatch'
      /usr/lib/ruby/vendor_ruby/bundler/cli.rb:20:in `dispatch'
      /usr/lib/ruby/vendor_ruby/thor/base.rb:440:in `start'
      /usr/lib/ruby/vendor_ruby/bundler/cli.rb:11:in `start'
      /usr/bin/bundle:34:in `block in <main>'
      /usr/lib/ruby/vendor_ruby/bundler/friendly_errors.rb:100:in `with_friendly_errors'
      /usr/bin/bundle:26:in `<main>'

Environment
      
  Bundler   1.13.6
  Rubygems  2.5.2
  Ruby      2.3.3p222 (2016-11-21 revision 0) [x86_64-linux-gnu]
  GEM_HOME  /var/lib/gems/2.3.0
  GEM_PATH  /var/lib/gems/2.3.0:/home/~/.gem/ruby/2.3.0:/usr/lib/x86_64-linux-gnu/rubygems-integration/2.3.0:/usr/share/rubygems-integration/2.3.0:/usr/share/rubygems-integration/all
  Git       not installed
--- TEMPLATE END ----------------------------------------------------------------

**Comment by colby-swandale** [comment]
You're using a fairly old version of Bundler, please update it to the latest version.

**Comment by achtadef** [comment]
@colby-swandale how should I do this?
"_Bundle install_ " should install all missing gems. But it's not working.

**Comment by colby-swandale** [comment]
You can install the latest stable version of Bundler with `gem install bundler`

**Comment by achtadef** [comment]
Bundler seems to be installed correctly, but as soon as i run "_bundle install_" i got the same error message
$ sudo gem install bundler
[sudo] password for xxxxxx: 
Successfully installed bundler-1.15.4
Parsing documentation for bundler-1.15.4
Done installing documentation for bundler after 4 seconds
1 gem installed

**Comment by colby-swandale** [comment]
what's the output of `bundle env`?

**Comment by achtadef** [comment]
$ bundle env
Environment

    Bundler   1.13.6
    Rubygems  2.5.2
    Ruby      2.3.3p222 (2016-11-21 revision 0) [x86_64-linux-gnu]
    Git       not installed

Bundler settings

    path
      Set for your local app (/home/takou/employees/.bundle/config): "path"
      Set for the current user (/home/takou/.bundle/config): "path"
    disable_shared_gems
      Set for your local app (/home/takou/employees/.bundle/config): "true"
      Set for the current user (/home/takou/.bundle/config): "true"

Gemfile

    source 'https://rubygems.org'
    
    
    # Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
    gem 'rails', '4.2.7.1'
    # Use sqlite3 as the database for Active Record
    gem 'sqlite3'
    # Use SCSS for stylesheets
    gem 'sass-rails', '~> 5.0'
    # Use Uglifier as compressor for JavaScript assets
    gem 'uglifier', '>= 1.3.0'
    # Use CoffeeScript for .coffee assets and views
    gem 'coffee-rails', '~> 4.1.0'
    # See https://github.com/rails/execjs#readme for more supported runtimes
    # gem 'therubyracer', platforms: :ruby
    
    # Use jquery as the JavaScript library
    gem 'jquery-rails'
    # Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
    gem 'turbolinks'
    # Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
    gem 'jbuilder', '~> 2.0'
    # bundle exec rake doc:rails generates the API under doc/api.
    gem 'sdoc', '~> 0.4.0', group: :doc
    
    # Use ActiveModel has_secure_password
    # gem 'bcrypt', '~> 3.1.7'
    
    # Use Unicorn as the app server
    # gem 'unicorn'
    
    # Use Capistrano for deployment
    # gem 'capistrano-rails', group: :development
    
    group :development, :test do
      # Call 'byebug' anywhere in the code to stop execution and get a debugger console
      gem 'byebug'
    end
    
    group :development do
      # Access an IRB console on exception pages or by using <%= console %> in views
      gem 'web-console', '~> 2.0'
    
      # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
      gem 'spring'
    end

Gemfile.lock

    GEM
      remote: https://rubygems.org/
      specs:
        actionmailer (4.2.7.1)
          actionpack (= 4.2.7.1)
          actionview (= 4.2.7.1)
          activejob (= 4.2.7.1)
          mail (~> 2.5, >= 2.5.4)
          rails-dom-testing (~> 1.0, >= 1.0.5)
        actionpack (4.2.7.1)
          actionview (= 4.2.7.1)
          activesupport (= 4.2.7.1)
          rack (~> 1.6)
          rack-test (~> 0.6.2)
          rails-dom-testing (~> 1.0, >= 1.0.5)
          rails-html-sanitizer (~> 1.0, >= 1.0.2)
        actionview (4.2.7.1)
          activesupport (= 4.2.7.1)
          builder (~> 3.1)
          erubis (~> 2.7.0)
          rails-dom-testing (~> 1.0, >= 1.0.5)
          rails-html-sanitizer (~> 1.0, >= 1.0.2)
        activejob (4.2.7.1)
          activesupport (= 4.2.7.1)
          globalid (>= 0.3.0)
        activemodel (4.2.7.1)
          activesupport (= 4.2.7.1)
          builder (~> 3.1)
        activerecord (4.2.7.1)
          activemodel (= 4.2.7.1)
          activesupport (= 4.2.7.1)
          arel (~> 6.0)
        activesupport (4.2.7.1)
          i18n (~> 0.7)
          json (>= 1.7.7)
          minitest (~> 5.1)
          thread_safe (~> 0.3, >= 0.3.4)
          tzinfo (~> 1.1)
        arel (6.0.3)
        binding_of_caller (0.7.2)
          debug_inspector (>= 0.0.1)
        builder (3.2.2)
        byebug (5.0.0)
          columnize (= 0.9.0)
        coffee-rails (4.1.0)
          coffee-script (>= 2.2.0)
          railties (>= 4.0.0, < 5.0)
        coffee-script (2.4.1)
          coffee-script-source
          execjs
        coffee-script-source (1.10.0)
        columnize (0.9.0)
        concurrent-ruby (1.0.0)
        debug_inspector (0.0.2)
        erubis (2.7.0)
        execjs (2.6.0)
        globalid (0.3.6)
          activesupport (>= 4.1.0)
        i18n (0.7.0)
        jbuilder (2.3.1)
          activesupport (>= 3.0.0, < 5)
          multi_json (~> 1.2)
        jquery-rails (4.2.1)
          rails-dom-testing (>= 1, < 3)
          railties (>= 4.2.0)
          thor (>= 0.14, < 2.0)
        json (1.8.3)
        loofah (2.0.3)
          nokogiri (>= 1.5.9)
        mail (2.6.4)
          mime-types (>= 1.16, < 4)
        mime-types (2.6.1)
        minitest (5.9.0)
        multi_json (1.11.2)
        nokogiri (1.6.8.1)
        rack (1.6.4)
        rack-test (0.6.3)
          rack (>= 1.0)
        rails (4.2.7.1)
          actionmailer (= 4.2.7.1)
          actionpack (= 4.2.7.1)
          actionview (= 4.2.7.1)
          activejob (= 4.2.7.1)
          activemodel (= 4.2.7.1)
          activerecord (= 4.2.7.1)
          activesupport (= 4.2.7.1)
          bundler (>= 1.3.0, < 2.0)
          railties (= 4.2.7.1)
          sprockets-rails
        rails-deprecated_sanitizer (1.0.3)
          activesupport (>= 4.2.0.alpha)
        rails-dom-testing (1.0.6)
          activesupport (>= 4.2.0.beta, < 5.0)
          nokogiri (~> 1.6.0)
          rails-deprecated_sanitizer (>= 1.0.1)
        rails-html-sanitizer (1.0.3)
          loofah (~> 2.0)
        railties (4.2.7.1)
          actionpack (= 4.2.7.1)
          activesupport (= 4.2.7.1)
          rake (>= 0.8.7)
          thor (>= 0.18.1, < 2.0)
        rake (10.5.0)
        rdoc (4.2.1)
        sass (3.4.23)
        sass-rails (5.0.6)
          railties (>= 4.0.0, < 6)
          sass (~> 3.1)
          sprockets (>= 2.8, < 4.0)
          sprockets-rails (>= 2.0, < 4.0)
          tilt (>= 1.1, < 3)
        sdoc (0.4.1)
          json (~> 1.7, >= 1.7.7)
          rdoc (~> 4.0)
        spring (1.3.6)
        sprockets (3.7.0)
          concurrent-ruby (~> 1.0)
          rack (> 1, < 3)
        sprockets-rails (2.3.2)
          actionpack (>= 3.0)
          activesupport (>= 3.0)
          sprockets (>= 2.8, < 4.0)
        sqlite3 (1.3.11)
        thor (0.19.1)
        thread_safe (0.3.5)
        tilt (2.0.1)
        turbolinks (2.5.3)
          coffee-rails
        tzinfo (1.2.2)
          thread_safe (~> 0.1)
        uglifier (2.7.2)
          execjs (>= 0.3.0)
          json (>= 1.8.0)
        web-console (2.2.1)
          activemodel (>= 4.0)
          binding_of_caller (>= 0.7.2)
          railties (>= 4.0)
          sprockets-rails (>= 2.0, < 4.0)
    
    PLATFORMS
      ruby
    
    DEPENDENCIES
      byebug
      coffee-rails (~> 4.1.0)
      jbuilder (~> 2.0)
      jquery-rails
      rails (= 4.2.7.1)
      sass-rails (~> 5.0)
      sdoc (~> 0.4.0)
      spring
      sqlite3
      turbolinks
      uglifier (>= 1.3.0)
      web-console (~> 2.0)
    
    BUNDLED WITH
       1.13.6

**Comment by achtadef** [comment]
$ sudo bundle --path
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your bundle as root
will break this application for all non-root users on this machine.
Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Using rake 10.5.0
Using i18n 0.7.0
Using json 1.8.3
Using minitest 5.9.0
Using thread_safe 0.3.5
Using builder 3.2.2
Using erubis 2.7.0
Your Gemfile.lock is corrupt. The following gem is missing from the DEPENDENCIES section: 'mini_portile2'

this is  what i get trying to install the missing gem
$ sudo gem install 'mini_portile2'
Successfully installed mini_portile2-2.2.0
Parsing documentation for mini_portile2-2.2.0
Done installing documentation for mini_portile2 after 0 seconds
1 gem installed

It did not solve the problem. Gem is still missing after i get the installation confirmation _:(

**Comment by colby-swandale** [comment]
You will need need to fix the corrupt Gemfile.lock issue by deleting it and re-run `bundle install`

**Comment by colby-swandale** [comment]
I'm closing this for now. If you're still experiencing your original issue don't be afraid to re-open this ticket.
