### ISSUE TITLE
Can't find gem after installing it

### ISSUE THREAD

**Issue by djcaesar9114** [bundler/bundler#6019]
Hello,
I successfully installed bundler (first 2.0.0.dev, then 1.16.0.pre.2 after having removed 2.0.0), and then I wanted to install the rails gem, but I've got this error:
`Error: Could not find a valid gem 'bundler' (>= 1.3.0) in any repository`
How can it be possible as `gem list` shows that bundler gem is correctly installed?
Thanks.

**Comment by segiddins** [comment]
Can you please share the information requested in http://bundler.io/doc/contributing/issues.html#reporting-unresolved-problems? Thanks!

**Comment by colby-swandale** [comment]
I'm closing this for now. If you're still experiencing your original issue don't be afraid to re-open this ticket.
