### ISSUE TITLE
Inconsistent lock file update on `bundle check`

### ISSUE THREAD

**Issue by hurricup** [bundler/bundler#6026]
Happens on bundler 1.15+, at least on windows 10 (seems mac too)

To reproduce:
1. Create some ruby project with a `Gemfile`
2. run `bundle install`
3. `Gemfile.lock` being created with resolved dependencies
4. Edit `Gemfile` and add some additional gem installed in the system
5. run `bundle check`
6. You'll get message `resolving dependencies... satisfied` and `Gemfile.lock` is updated with additional dependencies. This is cool.
7. Edit `Gemfile` and comment the gem you've added in the p.4
8. run `bundle check`
9. You'll get satisfied message and `Gemfile.lock` stays as it was, with commented dependency and this is not really cool.

Prior to 1.15, `bundle check` seems asks to run `bundle install` on every `Gemfile` change, even if all gems are actually installed on the local machine.

**Comment by colby-swandale** [comment]
Can you please attach the output of `bundle env` that has a Gemfile & Gemfile.lock which has this issue.

**Comment by hurricup** [comment]
Sure thing. You may see commented 'puppet' gem as an experiment.

[bundle_env.txt](https://github.com/bundler/bundler/files/1296056/bundle_env.txt)

**Comment by segiddins** [comment]
> You'll get satisfied message and Gemfile.lock stays as it was, with commented dependency and this is not really cool.

Stupid question, but why isn't it cool? Presumably running `bundle exec` will still succeed, and isn't that what `bundle check` is trying to answer?

**Comment by hurricup** [comment]
@segiddins not so stupid :)
`bundle check` being used for automation in IDE, like: when `Gemfile` was modified, run `bundle check` and collect dependencies from the lockfile (or run `bundle install` first if necessary). prior to 1.15 - `bundle install` been executed as requested by `bundle check` on any `Gemfile` modification and lock file was up to date. But now it says ok, but dependencies list is not :)

**Comment by segiddins** [comment]
Why is the dependencies list not OK? Running a `bundle exec` should be able to rewrite the lockfile exactly as `bundle check` did, and everything should still work the same?

**Comment by hurricup** [comment]
Because for IDE it looks like commented gem and it's dependencies are still in project and it may try to execute something, like `bundle exec rubocop` for example (where rubocop is commented gem)

**Comment by docljn** [comment]
Hello the team. As part of code triage I'm looking at old open issues and trying to understand what the next steps should be.

@segiddins and @hurricup my understanding is that `bundle check` confirms that the dependencies of the Gemfile are satisfied, where `bundle install` rewrites the Gemfile.lock to match the current Gemfile.

Is this issue still relevant?  Thanks.

**Comment by deivid-rodriguez** [comment]
Hi!

I don't think this is an issue, the `bundle check` behavior described in this ticket seems correct to me, like @segiddins pointed out.

**Comment by docljn** [comment]
Thank you @deivid-rodriguez - are you able to close this issue, then?
