### ISSUE TITLE
Git error when running Bundler from git checkout

### ISSUE THREAD

**Issue by indirect** [bundler/bundler#6029]
When running Bundler from a git checkout, as described in [SETUP.md](https://github.com/bundler/bundler/blob/master/doc/development/SETUP.md#development-setup), all commands print a git error.

Here's an example:

```
$ dbundle -v
fatal: Not a git repository (or any of the parent directories): .git
2.0.0.dev
```

The git error is coming from the gemspec, where we shell out to git:

https://github.com/bundler/bundler/blob/master/bundler.gemspec#L46

Git assumes that commands should run in the current directory, and so the gemspec's git command is running in the wrong place. To fix this, we should use the git option `-C` to pass the directory containing the gemspec file to the git command.

**Comment by arbonap** [comment]
👋🏽 I'd love to work on this and help out.

**Comment by colby-swandale** [comment]
@arbonap sure, let us know if you need any help solving this issue

**Comment by olleolleolle** [comment]
@arbonap This issue here, #6053 fixes it, does it not?
