### ISSUE TITLE
Outdated version check causes bundle install to fail on FIPS enabled systems

### ISSUE THREAD

**Issue by patrickwilkes** [bundler/bundler#6032]
I'm currently trying to get Rails apps installed on a FIPS enabled server, and appreciate the efforts that you've made recently to avoid using MD5 hashes (#4989 and follow-up #5433, along with recent refactor 6e1506ff8cc7393111267c3c5a0a29f8ecb4ecaa).

However the outdated version check that you introduced in 1.15.0 (1e05d24050b4177e9a8001b7c1083d713b474faf) is directly using the CompactIndex, and this causes bundle install to fail when FIPS is enabled.

Once I'd figured this out it was easy to fix using the disable_version_check setting (and it makes sense to turn this off anyway in my case).

I wonder though if you'd consider saving others this small pain by skipping the check regardless of the setting on FIPS enabled systems?

Many thanks.

**Comment by indirect** [comment]
That seems reasonable, and we should probably have the entire compact index source say that it is not available on FIPS systems
