### ISSUE TITLE
Rails 5 issue nokogiri (1.6.8) 

### ISSUE THREAD

**Issue by akshay18496** [bundler/bundler#6034]
C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/cache/nokogiri-1.6.8-x86-mingw32.gem.
It may be corrupted.
An error occurred while installing nokogiri (1.6.8), and Bundler cannot
continue.
Make sure that `gem install nokogiri -v '1.6.8'` succeeds before bundling.

In Gemfile:
  activeadmin was resolved to 1.0.0.pre4, which depends on
    rails was resolved to 5.0.0, which depends on
      actioncable was resolved to 5.0.0, which depends on
        actionpack was resolved to 5.0.0, which depends on
          actionview was resolved to 5.0.0, which depends on
            rails-dom-testing was resolved to 2.0.1, which depends on
              nokogiri

**Comment by colby-swandale** [comment]
Hi, `nokogiri-1.6.8-x86-mingw32.gem` may have not been downloaded correctly, you will need to remove it and make sure that bundler is able to download the correct file incase you have a proxy or firewall.

**Comment by colby-swandale** [comment]
ping @akshay18496 were you able to resolve your issue?

**Comment by colby-swandale** [comment]
I'm closing this for now. If you're still experiencing your original issue don't be afraid to re-open this ticket.
