### ISSUE TITLE
Error when trying to install gem 'pg'. Please help

### ISSUE THREAD

**Issue by baryskhanbimat** [bundler/bundler#6035]
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.3.0/gems/pg-0.21.0/ext
/usr/bin/ruby2.3 -r ./siteconf20170916-11128-1ftect8.rb extconf.rb
checking for pg_config... yes
Using config values from /usr/bin/pg_config
You need to install postgresql-server-dev-X.Y for building a server-side extension or libpq-dev for building a
client-side application.
You need to install postgresql-server-dev-X.Y for building a server-side extension or libpq-dev for building a
client-side application.
checking for libpq-fe.h... no
Can't find the 'libpq-fe.h header
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

**Comment by colby-swandale** [comment]
Hi, unfortunately this is an issue with the `pg` gem itself and not with bundler itself. I recommend following the instructions in the debug output.

```
You need to install postgresql-server-dev-X.Y for building a server-side extension or libpq-dev 
```
