### ISSUE TITLE
bundler warns about latest version and suggests installing pre-release

### ISSUE THREAD

**Issue by jeffb-stell** [bundler/bundler#6040]
When running bundle install, I am seeing:

> The latest bundler is 1.16.0.pre.2, but you are currently running 1.15.4.
> To update, run `gem install bundler --pre`

It seems bad to encourage people on the latest stable bundler version to update to a prerelease. If this was done to get more eyes on prerelease, could the message be enhanced to indicate it IS a prerelease and should maybe not be done on production systems?

**Comment by arbonap** [comment]
👋🏽 @jeffb-stell this has been discussed in detail in [this closed issue](https://github.com/bundler/bundler/issues/6004). A PR has been merged disabling this warning. Feel free to `bundle config disable_version_check true` to ignore the message for now.

**Comment by radar** [comment]
@arbonap is right. See #6004 for discussion.
