### ISSUE TITLE
1.16.0.pre.1 and .pre.2 sometimes do not generate binstubs on `bundle install`

### ISSUE THREAD

**Issue by doudou** [bundler/bundler#6046]
Can be reproduced with: [bundler_bug.zip](https://github.com/bundler/bundler/files/1314511/bundler_bug.zip). One would need to change the path to the ruby executable and the ruby version at the top of the file (ruby version is the version used by bundler in the gem path, e.g. `2.3.0` for `ruby/2.3.0/`).

If you run the shell script the first time, it will setup a self-contained gem home (in `env/gems`) and install bundler in it, then run `bundle install`. The first time, the binstubs are generated as expected in `env/bundle_dir/bin`.

However, if one `rm -rf env/bundle_dir` and re-run the script, the install does not re-generate the stubs. 1.15.4 does generate them. Neither 1.16.0.pre.1 or .pre.2 do.

**Comment by colby-swandale** [comment]
>  Neither 1.15.0.pre.1 or .pre.2

Do you mean 1.16.pre.1 and 1.16.pre.2?

**Comment by doudou** [comment]
Ah ... yes .. edited to fix.

**Comment by segiddins** [comment]
Does running `bundle pristine` fix the issue for you?

**Comment by doudou** [comment]
No. The binstubs folder remains empty

**Comment by doudou** [comment]
Sorry, that's inexact. There is one binstub in there: `bundle`.

**Comment by doudou** [comment]
Waitaminute.

Not true, running pristine with 1.16.pre.2 does re-add the binstubs.

I don't know if it helps finding the source, but running `pristine` using 1.15.4, on the install made with 1.16.pre.2 does *not* reestablish the binstubs.

**Comment by doudou** [comment]
In summary:

1. Install with 1.15.4 binstubs are present. Delete `bundle_dir` folder, install again with 1.15.4: **binstubs are present**
2. Install with 1.16.pre.2, binstubs are present. Delete `bundle_dir` folder, install again with 1.16.pre.2: **binstubs are missing**, only `bundle` is present.
   - running `bundle pristine` using 1.16.pre.2 re-adds the binstubs.
   - running `bundle pristine` using 1.15.4 does **not** re-add the binstubs

**Comment by doudou** [comment]
Ping

**Comment by segiddins** [comment]
I’m _tempted_ to say this isn’t an issue, and to use pristine if you’ve manually mucked with gem installations (no different than if you’d deleted any other file in the gem), but I suppose I could be convinced otherwise

**Comment by doudou** [comment]
I can understand the temptation ...

However, the whole things looks mushy to me. First, bundler does recreate the `bundle` binstub (the only one it does recreate). Moreover, I don't touch the gems, only the binstub dir (and nothing else, everything else is left as-is).

My use-case here is to make sure that obsolete binstubs are removed. Having to do a full pristine just for that sounds like a whole lot of work.

Finally, this breaks backward compatibility, and so far nobody seem to have an idea why ...

**Comment by segiddins** [comment]
Oh I know exactly why it happened, I made the PR that made the change because it lets “no-op” bundle installs be a lot faster

**Comment by doudou** [comment]
Could you give me a link to that PR ? At least I know what I'm up against ... :P

**Comment by segiddins** [comment]
I thought it was https://github.com/bundler/bundler/pull/5844 but I'm no longer sure... I'll look into this when I get a cache

**Comment by colby-swandale** [comment]
@doudou do you know if this issue still occurs on the latest version of Bundler?
