### ISSUE TITLE
Bundler.settings.without not found in 1.16.pre.2

### ISSUE THREAD

**Issue by tdtds** [bundler/bundler#6047]
I use `Bundler.settings.without` in 1.15 but 1.16.pre.2 does not have this method. Is this the intended incompatibility?

I can use `[:without]` instead, but this is also incompatible. When '--without ' option isn't specified, 1.15 returns `nil`, but 1.16.pre.2 returns empty Array.

```
# in 1.15
Bundler.settings.without # => []
Bundler.settings[:without] # => nil
```

```
# in 1.16.pre.2
Bundler.settings.without # => NoMethodError: undefined method `without'
Bundler.settings[:without] # => []
```

**Comment by colby-swandale** [comment]
`Bundler.settings.without` and `Bundler.settings.with` was considered a private API and we offered no guarantees to it's stability.

It was removed in https://github.com/bundler/bundler/commit/8ccf49c3b4a086f1e0cad2130dc30c04304175b7#diff-75219bd6bc0defc0e7f4ba322d92f950

**Comment by colby-swandale** [comment]
Same with `Bundler.settings[]`

**Comment by tdtds** [comment]
"Same with `Bundler.settings[]`"? How can I get the value of `with` and `without` options?

**Comment by colby-swandale** [comment]
The only supported way to get the `with` and `without` settings is by running `bundle config`

**Comment by tdtds** [comment]
Umm... OK, I will use `settings[]` in my own risk. Thank you.
