### ISSUE TITLE
bundle install fail for trying to use jekyll 

### ISSUE THREAD

**Issue by Caleb-Tan** [bundler/bundler#6051]
here is the issue:

Errno::ENOENT: No such file or directory - git clone "git://github.com/sinatra/
inatra.git" "C:/Ruby23-x64/lib/ruby/gems/2.3.0/cache/bundler/git/sinatra-b52589
ea06b9fac17e190c37b6500b2c2378e0b" --bare --no-hardlinks --quiet
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/source/git/
it_proxy.rb:162:in ``'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/source/git/
it_proxy.rb:162:in `block (2 levels) in git'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/source/git/
it_proxy.rb:239:in `block in capture_and_filter_stderr'
  C:/Ruby23-x64/lib/ruby/2.3.0/tempfile.rb:295:in `open'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/source/git/
it_proxy.rb:237:in `capture_and_filter_stderr'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/source/git/
it_proxy.rb:162:in `block in git'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/shared_help
rs.rb:73:in `with_clean_git_env'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/source/git/
it_proxy.rb:161:in `git'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/source/git/
it_proxy.rb:153:in `block in git_retry'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/retry.rb:39
in `run'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/retry.rb:29
in `attempt'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/source/git/
it_proxy.rb:152:in `git_retry'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/source/git/
it_proxy.rb:104:in `checkout'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/source/git.
b:306:in `fetch'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/source/git.
b:160:in `specs'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/definition.
b:246:in `block (2 levels) in index'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/definition.
b:244:in `each'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/definition.
b:244:in `block in index'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/index.rb:10
in `build'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/definition.
b:241:in `index'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/definition.
b:235:in `resolve'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/definition.
b:159:in `specs'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/definition.
b:147:in `resolve_remotely!'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/installer.r
:226:in `resolve_if_need'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/installer.r
:78:in `run'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/installer.r
:24:in `install'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/cli/install
rb:68:in `run'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/cli.rb:188:
n `block in install'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/settings.rb
92:in `temporary'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/cli.rb:187:
n `install'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/vendor/thor
lib/thor/command.rb:27:in `run'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/vendor/thor
lib/thor/invocation.rb:126:in `invoke_command'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/vendor/thor
lib/thor.rb:387:in `dispatch'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/cli.rb:22:i
 `dispatch'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/vendor/thor
lib/thor/base.rb:466:in `start'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/cli.rb:13:i
 `start'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/exe/bundle:30:in `block
in <top (required)>'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/friendly_er
ors.rb:121:in `with_friendly_errors'
  C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/exe/bundle:22:in `<top
required)>'
  C:/Ruby23-x64/bin/bundle:22:in `load'
  C:/Ruby23-x64/bin/bundle:22:in `<main>'
```

## Environment

```
Bundler   1.15.4
Rubygems  2.5.2
Ruby      2.3.3p222 (2016-11-21 revision 56859) [x64-mingw32]
GEM_HOME  C:/Ruby23-x64/lib/ruby/gems/2.3.0
GEM_PATH  C:/Ruby23-x64/lib/ruby/gems/2.3.0;C:/Users/engtechp7/.gem/ruby/2.3.0
Git       not installed
Platform  x64-mingw32
OpenSSL   OpenSSL 1.0.2j  26 Sep 2016
```

## Gemfile

### Gemfile

```ruby
source "https://rubygems.org"
ruby RUBY_VERSION

# Hello! This is where you manage which Jekyll version is used to run.
# When you want to use a different version, change it below, save the
# file and run `bundle install`. Run Jekyll with `bundle exec`, like so:
#
#     bundle exec jekyll serve
#
# This will help ensure the proper Jekyll version is running.
# Happy Jekylling!
gem "jekyll", "3.3.0"

# This is the default theme for new Jekyll sites. You may change this to anythi
g you like.
gem "minima", "~> 2.0"


gem "rack"
gem "sinatra", github: "sinatra"

# If you want to use GitHub Pages, remove the "gem "jekyll"" above and
# uncomment the line below. To upgrade, run `bundle update github-pages`.
# gem "github-pages", group: :jekyll_plugins

# If you have any plugins, put them here!
group :jekyll_plugins do
   gem "jekyll-feed", "~> 0.6"
end
```

### Gemfile.lock

```
GIT
  remote: git://github.com/sinatra/sinatra.git
  revision: 004daf4922af6ee7a7a87982f3040768e428209e
  specs:
    rack-protection (2.0.0.beta2)
      rack
    sinatra (2.0.0.beta2)
      mustermann (= 1.0.0.beta2)
      rack (~> 2.0)
      rack-protection (= 2.0.0.beta2)
      tilt (~> 2.0)

GEM
  remote: https://rubygems.org/
  specs:
    addressable (2.5.0)
      public_suffix (~> 2.0, >= 2.0.2)
    colorator (1.1.0)
    ffi (1.9.14)
    ffi (1.9.14-x64-mingw32)
    ffi (1.9.14-x86-mingw32)
    forwardable-extended (2.6.0)
    jekyll (3.3.0)
      addressable (~> 2.4)
      colorator (~> 1.0)
      jekyll-sass-converter (~> 1.0)
      jekyll-watch (~> 1.1)
      kramdown (~> 1.3)
      liquid (~> 3.0)
      mercenary (~> 0.3.3)
      pathutil (~> 0.9)
      rouge (~> 1.7)
      safe_yaml (~> 1.0)
    jekyll-feed (0.8.0)
      jekyll (~> 3.3)
    jekyll-sass-converter (1.4.0)
      sass (~> 3.4)
    jekyll-watch (1.5.0)
      listen (~> 3.0, < 3.1)
    kramdown (1.12.0)
    liquid (3.0.6)
    listen (3.0.8)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
    mercenary (0.3.6)
    minima (2.0.0)
    mustermann (1.0.0.beta2)
    pathutil (0.14.0)
      forwardable-extended (~> 2.6)
    public_suffix (2.0.4)
    rack (2.0.1)
    rb-fsevent (0.9.8)
    rb-inotify (0.9.7)
      ffi (>= 0.5.0)
    rouge (1.11.1)
    safe_yaml (1.0.4)
    sass (3.4.22)
    tilt (2.0.5)

PLATFORMS
  ruby
  x64-mingw32
  x86-mingw32

DEPENDENCIES
  jekyll (= 3.3.0)
  jekyll-feed (~> 0.6)
  minima (~> 2.0)
  rack
  sinatra!

RUBY VERSION
   ruby 2.3.1p112

BUNDLED WITH
   1.15.1
```

**Comment by colby-swandale** [comment]
HI, Bundler is trying to clone a git repository but it's unable to find git. Do you have git installed?

**Comment by Caleb-Tan** [comment]
Oh right,that may be the issue. I have git installed but I will check to
see if it's added to path, because I normally use git bash to use git,
instead of the cmd

**Comment by colby-swandale** [comment]
I'm closing this for now. If you're still experiencing your original issue don't be afraid to re-open this ticket.

**Comment by ajwann** [comment]
@Caleb-Tan, how did you originally install Ruby onto your Windows machine? I'd like to install it the same way to see if I can recreate your issue.
