### ISSUE TITLE
Bundler git check not working on windows

### ISSUE THREAD

**Issue by colby-swandale** [bundler/bundler#6052]
Bundler's git check does not appear to be working on the Windows platform. A few recent issues show that Bundler is printing exceptions to users rather then the helpful error messages.

See: #6051 #6033

**Comment by ashmaroli** [comment]
could it be because `GitNotInstalledError` is being `rescue-d`..?
https://github.com/bundler/bundler/blob/c3fe3e6f2a93c30869c70ea17a10041a9b2d27dd/lib/bundler/env.rb#L88-L92

**Comment by ajwann** [comment]
I can take a crack at this on my Windows partition.

**Comment by ajwann** [comment]
So far I am unable to recreate the issue. I have installed ruby through chocolaty and I'm on bundler 1.15.4, the same Bundler version that was reportedly throwing the exception in #6051.

When I try to install ```sinatra``` from master, similar to #6051, without git installed, I see:
```
The git source `git://github.com/sinatra/sinatra.git` uses the `git` protocol, which transmits data without encryption.
Disable this warning with `bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data s
ecure.
You need to install git to be able to use gems from git repositories. For help
installing git, please refer to GitHub's tutorial at
https://help.github.com/articles/set-up-git
```

It may be an issue with how @Caleb-Tan's development environment was set up in #6051. I'll try and configure my environment as closely to his as possible, and see if I can't reproduce the issue.

**Comment by ajwann** [comment]
Even after installing [Ruby 2.3.3 (x64)](https://dl.bintray.com/oneclick/rubyinstaller/rubyinstaller-2.3.3-x64.exe) through the Ruby-installer, I get the correct Bundler error I previously pasted above. 

My environmnet setup is identical to the setup in #6051:
```
Bundler 1.15.4
Rubygems 2.5.2
Ruby 2.3.3p222 (x64)- this time installed via the Ruby installer, not Choclatey
```

**Comment by ajwann** [comment]
Issue #6033 contains a similar environment setup, and also looks like Ruby was installed via the Ruby Installer. The main difference is that Ruby 2.4.0 was used instead of Ruby 2.3.3. 

I can't reproduce the issue with either environment setup. I get the correct Bundler error any time I try to install a gem from git.
