### ISSUE TITLE
Official docker image

### ISSUE THREAD

**Issue by Webysther** [bundler/bundler#6062]
Bundler organization maintain any docker image on hub.docker.com?

**Comment by RochesterinNYC** [comment]
What would you expect such a Bundler docker image to contain or do?

**Comment by Webysther** [comment]
Like [composer](https://hub.docker.com/_/composer/) to use to execute [inside image](https://hub.docker.com/r/dynaum/ruby-bundler-node/) with bash to build code or to [create a enviroment](https://hub.docker.com/r/webfatorial/bundler/). Will be very nice to have a existing official one.

**Comment by colby-swandale** [comment]
Thanks for the suggestion but the core team is not interested in maintaining an offical bundler docker image. I suggest just using the ruby images instead.

**Comment by hurricup** [comment]
@Webysther just curious, are you suggesting to maintain images for all ruby x bundler combinations?

**Comment by Webysther** [comment]
No, because is possible use [docker multi-stage](https://docs.docker.com/engine/userguide/eng-image/multistage-build/).
