### ISSUE TITLE
Problem installing the gem bundler

### ISSUE THREAD

**Issue by ogdibie** [bundler/bundler#6064]
When I run gem bundler install, I get the following response:

ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied @ dir_s_mkdir - /var/lib/gems/2.4.0

Any one has a idea on what I can do?

**Comment by colby-swandale** [comment]
You're trying to install gems where the user does not have permission to write into. Either change the folder's permissions to allow the user to write to or change the path the gems are being installed into using the `--path` [option](http://bundler.io/v1.15/man/bundle-install.1.html)

**Comment by ogdibie** [comment]
Thanks for the help. I think that was probably the problem. I messed around with it earlier and screwed some stuff over. I ended up removing the ruby and rbenv from my computer and reinstalling it...I got the gem install bundler to work but I am now having another problem installing the bundle for the project I am working on

**Comment by ogdibie** [comment]
I get this error:Could not find diff-lcs-1.3 in any of the sources...The Gemfile .lock looks like this:
EM
  remote: https://rubygems.org/
  specs:
    diff-lcs (1.3)
    rspec (3.6.0)
      rspec-core (~> 3.6.0)
      rspec-expectations (~> 3.6.0)
      rspec-mocks (~> 3.6.0)
    rspec-core (3.6.0)
      rspec-support (~> 3.6.0)
    rspec-expectations (3.6.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.6.0)
    rspec-mocks (3.6.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.6.0)
    rspec-support (3.6.0)

PLATFORMS
  ruby

DEPENDENCIES
  rspec

RUBY VERSION
   ruby 2.4.1p111

BUNDLED WITH
   1.14.6

**Comment by ogdibie** [comment]
GEM* error when I was copy passing..... I says it cannot find the diff-lcs. How can I make it find it?

**Comment by colby-swandale** [comment]
did you run `bundle install`?

**Comment by ogdibie** [comment]
Yes I did...it kept complaining that it could not find some requirements in
my SRC.....I had to install all the gems that I needed manually. I think I
got it to work now.

Thanks

**Comment by colby-swandale** [comment]
I'm closing this for now. If you're still experiencing your original issue don't be afraid to re-open this ticket.
