### ISSUE TITLE
Bundler outputs warnings on STDOUT when it should be on STDERR

### ISSUE THREAD

**Issue by francois** [bundler/bundler#6067]
I ran the following at the shell:

```
$ find $( bundle show activerecord ) -type f -name 'has_and_belongs_to_many_association.rb'
find: --pre`: unknown primary or operator
```

What Bundler returns on STDOUT is more than expected: the message

    /Users/francois/.rvm/gems/ruby-2.3.3/gems/activerecord-5.1.4
    The latest bundler is 1.16.0.pre.2, but you are currently running 1.15.1.
    To update, run `gem install bundler --pre`

This is unexpected, as the warning about an outdated version should not be part of the "useful" output of the command. In the end, I transformed my command to grep active record, which gave me what I wanted, so no harm done, but that was very surprising.

What I expected was:

    STDOUT: /Users/francois/.rvm/gems/ruby-2.3.3/gems/activerecord-5.1.4
    STDERR: The latest bundler is 1.16.0.pre.2, but you are currently running 1.15.1.
    STDERR: To update, run `gem install bundler --pre`

**Comment by colby-swandale** [comment]
Bundler will print errors to stderr in 2.0
