### ISSUE TITLE
Bug in available update warning

### ISSUE THREAD

**Issue by graywolf** [bundler/bundler#6076]
When running `bundle install`, I see

    The latest bundler is 1.16.0.pre.3, but you are currently running 1.15.4.
    To update, run `gem install bundler --pre`

however based on the name I'm assuming the `1.16.0.pre.3` is pre-release version, so the stable release version shouldn't tell user to upgrade to it.

**Comment by segiddins** [comment]
As of 1.16.0.pre.3, the update warning has been completely disabled for the time being. See https://github.com/bundler/bundler/issues/6004 for more of the discussion.
