### ISSUE TITLE
Error Installing appium_lib with Ruby v2.4.2 Due to JSON

### ISSUE THREAD

**Issue by PatrickDuncan** [bundler/bundler#6083]
Hello we're trying to install appium_lib v9.6.1 (bundle install) with Ruby v2.4.2-2 and we're getting an error with json v2.1.0 (and 1.8.7):

<pre>Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/json-2.1.0/ext/json/ext/generator
C:/Ruby24-x64/bin/ruby.exe -r ./siteconf20171006-3700-aias1v.rb extconf.rb
creating Makefile

current directory:
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/json-2.1.0/ext/json/ext/generator
make "DESTDIR=" clean

current directory:
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/json-2.1.0/ext/json/ext/generator
make "DESTDIR="
generating generator-x64-mingw32.def
compiling generator.c
Makefile:241: recipe for target 'generator.o' failed
process_begin: CreateProcess(NULL, x86_64-w64-mingw32-gcc -I.
-IC:/Ruby24-x64/include/ruby-2.4.0/x64-mingw32
-I/C/Ruby24-x64/include/ruby-2.4.0/ruby/backward
-I/C/Ruby24-x64/include/ruby-2.4.0 -I. -DJSON_GENERATOR -D_FORTIFY_SOURCE=2
-D__USE_MINGW_ANSI_STDIO=1 -DFD_SETSIZE=2048 -D_WIN32_WINNT=0x0501
-D__MINGW_USE_VC2005_COMPAT -D_FILE_OFFSET_BITS=64 -march=x86-64 -mtune=generic
-O2 -pipe -o generator.o -c generator.c, ...) failed.
make (e=2): The system cannot find the file specified.

make: *** [generator.o] Error 2

make failed, exit code 2

Gem files will remain installed in
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/json-2.1.0 for inspection.
Results logged to
C:/Ruby24-x64/lib/ruby/gems/2.4.0/extensions/x64-mingw32/2.4.0/json-2.1.0/gem_make.out

An error occurred while installing json (2.1.0), and Bundler cannot continue.
Make sure that `gem install json -v '2.1.0'` succeeds before bundling.

In Gemfile:
  appium_lib was resolved to 9.6.1, which depends on
    json
</pre>

We've followed https://github.com/bundler/bundler/issues/4462 to no avail.

Right now we're using Ruby 2.3.3 and everything is running smoothly,

**Comment by colby-swandale** [comment]
I don't think this issue relates to Bundler, are you able to install the json gem with `gem install json -v '2.1.0'`?

**Comment by PatrickDuncan** [comment]
@colby-swandale I was thinking that as well, but I wanted to follow suit with #4462

**Comment by colby-swandale** [comment]
#4462 isn't really a bundler issue either so we're not really able to help unless bundler is specifically the reason why the gem cannot be installed.

**Comment by colby-swandale** [comment]
@PatrickDuncan Were you able to resolve your issue?

**Comment by PatrickDuncan** [comment]
I will post it in the json repo. Thanks.
