### ISSUE TITLE
insecure defaults are not a good default.

### ISSUE THREAD

**Issue by r-obert** [bundler/bundler#6085]
```
The git source `git://github.com/pry/pry.git` uses the `git` protocol, 
which transmits data without encryption. Disable this warning with 
`bundle config git.allow_insecure true`, or switch to the `https` 
protocol to keep your data secure.
```

It shouldn't be opt-in. It should be the default.

Gemfile:
```ruby
gem "pry", github: "pry/pry"
```

**Comment by colby-swandale** [comment]
We're unable to change the GitHub url in bundler 1 due to strict backwards compatibility. In bundler 2 we're removing the `github` option in favour of the `git`option or you can define your own GitHub option with (which you can currently do in bundler 1):

```
git_source(:github) do |repo_name|
  repo_name = “#{repo_name}/#{repo_name}” unless repo_name.include(“/“)
  “https://github.com/#{repo_name}.git"
end
```

**Comment by r-obert** [comment]
Thanks. In the end I used the long form URL (`https://..`) but I think this was a bad choice, even with backwards compatibility in mind. It makes MITM attacks a real possibly with bundler + git. It feels like bundler and rubygems in general do not want to move away from a centralised platform (rubygems). Well, here is hoping for the future.

**Comment by r-obert** [comment]
By the way, the "centralised platform" thing is an issue because of the difficultly in removing code from there. Once it's added, it's an uphill battle to remove it. That's why I generally do not use it. Anyway, not relevant here. Thank you for the update.
