### ISSUE TITLE
Bundler encourages upgrading to pre-release versions

### ISSUE THREAD

**Issue by attilagyorffy** [bundler/bundler#6087]
Currently during any `bundle` invocation, bundler encourages its users to upgrade to pre-release software:

```
❯ bundle info nokogiri
The latest bundler is 1.16.0.pre.3, but you are currently running 1.15.4.
To update, run `gem install bundler --pre`
```

I really love bundler and I think it's far superior to a lot other package and dependency mangers but I'm concerned that it may give beginners the wrong idea to upgrade software that is considered unstable. What do you think?

**Comment by segiddins** [comment]
This has been disabled by default in 1.16.0.pre.3. I’m on my phone so I can’t link, but there are several other issues about this.

**Comment by colby-swandale** [comment]
See #6031

**Comment by mathieujobin** [comment]
Thank you !
