### ISSUE TITLE
bundle exec rescues 'SignalException' and aborts

### ISSUE THREAD

**Issue by dekellum** [bundler/bundler#6090]
This was first reported in puma/puma#1438. As of puma 3.10.0, SIGTERM handling was changed (in puma/puma#1337) to properly report the termination-by-SIGTERM status back to the parent process. This is accomplished by re-raising a SignalException. Unfortunately when puma is run via `bundle exec puma` and `bundle exec` uses CLI::Exec#kernel_load, the SignalException is rescued by bundler, logged to stderr, and the process is aborted via Kernel::abort (exit status 1). I believe that minimally, kernel_load should not be rescuing SignalException.  

An interesting possible workaround for this is that a `bundle binstub` produced wrapper does not include the same error handling as `CLI::Exec#kernel_load` and thus does not exhibit the same problem.

This can be reproduced via a simple, public, puma test app:

https://github.com/dekellum/lionfish

A Gemfile and Gemfile.lock is checked in.

My testing bundler version: 1.15.1

Below is log output what happens when the puma process is signaled with SIGTERM for a graceful restart.  Note the "bundle: failed to load command" output and stack trace from `bundle exec` Here exit status 1 is interpreted as a failure by systemd. From the original puma report (see above) this similarly confuses Heroku. 

~~~ txt
Oct 11 09:51:34 klein systemd[826]: Stopping Lionfish (Puma) HTTP Server...
Oct 11 09:51:34 klein bundle[25925]: - Gracefully stopping, waiting for requests to finish
Oct 11 09:51:34 klein bundle[25925]: === puma shutdown: 2017-10-11 09:51:34 -0700 ===
Oct 11 09:51:34 klein bundle[25925]: - Goodbye!
Oct 11 09:51:34 klein bundle[25925]: bundler: failed to load command: puma (/home/david/.gem/ruby/2.3.0/bin/puma)
Oct 11 09:51:34 klein bundle[25925]: SignalException: SIGTERM
Oct 11 09:51:34 klein bundle[25925]:   /home/david/.gem/ruby/2.3.0/gems/puma-3.10.0/lib/puma/launcher.rb:397:in `block in setup_signals'
Oct 11 09:51:34 klein bundle[25925]:   /home/david/.gem/ruby/2.3.0/gems/puma-3.10.0/lib/puma/single.rb:106:in `join'
Oct 11 09:51:34 klein bundle[25925]:   /home/david/.gem/ruby/2.3.0/gems/puma-3.10.0/lib/puma/single.rb:106:in `run'
Oct 11 09:51:34 klein bundle[25925]:   /home/david/.gem/ruby/2.3.0/gems/puma-3.10.0/lib/puma/launcher.rb:183:in `run'
Oct 11 09:51:34 klein bundle[25925]:   /home/david/.gem/ruby/2.3.0/gems/puma-3.10.0/lib/puma/cli.rb:77:in `run'
Oct 11 09:51:34 klein bundle[25925]:   /home/david/.gem/ruby/2.3.0/gems/puma-3.10.0/bin/puma:10:in `<top (required)>'
Oct 11 09:51:34 klein bundle[25925]:   /home/david/.gem/ruby/2.3.0/bin/puma:22:in `load'
Oct 11 09:51:34 klein bundle[25925]:   /home/david/.gem/ruby/2.3.0/bin/puma:22:in `<top (required)>'
Oct 11 09:51:34 klein systemd[826]: lionfish.service: Main process exited, code=exited, status=1/FAILURE
Oct 11 09:51:34 klein systemd[826]: Stopped Lionfish (Puma) HTTP Server.
Oct 11 09:51:34 klein systemd[826]: lionfish.service: Unit entered failed state.
Oct 11 09:51:34 klein systemd[826]: lionfish.service: Failed with result 'exit-code'.
Oct 11 09:51:34 klein systemd[826]: Started Lionfish (Puma) HTTP Server.

~~~

**Comment by colby-swandale** [comment]
\cc @segiddins thoughts?

**Comment by segiddins** [comment]
Seems like a reasonable request, and they submitted a PR for it

**Comment by dekellum** [comment]
Just in case the type label somehow sets expectations, for example backporting to a stable branch. This is a bug report IMO, not a feature request, thus I'm surprised about the `feature-request` label.

**Comment by dekellum** [comment]
Note, in course of PR and testing, this is another viable workaround to avoid this issue: 

`bundle config disable_exec_load true`

In other words, if `bundle exec` does a Kernel::exec (the older behavior) instead of Kernel::load, then the exec'd child process has no additional error handling getting in the way, and SignalException is handled by the ruby interpreter correctly.
