### ISSUE TITLE
No such file or directory @ dir_s_mkdir - H:. Use --trace to view backtrace

### ISSUE THREAD

**Issue by V2victory** [bundler/bundler#6094]
Why do I get this error?
what is pointing to H drive? I don't have H anymore as that is a drive on network.
What should I change to correct this?

**Comment by colby-swandale** [comment]
This isn't enough information for us to provide help, can you please attach the error you're getting and the output of `bundle env`

**Comment by V2victory** [comment]
all that I can send you is the screen shot. there are no log files generated.
I using it for the 1st time, I have to initialize and build my Murano application.
<img width="576" alt="capture1" src="https://user-images.githubusercontent.com/32749414/31546956-82947ca8-aff3-11e7-9e1d-132a7f5532f3.png">
 
If you can guide me a little more on where I can find the log files for the errors, I will look for it and share.

**Comment by colby-swandale** [comment]
I'm not sure what `murano` is or how it relates to bundler, i suggest talking talking to the `murano` authors.
