### ISSUE TITLE
new dependency conflicts after upgrading bundler

### ISSUE THREAD

**Issue by bsoule** [bundler/bundler#6095]
I'm not sure if this is a Bundler problem, or the fault of the gem in question. I have an existing project with a locked bundle. I haven't touched the Gemfile or Gemfile.lock for a while. Today I'm trying to start up another web server with this same project, and I'm getting conflicts resolving the dependencies around one particular gem, where previous deploys have not complained about compatibilities with these two gems at the locked versions.

    # Gemfile
    gem 'tzinfo'
    gem 'tzinfo-data'

    # Gemfile.lock shows both gems locked at:
        tzinfo (0.3.53)
        tzinfo-data (1.2013.3)

Old version of Bundler is 1.13.6
New version of Bundler is 1.15.4

When I run bundle install the error given is

    Downloading tzinfo-data-1.2013.3 revealed dependencies not in the API or the lockfile (tzinfo (>= 1.0.0)).
    Either installing with `--full-index` or running `bundle update tzinfo-data` should fix the problem.

(Also this is possibly an argument in favor of [allowing to force a gem version](https://github.com/bundler/bundler/issues/4552 ).)

**Comment by colby-swandale** [comment]
Can you please attach the output of `bundle env`

**Comment by colby-swandale** [comment]
I'm closing this for now. If you're still experiencing your original issue don't be afraid to re-open this ticket.

**Comment by junoteam** [comment]
Hello, I see issue is closed, but we for example, experience the same problem:

```
09:17:25 Downloading jader-0.0.9 revealed dependencies not in the API or the lockfile
09:17:25 (therubyracer (> 0.12.0)).
09:17:25 Either installing with `--full-index` or running `bundle update jader` should
09:17:25 fix the problem.
09:17:25 
09:17:25 In Gemfile:
09:17:25   jader
09:17:25 The command '/bin/sh -c bundle install' returned a non-zero code: 34
09:17:25 Failed with status code 34
09:17:25 Failed with status code 1
```
