### ISSUE TITLE
`bundle update <gem>` does not downgrade dependency.

### ISSUE THREAD

**Issue by arthwood** [bundler/bundler#6097]
Here's is extracted part of my Gemfile.lock:

```ruby
addressable (2.5.2)
      public_suffix (>= 2.0.2, < 4.0)
apartment (1.2.0)
      activerecord (>= 3.1.2, < 6.0)
      rack (>= 1.3.6)
public_suffix (3.0.0)
```

`addressable` is the only gem that has dependency on `public_suffix` and (3.0.0) is most recent version.

I was planning to update apartment gem. Most recent version is (2.0.0), which adds dependency on public_suffix (~> 2.0.5) and has two other dependencies (https://github.com/influitive/apartment/blob/v2.0.0/apartment.gemspec:
activerecord('>= 3.1.2', '< 6.0')
rack('>= 1.3.6')
Both are met in my `Gemfile.lock`.

I'd expect running `bundle update apartment` to downgrade `public_suffix` to (2.0.5) and install apartment (2.0.0) but none of these is happening.

**Comment by arthwood** [comment]
I've created empty sample project with `Gemfile`:

```ruby
gem 'addressable', '2.5.2'
gem 'apartment', '1.2.0'
```

run `bundle install`
removed version constraint for `apartment` gem.
run `bundle update apartment` -> no effect
run `bundle update` -> works as expected (upgrades `apartment`, downgrades `public_suffix`)

**Comment by arthwood** [comment]
The other scenario I tried is specifying new version for apartment:

```ruby
gem 'addressable', '2.5.2'
gem 'apartment', '2.0.0'
```
But then running `bundle update apartment` results in:

> Bundler could not find compatible versions for gem "public_suffix":
>   In snapshot (Gemfile.lock):
>     public_suffix (= 3.0.0)
> 
>   In Gemfile:
>     addressable (= 2.5.2) was resolved to 2.5.2, which depends on
>       public_suffix (< 4.0, >= 2.0.2)
> 
>     apartment (= 2.0.0) was resolved to 2.0.0, which depends on
>       public_suffix (~> 2.0.5)
> 
> Running `bundle update` will rebuild your snapshot from scratch, using only
> the gems in your Gemfile, which may resolve the conflict.

However I don't want to update all gems.
apparently bundle update <gem> tries to update only this gem whereas I'm ok if it updated any dependencies as well.

**Comment by segiddins** [comment]
Does `bundle update apartment public_suffix` work?

**Comment by arthwood** [comment]
@segiddins Yes, that works 👍 Just wondering if bundler shouldn't figure that out without user having to specify dependencies, especially if they are not present in `Gemfile`.

**Comment by segiddins** [comment]
The problem here is that the _other_ option is equally confusing (a lot of people don’t like these “automatic” downgrades, so they’ve been disabled entirely for Bundler 2)

**Comment by arthwood** [comment]
Hmm it's kind of against what bundling system is supposed to do in my opinion. We specify gem version range because we accept downgrade if required. Anyway, I assume there must have been a discussion and compelling arguments for disabling this feature. 
A good option would be to prompt about any downgrades because otherwise silently doing nothing, makes me think that there is no newer version for a gem that I'm trying to upgrade.
Thanks for explanation!

**Comment by segiddins** [comment]
Well also print out if you run “bundle update foo” and foo didn’t end up changing versions

**Comment by colby-swandale** [comment]
This looks answered. Closing.
