### ISSUE TITLE
Limit bundler's own update notice to stable releases

### ISSUE THREAD

**Issue by sos4nt** [bundler/bundler#6104]
When running `bundle`, it (currently) shows the following update notice:

```
The latest bundler is 1.16.0.pre.3, but you are currently running 1.15.4.
To update, run `gem install bundler --pre`
```

Although I like to update my tools, I usually don't want to install prerelease versions.

Please add an option to limit the update notice to stable releases. (or better yet, make that the default and add an option to include prereleases)

**Comment by colby-swandale** [comment]
The update notification has been disabled by default in the next release. See #6031
