### ISSUE TITLE
[!] There was an error parsing `Gemfile`: [!] There was an error while loading `pry-media.gemspec`: cannot infer basepath Does it try to require a relative path? That's been removed in Ruby 1.9. Bundler cannot continue.

### ISSUE THREAD

**Issue by r-obert** [bundler/bundler#6107]
On 1.9.3:
```
[!] There was an error parsing `Gemfile`:
[!] There was an error while loading `pry-media.gemspec`: cannot infer basepath
Does it try to require a relative path? That's been removed in Ruby 1.9. Bundler cannot continue.
```

Is bundler an opinionated Ruby tutorial, or a packaging tool?
Please consider a back-port that removes this fatal error.

**Comment by r-obert** [comment]
I see, the error is on Ruby's side. Can it not just be, `LoadError:  ...` ?

**Comment by r-obert** [comment]
backtrace relative to the gemspec would be nice too.

**Comment by r-obert** [comment]
Compare with Rubygem's output, which is simple and to the point:
<img width="720" alt="screen shot 2017-10-17 at 23 10 38" src="https://user-images.githubusercontent.com/8934693/31689557-0bd11a86-b390-11e7-8d93-f0c23c727049.png">

I'm lost in Bundler's sea of red.

**Comment by r-obert** [comment]
I suggest a few things:
- use colour selectively, it can add emphasis and it can add noise. red everywhere is obnoxious.
- do not hide errors in colour. 
- do not hide useful information in noise.

all the best,
faisal

**Comment by colby-swandale** [comment]
Firstly, please watch the attitude, it's not welcome and doesn't help in any way. I ask that you please review the [Code of Conduct](https://github.com/bundler/bundler/blob/master/CODE_OF_CONDUCT.md)

Sorry that you're having issues with Bundler. We will take your feedback into consideration and look into making improvements in the future.

**Comment by r-obert** [comment]
Thank you.
