### ISSUE TITLE
unable to "bundle install" under Windows with git source

### ISSUE THREAD

**Issue by jarmo** [bundler/bundler#611]
In my Gemfile i have among other things:
    gem 'authlogic', :git => 'git://github.com/odorcicd/authlogic.git', :branch => 'rails3'

And when trying to bundle install, i'm getting this strange failure. Same Gemfile and bundle install works under Ubuntu.

```
C:\project>bundle install
Fetching git://github.com/odorcicd/authlogic.git
remote: Counting objects: 3652, done.
remote: Compressing objects: 100% (1189/1189), done.
remote: Total 3652 (delta 2378), reused 3578 (delta 2341)
Receiving objects: 100% (3652/3652), 589.85 KiB | 80 KiB/s, done.
Resolving deltas: 100% (2378/2378), done.
Unable to open connection:
gethostbyname: unknown errorfatal: The remote end hung up unexpectedly
An error has occurred in git when running `git fetch --force --quiet 'C:/bin/pik/Ruby-187-p302/lib/ruby/g
ems/1.8/cache/bundler/git/authlogic-6baa44cd7023e0828fc87e150aa82c0caeeb7c3d'. Cannot complete bundling.
```

I'm on win7 64bit, git version 1.7.0.2.msysgit.0 and rails3 rc2.

Any ideas, what's causing that and how to solve it?

**Comment by trejkaz** [comment]
We saw this in 2017, on a current version of bundler running under JRuby:

```
 An error occurred while installing diff-lcs (1.3), and Bundler cannot continue.
 Make sure that `gem install diff-lcs -v '1.3'` succeeds before bundling.
```

That command does indeed fail, but with double-quotes it works fine. Not entirely sure whether the error message is just wrong, or whether bundler is actually running that command.

**Comment by iongion** [comment]
This issue is still there, I cannot go pass gem installation if they reference github repos.

Using msys2 installer from http://repo.msys2.org/distrib/x86_64/msys2-x86_64-20180531.exe

```
$ ruby --version
ruby 2.5.3p105 (2018-10-18 revision 65156) [x64-mingw32]
$ which ruby
/mingw64/bin/ruby
$ gem --version
2.7.8
$ bundle --version
Bundler version 1.17.1
$ git --version
git version 2.19.1
```

Any ideas ?
