### ISSUE TITLE
Bundler issues

### ISSUE THREAD

**Issue by Naccuddi** [bundler/bundler#6122]
Unfortunately, an unexpected error occurred, and Bundler cannot continue.

https://github.com/bundler/bundler/search?q=Unable+to+find+a+spec+satisfying+nokogiri+%28%7E%3E+1.8.1%29+in+the+set.+Perhaps+the+lockfile+is+corrupted%3F&type=Issues

**Comment by colby-swandale** [comment]
Hi, we need the full error report that Bundler prints otherwise we won't be able to help resolve your issue.
