### ISSUE TITLE
The ability to silence platform warnings

### ISSUE THREAD

**Issue by envygeeks** [bundler/bundler#6124]
https://github.com/bundler/bundler/blob/b9c12ee67661581f8a4fb5f47a375b5c7da2ed1e/lib/bundler/definition.rb#L880-L884

There really isn't any reason to ship that warning to me, and it would be nice if I could silence it, as I am well aware of the platform I am on, and I always inspect Gemfiles before I install anything, regardless of whether it's my own project or not.

**Comment by segiddins** [comment]
I think we could accept a PR adding a setting to disable that warning, but I think we want to keep it enabled by default
