### ISSUE TITLE
Should bundler installed git gems contain the entire repo (.git folder)?

### ISSUE THREAD

**Issue by bughit** [bundler/bundler#6127]
They do with 1.15.4. That does not seem to make sense.

**Comment by colby-swandale** [comment]
Yes, because Bundler needs to be able to checkout the given branch/ref/tag from the Gemfile.

**Comment by bughit** [comment]
That's only done once, when installing, the checked out commit never changes (the folder name even includes the commit hash), so why keep the repo?

**Comment by colby-swandale** [comment]
Bundler uses the `git` command to perform these operations so we need to keep the repository around for when you update your git gem to the latest commit, to checkout a specific branch/ref/tag if you update your Gemfile etc.

**Comment by bughit** [comment]
a git gem install folder represents a specific commit and never changes in place.

Are you saying that when you install a different commit, instead of cloning the repo again you copy the .git repo from a prior install into a new folder, then do a fetch and checkout?

**Comment by segiddins** [comment]
We keep a cache of a bare clone which is the only one that fetches from the upstream remote, and each commit that bundler uses clones & checks out the commit it needs from that local bare repo

**Comment by bughit** [comment]
Where does this bare clone live? If I understood you, as long as you have this clone, there is not need to keep the .git repo in each install.

**Comment by bughit** [comment]
The bare clone is under lib/ruby/gems/<ver>/cache/bundler/git/

**Comment by colby-swandale** [comment]
I'm closing this for now. If you have any more questions feel free to open a new issue.

**Comment by bughit** [comment]
The question has not really been answered conclusively, you were insisting that the repo is needed but from @segiddins response, it looks like it's not, so why keep the repo after install?

**Comment by segiddins** [comment]
It probably doesn’t need to be kept, but we’d need to implement the change to verify it doesn’t break any existing tests.

**Comment by colby-swandale** [comment]
I'm closing this. If you're still experiencing your original issue don't be afraid to re-open this ticket.
