### ISSUE TITLE
Bundler makes Foo::VERSION constant available when it shouldn't.

### ISSUE THREAD

**Issue by r-obert** [bundler/bundler#6136]
Imagine the following gemspec:

```ruby
require_relative "foo/version"
Gem::Specification.new do |g|
  g.version = Foo::VERSION
end
```

Gemfile:

```ruby
source 'https://rubygems.org'
group :default do
  gemspec
end
```

Loaded as follows:

```ruby
irb -rbundler/setup -rfoo
```

With no explicit declaration on `foo/version` but Foo::VERSION is available.
Maybe process isolation is needed?

**Comment by r-obert** [comment]
updated original post.

**Comment by segiddins** [comment]
You've `require_relative "foo/version"` in your gemspec, which bundler has loaded.

**Comment by r-obert** [comment]
Thank you. I am aware of that. That is why I suggested __process isolation__. `bundler/setup` means `require "gemspec"`? Makes no sense.

**Comment by r-obert** [comment]
Closing this because I don't have the energy to debate what is clearly a bug (in my eyes). It broke a release for me but that's okay. Thank you for your time.
