### ISSUE TITLE
bundle exec jekyll serve

### ISSUE THREAD

**Issue by alvarotrigo** [bundler/bundler#6137]
I'm not quite sure if this is a Jekyll / Ruby / Gem or Bundle problem, so apologies in advance if this is not the place to ask about it.

I used `sudo bundle install` and that might be the cause of the issue? 

Now I have:
`gem -v` 2.6.14
`ruby -v` ruby 2.3.5p376 (2017-09-14 revision 59905) [x86_64-darwin15]
`jekyll -v` jekyll 3.6.2
`bundle -v`Bundler version 1.16.0.pre.3

I'm getting the following error when trying to run `bundle exec jekyll serve` or just `jekyll serve`

> > /Users/myusername/.rvm/rubies/ruby-2.3.5/lib/ruby/site_ruby/2.3.0/rubygems.rb:271:in `find_spec_for_exe': can't find gem bundler (>= 0.a) (Gem::GemNotFoundException)
	from /Users/myusername/.rvm/rubies/ruby-2.3.5/lib/ruby/site_ruby/2.3.0/rubygems.rb:299:in `activate_bin_path'
	from /Users/myusername/.rvm/gems/ruby-2.3.5/bin/bundle:23:in `<main>'
	from /Users/myusername/.rvm/gems/ruby-2.3.5/bin/ruby_executable_hooks:15:in `eval'
	from /Users/myusername/.rvm/gems/ruby-2.3.5/bin/ruby_executable_hooks:15:in `<MacBooMacBook-MacBook-MacBook-Pro-MacBook-PrMacBook-MacBooMacBMaMacBMaMaMaMaMaMaMaMaMacBMaMaMaMacBMa

Also, when accessing the folder in which I have my blog `cd my_path` I get the following message:

> VM used your Gemfile for selecting Ruby, it is all fine - Heroku does that too,
you can ignore these warnings with 'rvm rvmrc warning ignore /Library/WebServer/Documents/blog/Gemfile'.
To ignore the warning for all files run 'rvm rvmrc warning ignore allGemfiles'.
Unknown ruby interpreter version (do not know how to handle): RUBY_VERSION.

**Comment by segiddins** [comment]
Given the error 
`/Users/myusername/.rvm/rubies/ruby-2.3.5/lib/ruby/site_ruby/2.3.0/rubygems.rb:271:in find_spec_for_exe': can't find gem bundler (>= 0.a) (Gem::GemNotFoundException) from /Users/myusername/.rvm/rubies/ruby-2.3.5/lib/ruby/site_ruby/2.3.0/rubygems.rb:299:inactivate_bin_path'`

it seems as if you have the `bundle` binstub in your `$PATH`, but `bundler` the gem isn't installed

**Comment by alvarotrigo** [comment]
I seem to have solved this particular issue by following the indications in [this answer](https://github.com/rvm/rvm/issues/1860#issuecomment-17342047) and [this other one](https://stackoverflow.com/a/47039723/1081396).

Now of course, I have [another one](https://stackoverflow.com/questions/47046419/could-not-find-jekyll-0) :) 
Not sure if related with bundle at all, so feel free to close the issue.
