### ISSUE TITLE
LoadError when trying to invoke `bundle exec` from ruby script after `bundler/setup`

### ISSUE THREAD

**Issue by tf** [bundler/bundler#6144]
Bundler Version: 1.16.0
Ruby Gems: 2.7.0

Trying to run 

```ruby
require 'bundler/setup'
system('bundle exec whatever')
```
fails with
```
/home/travis/.rvm/gems/ruby-2.4.1/bin/bundle:23:in `load': cannot load such file -- /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/exe/bundle (LoadError)
```
Minimal example: 

https://github.com/tf/bundler-executable-not-found
https://travis-ci.org/tf/bundler-executable-not-found/builds/296324791

If `Gem.activate_bin_path('bundler', 'bundle', '>= 0.a')` (which is what is loaded in the `bundle` executable) is called for the first time after `bundler/setup`, it reports the missing path `.rvm/rubies/ruby-2.1.7/lib/ruby/site_ruby/exe/bundle`. If it is called before `bundler/setup`, the correct value is already cached. The above Travis build contains examples of both cases for different Ruby versions.

In my case this causes all invocations of the form `system('bundler exec ...')` to fail that come from a binstub since binstubs include the `bundler/setup` line.

**Comment by tf** [comment]
Also happens after downgrading to Rubygems 2.6/Bundler 1.15:

https://travis-ci.org/tf/bundler-executable-not-found/builds/296337874

Even though this combination used to work some builds back in the real project where I originally encountered the issue today: https://travis-ci.org/tf/pageflow/jobs/291487846

So far only reproduced on Travis. Maybe its Travis specific?

**Comment by WozniakMac** [comment]
I have similar problems on Teamcity Ci. Did you try to remove bundler 1.16 from your system?

**Comment by tf** [comment]
I tried removing Bundler 1.16 and downgrading to 1.15, but it did not help:

https://travis-ci.org/tf/bundler-executable-not-found/jobs/296355343/config

**Comment by tf** [comment]
Since re-running passed Travis jobs also leads to failures now, either something could be broken on Travis or it might be an issue with the new Rubygems version. Still, downgrading Rubygems does not help either. But since I have not found a way yet to prevent rvm from installing a current Rubygems version first. So Rubygems 2.7 might still break something that is not fixed by downgrading.

**Comment by WozniakMac** [comment]
What does bundle install installed?
Bundle complete! 0 Gemfile dependencies, 1 gem now installed.

**Comment by tf** [comment]
Good question. I just added the empty Gemfile to be able to run `bundle exec`.

**Comment by WozniakMac** [comment]
Could you add some gems?

**Comment by WozniakMac** [comment]
It looks that i have different problem

**Comment by tf** [comment]
Maybe Bundler is counting itself as a gem? Listing gems after `bundle install`, does not reveal anything interesting: 

https://travis-ci.org/tf/bundler-executable-not-found/jobs/296361910

Here's a build with some rails gems installed:

https://travis-ci.org/tf/bundler-executable-not-found/jobs/296362939

It does not change much really.

**Comment by tf** [comment]
Was able to reproduce on local machine using Rubygems 2.7 and Bundler 1.16 with `BUNDLE_DISABLE_SHARED_GEMS: true`. 

On the other hand, installing without `--deployment`/`--path` fixes Travis build:
https://travis-ci.org/tf/bundler-executable-not-found/builds/296490703

Looks a bit like https://github.com/bundler/bundler/issues/4602#issuecomment-249274930. 

Could this be related to bundler being vendored in recent Rubygems versions?

**Comment by segiddins** [comment]
I'm currently unable to reproduce this in a test:

```diff
diff --git a/spec/commands/exec_spec.rb b/spec/commands/exec_spec.rb
index ae3148793..3ce1542be 100644
--- a/spec/commands/exec_spec.rb
+++ b/spec/commands/exec_spec.rb
@@ -746,6 +746,18 @@ __FILE__: #{path.to_s.inspect}
         file.chmod(0o777)
         bundle! "exec #{file}", :system_bundler => true
         expect(out).to eq("foo")
+
+        create_file(file, <<-RB)
+          #!#{Gem.ruby}
+          require "bundler/setup"
+          puts `bundle exec #{Gem.ruby} -e 'puts :foo'`
+        RB
+        file.chmod(0o777)
+        sys_exec! "'#{Gem.ruby}' #{file}"
+        expect(out).to eq("foo")
+
+        sys_exec! "BUNDLE_DISABLE_SHARED_GEMS=true '#{Gem.ruby}' #{file}"
+        expect(out).to eq("foo")
       end
     end
 

```

**Comment by tf** [comment]
So I think I tracked it down. Here's what is happening:

When `bundler/setup` is loaded, it patches Rubygems and overrides `activate_bin_path` to return the contents of `ENV["BUNDLE_BIN_PATH"]` when we are looking for the bin path of the bundler executable:

https://github.com/bundler/bundler/blob/d17f2e43236ba53f05b70e7317d218ba94e293c8/lib/bundler/rubygems_integration.rb#L472-L483

This environment variable is set by first trying to look up the bin path via rubygems, but falls back to a fixed relative path to Bundler's `exe` directory:

https://github.com/bundler/bundler/blob/d17f2e43236ba53f05b70e7317d218ba94e293c8/lib/bundler/shared_helpers.rb#L294-L300

When gems have been installed with `bundle install --deployment`, this rescue case kicks in, because apparently Bundler does not include its own sources in the `vendor/bundle` directory.

In the presence of Rubygems 2.7, `shared_helpers.rb` is loaded from `.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/bundler/shared_helpers.rb`. But there simply is no `../../../exe/bundle` directory in the vendored version of Bundler.

**Comment by tf** [comment]
So it's more or less a bug with the way Rubygems unpacks its vendored version Bundler if I understand correctly. Or a bug in Bundler making too concrete assumptions about the way it is installed.

**Comment by tf** [comment]
A temporary workaround is to invoke the script with `bundle exec` (or in my original bin stub case, call `bundle exec rake` instead of `bin/rake` in `.travis.yml`).

This makes Rubygems load and cache Bundler's gemspec (including bin paths) before the monkey patch is activated, causing the non-vendered, gem version of Bundler to be used.

**Comment by davidwessman** [comment]
@tf 
I have the same issue on Circle CI, my `bundle install` works, but when running `rails test` it cannot find rake.

Did you find anyway to solve it? Even running `bundle exec rails test` gives me the same issues.

**Comment by mshytikov** [comment]
@davidwessman in my case `rails test` fails  only because of 'spring' 
the line https://github.com/rails/spring/blob/v2.0.2/lib/spring/client/binstub.rb#L39
```
Gem.use_paths Gem.dir, Bundler.bundle_path.to_s, *Gem.path
```
in `bin/spring` makes it fail.
If you remove/comment out the line then it works fine (in my case)

**Comment by mattbrictson** [comment]
I'm seeing the same failure in our Circle CI builds after upgrading to 1.16.0. Downgrading to 1.15.4 is a successful workaround.

As mentioned in #6147, for me it has to do with the `--path` option.

If I install using `--path`, then I see an error:

```
$ bundle install --path vendor/bundle --jobs=4
$ bin/rake --version
Could not find rake-12.1.0 in any of the sources
Run `bundle install` to install missing gems.
```

But if I instead use `--system`, it works:

```
$ rm -rf vendor/bundle
$ bundle install --system --jobs=4
$ bin/rake --version
Running via Spring preloader in process 13465
rake, version 12.1.0
```

In my case `bin/rake` is the spring-enabled binstub that comes with Rails:

```ruby
#!/usr/bin/env ruby
begin
  load File.expand_path('../spring', __FILE__)
rescue LoadError => e
  raise unless e.message.include?('spring')
end
require_relative '../config/boot'
require 'rake'
Rake.application.run
```

I hope this info is helpful!

Again, downgrading to 1.15.4 solves this problem.

**Comment by vipulnsward** [comment]
Same here. Our CI systems started failing after 1.16.0. Running 

```
bundle exec rails runner -e test "puts 1" --trace
bundle exec bin/rails runner -e test "puts 1" --trace
```

fails. 

We install using `bundle install --path vendor/bundle --jobs=4` as well.

**Comment by davidwessman** [comment]
@mshytikov That did not work for me :/

**Comment by mattbrictson** [comment]
Turns out, the error I was seeing ([mentioned above](https://github.com/bundler/bundler/issues/6144#issuecomment-341850521)) was not due to upgrading to Bundler 1.16.0, but was due to Circle CI introducing the `BUNDLER_APP_CONFIG` environment variable. I can't speak for the other commenters in this thread, but my issue is actually a problem with Spring (specifically the way the binstubs interact with `BUNDLER_APP_CONFIG`) and not Bundler itself. See https://github.com/rails/spring/issues/545.

**Comment by eric-hu** [comment]
> Also happens after downgrading to Rubygems 2.6/Bundler 1.15:
> 
> https://travis-ci.org/tf/bundler-executable-not-found/builds/296337874
> 
> Even though this combination used to work some builds back in the real project where I originally encountered the issue today: https://travis-ci.org/tf/pageflow/jobs/291486495
> 
> So far only reproduced on Travis. Maybe its Travis specific?


@tf I just reviewed that link and I think the problem is that you're installing the new bundler 1.15, then reverting back to Rubygems 2.6.  The newly installed bundler may be referencing the old Rubygems, so the Rubygems 2.6 install should come before the Bundler 1.15 install.

From what I've seen of this bug, this issue should be Rubygems 2.7.1 specific. Can you update your test run and try again?

**Comment by hsbt** [comment]
Hi all, Can anyone try this issue with RubyGems 2.7.3? I couldn't reproduce this.

see. https://travis-ci.org/hsbt/bundler-executable-not-found/builds/309343716

**Comment by tf** [comment]
RubyGems 2.7.3 appears so have fixed the problem. I can also no longer reproduce the problem in the project where I originally encountered the issue.
