### ISSUE TITLE
Gem::LoadError: You have already activated rack-cors 1.0.1, but your Gemfile requires rack-cors 1.0.2

### ISSUE THREAD

**Issue by perlun** [bundler/bundler#6164]
This is similar to #6144 in that it's also related to `bundler/setup` somehow, but slightly different.

Preconditions:

- Project is a Ruby gem
- Ruby gem is installed via `bundler`
- Project has an executable.

The executable runs a few lines like this on startup:

```ruby
require 'bundler/setup'
Bundler.setup
```

This works well, both with bundler 1.15.4, 1.16.0 and so forth. _But_, we are utilizing self-restarts with [puma](https://github.com/puma/puma/) and here we are seeing issues. When the process is restarted, `bundler` chooses the wrong gems and this breaks everything:

```
$ bundle exec bundler_bug_app_server
Running from /Users/plundberg/.rvm/gems/jruby-9.1.13.0/bin/bundler_bug_app_server
Puma starting in single mode...
* Version 3.10.0 (jruby 9.1.13.0 - ruby 2.3.3), codename: Russell's Teapot
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://0.0.0.0:9292
Use Ctrl-C to stop
* Restarting...
Running from /Users/plundberg/.rvm/gems/jruby-9.1.13.0/bin/bundler_bug_app_server
Gem::LoadError: You have already activated rack-cors 1.0.1, but your Gemfile requires rack-cors 1.0.2. Prepending `bundle exec` to your command may solve this.
  check_for_activated_spec! at /Users/plundberg/.rvm/gems/jruby-9.1.13.0/gems/bundler-1.16.0/lib/bundler/runtime.rb:313
             block in setup at /Users/plundberg/.rvm/gems/jruby-9.1.13.0/gems/bundler-1.16.0/lib/bundler/runtime.rb:31
                       each at org/jruby/RubyArray.java:1734
                       each at /Users/plundberg/.rvm/rubies/jruby-9.1.13.0/lib/ruby/stdlib/forwardable.rb:189
                        map at org/jruby/RubyEnumerable.java:830
                      setup at /Users/plundberg/.rvm/gems/jruby-9.1.13.0/gems/bundler-1.16.0/lib/bundler/runtime.rb:26
                      setup at /Users/plundberg/.rvm/gems/jruby-9.1.13.0/gems/bundler-1.16.0/lib/bundler.rb:107
                     <main> at /Users/plundberg/.rvm/gems/jruby-9.1.13.0/gems/bundler-1.16.0/lib/bundler/setup.rb:10
                    require at org/jruby/RubyKernel.java:955
                     (root) at /Users/plundberg/.rvm/rubies/jruby-9.1.13.0/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:1
                     <main> at /Users/plundberg/.rvm/rubies/jruby-9.1.13.0/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55
                       load at org/jruby/RubyKernel.java:973
                     <main> at /Users/plundberg/.rvm/gems/jruby-9.1.13.0/gems/bundler-bug-0.1.0/exe/bundler_bug_app_server:7
```

I knew this is a tricky problem so I put together an extensive repro repo to be able to debug this in a reasonable way: https://github.com/perlun/bundler-1.16-bug

----

What I've concluded so far:

- It works correctly on MRI, have never managed to reproduce it there.
- The bug is only visible on JRuby.
- `bundler 1.15.4` seems to work correctly, even thought I _have_ on a rare occasion seen it there (but later when testing, the bug usually goes away by downgrading to 1.15.4). `bundler 1.16.0` exhibits the problem.
- I have no idea whether the problem is in bundler or JRuby; will cross-post to both projects to be on the safe side.
- It only occurs when multiple versions of a gem are installed (which is very common after living with a Ruby installation for some time.)

I will gladly assist in debugging this of course. My repro repo contains extensive instructions on how to trigger the problem. If you need more info or details, just let me know. I _did_ look at the ENV variables in the "first" and "second" startups, but they didn't give me that much; all relevant RUBYOPT and BUNDLER_* variables were identical on both startups.

However, I did see something strange: on the first run, it used the executable from my "own" repo and in the second run, it used the executable from an installed gem version. This only happened in my private GitHub repo, in the repro repo it _always_ used the executable from an installed gem version for whatever reason.

**Comment by colby-swandale** [comment]
It looks like this issue has been resolved? ping @perlun

**Comment by perlun** [comment]
@colby-swandale Indeed, thanks for asking. https://github.com/jruby/jruby/issues/4849 has the full details. Closing this now as the problem was indeed a JRuby bug, not a bundler bug per se.
