### ISSUE TITLE
Unable to detect bundler spec (1.16.0)

### ISSUE THREAD

**Issue by mleopard** [bundler/bundler#6165]
I keep running into this error when using bundler 1.16.0:
```
LoadError: no such file to load -- /home/dev/.rvm/rubies/jruby-1.7.4/lib/ruby/gems/shared/gems/bundler-1.16.0/exe/bundle
    load at org/jruby/RubyKernel.java:1073
  (root) at /home/dev/.rvm/gems/jruby-1.7.4/bin/bundle:23
```

I have also seen this error on another VM using a newer version of jruby:
```
Unable to detect bundler spec under '/home/dev/.rvm/rubies/jruby-1.7.27/lib/ruby/gems/shared/gems/bundler-1.16.0'' and its sub-dirs
```

And I noticed the directory structure between 1.15.4 and 1.16.0 are a bit different.

Bundler 1.15.4
├── bin
├── bundler.gemspec
├── CHANGELOG.md
├── CODE_OF_CONDUCT.md
├── CONTRIBUTING.md
├── doc
├── exe
├── lib
├── LICENSE.md
├── man
├── Rakefile
├── README.md
└── task

Bundler 1.16.0
├── CHANGELOG.md
├── exe
├── lib
├── LICENSE.md
├── man
└── README.md

If I explicitly set bundler to 1.15.4, my project will build without errors.

Is the different directory structure expected behavior?

**Comment by colby-swandale** [comment]
There was some changes to the files that are included in `bundler.gem` in #5862 but the `bin` directory nor the gemspec itself has been moved. Can you try reinstalling the bundler gem?

**Comment by mleopard** [comment]
Reinstalling the bundler gem didn't make a difference. I'm noticing an issue with how my gems are being installed, so perhaps this might be due to how I set up gem on my machine and not bundler 1.16. I tried reinstalling both 1.15.4 and 1.16 and the structure is still the same where 1.16 is missing a lot of files.

**Comment by colby-swandale** [comment]
ping @mleopard were you able to solve this problem?

**Comment by dr-itz** [comment]
Same problem here, but with warbler on JRuby 9.1.x. 

I manually downloaded the .gem from rubygems.org, manually extracted it to check. `bundler.gemspec` is missing. Also, https://github.com/bundler/bundler/pull/5862#issuecomment-319521002 lists the file as gone...

See also jruby/warbler#421

PR in a bit

**Comment by colby-swandale** [comment]
Thanks for the PR! I'm closing this now.
