### ISSUE TITLE
bundle update retrieves old version in Bundler 1.16.0

### ISSUE THREAD

**Issue by mount986** [bundler/bundler#6166]
My company has a nexus server which sits on top of rubygems.org in order to allow blacklisting of unsafe gems, as well as to hold in-home grown gems.  At the top of our Gemfile, we specify this nexus server as the source for all gems.  In the nexus server we have a home-grown gem which is currently at version 1.3.  Before upgrading to bundler 1.16, running a bundle update would correctly retrieve this latest version.  After upgrading, it is instead retrieving version 1.1.1 when doing an update.  Our Gemfile does not specify a version, but always asks for the latest.

**Comment by colby-swandale** [comment]
You're going to have to provide the output of `bundle env` for us to really help you in with this issue.

**Comment by greysteil** [comment]
This is almost certainly related to https://github.com/bundler/bundler/issues/6139. @mount986 - can you take a look at whether the sub-dependency requirements of your gems changed from v1.1.1 to v1.3, and whether Bundler 1.16 is upgrading one of those sub-dependencies to a version that v1.3 wouldn't be compatible with?

**Comment by colby-swandale** [comment]
ping @mount986

**Comment by colby-swandale** [comment]
I'm closing this for now. If you're still experiencing your original issue don't be afraid to re-open this ticket.
