### ISSUE TITLE
[2.0] Replacement for `show —paths` still needed

### ISSUE THREAD

**Issue by indirect** [bundler/bundler#6172]
We’ve deprecated `show` in favor of `list` and `info`, which is a good change, IMO. Now that we’re planning on deprecating the `show` command, we need a replacement for `show —paths`, to print every directory containing the gems installed in the bundle. This is needed for workflows like `rg SEARCH $(bundle show —paths)`, which does a recursive search for SEARCH through all the source code in the entire bundle.

**Comment by colby-swandale** [comment]
This feature has been merged. Closing.
