### ISSUE TITLE
Best practice for minimizing size on disk? (CircleCI caching)

### ISSUE THREAD

**Issue by CJBridges** [bundler/bundler#6175]
On CircleCI, you have the capability to [`save_cache`](https://circleci.com/docs/2.0/configuration-reference/#save_cache) and provide a directory to be cached (compressed under the covers).  Later, you can [`restore_cache`](https://circleci.com/docs/2.0/configuration-reference/#restore_cache).

I'm using this functionality to do a one time cache of `vendor/bundle` and keep using it as long as `Gemfile.lock` remains constant.

Is there a set of best practices for minimizing the size of `vendor/bundle` prior to saving it?  My main goal is to reduce the amount of time it takes to restore the cached `vendor/bundle` by reducing data stored.

```
$ du -chs vendor/bundle/ruby/2.3.0/*
284K	vendor/bundle/ruby/2.3.0/bin
  0B	vendor/bundle/ruby/2.3.0/build_info
 11M	vendor/bundle/ruby/2.3.0/bundler
 92M	vendor/bundle/ruby/2.3.0/cache  # this appears even with bundle install --no-cache
  0B	vendor/bundle/ruby/2.3.0/doc
 11M	vendor/bundle/ruby/2.3.0/extensions
442M	vendor/bundle/ruby/2.3.0/gems
1.4M	vendor/bundle/ruby/2.3.0/specifications
557M	total
```

Some tactics I've considered:
- (GOOD) I have used `--without` on some groups to reduce the size to the current numbers you see above (yay!).  Removing unused gems and grouping others so they can be excluded has helped.

- (GOOD) `rm -rf vendor/bundle/ruby/2.3.0/cache`, but don't really know the implications of dropping it.  This ended up being responsible for most of the space saved.

- (NO CHANGE) I have worked with using `--deployment` and `--no-cache`, but neither seem to change the resulting size.

- (BAD) `find vendor/bundle -type d -name test -o -name spec | xargs rm -rf` - This ended up breaking some rspec tests unfortunately and unsurprisingly.

All the GOOD changes have resulted in going from (compressed size) 146 MB down to 89 MB.  Please let me know of any other approaches I should be considering, or if there's documentation I'm missing somewhere else.

**Comment by segiddins** [comment]
Using `--without` and also running `bundle clean` would be the only (100% safe) things that come to mind.
