### ISSUE TITLE
Bundler.bat is not available anymore

### ISSUE THREAD

**Issue by FeodorFitsner** [bundler/bundler#6176]
When we refresh Ruby versions and gems on build worker images we do not do in-place "upgrade", but we do clean Ruby install. Right after install `gem update --system` is run to update rubygems. Apparently, Bundler 1.16.0 is being pulled by latest `gem update --system` and `bundler.bat` is not in `bin` folder anymore, only `bundle.bat`. Is it a regression or intended change?

I just did clean re-install of Ruby 2.4 on my dev machine and got only `bundle.bat`:

![image](https://user-images.githubusercontent.com/5041459/32986904-1ee02e9a-cc91-11e7-8587-acc8661de5c3.png)

This is installation log for clean Ruby 2.4 install:

```
c:\>ruby --version
ruby 2.4.2p198 (2017-09-14 revision 59899) [x64-mingw32]

c:\>gem update --system
Updating rubygems-update
Fetching: rubygems-update-2.7.2.gem (100%)
Successfully installed rubygems-update-2.7.2
Parsing documentation for rubygems-update-2.7.2
Installing ri documentation for rubygems-update-2.7.2
Installing darkfish documentation for rubygems-update-2.7.2
Done installing documentation for rubygems-update after 34 seconds
Parsing documentation for rubygems-update-2.7.2
Done installing documentation for rubygems-update after 0 seconds
Installing RubyGems 2.7.2
Bundler 1.16.0 installed
RubyGems 2.7.2 installed
Regenerating binstubs
RubyGems system software updated
```

**Comment by colby-swandale** [comment]
This is a rubygems issue, please open a new issue at https://github.com/rubygems/rubygems

**Comment by segiddins** [comment]
If you want the `bundler` exe, you'll need to install Bundler separately. It is intentional that RubyGems only has the `bundle` exe, and not `bundle-ruby` nor `bundler`

**Comment by FeodorFitsner** [comment]
@segiddins Thank you! However, `bundler` executable is broken after Rubygems update: https://github.com/rubygems/rubygems/issues/2083
