### ISSUE TITLE
An error occurred while installing json (1.8.6), and Bundler cannot continue. Make sure that `gem install json -v '1.8.6'` succeeds before bundling

### ISSUE THREAD

**Issue by samswag** [bundler/bundler#6178]
Fetching gem metadata from https://rubygems.org/.........
Using i18n 0.8.1
Fetching json 1.8.6
Installing json 1.8.6 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /home/samson/.gem/ruby/2.4.0/gems/json-1.8.6/ext/json/ext/generator
/usr/bin/ruby -r ./siteconf20171119-626-198n0qq.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/share/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /home/samson/.gem/ruby/2.4.0/gems/json-1.8.6 for inspection.
Results logged to /home/samson/.gem/ruby/2.4.0/extensions/x86_64-linux/2.4.0/json-1.8.6/gem_make.out

An error occurred while installing json (1.8.6), and Bundler cannot continue.
Make sure that `gem install json -v '1.8.6'` succeeds before bundling.

In Gemfile:
  github-pages was resolved to 126, which depends on
    jekyll-mentions was resolved to 1.2.0, which depends on
      html-pipeline was resolved to 2.5.0, which depends on
        activesupport was resolved to 4.2.7, which depends on
          json

**Comment by colby-swandale** [comment]
> mkmf.rb can't find header files for ruby at /usr/share/include/ruby.h

This is not a problem with Bundler, you're missing required libraries that ruby needs to compile your gem.

**Comment by zeeshan-za-ahmad** [comment]
This was happening to me on one of my project that was built on different ruby version.
I just changed my ruby version to 2.2.7 from 2.4.2.

**Comment by samswag** [comment]
Steps?

**Comment by zeeshan-za-ahmad** [comment]
I am using rvm to manage ruby.
You can check rvm guide to switch to ruby version.

https://www.phusionpassenger.com/library/walkthroughs/deploy/ruby/ownserver/nginx/oss/install_language_runtime.html
