### ISSUE TITLE
Cannot retrieve gem in Git repo behing a proxy (Windows)

### ISSUE THREAD

**Issue by abelsromero** [bundler/bundler#6179]
While Git, gem and budler work fine with the respective proxy configurations, the combination of a gem inside Git does not.

For instance, bundle fails trying to get a gem configured like this in the `Gemfile`.
```
gem 'middleman-asciidoc', github: 'middleman/middleman-asciidoc'
```
with the message
```
Fetching git://github.com/mojavelinux/middleman-asciidoc.git
fatal: unable to connect to github.com:
github.com[0: 192.30.253.112]: errno=No error
github.com[1: 192.30.253.113]: errno=No error


Retrying `git clone "git://github.com/mojavelinux/middleman-asciidoc.git" "C:/Users/-----/temp/opendevise.com/.bundle/gems/ruby/2.4.0/cache/bundler/git/middleman-asciidoc-06371e761af99724
e844b0866ee318f0b1b53785" --bare --no-hardlinks --quiet` due to error (2/4): Bundler::Source::Git::GitCommandError Git error: command `git clone "git://github.com/mojavelinux/middleman-ascii
doc.git" "C:/Users/-----/temp/opendevise.com/.bundle/gems/ruby/2.4.0/cache/bundler/git/middleman-asciidoc-06371e761af99724e844b0866ee318f0b1b53785" --bare --no-hardlinks --quiet` in direc
tory C:/Users/-----/temp/opendevise.com has failed.fatal: unable to connect to github.com:
github.com[0: 192.30.253.113]: errno=No error
github.com[1: 192.30.253.112]: errno=No error
```
If I remove the line, the rest of the gems are download and installed perfectly.

This is a work computer, for Git I have the proxy configuration insige `.gitconfig` in my %HOMEDRIVE% path, which happens to be a separated unit ("H:").

**Comment by arbonap** [comment]
hi @abelsromero, could you please print the output of `bundle env` so we can better help you?

**Comment by abelsromero** [comment]
Here it is attached
[bundle_env.txt](https://github.com/bundler/bundler/files/1497339/bundle_env.txt)

**Comment by colby-swandale** [comment]
Bundler performs all the git operations through the `git` command so you will need to make sure that git is reading your configuration correctly when using Bundler.

**Comment by abelsromero** [comment]
Git woks fine, it finds the config file with the proxy settings and eveything. The issue only appears when running from budler.
I even tried copying the `.gitconfig` to my windows home directory just in case the env_vars are not passed and resolved to default but nothing.

**Comment by segiddins** [comment]
Can you try running the following command (and seeing if it passes)?

```
ruby -e 'puts `git clone "git://github.com/mojavelinux/middleman-asciidoc.git"`; puts $?.success? ? :success : :failure'
```

**Comment by abelsromero** [comment]
Thanks @segiddins, I think I see the issue. Bundler is using the git protocol which does no use the proxy configuration.
Googling I found some workarrounds that require customs scripts or extra configurations like adding a url replacement with:
```
git config --global url."https://github.com/".insteadOf git@github.com:
git config --global url."https://".insteadOf git://
```
I cannot test it now, but I'll give it a try. However, wouldn't be easier to just use the HTTPS endpoint?

**Comment by segiddins** [comment]
You can either specify the full url using the `git:` key, or you can override the github shortcut:

```ruby
git_source(:github) { |repo_name| "https://github.com/#{repo_name}.git" }
```

In Bundler 2, the default `github` source key is going away for this very reason :)
