### ISSUE TITLE
Infinite "Resolving dependencies" using 1.16 with fastlane and atlassian-stash

### ISSUE THREAD

**Issue by jshier** [bundler/bundler#6181]
Bundler 1.16 spins forever in the "Resolving dependencies" step, outputting periods, with `Gemfile` containing only `fastlane` and `atlassian-stash` gems. 100% reproducible.

## Environment

```
Bundler             1.16.0
  Platforms         ruby, x86_64-darwin-17
Ruby                2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin17]
  Full Path         /Users/jshier/.rvm/rubies/ruby-2.4.2/bin/ruby
  Config Dir        /Users/jshier/.rvm/rubies/ruby-2.4.2/etc
RubyGems            2.6.14
  Gem Home          /Users/jshier/.rvm/gems/ruby-2.4.2@resolutiontest
  Gem Path          /Users/jshier/.rvm/gems/ruby-2.4.2@resolutiontest:/Users/jshier/.rvm/gems/ruby-2.4.2@global
  User Path         /Users/jshier/.gem/ruby/2.4.0
  Bin Dir           /Users/jshier/.rvm/gems/ruby-2.4.2@resolutiontest/bin
Tools               
  Git               2.13.6 (Apple Git-96)
  RVM               1.29.3 (latest)
  rbenv             not installed
  chruby            not installed
  rubygems-bundler  (1.4.4)
```

## Bundler Build Metadata

```
Built At          2017-10-31
Git SHA           10f20fa33
Released Version  true
```

### Gemfile

```ruby
source "https://rubygems.org"

gem "fastlane"
gem "atlassian-stash"
```

### Gemfile.lock

```
<No /Users/jshier/Desktop/ResolutionTest/Gemfile.lock found>
```

**Comment by arbonap** [comment]
Interesting...I also got the same thing to happen as @jshier when I didn't tie any of the gems to a version with Bundler 1.16. I let Bundler 1.16 try to resolve dependencies for at least a good 10 minutes.

@jshier not sure if this is useful to you, but when I tied the fastlane gem to the latest version, ie like `gem "fastlane", "= 2.66.2"` my dependencies resolved quickly with Bundler 1.16.

**Comment by colby-swandale** [comment]
@arbonap is correct, Bundler is trying to resolve a very wide set of possible solutions. Put a version constraint on both gems in the Gemfile and Bundler should resolve a lot quicker.

**Comment by jshier** [comment]
Sure, but that’s a severe regression over 1.15.4. Sorry, I forgot to mention that. I’ll play around with the versions without actually locking.

**Comment by segiddins** [comment]
@greysteil resolver regression

**Comment by greysteil** [comment]
Uh oh - I'll take a look this evening

**Comment by greysteil** [comment]
@jshier - thanks masses for reporting this. Can you let me know how long it takes Bundler to resolve this dependency set on v1.15.4? Running locally and I still don't have a resolution.

**Comment by greysteil** [comment]
This would be fixed by the tweak to the dependency sort order in https://github.com/bundler/bundler/pull/6186. I don't love that, but I don't have any major optimisations to the resolver up my sleeve right now, which would be the other way to address it.

**Comment by jshier** [comment]
@greysteil: It takes less than a second usually. So fast I’ve never bothered to time it. I can do more tests after Thanksgiving.

**Comment by greysteil** [comment]
@jshier - thanks. No need for more tests - the updated resolver eats this for breakfast after #6186.

**Comment by lparry** [comment]
I've also noticed our weekly bundle update has gone from taking seconds to taking 10-15 minutes, we run a fairly large `Gemfile` that is mostly unconstrained and review the changes each week.

Just in case #6186 doesn't solve our (similiar/probably related) issue, is there some flag I can pass to bundle update to see which gems it's spending so long trying to resolve are? Not super keen to add constraints to work around bundler suddenly having major performance regressions, but if we have to I'd like to narrow it down as much as possible

**Comment by segiddins** [comment]
@lparry setting the env var `DEBUG_RESOLVER` will cause a whole load of debug output to be printed

**Comment by indirect** [comment]
@lparry thanks for the additional data point. so that you're aware, putting no constraints in your Gemfile explicitly says to Bundler that you are willing to accept any version of that gem in existence, all the way back down to 0.0.0. As you can probably imagine, this forces Bundler to try every version of every gem every time you run `update`, even if you aren't actually willing to accept many of those versions. Setting minimum versions, or better yet using `pessimizer` to set pessimistic versions constraints and using something like Dependabot to handle upgrades will give you a better experience all around, even if we fix this exact performance issue.
