### ISSUE TITLE
bundle install --clean exits with code 15

### ISSUE THREAD

**Issue by FeodorFitsner** [bundler/bundler#6187]
`bundle install --retry=3 --clean` run with the most recent Bundler 1.16.0 exits with non-zero code 15 though there were no errors during gems installation. Looks like behavior change comparing with previous versions where exit code was 0. In AppVeyor CI environment non-zero code means "unsuccessful", so the build/test process stops.

There are AppVeyor builds demonstrating the regression:

* Successful build with Bundler 1.15.4: https://ci.appveyor.com/project/famished-tiger/rley/build/114/job/tpudkfqxfpgh9vg9
* Failing build with Bundler 1.16.0: https://ci.appveyor.com/project/famished-tiger/rley/build/115/job/j4jnhihqnr8q0474
* Another failing test with different gems: https://ci.appveyor.com/project/FeodorFitsner/simple-console/build/1.0.3150

cc @IlyaFinkelshteyn

**Comment by colby-swandale** [comment]
Thanks for the report!

**Comment by shayonj** [comment]
I believe 1.16.0 actually fixed the bug (unknown bug?). From what I understand, the default behavior should be: if `--path` (or `BUNDLER_PATH`) is not present (which is how appveyor is configured in the issue), then `bundle clean` or `bundle install --clean` should both complain about removing gems from the "system path" (default path). Hence, why a `--force` flag was required. However, in `1.15.4`, it appears that, there was a discrepancy between `bundle clean` and `bundle install --clean`.

That said, `bundle clean` would raise the appropriate error, whereas `bundle install --clean` would silently install and not clean (plus won't raising any errors).

---- 

**Example of `bundle clean` and `bundle install --clean` when no `--path` or `BUNDLER_PATH` is set:**

**in `1.15.4`**

`bundle clean` raises `InavlidOption` (which exits with `15` status code), but `bundle install --clean` does not.

```
bundle clean          
The latest bundler is 1.16.0, but you are currently running 1.15.4.
To update, run `gem install bundler`
Cleaning all the gems on your system is dangerous! If you're sure you want to remove every system gem not in this bundle, run `bundle clean --force`.

echo $? #status code
15
```

```
bundle install --clean
The latest bundler is 1.16.0, but you are currently running 1.15.4.
To update, run `gem install bundler`

...

echo $? #status code
0
```

**in `1.16.0`**

`bundle clean` and `bundle install --clean` both behave the same way.

```
bundle clean
Cleaning all the gems on your system is dangerous! If you're sure you want to remove every system gem not in this bundle, run `bundle clean --force`.

echo $?
15
```

```
bundle install --clean
...

echo $?
15
```

----

This behavior in `1.16.0` is now consistent. That said, to resolve the original issue I think either one of the following should happen:

- Install with a custom path each time `bundle install --clean --path /tmp/some-path`
- Or, Install on default system path and clean with force `bundle install --clean --force`

PR that fixed https://github.com/bundler/bundler/pull/5860

Would love to learn if I missed anything here :)

**Comment by FeodorFitsner** [comment]
Thank you for the detailed elaboration on this issue!

Having consistency is great and using `--force` does make sense, of course. 😄 Let's close the issue.

**Comment by segiddins** [comment]
Wow, thanks for hunting down the explanation for this, @shayonj!
