### ISSUE TITLE
Specify a RubyGems version?

### ISSUE THREAD

**Issue by ericsullivan** [bundler/bundler#6189]
I apologize if this has been discussed before, but I didn't see it when I searched. Is there any desire to specify a RubyGems version (like you can specify a ruby version) in the Gemfile? This was in the context of bundler-audit and whether it [should audit the ruby version](https://github.com/rubysec/bundler-audit/issues/179), and how it can't do that for the rubygem version (even though CVEs are posted in [ruby-advisory-db](https://github.com/rubysec/ruby-advisory-db/tree/master/libraries/rubygems))

**Comment by segiddins** [comment]
Bundler can't currently do that.

(well, it can, but it's 100% unsupported: `gem "rubygems\0", rubygems_version` would cause the resolver to raise an exception if you're on a different version, but really please don't use that)

**Comment by ericsullivan** [comment]
That's very interesting. I had been thinking something like how you [specify a ruby version](http://bundler.io/v1.12/gemfile_ruby.html)
```
rubygems '~> 2.7.3'
```
Then you could audit the Gemfile with bundler-audit, knowing that bundler would prevent it from loading if the rubygems version at runtime didn't match (and was possibly insecure).

The 100% unsupported method of treating it like a gem is very interesting. I tried it but I got "pathname contains null byte" on 1.16.0, so I'll listen to your advice :)

Is this a worthwhile feature?

**Comment by segiddins** [comment]
It's an interesting feature, but I'm not sold on it being worthwhile. If you just want to enforce a version, having `abort "bad version" unless Gem::VERSION == "2.7.3"` in the Gemfile is sufficient. The `ruby` DSL has been a bit of a pain to maintain, and has had a bunch of corner cases, so I'd rather not introduce another DSL method unless there's a large upside to it

**Comment by ericsullivan** [comment]
I felt the same way, interesting enough to ask, but likely not useful enough to add and maintain. Thank you for considering it, I'll go with the `abort` approach.

**Comment by wlipa** [comment]
If you want something that's a little more flexible with the version specifier, you can do it like this:

    fail "rubygems too old" unless Gem.rubygems_version >= Gem::Version.new('2.7.6')

It'd be nice to have a more elegant way to achieve this.  I agree with the original suggestion.
