### ISSUE TITLE
Make comment with timestamp optional when using bundle add

### ISSUE THREAD

**Issue by cpgo** [bundler/bundler#6193]
This is not a big deal, but I dont think the timestamp comment adds a lot of value on the Gemfile.
At this point its almost certain that the developer will be using some version control system.
`bundle add mygem --timestamp` could be an option

**Comment by arbonap** [comment]
I'd love to take a hand at this 👌🏼

**Comment by indirect** [comment]
This is definitely a leftover from the old `inject` command... we definitely want to change this. Ideally, we will eventually come up with some way for the `add` command to insert new gems into sorted lists of gems, if sorted lists exist, but this is a great first change. :)

**Comment by colby-swandale** [comment]
@arbonap are you still working on this? If not, let us know incase someone else want's to work on this issue.

**Comment by 315tky** [comment]
Hello, I'm looking to start contributing to a ruby project, and have chosen bundler. I'm going to try this "issue" for starters.  

After a quick look, seems the "add" option ( lib/cli/add.rb ) is calling lib/injector.rb and I can see the line in there that creates the timestamp in Gemfile....

**Comment by colby-swandale** [comment]
Probably not, i think we're just going to remove that piece of functionality entirely.

**Comment by colby-swandale** [comment]
This was merged in #6300. Closing.
