### ISSUE TITLE
Cannot install - Get permission error for  ~/.bundle/cache/compact_index folder

### ISSUE THREAD

**Issue by ashish-naik** [bundler/bundler#6196]
- What did you do?
I am using fastlane that is installed as part of Fabric. Trying to install plugin for fastlane using command `bundle exec fastlane add_plugin versioning`

- What  did you expect to happen?
Plugin installed.

- What happened instead?

```
DEBUG [2017-11-30 16:36:37.14]: Checking if there are any plugins that should be loaded...
DEBUG [2017-11-30 16:36:37.29]: Loading 'fastlane-plugin-versioning' plugin
WARN [2017-11-30 16:36:37.40]: Missing gem 'fastlane-plugin-versioning', please add the following to your local Gemfile:
WARN [2017-11-30 16:36:37.40]:
INFO [2017-11-30 16:36:37.40]: ▸ gem "fastlane-plugin-versioning"
WARN [2017-11-30 16:36:37.40]:
ERROR [2017-11-30 16:36:37.40]: Error loading plugin 'fastlane-plugin-versioning': Add 'gem "fastlane-plugin-versioning"' to your Gemfile and restart fastlane
DEBUG [2017-11-30 16:36:37.40]: uninitialized constant Versioning
ERROR [2017-11-30 16:36:37.40]: It seems like you wanted to load some plugins, however they couldn't be loaded
ERROR [2017-11-30 16:36:37.40]: Please follow the troubleshooting guide: https://docs.fastlane.tools/plugins/plugins-troubleshooting/
+------------------------+-----------+------------------+
|                     Used plugins                      |
+------------------------+-----------+------------------+
| Plugin                 | Version   | Action           |
+------------------------+-----------+------------------+
| fastlane-plugin-versi  | undefined | No actions found |
| oning                  |           |                  |
+------------------------+-----------+------------------+

WARN [2017-11-30 16:36:37.83]: Make sure to commit your Gemfile, Gemfile.lock and Pluginfile to version control
Installing plugin dependencies...
INFO [2017-11-30 16:36:37.83]: $ bundle install && echo 'Successfully installed plugins'
There was an error while trying to write to
`/Users/abc/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/versions`. It is likely that you need to grant
write permissions for that path.
```

How to get rid of this issue? I searched a lot and reinstalled bundler but no success.

My environment

- MacOS High Sierra
- Ruby 2.4.2
- Fabric
- Fastlane 2.67.0 via Fabric
- Seems Fabric comes with Ruby 2.2
- Bundler 1.16
- rbenv 1.1.1

Running bundler instal also gives same error.

There was an error while trying to write to
`/Users/ashishn/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/versions`. It is likely that you need to grant
write permissions for that path

**Comment by colby-swandale** [comment]
You need to review the file permissions in `/Users/ashishn/.bundle/cache/compact_index` and make sure the user running `bundler` can read/write all the files/folders.

**Comment by ashish-naik** [comment]
Which I understand and in some posts suggestions were made to Grant access to folder that some people advised against. 
See this post https://github.com/bundler/bundler/issues/5211

Apparently this was fixed but I am facing it.  
Isn't the installation of bundler supposed to take care of it?

**Comment by ashish-naik** [comment]
@colby-swandale please advise how do i resolve this issue. Do i need to raise it in another forum?

**Comment by colby-swandale** [comment]
> Which I understand and in some posts suggestions were made to Grant access to folder that some people advised against.

Yes, you need to grant the user that is running bundler read/write permissions to `/Users/ashishn/.bundle/cache/compact_index`

> people advised against.

I advised against allow all users & groups read, write and execute permissions. You only should grant read/write permissions to only the user/group that is running Bundler.

> Apparently this was fixed but I am facing it

What's the output of `bundler env`?

**Comment by ashish-naik** [comment]
Output of bundler env

`## Environment

```
Bundler       1.16.0
  Platforms   ruby, x86_64-darwin-17
Ruby          2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin17]
  Full Path   /Users/ashishn/.rbenv/versions/2.4.2/bin/ruby
  Config Dir  /Users/ashishn/.rbenv/versions/2.4.2/etc
RubyGems      2.6.13
  Gem Home    /Users/ashishn/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0
  Gem Path    /Users/ashishn/.gem/ruby/2.4.0:/Users/ashishn/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0
  User Path   /Users/ashishn/.gem/ruby/2.4.0
  Bin Dir     /Users/ashishn/.rbenv/versions/2.4.2/bin
Tools
  Git         2.14.3 (Apple Git-98)
  RVM         not installed
  rbenv       rbenv 1.1.1

  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2017-10-31
Git SHA           10f20fa33
Released Version  true
````

**Comment by quieterkali** [comment]
Please any idea about how to solve this? i am facing the same problem.

**Comment by colby-swandale** [comment]
@ashish-naik is this still an issue you're experiencing?

**Comment by ashish-naik** [comment]
@colby-swandale  I changed folder permission as you had advised and was able to install plugin.

**Comment by FloorD** [comment]
Having the same issues, how to I grant bundler folder permission?
For my immediate use case `sudo` to install the gems needed, but I'm sure there is a more gracious solution.

**Comment by hacklock** [comment]
chmod 777 /home

**Comment by jbshirk** [comment]
on MacOS 10.12.6 I navigated to ~/ and changed the permissions on .bundle to read and write, recursively to all contents. This also revealed that an older installation of bundler had already created a rubygems. file in compact_index about a year ago, but did so in a manner that left the whole structure as read only. Now the error is eliminated.
