### ISSUE TITLE
Creating own gem, how to run automatically every time any code change in file

### ISSUE THREAD

**Issue by gkmrakesh** [bundler/bundler#6198]
Hello,

Sorry if it is a repeated question!!

I am creating my own gem, i want to know is there any way to run my gem locally every time new code get added.

Thanks in advance,
Rakesh.

**Comment by colby-swandale** [comment]
@gkmrakesh I'm not sure what you mean, can you explain a bit more?

**Comment by cpgo** [comment]
If I understood correctly you want to reference you own gem on another project Gemfile.
The bundler docs give this example.
`gem 'extracted_library', :path => './vendor/extracted_library'`

**Comment by gkmrakesh** [comment]
@colby-swandale,
i want to autorun local gem i am creating as soon as i make any code changes to /lib folder, to see the result immediately i.e i want to see the result of my changes as soon as i add some code.

just like npm-watch, for example.

@cpgo,
Sorry, i am expected to run gem as soon as i make any code change to any file in /lib folder, so that my development process will be faster for gem creation

currently i am doing it like,
Step 1: Make changes to /lib folder of my gem which i am creating
Step 2: From terminal running "gem xyz.rb"

**Comment by errm** [comment]
Guard is a common tool used to achieve this sort of behaviour in Ruby projects. Often people use it to run there specs whenever a file is changed. If you are developing a gem you should be able to add guard as a development dependency to your .gemspec file:

```ruby
spec.add_development_dependency 'guard'
```

Take a look at the documentation on the guard webpage:
http://guardgem.org/

**Comment by colby-swandale** [comment]
This seems like this has been answered. Closing

**Comment by gkmrakesh** [comment]
@errm Thanks for your answer.
