### ISSUE TITLE
LoadError ... bundler-1.16.1/exe/bundle

### ISSUE THREAD

**Issue by wintersolutions** [bundler/bundler#6227]
All my gitlab CI builds fail with the new bundler version 1.16.1 with the following error when I use `bundle exec`:

```
/usr/local/bundle/bin/bundle:104:in `load': cannot load such file -- /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/exe/bundle (LoadError)

	from /usr/local/bundle/bin/bundle:104:in `<main>'
```

Downgrading to version 1.16.0 is working. Running `bundle install` beforehand is working. I can't reproduce the error on my local machine with 1.16.1.

The build runs on the `ruby:2.4.2` docker image.

**Comment by hsbt** [comment]
What's version of your RubyGems? 

It seems RubyGems problem. https://github.com/rubygems/rubygems/issues/2123

**Comment by wintersolutions** [comment]
```
gem -v
2.7.3
```
I tried updating to 2.7.4 but the error remains. When I run `gem pristine bundler` before executing, the error remains.

**Comment by wintersolutions** [comment]
Update: the `ruby:2.5.0` docker image has just been released and I can not reproduce the bug with it. Maybe we can close this and chalk it up to the `ruby:2.4.2` docker image having issues?

**Comment by segiddins** [comment]
👍 . Let us know if it re-surfaces and we can re-open.

**Comment by jasonkarns** [comment]
I'm experiencing the same issue on ruby 2.5.1 via homebrew.

```
$ ruby -v
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]
$ gem -v
2.7.6
$ gem update --system
Latest version already installed. Done.
$ gem pristine bundler
Restoring gems to pristine condition...
Skipped bundler-1.16.1, it is a default gem
```

**Comment by jasonkarns** [comment]
Workaround was to install bundler explicitly instead of using the RG-default version.

**Comment by bhagat19** [comment]
I am having a similar issue with 

$ ruby -v
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]
$ gem -v
2.7.6

@jasonkarns , the updated bundler's version is 1.16.1

How can i install the bundler explicitly?

**Comment by bhagat19** [comment]
I had a similar issue with the following configuration

```
$ ruby -v
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin16]
$ gem -v
2.7.6
```

However, updating the bundler did help.

`gems install bundler`

updated the bundler from 1.16.1 to 1.16.2
Seems there is an issue with **1.16.1**

**Comment by edtamarin** [comment]
I ma experiencing this issues as well. I am using Redmine, and bundler is needed to install its plugins. My configuration:
```
$ ruby -v
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]
$ gem -v
2.7.5
```
Running a bundler command gives:

```
$ bundle install --without development test --no-deployment
Traceback (most recent call last):
        1: from /usr/local/bin/bundle:23:in `<main>'
/usr/local/bin/bundle:23:in `load': cannot load such file -- /usr/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/exe/bundle (LoadError)
```

Running `gem install bundler` installed the latest version (2.0.1) but somehow it still relies on the old file. Any suggestions?

**Comment by mcmichels** [comment]
Exactly the same error message as @edtamarin 
SetUp a compltetlya new parrotOS. Updated all packages. Installed Bundler and ran 'bundler install'

Error:
```
$bundle install
Traceback (most recent call last):
	1: from /usr/local/bin/bundle:23:in `<main>'
/usr/local/bin/bundle:23:in `load': cannot load such file -- /usr/share/rubygems-integration/all/gems/bundler-1.17.3/exe/bundle (LoadError)

```


Then i uninstalled bundler and re-installed it. Same error message.
```
$ruby -v
ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux-gnu]
```

```
$gem -v
2.7.6
```

**Comment by edtamarin** [comment]
After some digging, I found out that running `gem update -- system` seemed to do the trick.

**Comment by mcmichels** [comment]
Problem solved myself:
[ ] sudo gem update --system
[ ] sudo gem uninstall bundler
[ ] sudo gem install bundler
[ ] bundle install

Now it seems working

**Comment by ice1000** [comment]
For me, `rm Gemfile.lock` and rerun `bundle install` solves the problem

**Comment by dctanner** [comment]
I booted a fresh AWS Lightsail Ubuntu 18.04, ran:
`Ubuntu 18.04 or later with:

sudo apt-get update
sudo apt-get install ruby2.5 libruby2.5 ruby2.5-dev bundler \
                     libmagickwand-dev libxml2-dev libxslt1-dev nodejs \
                     apache2 apache2-dev build-essential git-core phantomjs \
                     postgresql postgresql-contrib libpq-dev postgresql-server-dev-all \
                     libsasl2-dev imagemagick libffi-dev libgd-dev libarchive-dev libbz2-dev
sudo gem2.5 install bundler`

Then running `bundler` gave the same LoadError.

Is there something wrong with the ubuntu bundler package?
