### ISSUE TITLE
Upgrade to 1.16 to blocks deployment to Elastic Beanstalk Ruby platform

### ISSUE THREAD

**Issue by januszm** [bundler/bundler#6242]
Upgrading to `1.16` (both 1.16.0 and 1.16.1) makes it impossible to deploy Rails apps to Elastic Beanstalk with the following error:

```
There was an error while trying to write to `/var/app/ondeck/.bundle/config`. It
  is likely that you need to grant write permissions for that path.
```

In Elastic Beanstalk platform, gems are installed for `root` user, but the application is owned and run by `webapp` user. Webapp is a `nologin' user with no `home` directory. 

Here's an excerpt from `gem env`:
```
  - GEM PATHS:
     - /opt/rubies/ruby-2.4.2/lib/ruby/gems/2.4.0
     - /root/.gem/ruby/2.4.0
```

When using bundler version `1.15` the `config` file is still owned by root. But it seems like bundler is not trying to write to the `.bundle/config` file (and that's OK, there's no change in configuration during the deployment).

Any chance there's an unnecessary attempt to 'save' the config file without change?

**Comment by colby-swandale** [comment]
Hi, Firstly - it's *strongly* [recommended](https://github.com/bundler/bundler/blob/master/man/bundle-install.ronn#L211) to not install your gems as root. Which command are you performing that is causing this error?

**Comment by januszm** [comment]
@colby-swandale it's how Amazon's Elastic Beanstalk is designed. It is not 'me' performing any command. It's a part of the standard `eb deploy` (deployment) process. Amazon Elastic Beanstalk is quite popular and I believe it works that way for quite a long time already (root owns gems).  

From what I remember, EB unpacks the app bundle (zip created with `git archive` command) to the 'ondeck' dir, runs several preparation scripts (eg. database migration, assets precompilation, bundle install) and then runs the ruby app. 

Like I wrote earlier, it *seems* that after upgrade to 1.16, bundler tries to write *something* to the .bundle/config file. This didn't happen on version 1.15 and older.

**Comment by colby-swandale** [comment]
Thanks for the information about Amazon Benstalk. Do you have any information on what command bundler is running for the error to occur?

**Comment by segiddins** [comment]
Could you also provide the output of running `DEBUG=1 bundle install` ? Thanks!

**Comment by greghopkins** [comment]
Any thoughts on this? I'm experiencing the same issue. And since the bundle install and assets precompilation happen together (although different indexed steps), I cannot just change the permissions on the folder - as bundle install runs AFTER any of the things in `.ebextensions`. 

I supposed I could shut off precompilation and add it in as some sort of custom command in `.ebextensions` - but that also feels wrong.

**Comment by januszm** [comment]
@segiddins 

```
bash-4.2$ DEBUG=1 bundle install
`/root` is not writable.
Bundler will use `/tmp/bundler/home/ec2-user' as your home directory temporarily.
Running `bundle install` with bundler 1.16.0
There was an error while trying to write to `/var/app/ondeck/.bundle/config`. It is likely that you need to grant write permissions
for that path.
Bundler::PermissionError: There was an error while trying to write to `/var/app/ondeck/.bundle/config`. It is likely that you need to grant write permissions for that path.
```

```
bash-4.2$ ls -la
drwxr-xr-x 14 webapp webapp   4096 Feb 16 13:36 .
drwxr-xr-x  5 root   root     4096 Feb 16 13:36 ..
drwxr-xr-x 16 webapp webapp   4096 Feb 16 13:30 app
-rw-r--r--  1 webapp webapp    329 Feb 16 13:30 .babelrc
drwxr-xr-x  2 webapp webapp   4096 Feb 16 13:30 bin
drwxr-xr-x  2 root   root     4096 Feb 16 13:36 .bundle
drwxr-xr-x  6 webapp webapp   4096 Feb 16 13:30 config
```

`bundle install` is making an attempt to save to the `.bundle/config` file, earlier versions didn't (I suppose, since there were no errors in the same situation)

**Comment by januszm** [comment]
@colby-swandale actually `bundle exec rake assets:precompile` fails with the same error, which may indicate that this is the command that is causing problems in ElasticBeanstalk environment. I can't see the direct link between the actual command and the error. Both `bundle exec ...` and `bundle install` cause this problem.

**Comment by segiddins** [comment]
Dang, I thought running with `DEBUG=1` would also cause ruby to print out the line that the exception was coming from. If you're comfortable monkey-patching your local bundler source (you can `gem pristine bundler` afterwards), could you make the following change?

```diff
diff --git a/lib/bundler/friendly_errors.rb b/lib/bundler/friendly_errors.rb
index ae3299a7c..9ddd748c3 100644
--- a/lib/bundler/friendly_errors.rb
+++ b/lib/bundler/friendly_errors.rb
@@ -125,6 +125,7 @@ module Bundler
   rescue SignalException
     raise
   rescue Exception => e
+    raise
     FriendlyErrors.log_error(e)
     exit FriendlyErrors.exit_status(e)
   end

```

**Comment by januszm** [comment]
@segiddins here you go:

```bash
  /opt/rubies/ruby-2.4.3/lib/ruby/site_ruby/2.4.0/bundler/shared_helpers.rb:120:in `rescue in filesystem_access': There was an error while trying to write to `/var/app/ondeck/.bundle/config`. It is likely that you need to grant write permissions for that path. (Bundler::PermissionError)
  	from /opt/rubies/ruby-2.4.3/lib/ruby/site_ruby/2.4.0/bundler/shared_helpers.rb:115:in `filesystem_access'
  	from /opt/rubies/ruby-2.4.3/lib/ruby/site_ruby/2.4.0/bundler/settings.rb:351:in `set_key'
  	from /opt/rubies/ruby-2.4.3/lib/ruby/site_ruby/2.4.0/bundler/settings.rb:126:in `set_local'
  	from /opt/rubies/ruby-2.4.3/lib/ruby/site_ruby/2.4.0/bundler/settings.rb:114:in `set_command_option'
  	from /opt/rubies/ruby-2.4.3/lib/ruby/site_ruby/2.4.0/bundler/cli/install.rb:192:in `normalize_settings'
  	from /opt/rubies/ruby-2.4.3/lib/ruby/site_ruby/2.4.0/bundler/cli/install.rb:51:in `run'
  	from /opt/rubies/ruby-2.4.3/lib/ruby/site_ruby/2.4.0/bundler/cli.rb:224:in `block in install'
  	from /opt/rubies/ruby-2.4.3/lib/ruby/site_ruby/2.4.0/bundler/settings.rb:136:in `temporary'
  	from /opt/rubies/ruby-2.4.3/lib/ruby/site_ruby/2.4.0/bundler/cli.rb:223:in `install'
  	from /opt/rubies/ruby-2.4.3/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  	from /opt/rubies/ruby-2.4.3/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
  	from /opt/rubies/ruby-2.4.3/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
  	from /opt/rubies/ruby-2.4.3/lib/ruby/site_ruby/2.4.0/bundler/cli.rb:27:in `dispatch'
  	from /opt/rubies/ruby-2.4.3/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
  	from /opt/rubies/ruby-2.4.3/lib/ruby/site_ruby/2.4.0/bundler/cli.rb:18:in `start'
  	from /opt/rubies/ruby-2.4.3/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/exe/bundle:30:in `block in <top (required)>'
  	from /opt/rubies/ruby-2.4.3/lib/ruby/site_ruby/2.4.0/bundler/friendly_errors.rb:122:in `with_friendly_errors'
  	from /opt/rubies/ruby-2.4.3/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/exe/bundle:22:in `<top (required)>'
  	from /var/app/ondeck/bin/bundle:3:in `load'
  	from /var/app/ondeck/bin/bundle:3:in `<top (required)>'
  	from ./bin/webpack:12:in `load'
  	from ./bin/webpack:12:in `<main>'
   (Executor::NonZeroExitStatus)
```

**Comment by januszm** [comment]
@segiddins thanks, good catch!

Amazon Elastic Beanstalk sets the `without` setting via `BUNDLE_WITHOUT` environment variable.

I suspect that the recent versions of the Elastic Beanstalk Ruby platform (v2.6.3-v.2.7.0) were broken, all custom configuration variables are not available in those versions. One of them is `BUNDLE_WITHOUT` and probably that's why `bundler` complained about permissions.

cc @greghopkins , this seems to be resolved with version 2.7.1, all environment variables are available again.

I'm closing this issue since it was actually on AWS end.

**Comment by januszm** [comment]
Unfortunately, after changing the platform to 2.7.1 we have access to `BUNDLE_WITHOUT` env var again, but still , `bundler` makes unnecessary attempt to write to file `/var/app/ondeck/.bundle/config`

**Comment by segiddins** [comment]
Can you share the output of `bundle env` before running `bundle install`? Additionally, are you passing any arguments to `bundle install`? I'm just trying to understand the steps I need to take to reproduce this in a test -- thanks for bearing with me

**Comment by laurentqro** [comment]
+1

**Comment by cySheng** [comment]
+ 1

**Comment by MarkChanner** [comment]
+1
Here is the output from running _bundle env_:

## Environment

```
Bundler       1.16.0
  Platforms   ruby, x86_64-linux
Ruby          2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
  Full Path   /opt/rubies/ruby-2.5.1/bin/ruby
  Config Dir  /opt/rubies/ruby-2.5.1/etc
RubyGems      2.7.6
  Gem Home    /home/ec2-user/.gem/ruby/2.5.1
  Gem Path    /home/ec2-user/.gem/ruby/2.5.1:/opt/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0
  User Path   /home/ec2-user/.gem/ruby/2.5.0
  Bin Dir     /home/ec2-user/.gem/ruby/2.5.1/bin
Tools
  Git         not installed
  RVM         not installed
  rbenv       not installed
  chruby      0.3.9
```

## Bundler Build Metadata

```
Built At          2017-10-31
Git SHA           10f20fa33
Released Version  true
```

## Bundler settings

```
without
  Set via BUNDLE_WITHOUT: [:test, :development]
```

**Comment by januszm** [comment]
This seems to be resolved with the recent Elastic Beanstalk platform upgrade (2.8.0). I'm not sure how exactly though.

**Comment by Owohlet** [comment]
Did anyone find a solution for this?

**Comment by januszm** [comment]
@Owohlet upgrading your Elastic Beanstalk platform to the most recent Ruby stack helps
