### ISSUE TITLE
Gemspec template should explain how `spec.files` works

### ISSUE THREAD

**Issue by ragesoss** [bundler/bundler#6246]
I think it would be useful if the gemspec created by `bundle gem <gemname>` had some comments explaining how the `spec.files` configuration works.

I recently created my first gem, and the default files config based on shelling out to `git ls-files -z` was opaque to me... until I spent quite a while trying to figure out why a new file I added to the gem wasn't being copied over when I ran `rake install`. (The answer was that I had not yet added the file to git... which I hadn't done because the gem wasn't working as intended... which was because I hadn't added it to git!)

Once I realized that the installed gem will include all the files in an array assigned to `spec.files` in the gemspec, it was relatively easy to figure out what the default git-based configuration was doing, and why it made sense as one option for defining the gem's files.

Adding some comments explaining what `git ls-files -z` is doing, and how `spec.files` works to define the actual code included in the installed gem, would probably be helpful for other newbie gem builders. It looks like this would just require adding some comments to `newgem.gemspec.tt`. I'd gladly draft a PR if this seems like a good idea.

**Comment by colby-swandale** [comment]
We have a [guide for using bundler](http://bundler.io/v1.16/guides/creating_gem.html) to create a rubygem. Maybe we should print a banner with the link to the guide when you generate the gem to draw peoples attention to it.

**Comment by ragesoss** [comment]
That's a good idea, although not a good solution to the discoverability of `spec.files`, in my opinion.

I started from that guide and found it quite useful, but it's rather long, with lots of detailed sections that are about specific use cases and examples (like building a CLI), and the part that alludes to how `git ls-files -z` isn't really aimed teaching the reader about how to define the files in the gem... it's the in 'release your gem' section at the end, and seems to be more about getting your files committed and released than a necessary step to getting it working in the first place. (This makes sense; `spec.files` is probably not a topic that merits more detail in the guide.)

**Comment by 315tky** [comment]
I will pick this up and take a stab at it
