### ISSUE TITLE
Possibly infinite deadlock when using `bundle outdated` (regression?)

### ISSUE THREAD

**Issue by 2called-chaos** [bundler/bundler#6251]
I just updated bundler from 1.15.4 to most recent version 1.16.1 and suddenly `bundler outdated` deadlocks on resolving dependencies.

https://gist.github.com/2called-chaos/2c771d50d5201b1e6a221436bdc8aec7

The app is quite monolithic and has private gems but I boiled it down to a somewhat small example that is reproducible on at least my machine:

https://github.com/2called-chaos/bundler_dependency_deadlock_test

I have to admit though, it's quite an edge case by the looks of it and I could easily workaround the issue but I guess you might be interested.

**Note:** This issue was discovered by using a gem over git, it's the same with using path, I haven't tested a "normal" gem. I can reproduce it on at least Ruby 2.4(.3) and 2.5

The problem goes away if:

* the only dependency of `a_gem` (that is `pry-nav`) is directly in the Gemfile
* the `guard-rspec` dependency is removed
* the `pry` dependency is removed from the Gemfile (then being resolved as a dependency from either pry-nav or rspec-guard)

My idea was that there is obviously something going on with the resolution of `pry` as all parts of the equation have a pry dependencies. Weirdly enough `b_gem` was my attempt to just have the same pry requirement as guard (via guard-rspec) and then remove guard-rspec but the problem goes away. So it appears to be a combination of version restrictions and where they are coming from (since putting the virtually same thing directly into the Gemfile fixes it)

I'm lost here, maybe someone more familiar with the dependency logic can explain what happens here?

**Comment by colby-swandale** [comment]
I cloned your test repo, ran `bundler install` (i had to change the path to `a_gem`) and then ran `bundler outdated` which generated a report after a few seconds. Can you verify this is the same environment your testing?

```
# Gemfile
source 'https://www.rubygems.org'

# If I remove this it works
gem 'pry'

# replication gem of original problematic gem
gem 'a_gem', path: './a_gem'

# attempt to copy the same pry dependency as rspec-guard but the problem doesn't occur
#gem 'b_gem', path: '/tmp/bundler_test/b_gem'

# a_gem only adds pry-nav as dependency, if I put it here it suddenly works
#gem 'pry-nav'

# If I remove this it works
gem 'guard-rspec'
```

```
# Gemfile.lock
PATH
  remote: a_gem
  specs:
    a_gem (2.0.0)
      pry-nav

GEM
  remote: https://www.rubygems.org/
  specs:
    coderay (1.1.2)
    diff-lcs (1.3)
    ffi (1.9.18)
    formatador (0.2.5)
    guard (2.14.2)
      formatador (>= 0.2.4)
      listen (>= 2.7, < 4.0)
      lumberjack (>= 1.0.12, < 2.0)
      nenv (~> 0.1)
      notiffany (~> 0.0)
      pry (>= 0.9.12)
      shellany (~> 0.0)
      thor (>= 0.18.1)
    guard-compat (1.2.1)
    guard-rspec (4.7.3)
      guard (~> 2.1)
      guard-compat (~> 1.1)
      rspec (>= 2.99.0, < 4.0)
    listen (3.1.5)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
      ruby_dep (~> 1.2)
    lumberjack (1.0.12)
    method_source (0.8.2)
    nenv (0.3.0)
    notiffany (0.1.1)
      nenv (~> 0.1)
      shellany (~> 0.0)
    pry (0.10.4)
      coderay (~> 1.1.0)
      method_source (~> 0.8.1)
      slop (~> 3.4)
    pry-nav (0.2.4)
      pry (>= 0.9.10, < 0.11.0)
    rb-fsevent (0.10.2)
    rb-inotify (0.9.10)
      ffi (>= 0.5.0, < 2)
    rspec (3.7.0)
      rspec-core (~> 3.7.0)
      rspec-expectations (~> 3.7.0)
      rspec-mocks (~> 3.7.0)
    rspec-core (3.7.1)
      rspec-support (~> 3.7.0)
    rspec-expectations (3.7.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.7.0)
    rspec-mocks (3.7.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.7.0)
    rspec-support (3.7.0)
    ruby_dep (1.5.0)
    shellany (0.0.1)
    slop (3.6.0)
    thor (0.20.0)

PLATFORMS
  ruby

DEPENDENCIES
  a_gem!
  guard-rspec
  pry

BUNDLED WITH
   1.16.1
```

```
› bundler outdated
Fetching gem metadata from https://www.rubygems.org/.............
Fetching gem metadata from https://www.rubygems.org/..
Resolving dependencies..........

Outdated gems included in the bundle:
  * method_source (newest 0.9.0, installed 0.8.2)
  * pry (newest 0.11.3, installed 0.10.4) in groups "default"
  * slop (newest 4.6.1, installed 3.6.0)
```

What's the output of `bundler outdated --verbose` as well?

**Comment by 2called-chaos** [comment]
Hmm maybe I was a bit impatient when removing gems from the Gemfile to find a minimal example. I do have the exact same Gemfile.lock when I change the path to relative like you did and it does actually resolve but it's more like 20 seconds while hogging one core of my i7-4790K with 100%. 

Output of a verbose run: https://gist.github.com/2called-chaos/425cd5376f277a385bdf3fe76884fe4d

I added a bunch of gems again and I might be able to reduce the list further but I don't know how long I should wait for bundler. With the following Gemfile (LXX-LYY added) I get the following output (note I interrupted the process after 15 minutes).

Branch: https://github.com/2called-chaos/bundler_dependency_deadlock_test/tree/more_dependencies
Changes: https://github.com/2called-chaos/bundler_dependency_deadlock_test/commit/8eb1fe09ae1fcdef3057a63e5ee3a20162950440
Output: https://gist.github.com/2called-chaos/5b5068d8d701e86aea9437c20b2048ab

I don't know if it's relevant but I'm working with OS X.

**Comment by 2called-chaos** [comment]
As a little follow up, due to different problems with the apparently outdated `pry-nav`, we removed the dependency from our "devkit" gem and replaced it with `pry-byebug` and the problem vanished. Dependency resolution now takes 2-3 seconds.

I also validated that others on the team (all on different versions of macOS) encountered the same issue before the change.

My assumption: Something with the pry version restriction (pry-nav was the only one restricting the max. version of pry) in combination with some other factors (dependency from a gem instead of directly in the Gemfile) and possibly some OS quirk lead to the dependency resolution being extremely slow. 

As I suspected it seems to be an edge case (though not apparent in older versions of bundler) so it's your decision whether you want to further investigate this, I'm still here to verify, etc.

**Comment by segiddins** [comment]
On https://github.com/2called-chaos/bundler_dependency_deadlock_test/tree/more_dependencies, this resolves in a couple of seconds with bundler master vs 1.16.1, so I think we can close this out -- thanks for the excellent reproduction case, though!
