### ISSUE TITLE
installing native extensions and bundle

### ISSUE THREAD

**Issue by ruudgrosmann** [bundler/bundler#6259]
In order to install a bundle on my production server, I use 'bundle package' on the development server together with 'bundle install --local --deployment' on the productionserver.
This works very well as long as there are no native extensions. If there are native extensions, the production server tries to compile them. Which I don't want.

In issue #5668, I read there is a possiblity to precompile native extensions on the development server and copy them to the production machine.
That is good news, but I am afraid I am a bit too inexperienced to get it working. Hopefully you can advice me.

For example, one of the gems that uses native extensions is nokogiri. My Gemfile contains nokogiri. Bundle install uses the gem-files in vendor/cache to install them, but stops at nokogiri with 'Installing nokogiri 1.8.1 with native extensions'

I have done this: 

- DEV: created a vendor-directory with 'bundle package' and copied it to the production server
- DEV: located the gem with prebuilt extensions and all and made tarfile. 
- PROD: bundle install. Interrupted the process at 'installing with native extensions' for nokogiri
- PROD: extracted tarfile in 'vendor/bundle/....' at the place where the nokogiri gem was partly installed.
- bundle install again.

I have tried the following too:

- DEV: make a tarfile of vendor/ruby, which is what bundle install on production would create
- PROD: extracted tarfile, so that PROD has the same vendor-directory as DEV
- PROD: copied .bundle/config from DEV

However, bundle install does not notice the extensions are already there and tries to rebuild them again. In the second try, where bundle has all the files in my expectation needs, 'bundle exec' does not see the files in the vendor/ruby/2.4.0/bin directory. It seems bundle exec needs some configuration that bundle install provides.
Is it possible to install the package with bundle install and skip the building of native extensions and then install the native extensions for the gems that use native extensions with tarfiles? Or is there a better way to do this? Is there a way to make bundle aware of pre-installed files?

thanks, Ruud

**Comment by ruudgrosmann** [comment]
I found out that the second method actually _does_ work. It even is not necessary to have the .bundle directory in place. It seems important that the vendor directory is installed _as a whole_. It still is not possible to do a bundle install (which partly fails),  only place tarfiles of directories of the failed gems in bundle/2.0.4/gems and try bundle install again. Bundle will then try to install the failed gems again, although the result is there. There must be more files in the bundle/ruby directory (apart from the gem directory) that needs to be installed.

I would really like to be able to pre-install the needed file from selected gems before the first bundle install as well as put the bundle package in vendor/cache, after which `bundle install --local --deployment` uses the package and skips the pre installed gems because they are already there.

If that is not possible, I can always resort to the installing the bundle with a tarfile of the complete vendor/bundle directory, but I rather use as much of normal deployment process as possible.

At this point, maybe the output of `bundle env` is not that relevant any more. I can always provide it if still  wanted.

Ruud

**Comment by colby-swandale** [comment]
are you using a different OS, ruby verison between your production and dev?

**Comment by ruudgrosmann** [comment]
No, they are the same. The only difference is that the dev machine is an virtualbox machine and the production machine is a docker image. But since copying the complete vendor directory actually works, I assume this cannot be the reason for bundle to decide they should be recompiled.

I suspect bundle take timestamps or files into account that live outside the gems directory.

Ruud

**Comment by ruudgrosmann** [comment]
To be sure it is nothing with versions: I compiled the extensions in a docker container, made a tarfile of two gem-directories that were compiled. Then I used the tarfile

**Comment by ruudgrosmann** [comment]
Do I understand correctly it is not possible in any way to preinstall individual gems in the bundle directory that are previously built on a machine with the same environment?

Ruud

**Comment by ruudgrosmann** [comment]
Found it. It is possible to pre install a gem so that bundle install will not try to rebuild it.

In order to do that, on the development machine 

- go to vendor/bundle/ruby/VERSION
- create a tarfile with three components: for gem B (B including version number) this would be `tar cvf /tmp/B.tar gems/B extensions/ARCH/VERSION/B specifications/B.gemspec`
- this tarfile can be extracted on the target machine in the same directory prior to issuing `bundle install --deployment`. Bundle wil _not_ try to build it again.

Ruud

**Comment by eyusupov** [comment]
Came here looking how to cache native extensions. My solution was to use 
```
bundle config cache_all true
bundle install --path  <cache_path>
```
to populate the cache

and then
```
bundle config cache_path <cache_path>
bundle install
```
