### ISSUE TITLE
Running `bundle pristine` on a git source gem doesn't rebuild the native extension

### ISSUE THREAD

**Issue by wagenet** [bundler/bundler#6294]
I believe this can be fixed by adding the following before https://github.com/bundler/bundler/blob/v1.16.1/lib/bundler/cli/pristine.rb#L33:

```rb
FileUtils.rm_rf spec.extension_dir if spec.have_extensions?
```

I'm happy to send a PR if this sounds like the correct thing to do.

**Comment by colby-swandale** [comment]
Can you please provide us more information on how `bundle pristine` is not rebuilding native extensions and provide us with examples?

**Comment by colby-swandale** [comment]
Can you provide us with more information on how it's not working the way you expect with some examples?

**Comment by wagenet** [comment]
@colby-swandale if you look at the code, you'll see that it only removed the main source directory, not the built extension. That means that the reinstall won't rebuild the native extension.

**Comment by colby-swandale** [comment]
`bundle pristine` does rebuild native extensions even though it's not clear by just looking at the code, this is done by RubyGems when we reinstall the gem.

```
› ls -la nokogiri
-rwxr-xr-x  1 c  staff  2295772  8 Feb 19:49 nokogiri.bundle*

› bundle pristine
Installing mini_portile2 2.3.0
Installing nokogiri 1.8.2 with native extensions

› ls -la nokogiri
total 4488
-rwxr-xr-x  1 c  staff  2295772 16 Feb 07:25 nokogiri.bundle*
```
I've also used `bundle pristine` to rebuild `charlock_holmes` whenever `libicudata` is updated to a new version so i know for certain that the extension is compiled again.

**Comment by wagenet** [comment]
@colby-swandale it doesn't happen for Git gems however.

**Comment by colby-swandale** [comment]
Thanks for clarifying, yes this needs to be fixed. 

PS. A quick suggestion: Please explain in as much detail as possible about what the problem is in the issue description. Saying "bundle pristine doesn't rebuild extensions" offers no information for us and makes work for us in trying to figure out what you're talking about. See #6276 for an example on a great example of explaining an issue in Bundler.

Thanks

**Comment by wagenet** [comment]
@colby-swandale I've updated the title to something more descriptive, I believe. In my local tests, the fix I proposed in the initial issue description solves the problem. Should I submit a PR with this change?

**Comment by colby-swandale** [comment]
Yes please.

**Comment by wagenet** [comment]
@colby-swandale see PR for partial solution
