### ISSUE TITLE
Bundler fails to run command line tool (Ubuntu 16.04)

### ISSUE THREAD

**Issue by SeedyROM** [bundler/bundler#6296]
Working on a little project in rails and I noticed this morning that when I run bundle I get this error.
```
/usr/local/bin/bundle:23:in `load': cannot load such file -- /usr/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/exe/bundle (LoadError)
from /usr/local/bin/bundle:23:in `<main>'
```
My currently installed versions are:
```
☁  ~  ruby -v
ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]
☁  ~  gem -v
2.7.5
☁  ~  gem list

*** LOCAL GEMS ***
...
bundler (default: 1.16.1, 1.16.0, 1.11.2)
...
```

Can't find much information and even tried using an older version of bundler.
**I'll fork the repo ASAP.**

**Comment by SeedyROM** [comment]
I had an issue with my path trying to access and older version of ruby's gems.
This was my configuration issue!

**Comment by jafamo** [comment]
can you explain howto resolved ?
