### ISSUE TITLE
Errno::EACCES: Permission denied @ rb_sysopen when using systemd to start sharetribe service

### ISSUE THREAD

**Issue by arvindnm** [bundler/bundler#6297]
Hi all,
  I am new to sharetribe and dont have any experience with ruby etc. I followed the steps to setup sharetribe from here:
https://freedif.org/how-to-install-sharetribe-for-ubuntu-16-04/

When i start the services manually I do not see such issues. I see the below errors when i connect to the terminal again and check the status using 'journalctl -u sharetribe.service'.

I checked the permissions for the path and the files, i did chmod 777 so that all users have permissions. Any thoughts?

Feb 19 03:07:16 ubuntu-xenial-1 sharetri[4628]: W, [2018-02-19T03:07:16.099853 #4775]  WARN -- : Failed creating logger for file /home/arvind_nm/sharetribe/sharetribe/lo
Feb 19 03:07:16 ubuntu-xenial-1 sharetri[4628]: W, [2018-02-19T03:07:16.102594 #4775]  WARN -- : Errno::EACCES: Permission denied @ rb_sysopen -  /home/arvind_nm/sharetribe/sharetribe/log/newrelic_agent.log
Feb 19 03:07:16 ubuntu-xenial-1 sharetri[4628]: D, [2018-02-19T03:07:16.102956 #4775] DEBUG -- : Debugging backtrace:
Feb 19 03:07:16 ubuntu-xenial-1 sharetri[4628]: D, [2018-02-19T03:07:16.102956 #4775] DEBUG -- : Debugging backtrace:

**Comment by hsbt** [comment]
It's not bundler's issue. Maybe, You can resolve your problem with https://stackoverflow.com/.
