### ISSUE TITLE
Problems resolving dead git references on a branch in lock file

### ISSUE THREAD

**Issue by deivid-rodriguez** [bundler/bundler#6324]
Sometimes when I have an outdated git reference on a branch in my lock file (because of force-pushing on the branch leaving the sha reference invalid), I start getting the following kind of errors:

```console
$ LC_ALL=C bundle
Fetching gem metadata from https://rubygems.org/.......
Fetching https://github.com/decidim/decidim
fatal: Could not parse object 'cb70aded58b9215a495f0509e49daef930eec478'.
Git error: command `git reset --hard cb70aded58b9215a495f0509e49daef930eec478` in directory
/home/deivid/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/bundler/gems/decidim-cb70aded58b9 has failed.
If this error persists you could try removing the cache directory
'/home/deivid/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/cache/bundler/git/decidim-9495d3039168996748af12c0fdb04debdea10392'
```

I can reliably reproduce this at the moment, but I'm not sure if it's specific to my environment or a consistent reproduction. The steps would be:

```console
git clone https://github.com/podemos-info/decidim-module-votings decidim-votings
git checkout ef92898f56053d631fccaeb4f80bfe7aa4e7359f
LC_ALL=C bundle
```

Could someone confirm that this is specific to my envirnoment?

**Comment by deivid-rodriguez** [comment]
There's a related discussion in https://github.com/bundler/bundler/pull/6308, but I'm reticketing this to keep the discussion on its own issue!

**Comment by segiddins** [comment]
I can make this give a slightly better error message, but you can (in the meantime) run `bundle update decidim --source decidim` or `bundle update decidim decidim-dev` or `bundle update --source decidim`

**Comment by segiddins** [comment]
https://github.com/bundler/bundler/pull/6337 should help give a better error message!

**Comment by deivid-rodriguez** [comment]
Thanks so much @segiddins! :muscle

**Comment by colby-swandale** [comment]
This seems like this has been resolved. Closing.
