### ISSUE TITLE
`bundle update` shows incorrect message when updating git gems

### ISSUE THREAD

**Issue by deivid-rodriguez** [bundler/bundler#6325]
If I have

```ruby
gem "decidim", git: "https://github.com/decidim/decidim"
```

And I run

```
bundle update decidim
```

And that results in `bundler` updating the locked sha1 reference in my lock file, I wouldn't expect `bundler` to display the "Bundler attempted to update decidim but its version stayed the same" message.

Is this a reasonable expectation?

**Comment by colby-swandale** [comment]
That doesn't sound right. A repo to demonstrate this problem would be 👍

**Comment by segiddins** [comment]
Ha! I actually just started on a fix for this issue about half an hour ago, before I even saw it was filed! WIP PR incoming

**Comment by deivid-rodriguez** [comment]
Nice! Thanks @segiddins!!
