### ISSUE TITLE
allow to lock ruby on major version

### ISSUE THREAD

**Issue by mathieujobin** [bundler/bundler#6327]
Hello

instead of doing `ruby '~> 2.3.4'` which `rvm` does not support without setuping custom aliases.
it would be nice and simpler to just set `ruby '2.3'`

but bundler complains the version don't match

`Your Ruby version is 2.3.6, but your Gemfile specified 2.3`

in my opinion, 2.3.x should match 2.3

thanks

**Comment by segiddins** [comment]
Doing `~> 2.3.0` is what will allow any patch version of `2.3` to satisfy the requirement

**Comment by mathieujobin** [comment]
@segiddins the creates an annoyance for people using `rvm` though. 
it will complain `~> 2.3.0` is not a known version

**Comment by mathieujobin** [comment]
of course, the other solution would be to rvm to support it 

https://github.com/rvm/rvm/issues/3717
