### ISSUE TITLE
Invalid contributing guide in bundlerbot welcome message

### ISSUE THREAD

**Issue by benoittgt** [bundler/bundler#6332]
Hello

For example in this message https://github.com/bundler/bundler/pull/6320#issuecomment-370133227, bundlerbot refers to https://github.com/bundler/bundler/blob/master/CONTRIBUTING.md but this link doesn't work anymore. Instead it should point to https://github.com/bundler/bundler/blob/master/doc/contributing/README.md.

It seems the bundlerbot config is private. I was not able to find it. So sorry I can open a PR for this.

**Comment by hmistry** [comment]
Thanks for letting us know. The bot's response is in the `.github` folder.
