### ISSUE TITLE
Document the order that Bundler loads settings

### ISSUE THREAD

**Issue by colby-swandale** [bundler/bundler#6334]
Bundler settings can be configured in a number of different ways but the [bundler-config](https://github.com/bundler/bundler/blob/master/man/bundle-config.ronn) docs do not talk about in which [order Bundler loads this settings](https://github.com/bundler/bundler/blob/master/lib/bundler/settings.rb#L93). Which seems to be not as people expect (local > ENV). This has caused confusion and people have open issues (#6270) about this. This should be something that is documented that makes this clear to the user.

**Comment by rubymorillo** [comment]
Hey @colby-swandale,

Awesome. I'm thinking through this right now and it looks like we have to add a line in the *Description* section, specifically, this graph:

```Executing `bundle config <name> <value>` will set that configuration to the
value specified for all bundles executed as the current user. The configuration
will be stored in `~/.bundle/config`. If <name> already is set, <name> will be
overridden and user will be warned.```

Do you think the following is descriptive enough?

```Bundler loads local configuration settings before it loads environmental variables.```

Is there something missing? Should it instead go inside a different section of that doc?

**Comment by colby-swandale** [comment]
Thanks for grabbing this!

I would document the priority that Bundler uses for all the settings, which is currently: Local Config, Environment Variables, Global Config & Bundler Defaults.

**Comment by rubymorillo** [comment]
@colby-swandale sure thing! It looks like we mention that in the first graph of the bundler-config doc:

```This command allows you to interact with bundler's configuration system.
Bundler retrieves its configuration from the local application (`app/.bundle/config`),
environment variables, and the user's home directory (`~/.bundle/config`),
in that order of priority.```

How about if I worded it like this:

```This command allows you to interact with Bundler's configuration system.

Bundler loads configuration settings in this order:

1. Local config (`app/.bundle/config`)
2. Environmental variables (`ENV`)
3. Global config
4. User's home directory (`~/.bundle/config`)
```

I figure listing them out might make them more obvious to the user. 

BTW I used the settings originally listed in bundler-config. Should I swap out any for Bundler defaults?

**Comment by colby-swandale** [comment]
That looks nice! Only thing is that `Global Config` is `User's home directory (`~/.bundle/config`)`, maybe say `Global Config (~/.bundle/config)`? And then have `Default Config` last.

**Comment by rubymorillo** [comment]
@colby-swandale cool! Just opened up the PR and included your suggested changes: https://github.com/bundler/bundler/pull/6464

**Comment by colby-swandale** [comment]
We normally keep issues open until a PR that fixes them has been merged.

**Comment by rubymorillo** [comment]
Noted 👍🏽
