### ISSUE TITLE
Gemfile.lock is generated differently on different platforms

### ISSUE THREAD

**Issue by mackuba** [bundler/bundler#635]
We've got 4 people working in our team, 2 on Macs, 1 on Linux and 1 on Windows. They all have Bundler either at 1.0.0 final or something very recent (rc5, 6). And here's what happens:
- today I updated the lock file with bundle install on my Mac, and committed the change; a few hours later, the other Mac developer did the same, and his lock file had the Windows gems reversed - e.g.

my commit:

```
json (1.4.6)
json (1.4.6-x86-mingw32)
```

his commit:

```
json (1.4.6-x86-mingw32)
json (1.4.6)
```
- when the Linux developer calls bundle install, it's generated without the Windows versions at all
- when the Windows developer calls bundle install, it's generated with only the Windows versions (so json 1.4.6 generic disappears)

It's not a critical bug, as we can always remove those changes from the diff before committing, but it is very annoying...

**Comment by hasghari** [comment]
This is still happening in our Gemfile.lock. OSX and Ubuntu both running Bundler 1.10.6.
