### ISSUE TITLE
`bundle version` v1.16.1 prints strange "fatal: Not a git repository ...' message

### ISSUE THREAD

**Issue by 907th** [bundler/bundler#6453]
I see strange 'Not a git repo' messages when running `bundle version` command. All other commands (e.g. `bundle install`) do not print this message.

Terminal session:
```
$ \bundle version
fatal: Not a git repository (or any of the parent directories): .git
Bundler version 1.16.1 (2018-03-23 commit )
$ \bundle install
Using rake 12.3.1
Using concurrent-ruby 1.0.5
Using i18n 0.9.5
... omitted
$ which bundle
/Users/laise/.rvm/gems/ruby-2.5.0@my-project/bin/bundle
```

RVM: rvm 1.29.3 (master)
Ruby: ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin17]

**Comment by 907th** [comment]
The source of the problem is [this line](https://github.com/bundler/bundler/blob/master/lib/bundler/cli.rb#L464) which calls `BuildMetadata.git_commit_sha`. But the gem folder has no `.git` dir.

**Comment by 907th** [comment]
I found that packaged Bundler gem (bundler-1.16.1.gem) simply doesn't include `.git` dir. So I think that `bundle version` should avoid to try to extract any git-related info (`BuildMetadata.git_commit_sha`).

**Comment by indirect** [comment]
Thanks for catching this! We definitely shouldn't print that message if there is no `.git` directory.

**Comment by segiddins** [comment]
The released version (1.16.1) has the following (which wont call `git` at all, since the ivar is already set)

```ruby
# frozen_string_literal: true

module Bundler
  # Represents metadata from when the Bundler gem was built.
  module BuildMetadata
    # begin ivars
    @built_at = "2017-12-21".freeze
    @git_commit_sha = "0034ef341".freeze
    @release = true
    # end ivars

    # A hash representation of the build metadata.
    def self.to_h
      {
        "Built At" => built_at,
        "Git SHA" => git_commit_sha,
        "Released Version" => release?,
      }
    end

    # A string representing the date the bundler gem was built.
    def self.built_at
      @built_at ||= Time.now.utc.strftime("%Y-%m-%d").freeze
    end

    # The SHA for the git commit the bundler gem was built from.
    def self.git_commit_sha
      @git_commit_sha ||= Dir.chdir(File.expand_path("..", __FILE__)) do
        `git rev-parse --short HEAD`.strip.freeze
      end
    end

    # Whether this is an official release build of Bundler.
    def self.release?
      @release
    end
  end
end
```

**Comment by 907th** [comment]
@segiddins You're right! I debugged a little and found that my ruby 2.5.0 installation already have a copy of the Bundler 1.16.1 and this "preinstalled" Bundler is used by `bundle version` command instead of the one I installed manually (using `gem install bundler`).

Preinstalled Bundler path is:
~/.rvm/rubies/ruby-2.5.0/lib/ruby/site_ruby/2.5.0/bundler

Let's see on the `BuildMetadata` class from there:
```ruby
# ~/.rvm/rubies/ruby-2.5.0/lib/ruby/site_ruby/2.5.0/bundler/build_metadata.rb
module Bundler
  # Represents metadata from when the Bundler gem was built.
  module BuildMetadata
    # begin ivars
    @release = false
    # end ivars
    ...
```
**No ivars listed!**

I think that this is because RubyGems repo uses a plain copy of the Bundler in its own source code. At the time of writing it has `bundler @ 0034ef3` submodule (see [rubygems repo](https://github.com/rubygems/rubygems)).

I guess that metadata ivars are only injected into packaged version of Bundler. This approach is not compatible with using Bundler source code as is (like RubyGems do).

**Comment by greysteil** [comment]
I was doing a quick trawl of old issues this morning and saw this. I've created https://github.com/bundler/bundler/pull/6664 to stop it happening with future releases.
