### ISSUE TITLE
Permission denied when writing gem with `bundle gem`

### ISSUE THREAD

**Issue by mazarick** [bundler/bundler#6458]
I am running a recently installed Ubuntu inside of a Window10 machine.   I'm telling you this because there are likely to be many more people just like me and will run into the same problems.   I was actually trying to run "rake" inside of an older program that gave me further instructions to issue "bundle install".  I ran "bundle gem install" to get this error message.   I don't believe it is a permissions issue - it may be but the directory is:
```
 ls -l /usr/share/ruby*/all
drwxr-xr-x 0 root root 512 Mar 16 18:23 specifications

mazarick@mazarick-newPC:/usr/share/rubygems-integration/all/specifications$
total 164
-rw-r--r-- 1 root root  9986 Mar 13  2016 bundler-1.11.2.gemspec
-rw-r--r-- 1 root root  3350 Mar 13  2016 childprocess-0.5.9.gemspec
-rw-r--r-- 1 root root  3562 Mar 13  2016 did_you_mean-1.0.0.gemspec
-rw-r--r-- 1 root root  2064 Mar 13  2016 domain_name-0.5.20160216.gemspec
-rw-r--r-- 1 root root 14026 Apr 26  2014 erubis-2.7.0.gemspec
-rw-r--r-- 1 root root  3231 Nov  7  2014 http-cookie-1.0.2.gemspec
-rw-r--r-- 1 root root  3820 Dec 12  2015 i18n-0.7.0.gemspec
-rw-r--r-- 1 root root  2351 Mar 13  2016 listen-3.0.3.gemspec
-rw-r--r-- 1 root root  4439 Oct 25  2014 log4r-1.1.10.gemspec
-rw-r--r-- 1 root root  6487 Jun 14  2015 mime-types-2.6.1.gemspec
-rw-r--r-- 1 root root  5204 Mar 13  2016 minitest-5.8.4.gemspec
-rw-r--r-- 1 root root  1866 Mar 13  2016 molinillo-0.4.3.gemspec
-rw-r--r-- 1 root root  3608 Jan  6  2016 net-http-persistent-2.9.4.gemspec
-rw-r--r-- 1 root root  1362 May  6  2015 netrc-0.10.3.gemspec
-rw-r--r-- 1 root root  2992 Feb  6  2016 net-scp-1.2.1.gemspec
-rw-r--r-- 1 root root  4274 May  6  2015 net-sftp-2.1.2.gemspec
-rw-r--r-- 1 root root  8479 Feb 10  2016 net-ssh-3.0.1.gemspec
-rw-r--r-- 1 root root  1316 Mar 13  2016 net-telnet-0.1.1.gemspec
-rw-r--r-- 1 root root  1759 Mar 13  2016 power_assert-0.2.7.gemspec
-rw-r--r-- 1 root root  8562 Mar 13  2016 rake-10.5.0.gemspec
-rw-r--r-- 1 root root  1390 Mar 13  2016 rb-inotify-0.9.7.gemspec
-rw-r--r-- 1 root root  4817 Mar 16  2016 rest-client-1.8.0.gemspec
-rw-r--r-- 1 root root  6192 Mar 13  2016 test-unit-3.1.7.gemspec
-rw-r--r-- 1 root root  6521 Aug 19  2015 thor-0.19.1.gemspec
-rw-r--r-- 1 root root  2020 Oct 23  2015 unf-0.1.4.gemspec
```
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `/usr/bin/bundle gem install`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what actually happened was...

Error details

    Errno::EACCES: Permission denied @ dir_s_mkdir - /usr/share/rubygems-integration/all/specifications/install
      /usr/lib/ruby/2.3.0/fileutils.rb:253:in `mkdir'
      /usr/lib/ruby/2.3.0/fileutils.rb:253:in `fu_mkdir'
      /usr/lib/ruby/2.3.0/fileutils.rb:227:in `block (2 levels) in mkdir_p'
      /usr/lib/ruby/2.3.0/fileutils.rb:225:in `reverse_each'
      /usr/lib/ruby/2.3.0/fileutils.rb:225:in `block in mkdir_p'
      /usr/lib/ruby/2.3.0/fileutils.rb:211:in `each'
      /usr/lib/ruby/2.3.0/fileutils.rb:211:in `mkdir_p'
      /usr/lib/ruby/vendor_ruby/thor/actions/create_file.rb:61:in `block in invoke!'
      /usr/lib/ruby/vendor_ruby/thor/actions/empty_directory.rb:116:in `invoke_with_conflict_check'
      /usr/lib/ruby/vendor_ruby/thor/actions/create_file.rb:60:in `invoke!'
      /usr/lib/ruby/vendor_ruby/thor/actions.rb:94:in `action'
      /usr/lib/ruby/vendor_ruby/thor/actions/create_file.rb:25:in `create_file'
      /usr/lib/ruby/vendor_ruby/thor/actions/file_manipulation.rb:115:in `template'
      /usr/lib/ruby/vendor_ruby/bundler/cli/gem.rb:123:in `block in run'
      /usr/lib/ruby/vendor_ruby/bundler/cli/gem.rb:122:in `each'
      /usr/lib/ruby/vendor_ruby/bundler/cli/gem.rb:122:in `run'
      /usr/lib/ruby/vendor_ruby/bundler/cli.rb:370:in `gem'
      /usr/lib/ruby/vendor_ruby/thor/command.rb:27:in `run'
      /usr/lib/ruby/vendor_ruby/thor/invocation.rb:126:in `invoke_command'
      /usr/lib/ruby/vendor_ruby/thor.rb:359:in `dispatch'
      /usr/lib/ruby/vendor_ruby/thor/base.rb:440:in `start'
      /usr/lib/ruby/vendor_ruby/bundler/cli.rb:10:in `start'
      /usr/bin/bundle:19:in `block in <main>'
      /usr/lib/ruby/vendor_ruby/bundler/friendly_errors.rb:7:in `with_friendly_errors'
      /usr/bin/bundle:17:in `<main>'

Environment

    Bundler   1.11.2
    Rubygems  2.5.2.1
    Ruby      2.3.1p112 (2016-04-26 revision 0) [x86_64-linux-gnu]
    Git       2.7.4

Bundler settings

    gem.test
      Set for the current user (/home/xxx/.bundle/config): "false"
    gem.mit
      Set for the current user (/home/xxx/.bundle/config): "false"
    gem.coc
      Set for the current user (/home/xxx/.bundle/config): "false"
--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/bundler/bundler/search?q=Permission+denied+%40+dir_s_mkdir+-+%2Fusr%2Fshare%2Frubygems-integration%2F
all%2Fspecifications%2Finstall&type=Issues

If there aren't any reports for this error yet, please create copy and paste the report template above into a new issue.

**Comment by colby-swandale** [comment]
This is a reeeaalllly old version of Bundler. Please update to the latest version. Looking into the gem command, an error message since `1.11.2` has been added that will notify the user when the user does not have permission to create a new gem in the current folder.
