### ISSUE TITLE
If `Gemfile.lock` exists, `bundle lock --lockfile=<path>` does not do what you expect

### ISSUE THREAD

**Issue by deivid-rodriguez** [bundler/bundler#6460]
On a project with an existing `Gemfile.lock`, when I run

```bash
bundle lock --lockfile=AlternativeGemfile.lock
```

I get the output

```
Fetching gem metadata from https://rubygems.org/.........
Writing lockfile to /home/deivid/Code/nipanipa/AlternativeGemfile.lock
```

However, no `AlternativeGemfile.lock` file is actually written.

If I remove the `Gemfile.lock` file, then things work as I expect.

**Comment by agrim123** [comment]
This line [here](https://github.com/bundler/bundler/blob/master/lib/bundler/definition.rb#L340) seems to be the culprit. It does not check the file existence just the contents. If default lock file exists and we run `bundle lock --lockfile=AlternativeGemfile.lock`, assuming the contents are same it will not create a new `AlternativeGemfile.lock` file. However, if lock file does not exist, then this condition will be false and file would be created.  
Maybe we can introduce a check before this to check for file existence.
@colby-swandale any suggestions?

**Comment by colby-swandale** [comment]
sure
