### ISSUE TITLE
Could not load OpenSSL

### ISSUE THREAD

**Issue by ArielAleksandrus** [bundler/bundler#6472]
I'm using version 1.16.1 of bundler and when I try to run bundle install I get this error:
```

Could not load OpenSSL.
You must recompile Ruby with OpenSSL support or change the sources in your Gemfile from 'https' to 'http'.
Instructions for compiling with OpenSSL using RVM are available at http://rvm.io/packages/openssl.
```
I am using Linux Mint and version 1.1.0h of openssl

When I try to run `rails s` I get this error:

```
/home/aleksandrus/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require': libcrypto.so.1.0.2: cannot open shared object file: No such file or directory - /home/aleksandrus/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/x86_64-linux/digest/md5.so (LoadError)
```

I believe it tries to find version 1.0.2 of openssl while I have an upgraded version, 1.1.0
Any thoughts on how to fix this?

**Comment by colby-swandale** [comment]
This is not a Bundler issue, this seems to be an issue with your ruby environment. I suggest checking that your ruby environment is setup correctly and linked with the correct libraries.
