### ISSUE TITLE
`install` after changing a version can take a very long time to fail

### ISSUE THREAD

**Issue by indirect** [bundler/bundler#6483]
In this particular application, I changed a single version requirement in the gemfile, from sprockets ~> 3.0 to ~> 4.0.0.beta. When I ran `bundle install`, it took about 60 seconds to print this output:

```
$ bundle install
Fetching source index from https://enterprise.contribsys.com/
Fetching gem metadata from https://www.phusionpassenger.com/enterprise_gems/...
Fetching source index from https://enterprise.contribsys.com/
Fetching gem metadata from https://www.phusionpassenger.com/enterprise_gems/..
Fetching gem metadata from https://rubygems.org/...........
Fetching source index from https://www.phusionpassenger.com/enterprise_gems/
Fetching source index from https://www.phusionpassenger.com/enterprise_gems/
Fetching source index from https://rubygems.org/
You have requested:
  sprockets ~> 4.0.0.beta

The bundle currently has sprockets locked at 3.7.1.
Try running `bundle update sprockets`

If you are updating multiple gems in your Gemfile at once,
try passing them all to `bundle update`
```

The resolver didn't even run, and we didn't need to download gem information for 60 seconds to be be able to print that error message. Hopefully we can fail faster, saving people trying to install new versions in a large Gemfile a long wait.

**Comment by segiddins** [comment]
The resolver did run, the issue is that everything else in your gemfile is locked so it gets resolved before the Gem you’re updating

**Comment by colby-swandale** [comment]
ping @indirect did @segiddins reply fix this issue?

**Comment by colby-swandale** [comment]
Closing due to no response.
