### ISSUE TITLE
1.16.1 LoadError

### ISSUE THREAD

**Issue by BenjaminHoegh** [bundler/bundler#6485]
```
unix1@BOAS-BEF-60:/mnt/c/Users/bre/Documents/jekyll-toc-master$ bundle install
Traceback (most recent call last):
        1: from /usr/local/bin/bundle:23:in `<main>'
/usr/local/bin/bundle:23:in `load': cannot load such file -- /usr/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/exe/bundle (LoadError)
```

`ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-linux-gnu]
`
`gem 2.7.6
`
`bundler 1.16.1`

> *NOTE:* This ubuntu on Windows 10

**Comment by segiddins** [comment]
Hi there, could you please have a look at https://github.com/bundler/bundler/blob/master/doc/contributing/ISSUES.md ? Your issue is a bit light on information
