### ISSUE TITLE
False conflicts in 1.16.1

### ISSUE THREAD

**Issue by Jeiwan** [bundler/bundler#6487]
We're updating a Rails app from version 4.2.9 to version 5+ and get such conflicts:
```
Bundler could not find compatible versions for gem "actionpack":
  In Gemfile:
    rails (~> 5.0) was resolved to 5.0.0, which depends on
      actionpack (= 5.0.0)

    redis-session-store was resolved to 0.9.2, which depends on
      actionpack (< 5.2, >= 3)

    responders was resolved to 2.4.0, which depends on
      actionpack (< 5.3, >= 4.2.0)

    rspec-rails was resolved to 3.7.2, which depends on
      actionpack (>= 3.0)

    simple_form was resolved to 4.0.0, which depends on
      actionpack (> 4)
```
But 'actionpack' 5.0 fits just right to all the dependencies. There are also similar reports related to 'activerecord' and other Rails components.

Bundler 1.15.4 produces no such conflicts.

**Comment by colby-swandale** [comment]
Can you please attach the output of `bundle env`

**Comment by colby-swandale** [comment]
ping @Jeiwan

**Comment by Jeiwan** [comment]
Sorry for the delay, I had a busy week.
I saw this bug in a Docker container as well as on my local machine, and it appeared multiple times. I'll try to post all the details tomorrow, I need to recreate the same environment.

**Comment by Jeiwan** [comment]
Strange, this is not reproducible anymore. Probably it was caused by some weird gems combination.
