### ISSUE TITLE
Strange lockfile behaviour with bundle update/install and platform-specific gems

### ISSUE THREAD

**Issue by nilsding** [bundler/bundler#6491]
Hey everyone,
I recently stumbled upon some weird behaviour with `bundle update` and `bundle install` and some platform-specific gem dependencies in a few of our projects.  I successfully managed to track it down to the following:

- The `pry` gem, which has at least two gem versions: one for any platform (I'll call that one `ruby` from now on) and one for `java`
- That `java` platform version has an additional dependency on `spoon`, which has a dependency on `ffi`
- Any bundle command which modifies the Gemfile which is not `bundle install` (e.g. `bundle update` or `bundle lock`) adds the `ffi` dependency for the `ruby` platform.
- `bundle install` will correctly remove the `ffi` gem for the `ruby` platform from the `Gemfile.lock`, as it determined it's apparently not needed for that platform.

I have created a git repository with each step in its own commit to reproduce this behaviour: https://github.com/nilsding/bundler-lockfile-issue/commits/master.

----

Output of `bundle env`, if it's of any help:

## Environment

```
Bundler             1.16.1
  Platforms         ruby, universal-java-1.8
Ruby                2.3.3p0 (2018-02-21 revision 56859) [java]
  Full Path         /Users/nilsding/.rvm/rubies/jruby-9.1.16.0/bin/jruby
  Config Dir        /Users/nilsding/.rvm/rubies/jruby-9.1.16.0/etc
RubyGems            2.6.14.1
  Gem Home          /Users/nilsding/.rvm/gems/jruby-9.1.16.0
  Gem Path          /Users/nilsding/.rvm/gems/jruby-9.1.16.0:/Users/nilsding/.rvm/gems/jruby-9.1.16.0@global
  User Path         /Users/nilsding/.gem/jruby/2.3.0
  Bin Dir           /Users/nilsding/.rvm/gems/jruby-9.1.16.0/bin
Tools
  Git               2.16.2
  RVM               1.29.3 (master)
  rbenv             not installed
  chruby            not installed
  rubygems-bundler  (1.4.4)
```

## Bundler Build Metadata

```
Built At          2017-12-21
Git SHA           0034ef341
Released Version  true
```

## Bundler settings

```
jobs
  Set for the current user (/Users/nilsding/.bundle/config): "8"
gem.test
  Set for the current user (/Users/nilsding/.bundle/config): "rspec"
gem.mit
  Set for the current user (/Users/nilsding/.bundle/config): false
gem.coc
  Set for the current user (/Users/nilsding/.bundle/config): true
```

### Gemfile

```ruby
source "https://rubygems.org"

gem "pry"
gem "empyrean", "= 0.1.1"
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    coderay (1.1.2)
    empyrean (0.1.1)
    ffi (1.9.23-java)
    method_source (0.9.0)
    pry (0.11.3)
      coderay (~> 1.1.0)
      method_source (~> 0.9.0)
    pry (0.11.3-java)
      coderay (~> 1.1.0)
      method_source (~> 0.9.0)
      spoon (~> 0.0)
    spoon (0.0.6)
      ffi

PLATFORMS
  java
  ruby

DEPENDENCIES
  empyrean (= 0.1.1)
  pry

BUNDLED WITH
   1.16.1
```

**Comment by segiddins** [comment]
Weird, on `master` even `bundle install` doesn't seem to be removing `ffi`.

Thanks so much for the _amazing_ repro case.

**Comment by segiddins** [comment]
I think https://github.com/bundler/bundler/pull/6495 should fix this!

**Comment by nilsding** [comment]
@segiddins yes, #6495 indeed fixes this!  No more unnecessary platform-specific gems on [`bundle lock`](https://github.com/nilsding/bundler-lockfile-issue/commit/1b2766330acd6427e817705fdf0dcd842248d6fc) or [`bundle update`](https://github.com/nilsding/bundler-lockfile-issue/commit/015d993da19119249fdc5c42dc1393535044ba8a)s  🎉
