### ISSUE TITLE
Gemfile.rb rather than Gemfile ?

### ISSUE THREAD

**Issue by kriom** [bundler/bundler#6494]
Hi!

This is more a remark than an issue.

As the `Gemfile` is evaluated as Ruby code (http://bundler.io/man/gemfile.5.html), I think it should be possible to name it `Gemefile.rb` (but keep retro-compatibility).

Perhaps I am wrong but : Is there a good reason to name it `Gemfile` ?

To me, it makes more sense that the files evaluated as Ruby have the `.rb` extension.

In https://github.com/ruby/rake the problem is the same with `Rakefile` that should be named `Rakefile.rb` because evaluated by Ruby.

Or, in https://github.com/rails/rails, where `config/database.yml` containing configuration for Active Record should be named `config/database.yml.erb` because evaluated by ERB to give `yml`.

By keeping these names with no extension the developer apprentice does not automatically understand that this file will be evaluated by Ruby, ERB ...

I saw these issues #1315, #1576, so I know I can do : 
```
$ bundle config --local gemfile Gemfile.rb
You are replacing the current local value of gemfile, which is currently nil 
```
But I think `Gemfile.rb` and `Gemfile` (I let you decide the order if accepted) should be possible default native names for this file.
 
Another time perhaps you are totally disagree, in this case close this issue :).

Best regards.

**Comment by segiddins** [comment]
Bundler supports the `gems.rb` name as well ;)

**Comment by kriom** [comment]
Thanks ! It works well !

Perhaps for the future `gems.rb` should be put forward rather than `Gemfile`.

**Comment by segiddins** [comment]
We considered doing that, but community response was not overwhelmingly positive.
