### ISSUE TITLE
bundler/inline not working with sinatra application

### ISSUE THREAD

**Issue by democlitos** [bundler/bundler#6497]
Hi. Sinatra application is not started when bundler is used to resolve dependencies. In the following code the application is closed before sinatra server start.
```
require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'
  gem 'sinatra'
  gem 'json'
end

post '/api/messages/' do
    content_type :json

    { :sentence => params[:sentence], :tool => params[:tool], :operations => params[:operations]}.to_json
end
```

**Comment by colby-swandale** [comment]
This is not a problem with Bundler. i suggest opening this issue with the Sinatra project.
