### ISSUE TITLE
API to determine if the semantic match is specified in the Gemfile?

### ISSUE THREAD

**Issue by justin808** [bundler/bundler#6500]
Is there an API to determine if the semantic match is specified in the Gemfile?

I'd like to know if a version for a gem is specified using ">=" or "~>" in the Gemfile?

**Comment by segiddins** [comment]
There’s currently no public API for it, but you can try to parse the `DEPENDENCIES` section of the lockfile

**Comment by colby-swandale** [comment]
This seems answered.
