### ISSUE TITLE
Using incorrect source credentials from environment variable

### ISSUE THREAD

**Issue by hmcfletch** [bundler/bundler#6507]
We use Sidekiq Pro and the credentials for their gem server look like `<username>:<password>`. We just upgraded to Ruby 2.5.1 and installed bundler 1.16.1.

When we run `bundle install` we get an error trying to fetch from the Sidekiq Pro source.

Gemfile:
```ruby
source 'https://gems.contribsys.com/' do
  gem 'sidekiq-pro'
end
```

Environment variable:
```
BUNDLE_GEMS__CONTRIBSYS__COM=fakeusername:fakepassword
```

The error:
```
Fetching source index from https://gems.contribsys.com/

Bad username or password for https://fakeusername@gems.contribsys.com/.
Please double-check your credentials and correct them.
```

It looks like pulling the credentials from the environment variable splits the value on the `:` and only uses the username portion.

Two different work arounds:
* Downgrading to `1.15.4`
* `bundle config gem.contribsys.com fakeusername:fakepassword`

Please let me know if there is any other info you need.

**Comment by hmcfletch** [comment]
Unfortunately, I am now unable to reproduce the issue. Was trying to narrow down the reproduction steps. We are using `dotenv` as well, if that makes any difference.

Feel free to close if you feel the need.

**Comment by segiddins** [comment]
Bundler only prints the username, since printing the password constitutes a security vulnerability if necessary. Closing since things seem to work now!
