### ISSUE TITLE
weird `bundle update <specific gem>` behavior with Gemfile.lock's with platform locks

### ISSUE THREAD

**Issue by lamont-granquist** [bundler/bundler#6509]
pretty decent replication case that isn't too horrible here:

```
% git clone https://github.com/chef/opscode-pushy-client.git
% cd opscode-pushy-client
% git checkout 65ea3f70313ab23aeb8ac58c8b712c18c3bc979e
% bundle update opscode-pushy-client
Fetching gem metadata from https://rubygems.org/........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Bundler could not find compatible versions for gem "win32-api":
  In snapshot (Gemfile.lock):
    win32-api (= 1.5.3)

  In Gemfile:
    win32-api x86-mingw32

    windows-pr x86-mingw32 was resolved to 1.2.6, which depends on
      win32-api (>= 1.4.5)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
% bundle --version
Bundler version 1.16.1
```

win32-api 1.5.3 should satisfy >= 1.4.5 so something is going wrong.

**Comment by colby-swandale** [comment]
Can you please attach the output of `bundle env`, we can't really help you without having a Gemfile & Gemfile.lock available.

**Comment by segiddins** [comment]
Digging into this, I _think_ the issue is that `windows-pr` is actually a `ruby` platform gem, and so Bundler expects to be able to find `ruby` versions of its dependencies

**Comment by segiddins** [comment]
I think the issue is also that `windows-pr` isn't actually used by any of the other gems in the bundle, causing the platform headache. Simply removing it from the `Gemfile` seems to fix the issue for me :)

**Comment by lamont-granquist** [comment]
lolz.  i will give that a go.  =)

**Comment by colby-swandale** [comment]
ping @lamont-granquist were you able to resolve your issue?
