### ISSUE TITLE
Raises incorrect error from `gem`, causing an error in ActiveRecord

### ISSUE THREAD

**Issue by JoshCheek** [bundler/bundler#6512]
## The Bundler bug

When requiring a gem that doesn't exist:
* Bundler raises a `Gem::LoadError` ([here](https://github.com/bundler/bundler/blob/master/lib/bundler/rubygems_integration.rb#L401))
* Rubygems raises a `Gem::MissingSpecError` ([here](https://github.com/ruby/ruby/blob/707cbe6f990de42a927405bea75dd6c64a8944bf/lib/rubygems/dependency.rb#L310) from [here](https://github.com/ruby/ruby/blob/707cbe6f990de42a927405bea75dd6c64a8944bf/lib/rubygems/dependency.rb#L322) from [here](https://github.com/ruby/ruby/blob/707cbe6f990de42a927405bea75dd6c64a8944bf/lib/rubygems/core_ext/kernel_gem.rb#L65))

They are not directly substitutable, because they are initialized with different arguments:
```ruby
Gem::LoadError.instance_method(:initialize).parameters
# => [[:rest]]

Gem::MissingSpecError.instance_method(:initialize).parameters
# => [[:req, :name], [:req, :requirement]]
```

## The ActiveRecord bug

This causes a bug in ActiveRecord. When it fails to load the adapter, it tries to reraise the error ([here](https://github.com/rails/rails/blob/46b46e85c72f78e869a1b0038040849911c7e2c5/activerecord/lib/active_record/connection_adapters/connection_specification.rb#L197)).
* If Bundler is loaded, it gets a `Gem::LoadError`, succeeds at reraising and provides the helpful  message _"Could not load the 'sqlite3' Active Record adapter. Ensure that the adapter is spelled correctly in config/database.yml and that you've added the necessary adapter gem to your Gemfile."_
* If Bundler is not loaded, it gets a `Gem::MissingSpecError`, then errors while trying to reraise, causing an `ArgumentError` with the unhelpful _"wrong number of arguments (given 1, expected 2)"_

You can reproduce my error with [this](https://gist.github.com/JoshCheek/a0d3af7d6dce0450fbfcda3f1aa2cb19) gist.

However, if we strip away all the layers of complexity, it's just this:

```ruby
begin
  begin
    raise Gem::LoadError.new('somegem')
  rescue Gem::LoadError => err
    raise err.class, "I am a helpful message!"
  end
rescue Object
  $! # => #<Gem::LoadError: I am a helpful message!>
end


begin
  begin
    raise Gem::MissingSpecError.new('somegem', 'somerequirement')
  rescue Gem::LoadError => err
    raise err.class, "I am a helpful message!"
  end
rescue Object
  $! # => #<ArgumentError: wrong number of arguments (given 1, expected 2)>
end
```

## Anecdote to show that it matters

I was somewhat embarrassed when I discovered this as I was showing off a gem I wrote. We assumed it was a bug in my code and I wasn't able to show the example. If I had gotten the helpful error, I would have realized I hadn't installed sqlite3 on that version of Ruby.

## Fixing this will break ActiveRecord

Note that fixing this will break ActiveRecord. I know it's already broken, but this will cause the broken case to become the common case. I'll probably submit a bug report there, too, but it took a bit to debug this, so don't have time just now.

I'm not sure the best solution for ActiveRecord, they could raise it like this: `raise err, "helpful message..."`, that will fix the error by bypassing `#initialize`. However, `Gem::MissingSpecError` overrides the message, so their helpful message won't be returned, so, IDK.

```ruby
begin
  begin
    raise Gem::MissingSpecError.new('somegem', 'somerequirement')
  rescue Gem::LoadError => err
    raise err, "I am a helpful message!"
  end
rescue Object
  m = $!.method(:message)
  
  $!                  # => #<Gem::MissingSpecError: I am a helpful message!>
  $!.message          # => "Could not find 'somegem' (somerequirement) among 97 total gem(s)\nChecked in 'GEM_PATH=/Users/josh/.gem/ruby/2.4.1:/Users/josh/.rubies/ruby-2.4.1/lib/ruby/gems/2.4.0', execute `gem env` for more information"
  m.super_method.call # => "I am a helpful message!"

  m.source_location.tap { |f, l| break File.readlines(f)[l-1, 4] }
  # => ["    def message # :nodoc:\n",
  #     "      build_message +\n",
  #     "        \"Checked in 'GEM_PATH=\#{Gem.path.join(File::PATH_SEPARATOR)}', execute `gem env` for more information\"\n",
  #     "    end\n"]
end
```

**Comment by colby-swandale** [comment]
I'm not sure how this is an issue with Bundler and not ActiveRecord?

**Comment by colby-swandale** [comment]
Thanks for working on this figuring out this issue. This is probably an issue more for ActiveRecord then Bundler, it will need to handle this particular scenario. I suggest raising an issue with the [Rails project](https://github.com/rails/rails) and passing along this information.
