### ISSUE TITLE
bundle package creates weird folder structure when using --path parameter

### ISSUE THREAD

**Issue by ChrisBr** [bundler/bundler#6515]
Hello,

I'm not sure if this is intended behavior or if I use --path wrong. Anyway, when using --path parameter with bundle package I get a weird path structure for the downloaded gems:

```
bundle package --no-install --path vendor/bundle
```

will create the cache in ```vendor/bundle/vendor/cache/```. Fair enough, this might make sense although I would expect bundler is smart enough to create the cache in ``vendor/bundle``.

If I run:
```
bundle package --no-install --path vendor/cache
```

The cache is as expected in ``vendor/cache/``. However, it also creates the subfolders ``vendor/cache/vendor/cache/`` (empty) and ``vendor/cache/ruby/2.4.0/cache/`` (with the gems for the ruby version).

When I run first 
```
bundle install --path vendor/bundle
```

and afterwards
```
bundle package --no-install
```
(so the path is already set in ,bundle/config)

I get the expected folder structure

```
vendor/bundle/ruby/2.4.0/cache/
```
and
```
vendor/bundle/ruby/2.4.0/cache/
```

I would say this is not expected behavior ...

```
Bundler version 1.16.1
ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-linux-gnu]
```

**Comment by colby-swandale** [comment]
This looks like the issue has been answered.
