### ISSUE TITLE
web_1  | /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/spec_set.rb:88:in `block in materialize': Could not find dotenv-2.2.2 in any of the sources (Bundler::GemNotFound)

### ISSUE THREAD

**Issue by mitpaladin** [bundler/bundler#6518]
Hi, I'm building an application image in Docker and running into a problem where during the build stage it `Successfully installed dotenv-2.4.0` but then `docker-compose logs web` outputs ```web_1  | /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/spec_set.rb:88:in `block in materialize': Could not find dotenv-2.2.2 in any of the sources (Bundler::GemNotFound)
```

Is there any reason why bundler would be looking up an older version of dotenv than is built with?

**Comment by mitpaladin** [comment]
Hi, I'm building an application image in Docker and running into a problem where during the build stage it `Successfully installed dotenv-2.4.0` but then `docker-compose logs web` outputs `web_1 | /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/spec_set.rb:88:in `block in materialize': Could not find dotenv-2.2.2 in any of the sources (Bundler::GemNotFound)`

Is there any reason why bundler would be looking up an older version of dotenv than is built with?

**Comment by segiddins** [comment]
Please share the output of `bundle env`, as well as steps to reproduce the issue you’re experiencing
