### ISSUE TITLE
Error when run ./beef

### ISSUE THREAD

**Issue by thesalah1212** [bundler/bundler#6520]
When I run this "./beef"
I got this error
 
```
Bundler could not find compatible versions for gem "rack":
  In Gemfile:
    rack (~> 1.6.5)

    sinatra was resolved to 2.0.1, which depends on
      rack (~> 2.0)
```

**Comment by colby-swandale** [comment]
This error is typical when you have a version conflict. Your Gemfile specifies `rack -> 1.6.5` but Sinatra `2.0.1` is depending on `rack -> 2.0`. You will either need to update your application to use a version of Rack `2.x`  or downgrade Sinatra to a version that depends on rack `1.6.x`
