### ISSUE TITLE
vendor/cache vs vendor/bundle

### ISSUE THREAD

**Issue by kidbrax** [bundler/bundler#6521]
If I want to start my apps without having to install any gems, only use what is already bundled, should i have both a vendor/bundle directory and a vendor/cache directory?

http://bundler.io/v1.16/guides/deploying.html says it will install into vendor/bundle

but http://bundler.io/v1.16/man/bundle-package.1.html says it will install into vendor/cache

so do I need both? and what is the correct order for the command. `bundle package` and then `bundle install --deployment`? and then finally `bundle install --local`?

**Comment by segiddins** [comment]
`bundle install —path vendor/bundle && bundle package` should be fully portable

**Comment by colby-swandale** [comment]
ping @kidbrax, did you resolve your problem?

**Comment by segiddins** [comment]
>  I'm still unclear as to when you would need to use --deploy and/or --local

`--deployment` specifically disallows changes to your lockfile

`--local` disallows hitting the network to find gems
