### ISSUE TITLE
Not recognizing version range

### ISSUE THREAD

**Issue by andretf** [bundler/bundler#6528]
I'm trying to use a version range (`ruby '~> 2.4.0'`) that should be working as stated here:
https://github.com/bundler/bundler-features/issues/119

But I'm getting this error:

> Your Ruby version is 2.5.1, but your Gemfile specified ~> 2.4.0

I'm using bundler 1.16 btw.

**Comment by segiddins** [comment]
2.5.2 does not match ~> 2.4.0, which means “2.4.x”
