### ISSUE TITLE
only_update_to_newer_versions regression in v1.16

### ISSUE THREAD

**Issue by theflow** [bundler/bundler#6529]
Hi,

I've noticed a few edge cases where the `only_update_to_newer_versions` setting doesn't get respected anymore, where it used to work in Bundler 1.15.

Here is an example to reproduce: https://gist.github.com/theflow/edd84a5318738b59f65cf42eaaede9f3

Bundler v1.16 will downgrade carrierwave-mongoid to an really old version which is missing the version requirement on mongoid:

```
+ BUNDLE_ONLY_UPDATE_TO_NEWER_VERSIONS=true
+ bundle update mongoid carrierwave-mongoid
Fetching gem metadata from https://rubygems.org/..........
Resolving dependencies....
Using concurrent-ruby 1.0.5
Using i18n 1.0.1
Using minitest 5.11.3
Using thread_safe 0.3.6
Using tzinfo 1.2.5
Using activesupport 5.2.0
Using activemodel 5.2.0
Using bson 4.3.0
Using bundler 1.16.1
Using mime-types-data 3.2016.0521
Using mime-types 3.1
Using carrierwave 1.2.2
Using mongo 2.5.3
Using mongoid 7.0.1 (was 6.4.1)
Using carrierwave-mongoid 0.1.0 (was 1.0.0)
Bundler attempted to update carrierwave-mongoid but its version regressed from 1.0.0 to 0.1.0
Bundle updated!
```

I'm pretty sure it was introduced in https://github.com/bundler/bundler/commit/47256d20cb05ebc724ee67173094682153b6b4aa, but I don't understand the reason behind that change.

Here https://github.com/bundler/bundler/blob/master/lib/bundler/definition.rb#L975 it's comparing a `Bundler::Dependency` with an `Array` from the group_by which will always be non-equal, which I guess is not the intention?

Comparing the first element of the array fixes this issue for me, but not sure if that's the correct way and what's supposed to happen if there are multiple `dependencies_by_name`.

https://github.com/theflow/bundler/commit/07942b1a6ccec4faff8716afc89288edad8496d2

Cheers,
Florian

**Comment by theflow** [comment]
@segiddins if you have a minute, could you explain the reason behind 47256d20cb05ebc724ee67173094682153b6b4aa?

For example on a `bundle update` with your change it won't create additional requirements for any gem, since none of them are locked. Which means `only_update_to_newer_versions` doesn't enforce anything.

**Comment by segiddins** [comment]
I have no clue, I wrote that commit 10 months ago :)

If I had to guess, it would be so you could manually downgrade to a lower version by changing the requirement in your Gemfile?

**Comment by theflow** [comment]
I think your right @segiddins. I've added a test for that and a test reproducing the problem I'm seeing to my PR with an attempted fix.
