### ISSUE TITLE
Vendoring fileutils breaks alternate implementations

### ISSUE THREAD

**Issue by headius** [bundler/bundler#6532]
JRuby's fileutils.rb has code specific to JRuby, due to the fact that many of the Java APIs we call behave slightly differently than the POSIX calls that CRuby makes. By vendoring fileutils in 699d5184c1d500b60a25819977f1b286a84b3337 you have essentially caused JRuby's modifications to be ignored.

The case that led us to this issue was for FileUtils.mv, which in MRI expects an EXDEV to be raised when attempting to rename a file across devices. Our version of the `mv` method handled both EXDEV and the error we actually raised, EACCES. The vendored version only rescued EXDEV, so the EACCES bubbled out and broke various things.

I have a PR in progress that should fix this one case for JRuby master (JRuby 9.2, which will be Ruby 2.5 compatible). This issue should not affect JRuby 9.1.

However, there are several other JRuby-specific pieces of logic in our fileutils.rb that are now missing when running with Bundler on JRuby 9.2 or higher. The fileutils.rb code needs to either reflect JRuby's changes (and potentially other implementations) or it needs to not be vendored.

FWIW I do understand the issue here: you can't depend on a gem, and fileutils is now a gem. But vendoring the file directly in the respository means you will not get updated versions from the gem either.

**Comment by headius** [comment]
JRuby fix for the *one* case is in jruby/jruby#5168, which properly throws EXDEV (and removes our modification). However there are other modifications we can't afford to lose.

**Comment by segiddins** [comment]
Won’t jruby users have the same issues if they run `gem install fileutils` ?

**Comment by headius** [comment]
@segiddins We can (and likely will have to) release a -java version of the fileutils gem, but then it will be a fixed problem. That won't solve the Bundler issue.

**Comment by segiddins** [comment]
Then someone will need to refactor things to not use fileutils, which is a real shame.

**Comment by headius** [comment]
It occurs to me that the fileutils you're vendoring shouldn't eliminate the fileutils in stdlib, is that correct? That would reduce the impact of this bug substantially, but any methods copied over need to be audited for JRuby-specific versions.

It appears at a glance that you have vendored the entire file, but most likely only need a subset of those methods.

**Comment by headius** [comment]
Could you chat about this somewhere?

**Comment by headius** [comment]
@segiddins https://github.com/ruby/fileutils/pull/18

**Comment by headius** [comment]
So given the patches I've provided to @hsbt, I believe we could incorporate the same changes into your copy of fileutils and close this issue. However I'd recommend one of the following additional steps:

* Only vendor the methods you are actually using from fileutils, and ideally name them something that's not so ambiguous with the real fileutils.
* Always update the vendored copy from the gem repo as part of development/testing/release process.

**Comment by headius** [comment]
All our tweaks have been incorporated into fileutils, and they will be released soon in the 1.1.0 version of the gem.
