### ISSUE TITLE
1.16.2 - --path not obeyed

### ISSUE THREAD

**Issue by bkuhl** [bundler/bundler#6538]
In a Jenkins build, I'm trying to tell bundler to install the dependencies within the job's writable directory structure. For the life of me I can't get it to obey the `--path` parameter, so I must be misunderstanding unless it's bugged. 

    dir(properties.projectDir + '/slate/.bundle') {
        sh 'pwd'
        sh 'bundle version'
        sh 'bundle install --no-cache --path=./'
    }

I've tried:

 - `sh 'bundle install --no-cache --path=./'`
 - `sh 'BUNDLE_PATH=./ bundle install --no-cache --path=./'`
 - `sh 'bundle install --no-cache --path=' + properties.projectDir + '/slate/.bundle'`

CI Output:

    bundle install --no-cache --path=./
    
    There was an error while trying to write to
        `/home/ubuntu/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/versions`.

I'm not experienced with Ruby and that includes Bundler, so I may just be misunderstanding something.

**Comment by colby-swandale** [comment]
Bundler is trying to download the Gem Index from rubygems.org (it hasn't started installing gems yet) but the doesn't seem to have permission to write to where it's trying to. You need to fix the file permissions at `home/ubuntu/.bundle/cache/compact_index` and make sure the user running Bundler has the appropriate read/write permissions.
