### ISSUE TITLE
Alternative to Fallback to a temp dir when the home directory is not usable

### ISSUE THREAD

**Issue by brodock** [bundler/bundler#6546]
The changes in https://github.com/bundler/bundler/pull/4951 introduced many issues for people bundling ruby into omnibus packages, 

There are valid use-cases to not have the home directory writable. Alternatively to falling back to a tempdir, I suggest we try to find the `.bundle` and `. gem` folders first and assert they are writable. If that fails, than we fallback to tempdir.

So the heuristic should be like:

```ruby
home = Bundler.rubygems.user_home 
dot_bundle = File.join(home, '.bundle')
dot_gem = File.join(home, '.gem')

if home.nil?
  warning += "\n * It is not set at all"
elsif !File.directory?(home)
  warning += "\n * `#{home}` is not a directory"
elsif !File.writable?(home) && [dot_bundle, dot_gem].any? { |dir| !File.directory?(dir) || !File.writable?(dir) }
  warning += "\n * `#{home}` is not writable"
else
  return @user_home = Pathname.new(home)
end
```

That allows package software to provide required `.gem` and `. bundle` folders with right permission without messing with the rest of the environment.

**Comment by svoop** [comment]
This approach should fix deployment issues to application servers with tight security as well.
