### ISSUE TITLE
CHANGELOG does not have any docs for version 1.16.2

### ISSUE THREAD

**Issue by kevinburke** [bundler/bundler#6561]
There is a Git tag for 1.16.2 but the most recent version described in the CHANGELOG on the `master` (default) branch is 1.16.1.

**Comment by segiddins** [comment]
Colby, did you merge the tag back into master after the release?

**Comment by indirect** [comment]
It was me that actually ran the release and forgot to merge back to master, sorry. 😬

**Comment by indirect** [comment]
1.16.2 is merged back to master now, sorry for the trouble!

**Comment by colby-swandale** [comment]
Apologies, i should have done this myself :bowing_man:
