### ISSUE TITLE
version 1.16.x order of options issue

### ISSUE THREAD

**Issue by scurry** [bundler/bundler#6562]
## Issue
Order of options seems to matter in the parsing of the cli. The failed command is what my CI server runs. The CI server controls the order of the command line options. We can't change the order ourselves. I would assume the order of options would not matter, but as you can see it appears they do. Would you agree this is a bug?

## Failed (unexpected) command
`bundle --verbose package --all-platforms`

returns the result:
`Unknown switches '--all-platforms'`

[Issue details gist](https://gist.github.com/scurry/5e9f766c476e41f4edbf2580099b99f4)

**Comment by segiddins** [comment]
Is this only an issue on 1.16?

**Comment by cloudappdevelopment** [comment]
I have not tested this with other versions. I can go back to older versions and try.  How far back would you like?

**Comment by scurry** [comment]
I have not tried older versions but I certainly can.  How far back would you like me to try and report back?

**Comment by kerrizor** [comment]
Just quickly checked, this is an issue in 1.14 and 1.15 as well.

**Comment by colby-swandale** [comment]
There's not much we can do about this issue a PR is made into thor to fix this issue.

**Comment by colby-swandale** [comment]
I'm going to close this as there won't be anything more to add to this unless Thor fixes this issue.
