### ISSUE TITLE
[Feature request] Specifying groups for `bundle list`

### ISSUE THREAD

**Issue by ilikebits** [bundler/bundler#6564]
For example, I would like to be able to `bundle list --without test` or `bundle list --without development` (or perhaps `bundle list --only default`?) so that I can list only my production dependencies. My use case is that I'd like to do dependency analysis (in this case, checking for license compliance) on only the gems that are used in production.

**Comment by colby-swandale** [comment]
I like this idea but i'm a bit weary of adding the same options from `bundle install`

**Comment by agrim123** [comment]
I would like to take up this task if we are planning on implementing these options 😄.

**Comment by agrim123** [comment]
@ilikebits I did some experimenting [here](https://github.com/agrim123/bundler/tree/agr-bundle-list-options). Let me know if this was what you were requesting.
@colby-swandale Should I go ahead with PR?

**Comment by colby-swandale** [comment]
no need to ask, more then welcome to make a PR

**Comment by agrim123** [comment]
@ilikebits Should we close this issue? 😄
