### ISSUE TITLE
`outdated` doesn't show `bundler` itself

### ISSUE THREAD

**Issue by AlexWayfer** [bundler/bundler#6569]
Hello!

I have `gem 'bundler', '~> 1.16'` in the `Gemfile` and `bundler 1.16.1` installed.

And `bundle outdated` doesn't show the newer available `1.16.2` version of `bundler`.

I think it should.

Thanks.

**Comment by colby-swandale** [comment]
There doesn't seem to be interest in this. Closing.

**Comment by AlexWayfer** [comment]
> There doesn't seem to be interest in this.

From… who? There is interest from me, for example. I want to know about new versions of Bundler, which is used in my projects, when I check outdated gems in my project.
