### ISSUE TITLE
Bundler 2 Release Checklist

### ISSUE THREAD

**Issue by indirect** [bundler/bundler#6582]
It’s finally here! This is the checklist and countdown for releasing Bundler 2. The items listed here are probably each an entire issue or pull request by themselves, and this issue serves as a place to track those items. This issue is also a good place to discuss adding or removing items in this list.

### Deprecations
- [ ] Modify deprecation checker to print a warning on the deprecated version, and remove the feature entirely on the major after the deprecated version. #6586
- Verify that `with_clean_env` still works but prints a warning, and stops working in Bundler 3
- Move the implementation of `with_clean_env` to `without_bundle_env`, add docs for `without_bundle_env`.
- Update `with_clean_env` warning to say something like "It turns out `with_clean_env` was confusing because it tried to do two different things. Please check the docs and use either `with_original_env` or `without_bundle_env` depending on what you need."

### Compatibility
- Install Bundler 1.x and 2.x, have an existing Rails 5.2 app continue to work without issues
- Install _only_ Bundler 2.x, have an existing Rails 5.2 app continue to work without issues on Bundler 1.x
- Upgrade an existing Rails 5.2 app from Bundler 1 to 2, continue to run without issues
- Run `bundle init; echo 'gem "rails"' >> Gemfile; bundle install; bundle exec rails new .; bundle update --bundler` to install Rails 5.2, generate a new app, bump to Bundler 2, and use Rails without issues
- Deploy a Rails 5.2 app running Bundler 2 to Heroku without issues

### Documentation
- Review and update man pages for 2.x
- Review and update bundler.io pages for 2.x
- Review and update bundler.io guides for 2.x
- Review and update the `doc/` directory for 2.x
- Add a guide to bundler.io on how to upgrade from 1.x to 2.x
- Add a guide to bundler.io for how to use Bundler 2 on Heroku
- Give bundler.io a huge header-level toggle between 1.x and 2.x docs

### Announce the release schedule
- Prereleases for 4 weeks
- Release RC, fix reported issues, release new RC
- Final release is the first RC with no reported blockers for 2 weeks

### Publish blog posts
- One blog post covering a breaking change each week
- In every post:
	- Re-explain the release schedule
	- Link to the 1.x to 2.x upgrade guide
	- Ask for testers to report issues

**Comment by colby-swandale** [comment]
The Bundler 2/3 releases has changed around a bit and the TODO list for a major release is being reviewed from the feedback when we released Bundler 2. I'm going to close this as there will be a PR that will add to the repo docs.
