### ISSUE TITLE
Reword regression message.

### ISSUE THREAD

**Issue by jcoyne** [bundler/bundler#6584]
When I updated a constraint in my gemfile and ran `bundle update` I see this message:

```
Bundler attempted to update net-ssh but its version regressed from 5.0.1 to 4.2.0
```

The message made me feel like bundler aborted or something, but it did just as I asked and made the version change.  Perhaps this could be phrased as.

```
Notice: Version of net-ssh regressed from 5.0.1 to 4.2.0
```

**Comment by rubymorillo** [comment]
@segiddins slight edit:

> Note: net-ssh version regressed from 5.0.1 to 4.2.0

then lgtm 👍

**Comment by colby-swandale** [comment]
A change to fix this issue has been merged.
