### ISSUE TITLE
Gem not found:Cannot find actionable 5.2 

### ISSUE THREAD

**Issue by MarcSteven** [bundler/bundler#6587]
Cannot find the actionable 5.2

**Comment by hsbt** [comment]
Do you mean `actioncable` ?

**Comment by colby-swandale** [comment]
This issue offers no information on the problem you're experiencing. Please follow the [ISSUE](https://github.com/bundler/bundler/blob/master/doc/contributing/ISSUES.md) template when creating an issue.

**Comment by MarcSteven** [comment]
@hsbt yeah
