### ISSUE TITLE
unable to unset "polluted" bundle environment

### ISSUE THREAD

**Issue by phuongnd08** [bundler/bundler#6588]
I have a environment where it is technically "polluted" with a bundle setup:
```
env | grep BUNDLE_
BUNDLE_GITHUB__COM=***
BUNDLE_SILENCE_ROOT_WARNING=1
BUNDLE_APP_CONFIG=/usr/local/bundle
BUNDLE_BIN=/usr/local/bundle/bin
BUNDLE_PATH=/usr/local/bundle
```

Now I have another project that has its own Gemfile and I need to run it
```
unset BUNDLE_BIN BUNDLE_PATH  BUNDLE_APP_CONFIG
cd my-new-project-that-has-its-own-Gemfile && bundle install
```

Then bundle go ahead and install all the gems specified by a Gemfile that not the one in the current directory.

So the path to Gemfile has been hardcoded elsewhere that simply unset ENV won't do?

**Comment by colby-swandale** [comment]
what is the output of `bundle env`?

**Comment by phuongnd08** [comment]
before unset:
```
## Environment

```
Bundler       1.16.1
  Platforms   ruby, x86_64-linux
Ruby          2.4.3p205 (2017-12-14 revision 61247) [x86_64-linux]
  Full Path   /usr/local/bin/ruby
  Config Dir  /usr/local/etc
RubyGems      2.7.6
  Gem Home    /usr/local/bundle
  Gem Path
  User Path   /root/.gem/ruby/2.4.0
  Bin Dir     /usr/local/bundle/bin
Tools
  Git         2.1.4
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2018-06-17
Git SHA
Released Version  false
```

## Bundler settings

```
retry
  Set for your local app (/usr/local/bundle/config): 5
jobs
  Set for your local app (/usr/local/bundle/config): "20"
without
  Set for your local app (/usr/local/bundle/config): [:test, :development]
github.com
  Set via BUNDLE_GITHUB__COM: "***"
silence_root_warning
  Set via BUNDLE_SILENCE_ROOT_WARNING: true
app_config
  Set via BUNDLE_APP_CONFIG: "/usr/local/bundle"
bin
  Set via BUNDLE_BIN: "/usr/local/bundle/bin"
gemfile
  Set via BUNDLE_GEMFILE: "/app/Gemfile"
path
  Set via BUNDLE_PATH: "/usr/local/bundle"
bin_path
  Set via BUNDLE_BIN_PATH: "/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/exe/bundle"
```

After unset BUNDLE_BIN BUNDLE_GEMFILE BUNDLE_PATH BUNDLE_BIN_PATH
```
root@xxx:/app# echo $BUNDLE_GEM_FILE

root@xxx:/app#
```
`bundle env` now shows:

```
## Environment

```
Bundler       1.16.1
  Platforms   ruby, x86_64-linux
Ruby          2.4.3p205 (2017-12-14 revision 61247) [x86_64-linux]
  Full Path   /usr/local/bin/ruby
  Config Dir  /usr/local/etc
RubyGems      2.7.6
  Gem Home    /usr/local/bundle
  Gem Path
  User Path   /root/.gem/ruby/2.4.0
  Bin Dir     /usr/local/bundle/bin
Tools
  Git         2.1.4
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2018-06-17
Git SHA
Released Version  false
```

## Bundler settings

```
retry
  Set for your local app (/usr/local/bundle/config): 5
jobs
  Set for your local app (/usr/local/bundle/config): "20"
without
  Set for your local app (/usr/local/bundle/config): [:test, :development]
github.com
  Set via BUNDLE_GITHUB__COM: "919b447c7caa69bf41b82679bfd639434d85b1be"
silence_root_warning
  Set via BUNDLE_SILENCE_ROOT_WARNING: true
app_config
  Set via BUNDLE_APP_CONFIG: "/usr/local/bundle"
bin_path
  Set via BUNDLE_BIN_PATH: "/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/exe/bundle"
gemfile
  Set via BUNDLE_GEMFILE: "/app/Gemfile"
```

**Comment by phuongnd08** [comment]
before unset:

## Environment

Bundler 1.16.1
Platforms ruby, x86_64-linux
Ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-linux]
Full Path /usr/local/bin/ruby
Config Dir /usr/local/etc
RubyGems 2.7.6
Gem Home /usr/local/bundle
Gem Path
User Path /root/.gem/ruby/2.4.0
Bin Dir /usr/local/bundle/bin
Tools
Git 2.1.4
RVM not installed
rbenv not installed
chruby not installed


## Bundler Build Metadata

Built At 2018-06-17
Git SHA
Released Version false


## Bundler settings

retry
Set for your local app (/usr/local/bundle/config): 5
jobs
Set for your local app (/usr/local/bundle/config): "20"
without
Set for your local app (/usr/local/bundle/config): [:test, :development]
github.com
Set via BUNDLE_GITHUB__COM: "***"
silence_root_warning
Set via BUNDLE_SILENCE_ROOT_WARNING: true
app_config
Set via BUNDLE_APP_CONFIG: "/usr/local/bundle"
bin
Set via BUNDLE_BIN: "/usr/local/bundle/bin"
gemfile
Set via BUNDLE_GEMFILE: "/app/Gemfile"
path
Set via BUNDLE_PATH: "/usr/local/bundle"
bin_path
Set via BUNDLE_BIN_PATH: "/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/exe/bundle"


After unset BUNDLE_BIN BUNDLE_GEMFILE BUNDLE_PATH BUNDLE_BIN_PATH
root@xxx:/app# echo $BUNDLE_GEM_FILE

root@xxx:/app#

`bundle env` now shows:

Environment
Bundler       1.16.1
  Platforms   ruby, x86_64-linux
Ruby          2.4.3p205 (2017-12-14 revision 61247) [x86_64-linux]
  Full Path   /usr/local/bin/ruby
  Config Dir  /usr/local/etc
RubyGems      2.7.6
  Gem Home    /usr/local/bundle
  Gem Path
  User Path   /root/.gem/ruby/2.4.0
  Bin Dir     /usr/local/bundle/bin
Tools
  Git         2.1.4
  RVM         not installed
  rbenv       not installed
  chruby      not installed
Bundler Build Metadata
Built At          2018-06-17
Git SHA
Released Version  false
Bundler settings
retry
  Set for your local app (/usr/local/bundle/config): 5
jobs
  Set for your local app (/usr/local/bundle/config): "20"
without
  Set for your local app (/usr/local/bundle/config): [:test, :development]
github.com
  Set via BUNDLE_GITHUB__COM: "***"
silence_root_warning
  Set via BUNDLE_SILENCE_ROOT_WARNING: true
app_config
  Set via BUNDLE_APP_CONFIG: "/usr/local/bundle"
bin_path
  Set via BUNDLE_BIN_PATH: "/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/exe/bundle"
gemfile
  Set via BUNDLE_GEMFILE: "/app/Gemfile"

**Comment by colby-swandale** [comment]
You have configured Bundler (using the `bundler` config) to use the Gemfile located at `/app/Gemfile`

**Comment by phuongnd08** [comment]
I some how did it, but I didn't know how did it happen. Then how do I temporary unconfig it for a certain task?

**Comment by deivid-rodriguez** [comment]
@phuongnd08 I think you need to remove the setting from `/usr/local/bundle/config`.

**Comment by colby-swandale** [comment]
`gemfile` seems to be getting set by the `BUNDLE_GEMFILE` environment variable rather then being in `/usr/local/bundle/config`.

@phuongnd08 we can't really help you unless you can provide more information then just saying it's not working. What's the output of `bundle env` when you unset `BUNDLE_GEMFILE`?

**Comment by colby-swandale** [comment]
ping @phuongnd08

**Comment by deivid-rodriguez** [comment]
@colby-swandale Right, I misread the config output.

@phuongnd08 Something I noticed is that, at least in the example, is that you're not correctly unsetting `BUNDLE_GEMFILE`. You wrote `BUNDLE_GEM_FILE` instead.

**Comment by phuongnd08** [comment]
@colby-swandale I included the `bundle env` output post `unset of BUNDLE_GEMFILE` in this: https://github.com/bundler/bundler/issues/6588#issuecomment-397849288

@deivid-rodriguez Yes sorry my bad, I `unset BUNDLE_GEMFILE`. `echo $BUNDLE_GEMFILE` is returning empty string

**Comment by colby-swandale** [comment]
> After unset BUNDLE_BIN BUNDLE_GEMFILE BUNDLE_PATH BUNDLE_BIN_PATH

You're saying that your unsetting those settings but we can still see them being set by `ENV` vars in `bundle config`.

```
bin_path
  Set via BUNDLE_BIN_PATH: "/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/exe/bundle"
gemfile
  Set via BUNDLE_GEMFILE: "/app/Gemfile"
```

**Comment by deivid-rodriguez** [comment]
Is this a docker image?

**Comment by phuongnd08** [comment]
Yes it is inside a running docker container (Dockerfile: FROM ruby:2.4.3)

**Comment by phuongnd08** [comment]
You're saying that your unsetting those settings but we can still see them being set by ENV vars in bundle config => yes that's right, the env is already unset, yet bundle env still see the value. I unset every variable with `BUNDLE_` prefix yet bundle env still showing samething. I guess it must have persist that to a file

**Comment by colby-swandale** [comment]
@phuongnd08 were you able to resolve this problem?

**Comment by phuongnd08** [comment]
We base off our docker image on `FROM ruby:2.4.3`, which is an official ruby image. I checked the Dockerfile of such image (https://github.com/docker-library/ruby/blob/master/Dockerfile-slim.template) and the maintainer seems to deliberately:

```
# install things globally, for great justice
# and don't create ".bundle" in all our apps
```

I guess this is the reason for technically *polluted* bundle environment.

We didn't find a solution to multiple bundler environment so we have to try to approach the problem from different angle.
