### ISSUE TITLE
can you please help to resolve this!

### ISSUE THREAD

**Issue by nadaa** [bundler/bundler#6592]
Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/bundler/bundler/search?q=undefined+method+%60remotes%27+for+%23%3CBundler++Source++Git+0x00000000018a3b70%3E&type=Issues

**Comment by hsbt** [comment]
Duplicates with https://github.com/bundler/bundler/issues/6563 . Please wait a next release of bundler.

**Comment by nadaa** [comment]
I don't understand!.
When is the next release?
