### ISSUE TITLE
bundle install from local .gem file

### ISSUE THREAD

**Issue by MSP-Greg** [bundler/bundler#6593]
While trying to help someone with an issue using gem A as a dependency, I built a new A gem.

I'd like to test it with their repo, which uses `bundle install`.  Is there an option for installing from a local .gem file, as there is in RubyGems?

The gemfile path option exists, but I can't see how to install from a .gem file.  The docs state:

"Similar to the semantics of the :git option, the :path option requires that the directory in question either contains a .gemspec for the gem, or that you specify an explicit version that bundler should use."

Mentions a .gemspec file, but not .gem file...

Thanks, Greg

**Comment by colby-swandale** [comment]
You cannot install a gem using a `.gem` on the filesystem using Bundler. You can either use the [path](https://bundler.io/v1.16/man/gemfile.5.html#PATH) option and use a local copy of the gem's src. Or install the gem using rubygems and run `bundle install`

**Comment by MSP-Greg** [comment]
@colby-swandale

Thanks.  I'm stepping away from the trunk world, and working more with gems & bundler...

> Or install the gem using rubygems and run bundle install

I'll look at that.  The use case was testing some changes to extension gems (which needed 'pre-compiling') that were a requirement of another gem.

Thanks, Greg
