### ISSUE TITLE
Windows - bundle install - gem with both ruby & fat-binary versions

### ISSUE THREAD

**Issue by MSP-Greg** [bundler/bundler#6594]
This must be stupid question...

An extension gem used in a repo is listed in gemfile.  It is available as both a normal gem (uncompiled) and as a fat-binary (compiled) gem.  When executing `bundle install`, I cannot force the gem to build/compile.  I tried `:platforms => :ruby` in the gemfile, but it still installed the fat-binary...

So, how to I force bundler to install the normal gem?

I do much of my work with trunk, so I often have to bypass bundler.  Now, I'm working with release versions...

Thanks, Greg

**Comment by colby-swandale** [comment]
Can you please share a Gemfile/Gemfile.lock that we can use for context.

**Comment by MSP-Greg** [comment]
> Can you please share a Gemfile/Gemfile.lock that we can use for context.

It's someone else's gem that I was trying to help with.  Not today, but I'll come up with a simple example.

I may not have been clear.  Let's say I'm on Windows 64 bit Ruby. There is requirement for Gem 'a'.  Both `a-1.2.7-x64-mingw32.gem` & `a-1.2.7.gem` are available on RubyGems, and both meet other requirements.  How can Gemfile/Gemfile.lock specify that `a-1.2.7.gem` is used, while allowing other gems to used that are `x64-mingw32` platform?

IOW, can one 'mix & match' pre-compiled and standard within one Gemfile/Gemfile.lock?

Thanks, Greg

**Comment by segiddins** [comment]
> can one 'mix & match' pre-compiled and standard within one Gemfile/Gemfile.lock

yes

**Comment by MSP-Greg** [comment]
@segiddins

I was kind of expecting that was the answer.

It was a long time ago, but I think this issue may be the original reason that I disliked bundler.  I've been active building & testing trunk on MinGW/windows, so I often work with trunk.  Bundler would try to force a pre-compiled gem to install, and they often don't have an upper ruby version constraint (not bundler's fault), and hence, full stop.

I will dig into this later.  I hate to ask, but is there anywhere that describes where the line is between Bundler & RubyGems?

Thanks, Greg





I'll dig into it more later...

**Comment by segiddins** [comment]
>  I hate to ask, but is there anywhere that describes where the line is between Bundler & RubyGems

There's no firm line

**Comment by colby-swandale** [comment]
This seems answered. Closing.
