### ISSUE TITLE
Question: Why does Bundler still support Ruby 1.8.7?

### ISSUE THREAD

**Issue by eregon** [bundler/bundler#6600]
Ruby 1.8.7 is end of life since almost [5 years](https://www.ruby-lang.org/en/news/2013/06/30/we-retire-1-8-7/) now.
I am wondering, why does Bundler still support it?
Would it be enough to tell Ruby 1.8.7 users to use an old version of Bundler known to still support Ruby 1.8.7?

From an external point of view, it seems to create a lot of extra efforts for maintenance and making the codebase harder to read and understand.

**Comment by indirect** [comment]
Bundler conforms to [semantic versioning](https://semver.org]), which means we need to release a major version (e.g. 2.0) to drop compatibility with Ruby 1.8.7. As you can maybe imagine, it has been a complex process to ship breaking changes in Bundler without also breaking every existing Ruby project—but we're getting close. The `master` branch is currently Bundler 2.0, and we're pushing towards a prerelease.

While the `master` branch of this repo does not currently support Ruby 1.8.7, any commits that we backport to Bundler 1.x do need to support Ruby 1.8. After we release the Bundler 2.0 final, we plan to reduce support for the 1.x series to security issues only. At that point, we also plan to stop supporting Ruby 1.8 on the `master` branch. If you want to help, definitely check out the [Bundler 2.0 milestone](https://github.com/bundler/bundler/milestone/13).

**Comment by eregon** [comment]
Thank you for the quick answer, that makes sense.
