### ISSUE TITLE
bundler dependencies sprockets

### ISSUE THREAD

**Issue by derivou** [bundler/bundler#6603]
Heroku  since a couple of days requires for security reason to install gem sprockets >= 2.12.5 (if using  sprockets 2.)  ; But my rails gem is 3.2.21 and bundler says rails 3.2.21 is dependant on sprocket 2.2.1. So no deployment on Heroku possible. How can this be solved ?

**Comment by segiddins** [comment]
Have you tried running `bundle update sprockets` ?

**Comment by derivou** [comment]
Yes, sure. I tried ; Actually it stays with sprockets 2.2.3. If I add gem sprockets 2.12.5 in the gemfile it says rails depends on sprockets 2.2.1 and does not compile. If I change this in the gemfile.lock, it compiles with 2.12.5 but doing this on Heroku is not working (my lock file is window platform so discarded by Heroku and if I change the platform it causes other problems).  I also run gem install bundler and then bundle update but sprockets always stays unchanged. For now, I came back to earlier Heroku service pack but this can only be temprorary. I have to find a solution.

**Comment by segiddins** [comment]
Can you please show the full error message?

**Comment by derivou** [comment]
bundle update sprockets gives : 
[just_update.txt](https://github.com/bundler/bundler/files/2149383/just_update.txt)

adding gem sprockets 2.12.5 in the gemfile =>

D:\WEBplatform>bundle update sprockets
Fetching gem metadata from https://rubygems.org/...........
Fetching gem metadata from https://rubygems.org/..
Resolving dependencies...
Bundler could not find compatible versions for gem "sprockets":
  In Gemfile:
    sprockets (= 2.12.5) x86-mingw32

    rails (= 3.2.21) x86-mingw32 was resolved to 3.2.21, which depends on
      actionpack (= 3.2.21) x86-mingw32 was resolved to 3.2.21, which depends on
        sprockets (~> 2.2.1) x86-mingw32

**Comment by segiddins** [comment]
Looks like you’ll either need to update rails or stick with the old version of action pack then

**Comment by derivou** [comment]
Yes, I'm afraid I have to. But updating is uusally a long way, so I jump to last Rails 5 and have probably  couple of month of work ...

**Comment by segiddins** [comment]
You can also continue using the old version of sprockets, there's nothing in bundler that will stop you from doing that.
