### ISSUE TITLE
undefined method `remotes' for #<Bundler::Source::Git:0x0000563fc0246db8>

### ISSUE THREAD

**Issue by mmustala** [bundler/bundler#6604]
While waiting for a new release that includes a fix for this issue already discussed here https://github.com/bundler/bundler/issues/6563 I was wondering why I only get this error when trying to bundle my project with a Dockerfile like:
```
FROM ruby:2.5.1-alpine3.7

RUN apk update && \
    apk upgrade && \
    apk add git build-base libffi-dev \
    rm -rf /var/cache/apk/*

RUN bundle config --global frozen 1

WORKDIR /usr/src/app

COPY . .
RUN bundle install
```

But when using Dockerfile:
```
FROM ruby:2.5.1

RUN bundle config --global frozen 1

WORKDIR /usr/src/app

COPY . .
RUN bundle install
```
it bundles just fine. Also `ruby:2.5.1-slim` works after installing `git build-essential libffi-dev` packages.

They both use the same version of bundler. But something is different in the way it works. Just cannot think of what it could be.

My Gemfile:
```
source "https://rubygems.org"

gem 'aws-sdk-lambda'
gem 'rollbar'
gem "rdkafka", :git => 'https://github.com/mmustala/rdkafka-ruby.git', :branch => 'master'
gem "rake"
```

Should I install some additional package to make it work also with the alpine version?

**Comment by colby-swandale** [comment]
The bug that is happening in #6563  is in the error report that gets sent to the user, this means that there is a problem compiling the extension in one of your gems. This could is most liking a missing library or object that it requires.

I suggest installing Bundler 1.16.0 before you run bundle install and to see what the error is.
