### ISSUE TITLE
bundler -v reports 1.11.2 after installing 1.16.2 

### ISSUE THREAD

**Issue by vanboom** [bundler/bundler#6625]
I have looked everywhere and cannot figure this one out...

`bundle -v` reports 1.11.2 even after successfully installing 1.16.2.  Furthermore, I have verified that 1.16.2 is the only bundler version in /var/lib/gems/...

* Ubuntu 16.04
* ruby 2.3.1p112

I have another identical 16.04 machine that reports 1.16.2 just fine.

**Comment by colby-swandale** [comment]
I'm not sure how we can really help. The only advice I can offer is checking your gem environment with `gem env` and making sure that you're installing and loading the same gem env.

**Comment by indirect** [comment]
One possible problem I've seen in the past is that your `bundle` executable has somehow hardcoded a path to the wrong Ruby version. Try `head $(which bundle)` to see which Ruby you'll get when you run `bundle`.

But this is definitely a problem with your Ruby environment, and not a bug in Bundler. Sorry. :/
