### ISSUE TITLE
Unfortunately, an unexpected error occurred, and Bundler cannot continue.

### ISSUE THREAD

**Issue by aalluri-navaratan** [bundler/bundler#6630]
Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/bundler/bundler/search?q=No+such+file+or+directory+-+git+clone+%22git+%2F%2Fgithub.com%2Freactjs%2Freact-rails.git%22+%22C+%2FRuby23%2Flib%2Fruby%2Fgems%2F2.3.0%2Fcache%2Fbundler%2Fgit%2Freact-rails-01a4df8cfd590d33cd645d2d96dd9471332018a2%22+--bare+--no-hardlinks+--quiet&type=Issues

**Comment by colby-swandale** [comment]
Please follow the [ISSUE guide](https://github.com/bundler/bundler/blob/master/doc/contributing/ISSUES.md) when opening a new issue.
