### ISSUE TITLE
error command bundle install on windows 7 x64 bit

### ISSUE THREAD

**Issue by chihabmo** [bundler/bundler#6637]
Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/bundler/bundler/search?q=unknown+encoding+name+-+CP720&type=Issues

If there aren't any reports for this error yet, please create copy and paste the report template above into a new issue. Don't forget to anonymize any private data! The new issue form is located at:
https://github.com/bundler/bundler/issues/new

**Comment by colby-swandale** [comment]
This does not offer any information as to what the problem is. Please read [our ISSUE guide](https://github.com/bundler/bundler/blob/master/doc/contributing/ISSUES.md) for opening a new ticket.
