### ISSUE TITLE
bundler fails to find gem version from rubygems.org

### ISSUE THREAD

**Issue by SampsonCrowley** [bundler/bundler#6641]
Sometimes after pushing a gem version to rubygems.org, when I try to update the gem version in a related package i get the error:

**_Could not find gem 'better_record (>= 0.7.0, ~> 0.7)' in any of the gem sources listed in your Gemfile._**

if i run **gem install better_record** the gem is successfully installed locally
if i THEN run bundle, bundler magically finds the gem version that it couldn't find in any sources

**Comment by SampsonCrowley** [comment]
Happened for 3 out of 6 gem releases I pushed on a beta release gem today

**Comment by indirect** [comment]
The index Bundler uses is optimized for making `bundle install` faster, at the cost of sometimes needing up to 1-2 minutes for pushed gems to become available.

**Comment by colby-swandale** [comment]
This is not an issue with Bundler itself.
