### ISSUE TITLE
Bundler could not find compatible versions for gem "ruby"

### ISSUE THREAD

**Issue by olivierlacan** [bundler/bundler#6642]
Bundler: `1.16.3`
Ruby: `2.4.0`

Gemfile: 
```
gem "rails", github: "rails/rails", branch: "master"
```

Seems like Bundler is not yet compatible with the `required_ruby_version` requirements from gemspecs. It reports an incorrect Ruby version as an incompatible gem which seems like it could be misleading. 

```
Bundler could not find compatible versions for gem "ruby":
  In Gemfile:
    ruby

    rails was resolved to 6.0.0.alpha, which depends on
      ruby (>= 2.4.1)
```
https://github.com/rails/rails/blob/59c3ed1b3f90db197000e3867f255781a02412e7/rails.gemspec#L12

Would it be worth reporting this differently to clarify that it's a Ruby version incompatibility and not gem-related because the first place to look for a gem issue is usually the `Gemfile` but not in this case?

I'm guessing this might be trickier than it looks.

**Comment by segiddins** [comment]
> It reports an incorrect Ruby version as an incompatible gem which seems like it could be misleading.

Yeah, this is because I kinda hacked in Ruby & RubyGems compatibility by pretending they're gems. Would it be sufficient to remove the `gem` word ? Or reword ruby/rubygems mismatches to something like "Bundler found conflicting requirements for the ruby version:" ?

@rubymorillo would appreciate your thoughts on this

**Comment by segiddins** [comment]
https://github.com/bundler/bundler/pull/6647 should do that :)

**Comment by rubymorillo** [comment]
@segiddins would just tweak it slightly to: "Bundler found conflicting requirements for Ruby version: "
