### ISSUE TITLE
bundle install not working

### ISSUE THREAD

**Issue by yukichikawada** [bundler/bundler#6674]
#### Reproduce
```
$ rails new rails_app
Fetching source index from https://rubygems.org/
Resolving dependencies...
Network error while fetching https://rubygems.org/quick/Marshal.4.8/puma-3.12.0.gemspec.rz
(execution expired)
         run  bundle exec spring binstub --all
bundler: command not found: spring
Install missing gem executables with bundle install

$ cd rails_app/
$ bundle install
Fetching source index from https://rubygems.org/
Resolving dependencies...
Network error while fetching https://rubygems.org/quick/Marshal.4.8/rails-5.2.1.gemspec.rz
(execution expired)

$ bundle env
$ bundle install --verbose
```

`bundle env` & `bundle install --verbose` [gist](https://gist.github.com/yukichikawada/09df2fc643362b393e395f6f959f962e)
 Line 174 stuck out
`Need to query more than 500 gems. Downloading full index instead...`

#### Trying to accomplish & Command ran
bundle install

#### Expected
to install gems for the new rails app

#### What happened
```
HTTP GET https://index.rubygems.org/versions
Net::OpenTimeout: execution expired
Bundler::HTTPError: Network error while fetching https://index.rubygems.org/versions (execution expired)
HTTP GET https://index.rubygems.org/api/v1/dependencies
Net::OpenTimeout: execution expired
Fetching source index from https://rubygems.org/
Need to query more than 500 gems. Downloading full index instead...
Resolving dependencies...HTTP GET https://rubygems.org/quick/Marshal.4.8/rails-5.2.1.gemspec.rz
Net::OpenTimeout: execution expired
Network error while fetching https://rubygems.org/quick/Marshal.4.8/rails-5.2.1.gemspec.rz
(execution expired)
```
^^^ from bundle install --verbose ^^^
Also, Gemlock.file wasn't created by bundle install.

#### What I've tried
uninstall and reinstalling rbenv
Bundler.io 's trouble shooting guide commands

**Comment by greysteil** [comment]
It looks like you're having trouble connecting to rubygems. Are you able to access https://index.rubygems.org?

I'm going to close this as I'm 99% certain this is related to your setup, and not to Bundler. The index is up and working fine.

**Comment by yukichikawada** [comment]
Thanks. 

I am able to access https://index.rubygems.org

As I've uninstalled and reinstalled rbenv and don't know what else to try, could you recommend what I should investigate regarding my setup?

**Comment by greysteil** [comment]
Those logs are pretty clear that, for whatever reason, Bundler is getting timeouts from all of its https://index.rubygems.org requests. Are you perhaps on a very slow connection? Or is there anything else about your setup that might cause you to experience timeouts? Could your requests be being intercepted and waiting for user input (if you're monitoring outbound requests from your machine for example)?

**Comment by yukichikawada** [comment]
My connection should be fine, my second machine has no issues. And no, I am not monitoring outbound requests.

**Comment by yukichikawada** [comment]
Thanks for the tip. 

From my browser I can get to https://index.rubygems.org, however when I ping the address from my terminal all my requests timeout. Why might that happen?

**Comment by greysteil** [comment]
In that case I'm sorry, I don't have much advice - I've no idea what would be causing that.

Have you tried making the same request Bundler is making from within a console session?

```
require 'net/http'
uri = URI('https://index.rubygems.org/versions')
res = Net::HTTP.get_response(uri)
```

You should get a 200 response to the above.

**Comment by greysteil** [comment]
> From my browser I can get to https://index.rubygems.org, however when I ping the address from my terminal all my requests timeout. Why might that happen?

Interesting! I'm afraid I have literally no idea, though.

**Comment by yukichikawada** [comment]
Ok. Thanks anyways!

FWIW, the console session returned a 200 after 10 seconds or so, but during the same period every ping timed out.
