### ISSUE TITLE
Bundler does not build native extensions on jruby when using git dependencies

### ISSUE THREAD

**Issue by p-mongo** [bundler/bundler#6678]
Using jruby 9.2.0.0.

This gemfile works:

<pre>
source "https://rubygems.org"

gem 'bson'
</pre>

bundle install:

<pre>
Fetching gem metadata from https://rubygems.org/...............
Resolving dependencies...
Using bson 4.3.0 (java)
Using bundler 1.16.2
Bundle complete! 1 Gemfile dependency, 2 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
</pre>

Test:

<pre>
speed% be irb
irb(main):001:0> require 'bson'
=> true
irb(main):002:0> 
</pre>

However if I use git master of bson like this:

<pre>
source "https://rubygems.org"

gem 'bson', git: "https://github.com/mongodb/bson-ruby"
</pre>

It installs:

<pre>
[bson] Warning: No private key present, creating unsigned gem.
Fetching gem metadata from https://rubygems.org/
Resolving dependencies...
Using bson 4.3.0 (java) from https://github.com/mongodb/bson-ruby (at master@ef18ddd)
Using bundler 1.16.2
Bundle complete! 1 Gemfile dependency, 2 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
</pre>

But requiring bson fails:

<pre>
speed% be irb
irb(main):001:0> require 'bson'
Failed to load the necessary extensions.
Traceback (most recent call last):
       16: from /home/w/.rbenv/versions/jruby-9.2.0.0/lib/ruby/gems/shared/gems/bundler-1.16.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
       15: from /home/w/.rbenv/versions/jruby-9.2.0.0/lib/ruby/gems/shared/gems/bundler-1.16.2/lib/bundler/cli.rb:424:in `exec'
       14: from /home/w/.rbenv/versions/jruby-9.2.0.0/lib/ruby/gems/shared/gems/bundler-1.16.2/lib/bundler/cli/exec.rb:28:in `run'
       13: from /home/w/.rbenv/versions/jruby-9.2.0.0/lib/ruby/gems/shared/gems/bundler-1.16.2/lib/bundler/cli/exec.rb:74:in `kernel_load'
       12: from /home/w/.rbenv/versions/jruby-9.2.0.0/lib/ruby/gems/shared/gems/bundler-1.16.2/lib/bundler/cli/exec.rb:1:in `(root)'
       11: from /home/w/.rbenv/versions/jruby-9.2.0.0/bin/irb:13:in `(root)'
       10: from org/jruby/RubyKernel.java:994:in `load'
        9: from org/jruby/RubyKernel.java:1180:in `catch'
        8: from org/jruby/RubyKernel.java:1180:in `catch'
        7: from org/jruby/RubyKernel.java:1418:in `loop'
        6: from (irb):1:in `evaluate'
        5: from org/jruby/RubyKernel.java:1037:in `eval'
        4: from (irb):1:in `<eval>'
        3: from org/jruby/RubyKernel.java:970:in `require'
        2: from /home/w/.rbenv/versions/jruby-9.2.0.0/lib/ruby/gems/shared/bundler/gems/bson-ruby-ef18dddce818/lib/bson.rb:99:in `<main>'
        1: from org/jruby/RubyKernel.java:970:in `require'
LoadError (no such file to load -- bson-ruby)
irb(main):002:0> 
</pre>

In case of using bson master, the installation is much quicker and there's no bson-ruby.jar in the bson tree under ~/.rubies.

**Comment by segiddins** [comment]
This is because `bson` explicitly does not set extensions for JRuby.

https://github.com/mongodb/bson-ruby/blob/69f3dd4123441541a51cca825a91a8b714a8aaa1/bson.gemspec#L29-L35
