### ISSUE TITLE
Specifying gem runtime dependencies to be fetched from git within other gems fetched from git.

### ISSUE THREAD

**Issue by michaellmonaghan** [bundler/bundler#6690]
I am using bundler to fetch gems only hosted only within a git repository. The dependencies of these gems are also only hosted within git repositories as well. How can the run time dependencies for gems fetched from git be specified to be fetched from git? 

I tried adding gem lines to a gemfile within the gem requiring the dependencies but it does not appear to work.

**Comment by greysteil** [comment]
Hey @michaellmonaghan 👋.

It's not possible to specify alternative sources in a gemspec, so I don't think there's any way you can specify that sub-dependencies should also be fetched from a git repo. You can, however, move all of those sub-dependencies up to the top-level in your Gemfile with a git source on them, and Bundler will then fetch them from git.

Can you the Gemfile, Gemfile.lock, and gemspecs of the git dependencies you're trying to get this working for? In the meantime I'm going to close this so it doesn't cause any confusion for others.

**Comment by michaellmonaghan** [comment]
Thanks for the quick reply @greysteil!

I am currently listing all the git exclusive gem dependencies for each git exclusive gem in the project gemfile. I was curious if there was a more elegant solution. I'm thinking of using git submodules within the git exclusive gems requiring other git exclusive gems.

**Comment by greysteil** [comment]
No worries! You should be fine with sub-modules (Bundler clones them down too when it clones a git repo), but there's no more elegant solution than promoting everything to the top level - sorry! It keeps things *much* simpler on Bundler's side not to support arbitrary sources in the gemspec.
