### ISSUE TITLE
ENOMEM: Cannot allocate memory when running 'bundle exec jruby'

### ISSUE THREAD

**Issue by Sanchazo** [bundler/bundler#6700]
My system has plenty of memory.  This is running in WSL within Windows 10 build 1803.

https://gist.github.com/Sanchazo/174fd0986ca94784ecb08ffb1f7b6657

**Comment by ahorek** [comment]
could you try this?
```
set JRUBY_OPTS="-J-Xmx1000m"
```

**Comment by Sanchazo** [comment]
I actually already tried increasing the heap size to 5g with
`set JRUBY_OPTS="-J-Xmx5g"`
The error for java heap size is a bit different and specifcally references the java heap.

Thanks

**Comment by colby-swandale** [comment]
We won't be able to offer much help about this issue, i suggest opening an issue on the JRuby project and include as much details as possible @ https://github.com/jruby/jruby
