### ISSUE TITLE
Should Gemfile.lock be checked in into gem repositories?

### ISSUE THREAD

**Issue by jmonteiro** [bundler/bundler#6712]
On the [How to create a Ruby gem with Bundler](https://bundler.io/v1.16/guides/creating_gem.html) guide page, there's a mention about adding the `Gemfile.lock` when creating gems:

> (...) Gemfile.lock file (...) should always be checked into version control (...)

Although it's clearly stated, there are no mentions on why that's a good idea. What are the benefits of that approach?

There's also an old article from @wycats from 2010 [recommending not including Gemfile.lock](https://yehudakatz.com/2010/12/16/clarifying-the-roles-of-the-gemspec-and-gemfile/), although it might be very outdated as it's 8 years old.

If there are any other articles about this subject, I'd love to read them.

Taking a look on random gems, I found that a vast majority do not check the Gemfile.lock into their repositories.

That all said, **what's the official recommendation when creating a new gem: should we add Gemfile.lock or not? What are the pros and cons of it?**

**Comment by colby-swandale** [comment]
Yes, the official recommendation is to commit the `Gemfile.lock`. See also https://bundler.io/v1.16/guides/faq.html#committing-lockfiles-in-libraries for more information.
