### ISSUE TITLE
Recognize aarch64_linux_android platform please

### ISSUE THREAD

**Issue by afstanton** [bundler/bundler#6736]
When I type `bundle platform` in Termux, I get back `aarch64-linux-android`. I'd like to add that to the platforms in a Gemfile, but it appears that bundler does not recognize it in the list of valid platforms. (In particular, the tzinfo-data gem for Rails. I can take out the platform requirements, but that makes the gem install unnecessarily on platforms that don't need it.)

**Comment by segiddins** [comment]
Those platforms refer more to the _type of ruby_ that is being run on, rather than the OS

**Comment by colby-swandale** [comment]
This seems answered. Closing.
