### ISSUE TITLE
Facing issue on  "bundle exec rails console"  command 

### ISSUE THREAD

**Issue by dayalan719** [bundler/bundler#6759]
Hi ,
I have try to upgrade my ruby software 2.5.1.
I'm having issue , while executing the following command "bundle exec rails  console".
![error1](https://user-images.githubusercontent.com/40753616/47516840-1a2a0e00-d8a4-11e8-9777-8acc6409fb02.png)
I'm getting error like "Cannot load such a file--- 2.5/pg_ext "

Please help me to resolve this issue .

**Comment by bitsapien** [comment]
You will probably need to run `bundle install` again. If that does not work, try - `gem install pg` again.

**Comment by colby-swandale** [comment]
This doesn't seem like an issue with Bundler, i suggest sharing your problem to https://stackoverflow.com.
