### ISSUE TITLE
Event 'rys-gemfile' not defined in Bundler::Plugin::Events

### ISSUE THREAD

**Issue by ondra-m** [bundler/bundler#6766]
Hello,

I have a plugin for bundler which register a hook. The hook is then called in a Gemfile.

`bundle install` fail because the event is not yet register. It works in version `< 1.17`.

```ruby
# Gemfile

# register plugin
plugin 'rys-bundler', github: 'easysoftware/rys-bundler', branch: 'master'

# <-- This fail because bundler needs a defined event 
# <-- However the event is registered in the plugin above
Plugin.hook('rys-gemfile', self) 
```

Is there any chance that it will works again? I would like to avoid using `rescue`.

Thanks

**Comment by segiddins** [comment]
Can you please share the full error that you’re seeing? Thanks!

**Comment by ondra-m** [comment]
```
[!] There was an error parsing `Gemfile`:
[!] There was an error parsing `Gemfile`: Event 'rys-gemfile' not defined in Bundler::Plugin::Events. Bundler cannot continue.

# from Gemfile
# -------------------------------------------
# plugin 'rys-bundler', github: 'easysoftware/rys-bundler', branch: 'master'
> Plugin.hook('rys-gemfile', self)
# -------------------------------------------
```

**Comment by colby-swandale** [comment]
This is happening because of #6548 where we restrict the events to only be defined by Bundler. You will need to change your plugin to use either the `before-install`, `after-install`, `before-install-all` or `after-install-all` events

**Comment by ondra-m** [comment]
Will it change in the future or hooks are designed only for Bundler's internal things?

**Comment by colby-swandale** [comment]
Hooks will only be defined by Bundler going forward.

**Comment by ondra-m** [comment]
`rescue` will solve it
