### ISSUE TITLE
How to disable warning: Following files may not be writable, so sudo is needed

### ISSUE THREAD

**Issue by nleo** [bundler/bundler#6767]
```
Following files may not be writable, so sudo is needed:
  /usr/local/bin
  /var/lib/gems/2.5.0
  /var/lib/gems/2.5.0/build_info
  /var/lib/gems/2.5.0/cache
  /var/lib/gems/2.5.0/doc
  /var/lib/gems/2.5.0/extensions
  /var/lib/gems/2.5.0/gems
  /var/lib/gems/2.5.0/specifications
```

**Comment by nleo** [comment]
Quick googling doesn't helps me. Another warning shows how disable it by him self:

```
The git source `git://github.com/goodwill/capybara-select2.git` uses the `git` protocol, which transmits data without encryption. Disable this warning with `bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.
```

**Comment by colby-swandale** [comment]
There is currently no way to disable that message.

**Comment by MilovanTomasevic** [comment]
sudo chown -R `whoami`:ADMIN /usr/local/bin
  sudo chown -R `whoami`:ADMIN /var/lib/gems/2.5.0
  sudo chown -R `whoami`:ADMIN /var/lib/gems/2.5.0/build_info
  sudo chown -R `whoami`:ADMIN /var/lib/gems/2.5.0/cache
  sudo chown -R `whoami`:ADMIN /var/lib/gems/2.5.0/doc
  sudo chown -R `whoami`:ADMIN /var/lib/gems/2.5.0/extensions
  sudo chown -R `whoami`:ADMIN /var/lib/gems/2.5.0/gems
  sudo chown -R `whoami`:ADMIN /var/lib/gems/2.5.0/specifications

**Comment by MilovanTomasevic** [comment]
`sudo chown -R `whoami`:mt /usr/local/bin`
  `sudo chown -R `whoami`:mt /var/lib/gems/2.5.0`
  `sudo chown -R `whoami`:mt /var/lib/gems/2.5.0/build_info`
  `sudo chown -R `whoami`:mt /var/lib/gems/2.5.0/cache`
  `sudo chown -R `whoami`:mt /var/lib/gems/2.5.0/doc`
  `sudo chown -R `whoami`:mt /var/lib/gems/2.5.0/extensions`
  `sudo chown -R `whoami`:mt /var/lib/gems/2.5.0/gems`
  `sudo chown -R `whoami`:mt /var/lib/gems/2.5.0/specifications`

**Comment by MilovanTomasevic** [comment]
sudo chown -R `whoami`:mt /usr/local/bin
  sudo chown -R `whoami`:mt /var/lib/gems/2.5.0
  sudo chown -R `whoami`:mt /var/lib/gems/2.5.0/build_info
  sudo chown -R `whoami`:mt /var/lib/gems/2.5.0/cache
  sudo chown -R `whoami`:mt /var/lib/gems/2.5.0/doc
  sudo chown -R `whoami`:mt /var/lib/gems/2.5.0/extensions
  sudo chown -R `whoami`:mt /var/lib/gems/2.5.0/gems
  sudo chown -R `whoami`:mt /var/lib/gems/2.5.0/specifications

whoami put in ``

**Comment by MilovanTomasevic** [comment]
```console
  sudo chown -R `whoami`:<your_username> /var/lib/gems/2.5.0
  sudo chown -R `whoami`:<your_username> /var/lib/gems/2.5.0/build_info
  sudo chown -R `whoami`:<your_username> /var/lib/gems/2.5.0/cache
  sudo chown -R `whoami`:<your_username> /var/lib/gems/2.5.0/doc
  sudo chown -R `whoami`:<your_username> /var/lib/gems/2.5.0/extensions
  sudo chown -R `whoami`:<your_username> /var/lib/gems/2.5.0/gems
  sudo chown -R `whoami`:<your_username> /var/lib/gems/2.5.0/specifications
  ```

EDIT: Changed command to try to make clearer that it shouldn't be run as is.

**Comment by Elta3lab** [comment]
> ```
>   sudo chown -R `whoami`:mt /var/lib/gems/2.5.0
>   sudo chown -R `whoami`:mt /var/lib/gems/2.5.0/build_info
>   sudo chown -R `whoami`:mt /var/lib/gems/2.5.0/cache
>   sudo chown -R `whoami`:mt /var/lib/gems/2.5.0/doc
>   sudo chown -R `whoami`:mt /var/lib/gems/2.5.0/extensions
>   sudo chown -R `whoami`:mt /var/lib/gems/2.5.0/gems
>   sudo chown -R `whoami`:mt /var/lib/gems/2.5.0/specifications
> ```

chown: invalid group: ‘elta3lab:mt’

**Comment by nleo** [comment]
1. subl /var/lib/gems/2.5.0/gems/bundler-1.17.1
2. Ctrl+shift+F `Following files may not be writable, so sudo is needed`
3. Delete 3 lines of code

**Comment by nleo** [comment]
Also you can automate this with sed:

`sudo sed -i '/if sudo_needed/I,+2 d' /usr/local/lib/site_ruby/2.5.0/bundler.rb`

**Comment by danlo** [comment]
https://stackoverflow.com/questions/16376995/bundler-cannot-install-any-gems-without-sudo
