### ISSUE TITLE
Default Gems loading

### ISSUE THREAD

**Issue by eric-hemasystems** [bundler/bundler#6772]
With Ruby 2.5 the number of "default gems" [has expanded](https://stdgems.org/2.5.0/) to cover a lot of libraries that were previously bundled in Ruby. I think the intention is for this to be mostly an internal change. Developers should be able to just `require` the same as when they were bundled in Ruby.

In combination with `bundler` it seems this change is more noticeable. Previously I could just `require 'fileutils'` without modifying my Gemfile. Now I get this message:

```
Gem::LoadError (fileutils is not part of the bundle. Add it to your Gemfile.)
```

It seems to me that the default gems should be assumed in the Gemfile to maintain the historical behavior so I don't need to explicitly include libraries like `fileutils` in my Gemfile. If someone wants a specific version of a default gem they could of course specify that in their Gemfile.

Steps to Reproduce
--------------------

Verify at latest versions:

```
$ ruby -v
ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin18]
$ bundle -v
Bundler version 1.17.1
$ gem -v
2.7.8
```

Verify desired stdlib is not part of Gemfile:

```
$ grep fileutils Gemfile.lock 
```
Without bundler we can load the stdlib fine:

```
$ irb
irb(main):001:0> require 'fileutils'
=> true
```

With bundler we can no longer load the stdlib:

```
$ bundle exec irb
irb(main):001:0> require 'fileutils'
Traceback (most recent call last):
[....snip backtrace....]
Gem::LoadError (fileutils is not part of the bundle. Add it to your Gemfile.)
```

I can fix by adding fileutils but that shouldn't seem necessary for stdlibs.

**Comment by deivid-rodriguez** [comment]
#6963 should fix this, I think.

**Comment by eric-hemasystems** [comment]
I believe it will. Closing this under that assumption.
