### ISSUE TITLE
bundle update / bundle install failures

### ISSUE THREAD

**Issue by ottaviana** [bundler/bundler#6778]
Background info:

I download a my repository with Ruby files in it. When I run bundle install or bundle update I get this message:

```Fetching https://github.com/whatever/gem_whatever.git
The gemspec at /Users/whatever/.rvm/gems/ruby-2.5.1/bundler/gems/gem_whatever-6957c7a5bf83/whatever.gemspec is not valid. Please fix this gemspec.
The validation error was '"htttps://github.com/whatever/whatever" is not a valid HTTP URI
```

Sorry, bit of a beginner with this one. Thanks

**Comment by deivid-rodriguez** [comment]
@ottaviana This sounds like a misspelling, `htttps://github.com/whatever/whatever` should be `https://github.com/whatever/whatever`.

**Comment by colby-swandale** [comment]
ping @ottaviana. Were you able to solve your issue?
