### ISSUE TITLE
Stop bundler from remembering command line options

### ISSUE THREAD

**Issue by roberts1000** [bundler/bundler#6779]
Is there a way to tell bundler to not generate a `.bundle/config` file when we run bundle install with options (`bundle install --jobs=4 --retry=4`)?  This behavior is unexpected and it's causing an issue in my CI pipeline.  One of the tools in the pipeline detects the .bundle/config file in the application and throws a warning

```
**WARNING** You have the `.bundle/config` file checked into your repository. 
It contains local state like the location of the installed bundle as well as 
configured git local gems, and other settings that should not be shared 
between multiple checkouts of a single repo...
````

.bundle/config isn't checked into the repo, but it is created when I `bundle install ....` gets invoked on the pipeline.  It looks like this issue has been reported and discussed multiple times over the years.

Is there a recommended way to turn this behavior off? If not, could we consider adding an environment variable, or another command line option, to disable it?

**Comment by segiddins** [comment]
This will be changed in Bundler 3, which will follow shortly after Bundler 2, and the code for this transition is already in master.
