### ISSUE TITLE
Official ruby docker images set BUNDLER_VERSION

### ISSUE THREAD

**Issue by deivid-rodriguez** [bundler/bundler#6782]
I noticed that the official docker images for ruby set the `BUNDLER_VERSION` [environment variable](https://github.com/docker-library/ruby/blob/7efc2b75c021c08bbe17207059b5fb3d21dd7355/Dockerfile-alpine.template#L10-L14), and thus change the behavior of bundler.

This means that under a docker image, if you have a lock file like the following:

```
GEM
  remote: https://rubygems.org/
  specs:

PLATFORMS
  ruby

DEPENDENCIES

BUNDLED WITH
   1.16.4
```

and you're using a ruby image shipping 1.17.1 (the current latest), you'll be using the bundler version specified in the environment, 1.17.1, instead of the locked version in your lockfile, 1.16.4 (if you use the proper binstubs to run bundler).

This seems like expected behavior to me: you'll normally want the locked version in your lockfile to be used, but you can override it via environment if you need to. But I feel that the fact that all docker images set this environment variable by default can lead to confusion.

It seems to me that the ruby docker images only need these environment variables at build time, and it is unintended to leak them to the image at runtime. So, they should probably use [`ARG` instead of `ENV`](https://docs.docker.com/engine/reference/builder/#using-arg-variables) in this case (or at least rename the `BUNDLER_VERSION` environment variable). @bundler/maintainers Do you agree? Would you support adding a PR to the docker images to do this, so the default bundler behavior is not changed?

**Comment by indirect** [comment]
Your reasoning makes sense to me. 👍🏻 I have one thing to add, which is that for Bundler versions 1.x, Bundler treats any 1.x version (in both the env var and in the lock file) as “matching” with any running 1.x version of Bundler. The logic to exec to the locked version does not kick in until the locked version is 2.0 or greater.

**Comment by deivid-rodriguez** [comment]
Indeed, :+1:

https://github.com/bundler/bundler/blob/98040394795a8e5fd03d7e893f1a060041cd6777/lib/bundler/templates/Executable.bundler#L77-L83

I'll start this discussion at https://github.com/docker-library/ruby, then.

**Comment by deivid-rodriguez** [comment]
I opened a [new ticket](https://github.com/docker-library/ruby/issues/246) on the official repository for the docker images!
