### ISSUE TITLE
Change `github` to HTTPS in Bundler 2+

### ISSUE THREAD

**Issue by indirect** [bundler/bundler#6785]
As part of shipping Bundler 2 with "no brainer" changes that are technically breaking, we should update the `github` Gemfile DSL shortcut to use HTTPS instead of HTTP, and we should remove `git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }` from the Gemfile generated by `bundle init` and generated by `bundle gem foo`.

**Comment by gavrieltal** [comment]
I am looking for an open source project to get involved in, and I was recommended by a friend to start with Bundler. I'll try solving this one.

**Comment by gavrieltal** [comment]
a few questions:

is running `$ bin/rake spec` on a clean fork of the development master supposed to spit out hundreds of errors?

Do you want the relevant code simply commented out, saying that it used to be there, or do you want it outright removed?

Do you also want to remove `git_source(:bitbucket)` and `git_source(:gist)`?

**Comment by colby-swandale** [comment]
@gavrieltal I'm currently working on this issue. You should checkout our [help wanted/good first issue](https://github.com/bundler/bundler/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22+label%3A%22good+first+issue%22) tags that has a list of issues that we think are good first new contributors to get started on.

**Comment by deivid-rodriguez** [comment]
> is running $ bin/rake spec on a clean fork of the development master supposed to spit out hundreds of errors?

If I recall correctly, you need to run `bin/rake spec:deps` first.

**Comment by gavrieltal** [comment]
I got these error messages, don't know what it means entirely:
```Could not find 'rdiscount' (~> 2.2) among 47 total gem(s)
Checked in 'GEM_PATH=/home/gavriel/.gem/ruby/2.5.0:/var/lib/gems/2.5.0:/usr/lib/x86_64-linux-gnu/rubygems-integration/2.5.0:/usr/share/rubygems-integration/2.5.0:/usr/share/rubygems-integration/all', execute `gem env` for more information (Gem::MissingSpecError)
Could not find 'ronn' (~> 0.7.3) among 47 total gem(s)
Checked in 'GEM_PATH=/home/gavriel/.gem/ruby/2.5.0:/var/lib/gems/2.5.0:/usr/lib/x86_64-linux-gnu/rubygems-integration/2.5.0:/usr/share/rubygems-integration/2.5.0:/usr/share/rubygems-integration/all', execute `gem env` for more information (Gem::MissingSpecError)
/usr/bin/ruby2.5 -S gem install --no-document --conservative 'automatiek:~> 0.1.0' 'mustache:= 0.99.6' 'rake:~> 10.0' 'rdiscount:~> 2.2' 'ronn:~> 0.7.3' 'rspec:~> 3.6' 'rubocop:= 0.50.0'
Building native extensions. This could take a while...
ERROR:  Error installing rdiscount:
       ERROR: Failed to build gem native extension.

   current directory: /var/lib/gems/2.5.0/gems/rdiscount-2.2.0.1/ext
/usr/bin/ruby2.5 -r ./siteconf20181121-12145-1u253ii.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.5.0/gems/rdiscount-2.2.0.1 for inspection.
Results logged to /var/lib/gems/2.5.0/extensions/x86_64-linux/2.5.0/rdiscount-2.2.0.1/gem_make.out
Building native extensions. This could take a while...
ERROR:  Error installing ronn:
       ERROR: Failed to build gem native extension.

   current directory: /var/lib/gems/2.5.0/gems/rdiscount-2.2.0.1/ext
/usr/bin/ruby2.5 -r ./siteconf20181121-12145-8qf0vf.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

extconf failed, exit code 1
...```

**Comment by gavrieltal** [comment]
I had to install a number of packages to get past this point, including `ruby-dev`, `rubocop`, `ruby-full`, and `ruby-build`. I don't know that all of them are necessary per se. I'm still trying to get my fork to run spec cleanly (spec:deps works now), but I've moved my conversation onto slack. Maybe I'll write some docs about my experience if things work out.
