### ISSUE TITLE
Single line comment typo spec/bundler/ssl_certs/certificate_manager_spec.rb#L14

### ISSUE THREAD

**Issue by MSP-Greg** [bundler/bundler#6789]
certificates...

https://github.com/bundler/bundler/blob/9cfe9bd9be4b44bde1fd71e6faab494509ceb7b6/spec/bundler/ssl_certs/certificate_manager_spec.rb#L14

**Comment by gavrieltal** [comment]
may I claim this ticket?

Also, is it okay that a clean fork of the repository has 50+ errors in `bin/rake spec`?

**Comment by hsbt** [comment]
This is fixed at https://github.com/bundler/bundler/pull/6794
