### ISSUE TITLE
Bundle exec on Windows has no outputs

### ISSUE THREAD

**Issue by Maik93** [bundler/bundler#6792]
Hi all,
sorry to create new issue in something that seems so easy to solve, but I can't find a solution: I'm on Windows (completely new to gem and bundle, I'm just trying to use them for Jekyll), when I run `bundle exec jekyll serve` there's no output, neither with `bundle exec jekyll build`.
It's not a problem of Jekyll, because running that commands directly (without `bundle exec`) outputs as normal (but it can't compile my project due to dependency problems, and here it's why I need to use bundle).

Here's my `bundle env` output:
> ## Environment
>
> ```
> Bundler       1.17.1
>   Platforms   ruby, x64-mingw32
> Ruby          2.5.3p105 (2018-10-18 revision 65156) [x64-mingw32]
>   Full Path   C:/Ruby25-x64/bin/ruby.exe
>   Config Dir  C:/ProgramData
> RubyGems      2.7.6
>   Gem Home    C:/Ruby25-x64/lib/ruby/gems/2.5.0
>   Gem Path    C:/Users/super/.gem/ruby/2.5.0;C:/Ruby25-x64/lib/ruby/gems/2.5.0
>   User Path   C:/Users/super/.gem/ruby/2.5.0
>   Bin Dir     C:/Ruby25-x64/bin
> Tools         
>   Git         2.17.1.windows.2
>   RVM         not installed
>   rbenv       not installed
>   chruby      not installed
> ```
> 
> ## Bundler Build Metadata
> 
> ```
> Built At          2018-10-25
> Git SHA           2760d72d3
> Released Version  true
> ```
> 
> ## Gemfile
> 
> ### Gemfile
> 
> ```ruby
> source "https://rubygems.org"
> 
> gem "github-pages", group: :jekyll_plugins
> 
> # Windows does not include zoneinfo files, so bundle the tzinfo-data gem
> gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]
> 
> # Performance-booster for watching directories on Windows
> gem "wdm", "~> 0.1.1" if Gem.win_platform?
> ```
> 
> ### Gemfile.lock
> 
> ```
> GEM
>   remote: https://rubygems.org/
>   specs:
>      [...]
> 
> PLATFORMS
>   x64-mingw32
> 
> DEPENDENCIES
>   github-pages
>   tzinfo-data
>   wdm (~> 0.1.1)
> 
> BUNDLED WITH
>    1.17.1
> ```

Appreciating any help!

**Comment by Maik93** [comment]
Hi, this is what the same command (`bundle exec jekyll build`) shows on my Ubuntu 18.04 partition:

> Configuration file: ./_config.yml
>             Source: .
>        Destination: ./_site
>  Incremental build: disabled. Enable with --incremental
>       Generating... 
>        Jekyll Feed: Generating feed for posts
>                     done in 1.359 seconds.
>  Auto-regeneration: enabled
>     Server address: http://127.0.0.1:4000/
>   Server running... press ctrl-c to stop.

Your command (`bundle exec ruby -e 'puts :hi'`) prints "hi" as normal. Don't know what to think.

**Comment by deivid-rodriguez** [comment]
Hi @Maik93, I know this is a very old issue, but I'll ask just in case. Are you still having this issue? I think this should be fixed in newer versions of bundler.

**Comment by Maik93** [comment]
Yea just tried, everything works as expected!
Thanks, we can close the issue!

**Comment by deivid-rodriguez** [comment]
Thanks so much for double checking!
