### ISSUE TITLE
Plugin can't be installed through Gemfile when bundler is frozen

### ISSUE THREAD

**Issue by Edouard-chin** [bundler/bundler#6795]
Hello guys 👋 ,

We recently decided to create a Bundler plugin to help our many applications at Shopify dualboot their app. #6777 talks more about the "dualbooting" part and why it's useful.

After finishing writing the plugin, I realized that plugins can't be installed while bundler is frozen, which in our case is always true in production (the heroku ruby buildpack runs `bundle install --deployment`). This makes the plugin feature unusable if an app declare `plugin 'some_plugin'` in their Gemfile.

The error is `Unable to find a spec satisfying bootboot (>= 0) in the set. Perhaps the lockfile is corrupted?`, which makes sense since plugins don't get written as part of the Gemfile.lock snapshot.

While I'm not very familiar with Bundler, this seems to be a bug to me as otherwise the `plugin` and the source feature that comes with it is completely useless.
Shall plugins be part of the lockfile snapshot or should we allow their installation when bundler is frozen even when they aren't in the snapshot?

For some context and if you are curious you can find the "bootboot" plugin here https://github.com/shopify/bootboot

**Comment by indirect** [comment]
That... seems right to me. At least one of those things. I'm slightly concerned that plugins without locking might ship updates and produce breaking changes, but also slightly concerned that adding plugins to the lockfile might break backwards compatibility? Maybe the compatible option is to allow installing plugins even if they aren't in the lock. Any thoughts here, @segiddins?

**Comment by segiddins** [comment]
Is there a sample project that demonstrates the issue?

**Comment by segiddins** [comment]
Thanks! managed to reproduce and I think I have a fix, just need to write a test!
