### ISSUE TITLE
force_ruby_platform misses gemspec dependencies on Windows

### ISSUE THREAD

**Issue by deivid-rodriguez** [bundler/bundler#6801]
If you use `force_ruby_platform` on Windows, gemspec dependencies seem to be ignored. I was using this setting on byebug because I had [problems](https://ci.appveyor.com/project/deivid-rodriguez/byebug/build/746/job/5im93y1wd05629fr) in the past when installing some default gems under Windows, and setting that [fixed it](https://github.com/deivid-rodriguez/byebug/pull/343).

Since I encountered this problem I have now [removed the setting](https://github.com/deivid-rodriguez/byebug/pull/512), and things seem to be working fine, but I thought I would report it anyways.

I created a [sample project](https://github.com/deivid-rodriguez/force_ruby_platform_test) to demostrate [the issue](https://ci.appveyor.com/project/deivid-rodriguez/force-ruby-platform-test/builds/20503688). Basically, when I specify a runtime dependency on the gemspec (`rouge` in this case), and I use `force_ruby_platform` on Windows, this new dependency is ignored by `bundle install` even if the `gemspec` DSL is properly specified in the `Gemfile`.

**Comment by segiddins** [comment]
I don't have a windows machine handy, so can you check if https://github.com/bundler/bundler/pull/6809 fixes the sample project?

**Comment by deivid-rodriguez** [comment]
@segiddins Thanks so much for working on this!

I don't have a windows machine either, but I can configure appveyor :)

I tried to use your fix in the sample project's appveyor configuration. When using it, `bundle install` _does_ seem to install the dependency ("Installing rouge" is logged), so I think the issue is at least partially fixed. However, I cannot subsequently require the dependency. Not sure if this is still the same issue, a separate problem, or a problem with the way I'm running bundler under Windows. See https://ci.appveyor.com/project/deivid-rodriguez/force-ruby-platform-test for the latest build and https://github.com/deivid-rodriguez/force_ruby_platform_test/commits/master for the latest changes I added to the sample project.

**Comment by segiddins** [comment]
Huh, the test shows the file is requireable....

**Comment by segiddins** [comment]
Ah yeah. -r will come before the require Bundler puts in RUBYOPT

**Comment by deivid-rodriguez** [comment]
I see! Tried it in a different way and it worked now :point_right: https://ci.appveyor.com/project/deivid-rodriguez/force-ruby-platform-test/builds/20567819.
