### ISSUE TITLE
bundle list --without-group/--only-group not supported

### ISSUE THREAD

**Issue by Aqualon** [bundler/bundler#6813]
The `bundle list` options `--without-group` and `--only-group` added in https://github.com/bundler/bundler/pull/6572 fail for me with error `Unknown switches '--without-group'`

```
$ bundle version
Bundler version 1.17.1 (2018-10-25 commit 2760d72d3)
$ ruby --version
ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin18]
```

macOS Mojave 10.14.1 (18B75)

**Comment by colby-swandale** [comment]
Hi! These switches are available only on the new `bundle list` command that will be enabled by default in a future major release.

If you would like try it out now, you can enable the new list command by enabling the `list_command` feature flag with `bundle config list_command true`
