### ISSUE TITLE
Use single quotes in Gemfile (feature request)

### ISSUE THREAD

**Issue by ConorSheehan1** [bundler/bundler#6815]
## Feature request

Use single quotes in Gemfile for bundle commands that don't require string interpolation or special symbols.

## Usecase

Whenever I use `bundle add` I have to manually change the strings from double to single quotes to make rubocop happy. For example:

```shell
gem install bundler -v 1.17.1
printf "# frozen_string_literal: true\n\nsource 'https://rubygems.org'\n" > Gemfile
bundle add rubocop
bundle exec rubocop
```

```
# rubocop output
Inspecting 1 file
C

Offenses:

Gemfile:5:5: C: Style/StringLiterals: Prefer single-quoted strings when you don't need string interpolation or special symbols.
gem "rubocop", "~> 0.60.0"
    ^^^^^^^^^
Gemfile:5:16: C: Style/StringLiterals: Prefer single-quoted strings when you don't need string interpolation or special symbols.
gem "rubocop", "~> 0.60.0"
               ^^^^^^^^^^^

1 file inspected, 2 offenses detected
```

**Comment by hsbt** [comment]
Duplicates with https://github.com/bundler/bundler/issues/4220 and https://github.com/bundler/bundler/issues/4289

**Comment by ConorSheehan1** [comment]
Worth noting https://github.com/bundler/bundler/pull/6121 is open and would solve this issue. 
However, it's has been open since 2017, and now has conflicts and failing specs.

Looks like this has been the subject of debate on rubocop as well https://github.com/rubocop-hq/rubocop/issues/5306
