### ISSUE TITLE
how to debug a local version of bundler for development

### ISSUE THREAD

**Issue by gavrieltal** [bundler/bundler#6816]
Hi,

I'm relatively new to ruby development, and I'm trying to write tests for bundler. How do I run and/or debug a local version of bundler dev with source changes? Maybe is there a way to manually compile an executable in a local directory? Or is there a way to build a custom local gem and then require it in pry?

Thanks!

**Comment by colby-swandale** [comment]
Hi, I suggest checkout the some guides on how to debug ruby programs like https://www.rubyguides.com/2015/07/ruby-debugging and follow our [development guide](https://github.com/bundler/bundler/blob/master/doc/development/SETUP.md)
