### ISSUE TITLE
Where to report security bugs?

### ISSUE THREAD

**Issue by lzap** [bundler/bundler#6817]
Hello,

I've found a possible security issue, last week I sent an e-mail to team-at-bundler.io without any response so far. It is likely that core team is busy enough or my finding was not considered as important and that is fine. However while waiting for response, I wonder if it makes sense for you to set a security-at-bundler.io contact for those kinds of reports. Thus creating this tracking ticket, I don't think this is a bad idea at all :-)

Cheers.

**Comment by colby-swandale** [comment]
Hi! We had an issue with the bundler team's email and were not notified correctly, this has been fixed. We can confirm that we received your email and will look into it.

**Comment by lzap** [comment]
No rush take you time folks! Thanks for the update.
