### ISSUE TITLE
Platform warnings should be skipped when using bundler/inline

### ISSUE THREAD

**Issue by deivid-rodriguez** [bundler/bundler#6822]
I noticed that when using `bundler/inline`, I get the usual platform warnings for dependencies not meant for my platform:

```
The dependency activerecord-jdbcsqlite3-adapter (~> 51.0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for java. To add those platforms to the bundle, run `bundle lock --add-platform java`.
The dependency jruby-openssl (~> 0.10.1) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for java. To add those platforms to the bundle, run `bundle lock --add-platform java`.
```

However, since in the case of `bundler/inline` there's no lock file, I think these messages should be avoided?

**Comment by colby-swandale** [comment]
We should still notify the user of unused platform gems, but adjust the message to not include `bundle lock` instructions

**Comment by deivid-rodriguez** [comment]
So what would be the solution for those cases? I don't like unresolvable warnings.

**Comment by colby-swandale** [comment]
I'm not sure, does this message go away if the user sets `platform: [:java]` in the gem entry?
