### ISSUE TITLE
Could you upload bundler 2.0.0.pre.2 to S3?

### ISSUE THREAD

**Issue by oiahoon** [bundler/bundler#6825]
Hi, @indirect , i m a user of https://github.com/bundler/heroku-buildpack-bundler2, thank you very much to help us bundler2 guys on building on heroku.
could you please help to upload `2.0.0.pre.2` to s3 as well? since i found that `2.0.0.pre.1` has some issue, means:

> can't find gem bundler (>= 0.a) with executable bundle (Gem::GemNotFoundException)

but this exception disappears while using `2.0.0.pre.2`, so i want to change the bundler version to  `BUNDLER_VERSION      = "2.0.0.pre.2"`,  could you please kindly help uploading the pkg to 

> https://s3-external-1.amazonaws.com/heroku-buildpack-ruby

Great thanks!

**Comment by indirect** [comment]
Hi, I've updated the buildpack. Thanks for reminding me to do it!

**Comment by oiahoon** [comment]
@indirect sorry to bother you~~  we still dun have:
> https://heroku-buildpack-bundler2.s3.amazonaws.com/bundler-2.0.0.pre.2.tgz
i tried to upload it by my self via: `bundle exec rake gem:install bundler 2.0.0.pre.2`, but met problem below:
```
unset RUBYOPT; gem install bundler --version 2.0.0.pre.2 -no-ri-no-rdoc --env-shebang
Fetching bundler-2.0.0.pre.2.gem
Successfully installed bundler-2.0.0.pre.2
Parsing documentation for bundler-2.0.0.pre.2
Installing ri documentation for bundler-2.0.0.pre.2
Done installing documentation for bundler after 3 seconds
1 gem installed
rm -f bundler-2.0.0.pre.2.gem
rm -rf cache/bundler-2.0.0.pre.2.gem
tar czvf /var/folders/7g/q3_z1p555rb8shdkrgp_cvc80000gn/T/bundler-2.0.0.pre.220181204-46887-8h7aci/bundler-2.0.0.pre.2.tgz *
a build_info
a cache
...
...
a specifications/bundler-2.0.0.pre.2.gemspec
aws s3 cp /var/folders/7g/q3_z1p555rb8shdkrgp_cvc80000gn/T/bundler-2.0.0.pre.220181204-46887-8h7aci/bundler-2.0.0.pre.2.tgz s3://heroku-buildpack-bundler2/bundler-2.0.0.pre.2.tgz
rake aborted!
Command failed with status (127): [aws s3 cp /var/folders/7g/q3_z1p555rb8shdk...]
/Users/johuang/Work/heroku-buildpack-bundler2/Rakefile:14:in `s3_upload'
/Users/johuang/Work/heroku-buildpack-bundler2/Rakefile:54:in `block (3 levels) in install_gem'
/Users/johuang/Work/heroku-buildpack-bundler2/Rakefile:37:in `in_gem_env'
/Users/johuang/Work/heroku-buildpack-bundler2/Rakefile:49:in `block (2 levels) in install_gem'
/Users/johuang/Work/heroku-buildpack-bundler2/Rakefile:46:in `chdir'
/Users/johuang/Work/heroku-buildpack-bundler2/Rakefile:46:in `block in install_gem'
Fix issue someone may meet:
/Users/johuang/Work/heroku-buildpack-bundler2/Rakefile:45:in `install_gem'
/Users/johuang/Work/heroku-buildpack-bundler2/Rakefile:72:in `block in <top (required)>'
/Users/johuang/.rbenv/versions/2.6.0-dev/bin/bundle:23:in `load'
/Users/johuang/.rbenv/versions/2.6.0-dev/bin/bundle:23:in `<main>'
Tasks: TOP => gem:install
(See full trace by running task with --trace)
```

could you please help us？ thanks again.

**Comment by indirect** [comment]
@oiahoon ahh, shoot. I think it is a permissions error. Sorry about that, I’ll try to fix it now.

**Comment by indirect** [comment]
@oiahoon ok! permissions should be fixed now, I am able to download the file. Please let me know if you are still seeing any issues!
