### ISSUE TITLE
Exception when try to run Bundler pre 1 or 2 on windows Gem::GemNotFoundException

### ISSUE THREAD

**Issue by Shereind** [bundler/bundler#6826]
I got this exception when trying to run "bundler install" or "bundler -v" on 2.0.0.pre.2 or pre1 on windows 

C:/Ruby24-x64/lib/ruby/site_ruby/2.4.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundler (Gem::GemNotFoundException)
        from C:/Ruby24-x64/lib/ruby/site_ruby/2.4.0/rubygems.rb:308:in `activate_bin_path'
        from C:/Ruby24-x64/bin/bundler:23:in `<main>'

![image](https://user-images.githubusercontent.com/42438027/49440300-f1af0100-f7cb-11e8-9f0c-1818af02549b.png)

**Comment by deivid-rodriguez** [comment]
This was fixed via https://github.com/rubygems/rubygems/pull/2426, that should give you a better error message telling you how to proceed. But there's not a rubygems release including it. We should release a rubygems version with this fix before we release bundler 2.

**Comment by colby-swandale** [comment]
This seems answered. Closing.
