### ISSUE TITLE
i cant run bundle install

### ISSUE THREAD

**Issue by sanjeev1379** [bundler/bundler#6835]
Fetching source index from https://rubygems.org/

Retrying fetcher due to error (2/4): Net::HTTPRetriableError 302 "Found"
Retrying fetcher due to error (3/4): Net::HTTPRetriableError 302 "Found"
Retrying fetcher due to error (4/4): Net::HTTPRetriableError 302 "Found"--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/exe/bundle install`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what happened was...

Error details

    Net::HTTPRetriableError: 302 "Found"
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/net/http/response.rb:119:in `error!'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/net/http/response.rb:128:in `value'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/net/http.rb:915:in `connect'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/net/http.rb:858:in `start'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/rubygems/request/http_pool.rb:42:in `setup_connection'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/rubygems/request/https_pool.rb:6:in `setup_connection'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/rubygems/request/http_pool.rb:38:in `make_connection'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/rubygems/request/http_pool.rb:19:in `checkout'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/rubygems/request.rb:85:in `connection_for'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/rubygems/request.rb:140:in `perform_request'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/rubygems/request.rb:109:in `fetch'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/rubygems/remote_fetcher.rb:352:in `request'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/rubygems/remote_fetcher.rb:237:in `fetch_http'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/rubygems/remote_fetcher.rb:273:in `fetch_path'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/rubygems_integration.rb:668:in `fetch_specs'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/rubygems_integration.rb:678:in `fetch_all_remote_specs'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/fetcher/index.rb:9:in `specs'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/fetcher.rb:128:in `block in specs'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/fetcher.rb:127:in `each'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/fetcher.rb:127:in `specs'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/fetcher.rb:112:in `block in specs_with_retry'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/retry.rb:39:in `call'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/retry.rb:39:in `run'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/retry.rb:29:in `attempt'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/fetcher.rb:111:in `specs_with_retry'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:342:in `block (2 levels) in remote_specs'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:340:in `each'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:340:in `block in remote_specs'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/index.rb:10:in `build'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:336:in `remote_specs'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:83:in `specs'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/definition.rb:261:in `block (2 levels) in index'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/definition.rb:259:in `each'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/definition.rb:259:in `block in index'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/index.rb:10:in `build'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/definition.rb:256:in `index'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/definition.rb:250:in `resolve'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/definition.rb:174:in `specs'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/definition.rb:162:in `resolve_remotely!'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/installer.rb:225:in `resolve_if_need'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/installer.rb:78:in `run'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/installer.rb:24:in `install'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/cli/install.rb:71:in `run'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/cli.rb:189:in `install'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/cli.rb:20:in `dispatch'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/cli.rb:11:in `start'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/exe/bundle:34:in `block in <main>'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
      C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.13.6/exe/bundle:26:in `<main>'

Environment

  Bundler   1.13.6
  Rubygems  2.4.5.2
  Ruby      2.2.6p396 (2016-11-15 revision 56800) [i386-mingw32]
  GEM_HOME  C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0
  GEM_PATH  C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0;C:/Users/Rgn.COMPUTER/.gem/ruby/2.2.0
  Git       2.19.1.windows.1

**Comment by colby-swandale** [comment]
My guess is that you're behind a proxy that is intercepting your traffic and returning a 302 status. I suggest making sure you have a clear connection to https://rubygems.org for Bundler/RubyGems.

**Comment by mikegee** [comment]
@sanjeev1379 may we assume that you have resolved this problem?
