### ISSUE TITLE
`bundle add` for `git:` and `branch:`?

### ISSUE THREAD

**Issue by janpio** [bundler/bundler#6841]
Is there a way to add a dependency with `git:` and `branch:` ([How to install gems from git repositories](https://bundler.io/guides/git.html)) using the `bundle` CLI? 

This should be the result in my `Gemfile`:
```
gem 'nokogiri', git: 'https://github.com/rack/rack.git', branch: 'rack-1.5'
```

`bundle add` doesn't seem to have the necessary parameters: https://bundler.io/v1.17/man/bundle-add.1.html

**Comment by janpio** [comment]
I faked this with a (probably terrible) shell script:

```
#!/bin/sh

if [ -n "$REPO" ] && [ -n "$BRANCH" ]; then
    SEARCH='gem "fastlane".*'
    REPLACE="gem \"fastlane\", :git => \"$REPO\", :branch => \"$BRANCH\""
    sed -i "s@$SEARCH@$REPLACE@" Gemfile
fi
```

If I set the `REPO` and `BRANCH` env variables, this will replace the `gem "fastlane" ...` line (that I know is in the Gemfile) with another line that specified the repo and branch for the fastlane gem.

**Comment by gkpacker** [comment]
Maybe it can help you: https://github.com/rdp/specific_install

**Comment by janpio** [comment]
I don't think so, this seems to install the gem directly - I want to manipulate the `Gemfile` as per the example I added in my original post.

**Comment by colby-swandale** [comment]
There is no options to add a gem with the `git` or `branch` options, but a PR for this would be greatly welcomed.

**Comment by janpio** [comment]
I am looking into this. 

Probably relevant code:

https://github.com/bundler/bundler/blob/0ab0dc7ea999743ccab128f5ab582be834de427a/lib/bundler/cli.rb#L357-L371
https://github.com/bundler/bundler/blob/master/lib/bundler/cli/add.rb
https://github.com/bundler/bundler/blob/d44d803357506895555ff97f73e60d593820a0de/lib/bundler/dependency.rb#L80-L92
https://github.com/bundler/bundler/blob/master/man/bundle-add.ronn
https://github.com/bundler/bundler/blob/master/spec/commands/add_spec.rb

Further inspiration and to research:
https://github.com/bundler/bundler/pull/6556/files
https://github.com/bundler/bundler/search?utf8=%E2%9C%93&q=git&type=
