### ISSUE TITLE
some error on bundle

### ISSUE THREAD

**Issue by umapathireddy** [bundler/bundler#6842]
from D:/Ruby23/lib/ruby/gems/2.3.0/gems/bundler-1.17.2/lib/bundler/dsl.rb:47:in `eval_gemfile'
	from D:/Ruby23/lib/ruby/gems/2.3.0/gems/bundler-1.17.2/lib/bundler/dsl.rb:12:in `evaluate'
	from D:/Ruby23/lib/ruby/gems/2.3.0/gems/bundler-1.17.2/lib/bundler/definition.rb:34:in `build'
	from D:/Ruby23/lib/ruby/gems/2.3.0/gems/bundler-1.17.2/lib/bundler.rb:135:in `definition'
	from D:/Ruby23/lib/ruby/gems/2.3.0/gems/bundler-1.17.2/lib/bundler.rb:101:in `setup'
	from D:/Ruby23/lib/ruby/gems/2.3.0/gems/bundler-1.17.2/lib/bundler/setup.rb:20:in `<top (required)>'
	from D:/Ruby23/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from D:/Ruby23/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'

**Comment by colby-swandale** [comment]
This does not seem like the full error, can you please attach the full stack trace and the output of `bundle env`.

**Comment by umapathireddy** [comment]
thank you. issue is sloved
