### ISSUE TITLE
ERROR:  Error installing bundler: bundler requires Ruby version >= 2.3.0.

### ISSUE THREAD

**Issue by oshivwanshi** [bundler/bundler#6865]
We were using **Bundler version 1.12.5** with **ruby version = "2.1"** , **'poise-ruby', '~> 2.4.0'** and **'poise-ruby-build', '~> 1.1.0'**

But after the release Bundler version 2.0.0 - January 03, 2019 we are getting this error **STDERR: ERROR:  Error installing bundler:bundler requires Ruby version >= 2.3.0.**
can anyone please help me with this issue?

`===================================================================

    Error executing action `install` on resource 'ruby_runtime[logFileCollector-ruby-2.1]'

===================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    ruby_gem[bundler] (/var/chef/cache/cookbooks/poise-ruby/files/halite_gem/poise_ruby/ruby_providers/base.rb line 109) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
    ---- Begin output of /opt/ruby_build/builds/logFileCollector-ruby-2.1/bin/gem install bundler -q --no-rdoc --no-ri -v "2.0.0" ----
    STDOUT:
    STDERR: ERROR:  Error installing bundler:
        bundler requires Ruby version >= 2.3.0.
    ---- End output of /opt/ruby_build/builds/logFileCollector-ruby-2.1/bin/gem install bundler -q --no-rdoc --no-ri -v "2.0.0" ----
    Ran /opt/ruby_build/builds/logFileCollector-ruby-2.1/bin/gem install bundler -q --no-rdoc --no-ri -v "2.0.0" returned 1

    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/poise-ruby/files/halite_gem/poise_ruby/resources/ruby_gem.rb:75:in `block in action_upgrade'
    /var/chef/cache/cookbooks/poise-ruby/files/halite_gem/poise_ruby/resources/ruby_gem.rb:111:in `patch_environment'
    /var/chef/cache/cookbooks/poise-ruby/files/halite_gem/poise_ruby/resources/ruby_gem.rb:75:in `action_upgrade'
    /var/chef/cache/cookbooks/poise/files/halite_gem/poise/helpers/notifying_block.rb:69:in `notifying_block'
    /var/chef/cache/cookbooks/poise-ruby/files/halite_gem/poise_ruby/ruby_providers/base.rb:43:in `action_install'

`

**Comment by keith** [comment]
FYI this means that the version of `/usr/bin/gem` (`2.5.2.3`) that ships with macOS 10.14.2 (currently the newest point release) is no longer supported.

**Comment by indirect** [comment]
Bundler 2 no longer supports versions of Ruby that are so old they have been abandoned by the ruby-core team. That includes Ruby 2.2 and older. This is intended behavior, sorry.

**Comment by vgladiyenko** [comment]
If someone Googles this, just install the version from your Gemfile.lock by running two commands as shown in the official blog post [here](https://bundler.io/blog/2019/01/04/an-update-on-the-bundler-2-release.html).

```
cat Gemfile.lock | grep -A 1 "BUNDLED WITH"
BUNDLED WITH
   1.17.3

gem install bundler -v '1.17.3'
```

In my case I had this error when build a docker container, so I just replaced `RUN gem install bundler` with `RUN gem install bundler -v '1.16.1'` in my Dockerfile.

**Comment by ahmad-shawky** [comment]
Fixed by using @vgladiyenko answer.

**Comment by rolandvarga** [comment]
@vgladiyenko thank you this helped with a time travel project!

**Comment by mrhardikjoshi** [comment]
If you do not want to update your project's ruby version due to some reason, you can install the last supported version of Bundler for Ruby < 2.3:

`gem install bundler -v '~>1'`
