### ISSUE TITLE
Would you open the issue tab on https://github.com/bundler/heroku-buildpack-bundler2 ?

### ISSUE THREAD

**Issue by hidehiro98** [bundler/bundler#6869]
https://github.com/bundler/heroku-buildpack-bundler2

I have the issue with this buildpack and wanna post the issue so would you open the issue tab of this repo?

**Comment by hidehiro98** [comment]
The error is this.
```
       bundler-2.0.0 requires rubygems version >= 3.0.0, which is incompatible with the
       current version, 2.7.6
```

**Comment by colby-swandale** [comment]
I have enabled issues on the buildpack.

**Comment by hidehiro98** [comment]
Thank you very much!
