### ISSUE TITLE
Bundler 2 release fully broke installation CentOS 7

### ISSUE THREAD

**Issue by ssbarnea** [bundler/bundler#6870]
The installer `gem install bundler` no longer works on `CentOS 7` because the ruby version there is 2.0

This is a serious regression as it breaks CI all over the place and people will endup using pinning to avoid it.

Get should install the latest version supported by the current ruby interpreter, which is `1.17.3` if I am correct in this case.

```
# ruby --version
ruby 2.0.0p648 (2015-12-16) [x86_64-linux]
root@n0:~/.cache/.rmux/puppet-openstack-integration # gem install bundler --no-rdoc --no-ri --verbose
GET https://rubygems.org/latest_specs.4.8.gz
200 OK
GET https://rubygems.org/quick/Marshal.4.8/bundler-2.0.1.gemspec.rz
200 OK
Installing gem bundler-2.0.1
Downloading gem bundler-2.0.1.gem
GET https://rubygems.org/gems/bundler-2.0.1.gem
Fetching: bundler-2.0.1.gem (100%)
200 OK
ERROR:  Error installing bundler:
        bundler requires Ruby version >= 2.3.0.
```

**Comment by greysteil** [comment]
Thanks for the issue @ssbarnea.

Since Ruby 2.0 is end-of-life it's not supported by the latest version of Bundler anymore, and rubygems doesn't have the version resolution logic in it to figure out what the latest supported version is.

If you run `gem install bundler -v 1.17.3` you'll get a Bundler version that is compatible with Ruby 2.0.

**Comment by deivid-rodriguez** [comment]
I _think_ this would be fixed by https://github.com/rubygems/rubygems/pull/2539? It's been closed and requested to be split into separate different PRs because of including a bunch of unrelated bug fixes, but it claims to fix the `required_ruby_version` resolution logic in rubygems?

/cc @MSP-Greg
