### ISSUE TITLE
[Windows test failure] rspec './spec/bundler/bundler_spec.rb[1:2:2:1:1]' # Bundler#which when the executable in inside a quoted path behaves like it returns the correct executable returns the expected file

### ISSUE THREAD

**Issue by janpio** [bundler/bundler#6875]
As described in https://github.com/bundler/bundler/issues/6868#issuecomment-451418573 currently 665 out of 2509 tests of bundler are failing on my Windows environment. I am working on fixing this.

---

This is the first test that is failing:

```
rspec './spec/bundler/bundler_spec.rb[1:2:2:1:1]' # Bundler#which when the executable in inside a quoted path behaves like it returns the correct executable returns the expected file
```

Here is just that spec file:

```
C:\Projects\bundler (windows -> origin)
λ ruby bin/rspec ./spec/bundler/bundler_spec.rb:146
Run options:
  include {:locations=>{"./spec/bundler/bundler_spec.rb"=>[146]}}
  exclude {:ruby_repo=>false, :bundler=>"=< 2.0", :rubygems_master=>true, :git=>"=< 2.20.1", :rubygems=>"=< 2.6.14.1", :ruby=>"=< 2.4.4", :realworld=>true, :sudo=>true}

Bundler
  #which
    behaves like it returns the correct executable
      returns the expected file
    when the executable in inside a quoted path
      behaves like it returns the correct executable
        returns the expected file (FAILED - 1)
    when the executable is not found
      behaves like it returns the correct executable
        returns the expected file


Retried examples: 0

Failures:

  1) Bundler#which when the executable in inside a quoted path behaves like it returns the correct executable returns the expected file
     Failure/Error: expect(subject).to eq(expected)

       expected: "/e/executable"
            got: nil

       (compared using ==)
     Shared Example Group: "it returns the correct executable" called from ./spec/bundler/bundler_spec.rb:154
     # ./spec/bundler/bundler_spec.rb:146:in `block (4 levels) in <top (required)>'
     # ./spec/spec_helper.rb:122:in `block (2 levels) in <top (required)>'

Finished in 9.89 seconds (files took 1.6 seconds to load)
3 examples, 1 failure

Failed examples:

rspec './spec/bundler/bundler_spec.rb[1:2:2:1:1]' # Bundler#which when the executable in inside a quoted path behaves like it returns the correct executable returns the expected file
```

Test code is here: https://github.com/janpio/bundler/blob/b97a280c33607a0db12ee33dbb9104f735a3a527/spec/bundler/bundler_spec.rb#L126-L161

Problem is that https://github.com/janpio/bundler/blob/b97a280c33607a0db12ee33dbb9104f735a3a527/lib/bundler.rb#L421 on Windows does not just return `/e/executable` as expected in this example, but `C:/e/executable` - fully expanded paths on Windows always include a drive letter. `File` is not "configured" (What is the proper term here?) to receive this path, thus `which` returns `nil`.

---

How do I properly rewrite this test to reflect that?
Would it be valid to change the `expect` to check if the expected string is _included_ instead of equal to the returned value?
Changing to `let(:path) { ["C:/a", "C:/b", "C:/c", "C:/../d", "C:/e"] }` and `let(:expected) { "C:/e/executable" }` makes the tests pass on Windows, but obviously breaks them on all other OSes. Any idea how to generalize this?

**Comment by deivid-rodriguez** [comment]
If the test is working fine, I think it's fine to to adapt the test for Windows. For example,

```
let(:path) do
  if Gem.win_platform?
    %w[C:/a C:/b C:/c C:/../d C:/e]
  else
    %w[/a /b c ../d /e]
  end
end
```

And similarly for the other `let`.
