### ISSUE TITLE
auto version switching doesn't seem to work with JRuby

### ISSUE THREAD

**Issue by eli-darkly** [bundler/bundler#6880]
One of my CI builds - the one for JRuby - has been failing ever since the bundler 2.0 release. In other Ruby versions, the auto-switching mechanism correctly selects the older bundler version, but not in this one; it runs the command with 2.0 instead of the version specified in my gemspec, and then fails because 2.0 doesn't match my version constraint.

Details: https://gist.github.com/eli-darkly/5363c6463df846b7fc307783aa2eae0e

**Comment by colby-swandale** [comment]
The autoswitcher is only available on versions of RubyGems 2.7 and up. You will have to manage loading the correct version of Bundler yourself.

**Comment by eli-darkly** [comment]
I did try explicitly removing bundler 2.0 (which seems to be preinstalled in this CI Ubuntu image) but for some reason that caused a silent error that terminated my script, even though `gem uninstall` said it had succeeded. I guess I'll keep trying to make that work.
