### ISSUE TITLE
Fix Travis ruby-head,  RG 2.7.7 => 2.7.8 (attached code)

### ISSUE THREAD

**Issue by MSP-Greg** [bundler/bundler#6883]
@colby-swandale

Further info re #6881, which had a main goal of getting ruby-head/trunk passing.  I continued to work on my fork with it.  The fork CI is [here](https://travis-ci.org/MSP-Greg/bundler/builds/475985479).

Current results for ruby-head:
```
2459 examples, 25 failures, 2 pending
```

After patch:
```
2507 examples, 1 failure, 2 pending
```

The one failure appears to be due to an older rake version being used somewhere...

It does fail on Ruby-2.3.8 with RGV=2.5.2.  Considering that 2.3.8 is compatible with RGV 2.6.14, 2.7.8, and 3.0.2, I personally am not sure of the benefit of testing against 2.5.2, but that's your call.

I don't know bundler very well.  Attached is a patch file, feel to use any of the code to update Bundler CI.

[bundler_update_ci.patch.txt](https://github.com/bundler/bundler/files/2730599/bundler_update_ci.patch.txt)

**Comment by MSP-Greg** [comment]
Sorry, forgot two other items:

1. I tried running RuboCop locally with 0.61.1.  Big fail.  Now that RG is using RuboCop, maybe it would make sense to use similar setups?  0.50.0 is a bit old...

2. If Bundler CI is swapping out RubyGems versions, but the ruby-head/trunk tests have 24 additional tests that fail with a older RG version as the preinstalled version (courtesy of Travis), is there something wrong with the test setup?

Thanks, Greg

**Comment by deivid-rodriguez** [comment]
This should no longer be a problem.
