### ISSUE TITLE
The warning for running an older version of Bundler 1.x shows an incorrect solution

### ISSUE THREAD

**Issue by ZimbiX** [bundler/bundler#6909]
Given I have Bundler `1.17.1` installed, and a `Gemfile.lock` specifying Bundler `1.17.3`, when I run `bundle check`, I expect the solution in the warning shown to be helpful. Instead, the warning is:

```
Warning: the running version of Bundler (1.17.1) is older than the version that created the lockfile (1.17.3). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
```

The solution, `gem install bundler`, will not upgrade Bundler 1.x, but instead install 2.x. Thanks to the new version autoswitching, it still uses Bundler `1.17.1`, and the warning remains.

Issue #6908 makes this confusing to debug.

As documented, upgrading to Bundler 2 is not always convenient, so upgrading 1.x should be supported.

I think the solution shown should instead be:

```
We suggest you upgrade to the latest version of Bundler by running `gem update --system && gem install bundler && bundle update --bundler`, or upgrade to the latest version of Bundler 1.x by running `gem install bundler --version '~> 1'.
```

**Comment by Fryguy** [comment]
Also, wording wise, 1.17.1 is not older than 1.17.3.
