### ISSUE TITLE
GitHub HTTPS is not actually enabled by default in Bundler 2?

### ISSUE THREAD

**Issue by jfly** [bundler/bundler#6910]
I just upgraded to Bundler 2, and tried cleaning my Gemfile to remove the workaround from https://github.com/bundler/bundler/issues/4978#issuecomment-272248627. However, it looks like Bundler is still using `git://...` urls instead of `https://...` urls for me.

I dug into the code in the `2.0.1` branch, and it looks like there's a leftover TODO about making this switch: https://github.com/bundler/bundler/blob/v2.0.1/lib/bundler/dsl.rb#L307-L308.

I dug into the code history a bit to try to understand this better, and things get a little weird. My understanding:

1. In df2956dcc52fbf241988bd51ff6cbf5244198995, @indirect changed the default from `git://` to `https://`.
2. 1cc3d97a7f71726e16f57462cba2814b1237123e reverted that change.
3. 61e00d657174e84f3b27570becdfe9bccc3b3a0c added a config option and warned that the default for this option would be changing in version 2.
3. Then, in d9844e8d0f8d365c8750cf214a678602f29e4926, a new `github_https?` method was introduced, but the method isn't actually used anywhere except tests. The commit message claims that this changes the default behavior, but it doesn't. It looks like that commit was *trying* to double commit the code from https://github.com/bundler/bundler/pull/6798/files, but it's missing this key part:

![image](https://user-images.githubusercontent.com/277474/51237817-26b18600-192a-11e9-9e7a-5945b93ee63e.png)

I'm pretty confident think the right fix is to add this missing line of code to the `2.*` release series. I'll send in a PR implementing this soon.

**Comment by colby-swandale** [comment]
This has been fixed in `2-0-stable`

**Comment by hakusaro** [comment]
@colby-swandale I'm on Bundler 2.0.1 and I'm seeing that running `bundle` without explicitly running `bundle config --global github.https true` first will still revert `https` in the `lockfile` back to git. Is there a way to debug this?

**Comment by deivid-rodriguez** [comment]
@hakusaro It's expected, it's fixed on `2-0-stable` but not yet released, sorry about that.
