### ISSUE TITLE
Why does Bundler downloads the list of all gem versions?

### ISSUE THREAD

**Issue by eregon** [bundler/bundler#6915]
Bundler downloads https://index.rubygems.org/versions, which is 22MB uncompressed and contains in plain text the list of all gems and all versions.

On developer machines, this gets cached under `~/.bundle/cache/compact_index`.
But on TravisCI and other CI services, it seems to not be cached (at least by default).

I thought the new RubyGems API would enable Bundler to work without needing to download this large file, and only query information for gems in the Gemfile and their dependencies.

Is this a bug? Could Bundler work without downloading all gem versions?

I found this by debugging why Bundler is slow in TravisCI on TruffleRuby (oracle/truffleruby#1398).

**Comment by eregon** [comment]
FWIW, it's delivered as a 9.5MB gzip:
```
Content-Encoding: gzip
Content-Length: 10008523
```
So it's still a large file even compressed.

**Comment by segiddins** [comment]
It’s intentional — it allows for incremental updates of the set of all available gem versions, and the version list contains ETags that let us avoid hundreds or thousands of other downloads per bundle install

**Comment by colby-swandale** [comment]
This seems answered.

**Comment by eregon** [comment]
@segiddins OK, thanks for the answer.
So incremental updates are then stored in that file or separate files, before doing any resolution?

**Comment by segiddins** [comment]
Correct
