### ISSUE TITLE
The application encountered the following error: undefined method `current_feature' for class `Decidim::Components::BaseController'

### ISSUE THREAD

**Issue by Graf63** [bundler/bundler#6920]
Hi,

I restart my nginx and now i've got this error message :
The application encountered the following error: undefined method `current_feature' for class `Decidim::Components::BaseController'
I run the update of decidim but nothing...

Thanks

**Comment by hsbt** [comment]
Is it the `bundler`'s issue?

**Comment by Graf63** [comment]
Sorry, i did a mistake.
Thanks
