### ISSUE TITLE
bundle config build.<gem> doesn't send multiple parameters to extconf.rb correctly

### ISSUE THREAD

**Issue by brad1** [bundler/bundler#6940]
### What works (`bundler 1.7.2`)
`bundle config build.<gem> --with-opt-lib=... --with-client-lib=...`, then 
`bundle install`
This succeeds, giving the same results as:
`gem install gem -v x.y.z -- --with-opt-lib=... --with-client-lib=...`.   

From `mkmf.log`:
```
gcc ... -L"/path/to/lib" -L"/another/path"
```

### What happens now (tried with bundler `1.17.1` and `2.0.1`)
After the exact same steps as above:
```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.  

...

/usr/bin/ruby -I /usr/lib64/ruby/2.6.0 -r ./siteconf20190130-29495-12z1ot5.rb \ 
 extconf.rb --with-opt-lib\=<...>\ --with-client-lib\=<...>
```  
Notice that the build parameters are separated by an escaped space, because `extconf.rb` is being given the build parameters as one big string.  Verified this using `pry`.   

From `mkmf.log`:

```
gcc ... -L"/path/to/lib --with-client-lib=/another/path"
```
And the native extension fails to install because we can no longer find the required headers.

**Comment by amygitsthings** [comment]
I'm seeing this problem with 1.17.2 as well and I was not seeing this issue with bundler 1.15.4

**Comment by colby-swandale** [comment]
Can you please provide a Gemfile that we can use to reproduce this problem.

**Comment by amygitsthings** [comment]
I was trying to install the do_postgres gem and providing --with-pgsql-server-include and --with-pgsql-client-dir options

**Comment by coding-bunny** [comment]
Running into similar problems with bundler `1.17.3` on ruby `2.1.6`
Downgrading to bundler `1.15.4` makes it all work without issues.

Used the following command to generate output:
```
export DEBUG_RESOLVER=1
bundle 2> ~/debug_output.txt 1>~/stdio.txt &
```

see attached file
[stdio.txt](https://github.com/bundler/bundler/files/2879884/stdio.txt)

**Comment by jeremy** [comment]
Quick repro:

```ruby
# repro.rb
require 'bundler/inline'

system "bundle config --local build.mysql2 --with-mysql-config=mysqlconfig --example-argument"

gemfile do
  source 'https://rubygems.org'
  gem 'mysql2'
end
```

```bash
$ ruby repro.rb 
You are replacing the current local value of build.mysql2, which is currently nil
Traceback (most recent call last):
…snip…
/Users/jeremy/.rbenv/versions/2.6.1/lib/ruby/site_ruby/2.6.0/bundler/installer/parallel_installer.rb:201:in `handle_error': Gem::Ext::BuildError: ERROR: Failed to build gem native extension. (Bundler::InstallError)

    current directory: /Users/jeremy/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/mysql2-0.5.2/ext/mysql2
/Users/jeremy/.rbenv/versions/2.6.1/bin/ruby -I /Users/jeremy/.rbenv/versions/2.6.1/lib/ruby/site_ruby/2.6.0 -r ./siteconf20190306-75775-1csb26z.rb extconf.rb **--with-mysql-config\=mysqlconfig\ --example-argument**
checking for rb_absint_size()... yes
checking for rb_absint_singlebit_p()... yes
checking for rb_wait_for_single_fd()... yes
-----
Cannot find mysql_config at **mysqlconfig --example-argument**
…snip…
```

**Highlighted** the result of quoting/escaping the build config rather than passing it through verbatim.

**Comment by jeremy** [comment]
Quick fix:
```ruby
require 'bundler/inline'

system "bundle config --local build.mysql2 --with-mysql-config=mysqlconfig --example-argument"

if ENV['SHELLSPLIT']
  require 'bundler/installer/gem_installer'
  require 'shellwords'

  module ShellsplitSpecSettings
    def spec_settings
      if settings = super
        Shellwords.shellsplit settings
      end
    end
  end

  Bundler::GemInstaller.prepend ShellsplitSpecSettings
end

gemfile do
  source 'https://rubygems.org'
  gem 'mysql2'
end
```
Running it:
```bash
… extconf.rb --with-mysql-config\=mysqlconfig --example-argument
```

Looks like this was introduced by shellescaping/shelljoining arguments in the RubyGems installer: https://github.com/rubygems/rubygems/pull/2441/files#diff-352b7b3f2988f0f74c3e332074f59e09R74

So shellsplitting the spec_settings fixes it.

**Comment by deivid-rodriguez** [comment]
Thanks @jeremy, I created #7023 to add your patch to bundler.
