### ISSUE TITLE
Plugins are installed every time a command is run

### ISSUE THREAD

**Issue by rafaelfranca** [bundler/bundler#6946]
With this gemfile:

```ruby
source 'https://rubygems.org'

plugin "bootboot"
```

We have this output:

```
[2.6.0 bundler-plugin]$ bundle
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Fetching bootboot 0.1.2
Installing bootboot 0.1.2
Using bundler 1.17.2
Installed plugin bootboot
The Gemfile specifies no dependencies
Resolving dependencies...
Bundle complete! 0 Gemfile dependencies, 1 gem now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
[2.6.0 bundler-plugin]$ bundle
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Installing bootboot 0.1.2
Using bundler 1.17.2
The Gemfile specifies no dependencies
Bundle complete! 0 Gemfile dependencies, 1 gem now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
[2.6.0 bundler-plugin]$ bundle
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Installing bootboot 0.1.2
Using bundler 1.17.2
The Gemfile specifies no dependencies
Bundle complete! 0 Gemfile dependencies, 1 gem now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
```

As you can see every time I run the bundle install command the `bootboot` gem is installed.

**Comment by colby-swandale** [comment]
It would be good to know if it's actually installing the plugin every time or if this is an issue with the UI.

**Comment by ankitkataria** [comment]
@colby-swandale Investigating into the issue, I found that the plugins are not being recognised as `installed_specs` which leads to a failed check [here](https://github.com/bundler/bundler/blob/master/lib/bundler/source/rubygems.rb#L109). The pluging that is being installed is not present in `Bundler.rubygems.all_specs` while this is not the case with usual gems. I'm not sure how the this variable is being populated. Which part of the code should I be looking into? :thinking:

**Comment by rafaelfranca** [comment]
As workaround I did:

```
plugin "bootboot" if Plugin.installed?('bootboot')
```

So probably we can use that API to check internally to avoid installing the again.

**Comment by ankitkataria** [comment]
@rafaelfranca Thanks for advice! I added a small check and made a PR.
