### ISSUE TITLE
Bundler not complaint with semantic versioning specification

### ISSUE THREAD

**Issue by krystof-k** [bundler/bundler#6972]
I want to use build metadata part in my version number, according to the [semantic versioning specification](https://semver.org/#spec-item-10): `0.1.0+build`. But bundler refuses to install:

```shell
[!] There was an error while loading `language.gemspec`: Malformed version number string 0.1.0+build. Bundler cannot continue.
```

Any ideas? I think there is no reason not to follow semantic versioning specification, although this is probably quite unusual requirement.

**Comment by greysteil** [comment]
Currently, Rubygems doesn't support including build metadata in versions. As you're probably aware, different languages implement SemVer slightly differently, particularly on the less-used parts (build metadata, expectations pre-1.0.0, equivalence of tokens like `alpha` and `a`).

There is work going on to harmonise this at https://github.com/semver/semver, and Bundler and the Rubygems teams are represented there, but for now there's no way to specify build metadata in a Rubygems version number.
