### ISSUE TITLE
bundler issue 

### ISSUE THREAD

**Issue by SlowMonk** [bundler/bundler#6976]
trying to do bundle command but 

> Bundler could not find compatible versions for gem "bundler":
>   In Gemfile:
>     bundler (~> 1.15)
> 
>   Current Bundler version:
>     bundler (2.0.1)
> This Gemfile requires a different version of Bundler.
> Perhaps you need to update Bundler by running `gem install bundler`?
> 
> Could not find gem 'bundler (~> 1.15)' in any of the relevant sources:
>   the local ruby installation
> 

even though I uninstall bundler it still remained with bundler(2.0.1). 
I think my anaconda also has bundler things but not sure. 
How to force to use bundler 1.15? or to fix above issue

**Comment by ankitkataria** [comment]
@SangwonJakeEum 
`bundler (~> 1.15)` in the Gemfile means `>= 1.15 and < 1.2`, while you have bundler - 2.0.1 installed. 
 Have you tried - 
`gem install bundler -v 1.15` and then forcing the bundler version with - `bundle _1.15_ <command>` ?
