### ISSUE TITLE
Installing bundler with --default breaks bundler

### ISSUE THREAD

**Issue by p-mongo** [bundler/bundler#6992]
On a fresh ruby 2.6.1 installation:

<pre>
speed% gem install bundler --default
Fetching bundler-2.0.1.gem
Successfully installed bundler-2.0.1 as a default gem
Done installing documentation for bundler after 0 seconds
1 gem installed
speed% pwd
/home/w
speed% gem list|grep bund
bundler (default: 2.0.1, default: 1.17.2)
speed% bundle
Traceback (most recent call last):
	1: from /home/w/.rbenv/versions/2.6.1/bin/bundle:23:in `<main>'
/home/w/.rbenv/versions/2.6.1/bin/bundle:23:in `load': cannot load such file -- /home/w/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/bundler-2.0.1/exe/bundle (LoadError)
</pre>

If I now uninstall bundler, it is still broken:

<pre>
speed% gem uni bundler
speed% bundle            
Traceback (most recent call last):
	1: from /home/w/.rbenv/versions/2.6.1/bin/bundle:23:in `<main>'
/home/w/.rbenv/versions/2.6.1/bin/bundle:23:in `load': cannot load such file -- /home/w/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/bundler-2.0.1/exe/bundle (LoadError)
</pre>

Somehow installing bundler again installs version 2.0.1, but when I run bundle I get 1.17.2:

<pre>
speed% gem install bundler
Successfully installed bundler-2.0.1
Parsing documentation for bundler-2.0.1
Installing ri documentation for bundler-2.0.1
bDone installing documentation for bundler after 1 seconds
1 gem installed
u%                                                                                                                             speed% bundle
Could not locate Gemfile
speed% which bundler
/home/w/.rbenv/shims/bundler
speed% bundle -v
Bundler version 1.17.2
speed% gem -v
3.0.1
</pre>

At the end of all this I still have two default bundlers:

<pre>
speed% gem list|grep bund
bundler (default: 2.0.1, default: 1.17.2)
</pre>

So far I have not been successful in getting bunder 2 installed on this machine, though I have lock files created by bundler 2 hence clearly I succeeded in getting it installed elsewhere.

**Comment by hsbt** [comment]
It's an issue of [RubyGems](https://github.com/rubygems/rubygems). Please file this to rubygems repository.
