### ISSUE TITLE
Difference between v1 and v2 lock files

### ISSUE THREAD

**Issue by p-mongo** [bundler/bundler#6993]
Given the issues people have with bundler 2 (https://github.com/bundler/bundler/issues/6784, https://github.com/rubygems/rubygems/issues/2661), what exactly are the differences between v1 and v2 lock files that v2 lock files cannot be used by bundler v1?

Because I have this diff that made my lock file unusable:

<pre>
diff --git a/mongoid-app/Gemfile.lock b/mongoid-app/Gemfile.lock
index b87758e..52eda2d 100644
--- a/mongoid-app/Gemfile.lock
+++ b/mongoid-app/Gemfile.lock
@@ -93,7 +93,7 @@ GEM
     mini_mime (1.0.1)
     mini_portile2 (2.4.0)
     minitest (5.11.3)
-    mongo (2.7.0)
+    mongo (2.7.1)
       bson (>= 4.4.2, < 5.0.0)
     mongoid (7.0.2)
       activemodel (>= 5.1, < 6.0.0)
@@ -208,4 +208,4 @@ DEPENDENCIES
   web-console (>= 3.3.0)
 
 BUNDLED WITH
-   1.17.3
+   2.0.1
</pre>

According to https://bundler.io/blog/2019/01/03/announcing-bundler-2.html Bundler 2 does not have any new features.

**Comment by deivid-rodriguez** [comment]
Hei @p-mongo! You are right, bundler 1 and bundler 2 lockfile format should be compatible, and we decided to downgrade those hard errors to warnings for the time being. See #6996.

We still believe that the best way to use bundler is that an application always stick with the same version everywhere. It's not only about lockfile format compatibility, but about making the resolution use the exact same code that resolved the dependencies initially, so it's guaranteed to be the same.

But we acknowledge that we need to do this in a more user-friendly way, so that's why we're downgrading this to a warning.

**Comment by p-mongo** [comment]
Lock file incompatibility is actually preventing bundler 2 adoption because it is easier to downgrade the one machine that accidentally got bundler 2 installed on it to bundler 1 than to constantly deal with harassment from bundler everywhere else, especially since bundler 2 appears to have no significant new features.

Regarding resolution differences, since there is a lock file, what resolution is going on? Bundler should install the versions that the lock file specifies.

**Comment by deivid-rodriguez** [comment]
> Lock file incompatibility is actually preventing bundler 2 adoption because it is easier to downgrade the one machine that accidentally got bundler 2 installed on it to bundler 1 than to constantly deal with harassment from bundler everywhere else, especially since bundler 2 appears to have no significant new features.

I understand that, and we're working on fixing these issues, there's not much more I can say :man_shrugging:.

> Regarding resolution differences, since there is a lock file, what resolution is going on? Bundler should install the versions that the lock file specifies.

This not only applies to `bundle install` with an existing lock file, but to every situation where bundler is used. We would like to enforce that the exact same version is used all the time so all executions of bundler will lead to the same results.

**Comment by p-mongo** [comment]
I understand, thanks.
