### ISSUE TITLE
Use a `disabledByDefault` approach to rubocop

### ISSUE THREAD

**Issue by deivid-rodriguez** [bundler/bundler#7003]
Over the years, I've come to prefer enabling `rubocop` one rule at a time, but enabling consistency across the whole repo, rather that enabling the whole set of default rules, and maintaining a TODO file that gets a lot of churn over time and tends to get outdated.

I feel this approach gets less in the middle of developers with complaints that are not even enforced accross the whole repo. For example, rubocop yielded at me at https://github.com/bundler/bundler/pull/7002, but the offending rule is not fully enforced and [has exceptions](https://github.com/bundler/bundler/blob/4820acf3dbea172c6ec4f165b875acbe85f095cd/.rubocop_todo.yml#L213-L228). I feel it's easier for new developers to follow the current style if they "see it everywhere".

Also, maintaining the TODO file is not fun, and it obscures the point of other changes. For example, in the [2-0-stable merge](https://github.com/bundler/bundler/pull/6957), a big part of the diff is updating the `.rubocop_todo.yml` that doesn't really add much other than merge conflicts.

So, I propose to use the same approach we use in [rubygems](https://github.com/rubygems/rubygems/blob/77c3a99cc473c549bd322c7871d01fb6b8e5c580/.rubocop.yml).

**Comment by hsbt** [comment]
+1

I always enabled `disabledByDefault` at my project.
