### ISSUE TITLE
Upgraded to bundler 2.0.1 and getting version error with rails console but rails server works

### ISSUE THREAD

**Issue by salex** [bundler/bundler#7019]
I set up a new local rails staging server last week (debian/raspberrium) and ran into the `You must use Bundler 2 or greater with this lockfile.` error.

I followed the instructions and upgraded bundler on my OS x system. Got everything working including a capistrono deploy

I don't think I've tried `rails console` since the update, but now I'm getting the version error when I try to open the rails console.

    salexAir:icash salex$ bin/rails c
    You must use Bundler 2 or greater with this lockfile.

More or less did the upgrade over again and still does not work.

`bin/rails console` works on the staging server, but not local.
`bin/rails server` works locally and on staging server, no errors and launches puma

    salexAir:icash salex$ rbenv version
    2.5.3 (set by /users/salex/work/icash/.ruby-version)

    salexAir:icash salex$ bundle version
    Bundler version 2.0.1 (2019-01-04 commit d7ad2192f)

Some stuff from bundle env

    salexAir:icash salex$ bundle env
    ## Environment

    ```
    Bundler       2.0.1
      Platforms   ruby, x86_64-darwin-18
    Ruby          2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin18]
      Full Path   /Users/salex/.rbenv/versions/2.5.3/bin/ruby
      Config Dir  /Users/salex/.rbenv/versions/2.5.3/etc
    RubyGems      3.0.3
      Gem Home    /Users/salex/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0
      Gem Path    /Users/salex/.gem/ruby/2.5.0:/Users/salex/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0
      User Path   /Users/salex/.gem/ruby/2.5.0
      Bin Dir     /Users/salex/.rbenv/versions/2.5.3/bin
    Tools         
      Git         2.16.2
      RVM         not installed
      rbenv       rbenv 1.0.0
      chruby      not installed
    ```

    [...]

    ### Gemfile.lock

    ```
    GIT
      remote: https://github.com/annacruz/ofx.git
      revision: 371640317d94413881ad5d7da29962d8ba8ec9c4
      branch: master
      specs:
        ofx (0.3.2)
          nokogiri

    GEM
      [...]

        rails (5.1.6.1)
          actioncable (= 5.1.6.1)
          actionmailer (= 5.1.6.1)
          actionpack (= 5.1.6.1)
          actionview (= 5.1.6.1)
          activejob (= 5.1.6.1)
          activemodel (= 5.1.6.1)
          activerecord (= 5.1.6.1)
          activesupport (= 5.1.6.1)
          bundler (>= 1.3.0)
          railties (= 5.1.6.1)
          sprockets-rails (>= 2.0.0)
      [...]

    DEPENDENCIES
      autoprefixer-rails
      bcrypt (~> 3.1.7)
      byebug
      capistrano (~> 3.10)
      capistrano-bundler
      capistrano-rails (~> 1.3)
      capistrano-rbenv (~> 2.0)
      capistrano-rbenv-install (~> 1.2.0)
      capistrano3-puma
      capybara (~> 2.13)
      coffee-rails (~> 4.2)
      foundation-rails (= 6.4.3)
      jbuilder (~> 2.5)
      jquery-rails
      jquery-ui-rails
      listen (>= 3.0.5, < 3.2)
      nokogiri (~> 1.10.1)
      ofx (~> 0.3.1)!
      pg
      prawn
      prawn-table
      puma (~> 3.7)
      pundit
      rails (~> 5.1.4)
      sass-rails (~> 5.0)
      selenium-webdriver
      slim-rails
      smarter_csv
      spring
      spring-watcher-listen (~> 2.0.0)
      sqlite3
      tzinfo-data
      uglifier (>= 1.3.0)
      web-console (>= 3.3.0)

    BUNDLED WITH
       2.0.1
    ```

  I'm not sure if the rails dependencies `bundler (>= 1.3.0)` could be stopping the console or not. But then console works fine on the staging server.

  I've tried all the suggested fixes. I guess next step is to drop back to 1.7.x, unless someone can point out something I'm missing.

**Comment by salex** [comment]
Look at other posts after searches, I found something on google rails talk asking for results of `gem list`.

On my OS x

    bundler (2.0.1, default: 1.17.3)

On server

    bundler (2.0.1)

Not sure where the default is set, but could that be a problem?

**Comment by salex** [comment]
I hardly ever restart my mac, but just the the hell of it, I did.

I can now get into the rails console!

Not sure what was apparntly corrupt that caused my problem, but hopefully it is not going to be a repeating feature of Rail/Bundler

**Comment by calaway** [comment]
I had the same problem and a restart fixed it for me too. 

I'm wondering if it could have been a spring issue. If someone else runs into this, try running `spring stop` and trying again. Please post here if it works for you or not to help others. Thanks!

**Comment by katyp** [comment]
@calaway, I ran `spring stop` and voila! `rails c` is back up and at it! Thank you. Glad you posted your guess.

**Comment by abrahamchaibi** [comment]
`spring stop` also fixed the problem for me
