### ISSUE TITLE
Have the ruby version picked up from .ruby-version file if present

### ISSUE THREAD

**Issue by localhostdotdev** [bundler/bundler#7032]
e.g. same as doing `ruby(File.read('.ruby-version').strip) if File.exists?('.ruby-version')` in `Gemfile`

Would prevent the errors of having mismatching ruby versions and the duplication.

**Comment by localhostdotdev** [comment]
One thing I ran into is that this only works for mri released versions, e.g. `2.3.0`, `2.5.1`, etc., but not `ruby-head` for instance.

**Comment by colby-swandale** [comment]
Thanks for the idea but this would be something better suited as Bundler plugin.
