### ISSUE TITLE
Table output for bundle outdated

### ISSUE THREAD

**Issue by thomas-mcdonald** [bundler/bundler#7039]
Currently bundler displays outdated info one line per gem, with no consistent spacing / alignment for each item of information. Having used `yarn` a while, I have grown fond of the table format it uses to declare outdated gems, and would like to see something similar for bundle:

![Screenshot 2019-03-14 at 18 50 51](https://user-images.githubusercontent.com/197928/54383876-f4eb4000-468a-11e9-8bc9-5a6d97cc3440.png)

while I won't make the argument the colours are super useful here (imo they are a bit confusing), the table format seems more legible than the text blob that bundler outputs by default. Would there be any interest in a patch that adds a new output format?

**Comment by ankitkataria** [comment]
I would like to work on this!

**Comment by colby-swandale** [comment]
We'd welcome a PR that improves the `bundle outdated` UI. I don't think there is much more to add to this issue, so i'm closing it.
