### ISSUE TITLE
Unable to run my project on circle ci

### ISSUE THREAD

**Issue by Paluck29** [bundler/bundler#7048]
I added gem 'rake' to the Gemfile and rake in the Dependencies in the Gemfile.lock as was suggested by the error in the previous run. But now I am getting error. It now says that I have a older version of Ruby bundler , i.e. 1.15.4 but in the Gemfile.lock, it's written in the end, that, Bundled with 1.16.2

Following warning is coming and build is failing.

Warning: the running version of Bundler (1.15.4) is older than the version that created the lockfile (1.16.2). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.

Tried searching on the below link as well, but no solution.

https://github.com/bundler/bundler/search?q=Unable+to+find+a+spec+satisfying+rake+%28%3E%3D+0%29+in+the+set.+Perhaps+the+lockfile+is+corrupted%3F&type=Issues

![Screenshot (110)](https://user-images.githubusercontent.com/32965313/54533639-a56d8280-49b0-11e9-9fe1-0354c8f0beb9.png)
![Screenshot (109)](https://user-images.githubusercontent.com/32965313/54533640-a56d8280-49b0-11e9-8c81-834ba229e454.png)

**Comment by simi** [comment]
You need to run your commands in `bundler` environment. It is not clear for me how do you execute commands, but you need to prepend them with `bundle exec` or generate binstubs and run those.

https://bundler.io/v2.0/bundle_exec.html

**Comment by colby-swandale** [comment]
The message you have quoted is a warning and break your build. Can you please attach the error that is causing your build to fail.
