### ISSUE TITLE
`rake spec` results in "uninitialized constant Gem::RDoc"

### ISSUE THREAD

**Issue by duckinator** [bundler/bundler#7081]
I followed [doc/development/SETUP.md](https://github.com/bundler/bundler/blob/master/doc/development/SETUP.md) to get a working development environment:

```
$ git clone https://github.com/bundler/bundler.git
$ cd bundler
$ bin/rake spec:deps
$ bin/rake spec
```

However, `bin/rake spec` resulted in this error:

```
/usr/bin/ruby -S gem install 'rack:< 2.0' 'rack-test:~> 1.1' 'artifice:~> 0.6.0' 'compact_index:~> 0.11.0' 'sinatra:~> 1.4.7' 'rake:12.3.2' 'builder:~> 3.2' ruby-graphviz --no-document --conservative
ERROR:  While executing gem ... (NameError)
    uninitialized constant Gem::RDoc
```

Full logs: https://gist.github.com/duckinator/e3d11c6b0168e4dc804473558a3695e8

Weirdly, manually running the command that results in the error works fine... but still doesn't fix subsequent runs of `bin/rake spec`.

---

OS: Fedora 29
Ruby version: 2.5.3p105
Gem version: 3.0.3

`gem env`: https://gist.github.com/duckinator/d69f6f4f5a129f80d9eceb460dd33e1c

Not really sure how to start debugging this, honestly.

**Comment by duckinator** [comment]
This gets _farther_, but still results in multiple thousands of test failures on my system:

```
GEM_HOME=~/.gem/ruby/2.5.0/ RUBYOPT='-rrake' bin/rake spec
```

**Comment by indirect** [comment]
Seems like this is an issue with Ruby on Arch? It's fixed on master, though: https://github.com/rubygems/rubygems/issues/2483.

**Comment by duckinator** [comment]
Looks like it may be that, or at least related to it. (Although this is Fedora, not Arch.)

How would I work around this, prior to the next rubygems release?

**Comment by indirect** [comment]
@duckinator my impression is that you could edit the rubygems file directly on disk to allow you to install rdoc? or maybe check out the latest rubygems from master and install it.

**Comment by deivid-rodriguez** [comment]
Yeah, the patch is [very simple](https://github.com/rubygems/rubygems/pull/2604/files), so probably the easiest is to apply it manually.

**Comment by indirect** [comment]
(Also this makes me think that shipping a bugfix release so people can upgrade with `gem update --system` or whatever would be a great thing to do soon if someone has time. 😄)

**Comment by colby-swandale** [comment]
This looks answered.
