### ISSUE TITLE
Unknown SSL method `SSLv23'.: cert already in hash table

### ISSUE THREAD

**Issue by lernamanto** [bundler/bundler#7094]
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `/Applications/Server.app/Contents/ServerRoot/usr/bin/bundle install`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what actually happened was...

Error details

    ArgumentError: unknown SSL method `SSLv23'.: cert already in hash table
      /Applications/Server.app/Contents/ServerRoot/usr/lib/ruby/1.9.1/openssl/ssl-internal.rb:38:in `ssl_version='
      /Applications/Server.app/Contents/ServerRoot/usr/lib/ruby/1.9.1/openssl/ssl-internal.rb:38:in `block in set_params'
      /Applications/Server.app/Contents/ServerRoot/usr/lib/ruby/1.9.1/openssl/ssl-internal.rb:38:in `each'
      /Applications/Server.app/Contents/ServerRoot/usr/lib/ruby/1.9.1/openssl/ssl-internal.rb:38:in `set_params'
      /Applications/Server.app/Contents/ServerRoot/usr/lib/ruby/Gems/1.9.1/gems/bundler-1.10.6/lib/bundler/vendor/net/http/persistent/ssl_reuse.rb:43:in `connect'
      /Applications/Server.app/Contents/ServerRoot/usr/lib/ruby/1.9.1/net/http.rb:756:in `do_start'
      /Applications/Server.app/Contents/ServerRoot/usr/lib/ruby/1.9.1/net/http.rb:751:in `start'
      /Applications/Server.app/Contents/ServerRoot/usr/lib/ruby/Gems/1.9.1/gems/bundler-1.10.6/lib/bundler/vendor/net/http/persistent.rb:700:in `start'
      /Applications/Server.app/Contents/ServerRoot/usr/lib/ruby/Gems/1.9.1/gems/bundler-1.10.6/lib/bundler/vendor/net/http/persistent.rb:631:in `connection_for'
      /Applications/Server.app/Contents/ServerRoot/usr/lib/ruby/Gems/1.9.1/gems/bundler-1.10.6/lib/bundler/vendor/net/http/persistent.rb:994:in `request'
      /Applications/Server.app/Contents/ServerRoot/usr/lib/ruby/Gems/1.9.1/gems/bundler-1.10.6/lib/bundler/fetcher/downloader.rb:45:in `request'
      /Applications/Server.app/Contents/ServerRoot/usr/lib/ruby/Gems/1.9.1/gems/bundler-1.10.6/lib/bundler/fetcher/downloader.rb:15:in `fetch'
      /Applications/Server.app/Contents/ServerRoot/usr/lib/ruby/Gems/1.9.1/gems/bundler-1.10.6/lib/bundler/fetcher/dependency.rb:7:in `api_available?'
      /Applications/Server.app/Contents/ServerRoot/usr/lib/ruby/Gems/1.9.1/gems/bundler-1.10.6/lib/bundler/fetcher.rb:135:in `block in use_api'
      /Applications/Server.app/Contents/ServerRoot/usr/lib/ruby/Gems/1.9.1/gems/bundler-1.10.6/lib/bundler/fetcher.rb:135:in `reject!'
      /Applications/Server.app/Contents/ServerRoot/usr/lib/ruby/Gems/1.9.1/gems/bundler-1.10.6/lib/bundler/fetcher.rb:135:in `use_api'
      /Applications/Server.app/Contents/ServerRoot/usr/lib/ruby/Gems/1.9.1/gems/bundler-1.10.6/lib/bundler/source/rubygems.rb:320:in `select'
      /Applications/Server.app/Contents/ServerRoot/usr/lib/ruby/Gems/1.9.1/gems/bundler-1.10.6/lib/bundler/source/rubygems.rb:320:in `api_fetchers'
      /Applications/Server.app/Contents/ServerRoot/usr/lib/ruby/Gems/1.9.1/gems/bundler-1.10.6/lib/bundler/source/rubygems.rb:325:in `block in remote_specs'
      /Applications/Server.app/Contents/ServerRoot/usr/lib/ruby/Gems/1.9.1/gems/bundler-1.10.6/lib/bundler/index.rb:9:in `build'
      /Applications/Server.app/Contents/ServerRoot/usr/lib/ruby/Gems/1.9.1/gems/bundler-1.10.6/lib/bundler/source/rubygems.rb:324:in `remote_specs'
      /Applications/Server.app/Contents/ServerRoot/usr/lib/ruby/Gems/1.9.1/gems/bundler-1.10.6/lib/bundler/source/rubygems.rb:81:in `specs'
      /Applications/Server.app/Contents/ServerRoot/usr/lib/ruby/Gems/1.9.1/gems/bundler-1.10.6/lib/bundler/definition.rb:211:in `block (2 levels) in index'
      /Applications/Server.app/Contents/ServerRoot/usr/lib/ruby/Gems/1.9.1/gems/bundler-1.10.6/lib/bundler/definition.rb:209:in `each'
      /Applications/Server.app/Contents/ServerRoot/usr/lib/ruby/Gems/1.9.1/gems/bundler-1.10.6/lib/bundler/definition.rb:209:in `block in index'
      /Applications/Server.app/Contents/ServerRoot/usr/lib/ruby/Gems/1.9.1/gems/bundler-1.10.6/lib/bundler/index.rb:9:in `build'
      /Applications/Server.app/Contents/ServerRoot/usr/lib/ruby/Gems/1.9.1/gems/bundler-1.10.6/lib/bundler/definition.rb:206:in `index'
      /Applications/Server.app/Contents/ServerRoot/usr/lib/ruby/Gems/1.9.1/gems/bundler-1.10.6/lib/bundler/definition.rb:200:in `resolve'
      /Applications/Server.app/Contents/ServerRoot/usr/lib/ruby/Gems/1.9.1/gems/bundler-1.10.6/lib/bundler/definition.rb:140:in `specs'
      /Applications/Server.app/Contents/ServerRoot/usr/lib/ruby/Gems/1.9.1/gems/bundler-1.10.6/lib/bundler/definition.rb:129:in `resolve_remotely!'
      /Applications/Server.app/Contents/ServerRoot/usr/lib/ruby/Gems/1.9.1/gems/bundler-1.10.6/lib/bundler/installer.rb:79:in `run'
      /Applications/Server.app/Contents/ServerRoot/usr/lib/ruby/Gems/1.9.1/gems/bundler-1.10.6/lib/bundler/installer.rb:18:in `install'
      /Applications/Server.app/Contents/ServerRoot/usr/lib/ruby/Gems/1.9.1/gems/bundler-1.10.6/lib/bundler/cli/install.rb:107:in `run'
      /Applications/Server.app/Contents/ServerRoot/usr/lib/ruby/Gems/1.9.1/gems/bundler-1.10.6/lib/bundler/cli.rb:162:in `install'
      /Applications/Server.app/Contents/ServerRoot/usr/lib/ruby/Gems/1.9.1/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /Applications/Server.app/Contents/ServerRoot/usr/lib/ruby/Gems/1.9.1/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /Applications/Server.app/Contents/ServerRoot/usr/lib/ruby/Gems/1.9.1/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /Applications/Server.app/Contents/ServerRoot/usr/lib/ruby/Gems/1.9.1/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /Applications/Server.app/Contents/ServerRoot/usr/lib/ruby/Gems/1.9.1/gems/bundler-1.10.6/lib/bundler/cli.rb:10:in `start'
      /Applications/Server.app/Contents/ServerRoot/usr/lib/ruby/Gems/1.9.1/gems/bundler-1.10.6/bin/bundle:20:in `block in <top (required)>'
      /Applications/Server.app/Contents/ServerRoot/usr/lib/ruby/Gems/1.9.1/gems/bundler-1.10.6/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
      /Applications/Server.app/Contents/ServerRoot/usr/lib/ruby/Gems/1.9.1/gems/bundler-1.10.6/bin/bundle:18:in `<top (required)>'
      /Applications/Server.app/Contents/ServerRoot/usr/bin/bundle:23:in `load'
      /Applications/Server.app/Contents/ServerRoot/usr/bin/bundle:23:in `<main>'

Environment

    Bundler   1.10.6
    Rubygems  1.8.23.2
    Ruby      1.9.3p545 (2014-02-24 revision 45159) [universal.x86_64-darwin13]
    GEM_HOME  /Applications/Server.app/Contents/ServerRoot/usr/lib/ruby/Gems/1.9.1
    GEM_PATH  /Applications/Server.app/Contents/ServerRoot/usr/lib/ruby/Gems/1.9.1:/Users/user_name/.gem/ruby/1.9.1:/Applications/Server.app/Contents/ServerRoot/usr/lib/ruby/gems/1.9.1
    Git       2.20.1 (Apple Git-117)
--- TEMPLATE END ----------------------------------------------------------------

**Comment by deivid-rodriguez** [comment]
The bundler, rubygems and ruby version you are using are no longer supported. Please make sure you upgrade everything, starting with ruby, and let us know if you run into any problems.

Good luck!

**Comment by lernamanto** [comment]
Hi,

All sorted now, thank you very much!
--
djmil Secco
