### ISSUE TITLE
How to set bundler 2.0.1 as default

### ISSUE THREAD

**Issue by nhieu92** [bundler/bundler#7107]
Hi,
I'm using ruby 2.6.2 and at the root folder (Not contain any Gemfile.lock file).
```
gem list bundler
bundler (2.0.1, default: 1.17.2)

bundler -v
Bundler version 2.0.1
```

How can I switch to 2.0.1 as default ? (Current, it said default: 1.17.2)
Thank you.

**Comment by Akrabut** [comment]
Try `bundler config default 2.0.1`

**Comment by colby-swandale** [comment]
It's not a configuration variable you can set. It's the version of Bundler that is currently install in the default set of gems in ruby. You can update it with `gem update --system` but that will also update RubyGems.

**Comment by benbonnet** [comment]
No way to remove default gem (but while you search how to , you see that many versions can be set as default... so great!)

Which means, `bundler config default 2.0.1` will set a second default gem version if you had one
(here was my current state `bundler (2.0.1, default: 1.17.3, default: 1.16.1)`)

If 'im not wrong, when a gem is set as default, it ends up in some `...specifications/default/gemname.gemspec`

The only successful way I've found was to delete them all defaults (if you're on ubuntu, `locate specifications/bundler` would sho where it's at), and reinstall bundler

**Comment by sergeyradov** [comment]
Tried this and it worked for me `gem install bundler --default -v "2.0.1" `

**Comment by benbonnet** [comment]
@sergeyradov what's your  `gem list | grep bundler` output ? you'll which is the default one - and in my case, I had 2 defaults, which caused lots of troubles

**Comment by sergeyradov** [comment]
@benbonnet As a result I got 2 defaults. It looks like a issue in Gem set or I don't understand how defaults work in gem. 
After applying gem install bundler --default -v "2.0.1" I got two defaults and both could not be deleted.

**Comment by benbonnet** [comment]
that's pretty much the issue i had; and it sounds quite buggy. Unable to find how to get back to a single default

**Comment by JulesMoorhouse** [comment]
@sergeyradov  / @benbonnet did either of your guys solve this?

**Comment by sergeyradov** [comment]
I have resolved this by uninstall whole ruby through rbenv.
Than I started to indicate version.

**Comment by benbonnet** [comment]
same here, uninstalling and defining version on reinstall.

Moreover, while not being the cleanest way; I've found out how to remove (manually) the defined default gem as even after removing bundler, the default remains - so as describe in my previous comment, this step solves the presence of the 2 defaults :

`irb(main):001:0> File.join Gem::Specification.default_specifications_dir`

Then open the output folder, remove the corresponding gemspec file

**Comment by subrata** [comment]
> @benbonnet As a result I got 2 defaults. It looks like a issue in Gem set or I don't understand how defaults work in gem.
> After applying gem install bundler --default -v "2.0.1" I got two defaults and both could not be deleted.

I have resolved this by uninstalling whole ruby version through rbenv/rvm. After that I installed again and problem was resoled.

**Comment by benbonnet** [comment]
@subrata for sure scratching the whole stuff if you can is the best way. That is, having those two persistent defaults remains annoying - and quite feels buggy

**Comment by ToTenMilan** [comment]
Removing gemspec files has made `gem list` to show one bundler as default, but `bundle` was still using old default bundler

Solution/workaround for me was to do
```
rvm @global do gem install bundler -v 1.17.1
```
as in answer [here](https://github.com/rvm/rvm/issues/4566#issuecomment-451525422)  for different problem

**Comment by DeeprajPandey** [comment]
Facing the same issue as @sergeyradov and I am currently following what @benbonnet suggested.
But when I ran that in irb, I got a note that `Gem::Specification` will not work anymore after 2020-02-01.

Use this instead
```
irb(main):001:0> File.join Gem.default_specifications_dir
```

**Comment by coopeu** [comment]
Thanks ToTenMilan
rvm @global do gem install bundler -v 2.1.4

**Comment by pingnamo** [comment]
Facing this issue while installing bundler 2.1.4 but the system shows both 2.1.2 and 2.1.4 as default bundler gems.

Running this seems to have strange behaviour on the installed bundler version:
```
# gem install bundler -v 2.1.4 --default
Successfully installed bundler-2.1.4 as a default gem
# /path/to/ruby/gems/bundler-2.1.4/exe/bundle -v
Bundler version 2.1.2  <== but not bundler 2.1.4
```

Fixed the issue by following this to remove the default spec of bundler and `gem install bundler -v 2.1.4` again without the default flag

https://github.com/rubygems/rubygems/issues/2157

```
# rm /path/to/ruby/gems/specifications/default/rails-2.1.2.gemspec
# gem uninstall bundler -v 2.1.2
# gem install bundler -v 2.1.4
```
