### ISSUE TITLE
[help wanted] script using bundler/inline in "frozen" capistrano-deployed app

### ISSUE THREAD

**Issue by silent-e** [bundler/bundler#7114]
hello.  I need some help understanding if I'm just being dumb about my implementation of something.  I already have a solution that fixes what I'm about to describe but it feels wrong. Apologies for the length.

## Problem
I have an app I just recently converted to deploying with Capistrano.  As such it freezes my bundle with a .bundle/config file setting of `BUNDLE_FROZEN: "true"`.  All well and good for the app.  However I have a standalone ruby script, in `[RAILS_ROOT]/bin`, that gets deployed along with the app. That script uses `bundler/inline` to load gems that are newer than the ones specified in my app Gemfile.

Since I'm in a "frozen" deployment state I get the following when trying to run the bin script from the Rails root directory…

````
/home/app/.rbenv/versions/2.4.5/lib/ruby/site_ruby/2.4.0/bundler/definition.rb:506:in `validate_platforms!': Your bundle only supports platforms [] but your local platforms are ["ruby", "x86_64-linux"], and there's no compatible match between those two lists. (Bundler::ProductionError)
	from /home/app/.rbenv/versions/2.4.5/lib/ruby/site_ruby/2.4.0/bundler/definition.rb:471:in `validate_runtime!'
	from /home/app/.rbenv/versions/2.4.5/lib/ruby/site_ruby/2.4.0/bundler/inline.rb:53:in `gemfile'
	from bin/test:5:in `<main>'
````
_please ignore the use of 2.4.5.  we're working on upgrading._ 😄

Here's an example script that fails…

````ruby
#!/usr/bin/env ruby
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'

  gem 'awesome_print'
end

ap 'foo'
````

to get it to fail add `BUNDLE_FROZEN: "true"` to your `.bundle/config` file.  I can do this even in my local dev environment.

## How I got it work
Like I said at the start.  I figured out how to make the script run just fine.  To get it to work I had to wrap the `gemfile` call like so…

````ruby
#!/usr/bin/env ruby
require 'bundler/inline'
require 'bundler'

Bundler.settings.temporary(frozen: false) do
  gemfile do
    source 'https://rubygems.org'

    gem 'awesome_print'
  end
end

ap 'foo'
````

It feels weird to have to do that.  I want bundler inline to ignore the frozen status from the get-go.  But perhaps the Bundler devs have reasons.

## Plea for help
Does anyone have thoughts on this?  I would prefer to keep the bin script inside my Rails app since it and the app share .env settings.  I can't believe I'm the first person to run a ruby script using inline bundler inside a capistrano-deployed Rails app.  But perhaps I am.  🤔😄 

Thanks in advance.

(e)

**Comment by deivid-rodriguez** [comment]
Hi @silent-e! No need to apologize for the lenght, this is such a great issue report! Thanks!

I think the frozen concept doesn't apply to the inline mode since there is no lockfile? So we can probably fix this inside `bundler` with something similar to #7124, and to your workaround.
