### ISSUE TITLE
Bundle install is failing when installing gems with SIGTERM error

### ISSUE THREAD

**Issue by kthallam** [bundler/bundler#7119]
When we are running the gems install by using bundle.

Here is the error. 

--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `/opt/chef/embedded/bin/bundle install`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what actually happened was...

Error details

    SignalException: SIGTERM
      /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/dependency.rb:175:in `=='
      /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/dep_proxy.rb:16:in `=='
      /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:223:in `include?'
      /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:223:in `block in parent_of'
      /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:222:in `reverse_each'
      /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:222:in `each'
      /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:222:in `find'
      /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:222:in `parent_of'
      /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:282:in `requirement_tree_for'
      /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:273:in `block in requirement_trees'
      /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:273:in `map'
      /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:273:in `requirement_trees'
      /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:264:in `create_conflict'
      /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:149:in `process_topmost_state'
      /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:72:in `resolve'
      /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/vendor/molinillo/lib/molinillo/resolver.rb:42:in `resolve'
      /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/resolver.rb:201:in `start'
      /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/resolver.rb:184:in `resolve'
      /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/definition.rb:200:in `resolve'
      /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/definition.rb:140:in `specs'
      /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/definition.rb:129:in `resolve_remotely!'
      /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/installer.rb:195:in `resolve_if_need'
      /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/installer.rb:70:in `run'
      /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/installer.rb:22:in `install'
      /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/cli/install.rb:102:in `run'
      /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/cli.rb:175:in `install'
      /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/cli.rb:11:in `start'
      /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/exe/bundle:27:in `block in <top (required)>'
      /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
      /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/exe/bundle:19:in `<top (required)>'
      /opt/chef/embedded/bin/bundle:22:in `load'
      /opt/chef/embedded/bin/bundle:22:in `<main>'

Environment

  Bundler   1.12.5
  Rubygems  2.6.6
  Ruby      2.1.9p490 (2016-03-30 revision 54437) [x86_64-linux]
  GEM_HOME  /opt/chef/embedded/lib/ruby/gems/2.1.0
  GEM_PATH  /opt/chef/embedded/lib/ruby/gems/2.1.0:/root/.gem/ruby/2.1.0
  Git       not installed

      Bundler settings

  orig_path
    Set via BUNDLE_ORIG_PATH: "/opt/chef/embedded/bin:/sbin:/bin:/usr/sbin:/usr/bin:/opt/chef/embedded/bin:/opt/chef/embedded/bin:/usr/local/sbin:/usr/local/bin"
--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/bundler/bundler/search?q=SIGTERM&type=Issues

If there aren't any reports for this error yet, please create copy and paste the report template above into a new issue. Don't forget to anonymize any private data! The new issue form is located at:
https://github.com/bundler/bundler/issues/new

Running handlers:
Running handlers complete
Chef Client failed. 0 resources updated in 09 minutes 22 seconds

**Comment by deivid-rodriguez** [comment]
Hi! You're running a very old version of ruby (2.1) and bundler (1.12). It seems like `chef` is vendoring both, so your problem should be fixed by upgrading your chef installation.

Closing for now, but let us know if you still run into problems after upgrading.
