### ISSUE TITLE
BUNDLE_PATH is not respected with bundle/inline

### ISSUE THREAD

**Issue by lastk** [bundler/bundler#7131]
When setting `BUNDLE_PATH` with a script using `bundle/inline` the folder is created but the gems are not downloaded inside it.

test script:

```
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  gem 'hello-ruby-gem'
end
```
calling this script with: `BUNDLE_PATH=./vendor/bundle ruby test.rb` creates the empty folders `.vendor/bundle` inside my dir.

**Comment by deivid-rodriguez** [comment]
Closed as expected behavior and documented through a test in #7154.
