### ISSUE TITLE
Can't install gem backup. Ruby 2.6.2.

### ISSUE THREAD

**Issue by DSKonstantin** [bundler/bundler#7132]
`Ruby 2.6.2`
`Rails 5.2.3`

I try to install gem backup:
`gem install backup --version 5.0.0.beta.2`

Get it:
> Building native extensions. This could take a while...
> ERROR:  Error installing backup:
> 	ERROR: Failed to build gem native extension.
> 
>     current directory: /usr/local/rvm/gems/ruby-2.6.2@<gemset>/gems/unf_ext-0.0.7.5/ext/unf_ext
> /usr/local/rvm/rubies/ruby-2.6.2/bin/ruby -I /usr/local/rvm/rubies/ruby-2.6.2/lib/ruby/2.6.0 -r ./siteconf20190416-16071-1s4d5fk.rb extconf.rb
> checking for -lstdc++... no
> creating Makefile
> 
> current directory: /usr/local/rvm/gems/ruby-2.6.2@<gemset>/gems/unf_ext-0.0.7.5/ext/unf_ext
> make "DESTDIR=" clean
> 
> current directory: /usr/local/rvm/gems/ruby-2.6.2@<gemset>/gems/unf_ext-0.0.7.5/ext/unf_ext
> make "DESTDIR="
> compiling unf.cc
> g++: error: unrecognized command line option '-Wduplicated-cond'
> g++: error: unrecognized command line option '-Wmisleading-indentation'
> g++: error: unrecognized command line option '-Wrestrict'
> g++: error: unrecognized command line option '-Wimplicit-fallthrough=0'
> Makefile:211: recipe for target 'unf.o' failed
> make: *** [unf.o] Error 1
> 
> make failed, exit code 2
> 
> Gem files will remain installed in /usr/local/rvm/gems/ruby-2.6.2@<gemset>/gems/unf_ext-0.0.7.5 for inspection.
> Results logged to /usr/local/rvm/gems/ruby-2.6.2@<gemset>/extensions/x86_64-linux/2.6.0/unf_ext-0.0.7.5/gem_make.out

Thank you.

**Comment by colby-swandale** [comment]
Hi, this is not an issue with Bundler. Compile errors is a problem that needs to be raised with the gem authors.
