### ISSUE TITLE
i try to create db using rake db:create in my rails app and it is showing this error ''You must use Bundler 2 or greater with this lockfile.''

### ISSUE THREAD

**Issue by z-war** [bundler/bundler#7134]

**Comment by samyak-jn** [comment]
**To use Bundler 2 in your lockfile:**
> Update Rubygems
`gem update --system`
> update bundler
`gem install bundler`
> Update Gemfile.lock  in your project
`bundler update --bundler`

**Comment by deivid-rodriguez** [comment]
What's your rubygems version (`gem --version`), @z-war?

**Comment by colby-swandale** [comment]
no response. closing.
