### ISSUE TITLE
load: cannot load such file

### ISSUE THREAD

**Issue by phoenixadb** [bundler/bundler#7176]
Hello,

My environment is :
- rvm 1.29.8
- gem 3.0.3
- ruby 2.6.3

By default, I got Bundler 1.17.2. 
In order to get Bundler 2.0.1, I install it with  
`gem install --default bundler -v '2.0.1'`

I got a error when using it :
> load: cannot load such file

**Comment by OPARA-PROSPER** [comment]
Try running 

```
gem install bundler
```

It still automatically installs *bundler 2.0.1*

**Comment by phoenixadb** [comment]
Already tried. It creates directory with files and add it to gem list but is not functionnal.
The error happens when I try to execute bundler such as :
`bundler --version`

I managed to the error by removing RVM
`gem uninstall -aIx
rvm implode
gem uninstall rvm
gem dependency devise --pipe | cut -d \  -f 1 | xargs gem uninstall -a
/usr/bin/sudo rm -rf $HOME/.rvm $HOME/.rvmrc /etc/rvmrc /etc/profile.d/rvm.sh /usr/local/rvm /usr/local/bin/rvm`

... and reinstall it from scratch, with bundler as the first gem installed.
