### ISSUE TITLE
Raspberry pi metasploit instalation problem

### ISSUE THREAD

**Issue by 51a3Xp10InJ3c70r** [bundler/bundler#7195]
I am  trying to install msf on rpi and getting this error
Installing bcrypt 3.1.13 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.3.0/gems/bcrypt-3.1.13/ext/mri
/usr/bin/ruby2.3 -r ./siteconf20190609-5184-3uqpqi.rb extconf.rb
creating Makefile

current directory: /var/lib/gems/2.3.0/gems/bcrypt-3.1.13/ext/mri
make "DESTDIR=" clean

current directory: /var/lib/gems/2.3.0/gems/bcrypt-3.1.13/ext/mri
make "DESTDIR="
compiling bcrypt_ext.c
compiling crypt_blowfish.c
compiling crypt_gensalt.c
compiling wrapper.c
gcc  -D__SKIP_GNU -Wdate-time -D_FORTIFY_SOURCE=2 -D_FILE_OFFSET_BITS=64   -c -o
x86.o x86.S
x86.S: Assembler messages:
x86.S:202: Error: junk at end of line, first unrecognized character is `,'
<builtin>: recipe for target 'x86.o' failed
make: *** [x86.o] Error 1

make failed, exit code 2

Gem files will remain installed in /var/lib/gems/2.3.0/gems/bcrypt-3.1.13 for
inspection.
Results logged to
/var/lib/gems/2.3.0/extensions/arm-linux/2.3.0/bcrypt-3.1.13/gem_make.out

An error occurred while installing bcrypt (3.1.13), and Bundler cannot
continue.
Make sure that `gem install bcrypt -v '3.1.13' --source 'https://rubygems.org/'`
succeeds before bundling.

In Gemfile:
  metasploit-framework was resolved to 5.0.29, which depends on
    bcrypt

Please help

**Comment by colby-swandale** [comment]
> x86.S:202: Error: junk at end of line, first unrecognized character is `,'

Hi, this is not a bug with Bundler. Please check the gem homepage for support around the build error you're receiving.
