### ISSUE TITLE
bundle-config(1) manpage says `bundle install` doesn't remember options but it does

### ISSUE THREAD

**Issue by uasi** [bundler/bundler#7198]
From https://github.com/bundler/bundler/blob/v2.0.1/man/bundle-config.ronn#remembering-options

> Flags passed to `bundle install` or the Bundler runtime,
such as `--path foo` or `--without production`, are not remembered between commands.
If these options must be remembered,they must be set using `bundle config`
(e.g., `bundle config path foo`).

IIRC it was true in 2.0.0.dev but had been reverted back to the original behavior. Maybe we should reverse the change to manpages in this commit? https://github.com/bundler/bundler/commit/e120f40f72fe53f55e05db9204f98d28f1065e81

**Comment by colby-swandale** [comment]
Yes, this should be fixed. We would welcome a PR to help resolve this.

**Comment by uasi** [comment]
Okay, I'm on it. I found that a few more options are actually remembered -- `--frozen`, `--jobs`,  `--retry`, `--shebang`, `--trust-policy`, and `--with`. I'll describe them too.

**Comment by TSMMark** [comment]
Would this be causing an issue when installing from git source?

> The git source https://github.com/whoever/whatever.git is not yet checked out. Please run `bundle install` before trying to start your application

We just started getting this on CI this week, I'm thinking it could be related to the bundler 2.0.2 release.

**Comment by TSMMark** [comment]
Confirmed, fixing bundler version to 2.0.1 has solved the error:

> The git source https://github.com/whoever/whatever.git is not yet checked out. Please run bundle install before trying to start your application

**Comment by uasi** [comment]
@TSMMark I believe the issue you have is caused by this change https://github.com/bundler/bundler/pull/6798 

> Use https in the Github shortcut by default in Bundler 2

That is, `gem 'foo', github: 'whoever/whatever'` defaults to HTTPS, instead of plain HTTP, since 2.0.2.

**Comment by vanburg** [comment]
Beside that, is there a way to prevent re-writing/touching config file at all? Bundler re-writes config on each `bundle install` which may lead to another docker layer with only this changed file (in some setups). I'll tried to write-protect it, but this didn't help (as root):
> rm .bundle/config && touch .bundle/config && chmod 0440 .bundle/config
> bundle -v

> Bundler version 2.0.2

> bundle install --jobs=4
> bundle conf

> Settings are listed in order of priority. The top value will be used.
> jobs
> Set for your local app (/app/.bundle/config): 5
> ...

Keeping it untouched in this case would be perfect...
