### ISSUE TITLE
GemNotFoundException since version 2.0.2

### ISSUE THREAD

**Issue by Kjarrigan** [bundler/bundler#7205]
2.0.2 broke our systemd jobs. Works flawless with 2.0.1

Message:
```
Jun 14 11:24:44 systemd[1]: Started fluentd, bundled with plugins.
Jun 14 11:24:45 fluentd[1516506]: /usr/lib/ruby/2.5.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundle (Gem::GemNotFoundException)
Jun 14 11:24:45 fluentd[1516506]:         from /usr/lib/ruby/2.5.0/rubygems.rb:308:in `activate_bin_path'
Jun 14 11:24:45 fluentd[1516506]:         from /usr/local/bin/bundle:23:in `<main>'
Jun 14 11:24:45 systemd[1]: fluentd.service: Main process exited, code=exited, status=1/FAILURE
```

Script:

```bash
#!/bin/sh -a

[ -f /etc/default/fluentd ] && . /etc/default/fluentd

cd /opt/fluentd
bundle exec vendor/bin/fluentd --config /opt/fluentd/fluent.conf $@
code=$?
cd - >/dev/null
exit $code
```

Environment:

```
Linux foo #55-Ubuntu SMP Wed May 15 14:27:21 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]
Bundler version 2.0.2
```

**Comment by schneems** [comment]
I'm getting reports that Heroku customers are hitting this with Ruby 2.5.x when they try to upgrade to Bundler 2.0.2.

From the linked post. 

> The bug is fixed in RubyGems 2.7.10

The version of RubyGems that is packaged with Ruby 2.5.5 is `2.7.6.2` are there plans for a new version of 2.5 to be released with this version? Alternatively is there a patchfile that I can apply to 2.5.5 ? @hsbt 

Here's a link to the changelog for anyone curious:
 - https://blog.rubygems.org/2019/06/14/2.7.10-released.html.

**Comment by hsbt** [comment]
@schneems Ruby 2.5.5 with rubygems-2.7.6.2 did include the same patch for 2.7.10 at https://github.com/ruby/ruby/commit/7244db9da3a02fc5577200ad67a2e132b4a41f26

The alternative solution is to upgrade the latest stable version of Ruby 2.5.x.

**Comment by schneems** [comment]
We are using 2.5.5 with rubygems 2.7.6.2 and seeing this issue when the buildpack tries to run `bundle platform --ruby` against a customer's application.

**Comment by hsbt** [comment]
Interesting, the case of heroku is probably the difference from this issue. Can you file it with error log or another resource? Thanks.

**Comment by schneems** [comment]
Sorry for that response. I completely ignored that this issue is happening on our deployed version and not on master. I've bumped the version of Ruby on master but not deployed it yet. From our changelog

> Default Ruby version is now 2.5.5, was previously 2.5.3 (https://github.com/heroku/heroku-buildpack-ruby/pull/863)

I am terribly sorry for that confusion. I'll deploy soon and let you know if I have additional problems along with a reproduction.

**Comment by hsbt** [comment]
No problem! I always welcome to your report.

**Comment by schneems** [comment]
Hmm. I'm still seeing failures with Ruby 2.5.5

```
-----> Setting up Test for Ruby
-----> Using Ruby version: ruby-2.5.5
-----> Installing dependencies using bundler 2.0.2
       Running: bundle install --without development --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
       Activating bundler (2.0.1) failed:
       Could not find 'bundler' (2.0.1) required by your /app/Gemfile.lock.
       To update to the latest version installed on your system, run `bundle update --bundler`.
       To install the missing version, run `gem install bundler:2.0.1`
       Checked in 'GEM_PATH=vendor/bundle/ruby/2.5.0', execute `gem env` for more information
       
       To install the version of bundler this project requires, run `gem install bundler -v '2.0.1'`
       Bundler Output: Activating bundler (2.0.1) failed:
       Could not find 'bundler' (2.0.1) required by your /app/Gemfile.lock.
       To update to the latest version installed on your system, run `bundle update --bundler`.
       To install the missing version, run `gem install bundler:2.0.1`
       Checked in 'GEM_PATH=vendor/bundle/ruby/2.5.0', execute `gem env` for more information
       
       To install the version of bundler this project requires, run `gem install bundler -v '2.0.1'`
 !
 !     Failed to install gems via Bundler.
```

This was from Heroku CI. I can try to work on a reproduction but this week is short due to July 4th holiday.

**Comment by colby-swandale** [comment]
@schneems this looks like `bundler` is a dependency in the `Gemfile` and that it's locked to 2.0.1. Can you share the Gemfile so we can test?

**Comment by schneems** [comment]
@colby-swandale here's a repro on Heroku https://github.com/heroku/heroku-buildpack-ruby/pull/900 The Gemfile to repro this is pretty small

```
BUNDLED WITH
   2.0.1
```

But then the buildpack will use 2.0.2. 

I added comments to the description of what I think is happening. TLDR it looks like putting bundler directly on the PATH and not executing it via a `gem` shim wrapper triggers this failure. Though to trigger this case on Heroku you have to deploy twice. Granted i'm still exploring here, so take all my analysis with a grain of salt.
