### ISSUE TITLE
trading_ui make error

### ISSUE THREAD

**Issue by mostafatofighi83** [bundler/bundler#7240]
Service 'trading_ui' failed to build: The command '/bin/sh -c mkdir -p /opt/vendor/bundle  && chown -R app:app /opt/vendor  && su app -s /bin/bash -c "bundle install --path /opt/vendor/bundle"' returned a non-zero code: 1

when get command make build after 20 minute this error show  help me

**Comment by duckinator** [comment]
Is this still a problem? If so, can you provide more context on what you were trying to do and what the environment is?

**Comment by colby-swandale** [comment]
No response. Closing.
