### ISSUE TITLE
Bundler 2.x binstub incorrectly raises an error when run with a different bundler 2.x version

### ISSUE THREAD

**Issue by schneems** [bundler/bundler#7243]
## Behavior

When using Bundler 2.0.2 with Ruby 2.5.5 and a Gemfile.lock that specifies a different 2.x version such as 2.0.1, bundler will generate a binstub that cannot be executed, instead it errors out and says that it expects to find the exact 2.0.1 version (even though 2.0.2 is fine and present).

```
Activating bundler (2.0.1) failed:
Could not find 'bundler' (2.0.1) required by your /Gemfile.lock.
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:2.0.1`
Checked in 'GEM_PATH=/root/.gem/ruby/2.5.0:/usr/local/lib/ruby/gems/2.5.0:/usr/local/bundle', execute `gem env` for more information

To install the version of bundler this project requires, run `gem install bundler -v '2.0.1'`
```

## Expected Behavior

Expected the binstub generated by bundler match version selector logic of rubygems and allow any major version of bundler to be able to execute a Gemfile.lock with a similar major version (i.e. 2.0.2 should be able to execute a Gemfile.lock with 2.0.1 or 2.0.3 or 2.1.0 etc.)

## Reproduction

In a fresh docker instance:

```
docker run -it --rm ruby:2.5 bash
```

Using bundler 2.0.2 with a Gemfile that contains a gem with an executable:

```
gem install bundler -v 2.0.2
cat << EOM > Gemfile
source 'https://rubygems.org'

gem 'explain_shell'
EOM

cat << EOM > Gemfile.lock
GEM
  remote: https://rubygems.org/
  specs:
    explain_shell (1.0.2)

PLATFORMS
  ruby

DEPENDENCIES
  explain_shell

BUNDLED WITH
   2.0.1
EOM
```

> Note that the BUNDLED WITH points at a different 2.x version, but it should be fine

Now install the gems and specify you want binstubs:

```
bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
```

This will generate binstubs for all gems as well as for bundler, if you try to execute this binstub directly it fails:

```
$ vendor/bundle/bin/bundle install

Activating bundler (2.0.1) failed:
Could not find 'bundler' (2.0.1) required by your /Gemfile.lock.
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:2.0.1`
Checked in 'GEM_PATH=/root/.gem/ruby/2.5.0:/usr/local/lib/ruby/gems/2.5.0:/usr/local/bundle', execute `gem env` for more information

To install the version of bundler this project requires, run `gem install bundler -v '2.0.1'`
```

I originally found this in the Ruby buildpack, here's my original PR with the original Heroku specific repro (https://github.com/heroku/heroku-buildpack-ruby/pull/900)

**Comment by indirect** [comment]
We probably want to remove the custom binstub for Bundler, now that we are also working on removing the RubyGems code that locks Bundler versions?

**Comment by schneems** [comment]
> now that we are also working on removing the RubyGems code that locks Bundler versions?

Seems good. From a Heroku standpoint, if the next version of 2.x can work across a Gemfile.lock with any other version of 2.x then we're good to go. I'll leave my failing test case unmerged and cherry-pick it into the PR when I update to the next version of Bundler 2.x in the buildpack.

**Comment by indirect** [comment]
@deivid-rodriguez can you remind me where we are at on removing the Bundler version locking/exceptions from RubyGems?

**Comment by deivid-rodriguez** [comment]
Hi @indirect! The last progress made here was to [remove hard errors about this inside bundler's code](https://github.com/bundler/bundler/pull/6996/commits/e1d534ae6f749d2ef976ea77d787914681be2b1a), because they should be caught by the rubygems version finder earlier anyways.

But the code in rubygems that chooses bundler versions is still there.

In my opinion, the easiest way to fix this, at least for the time being, is to reproduce the exact same locking rubygems does inside the bundler binstub, as @schneems suggests (allow minor & patch level differences, but forbid major version mismatches).

**Comment by indirect** [comment]
That also makes sense to me! Let’s start there, and we can evaluate whether removing the major check makes sense once we have the next major release ready.

**Comment by deivid-rodriguez** [comment]
Great, I'll take this next :+1:.
