### ISSUE TITLE
Core testing - spec/bundler/source_spec.rb - 'out of sync' file

### ISSUE THREAD

**Issue by MSP-Greg** [bundler/bundler#7253]
@hsbt,

I wrote some code to see if the bundler 'update from upstream' could be automated (you may have the same) for ruby/ruby and the bundler default gem files, and ran the CI in Pipelines in my ruby/ruby fork.

In the Ruby CI, some of the specs in this file are 'pending', but the same doesn't happen with the copy here pushed into Ruby.

I really haven't looked at the code, nor an I familiar with Thor, but https://github.com/ruby/ruby/commit/19408c785c6f258024efcaa69d0642ad995c50b3 may need to be added here...

With that added, all the commits added here since the last update can be pushed into ruby/ruby and yield the same results on the MacOS job.  The Ubuntu job is being corrupted by something with Rspec...

**Comment by deivid-rodriguez** [comment]
These specs are no longer skipped everywhere since https://github.com/bundler/bundler/pull/7002. They are excluded from the Windows build though.

So I think this can be closed?

**Comment by MSP-Greg** [comment]
Ok.  Bundler is a default gem in Ruby Core, but the files are not synced often.

As I stated, Ruby Core tests itself with the bundler specs with MacOS.  This is done in an Azure Pipeline build, tested on Ubuntu & MacOS (not sure about versions).

There is no testing here on MacOS.  When I moved the current Bundler files into Core and tested them in my fork, something was amiss with this file, as there were additional failures.

So, whenever the next 'bundler sync' happens, the test results from the MacOS should compared before and after, and whatever the cause, fixed.

When bundler runs in Core as it currently is, there are no failures in this file.  When I ran it with the current bundler master, the following errors occurred on MacOS:

```
rspec ./spec/bundler/bundler/source_spec.rb:62 # Bundler::Source#version_message when there are locked gems that contain the relevant gem spec with a different version with color should return a string with the spec name and version and locked spec version
rspec ./spec/bundler/bundler/source_spec.rb:83 # Bundler::Source#version_message when there are locked gems that contain the relevant gem spec with a more recent version with color should return a string with the locked spec version in yellow
rspec ./spec/bundler/bundler/source_spec.rb:104 # Bundler::Source#version_message when there are locked gems that contain the relevant gem spec with an older version with color should return a string with the locked spec version in green
```

Ok to close, but I thought a 'marker' about this might be helpful.

**Comment by deivid-rodriguez** [comment]
Can you show the actual errors? Maybe those tests are actually failing on MacOS, since I don't use MacOS nor Travis, so maybe I introduced this issue unintentionally.

**Comment by MSP-Greg** [comment]
> Maybe those tests are actually failing on MacOS

I certainly make my share of mistakes, but in this instance...

There's a few reasons I prefer Appveyor over Pipelines.  One is that linking to a specific place cannot always be done in Pipelines.

Anyway, here's my test with updated bundler:
https://dev.azure.com/MSP-Greg/ruby-core/_build/results?buildId=308

Here's a test without the update:
https://dev.azure.com/MSP-Greg/ruby-core/_build/results?buildId=309

On both pages, you have to click 'macOS bundler' to get to the correct job, then click where it says 'test one error' to open the log.

**Comment by deivid-rodriguez** [comment]
> There's a few reasons I prefer Appveyor over Pipelines. One is that linking to a specific place cannot always be done in Pipelines.

Yes, you can :) https://dev.azure.com/MSP-Greg/ruby-core/_build/results?buildId=308&view=logs&jobId=66a08ec6-e709-53e0-033b-61f532a2f672&taskId=d0922d77-2365-53f7-a78c-24885f7003fb&lineStart=82&lineEnd=116&colStart=1&colEnd=1

> Anyway, here's my test with updated bundler:
https://dev.azure.com/MSP-Greg/ruby-core/_build/results?buildId=308

It sounds like I broke this in #7002 indeed. The Azure environment doesn't seem to support ANSI escape sequences, no matter whether it's using Windows or MacOS. So we should change the `:non_windows` filter to be `:non_azure` (maybe check if [`TF_BUILD` is set](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#system-variables)?).

**Comment by MSP-Greg** [comment]
> Yes, you can

Thanks, right click in the window...

> ANSI escape sequences

I forgot that the Ubuntu build is indeterminate (because it's output is failing, but that may be due to ANSI escape sequences), so it may have the same failures as macOS...

**Comment by deivid-rodriguez** [comment]
We've had a pretty stable build recently, and ruby-core issues are usually addressed very quickly by core developers, so I'll close this.

If you're still getting this issue, let me know and we can reopen.
