### ISSUE TITLE
windows CI - appveyor build results

### ISSUE THREAD

**Issue by MSP-Greg** [bundler/bundler#7254]
Ran a build on appveyor using ruby-head, with jobs done by spec folder.  It may make it easier to see patterns in the failures/errors, etc.  I increased the failure limit from 25 to 100 and man pages were generated.

I believe the two worst folders were 'commands' at 97 and 'install' at 100.  Most were much lower.

See:

https://ci.appveyor.com/project/MSP-Greg/bundler/builds/26169083

I'm not really familiar with the specs, so I won't be able to delve into it for a while.  Thought I'd post an issue in case some of those that are familiar with the specs might have a look...

**Comment by deivid-rodriguez** [comment]
Hi @MSP-Greg.

We already have [a Windows build](https://dev.azure.com/bundler/bundler/_build?definitionId=1) and we are aware of the failures. We just need to work on them.

So I'm going to close this issue if that's ok with you.

Thanks for trying this though!

**Comment by MSP-Greg** [comment]
Good day David (prefer David or Deivid?)

I'm aware of the Pipelines build here.  I wasn't sure how the man pages affected things, and they're easy to generate on Appveyor.  Grouping by spec folder also may make the results easier to inspect.

> We just need to work on them re that goal.

Just thought this might be helpful.  Ok to close.

**Comment by deivid-rodriguez** [comment]
> Good day David (prefer David or Deivid?)

Both are good :)

Thanks @MSP-Greg!
