### ISSUE TITLE
update's lock file order should same with install

### ISSUE THREAD

**Issue by SolaWing** [bundler/bundler#7262]
after bundle update, though the dependency not change, the path order is change. this make me have to run install to ensure the order consistency and avoid unneccesary commit
![图片](https://user-images.githubusercontent.com/3897953/61778856-22fb4080-ae32-11e9-8e9e-f0c8c56a5e87.png)

**Comment by deivid-rodriguez** [comment]
This is unexpected, can you show the result of `bundle env`, and ideally a way to reproduce this?

**Comment by SolaWing** [comment]
## Environment

```
Bundler       2.0.2
  Platforms   ruby, x86_64-darwin-18
Ruby          2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]
  Full Path   /Users/wang/.rbenv/versions/2.6.3/bin/ruby
  Config Dir  /Users/wang/.rbenv/versions/2.6.3/etc
RubyGems      3.0.3
  Gem Home    /Users/wang/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0
  Gem Path    /Users/wang/.gem/ruby/2.6.0:/Users/wang/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0
  User Path   /Users/wang/.gem/ruby/2.6.0
  Bin Dir     /Users/wang/.rbenv/versions/2.6.3/bin
Tools
  Git         2.20.1 (Apple Git-117)
  RVM         not installed
  rbenv       rbenv 1.1.2
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2019-06-13
Git SHA           496bca538
Released Version  true
```


I will try to reproduce it in a demo project

**Comment by SolaWing** [comment]
Reproduce Steps:
bundle gem demo
cd demo
bundle gem aaa
bundle gem subgem
# in demo's Gemfile, specify
```
gem 'subgem', path: './subgem'
gem 'aaa', path: './aaa'
```
# modify gemspec to make bundle update happy.
bundle update
# commit lock file
bundle install
# bundle update and install have different order

here is the result files
[demo.zip](https://github.com/bundler/bundler/files/3426137/demo.zip)

**Comment by deivid-rodriguez** [comment]
Reproduced, thanks! I'm going to have a look :+1:.

**Comment by deivid-rodriguez** [comment]
The problem is due to using relative paths starting with `./`. I'm working on a fix now, but you can workaround the problem by using `aaa` and `subgem`, instead of `./aaa` and `./subgem`.

**Comment by deivid-rodriguez** [comment]
#7264 should fix this!
