### ISSUE TITLE
newgem_spec.rb was broken with Ruby 2.7

### ISSUE THREAD

**Issue by hsbt** [bundler/bundler#7271]
I merged e1c518363641208429f397170354054b3d28effd into ruby/ruby at https://github.com/ruby/ruby/commit/0bd1cd677f769ac6128989bf1d021753698fdaac.

But newgem_spec.rb was broken with Ruby 2.7 same as https://travis-ci.org/rubygems/rubygems/jobs/567144945#L512

It's maybe caused `eval` with `path.expand_path.to_s` arg on https://github.com/bundler/bundler/blob/master/lib/bundler.rb#L575. But I didn't find the root cause yet.

I and @mame are investigating this issue.

**Comment by mame** [comment]
I could repo without bundler, so bundler is innocent :+1:  I'll file a ticket into ruby-core bug tracker.

**Comment by deivid-rodriguez** [comment]
I'm happy to have a look too. I'll start by trying to reproduce it, thanks for reporting this!

**Comment by hsbt** [comment]
We addressed this https://bugs.ruby-lang.org/issues/16041

**Comment by hsbt** [comment]
Fixed at https://github.com/ruby/ruby/commit/5931857281ce45c1c277aa86d1588119ab00a955

Thanks @nobu

**Comment by deivid-rodriguez** [comment]
Nice, thanks everyone!
