### ISSUE TITLE
[feature-request] add minitest-spec test option for gem command

### ISSUE THREAD

**Issue by jethrodaniel** [bundler/bundler#7292]
I often use minitest spec with new gems, and find myself manually converting the `--test=minitest` setup from `bundle gem` into a spec format.

It'd be nice if we could use `bundle gem --test=minitest-spec` to do this automatically.

PR: https://github.com/bundler/bundler/pull/7291

**Comment by jethrodaniel** [comment]
Added `[feature-request]` to the title because Github won't let me add the label.

**Comment by deivid-rodriguez** [comment]
I'm good with adding this feature, personally.

**Comment by deivid-rodriguez** [comment]
As per the related PR, this feature request was rejected some I'm closing this. I'm sorry :(
