### ISSUE TITLE
Bundler could not find compatible versions for gem "railties"

### ISSUE THREAD

**Issue by MarcSteven** [bundler/bundler#7316]
I update the rails6.0 and then it always showed this error:

**Comment by deivid-rodriguez** [comment]
You forget to paste the error.

Also, please include steps to reproduce the issue you're having.

Thanks!

**Comment by MarcSteven** [comment]
I update bundle and then all is okay, thank for your reply @deivid-rodriguez

**Comment by deivid-rodriguez** [comment]
Yeah, I'm sorry I got to this so late.Thanks for your feedback @MarcSteven!
