### ISSUE TITLE
Cannot resolve dependencies of rails and sass-rails

### ISSUE THREAD

**Issue by rulingcom-debug** [bundler/bundler#7326]
Yesterday, when I tried to execute bundle install to re-install my site,
a serious  error occurred. The bundler cannot resolve the dependencies of rails and sass-rails.

```
Bundler could not find compatible versions for gem "rack":
In Gemfile:
rails (~> 4.1.0) ruby depends on
  railties (= 4.1.0) ruby depends on
    actionpack (= 4.1.0) ruby depends on
      rack (~> 1.5.2) ruby

sass-rails (~> 4.0.2) ruby depends on
  sprockets (<= 2.11.0, ~> 2.8) ruby depends on
    rack (1.0.0)
```

Bundler version 1.7.2
Ruby ruby 2.1.2p95

Can any one  give me some suggestions? Thank you very much,

**Comment by rulingcom-debug** [comment]
The Gemfile:

source 'https://rubygems.org'

#social gems
gem "omniauth-google-oauth2"

#rails gem
gem 'rails', '~> 4.1.0'
gem 'sanitize'

#assets and templates
gem 'sass-rails', '~> 4.0.2'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'jquery-ui-rails', "5.0.0"
gem 'turbolinks'
gem 'normalize-rails', '~> 3.0.1'

#password
gem 'bcrypt-ruby', '~> 3.1.5'

#json
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0',          group: :doc
gem 'spring', '~> 1.7.2',       group: :development
gem 'active_model_serializers'

#parser
gem 'nokogiri', '~> 1.7.0.1'

#store api
gem 'httparty'

#database
# gem 'mongoid', github: "mongoid/mongoid"
gem 'mongoid', '~> 4.0.2'

#ntnu sso
gem 'mechanize', '~> 2.7'

# sockets
# gem "websocket-rails"

#file uploading and carrierwave
gem "mini_magick", "3.5.0"
gem 'carrierwave'
gem 'carrierwave-mongoid','~> 0.10.0', :require => 'carrierwave/mongoid'
gem 'zip-zip'
gem 'kaminari', '~> 1.0.1'
gem 'kaminari-mongoid', '~> 0.1.0'
gem 'impressionist', '~> 1.5.2'
gem 'chartkick', '~> 2.3.5'
gem 'usagewatch_ext'
gem 'ckeditor', '~> 4.2.4'
gem 'unicorn', '~> 5.4.0'
gem 'zhconv'
gem 'time_difference'
gem 'execjs'
gem 'therubyracer'

#excel
gem 'axlsx_rails'
gem 'spreadsheet'
gem 'rubyXL'

#form helpers
gem 'dynamic_form'

#built in modules
eval(File.read(File.dirname(__FILE__) + '/built_in_extensions.rb'))
#modules installed from the store
eval(File.read(File.dirname(__FILE__) + '/downloaded_extensions.rb'))
if File.exists?(File.dirname(__FILE__) + '/extra_gems.rb')
  eval(File.read(File.dirname(__FILE__) + '/extra_gems.rb'))
end

#development related gems
group :development do
  gem 'better_errors'
  # gem 'guard-bundler'
  # gem 'guard-rails'
  gem 'rails_layout'
  gem 'rb-fchange', :require=>false
  gem 'rb-fsevent', :require=>false
  gem 'rb-inotify', '~> 0.9.10', :require=>false
  gem 'byebug', '~> 9.0.6'
  gem "binding_of_caller"
end

#testing gems
group :test do
  gem "minitest"
  gem 'minitest-spec-rails'
end

#ask
gem 'gotcha'

**Comment by rulingcom-debug** [comment]
It seems that sprockets ruby depends upon rake just 1.0.0. Is it possible to resolve this issue? Thank you very much.

**Comment by deivid-rodriguez** [comment]
Hi!

You're using a very very old version of bundler. Can you upgrade to the latest version and try again? Note that you will also have to upgrade your ruby version to at least 2.4.

**Comment by deivid-rodriguez** [comment]
Closing due to lack of feedback.
