### ISSUE TITLE
Update Gem Task Release to handle multi-factor authentication

### ISSUE THREAD

**Issue by kaikuchn** [bundler/bundler#7335]
Hi,

I just activated multi-factor authentication on rubygems recently. When using gem commands to push I now need to either pass an OTP via flag or reply to the challenge. [See their guides](https://guides.rubygems.org/using-mfa-in-command-line/).

It'd be awesome if the `release` task would ask me to provide the OTP if rubygems requires it.

Best regards,
Kai

**Comment by deivid-rodriguez** [comment]
Which bundler version are you using? I think this should be properly working in both 2.0.2 and 2.1.0.pre.1.

**Comment by andrewhavens** [comment]
I'm also running into this issue. I try using the rake task and it hangs, but it never prompts me to enter my OTP, but if I use `gem push` then it works. `gem -v` shows 3.0.6

**Comment by deivid-rodriguez** [comment]
Which `bundler` version (`bundle -v`)? This should be fixed in both 2.0.2 and 2.1.0.pre.2.

**Comment by andrewhavens** [comment]
As for me, in this project it looks like 1.17.3

**Comment by deivid-rodriguez** [comment]
Closing since it should be fixed in the latest bundler.

**Comment by kaikuchn** [comment]
Sorry for my unresponsiveness. I somehow missed this conversation entirely...

I can confirm that this works with Bundler 2.0.2. Thanks :)
