### ISSUE TITLE
Specifying bundler version with underscores but still getting latest installed version

### ISSUE THREAD

**Issue by eebbesen** [bundler/bundler#7345]
Per https://stackoverflow.com/questions/56880223/using-multiple-bundler-versions, https://github.com/rbenv/rbenv/issues/235, et. al. using underscores around the version number should allow me to use different bundler versions on my machine. However, this is not working for me.

When I specify a bundler version that I _don't_ have installed bundler correctly complains though, so it seems to be version checking at least.
```bash
$ gem list bundler

*** LOCAL GEMS ***

bundler (2.0.2, 1.17.3, 1.17.0)

$ bundle _1.17.3_ -v
Bundler version 2.0.2

$ bundle _1.17.2_ -v
/Users/user/.rbenv/versions/2.3.6/lib/ruby/2.3.0/rubygems.rb:241:in `bin_path': can't find gem bundler (= 1.17.2) (Gem::GemNotFoundException)
  from /Users/user/.rbenv/versions/2.3.6/bin/bundle:22:in `<main>'
```
I'm on OS X Mojave 10.14.6. This persists even after `gem uninstall` and reinstall of bundler 2.0.2.

I'm looking for suggestions on debugging this. `--verbose` isn't helping: 
```bash
$ bundle _1.17.3_ install --verbose
Running `bundle install --verbose` with bundler 2.0.2
Found no changes, using resolution from the lockfile
Using concurrent-ruby 1.0.5
```

(repost of https://stackoverflow.com/questions/57794149/cannot-specify-bundler-version-when-multiple-are-installed)

**Comment by eebbesen** [comment]
Cheers @deivid-rodriguez!

**Comment by deivid-rodriguez** [comment]
No problem!
