### ISSUE TITLE
Use single-quoted strings when 'bundle add gem'

### ISSUE THREAD

**Issue by npupko** [bundler/bundler#7347]
I think it's nice to use single-quoted strings when we don't need string interpolation or special symbols.
I.e. now it works like:
```
bundle add rspec'
```
And the result will be  

`Gemfile`:
```ruby
gem "rspec", "~> 3.8.0"
```

It's better to:

`Gemfile`:
```ruby
gem 'rspec', '~> 3.8.0'
```

I can do it if you will found it useful.

**Comment by hsbt** [comment]
It's the standard style of bundler 

https://github.com/bundler/bundler/blob/master/.rubocop.yml#L752

And single quotation is not affected with performance improvement.  

https://www.viget.com/articles/just-use-double-quoted-ruby-strings/
