### ISSUE TITLE
Bundler on JRuby refuses to use java version of jaro_winkler

### ISSUE THREAD

**Issue by mvz** [bundler/bundler#7369]
I'm at a loss here. I'm trying to run bundler for [reek](https://github.com/troessner/reek) on JRuby 9.2.6.0 and 9.2.8.0, and it tries to install `jaro_winkler`:

```
Fetching jaro_winkler 1.5.3
Installing jaro_winkler 1.5.3 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
```

However installing `jaro_winkler` directly works, and it installed the java version:

```
$ gem install jaro_winkler
Successfully installed jaro_winkler-1.5.3-java
1 gem installed
```

After installing the java version like that, bundler still tries to install the non-java version when I run bundle install.

**Comment by deivid-rodriguez** [comment]
Thanks for reporting, that's weird. I'll have a look at soon as possible.

**Comment by mvz** [comment]
D'oh!

```bash
$ bundle config
[...]
force_ruby_platform
Set for the current user (/home/matijs/.bundle/config): true
```

No idea why I set it to true, but removing this setting fixed the problem.

**Comment by deivid-rodriguez** [comment]
You probably got bit by the sticky options behavior of bundler 1 and 2, where options are silently remembered when you use them once. We will change this in bundler 3.
