### ISSUE TITLE
Installing redmine gem

### ISSUE THREAD

**Issue by JagannathRajalbandi** [bundler/bundler#7380]
Hi there,

I tried to install the redmine gem to my app(which was already existed but commented).

On bundle install got the following issues.(FYI refer screenshot)

There are some errors that occurred to me. I think issues are related to dependency.

And also if possible can you provide references to downgrade versions(if upgrade solves current issue)

<img width="552" alt="Screenshot 2019-10-16 at 5 08 40 PM" src="https://user-images.githubusercontent.com/36688225/66915846-9e3a5000-f037-11e9-8ed1-4c42a9a8ca38.png">

**Comment by JagannathRajalbandi** [comment]
@André Arko Can anyone help me with this issue.

Thanks in Advance.

**Comment by deivid-rodriguez** [comment]
The error message is telling you that your `activeresource` requirement (`~> 4.1.0`) is incompatible with the `redmine` dependency on (`activeresource ~> 4.0.0`).

Dowgrading your `activeresource` requirement to `~> 4.0.0` in your `Gemfile` should fix the issue.

**Comment by colby-swandale** [comment]
ping @JagannathRajalbandi

**Comment by deivid-rodriguez** [comment]
Closing due to lack of feedback.
