### ISSUE TITLE
Show a human readable error if gem < 3.x is installed

### ISSUE THREAD

**Issue by albertvaka** [bundler/bundler#7382]
The internet is full of people lost [1] [2] because the error you get after installing bundler 2.0 on a system with gem 2.x is this nonsense:
```
'find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundle (Gem::GemNotFoundException)
```

Would be nice to detect this (very common) case and print something like `Bundler 2.x requires gem 3.x, please upgrade gem (or downgrade bundler)` and make the world a nicer place.

[1] https://stackoverflow.com/questions/54042692/rbenv-find-spec-for-exe-cant-find-gem-bundler-0-a-with-executable-bun
[2] https://github.com/rbenv/rbenv/issues/1138#issuecomment-452113825

**Comment by deivid-rodriguez** [comment]
Turns out this is a bug in rubygems, not in bundler. Upgrading your rubygems version (or your ruby to a version with a more recent rubygems) should fix this.

See https://bundler.io/blog/2019/05/14/solutions-for-cant-find-gem-bundler-with-executable-bundle.html.

**Comment by albertvaka** [comment]
:+1:
