### ISSUE TITLE
Could add the ruby version for `bundle config path`?

### ISSUE THREAD

**Issue by Whirlwind** [bundler/bundler#7383]
```
$ bundle config path /Users/whirlwind/.bundle/vendor

$ rvm use 2.5.0  # ruby 2.5
$ bundle install
Installing psych 2.2.2 with native extensions
Bundled gems are installed into `/Users/whirlwind/.bundle/vendor`

$ rvm use system # ruby 2.6
$ bundle install
Ignoring psych-2.2.2 because its extensions are not built. Try: gem pristine psych --version 2.2.2
Installing psych 2.2.2 with native extensions
Bundled gems are installed into `/Users/whirlwind/.bundle/vendor`

$ rvm use 2.5.0  # ruby 2.5
$ bundle install
Using psych 2.2.2    <- Will not reinstall psych!!!!!!!
Bundled gems are installed into `/Users/whirlwind/.bundle/vendor`

$ pod --help
/Users/whirlwind/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/yaml.rb:5: warning: It seems your ruby installation is missing psych (for YAML output).
To eliminate this warning, please install libyaml and reinstall your ruby.

```

I want to use `bundle config path` to custom a path to install all gems. But they will be installed in a path without any ruby version information.

If I use the `$GEM_HOME` or `$GEM_PATHS`, the rubygem will append the `ruby/2.5.0` to the path.

I think the gems should be installed at `/Users/whirlwind/.bundle/vendor/ruby/VERSION`. Right?

**Comment by Whirlwind** [comment]
I found that:

 If I use the `bundle config path --global`, I get the ~/.bundle/config:
```
---
BUNDLE_PATH: "/Users/whirlwind/.bundle/vendor"
```
The gems will be installed into `/Users/whirlwind/.bundle/vendor/gems/".

If I use the `bundle install --path=.bundle/vendor`, I get the `.bundle/config`:
```
---
BUNDLE_PATH: ".bundle/vendor"
```
The gems will be installed into `.bundle/vendor/ruby/2.6.0/gems`. It has the ruby version !!

It is different between the global and local configuration.

**Comment by deivid-rodriguez** [comment]
This should be fixed in bundler 2.1.0.pre.2, I think. Can you try with that version?

**Comment by Whirlwind** [comment]
It works for bundler 2.1.0.pre.2 !

**Comment by deivid-rodriguez** [comment]
Thanks for confirming. Closing as fixed by https://github.com/bundler/bundler/pull/7163.
