### ISSUE TITLE
Bundler issue

### ISSUE THREAD

**Issue by kundansingh27feb** [bundler/bundler#7397]
```
Errno::ENOTDIR: Not a directory @ rb_sysopen - /home/devtest/.bundle/config/bundler.lock
  /home/devtest/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/bundler/process_lock.rb:9:in `initialize'
  /home/devtest/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/bundler/process_lock.rb:9:in `open'
  /home/devtest/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/bundler/process_lock.rb:9:in `lock'
  /home/devtest/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/bundler/installer.rb:73:in `run'
  /home/devtest/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/bundler/installer.rb:25:in `install'
  /home/devtest/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/bundler/cli/install.rb:65:in `run'
  /home/devtest/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/bundler/cli.rb:235:in `block in install'
  /home/devtest/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/bundler/settings.rb:143:in `temporary'
  /home/devtest/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/bundler/cli.rb:234:in `install'
  /home/devtest/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /home/devtest/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
  /home/devtest/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
  /home/devtest/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/bundler/cli.rb:27:in `dispatch'
  /home/devtest/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
  /home/devtest/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/bundler/cli.rb:18:in `start'
  /home/devtest/.rvm/rubies/ruby-2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.17.3/exe/bundle:30:in `block in <top (required)>'
  /home/devtest/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/bundler/friendly_errors.rb:124:in `with_friendly_errors'
  /home/devtest/.rvm/rubies/ruby-2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.17.3/exe/bundle:22:in `<top (required)>'
  /home/devtest/.rvm/gems/ruby-2.3.3/bin/bundle:23:in `load'
  /home/devtest/.rvm/gems/ruby-2.3.3/bin/bundle:23:in `<main>'
  /usr/bin/ruby_executable_hooks:15:in `eval'
  /usr/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by deivid-rodriguez** [comment]
Can you run `gem uninstall rubygems-bundler` and try again?

**Comment by kundansingh27feb** [comment]
$ gem uninstall rubygems-bundler
ERROR:  While executing gem ... (Gem::InstallError)
    rubygems-bundler is not installed in GEM_HOME, try:
	gem uninstall -i /home/devtest/.rvm/rubies/ruby-2.3.3/lib/ruby/gems/2.3.0 rubygems-bundler

**Comment by kundansingh27feb** [comment]
Thanks it's got resolved but now getting the below issue:

Bundler will use `/tmp/bundler/home/unknown' as your home directory temporarily.

**Comment by deivid-rodriguez** [comment]
That's a warning I think, and should be preceded by another sentence with the reason for doing that?

**Comment by kundansingh27feb** [comment]
> That's a warning I think, and should be preceded by another sentence with the reason for doing that?

If this is a warning then why my project is not building? Here is the apache error log:

Could not find gem 'font-awesome-sass' in any of the gem sources listed in your Gemfile. (Bundler::GemNotFound)
        from /home/devtest/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/bundler/resolver.rb:255:in `each'
        from /home/devtest/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/bundler/resolver.rb:255:in `verify_gemfile_dependencies_are_found!'
        from /home/devtest/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/bundler/resolver.rb:49:in `start'
        from /home/devtest/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/bundler/resolver.rb:22:in `resolve'
        from /home/devtest/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/bundler/definition.rb:258:in `resolve'
        from /home/devtest/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/bundler/definition.rb:170:in `specs'
        from /home/devtest/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/bundler/definition.rb:237:in `specs_for'
        from /home/devtest/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/bundler/definition.rb:226:in `requested_specs'
        from /home/devtest/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/bundler/runtime.rb:108:in `block in definition_method'
        from /home/devtest/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/bundler/runtime.rb:20:in `setup'
        from /home/devtest/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/bundler.rb:107:in `setup'
        from /home/devtest/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/bundler/setup.rb:20:in `<top (required)>'
        from /home/devtest/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /home/devtest/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/home/devtest/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/bundler/resolver.rb:287:in `block in verify_gemfile_dependencies_are_found!': Could not find gem 'font-awesome-sass' in any of the gem sources listed in your Gemfile. (Bundler::GemNotFound)
        from /home/devtest/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/bundler/resolver.rb:255:in `each'
        from /home/devtest/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/bundler/resolver.rb:255:in `verify_gemfile_dependencies_are_found!'
        from /home/devtest/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/bundler/resolver.rb:49:in `start'
        from /home/devtest/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/bundler/resolver.rb:22:in `resolve'
        from /home/devtest/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/bundler/definition.rb:258:in `resolve'
        from /home/devtest/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/bundler/definition.rb:170:in `specs'
        from /home/devtest/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/bundler/definition.rb:237:in `specs_for'
        from /home/devtest/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/bundler/definition.rb:226:in `requested_specs'
        from /home/devtest/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/bundler/runtime.rb:108:in `block in definition_method'
        from /home/devtest/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/bundler/runtime.rb:20:in `setup'
        from /home/devtest/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/bundler.rb:107:in `setup'
        from /home/devtest/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/bundler/setup.rb:20:in `<top (required)>'
        from /home/devtest/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /home/devtest/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:54:in `require'

**Comment by deivid-rodriguez** [comment]
That's a hard error, but that's not the first _warning_ you mentioned.

In this case, you might've forgotten to run `bundle install` before booting your server?

Please, in the future, give me a hand and at least document the command you're trying to run, and properly format the backtraces. If you surround them with triple backquotes they become much easier to read!

Thanks!

**Comment by deivid-rodriguez** [comment]
Closing due to lack of feedback.
