### ISSUE TITLE
Inline Gemfile configuration? Like setting local gempath for project?

### ISSUE THREAD

**Issue by wade-welles** [bundler/bundler#7405]
I have read through the source code and the documentation and maybe I missed it but I was hoping someone could point out how to basically do `bundle --config path --local /path/to/new/gems/folder` but inline in a gemfile?

**Comment by deivid-rodriguez** [comment]
You mean like dropping the configuration inside the Gemfile itself? No, that's not currently, configuration lives at `.bundle/config`.

**Comment by deivid-rodriguez** [comment]
Closing due to lack of feedback, feel free to reply and reopen.
