### ISSUE TITLE
I have two sources on my gems, one is the local path I desire, the other is remote. Why is not not automatically downloading from the remote if the local is missing?

### ISSUE THREAD

**Issue by wade-welles** [bundler/bundler#7407]
How do I tell it to download from remote if local is missing, one would assume this would be the intuitive way to handle such a situation.

**Comment by deivid-rodriguez** [comment]
Can you provide more information and reproduction steps to show the behavior you expect vs the behavior you are seeing? At the moment I don't understand this issue very well.

**Comment by deivid-rodriguez** [comment]
Closing due to lack of feedback, feel free to reply and reopen.
