### ISSUE TITLE
Always ouput `Resolving dependencies...` to user

### ISSUE THREAD

**Issue by Whirlwind** [bundler/bundler#7408]
```
$ bundle exec pod install --ansi --verbose
  [DEPRECATED] Your Gemfile contains multiple primary sources. Using `source` more than once without a block is a security risk, and may result in installing unexpected gems. To resolve this warning, use a block to indicate which gems should come from the secondary source. To upgrade this warning to an error, run `bundle config set disable_multisource true`.
  Resolving dependencies...
```

The `Resolving dependencies...` is output by bundler, Is it a bug?

The bundler is 2.1.0.pre.2.

**Comment by deivid-rodriguez** [comment]
If you have a `Gemfile.lock` file, it shouldn't print that because it doesn't need to resolve dependencies. Can you rerun with the `--verbose` flag to see _why_ it's re-resolving?

**Comment by deivid-rodriguez** [comment]
I guess you found out about the culprit here? Could you give me, and anybody reading this with the same problem, a bit more info about the resolution? Thank you!
