### ISSUE TITLE
Bundle viz deprecation

### ISSUE THREAD

**Issue by fatkodima** [bundler/bundler#7414]
```
$ bundle viz
[DEPRECATED] The `viz` command has been moved to the `bundle-viz` gem, see https://github.com/bundler/bundler-viz
Resolving dependencies...
...
```

`https://github.com/bundler/bundler-viz` - returns 404.

So, was this already extracted or is there work in progress or is there a need for someone to do this?

**Comment by deivid-rodriguez** [comment]
Closing as a duplicate of https://github.com/bundler/bundler/issues/7041. You can find the information in there.
