### ISSUE TITLE
Add "--test=test-unit" option for gem command

### ISSUE THREAD

**Issue by mame** [bundler/bundler#7421]
I'd like to use "test-unit" for my gem, but `bundle gem` does not support it currently.

It is cumbersome to setup "test-unit" manually.  It would be great if we could use `bundle gem --test=test-unit`

PR: #7420

**Comment by mame** [comment]
Please add "feature-request" label to this issue.  I seem to have no permission.

**Comment by mame** [comment]
@kou,  who is the current maintiner of test-unit, told me that the same request (#5255) was rejected once.  Sorry, I couldn't find the request.

However, I still want you to support test-unit.  It is the most "standard" test framework.  I know that the de facto standard is rspec, but I believe that test-unit is still one of the most famous test frameworks for Ruby.
In addition, test-unit is bundled with the Ruby distribution.  Nowadays, bundler is bundled with ruby too.  I was really surprised that bundler ignores a bundled test framework but supports non-bundled ones.  If too many option really matters, you can drop other choices :innocent:  (That is a joke, but I think it is more reasonable than the current situation.)

I'd like to hear your opinions.

**Comment by hsbt** [comment]
I agree with to add `test-unit` option. Because ruby-core did ship `minitest` and `test-unit`. So they are always bundled all of ruby users different from `rspec`.

And I use `test-unit` instead of `minitest` recently. I can maintain this feature.

**Comment by amatsuda** [comment]
Huge :+1: for this. test-unit is my default choice, and it's indeed used in almost all gems that I authored, e.g.
https://github.com/kaminari/kaminari/blob/ff5c842/kaminari.gemspec#L26
https://github.com/amatsuda/active_decorator/blob/f5997ff/active_decorator.gemspec#L23

I'm really hoping to see a better future that I don't have to spend a commit for manually converting the generated minitest setup to test-unit that I actually use.

**Comment by deivid-rodriguez** [comment]
I also agree with adding this feature, and also commit to maintain it.

**Comment by mame** [comment]
Okay, I believe that the feature has been accepted.  Great, thank you!

Rather than merging this #7420, https://github.com/bundler/bundler/pull/5521 should be updated and merged.  So I'm closing my PR.
