### ISSUE TITLE
bundle exec gem --version outputs nothing

### ISSUE THREAD

**Issue by hanachin** [bundler/bundler#7441]
```
% bundler -v
Bundler version 2.1.0.pre.3
% gem -v
3.1.0.pre3
% cat Gemfile
% bundle exec gem --version
% bundle _2.1.0.pre.3_ exec gem --version
% bundle _2.0.2_ exec gem --version
3.1.0.pre3
```

:point_up: I hit this issue in the following rake task. 
https://github.com/rurema/doctree/blob/e91c072c86e68eda38caac53db1f2fb9c1eeaa6d/Rakefile#L27

This script use `bundle exec gem which bitclust` output. It works with bundler 2.0.2, but I got error with bundler 2.1.0.pre.3. Because `bundle exec gem` does not print command output to the STDOUT.

In 2.0.2, `ui` object in the rubygems is `Gem::ConsoleUI`.

```
% bundle _2.0.2_ exec gem --version

From: /home/sei/.rbenv/versions/master/lib/ruby/2.7.0/rubygems/user_interaction.rb @ line 153 :

    148:
    149:   ##
    150:   # Displays the given +statement+ on the standard output (or equivalent).
    151:
    152:   def say(statement = '')
 => 153:     binding.irb
    154:     ui.say statement
    155:   end
    156:
    157:   ##
    158:   # Terminates the RubyGems process with the given +exit_code+

irb(#<Gem::CommandManager:0x0000562dee0fbcf8>):001:0> ui
=> #<Gem::ConsoleUI:0x0000562dee6378e8 @ins=#<IO:<STDIN>>, @outs=#<IO:<STDOUT>>, @errs=#<IO:<STDERR>>, @usetty=true>
```

In 2.1.0.pre.3, the `ui` is `Bundler::UI::RGProxy`

```
% bundle _2.1.0.pre.3_ exec gem --version

From: /home/sei/.rbenv/versions/master/lib/ruby/2.7.0/rubygems/user_interaction.rb @ line 153 :

    148:
    149:   ##
    150:   # Displays the given +statement+ on the standard output (or equivalent).
    151:
    152:   def say(statement = '')
 => 153:     binding.irb
    154:     ui.say statement
    155:   end
    156:
    157:   ##
    158:   # Terminates the RubyGems process with the given +exit_code+

irb(#<Gem::CommandManager:0x0000560d2b568cc0>):001:0> ui
=> #<Bundler::UI::RGProxy:0x0000560d2a9f1bd0 @ui=#<Bundler::UI::Shell:0x0000560d2a9f1cc0 @shell=#<Bundler::Thor::Shell::Color:0x0000560d2a9f1c20 @base=nil, @mute=false, @padding=0, @always_force=false>, @level="info", @warning_history=[]>, @ins=#<File:/dev/null>, @outs=#<File:/dev/null>, @errs=#<File:/dev/null>, @usetty=false>
```

`Gem::ConsoleUI#say` print the statement to the STDOUT.
But `Bundler::UI::RGProxy#say` does not output the statement for `bundle exec` without `-V` / `--verbose` option.
Because `Bundler::UI::RGProxy#say` uses `@ui.debug`, the `@ui` is `Bundler::UI::Shell`, `Bundler::UI::Shell#debug` output nothing for `--no-verbose` .
https://github.com/bundler/bundler/blob/f6045fcf93cd3076cdd3d5e15622927c87df2db5/lib/bundler/ui/rg_proxy.rb#L14-L16
https://github.com/bundler/bundler/blob/f6045fcf93cd3076cdd3d5e15622927c87df2db5/lib/bundler/ui/shell.rb#L44-L46

**Comment by deivid-rodriguez** [comment]
Thanks for you helpful report, it should by fixed now in master, and released soon.

**Comment by hanachin** [comment]
Thank you so much for the quick fix 👍
