### ISSUE TITLE
keep platform warning out of `bundle show`?

### ISSUE THREAD

**Issue by jrochkind** [bundler/bundler#7448]
`bundle show --paths` is a very useful command for outputting paths of all dependencies, to use as arguments for other commands. 

For instance, I make a `gemgrep` command that will grep through ALL dependency sources, with a bash function like this:

    gemgrep () { grep "$@" -r . $(bundle show --paths); }

This used to work fine. But currently in some projects, executing `bundle show --paths` _first_ prints out this line:

    The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.

Perhaps I should fix that. But it ought not to ruin my use of `bundle show --paths` as an arg if I don't. But it does, since it includes that line, of course grep complains that the args aren't what expects, in particular it sees `-add-platform` and tries to use it as an arg for grep, and complains `grep: unrecognized option `--add-platform'`. 

Is there any way to get a `bundle show --paths` that _won't_ output warnings like this too, it will only output the actual output?  (Or if you sent warnings to stderr and actual output to stdout, I could at least pipe the warnings to /dev/null -- but nope, both are to stdout). 

If not, should there be?

**Comment by deivid-rodriguez** [comment]
We send warnings to stderr since bundler 2. Which `bundler` version are you using?

**Comment by jrochkind** [comment]
Aha, I am still on bundler 1.17.3, time to upgrade, sorry, thanks!

**Comment by deivid-rodriguez** [comment]
No problem, thanks for the feedback!
