### ISSUE TITLE
using 2.1.0 breaks heroku build

### ISSUE THREAD

**Issue by dorian-marie-france** [bundler/bundler#7486]
here is the build warning first:

```
       Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
       Warning: the running version of Bundler (2.0.2) is older than the version that created the lockfile (2.1.0). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
```

and here is the build error:

```
-----> Detecting rake tasks
 !
 !     Could not detect rake tasks
 !     ensure you can run `$ bundle exec rake -P` against your app
 !     and using the production group of your Gemfile.
 !     Activating bundler (2.1.0) failed:
 !     Could not find 'bundler' (2.1.0) required by your /tmp/build_95e09b1ae0ae43256cfeb3babc3d0e18/Gemfile.lock.
 !     To update to the latest version installed on your system, run `bundle update --bundler`.
 !     To install the missing version, run `gem install bundler:2.1.0`
 !     Checked in 'GEM_PATH=vendor/bundle/ruby/2.5.0', execute `gem env` for more information
 !     
 !     To install the version of bundler this project requires, run `gem install bundler -v '2.1.0'`
 !
```

(solution for now is to stay on 2.0.2, e.g. `gem uninstall bundler` (then yes to the questions) and then `gem install bundler -v 2.0.2`.

thanks for making bundler

**Comment by hsbt** [comment]
It seems to heroku platform issue. /cc @schneems 

I think heroku needs to install the new version of Bundler.

**Comment by schneems** [comment]
> I think heroku needs to install the new version of Bundler.

We deployed a change yesterday which should have fixed/mitigated this. If you're still seeing problems today then please open a support ticket help.heroku.com and link back to this bundler issue. 

Here' is the changelog https://devcenter.heroku.com/changelog-items/1716

**Comment by colby-swandale** [comment]
Thanks @schneems! I will close this ticket and direct anyone running into this issue to the linked Heroku articles.

**Comment by schneems** [comment]
Tag me as well please. It _should_ work but I want to keep my eye on it in
case.

Did we ever get confirmation that this is no longer an issue on Heroku?
I’ve not seen a ticket come in.
-- 
Richard Schneeman
https://www.schneems.com
