### ISSUE TITLE
Bundler 2.1.0 "rake release" fails and silently exits if rubygems OTP is enabled

### ISSUE THREAD

**Issue by mattbrictson** [bundler/bundler#7499]
I have multi-factor authentication enabled for my rubygems.org account.

With Bundler 2.1.0, `rake release` fails to push to rubygems and doesn't show any `gem push` output whatsoever. Here is an example:

```
$ bundle exec rake release
tomo 0.14.1 built to pkg/tomo-0.14.1.gem.
Tag v0.14.1 has already been created.
$
```

However Bundler 2.0.2 works fine; it shows this output:

```
$ bundle exec rake release
tomo 0.14.1 built to pkg/tomo-0.14.1.gem.
Tag v0.14.1 has already been created.
Pushing gem to https://rubygems.org...
You have enabled multi-factor authentication. Please enter OTP code.
Code:   
```

If I edit the source code of Bundler 2.1.0 to replace `Kernel.system` with `Bundler.original_system`, this fixes the problem, but I don't know why:

```patch
diff --git lib/bundler/gem_helper.rb lib/bundler/gem_helper.rb
index 7d4e382be..1f316f097 100644
--- lib/bundler/gem_helper.rb
+++ lib/bundler/gem_helper.rb
@@ -179,7 +179,7 @@ module Bundler
     def sh_with_input(cmd)
       Bundler.ui.debug(cmd)
       SharedHelpers.chdir(base) do
-        abort unless Kernel.system(*cmd)
+        abort unless Bundler.original_system(*cmd)
       end
     end
```

Here is my environment:

```
$ gem -v
3.1.1
$ ruby -v
ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin19]
$ bundler -v
Bundler version 2.1.0
$ rbenv --version
rbenv 1.1.2
$ env | egrep 'RUBY|BUNDLE|GEM'
BUNDLER_EDITOR=subl
GEM_EDITOR=subl
```

**Comment by deivid-rodriguez** [comment]
Ugh, I created a bit of a mess trying to refactor the UI, sorry.

I think #7493 should fix things for you too? Can you try it? I will release that very shortly.

**Comment by deivid-rodriguez** [comment]
Essentially the explanation why `Bundler.original_system` is that it resets `RUBYOPT` to its previous value before shelling out, and that contains `-rbundler/setup` at that point, which is what was silencing rubygems UI. I tried a similar patch to yours to fix it but it broke other things, so I went with #7493 in the end.

**Comment by mattbrictson** [comment]
@deivid-rodriguez yes, I just verified that #7493 fixes this issue for me. Thanks!

**Comment by deivid-rodriguez** [comment]
Ok, thanks to you!

Since this is now fixed in master I'll close this. I'll release 2.1.1 with the fix in the next day or two. Sorry about the issue.
